### ISSUE TITLE
An article in draft state, shows up in search

### ISSUE THREAD

**Issue by bashynx** [chatwoot/chatwoot#10026]
### Describe the bug

An article in draft state, does not show in article list but shows up in search

### To Reproduce

1. Have a draft article
2. Check your Helpdesk from private browser
3. Search for keyword contained in the article
4. See you can find the article

### Expected behavior

The draft articles shouldn't be easy to find by a random user.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Firefox 129.0, replicated on Brave 1.68.137

**Comment by pranavrajs** [comment]
@bashynx Thanks for reporting this. It is reproducible, will add a fix soon.
