### ISSUE TITLE
New Language Request for Crowdin: Azerbaijani

### ISSUE THREAD

**Issue by Grustamli** [chatwoot/chatwoot#10030]
### Is your feature or enhancement related to a problem? Please describe.

No

### Describe the solution you'd like

Please add a new language: Azerbaijani to Crowdin. It is missing.

**Comment by sojan-official** [comment]
Enabled this : 

https://translate.chatwoot.com/chatwoot-mobile-app/az
https://translate.chatwoot.com/chatwoot/az
