### ISSUE TITLE
Markdown conversion to whatsapp

### ISSUE THREAD

**Issue by LeonAlvarez** [chatwoot/chatwoot#10040]
### Describe the bug

Currently the text area under automation send message supports markdown but the meesage sent to whatsapp is not correctly converted, so there are difference between editor WYSIG and the message received.

For example  bold: `**` should be `*`in wahtsapp

WYSIG:
![image](https://github.com/user-attachments/assets/dfe1f82a-f3ea-49f8-8dc4-f1a3404b811c)
WHATAPP:
![image](https://github.com/user-attachments/assets/e267c9de-ccb9-4e28-a169-5595acaa93e0)

Note: I tested on selfhosted but guess it's same across all instances.

### To Reproduce

1) Create automation
2) Add a message with markdown
3) Trigger the automation
4) Compare WYSIG with actual message received

### Expected behavior

Markdown should be converted to whatsapp format

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Docker (if applicable)

latest docker

**Comment by pranavrajs** [comment]
@LeonAlvarez We do not support Markdown on the editor used in WhatsApp channel. If you are using an API channel, please process the response before sending it to WhatsApp.
