### ISSUE TITLE
{"error":"undefined method `reject' for nil"}

### ISSUE THREAD

**Issue by PyramidPavilion** [chatwoot/chatwoot#10056]
### Describe the bug

I'm trying to create interactive messages through chatwoot API using Python.
I followed this guide https://www.chatwoot.com/hc/user-guide/articles/1677689344-how-to-use-interactive-messages, but all the payload samples give me an error
{"error":"undefined method 'reject' for nil"}

### To Reproduce

`import requests

url = f"{base_url}/api/v1/accounts/{account_id}/conversations/{conv_id}/messages"
headers = {
        "api-access-token": "TOKEN HERE"
    }
    data = {
        "content": "Select one of the items below",
        "content_type": "input_select",
        "content_attributes": {
            "items": [
                {"title": "Option1", "value": "Option 1"},
                {"title": "Option2", "value": "Option 2"}
            ]
        }
    }

resp = requests.post(url, headers=headers, data=data)
print(resp.text)`

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@PyramidPavilion Please use content type as application/json.
