### ISSUE TITLE
Python error when try to upgrade chatwoot on Linux VM

### ISSUE THREAD

**Issue by idealprint** [chatwoot/chatwoot#10075]
### Describe the bug

Error whe upgrade chatwoot installation using cwctl -upgrade

$ sudo cwctl --upgrade -d
[sudo] password for usuario:
Checking for cwctl updates...
Installing packaging library...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

### To Reproduce

chatwoot manual linux VM installation 
Linux Ubuntu 24.04 on WSL2
Chatwoot version 3.11.0
run  cwctl -upgrade command

### Expected behavior

upgrade chatwoot to latest version

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 24.04

### Additional context

I had install chatwoot following the instructions here: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

**Comment by darker0n** [comment]
Confirming. The same problem

**Comment by vishnu-narayanan** [comment]
@idealprint We don't recommend doing a production install on WSL2. `cwctl` is tested and maintained for Ubuntu Linux 24.04/22.04/20.04. Could you try out the docker-based deployment on WSL2?

**Comment by darker0n** [comment]
@idealprint Try to upgrade manually using [this](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#upgrading-to-a-newer-version-of-chatwoot) tutorial.
It helped me.

**Comment by sojan-official** [comment]
Closing since we don't intend to support WSL at this point

**Comment by darker0n** [comment]
@sojan-official I have this problem on Debian 12

**Comment by hugorn** [comment]
Same problem now. VM with Ubuntu 24.04.1

**Comment by vishnu-narayanan** [comment]
@hugorn This is fixed in the latest cwctl version. Could you try using the latest cwctl(3.0.0) again?

**Comment by hugorn** [comment]
> @hugorn This is fixed in the latest cwctl version. Could you try using the latest cwctl(3.0.0) again?

It worked correctly using the cwctl(3.0.0) version, thank you very much for your help.
