### ISSUE TITLE
Cannot set user via SDK

### ISSUE THREAD

**Issue by pablofsc** [chatwoot/chatwoot#10071]
### Describe the bug

I cannot set the user reliably via the SDK. Calling `window.$chatwoot.setUser` usually does nothing and I cannot pinpoint exactly what causes it to work in the situations it does. I've found that, sometimes, calling `window.$chatwoot.reset` or refreshing the page will force the user's information to be displayed on the other side. 

I tested 3.7 and 3.12 and had the same issue in both. The two versions were tested in a simple html/js page and in an Ionic application, with the same results for both.

### To Reproduce

```javascript
(function (d, t) {
	var BASE_URL = "<my_base_url>";
	var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
	g.src = BASE_URL + "/packs/js/sdk.js";
	g.defer = true;
	g.async = true;
	s.parentNode.insertBefore(g, s);
	g.onload = function () {
		window.chatwootSDK.run({
			websiteToken: '<my_token>',
			baseUrl: BASE_URL
		});

		const user = {
			name: 'test name',
			email: 'testmail@test.com',
			company_name: 'test company',
			phone_number: '+155555555'
		};

		window.$chatwoot.setUser(user.email, user);
	};
})(document, "script");
```

Open the page and start a conversation.

### Expected behavior

The newly created conversation that appears in the inbox should have the contact information filled accordingly, but an anonymous conversation is created instead.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Chrome 128.0.6613.113 x64

### Docker (if applicable)

Docker is at 25.0.4.
Docker-compose is not used.

**Comment by pablofsc** [comment]
Also: I did try to call `setUser` at other moments, such as by waiting for `chatwoot:ready`, setting up timers or even calling the function manually via the console, but to no avail.

**Comment by sojan-official** [comment]
Tracking this over: https://github.com/chatwoot/chatwoot/issues/7065#issuecomment-2329645186
