### ISSUE TITLE
Impossible to create a message with attachment and external_created_at field.

### ISSUE THREAD

**Issue by dukhaSlayer** [chatwoot/chatwoot#10070]
### Describe the bug

While doing post to `{accountId}/conversations/{conversationId}/messages` with mutlipart form data all fields are treated as strings. If external_created_at field is present is is written to database to `message.content_attributes` in form: 
```
"{\"external_created_at\":\"1720041811\"}"
```

After this while rendering the message, on UI I'm getting an error:
```
[Vue warn]: Invalid prop: type check failed for prop "createdAt". Expected Number with value 1720041811, got String with value "1720041811".
```

Suggested fix:
In mesasge_builder.rb:
```
  def external_created_at
    @params[:external_created_at].present? ? { external_created_at: Integer(@params[:external_created_at]) } : {}
  end
```

### To Reproduce

Make a file upload query with the Postman and add integer field `external_created_at`. 

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@dukhaSlayer external_created_at fields is reserved for internal use case, should not be modified.
