### ISSUE TITLE
Favicon badge won't change when notification comes

### ISSUE THREAD

**Issue by softshape** [chatwoot/chatwoot#10088]
### Describe the bug

The Chatwoot favicon is supposed to change (with red dot) when a new support message arrives, but it never happens. Should this feature be enabled somewhere in the settings?

### To Reproduce

A self-hosted installation.

### Environment

Other [please specify in the description]

### Cloud Provider

None

### Platform

Browser

**Comment by laianeramos** [comment]
did you upload favicons with names like `favicon-badge-16x16.png` with the red dot?

**Comment by softshape** [comment]
No, I have a clean install of the Chatwoot

**Comment by laianeramos** [comment]
@softshape i see now. Maybe your notifications are not enabled

**Comment by pranavrajs** [comment]
@softshape The red dot is shown based on the notifications you subscribed and it seems to be working as expected. Please share the exact reproduction steps if you still have the issue and re-open the issue.

**Comment by softshape** [comment]
Notifications are enabled in my profile - 'Alert events for conversations:' is set to 'all'. Meanwhile favicon remains the same and I miss new dialogs.
