### ISSUE TITLE
Outbound Emails - Customise Sender and Content

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1008]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently CW sends emails based on a hard-set from address of the install as well as a hard-set name in a template. When using multiple inboxes, or even accounts, this causes confusion as to who the mail is from.

In reality, the From: name should be able to be set against the Inbox, as well as the From: address. 

The subject of the message as well as the message template including URL and domain should be easily customisable again on a per inbox basis so the content is exactly matching the site the person has visited. 

For now, we're going to have to turn off the emails because it seems to follow the one-hard set template/from data for all and in the world where people are extra vigilant about emails purporting to be from a specific sender, this would be a red flag for some.

**Comment by pranavrajs** [comment]
> Currently CW sends emails based on a hard-set from address of the install as well as a hard-set name in a template. When using multiple inboxes, or even accounts, this causes confusion as to who the mail is from.
In reality, the From: name should be able to be set against the Inbox, as well as the From: address.

@iammattmartin I think this would be fixed when you start using conversation continuity option.

> The subject of the message as well as the message template including URL and domain should be easily customisable again on a per inbox basis so the content is exactly matching the site the person has visited. For now, we're going to have to turn off the emails because it seems to follow the one-hard set template/from data for all and in the world where people are extra vigilant about emails purporting to be from a specific sender, this would be a red flag for some.

Customisations on email templates are planned based on account. Our idea to group everything under one business in an account. If you have a different business, creating a new account would be the right approach. We will add branding customisation at the account, not at the inbox level.

**Comment by iammattmartin** [comment]
Noted. The only constraint there is when you're managing lots of brands, you'd have to keep switching between accounts. Could get quite cumbersome. 

Likewise (related to the live view discussed in email), this would render such functionally a bit unworkable.

I am aware that some businesses have one main company but several brands which would mean all inboxes on the same account as logically correct but then they cannot customise the outbound emails based on that - they'd also need to split accounts which would be undesirable.

Giving the admin the ability to set template based on account OR the inbox would be a better experience overall but that said, if account views can be merged (i.e if you have access to two accounts, you can see data for both in one panel instead of having to constantly switch.... This then removes the need for customisations per Inbox and for live view as discussed).

**Comment by WevrLabs** [comment]
Maybe also formatting email messages by adding a little more clarity by enhancing the looks for the agent and client messages, like this example here:

<img width="754" alt="Screen Shot 2020-07-18 at 10 00 16 AM" src="https://user-images.githubusercontent.com/66124192/87848171-dc71e200-c8dd-11ea-9299-c097d5ae9898.png">

**Comment by iammattmartin** [comment]
If the template is customisable, you could easily do that yourself.

The issue with software generally is forcing you to do something in a set way. For example, we'd not be keen on that kind of lay out whereas others may be.

Giving control over the template and maybe some logic such as defining {if}'s to allow code to be defined on if the visitor or staff and so on.

**Comment by WevrLabs** [comment]
Can we weigh in here as well, @sojan-official ?
The observed behavior is that if the agent is the last one to send a message or a reply, the outbound email notification is triggered, even though the user may have read the message in the chatbox already, which I believe there's no need to still send out a notification in this case.

**Comment by iammattmartin** [comment]
This would be an entirely different issue and not related to customising that message.

If that happens, would recommend you open a new issue.

**Comment by WevrLabs** [comment]
Noted. I'll move it to a separate issue.
