### ISSUE TITLE
 .

### ISSUE THREAD

**Issue by megalhoes** [chatwoot/chatwoot#10096]
<p><a href="https://linear.app/chatwoot/issue/PR-838/option-to-disable-the-visibility-of-agents-from-the-all-tab">PR-838 Option to disable the visibility of agents from the All tab</a></p>

_Originally posted by @linear[bot] in https://github.com/chatwoot/chatwoot/issues/8662#issuecomment-1881072375_

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/4216
