### ISSUE TITLE
WhatsApp Improvements due to timeout (templates?)

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1009]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
WhatApp (via Twilio) has a limit on that you can only send another outbound message if the last inbound message was within 24 hours. It would be helpful to have a timer or CW simply not allowing another message which you can't tell the user didn't get.

Adding support to send a template from a drop down where it could initiate a simple message like: "We want to give you an update, please reply so we can do so" etc.

Then the conversation can continue.

Additionally, adding "Status Callback URL" support would actually help see if messages have been read/delivered etc from such data provided by Twilio (https://www.twilio.com/docs/whatsapp/api#monitor-the-status-of-your-whatsapp-outbound-message). Currently there is no way to tell this at all.

**Comment by pranavrajs** [comment]
> WhatApp (via Twilio) has a limit on that you can only send another outbound message if the last inbound message was within 24 hours. It would be helpful to have a timer or CW simply not allowing another message which you can't tell the user didn't get.

This is a general rule for both Whatsapp and Facebook integrations, you cannot send a message after 24 hours past last inbound messages. 

For Whatsapp, you can send template messages approved by the Whatsapp team after this time period. For now we are not supporting template message, but I think it would be good to block the normal messages if the time period is exceeded. For delivery status, we are not doing that now. This would be taken as a seperate issue and it needs to be implemented across the channels.

**Comment by pranavrajs** [comment]
> Adding support to send a template from a drop down where it could initiate a simple message like: "We want to give you an update, please reply so we can do so" etc.

On second thought, the template messages will be easier to implement when combined with canned message UX. @sojan-official / @nithindavid Any thoughts on this?

**Comment by pranavrajs** [comment]
@iammattmartin Splitting this to 3 different tickets

1 - Building the UX to prevent messages after 24-hour time window 
2 - Whatsapp template messages #1020 
3 - Read/delivered/undelivered status on messages #1021
