### ISSUE TITLE
Internal Server Error - Create Inbox

### ISSUE THREAD

**Issue by LeonelTasso** [chatwoot/chatwoot#10105]
### Describe the bug

Calling the API: `{{baseUrl}}api/v1/accounts/2/inboxes/` getting -  500 Internal server error

Curl: 

```
curl --location '{{baseUrl}}api/v1/accounts/2/inboxes/' \
--header 'Content-Type: application/json; charset=utf-8' \
--header 'Accept: application/json; charset=utf-8' \
--header 'api_access_token: xxxxxxxxxxxxx' \
--data '{
  "name": "Instancia 1",
  "avatar": "string",
  "channel": {
    "type": "web_widget",
    "website_url": "string",
    "welcome_title": "string",
    "welcome_tagline": "string",
    "agent_away_message": "string",
    "widget_color": "string"
  }
}'

```
Response: 
`{
    "status": 500,
    "error": "Internal Server Error"
}`

LOG from the server:

```
rails_1     | I, [2024-09-12T20:30:09.204302 #1]  INFO -- : source=rack-timeout id=eb854d9b-651a-473b-bc49-372be391bba1 timeout=15000ms state=ready
rails_1     | I, [2024-09-12T20:30:09.204950 #1]  INFO -- : [eb854d9b-651a-473b-bc49-372be391bba1] Started POST "/api/v1/accounts/2/inboxes/" for 189.34.118.139 at 2024-09-12 20:30:09 +0000
rails_1     | I, [2024-09-12T20:30:09.209681 #1]  INFO -- : [eb854d9b-651a-473b-bc49-372be391bba1] Processing by Api::V1::Accounts::InboxesController#create as JSON
rails_1     | I, [2024-09-12T20:30:09.209832 #1]  INFO -- : [eb854d9b-651a-473b-bc49-372be391bba1]   Parameters: {"name"=>"Instancia 1", "avatar"=>"string", "channel"=>{"type"=>"web_widget", "website_url"=>"string", "welcome_title"=>"string", "welcome_tagline"=>"string", "agent_away_message"=>"string", "widget_color"=>"string"}, "account_id"=>"2", "inbox"=>{"name"=>"Instancia 1"}}
rails_1     | I, [2024-09-12T20:30:09.248789 #1]  INFO -- : [eb854d9b-651a-473b-bc49-372be391bba1] Completed 500 Internal Server Error in 38ms (ActiveRecord: 7.1ms | Allocations: 6510)
rails_1     | F, [2024-09-12T20:30:09.250109 #1] FATAL -- : [eb854d9b-651a-473b-bc49-372be391bba1]   
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1]   
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/api/v1/accounts/inboxes_controller.rb:32:in `block in create'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/api/v1/accounts/inboxes_controller.rb:30:in `create'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/concerns/switch_locale.rb:17:in `switch_locale_using_account_locale'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/concerns/switch_locale.rb:39:in `set_locale'
rails_1     | [eb854d9b-651a-473b-bc49-372be391bba1] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'
rails_1     | I, [2024-09-12T20:30:09.250800 #1]  INFO -- : source=rack-timeout id=eb854d9b-651a-473b-bc49-372be391bba1 timeout=15000ms service=46ms state=completed
```

### To Reproduce

Call  api/v1/accounts/2/inboxes/

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Docker (if applicable)

version: '3'

services:
  base: &base
    image: chatwoot/chatwoot:latest
    env_file: .env ## Change this file for customized env variables
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    depends_on:
      - postgres
      - redis
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_production2
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=leonel

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - /data/redis:/data
    ports:
      - '127.0.0.1:6379:6379'

**Comment by guimaurer** [comment]
the same problem here

**Comment by pranavrajs** [comment]
@LeonelTasso You configuration seems to be missing the SECRET_KEY_BASE variable. Please read this guide and set the variable. https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#rails-production-variables

**Comment by LeonelTasso** [comment]
@pranavrajs  Thanks for your answer.

I configured the SECRET_KEY_BASE and the RAILS_ENV, but i still getting internal server error:


`
RAILS_ENV=production
SECRET_KEY_BASE=mBC6rSHjwriWsDpWpohRj90KMyrCxtqtm9zyY9IOBneMaywGQs1k9oB9LnJye9N
`

should i execute any command? or generate another user to create inbox?
