### ISSUE TITLE
I cannot see the "Insert article" button

### ISSUE THREAD

**Issue by afanjul** [chatwoot/chatwoot#10107]
### Describe the bug

After create a help portal, and associate it with an inbox, I'm still cannot see the "Insert Article" button in the chat view. 

### To Reproduce

I did the following steps:
#### 1 Create a help portal with some articles

![image](https://github.com/user-attachments/assets/26a48614-c118-48be-a81c-9d059726bda2)

#### 2 Associate the help portal to that inbox

![image](https://github.com/user-attachments/assets/b7054fda-bf28-4e00-ac8c-511566372499)

#### 3 Create a new conversation

![image](https://github.com/user-attachments/assets/d0974d1f-e159-4d0e-92d4-7df181967b76)

The button is missing...

### Expected behavior

The "Insert Article" button should appear

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Macos Sonora

### Browser and version

Chrome 128

### Docker (if applicable)

Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 8
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.13.19-6-pve
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.812GiB
 Name: chatwood
 ID: 91df6023-7355-4f18-a74b-a50c864301a5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

### Additional context

The button is not "hidden", because in the dev console doesn't appear. I also restarted the docker

**Comment by pranavrajs** [comment]
@afanjul The feature under a feature flag since it was under testing. I've removed it now. You can enable this in the super admin console for now.
