### ISSUE TITLE
Missing Arabic Translations

### ISSUE THREAD

**Issue by marwenayari** [chatwoot/chatwoot#10115]
### Describe the bug

Missing arabic translations especially in features descriptions

<img width="829" alt="image" src="https://github.com/user-attachments/assets/f18d49ce-21d5-47a0-9744-9a9f96d401c1">
<img width="802" alt="image" src="https://github.com/user-attachments/assets/189072ca-6de1-4737-b432-351482228fba">
<img width="809" alt="image" src="https://github.com/user-attachments/assets/d792c896-eca1-4c83-a373-fd544f02e13e">

### To Reproduce

- Use Arabic as language
- As agent, go to settings and switch between features (Or in url put `/app/accounts/1/settings/agents/list`)

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by marwenayari** [comment]
I'd like to work on this one, as a native arabic speaker and as we are using chatwoot on my company and arabic is the main language.

**Comment by pranavrajs** [comment]
@marwenayari Thanks for reporting this. The translations are managed at https://translate.chatwoot.com/chatwoot/ar. Since these texts are the recent introductions, you would see the translated strings from the next update.
