### ISSUE TITLE
cannot install community edition on ubuntu 20.04

### ISSUE THREAD

**Issue by injaan** [chatwoot/chatwoot#10117]
### Describe the bug

I have freshly installed ubuntu 20.04
and chatwoot installation script giving following error at installation stage 6
![Screenshot 2024-09-16 at 18 37 30](https://github.com/user-attachments/assets/667a701f-a76c-4277-9fa1-735a14fcf5e8)
and log file said
![Screenshot 2024-09-16 at 18 38 23](https://github.com/user-attachments/assets/caf1d044-19ec-4e3c-8eb0-c05c0f4c2223)

### To Reproduce

1. prepare freshly installed ubuntu 20.04
2. follow chatwoot self-hosted deployment guide https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

ubuntu 20.04

**Comment by injaan** [comment]
I started again with another new installation of ubuntu 20.04 and run install script. this time error log says

![Screenshot 2024-09-16 at 22 15 31](https://github.com/user-attachments/assets/f63753e1-1a36-4629-a292-2714547f0003)

**Comment by tecnomaster** [comment]
@injaan I had exactly the same issue and analyzing the install script process log file, discovered that in Ubunto 20.04 mkdir command is not located where the installation script expects, so, the magical immediate solution is to execute:
`
ln -s /bin/mkdir /usr/bin/mkdir`

That´s it.

**Comment by injaan** [comment]
@tecnomaster thank you, but it doesn't work

**Comment by tecnomaster** [comment]
@injaan Fisrt, you need to see the log of the installation process, as recommended by the script itself. If you see there a lot of failures related to the mkdir command, which are just involved at the 6th step, what you should do is look where is the mkdir command in your system, using:

whereis mkdir

Once you get the current path of it, just create the symlink with:

ln -s /bin/mkdir /usr/bin/mkdi

Please note that the first path is where the current mkdir file is located.

Once done that, just execute again the installation script and should work, if not, rebuild your VM from zero and do the symlink before to run the installation script.

**Comment by tecnomaster** [comment]
This is what I have done so far, starting from ubuntu 18 and upgrading it to ubuntu 20:

sudo apt update && sudo apt upgrade
sudo reboot
sudo apt install update-manager-core
sudo do-release-upgrade
sudo reboot
lsb_release -a
uname -mrs

ln -s /bin/mkdir /usr/bin/mkdir

wget https://get.chatwoot.app/linux/install.sh
chmod +x install.sh
./install.sh --install

Then, say yes to create the ssl, indicate your domain or subdomian en the email for Let´s Encrypt, answer yes to everything, wait for the 9 steps, and it should be done!

**Comment by injaan** [comment]
@tecnomaster in my system mkdir already located in "/usr/bin/mkdir"
![Screenshot 2024-09-18 at 10 46 34](https://github.com/user-attachments/assets/b7d132c4-7e06-4ffa-af86-1810ef913cb5)
and I think installation error was not related to mkdir command. the error saying something ruby, gem related "path or file not found" thing

**Comment by injaan** [comment]
@tecnomaster I've found the cause of the problem, it was because of faulty virtual machine (x86/64 emulated virtual machine on Apple silicon mac using QEMU) installed new ubuntu on real x86/64 machine and it is working now

**Comment by injaan** [comment]
@tecnomaster I've found the cause of the problem, it was because of faulty virtual machine (x86/64 emulated virtual machine on Apple silicon mac using QEMU) installed new ubuntu on real x86/64 machine and it is working now
