### ISSUE TITLE
How to translate language strings

### ISSUE THREAD

**Issue by tecnomaster** [chatwoot/chatwoot#10122]
### Describe the bug

I have to adapt some Spanish language strings, so I went into this folder:

`/chatwoot/app/javascript/dashboard/i18n/locale/es/ `

Then I changed some spanish strings at some .json files, however, the website doesn´t shows the changes, even if I executed:

`sudo systemctl restart chatwoot.target`

Could somebody tell me what steps I need to follow to see the changes at the website??

Thanks in advance for your very appreciated support on this matter.

Dan

### To Reproduce

Using ChatWoot 3.12.0 with Ubuntu 20.04

Just go into:
`/chatwoot/app/javascript/dashboard/i18n/locale/es/ `

Change some strings at the .json files

Nothing changes at the website

### Expected behavior

Spanish strings updated

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Chrome

### Additional context

We use our own VPS

**Comment by pranavrajs** [comment]
@tecnomaster The files are bundled by the build system. Changing the source files doesn't automatically update the strings on the UI. 

If you would like to contribute to the translations, please see the guidelines [here](https://www.chatwoot.com/docs/contributing-guide/translation-guidelines). Otherwise, try RAILS_ENV=production rake assets:clean assets:clobber assets:precompile

 from the chatwoot folder.

**Comment by tecnomaster** [comment]
@pranavrajs Thanks a lot. It worked really good. 

Just for any other people who could not understand you command, this is the explanation of it:

The command does the following:
   - Sets the Rails environment to production
   - Cleans old compiled assets
   - Removes all compiled assets
   - Recompiles all the assets for the production environment
   
   Thanks again bro.

**Comment by laianeramos** [comment]
@tecnomaster can you explain to me how to clean and recompile? I never did anything like this before. I'll appreciate so much

**Comment by tecnomaster** [comment]
@laianeramos Just go into the chatwoot folder and execute the following command:

`RAILS_ENV=production rake assets:clean assets:clobber assets:precompile `

**Comment by laianeramos** [comment]
@tecnomaster thank you so much!

**Comment by elinardo10** [comment]
i have this problem, but using a docker instalation. how to do this? i try run this command in insid container, but without success. please anybody can helpe how change in ui some change in file vue. thanks
