### ISSUE TITLE
Whatsapp agent display name

### ISSUE THREAD

**Issue by heitormsb** [chatwoot/chatwoot#10139]
### Is your feature or enhancement related to a problem? Please describe.

I'm trying to know if is possible to disable the agent name on WhatsApp messages.
![Screenshot_20240920_121802_WhatsApp](https://github.com/user-attachments/assets/e8b4112d-c434-4250-94b9-0b0bc347a833)

### Describe the solution you'd like

I know this is recent implemented feature, but I want if has any disable button to not show agent names on messages

**Comment by sojan-official** [comment]
@heitormsb are you using official chatwoot image / channels ? we don't have this feature on official builds

**Comment by heitormsb** [comment]
Sorry, that's it. My bad
