### ISSUE TITLE
Kubernetes api invalid token create user

### ISSUE THREAD

**Issue by LeonelTasso** [chatwoot/chatwoot#10147]
### Describe the bug

After deploy with in my server with docker wich occourred fine.
I decided to move to Kubernates
But after i deploy, created the super admin in onboard screen, and the platformApp, i getting :

`{
    "error": "Invalid access_token"
}`

Curl:

`curl --location 'https://k8s.mysite.com.br/platform/api/v1/accounts' \
--header 'api_access_token: KCAQcT4UZ81FcDYx54dLieaU' \
--header 'Content-Type: application/json' \
--data '{
"name": "Empresa Joao"
}'`

any thought?

### To Reproduce

`
env:
  ACTIVE_STORAGE_SERVICE: local
  ANDROID_BUNDLE_ID: com.chatwoot.app
  ANDROID_SHA256_CERT_FINGERPRINT: "AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8"
  ASSET_CDN_HOST: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_REGION: ""
  AWS_SECRET_ACCESS_KEY: ""
  ENABLE_ACCOUNT_SIGNUP: false
  FB_APP_ID: ""
  FB_APP_SECRET: ""
  FB_VERIFY_TOKEN: ""
  FORCE_SSL: false
  FRONTEND_URL: "http://0.0.0.0:3000"
  INSTALLATION_ENV: helm
  IOS_APP_ID: 6C953F3RX2.com.chatwoot.app
  LOG_LEVEL: info
  LOG_SIZE: 500
  MAILER_INBOUND_EMAIL_DOMAIN: ""
  MAILER_SENDER_EMAIL: ""
  MAILGUN_INGRESS_SIGNING_KEY: ""
  MANDRILL_INGRESS_API_KEY: ""
  RAILS_ENV: production
  RAILS_INBOUND_EMAIL_PASSWORD: ""
  RAILS_INBOUND_EMAIL_SERVICE: ""
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  REDIS_SENTINEL_MASTER_NAME: ""
  REDIS_SENTINELS: ""
  REDIS_TLS: true
  S3_BUCKET_NAME: ""
  SECRET_KEY_BASE: rjVXK83l26gwKIDmSwZA49xxxxxR2aJ5KwK0iSBGdvCzWBButFL9BWzjwXVumB9d
  SENTRY_DSN: ""
  SLACK_CLIENT_ID: ""
  SLACK_CLIENT_SECRET: ""
  SMTP_ADDRESS: ""
  SMTP_AUTHENTICATION: plain
  SMTP_ENABLE_STARTTLS_AUTO: true
  SMTP_OPENSSL_VERIFY_MODE: none
  SMTP_PASSWORD: ""
  SMTP_PORT: 587
  SMTP_USERNAME: ""
  TWITTER_APP_ID: ""
  TWITTER_CONSUMER_KEY: ""
  TWITTER_CONSUMER_SECRET: ""
  TWITTER_ENVIRONMENT: ""
  USE_INBOX_AVATAR_FOR_BOT: true
`

POD LOGS:

`I, [2024-09-21T20:21:02.016501 #1]  INFO -- : source=rack-timeout id=4681eab911e8a8ca050803996c056f33 timeout=15000ms state=ready
I, [2024-09-21T20:21:02.017076 #1]  INFO -- : [4681eab911e8a8ca050803996c056f33] Started POST "/platform/api/v1/accounts" for 10.244.0.9 at 2024-09-21 20:21:02 +0000
I, [2024-09-21T20:21:02.039393 #1]  INFO -- : [4681eab911e8a8ca050803996c056f33] Processing by Platform::Api::V1::AccountsController#create as JSON
I, [2024-09-21T20:21:02.039558 #1]  INFO -- : [4681eab911e8a8ca050803996c056f33]   Parameters: {"name"=>"Empresa Joao", "account"=>{"name"=>"Empresa Joao"}}
I, [2024-09-21T20:21:02.040502 #1]  INFO -- : [4681eab911e8a8ca050803996c056f33] Filter chain halted as :set_platform_app rendered or redirected
I, [2024-09-21T20:21:02.040720 #1]  INFO -- : [4681eab911e8a8ca050803996c056f33] Completed 401 Unauthorized in 1ms (Views: 0.2ms | ActiveRecord: 0.0ms | Allocations: 173)
I, [2024-09-21T20:21:02.040979 #1]  INFO -- : source=rack-timeout id=4681eab911e8a8ca050803996c056f33 timeout=15000ms service=24ms state=completed`

### Expected behavior

Create the account

![Captura de Tela 2024-09-21 às 17 22 46](https://github.com/user-attachments/assets/c28f1ca8-2635-4652-9ce0-2a05884d7be9)
![Captura de Tela 2024-09-21 às 17 22 57](https://github.com/user-attachments/assets/c5e807d7-c5f9-4f5f-b879-cd0ebf7ae0a3)

### Environment

Kubernetes

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by LeonelTasso** [comment]
<img width="553" alt="Captura de Tela 2024-09-23 às 15 29 51" src="https://github.com/user-attachments/assets/c2afcd73-16a1-48a8-9aed-013a60c95615">
Any token in the DB does not work

**Comment by heitormsb** [comment]
@LeonelTasso Are you using nginx?

**Comment by LeonelTasso** [comment]
> @LeonelTasso Are you using nginx?

Yes

**Comment by heitormsb** [comment]
nginx not allow by default "_" on your header, and give error when use "api_access_token".
Edit on nginx configmap, **enable-underscores-in-headers** to true

**Comment by LeonelTasso** [comment]
> @LeonelTasso nginx not allow "_" by default on header, and give error when use "api_access_token". Edit on nginx configmap, **enable-underscores-in-headers** to true

Thats it, thanks man
