### ISSUE TITLE
Unattended tab shows resolved tickets

### ISSUE THREAD

**Issue by Apacalipto** [chatwoot/chatwoot#10159]
### Describe the bug

![image](https://github.com/user-attachments/assets/c899c520-7bc6-462c-9e99-9d3182168b56)

I tried to look in the help center but i got a 404 error if i click the unattended documentation.

### To Reproduce

When I click the unattended tab in Chatwoot i still see tickets under, mine, unassigned and all.

![image](https://github.com/user-attachments/assets/736d470a-64e4-481d-ae24-fd38d8a68357)

But all these tickets have been resolved. So why do they still show on the unattended tab? Because it's Spam we already attended to and just closed. 

### Environment

Heroku

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by Apacalipto** [comment]
Is this tickets still showing on the unattended tab expect behaviour from Chatwoot or not?

**Comment by sojan-official** [comment]
@Apacalipto  Currently , The unattended tab will show conversations where the last response is from a customer.

**Comment by pranavrajs** [comment]
Please check what is shown right next to the title. 

<img width="243" alt="Screenshot 2024-09-29 at 12 18 12 PM" src="https://github.com/user-attachments/assets/d87e5683-e8b4-47d4-b854-5cd0d27c607d">


If the tag says open and it shows the resolved conversation, this is a bug. 

<img width="261" alt="Screenshot 2024-09-29 at 12 18 20 PM" src="https://github.com/user-attachments/assets/58ce9f8a-d85f-45d3-9161-f3d8e826762b">

If the tags show `All`, then it should show the resolved conversation as well. The idea is that there should be a followup response to the customer when there is a message from the customer and it applies to the resolved conversations as well. 

You can change the filter using this dropdown to see the unattended open conversations.
<img width="393" alt="Screenshot 2024-09-29 at 12 20 06 PM" src="https://github.com/user-attachments/assets/e8e08f37-d6dc-4e55-8a2a-26f7aa8c2284">


I hope this helps. Closing this here for now. Please feel free to reopen this if it still an issue.
