### ISSUE TITLE
@chatwoot/chatwoot@3.13.0: The engine "node" is incompatible with this module. Expected version "20.x". Got "21.7.2"

### ISSUE THREAD

**Issue by Kemmotar2** [chatwoot/chatwoot#10154]
### Describe the bug

I'm trying to install de docker version on my server cause I have many other sites there and can't do a direct install modifying packages and modifying the template1 on postgres.

But this error is preventing the docker container for webpack to properly run and the app is giving me error 500.

### To Reproduce

The docker file I'm uising is the one form the repo (docker/dockerfiles/webpack.Dockerfile) with this info:

FROM chatwoot:development

RUN chmod +x docker/entrypoints/webpack.sh

EXPOSE 3035
CMD ["bin/webpack-dev-server"]

The command I used is:

docker composer up

and the error I got form docker compose logs webpack is:
docker compose logs webpack
yarn install v1.22.19
chatwoot-webpack-1  | (node:9) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
chatwoot-webpack-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
[1/5] Validating package.json...
error @chatwoot/chatwoot@3.13.0: The engine "node" is incompatible with this module. Expected version "20.x". Got "21.7.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

any help on this? or any other output I can provide?

Thanks :)

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Linux 22.04

### Docker (if applicable)

 docker version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 6
  Paused: 0
  Stopped: 5
 Images: 10
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-88-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: srv-staging
 ID: 5b77d5f6-e74c-4ddd-bc21-28a2d424808d
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

docker compose version
Docker Compose version v2.21.0

**Comment by pranavrajs** [comment]
@Kemmotar2 The one you are following is for development setup, and the one @vishnu-narayanan shared is for production. There might be something missing in your setup, which is not identifiable from the description here. I'm closing this here as this is no longer an issue.
