### ISSUE TITLE
Manual installation via install.sh on low memory VPS

### ISSUE THREAD

**Issue by unizhu** [chatwoot/chatwoot#10156]
### Describe the bug

My VPS only has 2GB memory so I encounter the webpack error:

```bash
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

### To Reproduce

1. run install.sh --install

### Expected behavior

Some walk arounds.. already try add 
```bash
--max-old-space-size=1900
```

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
Please add a swap space of 4GB+, the issue should be resolved.
