### ISSUE TITLE
won't send any email to outside

### ISSUE THREAD

**Issue by sirmosi** [chatwoot/chatwoot#10169]
### Describe the bug

setup chatwoot via docker compose according to the documentation but any type of email won't send outside

### To Reproduce

here is my enviroment variables

MAILER_SENDER_EMAIL=no-reply@tejaratnaseri.com
SMTP_DOMAIN=tejaratnaseri.com
SMTP_ADDRESS=mail.tejaratnaseri.com
SMTP_PORT=587
SMTP_USERNAME=no-reply@tejaratnaseri.com
SMTP_PASSWORD=
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_TLS=true
SMTP_SSL=true

## Get this Error
![Screenshot from 2024-09-26 10-18-58](https://github.com/user-attachments/assets/1cdbf66d-f181-463c-a362-a77cb9e71e83)

after a while i get this:
![Screenshot from 2024-09-26 10-05-02](https://github.com/user-attachments/assets/a88518eb-531c-40b7-8dac-0bc9eb797d03)

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

ubuntu 20

### Docker (if applicable)

docker version 27.3.1
docker compose version 2.29.7

**Comment by sojan-official** [comment]
please follow the instructions to debug smtp errors : https://www.chatwoot.com/docs/self-hosted/faq/#how-to-debug-smtp-email-errors-in-chatwoot
