### ISSUE TITLE
Custom Roles is using Canned Responses help url

### ISSUE THREAD

**Issue by swinner2** [chatwoot/chatwoot#10192]
### Describe the bug

https://github.com/chatwoot/chatwoot/blob/a0dddae28935c7f8f405e5672356bf4f639869bb/app/javascript/dashboard/routes/dashboard/settings/customRoles/Index.vue#L125C23-L125C39
Should be `custom_roles` instead of `canned_responses`

### To Reproduce

Navigate to Custom Roles. The help link is `https://chwt.app/hc/canned`

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
Thanks for reporting this, this is an unreleased feature. The link will be updated when the docs are ready. Closing this here for now.
