### ISSUE TITLE
Bug CSAT WhatsApp

### ISSUE THREAD

**Issue by arthurbarret0** [chatwoot/chatwoot#10191]
### Describe the bug

When you mark a conversation as “Resolved” in a WhatsApp channel, the CSAT is only sent when it is within the 24-hour window.

It would be important to make it possible to send even outside the 24-hour window.

### To Reproduce

1. Start a conversation using a WhatsApp channel
2. Wait to leave the 24-hour window
3. Mark conversation as “Resolved”

### Expected behavior

One way around this is to create a WhatsApp template that will be used to send the CSAT survey

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
The messages have a 24-hour window in WhatsApp. You have to use a WhatsApp template otherwise. Since CSAT is not a template which every customer has on their FB profile, we can't automatically send it.
