### ISSUE TITLE
Feature: Whatsapp template messages

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1020]
Add support to send a template from a drop-down where it could initiate a simple message like: "We want to give you an update, please reply so we can do so" etc.

--- 

This messages have to be approved by Whatsapp. Investigate if there is an API to bring in the approved template messages.

**Comment by aag1990** [comment]
I use this feature on other platforms to send tickets updates to clients. I hope to see this in Chatwoot soon!
A local list can be available for users to add the approved template messages. So we can copy and past the approved template message to Chatwoot!

**Comment by DefCon-007** [comment]
@pranavrajs Can something like [https://chat-api.com/en/?lang=EN](chat-api) which provides rest api using the whatsapp web be integrated to chatwoot too? With the end user taking the legal responsibility of its use?

**Comment by sojan-official** [comment]
> I use this feature on other platforms to send tickets updates to clients. I hope to see this in Chatwoot soon!
> A local list can be available for users to add the approved template messages. So users can copy and past the approved template message to Chatwoot!

At the moment you can define your template messages as canned responses in chatwoot and use them.

**Comment by sojan-official** [comment]
> @pranavrajs Can something like [https://chat-api.com/en/?lang=EN](chat-api) which provides rest api using the whatsapp web be integrated to chatwoot too? With the end-user taking the legal responsibility of its use?

You could use the API channel to connect the third-party REST APIs.

**Comment by thundersparkf** [comment]
@sojan-official so if a template is approved by WhatsApp separately, we can add it as a canned response to Chatwoot and I just have to use the Canned response and it'll work outside the 24 hour window to send messages on WhatsApp, sorry to repeat all of it, but just wanted clarify

**Comment by pranavrajs** [comment]
Closing this as the feature is complete.
