### ISSUE TITLE
Feature: Read/Delivered status for Facebook/Twitter/Whatsapp/SMS messages

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1021]
- Investigate the APIs needed to fetch the delivered status of a message in Facebook/Twitter/Whatsapp/Twilio

--- 

- Integrate read/delivered API/webhooks
- Provide an indication at the frontend to indicate that the message has been delivered.

**Comment by WevrLabs** [comment]
For Twilio, I guess it's easier to implement. We already have it in WHMCS implemented in a custom addon we use to send invoice reminders. All the messages sent by this addon are logged in database, and along with every message sent, a message SID is returned from Twilio API response, this SID is then stored in the database to the corresponding message.

Then we have a callback file that receives the responses from Twilio callbacks, these responses include the SID that was saved earlier, the code in the callback url will then inspect the database and fetch the corresponding message to that SID and stores the status from Twilio callback to that message entry.

**Comment by clairton** [comment]
Hello @sojan-official,  could I do this?

**Comment by sojan-official** [comment]
@clairton  Sure please go ahead.

**Comment by clairton** [comment]
Hello guys, this PR in fine?

**Comment by sojan-official** [comment]
@clairton  Could you create a pull request against chatwoot#develop using the appropriate branch where you have made the changes? 

You should be able to do it from here : 

https://github.com/chatwoot/chatwoot/compare/develop...clairton:chatwoot:b2.7.0

**Comment by clairton** [comment]
https://github.com/chatwoot/chatwoot/pull/5157

**Comment by clairton** [comment]
Open #6038 for proposal read event in whatsapp api

https://github.com/chatwoot/chatwoot/pull/5157#issuecomment-1329332045

**Comment by pranavrajs** [comment]
Closing via https://www.chatwoot.com/docs/product/channels/supported-features#outgoing-message-delivery-status
