### ISSUE TITLE
Self hosted installation reports incorrect plan and limits agents

### ISSUE THREAD

**Issue by EdenGottlieb** [chatwoot/chatwoot#10250]
### Describe the bug

We currently have a community edition self hosted version of chatwoot installed on our kubernetes cluster.
We reached 18 agents (total, in all accounts) and we are now unable to create new users).
Going into the settings page in the super admin console it says we are on the premium plan with 0 agents.
It also says we have reached the limit of 18 agents and that we need to upgrade.
clicking on manage takes us to a stripe page with our installation's info.

When we started debugging it said we were on the premium plan with 0 subscribers. I tried to move to the community edition plan and it said stripe encountered an error. So I pressed cancel plan and it put us back in the community edition plan.
However, after clicking refresh multiple times in the settings page of the super admin console it still shows that we are on the premium plan with 0 agents. We waited about 15 minutes and tried again, even restarted the entire installation, but it still says premium plan with 0 agents.

How do we fix this issue?

### To Reproduce

Run a self hosted instance of chatwoot (version 3.13.0). Click settings in the super admin console and check plan details

### Expected behavior

We should be able to move back to the community edition plan and add as many agents as we like

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

**Comment by pranavrajs** [comment]
Please reach out to us on live-chat with your installation identifier.  You can go to your SuperAdmin panel and start a chat from there or go to chatwoot.com and initiate a conversation.
