### ISSUE TITLE
New sdk.js breaks everything 

### ISSUE THREAD

**Issue by DareFail** [chatwoot/chatwoot#10252]
### Describe the bug

https://app.chatwoot.com/packs/js/sdk.js

Overwrites "$" which breaks the jquery and makes out website not even load 

Can I load the previous version somewhere 

### To Reproduce

Load 
https://app.chatwoot.com/packs/js/sdk.js

And rely on jquery

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@DareFail This has been already addressed in our updates. The main app won't crash in places where is jQuery or underscore js. 

If you still have issues, and if you are on Chatwoot Cloud, please reach out to us on the live-chat support inside the dashboard. This would help us identify the account and take action if any.

If you are on self-hosted installation, please use the 3.13.x version, the develop branch is marked as unstable, would stay that way for some time until the next major release.
