### ISSUE TITLE
Feature: Files storage

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1026]
Most of the time the customer support person has to share a PDF or doc file to provide more information to the user. Right now, the user has to upload the document every time from his computer. 

### Suggestion

Create a separate page for agents/administrator to upload documents used frequently. On the reply box, provide an option to select the file from the already uploaded list instead of asking them to upload every time.

**Comment by sojan-official** [comment]
# ideas

- [ ] Ability to add attachments to canned responses
- [ ] Ability to send attachment messages in automation - #3195

**Comment by pranavrajs** [comment]
Closing this due to the lack of interest. We can revisit this later if there is sufficient interest.
