### ISSUE TITLE
Agent Availiability not Working

### ISSUE THREAD

**Issue by vfasoulas** [chatwoot/chatwoot#1029]
**Describe the bug**
if I change availabilty in profile/settings nothing change

**To Reproduce**
1. Go to 'Profile Settings'
2. Click on Availability Combobox
3. Select Busy
4. Refresh Page
5. Nothing changes

**Comment by pranavrajs** [comment]
@vfasoulas You save the profile using 'Update Profile' button.

<img width="175" alt="Screenshot 2020-07-11 at 9 53 32 PM" src="https://user-images.githubusercontent.com/2246121/87228771-f7fe5980-c3c0-11ea-8fe9-7daf76b24e39.png">

I understand it's confusing, we will improve that UX in future releases.

**Comment by vfasoulas** [comment]
It is not working even then.
PS: I m using Greek  Language in My Profile Settigns

**Comment by pranavrajs** [comment]
@vfasoulas Then it might something else, we will check it out.

**Comment by pranavrajs** [comment]
@vfasoulas Can you please share a screencast of the behaviour? I did a quick round of testing and everything seems good.

**Comment by vfasoulas** [comment]
from log file

Started PUT "/api/v1/profile" for 127.0.0.1 at 2020-07-15 03:50:53 -0700
Processing by Api::V1::ProfilesController#update as JSON
  Parameters: {"profile"=>{"name"=>"Φασουλάς Βασίλης", "email"=>"
vfasoulas@hmu.gr", "availability"=>"στη γραμμή"}}
Can't verify CSRF token authenticity.
Completed 500 Internal Server Error in 25ms (ActiveRecord: 1.9ms |
Allocations: 1233)

ArgumentError ('στη γραμμή' is not a valid availability):

It's seems that there is confusion with translation of availability string
(online)

Στις Κυρ, 12 Ιουλ 2020 στις 5:16 μ.μ., ο/η Pranav Raj S <
notifications@github.com> έγραψε:

**Comment by pranavrajs** [comment]
@vfasoulas The keys were also translated, I've added those to keys to the translation ignore list. #1050 should fix the issue.
