### ISSUE TITLE
Add "Whatsap" inboxes via API

### ISSUE THREAD

**Issue by vaestvita** [chatwoot/chatwoot#10297]
### Is your feature or enhancement related to a problem? Please describe.

there is currently no method to add a new inbox like whatsapp via api

### Describe the solution you'd like

I need to add an API method to create a WhatsApp inbox entry

```[tasklist]
### Tasks
```

**Comment by sojan-official** [comment]
You can replicate the same api call which is made by the Chatwoot UI when you are creating a whatsapp inbox.   please look into the browser console and see the payload and prarams. 

https://www.chatwoot.com/developers/api/#tag/Inboxes/operation/inboxCreation
