### ISSUE TITLE
Forward e-mail is equal @false

### ISSUE THREAD

**Issue by felinto-dev** [chatwoot/chatwoot#10304]
### Describe the bug

When creating a new inbox, the forwarding email is invalid, with the address ending in "@false":
![image](https://github.com/user-attachments/assets/a24be8c2-c125-4d52-8cc5-0fcaff67ffb3)

This is a default installation using caprover.

### To Reproduce

Install chatwoot using caprover and in the "caprover-web" instance set the following variables:

```
FRONTEND_URL=
MAILER_INBOUND_EMAIL_DOMAIN=
```

### Expected behavior

The correct domain instead of @false

### Environment

Other [please specify in the description]

### Cloud Provider

None

### Platform

Browser

**Comment by sojan-official** [comment]
please set up the variables required for conversation continuity : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity/ 

also note that any inbox created before these environment variables were populated wouldn't have the domain updated, you will have to manually update the address from console or recreate the inbox.

**Comment by felinto-dev** [comment]
> please set up the variables required for conversation continuity : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity/
> 
> also note that any inbox created before these environment variables were populated wouldn't have the domain updated, you will have to manually update the address from console or recreate the inbox.

Caprover creates several applications. chatwoot-web and chatwoot-worker. Do you know where I should put the environment variables related to email? In chatwoot-web or chatwoot-worker?

**Comment by felinto-dev** [comment]
@sojan-official

**Comment by sojan-official** [comment]
@felinto-dev  all environment variables related to chtwoot should be available in both web and worker

**Comment by PAY-DAY** [comment]
Perfect
