### ISSUE TITLE
portals not loading after 3.14 upgrade

### ISSUE THREAD

**Issue by devsubngrill** [chatwoot/chatwoot#10309]
### Describe the bug

new version 3.14 not load the help center portal only show loading in the page never load the configuration , cookies clean , and problem continue server reboot and chatwoot reboot

That update deleted the help center from the application and everything was lost after the update to 3.14.

![2024-10-17-04-06-support subngrill com](https://github.com/user-attachments/assets/fa57d53b-1cb4-46b8-bfbe-34b044df3b04)

### To Reproduce

ready described above 

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by devsubngrill** [comment]
@vishnu-narayanan Hello attached here are all the logs , all working fine before the new version, but after the upgrade to 3.14, they are not working anymore 

I have been installing since version 3.8 and this is the first time it has happened.

I take this opportunity to ask how Captain is configured. Are you going to make a tutorial?

[support.subngrill.com-1729153769475.log](https://github.com/user-attachments/files/17408855/support.subngrill.com-1729153769475.log)
[support.subngrill.com-1729153764611.log](https://github.com/user-attachments/files/17408856/support.subngrill.com-1729153764611.log)
[support.subngrill.com-1729153757979.log](https://github.com/user-attachments/files/17408857/support.subngrill.com-1729153757979.log)
[support.subngrill.com-1729153747179.log](https://github.com/user-attachments/files/17408858/support.subngrill.com-1729153747179.log)

**Comment by devsubngrill** [comment]
> @devsubngrill which type of deployment are you using? 

Linux Ubuntu 24.04 noble

I checked everything on the server and everything is updated, everything was working perfectly, but in version 3.14 the help center stopped working

Everything works except the help center area

**Comment by vishnu-narayanan** [comment]
@devsubngrill could you share the output of the following? Also, can you try `cwctl --upgrade` again and share the logs?
```
cwctl --version
```

**Comment by vishnu-narayanan** [comment]
Please share a screenshot of your web browser console after you load help center page.

**Comment by devsubngrill** [comment]
Hello @vishnu-narayanan 

attachment here is the screenshot you requested to me yesterday please check

![Screenshot 2024-10-17 232627](https://github.com/user-attachments/assets/c790b979-b82e-4efe-877a-830cf49bfd9e)
![Screenshot 2024-10-17 232605](https://github.com/user-attachments/assets/8f745680-b6a7-4ab2-a175-62d34055cee5)
![2024-10-17-23-25-support subngrill com](https://github.com/user-attachments/assets/566fbad7-d443-48e0-abcf-9edf2cdb6221)

**Comment by pranavrajs** [comment]
@devsubngrill This is not related to the upgrade I believe. Can you please the server side logs as well when you navigate to the portals page?

**Comment by rgfpy** [comment]
here with the same problem

**Comment by devsubngrill** [comment]
There are other people with the same problem that I had, I think I discovered that when changing to Vue in Node for some reason not all the necessary gems are installed, and after completing the update the database is not migrated, it remains in pending status. This can be verified by entering the super admin area and looking for the instance status area.

Check before my coment other person with the same problem 

@pranavrajs @vishnu-narayanan

**Comment by jtayrone** [comment]
After updating, check if the migrate was complete! If not, perform the migrate and try to access the help center again.

Read here: https://www.chatwoot.com/docs/self-hosted/deployment/upgrade

**Comment by vishnu-narayanan** [comment]
We have a hotfix release `3.14.1` that should address these issues. Please upgrade and see if the issue goes away.

https://github.com/chatwoot/chatwoot/releases/tag/v3.14.1

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
