### ISSUE TITLE
ViteRuby::MissingExecutableError in Dashboard#index

### ISSUE THREAD

**Issue by ChetSocio** [chatwoot/chatwoot#10308]
### Describe the bug

Hello devs, I have tried to setup docker environment for development  using this [Docker Setup Guide](https://www.chatwoot.com/docs/contributing-guide/project-setup#docker-for-development). Once, done, upon hitting localhost:3000, I received  
`ViteRuby::MissingExecutableError in Dashboard#index `

`No such file or directory - pnpm`

Upon digging inside docker container, the container named `chatwoot-rails-1` has no npm, yarn, pnpm or any other external packages installed but `chatwoot-base-1` has it all. I wonder if this is expected.  

![image](https://github.com/user-attachments/assets/72de290f-bd70-4dd0-beb8-3cf9019736c8)

 

### To Reproduce

Follow [Official Docker installation](https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker)
Go to 127.0.0.1:3000

Note: no external steps were done while setting up docker. Docker was properly setup at the time of installation of chatwoot. I am using docker compose instead of docker-compose

### Expected behavior

Expected docker development environment to work fine without this error

### Environment

Docker

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

Chrome Version 130.0.6723.58 (Official Build) (64-bit)

### Docker (if applicable)

` $ docker version`
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`$ docker info`
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-1014-azure
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.61GiB
 Name: my-workspace
 ID: c58d55cf-571d-4c36-8ff9-bbd3ac4d4c22
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

`$ docker compose version`
Docker Compose version v2.29.7

### Additional context

When I ran : 
` $ docker logs chatwoot-webpack-1`

I got:
`docker/entrypoints/webpack.sh: line 7: yarn: not found`

A deeper dive into this container shows no signs of installing external packages like yarn or any other dependencies  required to run server.  

I am ready to provide further details in case of need by contributors.

**Comment by ChetSocio** [comment]
Confirmed , This issue is not duplicate of others and no similar previous issues were found that solve this problem in latest version.

**Comment by charmant** [comment]
I ran into the same problem. The issue seems to be related to the recent switch from yarn to pnpm, but the file webpack.sh (located at [docker/entrypoints/webpack.sh](https://github.com/CarsoOEMparts/chatwoot/blob/develop/docker/entrypoints/webpack.sh)) hasn’t been updated to reflect this change. This causes the Webpack service to fail to start.

I’ve tried to fix file like this:

```bash
#!/bin/sh
set -e

. /root/.shrc

rm -rf /app/tmp/pids/server.pid
rm -rf /app/tmp/cache/*

pnpm install --frozen-lockfile

echo "Waiting for pnpm and bundle integrity to match lockfiles...."
PNPM="pnpm list --json | grep -q 'Missing dependencies'"
BUNDLE="bundle check"

until $PNPM && $BUNDLE
do
  sleep 2;
done

echo "Ready to run webpack development server."

exec "$@"
```

But it doesn't work.

**Comment by vishnu-narayanan** [comment]
Please use the latest develop branch.
