### ISSUE TITLE
Latest versions of chatwoot (3.13.0 - 3.14.0) don't show onboarding page

### ISSUE THREAD

**Issue by azraelx23** [chatwoot/chatwoot#10319]
### Describe the bug

Installed chatwoot via coolify, immediately shown login page without any way to create an account

### To Reproduce

1. Install chatwoot via docker on coolify
2. Open chatwoot
3. Immediately shown login page instead of onboarding page

### Expected behavior

this page is shown https://<self hosted domain url>/installation/onboarding

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows

### Browser and version

Microsoft Edge

**Comment by azraelx23** [comment]
had to revert to v3.12.0 for the onboarding page to show and I was able to create super admin account

**Comment by vishnu-narayanan** [comment]
@azraelx23 I Just tried out Chatwoot `3.14` via docker. I got the onboarding page and was able to sign up. It must be something related to Coolify or your Redis instance. 

Could you try this out without Coolify?

**Comment by rgfpy** [comment]
Hello, i have the same updated from 3.13 ro 3.14 and not working more the front page and not show the login page
Installation is in VPS.

The error show in console JS is: Uncaught SyntaxError: Invalid or unexpected token (at dashboard-DFlvZe8j.js:6:13851) the line JS is: _=s(1.toString);r.exports=function(p){return"Symbol("+(p===void 0?"":p)+")

**Comment by rgfpy** [comment]
> had to revert to v3.12.0 for the onboarding page to show and I was able to create super admin account

how you revert to previous version?

**Comment by vishnu-narayanan** [comment]
We have a hotfix release `3.14.1` that should address these issues. Please upgrade and see if the issue goes away.

https://github.com/chatwoot/chatwoot/releases/tag/v3.14.1

**Comment by azraelx23** [comment]
Looks like it is fixed on 3.14.1 , thankss @vishnu-narayanan !
