### ISSUE TITLE
Modal in the context menu disappears unless hovered

### ISSUE THREAD

**Issue by s00d** [chatwoot/chatwoot#10320]
### Describe the bug

The modal in the context menu disappears when it is not being hovered over. The issue seems to be related to the modal component located [here](https://github.com/chatwoot/chatwoot/blob/dff57013c3fbc4c847b972accdd88dcf98d66906/app/javascript/dashboard/modules/conversations/components/MessageContextMenu.vue#L154), which is nested inside a `div` block with `invisible` and `group-hover:visible` classes [here](https://github.com/chatwoot/chatwoot/blob/dff57013c3fbc4c847b972accdd88dcf98d66906/app/javascript/dashboard/components/widgets/conversation/Message.vue#L573).

As a result, the modal becomes invisible when the user moves the cursor away from the context menu, making interaction with it difficult.

### To Reproduce

1. Open any chat in the application.
2. Right-click on a message and select the "Delete" option from the context menu.
3. Move your mouse away from the context menu, for example, towards the dev tools area.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

macos

### Browser and version

chrome 3.14.0

**Comment by vishnu-narayanan** [comment]
@s00d could you also share a screencast?

**Comment by s00d** [comment]
![2024-10-18 14 14 23](https://github.com/user-attachments/assets/00efcc0f-fa86-435e-b541-0cac1908253e)

**Comment by iamsivin** [comment]
@s00d This [PR](https://github.com/chatwoot/chatwoot/pull/10333#event-14779623408) will resolve the issue.
