### ISSUE TITLE
Error running container chatwoot-vite

### ISSUE THREAD

**Issue by KokeroO** [chatwoot/chatwoot#10337]
After the last commit of switching from webpack to vite in docker

Error running container:
```
 ✔ Container chatwoot-vite-1  Created                                                                                                          0.0s
Attaching to vite-1
vite-1  | docker/entrypoints/vite.sh: line 7: pnpm: not found
vite-1 exited with code 127
```

_Originally posted by @KokeroO in https://github.com/chatwoot/chatwoot/issues/10322#issuecomment-2429252765_

**Comment by vishnu-narayanan** [comment]
Fixed in https://github.com/chatwoot/chatwoot/pull/10344

**Comment by vishnu-narayanan** [comment]
Please try out the latest `develop`.
