### ISSUE TITLE
this.position is always 0 on dashboard apps, so having 2+ apps doesn't work

### ISSUE THREAD

**Issue by bfontaine** [chatwoot/chatwoot#10339]
### Describe the bug

When having two or more dashboard apps, the response to the event `chatwoot-dashboard-app:fetch-info` is always sent to the first dashboard, even when it’s requested from the other ones.

### To Reproduce

1. Save this as `debug.html`:

```html
<html lang="en">
<body>
<button onclick="window.parent.postMessage('chatwoot-dashboard-app:fetch-info', '*')">Send</button>

<script>
	const x = (Math.random() * 1000) | 0;
	console.log(x);

	window.addEventListener('message', function(event) {
		console.debug(x, 'Got message', event);

		const event_data = JSON.parse(event.data);
		console.log(x, 'Got event:', event_data);
	});
</script>
</body>
</html>
```
This generates a random number, then when you click on the "Send" button it sends `chatwoot-dashboard-app:fetch-info` to the parent and logs the response along the random number.

2. Serve it at some URL accessible by your Chatwoot instance (tested on 3.13.0-3.14.1). I used [backloop.dev](https://backloop.dev/) but that’s irrelevant to the issue
3. In Chatwoot, add the URL as a first dashboard app "Debug" as well as a second one "Debug 2"
4. Open any conversation, open the browser console, go on the "Debug" tab and click on the "Send" button
5. Go on the "Debug 2" tab and click on the "Send" button

### Expected behavior

When clicking on the button in the first dashboard, you should always see the same random ID; and when you switch to the second dashboard, you should always see the same random ID that’s **different** from the first one. This ID serves to highlight which dashboard receives the event.

Actual behavior: it’s always the first dashboard that receives the event.
![Screenshot from 2024-10-22 17-01-46](https://github.com/user-attachments/assets/7da68855-7935-476a-a93c-ab539b2f4f06)

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 24.04.1 LTS

### Browser and version

Google Chrome Version 130.0.6723.58 (Official Build) (64-bit)

### Additional context

In another setup (same version but different dashboards), I had a different bug but with the same origin: the code that emits a message in response to the event `chatwoot-dashboard-app:fetch-info` in `onIframeLoad` crashed because the ID it looked for didn’t exist in the DOM, because `this.position` was always `0`.

**Comment by pranavrajs** [comment]
@scmmishra Please take a look.

**Comment by scmmishra** [comment]
Hey @bfontaine I have a fix in the works (https://github.com/chatwoot/chatwoot/pull/10342) We'll get this merged and released soon

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/10342
