### ISSUE TITLE
3.14.0 CORS issues

### ISSUE THREAD

**Issue by mazenkhalil** [chatwoot/chatwoot#10335]
### Describe the bug

Upgrading to v3.14.0 causing CORS issues on production

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ...`

- Using AWS CDN (Setting ASSET_CDN_HOST variable) causing the platform not to load at all
- Not able to add inboxes (messenger, email, ...)
- Analytics and monitoring not working
- ...

### To Reproduce

NA

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

**Comment by scmmishra** [comment]
Hey @mazenkhalil can you share your Cloudfront config? Also try setting the `Response headers policy` to SimpleCORS in the "Edit behavior" page of your distribution

**Comment by mazenkhalil** [comment]
@scmmishra Setting the Responds headers policy to SimpleCORS didn't help. Also please note that analytics tools are not loading as well such as MS Clarity.

Here our configurations:

![New Project-2](https://github.com/user-attachments/assets/8e9a3060-bd8d-4724-9441-b34f273416ae)
![New Project](https://github.com/user-attachments/assets/70c706af-3587-4d29-ba98-7d4a00fc30fa)

**Comment by mazenkhalil** [comment]
@scmmishra Apopogize seems there was some sort of caching... only AWS CDN is not working

**Comment by mazenkhalil** [comment]
@scmmishra [UPDATE] Setting the `Response headers policy` to `CORS-With-Preflight` solves the issue.

![image](https://github.com/user-attachments/assets/b4267ec6-b70f-4dff-a045-c2e9efcecd27)

**Comment by scmmishra** [comment]
> @scmmishra [UPDATE] Setting the `Response headers policy` to `CORS-With-Preflight` solves the issue.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/b4267ec6-b70f-4dff-a045-c2e9efcecd27)
> 
>  

Great! You could unset that and enable OPTIONS request, that should do the trick too. But this should work absolutely fine

**Comment by mazenkhalil** [comment]
@scmmishra Thank you for the support. The thing is OPTIONS is already enabled, without the response headers policy it doesn't work.

**Comment by scmmishra** [comment]
> @scmmishra Thank you for the support. The thing is OPTIONS is already enabled, without the response headers policy it doesn't work.

Ah, noted! I'll take a deeper dive and update the docs soon :)
