### ISSUE TITLE
Docker buid: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by Fabbzz** [chatwoot/chatwoot#10356]
### Describe the bug

Since today I run into this memory issue what was running fine on:

- 4x Core
- 8GB MEM

but now also happens on

- 8x Core
- 16GB MEM

#19 148.5 [128:0x7f497c1925f0]   124053 ms: Scavenge (reduce) 2023.4 (2080.4) -> 2023.3 (2081.1) MB, 6.03 / 0.00 ms  (average mu = 0.368, current mu = 0.285) allocation failure; 
#19 148.5 [128:0x7f497c1925f0]   125773 ms: Mark-Compact (reduce) 2025.7 (2082.9) -> 2025.5 (2083.6) MB, 1274.42 / 0.05 ms  (+ 27.0 ms in 6 steps since start of marking, biggest step 5.6 ms, walltime since start of marking 1317 ms) (average mu = 0.331, current mu =
#19 148.5 
#19 148.5 <--- JS stacktrace --->
#19 148.5 
#19 148.5 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
#19 148.5 ----- Native stack trace -----
#19 148.5 
#19 148.5 
#19 148.5 pid 115 exit 1
#19 148.5 Build with Vite failed! ❌------
executor failed running [/bin/sh -c if [ "$RAILS_ENV" = "production" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi]: exit code: 1

### To Reproduce

Build chatwoot > 3.14.1 (head and first vide versions) using the docker/Dockerfile

### Expected behavior

Complete build.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 24.04.1

### Docker (if applicable)

```
 docker version
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:40:59 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:40:59 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
# docker info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 24
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-47-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.25GiB
 Name: docker-01
 ID: 02ecf458-bb74-4bf3-8066-cac5bc800c1d
 Docker Root Dir: /mnt/docker/local
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 10.0.128.0/17, Size: 24
```

```
# docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by sojan-official** [comment]
@Fabbzz  is there any customizations in the code ?

**Comment by Fabbzz** [comment]
@sojan-official Nope, not at all! I found out that since the Vide builds since 5 days ago I needed to check what went wrong and why.

3.14.1 build went fine last night (yep no sleep); HEAD maxes out memory (and my brain atm) as described.

Both fresh git clones and only copy Dockerfile to ./ of the git clone folder.

**Comment by GeorgVolkov** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by vishnu-narayanan** [comment]
@Fabbzz Please try out the latest develop. Reopen if the issue persists.

**Comment by Fabbzz** [comment]
> @Fabbzz Please try out the latest develop. Reopen if the issue persists.

Will do; thanks!

**Comment by iammattmartin** [comment]
We've tried the latest release and this still happens.

We always had to add a 5GB swap file (despite the docs saying 1GB), and our VM has 8GB memory.

This now always fails.

Such large memory requirements for builds seems totally excessive...

**Comment by iammattmartin** [comment]
Managed to build adding 32GB of ram!
