### ISSUE TITLE
Your inbox is disconnected. You won't receive new messages until you reauthorize it

### ISSUE THREAD

**Issue by fb929** [chatwoot/chatwoot#10375]
### Describe the bug

I have several inboxes, all set up with different Gmail accounts via IMAP and SMTP using app passwords.
All these inboxes simultaneously showed the error "Your inbox is disconnected," and regenerating the app passwords didn’t help.
Moreover, the inboxes are actually working—I can see new emails in Chatwoot.
When trying to click "click here to reconnect," I get a 400 error from Google.

<img width="1436" alt="Screenshot 2024-10-30 at 13 07 05" src="https://github.com/user-attachments/assets/eb298e05-c5b6-41d6-952a-8f7eeaefd106">
<img width="1180" alt="Screenshot 2024-10-30 at 13 08 07" src="https://github.com/user-attachments/assets/eb74e9d8-4a72-49dc-9659-26b754f9e119">
<img width="1048" alt="Screenshot 2024-10-30 at 13 09 16" src="https://github.com/user-attachments/assets/6039869a-fe55-45e4-af6c-d9e8aefe7331">

### To Reproduce

I'm not sure, but it seems we just need to create an inbox on Gmail.

### Expected behavior

I expect the "Your inbox is disconnected" error to be absent.

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Amazon Linux release 2 (Karoo)

### Browser and version

Google Chrome Version 129.0.6668.60 (Official Build) (arm64)

### Docker (if applicable)

1. docker version
```
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        7155243
 Built:             Tue Apr 11 22:56:36 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       6051f14
  Built:            Tue Apr 11 22:57:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.7
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2. docker info
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., 0.0.0+unknown)

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 20.10.23
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc version: f19387a6bec4944c770f7668ab51c4348d9c2f38
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.179-171.711.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.761GiB
 Name: chatwoot-ec2.toolpad.org
 ID: K5V6:OFJG:52V6:7ZQW:DGC3:DCKU:46GC:XF5Q:XMEC:7IVR:M5KS:GW32
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
3. docker-compose version
```
Docker Compose version v2.29.7
```

**Comment by KokeroO** [comment]
Have you checked your inbox for any Gmail notifications?

**Comment by fb929** [comment]
> Have you checked your inbox for any Gmail notifications?

Yes, I checked the emails for notifications from Google – found nothing related.

**Comment by pranavrajs** [comment]
@scmmishra Please take a look. @fb929 I hope the OAuth app[1] is setup properly. Starting Sep 30, Google have started disabling the less secure apps[2].  

[1] https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/google-workspace-setup
[2] https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html

**Comment by scmmishra** [comment]
@fb929 most likely it is an issue with your GMail configuration, you can follow the 1st link @pranavrajs mentioned to set it up.

**Comment by fb929** [comment]
https://workspaceupdates.googleblog.com/2023/09/winding-down-google-sync-and-less-secure-apps-support.html

> All Other Applications
> If the app you are using does not support OAuth, you will need to [switch to an app that offers OAuth](https://support.google.com/a/answer/6260879#alternatives) or create an [app passwor](https://support.google.com/mail/answer/185833)d to access these apps.

If I understood correctly, using an "app password" remains a valid and functional authentication method, and there is no need to transition the application to OAuth authorization.

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by fb929** [comment]
> Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

`A Community of People Loving Jesus and Making Him Known in the Northland of New Zealand`

Not sure if this is within his area of responsibility.

**Comment by pranavrajs** [comment]
> A Community of People Loving Jesus and Making Him Known in the Northland of New Zealand. Not sure if this is within his area of responsibility.


 
Haha! I have reported as spam. 

> If I understood correctly, using an "app password" remains a valid and functional authentication method, and there is no need to transition the application to OAuth authorization.

They previously deprecated this, but based on the latest blog update, it seems it might work again. However, it’s unclear what happens to emails that have already been migrated. Currently, we don’t recommend using an app password, as there’s no way for us to verify if it will function correctly. Migrating would help us reach a state where we can effectively debug this.

**Comment by fb929** [comment]
Did I understand correctly that enabling OAuth will also enable Google authorization in the web UI?
