### ISSUE TITLE
Deploy to Heroku is broken

### ISSUE THREAD

**Issue by timgl** [chatwoot/chatwoot#1037]
**Describe the bug**

When clicking 'Deploy to Heroku' (or even manually pushing from git repo) the build fails. If you use the button, it won't give you any error. Manually pushing it gave me this: 
![image](https://user-images.githubusercontent.com/1727427/87434392-b81aba80-c5ea-11ea-8e49-fda94c70081d.png)

**To Reproduce**
1. Click 'deploy to heroku'
2. Build the app
3. See release command fail

**Expected behavior**
Chatwoot should deploy

**Screenshots**
See above

**Desktop (please complete the following information):**
 - Any

**Smartphone (please complete the following information):**
 - 

**Additional context**
Chatwoot looks great and keen to use it at PostHog :)

**Comment by pranavrajs** [comment]
Seems to be related to #1036. We are running db:prepare, so it should not break due to any migration, let me quickly deploy it to Heroku and see.

**Comment by pranavrajs** [comment]
@timgl This should be fixed in the latest master. Please check this out.
