### ISSUE TITLE
New messages from other channels do not appear as "Unread"

### ISSUE THREAD

**Issue by mohmmd256** [chatwoot/chatwoot#1038]
**Describe the bug**
When a user sends a new message to a previously initiated conversation from Facebook or Twitter, then these new messages won't get indicated as "Unread". New messages on conversations from chat widget behave as expected with no issues noticed.

**To Reproduce**
1. Initiate a conversation from Facebook or Twitter.
2. Go to 'Conversations' in Chatwoot and open the conversation.
3. Click on 'Resolve' (or just select another conversation to remove focus from it).
4. Send another message from the channel.
5. See error.

**Expected behavior**
All new messages that come in later on that conversation won't appear as "Unread".

**Screenshots**

![Screen Shot 2020-07-14 at 4 12 59 PM](https://user-images.githubusercontent.com/7905931/87436354-39734c80-c5ed-11ea-8514-8a2e1c27c291.png)

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Browser [chrome]
 - Version [e.g. 89]

**Additional Context**
This can lead to missing out on new messages sent by users and possible delays in replies.

**Comment by pranavrajs** [comment]
@mohmmd256 I couldn't reproduce this issue, Can you please a screen-cast of the behaviour?

**Comment by mohmmd256** [comment]
> @mohmmd256 I couldn't reproduce this issue, Can you please a screen-cast of the behaviour?

![ezgif-4-2fba1c1b7a43](https://user-images.githubusercontent.com/7905931/87594515-5ee77f80-c6ed-11ea-8b10-cc9b1dda04cf.gif)

**Comment by pranavrajs** [comment]
@mohmmd256 That's a weird behaviour, we will take a look at it.

**Comment by pranavrajs** [comment]
@WevrLabs Did you use our mobile app?

**Comment by WevrLabs** [comment]
> @WevrLabs Did you use our mobile app?

Hi @pranavrajs !
Yes, I've been trying it for the past couple of weeks (Android version).

**Comment by pranavrajs** [comment]
Thanks for confirming that.
