### ISSUE TITLE
Not able to loggin after upgrade latest

### ISSUE THREAD

**Issue by nrsf** [chatwoot/chatwoot#10383]
### Describe the bug

I'm not able to login after upgrade latest.

Just upgrade container from [v3.13.0] to [latest] and cannot login. 
If I open a browser that was logged in before it keeps looping to the URLs:
https://xxxx.yyyy.com/app/
to 
https://xxxx.yyyy.com/app/login
then to https://xxxx.yyyy.com/app/ 
and looping...

If I start browser in incognito mode it give me the error:
![image](https://github.com/user-attachments/assets/34c82aca-4be8-4d58-8035-5c9f5c11d76b)

### To Reproduce

Do not know.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Linux Ubuntu

### Browser and version

Chrome latest

### Additional context

Error log:
[_chatwootbi_chatwoot_app.1.lu61itntxtdb4pkr7z4f69dje_logs.txt](https://github.com/user-attachments/files/17606971/_chatwootbi_chatwoot_app.1.lu61itntxtdb4pkr7z4f69dje_logs.txt)

**Comment by nrsf** [comment]
Fixed ater run:
bundle exec rails db:chatwoot_prepare

**Comment by ryonwhyte** [comment]
Thank you @nrsf
