### ISSUE TITLE
Self-hosted Twitter integration results in "Sign in with Twitter" loop

### ISSUE THREAD

**Issue by Rid** [chatwoot/chatwoot#1040]
**Describe the bug**
After setting up twitter integration on our self-hosted install using the instructions from https://www.chatwoot.com/docs/twitter-app-setup the "Sign in with Twitter" button takes us to the "Authorize app to access your account?" twitter page, upon clicking authorize, you are then taken back to the `/app/accounts/<ID>/settings/inboxes/new/twitter` page which still displays the "Sign in with Twitter" button. Clicking the button again just follows the same loop.

**To Reproduce**
1.  Setup twitter integration using https://www.chatwoot.com/docs/twitter-app-setup
2. Go to https://chatwoot.example.com/app/accounts/ID/settings/inboxes/new/twitter
3. Click "Sign in with Twitter:
4. Authorize the app
5. Get taken back to setup 2

**Expected behavior**
Twitter integration to setup successfully.

**Logs**
```
I, [2020-07-14T16:09:37.140059 #221]  INFO -- : [d35288f1-b964-4e13-8dfd-5353dd3fefa9] Started GET "/twitter/callback?oauth_token=[FILTERED]&oauth_verifier=[FILTERED]" for 172.20.4.1 at 2020-07-14 16:09:37 +0000
I, [2020-07-14T16:09:37.141237 #221]  INFO -- : [d35288f1-b964-4e13-8dfd-5353dd3fefa9] Processing by Twitter::CallbacksController#show as HTML
I, [2020-07-14T16:09:37.141294 #221]  INFO -- : [d35288f1-b964-4e13-8dfd-5353dd3fefa9]   Parameters: {"oauth_token"=>"[FILTERED]", "oauth_verifier"=>"[FILTERED]"}
I, [2020-07-14T16:09:38.246711 #221]  INFO -- : [d35288f1-b964-4e13-8dfd-5353dd3fefa9] no implicit conversion of String into Integer
I, [2020-07-14T16:09:38.247253 #221]  INFO -- : [d35288f1-b964-4e13-8dfd-5353dd3fefa9] Redirected to https://chatwoot.example.com/app/accounts/2/settings/inboxes/new/twitter
```

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Browser: Chrome & FireFox
 - Version: 80.0.3987.132 & 78.0.1

**Server**
 - OS: Ubuntu 18.04
 - Ruby version: 2.7.1
 - Chatwoot version: 1.6.1

**Comment by pranavrajs** [comment]
Most of the people miss this step thinking that this is for development setup. Have you done https://www.chatwoot.com/docs/twitter-app-setup#create-a-dev-environment and do you have access to Business APIs?

**Comment by Rid** [comment]
@pranavrajs Thanks for the tip, I had setup a dev environment but assigned it to the wrong app. All working now.
