### ISSUE TITLE
Problemas al ingresar nuevos Agentes

### ISSUE THREAD

**Issue by JuQird** [chatwoot/chatwoot#10405]
### Describe the bug

Cuando agredo los datos de un nuevo agente, como el nombre y contraseña, se queda en pendiente por verificar, pero el correo electrónico con las informaciones para iniciar sesión no llega. 

### To Reproduce

![image](https://github.com/user-attachments/assets/f6a0c3f1-0b81-4352-9d2b-66edad63c53a)

### Expected behavior

Me gustaria, saber que debo solucionar, esta instalación la realice traves de easypanel 

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by wannaco** [comment]
No conozco de easypanel pero entiendo ellos utilizan la version selfhosted, por lo cual necesitas configurar las variables fe entorno requeridas para enviar correo https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables 

Contacta a su soporte para detalle de como hacerlo en su plataforma.

**Comment by leguizamonmax** [comment]
# Configuración general de SMTP
SMTP_ADDRESS=smtp.example.com               # Dirección del servidor SMTP
SMTP_PORT=587                                # Puerto del servidor SMTP (587 para STARTTLS o 465 para SSL)
SMTP_DOMAIN=example.com                      # Dominio del correo electrónico

# Configuración de autenticación SMTP
SMTP_USERNAME=your-email@example.com         # Dirección de correo para autenticación
SMTP_PASSWORD=your_password                  # Contraseña del correo electrónico
SMTP_AUTHENTICATION=login                    # Tipo de autenticación (puede ser "plain", "login", o "cram_md5")
SMTP_ENABLE_STARTTLS_AUTO=true               # Activa STARTTLS automáticamente (true para seguridad extra)
SMTP_OPENSSL_VERIFY_MODE=none                # Modo de verificación SSL (ajustar si tienes problemas con certificados SSL)

**Comment by sojan-official** [comment]
@JuQird easypanel is a community contributed installation for which we don't provide official suppot. please reach out to their team for debugging.
