### ISSUE TITLE
Erro no SMTP

### ISSUE THREAD

**Issue by mazierovictor** [chatwoot/chatwoot#10414]
### Describe the bug

Realizei a configuração do SMPT conforme as variaveis de ambiente, porém o erro Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" -- ainda permanece. Abaixo as variaveis configuradas.

MAILER_SENDER_EMAIL=MeuEmail@mail.com
SMTP_ADDRESS=smtp.mailgun.org
SMTP_AUTHENTICATION=plain
SMTP_DOMAIN=dominio.mailgun.org
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_PORT=587
SMTP_USERNAME=postmaster@dominio.mailgun.org
SMTP_PASSWORD=minha_senha_e97fed52dee29bf995be7dfebdb8b030-79295dd0-810d2a87

### To Reproduce

Pra produzir o erro acima tente recuperar a senha do usuário.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu Server

**Comment by mazierovictor** [comment]
Essa configuração poderia ser feita através do painel super admin.

**Comment by shivamkb17** [comment]
can you send me error log, SO That I can guide you, how can it will be fixed. Recently I also facing similar issue with google workplace smtp setting. but After checking log, I found the error.

**Comment by mazierovictor** [comment]
@shivamkb17 

error log:

I, [2024-11-18T14:25:19.487709 #1]  INFO -- : source=rack-timeout id=cfff2f77-836a-4e71-8735-a70c787a7c46 timeout=15000ms state=ready
I, [2024-11-18T14:25:19.488263 #1]  INFO -- : [cfff2f77-836a-4e71-8735-a70c787a7c46] Started POST "/auth/password" for 192.168.10.250 at 2024-11-18 14:25:19 +0000
I, [2024-11-18T14:25:19.493047 #1]  INFO -- : [cfff2f77-836a-4e71-8735-a70c787a7c46] Processing by DeviseOverrides::PasswordsController#create as HTML
I, [2024-11-18T14:25:19.493132 #1]  INFO -- : [cfff2f77-836a-4e71-8735-a70c787a7c46]   Parameters: {"email"=>"perito.victormaziero@gmail.com", "password"=>{"email"=>"perito.victormaziero@gmail.com"}}
I, [2024-11-18T14:25:19.524517 #1]  INFO -- : [cfff2f77-836a-4e71-8735-a70c787a7c46] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: 1bb47b62-5bea-4df5-9398-68b5dd56026a) to Sidekiq(default) with arguments: "Devise::Mailer", "reset_password_instructions", "deliver_now", {:params=>{:account=>nil}, :args=>[#<GlobalID:0x00007c44b5d601c0 @uri=#<URI::GID gid://chatwoot/SuperAdmin/1>>, "VFCbN89xgvvH-e-KN-xK", {:client_config=>"default"}]}
I, [2024-11-18T14:25:19.524991 #1]  INFO -- : [cfff2f77-836a-4e71-8735-a70c787a7c46] Completed 200 OK in 32ms (Views: 0.2ms | ActiveRecord: 14.1ms | Allocations: 4842)
I, [2024-11-18T14:25:19.525217 #1]  INFO -- : source=rack-timeout id=cfff2f77-836a-4e71-8735-a70c787a7c46 timeout=15000ms service=38ms state=completed

error log Sidekiq:


Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" -- \"meuemailvalido@gmail.com\""

**Comment by mazierovictor** [comment]
Alguém?? 

Estou precisando cadastrar agentes na minha plataforma e não estou conseguindo

**Comment by sojan-official** [comment]
please debug smtp config error using this : https://www.chatwoot.com/docs/self-hosted/faq#how-to-debug-smtp-email-errors-in-chatwoot 

in your case it seems like the system is attempting to use sendmail. this happens when the environment variable is not properly available in web / worker images.

**Comment by mazierovictor** [comment]
@sojan-official 

Eu fiz o debug, entretanto eu alterei o smtp nas variáveis de ambiente para utilizar o SeS da AWS, e no debug ainda está usando o smtp da mailgun.

E toda configuração que faço de acordo com o link passado ele só retorna erro.

![image](https://github.com/user-attachments/assets/b55c142e-24ca-44e3-aac0-643f29248900)


smtp_settings = {
  address: 'email-smtp.us-east-1.amazonaws.com',
  user_name: 'myusername',
  password: 'mypassword',
  authentication: 'plain',
  enable_starttls_auto: 'true',
}
mailer.mail(from: 'contato@mspericias', to: 'mazierovictor@gmail.com', subject: 'test', body: "Hello, you've got mail!").deliver
