### ISSUE TITLE
Bug: Incorrect Message Count in "Agents - Messages Received" Report

### ISSUE THREAD

**Issue by ghazialhouwari** [chatwoot/chatwoot#10423]
### Describe the bug

In the "Reports" section under "Agents," the "Messages Received" metric always displays a count of zero, even when agents have received messages.

<img width="861" alt="Conversation" src="https://github.com/user-attachments/assets/1153d4f7-913f-4653-a5c8-f1483a5bbace">

<img width="1253" alt="Agents metrics" src="https://github.com/user-attachments/assets/32b1fc16-cceb-43fd-9cf2-f057fd361c00">

<img width="1253" alt="Conversations metrics" src="https://github.com/user-attachments/assets/a64daa8a-cbeb-4fa9-85bb-23492e826b1c">

### To Reproduce

1. Set up a "Website Inbox".
2. Start a conversation with an agent using the website inbox.
3. Navigate to Reports → Agents → Messages Received and observe the "Messages Received" count for the agent.

### Expected behavior

The "Messages Received" metric should accurately reflect the number of messages received by the selected agent.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

macOS Sequoia 15.1

### Browser and version

Google Chrome Version 130.0.6723.117

**Comment by sojan-official** [comment]
fixed by : https://github.com/chatwoot/chatwoot/pull/10415
