### ISSUE TITLE
My server deployment failed

### ISSUE THREAD

**Issue by liubotao003** [chatwoot/chatwoot#10441]
### Is your feature or enhancement related to a problem? Please describe.

Dear developers, my server is CentOS, my database is MariaDB, I searched for the deployment documents, including changing the command of ubuntu to CentOS, but it was unsuccessful

### Describe the solution you'd like

please send a deployment document for my kind of server, thank you very much.

**Comment by pranavrajs** [comment]
Hey @liubotao003, We don't support MariaDB. Postgres is the database. We can't provide support for CentOS as we don't have a package maintained there. Please use the supported platforms.
