### ISSUE TITLE
It not works in subdirectory

### ISSUE THREAD

**Issue by xenera-zhangtao** [chatwoot/chatwoot#1045]
**Is your enhancement request related to a problem? Please describe.**
I deployed chatwoot in subdirectory of my domain, but it not works.
https://mydomian.com/sub-directory/
Because the js and css file can not be read(404 error).
the js and css path is the following
https://mydomian.com/packs/js/application-bec4331ea7ac1866afd7.js

https://mydomian.com/sub-directory/packs/js/application-bec4331ea7ac1866afd7.js will be correct.

**Describe the solution you'd like**
Can we set the sub-directory via conf file?
Thanks.

**Comment by sony-mathew** [comment]
Hey @xenera-zhangtao , Can you try setting `FRONTEND_URL` environment variable's value as `https://mydomian.com/sub-directory/`?

Ref: https://www.chatwoot.com/docs/environment-variables

@pranavrajs Please advise.

**Comment by sojan-official** [comment]
@xenera-zhangtao using chatwoot on a subdirectory is not advised.   please use a domain/subdomain since we are building features based on that assumption.
