### ISSUE TITLE
Chatwoot + easypanel not sending verification e-mail (Sendmail::DeliveryError: Delivery failed with exitstatus)

### ISSUE THREAD

**Issue by andreylima** [chatwoot/chatwoot#10452]
### Describe the bug

I'm using chatwoot 3.14 (altready tried with 3.9) installed with easypanel in Contabo Vps.
When I create another agent it won't send the verification email, and will return this message:

`Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" --\"myemail@hotmail.com\""`

These are the enviroment variables I'm using to configure SMPT:

```
MAILER_SENDER_EMAIL=myemail@myprovider.com.br
SMTP_ADDRESS=smtp.gmail.com
SMTP_USERNAME=myemail@myprovider.com.br
SMTP_PASSWORD=****
SMTP_PORT=587
SMTP_DOMAIN=gmail.com
SMTP_AUTHENTICATION=login
SMTP_OPENSSL_VERIFY_MODE=peer
SMTP_ENABLE_STARTTLS_AUTO=true
```

But I tried a lot of variation and It won't work, could someone save me please?

### To Reproduce

Install chatwoot with easypanel and set the variables as I did.

### Expected behavior

Sidekiq will show this error:

`Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" -- \"andreylrgv@hotmail.com\""`

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

3.14.0

### Browser and version

Chrome latest

### Docker (if applicable)

chatwoot/chatwoot:latest

**Comment by sojan-official** [comment]
it seems like your installation is still using sendmail and not the smtp config set in environment variables, please check with the easypanel team about this. ensure that you have these environment variables in both web and worker images . 

please use the the following guide to debug smpt issues further :
https://www.chatwoot.com/docs/self-hosted/faq#how-to-debug-smtp-email-errors-in-chatwoot
