### ISSUE TITLE
Feature: Show re-authorize screen for Facebook if the page access token is expired/invalid

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1046]
When the users change their Facebook password, the page access token gets invalidated. To overcome this, ask the user to reauthorize the Facebook connection

### Acceptance Criteria

- [ ] Run a cronjob every day to find the invalid token, mark the integration as invalid/needs-reauthorization
- [ ] If the flag is set, show a message in the frontend to reauthorize

https://developers.facebook.com/docs/facebook-login/reauthentication/

**Comment by pranavrajs** [comment]
`Facebook::Messenger::FacebookError: Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.`

**Comment by iammattmartin** [comment]
Cont of the email sent, this is fairly important.

There appears to be no way to fix this via the GUI when it happens apart from deleting the Inbox and recreating, losing all history associated.

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/1286
