### ISSUE TITLE
Instagram messages not being created

### ISSUE THREAD

**Issue by CrimsonSunrise** [chatwoot/chatwoot#10465]
### Describe the bug

I recently got advanced permisions from Facebook and now other people are able to log in using the "Continue with Facebook" to select the business account, facebook page and instagram account.

My advanced permissions from Facebook:
pages_manage_metadata
pages_messaging
instagram_manage_messages
public_profile
pages_show_list
business_management
instagram_basic

During the testing all worked very well, with only the testers and admins being able to send messages.

Now that I have advanced permissions I expected it to be working for anyone who create an inbox from their facebook account (fb business, professional instagram, linked facebook page with instagram, etc) but something weird is happening.

At first, I saw that the messages were sent to the sidekiq and I could see it on the logs but nothing was rendered on the frontend. Another interesting fact is that next to the message or message event on the sidekiq console I could see a message like "IG_MESSAGE_CREATE_LOCK". Went to the code and toke a look of what could it be. The file "app/lib/redis/redis_keys.rb" says:

```
## Sempahores / Locks
# We don't want to process messages from the same sender concurrently to prevent creating double conversations
IG_MESSAGE_MUTEX = 'IG_MESSAGE_CREATE_LOCK::%<sender_id>s::%<ig_account_id>s'.freeze
...
```

Which makes me believe the message was being tagged as spam or something.

The app console:
```
I, [2024-11-20T16:02:00.347607 #27]  INFO -- : [caa7e10f-41fc-456d-a4d2-09a94509ee13]   Parameters: {"object"=>"instagram", "entry"=>[{"time"=>1732118520015, "id"=>"17841407771149991", "messaging"=>[{"sender"=>{"id"=>"17841407771149991"}, "recipient"=>{"id"=>"571220752123436"}, "timestamp"=>1732118519675, "message"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDA3NzcxMTQ5OTkxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTczMzgxNDAxMjYwOTE1NDozMTk1MTk0NzAzNzc5MjkzNjY4MzAxMjEzNDkwNjM2MzkwNAZDZD", "text"=>"Coé jovem", "is_echo"=>true}}]}], "instagram"=>{"object"=>"instagram", "entry"=>[{"time"=>1732118520015, "id"=>"17841407771149991", "messaging"=>[{"sender"=>{"id"=>"17841407771149991"}, "recipient"=>{"id"=>"571220752123436"}, "timestamp"=>1732118519675, "message"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDA3NzcxMTQ5OTkxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTczMzgxNDAxMjYwOTE1NDozMTk1MTk0NzAzNzc5MjkzNjY4MzAxMjEzNDkwNjM2MzkwNAZDZD", "text"=>"Coé jovem", "is_echo"=>true}}]}]}}
I, [2024-11-20T16:02:00.348193 #27]  INFO -- : [caa7e10f-41fc-456d-a4d2-09a94509ee13] Instagram webhook received events
I, [2024-11-20T16:02:00.351361 #27]  INFO -- : [caa7e10f-41fc-456d-a4d2-09a94509ee13] [ActiveJob] Enqueued Webhooks::InstagramEventsJob (Job ID: b9ef2e52-4090-40f4-9fec-f73f204e5caa) to Sidekiq(default) with arguments: [{"time"=>1732118520015, "id"=>"17841407771149991", "messaging"=>[{"sender"=>{"id"=>"17841407771149991"}, "recipient"=>{"id"=>"571220752123436"}, "timestamp"=>1732118519675, "message"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDA3NzcxMTQ5OTkxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTczMzgxNDAxMjYwOTE1NDozMTk1MTk0NzAzNzc5MjkzNjY4MzAxMjEzNDkwNjM2MzkwNAZDZD", "text"=>"Coé jovem", "is_echo"=>true}}]}]
I, [2024-11-20T16:02:00.352199 #27]  INFO -- : [caa7e10f-41fc-456d-a4d2-09a94509ee13] Completed 200 OK in 4ms (Views: 0.4ms | ActiveRecord: 0.0ms | Allocations: 565)
```

The sidekiq console:
```
I, [2024-11-20T16:02:00.355626 #1]  INFO -- : [ActiveJob] [Webhooks::InstagramEventsJob] [b9ef2e52-4090-40f4-9fec-f73f204e5caa] Performing Webhooks::InstagramEventsJob (Job ID: b9ef2e52-4090-40f4-9fec-f73f204e5caa) from Sidekiq(default) enqueued at 2024-11-20T16:02:00Z with arguments: [{"time"=>1732118520015, "id"=>"17841407771149991", "messaging"=>[{"sender"=>{"id"=>"17841407771149991"}, "recipient"=>{"id"=>"571220752123436"}, "timestamp"=>1732118519675, "message"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDA3NzcxMTQ5OTkxOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTczMzgxNDAxMjYwOTE1NDozMTk1MTk0NzAzNzc5MjkzNjY4MzAxMjEzNDkwNjM2MzkwNAZDZD", "text"=>"Coé jovem", "is_echo"=>true}}]}]
I, [2024-11-20T16:02:00.358123 #1]  INFO -- : [ActiveJob] [Webhooks::InstagramEventsJob] [b9ef2e52-4090-40f4-9fec-f73f204e5caa] [Webhooks::InstagramEventsJob] Acquired lock for: IG_MESSAGE_CREATE_LOCK::17841407771149991::17841407771149991 on attempt 1
I, [2024-11-20T16:02:00.369577 #1]  INFO -- : [ActiveJob] [Webhooks::InstagramEventsJob] [b9ef2e52-4090-40f4-9fec-f73f204e5caa] Performed Webhooks::InstagramEventsJob (Job ID: b9ef2e52-4090-40f4-9fec-f73f204e5caa) from Sidekiq(default) in 15.14ms
```

Funny that Facebook Pages messaging is working fine and only Instagram isn't working now.

On the first test account, the one I used through the app review process, everything is working. I can receive messages from people outside the test permissions.

### To Reproduce

1. Create a new "Messenger" Inbox and connect Facebook Pages and Instagram.
2. Send a new message from any other account to the connected Instagram account.
3. Check if the message event appear inside Chatwoot or in the logs (app, sidekiq)

### Expected behavior

The message would appear as a new conversation in Chatwoot.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by dmasciel** [comment]
I have the same problem

**Comment by CrimsonSunrise** [comment]
I could solve the problem (partialy) by reinstalling Chatwoot in my vps many times until it worked.
For some reason it wasn't adding the instagram account id to the table but after some reinstalls it worked.
