### ISSUE TITLE
Deployment error reported, please help me fix it

### ISSUE THREAD

**Issue by liubotao003** [chatwoot/chatwoot#10524]
### Describe the bug

[chatwoot-setup.log](https://github.com/user-attachments/files/17971474/chatwoot-setup.log)

### To Reproduce

./install.sh --install ，An error message is displayed when this command is executed

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 22.04

**Comment by vishnu-narayanan** [comment]
@liubotao003 Could you share your machine specifications? RAM/CPU?

**Comment by liubotao003** [comment]
Plese help me
