### ISSUE TITLE
add the speechToText sent through evolutionapi as text together with the audio file

### ISSUE THREAD

**Issue by reichert** [chatwoot/chatwoot#10520]
### Is your feature or enhancement related to a problem? Please describe.

it is an alternative to a feature already requested

### Describe the solution you'd like

Some asked for a transcription feature using API. When using evolutionapi there is already a transcription routine and the transcription is sent with the AudioMessage with a key in json called "speechToText".
This would be easier to implement than a method for doing the transcription

**Comment by vishnu-narayanan** [comment]
@reichert There is no plan to support Evolution API at the moment. For Whatsapp, Chatwoot supports the official API.
