### ISSUE TITLE
Incoming files name wrong in Cloud API

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#10527]
### Describe the bug

When I receive images from the cloud api, the file names are coming wrong, when there are spaces. The file
"file 01.pdf" comes with the name "file_01.pdf-filename*=".

Using AWS S3 as storage.

### To Reproduce

1. In a Cloud API WhatsApp Channel send a file with filename = "arq 01.pdf"
2. Verify the filename in Chatwoot - will be "arq_01.pdf-filename*="

### Expected behavior

The filename must be the same who client send.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Debian

### Browser and version

Chrome Latest

**Comment by pranavrajs** [comment]
@jmelati We cannot reproduce this on our end. Can you please share more information on how to reproduce the issue here? Are you using official WhatsApp Cloud API?

**Comment by jmelati** [comment]
Yes, using Cloud API and AWS S3 storage.
Via whatsapp send an file with filename have spaces.
In Chatwoot the filename is wrong.
See attached video:

https://github.com/user-attachments/assets/67983f5c-c859-4507-b68f-b220e145269f

**Comment by pranavrajs** [comment]
@jmelati, can you please share the screenshot of the account settings page which has the commit ID and version.

**Comment by jmelati** [comment]
Shure!
![image](https://github.com/user-attachments/assets/bb97895b-f067-4855-a0c6-f4ca60e532be)

**Comment by sojan-official** [comment]
You are not using an official Chatwoot build !  For unofficial builds please contact with original author for issues.
https://github.com/search?q=959d2c0d8c4531e938b05890c40908b17e413f83&type=pullrequests

**Comment by jmelati** [comment]
No, @sojan-official and @pranavrajs .
I´m using official Chatwoot. The rebuild is only for translations, who in Portuguese-BR is not 100% accurate. Only translations. And the rebuild is done with this tutorial:
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm
without cwctl.

**Comment by jmelati** [comment]
@sojan-official 

I installed a new version of chatwoot on a new machine (direct installation in VM) and the error was reproduced.
![image](https://github.com/user-attachments/assets/4835bc21-64ec-401d-9919-ebf7c1790061)
