### ISSUE TITLE
Missing docs

### ISSUE THREAD

**Issue by amesas** [chatwoot/chatwoot#10533]
### Describe the bug

We can't find docs for some channels like Whatsapp

### To Reproduce

1. Go to the help center: https://www.chatwoot.com/help-center
2. Search for twilio or whatsapp
3. Click on any search result, like: https://www.chatwoot.com/docs/product/channels/whatsapp/whatsapp-cloud/#setup-whatsapp-inbox-in-chatwoot
4. You get a 404 

### Expected behavior

Find docs for all supported channels.

### Environment

Other [please specify in the description]

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@amesas Thanks for reporting this, we will fix this soon. If you refresh the URL, you would see the docs.

**Comment by amesas** [comment]
Fixed, thnx :)
