### ISSUE TITLE
Sent emails from gmail not reflecting on chatwoot

### ISSUE THREAD

**Issue by divyajagtap7** [chatwoot/chatwoot#10542]
### Describe the bug

When i reply from my gmail app it doesn't reflect on my chatwoot account

### To Reproduce

1.Go to gmail app 
2.Reply to some email
3.Go to chatwoot in your email
4.The sent mail doesn't reflect in chatwoot email

### Expected behavior

I am expecting the sent mail should reflect in chatwoot

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@divyajagtap7 Could you please provide more information? There’s no debug information available here. Have you connected the email using the native Gmail integration?

**Comment by divyajagtap7** [comment]
@pranavrajs What is happening is I am sending a mail from my email account to someone else and when i go to chatwoot that email is not coming on my chatwoot email channel . Is there any setting which i need to follow??

**Comment by sojan-official** [comment]
@divyajagtap7  Chatwoot will only fetch incoming emails to your inbox from external users and will track the emails send directly from Chatwoot. it will not fetch the mails you sent directly from your gmail account. 

For cloud related queries you can contact us directly via the contact support option available in your account ( click on the avatar on bottom left )
