### ISSUE TITLE
WebSocket Messages Not Updating in Real-Time needs Refresh to display messages

### ISSUE THREAD

**Issue by almomdegal** [chatwoot/chatwoot#10557]
### Describe the bug

I am experiencing an issue with messages in the Chatwoot widget not updating in real-time. The WebSocket connection appears to be established correctly, and logs indicate that message events are being processed by the backend without errors. However, the frontend fails to display updated messages in real-time.

Messages do not update in the widget despite being logged as successfully processed on the backend.
WebSocket connections are successfully established and maintained, with no visible errors in the network or backend logs.
A manual page refresh is required to see updated messages.

### To Reproduce

Chatwoot Version: 3.15.0
Environment: Production
Database: PostgreSQL
Redis: Configured for caching and Sidekiq (redis://redis:6379)

Open the widget on a website integrated with Chatwoot.
Initiate a conversation and send a message.
Observe that the sent message does not appear in the widget until the page is refreshed.

### Expected behavior

Messages sent or received in a conversation should appear in the widget immediately without requiring a page refresh.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22

### Browser and version

Chrome

### Docker (if applicable)

Docker version 27.3.1

### Additional context

version: "3.8"

# Command to use:
# command: bundle exec rails db:chatwoot_prepare

services:
  # Main Chatwoot frontend service
  chatwoot_app:
    image: chatwoot/chatwoot:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0 
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - servicos_network
    ports:
      - "3000:3000"
    environment:
      INSTALLATION_NAME: chatwootatrio
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: <your_secret_key>
      FRONTEND_URL: https://chatwoot.atriobusiness.com.br
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      REDIS_URL: redis://redis:6379
      # Email server configuration
      MAILER_SENDER_EMAIL: Chatwoot <your_email>
      SMTP_DOMAIN: <smtp_domain>
      SMTP_ADDRESS: <smtp_address>
      SMTP_PORT: <smtp_port>
      SMTP_USERNAME: <your_smtp_username>
      SMTP_PASSWORD: <your_smtp_password>
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: peer
      MAILER_INBOUND_EMAIL_DOMAIN: <your_email_domain>
      # Database configuration
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: <db_username>
      POSTGRES_PASSWORD: <db_password>
      POSTGRES_DATABASE: chatwoot
      # Storage
      ACTIVE_STORAGE_SERVICE: local
      # Logs
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_LOG_LEVEL: debug
      # Bot Avatar
      USE_INBOX_AVATAR_FOR_BOT: "true"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # Chatwoot worker
  chatwoot_worker:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - servicos_network
    environment:
      INSTALLATION_NAME: chatwootatrio
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: <your_secret_key>
      FRONTEND_URL: https://chatwoot.atriobusiness.com.br
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      REDIS_URL: redis://redis:6379
      # Email server configuration
      MAILER_SENDER_EMAIL: Chatwoot <your_email>
      SMTP_DOMAIN: <smtp_domain>
      SMTP_ADDRESS: <smtp_address>
      SMTP_PORT: <smtp_port>
      SMTP_USERNAME: <your_smtp_username>
      SMTP_PASSWORD: <your_smtp_password>
      SMTP_AUTHENTICATION: login
      SMTP_ENABLE_STARTTLS_AUTO: "true"
      SMTP_OPENSSL_VERIFY_MODE: peer
      MAILER_INBOUND_EMAIL_DOMAIN: <your_email_domain>
      # Database configuration
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: <db_username>
      POSTGRES_PASSWORD: <db_password>
      POSTGRES_DATABASE: chatwoot
      # Storage
      ACTIVE_STORAGE_SERVICE: local
      # Logs
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_LOG_LEVEL: debug
      # Bot Avatar
      USE_INBOX_AVATAR_FOR_BOT: "true"
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager

  # Redis service
  redis:
    image: redis:6.2.16
    networks:
      - servicos_network
    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  chatwoot_data:
    external: true

networks:
  servicos_network:
    external: true

**Comment by sojan-official** [comment]
@almomdegal  check if the sidekiq process is running properly and the jobs are being processed.

**Comment by davides93** [comment]
Hi, I encountered a similar issue on my Azure Kubernetes cluster. I was using Traefik as a reverse proxy for my Chatwoot pods. The problem was that Chatwoot was configured to use HTTPS and SSL, but the Chatwoot service and Traefik's service discovery were using an HTTP endpoint.

To resolve this, I disabled FORCE_SSL in the Chatwoot .env file, and it worked correctly.

Of course, SSL is essential for security. In my setup, Traefik handles SSL termination externally, while internal cluster communication remains HTTP on a custom port (e.g., 3000 for the Chatwoot web pod). This configuration ensures secure external access while maintaining efficient internal communication.

I hope this helps!

**Comment by almomdegal** [comment]
> @almomdegal check if the sidekiq process is running properly and the jobs are being processed.

All jobs were beeing process fine



> Hi, I encountered a similar issue on my Azure Kubernetes cluster. I was using Traefik as a reverse proxy for my Chatwoot pods. The problem was that Chatwoot was configured to use HTTPS and SSL, but the Chatwoot service and Traefik's service discovery were using an HTTP endpoint.
> 
> To resolve this, I disabled FORCE_SSL in the Chatwoot .env file, and it worked correctly.
> 
> Of course, SSL is essential for security. In my setup, Traefik handles SSL termination externally, while internal cluster communication remains HTTP on a custom port (e.g., 3000 for the Chatwoot web pod). This configuration ensures secure external access while maintaining efficient internal communication.
> 
> I hope this helps!

The issue was that:

If you're hosting a service like Chatwoot behind pfSense using HAProxy for SSL termination and running into issues with WebSocket connections dropping, here's a step-by-step explanation of the problem and how to solve it.

The Setup
Service (Chatwoot):

Running on an internal server at port 3000.
Configured with force_ssl = true, meaning it expects all connections to be HTTPS.
Does not have a valid SSL certificate for the internal connection.
HAProxy on pfSense:

Handles SSL termination using a valid certificate from ACME (Let’s Encrypt).
Forwards traffic from external HTTPS (port 443) to internal HTTPS (port 3000).
Simplifies certificate management by acting as a single point of SSL termination.
Issue:

WebSocket connections between the client and Chatwoot fail.
This happens because WebSocket handshakes rely on specific HTTP headers that aren’t automatically handled by HAProxy.
The Problem
WebSockets require a handshake during connection initialization. This involves specific HTTP headers:

Connection: Upgrade
Upgrade: websocket
When these headers are missing or incorrect, the WebSocket connection fails. By default, HAProxy doesn’t forward these headers correctly unless explicitly configured.

Additionally, Chatwoot needs to understand that the original connection was secure (HTTPS), even though the forwarded connection to the backend is HTTPS. This is where the X-Forwarded-Proto header comes in.

The Solution
To fix this issue, update your HAProxy configuration with the following rules:

haproxy

```
http-request set-header Connection "Upgrade" if { hdr(Upgrade) -i websocket }
http-request set-header Upgrade "websocket" if { hdr(Upgrade) -i websocket }
http-request set-header X-Forwarded-Proto https
```

Hope That if anyone faces a similary issue this helps!
