### ISSUE TITLE
Timeoutable error

### ISSUE THREAD

**Issue by EduardoAldrimf** [chatwoot/chatwoot#10551]
### Describe the bug

# ==> Configuration for :timeoutable
  # The time you want to timeout the user session without activity. After this
  # time the user will be asked for credentials again. Default is 30 minutes.
    config.timeout_in = 30.minutes

A feature acima aparentemente não está funcionando, testei também com 5 minutos e não obtive resultado.

config/initializers/devise.rb

### To Reproduce

Run chatwoot.

### Expected behavior

It was expected to log out of the user's session.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

**Comment by pranavrajs** [comment]
@EduardoAldrimf, I’m not sure what the issue is here. Could you please recreate the problem with more details?
