### ISSUE TITLE
Super Admin access lost

### ISSUE THREAD

**Issue by mormig35** [chatwoot/chatwoot#10571]
### Describe the bug

Hello Support In version 3.15 the super admin link not show in the console not is available to login to super admin area 

Installation Ubuntu 24.04 on linux 

![Chatwoot-12-11-2024_12_34_AM](https://github.com/user-attachments/assets/cf7f78ca-96ef-45f6-9452-7d9696ddb9e9)

### To Reproduce

ready describe arrive

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 24.04

**Comment by pranavrajs** [comment]
@mormig35 Thanks for testing v4 changes. You can hit /super_admin access directly to access for now. We will get a fix for it.

**Comment by scmmishra** [comment]
Hey @mormig35 fixed this issue, we'll merge this and publish it with the upcoming release
