### ISSUE TITLE
Popout Window alternative to in-frame

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1058]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Only having the option to keep the conversation on the website isn't liked by some customers. Many other chat/messenger solutions allow the chat to "popout". That being just a small popout window, no tool bars, just the chat in a new window. Allows the user to continue a chat whilst being able to do other things and not lose focus.

Our existing chat stats show that a large majority use this.

**Describe alternatives you've considered**
None possible.

**Comment by pranavrajs** [comment]
@iammattmartin We have seen a similar feature in other chat solutions, we will investigate the effort required for it. Taking it as an investigation ticket for the next sprint.
