### ISSUE TITLE
Captured data via widget (name/other)

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1059]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
As well as ask the users email, their name too to avoid the random names that CW assigns.

Expanding this further, would be good to capture additional data which could be set per inbox. Custom datafields; inputs; dropdown; text area etc.

**Describe alternatives you've considered**
None

**Comment by pranavrajs** [comment]
@iammattmartin As per the conversation we already had, we would be creating a question-answer bot which can be configured with custom questions and create workflows.

**Comment by PaoloC68** [comment]
It seems to me that this is tightly connected with #1131 ,the issues could merge

**Comment by nithindavid** [comment]
Closing this issue as we have now pre-chat forms to do this.
