### ISSUE TITLE
whatsapp channel - selfhosted pdf filename wrong

### ISSUE THREAD

**Issue by davides93** [chatwoot/chatwoot#10602]
### Describe the bug

In a WhatsApp channel conversation, when a user sends a named PDF file, the resulting filename is appended with an incorrect string “-filename*=“. This string should be removed during file download to enable opening the file in a PDF application. 
<img width="501" alt="image" src="https://github.com/user-attachments/assets/631af0a2-6496-4ab3-b4ba-5e1476f50174" />

### To Reproduce

1. Chatwoot v3.15
2. Configure WhatsApp channel
3. Send a named PDF file to the WhatsApp channel
The uploaded PDF will result in the appended string.

### Expected behavior

The PDF file should be named exclusively with the `.pdf` extension, devoid of any other strings. This ensures that upon downloading the file, I can directly open it without any additional steps.

### Environment

Kubernetes

### Cloud Provider

Azure

### Platform

Browser

### Operating system

MacOS

### Browser and version

Chrome

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/issues/10527 : please feel to reopen if you are using the official build

**Comment by jmelati** [comment]
I have the same problem, using cloud api. I already sent a video demonstrating the problem.
https://github.com/chatroot/chatroot/issues/10527

I installed a new version of chatwoot on a new machine (direct installation in VM) and the error was reproduced.
