### ISSUE TITLE
[CW-1718] chore: Inline images are shown as attachments in email Channel

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1063]
Inline images in the email are shown
<img width="356" alt="Screenshot 2020-07-19 14 40 39" src="https://user-images.githubusercontent.com/2246121/87871476-2f2ac700-c9ce-11ea-90be-29dc2a49a855.png">
 as attachments. It would good to display it inline.

<sub>[CW-1718](https://linear.app/chatwoot/issue/CW-1718/chore-inline-images-are-shown-as-attachments-in-email-channel)</sub>

**Comment by sojan-official** [comment]
ref: https://discord.com/channels/647412545203994635/650257251856285707/1105570723638030529

**Comment by pranavrajs** [comment]
Closing this as the issue is fixed already in the latest versions.
