### ISSUE TITLE
Private Note image (or attachment) message is sent to user

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#1073]
**Describe the bug**
When making a private note in the form of an image or other type of attachment, that message is actually sent to the user as well (observed in Widget and WhatsApp channels)!

**To Reproduce**
1. Start a chat from widget or WhatsApp.
2. On Dashboard reply box, switch to Private Note.
3. Select an attachment and send it.

**Expected behavior**
The user will be able to receive that message as well.

**Additional context**
Private notes of all kind should be prevented from reaching users.

**Comment by pranavrajs** [comment]
@WevrLabs Can reproduce this issue, we will provide a hot fix for this issue.

**Comment by pranavrajs** [comment]
This was closed via #1084
