### ISSUE TITLE
[Enhancement] disable sending out "New messages email notification" if the user already read the message in widget

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#1075]
**Is your enhancement request related to a problem? Please describe.**
The observed behavior is that if the agent is the last one to send a message or a reply, the outbound email notification is triggered after a short moment to the user, even though the user may have already read the message in the chatbox, which I believe there's no need to still send out an email notification in this case.

**Describe the solution you'd like**
Disabling the New messages email notification in case the user already read the messages in the chatbox.

**Additional context**
It can cause some confusion to the user, as sometimes if they reply in the chatbox after the email went out, we get the same reply again when they check their email later.

**Comment by pranavrajs** [comment]
@WevrLabs You are right, we are not considering the user_last_seen_at attribute before sending the email. We will take this as an enhancement.
