### ISSUE TITLE
Bug: Wrong directory for volumes in docker compose

### ISSUE THREAD

**Issue by mr-karan** [chatwoot/chatwoot#1080]
**Describe the bug**

[Here](https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml#L47) the path specified for Postgres data is `/data/postgres` which is some random path. Since `PGDATA` variable is unchanged, the path where data should actually be: `/var/lib/postgresql/data`.

Edit: While creating the above issue, I noticed the `Redis` path is wrong as well. According to [docs](https://hub.docker.com/_/redis) it should be `/data` and not `/data/redis` as specified [here](https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml#L57).

**Comment by pranavrajs** [comment]
@sony-mathew / @vishnu-narayanan Can you guys please take a look at this?

**Comment by mr-karan** [comment]
I guess this can be closed now :)
