### ISSUE TITLE
[Bug] (Conversation Continuity) Email replies do not parse Arabic or UTF characters correctly.

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#1081]
**Describe the bug**
When a user replies back to a conversation via email, if for example they use the Arabic language or put some emojis, it seems they are not interpreted correctly and show as "?????? ???? ????" instead.

**To Reproduce**
Steps to reproduce the behavior (Assuming Conversation Continuity is already enabled and set):
1. Initiate a conv. from chatbox and provide email for the bot.
2. Send a message and close the chatbox.
3. Go to the Dashboard as an agent and reply to that conversation after a few minutes.
4. As a user, check the email inbox for the "New messages on this conversation" notification message.
5. Reply to it using emojis or Arabic text.
6. See error on Dashboard.

**Expected behavior**
The agent will receive the reply from the user in the form of question marks "??? ?????? ???".

**Screenshots**

![Screen Shot 2020-07-21 at 5 37 36 PM](https://user-images.githubusercontent.com/66124192/88076051-e152c200-cb79-11ea-80df-6ae3ecfd5798.png).

**Comment by pranavrajs** [comment]
We know what we were getting into 😁. That's why we put it under a feature flag. This must be something to do with the encoding in the plain text version of the email. @WevrLabs Can you send a similar content which broke the UI to hello@chatwoot.com

**Comment by WevrLabs** [comment]
> We know what we were getting into 😁. That's why we put it under a feature flag. This must be something to do with the encoding in the plain text version of the email. @WevrLabs Can you send a similar content which broke the UI to [hello@chatwoot.com](mailto:hello@chatwoot.com)?

Noted 👍🏼. Will send you a test message in a bit.

**Comment by WevrLabs** [comment]
Update (new observations):
Not sure if it's the intended behavior, but I noticed if a user replies back without quoting the previous messages, then we receive an empty reply on the Dashboard.
