### ISSUE TITLE
Error Installer on Caprover

### ISSUE THREAD

**Issue by kang28ivan** [chatwoot/chatwoot#1083]
Hi, 
I am a new user who has just tried chatwoot.
I do not know whether this is a bug or not, but I have tried several times to install on the caprover it always fails with logs like this.

> 2020-07-22T12:18:03.349535868Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] 
> 2020-07-22T12:18:03.349562468Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] app/models/installation_config.rb:20:in `block in <class:InstallationConfig>'
> 2020-07-22T12:18:03.349575257Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] lib/global_config.rb:41:in `db_fallback'
> 2020-07-22T12:18:03.349627225Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] lib/global_config.rb:32:in `load_from_cache'
> 2020-07-22T12:18:03.349658165Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] lib/global_config.rb:12:in `block in get'
> 2020-07-22T12:18:03.349667182Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] lib/global_config.rb:11:in `each'
> 2020-07-22T12:18:03.349675743Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] lib/global_config.rb:11:in `get'
> 2020-07-22T12:18:03.349684331Z [877fc0d3-e31f-42cf-8117-288a6d0d89df] app/controllers/dashboard_controller.rb:11:in `set_global_config'
> 2020-07-22T12:30:52.554880778Z I, [2020-07-22T12:30:52.554411 #1] INFO -- : [692a3296-1ce1-49d9-816c-84277a163865] Started GET "/" for 180.253.116.219 at 2020-07-22 12:30:52 +0000
> 2020-07-22T12:30:52.560763599Z I, [2020-07-22T12:30:52.560518 #1] INFO -- : [692a3296-1ce1-49d9-816c-84277a163865] Processing by DashboardController#index as HTML
> 2020-07-22T12:30:52.603037913Z I, [2020-07-22T12:30:52.602844 #1] INFO -- : [692a3296-1ce1-49d9-816c-84277a163865] Completed 500 Internal Server Error in 42ms (ActiveRecord: 18.0ms | Allocations: 2258)
> 2020-07-22T12:30:52.606482959Z F, [2020-07-22T12:30:52.606264 #1] FATAL -- : [692a3296-1ce1-49d9-816c-84277a163865] 
> 2020-07-22T12:30:52.606510318Z [692a3296-1ce1-49d9-816c-84277a163865] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR: relation "installation_configs" does not exist
> 2020-07-22T12:30:52.606521175Z LINE 8: WHERE a.attrelid = '"installation_configs"'::regclass
> 2020-07-22T12:30:52.606550292Z ^
> 2020-07-22T12:30:52.606561352Z ):
> 2020-07-22T12:30:52.606570688Z [692a3296-1ce1-49d9-816c-84277a163865] 
> 2020-07-22T12:30:52.606580077Z [692a3296-1ce1-49d9-816c-84277a163865] app/models/installation_config.rb:20:in `block in <class:InstallationConfig>'
> 2020-07-22T12:30:52.606590243Z [692a3296-1ce1-49d9-816c-84277a163865] lib/global_config.rb:41:in `db_fallback'
> 2020-07-22T12:30:52.606599803Z [692a3296-1ce1-49d9-816c-84277a163865] lib/global_config.rb:32:in `load_from_cache'
> 2020-07-22T12:30:52.606609130Z [692a3296-1ce1-49d9-816c-84277a163865] lib/global_config.rb:12:in `block in get'
> 2020-07-22T12:30:52.606637129Z [692a3296-1ce1-49d9-816c-84277a163865] lib/global_config.rb:11:in `each'
> 2020-07-22T12:30:52.606646787Z [692a3296-1ce1-49d9-816c-84277a163865] lib/global_config.rb:11:in `get'
> 2020-07-22T12:30:52.606656039Z [692a3296-1ce1-49d9-816c-84277a163865] app/controllers/dashboard_controller.rb:11:in `set_global_config'

Is there something wrong with the installation? because I only use one click installer from Caprover

Thank you

**Comment by pranavrajs** [comment]
@kang28ivan Can you please try v1.6.3 in version field and see if the error is still there?

<img width="541" alt="Screenshot 2020-07-22 at 6 59 40 PM" src="https://user-images.githubusercontent.com/2246121/88182183-81c5e680-cc4d-11ea-9a8d-8fb0907cf30d.png">

**Comment by kang28ivan** [comment]
> @kang28ivan Can you please try v1.6.3 in version field and see if the error is still there?
> 
> <img alt="Screenshot 2020-07-22 at 6 59 40 PM" width="541" src="https://user-images.githubusercontent.com/2246121/88182183-81c5e680-cc4d-11ea-9a8d-8fb0907cf30d.png">

I already try install from v1.6.0 up to v1.6.3 still same error
I do not understand what is causing the error because the logs only get messages like the one above

is there an easy way to install ubuntu vps?

Thank you.

**Comment by kang28ivan** [comment]
Eh, is working now on v1.6.3 before I installed it did not work and an error and now I can't login with  'john@acme.inc' and '123456'
what is the default email and password?

**Comment by pranavrajs** [comment]
@kang28ivan You can signup for a new account. Closing this ticket as it is resolved.
