### ISSUE TITLE
would like to add an api  to set nicknames for customers 

### ISSUE THREAD

**Issue by CL545740896** [chatwoot/chatwoot#1086]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by pranavrajs** [comment]
Does this doc help? 
https://www.chatwoot.com/docs/website-sdk#to-set-the-user-in-the-widget

**Comment by CL545740896** [comment]
Yes  Nice
