### ISSUE TITLE
Maybe It can  add  a input  to  search keyword of chat msg 

### ISSUE THREAD

**Issue by CL545740896** [chatwoot/chatwoot#1089]
**Is your enhancement request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by CL545740896** [comment]
And  Then , we can setting the chat widgets  height  and  width  in sdk , is friendly

**Comment by sojan-official** [comment]
The ability to search messages is available in chatwoot now 
![Screenshot 2021-12-11 at 12 31 55 AM](https://user-images.githubusercontent.com/73185/145627738-dc4f8ee8-6ed7-4fe5-96f4-e2a3ee222d7c.png)
