### ISSUE TITLE
Inbox tree sorting

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1098]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently if you have lots of Inboxes, there is no sort order to them which can make management difficult. It would be nice to be able to group them by type (i.e facebook), or alphabetically... or even custom sort order (i.e we'd group them in brands).

**Comment by sojan-official** [comment]
@iammattmartin is it for the inbox management page or where its shown on the sidebar?

**Comment by iammattmartin** [comment]
This was referring to the side panel but I guess if you're applying a sort, it may as well just be used on both pages for consistency.

**Comment by pranavrajs** [comment]
I think we can start with sort the alphabetical order and work from there.

**Comment by calebjacobson** [comment]
I installed the self-hosted server and configured multiple inboxes. I am only seeing the inboxes sorted in the order that they were created (both the inbox management page and the sidebar). Am I missing something?
