### ISSUE TITLE
Docker documentation is unclear

### ISSUE THREAD

**Issue by rocketkittens** [chatwoot/chatwoot#1099]
The documentation for this project is poor, which is really unfortunate it looks good based on the screenshot and i like open source. However, i spent two nights trying to start the app and now i'm giving up until there is an improvement in the documentation for this project.

Hope to contribute in the future if i can get the app to run.

**Comment by sojan-official** [comment]
@rocketkittens could you detail what errors prevented you from getting the app to run?  are you trying out to run the app in your local machines or on a VM for production? 

to try it out in local you could use : https://www.chatwoot.com/docs/installation-guide-docker#production-environment 
```
docker-compose -f docker-compose.production.yaml build
```

we are also available on discord if you need support getting it to run https://discord.gg/cJXdrwS

**Comment by rocketkittens** [comment]
I'll give it another shot and try to provide details, give me some time, and thank you for providing the resources.

**Comment by milansimek** [comment]
One thing I noticed is the following:

There are two sets of instructions regarding deploying using docker:

1. https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker
2. https://www.chatwoot.com/docs/installation-guide-docker#production-environment

However, it seems deployment should be done using this docker compose file:

https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml

This file isn't mentioned in the documentation anywhere. Maybe this causes confusion?

**Comment by sojan-official** [comment]
updated https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker with further instructions. We will continue working on improving the documentation further
