### ISSUE TITLE
This project is interesting I want to contribute to it

### ISSUE THREAD

**Issue by shaharyar-shamshi** [chatwoot/chatwoot#1116]
This project is very much interesting and I want to contribute to it as open source developer can anybody help me with code walkthrough for better understanding

**Comment by sojan-official** [comment]
@shaharyar-shamshi  Thanks a lot for your interest in contributing to Chatwoot. We don't have a code walkthrough video at the moment, its something which we are working on. 

But you can get started right away if you have some experience in Ruby on Rails & Vue.js.

If you are new to either of those, the following links should help you get started.
https://vuejs.org/v2/guide/
https://www.learnenough.com/ruby-on-rails-4th-edition-tutorial/beginning

You can start picking up small issues, even while you are learning. Our team will be happy to give review comments and feedback.

## How to get started?

- Set up Chatwoot in your local machine : https://www.chatwoot.com/docs
- Play around and get used to the functionality. 
- Look through the GitHub issues to see if there is anything you feel confident to work on : https://github.com/chatwoot/chatwoot/issues
   - Post a comment on the issue and a team member will assign it to you, with further instructions.
- You can always reach out to the team on discord if you need help finding issues to work on or have any questions. : https://discord.gg/cJXdrwS - Feel free to report bugs as new issues on GitHub. 
 
Let us know if you need any further help
