### ISSUE TITLE
BrowserslistError: Unknown browser query `android all`

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#112]
- [ ] Fix the warnings shown in console output. Please see the attached screenshot.

<img width="860" alt="Screenshot 2019-10-05 16 42 40" src="https://user-images.githubusercontent.com/2246121/66252509-26df0380-e78f-11e9-9c9a-1f77f15b95fd.png">

**Comment by nisusam** [comment]
@pranavrajs This issue also mentioned here

https://github.com/browserslist/browserslist/issues/382

we have to perform `yarn upgrade` to resolve this issue

**Comment by pranavrajs** [comment]
@nisusam Thanks for looking into this issue, I can't blindly use `yarn upgrade` as it might break other packages. `browserslist` is not a dependency which is in `package.json`, the work would be to figure out the packages using `browserslist` and upgrade it to an acceptable version.

If you `yarn list`, you can see there are multiple packages which is using it 

```bash
➜ chatwoot git:(master) ✗ yarn list | grep browserslist
│  ├─ browserslist@^4.6.0
│  ├─ browserslist@^4.6.1
│  ├─ browserslist@^3.2.6
│  ├─ browserslist@3.2.8
├─ browserslist@4.6.3
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.6.2
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.4.2
│  ├─ browserslist@^4.0.0
│  ├─ browserslist@^4.0.0
```

**Comment by nisusam** [comment]
> I can't blindly use `yarn upgrade` as it might break other packages.

@pranavrajs Agreed.

**Comment by pranavrajs** [comment]
Closing as it is no longer an issue.
