### ISSUE TITLE
Chat history from $chatwoot.setUser()

### ISSUE THREAD

**Issue by danirolopes** [chatwoot/chatwoot#1120]
**Is your enhancement request related to a problem? Please describe.**
I don't if this is a bug or an enhancement, but...

I'm trying to use the $chatwoot.setUser function on the website SDK.
As you say in the docs, I do use $chatowoot.reset every time the user logs out.

But, when the user logs in again, the chat history is lost for him. Is this the intended behavior (the conversation is only available by email)? Or there is an way to retrieve the conversation history from the user via the setUser?

**Describe the solution you'd like**
I think the user should have access to the chat history when I call the setUser method

**Comment by pranavrajs** [comment]
@danirolopes Yes, this is the current behaviour we would make necessary changes to see resume the previous session.

**Comment by adamsvystun** [comment]
I see that this feature was not included in v1.8.0, will this be replanned for future releases?

**Comment by sojan-official** [comment]
@adamsvystun  if you implement the HMAC authentication, chat history will be persisted across the session 

https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#identity-validation-using-hmac
