### ISSUE TITLE
Display location, IP of the user who have initiated the conversation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1122]
- Display location (Place, Country)
- Display IP address on the sidebar

**Comment by rjroot** [comment]
Would be great to include active users on sites/properties, their current page if that help us push a notification (trigger). Can it also include referrer info?
Features such as daily,weekly,monthly visitor count,page view count can be pushed at some later stage if devs permit.

**Comment by pranavrajs** [comment]
Moving this v1.9.x to research more about GDPR implications.
