### ISSUE TITLE
Deploy to Heroku using Docker images

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1126]
Right now the Heroku deployment is following traditional Rails App deployment pattern, one of a couple of drawbacks for this approach is that the build process has to pull all the dependencies and compile it every time a new user is deploying the application. This is not required. As the same release is being deployed by everyone, it doesn't make sense to ask the users to wait until the compilation is complete.

As an alternative, I suggesting to investigate the deployment with Docker images https://devcenter.heroku.com/categories/deploying-with-docker so that prebuilt images are available for the users.

**Comment by nithindavid** [comment]
@vishnu-narayanan Can you please have a look at this and see if we can close this issue?

**Comment by pranavrajs** [comment]
Closing this as we can revisit it later.
