### ISSUE TITLE
Hide Empty Inbox

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1127]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Where you have a few (20+ Inboxes), these crowd the left hand panel, even when they may all be empty. An option to hide those inboxes which have no active messages would make things a bit more streamlined.

**Describe alternatives you've considered**
None

**Comment by pranavrajs** [comment]
@iammattmartin This is a good suggestion.

**Comment by pranavrajs** [comment]
@iammattmartin Closing this as #6309 solve the sidebar challenges and it would cover this issue as well.
