### ISSUE TITLE
Feature: Display Online Status, response time on the widget

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1132]
### Problem

In the current widget view, team availability is shown as a toast and there is no information about the time people will take to reply.

### Solution

- Remove the existing message input box and show an agent availability along with the response time.

### Acceptance criteria

- Add a DB field for the user to choose the response time
  - Replies in a few minutes
  - Replies in a few hours
  - Replies within a day

- Display the list of online agents and the response time text.
- Remove the input box for the message, introduce a button which says send a message.

### Design

<img src="https://user-images.githubusercontent.com/2246121/89739418-2e052b00-da9e-11ea-9f02-5a679c6dca2f.png" width="500" />

**Comment by CL545740896** [comment]
i hope it can coming soon

**Comment by pranavrajs** [comment]
@CL545740896 This would part of 1.8.1 release.
