### ISSUE TITLE
Default Locale not set

### ISSUE THREAD

**Issue by converso-chat** [chatwoot/chatwoot#1135]
**Describe the bug**
Hello! Shouldn't the "LANG" variable in Heroku's "Config Vars" set the default language I select? I replaced en_US.UTF-8 with pt_BR.UTF-8 and did not change it. Am I doing it wrong or is there another way to set the default language?

Thanks

**Comment by pranavrajs** [comment]
@converso-chat Can you please more info about this. Please share a screenshot or the page where you are facing the issue. Also please add the steps you have done.

**Comment by converso-chat** [comment]
Hello. As a post here from GIT I changed and Heroku the LANG variable, as shown in the image. However, in English, I would like to use Brazilian Portuguese as the default language. aA purpose, I am updating the language pt_br and I will post next, the language of the mobile app has already translated 100% and I will also post

Thanks

![image](https://user-images.githubusercontent.com/64017660/89935160-1c2f9f00-dbe8-11ea-8788-a413fb62443f.png)

**Comment by sojan-official** [comment]
@converso-chat  at the moment we don't have the ability to change the language of chatwoot at the installation level. 
We are working on this capability over  https://github.com/chatwoot/chatwoot/issues/830
