### ISSUE TITLE
Routing Error. No route matches [GET] "/monitoring/sidekiq"

### ISSUE THREAD

**Issue by nelajc** [chatwoot/chatwoot#1139]
**Routing Error. No route matches [GET] "/monitoring/sidekiq"**
I tried to setup chatwoot using docker and surely followed all the steps but unable to access sidekiq on,
http://0.0.0.0:3000/monitoring/sidekiq

**To Reproduce**
1. Access Rail App http://0.0.0.0:3000 (**good**)
2. Access Mailhog http://0.0.0.0:8025 (**good**)
3. Access Sidekiq http://0.0.0.0:3000/monitoring/sidekiq (**routing error**)
4. Access Sidekiq http://0.0.0.0:3000/sidekiq (**routing error**)
5. Add SIDEKIQ_AUTH_USERNAME and SIDEKIQ_AUTH_PASSWORD in .env (**still routing error**)

**Expected behavior**
Should be able to access sidekiq

**Screenshots**
![image](https://user-images.githubusercontent.com/46435602/90006438-70f81600-dccb-11ea-8e36-9a5c8030c493.png)
![image](https://user-images.githubusercontent.com/46435602/90006506-99801000-dccb-11ea-8888-ba6cdbb96d00.png)

**Comment by sojan-official** [comment]
@nelajc could you let us know where you find the instructions `Add SIDEKIQ_AUTH_USERNAME and SIDEKIQ_AUTH_PASSWORD in .env (still routing error)` 

In the latest versions of chatwoot, sidekiq access was moved to our super admin area

1) In your rails console type the following to create a super admin
```
s = SuperAdmin.new(email: "admin@xyc.com", password: "yourpassword")
```
2) Access yourchatwoot.com/super_admin 
3) authenticate and you can find sidekiq option on the sidebar

**Comment by nelajc** [comment]
Hi @sojan-official 

that SIDEKIQ_AUTH_USERNAME and SIDEKIQ_AUTH_PASSWORD, I found it in here [https://github.com/chatwoot/chatwoot/issues/431](url)

1. unable to see the rails console.
2. i was able to access that page but when I enter the super admin credentials it will just load the page.
3. answer's in number 2.

**Comment by sojan-official** [comment]
@nelajc  that was instructions for the older version, please ignore that. 

1. how did you try to access the rails console ? 
2. we don't create a super admin by default, so the credentials will only work after you create the user via rails console.

**Comment by nelajc** [comment]
@sojan-official 

hmmm rails console not on installation guide. can give me step by step on how to do it?

**Comment by pranavrajs** [comment]
@nelajc 

1. Open the directory where Chatwoot code is available. 
2. Run `bundle exec rails console`. If you are running on production mode, `RAILS_ENV=production bundle exec rails console`
3. You should be able to run the command specified in the comment above.

**Comment by jensonpaul** [comment]
I have the Chatwoot installed using CapRover on Ubuntu 20.04. It is working fine.
Just need to access the super_admin. How do I access the rails console?

**Comment by sojan-official** [comment]
@jensonpaul  access the server you have caprover running in 
run `docker exec -it $(docker ps --filter name=srv-captain--chatwoot-web -q) /bin/sh`

this will let you access to the container where you are running chatwoot-web service.
make sure to change `chatwoot-web` if you are running the container under a different name. 

now you have use the instructions posted by @pranavrajs  in earlier comment to get the console up and running

**Comment by nelajc** [comment]
> @nelajc
> 
> 1. Open the directory where Chatwoot code is available.
> 2. Run `bundle exec rails console`. If you are running on production mode, `RAILS_ENV=production bundle exec rails console`
> 3. You should be able to run the command specified in the comment above.

Hi @pranavrajs .
on number 2.. i am running chatwoot using docker, what container should I execute that command. we have a total of 7 containers in chatwoot docker. is this container named webpack on your github repository compose? [https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.yaml](url)

**Comment by nelajc** [comment]
**FIXED:**

instead of:
`s = SuperAdmin.**new**(email: "admin@xyc.com", password: "yourpassword")`

I used:
`s = SuperAdmin.**create**(email: "admin@xyc.com", password: "yourpassword")`

you can list super admins that was successfully created using:
`SuperAdmin.all`
