### ISSUE TITLE
Chore: Explore using latest Twitter APIs(V2)

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1140]
Explore how to leverage the latest Twitter v2 APIs to improve the Twitter experience on Chatwoot.

https://developer.twitter.com/en/products/twitter-api/early-access/guide#rollingout

**Comment by tejaswinichile** [comment]
#3777 Will be updated with this changes.

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
