### ISSUE TITLE
subpath no work

### ISSUE THREAD

**Issue by xpayserver** [chatwoot/chatwoot#1143]
**Describe the bug**
Cannot use chatwoot on subpoath of domain (xyz.com/support) 

I have configure nginx to rewrite url from subpath to container (https://github.com/xpayserver/btcpayserver-docker/blob/a/Production/nginx.tmpl#L99)
and also configure frontend url env var to have full path (https://github.com/xpayserver/btcpayserver-docker/commit/4723c02f005b6f4c6caac5adcf04100490c66de5#diff-041e5b6d1a178df181b5490a717537b2)
but still issue (https://xpayserver.com/chatwoot/) where asset load from root instead of correct path

**Comment by sojan-official** [comment]
Chatwoot is designed with the expectation that it will be run on a dedicated root domain/subdomain. Features are built with that expectation. 
So running it in a subpath is not something we are looking into at the moment.
