### ISSUE TITLE
Postgres on other than 5432 port doesn't work

### ISSUE THREAD

**Issue by markopolojarvi** [chatwoot/chatwoot#1145]
**Describe the bug**
I have an external Postgres database which uses non-standard port. Chatwoot doesn't seem to have an option to set custom port for Postgres. If I set IP:CUSTOM_PORT as POSTGRES_HOST, Chatwoot will attempt to connect to IP:CUSTOM_PORT:5432.

**To Reproduce**
1. Try to setup Postgres with custom port.

**Expected behavior**
Chatwoot should either parse POSTGRES_HOST and understand it's a non-standard port, or there should be POSTGRES_PORT env.

**Comment by pranavrajs** [comment]
@markopolojarvi You can make use of the `DATABASE_URL` env variable instead of setting `POSTGRES_USERNAME`, `POSTGRES_HOST` and `POSTGRES_PASSWORD`

This was missing in the documentation. I've added it via #1146. 

Please let us know if that works.

**Comment by markopolojarvi** [comment]
Something is still a bit wonky. I'm not sure if it's user error or the code ;)

```
chatwoot-worker_1  | + echo 'Waiting for postgres to become ready....'
chatwoot-worker_1  | + PGPASSWORD=
chatwoot-worker_1  | + PSQL='pg_isready -h  -p 5432 -U '
chatwoot-worker_1  | + pg_isready -h -p 5432 -U
chatwoot-worker_1  | Waiting for postgres to become ready....
chatwoot-worker_1  | pg_isready: option requires an argument: U
chatwoot-worker_1  | Try "pg_isready --help" for more information.
chatwoot-worker_1  | + sleep 2
```

It looks like it's not reading DATABASE_URL at all.

**Comment by pranavrajs** [comment]
@markopolojarvi  Can you share the config you are using?

**Comment by markopolojarvi** [comment]
Docker ENVs:

```
environment: 
  - MAILER_SENDER_EMAIL=team@foobar.com
  - SMTP_ADDRESS=smtp.mailgun.org
  - SMTP_AUTHENTICATION=plain
  - SMTP_DOMAIN=mg.foobar.com
  - SMTP_ENABLE_STARTTLS_AUTO=true
  - SMTP_PORT=587
  - SMTP_USERNAME=chatwoot@mg.foobar.com
  - SMTP_PASSWORD=xxx
  - FRONTEND_URL='https://chat.foobar.com'
  - ACTIVE_STORAGE_SERVICE='local'
  - REDIS_URL='redis:://chatwoot-redis:6379'
  - DATABASE_URI=postgresql://foobar-chatwoot:xxx@1.2.3.4:5443/foobar-chatwoot
  - RAILS_ENV=production
  - SECRET_KEY_BASE=xxx
  - LOG_LEVEL=info
  - LOG_SIZE=1024
```

**Comment by pranavrajs** [comment]
@markopolojarvi 

It should `DATABASE_URL` not `DATABASE_URI`

**Comment by markopolojarvi** [comment]
Ah, sorry, it was that originally. I just tested it with URI to see if there was a typo somewhere and I left it. Still doesn't work with DATABASE_URL.

**Comment by pranavrajs** [comment]
That's weird. Let us see if you have correct config. Attached below is a sample config for production use. 

You would be able to see 2 containers running the same base image with a different command. One for the actual app and another one for the SideKiq(worker). Are you sure that the same config is set for both rails and sidekiq containers?

https://github.com/chatwoot/chatwoot/blob/f5374e0cd9dc45fe8ab08c37514cb17b2e356ec5/docker-compose.production.yaml#L8-L30

**Comment by markopolojarvi** [comment]
Looks about right. I created two containers based on instructions at https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker and everything is running on top of them. Both are using same envs.

**Comment by pranavrajs** [comment]
@markopolojarvi Let me quickly run with this config and see if there is any error.

**Comment by quacktacular** [comment]
I modified my `rails.sh` and it appears to be working now:
```
if [ -z "$DATABASE_URL" ]; then
  PGPASSWORD=$POSTGRES_PASSWORD
  PSQL="pg_isready -h $POSTGRES_HOST -p 5432 -U $POSTGRES_USERNAME"
else
  PSQL="pg_isready -d $DATABASE_URL"
fi
```

**Comment by pranavrajs** [comment]
@quacktacular This is a good find. Can you raise a PR? I can work on top of this. Looks like there might be one more place we need to make this change

**Comment by pranavrajs** [comment]
Closing as #1147 is merged.
