### ISSUE TITLE
SMTP Notification on Heroku Deploy

### ISSUE THREAD

**Issue by angelosorno** [chatwoot/chatwoot#1148]
Hi, we're try to deploy the latest version on Heroku many times, but i don't understand, why the notification for a new account for agent don't run. We put the SMTP credential (SES by Amazon) like the tutorial. I don't know if AWS SES it's diferent that:

MAILER_SENDER_EMAIL=_email-smtp.us-east-1.amazonaws.com_
SMTP_ADDRESS=mail@domain.com
SMTP_USERNAME=******
SMTP_PASSWORD=******

This is our deploy on Heroku. https://fimlm-chat.herokuapp.com/app/login

Many thanks, for your comments.

**Comment by pranavrajs** [comment]
@angelosorno Under your resources tab in Heroku app, you will be able to see 2 dynos. 
1. Web
2. Worker

<img width="1252" alt="Screenshot 2020-08-15 at 12 01 40 PM" src="https://user-images.githubusercontent.com/2246121/90306897-163f0400-deef-11ea-9f0c-cfc68ca0226c.png">

Can you confirm whether both Dynos are "ON"?

**Comment by angelosorno** [comment]
Worker it's turn off
![imagen](https://user-images.githubusercontent.com/54144166/90307120-24facc00-de99-11ea-8be6-8a3504d66d43.png)

**Comment by pranavrajs** [comment]
@angelosorno Please turn on the worker, everything should work fine.

**Comment by pranavrajs** [comment]
@angelosorno Closing this, for now, feel free to re-open if this does not fix your issue.

**Comment by angelosorno** [comment]
Sr. Prana, really thank you.

![imagen](https://user-images.githubusercontent.com/54144166/90307185-a6eaf500-de99-11ea-9249-e3f76c8d8017.png)

All it's all right
