### ISSUE TITLE
how can i get the doc about  via  api channel ?

### ISSUE THREAD

**Issue by CL545740896** [chatwoot/chatwoot#1150]
**Describe the bug**
i want to know what different  about  webhook  ang  via api  inbox channel ?
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@CL545740896 We don't docs around API Channel, we will try to write one by this weekend.
