### ISSUE TITLE
Twitter generating Conversations for blocked users

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1154]
**Describe the bug**
If a blocked user tweets your @username, this is converted to a new conversation. Usually on Twitter, you would not expect to see this at all. You would not know it happened.

Even if you reply, they will not see the message either.

**To Reproduce**
Block @username
Tweet from that username to a username in your CW installation
New conversation appears from that username.

**Expected behavior**
I would imagine the expected behaviour would be more like twitter.com or your twitter client in that no message appears from a blocked user at all.

It is possible this is due to how the results are implemented from search. In which case, it may be pertinent to show a users blocked status in the CW interface, i.e at the top of the message or in the user card... "the user is blocked" etc.

Adding scope, ability to block a user from CW could be useful in situations that warrant it and likewise, unblocking them could be useful too.

**Comment by pranavrajs** [comment]
@iammattmartin I did a little bit researching and found that there is a field `user_has_blocked` to see if a blocked user mentions the account. We could build this enhancement.

> https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/subscribe-account-activity/faq
> 
> **If a blocked user mentions my subscribed user, how can I identify this?**
>
> You will see a boolean field `user_has_blocked` on the top level of the json response, set to either “true” or “false". This field will only be exposed on Tweet mentions.
