### ISSUE TITLE
Reviewing resolved conversations causes too much memory usage

### ISSUE THREAD

**Issue by quacktacular** [chatwoot/chatwoot#1162]
**Describe the bug**
When I navigate to Conversations > All and select "Resolved" the request takes over 10 seconds and a memory usage spike of over 512mb occurs. Request is to: `https://my_chatwoot_instance.com/api/v1/accounts/1/conversations?status=resolved&assignee_type=all&page=1`

In my case I run 10 replicas of Chatwoot in an ECS cluster, each task with a 512mb memory limit. This request causes the container to run out of memory (OOM) and die. 

**To Reproduce**
1. Setup Chatwoot instance with Docker (512mb memory limit, resolve at least 30 conversations)
2. Go to Conversations
3. Click on 'All'
4. Select 'Resolved' from the dropdown
5. See container OOMs

**Expected behavior**
> Set of resolved conversations are returned and displayed in UI
> Clicking load more loads older conversations

**Additional context**
I expect the query on conversations route just needs to be optimized. It's probably selecting too much information so RAM usage balloons.

**Comment by nithindavid** [comment]
@quacktacular  I'm closing this issue as there is no response. Please feel free to reopen if you want to continue the conversation.
