### ISSUE TITLE
Facebook 24 hour reply restriction

### ISSUE THREAD

**Issue by dixytudla** [chatwoot/chatwoot#1170]
I every one! 

Just curious if the Facebook 24 hour reply restriction is absolutely necessary? I asked cause I don't recall seeing it in the past versions. I only saw it when I upgraded to v1.7.2. I was on the developer version for a while. 

Thanks in advance for the replies!

**Comment by sojan-official** [comment]
It's a Facebook platform restriction that we have to adhere to https://developers.facebook.com/docs/messenger-platform/policy/policy-overview/

In the previous version, we weren't showing the notice but the messages sent after 24-hour window might get discarded at the messenger side. We wanted to ensure chatwoot users understand this caveat.
