### ISSUE TITLE
Dialogflow Integration

### ISSUE THREAD

**Issue by converso-chat** [chatwoot/chatwoot#1171]
**Is your enhancement request related to a problem? Please describe.**
Hello. I set up a greeting message for Twilio's WhatsApp channel, but it is not sent when starting a conversation. Another question is whether we can integrate a platform like Dialogflow, Watson for Chatbots.

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by pranavrajs** [comment]
@converso-chat There are 2 items mentioned in this issue

1. Hello. I set up a greeting message for Twilio's WhatsApp channel, but it is not sent when starting a conversation

This looks like a bug. Can you confirm whether the greeting message is not sent in Whatsapp conversation?

2. Another question is whether we can integrate a platform like Dialogflow, Watson for Chatbots.

This is possible with Agentbots concept. Please take a look at https://www.youtube.com/watch?v=KE4nKgepO_k
Native integration to existing popular Chatbot platforms is in consideration.

**Comment by converso-chat** [comment]
Really the greeting messages are not sent to Twilio / WhatsApp. As for Rasa my installation is in Heoku, I will install a place to try the BOT works. Thank you.

**Comment by pranavrajs** [comment]
@converso-chat I tried looking at the greeting message and it is sent correctly to the user.

<img width="501" alt="Screenshot 2020-09-11 at 12 46 48 PM" src="https://user-images.githubusercontent.com/2246121/92881971-1cac9700-f42d-11ea-96a5-175ce78809ff.png">

**Comment by sandys** [comment]
we would be highly interested in dialogflow integration as well

**Comment by pranavrajs** [comment]
@sandys @converso-chat Here is a document on the recently shipped native Dialogflow integration https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow
