### ISSUE TITLE
Widget not showing german locale de, all other yes

### ISSUE THREAD

**Issue by jensJJ** [chatwoot/chatwoot#1176]
**Describe the bug**
Widget not showing german locale de, all other yes
Using 'de' (german) locale doesn't switch to german.

**To Reproduce**

```
<script>

  (function(d,t) {
      window.chatwootSettings = {
  hideMessageBubble: false,
  position: 'left', // This can be left or right
  locale: 'de', // Language to be set
    type: 'expanded_bubble',
  launcherText: 'Chat with us'
};

      var BASE_URL = "https://chatwoot-url.com";
    var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src= BASE_URL + "/packs/js/sdk.js";
    s.parentNode.insertBefore(g,s);
    g.onload=function(){
      window.chatwootSDK.run({
          websiteToken: 'abc123',
        baseUrl: BASE_URL
      })
    }
  })(document,"script");
  
  window.addEventListener('chatwoot:ready', function () {
  window.$chatwoot.setLocale('de');
});
```

1. So I tried fr,es they all work, but not de.
2. login into VM, as chatwoot user
3. ~/chatwoot/app/javascript/widget/i18n/locale/de.json
4. edited the missing translations
5. rake assets:precompile RAILS_ENV=production in the app root
6. systemctl restart chatwoot.target
7. systemctl reload nginx

**Expected behavior**

Should switch  to german and show the new translations

**Environment**

Linux VM 18.04 Ubuntu LTS

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 80.0

**Comment by pranavrajs** [comment]
@jensJJ I can see that there are some translations are missing for German, would you be able to contribute to German here https://translate.chatwoot.com/chatwoot/de?

**Comment by pranavrajs** [comment]
Closing this via #1276
