### ISSUE TITLE
I18n locale is creating abnormal behaviour on SuperAdmin console

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1185]
Super Admin console is not currently set to use i18n files. However, setting I18n.locale on each request creates abnormal behaviour with super admin console. The text used in the console changes erratically.

**Comment by pranavrajs** [comment]
![photo_2020-09-02 16 37 48](https://user-images.githubusercontent.com/2246121/91974038-d6737b80-ed3a-11ea-8200-810b63dc97a7.png)

Irregular i18n locale selection due to caching?

**Comment by sojan-official** [comment]
the mailer issue should be fixed in : https://github.com/chatwoot/chatwoot/pull/1204

**Comment by sojan-official** [comment]
ref: https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests
