### ISSUE TITLE
How to authenticate into api using curl?

### ISSUE THREAD

**Issue by jackflax** [chatwoot/chatwoot#1194]
I've been trying to authenticate into API.  I get the below message, any help would be greatly appreciated!!

{"errors":["You need to sign in or sign up before continuing."]}

I've been using curl/php:

$server = "https://xxxxxxx.xxx";
$accesstoken = "Authorization: Bearer xxxxxxxxxxxapitokenfromprofilexxxxxxxxxxxxx";

$apidata = array("content" => "Test", "message_type" => "outgoing", "private" => true, "content_type" => "text", "content_attributes" => "{}");                                                                    
$datastring = json_encode($apidata);

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => $server."/api/v1/accounts/"5/conversations/3/messages",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => $datastring,
  CURLOPT_HTTPHEADER => array(
    "Content-Type: application/json", $accesstoken
  ),
));

$response = curl_exec($curl);

curl_close($curl);
#echo $response;

**Comment by pranavrajs** [comment]
Please see this section https://www.chatwoot.com/developers/api/#section/Authentication
