### ISSUE TITLE
Make documentation beginner friendly

### ISSUE THREAD

**Issue by manojmj92** [chatwoot/chatwoot#12]
Currently, there is no documentation in the ReadME that can help beginners get started with the project.

There should be documentation on how to run chatwoot in local environment, and this should contain details right from installing `rvm`, installing `postgres` etc.

**Comment by saint739** [comment]
I can't install too.

git clone ...
npm install
apt install imagemagik postgresql postgresql-server-dev-11
bundle 
cp shared/config/database.yml config/database.yml
cp shared/config/application.yml config/application.yml
cp .env.sample .env
#after I create user and db in psql and write it in config/database.yml
rake db:create 
(in /var/www/chatwoot)
rake aborted!
ArgumentError: invalid uri scheme ''

**Comment by pranavrajs** [comment]
@saint739 You must be missing the Redis URL, I've updated the development docs in `docs/development`. You can specify the Redis URL as shown in https://github.com/chatwoot/chatwoot/blob/master/docs/development/project-setup/environment-variables.md#configure-redis-url

**Comment by pranavrajs** [comment]
@saint739 Also, please go through https://docs.chatwoot.com/docs/development/environment-setup/ubuntu to see if you missed any dependencies.

**Comment by kirillarutyunov** [comment]
I had the same error 
> ArgumentError: invalid uri scheme ''

Solve it by setting redis_url.

Full docs available here: https://docs.chatwoot.com

**Comment by pranavrajs** [comment]
Closing this as docs.chatwoot.com is up and we are tracking the documentation for Mac(#85) and windows(#86) separately.
