### ISSUE TITLE
Redis::CommandError in DashboardController#index

### ISSUE THREAD

**Issue by darshit261991** [chatwoot/chatwoot#1201]
**Redis::CommandError in DashboardController#index**

When I start docker on my Mac and open localhost:3000 I get following error.
![Screen Shot 2020-09-04 at 6 49 31 PM](https://user-images.githubusercontent.com/28289275/92243755-96013280-eedf-11ea-8705-e6b92ee81771.png)

**Comment by pranavrajs** [comment]
@darshit261991 It looks like you have not set the Redis password, can you please share the config you are using?

**Comment by darshit261991** [comment]
You talking about .env file right? Here is the screen shot of .env file attached.

<img width="882" alt="Screen Shot 2020-09-06 at 11 32 32 PM" src="https://user-images.githubusercontent.com/28289275/92332163-3ea6c200-f099-11ea-94ce-dc4ece74c601.png">

**Comment by pranavrajs** [comment]
@darshit261991 Please share docker-compose file as well.

**Comment by nithindavid** [comment]
@darshit261991 I'm closing this issue as there is no response. Please feel free to reopen if you want to continue the conversation.
