### ISSUE TITLE
Feature: Outbound/Welcome Messages

### ISSUE THREAD

**Issue by seanvm** [chatwoot/chatwoot#1209]
**Is your feature request related to a problem? Please describe.**
We find that our conversions are much higher when we can engage our leads in a chat. With _other_ chat providers we found that we had much more engagement and believe it was due to their "outbound message" feature - essentially a welcome message configured to pop up after 10 seconds.

**Describe the solution you'd like**
We would like the ability to configure a welcome message that pops up on the screen after a set amount of time. 

- The message should be configurable
- Should be able to configure which agent it is from
- Should be able to configure how many seconds the user is on the page before it appears
- If the user has already begun a conversation, then it should not appear.

This is what Intercom's implementation looks like:

![image](https://user-images.githubusercontent.com/16951595/92508528-a3f3d380-f1bd-11ea-8fa9-4bb4b868026a.png)

**Comment by pranavrajs** [comment]
<img width="517" alt="Screenshot 2020-09-08 at 11 16 29 PM" src="https://user-images.githubusercontent.com/2246121/92510356-5745e200-f229-11ea-8f98-78428881ea98.png">

We have this unread message indicator which can be converted to build this feature. I understand this is a marketing use case and we have people requesting a similar feature. 

As a first step to improve the UX around bubble indicator we started experimenting with a new bubble design type. Our user research found that bubble design has lesser interaction compared to a link or a bubble with text. 

<img width="226" alt="Screenshot 2020-09-08 at 11 20 23 PM" src="https://user-images.githubusercontent.com/2246121/92510709-e226dc80-f229-11ea-918e-a920075f5723.png">

More about the feature you are requesting. Do you expect this to be configurable based on the page or a segment of customers etc?

**Comment by seanvm** [comment]
> As a first step to improve the UX around bubble indicator we started experimenting with a new bubble design type. Our user research found that bubble design has lesser interaction compared to a link or a bubble with text.
> 
I noticed that, and we are currently trying out the "expanded" bubble, although it still seems to gain significantly less interaction than a welcome message.

> More about the feature you are requesting. Do you expect this to be configurable based on the page or a segment of customers etc?
Our use case doesn't require page or segment targeting. Our primary target is first-time visitors to the website.

However, I know other companies use features like this as a way to target existing customers in-app and let them know about important changes, new features, etc.

**Comment by iammattmartin** [comment]
I'd agree on this.

Although scope should be considered for logic too. 

I.e been on page for X seconds, or visited Y amount of pages. likewise, being able to show a message based on the page they're on too would be very powerful a bit less robotic.

**Comment by sojan-official** [comment]
closing in favour of https://www.chatwoot.com/docs/product/features/campaigns/ongoing
