### ISSUE TITLE
launcherText appears not to work

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1210]
**Describe the bug**

Following the SDK docs, I added:

```
window.chatwootSettings = {
  hideMessageBubble: false,
  position: 'left', // This can be left or right
  locale: 'en', // Language to be set
  type: 'expanded_bubble', // [standard, expanded_bubble]
  launcherText: 'Test Test'
};
```

The position and type work as expected but the launcherText does not.

Currently running v1.7.2 and have forced an upgrade again but this appears to not have helped.

**Comment by pranavrajs** [comment]
@iammattmartin This was a mistake in the documentation, it should be `launcherTitle` instead of `launcherText`

**Comment by pranavrajs** [comment]
Thanks for reporting, this has been deployed to the site as well.
