### ISSUE TITLE
Feature: Show reports for a custom time range

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1216]
- Add a date range picker instead of 7 days / 30days
- Update the API if required

Acceptance criteria:

- identify the date range picker to be used in chatwoot

**Comment by chanukya-y** [comment]
Hi @pranavrajs,  i would like to work on this feature.

**Comment by sojan-official** [comment]
@chanukya-y  let us know if you need any help.

**Comment by chanukya-y** [comment]
@sojan-official , I have the application installed in my local machine. I have few things to confirm.

- I'm planning to use the plugin https://www.npmjs.com/package/vue2-daterange-picker for daterange picker. Is this okay ?
- I would like to know what would be the default range for the reports , that will be used when user opens the reports page initially.

Demo of the above mentioned plugin can be seen here https://innologica.github.io/vue2-daterange-picker/

**Comment by pranavrajs** [comment]
@chanukya-y Thanks for the research. I'm concerned about the size of the package. Can you please suggest alternatives?

**Comment by Brokray** [comment]
Do you guys have any update on this feature request ? :)

**Comment by sojan-official** [comment]
@Brokray  We don't have anyone working on this at the moment.  If you are interested in contributing, feel free to go ahead :)

**Comment by chanukya-y** [comment]
Hi @sojan-official  @pranavrajs 

I was held-up for sometime . Shall i resume working on this issue.

**Comment by sojan-official** [comment]
At the moments reports allow a specific range. let change this to a date range selector. 
<img width="454" alt="Screenshot 2021-06-16 at 11 41 56 PM" src="https://user-images.githubusercontent.com/73185/122270910-72522a80-cefc-11eb-91df-a78a01503b3a.png">

**Comment by sojan-official** [comment]
reassigning due to lack of activity.

**Comment by iamsivin** [comment]
CtkDatetimePicker - https://chronotruck.github.io/vue-ctk-date-time-picker/
Github profile - https://github.com/chronotruck/vue-ctk-date-time-picker

vue2-datepicker - https://mengxiong10.github.io/vue2-datepicker/index.html#Range
Github profile - https://github.com/mengxiong10/vue2-datepicker 

Any suggestion?
