### ISSUE TITLE
Feature: Filter reports by labels

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1217]
- Filter reports by labels

Acceptance criteria:

- Admin should be able to see reports of a particular label 
- Admin should have a button to download a CSV report for labels

## Design

<img width="1745" alt="Screenshot 2021-08-15 at 7 47 47 PM" src="https://user-images.githubusercontent.com/73185/129481488-ebab0b38-2a31-49ed-91b0-d402526d2b1c.png">

**Comment by sojan-official** [comment]
blocked by: https://github.com/chatwoot/chatwoot/issues/2823

**Comment by pranavrajs** [comment]
Closed via #3084
