### ISSUE TITLE
Feature: Filter reports by agents

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1218]
- Filter reports by agents

Acceptance criteria:

- Admin should be able to see reports of a particular agent.
- Admin should have a button to download a CSV report for  agents

## Design

<img width="1746" alt="Screenshot 2021-08-15 at 7 43 15 PM" src="https://user-images.githubusercontent.com/73185/129481380-9f403f1c-8ba5-464f-b186-f3092596c9a4.png">

**Comment by sojan-official** [comment]
blocked by: https://github.com/chatwoot/chatwoot/issues/2823

**Comment by pranavrajs** [comment]
Closed via #3084
