### ISSUE TITLE
Notify user if Slack connection has expired

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1225]
- Move Integration: Hook to disabled status.
- Save the exception
- Send an email to the account administrators stating that the integration has been disabled.

**Comment by monarch0111** [comment]
@pranavrajs Can you please assign this to me? I would like to explore this.

**Comment by sojan-official** [comment]
@monarch0111  do let us know if you have any questions :)

**Comment by monarch0111** [comment]
@sojan-official I have a question, at what step should the hook status be confirmed? I see there are different places from where we call `Slack::Web::Client` methods, any one of them can throw an error for hook disabled / oauth revoked.

One way I think can of is to create a wrapper class around `Slack::Web::Client`, which will handle exceptions regarding to slack apis. Please let me know if there is a better way.

**Comment by sojan-official** [comment]
@monarch0111  Idea of having a wrapper class is great and would be the cleaner approach 👍. But if you don't want to put in that much effort, we can just handle the exception in  ` lib/integrations/slack/send_on_slack_service.rb`  : `send_message` method. 

The other slack API calls would happen during the auth flow and chances of an expired token in that flow is slim. Its mostly when we relay the message into slack when we face the exception. The mentioned service should cover it. 

---

Also, take a look at this PR https://github.com/chatwoot/chatwoot/pull/1286/files 
We can use the same concern to mark whether the error threshold has passed and alert the user to reauthenticate.

**Comment by monarch0111** [comment]
Thanks for the insight, for now I will go with smaller approach as adding new class will have higer complexity. I will work on refactoring / adding wrapper class in another PR.

----
From https://github.com/chatwoot/chatwoot/pull/1286/files, I understand concern can be used to display error message on UI. Once I am done with the changes, I will raise an issue to implement UI changes.

**Comment by monarch0111** [comment]
@sojan-official @pranavrajs 
> Save the exception

What do you mean by this? Do we store exception somewhere or it is capturing exception in Sentry?

**Comment by sojan-official** [comment]
@monarch0111   sorry for the lack of clarity in the description there.  We just store a count of the error in Redis that's all.  

If its a handled exception, we don't capture it in sentry. We usually write the message to the logs though. refer the following block.
https://github.com/chatwoot/chatwoot/blob/807f79ef5d03098f5f0f70e4937779c98b498700/app/services/facebook/send_on_facebook_service.rb#L11

But feel free to go with your discretion  :)

**Comment by monarch0111** [comment]
> @monarch0111   sorry for the lack of clarity in the description there.  We just store a count of the error in Redis that's all.  
> 
> If its a handled exception, we don't capture it in sentry. We usually write the message to the logs though. refer the following block.
> https://github.com/chatwoot/chatwoot/blob/807f79ef5d03098f5f0f70e4937779c98b498700/app/services/facebook/send_on_facebook_service.rb#L11
> 
> But feel free to go with your discretion  :) 

Got your point, thanks! :)
