### ISSUE TITLE
Emojis doesnot render correctly in all platforms.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1227]
![image](https://user-images.githubusercontent.com/2246121/93001081-342d7200-f54a-11ea-977d-282d5a5cc355.png)

- **Browser**: Firefox 80.0
- **Operating System**: Generic Linux 0

**Comment by Giszmo** [comment]
My screenshot. The system is Ubuntu 20.04 with latest updates. On Chromium the smileys look fine.

**Comment by pranavrajs** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=1544717

**Comment by Giszmo** [comment]
guess that's not a ChatWoot issue then. Close?

**Comment by pranavrajs** [comment]
Yes, I think so. Closing it for now. If we can replicate this in multiple environments we will reopen this issue.
