### ISSUE TITLE
$chatwoot.setLabel() is not reliable

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1230]
**Describe the bug**

Adding one label fails while adding another label works just fine.

**To Reproduce**

I defined two labels: `paid` and `maybepaid`. I might have camelCased `maybePaid` in my original input but it's now shown as mentioned above.
On the client side I call `$chatwoot.setLabel("paid")` which works. The conversation needs to be reloaded to see the effect but the label gets added.
If I call `$chatwoot.setLabel("maybepaid")` or `$chatwoot.setLabel("maybePaid")`, the label does not get added.
If I add the label on the backend side, it works for both.

**Environment**

Server: CapRover on Digitalocean, running whatever the process gave me when installing it yesterday. In CapRover I can't find any version information and in the ChatWoot frontend neither.

Client: Ubuntu 20.04, Firefox 80.0.1 (64-bit)

**Comment by iammattmartin** [comment]
Usually, the version can be found within Settings > Account Settings > bottom of page unless a few releases behind as that was only added in the last 2~ releases. 

Maybe worth upgrading in any case if that isn't there.

**Comment by Giszmo** [comment]
v1.7.2

**Comment by pranavrajs** [comment]
@Giszmo 

> The conversation needs to be reloaded to see the effect but the label gets added.

This is known the label addition is not realtime. 

>  If I call $chatwoot.setLabel("maybepaid") or $chatwoot.setLabel("maybePaid"), the label does not get added.

Is there any error, we support only the predefined labels, you cannot add labels only the fly. This is done to reduce the irregularities in labels for eg: as you said maypbepaid can be written as mayBePaid or may-be-paid or mayBePaid and so on. To reduce the duplicate label there is no other standard way. So if you are using label on widget side, you have to define it in the dashboard.

I think these information should be custom-attribute not a label. Please take a look at https://www.chatwoot.com/docs/website-sdk#set-custom-attributes

Closing this as it is more of a conceptual issue not an acutal bug in the application. If you feel that is not the case, please feel free to reopen this.

**Comment by Giszmo** [comment]
The concept was understood. As I said:

> I defined two labels: paid and maybepaid

so subsequently I tried to set only those and no new on-the-fly labels.

So once again, with screenshots:

I have these labels defined:

![Screenshot from 2020-09-14 17-06-34](https://user-images.githubusercontent.com/96378/93133050-fe54ce80-f6ac-11ea-9e9f-eed163671b9d.png)

I am in this chat dashboard ...

![Screenshot from 2020-09-14 17-07-08](https://user-images.githubusercontent.com/96378/93133108-14628f00-f6ad-11ea-9844-cd4227ee8722.png)

... and client side ...

![Screenshot from 2020-09-14 17-07-18](https://user-images.githubusercontent.com/96378/93133145-1d536080-f6ad-11ea-8494-50b692f4756f.png)

I call the `setLabel()` method (which really should be named `addLabel()`), both without error:

![Screenshot from 2020-09-14 17-08-00](https://user-images.githubusercontent.com/96378/93133243-48d64b00-f6ad-11ea-8f15-3c7237979237.png)

and refresh the dashboard, to see this:

![Screenshot from 2020-09-14 17-08-22](https://user-images.githubusercontent.com/96378/93133265-5390e000-f6ad-11ea-94ac-b92d2eda689d.png)

**Comment by sojan-official** [comment]
ref:  #1229

**Comment by Giszmo** [comment]
So poking around a bit more I noticed that using undefined labels does work in that the label gets stored even though it was not defined beforehand which does raise DOS concerns. To test that, I ran

```
for (var i = 0; i < 100; i++) $chatwoot.setLabel("stupidLabel" + i)
```

(against my self-hosted instance) and got this:

![Screenshot from 2020-09-17 23-26-40](https://user-images.githubusercontent.com/96378/93548660-0b3c2100-f93e-11ea-9748-ee2035fe0650.png)

As that's not 100 errors, I created "stupidlabel5" on my instance and clicked on it. The counter said "1" but it doesn't show the conversation:

![Screenshot from 2020-09-17 23-26-59](https://user-images.githubusercontent.com/96378/93548776-59512480-f93e-11ea-8ba1-78e8a41434c9.png)

I know which conversation it is though and when selecting it, it does not show me any stupidlabel{n} labels for it.

Also after manually adding it:

![Screenshot from 2020-09-17 23-39-00](https://user-images.githubusercontent.com/96378/93549154-180d4480-f93f-11ea-8b0c-1d3768778dc8.png)

It's "shown":

![Screenshot from 2020-09-17 23-39-16](https://user-images.githubusercontent.com/96378/93549171-2196ac80-f93f-11ea-9919-7218919cf666.png)

But the conversation is not listed when searching for all labeled conversations:

![Screenshot from 2020-09-17 23-39-33](https://user-images.githubusercontent.com/96378/93549216-34a97c80-f93f-11ea-8244-708644985f17.png)

And when I return to the conversation via "Conversations", the label is gone again.

In fact, adding all my labels to the conversation:

![Screenshot from 2020-09-17 23-42-38](https://user-images.githubusercontent.com/96378/93549401-923dc900-f93f-11ea-8b8d-125949c847ab.png)

and then pressing F5 I get this:

![Screenshot from 2020-09-17 23-42-49](https://user-images.githubusercontent.com/96378/93549415-9c5fc780-f93f-11ea-8b63-56a5336d2bab.png)

**Comment by Giszmo** [comment]
Turns out the issue is with the label and not the sdk.

To reset stuff, on the capRover server I run:

```
# docker exec -it $( docker ps --filter name=chat-web -q ) /bin/sh
/app # bundle exec rails c
irb(main):001:0> Conversation.all.destroy_all
irb(main):002:0> Label.all.destroy_all
irb(main):003:0> ActsAsTaggableOn::Tagging.destroy_all
```
Which leaves me with a clean-ish panel:

![Screenshot from 2020-09-21 11-59-38](https://user-images.githubusercontent.com/96378/93783396-04ddcb80-fc02-11ea-8633-e2e00bf1dfca.png)

I create the labels "paid" and "maybepaid" written exactly like this:

![Screenshot from 2020-09-21 12-01-56](https://user-images.githubusercontent.com/96378/93783654-538b6580-fc02-11ea-872e-3656c7ad2f06.png)

![Screenshot from 2020-09-21 12-02-12](https://user-images.githubusercontent.com/96378/93783666-571eec80-fc02-11ea-9d67-30af078a56d7.png)

Create a test conversation from my website integration:

![Screenshot from 2020-09-21 12-03-55](https://user-images.githubusercontent.com/96378/93783850-99482e00-fc02-11ea-8f85-eca837429985.png)

Add both labels:

![Screenshot from 2020-09-21 12-04-59](https://user-images.githubusercontent.com/96378/93783943-b8df5680-fc02-11ea-90dd-87c4ddedc241.png)

They are shown next to the conversation:

![Screenshot from 2020-09-21 12-05-08](https://user-images.githubusercontent.com/96378/93783968-c1d02800-fc02-11ea-926f-d3b14eaf9088.png)

After hitting F5 to refresh, the "maybepaid" label is gone:

![Screenshot from 2020-09-21 12-05-53](https://user-images.githubusercontent.com/96378/93784036-dc0a0600-fc02-11ea-8c95-2af8d6282cc2.png)

**Comment by sojan-official** [comment]
identified the issue to be with a stale label defined in actsastaggable tags table.   ActAsTaggable will be removed as a part of #1249 , so this shouldn't occur in future. 

so closing in favour of #1249
