### ISSUE TITLE
Enhancement: Improve UX around availability status

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1234]
### Problem

Right now, the option to change availability status is hidden in profile settings. People might not realize that they have an option offline. To improve this UX, provide a setting right on the sidebar to change the status

### Design

<img width="391" alt="Screenshot 2020-09-14 at 5 24 24 PM" src="https://user-images.githubusercontent.com/2246121/93082974-73c19e80-f6af-11ea-90da-ac9816ba26b0.png">

**Comment by somenugget** [comment]
Hi @pranavrajs. I would like to take this issue 😋 Could you assign me?

**Comment by sojan-official** [comment]
@somenugget  let us know if you need any help :)
