### ISSUE TITLE
Redirect image attachment domain not working

### ISSUE THREAD

**Issue by yani94** [chatwoot/chatwoot#1235]
I have tried set both the followings env to 
`FRONTEND_URL=https://mydomain.com`
`FORCE_SSL=true` 

but it redirects the images attachment to https://127.0.0.1:3000 instead and not my domain.

_Originally posted by @yani94 in https://github.com/chatwoot/chatwoot/issues/756#issuecomment-689940548_

**Comment by pranavrajs** [comment]
@yani94 Are you running it production mode? (RAILS_ENV=production)

**Comment by yani94** [comment]
i'm running in linux vm production mode

**Comment by pranavrajs** [comment]
@yani94 Can you please share the server logs of both worker and web along with browser logs? The information available here is not enough for us to debug the issue.

**Comment by yani94** [comment]
@pranavrajs thanks for all your reply, turn out I'm missing this line `proxy_set_header Host $host;`  when I try to configure nginx. I will close this issue as it already solved.
