### ISSUE TITLE
feature: Include the messaged triggered from url in webhook events

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1239]
As I am leveraging chatwoot webhook events/APIs to build on top, receiving the URL where the user is currently chatting from will be helpful.

**Comment by somenugget** [comment]
Hi there. Can I take this issue?

**Comment by sojan-official** [comment]
@somenugget  let us know if you need any help.

**Comment by pranavrajs** [comment]
@sojan-official Do we need to keep this open? We have initiated_at URL on the events.
