### ISSUE TITLE
Feature: Use Gravatar Image if contact has no avatar attached to it

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1240]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For customers that use email, they have no avatar. It would be nice to just pull from Gravatar as we already have their email and this would add to a more personable touch.

It is fairly common and acceptable that this is done which is why people set up their gravatar in the first place.

**Comment by pranavrajs** [comment]
@iammattmartin We use to have gravatar before. I don't remember why we removed it. This seems like a nice addition.

**Comment by onlywicked** [comment]
I would like to work on this issue.

**Comment by pranavrajs** [comment]
@onlywicked Great! I'm assigning this to you.

**Comment by iammattmartin** [comment]
Question, does this only apply to admins? Looking at the code it seems to be but I could be wrong. @pranavrajs

**Comment by pranavrajs** [comment]
This applies to agents & admins only, I've noticed that. We can extend it to contacts also.

**Comment by iammattmartin** [comment]
That was certainly my original thought on it more than staff. Has real limited use for staff but i'd say more useful for users/visitors.

**Comment by onlywicked** [comment]
Okay, I'll integrate it for the users/visitor.

**Comment by pranavrajs** [comment]
@sojan-official This issue is not complete. Reopening now
