### ISSUE TITLE
Mail Channel Inbox Setup (Additional Instructions)

### ISSUE THREAD

**Issue by clixnet** [chatwoot/chatwoot#1244]
Hi Chatwoot Team:

I've setup mail channel inbox.  Followed the continuity instructions in setting up sendgrid and dns properly. 

I've confirmed sendgrid inbound parse is posting correctly to chatwoot.  However, no email is showing up in channel and I'm not sure where to start as I'm not seeing any errors. 

Are there any more detailed instructions on setting up or additional tips anyone could provide?  

Thank you!

**Comment by pranavrajs** [comment]
@clixnet Are you trying to use email channel or conversation continuity? 

If you are trying to use the email channel, it is still under a feature flag. It might not work. We will release in the upcoming releases.

If you are trying to use the conversation continuity, can you try setting up the following using the rails console?

```rb
account = Account.find(<your_account_id>)
account.domain = <verified_domain_in_sendgrid>
```

Once you have done this, you should be able to see the email sent to the user if they are offline will be of the format 

```rb
reply+<large-encrypted-string>@<your-verfied-domain>
```

<img width="619" alt="Screenshot 2020-09-18 at 1 17 32 PM" src="https://user-images.githubusercontent.com/2246121/93571043-84289080-f9b1-11ea-97e6-0f5e5ccbe0bf.png">

If the user replies to the email, it will be shown as a message in the conversation.

<img width="387" alt="Screenshot 2020-09-18 at 1 19 47 PM" src="https://user-images.githubusercontent.com/2246121/93571121-a3bfb900-f9b1-11ea-95fc-505ab644dbf6.png">

<img width="492" alt="Screenshot 2020-09-18 at 1 20 03 PM" src="https://user-images.githubusercontent.com/2246121/93571192-bafea680-f9b1-11ea-8eae-ba9d0ce11d1d.png">

Hope this helps.

**Comment by clixnet** [comment]
Thank you for the additional instructions.  I was referring to the email channel, but this information is helpful too.  Thanks again!

**Comment by maulikbafalipara** [comment]
Hello @pranavrajs 

I try to create an email channel with Postmark and I am facing the same issue.
can you please let me know email feature is now live or not?

![image](https://user-images.githubusercontent.com/16645207/118686220-7158ab00-b821-11eb-87a0-785ad952f844.png)

Email webhook successfully received but conversation(email ticket) is not created.
