### ISSUE TITLE
RESOLVE not working

### ISSUE THREAD

**Issue by clixnet** [chatwoot/chatwoot#1251]
Conversations that are marked resolved end up coming right back.  It is not working right.  They disappear from list, but the count stays the same, then reloading shows them right back.

**Comment by pranavrajs** [comment]
@clixnet Can you please follow this format https://github.com/chatwoot/chatwoot/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md while creating bugs? There is too little information about what the error is. If you could share browser console logs/server logs, that would be great.

**Comment by clixnet** [comment]
Issue was caused by unrelated project code.  It has been resolved.  Thank you.
