### ISSUE TITLE
Integration with MessageBird

### ISSUE THREAD

**Issue by aag1990** [chatwoot/chatwoot#1253]
MessageBird is another Whatsapp API provider that I would like to link to my Chatwoot. MessageBird has done a great job with their API documentation on the website, I hope that would help to apply the integration more easily.
It would be a significant add if Chatwoot integrates with MessageBird to get WhatsApp, SMS, voice messages, and other communication channels. 
Thank you for the great work Chatwood

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/discussions/2759
