### ISSUE TITLE
Feature: Staff "take" Conversation

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1257]
**Is your enhancement request related to a problem? Please describe.**
To speed up conversation assignment. It would be nice if a staff member could "take" a convo instead of having to select their name from what could be a large drop-down list.

**Describe the solution you'd like**
Simply a button next to the drop-down with "Take" or "Own" would be good enough. This could take a ticket when an owner is not assigned or when one is.

Likewise, the button could then change to "Release" when it is owned by the current user viewing the conversation.

**Comment by pranavrajs** [comment]
@iammattmartin This is a nice suggestion. We will see how we can update the UI around this.
