### ISSUE TITLE
Twitter character count

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1263]
**Describe the bug**

When replying to a tweet of a third party in a conversation (clicking reply to this tweet icon), the counter does not seem to take this into consideration.

We sent a tweet reply today with 0 characters left. Sent but it never appeared. We suspect this may have just been dropped due to the character count.

Although this then presents another issue, these messages seem to be silently rejected with no feedback to the staff/sender. It looks like it has gone but in reality, has not. We had to resend manually twitter.com.

There either needs to be better logging for tweets including those that have failed to be sent and the ability to edit/resend them etc.

**Comment by pranavrajs** [comment]
@iammattmartin Is it possible to share the logs during that time? 

Delivery status needs to be shown to the agent. We need to improve the UX around it.

**Comment by iammattmartin** [comment]
Any ideas what an error would look like in the production log?

I have the ActionCableBroadcastJob but can't see anything that represents an error.

**Comment by iammattmartin** [comment]
This appears to still be a problem and the same thing happened today. Long tweet reply just vanished. Had to send via Twitter UI.

I would say this needs some focus because long-er tweets just vanish but give the impression they've been sent. They need to fail if they have not been passed to twitter.

**Comment by tejaswinichile** [comment]
Ideas:

We can handle it before sending a message with minimal effort.
We can have a character count for the Twitter channel inbox editor. We will need UI/UX changes around it on channel check.

@pranavrajs @nithindavid  Thoughts?

**Comment by pranavrajs** [comment]
Isn't this the same as #2695? I guess we can close this issue.

**Comment by pranavrajs** [comment]
@iammattmartin Please feel free to re-open the issue if the problem still exist.
