### ISSUE TITLE
How do I fully translate in Japanese language

### ISSUE THREAD

**Issue by kohki-shikata** [chatwoot/chatwoot#1266]
**Is your feature request related to a problem? Please describe.**
I need to use chatwoot in Japan. So I'll fully translate to Japanse language this product.
However, I think it seems to config/ja.yml, config/device.ja.yml are ready for be translated partially.
I need to **fully** translate this product. How do I do?

**Describe the solution you'd like**
I beleive anyone can tell me what files to I should translate.

**Describe alternatives you've considered**
I wish docs describe easily how to translate this product.

**Additional context**
![2020-09-23_15h02_11](https://user-images.githubusercontent.com/4133263/93972844-0cda6e80-fdae-11ea-9291-6dd651ffcbb1.png)
or should I see another files?

**Comment by pranavrajs** [comment]
@kohki-shikata Please create an account and update the translations at https://translate.chatwoot.com/chatwoot/ja Once it is completed, we will bring that into the repository.
