### ISSUE TITLE
feat: Add support for events for a contact

### ISSUE THREAD

**Issue by cdunford** [chatwoot/chatwoot#1268]
**Describe the bug**

The docs indicate the website SDK can be used to add labels to the conversation by calling `addLabel` like:

```
window.$chatwoot.addLabel('support-ticket');
```

However, `addLabel` does not appear to be defined on `$chatwoot`.

**To Reproduce**

Use the following code:

```
<body>
  <script>
    (function (d, t) {
      var BASE_URL = "https://app.chatwoot.com";
      var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
      g.src = BASE_URL + "/packs/js/sdk.js";
      s.parentNode.insertBefore(g, s);
      g.onload = function () {
        window.chatwootSDK.run({
          websiteToken: 'YOUR_TOKEN',
          baseUrl: BASE_URL
        })
      }
    })(document, "script");

    (function () {
      window.addEventListener('chatwoot:ready', function () {
        window.$chatwoot.addLabel('support');
      });
    })();
  </script>
</body>
```

**Expected behavior**

`addLabel` should exist and should add a label to the conversation

**Browser logs**

```
index.html:20 Uncaught TypeError: window.$chatwoot.addLabel is not a function
    at index.html:20
    at y (CustomEventHelper.js:14)
    at Object.loaded (IFrameHelper.js:113)
    at window.onmessage (IFrameHelper.js:69)
```

**Environment**

app.chatwoot.com

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 85.0.4183.102

**Comment by pranavrajs** [comment]
@cdunford This was a mistake in the documentation. The method to be used is `setLabel` not `addLabel`

**Comment by cdunford** [comment]
Thanks. I noticed setLabel on the prototype and tried it in the ready
callback but my new conversation did not have the label. Does it need to be
called at a specific time?

**Comment by pranavrajs** [comment]
@cdunford Have you created the label on the backend? We do not support labels to be created on the fly, predefined-labels can only be used.

**Comment by cdunford** [comment]
Yes the label already exists:

![image](https://user-images.githubusercontent.com/1405868/94142767-c849e400-fe3c-11ea-88f5-7db095e09da6.png)

I call `setLabel` on `chatwoot:ready`:

```
(function () {
      window.addEventListener('chatwoot:ready', function () {
        window.$chatwoot.setLabel('support');
      });
    })();
```

Chat doesn't have any labels when it's started:

![image](https://user-images.githubusercontent.com/1405868/94142939-06df9e80-fe3d-11ea-8b81-b7444ae9a12d.png)

**Comment by cdunford** [comment]
Am I perhaps misunderstanding what this statement means: `Please note that the labels will be set on a conversation if the user has not started a conversation. In that case, the following items will not have any effect:`

I interpret that to mean I must call `setLabel` before a conversation is started; I actually don't see how I would call it after anyway.

**Comment by pranavrajs** [comment]
@cdunford Understood the problem. At the moment there is no other way to see whether the conversation has started or not. In the coming releases, we will move this to events. So instead of labels on conversation, you will be able to set events on a contact which would resolve this problem. Updating the title and keeping it open for now.

**Comment by sojan-official** [comment]
closing in favour of : https://github.com/chatwoot/chatwoot/issues/2271
