### ISSUE TITLE
Long file name appears to be broken in the UI

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1273]
**Describe the bug**
<img width="531" alt="Screenshot 2020-09-25 at 11 08 13 AM" src="https://user-images.githubusercontent.com/2246121/94230345-69a96680-ff1f-11ea-9695-fa79cc988718.png">

**To Reproduce**

- Upload a file from Widget/Facebook with a long file name.
- View the conversation in the agent dashboard.

**Comment by naresh3599** [comment]
Hi, @pranavrajs. would like to pick this one and contribute! ❤️
Please assign me.

**Comment by sojan-official** [comment]
@naresh3599  let us know if you need any help :)

**Comment by naresh3599** [comment]
Yeah sure,

**Comment by apclarity** [comment]
is this issue still open?

**Comment by narendran-kannan** [comment]
Working on this!

**Comment by sojan-official** [comment]
fixed in #1306
