### ISSUE TITLE
Conversation limits for agents

### ISSUE THREAD

**Issue by versedpro** [chatwoot/chatwoot#1275]
Is it possible that one agent can only handle 2 open conversations at once, the system doesn't give them 10.   Some agents can handle more open conversations than others.  This is to be able to load balance accordingly.

I assume to implement this stuff setting the limitation of open conversations to agent when its creating or adding.

**Comment by pranavrajs** [comment]
@versedpro It seems like this is a duplicate issue. Please see #1198
