### ISSUE TITLE
Integration with Infobip

### ISSUE THREAD

**Issue by AlejandroCarballo** [chatwoot/chatwoot#1277]
Infobip is a WhatsApp API provider that I would like to link to my Chatwoot. Infobip has done a great job with documenting their API on the website and integration with java language programming,
It would be great if Chatwoot integrates with Infobip to get WhatsApp, SMS, voice messages, and other communication channels.
Thanks for the excellent job!

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/discussions/2759
