### ISSUE TITLE
Date Separators in Chat History

### ISSUE THREAD

**Issue by NikhilGupta1997** [chatwoot/chatwoot#1278]
**Is your enhancement request related to a problem? Please describe.**
Similar to most messaging services, it would be great if the conversation history in ChatWoot can be demarcated using dates.

**Describe the solution you'd like**
I propose adding a date separator in the message history to reflect the date when those messages were created.
Here is a screenshot of my proposed solution
<img width="489" alt="Screenshot 2020-09-26 at 4 40 11 AM" src="https://user-images.githubusercontent.com/16648570/94337896-92a72580-000b-11eb-95b8-7d1c61d2ec3d.png">

**Comment by NikhilGupta1997** [comment]
@sojan-official/ @pranavrajs  You can assign this issue to me. I'll submit a pull request shortly.

**Comment by lovelynitar** [comment]
Hello, this feature is included in which version of chatwoot?

**Comment by pranavrajs** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/issues/3047
