### ISSUE TITLE
Fix "method_complexity" issue in app/models/conversation.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#128]
Method `run_round_robin` has a Cognitive Complexity of 11 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/models/conversation.rb#issue_5d9b93b4d887000001000191

**Comment by luchiago** [comment]
Hi, I would like to work on that.

**Comment by josemiguelo** [comment]
Should this PR still be open?

**Comment by pranavrajs** [comment]
Closing as the corresponding issue is fixed
