### ISSUE TITLE
Feature: Delete/Unsend Message

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1283]
**Is your feature request related to a problem? Please describe.**
If a staff member accidentally sends a message or pastes something into a message that needs to be removed, currently there is no way to do this.

For website conversations, it would be nice to be able to delete/unsend/hide a message within a period of time (i.e 10 seconds).

**Describe the solution you'd like**
An option on a message to remove it from public view, either delete or hide so that only staff can see it was sent and that it was removed.

There may be scope for this to apply to other channels too that support it. WhatsApp and Facebook certainly support message deletion normally but unsure if possible via API.

**Comment by Giszmo** [comment]
I see no reason for a time limit. Allow unpublishing, turning it into "this message was deleted" for the visitor.

I'd just like to make sure the agent remains auditable internally, so please never actually delete messages.

**Comment by iammattmartin** [comment]
Time limit is in relation to emails. If that message has already been sent, there would be no point in deleting/hiding it as they will already have a copy you cannot change. 

Deletion should always be possible. Data may be added to a reply by both the user or staff that cannot be stored, such as a card CVV; storing this in any format is against card rules.

There may also be a GDPR request for data deletion from a customer etc.

**Comment by pranavrajs** [comment]
@nithindavid I would come back with the agent permissions by Wednesday.

**Comment by pranavrajs** [comment]
@nithindavid For now, let us show the delete option only to the assigned agent. We can revisit this at a later point.

**Comment by Giszmo** [comment]
> show the delete option only to the assigned agent.

Is there plans to actually let the assigned agent delete all traces of messages he authored?

**Comment by pranavrajs** [comment]
Closed via #2532

**Comment by Giszmo** [comment]
Looking at #2532 I think the answer to my question above is "Agents can remove all traces of their messages, leaving no way of auditing policy compliance by superiors"?

**Comment by pranavrajs** [comment]
@Giszmo At the moment, yes. We will add a log when a user deletes a message so that auditing is available.
