### ISSUE TITLE
heroku: Can't log back in

### ISSUE THREAD

**Issue by bogorad** [chatwoot/chatwoot#1284]
**Describe the bug**

Can't log in after creating the first user and logging out.

**To Reproduce**

1. 'Single-click' deploy to Heroku.
2. Fix the 'dyno' bug - enable the second dyno.
3. Create the first user.
4. Log off.
5. Log back on - get user/password incorrect.
6. Try to create a user with the same email - get this error:

"You have already signed up for an account with (this email)"

7. Click 'forgot email', get this but obviously no email.

"Woot! Request for password reset is successful. Check your email for instructions"

**Expected behavior**

Should remember entered passwords properly. Second and third time around I used a simple [a-zA-Z0-9] password.

**Environment**

Heroku 'single-click' deploy.

**Desktop (please complete the following information):**
 - OS: Win10, latest patches
 - Browser Chrome, latest

**Comment by sojan-official** [comment]
@bogorad  have you configured an email service on your Heroku installation? 
You would have to verify the user first before you can start using the user.

**Comment by bogorad** [comment]
> @bogorad have you configured an email service on your Heroku installation?
> You would have to verify the user first before you can start using the user.

I wish it was explained somewhere. Thank you for your prompt reply!
