### ISSUE TITLE
Bug: Clicking multiple times creates a selection for the text

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1285]
<img width="211" alt="Screenshot 2020-09-29 at 12 21 45 PM" src="https://user-images.githubusercontent.com/2246121/94523112-5adbf000-024e-11eb-99d3-6d3ddad5ef90.png">

Clicking multiple times creates a selection for the text on widget

**Comment by Nico385412** [comment]
Hi ! i would like to fix this use, can you assign me ? ^^
