### ISSUE TITLE
Fix "similar-code" issue in app/javascript/src/api/account.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#129]
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/api/account.js#issue_5d9b93b9d8870000010001a4

**Comment by n1rna** [comment]
I would like toe work on this issue.

**Comment by pranavrajs** [comment]
Closing as the corresponding issue is not available.
