### ISSUE TITLE
Fix "method_complexity" issue in app/controllers/devise_overrides/confirmations_controller.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1290]
Method `create` has a Cognitive Complexity of 8 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/controllers/devise_overrides/confirmations_controller.rb#issue_5f738e3f977c600001000343

**Comment by somenugget** [comment]
@pranavrajs can I take this issue?

**Comment by sojan-official** [comment]
@somenugget  please go ahead :)
