### ISSUE TITLE
bug: setUser SDK function is broken

### ISSUE THREAD

**Issue by jcomo** [chatwoot/chatwoot#1296]
**Describe the bug**

Cannot call setUser because an internal function call throws a TypeError every time.

**To Reproduce**

1. Load the widget SDK
2. Call setUser
3. See error

**Expected behavior**

It should not throw an error

**Screenshots**

N/A

**Browser logs**

```
Uncaught (in promise) TypeError: Cannot read property 'avatar_url' of undefined
    at sdk.js:26
    at Array.reduce (<anonymous>)
    at j (sdk.js:25)
    at Object.setUser (sdk.js:53)
    at eval (index.ts?76aa:50)
```

**Server logs**

N/A

**Environment**

Chatwoot SDK

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 85.0.4183.102

**Additional context**

Trying to replace our drift integration with chatwoot, but this is blocking.

**Comment by danirolopes** [comment]
Same problem here! I'm using chatwoot for some time, and this problem started yesterday

**Comment by pranavrajs** [comment]
@danirolopes The fix has been deployed. Let me know this doesn’t work.
