### ISSUE TITLE
Replace text-sms icon on left sidebar if the inbox is a Whatsapp inbox

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1303]
Whatsapp inbox uses an SMS, replace it with a whatsapp inbox. We use ionicons v2(https://ionicons.com/v2/) Replace the icon with appropriate icon for whatsapp.

### Before
<img width="233" alt="Screenshot 2020-10-03 at 2 16 21 PM" src="https://user-images.githubusercontent.com/2246121/94987333-677c8300-0583-11eb-82df-f8e9be11e028.png">

### After
<img width="237" alt="Screenshot 2020-10-03 at 2 17 43 PM" src="https://user-images.githubusercontent.com/2246121/94987334-68adb000-0583-11eb-81e0-bb37dd5825af.png">

**Comment by sarawukl** [comment]
I'm working on this issue.

**Comment by pranavrajs** [comment]
@sarawukl Sure, I will assign this ticket to you.
