### ISSUE TITLE
Fix long label names getting broken in the sidebar

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1304]
<img width="236" alt="Screenshot 2020-10-03 at 2 20 03 PM" src="https://user-images.githubusercontent.com/2246121/94987359-8e3ab980-0583-11eb-94bc-0d9b282ca1a4.png">

### Solution

- Truncate the text and provide a tooltip on hover.

**Comment by amd-9** [comment]
May I try to fix this bug?

**Comment by sojan-official** [comment]
@amd-9  please feel free to go ahead.
