### ISSUE TITLE
Name and email address overflow in the customer sidepanel

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1305]
<img width="308" alt="Screenshot 2020-10-03 at 2 22 55 PM" src="https://user-images.githubusercontent.com/2246121/94987430-fc7f7c00-0583-11eb-8ea5-b24573860490.png">

### Acceptance criteria

- **Name**: Break the word and show the name in the second line.
- **Email**: Truncate the email address, show full email address on hover. 
   Provide a button on the right to copy the full email address.

**Comment by xlanor** [comment]
@pranavrajs , I would like to be assigned this and give this a shot.

As I am new to the codebase, is there any guide for me to narrow down which files to take a look at?

**Comment by pranavrajs** [comment]
@xlanor Feel free to take it. You can start looking at `ContactInfo.vue`

**Comment by mathamonkey** [comment]
Hi, 
Is it still open?

**Comment by sojan-official** [comment]
@mathamonkey seems like @muhsin-k opened a PR already for this.

**Comment by mathamonkey** [comment]
> @mathamonkey seems like @muhsin-k opened a PR already for this.

Yes, please let me know if there is any other beginner issue that I can contribute to.
