### ISSUE TITLE
Facing this issue while doing rake db:create

### ISSUE THREAD

**Issue by TheIncredibleHarsh** [chatwoot/chatwoot#131]
bundle exec rake db:create                           rake aborted!
ArgumentError: invalid uri scheme ''
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/redis-4.1.2/lib/redis/client.rb:438:in `_parse_options'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/redis-4.1.2/lib/redis/client.rb:83:in `initialize'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/redis-4.1.2/lib/redis.rb:45:in `new'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/redis-4.1.2/lib/redis.rb:45:in `initialize'
/Users/harshkumar/Documents/personal/chatwoot/config/initializers/redis.rb:2:in `new'
/Users/harshkumar/Documents/personal/chatwoot/config/initializers/redis.rb:2:in `<main>'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:318:in `block in load'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:318:in `load'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/engine.rb:666:in `block in load_config_initializer'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/notifications.rb:205:in `instrument'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/engine.rb:665:in `load_config_initializer'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/engine.rb:624:in `each'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/engine.rb:624:in `block in <class:Engine>'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:32:in `instance_exec'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:32:in `run'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:50:in `each'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/initializable.rb:60:in `run_initializers'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/application.rb:364:in `initialize!'
/Users/harshkumar/Documents/personal/chatwoot/config/environment.rb:5:in `<main>'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:324:in `block in require'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/activesupport/lib/active_support/dependencies.rb:324:in `require'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/application.rb:340:in `require_environment!'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bundler/gems/rails-4a2746db1c92/railties/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/Users/harshkumar/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)

**Comment by pranavrajs** [comment]
https://docs.chatwoot.com/#/development/project-setup/errors
