### ISSUE TITLE
[CW-1869] Prioritise conversations based on customer mood

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1317]
At the moment chatwoot conversations are prioritized based on last activity.  
We could explore bringing in additional parameter like  customer mood, the total value of customer etc to prioritize the sorting

ref: https://github.com/ankane/informers

<sub>[CW-1869](https://linear.app/chatwoot/issue/CW-1869/feature-prioritise-conversations-based-on-customer-mood)</sub>

**Comment by pranavrajs** [comment]
Closing this here as the model is not accurately producing results. We will re-open if there is a better model available.
