### ISSUE TITLE
Client side browser live chat widget needs manual refresh

### ISSUE THREAD

**Issue by ckc** [chatwoot/chatwoot#1322]
**Describe the bug**

As title mentioned, client side cannot got instance update message from agent

**To Reproduce**

1. Guest go to 'floating chatbutton'
2. Click on 'chat window'
3. Send message without problem
4. Client cannot get message from agent without whole web page reload (F5)

**Additional context**

I'm not sure is it problem or same with #411 ?

May I have any solution or hint for trace back to locate issue? Thanks

**Comment by WevrLabs** [comment]
Maybe the "worker" isn't activated and running?

**Comment by sojan-official** [comment]
@ckc  if you are running chatwoot on Heroku ensure the worker is turned on.  Also, ensure the `FRONTEND_URL` environment variable is set.
