### ISSUE TITLE
Support for launching the widget straight into full-screen on loading

### ISSUE THREAD

**Issue by pcolby** [chatwoot/chatwoot#1325]
**Is your feature request related to a problem? Please describe.**
No. Its just an additional feature :)

**Describe the solution you'd like**
I'd like to be able to embed the chat widget, already open, as the main central item on the webpage. This would be something similar to the pop-out window, but loaded directly, and without having to click to open.

**Describe alternatives you've considered**
I've considered (and still experimenting with) simply loading the widget onto a page, and automatically calling `window.$chatwoot.toggle();` on load.  This sort of works, and is what we'll probably do for now.  But the widget loads in a non-ideal small area to the side, and there's some jankiness before we get to toggle it.  There might be other options in the website SDK that work better, but I've played with all I could see in the docs (I am still playing though; any pointers would be great).

**Additional context**
The use case, is basically that we what to be able to include some "talk to us" links in email footers, that would go to https://chat.example.com, which would launch straight into a full-screen chat.

Here's a real-world (albeit clunky) [example using ClickDesk](https://my.clickdesk.com/cdMob?id=all_ag9zfmNsaWNrZGVza2NoYXRyDgsSBXVzZXJzGI2OpRUM).

Thanks!

**Comment by iammattmartin** [comment]
I'm sure this will be possible as the popout to external window is now possible so using the URL from that could work for you but it is getting that URL in the first place which you'll need.

**Comment by iammattmartin** [comment]
I'd say this would be achieveable with one I raised a while back #1237.

As being able to link generate would allow embedding in signatures and images on the site we well as full size windows etc.

**Comment by iammattmartin** [comment]
@pcolby You may be able to get this to work by copying the popout link i.e

https://domain/widget?website_token=xxxxxxxxxxxxx&locale=en

Conversation continuation won't work but this *may* work. It does open a chat window.

**Comment by pcolby** [comment]
Thanks @iammattmartin, yes, it looks like this will give me what I want. I wasn't sure if dropping the `cw_conversation` parameter would still work, but a quick test seems to suggest it will be just fine.

The pop-out domain in my case is `app.chatwoot.com` (ie we're using the hosted service), so I'll probably iframe it into a basic branded template (to get it under our preferred domain), and see how that works.

Thanks.

**Comment by RonWalker22** [comment]
@pcolby to have the widget open automatically, all you need to do is change one value in `window.$chatwoot` object. 

look here https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/packs/sdk.js

change `isOpen: false` to `isOpen:true`

If I remember correctly, that's all I needed to do. If there's more to it, look at my pull request:   #875  

Also in that pull request I talk about the need for full screen.

**Comment by iammattmartin** [comment]
I believe he means full screen instead of open in situ.

**Comment by pranavrajs** [comment]
@pcolby Would it be helpful if we expose a function like `window.$chatwoot.popout()` which would pop the conversation window? Your use case seems business specific, I would prefer to keep custom logic outside Chatwoot. With the new method on SDK, you can call the function whenever you want and achieve the result you have been suggesting.

**Comment by pcolby** [comment]
Thanks @iammattmartin and @pranavrajs!

I don't think this concept is "business specific" - ClickDesk, for example, offers it as standard feature.

That said, it look like I can get the behaviour I want by hosting a single status page at `chat.our-domain.io` with content like this:

```
<!DOCTYPE html>
<html>
 <head>
 ...
  <style type="text/css">
   iframe {
     position: fixed;
     background: #000;
     border: none;
     top: 0; right: 0;
     bottom: 0; left: 0;
     width: 100%;
     height: 100%;
   }
  </style>
 </head>
 <body>
  <iframe src="https://app.chatwoot.com/widget?website_token=<our-token>&locale=en"></iframe>
 </body>
</html>
```

So, assuming that the `iframe` URL I've distilled is semi-supported (ie not _likely_ to break often?) then I'm happy run with that, and close this request.

Thanks again.

**Comment by pranavrajs** [comment]
@pcolby This seems to be fine. I don't think this URL would have backwards-incompatible changes. If something is there which is breaking, we can work out an alternative. Feel free to close this ticket.

**Comment by hartois** [comment]
@pcolby, do you have any problem clearing the conversation on page refresh in that using case?

**Comment by hartois** [comment]
I realized that I needed what is described in #1237
