### ISSUE TITLE
Support push on offical mobile app with self hosted Chatwoot

### ISSUE THREAD

**Issue by nevros** [chatwoot/chatwoot#1338]
**Describe the bug**
As an agent I need to be aware when there is a chat message. Having issues here with the web app and not mobile app. When the web page or mobile application is open a new chat message is displayed on the screen with 1-2 seconds which is great.

***Web page***
When moving focus off the web page, to another application or tab, there is no notification of a new chat. 

***Mobile app***
When switching to another application and a new chat message arrives, there is no notification.

**To Reproduce**
1. Only active agent
1. All agent notification are turned on in the mobile application
1. Auto assign is turned on
1. New chat message sent, in the chat window ensure the agent is displayed proving they have been assigned to the chat

**Expected behavior**

Web page and mobile app should display a notification on new messages that have been assigned to the agent.

**Server logs**

```
2020-10-12T07:04:09.859914489Z 2020-10-12T07:04:09.858Z pid=1 tid=2m3t class=Notification::PushNotificationJob jid=0e534b789673ad14cd739706 INFO: start
2020-10-12T07:04:09.865372823Z 2020-10-12T07:04:09.865Z pid=1 tid=2ldp class=SendReplyJob jid=6bf882a28ebd59a50e52da81 INFO: start
2020-10-12T07:04:09.867249485Z I, [2020-10-12T07:04:09.866756 #1]  INFO -- : [ActiveJob] [SendReplyJob] [a316ddd7-c0a8-4d37-8e82-5473a10ac3d7] Performing SendReplyJob (Job ID: a316ddd7-c0a8-4d37-8e82-5473a10ac3d7) from Sidekiq(high) enqueued at 2020-10-12T07:04:09Z with arguments: 96
2020-10-12T07:04:09.871555458Z I, [2020-10-12T07:04:09.871169 #1]  INFO -- : [ActiveJob] [Notification::PushNotificationJob] [bf58b355-7526-41d2-8718-f466948dcf42] Performing Notification::PushNotificationJob (Job ID: bf58b355-7526-41d2-8718-f466948dcf42) from Sidekiq(default) enqueued at 2020-10-12T07:04:09Z with arguments: #<GlobalID:0x000055deb035e578 @uri=#<URI::GID gid://chatwoot/Notification/44>>
2020-10-12T07:04:09.894967304Z I, [2020-10-12T07:04:09.894564 #1]  INFO -- : [ActiveJob] [SendReplyJob] [a316ddd7-c0a8-4d37-8e82-5473a10ac3d7] Performed SendReplyJob (Job ID: a316ddd7-c0a8-4d37-8e82-5473a10ac3d7) from Sidekiq(high) in 27.46ms
2020-10-12T07:04:09.895650083Z 2020-10-12T07:04:09.895Z pid=1 tid=2ldp class=SendReplyJob jid=6bf882a28ebd59a50e52da81 elapsed=0.03 INFO: done
2020-10-12T07:04:09.898034730Z I, [2020-10-12T07:04:09.897178 #1]  INFO -- : [ActiveJob] [Notification::PushNotificationJob] [bf58b355-7526-41d2-8718-f466948dcf42] Performed Notification::PushNotificationJob (Job ID: bf58b355-7526-41d2-8718-f466948dcf42) from Sidekiq(default) in 25.44ms
2020-10-12T07:04:09.898084330Z 2020-10-12T07:04:09.897Z pid=1 tid=2m3t class=Notification::PushNotificationJob jid=0e534b789673ad14cd739706 elapsed=0.039 INFO: done
```

**Environment**

Self-hosted running version 1.8.0 on Docker swarm.

Is this setting needed? and if so where do I get this value from. Can not find any documentation on this.
```
# for mobile apps
# FCM_SERVER_KEY=
```

These values were updated and the server was restarted, but it did not change anything. Considering the platform was created with these values empty is there something that needs to be done in order to make this apply (other than a full restart)?
```
VAPID_PUBLIC_KEY=[masked]
VAPID_PRIVATE_KEY=[masked]
```

**Desktop (please complete the following information):**
 - OS: Windows 10 & OSX
 - Browser Chrome
 - Version latest for all above

**Smartphone (please complete the following information):**
 - Device: Andriod
 - Version Chattwoot app v0.0.59

**Comment by sojan-official** [comment]
@nevros mobile notifications won't work with self-hosted instances at the moment ( if you are using the mobile app published on AppStore ) .  You will have to use the custom build mobile apps https://github.com/chatwoot/chatwoot-mobile-app  with the appropriate FCM keys. we are still figuring out how to handle this case.  

The VAPID_KEYS are for the browser push notifications on your desktop. 
for the browser notifications to work, each agent will have to enable in on their profile settings page from a supported browser like chrome, firefox etc.

**Comment by nevros** [comment]
@sojan-official 
Mobile app makes sense, thank you for explaining this. FYI Rocket chat uses a central proxy server that is offered as a free service.

With the browser settings I am only able to find this within my profile. 
![image](https://user-images.githubusercontent.com/2770413/95750701-40435580-0ce9-11eb-941a-3e056c0fff2d.png)

The email notification works well, so those settings are operational. Is there meant to be more than this?

**Comment by iammattmartin** [comment]
"FYI Rocket chat uses a central proxy server that is offered as a free service."

.... subject to new usage limits.

It's worth noting that RC is far more mature and has been around far longer to mean admin if this isn't too much a drain on resource. CW is far younger and dev time would be spent on far better things.

**Comment by WevrLabs** [comment]
You mentioned updating the VAPID krys? I faced a similar issue few days ago, as a result of changing my keys. 
I worked around it by clearing the notifications subscriptions from the browsers I previously subscribed to, and also I deleted the rows from the notifications_subsciptions table in the database. And then resubscribed again in the browsers.

**Comment by pranavrajs** [comment]
@nevros @iammattmartin @WevrLabs 

We had a discussion about this already. One of the problem why push won't work on official app is because your instance doesnot have the credentials of our Firebase app. One of the things we can do here is to setup a proxy kind of server like the one which Rocket.chat uses, so your instance would be sending a payload to centralized Chatwoot instance which would deliver the message to the app. This is actually in discussion, it would take some more sprints to complete as there are other features have been asking for. 

@nevros You should set VAPID_KEYS inorder for the push notifications to work on the web application, it doesnot have an dependancy to Chatwoot cloud.

**Comment by pranavrajs** [comment]
Relabeling it as an enhancement

**Comment by nevros** [comment]
After deploying the entire stack again within Docker the push settings appeared correctly. Should have realized that restarting the docker container will not pick up environment variable changes within the compose file. Web notification are now working perfectly, thank you.

![image](https://user-images.githubusercontent.com/2770413/95798325-6d215800-0d3d-11eb-9ee4-053c7b0db889.png)

Understand the situation with the mobile app, that is more of a nice to have. Email notifications will make a suitable workaround.

@iammattmartin 
We have spent over 2 days playing with RC and was really hopeful in the beginning.  Clearly, that did not go well as we are here. Yes Chatwoot is under developed in comparison simply due to its age but I am confident it has a much strong future.  IMO, right now chatwoot is a better platform for servicing our requirements then RC. We are still getting the integration to our platform right but it is looking great so far.

An impressive project guys :)

**Comment by yourbabyscan** [comment]
Have you considered making the FCM keys changeable via AppConfig (see appconfig.org) which means they could be set on the app from the public App Store using an MDM.
