### ISSUE TITLE
Resolve conversation should remove agent & clear history 

### ISSUE THREAD

**Issue by nevros** [chatwoot/chatwoot#1341]
**Is your enhancement request related to a problem? Please describe.**
When an agent clicks on "Resolve" to close the conversation the customer does not see any change, there is no difference for them.  24 hours later if the customer opens up the chat again they will see the same conversation and will be routed to the same agent and appended. 

But that agent might not be available (on leave or what ever) at this point in time. And if its 2 weeks later on it will be a different subject and not related to the last conversation.

**Describe the solution you'd like**
When the agent selects "Resolve" the customer should get a notification within the chat, "This chat has been completed by the agent" or something similar. Maybe add in a button that says "Start a new chat". When they close the chat bubble the history is removed. The association with the agent is removed.

When the customer opens up the chat again it is empty just like the first time they used the chat. 

**Describe alternatives you've considered**
..

**Additional context**
We are planning on using chatwoot to support logged in users, so they are fully identified every time.
Guess this is not an issue if the user is not identified.

**Comment by pranavrajs** [comment]
@nevros We have received similar feedback from other users, so we are attempting to incorporate multiple conversations in the widget via #1206 . You can have more than one thread of conversation on the widget and it should resolve this problem.

**Comment by nevros** [comment]
@pranavrajs Very interested to see how this will work, it does sound like it will address most of this use case.
The updated chat widget looks great, nice work.

**Comment by Giszmo** [comment]
The linked PR and there the linked issue doesn't explain well how OP's issue would be resolved in the context.

We need to know which agent resolved how many issues and we need a record of that resolution. Also for me it is a feature that the client doesn't see I hit "resolved" as I do that after every answer I gave. After all many users will not reply back and it's cluttering the UI to keep those chats unresolved. If anything, a new button "close" could have such functionality. It could archive the chat the agent hat with the client such that the next chat the user opens goes to unassigned again, with an empty history but the agents should see there are archived chats.

If this would be the taken approach, the "resolve" could have an option "close if not re-opened in x hours/days/weeks".

**Comment by kwkcomputersolutions** [comment]
Hi guys, well done on a great product so far!

This feature (to "close" the current conversation into an "archive" / clear the history) or at the very least, notify the client that the query has been resolved is very important for our use case. A customer may contact us today with one issue and tomorrow have an unrelated issue. Our agents also work shifts, so the requirement of "unassigning" the conversation once resolve is also important

**Comment by morozover** [comment]
//When the customer opens up the chat again it is empty just like

I think this implementation will not be useful for customers.
History of communication (messages) is valuable thing.
For example in WhatsApp, Viber, FB Messenger dialogs are saved and agent cannot delete it.

**Comment by snaildos** [comment]
+1 100% agree with this. Great it is getting added.

**Comment by sojan-official** [comment]
Closing this in favour of Multiple Conversations in the website widget

https://github.com/chatwoot/chatwoot/issues/2355
