### ISSUE TITLE
Wrong transcript sent on multi installation environment

### ISSUE THREAD

**Issue by iwolfm** [chatwoot/chatwoot#1343]
I have setup to instances of chatwoot via Linux VM script. Everything works fine until I send a transcript via  e-mail.

Installation 1 database: chatwoot_production, port 3000
Installation 2 database: chatwoot_demo, port 3001

The second installation sends the transcript from the first installation. Everything else seems to work fine.
I have updated both installations to the most current release.

**Comment by pranavrajs** [comment]
@iwolfm Are you using a shared Redis instance?

**Comment by iwolfm** [comment]
@pranavrajs  yes

**Comment by iwolfm** [comment]
@pranavrajs : I create an additional instance of redis and it works fine. Thanks!
