### ISSUE TITLE
Enhancement: Add sounds to staff view.

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1345]
**Is your enhancement request related to a problem? Please describe.**
Yes, when staff have the admin area open and dealing with a chat, unless they keen a concisious view of that, conversation in a running chat may be forgotten.

The visitor gets a discreet noise on a new message, extending this to staff would be good as an optional setting per staff member.

This will help that when people are live on site, chats are not forgotten as active.

**Describe the solution you'd like**
The same noise visitors get when a new message is received.

**Comment by mohmmd256** [comment]
Might also bring this to attention:

![Screen Shot 2020-10-16 at 5 54 10 PM](https://user-images.githubusercontent.com/7905931/96280881-d1ac1380-0fd8-11eb-910f-3d5bbaeccc01.png)

**Comment by pranavrajs** [comment]
We have looked at the different ways to enable this. Most of it has been hacky and that's the reason why we suggested to go ahead with the push notification. I can see that this has growing interest. We will take a look at it again. 

@mohmmd256 Are you talking about the widget side? We don't have one on dashboard.

**Comment by iammattmartin** [comment]
Push is good but if you have a massive monitor (I use a 49" ultra wide screen), these are often missed due to being top right corner.

Also, we use Fluid (https://fluidapp.com/) to have CW in an app box so we can keep on the dock. Push notifications don't work for it.

When there is a native CW app/wrapper that may fix that but then the notification view and being able to see them still remains a problem. With bigger monitors appearing, that may happen more often. 

Finally, with as many notifications as some people may get in a day, it may be lost in all the noise too...

**Comment by mohmmd256** [comment]
@pranavrajs Yes correct, I am referring to the widget.

**Comment by tabrza** [comment]
@pranavrajs - what are your thoughts on moving forwards on this?

**Comment by pranavrajs** [comment]
@tabrza #989 changes only the sound file, it doesn't solve the problem.

**Comment by pranavrajs** [comment]
This is tracked via #1738, the changes are working, but we need to add an ability to mute the notifications, otherwise, it will be an annoying feature. Moving it to the new milestone as the development would be continued.
