### ISSUE TITLE
Upgrading Chatwoot installation on Caprover

### ISSUE THREAD

**Issue by RicardoRamirezR** [chatwoot/chatwoot#1347]
Hi there,

I followed the update procedure to work with to the latest version of Chatwoot in caprover. I ran the process but the version 1.7.2 still sowed up.

Any clues?

**Comment by pranavrajs** [comment]
@RicardoRamirezR Are you using the tag latest? If so it would be cached in Caprover and it wouldn’t be updated. You need to use the specific version for upgrade

**Comment by RicardoRamirezR** [comment]
Yes @pranavrajs, putting the version worked! Thank you!
