### ISSUE TITLE
Line Break in Welcome Message

### ISSUE THREAD

**Issue by converso-chat** [chatwoot/chatwoot#1350]
Hello. The welcome message cannot be placed with a line break? I need to insert a small menu to call our chatbot

Thanks

**Comment by pranavrajs** [comment]
@converso-chat Can you share a screenshot or a mockup with the intended behaviour?

**Comment by converso-chat** [comment]
Hello, 
I have no image, I already exclude it. But is like that:

"Hello, this is the first line </br>
And this is the second line </br>
Three lines "

Understood?

Thanks

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/1241
