### ISSUE TITLE
Allow attachments through API channel.

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#1355]
**Is your enhancement request related to a problem? Please describe.**
Agents can not send any attachments while using an inbox with an **API** channel, and this is kind of frustrating.

**Describe the solution you'd like**
Simply have the same feature as the **Website** channel for example.

I deeply apologised if this enhancement has already been requested, I did not find any issue on the matter.

Cheers.

**Comment by pranavrajs** [comment]
@Brokray API already supported it, this was disabled in the UI. I've created a PR to fix it.

**Comment by Brokray** [comment]
Thanks a lot for your quick response ! :)
