### ISSUE TITLE
Enhancement: Be able to specify browser informations through API channel.

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#1357]
**Is your enhancement request related to a problem? Please describe.**

I did not find any documentation on the subject, nor any endpoint allowing to modify `additional_attributes` by API. 
Did I miss something ?

If not, I thought it would be great if we could specify browser informations through API (like your widget does).

**Describe the solution you'd like**
Maybe on creation of a conversation take in account an additional field ?
This could also be done like '/toggleStatus', with a `/browser` endpoint ? 🤷 

**Additional context**
 ```
   "additional_attributes": {
        "browser": {
            "device_name": "Macbook",
            "browser_name": "Chrome",
            "platform_name": "Macintosh",
            "browser_version": "80.0.3987.122",
            "platform_version": "10.15.2"
        }
    }
```

**Comment by pranavrajs** [comment]
@sojan-official Can you please estimate this requirement?
