### ISSUE TITLE
Enhancement: "We are offline" widget text.

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1362]
**Is your enhancement request related to a problem? Please describe.**
In the latest release, the widget now shows "We are offline". This kind of text isn't too desirable as sometimes all staff may be "offline" even though they'll log back in immediately on getting message.

**Describe the solution you'd like**
The text location is good but should be customisable per Inbox as it is better to give control than force a hard set value as the current wording will/could/may put many off sending a message.

**Comment by jaime-rivas** [comment]
+1!

**Comment by nithindavid** [comment]
Closing in favour of #234
