### ISSUE TITLE
POSTGRES_PASSWORD is printed out by docker container

### ISSUE THREAD

**Issue by mikehardenize** [chatwoot/chatwoot#1371]
**Describe the bug**

I'm using your docker image, from docker-compose. I pass through a POSTGRES_PASSWORD environment variable. Chatwoot prints this password out when running:

```
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | + echo 'Waiting for postgres to become ready....'
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | + '[' -z  ]
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | + PGPASSWORD=My_Secret_Postgres_Password
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | + PSQL='pg_isready -h localhost -p 5432 -U chatwoot'
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | + pg_isready -h localhost -p 5432 -U chatwoot
Oct 28 11:51:01 support1 docker-compose[9573]: web_1     | Waiting for postgres to become ready....
```

This isn't ideal because it then ends up in our logs. I've tried reducing the log level, but it gets printed out regardless.

**Additional context**

I'm using an image built on the base docker image `chatwoot/chatwoot:v1.9.0`

**Comment by pranavrajs** [comment]
@mikehardenize This is unfortunate. Thanks for reporting. We will provide a quick fix for it.
