### ISSUE TITLE
Bug: Server responds with a broken image url on file upload

### ISSUE THREAD

**Issue by robinWongM** [chatwoot/chatwoot#1372]
**Describe the bug**

It seems that server will respond with the image url before it succeed the uploading when an agent is uploading an image. The browser will fetch the image when the image isn't ready and user will get a "broken" image.

**To Reproduce**

1. Click on attachment icon in a chatbox
2. Select an image to upload
3. Wait until an broken image appears

**Expected behavior**

The agent should get a perfect image rather than a broken image.

**Screenshots**

![image](https://user-images.githubusercontent.com/2606137/97541760-a675eb00-1a00-11eb-96f5-cc9f270e1b9f.png)

**Browser logs**

![image](https://user-images.githubusercontent.com/2606137/97542065-17b59e00-1a01-11eb-9bef-fd5aec61d7f9.png)

![image](https://user-images.githubusercontent.com/2606137/97542011-040a3780-1a01-11eb-99a0-96c334fa6295.png)

**Server logs**

![image](https://user-images.githubusercontent.com/2606137/97541651-7595b600-1a00-11eb-9d02-23559d0a6334.png)

**Environment**

self hosted: Kubernetes cluster (on premise) with docker image `chatwoot/chatwoot:develop`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] 87.0.664.12

**Additional context**

If I click "Reload the image" from the context menu, the image will be displayed as expected since the uploading process is done then.

**Comment by pranavrajs** [comment]
@robinWongM Are you using Cloud storage like S3 or GCS? If not, could you please try it with any cloud storage. Our current docker images doesnot support disk based file uploads. This is a known issue as seen in #1166

**Comment by robinWongM** [comment]
> @robinWongM Are you using Cloud storage like S3 or GCS? If not, could you please try it with any cloud storage. Our current docker images doesnot support disk based file uploads. This is a known issue as seen in #1166

I haved tried self-hosted minio which is S3-compatible, and chatwoot behaved the same. Unfortunately I couldn't use other cloud storage since the Kubernetes host is unable to access the Internet directly.

When I use local storage, chatwoot container is configured to persist its `/app/storage` on a Persistent Volume (while the docker-compose.production.yml doesn't). So when chatwoot is restarted (the Kubernetes Pod is deleted and recreated), previously uploaded file won't gone. It did work.

From the log, it seems that chatwoot received the request for the image BEFORE `Uploaded file to key xxx` (see green text). Maybe chatwoot doesn't wait for the uploading to complete?

**Comment by sbreiler-work** [comment]
I've the same problem, regardless if agent or contact is uploading an image. It seems to me, chatwoot returns a reply despite Sidekiq-Job/s3 upload isn't done yet.

**Environment:**
Self hosted installation on Ubuntu 20.10, **_AWS-S3 Cloud Storage_**

**Desktop (please complete the following information):**
 - OS: Win
 - Browser: Chrome
 - Version: 91

**Log:**
https://gist.github.com/sbreiler-work/07f04817df126ccb8cab0212169cc695

**Comment by crazybiceps219** [comment]
Hi I'm facing a similar issue. I'm using s3. When users upload an image this error is reported in sentry.
Sentry issue link:
https://sentry.io/share/issue/f5bfb3bf297c4853a2dfa77c05b54507/

**Comment by pranavrajs** [comment]
@tejaswinichile Please share the update on this.

**Comment by tejaswinichile** [comment]
Note to self: Test it when #3567 is merged.

**Comment by tejaswinichile** [comment]
This has been fixed by https://github.com/chatwoot/chatwoot/issues/3612 but it should not appear in the future it will be fixed by #3567
