### ISSUE TITLE
Create conversations from emails

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#138]
- [ ] when a customer replies to email notifications sent in #139 , it should be appended to the conversation
 - [ ] Parse attachments and add it to the conversation

**Comment by sony-mathew** [comment]
I'm taking this.

**Comment by alekseyp** [comment]
I'm interested a lot in that feature, mostly to replace old ticketing system.

Will it work with multiple IMAP accounts?
Or maybe email can be forwarded to single Chatwoot address, and then it will look at "TO" address to decide which inbox should it send to?

**Comment by pranavrajs** [comment]
> I'm interested a lot in that feature, mostly to replace old ticketing system.

@alekseyp This is work in progress, will be available soon.

> Or maybe email can be forwarded to single Chatwoot address, and then it will look at "TO" address to decide which inbox should it send to?

This is how it will be implemented. For every inbox, you will have an associated email address at chatwoot. You can fwd your support tickets to this email which would create the conversations.

**Comment by d-mo** [comment]
Is this still expected to be available soon?

**Comment by sojan-official** [comment]
@d-mo  we are taking this up the April release ( v1.4.0 ) .
