### ISSUE TITLE
"error": "undefined method `reject' for nil:NilClass" when I create a new message using API

### ISSUE THREAD

**Issue by sorumehta** [chatwoot/chatwoot#1381]
"error": "undefined method `reject' for nil:NilClass" (status 422)
"Can't verify CSRF token authenticity." On server.

The steps I followed

1. I created a new 'API' type inbox from the dashboard, then created a new contact with the following API in Postman: https://app.chatwoot.com/api/v1/accounts/1709/contacts
This worked.

2. Then I created a new conversation using this API: https://app.chatwoot.com/api/v1/accounts/1709/conversations
This also worked.

3. Now the Error part. I tried to create a new message with the API: https://app.chatwoot.com/api/v1/accounts/1709/conversations/1/messages

and the body payload I sent was:
{

    "content": "Hey man",
    "message_type": "incoming",
    "private": true,
    "content_type": "cards",
    "content_attributes": { }

}

Response:
{
    "error": "undefined method `reject' for nil:NilClass"
}
Status: 422

SERVER LOGS:
I also tried running the server on my local machine, and this is the logs:

rails_1     | Started POST "/api/v1/accounts/2/conversations/1/messages" for 172.24.0.1 at 2020-11-02 16:02:00 +0000
rails_1     | Cannot render console from 172.24.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails_1     | Processing by Api::V1::Accounts::Conversations::MessagesController#create as JSON
rails_1     |   Parameters: {"content"=>"Hello I need some help from you brooooo", "message_type"=>"incoming", "private"=>"[FILTERED]", "content_type"=>"cards", "content_attributes"=>{}, "account_id"=>"2", "conversation_id"=>"1", "message"=>{"content"=>"Hello I need some help from you brooooo", "message_type"=>"incoming", "private"=>"[FILTERED]", "content_type"=>"cards", "content_attributes"=>{}}}
rails_1     | Can't verify CSRF token authenticity.
rails_1     | Completed 422 Unprocessable Entity in 139ms (Views: 1.8ms | ActiveRecord: 13.8ms | Allocations: 22980)
rails_1     | 
rails_1

Notice: "Can't verify CSRF token authenticity." Why am I seeing this error?
Can somebody please help me out?

**Comment by pranavrajs** [comment]
@sorumehta It looks like you are not passing the correct payload for the content type `cards`. Please take a look at https://github.com/chatwoot/chatwoot/wiki/Creating-Bot-Messages-Types

**Comment by sorumehta** [comment]
@pranavrajs  You are right, I got the response after using correct payload. Thanks 👍 
But I didn't get any callback (from API inbox) when I sent a message from chatwoot dashboard. Any suggestions on that?

**Comment by pranavrajs** [comment]
@sorumehta Have you added a right callback? I'm closing this ticket as it is not a bug, please create a discussion if you still need help.

**Comment by sorumehta** [comment]
Okay. Thanks for your help :)
