### ISSUE TITLE
Unable to Login As Super_Admin

### ISSUE THREAD

**Issue by andrewdmaclean** [chatwoot/chatwoot#1384]
**Describe the bug**
When attempting to connect to the super_admin URL on a heroku-hosted instance, I am unable to login with my credentials 

**To Reproduce**

1. Go to `XYZ.herokuapp.com/super_admin/sign_in`
2. Input Email & Password
4. See error - "Couldn't find SuperAdmin"

**Expected behavior**

Access to Super Admin Dashboard

**Screenshots**

![image](https://user-images.githubusercontent.com/26526271/98305835-733ed900-1f77-11eb-8c94-486f5120fd92.png)

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Firefox
 - Version: 82.0.2 (64-bit)

**Comment by sojan-official** [comment]
@andrewdmaclean  super admin uses separate credentials. 
you need to create a super admin user before accessing the page 

https://github.com/chatwoot/chatwoot/wiki/Creating-a-super-admin-and-accessing-sidekiq

**Comment by andrewdmaclean** [comment]
@sojan-official that was it!

Thanks for the help 👌
