### ISSUE TITLE
Bug: Changing of availability status doesn't affect agents' status on setting->agents page

### ISSUE THREAD

**Issue by versedpro** [chatwoot/chatwoot#1402]
**Describe the bug**

When an agent changes his/her availability status himself/herself, it doesn't affect on setting->agent page.

**Expected behavior**

When agents change their availability status themselves, the admin has to see their status changes on list of agents(Setting->Agents).

**Comment by pranavrajs** [comment]
@versedpro Could you please provide a screencast of the behaviour?

**Comment by versedpro** [comment]
I assume something went wrong during I was installing dependencies or upgrading chatwoot.
Could you give me any tip about how to reflect the changes of availability status from back-end(or database) to front components or store?
Thanks in advance.

**Comment by sojan-official** [comment]
<img width="1682" alt="Screenshot 2020-11-17 at 10 49 53 AM" src="https://user-images.githubusercontent.com/73185/99349793-d78c6180-28c2-11eb-925d-dc4c1cb48d45.png">
