### ISSUE TITLE
Emails are not working on Chatwoot fresh install

### ISSUE THREAD

**Issue by Sx3** [chatwoot/chatwoot#1422]
We are running Chatwoot on
Ubuntu 20.04 

//Mail outgoing
MAILER_SENDER_EMAIL=accounts@chatwoot.com
SMTP_PORT=1025
SMTP_DOMAIN=chatwoot.com
//if you are running docker-compose, set SMTP_ADDRESS value as "mailhog",
//else set the value as "localhost"
SMTP_ADDRESS=mailhog
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=

we don't use authentication for our email server so that the .env look above ..but the emails are not working - welcome email and password reset emails are not working...any directions to troubleshoot this ?

**Comment by sojan-official** [comment]
@Sx3 I think you need to change the SMTP_DOMAIN and SMTP_ADDRESS.  
probably switch the `SMTP_ADDRESS` to localhost ?

**Comment by Sx3** [comment]
> @Sx3 I think you need to change the SMTP_DOMAIN and SMTP_ADDRESS.
> probably switch the `SMTP_ADDRESS` to localhost ?

yes it is `SMTP_ADDRESS` = localhost ..but no emails

**Comment by sojan-official** [comment]
@Sx3  Could you share the logs?

**Comment by pranavrajs** [comment]
@Sx3 I'm removing the bug label since it seems to be an issue with the configuration.

**Comment by Sx3** [comment]
Okay mailgun confis works.
