### ISSUE TITLE
Avatars are embedded without ssl, triggering security warnings in modern browsers

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1427]
**Describe the bug**

Visitors to my page are being greeted with a security warning or even disabled css/js due to chatwoot's avatars being served unsafely without ssl.

**To Reproduce**

1. Navigate to [my website](https://walletscrutiny.com/)

**Expected behavior**

The avatars should be embedded using the (working) https urls.

**Screenshots**

Most users see:

![Screenshot from 2020-11-19 00-54-11](https://user-images.githubusercontent.com/96378/99619293-e75e8f80-2a01-11eb-91c7-ba4598a80d02.png)

and some of them see even this overreaction:

![photo5017341900419606645](https://user-images.githubusercontent.com/96378/99619161-99498c00-2a01-11eb-943d-2d959ad4f219.jpg)

**Browser logs**

```
Loading mixed (insecure) display content “http://chat-web.support.walletscrutiny.com/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8ce6129203098e075e0b8e0c733075327025b6cd/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTWpVd2VESTFNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--4d45b4816f15c2e58b42a8adbf1192cbc34fc95a/Leo_freigestellt.png” on a secure page
vue.common.prod.js:2274:6
```

**Server logs**

Not sure what to share there :(

**Environment**

Self hosted installation of Chatwoot using CapRover.

**Additional context**

I tried to update ChatWoot before reporting this issue, following [these instructions](https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-caprover#upgrading-chatwoot-installation) on my CapRover apps.

On my backend app it says "v1.10.0" now.

**Comment by Giszmo** [comment]
Ironically those objected images are not even hosted anymore as I have not yet figured out how to persist them.

**Comment by pranavrajs** [comment]
@Giszmo I was checking the config. Please set FRONTEND_URL with `https` value `https://chat-web......`

<img width="402" alt="Screenshot 2020-11-20 at 9 29 58 PM" src="https://user-images.githubusercontent.com/2246121/99822437-3844c400-2b79-11eb-94a6-b315dcfcc468.png">

**Comment by Giszmo** [comment]
Thanks. That fixed it. It should probably default to https, not to http these days.

**Comment by pranavrajs** [comment]
@Giszmo I understand that. Since we do not handle the SSL installation in our installation flow, we have kept this open. This would be included in the future build, we would change this to HTTPS as default then.
