### ISSUE TITLE
Refactor callbacks_controller.rb to attach inbox id to facebook pages model

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#143]
Facebook pages model should have the inbox id as well.  

ref: https://github.com/chatwoot/chatwoot/pull/110/files#r334294307
ref: #110

**Comment by ogabriel** [comment]
Hi.

I got interested in tracking and fixing the issue, this can be assign to me?

**Comment by sojan-official** [comment]
@ogabriel  i have assigned you the ticket.  feel free to pick up any unassigned issues anytime.  

thanks for the interest.

**Comment by sojan-official** [comment]
Inbox belongs to Channel now, hence this is fixed.
