### ISSUE TITLE
Deploy chatwoot under an url prefix

### ISSUE THREAD

**Issue by hiaselhans** [chatwoot/chatwoot#1430]
**Is your feature request related to a problem? Please describe.**

I'd like to have chatwood be available under the main domain with a prefix. e.g:
https://mydomain.com/chatwoot/

**Describe the solution you'd like**

cleanest would be to extract this information from FRONTEND_URL env variable.

**Comment by sojan-official** [comment]
ref: #1045

**Comment by hiaselhans** [comment]
hmm too bad :/

It's not an uncommon requirement tough to run chatwoot behind a reverse proxy in a prefixed path....
could you point me to one or two places where those assumptions are used?
setting asset_path would at least solve the js/css tag side of it...

**Comment by iammattmartin** [comment]
I'd say it is fairly uncommon for such types of app due to the way CW is built and intended for use.

You could try this yourself but the results would not be good.

**Comment by pranavrajs** [comment]
@hiaselhans Since this is not a blog or page which you need to host to external users, it doesn't make sense to put effort to support prefix unless there is a solid use case. Could you please describe the use case?

**Comment by hiaselhans** [comment]
thx for your message @pranavrajs ...

For my use case it is a docker/kubernetes deployment with nginx reverse proxy.
It is true that many companies use 'service.companydomain.com' for their services, but i see many of them switching to companydomain.com/service. I prefer the later because it simplifies local testing/deployment (service.localhost vs localhost/service)

If it is a big effort to achieve it you are right, it's easier for me to switch my deployment, but if it's not too much of work it can be good to support it.
If not to simplify my deployment then to avoid problems with same origin policies of enterprise clients...
There has been an issue before and there will be more in the future i guess ;)

as far as i see there's already this for the js side:
https://github.com/chatwoot/chatwoot/blob/61d26f71c100f8137347a0bc51b31f29e4057a86/app/javascript/dashboard/constants.js#L2

and using ASSET_CDN_HOST=url/prefix js loaded at least...
https://github.com/chatwoot/chatwoot/blob/61d26f71c100f8137347a0bc51b31f29e4057a86/config/environments/production.rb#L34

As you guys know the source much better than me: I'm happy to invest some work to get it running, but if it means a big refractoring or you wuoldn't want that or whatever i will use my time for other things :)

**Comment by pranavrajs** [comment]
@hiaselhans I understand. The frontend url logic completely relies on the fact that the Chatwoot installation would be on subdomain not on a relative URL. This seems like a significant change and a lot of testing would be required to confirm that the app is working without issues. It is technically possible, but it is hard for us to take a look at this right now. If you are willing or have time, please take a look at the source code and see if you can implement the functionality. I'd happy to assist you with PR reviews and testing.

**Comment by sojan-official** [comment]
@hiaselhans We don't encourage installation under a relative URL because we have features in our future pipeline with the assumption of having a full domain name/ subdomain name available for chatwoot instance. 

One example is the knowledge base feature we are building, which would grow into a self-service portal for the customers.  you wouldn't want this portal to be exposed to customers as  `xyc.com/chatwoot/knowledgebase` but `support.xyc.com`. 

> Implementation of this could be : 
One can add a cname record for  `support.xyc.com` with  `chatwoot.xyc.com` . Chatwoot would deliver the knowledge base view instead of the login screen when the request came from `support.xyc.com`

So to accommodate such use cases, we would need a domain instead of a relative path.

**Comment by hiaselhans** [comment]
Well, okay. I'm closing this then....

My private take on this is that you seem to have a good looking piece of software.
If it's widely acessible (oauth, sub-path) there can be quite a big audience for it.
On the other hand i think it's very hard to compete with confluence.

and, even if that's the roadmap, i don't see a problem having just another container there to serve `xyc.com/support` or `support.xyc.com` or whatever the name should be. for the 'user' to decide ;)

**Comment by hiaselhans** [comment]
and thx @pranavrajs . I'll see if i go ahead with it.
