### ISSUE TITLE
CSP nonce support

### ISSUE THREAD

**Issue by piotrblasiak** [chatwoot/chatwoot#1432]
Currently it is not possible to use a strict CSP policy for styles with wootchat, is it uses inline styles without support for nonce.
It would be great if it was possibe to start woothchat with a nonce that it would then use for all inline styles, like:

wootchatSDK.run({ nonce });

**Comment by pranavrajs** [comment]
@piotrblasiak Thanks for creating this issue, this needs an investigation on what changes need to be done, we will take it in the future releases.

**Comment by pranavrajs** [comment]
Closing this as the issue is stale for a long time. Please feel free to reopen the issue if this is still needed.
