### ISSUE TITLE
feature: Ability to have a configuration in admin panel to disable signups 

### ISSUE THREAD

**Issue by KonstantinReido** [chatwoot/chatwoot#1441]
**Is your enhancement request related to a problem? Please describe.**
On the login page, I see "Create new account", but in our case, only users who I added should have access to the system, so better to hide this link.

**Describe the solution you'd like**
Possibly some configuration option available via super admin panel.

**Comment by sojan-official** [comment]
for now please use https://github.com/chatwoot/chatwoot/discussions/1428 as a solution

**We can have this as a configuration option in super admin pannel in the future.**

**Comment by sojan-official** [comment]
You can configure the installation config `ENABLE_ACCOUNT_SIGNUP` on super admin now to disable signups
