### ISSUE TITLE
feature: Sort and display online contacts

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1444]
> Sort contacts (Beta) by Online , to list active users on the site live could be usefull for many businesses

ref: https://discord.com/channels/647412545203994635/719548300868452362/780416006857424907

**Comment by pranavrajs** [comment]
**Contact Attributes**

- Full Name
- Display Name
- Email Address
- Phone number
- Social Profiles
    - Linkedin
    - Facebook
    - Twitter
        - User name
        - Follower Count (Can be used for sort)
        - Following Count (Can be used for sort)
- Location
    - City
    - Country
    - Address (Full text)
- Timezone
- Bio
- Website
- Avatar
- Company (A separate model)


**Custom Attributes**

Add a model to save "allowed additional attributes to each contact" for an account

```jsx
{
  "attribute_name": "",
  "attribute_key": "",
  "filter": true,
  "search": true,
}
```

**Contact table attributes**

```jsx
{
  "attribute_name": ""
}
```

```jsx
{
  "plan": "cx001",
  "account_id": 23,
}
```

Filter using

- Actual contact attributes
- Custom contact attributes

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/5499
