### ISSUE TITLE
Message-ID potentially invalid, per RFC2822

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1450]
**Describe the bug**

Message-ID in mail on self-hosted sent from CW seems invalid. i.e

```Message-ID: <conversation/xxx-xxxx-xxxx-xxx/messages/xxx@>```

There should be hostname or domain after the @

Both SMTP_ADDRESS and SMTP_DOMAIN are set in the .env file so not sure where else this would need to be set or if this is just an oversight?

I would however say that using the same domain as the sender address (if set per Inbox) would be best.

**Comment by pranavrajs** [comment]
@sony-mathew Can you please take a look into this?

**Comment by iammattmartin** [comment]
I'd say this needs to be given a bit of a bump.

We're seeing lots of our emails from CW go in to spam from those using SpamAssassin as it hits this rule.

`INVALID_MSGID           1.167 Message-Id is not valid, according to RFC 2822`

**Comment by pranavrajs** [comment]
@iammattmartin I have pushed a fix for this, let us test it out and see if that fixes it.

**Comment by pranavrajs** [comment]
@iammattmartin Could you please share the output of the following commands? (Login to rails console using `bundle exec rails console`)

```rb
account_id = 1 // Use you account id
account = Account.find(account_id)
account.domain
```

```rb
ENV.fetch('MAILER_INBOUND_EMAIL_DOMAIN', false)
```

```rb
GlobalConfig.get('MAILER_INBOUND_EMAIL_DOMAIN')['MAILER_INBOUND_EMAIL_DOMAIN']
```

**Comment by iammattmartin** [comment]
Not sure if you want that output before or after upgrade, but before:

```
2.7.2 :007 > account.domain
 => nil
2.7.2 :008 >
2.7.2 :009 > ENV.fetch('MAILER_INBOUND_EMAIL_DOMAIN', false)
 => false
2.7.2 :010 > GlobalConfig.get('MAILER_INBOUND_EMAIL_DOMAIN')['MAILER_INBOUND_EMAIL_DOMAIN'
2.7.2 :010 > GlobalConfig.get('MAILER_INBOUND_EMAIL_DOMAIN')['MAILER_INBOUND_EMAIL_DOMAIN'
]
 => nil
```

Let me know if I should do after upgrade and we'll get that done.

**Comment by pranavrajs** [comment]
It looks like the MAILER_INBOUND_EMAIL_DOMAIN is not set which is probably why it is generating the wrong message_id. I will add SMTP_DOMAIN/SMTP_ADDRESS as a fallback, @sojan-official any thoughts on this?

**Comment by iammattmartin** [comment]
This was our original setup from CW.

Is it worth setting this value in that case?

**Comment by sojan-official** [comment]
closing since this was because the environment variable was missing. The id is valid per RFC if the domain value is populated.
