### ISSUE TITLE
Audio player for audio message

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1458]
If the conversation is happening in Whatsapp, people tend to use audio messages along with text messages. The current interface shows a download button for all file types except the image files. This makes it harder for the support agents to hear the content as they have to download it first and play it locally. 

### Feature

Identify a good library to support inline audio player and play audio inside the app itself.

**Comment by pranavrajs** [comment]
@nithindavid Do you have any suggestions for a good audio player?

**Comment by WevrLabs** [comment]
Adding this feature could have a great deal on support experience and save time.

**Comment by WevrLabs** [comment]
Can't this be achieved by just rendering the `<a>` element of the download link into an `<audio>` element `if` the attachment file is an audio media? same way done with images.

Modern browsers seem to have native support for playing audio files inline, if elements were identified as `<audio>` in html output, without the need for additional libraries or audio players:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#examples
