### ISSUE TITLE
Refactor users table 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#146]
The users table is getting pretty bloated with the extra information, we should leave it alone for devise information and move out the other information to a separate table probably.

**Comment by laurenball** [comment]
planning to pick this up sometime this week!

**Comment by laurenball** [comment]
quick update: i've started work on this but got sidetracked by work deadlines. I'm planning to wrap this up this weekend at the latest

**Comment by sojan-official** [comment]
thanks for the update @laurenball

**Comment by sojan-official** [comment]
The initial idea we had for the user models have changed with the recent developments in the project.
we will break the roles and account attribute from users in #402 .  and that's the only viable refactoring I can see for this now.  

hence closing this ticket in favor of #402
