### ISSUE TITLE
Chatwoot and Chatwoot  Mobile App / Turkish(tr) %100 i translated.  

### ISSUE THREAD

**Issue by taylanguneyaktas** [chatwoot/chatwoot#1465]
Chatwoot and Chatwoot  Mobile App / Turkish(tr) %100 i translated.
 
Chatwoot admin panel  Site language (Beta) no Turkish(tr) why not ? :(

**Comment by taylanguneyaktas** [comment]
Can I update manually?
http://daytonamotor.herokuapp.com Where can I enter ftp information?

**Comment by iammattmartin** [comment]
Please register those at http://translate.chatwoot.com/.

**Comment by pranavrajs** [comment]
@iammattmartin I gues the translation is complete. We are bringing the language via #1466

**Comment by iammattmartin** [comment]
Ah. @taylanguneyaktas just a case of waiting for the next release.

**Comment by pranavrajs** [comment]
Fixed via #1466

**Comment by taylanguneyaktas** [comment]
delete all my issues

**Comment by iammattmartin** [comment]
Theres no need to do this at all. You can just close them. Please don't rename things that have been already completed. It is destructive.
