### ISSUE TITLE
Installation not successful withLinux VM script

### ISSUE THREAD

**Issue by mike9011** [chatwoot/chatwoot#1473]
**Describe the bug**
I'm trying to install Chatwoot on Ubuntu with the bash script from the documentation, but it fails every time i run it.
I tried it 5 times on Ubuntu version 20.04 (clean installation) and 3 times on Ubuntu version 18.04, but no matter what i do, it always fails and the server isn't reachable at port 3000.

**To Reproduce**

1. Follow instructions from; https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm

**Server logs**
[chatwoot.log](https://github.com/chatwoot/chatwoot/files/5624443/chatwoot.log)

**Environment**
Linux VM installation self hosted.

**Comment by pranavrajs** [comment]
```
-bash: line 8: unexpected argument `]]' to conditional unary operator
-bash: line 8: syntax error near `;'
-bash: line 8: `if [[ -z  ]]; then'
```

@mike9011 I can see this error, can you please try `./setup.sh master` and see if that works?

**Comment by pranavrajs** [comment]
Also can you please try `https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_18.04.sh` instead of `https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_18.04.sh`?

**Comment by mike9011** [comment]
> Also can you please try `https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_18.04.sh` instead of `https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_18.04.sh`?

That did the trick! Thank you very much for the fast reply and the great software!
