### ISSUE TITLE
Proactive Chat Invitation

### ISSUE THREAD

**Issue by saaiful** [chatwoot/chatwoot#1475]
With this feature, instead of waiting for the visitor to come and talk to you, the chat opens automatically as soon as the user enters web page or in a specific page with a delay. 

Imagine, in checkout page if user waits 60 second, a chat window opens and asks if the user need any help regarding checkout. It is way more user friendly and attracts more customer. 

Or in specific product page it opens after certain time with FAQ.

Ex: https://www.jivochat.com/help/triggers/tuning-triggers.html
https://www.liveagent.com/features/proactive-chat-invitations/

**Comment by pranavrajs** [comment]
@saaiful This is something which we have in the pipeline, you will hear more about this in future releases.

**Comment by pranavrajs** [comment]
Closing this as the feature is live via #2177
