### ISSUE TITLE
Reply from Slack as an agent

### ISSUE THREAD

**Issue by DataTables** [chatwoot/chatwoot#1479]
**Is your enhancement request related to a problem? Please describe.**

When replying to a thread with the Slack integration it shows up in the Customer's widget as "Bot". It is fantastic that we can reply from Slack, but is it possible to set the reply to be as from a specific agent (we could create a generic "Support" one for example)?

This is how it shows in the widget at the moment:

![image](https://user-images.githubusercontent.com/278219/100881771-3d254400-34a6-11eb-8752-01b77152c10c.png)

And my message from Slack:

![image](https://user-images.githubusercontent.com/278219/100881797-46aeac00-34a6-11eb-97bc-bed57fecd7f0.png)

**Describe the solution you'd like**

Able to assign a user to the reply rather than "Bot". Or even better, some mapping between Slack user names and a Chatwoot profile (perhaps a field in the user's settings?)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pranavrajs** [comment]
@DataTables If you use the same email address in Slack and Chatwoot, it would recognize the user and create message under his/her name. 

Let us say the user has a name agent@example.com in Slack, please use the same email address in Chatwoot also. This should solve the issue you mentioned.

**Comment by DataTables** [comment]
That's done it - thanks! Awesome stuff this.
