### ISSUE TITLE
Filter conversations using a date range

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1481]
Support filtering conversations using dates 

- [ ] Add API to support from and to date
  - [ ] Create filters on both created_at and last_activity_at attributes.
- [ ] Add a filter on the UI for the date range.

**Comment by rahulmr** [comment]
@pranavrajs  is this implemented? If not what is the ETA?

**Comment by pranavrajs** [comment]
@rahulmr The API for this is completed via https://github.com/chatwoot/chatwoot/issues/3840. We are working on the UI for it now via https://github.com/chatwoot/chatwoot/issues/3938

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/4031
