### ISSUE TITLE
Allow users to use a custom slack channel name

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1488]
Right now, the default Slack channel name is assumed as #customer-conversations. 

Allow the users to select a different channel name or create a new channel from the UI.

**Comment by ruruiye** [comment]
+1 for this feature, searched for a long time. I think user can select the channel name when connect to slack. I have used that feature for other apps.

**Comment by Startouf** [comment]
In the meantime, you could patch the source code there in your app : https://github.com/chatwoot/chatwoot/blob/534acfbf96778610b82146cb653b78fdc2a22d5b/app/controllers/api/v1/accounts/integrations/slack_controller.rb#L35

**Comment by muhsin-k** [comment]
Closing in favor of  https://github.com/chatwoot/chatwoot/pull/7637
