### ISSUE TITLE
Notification center on the web

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1489]
- Display all the notifications for the user
- Show a badge when new notifications are available
- Update page title to indicate that there is a new notification. eg: `(1) ....`

**Comment by pranavrajs** [comment]
@sojan-official to provide designs for the notification screen.

**Comment by sojan-official** [comment]
#  Notification Center V1 Mocks

## Notification Center page

![Notifications](https://user-images.githubusercontent.com/73185/103009539-ecf94900-455c-11eb-9045-df2dfd3e2b68.png)

## Sidebar States 

### pending notifications
![pending notifications](https://user-images.githubusercontent.com/73185/103009552-f1bdfd00-455c-11eb-9cea-3fb2f4fd80a2.png)

### no notifications 
![Inactive notifications](https://user-images.githubusercontent.com/73185/103009553-f1bdfd00-455c-11eb-96b8-88e0885d3f72.png)

## Notification Row 

### on bubble hover
![hover bubble on notification](https://user-images.githubusercontent.com/73185/103009554-f2569380-455c-11eb-882b-95e15bc3e43c.png)

Clicking on the bubble will mark the notification as read
