### ISSUE TITLE
Email Conversation Continuity = No Conversation Continuity

### ISSUE THREAD

**Issue by icjohnson** [chatwoot/chatwoot#1496]
All,

System Configuration:

# Mail Outgoing
MAIL_SENDER_EMAIL: support@mycompany.com (O365 Account)
SMTP_PORT: 587
SMTP_DOMAIN: mycompany.com
SMTP_ADDRESS: smtp.office365.com
SMTP_USERNAME: support@mycompany.com
SMTP_PASSWORD: *******
SMTP_AUTHENTICATION: login
SMTP_ENABLE_STARTTLE: ### true

# Mail Incoming
RAILS_INBOUND_EMAIL_SERVICE: relay
RAILS_INBOUND_EMAIL_PASSWORD:  ****************************************************

# Postfix
forward_to_chatwoot   unix  -       n       n       -       -       pipe
  flags=Xhq user=chatwoot:chatwoot argv=/home/chatwoot/bin/forward-to-chatwoot.sh
  ${nexthop} ${user}

# forward-to-chatwoot.sh
#!/bin/bash                                                                                         

export HOME="/home/chatwoot"
export PATH="/home/chatwoot/.rvm/gems/ruby-2.7.1/bin:/home/chatwoot/.rvm/gems/ruby-2.7.1@global/bin\
:/home/chatwoot/.rvm/rubies/ruby-2.7.1/bin:/home/chatwoot/bin:/usr/local/bin:/usr/bin:/bin:/usr/loc\
al/games:/usr/games:/home/chatwoot/.rvm/bin"

export GEM_PATH="/home/chatwoot/.rvm/gems/ruby-2.7.1:/home/chatwoot/.rvm/gems/ruby-2.7.1@global"
export GEM_HOME="/home/chatwoot/.rvm/gems/ruby-2.7.1"

source "/home/chatwoot/.rvm/scripts/rvm"

cd /home/chatwoot/chatwoot && bin/rails action_mailbox:ingress:postfix URL='https://support.mycompany.com/rails/action_mailbox/relay/inbound_emails' INGRESS_PASSWORD='*******************************'

# End: forward-to-chatwoot.sh

# Behavior:

1. When a user is notified by email that there is a note added to their conversation, they can see their conversation in the email, however, when they elect to reply to the email, the reply-to address is the email of the agent not the email of the 'support system' as in the account setup to send outbound emails (shown above).

2. If you change the email 'To' field to the outbound address (in my case support@mycompany.com), the email does indeed make it to the Chatwoot DB in the correct tables (action_mailbox_inbound and action_mailbox_storage) as can be seen from the mail logs: 

# Log
mail postfix/pipe[12188]: 181DA7E2C: to=<support@support.mycompany.com>, relay=forward_to_chatwoot, delay=2.6, delays=0.12/0.01/0/2.4, dsn=2.0.0, status=sent (delivered via forward_to_chatwoot service (2.0.0 Successfully relayed message to ingress))

However the conversation is not linked to the actual Chatwoot INBOX or the Chatwoot conversation within this Chatwoot INBOX.

# Questions:

1.  What is email continuity?  Seems that the email back and forth is now happening external to Chatwoot.  Is this by design? Do I have something configured incorrectly?
2.  As there are no tokens or any otherwise linked methods created nor assigned to incoming or outgoing email headers there seems to be no way to link email and chat widget conversations. And Further, no way to create tickets via unsolicited inbound emails to the defined outgoing support account.  

# Requests:

1.  Can we have Chatwoot treat incoming and outgoing email as conversations linked to INBOXES and CONTACTS?
2.  O365 Exchange email flows will allow me to pipe email to an address with an access token and a password  but the infrastructure is not build into the ActionMailbox framework - at least I could not get it to work.  In order to use postfix pipes I have to install an MTA on the chatwoot box and play forward the email.  Thus my support@mycompany.com in O365 must be forwarded to another email address (support@support.mycompany.com) managed by a Postfix MTA then piped to Rails via the ActionMailbox API.  Cludgy!  I would like to see this process tightened if at all possible.
3.  There is a support mailer in the environment that looks like it could be used to do what is needed here to link emails to conversations but it does not seem to be linked to anything (looks like a stub - setup to be built out later?).  Is there any documentation regarding this mailer with instructions for use?
4.  Priority:  What must be done to impress upon you the value of true conversation continuity via emails in/out of Chatwoot?  How can I up the priority for this functionality such that it can be built?

# Thank You!

**Comment by pranavrajs** [comment]
@icjohnson There are 2 concepts, email inboxes and conversation continuity. Hope the following diagram helps you understand it better.

<img width="762" alt="Screenshot 2020-12-07 at 10 50 24 PM" src="https://user-images.githubusercontent.com/2246121/101382999-9b0abf00-38de-11eb-845d-1bb1f52306df.png">

I guess this would answer your question. We don't have documentation on email inboxes as we were testing it out internally for some time. I'll see if I can put up something which would help you to create email inboxes.

On requests:

> Can we have Chatwoot treat incoming and outgoing email as conversations linked to INBOXES and CONTACTS?

Yes, this is how it works.

> O365 Exchange email flows will allow me to pipe email to an address with an access token and a password but the infrastructure is not built into the ActionMailbox framework - at least I could not get it to work. In order to use postfix pipes I have to install an MTA on the chatwoot box and play forward the email. Thus my support@mycompany.com in O365 must be forwarded to another email address (support@support.mycompany.com) managed by a Postfix MTA then piped to Rails via the ActionMailbox API. Cludgy! I would like to see this process tightened if at all possible.

Unfortunately, you can not directly retrieve email from every service provider. The easier way to do this is to forward to an email address which would be relayed to Chatwoot. In your case, Postfix or any other service provider like SendGrid incoming hooks should be used. I don't see any other easy way to do this. Also, this is a one-time setup.

> There is a support mailer in the environment that looks like it could be used to do what is needed here to link emails to conversations but it does not seem to be linked to anything (looks like a stub - setup to be built out later?). Is there any documentation regarding this mailer with instructions for use?

As I mentioned above, as it is under beta testing for a while we have not written any public docs yet. I would try to write something this week.

> Priority: What must be done to impress upon you the value of true conversation continuity via emails in/out of Chatwoot? How can I up the priority for this functionality such that it can be built?

At the moment, I think the email channel docs would make this request work.

Please let me know your thoughts.

**Comment by icjohnson** [comment]
Fantastic - That would be great!

Any help you can provide to help me get this working would be a boon.

Thank You,

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by icjohnson** [comment]
Sorry,

In the conversation continuity diagram below, step 3, when the user hits reply, it is the 'agents email address' that populates the "To:" address in the reply rather than an email address that routes to the ActionMailbox API. If I manually populate the "To:" address to the email of the account that forwards to ActionMailbox the conversation isn't linked (ie can't see the reply chatwoot) either.

Either way, hitting reply on the email and accepting the way the email is populated or changing the 'To:' field to support@mycompany.com, the reply don't make it into the conversation in the chatwoot conversation window.

Not sure why given your explanation below.

Ian

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pranavrajs** [comment]
@icjohnson This is happening because your setup is not complete. It would be of the format < reply+{some_random_hex_id}@subdomain.yourdomain.com>. Once the doc is up, you should be able to set it up.

**Comment by icjohnson** [comment]
Great - I'll await your doc with great interest...

Thank so very much!

Ian

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by icjohnson** [comment]
Sorry to bother pranavrajs.  Is there an ETA on this document as of yet?  Thanks!

**Comment by daghendrik** [comment]
Also looking for documentation on this. Having trouble getting conversation continuity to work. Using caprover and the latest version (v1.11.0)

**Comment by pranavrajs** [comment]
@icjohnson @daghendrik Sorry for the delay. I will get to the documentation this week.

**Comment by joeczucha** [comment]
I'm having similar issues to @icjohnson, but using Mandrill:

1) The email sent to a user has the FROM address set correctly but the REPLY TO address is the agent's own email address. @pranavrajs mentioned that this was because "your setup is not complete" but I can't find anything in the documentation about what additional steps need to be taken.

2) Manually overriding the email when composing a reply - the email is arriving at Mandrill, being forwarded to the webhook and being received by Chatwoot. I've just checked in rails console and I can see that there are 3 `ActionMailbox::InboundEmail` with a status of `pending`and that the `ActiveStorage::Blob` objects are also created. 

However, nothing appears in the conversations.

**Comment by nm** [comment]
+1 for documentation on this. Trying to get this working using Postmark.

**Comment by srameshr** [comment]
@pranavrajs Can we use AWS SES for email continuity? Currently, we are using the organizations AWS SES to send a confirmation email once   the staff team registers

**Comment by sojan-official** [comment]
we have added instructions to enable email channel 
https://www.chatwoot.com/docs/self-hosted#email-channel-setup 

if there are further issues in email or conversation continuity let's start a discussion and capture it there.
