### ISSUE TITLE
Start conversation

### ISSUE THREAD

**Issue by DataTables** [chatwoot/chatwoot#1497]
**Is your enhancement request related to a problem? Please describe.**

I've been surprised by how few conversations we've had with customers through chatwoot (that's nothing against chatwoot - I'm just explaining where I'm coming from with this request!) - so I was wondering if I could start a conversation with customers on the site.

**Describe the solution you'd like**

The admin pages could show a list of current users on the site with the option to start a chat with them. "Hi - I'm Allan - how's it going?".

**Describe alternatives you've considered**

I've dug around, but can't see such an option in chatwoot already?

**Additional context**

N/A

**Comment by pranavrajs** [comment]
@DataTables We don't have that feature right now, but I guess it would be solved by #1475. I'm interested in knowing whether you had a live chat before and you experience lesser conversations now?

**Comment by pranavrajs** [comment]
@DataTables If you feel #1475 would solve the issue you are having, please close this one. Otherwise please feel free to provide your thoughts.

**Comment by DataTables** [comment]
Brilliant, thanks for the fast reply. I agree the other issue covers my feature request. Apologies, I did search before and didn't find it. 

Chatwoot is our first chat app, so I've not no other usage to base a comparison on I'm afraid. Having used the client side interface, I don't think it can be down to chatwoot - the clientside interface is intuitive!
