### ISSUE TITLE
Conversations loading freeze on Agent Delete

### ISSUE THREAD

**Issue by vishal-pandey** [chatwoot/chatwoot#1499]
When we delete Agent who had conversation assigned before, conversations in all tab do not load.

I am attaching the error message from the terminal which we got.

![Screenshot from 2020-12-07 15-11-47](https://user-images.githubusercontent.com/19498820/101498535-3741ce00-3992-11eb-9053-56525b35d253.png)

**Comment by pranavrajs** [comment]
@vishal-pandey This is happening because the conversation is not unassigned when the user is removed from the account. We will fix it soon.

**Comment by vishal-pandey** [comment]
Thanks @pranavrajs 🙂
