### ISSUE TITLE
Add rubocop & eslint to the circle ci runs 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#151]
- [ ] Add rubocop to circle CI 
- [ ] Add eslint to circle CI runs

**Comment by pathaknv** [comment]
@pranavrajs I could pick this one.

**Comment by pranavrajs** [comment]
@pathaknv Thanks. Please feel free to work on this, I've assigned the issue to you.

**Comment by sabunt** [comment]
I used rubocop todo

**Comment by sabunt** [comment]
@pranavrajs  please merge my PR #168

**Comment by sojan-official** [comment]
fixed in #168
