### ISSUE TITLE
Can't assign & Get List of Agent bot

### ISSUE THREAD

**Issue by fiantinangon** [chatwoot/chatwoot#1510]
**Describe the bug**

i've created agent bot using rails command,and also I've got the agentbot token but when I trying to get lists agent bot using `/agent_bots` the list is empty

<img width="817" alt="Screen Shot 2020-12-14 at 9 43 34 AM" src="https://user-images.githubusercontent.com/9161278/102034855-9d46af00-3df1-11eb-8fd2-04b50f62964d.png">
<img width="1018" alt="Screen Shot 2020-12-14 at 9 44 50 AM" src="https://user-images.githubusercontent.com/9161278/102034867-a2a3f980-3df1-11eb-99ac-fe38557ebc7b.png">

And when I hit API to assign agent bot to an inbox, I got response 
```
{
    "error": "Resource could not be found"
}
```

<img width="1017" alt="Screen Shot 2020-12-14 at 9 45 10 AM" src="https://user-images.githubusercontent.com/9161278/102034929-cc5d2080-3df1-11eb-95dd-4643f1ab2c9c.png">

**To Reproduce**

1. Create agent bot using rails console
2. Fetch agent bot using API 
3. The agent bot list is empty
4. Assign agent bot using API
5. See error

**Expected behavior**

After creating agent bot from rails console, the agent bot should return while getting agent bot list API, and the agent bot can assign to the inbox using set_agent_bot API

**Comment by sojan-official** [comment]
In the URL you are sending the request you need to change  `:account_id`  and `:inbox_id` to the numeric account id and inbox ids.

**Comment by fiantinangon** [comment]
> In the URL you are sending the request you need to change `:account_id` and `:inbox_id` to the numeric account id and inbox ids.

Yes I've set the value through postman param field 
<img width="1019" alt="Screen Shot 2020-12-15 at 4 05 28 AM" src="https://user-images.githubusercontent.com/9161278/102135763-03cbdb80-3e8b-11eb-91ba-6af7e7c55aff.png">

**Comment by sojan-official** [comment]
@fiantinangon  Could you check the `Rails.env` value of the console and your rails server?  Make sure both of them are the same.  
The `GET /agent_bots` doesn't have any conditions associated so its stumps me that the endpoint returns nil even when you have records in the database. Only thing I can think of is the console could be running in `development` environment and rails server in `production` env or vice versa. 

If it is not working, will be happy to jump on a call and resolve the issue.

**Comment by fiantinangon** [comment]
> @fiantinangon Could you check the `Rails.env` value of the console and your rails server? Make sure both of them are the same.
> The `GET /agent_bots` doesn't have any conditions associated so its stumps me that the endpoint returns nil even when you have records in the database. Only thing I can think of is the console could be running in `development` environment and rails server in `production` env or vice versa.
> 
> If it is not working, will be happy to jump on a call and resolve the issue.

Thanks @sojan-official I've rechecked and yes the suspect is miss `env` as you thought , This issue has ben resolved thanks
