### ISSUE TITLE
Trouble with Enabling IP Logging

### ISSUE THREAD

**Issue by daghendrik** [chatwoot/chatwoot#1521]
Updated Caprover to the latest version (v.1.11.0). Followed the instructions at https://www.chatwoot.com/docs/self-hosted/enable-ip-logging for enabling IP Logging. Added ENV variables as per documentation

Logged into both worker and web docker instances (caprover) and executed the rails command to set my account id.

Failed on second command (account = Account.find(account_id)):

```
Traceback (most recent call last):
        1: from (irb):2
ActiveRecord::RecordNotFound (Couldn't find Account with 'id'=XXXXXX)
```

Using the Account ID / API Key from the  "Services" > "My License Key" page on MaxMind:

![image](https://user-images.githubusercontent.com/1830026/102334545-13344d00-3f8f-11eb-86a7-c9d9131b7bda.png)

**Comment by pranavrajs** [comment]
@daghendrik The account id should the Chatwoot account id. Your URL will be like `<your-installation-url>/app/accounts/<account-id>/dashboard`. I think we need to change the doc to indicate that the account_id is the chatwoot account_id not the Maxmind DB id.

**Comment by daghendrik** [comment]
@pranavrajs Thanks! That makes sense. It worked :-)
