### ISSUE TITLE
Add href to "initiated from" url

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1522]
**Is your enhancement request related to a problem? Please describe.**
Users approach us when surfing different articles on our project and comment on details of those articles. To quote the article, I need to open it myself and not only know the url, so I have to copy the url to get there.

**Describe the solution you'd like**
Please wrap the `Initiated from [url]` with a `href`: `<a href="[url]">Initiated from [url]</a>`

**Comment by pranavrajs** [comment]
This is a nice suggestion, we will consider in this sprint.
