### ISSUE TITLE
Move Pushercall in PusherListener to sidekiq background jobs

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#154]
We are making  API calls to pusher in PusherListener.

```
app/listeners/pusher_listener.rb
```

We should add a sidekiq job to handle this call in the background.

**Comment by lnarayan92** [comment]
@sojan-official I could pick this one

**Comment by sojan-official** [comment]
@lnarayan92  please go-ahead

**Comment by sojan-official** [comment]
@lnarayan92  Hey there, we recently removed pusher in favor of action cable. Might affect this issue slightly.  Just a heads up if you are still working on this.

**Comment by lnarayan92** [comment]
@sojan-official Thanks for the heads up, I had just started with this issue. 
what is the plan going forward?

**Comment by sojan-official** [comment]
@lnarayan92 whatever happened in `pusher_listener` now happens in `app/listeners/action_cable_listener.rb` .  we can move the  `send_to_members`  method to sidekiq.  

In short. we move the `action cable broadcasts to background job` .  let me know if you have any questions.

**Comment by lnarayan92** [comment]
got it, thanks!

**Comment by mbronek7** [comment]
Hi I would like to work on this issue as my first  open source contribution with ruby ;)

**Comment by mbronek7** [comment]
Hi Could you give me some feedback

**Comment by sojan-official** [comment]
@mbronek7  thanks a lot for working on this.  
will check the PR over this weekend and will let you know our thoughts
