### ISSUE TITLE
Conversations are not shown if the user is agent

### ISSUE THREAD

**Issue by SmartManoj** [chatwoot/chatwoot#1543]
**Describe the bug**

If he is assigned as Admin, it shows.

**Browser logs**

No logs

**Server logs**

No errors

**Environment** Heroku

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 87

**Comment by pranavrajs** [comment]
@SmartManoj Can you please provide a screencast of the bug?

**Comment by SmartManoj** [comment]
![image](https://user-images.githubusercontent.com/7231077/102973801-6a07cc80-4523-11eb-88a4-c4806db23e61.png)
Agent screen

**Comment by pranavrajs** [comment]
Please add the user to the inbox in Inbox settings. Settings -> Inbox -> Settings -> Collaborators -> Add the agent there.

**Comment by pranavrajs** [comment]
@SmartManoj Please close this issue if the above-mentioned step works for you.

**Comment by SmartManoj** [comment]
> Agent screen
> ![image](https://user-images.githubusercontent.com/7231077/102974164-1944a380-4524-11eb-998f-f467fc843dc9.png)
> 
> Admin screen
> ![image](https://user-images.githubusercontent.com/7231077/102974254-34afae80-4524-11eb-89bc-fd672d1d377c.png)
> 
> Agents List
> ![image](https://user-images.githubusercontent.com/7231077/102974279-3ed1ad00-4524-11eb-86d3-e9b3073fdd5e.png)

Edited

**Comment by pranavrajs** [comment]
Please post the screenshot of "Whatsapp channel settings -> Collaborator tab".

**Comment by SmartManoj** [comment]
> Please add the user to the inbox in Inbox settings. Settings -> Inbox -> Settings -> Collaborators -> Add the agent there.

This Solved

**Comment by SmartManoj** [comment]
Then only admins and collaborators should be shown in assign agent field. Right?

**Comment by pranavrajs** [comment]
Yeah is it showing the list of all agents irrespective of permissions?

**Comment by nithindavid** [comment]
@SmartManoj Closing this as there is no response. Please reopen if you are still facing this issue.
