### ISSUE TITLE
Report matrix base on label

### ISSUE THREAD

**Issue by fiantinangon** [chatwoot/chatwoot#1544]
**Is your feature request related to a problem? Please describe.**
We have a use case where labels have an important role in business processes, so we need more matrix related to label, for example: how much conversation on label A this month/week, and growth conversation on that label

**Describe the solution you'd like**
Add more matrix related to label data on the report

**Comment by pranavrajs** [comment]
@fiantinangon There is already an issue on this. Closing this as it is a duplicate of #1217
