### ISSUE TITLE
feat: Export Contacts

### ISSUE THREAD

**Issue by fiantinangon** [chatwoot/chatwoot#1545]
**Is your feature request related to a problem? Please describe.**
This feature helps the user to download contact data (name/phone/email/etc.) as csv files

**Describe the solution you'd like**
Add download contact button on the contact list

**Comment by pranavrajs** [comment]
This is a nice suggestion, we have thought about import/export contacts. We will consider this in future releases.

**Comment by shyjal** [comment]
This is a necessary feature. Export and import of contacts.

**Comment by sojan-official** [comment]
In interim, 
- contacts could be downloaded iterating through the API
- We also have an API to upload a contacts CSV ( ref: https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Importing-Existing-Contacts-and-Creating-Conversations#use-the-api )

**Comment by HSE-Group** [comment]
We are interested in using Chatwoot as our chat tool, but the export contacts feature is very important to pass them to other software... or if there was an integration with HubSpot, Orocrm, Suitecrm or Odoo crm....

**Comment by sojan-official** [comment]
note from #4788 
> I would like to be able to export `all the contacts or the result of a contact filter` from the dashboard in cvs format

**Comment by ankitgupta-unthinkable** [comment]
> 

Hi there,

Did you find any help or support on how to integrate Odoo with Chatwoot? I am also trying to integrate Odoo to help the agents to get information faster.

**Comment by lpadula** [comment]
> We are interested in using Chatwoot as our chat tool, but the export contacts feature is very important to pass them to other software... or if there was an integration with HubSpot, Orocrm, Suitecrm or Odoo crm....

Any update of this?

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/7258
