### ISSUE TITLE
[CW-2073] feat: Show Number of Unread Conversation on Page Title 

### ISSUE THREAD

**Issue by Regerta** [chatwoot/chatwoot#1546]
**Is your feature request related to a problem? Please describe.**
I always open chatwoot on my browser tab but i rarely open it, sometimes i miss messages from my clients (even with push notification enabled).

**Describe the solution you'd like**
- Adding realtime number of unread message or conversations on page title. eg: (15) Chatwoot
  Where (15) is number of current unread messages.

- And if possible, add autoplay sound with repeat function like phone ringtone when there's new conversation.

<sub>[CW-2073](https://linear.app/chatwoot/issue/CW-2073/feat-show-number-of-unread-conversation-on-page-title)</sub>

**Comment by pranavrajs** [comment]
@Regerta Thanks for the suggestion. This is a nice one! We can bring this in.

**Comment by scmmishra** [comment]
Great idea, we can also update the favicon with it
