### ISSUE TITLE
Frontend(webpack) not updating in test environment

### ISSUE THREAD

**Issue by RonWalker22** [chatwoot/chatwoot#1565]
**Describe the bug**
Frontend(webpack) is not updating when running chatwoot in test environment.

Even when I restart the servers, changes don't show up. Looks like it took a snapshot of the frontend and won't update.

**To Reproduce**

1. follow [this guide](https://github.com/chatwoot/chatwoot/wiki/Cypress-Tests-for-chatwoot) to prepare database and start chatwoot in test environment. 
2. make a change to the frontend
3. reload the page

**Expected behavior**

Changes to the frontend from my editor should show up. 

**Additional context**

I'm attempting to run cypress following [this guide](https://github.com/chatwoot/chatwoot/wiki/Cypress-Tests-for-chatwoot). Cypress works fine, but the frontend not updating is the issue. Also when I use Cypress in dev environment everything works as it should.

 It does respond to changes on the backend.

**Comment by pranavrajs** [comment]
@RonWalker22 I'm not sure whether I understood the problem, can you please provide me with a little bit more context on what you are trying to achieve? Are you trying to write test cases?

**Comment by RonWalker22** [comment]
I have written many cypress tests for chatwoot and they all work fine, as you can see [here](https://vimeo.com/495747621). The only issue is that I have to run the tests in a development environment instead of a test environment. 

When I attempt to run the cypress in a test environment the frontend is not updating. So let’s say I add a class to an element, the frontend will recompile but the element will render without the added class. Even when I restart the entire application, none of my changes on the frontend appear. 


The issue is not really with cypress as it does its job in both environments, I just added that for additional context for what I’m ultimately trying to achieve. The issue is that frontend not updating in the tests environment. 

I also tested this issue with a clean install of chatwoot, with the same results. 

Below is how I started chatwoot in test environment


```
#prepare database
RAILS_ENV=test bin/rake db:drop
RAILS_ENV=test bin/rake db:create
RAILS_ENV=test bin/rake db:migrate
RAILS_ENV=test bin/rake db:seed

# start chatwoot in test environment 
overmind start  -f Procfile.test RAILS_ENV=test
```
