### ISSUE TITLE
Email inbox is disabled in the latest version.

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1566]
**Describe the bug**

The UI to activate the email inbox is disabled in the latest version of the app hosted on heroku.

**To Reproduce**

1. Go to '/app/accounts/1/settings/inboxes/new'
2. Click on 'Email'
3. See an interaction error where the UI is disabled with a not supported message above.

**Expected behavior**
 Email should be available as a channel because there was a commit request that went in to support this channel in the previous versions.

**Screenshots**

**Browser logs**

N/A

**Server logs**

N/A

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

Self-hosted the latest image on Heroku.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Mojave
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 1.11

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] NA
 - OS: [e.g. iOS8.1] NA
 - Browser [e.g. stock browser, safari] NA
 - Version [e.g. 22] NA

**Additional context**

**Comment by sojan-official** [comment]
@srameshr The email inboxes are intentionally disabled since the feature isn't quite ready for production use. We are internally testing it out in beta, and it should be enabled across installations with in the next two releases.

**Comment by diego-vieira** [comment]
@sojan-official is there something we can do to help testing?
That’s the only feature that’s preventing me from using chatwoot. 

Many thanks

**Comment by kmander** [comment]
@sojan-official I'm also in the same boat as @diego-vieira – we, unfortunately, can't consider switching to Chatwoot until an email inbox feature is enabled. Happy to be involved in testing this and providing feedback.

**Comment by srameshr** [comment]
Amy estimations on when the next release with this feature enabled will be
released?

**Comment by pranavrajs** [comment]
@kmander @srameshr We would allow you to test it in the release which is going out tomorrow. We will add instruction for the same.

 #1659 was an ugly piece which has to be resolved before putting it for public beta.

**Comment by srameshr** [comment]
@pranavrajs Can we do it?
