### ISSUE TITLE
Large file name overflow issue while previewing 

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1568]
![image](https://user-images.githubusercontent.com/1277421/103393828-e1a0b180-4b4a-11eb-89ac-a8e1c2dee7af.png)

**Comment by gucci-ninja** [comment]
Hey! Can I work on this?

**Comment by pranavrajs** [comment]
@gucci-ninja Sure, please feel to take it.

**Comment by nithindavid** [comment]
@gucci-ninja Sorry for the confusion, I updated the reply-box design, which fixed this issue in #1623. Let me know if you want to take up #1626

**Comment by nithindavid** [comment]
Fixed in  #1623

**Comment by gucci-ninja** [comment]
@nithindavid all good, I can take 1626
