### ISSUE TITLE
Chatwoot and whatsapp business api use together

### ISSUE THREAD

**Issue by taylanguneyaktas** [chatwoot/chatwoot#1571]
Hi,
Does anyone use whatsapp business api official with chatwoot  ?

I installed it on my own server, it works /  https://34.65.206.160:9090/

**Comment by pranavrajs** [comment]
@taylanguneyaktas At the moment, we don't have the official integration. We would like to build this. If you have official Business API access, we would like to talk to you. Can we connect over a call for more details? Please feel free to schedule a call at https://calendly.com/chatwoot

**Comment by taylanguneyaktas** [comment]
.

**Comment by taylanguneyaktas** [comment]
.

**Comment by viapratica** [comment]
> Olá,
> Alguém usa o oficial da API de negócios do WhatsApp com o chatwoot?
> 
> Instalei no meu próprio servidor, funciona / https://34.65.206.160:9090/

We were integrating with an unofficial API, we reached 60% of the project but decided to suspend the investment by the hour. There are some peculiarities of Chatwoot that invibialize the direct integration. You need to create a connector between the API, whether official or not.

**Comment by viapratica** [comment]
> Hi,
> Does anyone use whatsapp business api official with chatwoot ?
> 
> I installed it on my own server, it works / https://34.65.206.160:9090/

We were integrating with an unofficial API, we reached 60% of the project but decided to suspend the investment by the hour. There are some peculiarities of Chatwoot that invibialize the direct integration. You need to create a connector between the API, whether official or not.

**Comment by pranavrajs** [comment]
@viapratica Anything we can help on this? Are you using the API channel?

**Comment by taylanguneyaktas** [comment]
hi,
delete all issue delete , please
