### ISSUE TITLE
Avoid Reply box resetting to normal message after sending a private note

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1577]
Right now, after a private note is sent to the customer, the reply box resets automatically to normal message behaviour. This creates confusion and agent would send a private note without realizing that the message type is reset to normal message

Acceptance criteria:

- Stay at the same message type even after a message is sent. ie; If the agent has sent a private note, the message type should stay as a private note.

**Comment by nithindavid** [comment]
Closing as this is fixed.
