### ISSUE TITLE
Use dynamic literals for label name in activity messages.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1579]
Use `{{labelId:labelName}}` instead of the hardcoded string in the activity messages.

Acceptance criteria:

- Label names are dynamic.
- Ability to click on the label name, this would display all the conversations tagged with the label.

**Comment by sojan-official** [comment]
should be  `{{label:id}}`  ? where we transform the string dynamically and convert it to label name ?
