### ISSUE TITLE
Switch from carrierwave to active storage for avatars and attachements

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#158]
- we use carrierwave aws : this should be changed to active storage for avatars and attachments

**Comment by nursoltan-s** [comment]
@sojan-official 
Hi, can you assign me to this issue?

**Comment by sojan-official** [comment]
@nursoltan-s I have assigned the issue, let us know if you need any help.

**Comment by sojan-official** [comment]
@rojasTob  Could you give this a check. if it's not the right fit, will find another one for you.

**Comment by rojasTob** [comment]
> @rojasTob Could you give this a check. if it's not the right fit, will find another one for you.

@sojan-official I will try to solve it.

**Comment by sojan-official** [comment]
@rojasTob  at this point we don't have to care about backward compatibility. there is no production systems running the software.  so we can switch over and call it day.  

so basically 
- add active storage 
- remove the existing avatar field 
- port the functionality to the active storage way and make sure it works

with active storage, people who want to run the system would have more options to choose the cloud provider they want with a simple switch of config. + carrierwave I believe would be slowly deprecated, in favor of the built-in solution from rails.

let me know if you have any questions.

**Comment by pranavrajs** [comment]
@karthik-sivadas Would you be interested to take a look at this one?

**Comment by karthik-sivadas** [comment]
@pranavrajs yeah sure. If no one working on this  then I will start working on this.

**Comment by rojasTob** [comment]
@pranavrajs  Hi, I was working on this. Sorry for my late message :(

**Comment by sojan-official** [comment]
@rojasTob  You can continue working on this. Meanwhile, if you need any help feel free to raise a WIP/Draft PR and we will be happy to help.

**Comment by rojasTob** [comment]
@sojan-official Thanks!

**Comment by sojan-official** [comment]
hey, @rojasTob do you have a branch on which you are working?  I am working on profile pictures for agents and would like to do it with active storage.  

I could build on top of what you have, so we won't have to duplicate the effort.

**Comment by rojasTob** [comment]
Hi @sojan-official , sorry for my late answer. I was working on a branch of a forked project. These days I have not worked on that, sorry I was sick. I hope to continue this week. I apologize.

**Comment by sojan-official** [comment]
@rojasTob no worries, i hope you are feeling better now.  We ended up adding active storage for the work we did over user model. 

But avatars and attachments still remain with carrierwave, so feel free to continue with this issue. Good luck and thanks a lot again for working on this.
