### ISSUE TITLE
chore: Improve Conversation Auto resolution job logic

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1583]
When we implement the conversation auto resolution job, chatwoot didn't have a mechanism to implement cronjobs, Now that we have `sidekiq-cron` . let's revisit this implementation.  

## Current Logic 
A single job is enqueued for each conversation to keep track of resolution. It also gets re-enqueued when the conversation is reopened 
ref: https://github.com/chatwoot/chatwoot/blob/a2764e5c1dbd65abbf6e26d50d974d39d4bb1ffc/app/models/conversation.rb#L174

## Proposed Logic
Add a hook into scheduled jobs and follow a Model similar to how we execute the campaign jobs.  
ref: https://github.com/chatwoot/chatwoot/blob/a2764e5c1dbd65abbf6e26d50d974d39d4bb1ffc/app/jobs/trigger_scheduled_items_job.rb#L6

- [ ] scheduled jobs will iterate over accounts with auto resolution configured and scheduled a new account conversation resolution job 
- [ ] Account conversation resolution job will fetch conversations that has passed auto resolution time period and will resolve them 
- [ ] Clean up the existing logic that schedules a single job per conversation.

**Comment by shivamsinghchahar** [comment]
Hi @pranavrajs Can I take this up?

**Comment by sojan-official** [comment]
@shivamsinghchahar  please feel free to go ahead.  I have updated the issue description with necessary details

**Comment by shivamsinghchahar** [comment]
@sojan-official Thanks a lot for the updated description! I have raised a PR. Could you take a look?
