### ISSUE TITLE
Save the state of contact sidebar (open/closed)

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1585]
Instead of the default open state, save the last state of the contact sidebar against each user and display the sidebar based on that value.

Acceptance criteria:

- Create a new DB model for each user `UserUISettings` or something similar
- Save the state of contact sidebar in DB
- Load the settings on initial load, display the sidebar based on the flag available.

**Comment by murtaza-bagwala** [comment]
@pranavrajs shall I pick this up ?

**Comment by pranavrajs** [comment]
@murtaza-bagwala This is already completed in one of the other PRs.
