### ISSUE TITLE
Allow admins to configure a section in the contact sidebar to display an iFrame

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1587]
If there is an external system which has information about the customer that needs to be displayed to the agent, there should be some sort of integration between the systems. As a first step towards this, we can start with allowing the admins to configure an iframe to be displayed on the sidebar.

- Create a section in settings to configure sidebar widgets
- Allow admins to configure a URL with/without authentication, provide `contact` and `conversation` as a context to the builder
- Display the iFrame whenever an agent opens a conversation.

Note: This is a feedback from a customer. The feature is completely spec-ed out. @sojan-official Can you review this and add your thoughts?

**Comment by andrezimpel** [comment]
This would be very valuable for my customers too!

**Comment by pranavrajs** [comment]
Closing this via #4761
