### ISSUE TITLE
Autogenerate push notification keys

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1589]
Right now, our users have to generate a VAPID key and update in the ENV for the browser notification to work. This is an unnecessary additional step.

- Autogenerate VAPID keys on installation or initial boot. (https://github.com/zaru/webpush#generating-vapid-keys)
- Save the generated VAPID keys to the database and cache it in Redis along with global cache.
- Use it for registering push notification on the web.

This reduces a step to install Chatwoot. 🔥

**Comment by FatGrizzly** [comment]
@pranavrajs @sojan-official Any updates on this?

**Comment by sojan-official** [comment]
@FatGrizzly The team isn't actively working on this at the moment. This issue is open for contributions.

**Comment by santhosh-chinnasamy** [comment]
@sojan-official I would like to work on this feature.

**Comment by muhsin-k** [comment]
@santhosh-chinnasamy Sure. Please feel free to go ahead.

**Comment by santhosh-chinnasamy** [comment]
@sojan-official / @muhsin-k can you review the pull request ?
