### ISSUE TITLE
Change the way mobile notifications are described

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1591]
**Current**
- A new conversation ID-34 has been created

**Proposed**
- [New ticket] - Conv-34 has been created in chatwoot
- [Assigned to me] - Conv-34 has been assigned to you
- [New message] - New message in conv -34

**Why**
It's difficult to filter the idea from the notification message as every notif text looks the same.

**Comment by pranavrajs** [comment]
@sojan-official This seems to be a low hanging fruit, would you be able to take this up soon?
