### ISSUE TITLE
MinIO configuration

### ISSUE THREAD

**Issue by LucasMilhomem** [chatwoot/chatwoot#1596]
I followed the instructions to configure minIO as object storage and it doesnt work

i've configured chatwoot on docker-compose along side with redis and postgres, now im trying to add minio(i dont know if its the best option as simple object storage) but look like he doesn't use my bucket, i might be missing something in this config, so im trying to use the documentation config like this:

      - ACTIVE_STORAGE_SERVICE=s3_compatible
      - STORAGE_BUCKET_NAME=chatwoot
      - STORAGE_ACCESS_KEY_ID=minioAccessKey
      - STORAGE_SECRET_ACCESS_KEY=minioSecretKey
      - STORAGE_REGION=sa-east-1
      - STORAGE_ENDPOINT=http://localhost:9000

but when i send a file in chat i got this error:

<Error>
	<Code>NoSuchBucket</Code>
	<Message>The specified bucket does not exist</Message>
	<BucketName>d4v7u86scqh0cb3xlh1wtd6juynt</BucketName>
	<Resource>/d4v7u86scqh0cb3xlh1wtd6juynt</Resource>
	<RequestId>16551A91E1CE267D</RequestId>
	<HostId>8783e922-9ee0-4f44-822e-33675e493bd1</HostId>
</Error>

if i force the bucket name on storage_endpoint like the config below he finds the bucket but i got this NoSuchKey error:

<Error>
	<Code>NoSuchKey</Code>
	<Message>The specified key does not exist.</Message>
	<Key>eyivthgu6buyjokd4gpfoumfnl9z</Key>
	<BucketName>chatwoot</BucketName>
	<Resource>/chatwoot/eyivthgu6buyjokd4gpfoumfnl9z</Resource>
	<RequestId>16551A700F97A593</RequestId>
	<HostId>8783e922-9ee0-4f44-822e-33675e493bd1</HostId>
</Error>

Then i searched for a issue like mine on chatwoot github and found about this STORAGE_FORCE_PATH_STYLE attribute that help with the case before, so chatwoot uses the right bucket and i dont need to force it anymore, but i keep receiving this noSuchKey error..

here is my minio simplest config on docker-compose:

storage:
    image: minio/minio
    volumes:
      - data-obj:/dataobj
    ports:
      - 9000:9000
    environment: 
      - MINIO_ACCESS_KEY=key
      - MINIO_SECRET_KEY=secret
    command: server /dataobj

**Comment by pranavrajs** [comment]
@LucasMilhomem Thanks for creating the issue, let me try to debug this during this sprint.

**Comment by pranavrajs** [comment]
@vishnu-narayanan Can you please go through this ticket in this release and confirm whether this bug still exists?

**Comment by vishnu-narayanan** [comment]
@LucasMilhomem I just tried using `minio` as the active storage backend and it seems to be working.

Could you please try and let us know if you are still facing issues ?


## Steps I followed

1. Spin up a new machine and install docker, docker-compose.
2. Run `minio` as a standalone container.

```
docker run \
  -p 9000:9000 \
  -p 9001:9001 \
  --name minio1 \
  -v /mnt/data:/data \
  -e "MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE" \
  -e "MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" \
  quay.io/minio/minio server /data --console-address ":9001"

```
3. Then I logged into the `minio` console(`http://<your-instance-ip>:9001`) and created bucket `chatwoot-assets`
4. Follow the chatwoot docs to get the `.env` and `docker-compose.yaml` file.
```
# Download the env file template
wget -O .env https://raw.githubusercontent.com/chatwoot/chatwoot/develop/.env.example
# Download the Docker compose template
wget -O docker-compose.yaml https://raw.githubusercontent.com/chatwoot/chatwoot/develop/docker-compose.production.yaml
```

5. Edit the `.env` file and add the `minio` bucket config.
```
ACTIVE_STORAGE_SERVICE=s3_compatible
STORAGE_BUCKET_NAME=chatwoot-assets
STORAGE_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
STORAGE_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
STORAGE_REGION=us-east-1
STORAGE_ENDPOINT=http://<your-instance-ip>:9000
STORAGE_FORCE_PATH_STYLE=true
```

6.  Also set the `redis` and `postgres` passwords.

```
# update redis and postgres passwords
nano .env
# update docker-compose.yaml same postgres pass
nano docker-compose.yaml
```

7. Prepare the database by running the migrations.

```
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
```

8.  Run Chatwoot.
```
docker-compose up
```

9. Now open Chatwoot, create a website inbox, and initiate a chat. Then try uploading a file. Watch the logs if needed and also browse the `minio` web console(`http://<your-instance-ip>:9001`) to see if the file is uploaded correctly.

**Comment by sojan-official** [comment]
closing this since the docs have been updated. We will reopen if required in the future.
