### ISSUE TITLE
Register new user API endpoint in community edition

### ISSUE THREAD

**Issue by randhipp** [chatwoot/chatwoot#1601]
**Is your feature request related to a problem? Please describe.**
can't register new user via API, only via web browser.

**Describe the solution you'd like**
I have a saas that register a new user, i would like to register a new user too in chatwoot via API, but it seem impossible now.

I need to have chatwoot account_id in return and saved it on my saas database

**Describe alternatives you've considered**
- Add super admin user and token for registering new user in chatwoot
- Add API endpoint for registering new user in chatwoot

**Additional context**
null

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/pull/1456 will cover this

**Comment by randhipp** [comment]
> #1456 will cover this


hi @sojan-official im testing new dev server using branch develop with merged feat/platform-apis
what to fill in this permissible_type ? 
or i need to to something in super_admin dashboard?

![image](https://user-images.githubusercontent.com/25372728/103876147-e266b400-5105-11eb-89f6-1c452a9419af.png)

![image](https://user-images.githubusercontent.com/25372728/103875868-86039480-5105-11eb-98aa-fe02a6e55718.png)

![image](https://user-images.githubusercontent.com/25372728/103876261-03c7a000-5106-11eb-99e4-fb763fd64073.png)

**Comment by sojan-official** [comment]
@randhipp  from the rails console create a platform app with the following command 

```
app = PlatformApp.create(name: 'xycapp`)
app.access_token.token
```

once you have the access token for platform app. you can do the following via the APIs
use this postman collection: https://www.getpostman.com/collections/7e83266e1db9d66ffa31


1.  Create an account 
2. Create a User
3. Create an Account User
4. Call Login User API to and authenticate the user to the system via sso URL


the PR isn't quite complete. so there could be gaps and breakages.

**Comment by randhipp** [comment]
> the PR isn't quite complete. so there could be gaps and breakages.

@sojan-official Thanks for pointing the right direction for me, just wanna try the possibility to integrating with my app as soon as possible. love the bleeding edge one  :smile: :smile:

**Comment by sojan-official** [comment]
@randhipp  this is merged to develop now.

**Comment by xiaoyunwu** [comment]
> app = PlatformApp.create(name: 'xycapp')
> app.access_token.token
@sojan-official should we still do this with 1.16.2 if we want to use the platform apis in #1456?
