### ISSUE TITLE
Change sidebar tag colors

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1608]
**Why?**
![image](https://user-images.githubusercontent.com/1277421/103670464-9ac61800-4f9f-11eb-9d78-d73c96bfda8c.png)
 The colors seem out of place with our current palette

**Comment by iammattmartin** [comment]
Can you give more detail as to the issue?

The tag colour is set when it is created and can be changed via the GUI (maybe even the API).

**Comment by pranavrajs** [comment]
@nithindavid The label colors are choosen by the user just like the way github label colors work. I don't think matching it to a color palette is feasible one. Closing this for now. Feel free to reopen if you think there is a room for improvement.
