### ISSUE TITLE
Websocket support to communicate with mobile apps

### ISSUE THREAD

**Issue by sorumehta** [chatwoot/chatwoot#1613]
**Is your feature request related to a problem? Please describe.**
Websocket connection with mobile clients, so that they can exchange messages with Chatwoot because they cannot listen to a webhook url

**Describe the solution you'd like**
From what I understand, right now a new message event is notified using a callback to the webhook url only. This works fine for servers, but isn't ideal for mobile apps. Its much easier for mobile apps to open a socket connection with the server and exchange messages using the socket connection.

Would love to know your thoughts on this.

**Comment by pranavrajs** [comment]
@sorumehta We already support websocket on the mobile app. Mobile apps exchange messages in realtime. Can you please provide a little bit more context on the issue you are facing?

**Comment by sorumehta** [comment]
@pranavrajs Oh! I guess I missed it because it wasn't mentioned in the API docs. Can you point me to a resource which can help me understand more on how to send messages to Chatwoot via websocket?

**Comment by sojan-official** [comment]
@sorumehta We don't have documentation for this yet. But if you take a look at how the chatwoot dashboard gets updated, you will get an idea.  Chatwoot instance has a WebSocket server open at `ws://localhost:3000/cable.` 

Each user in chatwoot has a pubsub token attribute used to subscribe to the updates coming through WebSocket.
So once the user connects to the socket.  He sends a subscribe command to get his updates. 

```
{"command":"subscribe","identifier":"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"nk8rgyBbqL1ED1f12YM87Fas\",\"account_id\":1,\"user_id\":1}"}
```
<img width="1927" alt="Screenshot 2021-01-06 at 1 29 44 PM" src="https://user-images.githubusercontent.com/73185/103744129-406e9b00-5023-11eb-83da-800b57d41508.png">
 
The socket server acknowledges the subscription and from there onwards keep sending events like conversation creation, contact presence etc.  

----

At the moment, the WebSocket endpoints are only used to push the updates to the client. All updates from the client like creating a message or so on are done via REST APIs. Except for a sole exception of presence updates from the client. 

Every minute the client sends a presence update to the server, letting it know that they are online. 
```
{"command":"message","identifier":"{\"channel\":\"RoomChannel\",\"pubsub_token\":\"nk8rgyBbqL1ED1f12YM87Fas\",\"account_id\":1,\"user_id\":1}","data":"{\"action\":\"update_presence\"}"}
```
---

At the moment, these WebSocket APIs are used only internally for the dashboard updates and our mobile apps. So it might not be as flexible as our public APIs. If there is more demand for the WebSocket APIs, we will invest more into it. Meanwhile, please take a look at what we have right now, and see if it suits your use cases.  Let us know if there are any gaps, and we will be happy to help.

**Comment by sorumehta** [comment]
@sojan-official  Thanks for the explanation.
