### ISSUE TITLE
Redis password not used for the default user, but set in env file

### ISSUE THREAD

**Issue by soerenCCC** [chatwoot/chatwoot#1618]
**Describe the bug**
The Frontend doesn't show up, just a short message that something went wrong.
<img width="571" alt="image" src="https://user-images.githubusercontent.com/45003287/103765252-2762eb80-501d-11eb-857e-43e804f34a5b.png">

The logs show:
```
rails_1     | I, [2021-01-06T11:34:38.098154 #1]  INFO -- : [8dcfbde8-be46-4984-9a9a-d06b1431cb29] Started GET "/" for 10.10.10.10 at 2021-01-06 11:34:38 +0000
rails_1     | I, [2021-01-06T11:34:38.100124 #1]  INFO -- : [8dcfbde8-be46-4984-9a9a-d06b1431cb29] Processing by DashboardController#index as HTML
rails_1     | I, [2021-01-06T11:34:38.103172 #1]  INFO -- : [8dcfbde8-be46-4984-9a9a-d06b1431cb29] Completed 500 Internal Server Error in 3ms (Allocations: 225)
rails_1     | F, [2021-01-06T11:34:38.105323 #1] FATAL -- : [8dcfbde8-be46-4984-9a9a-d06b1431cb29]   
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] Redis::CommandError (ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?):
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29]   
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] lib/global_config.rb:29:in `load_from_cache'
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] lib/global_config.rb:12:in `block in get'
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] lib/global_config.rb:11:in `each'
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] lib/global_config.rb:11:in `get'
rails_1     | [8dcfbde8-be46-4984-9a9a-d06b1431cb29] app/controllers/dashboard_controller.rb:11:in `set_global_config'
```

**To Reproduce**

.env file:
```
# Redis config
REDIS_URL=redis://redis:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=test123
# Redis Sentinel can be used by passing list of sentinel host and ports e,g. sentinel_host1:port1,sentinel_host2:port2
REDIS_SENTINELS=
# Redis sentinel master name is required when using sentinel, default value is "mymaster".
# You can find list of master using "SENTINEL masters" command
REDIS_SENTINEL_MASTER_NAME=
```

docker-compose -f docker-compose.production.yaml build
docker-compose -f docker-compose.production.yaml run --rm rails bundle exec rails db:reset
docker-compose -f docker-compose.production.yaml up

**Expected behavior**
See the frontend and container running with no error.

**Environment**
Debian 10
```
docker --version
Docker version 19.03.13, build 4484c46d9d
docker-compose --version
docker-compose version 1.21.0, build unknown
```

**Additional context**
I am new to docker and chatwoot. I was using this guide to get started: https://www.chatwoot.com/docs/installation-guide-docker

**Comment by pranavrajs** [comment]
@soerenCCC we will take a look at this

**Comment by milansimek** [comment]
@pranavrajs @soerenCCC I encountered the same issue. Seems it's related to the following difference between `docker-compose.yaml` and `docker-compose.production.yaml`:

Development compose:
https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.yaml#L100

Production compose:
https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml#L46

Note these two lines missing from the production file:

```yaml
command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
env_file: .env
```

After adding these lines, the error went away in my case.

**Comment by pranavrajs** [comment]
Sounds like the prod docker-compose is not updated. @milansimek Would you mind sending a pull request?

**Comment by soerenCCC** [comment]
> @pranavrajs @soerenCCC I encountered the same issue. Seems it's related to the following difference between `docker-compose.yaml` and `docker-compose.production.yaml`:
> 
> Development compose:
> https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.yaml#L100
> 
> Production compose:
> https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml#L46
> 
> Note these two lines missing from the production file:
> 
> ```yaml
> command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
> env_file: .env
> ```
> 
> After adding these lines, the error went away in my case.

worked for me. thank you!

**Comment by sojan-official** [comment]
we have updated docker deployment guides: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker . 
We will continue our work on documentation further.
