### ISSUE TITLE
BUG: Cannot create a new account: #<NoMethodError: undefined method `auto_resolve_duration' for #<Account:0x0000559f7dd5b548>>

### ISSUE THREAD

**Issue by sorumehta** [chatwoot/chatwoot#1621]
**Describe the bug**
While attempting to create a new account, getting the following in logs:
#<NoMethodError: undefined method `auto_resolve_duration' for #<Account:0x0000559f7dd5b548>>

**To Reproduce**

1. rails db:reset
2. Go to chatwoot app
3. Fill in signup details
4. Click submit 

**Expected behavior**

New account being created

**Screenshots**

**Server logs**

NoMethodError (undefined method `auto_resolve_duration' for #<Account:0x0000559f7ec46e68>):

app/builders/account_builder.rb:42:in `create_account'
app/builders/account_builder.rb:13:in `block in perform'
app/builders/account_builder.rb:12:in `perform'
app/controllers/api/v1/accounts_controller.rb:23:in `create'
app/controllers/application_controller.rb:18:in `handle_with_exception'
app/controllers/concerns/switch_locale.rb:24:in `set_locale'
app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

**Environment**
production

NOTE: I am using commit id: db189e3c26f3fbb22ff9fcebf320ac35c2f8a7a3 (chore: Sync the schema and migrations (#1610))

**Comment by pranavrajs** [comment]
@sorumehta Can you please share the entire logs after you do a db:reset? I could not reproduce this.

**Comment by sorumehta** [comment]
@pranavrajs Its working now for me too. Not sure what happened exactly. But I am closing the issue now. Will let you know if I encounter it again. Thanks
