### ISSUE TITLE
Add character count for reply box new UI

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1626]
**How**
- Show characters remaining warning message only when limit reaches 50 characters or less.

<img width="827" alt="Screenshot 2021-01-08 at 1 07 07 PM" src="https://user-images.githubusercontent.com/1277421/103987419-755d2800-51b2-11eb-961e-03a99dc47852.png">

@pranavrajs @sojan-official Any thoughts on the text used ?

**Comment by gucci-ninja** [comment]
I can work on this

**Comment by nithindavid** [comment]
@gucci-ninja Thabks for taking up, please branch out and work on top of #1623 which has the new reply box. Let me know if you need help.

**Comment by gucci-ninja** [comment]
@nithindavid what branch has the new reply box?

**Comment by nithindavid** [comment]
@gucci-ninja yes that's the one, there's 'ReplyBox' file, please see the changes in the above branch which had the same character counter, we just need to replicate the same code in new reply box.

**Comment by gucci-ninja** [comment]
@nithindavid Sorry for the questions. I don't have any dummy data to work with locally so it's a bit hard to test my changes. Any ideas on what to do?

**Comment by nithindavid** [comment]
@gucci-ninja We just need the count of characters inside reply box, SO by default there will be a chat in the local installation after you login, which should be enough to test this feature I guess. If you are stuck let me know, I'll explain in detail.
