### ISSUE TITLE
Bug: 404 Error in contactInboxCreation API

### ISSUE THREAD

**Issue by sorumehta** [chatwoot/chatwoot#1627]
**Is your enhancement request related to a problem? Please describe.**
The problem is that currently the API to create a new contact takes in "inbox_id" as a body parameter. And then you cannot use the same email_id again to start a conversation in another inbox of the same account. This is annoying, since each inbox belong to different channel/purpose and same user can belong to multiple inboxes.

**Comment by sojan-official** [comment]
@sorumehta  once you have the contact you can create a contact_inbox relationship with other inboxes as well.  
https://www.chatwoot.com/developers/api#operation/contactInboxCreation 

The intended flow is lookup for the contact using search API first if contact doesn't exist create it 
if it already exists you can either start a conversation using one of existing contact inbox source_ids 
or create a new content inbox relation and start the conversation using the newly generated source_ids

**Comment by sorumehta** [comment]
@sojan-official Thanks for the quick response! I tried the contactInbox creation API by sending a POST request to
https://app.chatwoot.com/api/v1/accounts/2651/contacts/1111823/contact_inboxes
Where 2651 is my account id and 1111823 is the contact id.

But I got 404- resource not found.

**Comment by pucilpet** [comment]
Actually I am doing this on a self hosted instance and I am getting the 404 error, too.

**Comment by sojan-official** [comment]
let me take a look and get back on this

**Comment by sorumehta** [comment]
@sojan-official  are you able to reproduce it at least?

**Comment by sorumehta** [comment]
@pranavrajs Are we going to investigate this further?

**Comment by sorumehta** [comment]
Okay figured it out. Docs don't say anything about passing inbox_id (although its pretty obvious). Closing the issue

**Comment by sojan-official** [comment]
@sorumehta  thanks for spotting that 🤦‍♂️ . I have raised a PR to fix the docs.
