### ISSUE TITLE
How to send image message via API?

### ISSUE THREAD

**Issue by xinjie-zhang** [chatwoot/chatwoot#1636]
https://www.chatwoot.com/developers/api#operation/conversationNewMessage

In this document, I could not find an example to send a message with image. Does anyone know how to do it?

**Comment by pranavrajs** [comment]
@xinjie-zhang Can you please try this postman collection? It has a sample on how to upload the file as a message. You would need to use multipart/form-data content and use `attachments[]` attribute to send the file. 

https://www.postman.com/collections/050de41bc0ed46e37663

**Comment by xinjie-zhang** [comment]
Great! It works. Are there any examples for other content type, like "input_email""cards""input_select""form""article" ?

**Comment by pranavrajs** [comment]
https://github.com/chatwoot/chatwoot/wiki/Creating-Bot-Messages-Types

Please check this wiki. Closing this as the original issue is solved.
