### ISSUE TITLE
Integrate widget into webpage inline

### ISSUE THREAD

**Issue by hartois** [chatwoot/chatwoot#1639]
Is it possible to integrate the chat widget inside the page, rather than as a pop-up element?

**Comment by sojan-official** [comment]
yes, you can trigger the chatwoot widget using 

```
window.$chatwoot.toggle();
```
https://www.chatwoot.com/docs/website-sdk#to-trigger-widget-without-displaying-bubble


Also, you can hide the bubble by default using the following config

```
window.chatwootSettings = {
  hideMessageBubble: true,
  position: 'left', // This can be left or right
  locale: 'en', // Language to be set
  type: 'standard', // [standard, expanded_bubble]
};
```

**Comment by hartois** [comment]
This is not exactly what I wanted:

![image](https://user-images.githubusercontent.com/11641656/104188371-3507df00-542a-11eb-8578-e1d27a4709c8.png)

I want the chat to be located inside the content as the arrow shows

**Comment by iammattmartin** [comment]
Check out #1325 and consider an iframe.

**Comment by hartois** [comment]
Thanks
