### ISSUE TITLE
feat: Separate webhook calls by inbox

### ISSUE THREAD

**Issue by pucilpet** [chatwoot/chatwoot#1645]
**Is your feature request related to a problem? Please describe.**
No, it's a feature request.

**Describe the solution you'd like**
I would like to be able to separate the webhook subscriptions by event and/or by channel/folder. So e.g. I would have a separate webhook post for folder 1 and event "message created" and a separate webhook for folder 3 and conversation closed.

**Additional context**
Right now we have 5 webhooks but as they fire for every event on every channel, we have hundreds of unnecessary webhook posts.

**Comment by pranavrajs** [comment]
@pucilpet Would it help if we give you an option to disable specific events?

**Comment by pucilpet** [comment]
> @pucilpet Would it help if we give you an option to disable specific events?

Yes, that would be a good start. 👍

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/4540 chatwoot now support subscribing to specific webhook events

**Comment by pranavrajs** [comment]
Closing this here as we have added support for event subscriptions. We will not be able to add support for single inboxes based subscriptions.
