### ISSUE TITLE
SMTP related environment variables not used in production.rb

### ISSUE THREAD

**Issue by milansimek** [chatwoot/chatwoot#1647]
Several variables present in the `.env` file are not being used in `config/environments/production.rb`

See `.env.example`:
https://github.com/chatwoot/chatwoot/blob/develop/.env.example#L51

`SMTP_AUTHENTICATION` and `SMTP_ENABLE_STARTTLS_AUTO` are configurable in this file.

However, in `production.rb` these values are hard-coded:
https://github.com/chatwoot/chatwoot/blob/develop/config/environments/production.rb#L108

Besides these two variables, it would be good to also have a `SSL_VERIFY_MODE` env variable.

Shall I create a pull request for this?

**Comment by sojan-official** [comment]
@milansimek  thanks for spotting that. feel free to go ahead.
