### ISSUE TITLE
Support location messages from Whatsapp in Chatwoot

### ISSUE THREAD

**Issue by josephktcheung** [chatwoot/chatwoot#1648]
**Is your enhancement request related to a problem? Please describe.**
From https://github.com/chatwoot/chatwoot/blob/dad737021f11f2e56d5d769e7161de55de9cc1fe/app/helpers/file_type_helper.rb#L2-L12, the message builder only supports `:image` and `:file` attachments. I wonder if we can extend the support to other existing file types as listed in `attachment.rb` https://github.com/chatwoot/chatwoot/blob/develop/app/models/attachment.rb#L24 through rest API 

**Describe the solution you'd like**
Create `audio`, `video`, `location` and `fallback` attachment via rest API

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by pranavrajs** [comment]
@josephktcheung I don't understand the issue here. We support any type of files. The method above is used for rendering, right now we only support image rendering, rest everything would be displayed as shown below.

<img width="314" alt="Screenshot 2021-01-14 at 1 44 00 PM" src="https://user-images.githubusercontent.com/2246121/104562591-915b4080-566e-11eb-85d8-c6a0e2419f27.png">

**Comment by josephktcheung** [comment]
@pranavrajs thanks for quick reply. Let's take location message as an example, I want to create a message with location latitude and longitude just like Facebook location message, how would I do that using the API?

**Comment by josephktcheung** [comment]
A bit more context:

We're using Chatwoot's custom API channel https://www.chatwoot.com/docs/channels/api/configure to connect to WhatsApp. We want to forward messages from WhatsApp to Chatwoot using the Rest API, which may contain image, audio, video, file, location messages.

I understand that Chatwoot's UI only supports image rendering https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/dashboard/components/widgets/conversation/Message.vue#L19-L28, but I wonder if I can at least save the message data into Chatwoot database e.g. lat / long / correct file type so that I can retrieve these information when fetching the `/messages` API (let's say we end up building our own custom UI).

**Comment by pranavrajs** [comment]
Just updating the title to "Support location messages in Chatwoot"

**Comment by sojan-official** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/issues/3398
