### ISSUE TITLE
Set a default image for a channel if profile image is not available

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#165]
- [ ] Inbox item is missing a default image

<img width="1532" alt="Screenshot 2019-10-20 23 02 30" src="https://user-images.githubusercontent.com/2246121/67163525-b559a480-f38d-11e9-933b-ae90edec5ee2.png">

**Comment by himynameisdave** [comment]
I can do this!

**Comment by pranavrajs** [comment]
@himynameisdave Please feel free to take it.

**Comment by josemiguelo** [comment]
Hi @himynameisdave. Are you still working on this? I can help :)

**Comment by himynameisdave** [comment]
@josemiguelo I am not, feel free to jump on it!

**Comment by Atsoamazed** [comment]
is this still open?

**Comment by pranavrajs** [comment]
@Atsoamazed Yes, it is. @josemiguelo Please reply if you are working on it.

**Comment by josemiguelo** [comment]
Yes. I am working on it. Sorry for the delay

**Comment by pranavrajs** [comment]
@josemiguelo Please don't be sorry. I just wanted to know if it is something you are working on.

Cheers.

**Comment by SarathSantoshDamaraju** [comment]
Is it still open?

**Comment by pranavrajs** [comment]
@SarathSantoshDamaraju Yeah, please feel free to take it.

**Comment by SarathSantoshDamaraju** [comment]
Sure !! Taking it.

**Comment by prabhumarappan** [comment]
@pranavrajs can we close this issue?

**Comment by pranavrajs** [comment]
@prabhumarappan Yeah! Thanks
