### ISSUE TITLE
Make contacts & conversation isolated in Inboxes 

### ISSUE THREAD

**Issue by dctmc** [chatwoot/chatwoot#1651]
it's be helpful if contacts and chats will be isolated in inbox/channel.. just operator connected to inbox  can view/share/make conversations

**Comment by pranavrajs** [comment]
@dctmc Can this be solved with multiple accounts?

**Comment by dctmc** [comment]
yes, can be solved, but in this case better to have an superuser option to manage user accounts in system using web interface.

**Comment by sojan-official** [comment]
@dctmc if you are using a self-hosted installation you can leverage our super admin interface to allocate multiple accounts across the users. 

https://github.com/chatwoot/chatwoot/wiki/Creating-a-super-admin-and-accessing-sidekiq

**Comment by VandrerenErik** [comment]
I'm getting the following error when trying to access:

![Untitled](https://user-images.githubusercontent.com/54407345/107934853-7aaf4e80-6f78-11eb-96cf-19864d1b8f28.jpg)

**Comment by sojan-official** [comment]
@VandrerenErik  Could you get us the logs from the backend if any ?

**Comment by VandrerenErik** [comment]
> @VandrerenErik Could you get us the logs from the backend if any ?

[scout_apm.log](https://github.com/chatwoot/chatwoot/files/5981635/scout_apm.log)

If there the log file you are looking for is another one, tell where to fetch it for you please.

**Comment by sojan-official** [comment]
@VandrerenErik  could you make the request and see 
```
cat /var/log/syslog
```

**Comment by VandrerenErik** [comment]
Here you have

[syslog.txt](https://github.com/chatwoot/chatwoot/files/5982227/syslog.txt)

**Comment by sojan-official** [comment]
@VandrerenErik I checked the logs and there aren't any errors except for the 401 unauthorized.
which version of chatwoot are you running? is there any code changes? 
Could you also try accessing the URL from an incognito window or after clearing cooking and cache ?

**Comment by VandrerenErik** [comment]
Sorry I forgot to mention the issue was solved, it was caused by an nginx "misconfiguration", removing the "www" subdomain solved the issue.

**Comment by sojan-official** [comment]
@VandrerenErik  Thanks for reporting back 😃
