### ISSUE TITLE
Links send from Slack have `<>` surrounding them, making them invalid.

### ISSUE THREAD

**Issue by DataTables** [chatwoot/chatwoot#1658]
**Describe the bug**

I've got Slack integration setup (with huge thanks to your help on that before!) and have noticed that when sending a message from Slack that contains a link, the link has `<>` characters placed around it. That results in the link having a trailing `>` when auto linked in the chat client making the link invalid.

**To Reproduce**

With Slack integration setup:

1. Start a chat
2. Send a link from the Slack thread
3. Click the link in the chat widget.

**Expected behavior**

I'm not sure if the correct thing would be to change the auto URL highlighter to ignore the `>` (as it is ignoring the leading `<`), or if the `<>` shouldn't be there in the first place (perhaps it is Slack that is adding them?).

**Screenshots**

Sent from Slack:
![image](https://user-images.githubusercontent.com/278219/104707588-822ece00-5714-11eb-92d2-dc9bf93ce175.png)

Seen in chat:
![image](https://user-images.githubusercontent.com/278219/104707616-8eb32680-5714-11eb-9f83-bf0d3ac5ceea.png)

**Environment**

Chatwoot self hosted - bare metal.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Firefox
 - Version: 84

Thanks!

**Comment by pranavrajs** [comment]
I guess this is a duplicate for #1537. I have not seen the issue with Slack, will test it out.

**Comment by DataTables** [comment]
Probably yes. Interestingly we do actually use `()` in some of our API doc links - e.g. https://datatables.net/reference/api/draw() . We do allow it to work without the parenthesis as well though - I just point it out as there are valid use cases.

**Comment by pranavrajs** [comment]
@DataTables Yeah, that makes sense. We are moving towards Github like markdown based editor, so this should be solved through that.

**Comment by DataTables** [comment]
Looking forward to that - I saw the latest commit was related to that.

I think this can probably be closed off as a duplicate then.

**Comment by pranavrajs** [comment]
@DataTables Let me test out the slack integration. I will close it afterwards.

**Comment by pranavrajs** [comment]
Closing this as the invalid link issues are fixed. However `<>` still remains. This is probably due to difference in markdown specs. Slack use mrkdwn where we use Common Markdown format

**Comment by DataTables** [comment]
Thank you :-)
