### ISSUE TITLE
Heroku deploy fails (1click button or manually git clone and push)

### ISSUE THREAD

**Issue by digitalescapade** [chatwoot/chatwoot#1667]
Heroku deploy fails each time I try, even if I clone manually git repo and push it to an heroku app.
See (end of) the logs below.
Any idea of workaround ?
![image](https://user-images.githubusercontent.com/65152965/104935122-229e2000-59ab-11eb-8ee3-aa16521337ac.png)

**Comment by pranavrajs** [comment]
@digitalescapade We will test it out soon and push a fix if there is an error.
