### ISSUE TITLE
Bug: API Add Labels does not work with v1.12.0 

### ISSUE THREAD

**Issue by pucilpet** [chatwoot/chatwoot#1669]
**Describe the bug**

When I try to add labels using API, the label is not added.

**To Reproduce**

1. Try to add a label with API /api/v1/accounts/{account_id}/conversations/{id}/labels
2. Label is not added
3. I get an empty payload as a result

**Expected behavior**

I expect that a label is added to the conversation.

**Browser logs**

Api returns:

[
{
"payload": [
]
}
] 

**Environment**

Caprover self-hosted installation.

**Additional context**

It used to work with v1.11.0 but after upgrade - it does not. Other api commands seem to continue working with the new version.

**Comment by pranavrajs** [comment]
@pucilpet Can you please share the request payload?

**Comment by pucilpet** [comment]
> 
> 
> @pucilpet Can you please share the request payload?

Now I got it to working after I sent the payload using --data-raw

--data-raw '{
  "labels": [
    "label1"
  ]
}'

Earlier I was using form/json to send the data but that does not seem to work anymore. So I guess this issue can be closed.

**Comment by punndcoder28** [comment]
Hi @pranavrajs I have been trying to use the create labels api for a conversation and like @pucilpet mentioned we get a successful response but it is empty 
```
[
   {
      "payload": [ ]
   }
]
```

Our request payload is 
```
{
   "labels": ["l1", "l2", ...]
}
```

We are user version 2.1.1. Currently using python `requests` to make any `https` calls.

**Comment by pranavrajs** [comment]
Can you please share the API URL, payload, response, or a postman collection?

**Comment by punndcoder28** [comment]
A small snapshot of the code we are using
```
requests_session = requests.Session()
requests_session.headers.update({"api_access_token": CHATWOOT_API_KEY})
....
# api call get create a new conversation and post a message happens here, after which the create labels api is called
labels_payload = {"labels": ["label1", "label2"]}

labels_response=requests_session.post(url=f"https://company.domain.name/api/v1/accounts/{CHATWOOT_ACCOUNT_ID}/conversations/{conversation_id}/labels",data=labels_payload)

print(labels_response.json())
```
And the response payload is `{'payload': []}`

**Comment by punndcoder28** [comment]
Hi @pranavrajs any updates regarding this? Hope I am not troubling you in you busy schedule

**Comment by sojan-official** [comment]
@punndcoder28 can you check the request logs? Also could you ensure that you are sending the request as json
ref: https://stackoverflow.com/a/9952774/939299

**Comment by pranavrajs** [comment]
@punndcoder28 Have you added `label1` and `label2` in the admin dashboard? If it is not defined in the account, you would not be able to add it to the conversation.

**Comment by punndcoder28** [comment]
> @punndcoder28 can you check the request logs? Also could you ensure that you are sending the request as json
> ref: https://stackoverflow.com/a/9952774/939299

This actually could be the problem. Let me try `json.dumps(request_payload)` and get back.



> @punndcoder28 Have you added `label1` and `label2` in the admin dashboard? If it is not defined in the account, you would not be able to add it to the conversation.

Yup the corresponding labels are present in the dashboard
