### ISSUE TITLE
Cannot save additional attributes via conversations API

### ISSUE THREAD

**Issue by josephktcheung** [chatwoot/chatwoot#1678]
**Describe the bug**

https://github.com/chatwoot/chatwoot/blob/develop/app/controllers/api/v1/accounts/conversations_controller.rb#L90 sets `additional_attributes` to `params[:additional_attributes]`, however `params[:additional_attributes]` is a `ActionController::Parameters` and not a `Hash`, hence it cannot pass the validation in https://github.com/chatwoot/chatwoot/blob/develop/app/models/conversation.rb#L145.

<img width="1757" alt="Screenshot 2021-01-21 at 12 27 58 PM" src="https://user-images.githubusercontent.com/4270232/105280192-25378a00-5be4-11eb-8114-b4f2091fe1b3.png">

Hence `additional_attributes` will always be saved as an empty hash.

**To Reproduce**

1. Make a post request to create a conversation with following json body:
```json
{
  "source_id": "<Source id>",
  "additional_attributes": {
    "comment_id": 1
  }
}
```
2. Created conversation's `additional_attributes` is an empty object

**Expected behavior**

Conversation's `additional_attributes` should be saved and returned successfully.

**Additional context**

https://github.com/chatwoot/chatwoot/blob/develop/spec/controllers/api/v1/accounts/conversations_controller_spec.rb#L138-L148 should add a test case where `params` contains `additional_attributes` hash and make sure that it's returned in the API response.

```ruby
    it 'creates a new conversation with additional attributes' do
        allow(Rails.configuration.dispatcher).to receive(:dispatch)
        post "/api/v1/accounts/#{account.id}/conversations",
             headers: agent.create_new_auth_token,
             params: { source_id: contact_inbox.source_id, additional_attributes: { comment_id: 1 } },
             as: :json

        expect(response).to have_http_status(:success)
        response_data = JSON.parse(response.body, symbolize_names: true)
        expect(response_data[:additional_attributes]).to eq({ comment_id: 1 })
      end
```

**Comment by pranavrajs** [comment]
@sojan-official Can you please take a look at this ticket?
