### ISSUE TITLE
Error after clean instalation

### ISSUE THREAD

**Issue by shadowsberg** [chatwoot/chatwoot#1679]
**Describe the bug**

After doing a clean install on Ubuntu 18.04 using the script, I immediately accessed my domain on port 3000 and I only see a message saying We're sorry, but something went wrong.
url chat.konectcoin.com

**To Reproduce**

1. Go to 'chat.konectcoin.com'
2. See error

**Expected behavior**

**Screenshots**

![Screenshot_20210121_005746](https://user-images.githubusercontent.com/9481680/105286142-bcb8c080-5b83-11eb-94d3-97276df2ab9b.png)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**
 - OS: Ubuntu serve 18.04
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@shadowsberg Can you please share the logs? You can check whether there is a log file at `log/production.log` or please share the relevant output from `cat /var/syslog`.

**Comment by shadowsberg** [comment]
I don't know how to access those logs, those routes don't return anything

**Comment by shadowsberg** [comment]
I got this inside the folder log / scout_amp.log

No configuration file loaded, and no configuration found in ENV. For assistance configuring Scout, visit https://$
[01/20/21 23:14:35 -0500 box.konectcoin.com (522)] INFO : Scout Agent [2.6.9] Initialized
[01/20/21 23:14:35 -0500 box.konectcoin.com (522)] INFO : Not Loading Instruments
[01/20/21 23:14:35 -0500 box.konectcoin.com (522)] INFO : Scout Agent [2.6.9] Installed
[01/20/21 23:14:35 -0500 box.konectcoin.com (522)] INFO : Monitoring isn't enabled for the [production] environment.
[01/20/21 23:14:35 -0500 box.konectcoin.com (522)] INFO : Deferring agent start. Standing by for first request

**Comment by pranavrajs** [comment]
@shadowsberg This doesn't matter as you are using the self-hosted instance. Can you please share the output of `cat /var/log/syslog`?

**Comment by shadowsberg** [comment]
Jan 21 07:36:26 box chatwoot-web.1[3231]: I, [2021-01-21T07:36:26.832629 #3231]  INFO -- : [e3578077-a613-4581-b398-1407e866fce6] Started GET "/" for 62.210.10.77 at 2021-$
Jan 21 07:36:26 box chatwoot-web.1[3231]: I, [2021-01-21T07:36:26.835488 #3231]  INFO -- : [e3578077-a613-4581-b398-1407e866fce6] Processing by DashboardController#index a$
Jan 21 07:36:26 box chatwoot-web.1[3231]: I, [2021-01-21T07:36:26.848603 #3231]  INFO -- : [e3578077-a613-4581-b398-1407e866fce6] Completed 500 Internal Server Error in 13$
Jan 21 07:36:26 box chatwoot-web.1[3231]: F, [2021-01-21T07:36:26.849600 #3231] FATAL -- : [e3578077-a613-4581-b398-1407e866fce6]
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] PG::ConnectionBad (FATAL:  password authentication failed for user "chatwoot"
Jan 21 07:36:26 box chatwoot-web.1[3231]: FATAL:  password authentication failed for user "chatwoot"
Jan 21 07:36:26 box chatwoot-web.1[3231]: ):
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6]
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] app/models/installation_config.rb:23:in `block in <class:InstallationConfig>'
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] lib/global_config.rb:41:in `db_fallback'
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] lib/global_config.rb:32:in `load_from_cache'
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] lib/global_config.rb:12:in `block in get'
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] lib/global_config.rb:11:in `each'
Jan 21 07:36:26 box chatwoot-web.1[3231]: [e3578077-a613-4581-b398-1407e866fce6] lib/global_config.rb:11:in `get'

**Comment by shadowsberg** [comment]
I managed to solve the problem, the issue is that my server was completely clean and the language seems to be affecting, it was in English but I think that the utf-8 was not configured, reconfigure the premises, uninstall postgres and run the script and I'm done , Thanks a lot

**Comment by Nobinbd** [comment]
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     2: <html>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     3:   <head>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     4:     <title>SuperAdmin | Chatwoot</title>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     5:     <%= javascript_pack_tag 'superadmin' %>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     6:     <%= stylesheet_pack_tag 'superadmin' %>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     7:   </head>
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]     8:   <body data-gr-c-s-loaded="true">
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939]
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939] app/views/installation/onboarding/index.html.erb:5
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939] app/controllers/application_controller.rb:18:in `handle_with_exception'
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
May  9 19:49:45 localhost chatwoot-web.1[33277]: [19f5746a-19a1-48d8-9a4e-45b59e67c939] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
May  9 19:55:01 localhost CRON[33928]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
May  9 20:05:01 localhost CRON[33965]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
May  9 20:05:57 localhost chatwoot-web.1[33277]: I, [2021-05-09T20:05:57.307108 #33277]  INFO -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] Started GET "/installation/onboarding" for 103.147.41.188 at 2021-05-09 20:05:57 +0000
May  9 20:05:57 localhost chatwoot-web.1[33277]: I, [2021-05-09T20:05:57.313090 #33277]  INFO -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] Processing by Installation::OnboardingController#index as HTML
May  9 20:05:57 localhost chatwoot-web.1[33277]: I, [2021-05-09T20:05:57.317906 #33277]  INFO -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]   Rendering installation/onboarding/index.html.erb
May  9 20:05:57 localhost chatwoot-web.1[33277]: I, [2021-05-09T20:05:57.319731 #33277]  INFO -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]   Rendered installation/onboarding/index.html.erb (Duration: 1.3ms | Allocations: 256)
May  9 20:05:57 localhost chatwoot-web.1[33277]: I, [2021-05-09T20:05:57.320601 #33277]  INFO -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] Completed 500 Internal Server Error in 7ms (Allocations: 727)
May  9 20:05:57 localhost chatwoot-web.1[33277]: F, [2021-05-09T20:05:57.322753 #33277] FATAL -- : [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] ActionView::Template::Error (Webpacker can't find superadmin.js in /home/chatwoot/chatwoot/public/packs/manifest.json. Possible causes:
May  9 20:05:57 localhost chatwoot-web.1[33277]: 1. You want to set webpacker.yml value of compile to true for your environment
May  9 20:05:57 localhost chatwoot-web.1[33277]:    unless you are using the `webpack -w` or the webpack-dev-server.
May  9 20:05:57 localhost chatwoot-web.1[33277]: 2. webpack has not yet re-run to reflect updates.
May  9 20:05:57 localhost chatwoot-web.1[33277]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
May  9 20:05:57 localhost chatwoot-web.1[33277]: 4. Your webpack configuration is not creating a manifest.
May  9 20:05:57 localhost chatwoot-web.1[33277]: Your manifest contains:
May  9 20:05:57 localhost chatwoot-web.1[33277]: {
May  9 20:05:57 localhost chatwoot-web.1[33277]: }
May  9 20:05:57 localhost chatwoot-web.1[33277]: ):
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     2: <html>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     3:   <head>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     4:     <title>SuperAdmin | Chatwoot</title>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     5:     <%= javascript_pack_tag 'superadmin' %>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     6:     <%= stylesheet_pack_tag 'superadmin' %>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     7:   </head>
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]     8:   <body data-gr-c-s-loaded="true">
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b]
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] app/views/installation/onboarding/index.html.erb:5
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] app/controllers/application_controller.rb:18:in `handle_with_exception'
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
May  9 20:05:57 localhost chatwoot-web.1[33277]: [4cc32ab1-4f87-43de-af27-ea2c09b66f9b] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

**Comment by Nobinbd** [comment]
I am facing this same problem and above is my log...
Can you please help me out...
Thanks..
