### ISSUE TITLE
Move activestorage attachments to CDN path

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#1680]
@sojan-official Please research about moving active storage URL to CDN instead of Rails app.

**Comment by duartemvix** [comment]
I was going through a problem like this with ActiveStorage uploads to cloud services. Is it your intention to also cover this?

```https://chatwoot.host.com/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--197f9b6abffeff1517d87ede094abb03028bf94a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTWpVd2VESTFNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--cb53ecc12138263c4bdc7c9d0aa09ec360e2c856/asset-5.jpg```
