### ISSUE TITLE
Identity Verification Badge

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#1682]
**Is your feature request related to a problem? Please describe.**
We can make use of the HMAC verification feature, by displaying a badge that indicates this session is verified (sample context attached).

## Verified:
![Screen Shot 2021-01-22 at 2 27 29 PM](https://user-images.githubusercontent.com/66124192/105495871-605dba00-5cc5-11eb-88b3-6970dae6f1f7.png)

## Unverified:
![Screen Shot 2021-01-22 at 4 10 44 PM](https://user-images.githubusercontent.com/66124192/105501214-9d797a80-5ccc-11eb-9831-8064e5b78d05.png)

**Describe alternatives you've considered**
Manual verification of identity, by asking the visitor to provide their account PIN code, latest 4 numbers of credit card, etc.

**Comment by sojan-official** [comment]
The verification badge is associated with `contact_inboxes`  objects.  Since a contact can have both HMAC verified and non-verified contact inboxes. It will be better to show the verified indication against each conversation.

**Comment by sojan-official** [comment]
We could also enable a toggle for mandatory identity verification. 
When enabled no user sessions are created without identity verification.

**Comment by WevrLabs** [comment]
> We could also enable a toggle for mandatory identity verification.
> When enabled no user sessions are created without identity verification.

won't this prevent sessions from visitors?

**Comment by WevrLabs** [comment]
The feature was inspired by this:
https://help.crisp.chat/en/article/how-to-verify-user-identity-with-cryptographic-email-signatures-166sl01/

**Comment by sojan-official** [comment]
@WevrLabs  the toggle will be an optional feature for those who are more conscious about security. This will be in addition to the verification badge.

**Comment by ayushin** [comment]
It would be great to allow such switch (require identifier hash) per inbox. You probably don't want it over the insecure channels like Web Live Chat and you want to automatically confirm user identity who replied from their e-mail address.

**Comment by sojan-official** [comment]
@SimonHausdorf for users chatting on website inbox, without identity validated. we show a warning like shown below.
![Screenshot 2022-06-07 at 2 14 48 PM](https://user-images.githubusercontent.com/73185/172337825-f87d2f84-9045-432f-a460-13c3ad44c7fa.png)
