### ISSUE TITLE
blank page when you want to confirm the account by email

### ISSUE THREAD

**Issue by skylide** [chatwoot/chatwoot#1686]
Hello, is it normal to have a blank page when you want to confirm the account by email?

**Comment by pranavrajs** [comment]
@skylide Is there any error on the browser console?

**Comment by skylide** [comment]
I found the problem. However, I noticed one thing. When you delete an agent already confirmed and want to add it, chatwoot does not send a confirmation email again

**Comment by sojan-official** [comment]
@skylide  Thanks a lot for reporting this. We have it in our radar. will keep you posted once we have an update.

**Comment by pranavrajs** [comment]
Fixed by https://github.com/chatwoot/chatwoot/pull/5279
