### ISSUE TITLE
Support Outgoing Mail Variable Like MAILER_SENDER_NAME Or Something Similar

### ISSUE THREAD

**Issue by ghost** [chatwoot/chatwoot#1692]
**Is your enhancement request related to a problem? Please describe.**
As a user, I would like to be able to configure a from name for system generated emails in the environmental configuration. The [documentation](https://www.chatwoot.com/docs/environment-variables) and default .env file configuration file does not provide a variable for an outgoing from email name, only a from email address (**MAILER_SENDER_EMAIL**).

**Describe the solution you'd like**
Please add an environmental variable, MAILER_SENDER_NAME. I have no variable preference, this is just an example. Please ensure this is respected by the app once configured. Then please [update the documentation](https://www.chatwoot.com/docs/environment-variables) accordingly.

**Describe alternatives you've considered**
If you already have a variable that is available for this, please [update the documentation](https://www.chatwoot.com/docs/environment-variables) to let the community know what it is.

**Additional context**
Thank you for building a fantastic chat tool!

**Comment by pranavrajs** [comment]
@sudo-create I guess this would be solved by #1485

**Comment by iammattmartin** [comment]
Would be nice for this to per set per Inbox like what can be done with the email address....

**Comment by iammattmartin** [comment]
This does not resolve it for most as it takes away being able to set an address per inbox.
