### ISSUE TITLE
Make formatting buttons on/off and retained.

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1697]
**Is your enhancement request related to a problem? Please describe.**
Current formatting options are only shown when you click on the icon.

**Describe the solution you'd like**
It would be better to always show formatting so that each option is one click away. I personally wondered where they were after upgrade until I clicked on the non-descript button that looked like a quote more than something indicative of formatting.

(The face and paperclip however are self-explanatory) 

**Describe alternatives you've considered**
The formatting options could be on by default, so always showing. Or even set on a staff user preference basis.

This would help where the setting (i.e shown) is lost when you switch between open/resolved/bot queries or even different inboxes. When you are actively using this through queries but also between many inboxes, this would be tedious.

**Comment by iammattmartin** [comment]
Just as a side comment. Some of the options shouldn't show when they're not supported i.e WhatsApp.

That only supports limited formatting such as **bold**, _italic_, underline, ~strikethrough~ and <pre>pre<pre>.

**Comment by pranavrajs** [comment]
> That only supports limited formatting such as bold, italic, strikethrough and monospace.
https://faq.whatsapp.com/general/chats/how-to-format-your-messages/?lang=en
Facebook also supports a code block in addition to those four.
https://www.facebook.com/help/147348452522644

@iammattmartin I believe we had disabled formatting for non-website/email channels. If it is still available, then it is a bug.

> The formatting options could be on by default, so always showing. Or even set on a staff user preference basis.

This can be saved in the db against a user. If you have turned it on, then we can keep the state until you manually turn it off.
