### ISSUE TITLE
channel avatar random file error

### ISSUE THREAD

**Issue by dejavoodooo** [chatwoot/chatwoot#1698]
**Describe the bug**

The channel avatar uploaded to app loses file reference after some period of time.

**To Reproduce**

1. Go to inboxes
2. Click on settings for inbox
3. Upload image for channel avatar

**Expected behavior**

File should remain accessible to chatwoot and chatwoot widget.

**Screenshots**

![image](https://user-images.githubusercontent.com/3332344/105864744-de68dc00-5fb7-11eb-940e-5a6375a10c77.png)
![image](https://user-images.githubusercontent.com/3332344/105864774-e58fea00-5fb7-11eb-93b6-fd80acfacf44.png)

**Browser logs**

![image](https://user-images.githubusercontent.com/3332344/105865125-39023800-5fb8-11eb-9d7a-c2ceb3a1147f.png)

**Server logs**

![image](https://user-images.githubusercontent.com/3332344/105864941-0c4e2080-5fb8-11eb-8cbe-da56bb2b038f.png)

**Environment**

Self-hosted heroku deployment.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Additional context**

I had originally assumed that image is no longer accessible once someone logs into the settings of the app. But I no longer believe this is the case. If I reupload the image it will persist for awhile but then stop working again without warning.

**Comment by sojan-official** [comment]
@dejavoodooo  have you configured a cloud storage provider? 
https://www.chatwoot.com/docs/configuring-cloud-storage

**Comment by dejavoodooo** [comment]
I did not realize this was required.

**Comment by dejavoodooo** [comment]
The file uploads and works for a short period of time then gets lost. I'm assuming local fs does not persist?

**Comment by sojan-official** [comment]
@dejavoodooo  yep that's correct. The Heroku filesystem is ephemeral 

https://help.heroku.com/K1PPS2WM/why-are-my-file-uploads-missing-deleted

We are working on improving our onboarding so that this is communicated.

**Comment by dejavoodooo** [comment]
Firs time using Heroku. Thank you for this! Sorry for the trouble.
