### ISSUE TITLE
Agent Invitation email content needs to be updated

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#17]
- [ ] Add who has invited, which inbox etc.

<img width="665" alt="Screenshot 2019-08-25 13 08 11" src="https://user-images.githubusercontent.com/2246121/63647054-79151980-c739-11e9-9adb-d07f5a2df289.png">

**Comment by laurenball** [comment]
@pranavrajs I'd be happy to pick this up. Do you have a preference for wording or format?

**Comment by laurenball** [comment]
bump @pranavrajs; I'm planning to knock this out this weekend if you're still looking for some work here

**Comment by pranavrajs** [comment]
@laurenball Please feel free to take it up. I'll post the content today.
