### ISSUE TITLE
Delete contacts

### ISSUE THREAD

**Issue by whande1992** [chatwoot/chatwoot#1707]
**Is your enhancement request related to a problem? Please describe.**
Over time, the registrations become more and more
 getting polluted, it's bad to manage, you need an option to exclude.

**Describe the solution you'd like**
Have an option in the contact register that allows you to delete it, and also allow the exclusion by the API.

**Comment by ilyakonovalenko** [comment]
You can just delete email from the contact data, contact will disappear from the list then.

**Comment by valentinwinkelmann** [comment]
I can delete the email, the name can not be deleted. The contact then remains without email. From a privacy point of view, a button to completely delete an entire contact & all associated conversations is clearly missing.

**Comment by sojan-official** [comment]
ref #1929
