### ISSUE TITLE
Twitter authorization does not work

### ISSUE THREAD

**Issue by ilyakonovalenko** [chatwoot/chatwoot#1708]
I have configured .env file for Twitter according to the documentation.
However, after clicking on "Sign in with Twitter" an error occurred: "We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

However, no logs are written for the issue. API keys are for sure active and environment is created for the app. So where to look?

**To Reproduce**

1. Go to app/accounts/ACCOUNT_ID/settings/inboxes/new/twitter
2. Click on 'Sign in with Twitter'
4. See error above

**Expected behavior**

At least some text error to find out the cause.

**Server logs**

Nothing in the logs.

**Environment**

Self-hosted with Docker

**Comment by pranavrajs** [comment]
@ilyakonovalenko do you have access to Twitter business APIs?

**Comment by ilyakonovalenko** [comment]
@pranavrajs Can you please let me know how and where to check it? I just followed your instruction to create app and environment.

**Comment by pranavrajs** [comment]
Please follow this guide https://www.chatwoot.com/docs/twitter-app-setup

**Comment by ilyakonovalenko** [comment]
@pranavrajs As stated already that is whay I followed. Account Activity API is active for the environment as well.

**Comment by seizmo** [comment]
Same here. Here are the logs:

`
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120] NoMethodError (undefined method `id' for nil:NilClass):
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120]
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120] app/controllers/twitter/authorizations_controller.rb:9:in `create'
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120] app/controllers/application_controller.rb:18:in `handle_with_exception'
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | [71c72b0e-9f0f-4ad5-9c01-dcbb20457120] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
`

**Comment by iammattmartin** [comment]
We too are getting the same error as @seizmo from our current integration that was setup correctly and has not changed.

**Comment by pranavrajs** [comment]
@seizmo @iammattmartin Not sure what went wrong. I will check it out.

**Comment by arladmin** [comment]
Facing the same issue.

The Twitter setup seems to be okay. 
But after authorizing the Twitter app, the same 'Sign in with Twitter' screen opens up. No error displayed.
