### ISSUE TITLE
Agent Name cannot be shorter than 4 characters if edited by Admin

### ISSUE THREAD

**Issue by Jiiniasu** [chatwoot/chatwoot#1714]
**Describe the bug**

Admins cannot set Agent Name to anything shorter than 4 characters on users while the users themselves do not have this restriction when editing Full Name.

**To Reproduce**

1. Go to **Settings**
2. Add an agent or edit an existing agent
3. Enter an **Agent Name** shorter than 4 characters
4. See Agent Name field light up in red and the Edit/Add Agent button become disabled

**Expected behavior**

I expected the admin to be able to set an Agent Name shorter than 4 characters. 

**Additional context**

We were running a self hosted v1.12.0.

In our case we wanted to only show agent's given name due to privacy. Two agents, of which I was one of them, apparently had too short names. Originally we wanted to set the proper Full Name and set the given name as Display Name, but soon realised we - as admins - could not set the Display Name for agents. This in turn led us to discover the minimum name limit, at least for admins. We were also a bit bummed that we could not restrict agents from editing Full Name and Display Name, but that is borderline offtopic for this bug report.

Manually removing `disabled="disabled"` from the submit-button HTML in the browser dev tools seem to allow the form submit properly though. =)

**Comment by karthik-sivadas** [comment]
@pranavrajs I would like to take the task. In my opinion, the validation in the agent edit and add form seems correct. Should I add validation in the user's profile setting with `minLenght(4)` or should I reduce the length in agent forms?

**Comment by pranavrajs** [comment]
@karthik-sivadas yes, that is correct.

**Comment by Jiiniasu** [comment]
Question: Why are you **adding** a 4 character minimum requirement for the names?
What practical use has this feature got other than giving me and other people with short names grief?

**Comment by sojan-official** [comment]
@Jiiniasu The number `4` was arbitrary, I think inspired by the character limit for usernames placed by services like Twitter.  
The key here for us is to have consistent validation across both the forms and also ensure that the validation will force the end-user to input a meaningful string.  

Do you have any recommendations in terms of character limits? does making the minimum requirement to 2 character helps?

**Comment by Jiiniasu** [comment]
Wouldn't the minimum of _one_ character make sense?
Without too much knowledge about names in languages such as chinese, japanese etc. I'd bet that single-character names isn't impossible.

**Comment by pranavrajs** [comment]
Since this was accepting full name, we expected it to have a minimum number of characters, but I agree with your point. @karthik-sivadas Can you please update the PR to include the changes in validation as well. Let us just keep 1 letter validation for now.
