### ISSUE TITLE
ChatWoot crashes : Segmentation faults on 1.12.2

### ISSUE THREAD

**Issue by Nirva-Software** [chatwoot/chatwoot#1718]
Hello,

We have a self-hosted installation using the docker image (1.12.2) + postgresql + redis

We are not able to reproduce the issues but the server has crashed recently:

* [2021-01-31T22:42:11.249647 #1]  INFO -- : RoomChannel#update_presence
/gems/ruby/2.7.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/synchronization/abstract_lockable_object.rb:37: [BUG] Segmentation fault at 0x00007f14f901bea8
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]
-> for this first crash no agent/admin and no client using the application

* [2021-02-01T15:26:43.913457 #1]  INFO -- : [d2351351-d462-4b8b-8fab-79267f3ee0f2] [ActiveJob] Enqueued Notification::EmailNotificationJob (Job ID: 7421baeb-e9d5-499f-a585-3bc71733bf27) to Sidekiq(default) with arguments: #<GlobalID:0x00007f15edde5af8 @uri=#<URI::GID gid://chatwoot/Notification/20>>
/usr/local/lib/ruby/2.7.0/ipaddr.rb:620: [BUG] Segmentation fault at 0x00007f15e9c2ac28
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-musl]
-> for this second crash a developer was sending messages using the javascript SDK

Is this a known bug ?
Is there a workaround ? Something we missed in the configuration ?
Do you need more info to investigate ?

Regards

**Comment by pranavrajs** [comment]
@Nirva-Software This is not a known issue. A quick search shows the following similar results. We would have to look deeper.

1. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=966653
2. https://github.com/bigcommerce/gruf/issues/94#issuecomment-589721841

cc: @sojan-official

**Comment by sojan-official** [comment]
seems like a Debian specific issue. There isn't any specific workaround we can do on the chatwoot side. 

https://wiki.debian.org/gitlab/#gitlab_crash_work_around_.28install_grpc_from_rubygems.org.29
