### ISSUE TITLE
Fix [Disable Generating CoffeeScript file when generate]

### ISSUE THREAD

**Issue by nursoltan-s** [chatwoot/chatwoot#172]
After every rails generate command it creates coffee file in /app/assets/javascripts folder. Since we don't need them. I think this is good idea to disable generation of coffee files.

**Comment by pranavrajs** [comment]
@nursoltan-s Thanks for the suggestion. :) @sojan-official will take a look at the PR.

**Comment by sojan-official** [comment]
#173  closes this
