### ISSUE TITLE
New lines in messages lost

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1730]
**Is your enhancement request related to a problem? Please describe.**
When sending a message where you press shift+enter for a new line, although the message can be typed out like this, the formatting is lost once sent.

This should be retained so it is sent as typed/displayed when typing.

**Comment by pranavrajs** [comment]
@iammattmartin Just to clarify this, is it happening on the web or mobile app?

**Comment by iammattmartin** [comment]
Web.

**Comment by popeeyy** [comment]
Is there going to be any fix for this soon? This seems to be happening when adding new lines to Dialogflow as well, the new lines won't appears in the chat widget on the website.

Widget: ![image](https://user-images.githubusercontent.com/29686338/124575686-74731f00-de00-11eb-8872-97a39a0d5f5f.png)
Dialogflow: ![image](https://user-images.githubusercontent.com/29686338/124575703-76d57900-de00-11eb-8f53-cc8799d16fa1.png)
