### ISSUE TITLE
Like / Retweet on Twitter

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1737]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to support retweeting and liking of posts. Easily accompilishable be two more icons within the message bubble (along with the reply and popout).

There are instances where both being used would be helpful negating the need to login to Twitter.com or a client to do just that.

**Comment by karthik-sivadas** [comment]
@pranavrajs Is anyone working on this issue? May I pick this?

**Comment by sojan-official** [comment]
@karthik-sivadas  feel free to go ahead

**Comment by WevrLabs** [comment]
Is this implemented yet?

@sojan-official

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
