### ISSUE TITLE
 Improve API documentation on the conversationSearch endpoint

### ISSUE THREAD

**Issue by whande1992** [chatwoot/chatwoot#1746]
I'm using the API for messages, but there was a difficulty in the endpoit to search for conversations, it is possible to use "query params" but it does not exemplify which fields I can use, I carried out some tests using the return of the query as a basis but without success.

I would like the documentation of this route to be improved, showing the fields that are accessible to use in the "q" parameter, and also an example of this query so that users can walk alone.

https://www.chatwoot.com/developers/api#operation/conversationSearch

**Comment by pranavrajs** [comment]
Closing as the endpoint would be deprecated in #6021
