### ISSUE TITLE
Show conversations filtered by agent

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1756]
**Is your feature request related to a problem? Please describe.**
I'm curious if an agent was active recently and how he handles conversations but I can't find a way to search for his conversations.

**Describe the solution you'd like**

Wherever an agent is mentioned, it should be clickable to see that agent's stuff.

The search box should feature an agent dropdown.

**Describe alternatives you've considered**

The Reports section also should allow to filter by agent. Right now that would be enough for me but ultimately the report section should allow for all-time, custom time windows, ... too.

**Additional context**

#1588 might be related?

**Comment by sojan-official** [comment]
We have added the following in our recent updates which should cover the mentioned use cases

- conversation filters: https://www.chatwoot.com/docs/product/others/advanced-conversation-filters
- agent reports: https://www.chatwoot.com/docs/user-guide/reports#agent-reports
