### ISSUE TITLE
1.13.0 has email inbox from the UI disabled 

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1785]
**Describe the bug**

If it's already available for beta use, why not just enable it with a warning? There is a thread running on this issue that's been open for a couple of months.

**To Reproduce**

Go to create new inbox.

**Expected behavior**

Enable email channel inbox.

**Screenshots**

NA

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)
Self hosted on Docker

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@srameshr We will add the setup instructions this week.

**Comment by srameshr** [comment]
@pranavrajs Can I know if this is coming up?

**Comment by srameshr** [comment]
@pranavrajs Will it be under conversation continuity or a new setup page?

**Comment by srameshr** [comment]
@pranavrajs @sojan-official Any help on this, please?

**Comment by nithindavid** [comment]
@srameshr  This will come with the next release.

**Comment by srameshr** [comment]
@nithindavid Please don't close until the release is out. I will manually close it myself later.

**Comment by sojan-official** [comment]
We have added instructions to enable the email channel.

https://www.chatwoot.com/docs/self-hosted#email-channel-setup

**Comment by srameshr** [comment]
@sojan-official It will be enabled for every account when ENABLE_SIGNUP is set to true right?

**Comment by sojan-official** [comment]
@srameshr  For the newer installations, it will be enabled by default. For older installations, you will have to enable it for the accounts via console.

**Comment by srameshr** [comment]
@sojan-official I gave it a try. It does not enable the email inbox UI. It still has the inactive class added to it. I followed the instruction for the inbox channel as well as conversation continuity. Here is my account details after logging 

1. ```Account.find(1)```

```
id: 1,
 name: "Acme Inc",
 created_at: Fri, 29 Jan 2021 19:23:30 UTC +00:00,
 updated_at: Fri, 05 Mar 2021 09:58:11 UTC +00:00,
 locale: "en",
 domain: "myorg.chatwootcrm.com",
 support_email: "accounts@myorg.com",
 settings_flags: 0,
 feature_flags: 15,
 auto_resolve_duration: nil,
 timezone: "UTC">
```

2. ```Account.enabled_features```
 ``` => {"inbound_emails"=>true, "channel_email"=>true, "channel_facebook"=>true, "channel_twitter"=>true}```

**Comment by sojan-official** [comment]
@srameshr If it was an older installation upgraded to 1.13.1. The email channel won't be enabled automatically for newly created accounts.  You would have to find the specific account via `Account.find(account_id)` and add channel_email as an enabled feature.

**Comment by srameshr** [comment]
@sojan-official 
So, I had installed Chatwoot version 1.13 a month ago and now upgraded to 1.13.1 and also ran DB migrations. So, does it mean anyone who creates a new account from now, on our instance will not have an email channel enabled by default? If that's the case this issue has to be re-opened.

**Comment by srameshr** [comment]
@sojan-official That's the case. I just updated version 1.13.1 and ran db migration commands and created a new account. It does not have channel_email enabled by default. Why is this the case?

**Comment by srameshr** [comment]
@sojan-official Is there any way that this can be enabled automatically?

**Comment by sojan-official** [comment]
@srameshr  We will have a migration toggling it on by default for all accounts in `1.14.0`

**Comment by srameshr** [comment]
So that's on the 14th of this month?
