### ISSUE TITLE
Chatwoot-worker service crashing after update

### ISSUE THREAD

**Issue by petrsoudek** [chatwoot/chatwoot#1787]

**Comment by sojan-official** [comment]
@petrsoudek do you still have this issue persisting? 
could you give more information about your installation environment and chatwoot version?

**Comment by petrsoudek** [comment]
solved

**Comment by sojan-official** [comment]
@petrsoudek  Thanks for the update, if you could add the steps you did to solve the issue might be helpful for the future :)
