### ISSUE TITLE
Add documentation on using serveo.net or ngrok for local development 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#180]
- documentation on how to configure the facebook app in development mode  ( ref #39)
- how to configure the bot url 
- how to run the bot endpoint in local using ngrock or serveo.net

**Comment by TJoker024** [comment]
Hi ! I would like to work on this issue, but being new to this project, could you give me some tips and pointers about where is should look at ? thank you !

**Comment by sojan-official** [comment]
@TJoker024  chatwoot also supports facebook messenger as a messaging channel along with the web widget. So get the facebook widget up and running.  One has to follow the steps here at https://developers.facebook.com/docs/apps/#register 

add these values to the appropriate variables in .env file 
```
FB_VERIFY_TOKEN=
FB_APP_SECRET=
FB_APP_ID=
```
one should also run a ngrok server  / servio server pointed to the local app and use the url in messenger settings of your facebook app 

![Screenshot 2019-11-24 at 2 44 08 AM](https://user-images.githubusercontent.com/73185/69485358-555e8e00-0e64-11ea-8aa8-9946f0ef6d00.png)

if you have everything set in terms of set up, you can connect you facebook page from chatwoot 
![Screenshot 2019-11-24 at 2 48 10 AM](https://user-images.githubusercontent.com/73185/69485397-e0d81f00-0e64-11ea-8c72-08e59e98ab20.png)



 once you connect, you should be able to able to send messages to your facebook page and receive it in chatwoot app you have running.  I know the documentation on this is sparse. if you are taking this up. we will surely help you alongside.

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/647
