### ISSUE TITLE
Shows the release version deployed

### ISSUE THREAD

**Issue by fv3rdugo** [chatwoot/chatwoot#1800]
I think it's a good idea to show the actual version deployed for good maintenance and future updates. 
For example, in the footer of the dashboard once the user is validated.
Release v1.13.0

**Comment by iammattmartin** [comment]
This is shown.

Account Settings  > bottom of the screen.

**Comment by pranavrajs** [comment]
<img width="569" alt="Screenshot 2021-02-18 at 11 18 35 AM" src="https://user-images.githubusercontent.com/2246121/108311463-0f18eb80-71db-11eb-9f31-2918ce508ce5.png">

@fv3rdugo There is a footer which shows the current version and the update notification. Please feel free to reopen the ticket if you don't find it.

**Comment by fv3rdugo** [comment]
Sorry. I promise I've been looking everywhere. Thanks for the answers.
