### ISSUE TITLE
Unable to send bot message types

### ISSUE THREAD

**Issue by tds-1** [chatwoot/chatwoot#1801]
I want to send attachments to chatwoot, are incoming attachments supported?
I referred the link "https://github.com/chatwoot/chatwoot/wiki/Creating-Bot-Messages-Types" to send messages to chatwoot via the API. I am not getting any response in chatwoot UI whereas API is returning a success response. 

`url = f'{api_endpoint}/{account_number}/conversations/{conv_id}/messages'`
```
request_data = {
   "content_type":"cards",
   "content_attributes":{
      "items":[
         {
            "media_url":"https://assets.ajio.com/medias/sys_master/root/hdb/h9a/13582024212510/-1117Wx1400H-460345219-white-MODEL.jpg",
            "title":"Nike Shoes 2.0",
            "description":"Running with Nike Shoe 2.0",
            "actions":[
               {
                  "type":"link",
                  "text":"View More",
                  "uri":"google.com"
               }
            ]
         }
      ]
   },
   "private":false
}

```

```
headers = {
    'api_access_token': 'userApiKey',
    'Content-Type': 'application/json'
}
```

**Comment by whande1992** [comment]
I also have this problem, I believe that it could enable receiving an image in base64. I will follow up on this case.

**Comment by sojan-official** [comment]
For attachments, you need to use multipart/form-data instead of JSON.
refer: https://github.com/chatwoot/chatwoot/discussions/1809

**Comment by sojan-official** [comment]
@tds-1  the card type messages are not supported in the dashboard at the moment. they will only get rendered in the widget.
