### ISSUE TITLE
Migration errror - undefined local variable or method `locked' for #<InstallationConfig:0x00005644fa624ea0>

### ISSUE THREAD

**Issue by adnanmirza1** [chatwoot/chatwoot#1804]
Error while migrating
undefined local variable or method `locked' for #<InstallationConfig:0x00005644fa624ea0>

**Comment by pranavrajs** [comment]
@adnanmirza1 Can you please the document you are following to install the software?

**Comment by adnanmirza1** [comment]
I'm following nothing, just cloned master and bundle install
rake db:create
than error in migration

**Comment by pranavrajs** [comment]
for dev setup, please use ‘rake db:create, rake db:schema:load rake db:migrate’

**Comment by adnanmirza1** [comment]
Hey! yes it fixed the error thanks
