### ISSUE TITLE
Document how one can contribute to the documentation

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#181]
- the documentation currently lives in https://www.chatwoot.com/docs

**Comment by sarslanoglu** [comment]
@sojan-official I can take a look if it's available

**Comment by sojan-official** [comment]
@pranavrajs  could you see if this issue is workable?

**Comment by pranavrajs** [comment]
@sarslanoglu This issue is regarding how we deploy the documentation website, It would be better if anyone of the Chatwoot team is able to do it.

**Comment by sarslanoglu** [comment]
@pranavrajs Sure, no problem

**Comment by ThisIsRuddy** [comment]
Is there an issue with the docs? When I go to the docs url it only shows 1 card which is the intro message.

![Screenshot_20191120-170116](https://user-images.githubusercontent.com/1761171/69260252-81a1b280-0bb7-11ea-8a57-f6e225fd9b95.png)

**Comment by pranavrajs** [comment]
@ThisIsRuddy It was glitch on mobile screens. You may please reload now. You should be able to see a screen like the one below.

<img width="781" alt="Screenshot 2019-11-20 at 10 53 14 PM" src="https://user-images.githubusercontent.com/2246121/69262015-b2e6a680-0be8-11ea-88f3-3a96236abddf.png">

You should be able to see a second hamburger menu.

**Comment by ThisIsRuddy** [comment]
@pranavrajs Thank you, its working as expected now 🎉😁
