### ISSUE TITLE
Contact Search Bug

### ISSUE THREAD

**Issue by vishal-pandey** [chatwoot/chatwoot#1814]
In the contact section when you have searching the contact and in between any new contact is created it also appear in the searched section even though it doesn't match the search criteria.  
  
I am attaching the screenshot of the dashboard with the search to depict the bug. Please take a look.   
  
  
![image](https://user-images.githubusercontent.com/19498820/108597450-155fc100-73af-11eb-8c7e-43f1315c9351.png)

**Comment by pranavrajs** [comment]
Sorry for missing this out. Closing this as there are a couple of changes in the API and UI since this issue is created.
