### ISSUE TITLE
Upgrade vue-router v4

### ISSUE THREAD

**Issue by vishal-pandey** [chatwoot/chatwoot#1815]
Hi @sojan-official 
I was looking at the packages Chatwoot use and found that vue-router version 2.2.0 is being used which is kind of become old (4 years) and are missing on some new functionalities like dynamic routing,  vue-slots  which may be useful for implementing the more advanced UI and navigation.   
  
Please comment about the possibility of upgrade.   
  
   
https://github.com/chatwoot/chatwoot/blob/c17380d48a8c8f6e974b6414ca40f61fd2509219/package.json#L55

**Comment by sojan-official** [comment]
@karthik-sivadas

**Comment by pranavrajs** [comment]
This might be a good ticket for @fayazara to get started.
