### ISSUE TITLE
Intro sent after first message when email removed

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1824]
In this instance, visitor sent message and entered name and email. The email was invalid so we removed this prior to sending the update.

On sending the update, the auto-greeting message then appeared.

That should not trigger if the message is sent by the staff user, even if the email is removed as it then looks silly.

**To Reproduce**

1. Start message, enter email/name and message.
2. Remove email from conversation via the admin side
3. Reply to conversation.

**Expected behavior**

Only the replied message should show. There should be no auto-prompt or request for email as would be seen with a new conversation.

**Screenshots**

![Screenshot 2021-02-23 at 2 12 43 PM](https://user-images.githubusercontent.com/15971590/108856165-ac13c400-75e1-11eb-9d89-ae348e0197fa.png)

**Comment by pranavrajs** [comment]
Closed via #1842
