### ISSUE TITLE
Checking for new messages is painfully slow and repetitive

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1825]
**Describe the bug**

Going to the tab (/app/accounts/1/inbox/1) of my relevant inbox, I do not get the latest messages, especially if 3h ago the computer was suspended.
Hitting F5 reloads something but doesn't load the latest reply on the active chat for example neither.
I have to close the tab and open it again.

On the Android app it's even worse. When I open it, it often requires me to log in again but even if not, it starts off on the equivalent of /app/accounts/1/dashboard I think, not my relevant inbox and I always have to filter by the correct inbox manually. Again and again and again. 

**Expected behavior**

On Browser: Ideally check even when the tab is not in the foreground and show when there is new messages like all those instant messengers do but at least when I switch to the "inbox 1" tab make sure to correctly load the current state without further hoops and loops.

On App: Ideally show a notification for new messages on selected inboxes but at least, when I open the app, don't ask for my credentials and don't switch to the dashboard if I was in a particular inbox before. And of course instantly load new messages.

**Environment**

Self hosted installation of Chatwoot v1.10.0 CapRover.

**Comment by pranavrajs** [comment]
@Giszmo Can you please try to update to the latest version of Web (1.13.1) and Mobile app and see if the problem still exists?

**Comment by iammattmartin** [comment]
I believe it does. We have the latest version and if the page is left, until we hard refresh, it does not update.

This sometimes affects conversations since resolved, that you go click resolve again and it re-opens them.

Same with updates, it could have been updated elsewhere, it looks unanswered so a new one is posted and then you refresh and both appear - this looks bad.

**Comment by sojan-official** [comment]
@iammattmartin is it the case that the page will miss some updates if the internet connection was disrupted.  Or are you experiencing it on a regular basis?

**Comment by iammattmartin** [comment]
Very regularly. Happens if a window/tab is not used in a while. It could be due to a loss in connection but I would say that needs to be improved as there is no visual indication in the interface that it has lost a connection.

**Comment by sojan-official** [comment]
@iammattmartin  thanks for the feedback we are working on some changes to address this.
