### ISSUE TITLE
Channel greeting message no longer works when pre-chat form active

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1827]
**Describe the bug**

When using pre-chat form in v1.13.1 (dev), it no longer fires the **Channel greeting message** after the visitor has entered the name/email/message.

It does fire if you disable pre-chat form.

![Screenshot 2021-02-24 at 6 03 40 PM](https://user-images.githubusercontent.com/15971590/109044706-a3e38380-76ca-11eb-88f2-d62737531525.png)

**Comment by pranavrajs** [comment]
I guess #1824 is related to this. @sojan-official Can you please take a look at this?

**Comment by iammattmartin** [comment]
This may need some further review and a re-open @pranavrajs.

Even though that earlier task is resolved. We still see instances where this does not happen.

The message does show on the admin side and if the visitor refreshes the page it appears but it does not do in real time without them reloading the page.

It doesn't always occur but we've managed to replicate it a few times now in testing but there is no difference in our request between the times it does happen and the times it does not.

**Comment by pranavrajs** [comment]
Let us re-investigate

**Comment by sojan-official** [comment]
Closing this since there hasn't been reports of this for a while. Let's reopen in case of reports.
