### ISSUE TITLE
Add GH Icon in the website footer.

### ISSUE THREAD

**Issue by soorajshankar** [chatwoot/chatwoot#1832]
it'd be nice if you add GitHub Icon here.
![image](https://user-images.githubusercontent.com/8408875/109179664-242fe480-77b0-11eb-9dc4-02377496a388.png)

 Header or footer is the first place to look for the Github link with most of the OSS projects.

**Comment by pranavrajs** [comment]
Closing as this is done.

**Comment by pranavrajs** [comment]
<img width="357" alt="Screenshot 2021-02-28 at 1 40 04 PM" src="https://user-images.githubusercontent.com/2246121/109421589-06f05580-79fe-11eb-9bab-60e8d70cd9bb.png">
