### ISSUE TITLE
Telegram Integration

### ISSUE THREAD

**Issue by trashcluster** [chatwoot/chatwoot#1843]
Hi, I have considered building a Telegram bot as a communication channel but i see that telegram is already in the list, only greyed out. 
Is this feature soon coming up or would you need help implementing it ?

**Comment by sojan-official** [comment]
@trashcluster  We had plans to implement a telegram integration, But it got deprioritized because of the lack of community interest around it.  
If you thinking to contribute, we will happy to help you with the PR.

**Comment by hartois** [comment]
I also need integration with Telegram. I plan to implement through Channel:Api

**Comment by trashcluster** [comment]
> 
> 
> I also need integration with Telegram. I plan to implement through Channel:Api

I thought about implementing Telegram integration as a standalone telegram client using MTproto, that way the end-user will have the most seamless experience as it will seem like a real telegram user and not a bot.

**Comment by sojan-official** [comment]
@trashcluster I agree with you that a conversation via a real telegram user would feel more personal. But adding an integration via bot would open up additional APIs like payments, storefront etc. 

It also seems like most of the customer support software providers have gone with using telegram bots instead of the user accounts.

**Comment by Turab** [comment]
> @trashcluster We had plans to implement a telegram integration, But it got deprioritized because of the lack of community interest around it.
> If you thinking to contribute, we will happy to help you with the PR.

After Whatsapp privacy changes, Telegram had a great deal of increase in the market. Although it may look like there is little interest; Chatwoot shall be ready when it boosts.

**Comment by stap780** [comment]
Hello!
somebody have news about telegram integration? 
i find that gemfile have telegram-bot gem. Maybe plans become reals?
I am looking for something that like rocketchat but more useful and on ruby. And telegram is last main feature that we need.
Our market Russia. And we thinking about using chatwoot as conversation platform for saas service like [Insales](https://www.insales.com/) (shopify analog).

**Comment by sojan-official** [comment]
Remaining Tasks 

- [ ] Add specs 
- [ ] Ensure recieving image attachments works
- [ ] Test & Merge the PR
