### ISSUE TITLE
I can't pass additional attributes.why?

### ISSUE THREAD

**Issue by NitinNR** [chatwoot/chatwoot#1844]
Response of that api generated request not containing the additional attributes which had pass with that request, please give me the solution.

**Comment by pranavrajs** [comment]
@NitinNR Can you please follow the issue template to create an issue?

Please share the payload you are passing and the response you are getting.

**Comment by NitinNR** [comment]
request:
dictToSend = {
      "content": message,
      "message_type": msg_type,
      "private": False,
      "content_type": "cards",
      "additional_attributes":{"name":"nitin"},
      "content_attributes": {
        "items":[
          {  
            "actions":[
            { 
              "text":message
              
            }
            ]
          }
        ]  
      }

    }

response:
{'id': 2456, 'content': 'hello', 'created_at': '2021-03-02T06:24:54.000Z', 'message_type': 'incoming', 'content_type': 'cards', 'private': False, 'content_attributes': {'items': [{'actions': [{'text': 'hello'}]}]}, 'source_id': None, 'sender': {'id': 143, 'name': '139004189363', 'avatar': 'https://www.gravatar.com/avatar/d5e3eb645bd11dfbf8af323c8f97fb73?d=404', 'type': 'contact'}, 'inbox': {'id': 13, 'name': 'test3'}, 'conversation': {'additional_attributes': {}, 'can_reply': True, 'channel': 'Channel::Api', 'id': 66, 'inbox_id': 13, 'messages': [{'id': 2456, 'content': 'hello', 'account_id': 4, 'inbox_id': 13, 'conversation_id': 66, 'message_type': 0, 'created_at': 1614666294, 'updated_at': '2021-03-02T06:24:54.000Z', 'private': False, 'status': 'sent', 'source_id': None, 'content_type': 'cards', 'content_attributes': {'items': [{'actions': [{'text': 'hello'}]}]}, 'sender_type': 'Contact', 'sender_id': 143, 'external_source_ids': {}, 'sender': {'additional_attributes': {}, 'email': '139004189363@gmail.com', 'id': 143, 'identifier': None, 'name': '139004189363', 'phone_number': '139004189363', 'pubsub_token': 'KJufmGSPVwsNbSdxbfjbsQP7', 'thumbnail': 'https://www.gravatar.com/avatar/d5e3eb645bd11dfbf8af323c8f97fb73?d=404', 'type': 'contact'}}], 'meta': {'sender': {'additional_attributes': {}, 'email': '139004189363@gmail.com', 'id': 143, 'identifier': None, 'name': '139004189363', 'phone_number': '139004189363', 'pubsub_token': 'KJufmGSPVwsNbSdxbfjbsQP7', 'thumbnail': 'https://www.gravatar.com/avatar/d5e3eb645bd11dfbf8af323c8f97fb73?d=404', 'type': 'contact'}, 'assignee': {'id': 4, 'name': 'Mustafa Fresh Bot', 'available_name': 'Mustafa Fresh Bot', 'avatar_url': 'https://www.gravatar.com/avatar/2d523340e54bbe77aef511f89a7cf289?d=404', 'type': 'user', 'availability_status': 'online'}}, 'status': 'open', 'unread_count': 1, 'agent_last_seen_at': 1614666042, 'contact_last_seen_at': 0, 'timestamp': 1614666294}, 'account': {'id': 4, 'name': 'annonymousstark@gmail.com'}, 'event': 'message_created'}

**Comment by NitinNR** [comment]
Please tell me the fix

**Comment by iammattmartin** [comment]
Please be patient. If you've paid for support, you can reach them by email for urgent assistance.

**Comment by sojan-official** [comment]
@NitinNR  the payload you are trying to send suggests that you are hitting the message creation endpoint. Messages don't have an attribute called `additional_attributes`. If you want to update additional_attributes, do it while you are creating the conversation.  

Also when creating an issue it's helpful for the team to have the `end_point` you are trying to hit along with the payload.

**Comment by NitinNR** [comment]
But we always create conversation only once if it is not exist.need to filter the messages that's why

**Comment by NitinNR** [comment]
So, you mean that just create blank additional attributes field when conversation get created then update when sending to messages end point  right?

**Comment by sojan-official** [comment]
> But we always create conversation only once if it is not exist.need to filter the messages that's why

depends on how you decide to build on top of chatwoot. Chatwoot supports multiple conversations for a single contact. So you could create additional conversations.

**Comment by sojan-official** [comment]
> So, you mean that just create blank additional attributes field when conversation get created then update when sending to messages end point right?

At the moment we don't support update conversation objects, so the only time when you can add additional attributes to the conversation is during the conversation creation.

**Comment by NitinNR** [comment]
> > So, you mean that just create blank additional attributes field when conversation get created then update when sending to messages end point right?
> 
> At the moment 

> > So, you mean that just create blank additional attributes field when conversation get created then update when sending to messages end point right?
> 
> At the moment we don't support update conversation objects, so the only time when you can add additional attributes to the conversation is during the conversation creation.

But we can't create new conversations for each message this will be annoying for users.

**Comment by sojan-official** [comment]
@NitinNR  Could you describe what's your use case and how the additional attributes help you?

**Comment by NitinNR** [comment]
Like whenever a new message get created it should cary more additional attributes like anything we need to pass for further logic that's why we want to add additional data in it.

**Comment by NitinNR** [comment]
Ok somehow I managed to achieve my goal.
