### ISSUE TITLE
Fix "method_lines" issue in app/javascript/dashboard/components/widgets/chart/BarChart.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#185]
Function `mounted` has 32 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/dashboard/components/widgets/chart/BarChart.js#issue_5db52e4230b57200010001a7

**Comment by sarslanoglu** [comment]
@pranavrajs I can take a look if it's possible

**Comment by pranavrajs** [comment]
@sarslanoglu Please feel free to take it.

**Comment by pranavrajs** [comment]
closed via #189
