### ISSUE TITLE
Feature: Adding support for short code API with twilio

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1853]
Estimation - 3
**Context**
Chatwoot supports integration with twilio API. Right now it assumes the twilio phone number to a normal phone number which includes country code. Twilio also has a short code API which is mainly used for promotional purposes and high volume purposes.
https://www.twilio.com/docs/sms/api/short-code

- If Chatwoot would not force a + in front of the phone number, the short code just might work. 
-  Some short codes can be 6 digits. So, if you could add to your Channel Type selector a "Short Code", then require minimum 5 maximum 6 digits.

**Comment by pranavrajs** [comment]
Closing this as the feature is already available.
