### ISSUE TITLE
docker installation problem on register

### ISSUE THREAD

**Issue by the-jojo-jj** [chatwoot/chatwoot#1861]
**Describe the bug**

**To Reproduce**

1. Docker based instalation
2.  docker-compose run --rm rails bundle exec rails db:reset
3. docker-compose up -d

**Expected behavior**

**Screenshots**
<img width="1369" alt="Screen Shot 2021-03-06 at 15 57 56" src="https://user-images.githubusercontent.com/70043720/110201324-14da2680-7e95-11eb-9566-7c12815b47d1.png">

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@the-jojo-jj Where did you get the URL `/register`, our signup URL is `<installation-url>/app/auth/signup`?

**Comment by the-jojo-jj** [comment]
Hi @pranavrajs thanks for your insight. 
yes, i was pointing to the wrong url, indeed i didn't check .env file. 

thanks.
