### ISSUE TITLE
Sounds trigger on events

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1864]
**Describe the bug**

Following the newly added sound notifications, these appear to trigger at odd times.

When closing a ticket the sound triggers as does when a ticket is re-opened, assigned and un-assigned.

I would assume the sound should only trigger when a message is updated (from a chat message) instead of any type of update?

**Comment by iammattmartin** [comment]
Rel: #1345

**Comment by pranavrajs** [comment]
I guess this should be closed by #1859

**Comment by pranavrajs** [comment]
#1859 would limit the sound alert to only incoming messages and private notes from other users.

**Comment by sojan-official** [comment]
- Provide configuration  to limit sound alerts to only for assigned messages / specific events
