### ISSUE TITLE
Setting email via setUser not working if identifier_hash is passed

### ISSUE THREAD

**Issue by oTree-org** [chatwoot/chatwoot#1865]
**Describe the bug**

If I pass identifier_hash, the user's email is not set, and they are prompted for their email. If I comment out identifier_hash, the email is properly set. (I use identifier_hash because it enables different chat sessions in each browser tab.)

**To Reproduce**

```
 <script>
    window.addEventListener('chatwoot:ready', function () {
        console.log('in chatwoot ready')
        window.$chatwoot.setUser(`r10vvn7w`, {
            name: 'r10vvn7w', 
            avatar_url: '', 
            email: 'r10vvn7w@example.com', 
            identifier_hash: 'r10vvn7w' 
        })
    });

    (function (d, t) {
        var BASE_URL = "https://otree-chatwoot.herokuapp.com";
        var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
        g.src = BASE_URL + "/packs/js/sdk.js";
        s.parentNode.insertBefore(g, s);
        g.onload = function () {
            window.chatwootSDK.run({
                websiteToken: 'n7qdSghTgas1KdXCxf5mayUM',
                baseUrl: BASE_URL
            })
        }

    })(document, "script");
```
**Environment**

I am self hosted, just set up today via Heroku button. Tested on Chrome and FF.

**Comment by pranavrajs** [comment]
@oTree-org You have to generate identifier hash as shown in https://www.chatwoot.com/docs/website-sdk/identity-validation

**Comment by pranavrajs** [comment]
Can you please share how you are generating the identifier_hash?

**Comment by oTree-org** [comment]
Hi, thanks for the info! However, I am still unable to get it to work. I used the Python code:

```
        message = bytes('webwidget.hmac_token', 'utf-8')
        # participant.code is the unique id for the person, like o3bai922 in the JS below.
        secret = bytes(participant.code, 'utf-8')
        hash = hmac.new(secret, message, hashlib.sha256)
        participant.identifier_hash = hash.hexdigest()
```

Now my JS looks like:

```
    window.addEventListener('chatwoot:ready', function () {

        window.$chatwoot.setUser('o3bai922', {
            name: 'o3bai922',
            email: 'o3bai922@example.com',
            identifier_hash: '9873b7266f9073c646ced7c6d2d12f19e93a8c2b69766af81590dbdf23a75158'
        })
        console.log('set identifier_hash')
    });

    (function (d, t) {
        var BASE_URL = "https://otree-chatwoot.herokuapp.com";
        var g = d.createElement(t), s = d.getElementsByTagName(t)[0];
        g.src = BASE_URL + "/packs/js/sdk.js";
        s.parentNode.insertBefore(g, s);
        g.onload = function () {
            window.chatwootSDK.run({
                websiteToken: 'iMR5T1jWcjMb681G5w6Pap3r',
                baseUrl: BASE_URL
            })
        }
    })(document, "script");
```

My console.log() is printing properly. But:

(1) the user is still prompted for their email, and in the chatwoot admin UI we have no email for them (just an id like sparkling-sky-162)
(2) when i have 2 tabs open in the same browser testing 2 users, it mixes their chat messages together, I guess because the tabs share the same cookie. I would like each chat to be isolated from others and just based on the unique ID in the javascript code. Actually this seemed to be working earlier, but now is not working.

If I remove identifier_hash, problem 1 goes away.

**Comment by oTree-org** [comment]
By the way, that JS code is from my browser's "view source". On the server side I generate a unique ID for each user:

```
        window.$chatwoot.setUser('{{ participant.code }}', {
            name: '{{ participant.code }}',
            email: '{{ participant.code }}@example.com',
            identifier_hash: '{{ participant.identifier_hash }}'
        })
```

**Comment by marcel-necker** [comment]
@oTree-org did you set your actual token in your python code above?:

`message = bytes('webwidget.hmac_token', 'utf-8')`

should be something like:
`message = bytes('n73sgh83...', 'utf-8')`

_"The key used to generate HMAC for each webwidget is different and can be copied from Inboxes -> Settings -> Configuration -> Identity Validation -> Copy the token shown there"_
Source: https://www.chatwoot.com/docs/website-sdk/identity-validation

**Comment by oTree-org** [comment]
Thanks Marcel. I didn't do that; will try later. 

(By the way, from the code sample, it wasn't obvious to me that `'webwidget.hmac_token'` was supposed to be replaced with something, as opposed to being just a string literal.)

**Comment by sojan-official** [comment]
@marcel-necker  Thanks for spotting that 
@oTree-org  We will look into the documentation and see how we can improve it.
