### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1866]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to see the screen, or at least the browser window of the visitor. This could help with support help or even sales queries when talking through things with the visitor.

Should either be allowed during an active chat by default, or the staff can send a share request to the user which they can accept or deny.

**Comment by pranavrajs** [comment]
Closing this as the video call / screenshare option is now available via Dyte integration. https://www.chatwoot.com/docs/product/features/dyte/

**Comment by iammattmartin** [comment]
This seems to require video/audio chat though and seems to force that as a workaround. Not really the solution I would have liked. I'm sure others might feel the same.
