### ISSUE TITLE
Invalid forward email on setting up Email inbox

### ISSUE THREAD

**Issue by successful-fella** [chatwoot/chatwoot#1867]
I followed [this guide](https://www.chatwoot.com/docs/conversation-continuity) to setup email channel which is recently enabled on Chatwoot. I'm getting some-alphanumeric@false ID to forward incoming support emails to.

![image](https://user-images.githubusercontent.com/61019742/110243690-74156500-7f81-11eb-8324-850bf47c54da.png)

**To Reproduce**

1. Fill environment RAILS_INBOUND_EMAIL_SERVICE and RAILS_INBOUND_EMAIL_PASSWORD
2. Start by adding email channel using Inbox option
2. Type in channel name and your support email, my case I wrote care@mydomain.com
3. Add agent(s) to inbox, I'd added myself.
4. It shows forward emails to given some-alphanumeric@false ID which is clearly invalid.

**Server logs**

I'm using caprover, running *docker service logs srv-captain--my-app --since 1m --follow* gives no logs.

**Environment**

Self hosted, Docker, Caprover

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  88.0.4324.190

**Comment by sojan-official** [comment]
@successful-fella  do you have conversation continuity set up on this installation ?
https://www.chatwoot.com/docs/conversation-continuity

**Comment by pranavrajs** [comment]
@successful-fella Removed the label `Bug` as it seems that it is a setup issue.

**Comment by successful-fella** [comment]
@pranavrajs Thank you. I'm still not sure if this is a setup issue. I'm trying to verify if I've done everything correctly.
In any case, it would be better to add a error/warning notification while settings up email inbox so to let users know that it has not been configured properly.

**Comment by successful-fella** [comment]
I'd SSH into docker container, enabled inbound_emails, and set account domain on rails console. I can see random-hex@domain.com now. I previously thought that Chatwoot recently enabled the email channel so I would not have to run commands mentioned at end of that guide. Though the email channel still won't create new conversations, that may be an issue with my postfix configuration and not chatwoot. Closing this issue, thanks for replying!
