### ISSUE TITLE
Manipulate messages content before they are delivered to visitor/agent?

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#1875]
**Is your feature request related to a problem? Please describe.**
No. It's a question that I cant find in the docs and was suggested by Nithin to post it here :)

**Describe the solution you'd like**
I would like to string-manipulate messages from visitors/agents before they are delivered to the other party. 

Ideally server-side, but could also be client-side.

As an example, if I want to make a small app to remove swearing from the chat messages from both visitor/agent.

Thank you for any input or pointers :-)

**Comment by pranavrajs** [comment]
It looks like you are suggesting #1280

**Comment by pranavrajs** [comment]
Closing this in favor of https://github.com/chatwoot/chatwoot/issues/1280#issuecomment-718776202

**Comment by brundles** [comment]
No @pranavrajs - I actually meant that I could manipulate the contents. I could as an example add links or do a realtime translation of the contents to German or whatever I wanted to do.
