### ISSUE TITLE
Getting access token

### ISSUE THREAD

**Issue by aekanshpartani** [chatwoot/chatwoot#1877]
**Is your feature request related to a problem? Please describe.**
I am working on using chatwoot APIs to integrate with our panel. But when we create a new user using platform APIs I don't get access token, I just get pub_sub token in response. 

**Describe the solution you'd like**
It will be great to get the access token as well either while creating or through a separate API maybe by using email/password combination.
If such things exists I didn't find it in documentation as suggested here - https://www.chatwoot.com/developers/api/#section/Authentication/userApiKey

Any help or guidance will be appreciated.

**Comment by sojan-official** [comment]
@aekanshpartani  the intention while building platform APIs was to return the access_token too in with the response body. Think we missed it out. We will take this up for our upcoming release. 

also If you are interested in taking it up, feel free to raise PR.

**Comment by aekanshpartani** [comment]
@sojan-official Okay thanks. Will try to make it work.
