### ISSUE TITLE
Run chatwoot prepare and migrate as a part of docker image

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1882]
**Is your enhancement request related to a problem? Please describe.**
I don't want to run migrate and prepare db scripts after installing a docker image on my machine. 

**Describe the solution you'd like**
Run the command as and when the image is deployed to a container.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by srameshr** [comment]
PR: https://github.com/chatwoot/chatwoot/pull/1876

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/1876#issuecomment-798765538
