### ISSUE TITLE
admin must be able to see the BOT conversations as well

### ISSUE THREAD

**Issue by JennyPrabhu** [chatwoot/chatwoot#1883]
**Is your feature request related to a problem? Please describe.**
My admin must be able to see the BOT conversations as well. 

**Describe the solution you'd like**
The BOT messages to be displayed in the admin console. 
So the ability to transfer the conversation between one inbox (chatbot) to another (human agent). 

**Describe alternatives you've considered**
Tried using the chatbot integration (rasa_route) but those conversations are not displayed in the admin console. The admin should be able to monitor the BOT conversations as well.

**Comment by sojan-official** [comment]
Admins / Agents already have the ability to filter and view BOT conversations. They can assign these conversations to themselves if they feel it's relevant.

<img width="969" alt="Screenshot 2021-03-09 at 6 28 52 PM" src="https://user-images.githubusercontent.com/73185/110474210-6852ab80-8105-11eb-83aa-5f7896889fe7.png">
