### ISSUE TITLE
Support variables in canned response

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#1886]
**Is your enhancement request related to a problem? Please describe.**  
- [x] Agents are frustrated using canned responses as they are quite unreadable (the autocomplete box is narrow, see screenshot).   
- [x] Agents find it really difficult to search through canned responses, as you have to know the exact keyword to find them.
- [ ] Add a {{agentName}} kind of variable in canned responses, so that they can feel personalised for the end user.

**Describe the solution you'd like**    
Propose the autocomplete but also propose a way to categorize canned responses to search through canned responses by category as well.    
  
**Describe alternatives you've considered**  
Implement a more complex search through canned responses ?    
I don't really know...    
   
**Additional context**  
<img width="760" alt="Screenshot 2021-03-09 at 19 49 13" src="https://user-images.githubusercontent.com/16147835/110521831-8bcf2380-8110-11eb-9474-9ba1409a64da.png">

**Comment by nithindavid** [comment]
Hey @Brokray
1. We have updated the design, in our latest release it's long and occupies full width.
2. I'll look into improving the search experience.

**Comment by Brokray** [comment]
Thank you for the quick feedback.   
I will definitely update my hosted Chatwoot then, thanks.    

Something else one of my agent just brought up : 
- Add a `{{agentName}}` kind of variable in canned responses, so that they can feel personalised for the end user. 

But this idea is more of a new feature. Would you like me to create another ticket for the later idea ?

**Comment by pranavrajs** [comment]
@Brokray No need, I just updated the title.

**Comment by popeeyy** [comment]
I would also like to see variables in canned responses, and make sure they include custom variables that are set by the website page so we can give users information about their account easier. Adding onto this, it would be nice if we could also change the entire response based on a variable, such as their browser. For example, if you want to instruct someone to do something that changes based on the browser, it would be much easier to be able to replace the entire message or maybe even chunks of a message based on a variable.

**Comment by sojan-official** [comment]
An improvement will be available in our latest release which will improve the canned response search. 
The keyword search is performed across the short ode as well as the response content, so uses should see better search results. 
ref: https://github.com/chatwoot/chatwoot/commit/add004a56e9c7155659f602f818775fa1a80b852

**Comment by heroic** [comment]
We've added variables in canned responses in our fork. Happy to contribute it back. We're passing an extra parameter in the get api, `conversation id`, and adding contact level variables for now. It should be easy to add more variables based on need. We're using variables like Zendesk does.

Using liquid for templating, so it should be possible to even allow conditions, and some logic if so desired

**Comment by sojan-official** [comment]
@heroic  Raising a PR would be awesome. The team can evaluate the approach and give feedback, as well as some of the community members to give a it a try as well.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3078

**Comment by pranavrajs** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/issues/2084
