### ISSUE TITLE
Feat: Add a rating system to rate agents.

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#1890]
**Is your feature request related to a problem? Please describe.**
When the conversation is resolved our administrator does not really have any way of telling if the agent's answer was acceptable for the end user.

**Describe the solution you'd like**
If the feature is activated : on conversation resolution propose a simple rating system with a customizable message.   
This would rate the conversation itself.   
Later we could find agents notation in stats based on conversations they have answered, or helped answer.

**Comment by aydenbottos** [comment]
Yes, this would be amazing!

**Comment by sojan-official** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/issues/2472
