### ISSUE TITLE
Improvement to path when offline

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1900]
**Is your enhancement request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When offline (i.e outside of business hours), the out of hours text is only small and may be overlooked.

When you start the chat, you only then see "we are offline" and nothing in the chat window.

I would suggest that either at the top of the window with text on a highlighted background, something like, "we'll be back on Monday at 8am" or, "tomorrow at 8am".

Maybe even adding in the timezone (GMT) etc as there is no indication of what timezone that time would be. Unless the widget can automatically provide the time based on the visitors timezone? Which would be even better.

This would then help avoid the "Hello?". "Anyone there" messages that we currently face when people can send messages in such a situation.

**Comment by iammattmartin** [comment]
Example: 
![Screenshot 2021-03-13 at 7 23 25 PM](https://user-images.githubusercontent.com/15971590/111041729-9996e880-8431-11eb-9100-02b6a44d8f79.png)

**Comment by pranavrajs** [comment]
Closing this as the feature is available now. 

<img width="383" alt="Screenshot 2023-12-05 at 1 14 26 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/1bac2ceb-d004-4bea-8f1a-fa0bf4008a7d">
