### ISSUE TITLE
SMTP mail no longer sending

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#1903]
**Describe the bug**

Outbound messages no longer initiate with the SMTP server set in .env on latest develop.

Checking mail logs, there is no connection attempts to the server.

Our setup has always been, and has not changed since it was last working.

```
# Mail outgoing
MAILER_SENDER_EMAIL=email@email.com
SMTP_PORT=25
SMTP_DOMAIN=localhost
# if you are running docker-compose, set SMTP_ADDRESS value as "mailhog",
# else set the value as "localhost"
SMTP_ADDRESS=localhost
#SMTP_USERNAME=
#SMTP_PASSWORD=
SMTP_AUTHENTICATION=none
SMTP_ENABLE_STARTTLS_AUTO=false
MAILER_INBOUND_EMAIL_DOMAIN=messenger.mail
```

**Comment by iammattmartin** [comment]
Errors in sidekiq

```
ArgumentError: wrong authentication type none
```

**Comment by iammattmartin** [comment]
Commenting that out and removing the value do not help.

The "none" option is needed where the SMTP server does not need authentication as is the case for when the SMTP server is on localhost.

**Comment by iammattmartin** [comment]
Even removing the line SMTP_AUTHENTICATION entirely, CW still seems to connect with an AUTH request when it shouldn't be doing so.

`none` appears to be an invalid option for the mailer anyway but the mailer docs say:

```
:authentication - If your mail server requires authentication, you need to specify the authentication type here. This is a symbol and one of :plain, :login, :cram_md5.
```

The big take away there is "if your mail server". Which ours does not but there appears to be no way to stop CW trying to use it now.

**Comment by sojan-official** [comment]
@iammattmartin  the previous version of chatwoot has some mailer config hardcoded that prevented few users from being able to use their mail servers.  

so the config used to look like this 
https://github.com/chatwoot/chatwoot/blob/6ba25bae3d4167f34e957b563875a553910be793/config/environments/production.rb#L103
```
config.action_mailer.smtp_settings = {
    address: ENV['SMTP_ADDRESS'],
    port: ENV['SMTP_PORT'] || 587,
    user_name: ENV['SMTP_USERNAME'],
    password: ENV['SMTP_PASSWORD'],
    authentication: :login,
    enable_starttls_auto: true
  }

```

where the authentication type and `enable_starttls` weren't taking in values from environment variables. 

comparing the values in your config it seems like  `SMTP_ENABLE_STARTTLS_AUTO` is set to `false` . Could you try updating that environment variable to `true` and restart the server ?

**Comment by iammattmartin** [comment]
No luck with that.

```
Mar 13 19:16:22 messenger postfix/smtpd[6061]: lost connection after AUTH from localhost[127.0.0.1]
Mar 13 19:16:22 messenger postfix/smtpd[6061]: disconnect from localhost[127.0.0.1] ehlo=1 auth=0/1 commands=1/2
```

My config now reads

```
# Mail outgoing
MAILER_SENDER_EMAIL=email@email.com
SMTP_PORT=25
SMTP_DOMAIN=localhost
# if you are running docker-compose, set SMTP_ADDRESS value as "mailhog",
# else set the value as "localhost"
SMTP_ADDRESS=localhost
#SMTP_USERNAME=
#SMTP_PASSWORD=
#SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
```

**Comment by sojan-official** [comment]
@iammattmartin I have pushed a fix. Could you give it a check?

**Comment by iammattmartin** [comment]
Looking good. Queued mail all gone out and new notifications are leaving.

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/1907
