### ISSUE TITLE
Wrong error message when login fails for non activated accounts

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1915]
**Describe the bug**

When I try to re-login into an account after logging out without activating the account via an email, it fails with a confusing error message.

**To Reproduce**

1. Signup with a dummy account and go to dashboard but don't activate your account via email auth.
2. Logout of the account
3. Try to login again.
4. You see a "bad password" error message.

**Expected behavior**
The error message should be
```
A confirmation email was sent to your account at 'myemail@mydomain.com'. You must follow the instructions in the email before your account can be activated
```

**Screenshots**

N/A

**Browser logs**

```
Request URL: https://app.chatwoot.com/auth/sign_in
Request Method: POST
Status Code: 401 Unauthorized
Remote Address: 3.224.159.100:443
Referrer Policy: strict-origin-when-cross-origin
Response: {"success":false,"errors":["A confirmation email was sent to your account at 'account1@asdf.com'. You must follow the instructions in the email before your account can be activated"]}
  ```

**Server logs**

NA

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku): app.chatwoot.com

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Any
 - Browser [e.g. chrome, safari]  Any
 - Version [e.g. 22] Latest

**Additional context**

N/A

**Comment by bijoysijo** [comment]
@srameshr 

When I tried this out, 

I visit chatwoot.com -> click on create an account -> fill out my full name, account name and work email -> got redirected to the dashboard (without any prompt asking / telling me that a confirmation email has been sent and that I should set a password using it) -> I sign out -> then try to sign back in with same mail id -> I get asked for a password (this is another point where I should have got a prompt saying, please set a password using confirmation link, which doesn't happen, and yet the sign-in page asks me for a password after I enter my mail id) -> I enter random password -> get a wrong password error.

The workflow could be modified to,

User signs up -> gets a message on the page, saying "please confirm your account via mail to continue sign up" -> user visits link send in mail -> upon confirming and setting a password, gets redirected to the dashboard.

or

User signs up -> account is created without a password being set -> user is taken to dashboard -> user signs out -> user tries signing in again -> user is prompted for mail id and password -> user enters mail id (let's say the user enters a random password) -> the error message should say, "please confirm your account" (although the first workflow would be more ideal, just my opinion 😄 )

**Comment by srameshr** [comment]
I chose the second part. I've added a lot of redundant checks because I don't know if the error will always be an array of strings. Also, by the way how come there is no option anywhere through the app to request a confirmation email once again.
```
      this.$store
        .dispatch('login', credentials)
        .then(() => {
          this.showAlert(this.$t('LOGIN.API.SUCCESS_MESSAGE'));
        })
        .catch(response => {
          // Reset URL Params if the authentication is invalid
          if (this.email) {
            window.location = '/app/login';
          }
          if (response && response.status === 401) {
            const { errors } = response.data;
            if (
              errors &&
              errors.length &&
              errors[0] &&
              typeof errors[0] === 'string'
            ) {
              this.showAlert(errors[0]);
            } else {
              this.showAlert(this.$t('LOGIN.API.UNAUTH'));
            }
            return;
          }
          this.showAlert(this.$t('LOGIN.API.ERROR_MESSAGE'));
        });
        ```

**Comment by srameshr** [comment]
@sojan-official Does this fix work for now?

**Comment by srameshr** [comment]
@sojan-official Do you think this PR will work if I raise one?

**Comment by sojan-official** [comment]
@srameshr  we are planning to revamp the current signup flow to include a password field right at the start. 
This looks good for a temporary fix until then. 

cc: @nithindavid

**Comment by srameshr** [comment]
Should I send a PR for this?

**Comment by sojan-official** [comment]
@srameshr  please go ahead
