### ISSUE TITLE
SSL ERROR: Cant send outbound email on version 1.14.0

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1922]
**Describe the bug**

A confirmation email, as well as email inbox, fails with the below logs 
```
Sidekiq(mailers) in 86.46ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))
```

**To Reproduce**

1. Create an account and see the worker logs for mail delivery
2. Or
3. Create an inbound email channel and see the logs

**Expected behavior**

As in pervious versions.

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

```
2021-03-16T11:07:36.189Z pid=1 tid=3481 class=ActionMailer::MailDeliveryJob jid=8d79d4b2580511dccdc39e1f INFO: start
I, [2021-03-16T11:07:36.424035 #1] INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [8c2da4fa-b457-43ea-9d0a-122ce57ff16e] Performing ActionMailer::MailDeliveryJob (Job ID: 8c2da4fa-b457-43ea-9d0a-122ce57ff16e) from Sidekiq(mailers) enqueued at 2021-03-16T11:07:36Z with arguments: "Devise::Mailer", "confirmation_instructions", "deliver_now", {:args=>[#<GlobalID:0x00007f5e25c9ae48 @uri=#<URI::GID gid://chatwoot/User/5>>, "iBnuHZcud-mMVLidh3NV", {:client_config=>"default", :redirect_url=>nil}]}
I, [2021-03-16T11:07:36.446160 #1] INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [8c2da4fa-b457-43ea-9d0a-122ce57ff16e] Rendering devise/mailer/confirmation_instructions.html.erb within layouts/mailer/base
I, [2021-03-16T11:07:36.447726 #1] INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [8c2da4fa-b457-43ea-9d0a-122ce57ff16e] Rendered devise/mailer/confirmation_instructions.html.erb within layouts/mailer/base (Duration: 1.4ms | Allocations: 280)
I, [2021-03-16T11:07:36.510413 #1] INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [8c2da4fa-b457-43ea-9d0a-122ce57ff16e] Delivered mail 6050917875f98_12382070824@worker-chatwootcrm-docker-c49949549-2f7bv.mail (28.1ms)
E, [2021-03-16T11:07:36.510691 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [8c2da4fa-b457-43ea-9d0a-122ce57ff16e] Error performing ActionMailer::MailDeliveryJob (Job ID: 8c2da4fa-b457-43ea-9d0a-122ce57ff16e) from Sidekiq(mailers) in 86.46ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))
```
**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku): Docker

**Desktop (please complete the following information):**

 - Version [e.g. 22]: 1.14.0

**Smartphone (please complete the following information):**
N/A

**Additional context**

N/A

**Comment by sojan-official** [comment]
@srameshr there was some hardcoded environment variables in the previous version, which we have made customizable.  
https://github.com/chatwoot/chatwoot/issues/1903#issuecomment-798711893

So could you check whether you have all those environment variable available in production or the value different from whats was set as default? 

primarily values for

smtp_authentication
smtp_enable_starttls_auto

```
 authentication: :login,
 enable_starttls_auto: true
```

**Comment by srameshr** [comment]
@sojan-official 
These are my environment variables and values for what you asked:

```
SMTP_AUTHENTICATION plain
SMTP_ENABLE_STARTTLS_AUTO true
```

**Comment by srameshr** [comment]
Also, adding an inbox email succeeds but when adding the new mail generated as the forwarding address to my mail account fails with this message to my inbox.

```

Address not found
--
Your message wasn't delivered to 79dee7852de4e44ed2de7c18498a0155@myorg.com because the address couldn't be found, or is unable to receive mail.

```

**Comment by srameshr** [comment]
@sojan-official On app.chatwoot.com I can add an inbound email channel and set the forwarding address successfully but I don't receive any emails nor can I send any email to and from the dashboard after adding the channel. 

None of the emails sent to the address shows up on the dashboard.

**Comment by srameshr** [comment]
@sojan-official 
Ok, so I got it. You have set openssl_verify to peer and it's not able to find the SSL certificate path. But setting SSL_CERT_DIR and SSL_CERT_FILE env variables in a generic Ruby application should solve this issue. But on Chatwoot it's not. 
Could you revert this change and push a hotfix?

**Comment by sojan-official** [comment]
@srameshr  there is a fix that's pushed on current develop.  There is also a couple of bugs that we need to get to.  So we will be cutting a 14.1 soon.

**Comment by srameshr** [comment]
@sojan-official Do you know why setting SSL_CERT_DIR and SSL_CERT_FILE is not picking up the cert file path and fixing that SSL error?

**Comment by sojan-official** [comment]
@srameshr  I have cut 1.14.1 which should reset automatically setting openssl_verify to peer unless it is specified. let me know if this fixes the issue.

**Comment by sojan-official** [comment]
tested in docker images with SendGrid and Mailgun config and the issue seems to be resolved

**Comment by alhazmy13** [comment]
@sojan-official i tested this with v1.14.2 docker image using mailgun and it seems the issue still exist.

error:
```
sidekiq_1   | I, [2021-03-23T03:33:03.829974 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [95d35326-0438-4ca4-8f38-dcb022a1fd01] Delivered mail 6059616f55e76_1234c4370a8@a57b1ad75be4.mail (480.5ms)
sidekiq_1   | E, [2021-03-23T03:33:03.830641 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [95d35326-0438-4ca4-8f38-dcb022a1fd01] Error performing ActionMailer::MailDeliveryJob (Job ID: 95d35326-0438-4ca4-8f38-dcb022a1fd01) from Sidekiq(mailers) in 497.74ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)):
sidekiq_1   | /usr/local/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock'
```

**Comment by sojan-official** [comment]
@alhazmy13  could you check whether your SMTP environment variables are as displayed below. and no other config is set? 

![Screenshot_2021-03-22_at_12 51 46_AM](https://user-images.githubusercontent.com/73185/112118956-e8d3da80-8be2-11eb-9d0b-89c3bca82c05.png)

if you have  `smtp_openssl_verify` environment variable, please remove that.
