### ISSUE TITLE
Manually trigger a verification email

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1924]
**Is your feature request related to a problem? Please describe.**
Sometimes, after signing up I don't get a verification email and I have no way of requesting a new verification email again from the UI dashboard. 

**Describe the solution you'd like**
Next to the agent name, if the account is not verified show a button to "Re-send Verification Email"

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by sojan-official** [comment]
For a temporary workaround, you can use the rails console to trigger a new verification email 

```
u = User.find_by(email: 'agent_email')
u.send_confirmation_instructions
```

**Comment by srameshr** [comment]
Could you expose an API to do this? I would send a PR for the dashboard to hit this from the Agents page.
