### ISSUE TITLE
Line breaks don't render in widget bubbles

### ISSUE THREAD

**Issue by digitalescapade** [chatwoot/chatwoot#1933]
**Describe the bug**

When a message is sent from agent to user and contains line breaks, it renders without any line break in chat widget bubble.

**To Reproduce**

1. Send a message that contains line break via createmessage API
2. Read it from js chat widget

**Expected behavior**

Message should display line break.
For example : 
> Line 1
> Line 2

instead of 
> Line 1 Line 2

**Environment**

Self hosted Chatwoot on Heroku

**Desktop (please complete the following information):**
 - OS: all
 - all Browser 
 - JS widget

**Comment by iammattmartin** [comment]
May be related to #1730

**Comment by sojan-official** [comment]
seems like this is the same as #1730.  closing this to track the future conversations on a single ticket.
