### ISSUE TITLE
ContactId duplicated across accounts.

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#1937]
**Describe the bug**

I have 2 different accounts and each of those accounts interacts with a customer with the email abc@xyz.com. Now, I expect 2 different contact entries in the contacts table. But, it just overrides existing contact with abc@xyz.com

**To Reproduce**

1. Use two browser windows, one in incognito so the session is not maintained.
2. Create new accounts and new inboxes and chat with those inboxes one after the other with the same customer email.
3. The account running in the non-incognito window creates contact with id say, 11
4. Now continue to talk to the other account in the incognito window. It initially creates an account with a random name and as soon as you enter the same customer email id it merges the contact as one.

**Expected behavior**

Contacts should not be merged even if they have the same email id as long as they are talking to different accounts.

**Screenshots**

N/A

**Browser logs**

N/A

**Server logs**

N/A

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku) Docker

**Desktop (please complete the following information):**
 - Version [e.g. 22]: 1.14

**Additional context**

N/A

**Comment by sojan-official** [comment]
@srameshr  Could you double-check whether the widget belongs to a different account in the test cases you mentioned?

The easiest way to do this is to use different colours for both the widget. 

  ---
  
Chatwoot isolates contact records on a per-account basis, the merge action would only happen between contacts in the same account

ref: https://github.com/chatwoot/chatwoot/blob/54d578676b25383fea9a8e8e5219aadb95f9e655/app/actions/contact_merge_action.rb#L17

But there wouldn't be separate records for the same contact across the various inboxes. 

---
I have tested this case on my end and it seems to be working fine. Let me know if you are still facing this.
