### ISSUE TITLE
Make it obvious for agent there are new messages

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#1942]
**Is your enhancement request related to a problem? Please describe.**
As an agent, I open https://app.chatwoot.com/app/accounts/3889/inbox/3137 in a tab, then go work in other browser tabs (same window).

When receiving a message from customer, I don't see it unless I go and check the tab page content, where it does show. I can't check every minute.

**Describe the solution you'd like**
1. Have the browser tab title change like Whatsapp & Trello do. Show a different favicon and (4) as number of new messages at start. Attached Trello icon with notification alert.

![2021-03-18_19-43](https://user-images.githubusercontent.com/1283842/111672079-430b1f00-8822-11eb-88a9-5ff884aee077.png)

2. Play a sound for new messages. Saw other bug opened about this as a new feature. Guess it's not in your cloud yet?

**Comment by sojan-official** [comment]
@mariusa  you should be able to enable the audio alerts by navigating to your profile setting. 

<img width="280" alt="Screenshot 2021-03-19 at 3 46 24 PM" src="https://user-images.githubusercontent.com/73185/111765369-4954d600-88ca-11eb-8817-b9f8cd42d55f.png">

**Comment by rhost** [comment]
is that possible to get audio notification, only for agent which handling current chat instead notify all active agent?

**Comment by sojan-official** [comment]
@rhost at the moment the audio notifications work for all the new conversations. We will be adding the ability to specify notification for different alert types

**Comment by connor4312** [comment]
I would love to have [browser notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) as well. This is more prominent than an audio alert (especially if I'm listening to music) and also can integrate into OS' notification centers.

**Comment by tabrza** [comment]
@sojan-official - i have enabled audio notification in the settings but am not getting any. do i need to do any additionals here?

**Comment by mariusa** [comment]
Audio notifications work for me (at https://www.chatwoot.com/)

**Comment by sojan-official** [comment]
> @sojan-official - i have enabled audio notification in the settings but am not getting any. do i need to do any additionals here?

Could you give information about the browser you are using?

**Comment by tabrza** [comment]
I'm using chrome. Do i need to set any env variables for this?
