### ISSUE TITLE
UI not updating when sending/receiving messages

### ISSUE THREAD

**Issue by strafrecht** [chatwoot/chatwoot#1948]
**Describe the bug**

When using self-hosted chatwoot with docker-compose setup, messages are displaying as "not sent" (i.e. the UI is not updating correctly, meaning the text bubbles remain light blue instead of dark blue) even though the data is sent to the server. The admin interface UI also does not update to show these new messages, and requires a refresh for them to appear.
Restarting the docker containers temporarily fixes the issue, however after ~5 hours, the issue reappears.

**To Reproduce**

1. Follow the instructions for installing via docker-compose -> [https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker](link)

**Expected behavior**

Messages bubbles should turn dark blue almost immediately, to show that the message has been sent. The admin interface should also update when new messages have been received.

**Screenshots**

**Browser logs**

Response Headers
```
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 19 Mar 2021 17:46:02 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
ETag: W/"fbd6de37b5f3f3f6c296cc31cc1ff37e"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: bef7d7de-d2a2-47cb-a2dc-9bd6629ad5f5
X-Runtime: 0.054636
Strict-Transport-Security: max-age=31536000; includeSubDomains
```
Response:
```
{"id":177,"content":"adsfdsaf","inbox_id":4,"conversation_id":8,"message_type":0,"created_at":1616175962,"private":false,"source_id":null,"sender":{"additional_attributes":{},"email":null,"id":571,"identifier":null,"name":"lively-smoke-246","phone_number":null,"pubsub_token":"C2bPKA9BETaGeUMVhuUZASZb","thumbnail":"","type":"contact"}}
```

**Environment**

Self-hosted docker-compose running on ubuntu

**Comment by ajarmoszuk** [comment]
Exact same case happening to me.

**Comment by asasr** [comment]
fhad1012@icloud.com

**Comment by pranavrajs** [comment]
@strafrecht Sorry for missing this issue. Is this still happening? Can you please provide some more information like docker logs to help me debug this further?

**Comment by sojan-official** [comment]
closing this since there hasn't been recent activity on this issue.Please reopen if the issue persists
