### ISSUE TITLE
Deploy to other websites 

### ISSUE THREAD

**Issue by irhrhd** [chatwoot/chatwoot#1949]

**Comment by iammattmartin** [comment]
You've not added any context.

What are you trying to achieve?

**Comment by irhrhd** [comment]
Like aws and azure not just heroku

**Comment by iammattmartin** [comment]
Well you can deploy anywhere as a base setup with caprover or the manual linux install instructions/docker.

https://caprover.com/
https://www.chatwoot.com/docs/installation-guide-docker
https://www.chatwoot.com/docs/installation-guide-ubuntu

If you want a more structured layout with specific services dealing with each part (i.e db etc), you'd have to do that yourself currently

**Comment by sojan-official** [comment]
like @iammattmartin  mentioned. there are no limitations on installation options. 
You can use either docker or ubuntu installations to deploy chatwoot on any service that provides a Linux vm/ containers
