### ISSUE TITLE
HTML Emails in Conversation view

### ISSUE THREAD

**Issue by Jivings** [chatwoot/chatwoot#1950]
**Is your enhancement request related to a problem? Please describe.**

The conversation viewer doesn't display HTML emails (and also doesn't display plain text emails correctly either).

**Describe the solution you'd like**

- Simplest solution is for Chatwoot to handle plain text emails correctly (it looks like it's stripping newlines right now), and even to handle the `format=flowed` [[1]] encoding since that's pretty simple.
- Full solution is to provide an HTML email viewer as well.

**Additional context**

Here is the email as shown in Helpscout:
![image](https://user-images.githubusercontent.com/1462828/111856533-545d4400-8966-11eb-9f73-fc70f9bb72d8.png)

And in Chatwoot:
![image](https://user-images.githubusercontent.com/1462828/111856527-4b6c7280-8966-11eb-8f1d-8b911cf4d0ee.png)

[1]: https://joeclark.org/ffaq.html

**Comment by sojan-official** [comment]
<img width="840" alt="Screenshot 2021-08-15 at 7 09 17 PM" src="https://user-images.githubusercontent.com/73185/129480542-d60a94ae-7bfe-4f7d-9966-48c6f27e8fa7.png">

Chatwoot now support html emails in conversation view
