### ISSUE TITLE
Bug: Fix zooming while input is active on widget

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1954]
![image](https://user-images.githubusercontent.com/1277421/111862683-e2dcc000-897c-11eb-8d6a-a6cb379c1034.png)

**Comment by pranavrajs** [comment]
@nithindavid I guess this because the font-size is 14px, not 16. If it's not 16px, the browser would auto-zoom. I think we can reconsider the font-sizes.

**Comment by Rishav-Saw** [comment]
yup that might be the case but I probably think that i have to fork it first and then I can modify it I have just made my account here and just know basics of github

**Comment by nithindavid** [comment]
@Rishav-Saw You can join our discord channel - https://discord.gg/cJXdrwS to get help.
