### ISSUE TITLE
Bug: Clear search input when page changes

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1955]
![image](https://user-images.githubusercontent.com/1277421/111862745-38b16800-897d-11eb-8474-c40b44d7b5c0.png)

**Comment by tharun208** [comment]
@nithindavid I like to work on this

**Comment by niklashaug** [comment]
@nithindavid if @tharun208 hasn't started working on this yet, I'd like to take over this issue.

**Comment by sojan-official** [comment]
@tharun208  could you give an update on whether you are still working on this? 
If not I will assign this to @niklashaug

**Comment by sojan-official** [comment]
@niklashaug  if you are still interested, please feel free to work on this.

**Comment by niklashaug** [comment]
@nithindavid The search input already gets cleared when you open another page on the sidebar (e.g. Contacts) so I think you mean that it should get cleared when you change one of the tabs (Mine, Unassigned, All), right? Should it also get cleared when the status type gets updated?

**Comment by nithindavid** [comment]
@niklashaug On the sidebar there are links to  `labels` and `inboxes`  once clicked the search is expected to clear.

On the Mine, Unassigned tab switching we do not expect to clear the search.

@sojan-official @pranavrajs Any thoughts ?

**Comment by sojan-official** [comment]
@nithindavid @niklashaug  let's clear the filters in both cases 

- when the user toggles mine unassigned all etc 
- when the user applies filter like inbox, labels etc

the way the UI works right now, the search doesn't respect the filters. it runs the query against all conversations.
So retaining the search query text even after the user navigated to a different filter will give the user a false expectation.
