### ISSUE TITLE
Collapse to smaller header when conversation is active

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#196]
**Describe the bug**
The header is to be shown only when the conversation hasn't started. When user sends a message it should collapse the `Banner` header to a smaller one. The smaller component is already in the widget source components.

**Screenshots**
![image](https://user-images.githubusercontent.com/1277421/67863175-6a881b80-fb49-11e9-9138-500e97e669ee.png)

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/426
