### ISSUE TITLE
Managing Twitter Events triggering conversations

### ISSUE THREAD

**Issue by Luuuuuis** [chatwoot/chatwoot#1961]
**Is your enhancement request related to a problem? Please describe.**
I get spammed with unrelated replies that I'm not interested in.

**Describe the solution you'd like**
A setting to manage all events that can trigger a conversation in the Twitter Inbox settings tab (e.g. DM, reply, mention, ...)

**Describe alternatives you've considered**
Resolving these conversations :/

**Additional context**
I developed a bot auto replying on German laws with the corresponding law text and it gets a lot of replies that are totally irrelevant for user support

**Comment by pranavrajs** [comment]
@Luuuuuis A little bit more context would be helpful. Can you share a screenshot or something?

Right now, the message you get is the ones with mentions or DMs. I didn't completely understand the problem you are facing.

**Comment by Luuuuuis** [comment]
Okay. My problem is that I get tons of replies, but they are completely irrelevant to me. I get them because I have a bot that auto replies with law text triggered by certain key word. But I don't want to get any conversations out of that, because the replies on that law text tweet don't interest me. I only want to get new conversations either when someone tags me in their tweet or when someone writes me a DM.   
![image](https://user-images.githubusercontent.com/45736619/111919264-65eb3c80-8a89-11eb-97e0-d8a2df693076.png)
For example here I have a conversation between two people about some kind of law thing I don't even understand and I'm not interested in. (And I have like 300 open conversations because every tweet of mine gets shown as one but you already have that report)

It would be great if there were settings I could turn that replies off.

Hope you understand my situation better now.

**Comment by amblerkr** [comment]
The tweet I retweeted will be displayed in the message box. I want to receive only DM. 
![image](https://user-images.githubusercontent.com/67187038/112114737-bda9b500-8bfb-11eb-91c1-2a2687d2cd3b.png)

**Comment by Luuuuuis** [comment]
This is my account after 3 days not looking into it :D

![image](https://user-images.githubusercontent.com/45736619/112687891-6a906600-8e78-11eb-8d95-98ecaf91c394.png)

**Comment by sojan-official** [comment]
@imc67  The client with whom we worked initially modeled the integration would receive support queries through both DMs, as well as tweets. 

This item was a lot amidst the other priorities I believe. The easiest fix I guess would be a setting for the Twitter inbox which can be toggled to stop creating conversations from tweets. We will prioritize or would be happy to support community contributions.
