### ISSUE TITLE
Slack integration error

### ISSUE THREAD

**Issue by manuelmeurer** [chatwoot/chatwoot#1962]
**Describe the bug**

Setting up the Slack integration does not work.

**To Reproduce**

1. Go to the integrations page
2. Click on "Connect" for the Slack integration
3. Select the correct Slack workspace and click "Allow"
4. Back on the integrations page, see error 500 in the console. It still says "Connect" next to the Slack integration. Connecting again does the same as first time.

**Expected behavior**

Well, connecting should work. :) I'd probably expect to be able to select a channel where Chatwoot posts messages to next?

**Screenshots**

![Chatwoot 2021-03-21 21-27-43](https://user-images.githubusercontent.com/16672/111919896-705b0580-8a8c-11eb-8955-bd0e5417cad7.png)
![Chatwoot 2021-03-21 21-28-29](https://user-images.githubusercontent.com/16672/111920039-0f7ffd00-8a8d-11eb-8f7e-1e349f7dd483.png)

**Environment**

Chatwoot Cloud (app.chatwoot.com)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 89.0.4389.90

**Comment by pranavrajs** [comment]
@manuelmeurer Thanks for reporting this. We will debug the issue.

**Comment by manuelmeurer** [comment]
I just tried it again and it worked. 🤷
