### ISSUE TITLE
chore: Ability to filter contact/id/conversations endpoint

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1963]
At the moment, `contact/id/conversations` returns all conversations associated with the contact

I would like the ability to pass filters to this endpoint  and filter this conversation based on 
conversation status, inbox, labels

**Comment by pranavrajs** [comment]
@sojan-official I guess we add page parameter as well.

**Comment by pranavrajs** [comment]
Closing as the filter API is available now.
