### ISSUE TITLE
chore: Ability to order the conversation api

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1964]
at the moment conversations are ordered by the last active time. 
I would like the api to have different order by options 

example: order by created_at

**Comment by pranavrajs** [comment]
@sojan-official Is it still relevant? Looks like a good candidate for a backend ticket.

**Comment by sojan-official** [comment]
@pranavrajs will spec it out

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/4864
