### ISSUE TITLE
Bug: New icon for sidebar items routes to inbox

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#1965]
the new icon next to label, teams on sidebar leads only to inbox.

**Comment by XuanThuLe** [comment]
G88-Global Game Pỏtal

**Comment by surajput32** [comment]
@nithindavid I can't find where is this 'new' icon. Could you add a screenshot so that it will be more clear?

**Comment by nithindavid** [comment]
@surajput32 The new icon is created dynamically here `app/javascript/dashboard/components/layout/Sidebar.vue:142` by setting `newLink: true` but in the same file there are functions for labels and teams. But when you add `newLink` to `labelSection, teamSection` the new button will be redirecting you only to inbox. 
This is because in `app/javascript/dashboard/components/layout/SidebarItem.vue:111` is using `router link to inbox`, You need to change from hard coded link to the `toStateName` passed via props.

Let me know if you need more help

**Comment by nithindavid** [comment]
![image](https://user-images.githubusercontent.com/1277421/115186974-31a68280-a100-11eb-991a-5b9ccc445f55.png)

**Comment by surajput32** [comment]
@nithindavid Thanks for the details. I got the idea. Assign it to me.
