### ISSUE TITLE
Adjust padding of bubbles to avoid clutter.

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#197]
**Describe the bug**
Spacing between agent and user bubbles seems to be very close, Adjust them to have a good visual breathing space. also the bubble appears odd when text breaks to multiple lines.

**Screenshots**
![image](https://user-images.githubusercontent.com/1277421/67863370-ca7ec200-fb49-11e9-8621-329fc8087b43.png)

**Comment by pranavrajs** [comment]
Closed as it is stale
