### ISSUE TITLE
feat: Ability to send voice message to channel from agent dashboard

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#1973]
I would like to give my agents the ability to sent voice messages to supported channels from the agent dashboard

## Acceptance
- [ ] Interface to record voice messages in chatwoot 
- [ ] attach the message as voice message into conversation
- [ ] Send as voice messages to channels like facebook, whatsapp, telegram, line etc

ref: https://github.com/grishkovelli/vue-audio-recorder

**Comment by KieranHolroyd** [comment]
could be done with this presumably, then just simply upload it to the local chatwoot server https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API.
https://developers.facebook.com/docs/whatsapp/api/messages/media then based on the audio object here, you simply link to the stored file, via http and that's it i think

**Comment by giquieu** [comment]
Hello everyone,
I'm interested in this functionality. I would like to contribute to this.
I would like to leave my opinion about the layout of the vue-audio-recorder component, which does not match the layout of the dashboard, I did some quick tests and it is not possible to change the layout of the component.
By component layout, I mean the way it records audio. He has several functions that he thinks are not useful for this use case. such as audio playback and audio downloading.

@sojan-official  
Do you intend to use this component?

**Comment by sojan-official** [comment]
@giquieu  We don't have a specific preference for the component. It was just a sample reference. If you are interested in contributing feel free to make the choice about the component at your discretion. let us know if you need any help

**Comment by giquieu** [comment]
Nice @sojan-official ,
I thought of using mic-recorder-to-mp3
Ref; https://www.npmjs.com/package/mic-recorder-to-mp3

And use the attachment structure to send the audio.
The audio will be recorded and sent as an attachment type message, what do you think?

**Comment by sojan-official** [comment]
@giquieu Sounds like a plan which we can go ahead with. Chatwoot should identify the file type to be mp3 and render the audio player 👍

**Comment by giquieu** [comment]
Nice, @sojan-official 
Can you assign it to me?

**Comment by pranavrajs** [comment]
@giquieu The package you mentioned seems to be outdated and has not been maintained for a long time. Do you have any other suggestions around the same?

**Comment by giquieu** [comment]
Hello Pranav,
Do not know. I can even look for another one if necessary.
The only arguments I have in favor is the code, which is simple, it just accesses the native MediaRecorder API and finally uses lamejs to convert to MP3.
Anyway, we can implement direct access to the MediaRecorder API, what do you think is better?

**Comment by giquieu** [comment]
> @giquieu The package you mentioned seems to be outdated and has not been maintained for a long time. Do you have any other suggestions around the same?

Hello @pranavrajs ,
Do not know. I can even look for another one if necessary.
The only arguments I have in favor is the code, which is simple, it just accesses the native MediaRecorder API and finally uses lamejs to convert to MP3.
Anyway, we can implement direct access to the MediaRecorder API, what do you think is better?

**Comment by pranavrajs** [comment]
@giquieu I would suggest direct implementation as it would be easier to debug.

**Comment by giquieu** [comment]
Hi, 
As I used the attachment mechanism, I'll wait for the merge from https://github.com/chatwoot/chatwoot/pull/3966. So I can refactor to consider the feature flag.

**Comment by pranavrajs** [comment]
@giquieu Since #3966 is merged, I guess you can move forward with the PR. Let us know if you need any help.

**Comment by giquieu** [comment]
Hello @pranavrajs , I sent a draft, could you check and validate if it is acceptable to send the PR?
[# ](https://github.com/chatwoot/chatwoot/pull/4064)

**Comment by sojan-official** [comment]
@giquieu Thanks for the Draft PR. Let's take it forward over the PR
