### ISSUE TITLE
Widget sets a cookie to track the conversation before the widget has ever been opened

### ISSUE THREAD

**Issue by Jivings** [chatwoot/chatwoot#1976]
**Describe the bug**

When the Chatwoot widget is loaded it sets a cookie `cw_conversation`. It seems like this is uneccessary, and is only ever needed if the vistor interacts with the widget.

**To Reproduce**

Load the chat widget script on a webpage.

**Expected behavior**

The widget should only set a cookie after the visitor opens/interacts with it as that's when the conversation starts.

**Screenshots**

![image](https://user-images.githubusercontent.com/1462828/112114759-61db2e00-8bf3-11eb-8355-a9738e37afa2.png)

**Environment**

Both environments. 

**Additional context**

My company is anti-tracking so don't wish to use any tracking cookies. This cookie is used for tracking and would require us to show a cookie banner.

**Comment by sojan-official** [comment]
@Jivings one of the features we are working on at the moment is the ability to sent proactive messages based on the pages visited.  This lets the agents send a message like "May I help you ?"  to visitors even before they initiate the conversation.  

But we can definitely consider the behaviour: the cookie is set upfront only if proactive messaging is enabled on the account.

**Comment by Jivings** [comment]
Ah yeah it makes sense why you want this cookie then. But it would be great if I had the option to not use that and so not set that cookie 😃

**Comment by pranavrajs** [comment]
@Jivings This cookie is required for identify the user when they returns and is essential for the conversation continuity. Closing this as the change is not something we can implement in a short term.

**Comment by Jivings** [comment]
@pranavrajs Why do you need conversation continuity if the user has never interacted with the chat widget?
