### ISSUE TITLE
Widget footer needs a style cleanup

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#198]
**Describe the bug**
The widget footer looks needs to be changed to a cool one.
- Change button to icon only

**Screenshots**
![image](https://user-images.githubusercontent.com/1277421/67863577-2b0dff00-fb4a-11e9-8676-1cc2bd875f30.png)

**Comment by sojan-official** [comment]
we can take inspiration from how intercoms widget functions

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/commit/7e3409c3e1c62db0627fcc4ea2570df2f13f9824
