### ISSUE TITLE
CI Proposal

### ISSUE THREAD

**Issue by AlexVKO** [chatwoot/chatwoot#1981]
Hey guys,

I'm building a **managed CI** platform specifically for ruby projects.

This is the run of one of your last commits https://ruby.ci/AlexVKO/chatwoot/60217d8/rspec (from a fork) 

I'm asking the biggest open-source Rails projects for support. I'm at a fast pace and adding a lot of new features that really no other CI platform can deliver to the ruby community. (rerun failures, flaky tests detector, no bottled machines, parallel steps, parallel RSpec) 

**There is no configuration needed**, just install the GitHub app and select the build packs for RSpec, Simplecov, and Rubocop, and you should be good to go(it should take 30 s).

https://github.com/marketplace/rubyci

If you guys agree on using it, I'll be giving you 10x speed as an early supporter.

I hope you enjoy the platform, I have a lot of things to do yet, but it is in a state that people are using and the feedback is being great, I deeply appreciate any kind of feedback from you guys as well.

Thanks!

**Comment by AlexVKO** [comment]
I created this video setting up your project if you guys want to take a look!

https://www.youtube.com/watch?v=l1sjzWpU8Rk

**Comment by sojan-official** [comment]
@AlexVKO We will take a look :D

**Comment by AlexVKO** [comment]
Example of a Pull Request: https://github.com/AlexVKO/chatwoot/pull/1

**Comment by sojan-official** [comment]
@AlexVKO  We have enabled running rubyci on our PRs. Will keep you posted on our feedback

**Comment by AlexVKO** [comment]
Awesome, just let me know if you guys need any new features too!
