### ISSUE TITLE
Fails bundle install due to yanked mime magic 0.3.5

### ISSUE THREAD

**Issue by edumansky** [chatwoot/chatwoot#1986]
**Describe the bug**

When running `bundle install` (in my case trying to deploy to Heroku via the deploy button), it fails due to mimemagic 0.3.5 being yanked by the author:

>       Bundler Output: Fetching gem metadata from https://rubygems.org/........
>        Your bundle is locked to mimemagic (0.3.5), but that version could not be found
>        in any of the sources listed in your Gemfile. If you haven't changed sources,
>        that means the author of mimemagic (0.3.5) has removed it. You'll need to update
>        your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
>        in order to install.
>  !
>  !     Failed to install gems via Bundler.
>  !
>  !     Push rejected, failed to compile Ruby app.
>  !     Push failed

**Additional context**

Looks like a major issue impacting all Rails projects

https://github.com/rails/rails/issues/41750

**Comment by pranavrajs** [comment]
@edumansky Yes, we noticed the issue. There was a license change in mimemagic moving it to GPL.

**Comment by edumansky** [comment]
Yeah, that's clearly not ideal for your project. Hopefully Rails team will come up with something workable.

**Comment by jrbrasil** [comment]
OK.
Have a solution to solve this problem? 
Thanks a lot!!

**Comment by sojan-official** [comment]
We have added a new release which should fix this
https://github.com/chatwoot/chatwoot/releases/tag/v1.14.3
