### ISSUE TITLE
Finish creating Cloudron package :)

### ISSUE THREAD

**Issue by jdaviescoates** [chatwoot/chatwoot#1989]
Just a little reminder to @sojan-official that it'd be awesome for there to be a Cloudron package for Chatwoot :)

(re https://forum.cloudron.io/post/8887 ) ;)

Thanks!

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/cloudron-chatwoot

**Comment by gramakri** [comment]
@sojan-official ah, this is great! I will look into this this week. (girish from Cloudron here)
