### ISSUE TITLE
Make search results more navigable

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#1990]
**Is your enhancement request related to a problem? Please describe.**

The search is good to find the first hit but when I want to reply to all users that mentioned XY, it's hard to go through quickly.

**Describe the solution you'd like**

* Keep the search results visible while replying to a conversation. It could be an extra tab next to Mine/Unassigned/All/Search
* Organize Search Results hierarchically by Inbox/Conversation/Message. Selecting the conversation should get me to the end of that conversation while expanding and selecting the message [should get me there](#1979) in the conversation.

**Describe alternatives you've considered**

* When opening the search window, show the last search again
* Have the text selected, so in case I start typing I get to do a new search without having to manually clear the input
* Add option to filter by inbox
* Indicate which Conversation was recently visited by me

**Comment by pranavrajs** [comment]
Closing this in favour of #6021
