### ISSUE TITLE
Error install chatwoot Ubuntu Linux 20.04

### ISSUE THREAD

**Issue by jrbrasil** [chatwoot/chatwoot#1991]
Hi,
Okay?
See the error below when installing chatwoot on ubuntu linux 20.04

Using /usr/share/rvm/gems/ruby-2.7.2
fatal: destination path 'chatwoot' already exists and is not an empty directory.
Already on 'master'
Your branch is up to date with 'origin/master'.
Fetching gem metadata from https://rubygems.org/.......
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of
mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.11s.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
Would you like to configure Webserver and SSL (yes or no): no
Woot! Woot!! Chatwoot server installation is complete
The server will be accessible at http://<server-ip>:3000
To configure a domain and SSL certificate, follow the guide at https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm

I followed the documentation on your website.
https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm

This error occurs when running the command ./setup.sh master

Here is the version of the operating system:

root@server-console-wisechat:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

Can you help me to solve this problem?
With best regards,

**Comment by mohammedfarish** [comment]
We're now facing an issue with the `mimemagic` package. The developers of the package has made changes with their licensing. You can refer to this link, which is exactly what's causing this. https://github.com/chatwoot/chatwoot/issues/1986

**Comment by sojan-official** [comment]
We have added a new release which should fix this
https://github.com/chatwoot/chatwoot/releases/tag/v1.14.3

**Comment by jrbrasil** [comment]
> 
> 
> We have added a new release which should fix this
> https://github.com/chatwoot/chatwoot/releases/tag/v1.14.3

Hi,
The same error occurred.
See below: 


root@server-console-wisechat:~/install/mime-magic-0.3.5/chatwoot-1.14.3/deployment# pwd
/root/install/mime-magic-0.3.5/chatwoot-1.14.3/deployment

root@server-console-wisechat:~/install/mime-magic-0.3.5/chatwoot-1.14.3/deployment# ./setup_20.04.sh master

Using /usr/share/rvm/gems/ruby-2.7.2
fatal: destination path 'chatwoot' already exists and is not an empty directory.
Already on 'master'
Your branch is up to date with 'origin/master'.
Fetching gem metadata from https://rubygems.org/.......
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of
mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 1.15s.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.
Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.

Anything else to be done? 
With best regards,
José Roberto

**Comment by sojan-official** [comment]
@josemiguelo  please try the installation on a fresh VM.
