### ISSUE TITLE
input_select webhook hit doesn't contain value if we do not select the latest one

### ISSUE THREAD

**Issue by aekanshpartani** [chatwoot/chatwoot#1992]
**Describe the bug**

We send user multiple (two in this case) input_select, but when user select first one it gets selected & displayed in panel but webhook hit doesn't contain submitted values.

**To Reproduce**

1. Send two or more input_select, select the first one you sent
2. Check for webhook hits and see if you get submitted values
3. It happens most of the times not 100%

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/36094789/112586223-671dc000-8e21-11eb-9026-cee0375fc94e.png)

![image](https://user-images.githubusercontent.com/36094789/112586296-903e5080-8e21-11eb-9587-161d0b2f0630.png)

**Additional context**

We are using webhook data and storing it, to connect dialogflow chatbot at the end.

**Comment by pranavrajs** [comment]
<img width="308" alt="Screenshot 2022-03-21 at 12 38 10 PM" src="https://user-images.githubusercontent.com/2246121/159217704-e4f675db-1dcf-4413-8b31-e19a9ce541e9.png">


@aekanshpartani Over the last couple of releases, we have made changes around the webhook events, I tested the latest version and it doesn't seem to have the issue. Please feel free to reopen the issue if it is not the case.

cc: @sojan-official
