### ISSUE TITLE
No conversation continuity if customer emails more than once before receiving a reply

### ISSUE THREAD

**Issue by Jivings** [chatwoot/chatwoot#2006]
**Describe the bug**

If a customer emails the support channel more than once before the chatwoot agent has had a chance to reply then it appears in the conversation view as two conversations.

**Expected behavior**

I think that since the conversation is being received from the same email address it should be considered as part of the same conversation

**Screenshots**

![image](https://user-images.githubusercontent.com/1462828/112739115-239f8f00-8fa4-11eb-86b2-3e5017b8eed0.png)

**Environment**

Self hosted via docker on Ubuntu

**Comment by pranavrajs** [comment]
@Jivings This issue got missed somehow, sorry about that. However, the latest updates should fix these issues. Please feel free to reopen if you still have this problem.
