### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by mohammedfarish** [chatwoot/chatwoot#2007]
**Describe the bug**

Trouble getting the service run, after the installation.

**Screenshots**

I've posted my screenshots to the community support server on discord but I haven't got a resolution from there, yet so here's the repost.![image](https://user-images.githubusercontent.com/62788088/112776251-34a5da00-9050-11eb-93ce-54da97f18700.png)

**Server logs**

![image](https://user-images.githubusercontent.com/62788088/112776316-6b7bf000-9050-11eb-9833-bd41ea115cf0.png)

**Environment**

I'm running this service on an Ubuntu 20.04 LTS VPS with a custom test domain. 

**Additional context**

The installation seem to have been successful, compared to the mimemagic yanking issue.

Additionally, I can see that the mobile app has recognised the server address as a working chatwoot server.

**Comment by pranavrajs** [comment]
@mohammedfarish It looks like the assets building is failing. What is the memory size you are using?

**Comment by mohammedfarish** [comment]
it's running on a $5 DO Droplet with 1GB of Memory. What's the reccomended system requirment?

**Comment by sojan-official** [comment]
@mohammedfarish  We usually run our installations on 4GB machines,  you should be able to run on 2 GB as well.  if the compilation fails, try increasing the swap  

ref: https://github.com/chatwoot/chatwoot/issues/1700

**Comment by mohammedfarish** [comment]
As suggested, I went ahead and scaled up my server to a 4GB Memory Instance and reinstalled the whole package and now it works. Thanks for the support guys! Cheers.
