### ISSUE TITLE
Bug: Email overflows in conversation bubble

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2008]
**Expectation** 
- Should overflow and show scrollbar if email is long.

![image](https://user-images.githubusercontent.com/1277421/112807280-56758000-9095-11eb-8fba-b5c098c62bf7.png)

**Comment by ramezrafla** [comment]
This related to issue #2009, we shouldn't show the trail of previous messages in the chat bubble (or in the backend), just the most recent message is relevant

**Comment by nithindavid** [comment]
@ramezrafla this is different from the issue you mentioned. This is for non responsive HTML emails and emails with long links/words.
