### ISSUE TITLE
Permission issue on linux machine

### ISSUE THREAD

**Issue by DiponRoy** [chatwoot/chatwoot#2013]
**Describe the bug**

While running project on Linux machine faceting error as bellow.

> ERROR: for 741580ef719b_backend_webpack_1  Cannot start service webpack: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker/entrypoints/webpack.sh\": permission denied": unknown
> 
> ERROR: for webpack  Cannot start service webpack: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"docker/entrypoints/webpack.sh\": permission denied": unknown
> ERROR: Encountered errors while bringing up the project.

But things are working good with windows machine . On Linux machine doing things as root user. 
Using TAG: 1.14.3

**To Reproduce**
docker-compose build
docker-compose run --rm rails bundle exec rails db:reset

**Comment by sojan-official** [comment]
@DiponRoy  could you specify which Linux distro you are using?

**Comment by DiponRoy** [comment]
@sojan-official  5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by sojan-official** [comment]
Closing this since we haven't heard any other reports about this from the community. 
Seems more of a docker daemon issue than an issue with chatwoot.
