### ISSUE TITLE
Fix: Agent collision not working for all channels

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2015]
- Frontend is only handling typing indicators for webwidget

**Comment by sojan-official** [comment]
@iamsivin  ref: https://github.com/chatwoot/chatwoot/blob/eb80324eaafc9451fd4b2a24cbdefb3ac5c065d8/app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue#L393

we need to remove the condition that limits this to website inbox
