### ISSUE TITLE
url broken  /super_admin/access_tokens "uninitialized constant PlatformAppPermissibleDashboard"

### ISSUE THREAD

**Issue by agustinrudas** [chatwoot/chatwoot#2021]
**Describe the bug**

Hello, Today i noticed.   The "/super_admin/access_tokens" url  is broken.     
This error is not critical, all seems to be working. 
but we can't access to this link.. 

**Running**

Chatwoot Version: v1.14.3
Latest Commit:  [42534e1df423abf62efcae16c2202b3418319d22](https://github.com/chatwoot/chatwoot/commit/42534e1df423abf62efcae16c2202b3418319d22)
Commit Date:   Tue Mar 30 18:16:17 2021 +0530

**To Reproduce**

1. Go to 'https://host/super_admin/access_tokens'
2. See error

**Expected behavior**

Load the window.  .../super_admin/access_tokens url

**Browser logs**
```

 Showing /gems/ruby/2.7.0/gems/administrate-0.14.0/app/views/fields/polymorphic/_index.html.erb where line #21 raised:

uninitialized constant PlatformAppPermissibleDashboard

Trace of template inclusion: #<ActionView::Template app/views/super_admin/application/_collection.html.erb locals=["collection_field_name", "collection_presenter", "page", "resources", "table_title"]>, #<ActionView::Template app/views/super_admin/application/index.html.erb locals=["page", "resources", "search_term", "show_search_bar"]>

Rails.root: /app
```
**Environment**

License: self hosted installation
Type: Docker
Installation type: Docker-Compose

**Additional context**

The only thing i made few days ago was to setup a api key PlatformApp  to create accounts via API.

**Comment by agustinrudas** [comment]
The bug persist. can't check the access tokens url window

**Comment by agustinrudas** [comment]
Hello Awesome Chatwoot Team

The issue persist on the latest commit. 
**commit 090b5f46e803b9afe83386f80c6acf4ae12dc1f9
Merge: bc9db36 10c18aa
Author: Sojan <sojan@pepalo.com>
Date:   Tue May 18 16:05:18 2021 +0530

    Merge branch 'release/1.16.2'**

**ERROR:**

` Showing /gems/ruby/2.7.0/gems/administrate-0.16.0/app/views/fields/polymorphic/_index.html.erb where line #21 raised:

uninitialized constant PlatformAppPermissibleDashboard`

`Trace of template inclusion: #<ActionView::Template app/views/super_admin/application/_collection.html.erb locals=["collection_field_name", "collection_presenter", "page", "resources", "table_title"]>, #<ActionView::Template app/views/super_admin/application/index.html.erb locals=["page", "resources", "search_term", "show_search_bar"]>`

`Rails.root: /app
Application Trace | Framework Trace | Full Trace
app/views/super_admin/application/_collection.html.erb:69
app/views/super_admin/application/_collection.html.erb:63:in `each'
app/views/super_admin/application/_collection.html.erb:63
app/views/super_admin/application/_collection.html.erb:56
app/views/super_admin/application/index.html.erb:56 `

``

**Comment by sojan-official** [comment]
Tested on the latest build and we can't replicate the issue. 
Ensure that your chatwoot server is restarted after the latest changes are pulled in. 

We will reopen this if it still persists.

**Comment by joelr45** [comment]
Hey guys, awesome platform. I am also seeing this persist with the latest:

`ActionView::Template::Error (uninitialized constant PlatformAppPermissibleDashboard):`

Steps to reproduce: Create user with access token.

**Comment by TheIrritainer** [comment]
Hello @sojan-official, I might have found a clue how to reproduce this bug;

apparently you run into this when you delete an account in the super admin. That account deletion does not clean the access_tokens and the platform_app_permissibles

hope it helps

**Comment by sojan-official** [comment]
@TheIrritainer  Thanks a lot for reporting back. Let me try to reproduce this with the mentioned test case. 
We will add a migration to clean up the orphaned records.

**Comment by norbert-they** [comment]
@sojan-official It also happens when you are creating users and accounts via API
