### ISSUE TITLE
Feat: Out of office autoresponder

### ISSUE THREAD

**Issue by azyzio** [chatwoot/chatwoot#2035]
Hi, I just updated chatwoot to the newest version and I can see that the UI for working hours is here :) That is awesome, thanks!!

I noticed that after the feature became available for everyone, it caused some problems such as those in #1827 & #1824 that were fixed in #1842. I notice that there is still a comment to remove the part of the code that I put there, so I think I'm a good person to explain what it was doing (please, don't hesitate to mention me @azyzio if something isn't clear)

https://github.com/chatwoot/chatwoot/blob/develop/app/services/message_templates/hook_execution_service.rb#L8
```ruby
    # TODO: let's see whether this is needed and remove this and related logic if not
    # ::MessageTemplates::Template::OutOfOffice.new(conversation: conversation).perform if should_send_out_of_office_message?
```

The above was responsible for sending automatic out-of-office messages. I can see that currently, the out-of-office message appears in the window before starting the conversation, but nothing really happens when someone does write to us:
![image](https://user-images.githubusercontent.com/1789131/113265775-cfaee600-92d4-11eb-933a-10e8d796f82a.png)
![image](https://user-images.githubusercontent.com/1789131/113265805-d76e8a80-92d4-11eb-9760-44a3e8c0fc3b.png)

The behavior I designed was that the out-of-office message was sent as a response to someone trying to reach out after working hours (something like a chatbot response). I think it makes a lot of sense as some customers might not read the note when starting the conversation. Out-of-office message is there to manage their expectations and send them to some self-service solutions. We can't do it after disabling the feature. Here is the example from Tidio chat app.
![2b057083-d6ba-4c4f-8cde-2cd856400ac2](https://user-images.githubusercontent.com/1789131/113268392-9c218b00-92d7-11eb-8886-ba589fe5a1f7.png)

I am ready to fix all the bugs that were caused by the out-of-office autoresponder. Just please let me know that the described behavior is something you are willing to re-introduce :)

@pranavrajs @sojan-official

**Comment by pranavrajs** [comment]
@azyzio The functionality was disabled as we saw a couple of issues with the timezone and the way auto-responder was being executed. Please give me a couple of days, I will come up with issues and possible fixes for the same. We can work together on this to make this live in 1.16.0. 

Thanks for the work :)

**Comment by sojan-official** [comment]
@azyzio  we weren't able to pick this up for the v1.16.0 release because of conflicting priorities. But we will take this up for v1.17.0 after specing out the impact areas. 

cc: @pranavrajs

**Comment by azyzio** [comment]
I am happy to help out, would you be able to provide some context about what was wrong with it? I can work on the fixes

**Comment by sojan-official** [comment]
@azyzio  Sorry for the delayed response on this. I missed out on this in the sea of notifications 😅

At the time, we deprioritized this because

1) we already had the out-of-office message shown on the widget. So there was a question of whether we needed to show an additional response. 
2) we added a timezone setting for the inbox that wasn't considered in the `out of office autoresponder` template hook.

Case 2 has been addressed with https://github.com/chatwoot/chatwoot/pull/2183.

----

I think there is still value in showing the message for case 1 as you described.  We will enable the template hook as we add business hours to all the available channels. We need to do a fresh round of testing after this.  

At the moment, on my evaluation, the changes should be mostly frontend ones.  I will keep you posted on further updates.

cc: @pranavrajs

**Comment by sojan-official** [comment]
## Acceptance 

- [ ] Ability to configure business hours for all channels [ currently only Web widget is supported ] 
>  - Replicate the UI available for web widget into settings tab for other channels as well
- [ ] Enable the out of office auto-responder for all channels, ref: https://github.com/chatwoot/chatwoot/blob/develop/app/services/message_templates/hook_execution_service.rb#L8
> - For tweets we shouldn't be posting out of office messages.
> - Out of office auto-response text should only be triggered once in a day

## Testing
- [ ] Website Channel 
  - autoresponder messages get sent correctly when a message comes in outside office hours
- [ ] Facebook Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
- [ ] Twitter Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
  - autoresponder messages will not be send for tweet conversations
- [ ] Whatsapp Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
- [ ] SMS Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
- [ ] Email Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
- [ ] API Channel
  - Ability to add office hours
  - Ability to edit office hours
  - autoresponder messages get sent correctly when a message comes in outside office hours
