### ISSUE TITLE
notification email  A new conversation [ID - 9] has been assigned to you - include customer msg & email

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#2041]
**Is your enhancement request related to a problem? Please describe.**
sometimes chatwoot loads very slowly, or now not at all (app.chatwoot.com took too long to respond.)
I can't see the message, can't reply :(

**Describe the solution you'd like**
Please include the conversation history and customer email in this notification email.

Set the email reply-to to customer email

Thanks

**Comment by iammattmartin** [comment]
> Set the email reply-to to customer email

Would need to be optional as that then moves the conversation out of CW and thus continuity.

**Comment by mariusa** [comment]
Ah, good point.

**Comment by pranavrajs** [comment]
### Todo:

- [ ] Include the messages in the email template with the conversation.
- [ ] Change the template content to the following.

```
Hey %{agent_name},

A new conversation (#%{id} - link to conversation) has been created in %{inbox_name}. %{contact_name} wrote:

%{message 1}
%{message 2}
...
%{message n}

```

**Comment by shivamsinghchahar** [comment]
@pranavrajs Can I take this up?

**Comment by pranavrajs** [comment]
Sure, please go ahead.

**Comment by shivamsinghchahar** [comment]
@pranavrajs I have raised a PR (https://github.com/chatwoot/chatwoot/pull/3414). Could you take a look?

**Comment by shivamsinghchahar** [comment]
@pranavrajs I have raised a PR (https://github.com/chatwoot/chatwoot/pull/3414). Could you take a look?
