### ISSUE TITLE
Bug: 'sent from: user' is wrong when agent replies from twitter.com

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2045]
**Estimation** - 

When twitter inbox is connected with chatwoot and if agent replies to a conversation on twitter, the conversation would appear on the chatwoot side. But the messages that appear on the Chatwoot dashboard for the same conversation shows "sent from" incorrectly.

**Comment by pranavrajs** [comment]
### Context

Message sent from Twitter is shown as an incoming message. It should be an outgoing message.

### Todo:

- [ ] We already have a check on the Direct Message Parser service to check if the sender ID is equal to the tweet author id. There might be a change in the payload. Verify whether the message payload is correct and the data types are valid.

https://github.com/chatwoot/chatwoot/blob/6515b6956010de35602c5087e59732c7a25fa69b/app/services/twitter/direct_message_parser_service.rb#L73-L75

- [ ] Check if tweets have the same behavior.

**Comment by pranavrajs** [comment]
Closing as the Twitter Inbox is currently disabled
