### ISSUE TITLE
Empty attachments when sending to agent using API Channel

### ISSUE THREAD

**Issue by mdpdaviadmin** [chatwoot/chatwoot#2049]
**Describe the bug**

I am trying to upload an image file like an attachment in a message sent to an agent. I have used this postman template as a reference: https://www.postman.com/collections/050de41bc0ed46e37663. While executing the POST request in postman send the message with the image attachment successfully, using the same request from python (copy the code from Postman working example) ends in a message with an empty file in the message.

**To Reproduce**

1. Go to Postman and send a message with an image attachment. It finishes ok.
2. Copy the Python code for this request and execute it. the message arrives but with an empty attachment

**Expected behavior**

The correct attachment 

**Environment**

Using self hosted Chatwoot in Heroku

**Comment by pranavrajs** [comment]
@mdpdaviadmin Can you please share the logs or the code you are using? It seems like an issue with your end. I couldn't reproduce the error.
