### ISSUE TITLE
Bug: Alignment issue in activity message

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2055]
Vertically align the timestamp and message. 

![image](https://user-images.githubusercontent.com/1277421/113657201-0a40c600-96bb-11eb-82e8-9b362cd37fed.png)

**Comment by sivin-git** [comment]
Looks fixed in develop branch

<img width="513" alt="Screenshot 2021-04-06 at 12 21 45 PM" src="https://user-images.githubusercontent.com/64252451/113670411-b6da7200-96d2-11eb-8af0-a526b54259cd.png">
