### ISSUE TITLE
[CW-2836] Add the option to check whether the widget is installed or not

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2056]
- Add button "Verify widget installation" near messenger script
- Check the widget is added in any website
- Show toast message "Chatwoot has been installed on your website"

<sub>[CW-2836](https://linear.app/chatwoot/issue/CW-2836/add-the-option-to-check-whether-the-widget-is-installed-or-not)</sub>

**Comment by pranavrajs** [comment]
Closing it here, will be prioritizing this in Linear.
