### ISSUE TITLE
Can't create incoming message through API Channel

### ISSUE THREAD

**Issue by defizor** [chatwoot/chatwoot#2067]
Self hosting, Linux VM

POST to /api/v1/accounts/1/conversations/29/messages for instance returns 200 OK but CONTENT and CONTENT_TYPE stays NULL:

```
{
"content": "string",
"message_type": "incoming",
"private": false,
"content_type": "cards",
"content_attributes": { }
}
```

```
{"id":85,"content":null,"inbox_id":6,"conversation_id":29,"message_type":1,"content_type":null,"content_attributes":{},"created_at":1617862872,"private":false,"source_id":null,"sender":{"id":1,"name":"xxx","available_name":"xxx","avatar_url":"xxx","type":"user","availability_status":"online"}}
```

I do get a new conversation but it stays blank. account id and conversation ID are correct. Any pointers?

Thank you very much!

**Comment by pranavrajs** [comment]
@defizor https://github.com/chatwoot/chatwoot/wiki/Creating-Bot-Messages-Types#card-messages

Please use the exact format for card messages.

**Comment by pranavrajs** [comment]
If it is still not working, please share the logs while you hit the API.

**Comment by defizor** [comment]
@pranavrajs Hello! Thanks for getting back to me so quickly :)

I've tried the exact format for card and all the others, still getting a 200OK response from the api returning:
```
{
  "id": 90,
  "content": null,
  "inbox_id": 6,
  "conversation_id": 29,
  "message_type": 1,
  "content_type": null,
  "content_attributes": {},
  "created_at": 1617901990,
  "private": false,
  "source_id": null,
  "sender": {
    "id": 1,
    "name": "Leo",
    "available_name": "Leo",
    "avatar_url": "https://www.gravatar.com/avatar/2722d8a9a22f5700342ba5bde7256120?d=404",
    "type": "user",
    "availability_status": "online"
  }
}
```
This only happens through API Channel, all other channels work just fine

which log would you like me to share?

**Comment by defizor** [comment]
Something interesting I noticed, I did not set the sender. It was supposed to be an incoming message and the sender shouldn't be "Leo", as he is an agent and only be able to produce outgoing messages.

**Comment by defizor** [comment]
Started fresh and solved the problem, couldn't pin point a reason as to why incoming messages were arriving as outgoing messages. Will check further and update in case I find any real bugs :)
