### ISSUE TITLE
New team is not shown up until user manually refreshes page

### ISSUE THREAD

**Issue by niklashaug** [chatwoot/chatwoot#2068]
**Describe the bug**

When the user creates a new team it is not shown up in the sidebar until he refreshes the page.

**To Reproduce**

1. Go to Settings / Teams
2. Create a new team
3. Go back to Home

**Expected behavior**

After having created a new team the user expects the new team to be shown-up as soon as he leaves the settings page.

**Comment by pranavrajs** [comment]
@niklashaug Nice find! We should have updated the UI state automatically.
