### ISSUE TITLE
User received message from another conversation

### ISSUE THREAD

**Issue by KonstantinReido** [chatwoot/chatwoot#2070]
**Describe the bug**

We faced with a quite strange case. One of our users asked some question, and we answered him, but on the next day in conversation with him appeared message from another user, who told us that this conversation just appears in his browser:
`
Hi! This was mysterious, I have not had this dialogue with you - but it now appeared in chat inside my user. Regards some_user_name
`

Chatwoot 1.13.1. Today, at night will update on the latest version.

**Comment by pranavrajs** [comment]
@KonstantinReido Is there any additional logs or something which can help us in the debugging this?

**Comment by KonstantinReido** [comment]
@pranavrajs 

1) because of our setup on Heroku, I don't have access to logs related to this event
2) user contacted us (in both cases) via a widget on our website (not sure if it a correct answer to your question)

**Comment by sojan-official** [comment]
@KonstantinReido  could you also share whether you use hmac authentication on your chat widget ?

**Comment by KonstantinReido** [comment]
@sojan-official Some time ago I added `identifier_hash` to chatwoot widget, but didn't understand how to restrict requests without this hash, so asked a question https://github.com/chatwoot/docs/issues/8, it still without an answer, so my "hmac authentication" is just an `identifier_hash` in options of the widget.

**Comment by hartois** [comment]
@KonstantinReido 
Perhaps you are facing the problem that I described in https://github.com/chatwoot/chatwoot/issues/1664

**Comment by sojan-official** [comment]
@KonstantinReido  apologises for losing track on that one. let's discuss the questions you have over https://github.com/chatwoot/docs/issues/8 .  I will capture the summary of the discussion as documentation towards the end.

**Comment by pranavrajs** [comment]
Closing this as we pushed a fix in https://github.com/chatwoot/chatwoot/pull/3434 and we will track the doc update in chatwoot/docs#8
