### ISSUE TITLE
Allow adding regex validation on form message type inputs.

### ISSUE THREAD

**Issue by nimitwalia89** [chatwoot/chatwoot#2077]
Currently adding validations is not easy. We basically have to check the users submitted values and send message again with same inputs. It would be easier to developer and better user experience if we allow adding regex for input validations.

**Comment by sojan-official** [comment]
The form text inputs now support the following attributes 

`pattern` : standard html attribute that supports regex 
`pattern_error` : a custom error message for the regex validation
`required` :  whether field is required


example 

```
 { "name": 'email', "placeholder": 'Please enter your email', "type": 'email', "label": 'Email', "required": 'required',          "pattern_error": 'Please fill this field', "pattern": '^[^\s@]+@[^\s@]+\.[^\s@]+$' },
 { "name": 'text_area', "placeholder": 'Please enter text', "type": 'text_area', "label": 'Large Text', "required": 'required',          "pattern_error": 'Please fill this field' },      
 { "name": 'text', "placeholder": 'Please enter text', "type": 'text', "label": 'text', "default": 'defaut value', "required": 'required',          "pattern": '^[a-zA-Z ]*$', "pattern_error": 'Only alphabets are allowed' },      
```
