### ISSUE TITLE
When sending images, Private Note is indistinguishable from Message

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#2095]
As the visual clue to distinguish a sent message from a Private Note is the background color and shared images are used to fill the background, hiding the background color, I now don't know if a shared screenshot is visible to the visitor or not.

**To Reproduce**, send an image as a Private Note

**Expected behavior**: The image gets maybe some margin in the "Private Note" background color.

**Screenshot**:

![Screenshot from 2021-04-13 16-24-27](https://user-images.githubusercontent.com/96378/114616405-d3e3e780-9c74-11eb-96d3-8603fe63a68e.png)

**Comment by pranavrajs** [comment]
@Giszmo It looks like you are on an older version of Chatwoot. Could you please upgrade to the latest and try this again?

**Comment by Giszmo** [comment]
Issue is fixed in latest version. thanks.
