### ISSUE TITLE
Duplicate conversations on live chat

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#2098]
**Describe the bug**

Sometimes there a live chat conversation starts showing as a new one. 
This happened twice, I'm not sure if it's a known/unavoidable issue (eg client openeded another browser)

**To Reproduce**

Can't reproduce, but here they are, on the hosted version:
https://app.chatwoot.com/app/accounts/3889/conversations/17
https://app.chatwoot.com/app/accounts/3889/conversations/18

**Expected behavior**

Would it be possible to avoid duplicates?

**Screenshots**

![2021-04-14_13-53](https://user-images.githubusercontent.com/1283842/114699785-65ad2c80-9d29-11eb-85c5-bd1119d031ee.png)

Thanks!

**Comment by sojan-official** [comment]
Both the conversations were created by the same contact in different browser sessions.

If you want the contact to have a continuous conversation history, you can look at adding identity validation
https://www.chatwoot.com/docs/website-sdk#identity-validation

**Comment by mariusa** [comment]
Thanks for checking
