### ISSUE TITLE
Display indicator if message was read by customer

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#2099]
**Is your enhancement request related to a problem? Please describe.**
After replying to a customer (usually on live chat widget channel), it's not clear if the customer saw the message or not. I'm asking myself if I should send an email too.
The only related indicator now is the green "online" badge on the customer icon, in the conversations list view.

**Describe the solution you'd like**
Please consider a solution similar to WhatsApp, showing an indicator on sent messages / received by client / read by client.
Where possible, this should work multi-channel, eg Live chat / WhatsApp / email via 1px img embed (if enabled)

**Comment by pranavrajs** [comment]
@mariusa This is a nice suggestion, it would be a good option to consider along with delivery status.

**Comment by WevrLabs** [comment]
May also leverage Twilio's API on this matter, regarding WhatsApp messages:

https://www.twilio.com/docs/sms/api/message-resource#message-status-values

![Screen Shot 2021-05-04 at 12 04 27 AM](https://user-images.githubusercontent.com/66124192/116939337-74be3500-ac6c-11eb-941f-01629884ca61.png)
