### ISSUE TITLE
Bug: Switch to normal editor for twitter and others without MD support

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2100]
The RichText edit toggle button is hidden but UI is still showing rich text editor for inboxes like twitter.
![image](https://user-images.githubusercontent.com/1277421/114742453-62399580-9d69-11eb-8be1-f516fa75a638.png)

**Comment by pranavrajs** [comment]
@nithindavid Please tag the issue with the right labels / severity / project.

**Comment by nithindavid** [comment]
Closing this issue as it's fixed.
