### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [chatwoot/chatwoot#2106]
#### ⚠️ Potential Vulnerability in chatwoot

👋 Hello, @pranavrajs, @sojan-official, @nithindavid - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/1-other-chatwoot and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/2112
