### ISSUE TITLE
Bug: Incorrect avatar icon for twilio sms inbox

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2109]
<img width="466" alt="Screenshot 2021-04-16 at 4 52 33 PM" src="https://user-images.githubusercontent.com/73185/115017456-338bfe00-9ed4-11eb-97f1-c5791bf01800.png">

The Twilio SMS inbox shows WhatsApp icons on avatars

**Comment by Hassanelashram** [comment]
@sojan-official @pranavrajs Hey, looks like something I could look at to get started , can I ?

**Comment by pranavrajs** [comment]
@Hassanelashram Sure, please feel to work on it.

**Comment by Hassanelashram** [comment]
@pranavrajs I am unable to start the app unfortunately as I keep getting 
```
pg_isready -h localhost -p 5432 -U admin
localhost:5432 - no response 
```

over and over

**Comment by Hassanelashram** [comment]
@pranavrajs I cannot get the app running unfortunately as the pg_isready never seems to be true.

(I have no DATABASE_URL variable)

**Comment by stoneWeaver** [comment]
> @pranavrajs I cannot get the app running unfortunately as the pg_isready never seems to be true.
> I keep getting `localhost:5432 - no response`
> (I have no DATABASE_URL variable)
May I ask how you solve this problem

**Comment by pranavrajs** [comment]
@Hassanelashram Could you please share the document which you are following to set up the dev env?

**Comment by Hassanelashram** [comment]
@pranavrajs I am following this [documentation](https://www.chatwoot.com/docs/environment-variables)
I think my issue is with the postgres_url

**Comment by sojan-official** [comment]
@Hassanelashram  were you able to set up the repo?

**Comment by Hassanelashram** [comment]
@sojan-official I was not unfortunately

**Comment by sojan-official** [comment]
@Hassanelashram  if you are still interested in working over the issue. let me try to help you with the set-up. 
could you try the set-up using the documents listed over here based on which operating system you are using?

https://www.chatwoot.com/docs/contributing-guide/environment-setup/mac-os
https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker ( docker )
