### ISSUE TITLE
chatwoot and  sidekiq containers are not working 

### ISSUE THREAD

**Issue by Aicha-cher** [chatwoot/chatwoot#2110]
**Describe the bug**
Hi to all, 
Both containers  sidekiq and chatwoot stop after few minutes, i suspected my email setting  so a commented those entries on the env file, but still the same problem 
* chatwoot doesnt display any log 
* here is the log of  sidekiq:

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'

/usr/local/bundle/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'

/usr/local/bundle/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'

/usr/local/bundle/bin/bundle:23:in `load'

/usr/local/bundle/bin/bundle:23:in `<main>'

**Environment**

selfhosted using docker

**Comment by sojan-official** [comment]
@Aicha-cher  can you provide the full error logs?

**Comment by Aicha-cher** [comment]
@sojan-official  here is the full log 

`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.

I, [2021-04-17T13:00:30.059197 #1]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified

2021-04-17T13:00:30.060Z pid=1 tid=4ed INFO: Booting Sidekiq 6.1.1 with redis options {:url=>"redis://redis:6379", :password=>"REDACTED", :size=>25}

2021-04-17T13:00:30.061Z pid=1 tid=4ed WARN: Redis::CommandError: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

2021-04-17T13:00:30.062Z pid=1 tid=4ed WARN: /gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:127:in `call'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:108:in `block in connect'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:308:in `with_reconnect'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:106:in `connect'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:381:in `ensure_connected'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:233:in `block in process'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:320:in `logging'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:232:in `process'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis/client.rb:126:in `call'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:2192:in `block in hget'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:69:in `block in synchronize'

/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'

/usr/local/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:69:in `synchronize'

/gems/ruby/2.7.0/gems/redis-4.2.1/lib/redis.rb:2191:in `hget'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:361:in `block in status_from_redis'

/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq.rb:98:in `block in redis'

/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:63:in `block (2 levels) in with'

/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `handle_interrupt'

/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:62:in `block in with'

/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `handle_interrupt'

/gems/ruby/2.7.0/gems/connection_pool-2.2.3/lib/connection_pool.rb:59:in `with'

/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq.rb:95:in `redis'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:360:in `status_from_redis'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:272:in `initialize'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `new'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:187:in `block in load_from_array'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `each'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:186:in `load_from_array'

/gems/ruby/2.7.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:157:in `load_from_hash'

/app/config/initializers/sidekiq.rb:12:in `<main>'

/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'

/gems/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:318:in `block in load'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:318:in `load'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/engine.rb:666:in `block in load_config_initializer'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/notifications.rb:182:in `instrument'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/engine.rb:665:in `load_config_initializer'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/engine.rb:625:in `block (2 levels) in <class:Engine>'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/engine.rb:624:in `each'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/engine.rb:624:in `block in <class:Engine>'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:32:in `instance_exec'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:32:in `run'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:61:in `block in run_initializers'

/usr/local/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'

/usr/local/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'

/usr/local/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'

/usr/local/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'

/usr/local/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:50:in `each'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:50:in `tsort_each_child'

/usr/local/lib/ruby/2.7.0/tsort.rb:415:in `call'

/usr/local/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'

/usr/local/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'

/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each'

/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `call'

/usr/local/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'

/usr/local/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'

/usr/local/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/initializable.rb:60:in `run_initializers'

/gems/ruby/2.7.0/gems/railties-6.0.3.5/lib/rails/application.rb:363:in `initialize!'

/app/config/environment.rb:5:in `<top (required)>'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `block in require'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:291:in `load_dependency'

/gems/ruby/2.7.0/gems/activesupport-6.0.3.5/lib/active_support/dependencies.rb:324:in `require'

/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:252:in `boot_application'

/gems/ruby/2.7.0/gems/sidekiq-6.1.1/lib/sidekiq/cli.rb:37:in `run'

/gems/ruby/2.7.0/gems/sidekiq-6.1.1/bin/sidekiq:31:in `<top (required)>'

/gems/ruby/2.7.0/bin/sidekiq:23:in `load'

/gems/ruby/2.7.0/bin/sidekiq:23:in `<top (required)>'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `load'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:63:in `kernel_load'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli/exec.rb:28:in `run'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:494:in `exec'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:30:in `dispatch'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/cli.rb:24:in `start'

/usr/local/bundle/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'

/usr/local/bundle/gems/bundler-2.2.15/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'

/usr/local/bundle/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'

/usr/local/bundle/bin/bundle:23:in `load'

/usr/local/bundle/bin/bundle:23:in `<main>'

**Thanks**

**Comment by jcsa1986** [comment]
I have the exact same issue... Did you solved?

The sidekiq container fails to start with the same errors in the log as your post, and the chatwoot base only says: "Switch to inspect mode".

I manage to get the sidekiq working by not setting a password in the REDIS_PASSWORD environment variable, but the base won't work no matter what I did.

I read somewhere that "Dropping bundle exec, and calling the Ruby script directly fixs the issue. Run: rails server -b 0.0.0.0.", but I have no idea where or how should I run that command.

Thank you.

**Comment by sojan-official** [comment]
@jcsa1986  @Aicha-cher  are you guys following this doc to run chatwoot ? 

https://www.chatwoot.com/docs/self-hosted/deployment/docker

**Comment by jcsa1986** [comment]
Hit here.

Yes. I am... After running docker-compose up -d both containers (sidekiq and base) start and immediately stop.

Regards.

**Comment by sojan-official** [comment]
@jcsa1986 @Aicha-cher  I have added fixes for this issue. let us know if you face any difficulties
You will need to set up redis and postgres passwords in .env and postgres password in docker-compose.yml
