### ISSUE TITLE
Unable to add emoji exactly where the cursor is at

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2116]
**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the agent reply box
2. Type "Hi welcome" message
3. Move the cursor position to Hi
4. Select emoji
5. Emojie append to end of the message

**Expected behaviour**

- User should be able to add emoji exactly where the cursor is at

**Screenshot**

![Screenshot 2021-04-17 at 11 58 25 AM](https://user-images.githubusercontent.com/12408980/115104155-72897600-9f0b-11eb-8d01-c65e2eb122d6.png)

**Comment by andresyebra** [comment]
Hi,
I've fixed this issue for "Reply Section" using a textarea element: 
![image](https://user-images.githubusercontent.com/10139341/115982311-b578c880-a55f-11eb-99ed-2b65f5ac2795.png)
