### ISSUE TITLE
Rails Migrations fail during initial setup. 

### ISSUE THREAD

**Issue by e-karma** [chatwoot/chatwoot#2117]
**Describe the bug**

Migrations fail during initial setup.. 

undefined local variable or method `locked' for #<InstallationConfig:0x00007fa6e4365140>
Did you mean?  lock!

**Screenshots**
![Screen Shot 2021-04-18 at 9 42 27 PM](https://user-images.githubusercontent.com/6776633/115170749-67f7e980-a08f-11eb-9f0d-be02c9e8130a.png)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

MacBooks-MacBook-Pro:chatwoot macbookpro$ rails db:migrate RAILS_ENV=development
== 20200510112339 CreateInstallationConfig: migrating =========================
-- create_table(:installation_configs)
   -> 0.0547s
-- add_index(:installation_configs, [:name, :created_at], {:unique=>true})
   -> 0.0071s
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `locked' for #<InstallationConfig:0x00007fc7212e2300>
Did you mean?  lock!
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/macbookpro/repos/native/chatwoot/app/models/installation_config.rb:39:in `set_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:604:in `catch'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:201:in `block in halting'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/validations.rb:337:in `valid?'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:68:in `valid?'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:84:in `perform_validations'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:47:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `block in save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/suppressor.rb:44:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/persistence.rb:38:in `create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:100:in `block in create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `block in scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:784:in `_scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:100:in `create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:169:in `find_or_create_by'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/querying.rb:21:in `find_or_create_by'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:62:in `save_as_new_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:52:in `save_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:43:in `block in reconcile_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:40:in `each'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:40:in `reconcile_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:23:in `process'
/Users/macbookpro/repos/native/chatwoot/db/migrate/20200510112339_create_installation_config.rb:11:in `change'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:828:in `exec_migration'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:811:in `block in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:810:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1002:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1361:in `ddl_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1280:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1229:in `block in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1229:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1061:in `up'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1036:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:84:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/command.rb:48:in `invoke'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'

Caused by:
NameError: undefined local variable or method `locked' for #<InstallationConfig:0x00007fc7212e2300>
Did you mean?  lock!
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/attribute_methods.rb:432:in `method_missing'
/Users/macbookpro/repos/native/chatwoot/app/models/installation_config.rb:39:in `set_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:428:in `block in make_lambda'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:605:in `block (2 levels) in default_terminator'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:604:in `catch'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:604:in `block in default_terminator'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:201:in `block in halting'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:513:in `invoke_before'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:134:in `run_callbacks'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/callbacks.rb:825:in `_run_validation_callbacks'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activemodel-6.0.3.6/lib/active_model/validations.rb:337:in `valid?'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:68:in `valid?'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:84:in `perform_validations'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/validations.rb:47:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `block in save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:314:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/suppressor.rb:44:in `save'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/persistence.rb:38:in `create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:100:in `block in create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `block in scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:784:in `_scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:407:in `scoping'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:100:in `create'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/relation.rb:169:in `find_or_create_by'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/querying.rb:21:in `find_or_create_by'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:62:in `save_as_new_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:52:in `save_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:43:in `block in reconcile_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:40:in `each'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:40:in `reconcile_general_config'
/Users/macbookpro/repos/native/chatwoot/lib/config_loader.rb:23:in `process'
/Users/macbookpro/repos/native/chatwoot/db/migrate/20200510112339_create_installation_config.rb:11:in `change'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:828:in `exec_migration'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:811:in `block in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:810:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1002:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1310:in `block in execute_migration_in_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1361:in `block in ddl_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/transactions.rb:212:in `transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1361:in `ddl_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1309:in `execute_migration_in_transaction'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1281:in `block in migrate_without_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1280:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1280:in `migrate_without_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1229:in `block in migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1382:in `with_advisory_lock'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1229:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1061:in `up'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/migration.rb:1036:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:84:in `each'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activerecord-6.0.3.6/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/command.rb:48:in `invoke'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/railties-6.0.3.6/lib/rails/commands.rb:18:in `<main>'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/macbookpro/.rvm/gems/ruby-2.7.2/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Environment**

Self Hosted, non-docker

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sojan-official** [comment]
please use `rake db:chatwoot_prepare` when you are setting up
