### ISSUE TITLE
Bug: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by iamsivin** [chatwoot/chatwoot#2124]
Steps to reproduce:

1. Go to conversation.
2. Click on contact details.
3. Scroll down to the assigned team and click none .
4. See the error on console.

**Screenshots**

<img width="927" alt="Screenshot 2021-04-19 at 11 43 45 AM" src="https://user-images.githubusercontent.com/64252451/115189987-fd819080-a104-11eb-9d71-c8dbd3802aa9.png">

**Comment by niklashaug** [comment]
Hey, can I submit a PR that fixes this issue?

**Comment by muhsin-k** [comment]
@niklashaug Please feel free to go ahead
