### ISSUE TITLE
Why support all languages for other countries even China's Taiwan but China ! ! !

### ISSUE THREAD

**Issue by jyjin** [chatwoot/chatwoot#2125]
We found it support all languages but China? Chatwoot is a very shocking IM communication software. We wanted to pursue cooperation, but this process is really disappointing.
<img width="647" alt="china" src="https://user-images.githubusercontent.com/8912548/115203305-e6a16500-a129-11eb-8051-77e4a09b2456.png">

**Comment by pranavrajs** [comment]
@jyjin Thanks for pointing this out. We would enable this in the next release? I believe the translations might not be complete in the last release. 

Anyway we will be releasing an intermediate version v1.15.1 which would enable this. 

Meanwhile, could you please contribute to the rest of the translations here. https://chatwoot.crowdin.com/chatwoot/zh-CN

**Comment by pranavrajs** [comment]
Closed via #2135
