### ISSUE TITLE
seed fail(unknown attribute 'inbox' for Contact)

### ISSUE THREAD

**Issue by RonWalker22** [chatwoot/chatwoot#213]
**Describe the bug**

seeding the database fails with `UnknownAttributeError: unknown attribute 'inbox' for Contact`

perhaps there were changes to the Contact model and someone forgot to update the seed file.

**To Reproduce**

seed the database on a fresh install

**Expected behavior**
no error

**Comment by sojan-official** [comment]
fixed in #214
