### ISSUE TITLE
Bug: Cant display Bot assigned conversations - just loading spinner

### ISSUE THREAD

**Issue by entttom** [chatwoot/chatwoot#2138]
**Describe the bug**

**To Reproduce**

1. Open a channel
2. Switch opened to bot assigned conversations
3. Wait for loading of the bot assigned conversations 
4. No messages appear - just infinite loading circle and error message in browser log ( see below)

Loaded Bot assigned conversations

GET Request seems not to work: 
Request URL: https://work.url/api/v1/accounts/1/conversations?status=Bot&assignee_type=all&page=1
Request Method: GET
Status Code: 500 Internal Server Error

Every other GET reueust to status=open and status=resolved is working like a charm.

![Bildschirmaufnahme 2021-04-20 um 20 59 43](https://user-images.githubusercontent.com/16444099/115449925-95719e00-a21b-11eb-848c-00433e8362f9.gif)

**Comment by pranavrajs** [comment]
@entttom Can you please share the server error logs you get when you call the API?

**Comment by pranavrajs** [comment]
Please share the self-hosted Chatwoot version number as well.

**Comment by entttom** [comment]
> Please share the self-hosted Chatwoot version number as well.
Its 1.15.1

Found the bug it only appears in the german (de) version.

how to fix it -> app/javascript/dashboard/i18n/locale/de/chatlist.json

change   
```
    {
        "TEXT": "Bot",
        "VALUE": Bot"
      }
```
to

```
      {
        "TEXT": "Bot",
        "VALUE": "bot"
      }
```

after this change the correct GET request is made:
/api/v1/accounts/1/conversations?status=**b**ot&assignee_type=me&page=1 instead of 
api/v1/accounts/1/conversations?status=**B**ot&assignee_type=me&page=1

**Comment by pranavrajs** [comment]
@entttom Thanks for reporting this. I think the key is getting translated along with the text. 

@chatwoot/engineering It might be good to add a check here on the status to make sure that valid keys only will be used in the queries, otherwise, let us default to open.

**Comment by GrygorievEvgeniy** [comment]
In russian locale the same problem, but cant fix it beacause havent    
 {
        "TEXT": "Bot",
        "VALUE": Bot"
      }

**Comment by sojan-official** [comment]
This should be fixed in the latest release as we switched to a different approach 
https://github.com/chatwoot/chatwoot/commit/f68a4b55bb5748ea90f1c4dc552f2f390aa70a46
