### ISSUE TITLE
chore: Assign outbound conversation to the agent who initiated the conversation

### ISSUE THREAD

**Issue by bensont1** [chatwoot/chatwoot#2147]
**Describe the bug**

When sending out emails from an email inbox, the "From" line on the receiving end shows it is from "Notification from Support" where "Support" is the name of the inbox on chatwoot.

To clarify, this issue only occurs when an Agent initiates the conversation from the contacts page.

**To Reproduce**

1. Go to Contacts, select contact, select New Conversation 
2. Select an email inbox
3. Send email
4. Receiver replies to email
5. Agent responds to email
6. Receiver will receive an email with "From" line of "Notification from Support"

**Expected behavior**

The expected "From" line should show "First Last from Support" where First Last is the name of the Agent.

**Environment**

Self hosted Heroku

**Comment by pranavrajs** [comment]
@bensont1 Thanks for reporting the issue. 

@sojan-official I guess we need to auto-assign the conversation to the agent who has created it. Thoughts?

**Comment by sojan-official** [comment]
@pranavrajs sounds like a good idea.

**Comment by sojan-official** [comment]
will be covered as a part of https://github.com/chatwoot/chatwoot/issues/2306
