### ISSUE TITLE
Add inbox info to previous conversations

### ISSUE THREAD

**Issue by hexclann** [chatwoot/chatwoot#2166]
Lets say I have several inbox, website live chat and e-mail support. If some customer contacts me on different channels, I can see the previous conversations from that customer in `Contacts` >> `View details` but it does not show which conversation is from which inbox. 

![chrome_7uKM0UZ1sD](https://user-images.githubusercontent.com/59732888/116227244-8df94a00-a771-11eb-809f-7522df0900be.png)

Is it possible to add a tag like this: (to show which conversation belong to which channel)
![chrome_CP8ekXkoFY](https://user-images.githubusercontent.com/59732888/116227366-aff2cc80-a771-11eb-9d39-1956835b4c87.png)

**Comment by sojan-official** [comment]
we could also have the avatar indicators.
<img width="360" alt="Screenshot 2021-04-27 at 4 41 07 PM" src="https://user-images.githubusercontent.com/73185/116232176-61483100-a777-11eb-9af3-d75c20ac0ece.png">
