### ISSUE TITLE
Seeds fail due to invalid phone number format

### ISSUE THREAD

**Issue by mjarmula** [chatwoot/chatwoot#2169]
**Describe the bug**

While seeting up the project on my local env,  I got an error while running seeds because of an invalid phone number format

**To Reproduce**
run `bundle exec rails db:reset`

**Screenshots**
![validation_failed](https://user-images.githubusercontent.com/46462548/116281094-a37a6e00-a789-11eb-897e-27245cc2075e.png)

**Environment**
Local env, Linux 20.04

**Additional context**

May I submit PR with the fix :)?

**Comment by sojan-official** [comment]
@mjarmula  I have added a fix for this in https://github.com/chatwoot/chatwoot/pull/2167 . 
Thanks for reporting.
