### ISSUE TITLE
readableTime overlapping message text [firefox]

### ISSUE THREAD

**Issue by RonWalker22** [chatwoot/chatwoot#218]
**Describe the bug**
Within Firefox the time is overlapping with message text when newlines are used for both standard reply and private note.
**To Reproduce**
1. create a message, within a conversation, with newlines in Firefox. 

**Expected behavior**
Just like in chrome, the time should not be overlapping message text. 

**Screenshots**

#### Firefox before fix(Overlapping bug)
![Firefox before fix](https://user-images.githubusercontent.com/18250094/69025826-6a778080-097d-11ea-9829-2399909724b0.png)

#### Chrome before fix(No bug)
![Chrome before fix](https://user-images.githubusercontent.com/18250094/69025827-6a778080-097d-11ea-881d-244b3ed66b22.png)

#### Chrome after fix(No bug)
![Chrome after fix](https://user-images.githubusercontent.com/18250094/69025828-6b101700-097d-11ea-8aa5-ed29f3952754.png)

#### Firefox before fix(No bug)
![Firefox before fix](https://user-images.githubusercontent.com/18250094/69025829-6b101700-097d-11ea-9300-9286c8892900.png)

**Desktop (please complete the following information):**
 - OS: [MacOs Catalina 10.15.1]
 - Browser [Firefox]
 - Version [lastest firefox version ]

**Comment by pranavrajs** [comment]
Fixed via #219
