### ISSUE TITLE
Out of office message is not working properly even after setting business hours and setting timezone

### ISSUE THREAD

**Issue by vishal-pandey** [chatwoot/chatwoot#2182]
**Describe the bug**

Out of office message is not working properly even after setting business hours and setting timezone

**To Reproduce**

Steps to reproduce the behaviour:
1. Create website inbox
2. Set business hours
3. Start conversation in web widget
4. Out of office message is not sent even when outside outside business hours.

**Comment by vishal-pandey** [comment]
https://github.com/chatwoot/chatwoot/blob/b89cc9cf5722611a2090bdea03b969c9e65f62d5/app/services/message_templates/hook_execution_service.rb#L8

Have to un comment this line to test it.

**Comment by sojan-official** [comment]
ref : https://github.com/chatwoot/chatwoot/issues/2035

**Comment by sojan-official** [comment]
closing in favor of  #2035

**Comment by XuanThuLe** [comment]
Ok

**Comment by XuanThuLe** [comment]
Ok
