### ISSUE TITLE
Platform login query param does not support + in email

### ISSUE THREAD

**Issue by bensont1** [chatwoot/chatwoot#2186]
**Describe the bug**

Following the steps here (https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Platform-APIs) for building a custom login using an existing user database.

Requesting a login URL from GET /platform/api/v1/users/{user_id}/login and using the returned URL will result in a 401 with error  "Invalid login credentials" when there is a `+` within the email, for example `account+test1@test.com`.
 
The constructed return URL looks something like this:
```
https://chatwoot_installation.com/app/login?email=account+test1@test.com
```

**To Reproduce**

1. Follow steps in the wiki
2. Create a user using an email with `+`
3. Perform Platform/User/Login
4. Error occurs, unable to login

**Expected behavior**

Should be able to login

**Environment**

Self hosted Heroku

**Comment by bensont1** [comment]
Revising this issue, redirect email query param in the URL login does not support `+` alias emails i.e `account+test1@test.com`

**Comment by sojan-official** [comment]
@bensont1  we might need to do a URL encode over the emails before constructing the URL. let me investigate and get back.
