### ISSUE TITLE
New reply box loses focus

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2200]
Since the most recent change (addition of the "Enter to send" checkbox), when you enter a reply with that selected and press enter, on sending, the focus on the input is lost so you have to manually click within that to send another message.

This behaviour has changed as it always used to retain focus on that input.

v1.15.1

**Comment by pranavrajs** [comment]
@iammattmartin Thanks for reporting this. This is a confirmed bug.
