### ISSUE TITLE
Define a limit for maximum message characters for WhatsApp channel

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#2206]
**Is your enhancement request related to a problem? Please describe.**
Recently, I discovered that a message nearly 1700 characters  failed to be delivered via WhatsApp channed, I doubled checked by resending it, but it wasn't delivered, I went and checked twilio logs, but it wasn't there either, so my guess was that Twilio does not receive messages that exceed a certain limit.

**Describe the solution you'd like**
A good starting point would be to limit the number of characters that can be input in the reply box.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by pranavrajs** [comment]
@WevrLabs We have a limit defined on the message as per the doc here. https://www.chatwoot.com/docs/product/channels/supported-features#maximum-message-size-number-of-characters

I believe this was written by taking the standard Whatsapp API into consideration. 

Are you suggesting that 10k character limit is not the right one?

**Comment by WevrLabs** [comment]
@pranavrajs very much indeed. I believe it is somewhere around 1600 characters, because also the other day, I recall facing
 a similar issue but this time "receiving" a message that exceeds this limit. This was the alert received from Twilio:

![Screen Shot 2021-05-04 at 11 25 21 AM](https://user-images.githubusercontent.com/66124192/116984840-fabd9880-accb-11eb-9416-ff9e3281bead.png)

**Comment by pranavrajs** [comment]
https://support.twilio.com/hc/en-us/articles/360033806753-Maximum-Message-Length-with-Twilio-Programmable-Messaging

This sounds like the case. Let me change the value to it then.
