### ISSUE TITLE
Error SMTP

### ISSUE THREAD

**Issue by poggioni-dot** [chatwoot/chatwoot#2207]
Hello guys, I configured or smtp as in the tutorial using sendgrid, I saw here on git how to create a superadmin and on sidekiq I'm getting this error when sending email. can someone help me?

Devise::Mailer#reset_password_instructions

 {"_aj_globalid"=>"gid://chatwoot/User/4"}, "_DWBuUXy18dioxzKfTyx", {"client_config"=>"default", "_aj_symbol_keys"=>["client_config"]}
 
  | OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain)

**Comment by pranavrajs** [comment]
@poggioni-dot Could you please share a little bit more detail on the logs. Can you also please share the environment variables you are using?

**Comment by poggioni-dot** [comment]
SMTP_ADDRESS=smtp.sendgrid.net
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_PORT=587
SMTP_USERNAME=apikey
SMTP_PASSWORD= KEY API GENERATED ON SENDGRID

how do I access the log to send you?

**Comment by poggioni-dot** [comment]
Would there be any way to approve the agent through the super admin panel or via the ruby ​​console? I installed the system on the digital ocean and for some reason I can't access via ssh, only directly through the digital ocean panel

**Comment by aydenbottos** [comment]
What process did you use to generate your SSL certificate? Without looking at it too much, that error probably means you generated a self-signed certificate using the OpenSSL client. Instead, you need to use a signed certificate like a Let's Encrypt one.

**Comment by pranavrajs** [comment]
@vishnu-narayanan @tejaswinichile Can you please take a look at this?

**Comment by aydenbottos** [comment]
Necroposting much?

**Comment by Startouf** [comment]
I am running my mail server on an instance of mine and I need to use self signed certificate.

On regular rails applications, it's enough to add

```
config.action_mailer.smtp_settings = {
    ca_file: '/etc/ssl/certs/ca-certificates.crt',
  }
```

And to add the mailer certificate in there, but it seems like adding this to config/environments/production.rb isn't enough :/
