### ISSUE TITLE
allow access to uploaded images only to authenticated users 

### ISSUE THREAD

**Issue by ahmadhaidarahmad** [chatwoot/chatwoot#2228]
I need to allow access to uploaded images only to authenticated user and an admin during a conversation to make sure that only the admin and the customer are the only users who are allowed to see the images on the web to make it private and secure
Regards

**Comment by iammattmartin** [comment]
Might create a problem for email updates with images....

**Comment by pranavrajs** [comment]
@ahmadhaidarahmad The images have a short-lived expiry token attached to them. This makes sure that the images are not publicly available to everyone every time.

Closing this as there is no further action expected here.
