### ISSUE TITLE
Health-check / status endpoint

### ISSUE THREAD

**Issue by jbg** [chatwoot/chatwoot#2238]
**Is your feature request related to a problem? Please describe.**

When deploying behind a load balancer or other frontend, a relatively cheap health-check is desirable that indicates that the application is ready to receive requests but doesn't do heavy things like template rendering.

**Describe the solution you'd like**

An endpoint that simply returns 200 OK if Chatwoot is healthy and ready to receive requests.

Ideally the health check would also take into account PG/Redis/etc connectivity, but it ideally would not couple the rate of that check to the rate that the health check endpoint is called at, because in some cloud environments the health check endpoint can be called at quite a high rate.

If it's practical, checking the health of db/redis/etc every N seconds and storing a health status, and then returning that stored health status from the health check endpoint, would be ideal. Alternatively some short-term caching mechanism could be used on the health check endpoint's response.

**Describe alternatives you've considered**

I've searched the repository and documentation to see if there is an existing health endpoint but could not find one. At present I'm simply using `/`, but the template rendering, request processing, etc, is quite heavy so the health checks cause considerable load.

**Comment by pranavrajs** [comment]
@jbg We use an endpoint `GET <installation-url>/api` to get the details of the version of the instance. I guess you can use that for now.

```
GET /api 

Response:

{
  "version":"1.15.1",
  "timestamp":"2021-05-07 05:58:17"
}
```

**Comment by jbg** [comment]
That's fine, but this seems to return 200 OK no matter whether Chatwoot is working correctly or not. For example, if I block the database or redis connectivity, even after some time, I still get 200 OK from this endpoint.

**Comment by sojan-official** [comment]
would be worthwhile to implement a way to health check out sidekiq workers as well 

ref: https://github.com/mperham/sidekiq/wiki/Monitoring#sidekiqmon
ref: https://github.com/arturictus/sidekiq_alive

**Comment by pranavrajs** [comment]
Closing this here as the `/api` endpoint currently takes Redis and Postgres statuses as well.
