### ISSUE TITLE
Rasa and Twilio simultaneous integration

### ISSUE THREAD

**Issue by thundersparkf** [chatwoot/chatwoot#2242]
From the documentation, I have been able to setup a Twilio WhatsApp inbox.

 However, our use case requires us to integrate an NLP bot(preferably open source) to handle conversations over WhatsApp. Rasa allows integration through a built in Twilio connector.

 If one were to bridge the both and have an architecture that allows users to send messages over WhatsApp, which are first handled by the bot with the option of support staff taking over conversation if and when needed, all in WhatsApp. 

Is such a setup possible out of the box?

**Comment by thundersparkf** [comment]
So I'm a bit confused as to how. Because the [rasa-agent-bot-demo](https://github.com/chatwoot/rasa-agent-bot-demo.git) implements their own frontend. Would that I mean I would need sort of a buffer application between my Twilio message input and rasa backend

**Comment by sojan-official** [comment]
@thundersparkf  yes with the agent bot APIs you would need to construct a bridge server between chatwoot and rasa.

**Comment by thundersparkf** [comment]
Got it! Thank you. I was able to implement it.
