### ISSUE TITLE
visitor can not cancel the chat

### ISSUE THREAD

**Issue by ufukayyildiz** [chatwoot/chatwoot#2265]
hi

Thanks for this software.

visitor can not cancel the chat, is this normal?

**Comment by iammattmartin** [comment]
Yes. Once a chat/message is opened, it remains that way. Even if closed on the admin side, it can still be updated by the visitor.

**Comment by ufukayyildiz** [comment]
ok.

but if customer does not use a personel/private pc other users can see the conversions. Even after closed the browser data is still there.

**Comment by iammattmartin** [comment]
True. Problem is currently there is no way to restart that chat, if a public conversation. 

Has been discussed in #980 but no current way.

**Comment by pranavrajs** [comment]
@timcowlishaw Closing this in favor of #2828
