### ISSUE TITLE
feat: Assign the new conversation to the sender in campaigns

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2282]
If a conversation is created via campaigns, right now it is assigned to a random agent using a round-robin mechanism. Ideally, the sender should be the initial assignee of the conversation.

**Comment by sojan-official** [comment]
Should this be optional?  The sender configured in the campaign might not be online at the time when the campaign was triggered. The round robin gives a better chance for an available agent to pick up that conversation.
