### ISSUE TITLE
Unread messages when agent send message to the contact.

### ISSUE THREAD

**Issue by drivasintelnexo** [chatwoot/chatwoot#2284]
**Describe the bug**

I have a frontend chat app consuming 1 API Channel created in my VM Chatwoot, but i notice if the contact received a message from one agent, the unread_message property is not increase. But if the agent receive the message from one contact. Unread_message increases.

**To Reproduce**

1. Send a new message from the agent in response to any contact.

**Expected behavior**

When the agent response any message to any contact created in API Channel increase the unread_message property in +1

**Screenshots**

**Browser logs**

![image](https://user-images.githubusercontent.com/84192882/118533944-4cbfde80-b70e-11eb-9544-03d73d72618d.png)

![image](https://user-images.githubusercontent.com/84192882/118534041-6a8d4380-b70e-11eb-999b-0d39a1142679.png)

**Comment by sojan-official** [comment]
@drivasintelnexo this behaviour is intended. The conversation APIs are designed to be consumed from an agent's perspective.  The current unread message counter acts as a prompt for the agents to quickly pick up the conversation where a reply is needed.

the following image indicates where the unread count is used ( green badge ) 

<img width="468" alt="Screenshot 2021-05-18 at 7 11 36 PM" src="https://user-images.githubusercontent.com/73185/118661595-e2da2e80-b80c-11eb-8688-63ad8a6e0e03.png">

it won't be helpful in this case to update the indicator on agent messages.
