### ISSUE TITLE
Don't create conversation unless clicked with campaign

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2288]
**Is your enhancement request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Currently, it looks like a new conversation is created when a rule is matched but this might be non-ideal as there will be a high percentage of chats simply with no content (replies) (or where the X (closure) is pressed). It also triggers a new conversation email which isn't ideal.

A conversation should really only be generated when a visitor interacts with the campaign and provides some details (#2287) or responds.

Likewise, if a user clicks the X, it should learn, close and not keep popping up with the message on each new page as that will get **really** annoying.

**Comment by pranavrajs** [comment]
@iammattmartin Thanks for the suggestion, we will update this experience in the next release.

**Comment by iammattmartin** [comment]
I see this was pushed and works much better, although, I do see further scope possibly, to only create the conversation when information is entered.

I note that with the campaign, it skills capturing user details, which is probably bad as it reverts to the previous widget behaviour that was quite problematic with conversations started with no valid/usable contact details and it won't stop silly messages such as "hey" without anything further.

Any possibility to improve that process @pranavrajs

**Comment by pranavrajs** [comment]
@iammattmartin Yes, this is something which we have been discussing. The behaviour to collect information would be improved in future releases.

**Comment by pranavrajs** [comment]
It was tricky to enable pre-chat form along with the campaign. We are working on how to achieve that. It's more of a product question and the UX flow. Once that is finalized, we will take that to the sprint.

**Comment by iammattmartin** [comment]
Thanks. Looking forward to that improvement.
