### ISSUE TITLE
Delete Campaigns

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2289]
**Is your enhancement request related to a problem? Please describe.**
Yes, unable to delete campaign.

**Describe the solution you'd like**
You should be able to delete (fully) the campaign instead of just disabling it.

i.e now I have some test campaigns that cannot be deleted.

**Comment by aydenbottos** [comment]
For now, you could just go to the database and remove the entry manually.

**Comment by aydenbottos** [comment]
Good point. I just thought that this Github repo was only for the self-hosted version, not the cloud one.
