### ISSUE TITLE
Getting 404 on Nextjs localhost

### ISSUE THREAD

**Issue by softmarshmallow** [chatwoot/chatwoot#2292]
I get this on console
```
Failed to load resource: the server responded with a status of 404 (Not Found)
```
![image](https://user-images.githubusercontent.com/16307013/118600541-19ec1800-b7ec-11eb-94e6-0c25b095d69c.png)

pages/some-page.tsx
```
      <Head>
        <script
          src={`(function(d,t) {
        var BASE_URL="https://app.chatwoot.com";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: '----------',
            baseUrl: BASE_URL
          })
        }
      })(document,"script");`}
        ></script>
      </Head>
```

**Comment by aydenbottos** [comment]
Just curious: are you using the cloud-hosted version, as your base URL is "app.chatwoot.com" when it should be the actual URL of your application, or did you just change that to protect privacy.

**Comment by softmarshmallow** [comment]
Yup. the hosted official version. and the code is from the chatwoot console

**Comment by aydenbottos** [comment]
Ah ok. It might be worth contacting Chatwoot support instead because as far as I can see, everything looks ok.

**Comment by sojan-official** [comment]
@softmarshmallow I think the url for some reason is coming out as  `sdk.js%22;%20%....` instead of `https://app.chatwoot.com/packs/js/sdk.js` the 404 error is because of that. 

@nithindavid  @pranavrajs  thoughts?

**Comment by pranavrajs** [comment]
@softmarshmallow Added a doc here https://www.chatwoot.com/docs/product/channels/live-chat/integrations/nextjs/ Please take a look.
