### ISSUE TITLE
Freeze screen with Gatsby 2/3 + Safari

### ISSUE THREAD

**Issue by docJerem** [chatwoot/chatwoot#2298]
**Describe the bug**

Loading of the **page is frozen on Safari + Gatsby App** (tested on Gatsby v2 & v3) , then it's impossible for the user to click on the chat or any elements.

NB: Tested with the chatwoot plugin for Gatsby and a copy/paste of the script directly in public / index.html.

NB2: Tested with new scaffolded Gatsby apps

**To Reproduce**

1. Go on a Gatsby website
2. wait 2/3 seconds ...

**Browser logs**

Impossible to display a console (Safari is frozen)

**Environment**

Gatsby v2 or v3 

**Desktop (please complete the following information):**
 - OS:  OSX
 - Browser: Safari
 - Version 14.1 (16611.1.21.161.6)

**Comment by docJerem** [comment]
@sojan-official Yes I am

**Comment by sojan-official** [comment]
@docJerem  There was an issue with our 1.16.1 release which caused unnecessary requests to get created.  
could you try updating to 1.16.2 and see if the issue is resolved?

**Comment by docJerem** [comment]
Thanks @sojan-official, I confirm the 1.16.2 fix the issue  🎉
