### ISSUE TITLE
get dialogflow bot messages in chatwoot

### ISSUE THREAD

**Issue by abasit007** [chatwoot/chatwoot#2302]
hi there hope everyone is doing fine ..
i am trying to integrate dialogflow in chatwoot but am kind of stuck bot is working fine but cant figure out how bot conversation will be fetched to chatwoot
what i have done so far:
i have setting of chatwood as suggested in => https://github.com/chatwoot/chatwoot/pull/2155
hook =  Inbox.first.hooks.new
hook.account_id = Inbox.first.account_id
hook.type = "inbox"
hook.app_id = "dialogflow"
hook.settings["project_id"] = "your dialog-flow project id"
hook.settings["credentials"] = Hash ( contents of your  dialog-flow credential key file)
hook.save!

but what i want to know what to do with fulfillment at which URL fulfillment web-hook appoint or how job will run or what event will trigger the job to fetch conversation

**Comment by sojan-official** [comment]
@abasit007  At the moment there is no support for fulfilment webhooks. The intents have to be configured in Dialogflow itself which provides back a text response or the custom payloads as mentioned in the original PR. 

As for the working.  Whenever a conversation message is created in an inbox connected with Dialogflow, a background job will call Dialogflow APIs with the message as the parameter.  The job will parse dialogflow's text of custom response and work accordingly.  


--- 
if you are facing further issues: could you show me the output for the following from your rails console.( **hide the credentials** )
```
Integration::Hook.first
```

**Comment by abasit007** [comment]
@sojan-official i am understanding but without fullfillment i didn't reaceiverd the response

**Comment by abasit007** [comment]
id: 2,
 status: "enabled",
 inbox_id: 3,
 account_id: 1,
 app_id: "dialogflow",
 hook_type: "inbox",
 reference_id: nil,
 access_token: "token that was assigned",
 created_at: Wed, 19 May 2021 07:04:48 UTC +00:00,
 updated_at: Thu, 20 May 2021 09:47:28 UTC +00:00,
 settings:
  {"project_id"=>"we-ror-rsbo",
   "credentials"=>
    {"type"=>"service_account",
     "auth_uri"=>"https://accounts.google.com/o/oauth2/auth",
     "client_id"=>"client_id",
     "token_uri"=>"https://oauth2.googleapis.com/token",
     "project_id"=>"we-ror-rsbo",
     "private_key"=>
      "-----BEGIN PRIVATE KEY-----\nkey-orignal value-\n-----END PRIVATE KEY-----\n",
     "client_email"=>"we-ror@we-ror-rsbo.iam.gserviceaccount.com",
     "private_key_id"=>"26d295214160e8872b76c78350c320eb3ae986a7",
     "client_x509_cert_url"=>"url",
     "auth_provider_x509_cert_url"=>"https://www.googleapis.com/oauth2/v1/certs"}}
     
     here is the output you asked for

**Comment by abasit007** [comment]
i am unable to get dialogflow response without fullfillment 
even if i do
 `bundle exex sidekiq -q integrations `
no background job runs

**Comment by abasit007** [comment]
@sojan-official also you can see that hook job for dialog floww is not being called in the pr anywhere [](https://github.com/chatwoot/chatwoot/pull/2155)

**Comment by abasit007** [comment]
@sojan-official i got it working but now when a user sends a message conversation is not created in the inbox

**Comment by sojan-official** [comment]
<img width="469" alt="Screenshot 2021-05-21 at 3 10 57 PM" src="https://user-images.githubusercontent.com/73185/119117321-c0cbf080-ba46-11eb-981e-4f7a3f73d9e6.png">

 when Dialogflow is enabled the conversations will initially be created under the bot category

**Comment by sojan-official** [comment]
@abasit007 let us know if you are still facing any issues.
