### ISSUE TITLE
Trick to use Slack Integration?

### ISSUE THREAD

**Issue by wflanagan** [chatwoot/chatwoot#2304]
I'm attempting to deploy the Chatwoot app using CapRover. I have configured the Slack app in my account. Further, I've configured as the documentation states in the Chatwoot help.  

When I attempt to hit "connect", I receive an error page from Slack stating: 

```
Something went wrong when authorizing this app.
Try going back and authorizing again. If problems persist, contact support for help.

Error details
Please specify `client_id`
```

When I manually add the client_id param to the URL, and hit it.. I get the OAuth dialog. If I complete this, ti returns to Chatwoot, but does not provide any sort of notification. Further, the "Slack" connect button still says "connect." 

Caprover is hosted on DigitalOcean. Latest Chrome. MacOs Big Sur.

The documentation states to use the base url as the redirect URL. I'm wondering if that's not right? Also, it seems the URL that's produced by what I'm guessing is Omniauth doesn't have the client_id in it. 

So, net, is there a trick to get the Slack integration working?

**Comment by wflanagan** [comment]
I'll add that I have a few services that integrate with Slack. And, most have this problem. I think that Slack made a change to their OAuth requirements.

**Comment by pranavrajs** [comment]
@wflanagan I can reproduce this in the staging environment. I'm not sure whether something changed recently.

**Comment by wflanagan** [comment]
@sojan-official Hey, thanks for the docker reference. FYI.. the docker image boots basically stating the following in the logs: 

2021-05-21T20:11:38.849972239Z Switch to inspect mode.
2021-05-21T20:11:38.851176267Z
2021-05-21T20:11:45.696337306Z Switch to inspect mode.
2021-05-21T20:11:45.697945289Z
2021-05-21T20:11:52.549161984Z Switch to inspect mode.
2021-05-21T20:11:52.550676445Z
2021-05-21T20:11:59.385619918Z Switch to inspect mode.
2021-05-21T20:11:59.386869082Z

and is non-operational.

**Comment by sojan-official** [comment]
@wflanagan  the images which we provide on the hub are the base images.  Using the base image you will have to build images for the server and worker with the required service

ref: https://github.com/chatwoot/chatwoot/blob/develop/docker-compose.production.yaml
https://www.chatwoot.com/docs/self-hosted/deployment/docker

**Comment by ilearnio** [comment]
This issue still happens for me after I deployed to heroku yesterday using your "One click Heroku deploy" button

**Comment by pranavrajs** [comment]
@ilearnio Have you configured the Slack app as described here https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/slack-integration-setup?

**Comment by ilearnio** [comment]
@pranavrajs Yes, I did everything exactly as described in that instructions, set the environemtns variables. Tried to restart all dynos, that didn't help.

```
$ heroku config
...
SLACK_CLIENT_ID:          1222774645425.21231111***
SLACK_CLIENT_SECRET:      ed7***
```

**Comment by pranavrajs** [comment]
@ilearnio Can you please try deploying the develop branch and see if the issue still persist?

**Comment by ilearnio** [comment]
@pranavrajs It fixed the issue! However the Chatwoot Slack app doesn't receive notifications from the website's live chat dialog. 

![image](https://user-images.githubusercontent.com/14331216/120085699-f3c75180-c0e2-11eb-8ce2-450850dc4411.png)

![image](https://user-images.githubusercontent.com/14331216/120085687-e1e5ae80-c0e2-11eb-85cf-c13a82b08b2e.png)

**Comment by sojan-official** [comment]
@ilearnio chatwoot will create a channel called customer-conversations, under which it will create threads for all the incoming messages.  Please search amidst the channels to see `customer-conversations` was created

**Comment by ilearnio** [comment]
@sojan-official Ah, you're right. It was created but it was hidden in Browse all channels view. Awesome. Thank you!
