### ISSUE TITLE
Outbound conversations not auto-opening upon response

### ISSUE THREAD

**Issue by aherrera31** [chatwoot/chatwoot#2305]
we just began sending out new messages using the "add contact" -> "new message" flow in the UI. Once we sent the message out, and the contact responded, it did not move the conversation to the "open" state, so we are missing all of these responses. I worry many other people using this flow are encountering the same thing

**To Reproduce**

1. Create a new contact with a valid phone number
2. Message (SMS) that contact using the "New Message" button
3. Have the contact respond to your message
4. You will see this conversation will not be marked as opened. In order to see the response, you'll have to search for the contact, and view their historical conversations. 

** note, this issue does not happen if the contact had previously existed and had previous conversations with Chatwoot **

**Expected behavior**

I would expect the conversation to be marked as "opened" and assigned to the person who sent the original message. The latter part of the previous sentence ties into https://github.com/chatwoot/chatwoot/issues/2303

**Environment**

Heroku self-hosted

**Comment by aherrera31** [comment]
So actually I just sent the outbound message using the reproduction steps above and it was default set to Bot, and when we get a response, it was in bot mode as well. Could this be an error on our end? @pranavrajs

**Comment by sojan-official** [comment]
@aherrera31  if you have an agent bot set on the inbox, all conversations will be created in bot status by default. 
This doesn't make sense for outbound conversations. We will take this up in our upcoming releases.

**Comment by aherrera31** [comment]
Thanks gentlemen @pranavrajs @sojan-official

**Comment by pranavrajs** [comment]
Closing as the bot status doesn't exist anymore, and there are a lot of changes in the bot configuration.
