### ISSUE TITLE
Add Ability to Send Images from SMS inbox with Twilio

### ISSUE THREAD

**Issue by bensont1** [chatwoot/chatwoot#2311]
**Is your feature request related to a problem? Please describe.**
Our support staff need the ability to show users image relating to their account

**Describe the solution you'd like**
Add ability for Agents to send image attachments by selecting a file or pasting an image (a screenshot if in clipboard) 

**Describe alternatives you've considered**
We were thinking about a short term solution with uploading an image on another service and sending a link to the user. This is not a good experience though.

**Additional context**
Would be cool to support screenshot and paste/drag and drop files

**Comment by pranavrajs** [comment]
@bensont1 Thanks for the suggestion, we don't support MMS at the moment. We will consider it in the next releases.

**Comment by sojan-official** [comment]
requires removing the condition here that limits attachments to whats app alone: 
 https://github.com/chatwoot/chatwoot/blob/70d41ffcdda51f48389e67d93f05de3a3892aa7b/app/services/twilio/send_on_twilio_service.rb#L19

ref: https://support.twilio.com/hc/en-us/articles/223179808-Sending-and-receiving-MMS-messages 

> note:  MMS messages can only be sent within the US and Canada. International MMS messaging outside these two countries is not yet supported, however, MMS messages sent internationally will be converted to SMS text messages with a URL link to the media.

## Acceptance 
- [ ] Create an SMS via Twilio inbox 
- [ ]  Try sending an MMS message to a US number from chatwoot ( should receive as MMS )
- [ ]  Try sending an MMS to non us number from chatwoot ( should receive as media URL  ) 
- [ ]  Chatwoot should handle MMS message it receives to an SMS inbox
