### ISSUE TITLE
Invited users in limbo

### ISSUE THREAD

**Issue by wflanagan** [chatwoot/chatwoot#2325]
New agents cannot be invited and gain access to the system. 

** To Reproduce **

- When I setup my new on-premise chatwoot server, I go into Teams > Agents, and invite 2 to 3 new people via email.  
- They receive an invite. 
- Click on the invite link in email.  
- They are presented with the login page. If you try to create an account, it says an account is present. If you try to login, the user doesn't YET have a password. 
- So, they can't login. 
- Next, attempt to reset password.  You'll receive a password link. 
- Click on this, and you'll be linked to the reset password screen. 
- On the reset password screen, when you add your new password, and click Submit, you get an error that states
- `Could not connect to Woot Server, Please try again later` 

And, the new Chatwoot user is stuck.  

I expected that I'd be able to invite agents, and they'd be able to access the system.

**Comment by pranavrajs** [comment]
@wflanagan Would you be able to share the server logs when the reset password API is called?

The most common reason for this error we have found is that the [FRONTEND_URL](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-frontend-url) env is not configured properly.

**Comment by wflanagan** [comment]
`2021-05-22T13:23:44.673611417Z I, [2021-05-22T13:23:44.673350 #1] INFO -- : [c4a1a109-9721-43e6-8a27-8f1e3acd5d99] Processing by DeviseOverrides::PasswordsController#update as HTML
2021-05-22T13:23:44.673648255Z I, [2021-05-22T13:23:44.673481 #1] INFO -- : [c4a1a109-9721-43e6-8a27-8f1e3acd5d99] Parameters: {"reset_password_token"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "password"=>"[FILTERED]"}
2021-05-22T13:23:44.674428318Z W, [2021-05-22T13:23:44.674235 #1] WARN -- : [c4a1a109-9721-43e6-8a27-8f1e3acd5d99] Can't verify CSRF token authenticity.
2021-05-22T13:23:44.680492912Z I, [2021-05-22T13:23:44.680260 #1] INFO -- : [c4a1a109-9721-43e6-8a27-8f1e3acd5d99] Completed 422 Unprocessable Entity in 7ms (Views: 0.4ms | ActiveRecord: 0.6ms | Allocations: 878)`

FRONTEND_URL = https://host.name.of.the.insatllation

**Comment by wflanagan** [comment]
@pranavrajs It wasn't that. It was something with the Secret. I generated a new key and placed it, and now things are operational on that front. Sorry about the noise.

**Comment by pranavrajs** [comment]
No worries! Glad to see that it is solved.
