### ISSUE TITLE
Add Hebrew support

### ISSUE THREAD

**Issue by motiko** [chatwoot/chatwoot#2326]
**Describe the solution you'd like**
Add hebrew locale support 

**Additional context**
Consider full right to left support. 
I know arabic is there but seems design is still left to right (at least on the widget).

PS I would be happy to add translations to Crowdin. I already have the widget part translated on my fork.

**Comment by pranavrajs** [comment]
@motiko Added the language here https://chatwoot.crowdin.com/chatwoot/he. :) 

RTL to LTR design change will be taken in a separate ticket.
