### ISSUE TITLE
Improve widget on page

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2328]
**Is your enhancement request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Each time you navigate through pages, the widget has to reload on the new page. This happens in-chat as well as when just a button.

Compared to say intercom where if you navigate through pages, it remains in the same place without needing to re-appear each time.

Clearly, this can be done technically so it should be considered to create a much smoother experience especially if in-chat where it disappears for a second or two on each page load.

**Comment by pranavrajs** [comment]
@iammattmartin If I understand this correctly, the experience you have shared is dependant on how the website is built and live-chat is implemented. If you could provide me with a context on how your website is built, I could help you better. 

If you look at chatwoot.com for example. We don't reload the widget on URL change. Please see the screencast below.

![FFwfqXhLeP](https://user-images.githubusercontent.com/2246121/119301381-03c4d880-bc80-11eb-8566-db783bd31ee0.gif)

**Comment by iammattmartin** [comment]
Ah ha. In that case, I shall investigate further. :)
