### ISSUE TITLE
enhancement: Inconsistent message validations for twilio SMS channel 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2333]
> When sending an SMS response in Chatwoot, I am character limited to 140 or whatever. However, when I go to "New message" via the contacts panel, I am not character limited, and I was able to send a 300 character test message out. This is an inconsistency in the UI, and not sure why do the character limit, if we can successfully send larger messages

ref: https://discord.com/channels/647412545203994635/719548300868452362/845679328213467196

- Increase the character count if 160 isn't relevant 
- Set up validation for character count in outbound messages

**Comment by pranavrajs** [comment]
@sojan-official Character count is valid, the outbound message has to re-use the logic we have in the reply box.

**Comment by sojan-official** [comment]
@pranavrajs  Twilio supports concatenation and there isn't an API hard limit at 160 I suppose. so should we enforce the limit?

ref: https://www.twilio.com/docs/glossary/what-sms-character-limit
