### ISSUE TITLE
As a business owner, I would like to set business hours on the widget

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#234]
- [ ] Create UI to accept business active hours from the UI
- [ ] Create a DB field to store the business hours
- [ ] Create an API to update the business hours.
- [ ] Provide an indication in widget if current time is outside of the business hours.

**Comment by pranavrajs** [comment]
@sojan-official Taking it out of v1.0.0, we can prioritize this in next sprint.

**Comment by azyzio** [comment]
Hey,
Let's reopen the conversation about this :) We're considering switching to chatwoot and it is the most essential missing thing in our case. 

I could potentially help on the back-end side (don't know vue.js unfortunately), but would be good to discuss the concept in more detail first. 

**1. What do you think the working hours should be associated with:**
- Whole account
- Specific agents
- Inboxes

In my company and in the chat solution we're currently using, the hours are set for the whole account. I would recommend this solution too.

**2. Working hours per day of week**
I believe it's essential to keep the working hours separate for each day of week as probably 90% of businesses are closed / have different hours on e.g. weekends.

**3. Ability to say closed**
As above - it should be possible to say that on a given day, the business is closed completely

**4. We'll need to add the concept of timezones to each account**
I believe the best place to set those is on the same screen as setting the working hours. This way, there will be less surprises for users that set the working hours without changing the default timezone setting.

**5. Actions on outside business hours**
I believe the simplest response to any message is enough for the moment. This should of course be customisable.

**6. Behaviour when all agents are offline**
In our current chat solution, the widget is automatically set to offline when no agents are connected. The same message gets sent to the sender. Personally, I would consider it out-of-scope for this issue.

**Comment by azyzio** [comment]
@pranavrajs @sojan-official 
Any thoughts here?

**Comment by pranavrajs** [comment]
@azyzio Thanks for writing up the details.

> What do you think the working hours should be associated with: In my company and in the chat solution we're currently using, the hours are set for the whole account.

I believe we might need to add the config or some kind of inheritance to the inboxes because we support multi brand inboxes. Adding the config on account is a good start.

> Working hours per day of week
I believe it's essential to keep the working hours separate for each day of week as probably 90% of businesses are closed / have different hours on e.g. weekends.

This sounds good. 

> Ability to say closed
As above - it should be possible to say that on a given day, the business is closed completely

How can we do this? Could this be a list of dates which account admin can configure as holidays?

> We'll need to add the concept of timezones to each account
I believe the best place to set those is on the same screen as setting the working hours. This way, there will be less surprises for users that set the working hours without changing the default timezone setting.

This would be required and the widget should show a relative time.

> Actions on outside business hours
I believe the simplest response to any message is enough for the moment. This should of course be customisable.

<img width="456" alt="Screenshot 2020-10-27 at 2 57 31 PM" src="https://user-images.githubusercontent.com/2246121/97282498-beb10300-1864-11eb-9811-7961996e1201.png">

I believe if the user is messaging outside of the work hours, we can just show a message, the "Team will be back on Tuesday 9:00" or so.

> Behaviour when all agents are offline
In our current chat solution, the widget is automatically set to offline when no agents are connected. The same message gets sent to the sender. Personally, I would consider it out-of-scope for this issue.

We got a similar response on https://github.com/chatwoot/chatwoot/issues/1362, I guess the offline / online part can be based on business hours.

If you have an idea on data modelling, feel free to jump in. Meanwhile I will try to create some mockups on this.

**Comment by azyzio** [comment]
Hey @pranavrajs ,

Thanks for the response. I have just pushed the required changes on the back-end. As I mentioned: unfortunately I won't be able to help with vue.js.

Eventually, I followed your suggestion and associated working hours with inboxes.

Please let me know if you have any questions or concerns regarding my approach.

Best,
Adam

**Comment by azyzio** [comment]
Regarding the needs on the front end, I can see the following:
- The toggle turn turn on / off working hours feature for a given inbox.
- The tab to update working hours for each day of week (with the ability to turn the given day of week off altogether) and an out-of-office message for a given inbox.
- The place to change the account timezone (I can see it in the above tab, but not 100% sure it's the best place)

If there's anything I can help with on the back-end side - please let me know

**Comment by pranavrajs** [comment]
@azyzio Thanks for the effort you put on the PR. Let me go through the PR. We will figure out what changes needs to be done on the frontend.

**Comment by pranavrajs** [comment]
Moving this 1.11.0 as the UI work is not complete.
