### ISSUE TITLE
Improve ability to change user accounts

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2341]
**Is your enhancement request related to a problem? Please describe.**
Yes.

We've updated our username on twitter and Facebook. There appears to be no way to sync in the new changes in Chatwoot without fully deleting and re-adding which is non-ideal.

Similar to Twilio, you cannot change the name of an Inbox once set. 

**Describe the solution you'd like**
Need a way to resync account to pickup new details, or re-align or in the cases of hard-set, be able to change the visual names in the CW GUI.

**Comment by XuanThuLe** [comment]
Ok
