### ISSUE TITLE
Ubuntu 20.04 installtion script failed (Couldn't create 'chatwoot_production' database)

### ISSUE THREAD

**Issue by ilearnio** [chatwoot/chatwoot#2351]
**Describe the bug**

I run the installation script on a fresh Ubuntu 20.04 and I got the following error (even though setup succeded (but failed to work), and error was skipped):

```
/usr/local/rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
I, [2021-05-29T03:10:25.555457 #23153]  INFO -- : Raven 3.0.3 configured not to capture errors: No host specified, no public_key specified, no project_id specified
Dropped database 'chatwoot_production'
PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
Couldn't create 'chatwoot_production' database. Please check your configuration.
rake aborted!
ActiveRecord::StatementInvalid: PG::InvalidCatalogName: ERROR:  template database "template1" does not exist
```

Thus after install the web app is showing 500 error 

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

**To Reproduce**

1. Setup a fresh Ubuntu 20.04 server
2. Execute 
```
wget https://raw.githubusercontent.com/chatwoot/chatwoot/develop/deployment/setup_20.04.sh -O setup.sh
chmod 755 setup.sh
./setup.sh master
```

3. Scroll up or search for "template database "template1" does not exist" to localte the error 

**Expected behavior**

Database should be created

**Server logs**

https://gist.github.com/ilearnio/33d1a7a74afd3d13db4f43a38553de4c

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**
 - OS: Ubuntu 12.04.2

**Comment by ilearnio** [comment]
Please let me know how can I fix that, thanks!

**Comment by pranavrajs** [comment]
@ilearnio `Dropped database 'chatwoot_production'` I don't know why this happened, let me try to deploy it on a Ubuntu machine.

**Comment by ilearnio** [comment]
I just tried it again on VirtualBox Ubuntu 20.04, same issue

**Comment by pranavrajs** [comment]
@ilearnio Just tried it on an AWS EC2 machine, it is working without issues. Can you please share the following?

1. Complete log while you run the script
2. The machine size (RAM, CPU)

**Comment by ilearnio** [comment]
@pranavrajs You can see the gist link I attached to the issue, it contains the entire log, starting from the first SSH login to Ubuntu.

VPS info:
```
15 Gb NVMe SSD Storage
Intel® Xeon™ 3 Core
1024 Mb DDR4 Memory
150 Mb/s Speed
```

Also tried on Macos through VirtualBox using Ubuntu 20.04 iso (downloaded from official Ubuntu website).

**Comment by sojan-official** [comment]
@ilearnio I think it's an issue with the encoding configuration.  
```
ERROR:  encoding "UTF8" does not match locale "en_US"
```

before running the installation script try running the following steps in your server

```
## Make sure you've got your locale properly generated
sudo locale-gen en_US.UTF-8

### Update the /etc/default/locale file with the corresponding variables
sudo cat - > /etc/default/locale <<EOF
 LANG=en_US.UTF-8
 LANGUAGE=
 LC_CTYPE="en_US.UTF-8"
 LC_NUMERIC="en_US.UTF-8"
 LC_TIME="en_US.UTF-8"
 LC_COLLATE="en_US.UTF-8"
 LC_MONETARY="en_US.UTF-8"
 LC_MESSAGES="en_US.UTF-8"
 LC_PAPER="en_US.UTF-8"
 LC_NAME="en_US.UTF-8"
 LC_ADDRESS="en_US.UTF-8"
 LC_TELEPHONE="en_US.UTF-8"
 LC_MEASUREMENT="en_US.UTF-8"
 LC_IDENTIFICATION="en_US.UTF-8"
 LC_ALL=en_US.UTF-8
 EOF
```

ref: https://ouestcode.com/journal/archive/2014-postgres-rails-the-chosen-lc-ctype-setting-requires-encoding-latin1

**Comment by ilearnio** [comment]
@sojan-official I did as suggested in the article you sent, but still have the same error. And it happens before encoding error 
![image](https://user-images.githubusercontent.com/14331216/120431807-aa486200-c381-11eb-8c71-f6aa9bbe1cbb.png)

**Comment by sojan-official** [comment]
@ilearnio  could you try running the install on a fresh VM? the installation script doesn't support reruns at the moment. So if it exited previously with an error, it would leave the installation in a halfway state.

**Comment by ilearnio** [comment]
The setup doesn't work on Virtual box Ubuntu either, even though it has correct local config

![image](https://user-images.githubusercontent.com/14331216/120462655-cceb7280-c3a3-11eb-867d-68fdd8a1e037.png)

**Comment by sojan-official** [comment]
@ilearnio  I tried on a fresh VM in the digital ocean with ubuntu 20.04 and things are working.  

If the errors are persisting and you are looking for a production deployment, I would suggest trying our caprover / docker installations. The installation and overhead management are the same.

**Comment by ilearnio** [comment]
I've debugged and fixed the issues in the existing server myself. But the issue with locale was the main one. SO thanks for helping me out!
