### ISSUE TITLE
Chatwoot widget is mostly invisible in Safari

### ISSUE THREAD

**Issue by rafpaf** [chatwoot/chatwoot#2354]
The widget is mostly invisible in Safari but visible in Chrome and Firefox.

On Safari: https://ex.plicat.io/bpt/screenshot2.png
On Chrome: https://ex.plicat.io/bpt/screenshot1.png

I checked the CSS. The only styles that affect the invisible elements are in chatwoot's own stylesheets.

I installed Chatwoot via Caprover.

**Comment by pranavrajs** [comment]
@rafpaf Would you be able to share the URL at which the widget is added? This doesn't occur in our production instance. Please see the screenshot below. 
<img width="1011" alt="Screenshot 2021-05-30 at 7 17 41 PM" src="https://user-images.githubusercontent.com/2246121/120106689-b5ca3c00-c17b-11eb-99fe-39c20621a401.png">

**Comment by iammattmartin** [comment]
Not seeing the same behaviour on our install on 4 sites, on Safari.

**Comment by pranavrajs** [comment]
Closing this as there is no further information. @rafpaf Please feel free to re-open the conversation if the issue is not resolved.
