### ISSUE TITLE
Multiple Conversations in Website Widget

### ISSUE THREAD

**Issue by dave-apex** [chatwoot/chatwoot#2355]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
From my initial tests, it looks like there is only a single conversation thread per user. We are currently Intercom users and the fact that the user can decide to start multiple, separate conversations is very helpful. It lets you thread the conversation for each topic separately.

**Comment by pranavrajs** [comment]
@dknapp47 This is under consideration, via the PR #1206

**Comment by nithindavid** [comment]
**Proposal** 
- To get multiple conversations on widget, We would need to refactor the vuex store. Currently it supports only one conversation object. So this would be a major refactoring on the store side. I would like to propose the Normalised way to manage state documented on redux  https://redux.js.org/usage/structuring-reducers/normalizing-state-shape 
I have done a basic research on the approach to do this.
https://github.com/chatwoot/chatwoot/compare/spike/multiple-conv-widget?expand=1

- We would need an another vue page which lists the multiple conversations and associated state actions and getters for the same. This could be a good starting point which can be started on storybook.

- We could create another module for the store part, Which could be again sub divided as smaller PR's by starting with the initial state, mutations, actions, getters as subsequent PR's along with tests for each and covering all the actions/cases in current store. 

- Then we could use the store on the conversations page and last would the biggest part of replacing the current state invocations on the Vue file side and replacing them with the new store.
