### ISSUE TITLE
trying to use bot message from article you provided but not working

### ISSUE THREAD

**Issue by NitinNR** [chatwoot/chatwoot#2358]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

![Screenshot (11)](https://user-images.githubusercontent.com/46310938/120441118-e12e7000-c3a1-11eb-804d-52c45a91809c.png)

**Comment by pranavrajs** [comment]
@NitinNR Can you please provide the payload, the API URL, logs etc so that we can take a look into this?

**Comment by NitinNR** [comment]
here is the postman request
![Screenshot (13)](https://user-images.githubusercontent.com/46310938/120442312-15566080-c3a3-11eb-93a5-3c4052b92234.png)

and response:
![Screenshot (14)](https://user-images.githubusercontent.com/46310938/120442393-2ef7a800-c3a3-11eb-8ebf-713769774dbe.png)

**Comment by sojan-official** [comment]
@NitinNR  In your payload, you are specifying the `message_type` attribute to be incoming. ie messages sent from contact to agents. 

There is no support for that. Bot messages can only be `outgoing`. ie send from the bot / agent to a contact.

**Comment by NitinNR** [comment]
> @NitinNR In your payload, you are specifying the `message_type` attribute to be incoming. ie messages sent from contact to agents.
> 
> There is no support for that. Bot messages can only be `outgoing`. ie send from the bot / agent to a contact.

It's also not working as outgoing too?

**Comment by sojan-official** [comment]
@NitinNR  The bot messages will only be rendered properly in the chat widget,  On the dashboard, they will only appear as normal messages.

**Comment by NitinNR** [comment]
> @NitinNR The bot messages will only be rendered properly in the chat widget, On the dashboard, they will only appear as normal messages.

Chat widget?I just don't get it.explain

**Comment by NitinNR** [comment]
hello please anyone can tell me whats the issue here?

**Comment by sojan-official** [comment]
This is the chatwoot chat widget.  The screenshot you have posted are of our agent dashboard

<img width="474" alt="Screenshot 2021-06-03 at 5 32 06 PM" src="https://user-images.githubusercontent.com/73185/120641755-a0158900-c491-11eb-8417-8e80bd0bc16b.png">

**Comment by NitinNR** [comment]
so bot message only support in chat widget that's not fair it should be in website or panel too

**Comment by iammattmartin** [comment]
@NitinNR You can always change the code yourself. Saying "it's not fair" when this project is open source, is a bit rich. You don't *have* to use the software, no doubt, without paying for a support subscription.

**Comment by NitinNR** [comment]
> @NitinNR You can always change the code yourself. Saying "it's not fair" when this project is open source, is a bit rich. You don't _have_ to use the software, no doubt, without paying for a 

Yah yah yah only because I am not paying for this so I don't speak anything about it right just use whatever I have is that you wanna say.

**Comment by pranavrajs** [comment]
@NitinNR 

If something is not working or has to be improved, please feel to create an issue with suggestions. As a community, we try to accept most of the suggestions provided by the community members.

If there is a certain request which doesn't feel in the direction of the product or is not in the immediate pipeline, we ask people to create a fork to solve the use case. It doesn't mean the suggestions are not valued or it should not be raised. 

The expectation that community members would prioritize every request is not ideal. If there is a request/change, please take time to write about the use case and solution proposed.
