### ISSUE TITLE
As a business owner, I would like to customize the color of the widget.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#236]
- [x] Add a DB field to store the hex value
- [ ] Implement Color Picker in the UI
- [x] Update the color the widget based on the config

**Comment by pranavrajs** [comment]
Fixed via #387

**Comment by tabrza** [comment]
@pranavrajs - hope you had a great weekend!
i've been trying to change some of the colors on the color picker but can't for the life of me figure out from where. it all appears in the node modules which of course is in the gitignore..
