### ISSUE TITLE
Incoming email with SendGrid: No template found for ActionMailbox::Ingresses::Sendgrid::InboundEmailsController#create

### ISSUE THREAD

**Issue by jike212** [chatwoot/chatwoot#2362]
I've connected my self-hosted chatwoot to Sendgrid however I receive the following log entry when incoming messages come in and the messages do not appear in the inbox.

```
No template found for ActionMailbox::Ingresses::Sendgrid::InboundEmailsController#create, rendering head :no_content
```

I can't seem to find anything related to this in the documentation

**Comment by pranavrajs** [comment]
@jike212 Have you configured `RAILS_INBOUND_EMAIL_SERVICE` env to `sendgrid`? 

Please see this doc https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity#configuring-inbound-reply-emails

**Comment by jike212** [comment]
Hi, yes I've done that (I believe that's how it knows to use sendgrid ingress)

**Comment by pranavrajs** [comment]
1.31.1 is an old version. Could you please try updating it to 1.16.2 and see if it still persist? (Please note that you would have to update 1.14.0 -> 1.15.0 -> 1.16.2 upgrade, let me know if you need any help)

**Comment by jike212** [comment]
Just ran the upgrades in that order (currently running 1.16.2) and continuing to get the same error in the logs for incoming emails.

**Comment by pranavrajs** [comment]
@jike212 Thanks for confirming, we will test it out.

**Comment by jike212** [comment]
Thank you, let me know if there's anything I can share privately as well before I rebuild it again just in case you're able to catch something with a quick glance

**Comment by jike212** [comment]
After rebuilding everything from scratch, emails now seem to be working fine. Not sure what was causing it previously.
