### ISSUE TITLE
Inbound e-mails are cropped

### ISSUE THREAD

**Issue by yourbabyscan** [chatwoot/chatwoot#2365]
When customers send an e-mail to us (info@mydomain.com), their e-mail is redirected to SendGrid (guid@parse.mydomain.com) which then uses the webhook to add the e-mail to Chatwoot. The new conversation appears. This is sometimes cut off (maybe 50% of the time at the moment, but we don't receive many e-mails directly through this method). Working e-mails have included attachments, but the text of the body of the e-mail has appeared cropped. So much so, that on some occasions I could see the beginning of the message body in the conversation list, but when I selected the message I couldn't read any of the message body. 

I've checked our Azure Blob Storage and the full/entire e-mail appears to be there and intact, but isn't available when viewed as a message. 

**To Reproduce**

Send e-mails to Chatwoot e-mail address of varying length. Reply to the e-mail from Chatwoot, and then reply again to Chatwoot. E-mails variably get cut off. Sometimes entirely, sometimes half of the e-mail would be missing, and sometimes only a few letters missing. 

**Expected behavior**

The entire message from the customer would be visible. 

**Screenshots**

<img width="483" alt="Screenshot 2021-06-02 at 17 55 33" src="https://user-images.githubusercontent.com/79193857/120521141-83634d80-c3cc-11eb-8e61-2cf6abbd9a63.png">
<img width="492" alt="Screenshot 2021-06-02 at 17 55 44" src="https://user-images.githubusercontent.com/79193857/120521158-878f6b00-c3cc-11eb-9f27-ab6cb049013e.png">
<img width="480" alt="Screenshot 2021-06-02 at 17 56 25" src="https://user-images.githubusercontent.com/79193857/120521171-89f1c500-c3cc-11eb-9423-e3375888b526.png">

In each of the screenshots, the message was truncated. The original e-mail contained more content, and was present in the blob in Azure Blob Storage. (can't share due to sensitive info). 

**Browser logs**

I've included the browser logs. Whilst there's loads of errors listed, none leapt out to me as the cause, or relevant...
[chat.yourbabyscan.com-1622653688615.log](https://github.com/chatwoot/chatwoot/files/6586345/chat.yourbabyscan.com-1622653688615.log)

**Server logs**

Share the server logs to debug the issue further

**Environment**

Heroku instance

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 91.0.4472.77

**Comment by pranavrajs** [comment]
@yourbabyscan Thanks for reporting the issue with detailed logs. Could you please add the Chatwoot version you are using? You can see the version in Settings -> Account Settings

**Comment by pranavrajs** [comment]
@yourbabyscan Can you please confirm if you still have the issue?

**Comment by yourbabyscan** [comment]
> @yourbabyscan Can you please confirm if you still have the issue?

Hi @pranavrajs, unfortunately, yes. :(

I thought I'd set up automatic updates in heroku so that I would receive future updates, and the problem would go away over time, however I realised a few days ago, I'd set this up against a fork rather that the original so hadn't been getting updates. I got quite excited with hopes that updating might resolve this frustration, however, following a successful upgrade to the latest version, I'm still experiencing the same problem. 

I'm currently deployed from 20b96c7 in the master branch, committed 7 days ago (v1.19.0).

Interestingly the mobile app has differing results. Often e-mails that are cropped in the web app, are visible in the mobile app, but also e-mails that are visible in the web app can suddenly display HTML in the mobile app, almost as though it contains malformed HTML that the app isn't handling. In all instances, the full version of the e-mail appears to be stored in blob storage (in my case Azure). 

I also haven't yet seen the issue occur through any other channels (we're using Facebook, SMS & WhatsApp via Twilio, E-mail and Website) and this only seems to happen with E-mail. 

Any suggestions you may have would be very much appreciated

**Comment by pranavrajs** [comment]
@yourbabyscan Would you be able to share one such email (original EML version)? If not here, please share it on hello@chatwoot.com. Here is an article on how to download the original message(https://support.google.com/mail/answer/9261412?hl=en)
