### ISSUE TITLE
Super long emails slow down site (Image error)

### ISSUE THREAD

**Issue by TyCoolidge** [chatwoot/chatwoot#2367]
**Is your enhancement request related to a problem? Please describe.**
On our local chatwoot, we received about 14 emails each containing a message with over 100,000+ characters (seems like an image was trying to be sent)

**Describe the solution you'd like**
There should be a way to filter images like this out instead of returning all those characters

**Describe alternatives you've considered**
I quick button to delete conversations would be helpful.

**Comment by pranavrajs** [comment]
@TyCoolidge If you don't mind, will it be possible to share the email export to debug this issue?

**Comment by pranavrajs** [comment]
@TyCoolidge This was an issue with the way text content was captured. This has been fixed in the commit mentioned above. Future emails should not have an issue.
