### ISSUE TITLE
As an agent, I would like to update my name, profile picture

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#238]
- [ ] Add a profile section for the agent
- [ ] Allow the agent to update his name
- [ ] Allow the agent to upload image from the UI
- [x] API to update agent name, email and password
- [x] API to update avatar - dependant on #158

**Comment by sojan-official** [comment]
ref : #294

**Comment by sojan-official** [comment]
https://evilmartians.com/chronicles/rails-5-2-active-storage-and-beyond
