### ISSUE TITLE
download agent reports does nothing

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#2397]
**Describe the bug**

On the reports page, when clicking download agent reports, nothing happens. Please advise if this is a configuration issue?

**Comment by iammattmartin** [comment]
Do you have a popup blocker active?

It works here but you have to allow the popup. A CSV is downloaded once accepted.

**Comment by pranavrajs** [comment]
@tabrza Can you please share a screencast of the behaviour? There is no additional configuration for it to work.

**Comment by tabrza** [comment]
Turning off the popup blocker worked. thank you! 
what is the file type though? i changed it to xls and tried opening it with my editor as well but there's no formatting etc.

**Comment by tabrza** [comment]
Turning off the popup blocker worked. thank you! 
what is the file type though? i changed it to xls and tried opening it with my editor as well but there's no formatting etc.

**Comment by iammattmartin** [comment]
It's a CSV.

**Comment by sojan-official** [comment]
@tabrza  are you still facing issues ?

**Comment by tabrza** [comment]
All fine now, thank you so much
