### ISSUE TITLE
As an agent, I would like to know which all agents have participated in the conversation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#241]
- [x] Add participant table to store the conversation participants. Table references a conversation and, a contact, or a user. 
- [ ] Whenever a new user/contact replies to the conversation add them to the participant table.
- [x] Show the list of participants a new table in the sidebar
- [ ] tagging agents add thems to participants table
- [ ] ability to receive notifications from participating conversations

**Comment by SuprajaRamesh** [comment]
Hi! I'd like to work on this if no one has picked this up already.

**Comment by SuprajaRamesh** [comment]
@sojan-official @pranavrajs Do we need a separate table for this purpose? We can query this information from the messages table using the conversation_id, isn't it?

**Comment by pranavrajs** [comment]
@SuprajaRamesh Querying might not be effective, having a separate table is suggested as the query would be simple.

@sojan-official Thoughts?

**Comment by sojan-official** [comment]
makes sense to me. Let's have it as a separate table, will be helpful in future if we want to add permissions based on participation.

**Comment by sojan-official** [comment]
ref: #2443
