### ISSUE TITLE
Sometimes, the email channel conversations takes forever to load

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2418]
**Describe the bug**

The conversations emerging from an e-mail inbox takes 30 seconds plus to load and fails with a timeout error without any updates in the UI about the data or the error.

**To Reproduce**

1. Create an email inbox channel
2. Visit conversations menu item
3. The loader in the conversations just keeps spinning forever.
4. Timeout error in the browser console and nothing in the UI

**Expected behavior**

The conversations should load ASAP.

**Screenshots**

N/A

**Browser logs**

Timeout error. 

**Server logs**

N/A

**Environment**

Docker on AWS.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Hosted AWS Amazon Linux Docker
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 1.16.2

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sojan-official** [comment]
@srameshr Could you take a look at the rails server logs and see if there is something helpful?

**Comment by srameshr** [comment]
Il update this bug when I can reproduce the issue again.

**Comment by pranavrajs** [comment]
@srameshr The fix would work for the future emails.
