### ISSUE TITLE
Instagram direct messages inbox channel

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2419]
**Is your feature request related to a problem? Please describe.**
Facebook has recently opened the Instagram direct messages API to the public and it would be the most used channel to integrate with.

**Describe the solution you'd like**
The new Instagram DM inbox channel.

**Describe alternatives you've considered**
N/A

**Additional context**
Since this is the most used communication channel I think this should be a priority as most businesses depend on it.

**Comment by iammattmartin** [comment]
This is a duplicate of #2096, raised some time back.

**Comment by pranavrajs** [comment]
Closing as it is a duplicate of #2096
