### ISSUE TITLE
Widget scroll with campaign active

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#2430]
**Describe the bug**

When a user clicks on the campaign message, it opens the full widget to start but then has a long scroll already active.

Scrolling to the bottom shows an empty message window.  Also, it loses focus of the original reply window as attached.

Latest build as a of few minutes ago.

![Screenshot 2021-06-15 at 7 04 16 PM](https://user-images.githubusercontent.com/15971590/122101716-8e769e80-ce0c-11eb-8e2f-d960b8abfec1.png)

Edit: this also is replicated in the pop-out window widget which rules out any offending content on the page when in-line.

**Comment by pranavrajs** [comment]
@iammattmartin Can you please try clearing the cache and rebuilding the assets?

**Comment by iammattmartin** [comment]
With `rake assets:clobber assets:precompile RAILS_ENV=production`?

If so, we already do that on each update to ensure nothing is left behind.

**Comment by pranavrajs** [comment]
Yes, weird. It would be helpful if you could share a screencast about the same.

**Comment by iammattmartin** [comment]
I'll ping you over an email shortly.

**Comment by pranavrajs** [comment]
@iammattmartin Never mind, I could reproduce the error. It was a silly mistake. Thanks for reporting. I will get it merged once the tests are passed.

**Comment by iammattmartin** [comment]
:) Did send that over already but glad you've identified it.
