### ISSUE TITLE
Investigate the effort required to add Elasticsearch

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#244]
- [ ] Figure out the gems to be used
- [ ] Figure out if any additional configuration is required

**Comment by aadrian** [comment]
@pranavrajs what would be the role of Elasticsearch in this project since Postgres does have full text search out of the box?

**Comment by pranavrajs** [comment]
@subintp @sojan-official Please share your thoughts.

**Comment by sojan-official** [comment]
@aadrian  The initial requirement here is searching through the chat message for which the full text search might suffice. 

But I see search requirements for us involving multiple data models, especially on the filtering front. .
So let's invest in a robust search and index solution.  

 
ref: https://github.com/ankane/searchkick

**Comment by sojan-official** [comment]
Elastic search can be implemented with the seachkick gem without additional complications in the rails app side. But it would add up an additional layer in infra set up, which would be an added complication. so for the initial search, we will go with postgres full-text search . 

We will explore this later if required.
