### ISSUE TITLE
Live chat widget preview for inbox settings page

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2441]
### The problem
Currently there are more than 8 different configuration settings on widget in the form of color, Welcome titles, greetings etc. This could possibly create a confusion when a user is configuring the widget on their website. There is no way to predict how the widget will behave depending on the combination of these settings.

### Proposed solution
To solve this we will have an widget configure page, which will have a dummy widget which will change it's appearance as per the settings. **This can be imagined like a widget preview on settings page**

### Breakdown of achievable tasks

- [ ]  Storybook entry for the widget preview component. This will be a bare minimal replica of our live widget without any functionality. Just need to mimic the look and feel.
- [ ] Modifying the component to accept props and change look according to the settings selected.
- [ ] Creating a settings page to include the widget component and settings to configure.
- [ ] Integrating the page with widget settings page.

**Comment by srameshr** [comment]
@pranavrajs @SanjuSudheerM  Will this be available in the next weeks release?

**Comment by pranavrajs** [comment]
Closing this via #2853
