### ISSUE TITLE
Feat: New User Role - Conversation Participant

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2443]
Create a new type of user role `participant` with limited permissions who can only

- View conversations where they have been added as a participant 
- Reply to the conversations where they have been added as a participant. 
- Receive notifications on updates in conversations in which they are participating
- Use Chatwoot mobile apps

## Additional Changes 

- Conversations will have a participants Section where agents can add a specific participant
- All Conversation Assignees will also get added to the participant section on the assignment.
  -  this let them follow the relevant conversation even when the assignment changes

## Use Cases 

- New customer support rep who is under training, where access can be given at specific conversation levels
- Bring In members from other functions if a customer query requires their help
- Ability to facilitate conversations between multiple stakeholders and customer in industries like delivery, ecom etc 
    -  Vendors / Merchants can be added to relevant conversations as participants via API/Agent Assignment
    -  A customer support agent can bring in the delivery personnel as a participant to the conversation in case of customer queries.
    
 ref: https://github.com/chatwoot/chatwoot/issues/1093#issuecomment-663958872

**Comment by hanthor** [comment]
Tagging an agent should automatically make them a participant and send them a notification.

**Comment by pranavrajs** [comment]
@hanthor When a user is tagged in a conversation, they will get a notification via email/push. You can enable the notifications in the profile settings.

**Comment by joshymg** [comment]
"this let them follow the relevant conversation even when the assignment changes"
That will be a deal killer for me. If the 'participant' is removed from the conversation, then they should not be able to view that any longer.

**Comment by sojan-official** [comment]
@joshymg  `assignment` denotes ownership of the issue, `participation` denotes permissions to access the conversation/who should receive notifications. 

- `assignment` is extra responsibility added to a participant 
- removing a person from the participant list will remove their access to the conversation as well.

**Comment by sojan-official** [comment]
note: temporary workaround  shared by techworkpro on #discord
ref: https://discord.com/channels/647412545203994635/647729576427913228/915803454121848882

> Create Email Inbox per agent to be segmented. 
> Admins will be added as collaborators on every Inbox.
> Upon receiving a new conversation, admin/first line agent will reply first. Then click on the contact name in rightside details tab to open the contact details in new page. From there they write a new message to the contact after selecting the correct inbox it has to be assigned to. The segmented agent can only see this conversation and take over the lead from that inbox. The admin can add more details like phone number to the contact, if its not already automatically captured. Also make use of the Private notes to pass any relevant handover info.

**Comment by ayushin** [comment]
Is this going to be done any time soon?

We are building a service marketplace where we would like to use chatwoot for customers to communicate with service providers while customer support is able to monitor/intervene.

So we need a way for a chatwoot user to initiate a new conversation and add another user as a participant at the same time notifying the new participant (the service provider) of a new conversation.

Is this something feasible with chatwoot or shall we build a custom chat app for this?

**Comment by ayushin** [comment]
I can imagine that when a new conversation is created, a webhook is fired and when our platform recognises the booking number, it would call the chatwoot api and add the relevant participants and it would be done.

**Comment by ayushin** [comment]
Anybody interested in implementing this? We may be able to sponsor this feature.

**Comment by sojan-official** [comment]
@ayushin  thanks for providing the feedback. The implementation is still under discussion amidst the team and we don't have an ETA for this yet.

**Comment by joshymg** [comment]
Any possibility of a temporary fix using some front-end tweak? 
e.g.: Hide the "Unassigned" and "All" tabs on the Agent dashboard and the mobile App. Agents need to see only the conversations explicitly assigned to them.

**Comment by pranavrajs** [comment]
Closing as completed.
