### ISSUE TITLE
Dialogflow integration for API type inboxes

### ISSUE THREAD

**Issue by randhipp** [chatwoot/chatwoot#2461]
**Describe the bug**

No Inbox shown in dropdown when add dialogflow integration, despite inboxes already created with API Type.

**To Reproduce**

1. Go to dialogflow integration
2. Add new hook
3. click on inbox select / dropdown
4. no option can be selected

**Expected behavior**

Inboxes shown, and can be set to API type inboxes.

**Screenshots**

![image](https://user-images.githubusercontent.com/25372728/122696962-8be1d200-d26e-11eb-93b2-73eeb1a03a33.png)
![image](https://user-images.githubusercontent.com/25372728/122697057-b5026280-d26e-11eb-9c6b-c77531e74e21.png)

**Environment**

tested on local server with latest develop, and app.chatwoot.com. Both have same issue

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (x86_64)

**Comment by pranavrajs** [comment]
@randhipp Thanks for the suggestion, we are already considering it for other inboxes. The only thing pending is to test out the flow and see if everything is working properly.
