### ISSUE TITLE
Allow the user to create a new conversation if the previous one is resolved

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2466]
- If CSAT survey is enabled
  - Disallow user to reply to a resolved conversation, show new conversation button
 
- If CSAT survey is disabled
  - The behaviour of the input box remains the same.

**Comment by pranavrajs** [comment]
@muhsin-k I will share the UI mockup by Wednesday.

**Comment by iammattmartin** [comment]
Would there be a way to ensure a new conversation without using CSAT?

Also, when someone opens (or re-opens?) a previous conversation about one topic, if a new conversation, it might be nice to "link" them.

So when staff look, they could see a "customer created a new ticket, in reference to previous conversation[link]".

As much as there needs to be an ability to open multiple conversations as they may pertain to different things, if you auto close a conversation but help is still needed, one single topic could be split over 1 or more conversations making things very fragmented. 

Maybe a merge conversations button is needed for such a scenario.
