### ISSUE TITLE
feat: CSAT Responses

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2472]
- [x] Add a `csat_response` table to capture the response 
      [point, feedback text, converastion_id, assigned_id]
- [x] Add an API to fetch the list of responses 
      (paginated - default page size: 25)
      (Date range filter)
- [x] Generate CSAT Records when contact interact with the component

**Comment by sojan-official** [comment]
Raises https://github.com/chatwoot/chatwoot/pull/2503 for the first 3 items.
Let's take up the remaining reporting APIs in another PR
