### ISSUE TITLE
Investigate the effect on merging a contact on widget

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2474]
- Investigate the side effects of merging a contact on the widget side
  - Do we need to consider handling pubsub token on the widget?

- Do we need to update the existing conversation with the new contact object?
- Do we need to remove the existing contact from the UI store?

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/2457 

If the mergee contact is currently chatting on web widget, merging will break the live chat.
We will have to update the pubsub token on the widget
