### ISSUE TITLE
A way to close a conversation with a user via API

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#2488]
**Is your feature request related to a problem? Please describe.**
In a bot context, we would like that at the end of a conversation, the conversation gets closed. Currently, when a user would "finish" a flow, the chat (via widget) just remains there and the user can still type stuff.

**Describe the solution you'd like**
An API endpoint that lets us finalize a conversation where a user can actually see that the conversation is closed. As such, when a user opens the chat page next time, they start with a fresh conversation.

**Describe alternatives you've considered**
Perhaps calling `reset()` on the web page when the widget loads, to start a new session for the user every time.

**Additional context**

**Comment by sojan-official** [comment]
@brentco  If you create a new conversation against the user contact inbox,  The widget will load the latest conversation ( empty) .

ref: https://www.chatwoot.com/developers/api/#operation/newConversation 

let me know if this helps

**Comment by brentco** [comment]
Hi @sojan-official ,
Thanks for the information, but it's not quite what I'm looking for. Once the conversation "ends" the user should be unable to send more messages AND additionally, when they visit the chat page again, their closed chat should be gone.

**Comment by sojan-official** [comment]
@brentco  At the moment the chat widget only supports one conversation. If a new conversation was created through the API. it will replace the existing conversation show to the user. they won't be able to send more messages. 

We also have a new CSAT feature that is coming up, where you will get a similar behavior on conversation resolution.

**Comment by pranavrajs** [comment]
Closing this in favor of #2827
