### ISSUE TITLE
After resolving conversation, go to next conversation or blank if it was the last

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#2489]
**Is your enhancement request related to a problem? Please describe.**
When the last conversation in Inbox is marked Resolved, the URL remains
https://app.chatwoot.com/app/accounts/3889/conversations/77
and the screen on the right still shows conversation details.
The "Conversations" section on the left is empty, as expected.

**Describe the solution you'd like**
Change URL to
https://app.chatwoot.com/app/accounts/3889/dashboard
and show a message that there are no conversations.

Thanks!

**Comment by sojan-official** [comment]
You could use our keyboard shortcuts to navigate to the next conversation 

![Screenshot 2021-09-06 at 12.03.09 AM.png](https://images.zenhubusercontent.com/5d8c823e1165610001736621/1aea9d70-70f4-4d6b-8c2a-24f4df6b56c9)

**Comment by pranavrajs** [comment]
Closing this in favor of https://github.com/chatwoot/chatwoot/issues/5372
