### ISSUE TITLE
Inbox Settings (Email) - Reply time is not set

### ISSUE THREAD

**Issue by ddlogesh** [chatwoot/chatwoot#2492]
**Inbox Settings (Email) - Reply time is not set in backend**

**Screenshots**

<img width="1440" alt="Screenshot 2021-06-22 at 9 50 00 PM" src="https://user-images.githubusercontent.com/35095700/122963746-30196500-d3a4-11eb-9693-e45ddee1af43.png">

**Environment**

Chatwoot Cloud (app.chatwoot.com)

@sojan-official Please do assign me.

**Comment by sojan-official** [comment]
@ddlogesh  if you are going to work on this. 

Let's stop showing the reply time field for email inboxes as it isn't relevant in the case of the email channel

**Comment by sojan-official** [comment]
this has been fixed in recent releases
