### ISSUE TITLE
Allow superadmin to confirm users manually

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#2513]
**Is your enhancement request related to a problem? Please describe.**
I NEED an email setup to create new accounts. This is not always possible.

**Describe the solution you'd like**
Allow a super admin to verify accounts without an email.

**Describe alternatives you've considered**
Created a temporary sendgrid account that uses gmail but this is blocked by many servers.

**Comment by sojan-official** [comment]
While we will evaluate adding this as functionality to super admin.  you could verify accounts using the rails console.

```
u = User.find_by(email: 'agent_email')
u.confirm
# if you want to resend confirm instructions instead 
# u.send_confirmation_instructions
```

**Comment by brentco** [comment]
Ah that's good that at least there is already an option, however, I don't expect the business people that will manage the instance to be able to execute things in the rails console.

**Comment by sojan-official** [comment]
> Ah that's good that at least there is already an option, however, I don't expect the business people that will manage the instance to be able to execute things in the rails console.

You are right. That's not an expectation 😁
This is more of a workaround.

**Comment by sojan-official** [comment]
closing this since super admin now have the ability to update the confirmed date for users, which marks them as confirmed
