### ISSUE TITLE
Outgoing Sendgrid issues: from address does not match a verified Sender Identity

### ISSUE THREAD

**Issue by jike212** [chatwoot/chatwoot#2522]
Running Chatwoot 1.17.1

Outgoing emails were previously working for me using Sendgrid however they seem to be quite fragile. Today, outgoing messages appear to have stopped working completely and I receive the following error in the worker logs:

```
 WARN: Net::SMTPFatalError: 550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved.
```
The domain is validated (and was working previously) and the `MAILER_SENDER_EMAIL` environment variable is set as well.

The only thing I can think of for it not working is that I added a second email inbox (just for testing incoming mail, not outgoing) but I didn't change the mailer sender email variable which was working previously so there shouldn't have been any issue with the original inbox.

Is there a way to display in the logs what the from address is? The outgoing email feature still seems very fragile in my testing experience so far. It will work one day and stop working the next and the reasons as to why are unclear.

**Comment by semaf** [comment]
Have the same issue with verified domain and email addresses.

**Comment by angebagui** [comment]
I have the same issue.

**Comment by bhavyajhaaa** [comment]
<img width="816" alt="sendgrid_error" src="https://user-images.githubusercontent.com/47248872/154831010-3c0d4dd6-5c64-4cc7-b182-0b63c5326413.png">
@pranavrajs @sojan-official Having the same issue. Please help with this.

![image](https://user-images.githubusercontent.com/47248872/154831607-ddf60fec-3901-40fc-8b3d-5c9954e180ad.png)

The email id is contact@weunlearn.org and weunlearn.org is verified in sendgrid.
We have also tried to keep SMTP_DOMAIN as weunlearn.org

**Comment by sojan-official** [comment]
@bhavyajhaaa could you specify the following information

- which is installation environment which you are using? 
- did you update `MAILER_SENDER_EMAIL` variable with an email address that is from your verified SendGrid domain?

**Comment by bhavyajhaaa** [comment]
@sojan-official 
- We're deploying on AWS ECS using the official chatwoot image.
- We verified domain and single sender for contact@weunlearn.org

![image](https://user-images.githubusercontent.com/47248872/154959249-84d1cf01-1747-4590-8707-63b7d7b77aec.png)

**Comment by sojan-official** [comment]
@bhavyajhaaa could you make sure that the environment variables are updated inside your worker containers as well? 
 also, that both the worker and web services were restarted after the variables were updated.

**Comment by bhavyajhaaa** [comment]
@sojan-official 
![image](https://user-images.githubusercontent.com/47248872/154963687-67efad40-5497-4d25-aff6-e9e5558ac9d7.png)
this is inside the containers and both have the same value.
The services are restarted after updation too.

**Comment by sojan-official** [comment]
@bhavyajhaaa  The only thing I can think of in this case is the value of the `MAILER_SENDER_EMAIL` that is getting sent to SendGrid isn't the right one. Everything else seems right.  

Could you open up a rails console inside the container and check the value? 
```
ENV.fetch('MAILER_SENDER_EMAIL', '')
```

if it's not returning the correct value, you might need to check with SendGrid support. 
Could also try configuring an alternative email provider like mailgun just to verify.

**Comment by bhavyajhaaa** [comment]
@sojan-official 
Realised the error was in env variable name - "MAILER_SENDER_EMAIL " instead of "MAILER_SENDER_EMAIL"
But a new error is showing up now.
![image](https://user-images.githubusercontent.com/47248872/154984524-976deda7-5444-4cce-b2f6-c9fb656b2a7c.png)

**Comment by sojan-official** [comment]
@bhavyajhaaa could you try with port 465?

ref: https://sendgrid.com/blog/whats-the-difference-between-ports-465-and-587/

**Comment by HT-Moh** [comment]
Thanks, I missed it. now it works 
I change `support_email` column on the account table directly, but it didn't work. 
I changed the `settings_flag` to 1 as well then I was to see to Support Email on the frontend.

**Comment by sojan-official** [comment]
@HT-Moh thanks for the update. 

Generic emails like password reset and agent confirmation are sent using the value in an environment variable. 
The support email flag is specific for account emails like conversation continuity.

**Comment by bhavyajhaaa** [comment]
@sojan-official  Tried with port 465 now but the same error shows up.
![image](https://user-images.githubusercontent.com/47248872/155116113-7a4d6e5e-ce98-4afc-a6e2-32cf45cdb9a5.png)

**Comment by sojan-official** [comment]
@bhavyajhaaa  could you verify the value of `SMTP_DOMAIN` and make sure that its your verified domain ? 

double check that the following environment variables are configured as per below 
```
SMTP_ADDRESS=smtp.sendgrid.net
SMTP_AUTHENTICATION=plain
SMTP_DOMAIN=<your verified domain> ( not smtp.sendgrid.net domain )
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_PORT=587
SMTP_USERNAME=apikey
SMTP_PASSWORD=<your Sendgrid API key>
```


if  it doesn't work could you try setting tls as true? 
add SMTP_TLS=true environment variable to chatwoot instance.

https://stackoverflow.com/a/49295050/939299

**Comment by bhavyajhaaa** [comment]
@sojan-official Updating SMTP port to 587 worked. Thank you for helping out!
