### ISSUE TITLE
As an agent, I would like to send files/images to the user

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#253]
- [x] Handle file/image upload in UI
- [x] APIs for attachment upload

**Comment by nivv** [comment]
@pranavrajs Is this implemented for email conversations as well? I can't seem to find the attachment button.

![image](https://user-images.githubusercontent.com/4033930/116210703-67241f00-a743-11eb-9b00-bbdde79f6923.png)

**Comment by pranavrajs** [comment]
@nivv It might be a bug, can you please raise a separate issue?

**Comment by nivv** [comment]
@pranavrajs will do! Thanks!
