### ISSUE TITLE
feat: Improved sidebar for agent dashboard

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2530]
- Update the sidebar of the chatwoot agent dashboard to accommodate a secondary navigation.

![image](https://user-images.githubusercontent.com/2246121/123600240-19479800-d814-11eb-882e-8baa9775a4e5.png)

**Comment by iammattmartin** [comment]
Being able to hide Inboxes with no conversations (from an earlier issue) would be helpful as with as many as we use, we never see the labels above the fold. I'm sure others will be the same.

**Comment by pranavrajs** [comment]
@iammattmartin Thanks for the suggestion. It makes sense. This would allow you to customer views filters and along with that we would add the ability to hide empty inboxes as an enhancement.

**Comment by iammattmartin** [comment]
I think the "add new inbox" may be redundant there too. After all, how often does someone add new inboxes compared to say filters or labels. Those two I could see have regular usage but inboxes, I'd think are fairly static once all configured.

**Comment by nithindavid** [comment]
@iammattmartin The redundant "add new inbox" makes sense. I'll try it without the filter.

**Comment by pranavrajs** [comment]
Closing this as the design is already implemented.
