### ISSUE TITLE
confidentiality and transfer

### ISSUE THREAD

**Issue by josep112** [chatwoot/chatwoot#2547]
** Is your feature request related to an issue? Please describe.**
Agents should have secrecy in messages and the ability to transfer the channel

** Describe the solution you would like **
An agent talking to a channel could only be seen by an agent with supervisor category. If the agent wanted to transfer the conversation to another agent, the messages would be visible in this case

**Comment by iammattmartin** [comment]
Do you have a use case?

Is this to limit agents to only see departments they are assigned to? or something more specific?

**Comment by pranavrajs** [comment]
@josep112 If I understand this correctly, you want the agents to see only the conversation they are assigned to, right? They shouldn't see anything else. If that is the case then #2443 should cover those, we can close this ticket.

**Comment by josep112** [comment]
@pranavrajs I looked for how to make a new type of participant user role but I didn't find this role in the agents I have only administrator and agent, where is this so I can test it?

**Comment by iammattmartin** [comment]
It's only an idea currently, not implemented. Would monitor #2443 and once complete, you should be able to do what you want.

**Comment by pranavrajs** [comment]
Closing this as it is a similar to #2443.
