### ISSUE TITLE
Error using PlatformAppApiKey

### ISSUE THREAD

**Issue by drivasintelnexo** [chatwoot/chatwoot#2548]
**Describe the bug**

**To Reproduce**

1. I generate following the instructions here: [](https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Platform-APIs)
2. Create my Platform App
3. receive the token in rails console
4. when i invoke platforms endpoints in postman to make tests using in headers the PlatformAppApiKey i received { "error": "non permissible resource"}

**Expected behavior**

I expected to receive a successfully response to the request

**Environment**
 I'm using a Linux VM selfhosted environment

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [POSTMAN]

**Comment by drivasintelnexo** [comment]
I was mistake in url params id in some endpoints with get request to platform api endpoints.

**Comment by nguyenhuuloc304** [comment]
I encountered the same issue even I checked endpoint correctly. I am using docker env. 

Hi @drivasintelnexo Could you help to take a look and advise what I am wrong? Thank you.

![image](https://user-images.githubusercontent.com/21157325/154798626-0dd3ae80-ff81-4325-9ac1-2701296bf216.png)
![image](https://user-images.githubusercontent.com/21157325/154798644-b3090d76-b13f-4fdd-a9b6-15925ffb9b09.png)

**Comment by sojan-official** [comment]
@nguyenhuuloc304 platform apps have access only to the resources it create. I guess account 1 might not have been created by your platform app. 


you can run this script to add permissions for platform apps on objects which weren't created by the platform app 

run the following in a rails console in your chatwoot installation 
```
# replace the number 1 with appropriate ids for platform app and account
PlatformAppPermissible.create!(platform_app: PlatformApp.find(1), permissible: Account.find(1))
```

**Comment by nguyenhuuloc304** [comment]
Hi @sojan-official 
Thank you so much for your explanation. Then I am trying to create new account using platformAppApiKey, However, I faced another issue as below. Could you help me advice how to fix it? Thank you.

![image](https://user-images.githubusercontent.com/21157325/155059105-42985c19-7ce8-49b9-8755-69d0cfc0b9b2.png)
