### ISSUE TITLE
Replace the Twilio inbox channel with two new easier to understand SMS & Whatsapp channel

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2550]
**Is your enhancement request related to a problem? Please describe.**
Twilio as a channel can sound confusing to some users. So, how about removing the Twilio icon/channel and putting up 2 new ones called SMS and Whatsapp?

Will you accept a PR for this specific request?

**Describe the solution you'd like**
Update Twilio channel by replacing it with SMS and Whatsapp channel in the /inboxes page.

**Describe alternatives you've considered**
N/A

**Additional context**
![imageedit_6_6190391977](https://user-images.githubusercontent.com/8149408/124126823-adc22c80-da98-11eb-9e5b-2593efd4449b.png)

**Comment by pranavrajs** [comment]
@srameshr Yes, this makes sense. `SMS via Twilio`, `Whatsapp via Twillio` seems alright.

**Comment by kemilioo** [comment]
Hi @pranavrajs , i just hosted chatwoot in my local. Currently I having a difficulties in connecting chatwoot to the whatsapp business. Could you explain more on this?

**Comment by sojan-official** [comment]
@kemilioo  We don't support the business API directly yet. you will need to obtain a WhatsApp number via Twilio before you can connect it. 

ref : https://www.chatwoot.com/docs/product/channels/twilio-whatsapp-sms

**Comment by kemilioo** [comment]
@sojan-official , Thanks for the respond. Now I understood on how to connect them.

**Comment by srameshr** [comment]
@sojan-official @pranavrajs 

![Screenshot 2021-07-05 at 3 40 44 PM](https://user-images.githubusercontent.com/8149408/124462967-d5263b80-ddaf-11eb-8462-5caf79abf249.png)
![Screenshot 2021-07-05 at 3 41 35 PM](https://user-images.githubusercontent.com/8149408/124462980-d9525900-ddaf-11eb-88a8-c01d8c4093c6.png)
![Screenshot 2021-07-05 at 3 42 15 PM](https://user-images.githubusercontent.com/8149408/124463004-e3745780-ddaf-11eb-83da-de88c89846a4.png)

PR here: https://github.com/chatwoot/chatwoot/pull/2566

I have not deleted the Twilio related files but kept it there with a deprecation warning and I've not tried to make SMS and Whatsapp files as a common configurable component because in the future apart from Twilio is any new provider is integrated the form fields may vary from provider to provider for both SMS and Whatsapp channel

**Comment by srameshr** [comment]
Also, going further when Chatwoot supports new providers apart from Whatsapp & SMS via Twilio, we could provide a select box within each channel as a configurable option that loads appropriate form fields that the provider needs.

**Comment by pranavrajs** [comment]
@srameshr Sounds good. We will get the review done soon.
