### ISSUE TITLE
postgres:5432 - no response

### ISSUE THREAD

**Issue by kemilioo** [chatwoot/chatwoot#2559]
**Describe the bug**

Keep getting this error when trying to run  ```bundle exec rails db:chatwoot_prepare```

```bash
Starting redis-chat ... done
Starting postgres-chat ... done
Creating chatwoot_ror_run ... done
+ rm -rf /app/tmp/pids/server.pid
+ rm -rf /app/tmp/cache/assets /app/tmp/cache/bootsnap-compile-cache /app/tmp/cache/bootsnap-load-path-cache /app/tmp/cache/webpacker
+ echo 'Waiting for postgres to become ready....'
Waiting for postgres to become ready....
+ docker/entrypoints/helpers/pg_database_url.sh
+ export 'POSTGRES_PORT=5432'
+ PG_READY='pg_isready -h postgres -p 5432 -U chat_admin'
+ pg_isready -h postgres -p 5432 -U chat_admin
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U chat_admin
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U chat_admin
postgres:5432 - no response
+ sleep 2
+ pg_isready -h postgres -p 5432 -U chat_admin
postgres:5432 - no response
+ sleep 2
```

**To Reproduce**

1. docker-compose up -d
2. docker-compose run --rm rails bundle exec rails db:chatwoot_prepare

![image](https://user-images.githubusercontent.com/81754437/124373675-eb0c0180-dcc6-11eb-9f06-4f01950b2dff.png)

**Comment by thundersparkf** [comment]
Have you tried to exec into the container after the first step?

```docker exec -it <container-name>  bash```

And then
``` psql -h postgres -p 5432 -U chat_admin```

If not, I think that maybe the issue. Try with ```-U chatwoot```

**Comment by kemilioo** [comment]
Thanks for the respond, now its working !

---
### Steps of Troubleshooting

I have fixed this issue, but not sure which process that success. 

1. I gave DB permission to the new user [Step 1-6] > https://tableplus.com/blog/2018/04/postgresql-how-to-grant-access-to-users.html
2. Change new password inside ```.env``` and ```docker-compose.yml```. Both passwords need to be the same
3. Then I restarted the container

---
### Result

![image](https://user-images.githubusercontent.com/81754437/124407776-501f3000-dd77-11eb-97e9-6eee84f03ad6.png)

**Comment by jose632silva** [comment]
How to access the database?
Please!
