### ISSUE TITLE
Facebook Chat messages customer name is set as "John Doe"

### ISSUE THREAD

**Issue by bytefact** [chatwoot/chatwoot#2560]
**Describe the bug**

On Facebook messenger Live mode, Facebook contact names are not setting correctly. Contact names are set as "John Doe".
But If resolving correct names for Facebook app admin.

**To Reproduce**
1. Chatwoot is runnnig on production environment.
2. Configured 2 facebook pages as external Channel.
3. Created a facebook app for messenger platform, sent review request to facebook and facebook approved it.
4. When facebook app admin sends message to facebook page, chatwoot resolves sender name correctly.
5. But when facebook page customers are sending message to facebook page, chatwoot shows sender name as "John Doe"

**Expected behavior**
Chatwoot should resolve contact names correctly for Facebook pages message request.

**Screenshots**
![image](https://user-images.githubusercontent.com/12614867/124385502-c4b28a00-dcf7-11eb-90ca-51a10b8b93bc.png)

**Logs
journalctl -u chatwoot-worker.1.service -f
`
Jul 04 12:32:06 chat chatwoot-worker.1[79254]: I, [2021-07-04T12:32:06.323912 #79254]  INFO -- : [ActiveJob] [ActionCableBroadcastJob] [7a4ea4a6-31d8-492e-935f-e348215df93e] Performing ActionCableBroadcastJob (Job ID: 7a4ea4a6-31d8-492e-935f-e348215df93e) from Sidekiq(default) enqueued at 2021-07-04T12:32:06Z with arguments: ["XKmaLssuHgBxWagVJ7pM3gcw"], "conversation.read", {:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::FacebookPage", :id=>582, :inbox_id=>7, :contact_inbox=>#<GlobalID:0x0000558cec95b798 @uri=#<URI::GID gid://chatwoot/ContactInbox/37350>>, :messages=>[{"id"=>4230, "content"=>"amra try korbo bole dite", "account_id"=>1, "inbox_id"=>7, :conversation_id=>582, :message_type=>1, :created_at=>1625401925, "updated_at"=>Sun, 04 Jul 2021 12:32:05 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>"m_iynabcc_Akb8xuwUOJK2Hu72QjckOkdMQKic19GgY-9XilfCVaLFSRlN8BN6AJqeAXqlBg1ULWny827kyzPTiQ", "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>nil, "sender_id"=>nil, "external_source_ids"=>{}}], :meta=>{:sender=>{:additional_attributes=>{}, :email=>nil, :id=>37349, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"dRVyDNJtmoztKCRonTZ7R14A", :thumbnail=>"", :type=>"contact"}, :assignee=>{:id=>43, :name=>"Naznin Islam", :available_name=>"naznin", :avatar_url=>"https://chat.shajgoj.com/rails/active_storage/representations/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBEdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1306a694436b7ae7f084faf0bd679f7a5a5a451b/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCam9MY21WemFYcGxTU0lNTWpVd2VESTFNQVk2QmtWVSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--dd90c54d9d71b5fedae01dba81a6bbcbb5147e6c/199359059_541762426825010_7550110023872735396_n.jpg", :type=>"user", :availability_status=>"online"}}, :status=>"open", :unread_count=>3, :agent_last_seen_at=>0, :contact_last_seen_at=>1625401925, :timestamp=>1625401925, :account_id=>1}
`

journalctl -u chatwoot-web.1.service -f
`
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.252103 #79135]  INFO -- : RoomChannel is streaming from WqxKF8aF7ULTk57ZuHcfbpFg
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.255204 #79135]  INFO -- : RoomChannel is transmitting the subscription confirmation
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.322900 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ContactAvatarJob (Job ID: 6c55b730-037b-4c9e-b24f-ca92c1d08776) to Sidekiq(default) with arguments: #<GlobalID:0x00007fc7a82c6380 @uri=#<URI::GID gid://chatwoot/Contact/41104>>, ""
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.347032 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: bd7355f7-aea2-4dac-bf6f-e4d4bd3a2b7d) to Sidekiq(default) with arguments: ["XKmaLssuHgBxWagVJ7pM3gcw"], "assignee.changed", {:additional_attributes=>{}, :can_reply=>false, :channel=>"Channel::FacebookPage", :id=>nil, :inbox_id=>7, :contact_inbox=>#<GlobalID:0x00007fc7903accd0 @uri=#<URI::GID gid://chatwoot/ContactInbox/41104>>, :messages=>[], :meta=>{:sender=>{:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact"}, :assignee=>{:id=>1, :name=>"Mesba ul Alam", :available_name=>"Mesba ul Alam", :avatar_url=>"https://www.gravatar.com/avatar/8b94390caf81861b33a4daf183929423?d=404", :type=>"user", :availability_status=>"online"}}, :status=>"open", :unread_count=>0, :agent_last_seen_at=>0, :contact_last_seen_at=>0, :timestamp=>0, :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.354162 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued EventDispatcherJob (Job ID: 338ce317-35c4-4098-9628-6f4f8c6e0488) to Sidekiq(events) with arguments: "assignee.changed", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:conversation=>#<GlobalID:0x00007fc7a82ae550 @uri=#<URI::GID gid://chatwoot/Conversation/1195>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.364797 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: de1b6189-a726-4e3c-b095-1f978bb9dd44) to Sidekiq(default) with arguments: ["w4hn3HCopjEkqjiJuLcu7M6R", "Jg22CNm6siKKgcswyjEAAFUd", "66czoSZXNNKSQ5PKdCPVmNAE", "gRV4V22uzDnEHuaRtZva4W7a", "Jvk9vvoExtLkZPyJAz4HLWa1", "CczLBfPZi8E38o5W3h5DnJic", "h9XEm5bQQkRsEQcbDV2162b5", "nCMDw1vEmz1BDk89Yzg2hnET", "XKmaLssuHgBxWagVJ7pM3gcw"], "contact.created", {:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact", :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.369758 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued EventDispatcherJob (Job ID: eeec318a-58a6-4377-b72a-0d2b9bc9e4c9) to Sidekiq(events) with arguments: "contact.created", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:contact=>#<GlobalID:0x00007fc7b077c610 @uri=#<URI::GID gid://chatwoot/Contact/41104>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.387246 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: cc804a08-bac9-4219-bdb2-19a5213478f0) to Sidekiq(default) with arguments: ["XKmaLssuHgBxWagVJ7pM3gcw"], "conversation.created", {:additional_attributes=>{}, :can_reply=>true, :channel=>"Channel::FacebookPage", :id=>1195, :inbox_id=>7, :contact_inbox=>#<GlobalID:0x00007fc7903f3bf8 @uri=#<URI::GID gid://chatwoot/ContactInbox/41104>>, :messages=>[{"id"=>4744, "content"=>"Hlw", "account_id"=>1, "inbox_id"=>7, "conversation_id"=>1195, "message_type"=>"incoming", "created_at"=>Sun, 04 Jul 2021 12:45:28 UTC +00:00, "updated_at"=>Sun, 04 Jul 2021 12:45:28 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>"m_DYAyyUSYTbQzm6fgL3UjJgXd6GkVm6ONk5ki2YUvpJ7Vp6c7VIRQcAOfNXvv9uscj6L8R4UaqlGNHgOwSHFU9g", "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>41104, "external_source_ids"=>{}, :created_at=>1625402728, :message_type=>0, :conversation_id=>1195, :sender=>{:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact"}}], :meta=>{:sender=>{:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact"}, :assignee=>{:id=>1, :name=>"Mesba ul Alam", :available_name=>"Mesba ul Alam", :avatar_url=>"https://www.gravatar.com/avatar/8b94390caf81861b33a4daf183929423?d=404", :type=>"user", :availability_status=>"online"}}, :status=>"open", :unread_count=>1, :agent_last_seen_at=>0, :contact_last_seen_at=>0, :timestamp=>1625402727, :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.391982 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued EventDispatcherJob (Job ID: a28b0451-4966-48bc-b0d2-146883b0caf0) to Sidekiq(events) with arguments: "conversation.created", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:conversation=>#<GlobalID:0x00007fc7a827acf0 @uri=#<URI::GID gid://chatwoot/Conversation/1195>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.393541 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued Notification::PushNotificationJob (Job ID: bb324876-3a52-4fb3-a76e-bc28e68da546) to Sidekiq(default) with arguments: #<GlobalID:0x00007fc79c246a10 @uri=#<URI::GID gid://chatwoot/Notification/1196>>
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.396498 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued Notification::EmailNotificationJob (Job ID: 8be62f11-9892-4937-adc3-c61868722cd5) to Sidekiq(default) with arguments: #<GlobalID:0x00007fc7a82760d8 @uri=#<URI::GID gid://chatwoot/Notification/1196>>
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.406408 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: 637ca991-630b-4127-b92c-1703a16c18d7) to Sidekiq(default) with arguments: ["XKmaLssuHgBxWagVJ7pM3gcw", "zuvoK3uGtkNLPjQhE6o5rjru"], "message.created", {"id"=>4744, "content"=>"Hlw", "account_id"=>1, "inbox_id"=>7, "conversation_id"=>1195, "message_type"=>"incoming", "created_at"=>Sun, 04 Jul 2021 12:45:28 UTC +00:00, "updated_at"=>Sun, 04 Jul 2021 12:45:28 UTC +00:00, "private"=>false, "status"=>"sent", "source_id"=>"m_DYAyyUSYTbQzm6fgL3UjJgXd6GkVm6ONk5ki2YUvpJ7Vp6c7VIRQcAOfNXvv9uscj6L8R4UaqlGNHgOwSHFU9g", "content_type"=>"text", "content_attributes"=>{}, "sender_type"=>"Contact", "sender_id"=>41104, "external_source_ids"=>{}, :created_at=>1625402728, :message_type=>0, :conversation_id=>1195, :sender=>{:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact"}, :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.413931 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued EventDispatcherJob (Job ID: dee1051d-abad-4360-bbba-2c78e542c5fa) to Sidekiq(events) with arguments: "message.created", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:message=>#<GlobalID:0x00007fc7bc834308 @uri=#<URI::GID gid://chatwoot/Message/4744>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.414953 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued SendReplyJob (Job ID: 7f662492-e89d-49b6-aecd-cb78149ec81b) to Sidekiq(high) with arguments: 4744
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.418463 #79135]  INFO -- : RoomChannel is streaming from 2i7L3LzmH4Pq6A4ZCs2bwPC8
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.428852 #79135]  INFO -- : RoomChannel is transmitting the subscription confirmation
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.434229 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498] Started GET "/widget?website_token=[FILTERED]" for 103.158.62.18 at 2021-07-04 12:45:28 +0000
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.435962 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498] Processing by WidgetsController#show as HTML
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.436027 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498]   Parameters: {"website_token"=>"[FILTERED]"}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.437527 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: e557c105-b285-4ee4-a21d-b4e5d70c4a32) to Sidekiq(default) with arguments: ["w4hn3HCopjEkqjiJuLcu7M6R", "Jg22CNm6siKKgcswyjEAAFUd", "66czoSZXNNKSQ5PKdCPVmNAE", "gRV4V22uzDnEHuaRtZva4W7a", "Jvk9vvoExtLkZPyJAz4HLWa1", "CczLBfPZi8E38o5W3h5DnJic", "h9XEm5bQQkRsEQcbDV2162b5", "nCMDw1vEmz1BDk89Yzg2hnET", "XKmaLssuHgBxWagVJ7pM3gcw"], "contact.updated", {:additional_attributes=>{}, :email=>nil, :id=>41104, :identifier=>nil, :name=>"John Doe", :phone_number=>nil, :pubsub_token=>"zuvoK3uGtkNLPjQhE6o5rjru", :thumbnail=>"", :type=>"contact", :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.440210 #79135]  INFO -- : [b11323da-b667-4bbd-a7bd-67988e5141be] [ActiveJob] Enqueued EventDispatcherJob (Job ID: dbf5208a-09d6-470c-9606-adc4fbd07bb6) to Sidekiq(events) with arguments: "contact.updated", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:contact=>#<GlobalID:0x00007fc790304fa8 @uri=#<URI::GID gid://chatwoot/Contact/41104>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.463282 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: 2f7cccd4-bfe7-4a25-866d-5d387ad4bf46) to Sidekiq(default) with arguments: ["w4hn3HCopjEkqjiJuLcu7M6R", "Jg22CNm6siKKgcswyjEAAFUd", "66czoSZXNNKSQ5PKdCPVmNAE", "gRV4V22uzDnEHuaRtZva4W7a", "Jvk9vvoExtLkZPyJAz4HLWa1", "CczLBfPZi8E38o5W3h5DnJic", "h9XEm5bQQkRsEQcbDV2162b5", "nCMDw1vEmz1BDk89Yzg2hnET", "XKmaLssuHgBxWagVJ7pM3gcw"], "contact.created", {:additional_attributes=>{}, :email=>nil, :id=>41105, :identifier=>nil, :name=>"restless-fog-519", :phone_number=>nil, :pubsub_token=>"MaYUq9HzZQqfc7ra7TwifM98", :thumbnail=>"", :type=>"contact", :account_id=>1}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.464275 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498] [ActiveJob] Enqueued EventDispatcherJob (Job ID: e1aa4cb5-50de-445d-89f1-8deb3aca8342) to Sidekiq(events) with arguments: "contact.created", Sun, 04 Jul 2021 12:45:28 UTC +00:00, {:contact=>#<GlobalID:0x00007fc7a823e2c8 @uri=#<URI::GID gid://chatwoot/Contact/41105>>}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.465746 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498]   Rendering widgets/show.html.erb
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.478354 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498]   Rendered widgets/show.html.erb (Duration: 12.5ms | Allocations: 5497)
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.478715 #79135]  INFO -- : [835599af-5c3e-4a9d-8a24-8cb1e664e498] Completed 200 OK in 43ms (Views: 8.4ms | ActiveRecord: 12.1ms | Allocations: 13746)
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.532741 #79135]  INFO -- : [2fa2f82b-6bdd-42fa-b1ca-eb58cc23b9ef] Started GET "/api/v1/accounts/1/conversations/meta?inbox_id=7&status=open&assignee_type=me" for 103.117.194.242 at 2021-07-04 12:45:28 +0000
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.533793 #79135]  INFO -- : [2fa2f82b-6bdd-42fa-b1ca-eb58cc23b9ef] Processing by Api::V1::Accounts::ConversationsController#meta as JSON
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.533847 #79135]  INFO -- : [2fa2f82b-6bdd-42fa-b1ca-eb58cc23b9ef]   Parameters: {"inbox_id"=>"7", "status"=>"open", "assignee_type"=>"me", "account_id"=>"1"}
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.538529 #79135]  INFO -- : [7e1c6450-89e1-4721-976f-421c756ac80b] Started GET "/api/v1/accounts/1/conversations/meta?status=open&assignee_type=me" for 103.117.194.242 at 2021-07-04 12:45:28 +0000
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.539460 #79135]  INFO -- : [7e1c6450-89e1-4721-976f-421c756ac80b] Processing by Api::V1::Accounts::ConversationsController#meta as JSON
Jul 04 12:45:28 chat chatwoot-web.1[79135]: I, [2021-07-04T12:45:28.539530 #79135]  INFO -- : [7e1c6450-89e1-4721-976f-421c756ac80b]   Parameters: {"status"=>"open", "assignee_type"=>"me", "account_id"=>"1"}
`

**Environment**
Linux VM

**Comment by pranavrajs** [comment]
@bytefact This is happening because your app is not approved yet or there is a permission issue in the Facebook developer app.
