### ISSUE TITLE
Conversation closing (web widget)

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#2564]
**Is your feature request related to a problem? Please describe.**
The primary use I have for Chatwoot is to use the chat widget to communicate with programmed flows in our custom backend through the use of all the callbacks and APIs that are available. As such, when a user clicks the chat button an event `webwidget_triggered` is sent to the backend. This is seen as a "create a new flow and start it" trigger and will in turn send a message back to the customer, starting the rest of the flow. Later on, the flow will end and the user should see that they can no longer send messages and that the conversation has ended.

**Describe the solution you'd like**
An API endpoint to close a conversation, that is also visible to the customer the chat widget. It should make sure that when you close a conversation, the next time a user opens the chat window, `webwidget_triggered` is triggered again.

An example of a "closed" chat session on another chat widget from another company:
![image](https://user-images.githubusercontent.com/7480592/124440727-38e24180-dd7b-11eb-82ad-277617b02edb.png)

**Describe alternatives you've considered**
1. **Always call `window.$chatwoot.reset();` in the widget itself on client side when it's loading**: This has the downside that it's always a new user. No visibility of returning customers. Also no persistence over page refreshes if desired.
2. **Create a new conversation with the user**: While this does clear all messages (on page refresh), it will not prevent the user from typing new messages, and I fear what a new conversation might look like in the agent dashboard.
3. **A custom endpoint in our own backend that is called alongside the widget during load to check if we need to reset**: This is a possible workaround for us if we can't get a proper API endpoint and if we have access to the source ID in JavaScript.

**Comment by pranavrajs** [comment]
@brentco Can you please try the latest develop image where we have enabled the CSAT surveys? With this option, you would be able to achieve the issue which you have mentioned. The user would not be able to create further messages.

**Comment by brentco** [comment]
I'm sorry @pranavrajs I haven't had the time yet to try out the develop image!

**Comment by brentco** [comment]
@pranavrajs I've upgraded our staging environment with the new version (v1.18.1) and I'm trying out the CSAT feature. It does indeed work as desired, except for one thing. Is it possible to automatically trigger a new conversation when the user reopens the chat widget (for example on the next page visit)? If not, is it possible to have the user not have to send a message to reopen a conversation?

**Comment by sojan-official** [comment]
@brentco You could create a new conversation for the user through API once the CSAT survey is submitted ( You can listen to the webhook `message_updated` event for input_csat message types )

if the user refreshes the page, chatwoot will pick up the new conversation which was created through the API

**Comment by pranavrajs** [comment]
@brentco Closing this conversation in favour of #2830
