### ISSUE TITLE
PLATFORM API ACCOUNT_ID RETURN NULL

### ISSUE THREAD

**Issue by djra26111990** [chatwoot/chatwoot#2568]
**Describe the bug**

I was trying to create an account, user account and users with the new Platform API. 

I send the name account in a  POST request to /platform/api/v1/accounts using the PlatformAppApiKey, 

I use the id in the response to create the account user, and finish to create the user, pass one POST Request to platform/api/v1/users with 
{
"name": "userName",
"email": "UserEmail",
"password": "UserPassword"
}

And the json response return the account_id: NULL 

so, when i try to use the SSO get endpoint to login that user the dashboard stay white without render nothing.

**Expected behavior**
Enter the dashboard like the user agent profile accounts made with Email invitations 
associate with an unique account number using the Platform API.

**Environment**

Self hosted Chatwoot v.1.17.1
Ubuntu Server 20.04 LTS 

**Desktop (please complete the following information):**
All test to platform endpoints was made with Postman.

**Comment by sojan-official** [comment]
@djra26111990  You will need to create an account_user association after creating the user before they can log in to the dashboard. 

https://www.chatwoot.com/developers/api#tag/Account-Users

**Comment by djra26111990** [comment]
@sojan-official But, in this order i need to consume the platform API endpoints? 

First. Accounts
Second. Accounts_Users to give the new account_users role and associate with their account_id, right?
Third. Users with their name, email and password? 

There is one question. I can associate multiple account_users to one account_id ? Like creating agents on the frontend side with email invitation?

**Comment by sojan-official** [comment]
> @sojan-official But, in this order i need to consume the platform API endpoints?
> 
> First. Accounts
> Second. Accounts_Users to give the new account_users role and associate with their account_id, right?
> Third. Users with their name, email and password?
> 
> There is one question. I can associate multiple account_users to one account_id ? Like creating agents on the frontend side with email invitation?

That is correct. you can refer for an overview : https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Platform-APIs

**Comment by djra26111990** [comment]
I've follow the steps in the refer link that you post it here bro @sojan-official thanks for your help! it worked!

**Comment by djra26111990** [comment]
i'm going to close the thread
