### ISSUE TITLE
Webhooks - incoming?

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#2572]
**Is your enhancement request related to a problem? Please describe.**

I cant find documentation for incoming Webhooks.

I can see the "message created" webhook (https://www.chatwoot.com/docs/product/features/webhooks) but cannot find any information about incoming webhooks?

**Describe the solution you'd like**
I would like to be able to send information to Chatwoot (like an answer) via Webhook. So reply to a message from outside Chatwoot.

**Describe alternatives you've considered**
If there is no Webhook, could this be done in a simple way via API?

**Additional context**
n/a

**Comment by sojan-official** [comment]
@brundles for sending information to chatwoot you can use our REST APIs https://www.chatwoot.com/developers/api

**Comment by brundles** [comment]
Hi @sojan-official - thank you for the quick reply. So no incoming webhooks yet, correct?

Thanks

**Comment by sojan-official** [comment]
> Hi @sojan-official - thank you for the quick reply. So no incoming webhooks yet, correct?
> 
> Thanks

That is correct. At the moment, we don't have plans for incoming webhooks.

**Comment by pranavrajs** [comment]
Closing as this is more of a question rather than a feature. Please feel free to reopen if needed.
