### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2595]
https://sentry.io/share/issue/579a99050bc84a24b92ef6f31ece11fb/

**Comment by SanjuSudheerM** [comment]
@muhsin-k Can I work on this?

**Comment by SanjuSudheerM** [comment]
#2702

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/pull/2702
