### ISSUE TITLE
Website Widget pop up on page load event

### ISSUE THREAD

**Issue by hitesh240989** [chatwoot/chatwoot#2596]
Can you please help to enable the website widget to pop up as soon as any user will land on the home page? 

Currently, the user has to click the widget then only it will show but it's better if any user visiting the website it should pop up immediately on page load.

Please advise if we can have this enhancement.

Thanks in advance.

**Comment by muhsin-k** [comment]
@hitesh240989 You could use the `toggle` method for opening the widget. https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#trigger-widget-without-displaying-bubble

**Comment by hitesh240989** [comment]
> @hitesh240989 You could use the `toggle` method for opening the widget. https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#trigger-widget-without-displaying-bubble

Thank you @muhsin-k
