### ISSUE TITLE
Configure once click deploys with "Deploy to Heroku" button

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#260]
- [ ] Investigate the changes required for Heroku deployment
- [ ] Add app.json with sufficient information

**Comment by karthik-sivadas** [comment]
@pranavrajs I would like to take up this task. Had some confusion regarding the implementation as in should I create a script to deploy the app or wait till the docker task is completed. IMHO it would be better to use docker to deploy this in Heroku as it would avoid updating in two places for changes in deployment procedure.

**Comment by pranavrajs** [comment]
@karthik-sivadas I guess creating app.json schema should work for now. 
https://devcenter.heroku.com/articles/app-json-schema

I don't think this task has dependancy over docker image.

**Comment by sony-mathew** [comment]
I would like to help with this task as I have some prior context on this @pranavrajs @karthik-sivadas .

**Comment by sony-mathew** [comment]
I have started working on this.
