### ISSUE TITLE
Design: Buttons for actions like delete, close modal needs better styles

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2616]
- Unify the action buttons styles
- Add hover effects

![image](https://user-images.githubusercontent.com/1277421/125425116-be12fed0-cf27-4dd6-9b75-9505ba8b69d9.png)

**Comment by khushi200701** [comment]
Hey, I'm interested in working on this. Can you give more info?

**Comment by nithindavid** [comment]
hello @khushi200701, Sorry this issue is actually completed and we did not update the status.

Let me know what kind of tickets on design would suit you, So I'll ping you on them if I find some tickets in that area.

**Comment by pranavrajs** [comment]
Closing this as the button is removed and doesn't exist anymore in the platform.
