### ISSUE TITLE
As an agent I would like to be able to answer from my smartphone

### ISSUE THREAD

**Issue by Brokray** [chatwoot/chatwoot#2617]
First of all, I am sorry if this demand as already been made, I did not found anything about it.
Second, you are really doing an amazing job with Chatwoot! :)

**Is your enhancement request related to a problem? Please describe.**
The Chatwoot UI is not properly responsive, using a phone to answer to users is rather difficult.

**Describe the solution you'd like**
Make the interface responsive enough to be usable.    
At the moment the main menu is perfectly responsive (turns into a burger menu).     
Maybe we could add the same behaviour to the **conversations list** this way it makes enough room for the actual conversation ?

**Describe alternatives you've considered**
Not much to be fair...

**Comment by sojan-official** [comment]
@Brokray  We have ios and android apps available. 

https://apps.apple.com/app/id1495796682
https://play.google.com/store/apps/details?id=com.chatwoot.app&hl=en

**Comment by pranavrajs** [comment]
At the moment, we don't plan to support the web on mobile devices. This could be a future enhancement. Closing this as the mobile apps are available.

**Comment by Brokray** [comment]
@sojan-official @pranavrajs 
Definitely! However, I forgot a huge detail in my request.  

My request came from agents that are using a **self-deployed Chatwoot**.     

Is there any easy way to use a self-deployed architecture on mobile at the moment? If not, do you plan to support it?

**Comment by Brokray** [comment]
Thank you guys, I did not notice you could specify a self-hosted address on your mobile app.    
Great job again ! 👌
