### ISSUE TITLE
Two access tokens created for each new user

### ISSUE THREAD

**Issue by DevS1993** [chatwoot/chatwoot#2620]
**Describe the bug**

When a new user is created, a single access token should be created.

**To Reproduce**

```
# app/models/user.rb:88
after_create_commit :create_access_token
```
```
# app/models/concerns/access_tokenable.rb:5
after_create :create_access_token
```

**Expected behavior**

One access token should be created when a user is created.

**Screenshots**

![image](https://user-images.githubusercontent.com/21246070/125548307-ab3e39ba-e0f4-45c1-acda-9f811748738b.png)

**Comment by pranavrajs** [comment]
@DevS1993 Thanks for reporting this. 👍
