### ISSUE TITLE
Install linters locally

### ISSUE THREAD

**Issue by gruz0** [chatwoot/chatwoot#264]
Hey!

I want to add some useful tools like `Makefile` to install linters locally to prevent sending invalid commits to the repo by running all linters locally.

How it may looks like:

1. I've [bin/install_linters_dependencies.sh](https://github.com/gruz0/inspirer-web/blob/master/bin/install_linters_dependencies.sh)
2. Then create a `Makefile` with target `install_linters` (https://github.com/gruz0/inspirer-web/blob/master/Makefile)
3. It adds Git's `pre-commit` hook like this: https://github.com/gruz0/inspirer-web/blob/master/bin/pre-commit

What will it do for us? The same code for all contributors :-)

**Comment by sojan-official** [comment]
@pranavrajs  thoughts ?

**Comment by pranavrajs** [comment]
@gruz0 We used `lint-staged` package to manage pre-commit hooks. We have `eslint` running on commit. I guess PR #283 should fix the issue. Please let me know if you have any additional thoughts.

**Comment by gruz0** [comment]
Ok.
