### ISSUE TITLE
Bundle Command Finsihes with Error

### ISSUE THREAD

**Issue by Suleman-Elahi** [chatwoot/chatwoot#265]
Platform : Linux
Ruby Version: 2.6.5p114
Gem Version: 3.0.3
running `bundle` command after `yarn install` throws the following error.

![image](https://user-images.githubusercontent.com/24384996/69404625-be8ab800-0d23-11ea-97f2-3fbe554504d9.png)

**Comment by sojan-official** [comment]
@Suleman-Elahi  could you run the command `gem install nokogiri -v '1.10.5' and give us the output if it's erroring out? 

if it succeeds, please proceed from the step `bundle` again.

**Comment by Suleman-Elahi** [comment]
```
(base) inklik@inklik-LIFEBOOK-A555:~/t/chatwoot$ gem install nokogiri -v '1.10.5'
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
	ERROR: Failed to build gem native extension.

    current directory: /home/inklik/.gem/gems/nokogiri-1.10.5/ext/nokogiri
/snap/bin/ruby -I /snap/ruby/160/lib/ruby/2.6.0 -r ./siteconf20191122-23653-17927mg.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/snap/ruby/160/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/inklik/.gem/extensions/x86_64-linux/2.6.0/nokogiri-1.10.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/inklik/.gem/gems/nokogiri-1.10.5 for inspection.
Results logged to /home/inklik/.gem/extensions/x86_64-linux/2.6.0/nokogiri-1.10.5/gem_make.out

```
mkmf.log file: https://paste.ee/p/PIMEB

**Comment by gruz0** [comment]
@Suleman-Elahi, try to install libxml2 first: `brew install libxml2`

**Comment by sojan-official** [comment]
@Suleman-Elahi  if you are on ubuntu/ other flavors of linux.  use the appropriate commands to install the packages @gruz0  suggested. 

```
sudo apt-get install zlib1g-dev
```

**Comment by Suleman-Elahi** [comment]
Thank you @sojan-official and @gruz0

That actually worked. I am using Enso OS. Now, I am having troubles with next command so I am finding it a bit hard to set this up on my own as I am not a Ruby expert. I'll wait until a Docker image is available or docker-compose.

![image](https://user-images.githubusercontent.com/24384996/69415046-e6851600-0d39-11ea-811c-b1845ee8d5b2.png)

**Comment by sojan-official** [comment]
@Suleman-Elahi  #270  is merged and you should be able to use docker for the set up now. 
Let us know if you face any issues.

**Comment by Suleman-Elahi** [comment]
At least there is still one issue....

![image](https://user-images.githubusercontent.com/24384996/69600398-74ad1500-1036-11ea-9a8b-afcbbe5294fb.png)

**Comment by sojan-official** [comment]
you have to run the following steps before doing `docker compose up`

```
docker volume create --name=postgres
docker volume create --name=redis
docker-compose build
```

please ref : http://localhost:8000/docs/quick-setup . [ Docker set up instructions ]

**Comment by Suleman-Elahi** [comment]
The `docker-compose` is now working. But can you tell me how I use it locally? I have changed localhost to my public IP after enabling port forwarding in router. I am able to access Chatwoot externally but the inbox script doesn't work after I add it to test HTML page. Also, the Facebook integration doesn't work; the loader keeps rotating.

![Screenshot_20191128_173218](https://user-images.githubusercontent.com/24384996/69804845-6fea8b80-1205-11ea-8a2f-90817986c835.png)

![image](https://user-images.githubusercontent.com/24384996/69805316-69a8df00-1206-11ea-9f36-02a0e0704747.png)

**Comment by sojan-official** [comment]
make sure you run the docker compose with RAILS_ENV variable set to development in docker compose file.

After you have the chatwoot app running, login using the credentials . `john@acme.inc` and password:  `123456` you can also open the window  localhost:3000/widget_tests  , this page will have the web widget running and you can test out the messaging via that. 

-----------------

looking at the current issues 
- we don't have documentation on setting up facebook. #39  . @pranavrajs  will be working on that 
- In test html i noticed that the webtoken for your sdk is 'undefined' that seems weird. you should copy paste the sdk code by loging in as admin, go to the settings -> inbox -> setting of your website inbox and 

if you are still facing issues, feel free to schedule a call and we will be glad to help 
https://calendly.com/chatwoot/
