### ISSUE TITLE
feat: CSAT response collection page

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2654]
To collect the CSAT response from all channels, we will be sending a link to the format. `<installation-url>/app/responses/<response-uuid>` to the contact once the conversation is resolved.

**Todo**:

- [ ] Create a responsive design to collect rating and feedback.
- [ ] Use the APIs from #2653 to find and submit the response.

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/2685
