### ISSUE TITLE
feat: Add action to snooze the conversation, filter snoozed conversations

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2657]
- Add buttons to "Snooze", "Snooze until"
    - Snooze - Default one day snooze.
    - Snooze until - Open a modal to choose the date.
    
- Add a view to see the snoozed conversations

**Comment by sojan-official** [comment]
We could give some defaults into the drop down for the items which are used often like 

- Snooze till later ( 4-5 hours )
- Snooze till tomorrow
- Snooze till next week
- Snooze till  ( custom date picker )

Since the interaction with date picker modal often takes multiple clicks

**Comment by sojan-official** [comment]
Some of the functionalities mentioned in this ticket is already covered in https://github.com/chatwoot/chatwoot/pull/2682 

What remains now is implementing the "custom" option to snooze menu group, along with a date picker

**Comment by pranavrajs** [comment]
Let us leave that for now.
