### ISSUE TITLE
feat: Standardize content editor

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2659]
- [ ] Fix rendering issues with `hard_break`.
- [ ] Support canned response everywhere even if the rich content editor is not enabled.

**Comment by sagararyal** [comment]
@pranavrajs when implemented does this solve an issue: 
where canned responses currently lose line breaks when updated.



https://user-images.githubusercontent.com/5401575/156614365-759a8e7b-81d4-4614-9068-6ff4d43fc536.mov

**Comment by pranavrajs** [comment]
@sagararyal We have not seen this issue so far, let me see if we can reproduce it.

**Comment by nithindavid** [comment]
Closing this as we have fixed both the mentioned issues in past releases.
