### ISSUE TITLE
[CW-2833] feat: Ability to suppress / Hide System Default Message on API

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2667]
### Discussed in [https://github.com/chatwoot/chatwoot/discussions/2628](https://github.com/chatwoot/chatwoot/discussions/2628)

<div type='discussions-op-text'>

<sup>Originally posted by **Stephen-Lobo** July 14, 2021</sup>
Is there any way to hide / not to display the default system messages when a new Conversation / Label / Message created via API ?

Maybe passing 'true/false' option in the API code.

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/26e12b1c-16e3-42a6-a39a-aade35e5de48/e01b7f9f-9251-42bd-bcee-c115541f4bb4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8yNmUxMmIxYy0xNmUzLTQyYTYtYTM5YS1hYWRlMzVlNWRlNDgvZTAxYjdmOWYtOTI1MS00MmJkLWJjZWUtYzExNTU0MWY0YmI0IiwiaWF0IjoxNzAxNDA4MDY5LCJleHAiOjE3MDE0OTQ0Njl9.0xBQ8o7HSpRKs2h29PWxSnU1LeeYEsr-wQLoVbelwcw)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2833](https://linear.app/chatwoot/issue/CW-2833/feat-ability-to-suppress-hide-system-default-message-on-api)</sub>

**Comment by pranavrajs** [comment]
Closing this here as the issue has not been picked up yet and there is no interaction from the community on it.
