### ISSUE TITLE
Deleting Whatsapp (Twilio) messages

### ISSUE THREAD

**Issue by pucilpet** [chatwoot/chatwoot#2691]
**Is your enhancement request related to a problem? Please describe.**
In the v.1.18 you added the ability to delete messages. For Twilio/Whatsapp the deletions are not respected.

**Describe the solution you'd like**
I would like to be able to redact/remove Whatsapp messages that are accidentally sent.

**Additional context**
I think the deletions can be done by updating the message body or by deleting the message resource. Needs further investigation.

https://www.twilio.com/docs/whatsapp/api/message-resource#update-a-message-resource

**Comment by pranavrajs** [comment]
@pucilpet The WhatsApp cloud API doesn't support WhatsApp message deletion. To keep it consistent across WhatsApp channel providers, we will not be supporting this.
