### ISSUE TITLE
SECURITY: empty identifier_hash allows impersonate any user

### ISSUE THREAD

**Issue by ayushin** [chatwoot/chatwoot#2694]
Hi,

I am trying to use /widget from a webview in a mobile app and would like to pass the user identity hmac.

I've noticed first of all that the documentation says identity_hash but it does not exist anywhere in the code. I found identifier_hash but passing it to the widget does not do anything either.

It would be great if it was possible to pass it along with &web_token to the /widget

**Comment by pranavrajs** [comment]
@ayushin Are you using the react-native SDK for the mobile apps?

**Comment by ayushin** [comment]
No, flutter and loading the widget in the webview

**Comment by ayushin** [comment]
I also noticed that it is possible to provide an arbitrary user email and name without any identity hash and the user will be displayed in chatwoot.

So any user can impersonate any other user.

**Comment by ayushin** [comment]
What happens?

setUser('any user id', email: 'impersonated@email.com', name: 'Impersonated User')

assigns the conversation to the impersonated@email.com user instead of creating a new contact

What you expect to happen?

Clearly mark verified and unverified contacts and do not allow overwriting contact details of identified users by unidentified users.

**Comment by ayushin** [comment]
This can be solved with https://github.com/chatwoot/chatwoot/issues/2745

**Comment by ayushin** [comment]
Duplicate of #2762
