### ISSUE TITLE
Javascript manipulation of incoming strings in agents side?

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#2718]
**Describe the solution you'd like**
I'm trying to add some Javascript to be fired upon incoming messages (wanting to manipulate the strings in the incoming messages).

As far as I can tell via Chromes network-inspector we get some nice JSON from /api/v1/accounts/1/conversations/1/update_last_seen each time a client writes.

How would I best catch this? Ie. where should I add my JS to manipulate this?

Thank you :)

**Comment by pranavrajs** [comment]
@brundles I don't understand the requirement here. Do you want to change the message displayed to the agent?

**Comment by brundles** [comment]
Hi @pranavrajs - yes, exactly. So on the agents side I'd like to change the contents of the message, to add some supporting information based on the content. By manipulating it on the agentside, it would not be visible for the user, only for the agent.

So basically I just want to intercept the messages in the browser before they're rendered for the agent.

**Comment by pranavrajs** [comment]
The ideal way to do this is to listen for the webhooks for `message:created` and add more context in a private note via the API. 

Closing this as it doesn't seem like bug or a feature that we can build.
