### ISSUE TITLE
Inbox Email Address is without a domain

### ISSUE THREAD

**Issue by semaf** [chatwoot/chatwoot#2722]
Hey,

I can not find where I should set the domain for the "Email Inbox" to get after setting up the correct email address?

At the moment is the email address listed like "f8873e1b603f241202f78e6ce30cb3e1@"

**Comment by iammattmartin** [comment]
Have you set `MAILER_INBOUND_EMAIL_DOMAIN` in the .env?

**Comment by semaf** [comment]
Yes did it

**Comment by pranavrajs** [comment]
@semaf It seems like the email documentation is not clear. We will add a video tutorial for the same in the coming weeks.

**Comment by semaf** [comment]
Reinstalled everything and now it has worked. But have another issue that the mails will not income to chatwoot as there is no any record at DNS.

**Comment by iammattmartin** [comment]
That is something you manage outside of Chatwoot and not something it provides.

**Comment by semaf** [comment]
You are right. Just missing documentation for it how to setup exim, postfix etc for chatwoot to catch emails with **reply+**

**Comment by iammattmartin** [comment]
Looks like this has been skipped in the guide at https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity.

I suspect it just needs the pipe location of where to send the email. Configuring the MTA will be down to you generally.

**Comment by semaf** [comment]
Thats also unclear.

https://github.com/chatwoot/chatwoot/issues/2712

**Comment by zbaloch** [comment]
Not able to setup email channel.

**Comment by hodl** [comment]
This is a nightmare. How the heck do you pipe into the actionmailer? Using bin/rails doesn't work. Using chatwoot/chatwoot/bin/rails doesn't work. Nothing seems to work.

**Comment by iammattmartin** [comment]
It is [pending](https://github.com/chatwoot/chatwoot/issues/2722#issuecomment-888926382) a guide. You'll need to wait for that or work it out yourself.

**Comment by hodl** [comment]
Maybe a hint please. I have been trying to work this out for months...

**Comment by iammattmartin** [comment]
Theres no "hint", we're waiting for a guide as yet unwritten.

**Comment by hodl** [comment]
Ah. I misunderstood your comment. Thanks.
When I try piping into action mailer either using this https://serverfault.com/questions/258469/how-to-configure-postfix-to-pipe-all-incoming-email-to-a-script or this technique https://stackoverflow.com/questions/58326314/postfix-setup-for-action-mailbox I get various different errors, but mostly I believe it is trying to use system ruby instead of the nvm managed one. Have you had similar experience?
