### ISSUE TITLE
feat: Add support for Line messenger

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2738]
Add a new channel type than support line messenger

ref: https://developers.line.biz/en/services/messaging-api/

**Comment by sojan-official** [comment]
@Brij2027 The issue intends to add support for line messenger in chatwoot so that a business can manage the customer communications in Line using chatwoot. 

If you were looking to contribute, We already have an internal effort going on for this. Let me know if you need help finding another issue.

**Comment by Brij2027** [comment]
Yes I'm looking for contribution but I'm a newbie so if you can provide me
with some simple issue to deal with that'll be great.Thanks in advance.

**Comment by sojan-official** [comment]
Remaining Tasks

- [ ] Add specs
- [ ] Test & Merge the PR
