### ISSUE TITLE
feat: Allow wildcard URL's for campaigns

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#2739]
**Is your feature request related to a problem? Please describe.**
Currently campaigns are running on specific URLs

**Describe the solution you'd like**
Single campaign can run on multiple URLs. For example:
https://www.bbc.com/sport/*

This could include something like the following where anything ending in chat on the domain will have the campaign running
https://www.bbc.com/*/chat

**Additional context**
Such a solution will reduce the effort required by the campaign creator when running it on multiple URLs

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/3192
