### ISSUE TITLE
Ability to pass the user information to chatwidget via parameters when initializing a widget.

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#274]
The js SDK should have the option to update the user information via API

- [ ]  ability to update user details on widget initialize 
- [ ]  ability to label the conversation through the js sdk
- [ ]  trigger chat window from anywhere

**Comment by vfasoulas** [comment]
please do not postpone again this feauture to next version

**Comment by pranavrajs** [comment]
@vfasoulas Nope, we are on it. 👍

**Comment by vfasoulas** [comment]
thanks
