### ISSUE TITLE
feat: Custom Fields in pre-chat form

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2744]
### Problem Statement

Right now, our pre-chat form only supports name, email and message. Adding more combinations of fields helps the customers in different business needs. So the customers can completely customize whatever details are required before starting a new conversation.

### Proposed solution

Add support for various combos, 

- [ ] Name and phone number
- [ ] Name, email, phone number
- [ ] Name, phone number, message

### Design Mocks

![Screenshot 2022-03-02 at 12 58 23 PM](https://user-images.githubusercontent.com/12408980/156314966-9307a813-e429-45c6-a167-e73b4f931345.png)
![Screenshot 2022-03-02 at 12 58 51 PM](https://user-images.githubusercontent.com/12408980/156314971-9a80c478-d6e6-4a42-9811-2492c3e1f231.png)
![Screenshot 2022-03-02 at 12 59 10 PM](https://user-images.githubusercontent.com/12408980/156314976-c1b7af7d-e03d-4ee0-9389-6b39c303ec9d.png)

_Originally posted by @tabrza in https://github.com/chatwoot/chatwoot/issues/1131#issuecomment-891577370_

**Comment by tejaswinichile** [comment]
MVP:

Add phone number as a custom attribute and show the checked custom attributes in widget pre-chat form, according to the enabled custom attribute.
