### ISSUE TITLE
JWT based customer identification

### ISSUE THREAD

**Issue by ayushin** [chatwoot/chatwoot#2745]
**Is your enhancement request related to a problem? Please describe.**

`https://app.chatwoot.com/widget` is an extremely useful tool for presenting chat widget in different situtions

Unfortunately it is impossible to pass a verified user identity to this url.
 
**Describe the solution you'd like**

I would like to be able to pass a JWT in the query string containing the user details signed with the inbox secret key.

**Describe alternatives you've considered**
Alternatively you could pass all separate parameters and and identifier hash, but this is a non-standard and more cumbersome approach.

**Additional context**
The idea comes from Tiledesk and it works really well:

https://developer.tiledesk.com/apis/authentication

**Comment by ayushin** [comment]
Is anybody still considering this?

**Comment by pranavrajs** [comment]
@ayushin We will not be picking this up. The URL is not designed to be used directly.
