### ISSUE TITLE
Custom SMTP server per user

### ISSUE THREAD

**Issue by raikasdev** [chatwoot/chatwoot#2748]
**Is your enhancement request related to a problem? Please describe.**
In customer perspective company's own SMTP server/domain in E-mails would look better.
So, allowing per user SMTP server, so custom SMTP can be set on SaaS and per user on self hosted.

**Describe the solution you'd like**
Add possibility to add custom SMTP settings for email channel.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by sojan-official** [comment]
This is something which we have in our pipeline. The ability to configure SMTP setting for each email inboxes.

**Comment by sojan-official** [comment]
SMTP configuration is now available for email inboxes 
https://github.com/chatwoot/chatwoot/pull/3298
