### ISSUE TITLE
Cant change the notification email address

### ISSUE THREAD

**Issue by diaspora-france** [chatwoot/chatwoot#2751]
**Describe the bug**

i did change the MAILER_SENDER_EMAIL value in .env but all emails sent to customers in notification go to accounts@chatwoot.com

**To Reproduce**

1. Send a message to the chat
2. reply when the custumer when he is offline
3. the notification is sent with the header : "Notifications from XXXX" <accounts@chatwoot.com>

**Expected behavior**

The custumer replies to the email but we dont received the answer

**Environment**

self hosted installation

**Comment by sojan-official** [comment]
@diaspora-france  did you restart the service after updating the environment variables?

**Comment by diaspora-france** [comment]
Hi,

and thank you for your responsiveness !

I did restart the service. 

All of my setup is working fine. When I create an agent account, the email goes with the address configured in MAILER_SENDER_EMAIL. It's only notifications to customers

**Comment by sojan-official** [comment]
We will take a look into this. 

Meanwhile, do you have conversation continuity enabled? https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity

**Comment by diaspora-france** [comment]
Thanks ! No, we didnt enabled the conversation continuity yet.

**Comment by diaspora-france** [comment]
Hi,

I did fix the issue by changing directly in DB the value of support_email in the account table

**Comment by sojan-official** [comment]
@diaspora-france  Thanks for reporting back.  You could also customize the support_email at a global level from the super admin panel. 

it's just that if a value is set on the account, it will take precedence over the global config. / environment variables 

<img width="1357" alt="Screenshot 2021-08-20 at 9 30 19 PM" src="https://user-images.githubusercontent.com/73185/130261174-799823d6-0f32-4703-8698-f4ca5adee6a5.png">
