### ISSUE TITLE
Replace the string "Chatwoot" with {installationName}

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2754]
**Is your enhancement request related to a problem? Please describe.**
Replacing the string Chatwoot throughout the app takes forever because it's hardcoded in over 900 files. 

**Describe the solution you'd like**
Replace string Chatwoot in translation and other JS and RB files with ```installationName``` variable that's provided via global config.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by pranavrajs** [comment]
This is not a focus area / a relevant effort for our roadmap. Closing this for now.
