### ISSUE TITLE
can't install ruby  - Ubuntu 20.04

### ISSUE THREAD

**Issue by abraham-azzam** [chatwoot/chatwoot#2766]
<pre><font color="#4E9A06"><b>abraham@abraham-virtual-machine</b></font>:<font color="#3465A4"><b>~</b></font>$ rvm install ruby-3.0.2
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/ubuntu/20.04/x86_64/ruby-3.0.2.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-3.0.2 - #configure
ruby-3.0.2 - #download
<font color="#C4A000">No checksum for downloaded archive, recording checksum in user configuration.</font>
/usr/share/rvm/scripts/functions/db: line 51: /usr/share/rvm/user/md5.new: Permission denied
mv: cannot stat &apos;/usr/share/rvm/user/md5.new&apos;: No such file or directory
/usr/share/rvm/scripts/functions/db: line 64: /usr/share/rvm/user/md5: Permission denied
/usr/share/rvm/scripts/functions/db: line 51: /usr/share/rvm/user/sha512.new: Permission denied
mv: cannot stat &apos;/usr/share/rvm/user/sha512.new&apos;: No such file or directory
/usr/share/rvm/scripts/functions/db: line 64: /usr/share/rvm/user/sha512: Permission denied
ruby-3.0.2 - #validate archive
ruby-3.0.2 - #extract
mkdir: cannot create directory ‘/usr/share/rvm/rubies/ruby-3.0.2’: Permission denied
mktemp: failed to create directory via template ‘/usr/share/rvm/tmp/rvm-tmp.XXXXXXXXX’: Permission denied
mkdir: cannot create directory ‘’: No such file or directory
tar: : Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
<font color="#CC0000">Unpacking bin-ruby-3.0.2.tar.bz2 failed.</font>
<font color="#C4A000">Mounting remote ruby failed with status 6, trying to compile.</font>
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/share/rvm/rubies/ruby-3.0.2, this may take a while depending on your cpu(s)...
ruby-3.0.2 - #downloading ruby-3.0.2, this may take a while depending on your connection...
<font color="#C4A000">No checksum for downloaded archive, recording checksum in user configuration.</font>
/usr/share/rvm/scripts/functions/db: line 51: /usr/share/rvm/user/md5.new: Permission denied
mv: cannot stat &apos;/usr/share/rvm/user/md5.new&apos;: No such file or directory
/usr/share/rvm/scripts/functions/db: line 64: /usr/share/rvm/user/md5: Permission denied
/usr/share/rvm/scripts/functions/db: line 51: /usr/share/rvm/user/sha512.new: Permission denied
mv: cannot stat &apos;/usr/share/rvm/user/sha512.new&apos;: No such file or directory
/usr/share/rvm/scripts/functions/db: line 64: /usr/share/rvm/user/sha512: Permission denied
mkdir: cannot create directory ‘/usr/share/rvm/tmp/rvm_src_15049’: Permission denied
mkdir: cannot create directory ‘/usr/share/rvm/log/1628317044_ruby-3.0.2’: Permission denied
tee: /usr/share/rvm/log/1628317044_ruby-3.0.2/extract.log: No such file or directory
<font color="#4E9A06">ruby-3.0.2 - #extracting ruby-3.0.2 to /usr/share/rvm/src/ruby-3.0.2</font>.....
<font color="#CC0000">Error running &apos;__rvm_package_extract /usr/share/rvm/archives/ruby-3.0.2.tar.gz /usr/share/rvm/tmp/rvm_src_15049&apos;,</font>
<font color="#CC0000">please read /usr/share/rvm/log/1628317044_ruby-3.0.2/extract.log</font>
<font color="#CC0000">There has been an error while trying to extract the source. Halting the installation.</font>
<font color="#CC0000">There has been an error fetching the ruby interpreter. Halting the installation.</font>
<font color="#4E9A06"><b>abraham@abraham-virtual-machine</b></font>:<font color="#3465A4"><b>~</b></font>$ </pre>

**Comment by sojan-official** [comment]
@abraham-azzam  Could you give more information?

If this is an instance prepared using the chatwoot installation script. To upgrade the ruby install you would need to log in as `chatwoot` user

```
# Login as Chatwoot user
sudo -i -u chatwoot

# Navigate to the Chatwoot directory
cd chatwoot
```

**Comment by sojan-official** [comment]
Closing since there is no further updates on this issue
