### ISSUE TITLE
Chatwoot widget is can't see in Safari and Firefox.

### ISSUE THREAD

**Issue by redmagic0099** [chatwoot/chatwoot#2776]
Chrome and Edge can see  but Safari and Firefox can't see  widget.
Using chatwoot v1.17.1 Self hosted  for EC2 instance(t2.medium)

Chatwoot log return 200 every time.
but Safari and Firefox web tool console logs these errors when couldn't show widgets
Uncaught TypeError: document.body is null
    createFrame DOMHelpers.js:8
    run sdk.js:120
    onload 33:(index)
Some cookies are misusing the recommended "sameSite" attribute

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/2777
