### ISSUE TITLE
bug: chatwoot live chat widget not loading on Firefox and Safari

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#2777]
**Describe the bug**

**To Reproduce**

1. Open Firefox or Safari and go to https://www.infinitefleet.com/
2. See error.

**Expected behavior**

Chatwidget should be loaded on Firefox and Safari by default.

**Screenshots**

Chrome 92 / Mac OS
![image](https://user-images.githubusercontent.com/3526167/128684332-aea326b2-8285-4e01-a1f7-dd4638aa6b2c.png)

Firefox 90/ Mac OS
![image](https://user-images.githubusercontent.com/3526167/128684427-0c691df3-3ade-4fca-b017-994f814f3d72.png)

Firefox after turning off enhanced tracking protection 
![image](https://user-images.githubusercontent.com/3526167/128683856-fefd8831-db97-4219-b9ca-bdbeaadcbaac.png)

**Browser logs**

n/a

**Server logs**

n/a

**Environment**

Self-hosted Docker.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Smartphone (please complete the following information):**
 - n/a

**Additional context**

**Comment by vishnu-narayanan** [comment]
@sojan-official could you please take a look ?

**Comment by pranavrajs** [comment]
Please add the script to the end of the body, not at the head. The problem here is that body might not be initialized before chatwoot loads.

**Comment by vishnu-narayanan** [comment]
@redmagic0099 Could you please try this out and let us know if the problem persists ?
