### ISSUE TITLE
Feature: Filter reports by inbox

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2780]
- Filter reports by inbox
- Update API to accept inbox information

Acceptance criteria:

- Admin should be able to see reports of a particular inbox.
- Admin should have a button to download a CSV report for inbox

## Design

<img width="1750" alt="Screenshot 2021-08-15 at 7 41 01 PM" src="https://user-images.githubusercontent.com/73185/129481338-3c89cb8f-241b-467a-b883-65a046fda1d4.png">

**Comment by sojan-official** [comment]
blocked by: https://github.com/chatwoot/chatwoot/issues/2823

**Comment by pranavrajs** [comment]
Closed via #3084
