### ISSUE TITLE
New inbox channel for Youtube support

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#2783]
**Is your feature request related to a problem? Please describe.**
Channel to moderate and reply to comments on a Youtube channel. 

**Describe the solution you'd like**
Youtube provides an API for CRUD operation on the comments resource: https://developers.google.com/youtube/v3/docs/comments

**Describe alternatives you've considered**
Chatwoot would be the first major platform to provide this integration in a sea of other CRM providers.

**Additional context**
N/A

**Comment by pranavrajs** [comment]
Closing this as there is not enough interest for the feature.
