### ISSUE TITLE
feat: Settings section to config email footer for agents

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2800]
Estimation - 1
The email channel needs to have support for footer with replying agents name and email.

- The setting could go to profile settings page
- There should be a preview of footer
- It should have a Checkboxes and labels to show name, email, position on the footer
- The position is a new field and might need an input field
- Name and email can be used from profile data

**Comment by pranavrajs** [comment]
Footer can be common to all channels. 

For eg: In Twitter/Whatsapp channels, while replying to the user, large brands add a footer at the end. An example is shown below.

<img width="604" alt="Screenshot 2021-08-14 at 2 42 38 PM" src="https://user-images.githubusercontent.com/2246121/129441135-f235d265-c8bc-426f-a4b3-3464edac127b.png">

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/3874
