### ISSUE TITLE
The swagger.json needs some fixing

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#2806]
**Is your enhancement request related to a problem? Please describe.**
While the swagger.json is "valid enough" there are some violations to the spec that cause editors (including [https://editor.swagger.io](https://editor.swagger.io)) that are more strict (for example Postman) to be unable to validate the swagger for generation based on it.

**Describe the solution you'd like**
I suggest importing the swagger.json into Postman or [https://editor.swagger.io](https://editor.swagger.io) and watch its validation errors. Most errors are simple and small fixes such as:

- base path must start with "/"
- paths must start with "/"
- required is an array of property names (instead of a boolean) and should sit on schema level not property level
- public endpoints should be marked with `"security": []` instead of nil
- ...

**Comment by pranavrajs** [comment]
@brentco Thanks for reporting this. Do you have a suggestion on the changes needed? If so, please feel to raise a PR, otherwise, the team can take a look at it in the next release.

**Comment by brentco** [comment]
> @brentco Thanks for reporting this. Do you have a suggestion on the changes needed? If so, please feel to raise a PR, otherwise, the team can take a look at it in the next release.

Sure thing, I can go through and fix it :)

**Comment by pranavrajs** [comment]
Great! Let me know if you need any help. Please see this document to understand how we maintain the Swagger documentation.

https://www.chatwoot.com/docs/contributing-guide/api-documentation
