### ISSUE TITLE
Reported Issues at Huntr

### ISSUE THREAD

**Issue by B3EF** [chatwoot/chatwoot#2813]
hi @pranavrajs, @sojan-official, @nithindavid

https://huntr.dev/bounties/1625475209542-chatwoot/chatwoot/
https://huntr.dev/bounties/1625474692857-chatwoot/chatwoot/
https://huntr.dev/bounties/1625472546121-chatwoot/chatwoot/
https://huntr.dev/bounties/1625472018080-chatwoot/chatwoot/
https://huntr.dev/bounties/1625470476437-chatwoot/chatwoot/

please verify the reports.

**Comment by pranavrajs** [comment]
@B3EF Sure! We will be prioritizing the fixes in the v1.20 release. We will track the changes and communication in the  Huntr.dev. Closing it here for now.

**Comment by B3EF** [comment]
Ok

**Comment by B3EF** [comment]
hi @pranavrajs , can you check and verify the bug at huntr , it will help me grab a small amount of bounty , at huntr until a fix is confirmed the adversary page will be private.
?
