### ISSUE TITLE
Multiline support for channel greeting message

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2816]
Chatwoot supports a greeting message to be set so that the system would respond automatically when a conversation is created. It is not possible to add multiple lines to this message.

### Problem

If you need to set an auto-response message as shown below on an email channel, then the existing system would shrink it to a single message.

**Expected:**
```
Hi X, 

Thanks for reaching out to the support, we will get back to you as soon as possible.

Regards
Acme Team
```

**Current output:**
```
Hi X, Thanks for reaching out to the support, we will get back to you as soon as possible. Regards Acme Team
```

### Solution

- [ ] Use a text area for Whatsapp, Twitter, Facebook.
- [ ] Use a rich content editor for email, website, or any other channel.
<img width="467" alt="Screenshot 2021-08-14 at 2 53 28 PM" src="https://user-images.githubusercontent.com/2246121/129441389-37a6123d-282c-425b-a060-281a3ba94676.png">

- [ ] Disable greeting message if the conversation is a tweet.
- [ ] Verify that the greeting message is working in all channels.

### Followup investigation

- [ ] Standardize editor for chat, campaigns, and greeting message

**Comment by fayazara** [comment]
@sojan-official @tejaswinichile we need to skip sending the Greeting message if the conversation is a tweet, can we handle this in the backend please?

**Comment by sojan-official** [comment]
@fayazara  it should be a minor change, I will have it updated on your PR
