### ISSUE TITLE
[Help] Linking Facebook page

### ISSUE THREAD

**Issue by mohmmd256** [chatwoot/chatwoot#2818]
Hello all,

Trying to help out a friend setup their Chatwoot instance (Linux VM type of deployment). When it comes to try linking a Facebook page, it gets stuck in this screen, and the below errors appear in log:

<img width="1215" alt="Screen Shot 2021-08-11 at 7 05 23 PM" src="https://user-images.githubusercontent.com/7905931/129451533-97ea336c-b54a-4d8e-b87f-bf07e34e0d9d.png">

```
Aug 12 07:44:07 chatty chatwoot-web.1[44937]: F, [2021-08-12T07:44:07.966655 #44937] FATAL -- : [ec5db24e-da3d-41e2-ac1d-5a9a41b7c293]
Aug 12 07:44:07 chatty chatwoot-web.1[44937]: [ec5db24e-da3d-41e2-ac1d-5a9a41b7c293] Koala::Facebook::ClientError (type: GraphMethodException, code: 100, message: API calls from the server require an appsecret_proof argument, x-fb-trace-id: CX5zrNkeY7q [HTTP 400]):
```

### Environment Overview:

- The FB App is in dev mode, not yet approved by facebook, and to my understanding, since it is meant for internal use with no possibility of usage by public, as long as the admin of page we are attempting to link is with a role (admin) in the app, then all permissions should be applied and work with no exception.
- For the env values of CW for FB app, i am confident they are correctly set.
- the verify_token in webhook settings matches the one in CW env.
<img width="996" alt="Screen Shot 2021-08-14 at 5 44 36 PM" src="https://user-images.githubusercontent.com/7905931/129452693-00c2fe76-1118-4a20-8504-a02ab438b76b.png">

If anyone recently set up their self-hosted instance with a similar scenario as the above and successfully got to link FB page, your input is highly appreciated 🙏🏼

**Comment by sojan-official** [comment]
ref : https://github.com/chatwoot/chatwoot/discussions/2072

**Comment by mohmmd256** [comment]
Hi everyone

So we figured out the cause of this issue.

It was this option in the **Advanced Settings** section of the Facebook app:

<img width="767" alt="Screen Shot 2021-09-04 at 12 23 01 PM" src="https://user-images.githubusercontent.com/7905931/132098086-0d1a0308-8ae3-42e0-a303-c640922b59c9.png">


Once disabled, we were able to link the page immediately and receive messages on Chatwoot.

**Comment by sojan-official** [comment]
@mohmmd256  thanks a lot for documenting this.
