### ISSUE TITLE
End conversation from chat widget

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#2828]
**Context:**

Provide an option to the user to end the conversation once they are done with it. This would move the conversation from the queue.

**Changes:**
- [ ] Add a dropdown on the widget to select the end conversation button. Design attached. Move the existing open in a new window button to the dropdown.
- [ ] Add an API to resolve the conversation.
- [ ] Add an activity message "Conversation was resolved by %{user_name}".

**Design:**

<img width="432" alt="end-chat(2)" src="https://user-images.githubusercontent.com/2246121/129533601-5d7eb2dd-0840-4735-b191-33694c7ba961.png">

**Comment by iammattmartin** [comment]
I'd just like to add that hiding the expand option probably isn't great and the end chat should really be more visible. 

Often the three dots is used for things like sound, email transcript and contact details. Not core functionality for the window itself.

**Comment by pranavrajs** [comment]
@iammattmartin There is not enough space for the end chat button which is why we went with this design. This makes sense. Let us revisit the design.
