### ISSUE TITLE
feat: ability to disable keyboard shortcuts

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#2847]
**Is your feature request related to a problem? Please describe.**

Accidental keyboard shortcut invocations can cause Agents to lose a message text midway or mark a conversation resolved. Some might want to turn this behavior off.

**Describe the solution you'd like**

Setting to enable/disable keyboard shortcuts.

**Describe alternatives you've considered**
n/a

**Additional context**
https://app.chatwoot.com/app/accounts/1/inbox/37/conversations/7941

**Comment by vishnu-narayanan** [comment]
cc: @pranavrajs @sojan-official  @iamsivin

**Comment by pranavrajs** [comment]
@vishnu-narayanan Instead of disabling the shortcuts, we can disable the shortcuts while the input box is active.

**Comment by vishnu-narayanan** [comment]
@pranavrajs That could fix also work. Adding further, it is nice to have shortcuts even when the textbox is active. Like making the text bold or say adding a label via shortcuts. A Gmail like behavior would be optimum.

**Comment by iamsivin** [comment]
@pranavrajs @vishnu-narayanan  I think it will fix by this PR https://github.com/chatwoot/chatwoot/pull/2790

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/2790
