### ISSUE TITLE
feat: Add widget preview on inbox settings page

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2853]
Estimation - 2

- The left side of the page has 3-column  space on the left side of widget settings page
- Make sure the preview box is `fixed` positioned and closable 
- Refer #2523 for the dummy widget component 
- Update widget preview for settings 
1. Welcome Heading
2. Welcome Tagline
3. Widget Color
4. Channel Avatar

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/2441
