### ISSUE TITLE
bug: Bot activity status translation is missing

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2857]
![Screenshot 2021-08-23 at 11 06 15 PM](https://user-images.githubusercontent.com/12408980/130491932-d882be05-8888-4f06-88a6-15f14f8121aa.png)

**Comment by sojan-official** [comment]
the status bot should be deprecated in favor of pending, could you add the test conditions to recreate this?

**Comment by muhsin-k** [comment]
Closing since not able to reproduce the issue
