### ISSUE TITLE
Define Scalability procedures and requirements - Documentation

### ISSUE THREAD

**Issue by alayhi** [chatwoot/chatwoot#286]
Please inform us of how best to scale this applciation based on best practices that inform your own development.

Thank you :)

**Comment by sojan-official** [comment]
To be honest, It still very early for us to talk about scalability.  We have been following the best practices while developing this application. But we haven't done load testing of any scale on this yet.  

Only validation we can talk about now is the deployment of chatwoot we have on our main website. It handled around 10k pageviews a day, from hackernews, when we were trending there.  We received over 200 conversations during the time.  All this was handled by a chatwoot deployment running on heroku's free dyno. 

So I guess we are fairly confident in terms of this application's scalability for small to medium businesses.  We will also spend some effort into further investigation once we cut the `v1.0.0` release.
We are also actively listening to the community on their experiences in this front.   

let me know if you have more questions @alayhi
