### ISSUE TITLE
Provide pre-built docker images on docker hub

### ISSUE THREAD

**Issue by kolaente** [chatwoot/chatwoot#287]
**Describe the solution you'd like**

As someone who wants to install and use chatwwot, I would love to only have a docker container I could then integrate in my docker compose setup without having to build it first. That way, I don't have to deal with building and pusing the image every time I want to update it.

This could be set up easily using [docker automated builds](https://docs.docker.com/docker-hub/builds/) or some CI system like [drone](https://cloud.drone.io/) or [circleCI](https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/) (I saw you're already using circleCI in this repo, so it is probably easier to just extend that.

**Describe alternatives you've considered**
Building the image every time, see above.

**Comment by sojan-official** [comment]
@kolaente  we have hooked docker hub auto builds to master. 
https://hub.docker.com/r/chatwoot/chatwoot/

let me know if you need any other help.

**Comment by kolaente** [comment]
Awesome, thanks!

**Comment by SebastiaanKloos** [comment]
When using the above image the container stops working and outputs this to the log: Switch to inspect mode.

**Comment by pranavrajs** [comment]
@SebastiaanKloos I've created an issue for this, we will inspect the issue. https://github.com/chatwoot/chatwoot/issues/427
