### ISSUE TITLE
Business hours doesn't respect timezone with daylight savings time

### ISSUE THREAD

**Issue by sarhugo** [chatwoot/chatwoot#2882]
**Describe the bug**

At widget the timezone offset is sent but it doesn't take dst in mind. The problem is that at [widget settings](https://github.com/chatwoot/chatwoot/blob/4a23a393f76f7bc39b791c067bb2fabc51f8fda1/app/views/widgets/show.html.erb#L26) the offset is taken from the timezone itself and it has no context of the current date. Solution should be to get the offset from a current date instance.

`ActiveSupport::TimeZone[@web_widget.inbox.timezone].now.formatted_offset`

**To Reproduce**

1. Go to Inbox settings, Business Hours
2. Choose one timezone with dst
3. Check the widget
4. When dst is enabled business hours are wrong.

**Comment by sojan-official** [comment]
@sarhugo  feel free to go ahead.
