### ISSUE TITLE
enhancement: Change agent reports filename to include date as report name

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2883]
**Estimation** - 1

Currently the agent reports under Reports => Download agent reports (Green button on right top) downloads the reports as CSV. But the file is always `download` which could be changed to include `Date` so that files are distinguishable.

https://stackoverflow.com/questions/7034754/how-to-set-a-file-name-using-window-open

**Comment by SanjuSudheerM** [comment]
@nithindavid I would like to work on this ticket. What would be the expected filename be?

**Comment by nithindavid** [comment]
@SanjuSudheerM You could use ‘agent-report-DD-MM-YYY.csv’

**Comment by SanjuSudheerM** [comment]
PR Raised #2931

**Comment by wilso199** [comment]
@nithindavid Just a housekeeping note - I think the work for this feature has been complete.

**Comment by pranavrajs** [comment]
@wilso199 Thanks for informing 👍
