### ISSUE TITLE
enhancement: No unit for time based graphs on reports page graph

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2884]
**Estimation** - 1

On reports page we have sections for First response time and Resolution Time. Which plots a graph with time series on the Y axis. But it mentions no unit for the axis. We need to mention the unit on the axis

<img width="1012" alt="Screenshot 2021-08-25 at 11 27 25 PM" src="https://user-images.githubusercontent.com/1277421/130841683-cffbd1a4-6ee7-4c3c-8ed4-864961e7b22d.png">

**Comment by nithindavid** [comment]
@himanshu007-creator let me where you are stuck

**Comment by himanshu007-creator** [comment]
https://github.com/chatwoot/chatwoot/blob/3941c6f32ba05dad1bb730b60ed9f111aca38afc/app/javascript/dashboard/i18n/locale/ne/report.json#L10

will it be good to mention here in the description, if i replace <code>Total</code> with <pre>Total <br>(time in Hrs)</pre>

**Comment by virajbahulkar** [comment]
Can I pick this up?

**Comment by pranavrajs** [comment]
<img width="337" alt="Screenshot 2022-06-02 at 8 33 13 PM" src="https://user-images.githubusercontent.com/2246121/171660012-39fb1b6f-af97-4d09-8c0a-c7e57201ee24.png">

Closing this as the feedback is already incorporated.
