### ISSUE TITLE
bug: Selected agent profile picture is not showing in multi-select

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2895]
https://user-images.githubusercontent.com/12408980/131073460-971efcd2-42b2-433f-be94-726e7e0f8005.mov

**Comment by wilso199** [comment]
Hi @muhsin-k are you looking for contributors for this bug? I would be interested in working on it.

**Comment by muhsin-k** [comment]
@wilso199 Please feel free to go ahead
