### ISSUE TITLE
Add new inbox WhatsApp using https://www.360dialog.in $5/mo

### ISSUE THREAD

**Issue by ariaseta** [chatwoot/chatwoot#2902]
**Is your enhancement request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Add new inbox whatsapp from 360dialog like respond.io or uchat.com.au

**Describe alternatives you've considered**
Right now, only 360dialog who provide API only with reasonable price

**Additional context**

**Comment by sojan-official** [comment]
please refer https://github.com/chatwoot/chatwoot/discussions/2759

**Comment by prajeshmadhavi** [comment]
I haved used API Channel to integrate with 360 Dialog. You can do so.
