### ISSUE TITLE
spike: Find efforts to switch to Microsoft fluent icons

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2906]
As of now there isn't a straightforward library for vue to use fluent icons. 
- We need to see how to use the svg icons. By creating new package or use an existing one
- find how to reduce the bundle size. (Tree shaking)
- efforts to switch to ion icons in existing codebase 
- customisation options like color, fill styles

**Comment by pranavrajs** [comment]
@fayazara Please spend 0.5 worth of effort to investigate the changes required for this and post your findings here. 

Expectation: The steps required for migration if icons can be replaced. Otherwise, please share the challenges to include the pack.

**Comment by fayazara** [comment]
I was able to optimise all the icons from the Microsoft repo, using [SVGO](https://github.com/svg/svgo), brought the size down to nearly 4 mb (note, this is all the icons, close 4k)

Wrote a small script to convert them to .vue component files - https://github.com/fayazara/fluenticons/tree/v2/components/FluentIcon

I've also added `fill="currentColor"` attribute of svg to all the file, so we can dynamically change the icon color using css text-color (`color: #tomato`) property,.

This way we could just use the components like this `<FluentIcon class="text-red-600" />` or `<FluentIcon style="#f56565" />`

Would this help?

**Comment by nithindavid** [comment]
@fayazara Great! :D
