### ISSUE TITLE
spike: Efforts to bring in tailwind on dashboard

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#2915]
**Estimation** - 1

- Find the configurations effort needed to add tailwind UI to dashboard
- Since widget already uses tailwind, unify the configurations
- Style changes and tweaks needed on the foundation side, especially with spacing and css variables
- Moving existing color palettes and variables into tailwind
- Strategy to sideline foundation code as much as possible and how to write styles with tailwind moving forward
- As per the internal discussion we would be mostly going with `@apply ` than writing classes in the DOM
- Configure https://tailwindcss.com/docs/just-in-time-mode
- Supporting theming, which could benefit dark mode and user customisable/preferred themes https://tailwindcss.com/docs/theme

**Comment by nithindavid** [comment]
@pranavrajs @fayazara Please add if you guys find anything other than the mentioned points.

**Comment by fayazara** [comment]
- Configure PurgeCSS properly to reduce CSS footprint and file sizes.
- Could use the official [form](https://github.com/tailwindlabs/tailwindcss-forms) plugins, [typography](https://github.com/tailwindlabs/tailwindcss-typography) plugins if necessary, goes very well with tailwindcss classes.

**Comment by pranavrajs** [comment]
@fayazara We already have a purge configuration in Tailwind. I guess we could add the dashboard files also to the list. See here

https://github.com/chatwoot/chatwoot/blob/develop/tailwind.config.js#L4

**Comment by FredrikZeiner** [comment]
I'd like to take a look at this, if it's available. I have a few questions though.

From what I've seen code spelunking, it looks like the widget doesn't use tailwind all around? Is it desirable to do so?
Are there any guidelines in terms of the max size of PR's? I'd like to break this up into smaller deployable pieces, otherwise this PR will be absolutely humongous.

Chatwoot looks great today, but has a few styling inconsistencies. This will take it to the next level.

**Comment by sojan-official** [comment]
@FredrikZeiner We prefer to ship work in small units. Though there isn't a strict limit on the line of code, changes beyond 400-500 lines usually take more extended review circles. 

The idea of this spike aligns with your suggestion `to break this up into smaller deployable pieces.` ie. 

- A PR to make the tailwind styles available into the dashboard pack, so developers could start using the tailwind styles for future changes.
- We will make subsequent smaller PRs to move the color palettes and other information 
- We sideline the usage of foundation across the app through subsequent smaller PRs 


cc: @pranavrajs  @nithindavid @muhsin-k @fayazara 

self note: Ability to use tailwind classes in the super admin dashboard

**Comment by sojan-official** [comment]
will be covered in https://github.com/chatwoot/chatwoot/pull/7460
