### ISSUE TITLE
Feat: API to  Filter reports by teams

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2916]
- [ ] API to Filter reports by teams
- [ ] Update API to accept team information
- [ ] API to download team report
- [ ] Swagger documentation updates

**Comment by sojan-official** [comment]
@aswindevps Let's raise a PR with the backend and swagger changes alone for this one.  I have moved the design to a new ticket for @fayazara  to work on https://github.com/chatwoot/chatwoot/issues/3058

**Comment by aswindevps** [comment]
sure @sojan-official
