### ISSUE TITLE
chore: Ability to use special characters in password

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2919]
Problem: When I am signing up for a new chatwoot account, Sometimes the password generated by my password manager isn't accepted by chatwoot which is frustrating. 

Cause: Chatwoot uses https://github.com/ValiMail/devise-secure_password for ensuring the password restrictions. The gem has a specific whitelist of allowed special characters.  This needs to be updated to support: https://owasp.org/www-community/password-special-characters

# Required Changes 
- [x] Propose the change on the original gem repo
- [x] Create a fork and update the safe list of characters. ref: one of the forks contains example changes:  https://github.com/ValiMail/devise-secure_password/compare/master...UnitooTeam:master
- [x] Commit the changes to the original repo if maintainers approve the change 
- [x] Use the fork / updated gem in Chatwoot so that the issue is resolved 

# Acceptance and Testing
- [x] Ability to use passwords generated by various password managers which included special characters ( Dashlane, Lastpass, built-in managers  for chrome, safari, etc )
- [x] Ensure the special characters are compliant with the proposed list.

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please take a look at this and see if you have any questions / concerns?

**Comment by tejaswinichile** [comment]
Added the changes here https://github.com/ValiMail/devise-secure_password/pull/68
We are pointing our gem to the new fork.
