### ISSUE TITLE
Question: Is there a way to change an agents password?

### ISSUE THREAD

**Issue by petebytes** [chatwoot/chatwoot#294]
The seed file provides a way to provide a password, but I cannot find anyplace in the UI to change password even when creating a new agent.

Thanks - this project is pretty awesome.

**Comment by pranavrajs** [comment]
@petebytes Thanks for the feedback. You have to use the reset password flow for now. We will add that missing piece soon.

**Comment by petebytes** [comment]
That works - thanks!
