### ISSUE TITLE
"systemctl restart chatwoot.target" command is not working windows wsl : ubuntu20.4

### ISSUE THREAD

**Issue by rohitsh1691** [chatwoot/chatwoot#2940]
Is there any alternative command to run all services for chatwoot in wsl.

![image](https://user-images.githubusercontent.com/12787353/131609793-5b95a2b4-8349-468c-9dbc-8db057b7b9ca.png)

**Comment by pranavrajs** [comment]
@vishnu-narayanan Can you please take a look at this?

**Comment by rohitsh1691** [comment]
@vishnu-narayanan I am using windows subsystem for Linux and in that command "systemctl" command doesn't work. Is there any way to start all services for the chatwoot from the service command?

**Comment by vishnu-narayanan** [comment]
WSL does not support `systemd` as of now.

https://github.com/systemd/systemd/issues/8036
https://github.com/Microsoft/WSL/issues/1579

**Comment by vishnu-narayanan** [comment]
There are some workarounds to get it working partially. Maybe you could try those. 
https://github.com/Microsoft/WSL/issues/1579

**Comment by vishnu-narayanan** [comment]
Closing this for now. Please feel free to reopen if you have more questions.
