### ISSUE TITLE
feat: Add support for rich content messages in new conversation

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2942]
The user is able to create a new conversation with a particular contact. Currently, the current message field doesn't support rich content messages. Use the rich content editor used in the message layout here as well.

<img width="600" alt="Screenshot 2021-09-01 at 1 32 36 PM" src="https://user-images.githubusercontent.com/12408980/131635180-4c43c122-bd12-484b-ab5e-5cd1bbd498c0.png">

**Note**
- Add the rich editor support for web widget and email channel only

**Comment by pranavrajs** [comment]
@muhsin-k Please restrict the rich content editor usage based on the inbox channel type.

**Comment by muhsin-k** [comment]
@srameshr Sure. Please feel free to go ahead
