### ISSUE TITLE
Question: How do you confirm new agent when deploying to heroku?

### ISSUE THREAD

**Issue by petebytes** [chatwoot/chatwoot#295]
Deployed to Heroku and added a new agent(administrator) which resulted in a pending confirmantion state.
Never received email and checked Spam :)

**Comment by pranavrajs** [comment]
@petebytes I guess we might have missed telling the users to configure their own SMTP servers for emails. You will be able to see 3 config variables which need to be added to get the emails working. 

https://www.chatwoot.com/docs/environment-variables

@sony-mathew Let us add SMTP settings to Heroku one-click deploy as optional param if it is possible.

I added this https://github.com/chatwoot/chatwoot/issues/296 to track the issue.

@petebytes Thanks for the feedback, is there something which you think we missed in One-Click deploy flow.

**Comment by petebytes** [comment]
Wow fast response - I think just a review all env vars and which should be added to heroku deployment. If they are not accessible in the UI after deployment.

**Comment by petebytes** [comment]
I just set the ENV vars in heroku after deployment and worked fine.
Thanks
