### ISSUE TITLE
chore: Ability to differentiate between tweets and DMs

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2961]
## Acceptance 

Ability to differentiate between Twitter tweets and messages in a single glance 

### Dashboard 
<img width="596" alt="Screenshot 2021-09-05 at 11 15 56 PM" src="https://user-images.githubusercontent.com/73185/132136446-90066ac5-a7f5-4440-8907-294d07d72373.png">

### Icon

svg zip : 
[twitter.svg.zip](https://github.com/chatwoot/chatwoot/files/7112076/twitter.svg.zip)

**Comment by iamsivin** [comment]
This issue will fix by this PR #3003
