### ISSUE TITLE
feat: Sync conversation history when adding a new channel like Facebook

### ISSUE THREAD

**Issue by datnguyen293** [chatwoot/chatwoot#2966]
**Is your enhancement request related to a problem? Please describe.**
I'm now adding Facebook page and writing code for a new channel for our local messaging provider like Facebook Messenger. When adding new channel, I would like to see the conversation history from that channel so I can use Chatwoot only to continue the works.

**Describe the solution you'd like**
Pulling conversation history. The history conversation can be assigned to agents or not but shouldn't send notification for new messages added (via push on both web and mobile apps).

**Describe alternatives you've considered**
Please describe the steps to implement it with API Channel as well.

**Comment by muhsin-k** [comment]
@sojan-official / @tejaswinichile Could you please look into this?

**Comment by sojan-official** [comment]
In an API channel, you could create a conversation in `pending` status and backfill the messages in the conversation before toggling the conversation status to `open` and assign it to an agent.

**Comment by datnguyen293** [comment]
That's good idea. Can I apply them same strategy for Facebook Messenger?

Thanks

**Comment by sojan-official** [comment]
@datnguyen293  for channels like Facebook messenger we have it in our pipeline to sync older conversations on inbox creation using the Facebook conversations API

**Comment by napter** [comment]
Hey - is there any way to do this now? Is this doable with the Chatwoot API? If so, even just a script to connect to the FB and Chatwoot API to do this would be great.

**Comment by sojan-official** [comment]
@napter if you are building over an API channel in chatwoot, you can import the conversations; otherwise, it's not possible at the moment.

**Comment by pranavrajs** [comment]
We are not pulling previous conversations in most channels as a general behavior. Closing this here as we will not take it up as a feature.
