### ISSUE TITLE
Chat box does not stay closed after its closed, but instead reappears after page refresh

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#2970]
**Describe the bug**

If I chat with a customer, and I send a reply to them that they do not see, then this reply will be slightly visible next time they come back. This is super and expected behavior.

However, of the client closes that chatbox because they perhaps understood the message (or just dont care), then the box will re-appear next time the reload the page (or visit other page).

**To Reproduce**

1. Send chat message to agent
2. Leave page
3. Allow agent to reply
4. Return to page
5. Do not open the chat message that is now visible, but instead click X to close it. The chat message now correctly is closed.
6. Reload page, and see that the chat visible again, despite I had just closed it.

**Expected behavior**

I would expect the chatbox to stay closed if i click X and not open until I click i t again.

This would also emulate how Intercom and other similar platforms work.

**Comment by brundles** [comment]
I cant even reply to the message, close it and then expect it to stay closed. It still pops up 😳

**Comment by jacka2021** [comment]
I second this 100 % @muhsin-k 

It is causing irritation for people using my system, that they are not able to turn this off. It pops up again and again.

**Comment by muhsin-k** [comment]
@jacka2021 @brundles We are able to reproduce the error. This is a confirmed bug. We will prioritize in the next sprint.

**Comment by pranavrajs** [comment]
@iamsivin Please make the bubble clickable along with this change. 

![Screenshot 2021-09-21 at 10.55.51 PM.png](https://images.zenhubusercontent.com/5bcf4a59b198c93527505cd6/2812725b-0e5a-457a-bb58-513d14464be7)

**Comment by brundles** [comment]
Can I help in any way @iamsivin ? :)
