### ISSUE TITLE
Bug: content_type is nil for new message in webhook events

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#2974]
ref: https://discord.com/channels/647412545203994635/650257251856285707/884475687170342962 

> Hi, we have connected with a bridge server to send message from chatwoot to whatsapp by configuring webhook url and all that. So, when we try to get the content_type in req.body, because only then different types of messages can be sent (as for now, we have done sending just text messages), the value is null. How to get the content_type as it is showing null? I have attached the app logs for reference

![Chatwoot_content_type](https://user-images.githubusercontent.com/73185/132331038-fc8e3324-ae39-4232-a0b8-79f0869f455c.jpeg)

## Acceptence 
- [ ] Ensure content_type can't be null
- [ ] Backfill old data with content_type : 'text' for old messages through a migration

**Comment by murtaza-bagwala** [comment]
@sojan-official shall I pick this up ?

**Comment by murtaza-bagwala** [comment]
@pranavrajs shall I pick this up ?

**Comment by muhsin-k** [comment]
@murtaza-bagwala Please feel free to go ahead.
