### ISSUE TITLE
enhancement: Merging Contact should copy additional attribute Information 

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#2979]
At the moment, merge contacts don't copy over additional attributes like social links, company names from mergee contact to base contact. So

- [ ] When we execute merge contact action, we should copy over the additional attributes from mergee contact to base contact.

this issue blocks: #2457

**Comment by sojan-official** [comment]
should be closed in https://github.com/chatwoot/chatwoot/pull/2812
