### ISSUE TITLE
Snoozed conversation status

### ISSUE THREAD

**Issue by hanthor** [chatwoot/chatwoot#2985]
**Is your enhancement request related to a problem? Please describe.**

Snoozed conversation don't show the Snooze conditions

**Describe the solution you'd like**

Have a list like Gmail that show how long the conversations will be snoozed for.

**Describe alternatives you've considered**
You could also put it in the notice in the conversation itself 
 "agent" snoozed conversation until "condition"

**Comment by hanthor** [comment]
Can't tell the difference between snoozed for a week or snoozed until reply

**Comment by muhsin-k** [comment]
@hanthor Thanks for the feedback and we will prioritize in the next sprint.

**Comment by muhsin-k** [comment]
**Todo**
- [ ] Add text near view details button 
- [ ] Add a computed method for finding the snoozed text

| Snooze Type  | Snoozed Text |
| ------------- | ------------- |
| Next Reply | Conversation was snoozed until next reply  |
| Tomorrow  | Conversation was snoozed until tomorrow  |
| Next Week  | Conversation was snoozed till next Monday  |


**Design**
<img width="837" alt="Screenshot 2021-09-13 at 4 33 42 PM" src="https://user-images.githubusercontent.com/12408980/133072818-53102a46-fca8-4834-a2ae-d80683a8b699.png">
