### ISSUE TITLE
bug: notices in message previews

### ISSUE THREAD

**Issue by hanthor** [chatwoot/chatwoot#2989]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5840441/132761650-6b98659d-ee22-48b1-bc84-90b991af87cf.png)

Message previews should ignore room notices

**To Reproduce**

Have a bot reopen a room because of new activity

**Expected behavior**

should show latest message or private note

**Comment by sojan-official** [comment]
Note: Conversations in the list get reordered when a new activity message is added. We can revisit that behavior when taking a look at this.

**Comment by pranavrajs** [comment]
Closing this as the activity messages are now discarded and private note/last message is shown in the list
