### ISSUE TITLE
feat: Ability to trigger custom events through Chatwoot JS SDK

### ISSUE THREAD

**Issue by valentinwinkelmann** [chatwoot/chatwoot#2995]
**Is your feature request related to a problem? Please describe.**
For a current client support in our system, we want to be able to execute javascript commands directly at the client. We have created interactive javascript tutorials via Intro.js, which we want to execute to show the visitors certain things. However, it would certainly be useful for many other situations as well. I tried to find a kind of OnMessage event that allows me to wait for certain texts in the chat like ///CallEvent01 to trigger a javascript function. Unfortunately I can't find a way to react to the incoming messages via javascript at all.

**Describe the solution you'd like**
My suggestion would be to add another possibility like //EventName or /#EventName beside the /SampleText commands. So a certain trigger text, which then triggers an event with this name on the client side.
Concretely related to our example, it would allow us to run a special intros tutorial as soon as we realize the visitor needs a detailed instruction.

**Describe alternatives you've considered**
Alternatively, it would be possible to include a kind of OnMessage(text) event in the widget code, which allows to check the text for a special trigger string on every incoming message on the visitor page. if then //CallEvent1 would be in the text, it would be possible to react to it via a simple javascript function. This is certainly easier to implement than the first solution, but has the disadvantage that the visitor would see this message instead of this happening invisibly for the visitor in the background. Basically it would make sense to have a kind of "OnMessage" event to play individual notification sounds or to show a "New Message" text in the tab title.

**Comment by brentco** [comment]
We have as a workaround implemented a sidecar websocket in which we send bi-directional events to the backend that controls the chat. I have posted this in my issue #3488
