### ISSUE TITLE
The anonymity of correspondence is violated

### ISSUE THREAD

**Issue by GyR4uk** [chatwoot/chatwoot#2996]
Our users began to complain that they sometimes see the correspondence of other users.
This happens randomly.

**Comment by iammattmartin** [comment]
You'd need to give more information about your setup.

What users, do they share any common infra? Do you have a proxy/load balancer in front of your installation?

**Comment by GyR4uk** [comment]
1) We use deploy via docker-compose.
2) Before chatwoot, there is only nginx.
3) The error occurred both accidentally and when the same email was used.

Under what conditions can I get access to the history of another user's correspondence at all?

**Comment by pranavrajs** [comment]
@GyR4uk There is still not enough information to debug the error. Would you be able to provide a screencast of the behaviour?

**Comment by GyR4uk** [comment]
I will try to repeat this bug and let you know

**Comment by sojan-official** [comment]
Please feel free to reopen this if it reoccurs
