### ISSUE TITLE
[CW-1866] Add date and timestamps to transcripts sent via email

### ISSUE THREAD

**Issue by cgb** [chatwoot/chatwoot#2999]
**Is your feature request related to a problem? Please describe.**
Using a website Inbox, users or admins receive a chat transcript without date or timestamps, making it difficult to gauge the inter-message response times and start/end times for a chat session 

**Describe the solution you'd like**
The date and timestamp are available on every message within the Chatwoot admin interface.  For contacts, the chat messages are divided by a date header.

When a chat transcript is sent, it would be great to have a global option or per-inbox option to allow the sending of precise date and timestamps.

**Additional context**
I'm happy for the date and timestamps to be sent to user & admins, but it might make sense to divide the option between admins, whom get the precise detail, and end users / contacts whom might only get the date without time precision, in case organisations want to hide that level of detail from end users.

Thanks!

<sub>[CW-1866](https://linear.app/chatwoot/issue/CW-1866/add-date-and-timestamps-to-transcripts-sent-via-email)</sub>

**Comment by muhsin-k** [comment]
@cgb Thanks for the feedback and we will prioritize in the next sprint.

**Comment by iammattmartin** [comment]
Some consideration maybe should given on time stamps either for local install time to the host (i.e site viewed) or the vistor....

**Comment by cgb** [comment]
@muhsin-k Wondering if anything has developed on this?  Thanks!
