### ISSUE TITLE
[Bug] Administrator can delete himself even if there are no other verified admins available

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#302]
**Describe the bug**
An administrator can delete himself when there are no other active admins available

**To Reproduce**
1. Send Invite to a new admin
2. The delete admin option becomes available next to the current admin
3. Click on that and you receive an error 'error connecting to woot server`

**Expected behavior**
- Administrators shouldn't be able to delete themselves if there is no other active admin
- When the Administrator deletes himself, he should be logged out instead of the error that is shown. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Comment by sojan-official** [comment]
@pranavrajs  thoughts.

**Comment by pranavrajs** [comment]
A logged-in administrator cannot remove himself, right now.
