### ISSUE TITLE
Import API should throw an error if there is no valid file

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3031]
Contact Imports API now returns 200 success even if there is no file attached in the request. It should ideally throw a 422. 

To reproduce:

1. POST to `/api/v1/accounts/${accountId}/contacts/import`.
2. API will return a 200 Success. 
3. Look at the logs, it will throw an error in the worker processing.
<img width="1225" alt="Screenshot 2021-09-17 at 3 24 17 PM" src="https://user-images.githubusercontent.com/2246121/133764032-8519d1ce-f3f7-4996-ba78-604f189d818d.png">

**Comment by murtaza-webonise** [comment]
@pranavrajs shall I pick this up ?

**Comment by murtaza-bagwala** [comment]
@pranavrajs shall i pick this up ?

**Comment by pranavrajs** [comment]
@murtaza-bagwala Please feel free to go ahead. Let me know if you need any help.
