### ISSUE TITLE
Telegram Channel problems with groups

### ISSUE THREAD

**Issue by clanto007** [chatwoot/chatwoot#3033]
**Describe the bug**

After configured telegram channel when someone contact the bot the system run and agent receive the message on chatwoot. But when the bot is inserted in a group chatwoot doesn't receive the messages from the groups. Tried in web and mobile app.

**To Reproduce**

1. Insert the bot in a group
2. Contact the group on telegram
3. See error

**Browser logs**

No errors on browser

**Server logs**

No log, I'm using the chatwoot cloud

**Environment**
Chatwoot Cloud

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20h1
 - Browser chrome
 - Version 93

**Smartphone (please complete the following information):**
 - Device: Fairphone
 - OS: Android 10
 - Browser Firefox
 - Version 92

**Comment by iammattmartin** [comment]
I think the general question might be, what use case is there for a CW convo/bot to be in a group?

**Comment by clanto007** [comment]
It might be usefull for some situations, for exemple in our case we use groups for IT assistence to schools were in groups there is our contact plus digital team of schools, in this case when we write, or a member of digital team write to us is to responde to a problem and to have the other informed. Also in some businesses we have groups with internal IT teams so that all the internal teams know problems and have an only chat with all assistence tickets (plus the single chat one to one that must be always available for all the cases).

But the channel is programmed to be used in a group, so this is a bug, or is not implemented in the channel?

**Comment by iammattmartin** [comment]
Just a pre-emptive question if it wasn't designed for that. They'll be able to confirm either way.

**Comment by sojan-official** [comment]
Chatwoot is designed in a way to handle conversations from a single contact and multiple agents.  So at the moment, the telegram integration doesn't support group conversations.  We are looking into supporting multiple participants in the conversation for the future. But that's a larger effort and might take a while.

**Comment by clanto007** [comment]
Thank you very much

**Comment by pranavrajs** [comment]
@clanto007 Closing this as we will not be picking it up anytime soon. The product focuses on support/communication with individual/business customers. Group conversations have different behavior altogether. We will revisit this if there is a significant interest in group conversations.

**Comment by vagner-dias** [comment]
Hello. just to indicate interest in this feature.

+1

**Comment by clanto007** [comment]
One thing that can be done instead of integrate group conversation, I think that can be easier for chatwoot to see the group conversation as a customer chat, the group name as contact name and for every message of every partecipant to write before the message the name of partecipant.
John: Hello!
Anna: Hi
As for example matrix/telegram bridge.
So we can have group chats also in other channels with this workaround without integrate group conversations, what do you think? It's easier to do this instead?
