### ISSUE TITLE
feat: Ability to send attachments to Line Messenger

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3038]
# Acceptance 

- [ ] Enable attachments option in reply box for line channel 
- [ ] Send the attachment to the line conversation 
- [ ] The attachment should be properly rendered in line depending on the type

**Comment by gvdseype** [comment]
Hi, I would like to contribute to this feature. (This would be my first open source contribution)

**Comment by sojan-official** [comment]
line supports image and audio messages with specific restrictions. We will have to enforce validations to accept these specific types of attachments.

ref:
https://developers.line.biz/en/reference/messaging-api/#image-message
https://developers.line.biz/en/reference/messaging-api/#video-message
https://developers.line.biz/en/reference/messaging-api/#audio-message

**Comment by kanawutc** [comment]
Hello @gvdseype gvdseype

When will you going to finish this?

> Hi, I would like to contribute to this feature. (This would be my first open source contribution)

**Comment by arnoldng** [comment]
Hello, @sojan-official do you have any update?  Thanks

**Comment by sanjayws** [comment]
Hi, it was previously possible to do attachments, but i do not see the icon to do it in 2.18
