### ISSUE TITLE
feat: Ability to receive attachment in Line messenger Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3039]
At the moment only text messages from line messenger are supported in chatwoot, We want to enable support for other types of messages send to chatwoot from line

**Comment by murtaza-webonise** [comment]
Shall I pick this up ?

**Comment by sojan-official** [comment]
@murtaza-bagwala  please go ahead

**Comment by murtaza-webonise** [comment]
@sojan-official I need test line creds. If you could DM me ?

**Comment by sojan-official** [comment]
Hey @murtaza-webonise,  We usually recommend individual developers to get personal credentials since they would need a line account for testing anyways. it's completely free 

https://developers.line.biz/en/docs/messaging-api/getting-started/#using-console

**Comment by murtaza-bagwala** [comment]
@sojan-official what other types of messages are we expecting ? I am working on integrating image/audio/video.

**Comment by sojan-official** [comment]
@murtaza-bagwala  ref: https://developers.line.biz/en/docs/messaging-api/message-types/ 

There are additional message types like stickers, location, etc. But for now let's stick with image, audio, and video. show unsupported message type for other types.
