### ISSUE TITLE
feat: Render video messages in conversations

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3041]
Video Messages in Chatwoot are rendered as file attachments at the moment. We want to convert make them playable right in the conversation window

## Acceptance 
- [ ] Incoming video attachments are labeled with video type 
- [ ] Show a thumbnail of the video message in Chatwindow similar to image attachments
- [ ] On click of thumbnail, open up up the video in a modal where the agent can click and play the video

**Comment by SanjuSudheerM** [comment]
@sojan-official Can I work on this?

**Comment by sojan-official** [comment]
@SanjuSudheerM  sure :)

**Comment by SanjuSudheerM** [comment]
@sojan-official Does this applicable to the widget?

**Comment by SanjuSudheerM** [comment]
Sure @sojan-official, for now, I have raised PR #3201 by adding the video preview on the conversation view in the dashboard.

**Comment by SanjuSudheerM** [comment]
@sojan-official just a housekeeping note, Can we close this ticket as we have covered the tasks mentioned in the PR?

**Comment by pranavrajs** [comment]
Makes sense. :) Closing it now.
