### ISSUE TITLE
Not able to edit or remove campaigns

### ISSUE THREAD

**Issue by jaimyborgman** [chatwoot/chatwoot#3056]
**Describe the bug**

I'm currently testing out chatwoot but after creating a campaign I'm not able to edit nor remove the created item.

**To Reproduce**

1. Go to 'campaigns'
2. Click on 'create an ongoing campaign'
3. Go to the campaigns overview page
4. Not possible to edit or remove the campaign

**Expected behavior**

There should be a possibility to edit and remove a campaign.

**Screenshot**
<img width="1674" alt="Screenshot 2021-09-20 at 15 37 55" src="https://user-images.githubusercontent.com/1233769/134011974-3e3822fa-a735-4a1f-bba3-31072357552b.png">

**Version**
v1.20.0

**Comment by pranavrajs** [comment]
@jaimyborgman It would be helpful if you can share a screencast.

**Comment by jaimyborgman** [comment]
@pranavrajs see screenshot there is no ability to edit/remove a campaign

**Comment by pranavrajs** [comment]
@jaimyborgman There is a horizontal scroll on the table. I guess from the UX it is not clear 🤦 Can you please confirm whether this is the issue?

**Comment by jaimyborgman** [comment]
@pranavrajs haha that's weird i was trying to scroll which didn't work first and after refreshing twice it worked... or nevermind we can close this ticket 😅
