### ISSUE TITLE
Migration Error || Develop Branch

### ISSUE THREAD

**Issue by pushoo-sharma** [chatwoot/chatwoot#3068]
Have referred to this Issue as well [ #1804](https://github.com/chatwoot/chatwoot/issues/1804)

The only difference is my **InstallationConfig id: nil**

**Comment by pushoo-sharma** [comment]
```
== 20200510112339 CreateInstallationConfig: migrating =========================
-- create_table(:installation_configs)
   -> 0.0078s
-- add_index(:installation_configs, [:name, :created_at], {:unique=>true})
   -> 0.0026s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `locked' for #<InstallationConfig id: nil, name: "INSTALLATION_NAME", serialized_value: "{}", created_at: nil, updated_at: nil>
Did you mean?  lock!
/.rvm/gems/ruby-3.0.2/gems/activemodel-6.1.4.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
```

Branch - `Develop`

**Comment by pushoo-sharma** [comment]
Dropped the database and have redone it again the same issue persists.

**Comment by sojan-official** [comment]
@pushoo-sharma  please use `rake db:chatwoot_prepare` instead of `rake db:migrate`. . Some of the migrations are really old and the underlying data scheme would have changed, so for fresh set up creating a database from `db schema:load` is recommended than running migrations all the way from start.

**Comment by sojan-official** [comment]
Feel free to reopen if the issue still persists
