### ISSUE TITLE
[Feature] Ability to use chatwoot in local languages

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#307]
**Is your feature request related to a problem? Please describe.**
- I would like to let my agents use chatwoot in the local language 
- I would like to translate chatwoot completely into my local language

**Describe the solution you'd like**
- language option in agent/account settings so each individual can choose language of choosing
- the organization set to have a particular language as a fallback 

**Describe alternatives you've considered**
N/A

**Additional context**
Ability to onboard users to the software is easier with local language support.

**Road Map**

- Stage 1:  Accounts can have a default language which will be used to translate every aspect related to that account & also the widget

- Stage 2: Accounts can have multiple allowed languages apart from the primary language 
  - if users browser settings give any of the values in the allowed languages, we will show the widget in that language
  - if the language setting doesn't match allowed languages we will fall back to the default language
  - we can also explore doing the same behavior for agent dashboard as well.

- Stage 3:  Agent Setting to Select language from the allowed languages for that account 
  -  If Agent has a language set, the dashboard will be shown in that language else in the default language

**Comment by freinhard** [comment]
What about starting with the channel (website) widget? To me this seems to be a low hanging fruit.

**Comment by sojan-official** [comment]
@freinhard  Considering the whole breadth of the feature, it's a good suggestion to make the customer-facing side translated.  
But the front end of the app is already built with translation in mind.  So it's having the language files for other languages and having a setting for the admin/agent to switch to another available language if we want the agent side to be multilingual. 

When someone starts working on this, I guess they can take up either direction and proceed.

**Comment by sojan-official** [comment]
ref #415

**Comment by zgagne** [comment]
Hi, I would like to work eoth you on this project and it seems like a good way to start here. In fact, we have 3 days left to make this feature. I would like to know how this is going.

- Did someone started the translation?
- What are the languages that we want? (I can do French translation)
- Should we launch a translating project on Crowdin (Free for Open-Source Projects)

**Comment by pranavrajs** [comment]
@zgagne Thanks. We have done a basic setting to save the language in an account. 

These are the list of language we intend to support. We were expecting this to be added in the next couple of sprints.
https://github.com/chatwoot/chatwoot/blob/bab9d663d29c0503ced4feb6809e00946a853f74/config/initializers/languages.rb

> Did someone started the translation?

We were thinking of adding German now.

> What are the languages that we want? (I can do French translation)

I've explained it above. It's great that you can do a French translation. 

https://github.com/chatwoot/chatwoot/tree/develop/config/locales
https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n

These two folders have most of the text used in the system. Please feel free to add an `fra` folder.

> Should we launch a translating project on Crowdin (Free for Open-Source Projects)

Sounds like a good idea.

**Comment by sojan-official** [comment]
@zgagne  we have merged in template german translation for an example. feel free to raise a PR with french :)

**Comment by sojan-official** [comment]
@zgagne we have launched chatwoot on crowdin : http://translate.chatwoot.com/
