### ISSUE TITLE
enhancement: Show prompt on network disconnect

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3088]
Show prompt for reloading the page after network disconnect

**Steps**

- Check app is connected to the internet or not 
- Add a popover near the upper right corner
- On clicking the refresh button, It should have action to refresh the page

**Design**
<img width="350" alt="network-disconnect" src="https://user-images.githubusercontent.com/12408980/134893983-2fec5919-5458-4733-a164-91227b1afb2b.png">

**Reference**
https://github.com/chatwoot/product/issues/57

**Comment by seagalputra** [comment]
Hi @muhsin-k, can I work on this issue? I would like to implement the online/offline status using [Online/Offline events](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events) in Navigator API and it supposed to be enough to check whether user is online or not.

**Comment by muhsin-k** [comment]
@seagalputra Please feel free to go ahead
