### ISSUE TITLE
[CW-1269] feat: Add an option to crop the channel logo/profile avatar

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3089]
- Add the option to crop the channel logo or user avatar before uploading.
- Use https://github.com/Agontuk/vue-cropperjs package

**Referenece**
https://medium.com/swlh/image-crop-and-upload-in-vuejs-2d8d5c73c310

<sub>[CW-1269](https://linear.app/chatwoot/issue/CW-1269/feat-add-an-option-to-crop-the-channel-logoprofile-avatar)</sub>

**Comment by MaximeKoitsalu** [comment]
Hey Muhsin, this projects look really cool. I'd love to try and implement vuejs cropper in your application.

**Comment by sojan-official** [comment]
@MaximeKoitsalu  Feel free to give it a go. Lets us know if you need any help.
