### ISSUE TITLE
Instant preview of chat widget on customisation

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3095]
**Is your enhancement request related to a problem? Please describe.**
It would be more intuitive to create and modify the live chat widget if there is a live preview of it on the side that reflects the changes. 

**Describe the solution you'd like**
![Screenshot 2021-09-27 at 10 35 15 PM](https://user-images.githubusercontent.com/8149408/134954058-d7738b10-178f-4596-aaac-7fde03db2747.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pranavrajs** [comment]
Duplicate #2441

**Comment by pranavrajs** [comment]
Closing it here as #2441 has more context.
