### ISSUE TITLE
[Feature] Agents should be able to edit their details

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#310]
**Is your feature request related to a problem? Please describe.**
As an agent in chatwoot system, I am not able to edit my details 

**Describe the solution you'd like**
Have an interface where I can update basic details like name and display picture

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sojan-official** [comment]
ref: #294  should be able to edit passwords as well

**Comment by pranavrajs** [comment]
@sojan-official This is a duplicate of https://github.com/chatwoot/chatwoot/issues/238
