### ISSUE TITLE
bug: Remove temporary message if message is failed to send

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3104]
**Steps to reproduce**
- Go to a conversation 
- Upload `SVG` file via drag and drop
- Click on the send button 
- Temporary message "Uploading attachment" still showing even though the upload fails

https://user-images.githubusercontent.com/12408980/135248085-a70c1d2f-0cf4-4264-8562-3e937f2cd39b.mov

**Comment by sojan-official** [comment]
closing in favour of #3565
