### ISSUE TITLE
feature: Ability to remove user profile picture

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#3107]
## Backend

- API to delete contact conferring to the following standards 
```
DELETE api/v1/porfile/avatar
# returns head: ok  if successful 
```

## Frontend 
- User should be able to see the delete option in the profile section

<img width="688" alt="Screenshot 2021-09-29 at 4 24 42 PM" src="https://user-images.githubusercontent.com/12408980/135255360-16da8d03-103b-47d8-ad5f-5b1fda2e0ef9.png">

- Clicking on the "Delete Avatar" button should delete the avatar.

**Comment by wweverma1** [comment]
@muhsin-k Can I start working on this feature?

**Comment by sojan-official** [comment]
@wweverma1  Please go ahead

**Comment by wweverma1** [comment]
@sojan-official I'm having problems in setting up the project on my machine.
Can you help me with it?

**Comment by sojan-official** [comment]
@wweverma1  Sure could you provide information on the issues you are facing?

**Comment by rishabhjha708** [comment]
hi @sojan-official can i take this up ?

**Comment by santhosh-chinnasamy** [comment]
@rishabhjha708 yes it requires both backend and frontend changes.

**Comment by wweverma1** [comment]
@sojan-official I am currently learning ruby so I thought I'll try to solve this issue, but I'm unable to solve it. 
So can you please assign it to someone else.

**Comment by santhosh-chinnasamy** [comment]
I am interested in taking this feature, assign it to me.
