### ISSUE TITLE
"Show all" option in the status drop-down for the conversation list

### ISSUE THREAD

**Issue by hanthor** [chatwoot/chatwoot#3109]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I'm always frustrated when I can't see all the conversations in any single view I have to go between resolved snoozed and open and closed to get a good overview of conversations that have come in recently

**Describe the solution you'd like**
There should be an all option either at the top or at the bottom of the list

**Describe alternatives you've considered**

If it would be confusing maybe there could be a separate view for administrators so that they could just get a quick overview of conversations that have come in. But I don't think it would be confusing for agents to have an all option.

**Additional context**

**Comment by pranavrajs** [comment]
@hanthor Isn't this completed by https://github.com/chatwoot/chatwoot/pull/3102? We added an "All" filter in the status filter. Please feel to re-open the issue if it doesn't solve the issue.
