### ISSUE TITLE
Reported 2 new security issues at huntr

### ISSUE THREAD

**Issue by B3EF** [chatwoot/chatwoot#3122]
https://huntr.dev/bounties/ab189b9b-3de3-4739-82bf-d1cd156ebf32/
https://huntr.dev/bounties/61992885-e26c-4fde-b53e-cdbbd260ec67/

**Comment by pranavrajs** [comment]
Closing this here as we would be responding to the security issue in Huntr only.

**Comment by B3EF** [comment]
hi @pranavrajs  its been one month since i have reported the issue , any updates ?
