### ISSUE TITLE
CHATWOOT_INBOX_TOKEN in global_config instead of ENV

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3126]
**Describe the bug**

Can I know why is CHATWOOT_INBOX_TOKEN a part of global_config instead of ENV? If its a part of ENV it would make more sense because the CHATWOOT_INBOX_TOKEN can be dynamically configured for different instances that has been deployed on different environments without having to manually change it each time.

**To Reproduce**

N/A

**Expected behavior**
N/A

**Screenshots**

N/A

**Browser logs**

N/A

**Server logs**

N/A

**Environment**

app.chatwoot.com

**Comment by pranavrajs** [comment]
@srameshr CHATWOOT_INBOX_TOKEN is used to display the chatwoot widget inside Chatwoot. It doesn't make sense to move it to the environment variables. 

> it would make more sense because the CHATWOOT_INBOX_TOKEN can be dynamically configured for different instances

I'm not sure what this means. Can you please provide more context? 

Closing this as it doesn't seem to be something that is improving a workflow.

**Comment by srameshr** [comment]
@pranavrajs INBOX_TOKEN is currently set in a YAML config file. It's not dynamic or on-demand like loading it from ENV file. What I am asking for is to change
```
    #       window.chatwootSDK.run({
    #         websiteToken: '<%= @global_config['CHATWOOT_INBOX_TOKEN'] %>',
    #         baseUrl: BASE_URL,
    #       });
```

to 

```
    #       window.chatwootSDK.run({
    #         websiteToken:  '<%= ENV.fetch('CHATWOOT_INBOX_TOKEN', '') %>',
    #         baseUrl: BASE_URL,
    #       });
```

in vueapp.html.erb
