### ISSUE TITLE
Provide wildcard URL's for campaigns

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3129]
**Is your feature request related to a problem? Please describe.**
The URL for campaigns that trigger a popup when a user is on a particular page requires the use of absolute URLs. But, most real-world use cases consist of very dynamic URLs for the same page. 

For an example of Chatwoot, the account ID for each user gives a different URL for the same page:
```
https://app.chatwoot.com/app/accounts/2931/campaigns/ongoing
https://app.chatwoot.com/app/accounts/1002/campaigns/ongoing
https://app.chatwoot.com/app/accounts/1542/campaigns/ongoing
```

**Describe the solution you'd like**
Provide wildcard matching of URL's. For example the URL in a campaign can be something like this
```
https://app.chatwoot.com/app/accounts/*/campaigns/ongoing
```

**Describe alternatives you've considered**
N/A
**Additional context**
![Screenshot 2021-10-03 at 2 32 05 PM](https://user-images.githubusercontent.com/8149408/135746952-f73af9d4-8478-4897-af70-d327d23e659c.png)

**Comment by sojan-official** [comment]
duplicate: https://github.com/chatwoot/chatwoot/issues/2739
