### ISSUE TITLE
Viber inbox

### ISSUE THREAD

**Issue by ilyakonovalenko** [chatwoot/chatwoot#3148]
**Describe the solution you'd like**
It would be nice to have an ability to add Viber accounts into inboxes. Viber supports free bot API which can be easily used to integrate.

**Additional context**
Viber API: https://developers.viber.com/docs/api/rest-bot-api/

**Comment by hartois** [comment]
Agree. It will be very good. We also need a Viber inbox.

**Comment by pranavrajs** [comment]
Closing this as we would build a plugin system to make it easy to build external inboxes. It doesn't need to be part of the actual product, and can exist as an independent plugin maintained by the community.
