### ISSUE TITLE
VK.com inboxes

### ISSUE THREAD

**Issue by ilyakonovalenko** [chatwoot/chatwoot#3149]
**Describe the solution you'd like**
It would be nice to have a native VK.com inboxes. VK.com is a social network, it has webhooks and API to handle everything which happens in the communities: messages, wall messages, mentions, etc.

**Additional context**
Callback API is here: https://vk.com/dev/callback_api

**Comment by Kr00t** [comment]
This is VK Group - https://vk.company/en/. Biggest IT company in Russia. By [this](https://vk.com/dev/callback_api) link you`ll find DEV API (can change language at footer)

**Comment by pranavrajs** [comment]
Closing this as we would build a plugin system to make it easy to build external inboxes. It doesn't need to be part of the actual product, and can exist as an independent plugin maintained by the community.
