### ISSUE TITLE
Searching Phone number

### ISSUE THREAD

**Issue by sunnyjey** [chatwoot/chatwoot#3159]
**Describe the bug**

The contact number is searchable only **without** Country code prefix. The search fails with country code suffix. 

Suppose +910000000000 is added to the contact. If you search +910000000000 or 910000000000, it fails. But, searching with 0000000000 or 0000000 or any digits except country code works. This is causing a big problem, specially for API calls. 

**To Reproduce**

1. Search any stored contact number with country code prefix. It fails
2. Remove the country code, and then search. This works.

**Expected behavior**

Search should work with and without country code. 

**Environment**

Self hosted installation of Chatwoot. 
Docker/Linux VM installation

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/3241
