### ISSUE TITLE
not updating to new version

### ISSUE THREAD

**Issue by NitinNR** [chatwoot/chatwoot#3164]
like i did all to update the older version to new version from doc but still not working like there is feature in new one called contact import but i'm not able to do so in my self hosted one

if I go for update the older it says already up to date

**Comment by pranavrajs** [comment]
@NitinNR Can you please describe the steps you did to upgrade the instance? Also, can you please follow the steps described in the issue template before raising the request? It is hard to reproduce issues like this without context.

**Comment by NitinNR** [comment]
I am following the steps mentioned here : https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#upgrading-to-a-newer-version-of-chatwoot and checking logs by this : https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#viewing-logs for the errors but nothing seems disturbing here. is there any other way to check the logs for update issue?please let me know,thank you

**Comment by sojan-official** [comment]
@NitinNR check yoururl.com/api and see if the version is updated on the API
