### ISSUE TITLE
Chatbots: Integration with CSML.dev

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3185]
#### Problem Statement:

Chatwoot should natively support chatbots so that people who are self-hosting the solution don't need to rely on third-party services like Dialogflow. 

#### Build a Prototype:

Integrate with CSML.dev (https://github.com/CSML-by-Clevy/csml-engine), the open-source programming language to build bots. Their latest release v1.7.0 has a Postgres connector which makes it easier to bundle it with Chatwoot and deploy as a single solution.

**Comment by voko3456** [comment]
That's will be great 👍

**Comment by pranavrajs** [comment]
Closing as v1 is available in beta.
