### ISSUE TITLE
[CW-2832] Chore: set codeclimate.yml method count to default 20

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#3205]
Refer the change here: https://github.com/chatwoot/chatwoot/pull/3198/files/474f348b2d59094c817ab57ee7a53e78a1ad1b71#diff-e97904d8a0443f46ad2c8ceb5fbe5355e52f6be540378ab8ea1e98870395d7de

<sub>[CW-2832](https://linear.app/chatwoot/issue/CW-2832/chore-set-codeclimateyml-method-count-to-default-20)</sub>

**Comment by sabarish98** [comment]
Hi @tejaswinichile, just reverting the method count value to 20 / removing the introduced code is the change with respect to this issue? I believe we will have to do that after the `contacts_controller` was refactored as service objects / concerns. Is that done?

**Comment by apraditya** [comment]
Hi @sabarish98, I'm interested taking this issue. Can I confirm that what's left is to get the `contacts_controller` refactored as service objects / concern?

**Comment by sabarish98** [comment]
@apraditya, although I had left a comment months ago, I didn't hear back from the @tejaswinichile and thus didn't get it assigned / refractor anything regarding this. So, I may not be the right person to validate this.

@tejaswinichile : Please clarify

**Comment by sojan-official** [comment]
@apraditya Let me assign the issue to you. Refactoring the contacts controller should suffice.

**Comment by pranavrajs** [comment]
Moved to internal tech debt list
