### ISSUE TITLE
Replace textarea with ReplyBox for initiating conversations from contacts

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3206]
**Is your enhancement request related to a problem? Please describe.**
I want access to quick replies as well as attachments while initiating conversations from individual contacts via "New Message" from the contacts screen.

**Describe the solution you'd like**
Replace textarea with ReplyBox component

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by muhsin-k** [comment]
Duplicate: https://github.com/chatwoot/chatwoot/issues/2942
