### ISSUE TITLE
chore: replace dependent: :destroy with :destroy_async

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3221]
Models in chatwoot like Account, Conversations, etc could have. a large number of associations.  replace the dependent : :destroy for these associations with `:destroy_async`

> When we have a large system with multiple layered hierarchies of associated objects, cascading deletes might fail. A model could have associations that are destroyed which in turn trigger other deletions and this can continue down a complex tree. Such cascading deletes could turn out to be quite time consuming and might be rolled back in case of a server timeout error.

ref: 
https://www.bigbinary.com/blog/rails-6-1-allows-associations-to-support-destroy_async-option-with-dependent-key
https://blog.saeloun.com/2020/11/18/rails-6.1-adds-support-for-destroying-dependent-associations-in-the-background.html

**Comment by tejaswinichile** [comment]
@akhilgkrishnan Check this https://github.com/chatwoot/chatwoot/pull/3336
