### ISSUE TITLE
Ubuntu Install Script

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#3230]
**Describe the bug**

https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_20.04.sh script seems invalid.

libreadline that is installed seems to not install v7 as required by the ruby-3.0.2 builder resulting in:

Libraries missing for ruby-3.0.2: libffi.so.6,libgdbm.so.5,libreadline.so.7. Refer to your system manual for installing libraries

`libreadline-dev is already the newest version (8.0-4).`

**Comment by iammattmartin** [comment]
Re-run and was fine. MIght have been a down repo.

**Comment by sojan-official** [comment]
@vishnu-narayanan can we verify ?
