### ISSUE TITLE
Chatwoot Docker not starting after unexpected restart

### ISSUE THREAD

**Issue by one-juru** [chatwoot/chatwoot#3234]
**Chatwoot Docker outputs: Switch to inspect mode.**

I restarted my server yesterday, to apply the newest Updates, and the chatwoot base container wasn't starting again and just outputting the lines "Switch to inspect mode." I tried starting it with portainer and via the command line.

**To Reproduce**

1. Restart Server
2. Try to start docker containers with portainer or command line
3. realize that the docker container instantly stops and outputs "Switch to inspect mode."

**Expected behavior**

Docker container should start and open webinterface

**Server logs**
"Switch to inspect mode." (not more)

**Environment**

Server: Ubuntu 20.04 with Docker and Portainer
Installed like described in the docs.

**Comment by vishnu-narayanan** [comment]
Yeah, it shouldn't require a reinstall. Is it something related to portainer ? Could you ssh in and see if it works with `docker-compose up` from the cli ?

**Comment by one-juru** [comment]
I deleted every container and every persistent storage space, and tried to set it up again - but it still fails with the same error message and stops the container. Resetting the entire VPS would definitely solve that problem (tested on another fresh Ubuntu vm), but I wouldn't like to do that. Do you have any other idea?

**Comment by one-juru** [comment]
EDIT: It seems that the web interface works, even though the chatwoot_base container is stopped and exited with code 0 ("switch to inspect mode").

Do we even need that container? The installation seems to work fine without it...

**Comment by sojan-official** [comment]
@one-juru  the base container is only required to build the web and worker containers.
