### ISSUE TITLE
Feature: Integrate Chatwoot into Slack

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#324]
**Is your feature request related to a problem? Please describe.**
Sometimes I might not be logged in to chatwoot, I would still like to not miss the message. So a slack integration would be super helpful

**Comment by pranavrajs** [comment]
@sojan-official / @sony-mathew Let us prioritise this for this sprint.

**Comment by sony-mathew** [comment]
@pranavrajs Sure thing. Before we start the integration, I would like to have more clarity on this. 

1. Is it a two-way integration that we are looking at meaning, are we only pushing the notification messages onto slack or are we also receiving the replies from slack and adding it to the conversation?
2. Would it be an app in the Slack apps marketplace or API based on the user?

**Comment by pranavrajs** [comment]
> Is it a two-way integration that we are looking at meaning, are we only pushing the notification messages onto slack or are we also receiving the replies from slack and adding it to the conversation?

To start with we will only have messages from Chatwoot being sent to Slack, not the other way around.

> Would it be an app in the Slack apps marketplace or API based on the user?

It would not be in the Slack app marketplace.

**Comment by pranavrajs** [comment]
Closed via #974
