### ISSUE TITLE
Blank CSAT Report but records exist in DB.

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#3242]
**Describe the bug**
Installed version 1.21.0 and ran a couple of chats with CSAT. We did 3 CSATs post chat, but i can't see them in reporting. 

**To Reproduce**
Installation: - Plain script install with Ubuntu 20.04. No other customizations or changes. 

1. Setup Telegram bot to receive and send chats
2. Close or "Resolve" a chat, then the other end has a link for CSAT.
3. Other side does CSAT successfully, verified data exist in PG DB csat_survey_responses
4. Go to reporting
5. All other reports are fine except CSAT which shows "--" in all fields 

**Expected behavior**
1) When generating CSAT report, it should show up all the CSATs as expected

**Screenshots**
1) Normal chat ends with CSAT, someone fills it up and completes the rating
![image](https://user-images.githubusercontent.com/25242465/137736199-4860ea73-0546-47b5-972c-97ffcd9b700f.png)
![image](https://user-images.githubusercontent.com/25242465/137736286-f1e4236a-9096-4989-93da-c3ce01915d42.png)

2) Backend PGDB data exists
![image](https://user-images.githubusercontent.com/25242465/137736369-99718ae6-ee63-4abd-9b4c-de744060fb12.png)

3) However, report is blank
![image](https://user-images.githubusercontent.com/25242465/137736440-3e2a28b3-ec93-4e9a-bd58-2b3537e35799.png)

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/4027/files
