### ISSUE TITLE
Z order on the left hide button is wrong

### ISSUE THREAD

**Issue by hanthor** [chatwoot/chatwoot#3243]
![image](https://user-images.githubusercontent.com/5840441/137775136-6d81688c-ffa5-479d-883c-4cb843bffcf5.png)

It will show even when viewing an image 

![image](https://user-images.githubusercontent.com/5840441/137775207-9dfb39d6-ef6a-48ac-aab4-8951b401ac57.png)

**Comment by jayeclark** [comment]
@pranavrajs This is tagged hacktoberfest, but at a quick glance I didn't see contributor guidelines. Is this issue open to a community fix?

**Comment by superspike7** [comment]
can I work on this?

**Comment by sojan-official** [comment]
@jayeclark  yep, please feel free to go ahead. ref: https://www.chatwoot.com/docs/contributing-guide  

@superspike7 will pass it on to you if @jayeclark doesn't have the bandwidth.

**Comment by jayeclark** [comment]
@sojan-official Thanks - I do have the bandwidth & will start on it this morning!

**Comment by sojan-official** [comment]
@jayeclark Please take your time :)
