### ISSUE TITLE
bug: Telegram attachment captions are not rendered

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#3244]
**Describe the bug**

When sending an attachment of any type with a caption (image, file, audio, etc), the message received in Chatwoot does not include this caption. This can make conversations be out of context in some situations.

**To Reproduce**

1. Go to Telegram and send your bot any image (or file) and type a caption before sending it. 
<img width="440" alt="Screen Shot 2021-10-18 at 11 38 22 PM" src="https://user-images.githubusercontent.com/66124192/137810393-a12bd772-55c6-425f-a29f-58b5ff47da39.png">

2. View the received message on Chatwoot dashboard.
3. See error (the image or file is received without the caption).
<img width="545" alt="Screen Shot 2021-10-18 at 11 42 25 PM" src="https://user-images.githubusercontent.com/66124192/137810885-713e021b-c52b-4c96-b5f2-43072f88a483.png">

**Expected behavior**

Captions received along with attachments on Telegram should be rendered in Chatwoot as well.

# Extra:

this could have its own issue, but since it's related to the functionality here, I thought of mentioning it:

When receiving files on Telegram, the names of these files are not rendered properly in Chatwoot.
<img width="362" alt="Screen Shot 2021-10-18 at 11 35 08 PM" src="https://user-images.githubusercontent.com/66124192/137811086-ddd1232c-d74b-4a36-8ebd-61834b6c8361.png">

and extensions of the files as well (this was supposed to be a `zip` file)
<img width="413" alt="Screen Shot 2021-10-18 at 11 45 40 PM" src="https://user-images.githubusercontent.com/66124192/137811317-c37a5ad8-1014-46ba-88c3-566659fb2b5a.png">

**Comment by virajbahulkar** [comment]
> Thanks, @WevrLabs for reporting the scenario, we will look into it. 👍🏼
> 
> @virajbahulkar Let us know if you need any help while fixing it.

@tejaswinichile I have added telegram bot but I'm not receiving messages on chatwoot dashboard, I have also assigned agent to it. Can you help me out here? I think I'm missing something
