### ISSUE TITLE
HTML emails are not rendered properly in the Slack Integration

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3247]
<img width="472" alt="Screenshot 2021-10-20 at 12 10 59 PM" src="https://user-images.githubusercontent.com/2246121/138041185-21b3205c-1617-47b3-9403-fe59e74dbd19.png">

![image](https://user-images.githubusercontent.com/2246121/138041225-14d30b60-034a-4c73-9603-045ec11219fa.png)
--- 

Email channel replies are not rendered properly in the Slack channel. This creates a nuisance for the users as the Slack channel is flooded with HTML text. 

As an immediate fix, we can disable all email channels messages sent to Slack. Instead of the message, a link to view the message can be sent.

**Comment by pranavrajs** [comment]
@tejaswinichile Please assess the effort, if it is less effort, please go ahead with the implementation.

**Comment by tejaswinichile** [comment]
**Notes**
Fix: If the channel is email either remove the HTML tags or apply the style in the HTML tags.

@pranavrajs I will go ahead with the implementation not much difference in effort between the quick fix and the actual fix.
