### ISSUE TITLE
Can we add annotate to the project?

### ISSUE THREAD

**Issue by mukesh4139** [chatwoot/chatwoot#326]
Hi everybody,

I was going through the project with the intention of understanding different models and their associations and eventually see if I can contribute in some meaningful way. I personally feel model annotations give great insight into the models. Can I open a PR for this?

Link to the GEM:
https://github.com/ctran/annotate_models

**Comment by sojan-official** [comment]
Hey @mukesh4139  

think it will be a good idea to have some documentation/annotations in the code, especially when we are striving to make this repo a beginner-friendly one.  Feel free to take this up. 

Will be happy to help if you have any questions over how the data models are tied together . Connect us on discord https://discord.gg/cJXdrwS or over the GitHub issues 

good luck

**Comment by sojan-official** [comment]
closed in #327
