### ISSUE TITLE
feat: Support additional attachment types in Chatwoot

### ISSUE THREAD

**Issue by crottolo** [chatwoot/chatwoot#3270]
I use twilio account in sandbox mode.

**To Reproduce**

1. Go to 'chat with client'
2. Click on 'nothing'

after send message (client) with attachments same as xls xlsx, docx , you can't download a file.
csv format work

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**server:**
 - OS: Ubuntu 20.04
 - Browser chrome
 - Latest version, clean install today

see the screnshot
![Schermata 2021-10-23 alle 17 46 48](https://user-images.githubusercontent.com/16843729/138563044-52d39438-bff0-4b6a-862d-865e83721f44.png)

twilio screenshot
![Schermata 2021-10-23 alle 17 51 11](https://user-images.githubusercontent.com/16843729/138563160-e6fd391d-d8de-46b6-b84a-1a0428fab5f5.png)

webhook message from chatwoot
![Schermata 2021-10-23 alle 17 56 38](https://user-images.githubusercontent.com/16843729/138563284-0da4255b-d5c2-4ad3-b381-d2cbb0e82877.png)

**Comment by crottolo** [comment]
> hi, if you send attachments (client, not agents of chatwoot) xlsx,xls,doc or docx i can't download the file... You don't have the link for for download the file...
> 
> the link is visibile only for csv file I
> 
> ![Schermata 2021-10-29 alle 18 16 50](https://user-images.githubusercontent.com/16843729/139468917-479037ec-701a-49ad-b78a-1709f620bcc8.png) @pranavrajs

did I correctly describe the issue?

**Comment by sojan-official** [comment]
@crottolo thanks for describing the issue in detail, I think it is because we are not supporting .docx and .xlsx file types internally. we will take this up as an enhancement.

**Comment by crottolo** [comment]
> @crottolo thanks for describing the issue in detail, I think it is because we are not supporting .docx and .xlsx file types internally. we will take this up as an enhancement.

perfect. I think, if possibile, for all file not recognized, the link for download. After we can adjust the code for preview or other features...

**Comment by sojan-official** [comment]
We will work on supporting the following attachment types.
- [ ] docx
- [ ] xlsx
- [ ] rar
- [ ] zip
