### ISSUE TITLE
Agent to see only 'mine'

### ISSUE THREAD

**Issue by koral99digital** [chatwoot/chatwoot#3272]
Hello everyone!

i'm not sure if this is a bug, or this is the how it meant to be...
i noticed that agents have "Mine" and "All" tabs.
in "All" tabs, they see all conversation that are in the system.

is there a way to disable this? the idea is that agents will only see conversations that are assigned to them

**Comment by joshymg** [comment]
This is a badly needed feature. My client is about to shut down my project because of this. Back to searching for an alternate.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4216
