### ISSUE TITLE
Fix "Rubocop/Metrics/BlockLength" issue in lib/tasks/auto_annotate_models.rake

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#328]
Block has too many lines. [45/30]

https://codeclimate.com/github/chatwoot/chatwoot/lib/tasks/auto_annotate_models.rake#issue_5de1313a7c47d10001000256

**Comment by mukesh4139** [comment]
Can we exclude this file from rubocop? 
Rubocop suggests `Align the elements of a hash literal if they span more than one line.`

I think the readability of the current version is better than the aligned one.

Eg. 

Suggested by Rubocop
```ruby
my_hash = {
  abc: 10,
  def: 20,
  ghijklmno: 30,
  p: 40,
  qrstuvwyxzw: 50
}
```

vs
Current Version
```ruby
my_hash = {
  abc                : 10,
  def                 : 20,
  ghijklmno      : 30,
  p                   : 40,
  qrstuvwyxzw : 50
}
```

**Comment by sojan-official** [comment]
closing this we added this to ignore list.
