### ISSUE TITLE
Conversation doesn't show Contact details set via setUser()

### ISSUE THREAD

**Issue by lowlyocean** [chatwoot/chatwoot#3295]
**Describe the bug**

Sometimes, even if window.$chatwoot.user.identifier_hash and window.$chatwoot.identifier are correct, some new conversation started from widget doesn't show in Inbox with expected Contact details. Instead it generates some random user like **something-blah-13** and the email etc. are left blank.

**To Reproduce**

1. Create Website Inbox
2. Add widget to your app
3. Run setUser() with email, identifier, name, identifier_hash
4. Start Conversation and see on the Dashboard that the conversation does NOT have expected Contact info set with setUser()

**Expected behavior**

I would expect that the Contact info would appear as set by setUser()

**Screenshots**

N/A

**Browser logs**

No relevant logs or errors in browser console

**Server logs**

Will extract any parts that are asked, as needed

**Environment**

v1.21.1 Self-hosted on Heroku

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 94.0.4606.81

**Additional context**

N/A

**Comment by lowlyocean** [comment]
Is there an ability to pull in non-minified version of the widget from deployed instance on Heroku, so as to be able to set breakpoints and better investigate the issue from my end?

**Comment by sojan-official** [comment]
@lowlyocean  were you able to resolve this issue?

**Comment by lowlyocean** [comment]
Even though $chatoot.user is populated, it didn't mean that setUser succeeded in setting Contact info. In my app's Login response handler, I added a listener for chatwoot:ready which calls setUser. I also just call setUser once manually, in case chatwoot:ready fired already before login handler.
