### ISSUE TITLE
Authorised Instagram page does not show up in the select element after facebook auth

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3307]
**Describe the bug**

After authorizing both FB Pages and Instagram accounts of which the user is an admin of, the authorized IG accounts does not show up in the "Choose Page" select box and on the contrary, FB pages are available inside the select box.

**To Reproduce**

1. Go to Inboxes and Add New Inbox
2. Click on Messenger and Authorize both IG and FB pages and accounts.
3. Now after the modal close, click on the "Choose Page" select box and search for the IG account you authorized via FB Auth and its not visible.

**Expected behavior**

IG accounts should be shown

**Screenshots**

![Screenshot 2021-10-29 at 4 17 58 PM](https://user-images.githubusercontent.com/8149408/139422205-d4b82073-2832-4a63-8464-7c86f21d868e.png)

**Browser logs**

NA

**Server logs**

NA

**Environment**

app.chatwoot.com

Chrome Mac OS

**Additional context**

NA

**Comment by srameshr** [comment]
@tejaswinichile Could you let me know if I am missing something here?

**Comment by iammattmartin** [comment]
I don't believe you see it separately. It'll come thought the same messenger inbox as facebook messages.

At least, that is how ours is working.

**Comment by sojan-official** [comment]
There will only be a single Facebook page that would show up in the list that represents the messenger profile for both the Facebook page and Instagram profile.
Also you can connect a Facebook page to only one inbox in a chatwoot instance ( across all the accounts ).

**Comment by srameshr** [comment]
@sojan-official I cross-checked all of it. I still don't get any messages I send to my IG account on my app.chatwoot.com instance. The same happens for my private hosted instance as well.
Also, sometimes, my private chatwoot instance agent account sends a bot message titled "GROUP NOT FOUND" when I try to add an IG channel

**Comment by tejaswinichile** [comment]
Do you see the messages from test webhooks to your instance? check if the webhooks are working?

**Comment by srameshr** [comment]
It was a bug with FB account for me. It worked with a new account
