### ISSUE TITLE
Integrate with botpress chatbot

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3308]
BotPress ChatBot is open source chatbot support building advanced bot with flow builder
https://github.com/botpress/botpress

**Comment by iammattmartin** [comment]
Duplicate of #2502

**Comment by sojan-official** [comment]
closing in favor of #2502

**Comment by sanjayws** [comment]
I made a very simple yet workable Botpress integration with CW using the great guide from here https://github.com/chatwoot/rasa-agent-bot-demo. Do reach out, happy to share my very rudimentary php code.

**Comment by drdaga** [comment]
> I made a very simple yet workable Botpress integration with CW using the great guide from here https://github.com/chatwoot/rasa-agent-bot-demo. Do reach out, happy to share my very rudimentary php code.

can u help i want to integrate chatwoot with botpress
