### ISSUE TITLE
TEAM_AVAILABILITY translations not working properly

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#3314]
**Describe the bug**

check the translation for `TEAM_AVAILABILITY.Offline`  it's not getting translated.
https://app.chatwoot.com/app/accounts/1/conversations/10155

**To Reproduce**

1. Go to https://www.chatwoot.com/
2. Click on google to translate web browser
3. Scroll down to when you see the message "We are away at the moment"
4. The message should be in the respective translations.

**Expected behavior**

It should display message in respective language.

**Screenshots**
<img width="582" alt="Screenshot 2021-11-02 at 8 07 53 PM" src="https://user-images.githubusercontent.com/10827585/139868611-45c2cdad-9885-4092-864d-92069af9ede8.png">

**Comment by akhilgkrishnan** [comment]
@tejaswinichile I can pick this

**Comment by vishnu-narayanan** [comment]
@akhilgkrishnan To add additional context, we manage translations via Crowdin. This issue is due to the missing Dutch translation in this file https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/widget/i18n/locale/nl.json#L13. 

Please use https://translate.chatwoot.com/

**Comment by vishnu-narayanan** [comment]
`TEAM_AVAILABILITY.OFFLINE` should be `Op dit moment zijn we niet aanwezig`

**Comment by akhilgkrishnan** [comment]
Thanks @vishnu-narayanan . Btw there are couple other languages having this issue eg: Malayalam

**Comment by vishnu-narayanan** [comment]
Yes, that is because not all languages are 100%  complete. You can check the progress for a language at https://translate.chatwoot.com/chatwoot

**Comment by akhilgkrishnan** [comment]
@vishnu-narayanan I can only see the en.json on widget folder
