### ISSUE TITLE
Enable quote support in the editor

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#3315]
<img width="550" alt="Screenshot 2021-11-02 at 8 11 49 PM" src="https://user-images.githubusercontent.com/10827585/139870192-a6a80b6d-0eaa-41f3-b6fb-e071cdb257a8.png">
 

> The quote was initialized in the editor 

But when I posted it, it appeared with the angle bracket `<` as shown in the screenshot.

**Comment by LiamAshdown** [comment]
@sojan-official This appears to be fixed as screenshots below.

<img width="573" alt="Screenshot 2023-07-22 at 16 31 50" src="https://github.com/chatwoot/chatwoot/assets/43280985/c110a1a4-51c3-4f19-8d24-d6f448dbeda9">
<img width="599" alt="Screenshot 2023-07-22 at 16 32 00" src="https://github.com/chatwoot/chatwoot/assets/43280985/878cd9d5-60e9-4306-a205-5b480647c3f4">

**Comment by sojan-official** [comment]
@LiamAshdown  Thanks for testing this out. 
I couldn't replicate it on my end as well.
