### ISSUE TITLE
Display account id in account settings

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3317]
<img width="488" alt="Screenshot 2021-11-03 at 11 41 15 AM" src="https://user-images.githubusercontent.com/2246121/140023965-df747f44-2b9d-4068-80ad-348dc4cd6a63.png">

In the API docs, we are asking the users to use the account id. It is not displayed anywhere in the application. The devs would need to deduce it from the URL which is a bad UX.

Todo:

- [ ] Display Account ID in the account settings screen

**Comment by SanjuSudheerM** [comment]
@pranavrajs Can I work on this?

**Comment by pranavrajs** [comment]
Sure, please feel free to.

**Comment by SanjuSudheerM** [comment]
@pranavrajs Could you share your idea on where to put the account Id (any UX available), or shall I proceed as in the image?

<img width="500" alt="Screenshot 2021-11-08 at 7 40 06 PM" src="https://user-images.githubusercontent.com/23727388/140756979-03b15681-43d3-4505-98fa-ce9377a477c9.png">

**Comment by sojan-official** [comment]
<img width="1176" alt="Screenshot 2021-11-11 at 10 27 20 PM"  src="https://user-images.githubusercontent.com/73185/141337948-a769682d-b308-42d3-a130-30005e026518.png">


@SanjuSudheerM let's use the code block instead, you can see an example on the profile settings page.
