### ISSUE TITLE
Include previous messages for more context when sending @mention/@assign email notification

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#3321]
**Is your enhancement request related to a problem? Please describe.**
Right now, an agent gets an email notification when they are mentioned/assigned in a conversation. 

The `@mention` notification right now only includes the message in which they are mentioned. The `@assign` notification right now does not have any information other than the assignment.

**Describe the solution you'd like**
Include previous messages in the conversation when sending an email notification. This would make the email notifications more informative and useful. 
 
**Describe alternatives you've considered**
A possible iteration over this would be to include more details about the conversation in email notification that is available in the sidebar.

**Additional context**
n/a

**Comment by shivamsinghchahar** [comment]
@vishnu-narayanan Can I take this up?

**Comment by vishnu-narayanan** [comment]
@shivamsinghchahar Thank you for your interest. This ticket has not been vetted yet. Let us confirm that first. 

@sojan-official @tejaswinichile Could you please share your thoughts on this?
cc: @pranavrajs

**Comment by tejaswinichile** [comment]
@vishnu-narayanan we can do this, my concern is that what if the very last comment doesn't make any sense should we still show that?

 If we decide this then @shivamsinghchahar  can pick this up.
It's a doable ticket won't take much of a input from our side.

How to show the message?
: We can show the notification as quoted text, and the assigned conversation text.

CC @sojan-official

**Comment by vishnu-narayanan** [comment]
>my concern is that what if the very last comment doesn't make any sense should we still show that?
Yes, since making sense of something like that is out of scope at the moment(NLP). I was thinking of sending a maximum of the last 3 messages if available.

**Comment by sojan-official** [comment]
We could implement a mailer similar to our conversation summary mailer and add the last 3-5 messages in the conversation.

**Comment by vishnu-narayanan** [comment]
Thank you @tejaswinichile @sojan-official. Assigning this to @shivamsinghchahar. 

@shivamsinghchahar The consensus is to include the last 3-5 messages. Please feel free to start work on this and let us know if you have any questions.

**Comment by shivamsinghchahar** [comment]
@vishnu-narayanan I have raised a PR, could you take a look?
