### ISSUE TITLE
Issue with SMTP

### ISSUE THREAD

**Issue by roshanjonah** [chatwoot/chatwoot#3328]
### Discussed in https://github.com/chatwoot/chatwoot/discussions/3327

<div type='discussions-op-text'>

<sup>Originally posted by **roshanjonah** November  4, 2021</sup>
I am using Helm Charts, I declared the following variables to use Postmark to deliver emails. 

```
 MAILER_SENDER_EMAIL: "notify@xxx.com"
 SMTP_ADDRESS: "smtp.postmarkapp.com"
 SMTP_AUTHENTICATION: "cram_md5"
 SMTP_USERNAME: "PM-T-outbound-xxx"
 SMTP_PASSWORD: "SbV3hSQDsgWv-xxx"
 SMTP_ENABLE_STARTTLS_AUTO: "true"
 SMTP_OPENSSL_VERIFY_MODE: "none"
 SMTP_PORT: "587"
 ```
 
 But for some reason, none of the emails would go out. When I try to reset the password link on the UI to trigger email sending, it gives me the following error in the 'worker' logs - https://justpaste.it/2k7e0</div>

**Comment by SimonHausdorf** [comment]
@roshanjonah would be nice if you would have let us know what the issue was.
