### ISSUE TITLE
Limit the number of agents a particular user can create 

### ISSUE THREAD

**Issue by willph** [chatwoot/chatwoot#3330]
If it were possible to determine how many agents each user could create.
User X = 5 agents, Y = 2 agents, z = 3..........

In SUPER_ADMIN account could have the option when creating each user to define the number he could create agents.

I hope you can understand, I don't know if I posted it correctly.

I didn't find this in the documentation. 
If so, please indicate where.

Congratulations to the project!!!
Thanks!

**Comment by pranavrajs** [comment]
@willph I don't completely understand the problem here. Do you want to limit the number of users an admin can invite? What is the use case?

**Comment by willph** [comment]
> @willph I don't completely understand the problem here. Do you want to limit the number of users an admin can invite? What is the use case?

It's just that I saw on the chatwoot.com site that there is a free plan for up to 2 agents.

With that I found interesting the part of limiting the number of agents that a user could create.

But I didn't find anything about it in the documentation.

**Comment by pranavrajs** [comment]
Closing this here as we will take it up in https://github.com/chatwoot/chatwoot/issues/3773
