### ISSUE TITLE
Using anycable as an adapter for actioncable

### ISSUE THREAD

**Issue by brunoprietog** [chatwoot/chatwoot#3331]
[Anycable](https://anycable.io/) is an actioncable adapter written in Go that improves latency and scalability of actioncable dramatically. The main advantage is that you don't have to change any of the code, just the adapter and run the rpc server and anycable go. This would help reduce infrastructure costs for you and those using the self hosted version.

It would be great if you could consider using anycable, considering the great benefits and the little effort it takes to set it up.

Thanks!

**Comment by pranavrajs** [comment]
@brunoprietog Thanks for the suggestion, we have already looked at AnyCable as an alternative if something isn't scaling. As far as we know, nobody has reported any issues with scaling to a larger customer base. Is this issue related to any issues in scaling the usage?

**Comment by brunoprietog** [comment]
Thanks for your response! No, it's not really because of scaling issues, but a reduction in memory usage is always welcome, especially on small servers. I guess implementing anycable wouldn't require much effort, maybe the complicated part would be the upgrade only.

**Comment by pranavrajs** [comment]
This was part of our strategy if the action cable doesn't scale with traffic. It seems like the existing setup works without issue, so we would not be considering this soon.

Closing this as this is a future enhancement, would not be picked up immediately.
