### ISSUE TITLE
Command bar for productivity

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3335]
The command bar is supported by most of the applications right now. The palette that opens when clicking on `Cmd + K` is really useful to navigate through the application. I've been using Superhuman for quite some time, I use the command bar more often than the keyboard shortcuts. 

Todos: 

- [ ] Research about the existing projects which can be integrated directly to Chatwoot (open-source as well as closed source ones like commandbar.com)
- [ ] List out the features that need to be supported. List all the global features as well route-aware commands.

**Comment by fayazara** [comment]
This is the library which we were discussing internally - https://github.com/ssleptsov/ninja-keys
Demo - https://ninja-keys-demo.vercel.app/

Here's a reactjs library called kbar which looks really good. - https://kbar.vercel.app/

**Comment by fayazara** [comment]
For commands we could write a few global bus events and add them in a seperate component and import it globally in the dashboard route component.

**Comment by fayazara** [comment]
@pranavrajs  Here's a quick demo of the ninja-keys library. Ion icons are not working as expected, looking for a workaround.

https://user-images.githubusercontent.com/15716057/140773290-d0bddbb7-f438-47fc-adb8-93ac0ae4db3c.mp4

**Comment by muhsin-k** [comment]
@fayazara This is nice ❤️

**Comment by pranavrajs** [comment]
@fayazara Awesome man! This is nice. Let me know if you need any help.
