### ISSUE TITLE
Enhancement: Show unread marker or widget toggle button

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3343]
**Context**

The widget shows the unread messages as bubbles when it arrives or page is reloaded. But when the user chooses to close the unread bubble view there is no visual cue on widget to remind the user that there are unread messages. We could solve this by adding a red marker on the bubble.

- Show only when unread count sent from widget is greater than 0

![image](https://user-images.githubusercontent.com/1277421/140864870-2eb09847-82ee-4576-a62e-75d6d99ba390.png)

**Comment by SanjuSudheerM** [comment]
@nithindavid Can I work on this?

**Comment by nithindavid** [comment]
@SanjuSudheerM sure 👍
