### ISSUE TITLE
[CW-2835] No special characters in the web widget - Inter font

### ISSUE THREAD

**Issue by ghost** [chatwoot/chatwoot#3347]
**Describe the bug**

If you try to use some special characters in the web widget like for example: `ą, ę, ć, ż, ó` - they do not look like they are supposed to do.

**To Reproduce**

You can just send a message that contains these special characters in the web widget.

**Expected behavior**

Special characters should appear just like any other characters.

**Screenshots**

<details>

<summary> Preview </summary>

![obraz](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/835c404e-bdfb-42a5-b8b7-93afbb43625c/54fdc94a-bcfb-4b2b-9066-460631fdd7ef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi84MzVjNDA0ZS1iZGZiLTQyYTUtYjhiNy05M2FmYmI0MzYyNWMvNTRmZGM5NGEtYmNmYi00YjJiLTkwNjYtNDYwNjMxZmRkN2VmIiwiaWF0IjoxNzAxNDA4MzkwLCJleHAiOjE3MDE0OTQ3OTB9.EojH_gSRaS705nGpnq9myoacCpfpVJqicUJkD5FLOOw)

</details>

**Environment**

Self hosted installation deployed on Heroku.

**Additional context**

That's more of a question than additional context, but why are fonts downloaded instead of specifying `url` to download them in the `@font-face` in `widget_fonts.scss`?

Can we change these fonts, so they support special characters like these that I mentioned?

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2835](https://linear.app/chatwoot/issue/CW-2835/no-special-characters-in-the-web-widget-inter-font)</sub>

**Comment by pranavrajs** [comment]
Closing this in favor of https://github.com/chatwoot/chatwoot/issues/9762
