### ISSUE TITLE
Support Facebook post comments

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#3355]
**Is your feature request related to a problem? Please describe.**
Support reading and replying to comments on a post via the dashboard Messenger inbox channel

**Describe the solution you'd like**
New conversations in the Messenger inbox channel or a new channel

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by iammattmartin** [comment]
Already discussed in 2096

**Comment by sojan-official** [comment]
closing in favor of #2096

**Comment by srameshr** [comment]
@sojan-official Oops, I forgot to look up the issue before posting it.
