### ISSUE TITLE
Unable to Create Super Admin Account

### ISSUE THREAD

**Issue by aw-0** [chatwoot/chatwoot#3356]
**Describe the bug**

When following https://www.chatwoot.com/docs/self-hosted/monitoring/super-admin-sidekiq/ on a 1-Click Heroku Instance, I receive the following error when running `s = SuperAdmin.create!(email: "admin@xyc.com", password: "yourpassword")`:

```
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client': connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (ActiveRecord::ConnectionNotEstablished)
	Is the server running on that host and accepting TCP/IP connections?
/app/vendor/bundle/ruby/3.0.0/gems/pg-1.2.3/lib/pg.rb:58:in `initialize': connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (PG::ConnectionBad)
	Is the server running on that host and accepting TCP/IP connections?
```

**To Reproduce**

1. Create a 1-Click Chatwoot Heroku Instance
2. Follow https://www.chatwoot.com/docs/self-hosted/monitoring/super-admin-sidekiq/
3. Execute `s = SuperAdmin.create!(email: "admin@xyc.com", password: "yourpassword")`

**Expected behavior**

A Superadmin account is created and can access /super_admin on the Chatwoot site.

**Screenshots**

![image](https://user-images.githubusercontent.com/43796708/141177802-b468e3a8-cb1e-4fe5-86d7-f6ed7169d8dc.png)

**Environment**

1-Click Deploy Heroku Instance

**Comment by sojan-official** [comment]
@aw-0 If your installation is on Heroku, you need to run the rails console in the Heroku instance. In the screenshot, is seems like you are running the console in your local machine.

ref: https://devcenter.heroku.com/articles/getting-started-with-rails5#run-the-rails-console

**Comment by aw-0** [comment]
@sojan-official I'm running it in the instance using `heroku ps:exec -a [APP_NAME]`. Is that the right way to do it? Thanks for your help :)

**Comment by sojan-official** [comment]
@aw-0  I haven't tried sshing to dyno .  try `heroku run rails console` instead. you might have to specify the app name parameter as well.

**Comment by aw-0** [comment]
Yep, that worked. Appreciate the support!
