### ISSUE TITLE
[CW-33] 'Close' Campaign

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#3363]
**Is your enhancement request related to a problem? Please describe.**
Yes. If you have multiple campaigns on different pages, or one say on the root domain (https://www.domain.com), which will trigger each time the page is changed, this is bad UX.

Whilst there is an X that shows, if you close this and go to another page, it pops up again. I don't believe it should do this repeatedly given the intent to not engage with the invite has been closed.

<sub>[CW-33](https://linear.app/chatwoot/issue/CW-33/close-campaign)</sub>

**Comment by tejaswinichile** [comment]
@iammattmartin Can you add a screencast video of your issue? We will take a look at it in the future release.

**Comment by iammattmartin** [comment]
I'm not sure it needs a screen cast.

i.e put campaign on https://www.domain.com

Go to home page of that site, it pops up. 
Change to another page, it'll pop up.

Close the popup with the X, change page, it'll pop-up again.

If the user presses the X to close the popup. It should not happen again, either for that session or cookie. 

It will cause annoyance for someone that keeps appearing when they've no intent with interacting with it.

**Comment by muhsin-k** [comment]
@iammattmartin Yes. I am able to reproduce this. Maybe we can add the option to disable triggering campaigns globally for the current session if the user closes the campaign.

cc @pranavrajs @sojan-official

**Comment by iammattmartin** [comment]
I'd say that would be a good thing.

**Comment by sojan-official** [comment]
The constant nudging from multiple campaigns wouldn't be the ideal experience.

But would it make sense to disable it for a certain amount of time like x hours or n number of days?  You might want to retarget the user again when you add a new campaign ( if you have a better offer or a new sale that's running )

**Comment by pranavrajs** [comment]
@sojan-official Adding this to production discussions for prioritization.

**Comment by mxsxs2** [comment]
Is there any progress on this?

**Comment by pranavrajs** [comment]
@mxsxs2 We are prioritising this soon.

**Comment by pranavrajs** [comment]
Sounds good to me.
