### ISSUE TITLE
How to disable conversation continuity?

### ISSUE THREAD

**Issue by PyB1l** [chatwoot/chatwoot#3368]
We have a self hosted version of chatwoot, and we would like to disable conversation continuity in email threads 
 without disabling pre-chat form.

Is there any way to accomplish this feature?

**Comment by tejaswinichile** [comment]
@PyB1l 
1. You can remove the forward rule from your email inbox, through email account settings.
2. And run these queries on your rails console
```
account = Account.first
account.disable_features('channel_email')
account.save!
```

**Comment by PyB1l** [comment]
Thanks for your quick response. Do you think that It is also posible to close conversasion when an agent presses resolve?
I mean that even the client could not conitnue sending messages to the same conversation that an ganet has marked as resolved, but instead create a new one

**Comment by sojan-official** [comment]
@PyB1l  you can enable CSAT surveys for your inbox. when the survey is enabled after a conversation is resolved. Chatwoot will prompt the contact to rate the conversation and start a new one when required.

**Comment by PyB1l** [comment]
This workaround imlpies that the user must click on CSAT? Or it works anyways if CSAT is enabled?

**Comment by sojan-official** [comment]
<img width="427" alt="Screenshot 2021-11-12 at 4 56 56 PM" src="https://user-images.githubusercontent.com/73185/141459902-a2e3ba22-bb27-4f8e-823c-ceeebd450c98.png">

CSAT is optional

**Comment by PyB1l** [comment]
Thanks is should do the trick.. One last question (I promise!). When the agent resolves the conversation and the CSAT is displayed, is there a way to refresh the session? So that if a refersh tha page it should display the prechat form again and not the 
CSAT button

**Comment by sojan-official** [comment]
@PyB1l  Not directly without writing code. But you could write a custom service that listens to chatwoot webhook events and create a new conversation against the contact using the APIs.

**Comment by PyB1l** [comment]
Is this a feature that could possible get into chatwoot someday?

**Comment by sojan-official** [comment]
@PyB1l  its something in our roadmap to have a setting that would let users choose the behavior they want 
- either close conversations completely on the resolution 
- or let contacts to reopen resolved conversations

**Comment by PyB1l** [comment]
I tried the following verifing tha t the aacount is correct but still when a user is

```account = Account.first
account.disable_features('channel_email')
account.save!

**Comment by tejaswinichile** [comment]
@PyB1l Have you removed the forwarder email too?

**Comment by PyB1l** [comment]
I am not sure where to do that, we use Amazon email service for our
instalation

**Comment by tejaswinichile** [comment]
@PyB1l  Check the 5th point you must have configured the forwarder rule for some email id correct? When you will remove that and run `account.disable_features('channel_email')` this will ensure that you won't receive any email from conversations.

But if you are using the same email for notification on conversation created or conversation assigned those you will still receive.

**Comment by PyB1l** [comment]
@tejaswinichile I think these instructions refer to email channel, while my issue is in website channel, I need to disable chatwoot sending emails every time an agent sends a respose and the user is offline

**Comment by PyB1l** [comment]
We have a general email service setup that is needed for the agents (password change, converseation notifications etc). We just need to disable the mails goinh to chat clients

**Comment by tejaswinichile** [comment]
@PyB1l Let me check into this more.
> We have a general email service setup that is needed for the agents (password change, converseation notifications etc). We just need to disable the mails goinh to chat clients

**Comment by PyB1l** [comment]
Thanks @tejaswinichile the big picture is that in standart website channel with pre-chat form enabled, we need to disable sending emails to widget clients (although we get the emails from either pre chat form either `setUser` method)

**Comment by PyB1l** [comment]
@sojan-official If I just comment out from `chatwoot/app/workers/conversation_reply_email_worker` the 
following lines 9-14

```
    # send the email
    if @conversation.messages.incoming&.last&.content_type == 'incoming_email'
      ConversationReplyMailer.with(account: @conversation.account).reply_without_summary(@conversation, last_queued_id).deliver_later
    else
      ConversationReplyMailer.with(account: @conversation.account).reply_with_summary(@conversation, last_queued_id).deliver_later
    end
```

Would this stop sending an email transcript to users?

**Comment by sojan-official** [comment]
@PyB1l  you will only need to comment out the reply_with_summary  part. without_summary is responsible for delivering replies to the conversations that come in via email channel.

**Comment by PyB1l** [comment]
Thanks!

**Comment by PyB1l** [comment]
@sojan-official Thanks for the insight. Do you think it would be better to change `chatwoot/app/moidels/message.rb` line 194 method `can_notify_by_mail` to this:

```
 def can_notify_via_mail?
    return false
  end
```

Would this affect only transcript or email channel as well?
