### ISSUE TITLE
Feature request: Email signature

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#3378]
It would be great if each agent could set in their **profile settings** a signature that would be automatically added to any outgoing emails (from email Inbox, but also conversation continuity, chat transcript).

There would be a text field that would allow HTML tags, so we could have a signature with logo image, bold text, etc.

I love Chatwoot, but this is the last missing feature preventing me from using it in Production.

**Comment by Robinjoeh** [comment]
Yeap - this should be highly prioritized. I helped a few organizations to test Chatwoot and this was the most critical thing for all of them. Using the email channel without signatures is a no-go for almost all organizations.

Even adding a basic text field (that accepts plain HTML), which is then appended to outgoing emails (sent by the specific user) would be sufficient to start with, and expand it with a more advanced WYSIWYG-editor at a later stage.

**Comment by jean-philippeansel** [comment]
@Robinjoeh

Exactly! Basic text field that accepts plain HTML is enough, and users can host images externally if they need to include company logo, social network icons, etc.

This is the main issue (along with #3304 - All outgoing emails are sent from accounts@chatwoot.com) that prevents us from using Chatwoot.

**Comment by jdsalchow** [comment]
This would be helpful indeed :)

**Comment by pranavrajs** [comment]
- [ ] API for saving Email Signature 
- [ ] UI to select email signature

**Comment by sdobbelaere** [comment]
+1 email signature is a must to use the service.  Branding is important.
