### ISSUE TITLE
Translation issue - outgoing email sender (FROM)

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#3380]
**Describe the bug**

By default, all emails sent by agents have the following "from" header in any language:
**Agent_Name from CompanyName <emailaddress@domain.com>**

**To Reproduce**

1. Go to Profile Setting and set your language to "French"
2. Go to Email Inbox and add an answer to a conversation
3. Login to the recipient email address to open the message you've just sent

**Expected behavior**

The FROM header should be **Agent_Name de CompanyName <emailaddress@domain.com>**, not **Agent_Name from CompanyName <emailaddress@domain.com>**

Same issue with conversation continuity, chat transcripts.

**Comment by akhilgkrishnan** [comment]
I can pick this up

**Comment by tejaswinichile** [comment]
@akhilgkrishnan Go ahead let us know if you face any issues.
