### ISSUE TITLE
Invalid emails can be passed in cc_emails, bcc_emails parameter

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3388]
**Context:** There is no validation for cc_emails, bcc_emails in the send message API

**Method & URL**: POST `/api/v1/accounts/<account-id>/conversations/<conversation-id>/messages`

**Todo**:
- [ ] Add email validations for cc_emails, bcc_emails params
- [ ] Throw a 422 error in the API if an invalid array of emails is passed

**Comment by vedhapre** [comment]
Hi is this issue still open? I can take it

**Comment by tejaswinichile** [comment]
@vedhapre Yes, the backend validation is not there. You can pick this up

**Comment by juls0730** [comment]
Is this issue still open, I see a pull request that has been closed before it was merged mentioned, if it is I could pick this up

**Comment by sojan-official** [comment]
@juls0730  please go ahead.
