### ISSUE TITLE
SMTP_TLS enviroment variable is missing in the document

### ISSUE THREAD

**Issue by hzilex** [chatwoot/chatwoot#3396]
**Describe the bug**

Some smtp server need ssl authentication to send mail. If with out set SMTP_TLS to true. It will get 'EOFError: end of file reached' in chatwoot-workers log. I think the SMTP_TLS may need to list in the document.

**Comment by sojan-official** [comment]
@hzilex thanks for reporting this,

# Tasks 
- [ ] Mention the environment variables `SMTP_TLS` and `SMTP_SSL` in .env.example 
- [ ] Mention the same in our documentation : https://github.com/chatwoot/docs/blob/main/docs/self-hosted/configuration/environment-variables.md

**Comment by vinayak-gaikwad** [comment]
Hello, can I work on this?

**Comment by tejaswinichile** [comment]
@vinayak-gaikwad Sure, don't forget to raise PR against doc too.

**Comment by vinayak-gaikwad** [comment]
In the case of doc should I create a new issue or just raise PR with fixes

**Comment by tejaswinichile** [comment]
@vinayak-gaikwad You can mention this issue in the PR description.
