### ISSUE TITLE
Feature: Super Admin dashboard

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#340]
**Is your feature request related to a problem? Please describe.**
Its hard to know all the env variables i need to set up to get chatwoot up and running 

**Describe the solution you'd like**
Have a super admin dashboard similar to wordpress, where the user can set up all the required values to get chatwoot server up and running 

![wordpress dashboard](https://i1.wp.com/wordpress.org/support/files/2018/10/install-step5_v47.png)

**Describe alternatives you've considered**
have sh scripts or clear instructions on deploying to the server. 

**Additional context**

**Comment by pranavrajs** [comment]
Closing as the super admin console is complete. 

Created a new ticket for initial setup. https://github.com/chatwoot/chatwoot/issues/900
