### ISSUE TITLE
Chatwoot Over Nginx And CloudFlare - Assets Problem

### ISSUE THREAD

**Issue by hiagodotme** [chatwoot/chatwoot#3407]
**Describe the bug**

I have an android app, i am setting up a webview to provide support via chatwoot.
It turns out that the images of the channels are not loaded, this is due to my infrastructure.

**To Reproduce**
On the edge I have CloudFlare it receives the connection via HTTPS and forwards it via HTTP to my NGIXN reverse proxy. So far so good, it turns out that when referencing the image, Chatwoot informs an endpoint (in https), but this same endpoint forwards to the final address of the image, but using HTTP, Cloudflare after that makes another redirect to the image by placing the address again under the https.

**Environment**

Docker Linux

Is this a bug? Is there a way around? In the WebView of my android app I get Mixed Content error.

**Comment by vishnu-narayanan** [comment]
Closing this for now. Please reopen if this issue still exists.
