### ISSUE TITLE
not able to send video attachment via whatsapp 360dialog 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3427]
not able to send video attachment via whatsapp 360dialog

**Comment by pranavrajs** [comment]
@voko3456 Can you please share file type you are trying to send?

**Comment by voko3456** [comment]
mp4,wmv

**Comment by DDoerner** [comment]
I don't know whether it's the same issue, but when we send a file with whatsapp (be it a image or video) then we don't get notified via our slack integration. The file is visible in the chatwoot portal, but neither the file nor a notification about it is sent with the slack integration. As we solely work via the integration and not with the portal itself, we would miss these files. 

@voko3456 is this the same setup that you're having problems with?

**Comment by pranavrajs** [comment]
@voko3456 Is this still an issue?

@DDoerner Slack case might be different. We can investigate it.

**Comment by voko3456** [comment]
@pranavrajs the issue was fixed im able to send video attachment so im going to close this issue
