### ISSUE TITLE
Cannot set password

### ISSUE THREAD

**Issue by Xolsurf3r** [chatwoot/chatwoot#344]
**Describe the bug**
Cannot set new password(other than from default user) for newly registered user after email verification.

**To Reproduce**
1. Go to Verification Email
2. Click on Verify Now
3. Enter NEW password in the boxes
4. See error.

**Comment by sojan-official** [comment]
@Xolsurf3r  could you also post a screenshot / logs if any ?

**Comment by sojan-official** [comment]
@Xolsurf3r  there was a minor bug in the URL generation in mailers, that is fixed now.  
Ensure that the correct  value for environment variable `FRONTEND_URL` is set. 

https://www.chatwoot.com/docs/environment-variables

Lets us know if it's still reoccurring.
