### ISSUE TITLE
chore: Update Inbox members swagger documentation

### ISSUE THREAD

**Issue by wasannoom** [chatwoot/chatwoot#3441]
**Describe the bug**

I try to use API for getting members in the inbox but got 404

**To Reproduce**

1. Use API same as (https://www.chatwoot.com/developers/api/#operation/get-inbox-members)
2. Got 404

**Expected behavior**

Should return a list of members

**Comment by wasannoom** [comment]
@pranavrajs I use this path. I'm not sure is correct or not?
`/api/v1/accounts/3/inbox_members?inbox_id=15`

and get error

`<!DOCTYPE html>
<html>

<head>
	<title>The page you were looking for doesn't exist (404)</title>
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<style>
		body {
			background-color: #EFEFEF;
			color: #2E2F30;
			text-align: center;
			font-family: arial, sans-serif;
			margin: 0;
		}

		div.dialog {
			width: 95%;
			max-width: 33em;
			margin: 4em auto 0;
		}

		div.dialog>div {
			border: 1px solid #CCC;
			border-right-color: #999;
			border-left-color: #999;
			border-bottom-color: #BBB;
			border-top: #B00100 solid 4px;
			border-top-left-radius: 9px;
			border-top-right-radius: 9px;
			background-color: white;
			padding: 7px 12% 0;
			box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
		}

		h1 {
			font-size: 100%;
			color: #730E15;
			line-height: 1.5em;
		}

		div.dialog>p {
			margin: 0 0 1em;
			padding: 1em;
			background-color: #F7F7F7;
			border: 1px solid #CCC;
			border-right-color: #999;
			border-left-color: #999;
			border-bottom-color: #999;
			border-bottom-left-radius: 4px;
			border-bottom-right-radius: 4px;
			border-top-color: #DADADA;
			color: #666;
			box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);
		}
	</style>
</head>

<body>
	
	<div class="dialog">
		<div>
			<h1>The page you were looking for doesn't exist.</h1>
			<p>You may have mistyped the address or the page may have moved.</p>
		</div>
		<p>If you are the application owner check the logs for more information.</p>
	</div>
</body>

</html>`


but I try with other path still get 404
`/api/v1/accounts/3/inboxes/15/inbox_members`


but I try with only inboxes I get 200 normally
`/api/v1/accounts/3/inboxes/15`

`{
    "id": 15,
    "avatar_url": "xxxx"
    "channel_id": 15,
    "name": "CWA-DEMO-000-EN",
    "channel_type": "Channel::Api",
    "greeting_enabled": false,`

**Comment by sojan-official** [comment]
@wasannoom we will need to update the swagger docs I think. 
Here is the postman call for the same : https://www.postman.com/chatwoot/workspace/chatwoot-apis/request/162770-efac7f9b-5cb6-4f94-b1a3-67070b2b54b4 


the correct URL is `{{host}}/{{api_version}}/accounts/{{account_id}}/inbox_members/{{inbox_id}}`

example :
```
curl --location --request GET 'http://localhost:3000/api/v1/accounts/1/inbox_members/1' \
--header 'api_access_token: AGShdXcmDjvVyxBB5ixXJ8E4'
```

**Comment by wasannoom** [comment]
@sojan-official It works! Thank you for your answer :D
