### ISSUE TITLE
bug: Cannot copy text content from sidebar

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3454]
With the new draggable sidebar feature there is no way one could copy text content from sidebar.

- We might need to disable the drag over content inside the content area
- Make only the title or collapsed box draggable, Show a different mouse pointer to tell user it's draggable `cursor: grab;`

https://user-images.githubusercontent.com/1277421/143174208-bc4c8f96-f0b1-4415-9096-ce4f00478b09.mov

@muhsin-k @iamsivin Any thoughts ?

**Comment by sojan-official** [comment]
@muhsin-k  @iamsivin  Let prioritize this based on the bandwidth.
