### ISSUE TITLE
setCustomAttributes call fails due to HMAC failed error

### ISSUE THREAD

**Issue by 1t5j0y** [chatwoot/chatwoot#3458]
**Describe the bug**

On an inbox with 'Enforce User Identity Validation' enabled, I am calling the JS setUser and setCustomAttributes methods. The setUser call is successful but the setCustomAttributes call fails.

Error response for the request to `PATCH https://<redacted>/api/v1/widget/contact?website_token=<redacted>` is
Code: `401 Unauthorized`
Body: `{"error":"HMAC failed: Invalid Identifier Hash Provided"}`

The previous call to the same endpoint to set the user returns a 200.
 
**To Reproduce**

1. Enable 'Enforce User Identity Validation' on a website inbox
2. Call setUser and setCustomAttributes javascript methods to set the user attributes
3. See error for the setCustomAttributes call

**Expected behavior**

From the docs, HMAC validation should only apply to the `setUser` call so the `setCustomAttributes` call shouldn't fail due to an HMAC failed error.

**Screenshots**

![image](https://user-images.githubusercontent.com/54208632/143210058-4c6fdb5d-23dc-4f84-896c-a7ae2d41b9c8.png)

**Environment**

Self hosted. Docker. Chatwoot v1.22.0

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [Firefox]
 - Version [94.0]

**Comment by kacperc-activenow** [comment]
I am having the same issue, but with some GET requests, is it normal? When I tried to replicate it on localhost, params used to verify HMAC - identifier and identifier_hash returned `nil` for the failed requests for some reason.

Also users get identified properly, but custom attributes are not being set at all.

![obraz](https://user-images.githubusercontent.com/60870179/144194699-d63ca425-d0eb-4c66-9790-ea6a34e56391.png)

**Comment by aswindevps** [comment]
Both setUser and setCustomAttribues calls are tested in develop branch and it's working when we enforce the user identity validation. Please check the attached screen recording.
https://user-images.githubusercontent.com/5848740/152125125-0ec86423-9124-4c12-9109-d724ca290d3c.mp4

@pranavrajs please validate from your side.

**Comment by pranavrajs** [comment]
@1t5j0y It seems like the latest changes have a fix for this issue. I'm no longer able to reproduce this on develop.
