### ISSUE TITLE
Bug on Signup

### ISSUE THREAD

**Issue by kodermax** [chatwoot/chatwoot#3468]
**Describe the bug**

**To Reproduce**

1. Go to '/app/auth/signup'

**Screenshots**

![image](https://user-images.githubusercontent.com/590985/143599393-1c5b4c4f-c7c3-40cb-9d70-fef6b6c3de29.png)

**Comment by sojan-official** [comment]
@kodermax  is it on a self-hosted instance or on app.chatwoot.com ?

**Comment by startshineye** [comment]
on a self-hosted instance I also encountered such a problem

**Comment by startshineye** [comment]
@kodermax Have you solved this problem？

**Comment by startshineye** [comment]
https://github.com/chatwoot/chatwoot/issues/1752;

**Comment by kodermax** [comment]
Yes, it works

**Comment by pranavrajs** [comment]
@kodermax Thanks for confirming. Closing as the issue is solved.
