### ISSUE TITLE
Error installing server

### ISSUE THREAD

**Issue by Alarees** [chatwoot/chatwoot#3470]
**Describe the bug**

after the installation compleated, i get the flowing error (We're sorry, but something went wrong. If you are the application owner check the logs for more information.)

**To Reproduce**

1. run codes on [doc page](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm)
```
wget https://raw.githubusercontent.com/chatwoot/chatwoot/master/deployment/setup_20.04.sh -O setup.sh
chmod 755 setup.sh
./setup.sh master
```
2. entering yes when prompted about domain setup
3. navigateing to my site, then see the error

**Screenshots**

![error](https://user-images.githubusercontent.com/18484561/143620200-7f307419-d275-4a8d-a21f-c649ff4290bf.png)

**Browser logs**

```
Failed to load resource: the server responded with a status of 500 ()
```

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-90-generic x86_64)
 - Browser : Chrome

**Additional context**
i have a fully new ubuntu server, i install `ispconfig` on it and then install chatwoot server

**Comment by vishnu-narayanan** [comment]
@Alarees I am not able to reproduce this issue.  I just tried a fresh install and it seems to be working as expected. From your logs, it seems the installation part is successful.  The SSL on your domain also seems okay and thus `nginx` part should also be fine. 

Could you check the rails server logs when you are trying to access the webpage ?

**Comment by Alarees** [comment]
Hi,
i just reinstall ubuntu on my server, and then install chatwoot server and it works fine,
and after that i install ispconfig
it looks like some of ispconfig configrations doesn't work will with chatwoot server
