### ISSUE TITLE
chore: Add validation for account auto resolution time

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3474]
At the moment a person can configure even value `999999` for account auto resolution time in the account settings page. Which in the backend would give an `::DatetimeFieldOverflow: ERROR: timestamp out of range`

- [ ] Set maximum auto resolution time period to 999 days
- [ ] Frontend validation to show error if range crosses that
- [ ] Backend validation to prevent values saved over 999 days

**Comment by WevrLabs** [comment]
While on this, is it possible to add another validation for auto-resolution, by excludeling conversations where the last message is not from agent. That is, executing auto-resolve only on conversation where the last message or reply is from an agent. 

Case scenario here is that a month we had a situation where internet access to agents and staff was ceased for a period of approximately 30 hours nationwide, and our auto-resolve was set to 24 hours, so we missed some conversations from users that were opened during this blackout window.

**Comment by shivamsinghchahar** [comment]
@sojan-official I can take this up.

**Comment by shivamsinghchahar** [comment]
@sojan-official Raised a PR for this here: https://github.com/chatwoot/chatwoot/pull/3651
