### ISSUE TITLE
Please fix the Caprover Upgrade instructions!

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#3475]
**Describe the bug**

I follow [the instructions](https://www.chatwoot.com/docs/self-hosted/deployment/caprover#upgrading-chatwoot-installation) but my chatwoot remains stuck on version `v1.10.0`.

**To Reproduce**

1. Go to Caprover -> apps -> chat-web -> deployment -> 5
2. Paste this exact block:
```
{
  "schemaVersion": 2,
  "dockerfileLines": [
    "FROM chatwoot/chatwoot:latest",
    "RUN chmod +x docker/entrypoints/rails.sh",
    "ENTRYPOINT [\"docker/entrypoints/rails.sh\"]",
    "CMD bundle exec rake db:chatwoot_prepare; bundle exec rails s -b 0.0.0.0 -p 3000"
  ]
}
```
3. Click deploy
4. See version in Chatwoot Account settings unchanged at v1.10.0

**Expected behavior**

See version greater than this one year old version

**Environment**

This is a self-hosted Caprover instance. The host is Ubuntu 18.04 with latest updates.

**Additional context**

Docker appears to not get the actual latest chatwoot/chatwoot image and the list of images is a testament of my in vane struggle with updates "9 months ago", too:

```
# docker images | grep chat-web
img-captain-chat-web                3         ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                4         ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                5         ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                6         ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                7         ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                latest    ae43a49fe91f   9 months ago    756MB
img-captain-chat-web                2         6d513298726e   12 months ago   756MB
img-captain-chat-web                1         afcc70673179   14 months ago   815MB
img-captain-chat-web                0         2df7ba02f640   15 months ago   22.1MB
```

I was tempted to pin the version with a tag that is not "latest" as I had issues on other systems with docker's use of "latest" (we have a "latest" already. Why download it again?) but looking at [Docker Hub](https://hub.docker.com/r/chatwoot/chatwoot/tags) I was not sure ... is there no version number assigned to the same digest as the "latest" tag??

**Comment by Giszmo** [comment]
So I found #1347 to probably be the relevant duplicate which makes me want to change the topic: Please fix the Upgrade instructions! They don't say you have to do anything but paste that block of gibberish (to the laydeveloper) and hit "deploy".

**Comment by sojan-official** [comment]
@Giszmo  Thanks for fixing this.
