### ISSUE TITLE
Bug: Invalid error message when updating a contact

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3476]
When updating contact information from the sidebar, with a phone number that is already associated to another contact, the system displays the invalid error "Duplicate email address" instead of "Duplicate phone number" 

## Steps to reproduce

1. Create contact a with phone number: +12222222
2. Create contact B
3. Navigate to contact pannel, select contact B and try to update contact b with phone number: +12222222
4. "Duplicate email address" error is displayed instead of "Duplicate phone number error"

**Comment by thedev105** [comment]
@sojan-official can I take this issue?

**Comment by pranavrajs** [comment]
@thedev105 Sure, please go ahead.

**Comment by thedev105** [comment]
@pranavrajs PR #3500 is ready for review!
