### ISSUE TITLE
Enhacement : Ability for admin to send out password reset email for agents

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#348]
**Is your enhancement request related to a problem? Please describe.**
Admin should be able to send reset password email to the agent

**Describe the solution you'd like**
-  Login as admin 
- Click Settings 
- Click Agents 
-  Click edit next to an agent 
- In the edit modal, have option to reset agent password 
- this will send an email to the agent with a link to reset password 

**Mock** 

![Screenshot 2019-12-06 at 11 47 22 AM](https://user-images.githubusercontent.com/73185/70300779-7210a380-181e-11ea-950e-ad54d716b88a.png)

**Changes required**

- [ ]  API to trigger the email to the agent 
- [ ] Front end changes to add the link in the modal  &  Trigger the API

**Comment by sojan-official** [comment]
@mukesh4139

**Comment by mukesh4139** [comment]
@sojan-official this looks fine. I have not worked on Vue before. But I think there is the minimal change required on the frontend, I will figure out.

**Comment by sojan-official** [comment]
Fixed in #351  🎉

**Comment by shgninc** [comment]
I need to reset password, manually as admin, not by sending email.
How can i do that?
