### ISSUE TITLE
Allow always online status

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3484]
**Is your enhancement request related to a problem? Please describe.**
When the inbox is primarily covered by a bot, and no agents are online (because they don't need to be) the chat widget will say "away at the moment".

**Describe the solution you'd like**
A way to keep the status on online. Furthermore, it would be nice if instead of choosing between a list of "replies within x", let the inbox administrator customize it freely. Example: Replies immediately, or no such message at all.

**Comment by sojan-official** [comment]
@brentco one option is to configure business hours in a way that you are available 24/7 .  The chat widget will rely upon the business hour configuration instead of the agent online status.

**Comment by brentco** [comment]
> @brentco one option is to configure business hours in a way that you are available 24/7 . The chat widget will rely upon the business hour configuration instead of the agent online status.

That indeed looks promising, however, when I save the time slots, it resets to time windows of 8 hours after saving.

**Comment by sojan-official** [comment]
@brentco  could you try configuring between 12:00 am to 11:30: pm (23.5 hours) slots?

**Comment by brentco** [comment]
@sojan-official Yep that works, I assume that's a small bug then?

**Comment by sojan-official** [comment]
> @sojan-official Yep that works, I assume that's a small bug then?

yep. logged https://github.com/chatwoot/chatwoot/issues/3491 to track the same.

**Comment by pranavrajs** [comment]
Closing this as 24 * 7 option is now configurable via UI. Ref: https://github.com/chatwoot/chatwoot/pull/4018
