### ISSUE TITLE
Creating a new conversation for a user does not replace it in web widget

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3485]
**Describe the bug**
I was told in the past that when you create a new conversation for a certain user, the chat widget will load the new conversation instead of the existing one. This however doesn't happen. Above that, it will take a page refresh to have the chat widget realize it.

This ties in to being able to actually END a conversation so that a user can no longer talk in that conversation and must create a new one. CSAT covers this somewhat, but is not ideal and cannot be triggered by API (I'll create another ticket for that).

**To Reproduce**

1. Have a conversation via chat widget
2. Call the API endpoint to resolve the current conversation
3. Call the API endpoint to create a new conversation
4. Nothing happens on user side

**Expected behavior**

The web widget (and API) should present a new and empty conversation instead of its existing old one. There are no errors or anything, just doesn't seem to work.

**Environment**

A self hosted docker environment.

**Desktop (please complete the following information):**
 It happens always on every device.

**Comment by sojan-official** [comment]
@brentco  the new conversation should be created with the same contact_inbox  under which the conversation is happening in the chat widget.

**Comment by brentco** [comment]
Hi @sojan-official, it seems like a mistake on my end. Does it matter if this API call is invoked with bot API key or administrator API key? In my tests both seem to work (after page refresh) while in my backend calls it doesn't work... so I'll have to investigate on my end! I'll close this issue if it was my mistake.

**Comment by sojan-official** [comment]
@brentco You can create a conversation using either API key it should be fine. Bot the objects have permissions to access the conversation to create an end point. it's just when it comes to other endpoints bot API key has limited access.

**Comment by pranavrajs** [comment]
@brentco Is this still an issue? Please feel free to reopen if you still face the issue.
