### ISSUE TITLE
feat: Make conversation continuity in website channel optional

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3486]
**Is your enhancement request related to a problem? Please describe.**
I can't find where to disable transcripts. When the conversation is resolved (or there are new messages) the user always gets an email with the transcript.

**Describe the solution you'd like**
I would like to control this behavior by being able to disable such email communication unless explicitly requested by the user (at the end of a conversation for example) or explicitly sent by the agent.

**Describe alternatives you've considered**
Remove the email from the user so it cannot send emails...

**Comment by sojan-official** [comment]
fixed in https://github.com/chatwoot/chatwoot/pull/3817
