### ISSUE TITLE
API to actually CLOSE a conversation

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3487]
**Is your enhancement request related to a problem? Please describe.**
Related to #3485 , when I resolve a conversation, the user does not see anything and can still talk in the conversation. This does not fit in a session-based chat approach where every time a user wants to chat, it starts a session (and blank conversation).

**Describe the solution you'd like**
An API to actually CLOSE a conversation so that the user can no longer type in it. Not via CSAT because then the user is required to give input and there is a button to start a new chat. Alternatively, CSAT could be used but be able to customize the CSAT form.

**Describe alternatives you've considered**
CSAT and it's almost perfect, however I don't want to force the user to have to send a message. The normal flow of our bot setup is that when a user presses the widget button, it sends a "webwidget_triggered" event and the bot starts talking. However, with CSAT, a message from the user is forced as first event in a conversation and that's different from the "normal" flow.

**Additional context**
I want to have a more conventional session-based chat approach rather than a "continuous thread" that chatwoot does now.
1. User enters a page
2. User opens chat and it starts a new conversation
3. Bot and/or agent talk to the user
4. Agent or user can end the conversation

**Comment by brentco** [comment]
Will experiment a bit more with CSAT and I will update this ticket if necessary.

**Comment by pranavrajs** [comment]
We have an issue with ending the conversation. You can see the details here. https://github.com/chatwoot/chatwoot/issues/2830

I guess this issue would be solved via https://github.com/chatwoot/chatwoot/issues/2827. If so, please close this one :) We will take this up in the next releases.

**Comment by brentco** [comment]
Ok, closing! Perhaps this can be used as extra information.
