### ISSUE TITLE
API and SDK for custom events

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3488]
**Is your feature request related to a problem? Please describe.**
Today we had a requirement where when the agent or bot did something on their end, something happened in the customer's browser. For this, we created an additional websocket connection over which we send events.

**Describe the solution you'd like**
Considering Chatwoot already has a websocket connection, and already controls the chat widget via events, perhaps it is low hanging fruit to extend this to where we can send events to a customer through API, and listen to these events on the chat widget side in JavaScript.

**Describe alternatives you've considered**
A secondary websocket, separate from chatwoot.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/2995
