### ISSUE TITLE
Ability as super admin to confirm a user via GUI

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3489]
**Is your enhancement request related to a problem? Please describe.**
In our test environment we create agents with fake profiles (and thus fake emails). However, they are unusable until they are confirmed and a developer has to step in and execute rails commands to manually activate the user.

**Describe the solution you'd like**
As super admin or regular admin, be able to verify agents without them having to access their email.

**Comment by yangbailiang** [comment]
@brentco How can I activate my account manually

**Comment by brentco** [comment]
@yangbailiang With the following steps:
1. run command `bundle exec rails console`
2. ```user = User.find_by(email: "<agent email here>")
user.confirm
user.password = '<password here>'
user.save
```
Note that the password is probably not necessary to pass in. The important part is that you call `confirm` and `save`.

**Comment by sojan-official** [comment]
You can confirm the user from super admin dashboard now but setting a confirmed at date
<img width="1202" alt="Screenshot 2022-03-28 at 11 53 24 PM" src="https://user-images.githubusercontent.com/73185/160462207-0e82be05-0c9e-46a5-bf3f-f198ac8392b4.png">

**Comment by voarsh2** [comment]
I don't see where this super admin dashboard is? How do I get it? I am the "super admin"
