### ISSUE TITLE
[CW-34] Disable user input in CSAT

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3490]
**Is your enhancement request related to a problem? Please describe.**
The normal flow of a bot conversation in my use case, is that Chatwoot sends a webwidget_triggered event to my bot and the bot starts talking. This event gets sent when the user clicks on the chatwoot bubble.

When resolving a conversation, and having CSAT enabled, I can achieve what I described in #3487. However, CSAT shows a message field that the user must fill in as a "first message" which is different to the regular "click on chatwoot bubble" flow and doesn't make much sense for a bot unless it does some advanced interpretation like NLP to automatically adapt to the user's input.

**Describe the solution you'd like**
"Start new conversation" starts a new conversation without the user filling something in.

**Describe alternatives you've considered**
Creating a new conversation via API but it doesn't seem to work: #3485 

<sub>[CW-34](https://linear.app/chatwoot/issue/CW-34/disable-user-input-in-csat)</sub>

**Comment by brentco** [comment]
@pranavrajs I suppose this is related to #2830 and could be fixed with that?

**Comment by scmmishra** [comment]
Closing this, find reference to the resolution here: https://github.com/chatwoot/chatwoot/issues/2830#issuecomment-923016026
