### ISSUE TITLE
user id for window.$chatwoot.setUser

### ISSUE THREAD

**Issue by kodermax** [chatwoot/chatwoot#3493]
What the user id should I pass to setUser(userId,...)?

**Comment by brentco** [comment]
Anything of your choosing as long as it's unique to a user.

**Comment by sojan-official** [comment]
> Anything of your choosing as long as it's unique to a user. In my case it's the logged-in user's database ID.

as mentioned by @brentco it is recommended to pass the unique identifier you have in your system for the logged-in user.
