### ISSUE TITLE
API Contact search + fails

### ISSUE THREAD

**Issue by Stephen-Lobo** [chatwoot/chatwoot#3495]
**Describe the bug**
Search contact via API fails if contact number contains **+** Prefix 

**To Reproduce**

1. Search any contact with + and without + prefix through GET Command Via API / Postman
2. For eg use contact number +123456789. The search does not works. 
3. Now search same contact number without +, it works. 

**Expected behavior**
API Get command for search should also consider when contact number contains + prefix.

**Environment**

Self hosted
Latest chatwoot version

**Comment by pranavrajs** [comment]
Hey Stephen, Can you please share a screencast? It seems like the API is working for me with or without + sign, and I see that we have covered this issue already here https://github.com/chatwoot/chatwoot/pull/3241/files

**Comment by Stephen-Lobo** [comment]
There is definitely search bug in current version. Pls see screenshot video:

https://user-images.githubusercontent.com/87435610/144429646-1fdf6c60-b996-49fd-91f5-01600be73ab6.mov

**Comment by Stephen-Lobo** [comment]
@pranavrajs 

Friendly bump.

**Comment by sojan-official** [comment]
@pranavrajs  Seems like the previous PR opted for filtering the value on the frontend.  We could probably remove that and just implement a filter in the backend.

**Comment by pranavrajs** [comment]
Closing this as the issue is resolved in recent releases.
