### ISSUE TITLE
Feature: Desktop notifications for agents

### ISSUE THREAD

**Issue by brentco** [chatwoot/chatwoot#3497]
**Is your enhancement request related to a problem? Please describe.**
Audio notifications are not enough to alert an available agent to a new assigned conversation.

**Describe the solution you'd like**
Browser desktop notifications would be a bit better.

**Describe alternatives you've considered**
Mail notifications, but not as quick and maybe not as visible unless email client is customized.

**Comment by pranavrajs** [comment]
@brentco We have browser push notifications already in Chatwoot. You can enable them in your profile settings. Can you please share whether you are using a self-hosted installation, if so are you on the latest version?

**Comment by brentco** [comment]
@pranavrajs Ah, we are running self-hosted via Docker. The current version is v1.18.1. We are waiting for some upcoming features to upgrade everything.

**Comment by sojan-official** [comment]
@brentco  We have made some significant changes over the recent versions. You could take a look at the changelog here 
ref: https://www.chatwoot.com/changelog/ 

Browser push notifications are already available in chatwoot. 

In the older version, you can configure them by adding the environment variables mentioned in this doc
https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#push-notification 

in the newer versions, 1.20+ chatwoot will auto-generate these keys and require no additional configuration.
