### ISSUE TITLE
Add twitter as a channel

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#35]
- [ ] Configure Twitter app for Chatwoot
- [ ] Admins should be able to add their pages
- [ ] Subscribe to the webhook events in Twitter SDK

**Comment by pranavrajs** [comment]
@sojan-official Please break it into Vue/Rails work if needed.

**Comment by muhzi4u** [comment]
@pranavrajs I would like to work on twitter channel integration.

**Comment by sojan-official** [comment]
Closing this issue for now since twitter DMs are working. 
Will take up the subsequent work in the next release.
