### ISSUE TITLE
SMS Channel Integration

### ISSUE THREAD

**Issue by joer14** [chatwoot/chatwoot#350]
**Is your feature request related to a problem? Please describe.**

I'm curious what the community thinks about adding support SMS as a channel/integration.
It seems like it could be really useful to provide this type of functionality as an option, as it would allow users to interact with the support team without using a web interface. 

**Describe the solution you'd like**
Maybe allow admin to configure Twilio or AWS SNS credentials, and associated phone numbers that text messages are sent to, and the support agents assigned to the given number. When a user texts the number, we would automatically create a record of them and associate prior chats with them in the future.

**Describe alternatives you've considered**
This interface (SMS) is pretty distinct from existing options. It might be possible to do a work around by using SMS to email gateway.

**Additional context**
This is a pretty standard and compelling feature in some other support apps like Zendesk.

**Comment by pranavrajs** [comment]
@joer14 This is definitely something we are considering for next sprint. We have received the same feedback from other users. We appreciate PRs if you think you can contribute.

**Comment by pranavrajs** [comment]
This would be a stretch goal for this sprint.
