### ISSUE TITLE
bug: CCing people from other conversation

### ISSUE THREAD

**Issue by Robinjoeh** [chatwoot/chatwoot#3503]
**Describe the bug**

Chatwoot is CC:ing contacts based on the previous message.

**To Reproduce**

1. Open a conversation
2. Reply to a conversation and add CC recipient, email will be sent correctly
3. Reply to another conversation (from a different person) and the person you CC:ed in the previous conversation will be included in this one as well. The "CC" field in the conversation will still be shown empty, and you will not see that you have mistakenly CC:ed the person until the message is sent.

**Environment**

Self-hosted, v1.22.1.

**Comment by Robinjoeh** [comment]
Have you been able to reproduce this? It has happened several times now, and if you need more info I'll be happy go gather more details.

**Comment by sojan-official** [comment]
@Robinjoeh We have been able to reproduce the issue and we are working on fix for this

**Comment by Robinjoeh** [comment]
@sojan-official Perfect, keep up the good job!
