### ISSUE TITLE
JSSDK Option is Not Toggled Please toggle the "Login with Javascript SDK" Option to Yes in developers.facebook.com to use the JSSDK for Login.

### ISSUE THREAD

**Issue by ahmednamoha** [chatwoot/chatwoot#3510]
JSSDK Option is Not Toggled
Please toggle the "Login with Javascript SDK" Option to Yes in developers.facebook.com to use the JSSDK for Login.

**Comment by sojan-official** [comment]
Go to your FB developer page, choose your FB app, for Facebook login settings, and turn on the SDK option

![144567664-2572d7ee-bef9-452e-bdb1-992ad22fedd4](https://user-images.githubusercontent.com/73185/144802586-013efeb2-354d-43b7-a4f1-61ad3b55fe3c.png)


ref: https://github.com/chatwoot/chatwoot/discussions/3397

**Comment by ahmednamoha** [comment]
thanks it is helped me
