### ISSUE TITLE
add ability to send interactive session messages via automation 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3517]
![92940135-57560580-f414-11ea-955d-a29370edc450](https://user-images.githubusercontent.com/20530550/145024448-0bc9a664-22c5-4f97-b33a-157f385d5452.png)

**Comment by tejaswinichile** [comment]
We have this issue mentioned here https://github.com/chatwoot/chatwoot/issues/3195#issuecomment-947911895 I am closing this as it's an already mentioned requirement.
