### ISSUE TITLE
Inconsistency in the API documentation and webhook events documentation

### ISSUE THREAD

**Issue by NusretOzates** [chatwoot/chatwoot#3520]
**Is your enhancement request related to a problem? Please describe.**
It is a very very tiny problem but I want to contribute :) In the API documentation, it says the ID of the Agent is the type of integer. In the documentation of the webhook events, the ID of the Agent seems like a string. But when I get a "message_created" event, the ID  of the Agent is an integer.

![image](https://user-images.githubusercontent.com/19870022/145100098-222a23f7-61d0-418d-946b-fff89c65f36e.png)
![image](https://user-images.githubusercontent.com/19870022/145100116-3247fee7-3b8d-43d6-ad94-032d4d8df178.png)

**Describe the solution you'd like**
The documentation of the webhook events should be updated.

**Comment by Dhananjay-JSR** [comment]
Made a Pull Request Over Here :- https://github.com/chatwoot/docs/pull/205
