### ISSUE TITLE
Portainer Docker Compose stack — base container not running

### ISSUE THREAD

**Issue by dominikmukrecki** [chatwoot/chatwoot#3521]
**Describe the bug**

I am using these stack files (docker-compose.yaml and .env):

https://github.com/dominikmukrecki/chatwoot-portainer-stack.git

After setting up the stack in Portainer chatwoot_base container is not working and after restart immediately stops.

The same issue reproduces after using docker-compose up directly from the terminal.

**To Reproduce**

1. Use docker-compose.production.yaml based docker-compose.yaml file along with .env.example based .env file. Source fIles are mentioned here: https://www.chatwoot.com/docs/self-hosted/deployment/docker
2. Use these files on Portainer dashboard to deploy stack

OR

`docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
docker-compose up -d`

in terminal.

**Expected behavior**

chatwoot_base container could not be started.

**Screenshots**

![image](https://user-images.githubusercontent.com/64379788/145112482-0de3a0b2-7ebe-4a47-a0f7-aa5f8b27d2f8.png)

**Browser logs**

nothing

**Server logs**

Switch to inspect mode.
Switch to inspect mode.

{
    "AppArmorProfile": "docker-default",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [
            "irb"
        ],
        "Domainname": "",
        "Entrypoint": null,
        "Env": [
            "SECRET_KEY_BASE=replace_with_lengthy_secure_hex",
            "FRONTEND_URL=http://0.0.0.0:3000",
            "ASSET_CDN_HOST=",
            "FORCE_SSL=false",
            "ENABLE_ACCOUNT_SIGNUP=false",
            "REDIS_URL=redis://redis:6379",
            "REDIS_PASSWORD=",
            "REDIS_SENTINELS=",
            "REDIS_SENTINEL_MASTER_NAME=",
            "POSTGRES_HOST=postgres",
            "POSTGRES_USERNAME=postgres",
            "POSTGRES_PASSWORD=",
            "RAILS_ENV=development",
            "RAILS_MAX_THREADS=5",
            "MAILER_SENDER_EMAIL=Chatwoot <accounts@chatwoot.com>",
            "SMTP_DOMAIN=chatwoot.com",
            "SMTP_ADDRESS=mailhog",
            "SMTP_PORT=1025",
            "SMTP_USERNAME=",
            "SMTP_PASSWORD=",
            "SMTP_AUTHENTICATION=",
            "SMTP_ENABLE_STARTTLS_AUTO=true",
            "SMTP_OPENSSL_VERIFY_MODE=peer",
            "MAILER_INBOUND_EMAIL_DOMAIN=",
            "RAILS_INBOUND_EMAIL_SERVICE=",
            "RAILS_INBOUND_EMAIL_PASSWORD=",
            "MAILGUN_INGRESS_SIGNING_KEY=",
            "MANDRILL_INGRESS_API_KEY=",
            "ACTIVE_STORAGE_SERVICE=local",
            "S3_BUCKET_NAME=",
            "AWS_ACCESS_KEY_ID=",
            "AWS_SECRET_ACCESS_KEY=",
            "AWS_REGION=",
            "RAILS_LOG_TO_STDOUT=true",
            "LOG_LEVEL=info",
            "LOG_SIZE=500",
            "FB_VERIFY_TOKEN=",
            "FB_APP_SECRET=",
            "FB_APP_ID=",
            "IG_VERIFY_TOKEN=",
            "TWITTER_APP_ID=",
            "TWITTER_CONSUMER_KEY=",
            "TWITTER_CONSUMER_SECRET=",
            "TWITTER_ENVIRONMENT=",
            "SLACK_CLIENT_ID=",
            "SLACK_CLIENT_SECRET=",
            "IOS_APP_ID=L7YLMN4634.com.chatwoot.app",
            "ANDROID_BUNDLE_ID=com.chatwoot.app",
            "ANDROID_SHA256_CERT_FINGERPRINT=AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8",
            "USE_INBOX_AVATAR_FOR_BOT=true",
            "ENABLE_PUSH_RELAY_SERVER=true",
            "PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=C.UTF-8",
            "RUBY_MAJOR=3.0",
            "RUBY_VERSION=3.0.2",
            "RUBY_DOWNLOAD_SHA256=570e7773100f625599575f363831166d91d49a1ab97d3ab6495af44774155c40",
            "GEM_HOME=/usr/local/bundle",
            "BUNDLE_SILENCE_ROOT_WARNING=1",
            "BUNDLE_APP_CONFIG=/usr/local/bundle",
            "BUNDLE_WITHOUT=development:test",
            "BUNDLER_VERSION=2.1.2",
            "EXECJS_RUNTIME=Disabled",
            "RAILS_SERVE_STATIC_FILES=true",
            "BUNDLE_FORCE_RUBY_PLATFORM=1",
            "BUNDLE_PATH=/gems"
        ],
        "ExposedPorts": {
            "3000/tcp": {}
        },
        "Hostname": "ae5c0ec3704e",
        "Image": "chatwoot/chatwoot:latest",
        "Labels": {
            "com.docker.compose.config-hash": "a4a22e203a636fe094242bc4f7468f289ccecbe5426ebb1b839e641c95559114",
            "com.docker.compose.container-number": "1",
            "com.docker.compose.oneoff": "False",
            "com.docker.compose.project": "chatwoot1",
            "com.docker.compose.project.config_files": "/data/compose/60/docker-compose.yaml",
            "com.docker.compose.project.working_dir": "/data/compose/60",
            "com.docker.compose.service": "base",
            "com.docker.compose.version": "1.27.4"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": false,
        "User": "",
        "Volumes": {
            "/app/storage": {}
        },
        "WorkingDir": "/app"
    },
    "Created": "2021-12-07T21:46:33.186231539Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/37cfea81c681a235cbb8c980ad310ed59b9247d5d8780c8e5873c85c4f6dd875-init/diff:/var/lib/docker/overlay2/2af45a011c65b0bb36d8ddfd2493b0ba4c6c30d7432c329dcaaba46e5fa797f8/diff:/var/lib/docker/overlay2/aa2bf946e97a2d5cd48b5619337d3302e02f1d204725127eb6da8b0a318555a3/diff:/var/lib/docker/overlay2/16fdd03411fe1f12b670bc42414c964739f1a0e93a1207639314e3a457981ade/diff:/var/lib/docker/overlay2/d47d4f6c795fe463980d0e920a04c3b1f9e6f9921987f4c68734ffa53a14f193/diff:/var/lib/docker/overlay2/460cf5e9259695f3a43d059a72231980aca0904a8c1171a2ea5cfa0f0ceb10b1/diff:/var/lib/docker/overlay2/eb8122fa98de89a22e2de29e99d61d5d115ffa1a6170d0e01903555dc72f1375/diff:/var/lib/docker/overlay2/4ab4ee2a1f110c20a4a0089d293868d3c773fa5847c9759ba6eec283b2177662/diff:/var/lib/docker/overlay2/7b70c629a13868285107913b90b65261484a9469d2996a45828dbef9977feda5/diff:/var/lib/docker/overlay2/3ba92fd2e54ef56b386d5b0f0451c4a59022336ed30bda5ac7761360060506bf/diff:/var/lib/docker/overlay2/b9f8cf21bcf4ac53427e5a9b4dd8a403f21bf9869dbae8cd471dd8e31118e9ea/diff",
            "MergedDir": "/var/lib/docker/overlay2/37cfea81c681a235cbb8c980ad310ed59b9247d5d8780c8e5873c85c4f6dd875/merged",
            "UpperDir": "/var/lib/docker/overlay2/37cfea81c681a235cbb8c980ad310ed59b9247d5d8780c8e5873c85c4f6dd875/diff",
            "WorkDir": "/var/lib/docker/overlay2/37cfea81c681a235cbb8c980ad310ed59b9247d5d8780c8e5873c85c4f6dd875/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/data/storage:/app/storage:rw"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": null,
        "CapDrop": null,
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": null,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "chatwoot1_default",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {},
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": ""
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": []
    },
    "HostnamePath": "/var/lib/docker/containers/ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888/hostname",
    "HostsPath": "/var/lib/docker/containers/ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888/hosts",
    "Id": "ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888",
    "Image": "sha256:1cb427ce200e80abe963ea28e3b9d24ae0431689a4bb6ebc8e6f7640d91d3ab5",
    "LogPath": "/var/lib/docker/containers/ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888/ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/app/storage",
            "Mode": "rw",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/data/storage",
            "Type": "bind"
        }
    ],
    "Name": "/chatwoot1_base_1",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "",
        "Networks": {
            "chatwoot1_default": {
                "Aliases": [
                    "base",
                    "ae5c0ec3704e"
                ],
                "DriverOpts": null,
                "EndpointID": "",
                "Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": null,
                "IPAddress": "",
                "IPPrefixLen": 0,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "",
                "NetworkID": "cb9c99df20fea088a5f21d2b011d2d0ce53a348142aa4d9a7153cb3facd5e2cd"
            }
        },
        "Ports": {},
        "SandboxID": "a7b758420299c8e8850336872d683e36f8786299e4bf3fbbd01763b19ef1344b",
        "SandboxKey": "/var/run/docker/netns/a7b758420299",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "irb",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 33,
            "ResourceId": "2_chatwoot1",
            "SubResourceIds": [],
            "Type": 6,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/ae5c0ec3704ec5fd7c91d405d604906bbf08836a2bbf01c29302645755ce8888/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2021-12-07T21:56:43.827936234Z",
        "OOMKilled": false,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2021-12-07T21:56:43.443069015Z",
        "Status": "exited"
    }
}

**Environment**

Docker/Portainer Business Edition/Ubuntu VM

**Comment by sojan-official** [comment]
@dominikmukrecki  The base image is meant to be an intermediate image to build the worker and web images, it is not required for the base image to be running for the chatwoot instance to work.  Are you able to access the installation otherwise? 

@vishnu-narayanan  if you give the portainer installation a try anytime, let's keep a fork of the configuration in chatwoot org as well to track the issues.

**Comment by dominikmukrecki** [comment]
Issue successfully resolved for now. Change in docker-compose.yaml

`env_file: .env`

into

`env_file: stack.env`

and upload all .env variables into Portainer stack creator :)
