### ISSUE TITLE
Add foreign key with delete cascade for destroy_async

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#3530]
**Describe the bug**

We have added destroy_async but the `destroy_async option should not be used when the association is backed by foreign key constraints in the database.` 

Find all the foreign key and update it with the `cascade: delete`

**To Reproduce**

Try to delete a record that has dependent: destroy_async present, it won't delete the record because of foreign key violation

**Expected behavior**

Parent record should delete the dependent record having dependent: destroy_async.

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/10827585/145205044-b84e75fe-95e3-41f3-bf77-6f21ecc3b6ca.png)

Refer a PR: https://github.com/chatwoot/chatwoot/pull/3527
Follow the same thing for the below.
Update foreign key for the below keys:

```
add_foreign_key "account_users", "accounts"
  add_foreign_key "account_users", "users"
  add_foreign_key "agent_bots", "accounts"
  add_foreign_key "campaigns", "accounts"
  add_foreign_key "campaigns", "inboxes"
  add_foreign_key "contact_inboxes", "contacts"
  add_foreign_key "contact_inboxes", "inboxes"
  add_foreign_key "conversations", "campaigns"
  add_foreign_key "conversations", "contact_inboxes"
  add_foreign_key "conversations", "teams"
  add_foreign_key "csat_survey_responses", "accounts"
  add_foreign_key "csat_survey_responses", "contacts"
  add_foreign_key "csat_survey_responses", "conversations"
  add_foreign_key "csat_survey_responses", "messages"
  add_foreign_key "csat_survey_responses", "users", column: "assigned_agent_id"
  add_foreign_key "data_imports", "accounts"
  add_foreign_key "notes", "accounts"
  add_foreign_key "notes", "contacts"
  add_foreign_key "notes", "users"
  add_foreign_key "team_members", "teams"
  add_foreign_key "team_members", "users"
  add_foreign_key "teams", "accounts"
```

**Comment by tejaswinichile** [comment]
Add a sidekiq job for the migration.

**Comment by sojan-official** [comment]
@tejaswinichile updated the issue to remove active storage tables. Just need to make this change for the records for which we added destroy async.
