### ISSUE TITLE
dockerhub builds failing

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#3532]
**Describe the bug**

Dockerhub builds are failing since today morning. 

**To Reproduce**

1. Go to https://hub.docker.com/repository/docker/chatwoot/chatwoot/builds

**Expected behavior**

docker builds should pass

**Screenshots**

n/a

**Browser logs**

n/a

**Server logs**

n/a

**Environment**

n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by vishnu-narayanan** [comment]
Appears to be an issue from upstream as multiple users are reporting the same. 

https://forums.docker.com/t/failed-to-authorize-rpc-error-code-unknown-desc-failed-to-fetch-oauth-token-unexpected-status-401-unauthorized/118562/5

**Comment by sojan-official** [comment]
i have raised a support ticket

**Comment by vishnu-narayanan** [comment]
Looks like builds are working again. 
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/3526167/145542190-4b83e06d-70d3-479a-b572-4226748ee268.png">

**Comment by sojan-official** [comment]
👍
