### ISSUE TITLE
feat: Ability to send Buttons from Chatwoot WABA (360Dialog)

### ISSUE THREAD

**Issue by sultanlive** [chatwoot/chatwoot#3538]

**Comment by sultanlive** [comment]
For example:

```
{
    "content": "Select one of the items below",
    "content_type": "input_select",
    "content_attributes": {
        "items": [
            { "title": "Option1", "value": "Option 1" },
            { "title": "Option2", "value": "Option 2" }
        ]
    },
    "private":false
}
```

But not working for 360Dialog WhatsApp

**Comment by sojan-official** [comment]
@sultanlive  Chatwoot doesn't support interactive messages for channels other than the website at the moment. Its something which we are looking into.

**Comment by pranavrajs** [comment]
Closing this as the template messages are supported now. You can create a button template in 360Dialog and send it from Chatwoot.
