### ISSUE TITLE
database or platform api special validation

### ISSUE THREAD

**Issue by Alarees** [chatwoot/chatwoot#3540]
**Is your enhancement request related to a problem? Please describe.**
**No**

**Describe the solution :**
the app i am using does not require email address, when i want to create chatwoot user with `Platform API`  can't becouse the api request email address which i don't have or i don't need

**Describe alternatives you've considered**
register user with phone number instead of email

**Additional context**
i don't want email to register my user

**Comment by sojan-official** [comment]
Email is a mandatory field at the moment for chatwoot for users.

So a workaround you could do is supplement something like `userid@local.local` as a placeholder.

**Comment by pranavrajs** [comment]
Closing this as there is not further work to be done here. The login is based on email, so we cannot work with phone number here.
