### ISSUE TITLE
twitter mentions not coming in mentions section

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3541]

**Comment by sojan-official** [comment]
@voko3456  if you refering to the mentions tab in the conversation sidebar. It will aggregate all the chatwoot conversations where the currently logged-in user was mentioned. 

Agents in chatwoot can mention each other on conversations by using `@` in private notes

**Comment by voko3456** [comment]
Aha thanks that wa misunderstood from me
