### ISSUE TITLE
Docker Chatwoot Production deployment guide not working

### ISSUE THREAD

**Issue by Jonaswinz** [chatwoot/chatwoot#3542]
Hi, I just tried to set up an instance of chatwoot with docker, to try it out. I followed this instructions: https://www.chatwoot.com/docs/self-hosted/deployment/docker. I ran all commands in the required order, except the ubuntu ones, because I already have a running docker instance. I also only changed the passworts in the .env and docker-compose file.

After running db prepare command I get this output:

[prepare.txt](https://github.com/chatwoot/chatwoot/files/7696861/prepare.txt)

After docker-compose up -d all containers start, but sidekiq. rails and base are stopping a few seconds later

Logs of base docker container: 
[base.txt](https://github.com/chatwoot/chatwoot/files/7696862/base.txt)

Logs of sidekiq docker container:
[sidekiq.txt](https://github.com/chatwoot/chatwoot/files/7696864/sidekiq.txt)

Logs of rails docker container:
[rails.txt](https://github.com/chatwoot/chatwoot/files/7696865/rails.txt)

My Docker enviroment:

Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:48 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Please share some thoughts
Jonas

**Comment by Jonaswinz** [comment]
After a lot of try and error, it turns out that the alpine linux version 3.14 has some problems with docker 19. 
 [base image](https://forums.docker.com/t/builds-with-alpine-linux-3-14-fail-on-docker-hub/112469)
I resolved the issue, by upgrading the docker engine to 20.

**Comment by vishnu-narayanan** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/2845
