### ISSUE TITLE
IMAP SMTP Username must be mail adress 

### ISSUE THREAD

**Issue by entttom** [chatwoot/chatwoot#3544]
In v2.0.0 the smtp and imap username for a email channel must be a mail adress - in my case its a simple username without the domain part. 
Maybe you can cancle the validation in further releases.

for everyone other facing this problem - with the chrome dev tools you can delete the the disable class from the submit button so you can save it - at least for the IMAP setting.
this workarround isnt working for the SMTP setting.

Edit:

also working for SMTP - used the wrong port (in my case 587)- shame on me ;)

kind regards, 
thomas

**Comment by sojan-official** [comment]
@aswindevps We could change the validation.

**Comment by entttom** [comment]
> @aswindevps We could change the validation.

@aswindevps  @sojan-official and it would be fantastic if there is an from field: right now the username is also the sender (in this case username: 80bc197d79b962)

<img width="635" alt="Bildschirmfoto 2021-12-13 um 14 35 06" src="https://user-images.githubusercontent.com/16444099/145822069-74338889-6c19-4fd2-b9af-7eedf2b4fdfb.png">

**Comment by uhlhosting** [comment]
Same for us: Postal uses usernames in form user/domain not like usual emails, please fix or give workaround.

**Comment by sojan-official** [comment]
@entttom  @uhlhosting  We are working on a fix for this in our upcoming releases.

**Comment by uhlhosting** [comment]
Any ETA time for this?

I just want to say, that this for me worked in past on version 1.7.0 the one that comes with btcpayserver. Anyhow, will wait for a fix for this.

**Comment by sojan-official** [comment]
@uhlhosting  we are tracking this for  the upcoming release on April 15
