### ISSUE TITLE
Deleting contact won't work if is still referenced from table "csat_survey_responses"

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#3546]
**Describe the bug**

Observed that when trying to delete a contact, sometimes it is not possible and returns 500 error.

**Additional context**

Upon inspecting the logs, it appears that the cause preventing the contact from being deleted is that it is still referenced from table "csat_survey_responses" ... Confirmed by deleting rows in this table which reference contact XXX , and then deleting contact XXX was successful.

**Comment by sojan-official** [comment]
closing in favor of  https://github.com/chatwoot/chatwoot/issues/3530
