### ISSUE TITLE
Enhancement: Add keyboard shortcut for conversation actions 

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3550]
![image](https://user-images.githubusercontent.com/1277421/145764046-9aad5595-a9f3-4fa8-a9fb-de778b6b0ba8.png)
- Add keyboard shortcut for action in the menu
- Show the shotcuts them on the list

**Comment by pranavrajs** [comment]
Closing this in favour of https://www.notion.so/chatwoot/Keyboard-shortcuts-7b06b4c2ccd2450cbbce3125cf2770b9?pvs=4
