### ISSUE TITLE
Enhancement: Add background color to draggable blocks in sidebar

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3554]
![image](https://user-images.githubusercontent.com/1277421/145838753-6a715b6c-b53c-48e1-b6d0-873ce5a1d257.png)

**Comment by SanjuSudheerM** [comment]
@nithindavid Can I work on this?

**Comment by nithindavid** [comment]
> @nithindavid Can I work on this?

Sure

**Comment by SanjuSudheerM** [comment]
#3778

**Comment by SanjuSudheerM** [comment]
Just a housekeeping note, can we close this ticket?
