### ISSUE TITLE
PlatformAppPermissible tokens break webUI

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#3556]
**Describe the bug**
I tried to setup SSO using guide here https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup. 

Probably made a couple of mistakes, but eventually i was given the URL. This, however, seem to have broken the web page super_admin -> access token throwing error as below.
![image](https://user-images.githubusercontent.com/25242465/145850390-63068a9a-6a16-44ad-9d3b-c4555bd4fd0e.png)

 
**To Reproduce**
1) Create a login token method as described in article above. 
2) Go to super_admin
3) Go to Access Tokens

Caveat. If you know the ID, you can access it with /1 -> for token ID 1
e.g. https://{base_url}/super_admin/access_tokens/1

**Expected behavior**
Able to access and see Access Tokens listing page like normal.

**Browser logs**

Share the browser logs to debug the issue further

Share the server logs to debug the issue further
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: F, [2021-12-13T16:21:30.356699 #108374] FATAL -- : [f9050a46-3876-4e1a-942f-e5790ff9a146]
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] ActionView::Template::Error (uninitialized constant PlatformAppPermissibleDashboard):
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     18:
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     19: <% if field.data %>
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     20:   <%= link_to(
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     21:     field.display_associated_resource,
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     22:     [namespace, field.data]
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     23:   ) %>
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]     24: <% end %>
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146]
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] app/views/super_admin/application/_collection.html.erb:69
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] app/views/super_admin/application/_collection.html.erb:63:in `each'
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] app/views/super_admin/application/_collection.html.erb:63
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] app/views/super_admin/application/_collection.html.erb:56
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: [f9050a46-3876-4e1a-942f-e5790ff9a146] app/views/super_admin/application/index.html.erb:56
Dec 13 16:21:30 omnidemo chatwoot-web.1[108374]: I, [2021-12-13T16:21:30.357689 #108374]  INFO -- : source=rack-timeout id=f9050a46-3876-4e1a-942f-e5790ff9a146 timeout=15000ms service=44ms state=completed
Dec 13 16:21:32 omnidemo chatwoot-web.1[108374]: I, [2021-12-13T16:21:32.383424 #108374]  INFO -- : RoomChannel#update_presence

**Environment**
Self-hosted on Ubuntu Linux 20.04 CW version 2.0

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/2021
