### ISSUE TITLE
bug: Attachment bubble gets stuck when the API call fails

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3565]
ref: #3557

If the file upload fails for some reason, the UI doesn't communicate it to the end-users, instead it get stuck with the uploading bubble

## Widget 
![Screenshot 2021-12-14 at 7 07 34 PM](https://user-images.githubusercontent.com/73185/146008787-aad9f6bf-18e1-4acd-8d68-23d89d1db6bd.png)

## Dashboard
- dashboard shows error message, but bubble is not removed 

![Screenshot 2021-12-14 at 7 08 14 PM](https://user-images.githubusercontent.com/73185/146008891-27b6b61b-c40a-4d0b-a313-d39a0bb3e3eb.png)

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3270

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3104

**Comment by nithindavid** [comment]
@sojan-official Can we close this issue? Anything else pending ?
