### ISSUE TITLE
feat: Ability to use active storage direct upload

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3567]
Large file uploads could clog up the application server. They are also susceptible to requesting time outs from services like Heroku. So let's explore implementing file uploads via active storage direct upload

ref: 
https://edgeguides.rubyonrails.org/active_storage_overview.html#direct-uploads
https://blog.commutatus.com/understanding-rails-activestorage-direct-uploads-a4aeca7eccf
https://devcenter.heroku.com/articles/request-timeout
https://www.bigbinary.com/blog/uploading-files-directly-to-s3-using-pre-signed-post-request
https://devcenter.heroku.com/articles/direct-to-s3-image-uploads-in-rails

**Comment by sojan-official** [comment]
ref: #1372

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3430

**Comment by pranavrajs** [comment]
@tejaswinichile @sojan-official Let us syncup on this issue.
