### ISSUE TITLE
bug: Email content is missing

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3572]
One of the conversations in our prod account has an email with content missing. Here is the [link](https://app.chatwoot.com/app/accounts/1/conversations/11393) to the conversation. It looks like this attachment validation might be triggering this error.

- [ ] Investigate the root cause

**Comment by tejaswinichile** [comment]
This is an email with HTML content that we received on hello@chatwoot.com. The message got created but there is no text content to show in the message.

cc @pranavrajs @sojan-official Might get fixed by https://github.com/chatwoot/chatwoot/pull/3611/files

**Comment by tejaswinichile** [comment]
My question is what should be the text content for this?

**Comment by sojan-official** [comment]
fixed by https://github.com/chatwoot/chatwoot/commit/44486fc8e1673866ba3ec4654c730b51bbd1b0d2

**Comment by tejaswinichile** [comment]
Used the similar email in forward https://app.chatwoot.com/app/accounts/1/conversations/11888

**Comment by sojan-official** [comment]
@tejaswinichile  I have reverted some of the changes added over https://github.com/chatwoot/chatwoot/commit/44486fc8e1673866ba3ec4654c730b51bbd1b0d2 since it rewrites the original HTML content that we intend to store into content attributes.  Let's sync up on this later.
