### ISSUE TITLE
bug: User can skip pre-chat if campaigns are enabled

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3574]
There are no clear re-producible steps here. 

A customer reported that he is seeing unknown contact information in some of the conversations even though the pre-chat form is enabled. It seems there are a couple of similar contacts in the Chatwoot prod account as well. There is a common behavior among all these that those conversations are created from Campaigns.

An example conversation can be seen [here](https://app.chatwoot.com/app/accounts/1/conversations/11663).

**Comment by pranavrajs** [comment]
@sojan-official I think this must be fixed via https://github.com/chatwoot/chatwoot/pull/4234

**Comment by sojan-official** [comment]
lets reopen if we get further reports then
