### ISSUE TITLE
Update the command bar library to the original author

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3577]
We are using a forked version of CommandBar, @fayazara please update it to the original version as most of the changes are already available in the upstream.

**Comment by fayazara** [comment]
@pranavrajs there seem to be a lot of issues in the new update from the author. Some actions wont work unless we choose the command 3 - 4 times. Will try debuggin this with the author.

**Comment by pranavrajs** [comment]
Sounds good. Can you also please make sure that the changes from our fork are available in the upstream?

**Comment by pranavrajs** [comment]
Fixed via https://github.com/chatwoot/chatwoot/pull/3710
