### ISSUE TITLE
Create separate UI to display FB creds together in super_admin panel

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3578]
// Todo @nithindavid to take over the draft PR from @vishnu-narayanan 
// @vishnu-narayanan / @sojan-official to add more context on the issue

**Comment by rahulmr** [comment]
@pranavrajs could you please also create some video for self hosted configuration of FB creds? I tried to integrate but it is not clear what all permissions must be given to the business app created on developers dashboard ? A details video on facebook setup for chatwoot would be really beneficial. Thanks for wonderful product. It will be good if you can maintain separate code for community edition and enterprise edition.
