### ISSUE TITLE
AWS Migration: List the steps to migrate the environment

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3579]
// Todo to be completed by @vishnu-narayanan

**Comment by vishnu-narayanan** [comment]
@pranavrajs @sojan-official 


## Migration steps 
1. Decide on the AWS infra setup. Detailed in the next section. 
2. DB migration is required.
3. For active storage, we are using s3 and no migration is needed.
4. DNS is also managed by Route53. 
5. Monitoring, logging, alerting and APM are currently being used as add ons. Will need to switch to independent services. Also, this needs to be evaluated again based on what we choose for step #1. 

## Possible AWS infra setup options
1. EC2 - Standard 3 tier architecture. 
Ref: https://www.chatwoot.com/docs/self-hosted/deployment/aws
2. Beanstalk can be used in two flavors.
    - EC2
    - Containers (uses ECS under the hood)
 3. ECS - Elastic Container Service 
 4. EKS - Elastic Kubernetes Service.
 5. AWS App Runner is a new service that was announced in May 2021 and comes the closest to a PaaS. At the moment, will not work for us it only supports `python3` and `node12` as runtimes.

**Comment by pranavrajs** [comment]
Closing it for now as we would only migrate RDS for the time being.
