### ISSUE TITLE
As an agent, I would like be alerted when a customer sends me a message

### ISSUE THREAD

**Issue by max-carroll** [chatwoot/chatwoot#359]
**Scenario 1**

Given Im an agent
And I have the web client for chatwoot open
When a customer initiates a conversation
Then I should get a notification

**Scenario 2**

Given Im an agent
And I am in a conversation with a customer
When a customer sends me another message
Then I should be alerted

**Conversation**

Do we want to be alerted in different ways  for each scenario or will one suffice?

Could we perhaps configure whether we want an audio notification, and if we want this do we want this configurable as a system, agent or channel level

My thoughts are perhaps at an Agent level, because some people may be anoyed by it, somepeople may depend on it, and so this is perhaps would be better as a personal choice rather than a system or business level choice

**Comment by sojan-official** [comment]
@max-carroll  the initial version had audio notifications, which ended up being a nuisance when a bunch of messages comes in via multiple conversations,  cause of which we had to pull back the feature.  

But alerting the agent is definitely a priority and we are looking into improving the previous implementation. we are also considering push notifications as an alternative.

**Comment by max-carroll** [comment]
Awesome, in that case shall I close this issue, or shall I modify it based on what you said?

**Comment by sojan-official** [comment]
@max-carroll I think we don't have any Github issues tracking this change. so let's keep this open until the change is merged.

**Comment by pranavrajs** [comment]
Taking it out of v1.0.0, will prioritize in the next sprint.

**Comment by MichaelArriaga** [comment]
I have to manually refresh in order to see updates or new conversations. Is this normal?

**Comment by pranavrajs** [comment]
@MichaelArriaga This is not normal, it should be a bug.

**Comment by max-carroll** [comment]
Hoewever in my opinion, being alerted when receiving a message would be desired behaviour, I am actually awaiting this feature before I transition over to chatwoot

**Comment by bfitec** [comment]
Will this be fixed soon? @pranavrajs My Drift subscription renews on the Feb 15th and we're rushing to replace it with ChatWoot! Should I try to do a manual deployment instead of a heroku deployment?

Thank you for all your hard work on this, very excited to see where this goes and the hosted version.

**Comment by sojan-official** [comment]
We will be implementing audio alerts 
- [ ] in the widget when a new message arrives for contact 
- [ ] in the dashboard when agents get a new message

**Comment by sojan-official** [comment]
we are having some technical issues in enabling the audio notification on the dashboard side, But the v1.2 release contains audio notifications on the widget side when customer receives a new message from agent. 

We will move the remaining work on this issue to v1.3. we will also explore browser push notifications as an alternative.

**Comment by ndom91** [comment]
What about allowing other forms of agent / dashboard notification? So that the agents don't always need to keep the dashboard open.

For example, you could do simple email notifications on new chats. Or Telegram / Pushbullet - both easy to implement.

**Comment by sojan-official** [comment]
@ndom91 Thanks for the ideas.  We are exploring several options here.  In today's release, we added the option to opt-in for email notifications whenever a new conversation is created in the inbox.  we didn't want to do this for each message response since that can generate a huge amount of email. 

We have a [mobile app](https://github.com/chatwoot/chatwoot-mobile-app) being developed so that should alert you as well.  Another feature in this release is webhooks, so you can implement custom notification workflows on your own. We are still collecting feedback on improving the overall experience.

**Comment by ndom91** [comment]
@sojan-official yeah I agree - only on new conversation, good stuff. Thanks for the quick response / update

**Comment by meaziz** [comment]
just want to make sure that "New Conversations." also means that conversations that were marked resolve but the user triggered it again.

**Comment by sojan-official** [comment]
@meaziz  we will have notifications for reopened conversations as well. ie, when a conversation marked resolved gets a new message.

**Comment by andreipopovici** [comment]
Might I suggest a timer-based escalation method used by a large player in the market?

Once a new message comes in, show a dashboard notification (optionally a tasteful audio chirp). If it's not acknowledged for 1 minute, send a mobile push notification. If that's not read for ~5 minutes, send a notification email for that conversation.

This would require keeping track of each notification triggered and its timer in a queue. Acknowledging a notification by taking action elsewhere (for example, ignoring the mobile push notification but replying in the dashboard should cancel the notification timer and avoid sending the email).

It's a little more work but it ensures no messages are ever missed.

**Comment by sojan-official** [comment]
@andreipopovici thanks for the suggestion. We will keep it in mind as we add more features to the notification system in upcoming releases. But taking a cue from your suggestion in the current release we are evaluating a following case. 

if a user has both email and push notification subscribed, we will trigger the push notification immediately and only if it hasn't been acknowledged in the next few minutes,  we will trigger the email. This will reduce the email notification spam I guess.

**Comment by andreipopovici** [comment]
I'll just leave this here as a warning against over-complicating things 🤣

https://pbs.twimg.com/media/C6ROe0mU0AEmpzz?format=jpg

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/commit/e9131ea55862a49994bb582458631179e2277d5b
