### ISSUE TITLE
forbidden: Provided scope(s) are not authorized [Google Cloud Storage]

### ISSUE THREAD

**Issue by dominikmukrecki** [chatwoot/chatwoot#3591]
GCS is configured as follows: https://www.chatwoot.com/docs/self-hosted/deployment/storage/gcs-bucket, but `forbidden: Provided scope(s) are not authorized` error is returned after, for example, sending the image. Sent and received images are blank.

Services usage logs are without any activity.

![image](https://user-images.githubusercontent.com/64379788/146275688-7d6784ea-6dc8-4f8c-9919-eed552b6e7be.png)
![image](https://user-images.githubusercontent.com/64379788/146275743-2c8484d4-7994-4d3d-b5ce-e233be879332.png)

**Comment by dominikmukrecki** [comment]
Resolved: stack is up and running :)

GCS_CREDENTIALS should be with quotes wrapped. I am using Portainer to set my stack.

Not working:

`GCS_CREDENTIALS={   "type": "service_account",   "project_id": "redacted",   "private_key_id": "redacted",   "private_key": "redacted",   "client_email": "redacted",   "client_id": "redacted",   "auth_uri": "https://accounts.google.com/o/oauth2/auth",   "token_uri": "https://oauth2.googleapis.com/token",   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",   "client_x509_cert_url": "redacted" }`

Working:

`GCS_CREDENTIALS='{   "type": "service_account",   "project_id": "redacted",   "private_key_id": "redacted",   "private_key": "redacted",   "client_email": "redacted",   "client_id": "redacted",   "auth_uri": "https://accounts.google.com/o/oauth2/auth",   "token_uri": "https://oauth2.googleapis.com/token",   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",   "client_x509_cert_url": "redacted" }'`

I hope, that my mistake will help other Chatwoot fans :) Cheers :)

**Comment by vishnu-narayanan** [comment]
@dominikmukrecki Thank you for sharing 😄
