### ISSUE TITLE
chore: Facebook Sender ID in Webhook calls

### ISSUE THREAD

**Issue by dominikmukrecki** [chatwoot/chatwoot#3592]
**Is your feature request related to a problem? Please describe.**
Is there any possibility to retrieve Facebook Sender ID from the message/conversation/contact?

As you can see, here is an example of Sidekiq log:

I, [2021-12-15T22:54:26.704377 #1]  INFO -- : [521fe7ad-e099-47a3-9885-d7b9cfea22e6] [ActiveJob] Enqueued Webhooks::FacebookEventsJob (Job ID: 61139d80-9403-416b-876a-7113df212141) to Sidekiq(default) with arguments: "{\"messaging\":{\"sender\":{\"id\":\"108476238053526\"},\"recipient\":{\"id\":\"3291192954316443\"},\"timestamp\":1639608866175,\"message\":{\"mid\":\"m_N1zlay9r-hnIBYG2-LZFHXHQRNRVQnlTV_Kke0HvV9rPUwMeXNy9nxgCxC2g3G62r2-WvYynIwNG-HeDEIuBmw\",\"is_echo\":true,\"app_id\":1234833323665306,\"attachments\":[{\"type\":\"image\",\"payload\":{\"url\":\"https://scontent.xx.fbcdn.net/v/t1.15752-9/cp0/248023079_351315143414323_7637649199409243441_n.png?_nc_cat=100\\u0026ccb=1-5\\u0026_nc_sid=58c789\\u0026_nc_ohc=ow-V69fGGkYAX8VPdDT\\u0026_nc_ad=z-m\\u0026_nc_cid=0\\u0026_nc_ht=scontent.xx\\u0026oh=03_AVJebBLI5E8DAt5ZfHUGjJDskpjhPavxNz4PmmxJmRezXw\\u0026oe=61E0AB7A\"}}]}}}"

Are these data included in the Chatwoot webhook payload?

**Describe the solution you'd like**
Simply adding Facebook payload into Chatwoot webhooks.

**Describe alternatives you've considered**
Possibility to get data directly from Sidekiq as another webhook call.

**Additional context**
I would like to build CRM using unique FB PSID (https://developers.facebook.com/docs/messenger-platform/identity/id-matching/) as a customer identifier.

**Comment by sojan-official** [comment]
@dominikmukrecki  every conversation in chatwoot will have an associated contact_inbox ( contact_session ) . This session object contains an attribute called source_id which denotes the unique identifier for that contact in the external platform from where the conversation was created. 

You can query the chatwoot API and fetch this information.  
for example query the contactable inboxes endpoint for a contact ref: https://www.chatwoot.com/developers/api/#operation/contactableInboxesGet



ref: https://github.com/chatwoot/chatwoot/wiki/Building-on-Top-of-Chatwoot:-Importing-Existing-Contacts-and-Creating-Conversations

**Comment by dominikmukrecki** [comment]
Greetings @sojan-official, thank you for the detailed explanation. I am closing for now and will return with step by step solution after trials and errors. Cheers :)
