### ISSUE TITLE
feat: company management in widget setUser

### ISSUE THREAD

**Issue by Nirva-Software** [chatwoot/chatwoot#3599]
I quote from the documentation "Support for additional parameters is in progress."
So here some suggestions.

At the moment with setUser we can use: name, email, phone_number.
It would be nice if the fields company, city, country could be used as parameters of the setUser in the widget.
In particular for the company, there is already an icon displayed (briefcase) when we looked at a contact. So it seems to be an 'important' field but not managed by the setUser.

Todo:

- [ ] Support more parameters in the setUser method.

**Comment by muhsin-k** [comment]
@pranavrajs Are attributes like description, company name, location enough, or do we need to consider the social profiles?

**Comment by pranavrajs** [comment]
@muhsin-k As discussed previously, let's keep description, company name, city, country_code, social_profiles. Location is a deprecated attribute, let us focus on city_name, country_code for now.
