### ISSUE TITLE
Set rich content editor in email messages as default

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3606]
**Problem:**

When the user press `enter` in the normal editor, it sends the message right away. Although it is ideal for chat messages, this behavior is not ideal for an email thread. 

Also, the visibility of the feature is low.

**To discuss:**

- [ ] Can we set rich content editor in email thread by default?
- [ ] or Can move away from `Enter to send` and use something like `Cmd + Enter` to send the message?

@nithindavid @sojan-official Thoughts

More context: https://discord.com/channels/647412545203994635/654017096812068864/921016198710308966

**Comment by sojan-official** [comment]
Both the proposals sound good to me 

- There have been multiple reports of confusion about the enter to send checkbox

**Comment by pranavrajs** [comment]
Closing as the feature is complete.
