### ISSUE TITLE
Mails sent from live.fr are not received in Chatwoot

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3607]
There is a bug reported by one of the Cloud users that any emails that are sent from `live.fr` are not received in Chatwoot. 

For context, look at [this conversation](https://app.chatwoot.com/app/accounts/1/conversations/11661).

Transcript:

```
Example :
1- Email from live.fr to Chatwoot inbox
1st step - Email from live.fr to Chatwoot inbox ==> OK (received well in chatwoot)
2nd step - Chatwoot send response ==> OK (received well on live.fr)
3rd step (problem starts) - Response from live.fr ==> PROBLEM (no email received in Chatwoot)
And since this 3rd step, chatwoot stops receiving messages from live.fr
```

**Comment by tejaswinichile** [comment]
@pranavrajs Not able to understand the issue, I have asked the customer some questions for further investigation, but he has not replied.

Not sure how to proceed with this.

**Comment by pranavrajs** [comment]
@tejaswinichile Let us park this until we get a reply.
