### ISSUE TITLE
Messages are created out of order

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3608]
Reported by a Cloud user using 360Dialog integration.

"The problem I have is that the messages arrive out of order. Even answers sent before coming after other information."

![image](https://user-images.githubusercontent.com/2246121/146617953-ca38e74c-fc6f-4d61-985a-eee6ca6c367f.png)
![image](https://user-images.githubusercontent.com/2246121/146617955-78a9d78d-c2e1-4e7c-bed4-f26e32a300d8.png)

More context is available in [this conversation](https://app.chatwoot.com/app/accounts/1/conversations/11589).

**Comment by sanjayws** [comment]
Don't know if this might help anyone, i had the same issue with 360 when my server was behind NAT/proxy. When i hosted it with public IP has no issues. This can be reproduced on my end many times.

**Comment by pranavrajs** [comment]
Closing this as the case was not reproducible by the team.
