### ISSUE TITLE
Pressing Enter in `Get notified by email` box does nothing

### ISSUE THREAD

**Issue by nh2** [chatwoot/chatwoot#3609]
Entering email address into the `Get notified by email` input box, and pressing <kbd>Enter</kdb> does not submit the email address as expected.

**To Reproduce**

1. Open chatwoot box.
2. Write a message and submit. Wait for `Give the team a way to reach you.` and `Get notified by email` to appear.
3. Enter email address into box.
4. Press enter.

**Expected behavior**

The email address is submitted and saved.

**Actual behavior**

The cursor jumps to the `Type your message` bar without submitting the email.

The user likely does not notice that their email address wasn't actually submitted.

**Desktop (please complete the following information):**
 - Browser: Firefox 95

**Comment by pranavrajs** [comment]
@nh2 I can reproduce this. We will pick it up in the next sprint. 

@iamsivin Please take a look at this issue whenever you have time.
