### ISSUE TITLE
Make chatwoot available in digitalocean marketplace

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#361]
We would like to make chatwoot available  and instant deployable app in digital ocean marketplace 

https://marketplace.digitalocean.com/

# tasks 

- [x]  Research whether any extra work will be required to do this  ( https://github.com/digitalocean/marketplace-partners/blob/master/getting-started.md )
- [x] Test out the snapshot deployment as mentioned by digital ocean getting started guide

**Comment by debmaj2** [comment]
This would be very beneficial. We wanted to develop Auth, Video Calling and a Forms on top of Chatwoot. However, our cloud resources are with DigitalOcean

**Comment by pranavrajs** [comment]
@debmaj2 You don't need this ticket to get Chatwoot deployed to DigitalOcean, although this ticket makes it easier to do it in a click. If you want some help to get it deployed to DigitalOcean with docker, our team will be happy to assist.

**Comment by vishnu-narayanan** [comment]
### Digital Ocean 

*IMPORTANT: After you've read the link above, and before you build your app, please confirm that the answer to all of the questions below are "YES":*

-[ ] Should you wish to monetize the users of your 1-Click App, you have built-in your own mechanism to allow them to upgrade or to purchase licensing. (DigitalOcean does not currently provide a licensing engine, although we do plan to offer one in the future.)

If you answered "YES" to all of the above items, then you may begin your Vendor Portal Registration.


@pranavrajs @sojan-official thoughts on this ?

**Comment by pranavrajs** [comment]
@vishnu-narayanan 

> Should you wish to monetize the users of your 1-Click App, you have built-in your own mechanism to allow them to upgrade or to purchase licensing. (DigitalOcean does not currently provide a licensing engine, although we do plan to offer one in the future.)

Yes. We will have our own licensing system for EE edition software.

**Comment by vishnu-narayanan** [comment]
https://github.com/digitalocean/marketplace-kubernetes/pull/260

**Comment by vishnu-narayanan** [comment]
Market place listing under review.
![image](https://user-images.githubusercontent.com/3526167/133596165-6bdf493c-60e7-482d-b6a7-dc48a7d6637f.png)

**Comment by pranavrajs** [comment]
@vishnu-narayanan Nice work! Does this mean it would be listed on their pages after approval?

**Comment by vishnu-narayanan** [comment]
Yes, users should be able to install chatwoot as a 1 Click Kubernetes app within DigitalOcean.

**Comment by vishnu-narayanan** [comment]
https://marketplace.digitalocean.com/apps/chatwoot
