### ISSUE TITLE
Icon instead of image after image upload

### ISSUE THREAD

**Issue by dominikmukrecki** [chatwoot/chatwoot#3612]
**Describe the bug**

After uploading an image to the conversation, there is an icon instead of an image. After refreshing or changing view and returning image presents properly. As storage Google Cloud Storage is used, properly configured.

**To Reproduce**

Paste or upload images into the conversation.

**Expected behavior**

An icon instead of an image appears. Refreshing fixes the problem permanently.

**Screenshots**

![Zrzut ekranu 2021-12-18 161052](https://user-images.githubusercontent.com/64379788/146656992-eacffe27-e047-4baf-99f3-91aec73d7f08.png)
![Zrzut ekranu 2021-12-18 161107](https://user-images.githubusercontent.com/64379788/146656997-ce8962bc-6d57-405c-8a55-cca85748d602.png)
![Zrzut ekranu 2021-12-18 161123](https://user-images.githubusercontent.com/64379788/146656998-01341121-01e9-401d-9ed3-172fd3d7e3ba.png)

**Browser logs**

Failed to load resource: the server responded with a status of 404 ()

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/1372
