### ISSUE TITLE
feat: Push notifications for Safari

### ISSUE THREAD

**Issue by apitel** [chatwoot/chatwoot#3620]
This is a feature request. It would be great to have operator push notifications available for Safari as there are with other browsers. Not having this support makes it difficult to roll out as we would need to force our operators to switch browsers, when we currently have a working chat solution with full Safari support. 

Thank you in advance for your consideration.

**Comment by jean-philippeansel** [comment]
Same here! It would be great to have working push notifications on Safari.

**Comment by sojan-official** [comment]
## notes

The current implementation of push notifications in Chatwoot is done using `webpush` [api](https://www.w3.org/TR/push-api/) , which unfortunately safari doesn't support. So the current implementation for other browsers can't be extended for safari.
ref: https://github.com/zaru/webpush/issues/49

At the moment implementing push notifications for support will involve dedicated effort in the development and maintenance of safari notifications alone using a gem-like https://github.com/ostinelli/apnotic

**Comment by HeVictor** [comment]
Hi, would this feature request still be open for contribution? I'm new to OSS and Chatwoot and was wondering if I could take a stab at it. Thanks!

**Comment by sojan-official** [comment]
@HeVictor, feel free to :) Let us know if you need any help.

**Comment by HeVictor** [comment]
Hi again, firstly a disclaimer that I'm working through this a bit slowly as I'm quite new to push notifications and am currently not able to dedicate too much time for this each day, hope that won't be a problem. 

From my research on the issue it does seem like Safari will eventually support the standard `webpush` API from Safari 16 onwards, so I assume that in the future when the minimum support is pegged to Safari 16 then the current implementation should just work as-is. But from my understanding the current versions of Safari will still need to rely on the APN for delivering push notifications which requires a paid Apple Developer Program membership for obtaining a "website push ID". Does Chatwoot have one currently? I've had a brief look around the codebase and the docs but wasn't able to find the necessary info.

**Comment by sojan-official** [comment]
@HeVictor Thanks a lot for the investigation. I think it's not worth the effort to support the older APIs since Safari 16 is close to the official release. We can close this issue out after testing the web push with Safari 16 and make any changes if required.
