### ISSUE TITLE
feat: Auto scroll conversations page

### ISSUE THREAD

**Issue by ahmednamoha** [chatwoot/chatwoot#3622]
![screen-capture](https://user-images.githubusercontent.com/55894443/146679946-13ae3a4a-1772-4dc4-accf-92bfcfa3a855.gif)

conversations page is not Auto scrolling

**Comment by dominikmukrecki** [comment]
I am also opting for this feature :)

**Comment by WEBudoGT** [comment]
Before version 2.0 it was a feature that worked just fine

**Comment by pranavrajs** [comment]
@WEBudoGT Yeah. It seems like a bug, introduced after the 2.0 release. We will investigate this.

**Comment by ChrisvanChip** [comment]
My team (and myself) is getting pretty frustrated by this bug. Is there an easy temporary fix while we are waiting on a patch?

**Comment by WEBudoGT** [comment]
> @WEBudoGT Yeah. It seems like a bug, introduced after the 2.0 release. We will investigate this.

Hello @pranavrajs 
Just wondering if this was fixed?

**Comment by pranavrajs** [comment]
@WEBudoGT This was an easy fix, but took a while to figure out what was going on. It will be fixed in #4251

**Comment by ChrisvanChip** [comment]
Thanks a lot for your help! Our team will appreciate it :)
