### ISSUE TITLE
bug: web chat campaign blocks page with iframe

### ISSUE THREAD

**Issue by gcleaves** [chatwoot/chatwoot#3625]
When the campaign is triggered and the message appears, some of the page is blocked. This happens because the entire chat widget seems to open even though it is invisible, see screen shot.

**Expected behavior**

The chat widget should behave as if it were closed and not overlay the page.

**Screenshots**

See this screenshot with Chrome developer tools open. It shows how the widget-holder is blocking the buttons on the page.

<img width="440" alt="Screenshot 2021-12-19 at 19 59 00" src="https://user-images.githubusercontent.com/1041253/146687504-65ead333-2c62-4c94-b1df-7d9c8907409e.png">

**Environment**

Chatwoot Cloud (app.chatwoot.com)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: chrome
 - Version: 96

**Comment by nithindavid** [comment]
@gcleaves Thanks for reporting this, I Will look into this to get fixed.
