### ISSUE TITLE
bug: Background inconsistencies with campaigns table 

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3626]
![image](https://user-images.githubusercontent.com/1277421/146713225-f386cb2b-b28d-40a4-be9f-2d79103c83a6.png)

**Comment by anoymouscoder** [comment]
@pranavrajs @nithindavid Could you provide more information about this issue? And what is expect behaviours?

**Comment by nithindavid** [comment]
@anoymouscoder As you can see the screenshot, the white background is getting cut even before the table ends. (See the color change behind the delete button)
The expectation is to have white bg till end of the row/table.

**Comment by amaljosea** [comment]
Taking a look at this issue
