### ISSUE TITLE
Intermittent issue of panel getting freeze

### ISSUE THREAD

**Issue by sahilmittal** [chatwoot/chatwoot#3629]
I am using self hosted version of chatWoot 1.8 and sometimes UI freezes with below error in browser console -

vue.common.prod.js:659 TypeError: Cannot read properties of undefined (reading 'key')
    at no (vue.common.prod.js:2144)
    at vue.common.prod.js:3122
    at b (vue.common.prod.js:3120)
    at vue.common.prod.js:3122
    at b (vue.common.prod.js:3120)
    at i.__patch__ (vue.common.prod.js:3189)
    at i.e._update (vue.common.prod.js:1850)
    at i.o (vue.common.prod.js:3525)
    at pn.get (vue.common.prod.js:1445)
    at pn.run (vue.common.prod.js:1483)

At this point I am not able to perform any UI actions but in the network section messages are continuously coming form the server.
Issue gets resolved once I refresh the page.

I am not sure about the exact cause or triggering point of this error.
It would be really helpful If anyone can let me know if this is some existing issue with chatwoot UI and how It can be fixed ?
Also if you can suggest me how I can debug it further.

**Comment by muhsin-k** [comment]
@sahilmittal Is there any way to reproduce the issue you are facing?

**Comment by pranavrajs** [comment]
@sahilmittal Notice that you are on 1.8. Can you please update to the latest version and see if it is still there? There were a lot of fixes during the last 2 releases.

**Comment by sahilmittal** [comment]
@pranavrajs I noticed that the panel get stuck when too many conversations are pushed concurrently. I added the `errorHandler` to find the root cause -

```
Vue.config.errorHandler = function(err, vm, info) {
  console.log("err: ", err);
  console.log("vm: ", vm);
  console.log("info: ", info);
};
```  

This was the result -
```
err:  TypeError: Cannot read properties of undefined (reading 'key')
    at no (vue.common.prod.js:2144)
    at vue.common.prod.js:3122
    at b (vue.common.prod.js:3120)
    at vue.common.prod.js:3122
    at b (vue.common.prod.js:3120)
    at i.__patch__ (vue.common.prod.js:3189)
    at i.e._update (vue.common.prod.js:1850)
    at i.o (vue.common.prod.js:3525)
    at pn.get (vue.common.prod.js:1445)
    at pn.run (vue.common.prod.js:1483)
application.js:39 vm:  undefined
application.js:40 info:  nextTick
```

On backtracking through the stacktrace, I reached to the following piece of code in /modules/conversations/index.js -

```
[types.default.MARK_MESSAGE_READ](_state, { id, lastSeen }) {
    const [chat] = _state.allConversations.filter(c => c.id === id);
    if (chat) {
      chat.agent_last_seen_at = lastSeen;
    }
  },
```

Could this info be of any help?

**Comment by sojan-official** [comment]
@sahilmittal  [1.8 ](https://github.com/chatwoot/chatwoot/releases/tag/v1.8.0)is quite old (14 Sep 2020) and the codebase has significantly evolved from that point over the last year. 

I think the best bet here is to upgrade the installation to a newer version. We have made significant changes in how conversations are handled over the last few releases.

**Comment by sahilmittal** [comment]
@sojan-official I agreed that the version is old, but just wanted to make sure that even if upgrade the version, will this problem be solved.

A couple of more observations -

1. If I comment any of the below lines, the panel works just fine - 

1.1  File: /modules/conversations/index.js
      Line: `chat.agent_last_seen_at = lastSeen;`

1.2 File: app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
      Line: `this.$store.dispatch('markMessagesRead', { id: this.currentChat.id })`

2. Tried both - updating the component and the root component in the global `errorHandler` (`Vue.config.errorHandler = function(err, vm, info) { ... }`) - it doesn't work! 
     `vm.$forceUpdate();` -- doesn't work since `vm` is `null`
     `window.WOOT.$forceUpdate();` -- doesn't work - dont' know why

3. Tried other ways as well, as mentioned here: https://michaelnthiessen.com/force-re-render/; but only the worst solution worked which is to reload the page itself- 
    `location.reload();`

For now, this ugly solution is what I've deployed; but at least panel doesn't freezes randomly.

Before making effort of upgradation, I wanted to check if you have observed such an issue before, and was catered.

**Comment by sojan-official** [comment]
@sahilmittal  may be worth looking into https://github.com/chatwoot/chatwoot/issues/3425 
We have a fix for this on our latest releases

**Comment by pranavrajs** [comment]
@sahilmittal Should we keep this open? Does change as mentioned in #3425 work for you?

**Comment by sahilmittal** [comment]
@pranavrajs Haven't tried upgrading the chatwoot yet and had settled with the #3 solution for now. You can close this one if you're not able to repro the same with the latest version
