### ISSUE TITLE
chore: avoid Horizontal scroll on canned responses page

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3634]
<img width="1582" alt="Screenshot 2021-12-21 at 5 47 04 PM" src="https://user-images.githubusercontent.com/73185/146928719-ba178233-e0dc-43d5-b124-cf0d03ad0660.png">

lengthy canned responses make the canned responses page scroll horizontally, avoid this.

**Comment by shivamsinghchahar** [comment]
@sojan-official Can I take this up?

**Comment by sojan-official** [comment]
@shivamsinghchahar  please go ahead

**Comment by shivamsinghchahar** [comment]
@sojan-official I'm checking `/app/accounts/1/settings/canned-response/list` page and I'm not able to reproduce this. Was this fixed or maybe I'm missing something?

**Comment by sojan-official** [comment]
@shivamsinghchahar verified that this is not an issue anymore.  thanks for checking it
