### ISSUE TITLE
[Enhancement] Make linux installation easier

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#365]
We would like to make chatwoot available for all Linux.
Research about https://snapcraft.io/

**Comment by sojan-official** [comment]
we have the docker based installation: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker 
as well as the script for ubuntu: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm
