### ISSUE TITLE
Titles in change password form isn't clear

### ISSUE THREAD

**Issue by iprithvitharun** [chatwoot/chatwoot#3656]
**Is your enhancement request related to a problem? Please describe.**

The "Password" title in the Change password form isn't clear. Not sure if the user has to enter the current or new password.

**Describe the solution you'd like**

The title needs to be changed to "New password".

<img width="881" alt="new-password" src="https://user-images.githubusercontent.com/58725708/147498309-56403d5e-cc6a-4eef-870c-aa3fa96ad86b.png">

**Comment by iprithvitharun** [comment]
Please assign this to me.

**Comment by pranavrajs** [comment]
@iprithvitharun Please feel to raise a PR for the same.
