### ISSUE TITLE
Error with plurals in Invite members onboarding guide 

### ISSUE THREAD

**Issue by iprithvitharun** [chatwoot/chatwoot#3671]
**Is your enhancement request related to a problem? Please describe.**

"Email address" does not agree with the other words in the sentence.

<img width="535" alt="onboarding-invite-instruction" src="https://user-images.githubusercontent.com/58725708/147677831-9116d6db-8a98-4afc-a604-ac7a55ceef5f.png">

**Comment by Anisha-art** [comment]
I have shared a pull request, fixed this issue, please check.
