### ISSUE TITLE
Content updates

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3673]
- [x] https://github.com/chatwoot/chatwoot/issues/3672
- [x] #3671 
- [x] #3670 
- [x] #3669 
- [x] #3656 
- [x] #3655

**Comment by pranavrajs** [comment]
@iprithvitharun I created a holder issue so that it can be tracked together.

**Comment by iprithvitharun** [comment]
@pranavrajs Guess we can close this issue as well.

**Comment by pranavrajs** [comment]
@iprithvitharun Thanks 🙌
