### ISSUE TITLE
Changes in env variables are not reflected in the installation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3674]
The changes in the ENV variables are not updated in the installation. I believe this is due to the InstallationConfig and GlobalConfig changes in the https://github.com/chatwoot/chatwoot/pull/3288

**To reproduce:**

- [ ] Initialize a new installation with default settings
- [ ] Change the ENV variable to `ENABLE_ACCOUNT_SIGNUP` to true
- [ ] Restart the server

The expected behavior is that the Signup screen is enabled, but it doesn't happen as the GlobalConfig cache would prevent this change. 

@vishnu-narayanan @sojan-official Please take a look at this when you have time. 

_Note: Disable user signup is still documented using the ENV Variables. https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#disable-new-user-signup_

**Comment by vishnu-narayanan** [comment]
@pranavrajs Updated the docs accordingly.
