### ISSUE TITLE
feat: Ability to add custom attributes in messages to be used in internal integrations

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3683]
ref: https://discord.com/channels/647412545203994635/719548300868452362/923588811320066088

> unfortunately not, the intention is to save the ID of the messages in order to reply and delete them...
> the option to reply you have not yet implemented but the option to delete yes but I can't delete it without the message ID on my side.
> I know I could save the message ID in my application side but I don't use any storage and it would be simpler to store it directly in chatwoot.
> I believe that creating a storage in my application just for that would be a waste of resources...
> 
> but I believe that for the future it would be interesting to allow the use of custom attributes within this attribute at least when the content_type is text.
> Thanks for your support.

**Comment by terion-name** [comment]
+1 
very needed for api integrations

**Comment by pranavrajs** [comment]
@sojan-official Do we need this ticket now as we have shipped the custom attributes feature?

**Comment by sojan-official** [comment]
@pranavrajs, the request here is to have the ability to save meta information to messages, not conversations, i.e. to the `content_attributes`. So that they can associate internal ids or other data while creating messages through APIs.

**Comment by scmmishra** [comment]
Closing this issue for now, the use case does not seem like it's worth the effort required to build and maintain this. Ideally the integration should manage its own data and references to the messages and conversations.
