### ISSUE TITLE
Cannot confirm new accounts or reset password

### ISSUE THREAD

**Issue by florianmonfort** [chatwoot/chatwoot#3686]
**Describe the bug**

Create a new account, or use Reset password feature, the person receives the email successfully but when clicking on the link in the email they always end up on the normal landing page. The account is still not confirmed AND cannot reset the password.

**To Reproduce**

- Create new account;
- OR reset password for existing account;
- Click on link in received email;

**Expected behavior**

- For new account: Log in page should confirm account has been confirmed successfully;
- For existing account: should arrive on page to set up the new password;

**Screenshots**
Click here:
![image](https://user-images.githubusercontent.com/1446429/148021552-a8fe6f92-a32f-4e78-b2f6-d5afec6955ac.png)
![image](https://user-images.githubusercontent.com/1446429/148021619-5b316226-095a-4183-87e5-8847fac27d38.png)

... Always end up on this page:

![image](https://user-images.githubusercontent.com/1446429/148021679-b8357528-5833-47eb-a19b-c8deaa6fccd8.png)

**Browser logs**

There are no errors showing in Console. Just always going to domain/app/login URL.

**Server logs**

No specific logs available to show.

**Environment**

We are using self hosted version using Docker. Version installed is 2.0.0. Docker version 20.10.0.

**Additional context**

This is for us a blocking/serious level issue as since we can't either add or reset password for any accounts, we are essentially completely unable to roll out Chatwoot internally. Nobody can get their accounts working...

**Comment by vishnu-narayanan** [comment]
@florianmonfort 

a temporary workaround would be to access the rails console and confirm the users manually.

```
irb> u = User.find_by(email: "test@test.com")
=> #<User id: 1, provider: "email", uid: "test@test.com", name: "Test", ...
irb> u.confirm
=> true
irb> u.save
=> true
```

**Comment by sojan-official** [comment]
@florianmonfort  Could you check whether you have the `FRONTEND_URL` environment variable configured correctly ?

**Comment by nosovk** [comment]
@florianmonfort check for // in urls. Probably you entered something like https://chatwoot.domain.com/ and resulting link looks like https://chatwoot.domain.com//reset-link
I faced similar issue and changing env helped

**Comment by florianmonfort** [comment]
> @florianmonfort check for // in urls. Probably you entered something like https://chatwoot.domain.com/ and resulting link looks like https://chatwoot.domain.com//reset-link I faced similar issue and changing env helped

Hello, we managed to fix it with latest version and double checking config as suggested. You can close this!
