### ISSUE TITLE
Support more file extensions in the chat

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3692]
> Request received on the live chat.

Just introduced the self-hosted version of chatwoot to our customers. The feedback from them about the chat is very good, which I want to forward to you. 😊

---

We would love to have file formats like :

Software | Accepted formats
-- | --
Altium (PROTEL) | *.PCB/DDB/PCBDOC
TARGET | *.T2001/300*
EAGLE | *.BRD
Autodesk® Fusion 360™ | *.fbrd
KICAD | *.brd/kicad_pcb
EXT. GERBER | *.ZIP/RAR/etc.
Gerber X2 | .GBR

I can understand that there are too many additional formats. But it would be nice if at least archives like *.ZIP, *.RAR, *.7Z, *.TAR, and *.TGZ can be added.

**Comment by sojan-official** [comment]
We support some of the files mentioned above 

```
zip
rar
7z
tar
```

ref: https://github.com/chatwoot/chatwoot/commit/6fe548411996ff4f43d8139ccce7e10796c82cec

**Comment by scmmishra** [comment]
Closing this as it's not a priority, if there's more demand for this in the community, we can plan on this
