### ISSUE TITLE
Setting gmail SMTP Server as Email sender for Agent Verification

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#3694]
**Describe the bug**

I try to set my self-hosted CW to use gmail as SMTP Server

**To Reproduce**

1. Install via linux script on Linux VM
2. Apps already running and i had tried the innboxe feature for 3 different channel (Telegram, Email dan Website) and working well
3. I add another agent with valid gmail email
4. Record created but status is Pending Verification and there is no email verification in gmail inbox

**Expected behavior**

Email Verfication sent and agent status is verified

**Environment**
I use self-hosted on linux VM with .env conf like bellow (SMTP conf only) :

![SS](https://user-images.githubusercontent.com/16577318/148188778-973db3eb-2c08-43bd-9dba-e748e32e6f92.png)

**Additional Informastion**
I use apps password  on SMTP_PASSWORD

**Comment by sanjayws** [comment]
Mine works, try with these?

SMTP_ADDRESS=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=<redacted>
SMTP_PASSWORD=<redacted>
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=peer

**Comment by aldhielman** [comment]
> Mine works, try with these?
> 
> MAILER_SENDER_EMAIL="[someone@email.com](mailto:someone@email.com)" SMTP_DOMAIN=gmail.com SMTP_ADDRESS=smtp.gmail.com SMTP_PORT=587 SMTP_USERNAME= SMTP_PASSWORD= SMTP_AUTHENTICATION=login SMTP_ENABLE_STARTTLS_AUTO=true SMTP_OPENSSL_VERIFY_MODE=peer

thanks @sanjayws for your suggest, I've tried to adjust my config as your suggest and it seems "partialy work".
I means for Reset Password, email are successfully sent to my agent's email, but for Confirmation Email after I add Agent doesn't work for now

**Comment by scmmishra** [comment]
@aldhielman using GMail as an alternative to an email server is not recommended, eventually, GMail will just starting blocking sends.
