### ISSUE TITLE
Have Linux installation have preconfigured SMTP server so that installation works out of the box

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#3696]
- Have Linux installation have preconfigured SMTP server so that installation works out of the box

**Comment by vishnu-narayanan** [comment]
Update
----
Tried setting up postfix and sending an email. The postfix configuration part appears to work fine and an email was sent.

Gmail rejected the email citing DMARC policies. 


```
rom MAILER-DAEMON@chatwoot.dev Thu Jan  6 08:30:49 2022
Date: Thu, 6 Jan 2022 08:30:49 +0000 (UTC)
From: MAILER-DAEMON@chatwoot.dev (Mail Delivery System)
Subject: Undelivered Mail Returned to Sender
To: contact@chatwoot.dev
Message-Id: <20220106083049.7246F40F99@vn-build4-smtp>

[-- #1.1 24/966 text/plain, 8bit, utf-8 --]
[-- Notification --]

This is the mail system at host vn-build4-smtp.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<vishnu@chatwoot.com>: host aspmx.l.google.com[142.251.12.26] said: 550-5.7.26
    Unauthenticated email from chatwoot.dev is not accepted due to 550-5.7.26
    domain's DMARC policy. Please contact the administrator of 550-5.7.26
    chatwoot.dev domain if this was a legitimate mail. Please visit 550-5.7.26
    https://support.google.com/mail/answer/2451690 to learn about the 550
    5.7.26 DMARC initiative. p17si1203970plp.580 - gsmtp (in reply to end of
    DATA command)

[-- #1.2 20/796 message/delivery-status, 7bit, us-ascii --]
[-- Delivery report --]

[-- No MIME handler installed, or not applicable --]

[-- #1.3 19/497 message/rfc822 --]
[-- Undelivered Message --]

Date: Thu, 06 Jan 2022 08:30:47 +0000
From: contact@chatwoot.dev
To: vishnu@chatwoot.com
Subject: Test email subject line
Message-ID: <20220106083047.naawz%contact@chatwoot.dev>

Hello,

This is a test message from vn.
```

**Comment by sojan-official** [comment]
@vishnu-narayanan ref: https://mxtoolbox.com/SuperTool.aspx?action=dmarc%3achatwoot.dev 
should be because we have explicitly reject policy added for that domain. But in most installations, it should be okay?

**Comment by vishnu-narayanan** [comment]
@sojan-official You are right. Let me try another domain.

**Comment by vishnu-narayanan** [comment]
All major cloud providers block outbound traffic on port 25 as part of their spam protection measures. After installing the postfix server, the user should request AWS/GCP/Azure to enable traffic on this port for the postfix email server to work.

References
----
1. AWS https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/
2. GCP https://cloud.google.com/compute/docs/tutorials/sending-mail
3. Azure https://learn.microsoft.com/en-us/azure/virtual-network/troubleshoot-outbound-smtp-connectivity

**Comment by pranavrajs** [comment]
@vishnu-narayanan This sounds good. Do we need ask them to setup DKIM or SPF as well?

**Comment by vishnu-narayanan** [comment]
@pranavrajs Yes. That should improve the email reputation.
