### ISSUE TITLE
SELF-HOSTED service with Facebook messenger

### ISSUE THREAD

**Issue by ganbaaelmer** [chatwoot/chatwoot#3698]
Hello
I'm from Mongolia.
Because of my location its hard to use Cloud services. So i need to create server on my infrastructure.
So your SELF-HOSTED 19USD service can manage my rasa and facebook messenger requests.
I mean for beginning of the conversation rasa will answer Greeting or something then it will automatically send to Chatwoof.
It means my operators (human) can continue handle conversation. So its possible?

if its possible please give me example ?
Please help me i really wanna use rasa, chatwoof and facebook messenger together.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/rasa-agent-bot-demo/issues/11
> It's not possible out of the box, But you should be able to do it via the chatwoot APIs and writing a custom integration.
ref: https://www.chatwoot.com/docs/product/others/agent-bots

ref: #3597
