### ISSUE TITLE
Add specs for rails controllers

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#37]
- [ ] Add rspec for rails controllers 

find the list of rails controllers without test coverage here 

https://codeclimate.com/github/chatwoot/chatwoot/code?q=controllers
Feel free to pick any and raise a PR for the same.

**Comment by austinratcliff** [comment]
Hey @pranavrajs! 👋 I'd love to pick up this issue for Hacktoberfest. Is that ok even though it's not labeled with `Hacktoberfest`?

**Comment by sojan-official** [comment]
@austinratcliff  Please feel free to pick this up, if you are still available.

**Comment by Jsscrdng** [comment]
Can i get this one?

**Comment by sojan-official** [comment]
@Jsscrdng  go ahead :)

**Comment by sojan-official** [comment]
@venarius if you are still working on this. Could you also take a look at the controllers without any specs? i think we can increase our test coverage significantly then. 

https://codeclimate.com/github/chatwoot/chatwoot/code?q=controllers  should give a list.

**Comment by venarius** [comment]
@sojan-official already doing it. I just started with the controllers that had already some tests first :)

**Comment by sojan-official** [comment]
@venarius  our test coverage is at 60% ( https://codeclimate.com/github/chatwoot/chatwoot ) . thanks a ton for the great work.

**Comment by sojan-official** [comment]
Closing this since most of the controllers are covered now . We will create specific issues for the remaining ones.
