### ISSUE TITLE
Add openssl_verify_mode in email channel for smtp configuration.

### ISSUE THREAD

**Issue by aswindevps** [chatwoot/chatwoot#3700]
Fixes: https://github.com/chatwoot/chatwoot/issues/3631

**Backend**
Add `smtp_openssl_verify_mode` column to email channel table. 
The default value should be `none`

**Frontend**
Add a dropdown in the UI to select the openssl_verify_mode.
Values should be `none, peer, client_once, fail_if_no_peer_cert`

**Comment by jhengstermann** [comment]
Any news regarding this? Currently we can't use the email client with our provider
