### ISSUE TITLE
Chatwood Self-Hosted (Docker): Setting FORCE_SSL=true breaks Websocket

### ISSUE THREAD

**Issue by vorletzter** [chatwoot/chatwoot#3704]
**Describe the bug**

Setting FORCE_SSL=true in Chatwood Self-Hosted (Docker) breaks WebSockets

**To Reproduce**

1. Setting FORCE_SSL=true in .env file (as described on https://www.chatwoot.com/docs/self-hosted/deployment/docker )
2. Adding a WebSite Channel and ingerating in
3. WebChat is not working, because wss:// is getting redirected with Status 301 to https:// and the WebChat does not seem to handle redirects

**Browser logs**

-- Console:
action_cable.js:241 WebSocket connection to 'wss://<domain.tld>/cable' failed: Error during WebSocket handshake: Unexpected response code: 404 

--- Network:

GET /cable HTTP/1.1
Host: <domain.tld>
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://<domain.tld>
Sec-WebSocket-Protocol: actioncable-v1-json, actioncable-unsupported
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: OVGgLOlWwrbiF/IcmC7D7w==
Connection: keep-alive, Upgrade
Cookie: StickyCookie=63c648c9568b113d
Sec-Fetch-Dest: websocket
Sec-Fetch-Mode: websocket
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Location: https://<domain.tld>/cable
Date: Thu, 06 Jan 2022 22:02:52 GMT
Transfer-Encoding: chunked

**Environment**

Self Hosted (Docker) with Traefik v2 as Forward Proxy in a testing environment
Tested with recent Firefox and Chromium.

Everything works fine with
FORCE_SSL=false in env file. 

Took me some time, because i thought the issue was caused by traefik. But setting the FORCE_SSL to  true breaks my WebChat reproducibly.

**Comment by vishnu-narayanan** [comment]
@vorletzter I just tested this out on our docker instance with `FORCE_SSL=true` and everything seems to be working fine. We are using `nginx` for the proxy/ssl termination layer though.

Please find attached the image in which the environment variable was changed from `FORCE_SSL=false` to `FORCE_SSL=true`. The web browser was able to establish wss:// connection with both settings.

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/3526167/154042645-6ff8b0d5-b620-43a4-b596-ec4ae798ed14.png">

Are you still facing this issue?

**Comment by sojan-official** [comment]
@vorletzter  feel free to open the issue if it still persists.
