### ISSUE TITLE
[CW-372] Error with labels and upper case

### ISSUE THREAD

**Issue by latrocha** [chatwoot/chatwoot#3709]
When you label a conversation from the API, if you use an upper case letter, the label is placed, but you cannot see the conversation under the label. You can see it in the count , but you cannot remove it from the conversation.
Said label is automatically removed when you add another label.
If you have an open conversation which had that label, this behaviour will continue. if you remove the labels and close the conversations, then you can use lowercase labels and behaviour is normal.
The workaround i used is to pass all labels in lowercase.
This bug is occurring in chatwoot self hosted, using ubuntu 20.04 server and in google chrome.
I'm using chatwoot v1.22.0

<sub>[CW-372](https://linear.app/chatwoot/issue/CW-372/error-with-labels-and-upper-case)</sub>

**Comment by tejaswinichile** [comment]
@scmmishra @pranavrajs I tried to reproduce the issue; it seems it has been handled in this PR [https://github.com/chatwoot/chatwoot/pull/975/](https://github.com/chatwoot/chatwoot/pull/975/files) which is available in the latest version. Updating the version would help the customer to fix the issue.

**Comment by tejaswinichile** [comment]
@latrocha Can you update the chatwoot version to v2.15.0 or later? We have handled this issue in this fix https://github.com/chatwoot/chatwoot/pull/975/files The fix is available from version v2.15.0.
