### ISSUE TITLE
Add option to get push notifications when any new messages come in on an inbox

### ISSUE THREAD

**Issue by hanthor** [chatwoot/chatwoot#3712]
Add option to get push notifications when new messages come in on an inbox

Currently, you can only get notifications when there is a new conversation, or if it is assigned to you. But unassigned conversations have no option to get push notificaitons

**Comment by hanthor** [comment]
Or enable multi-assignments on conversations. Or assignment groups.

**Comment by sojan-official** [comment]
ref: #2443 #241

**Comment by sojan-official** [comment]
closing in favor of #241
