### ISSUE TITLE
Setting up auto reply on Email Inbox, does not send out the Auto Reply.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3713]
- Setup an email inbox
- Configure Auto-reply

**Expected:** AutoReplies should be sent to the customer.

The customer doesn't receive automatic replies.

**Context:** Created from a report by the customer on live chat. Link to the conversation [here](https://app.chatwoot.com/app/accounts/1/conversations/11913)

**Comment by ajtatum** [comment]
I'll admit that I'm a tad disappointed that channel greetings don't work for emails, but having this implemented would be outstanding!

**Comment by sojan-official** [comment]
@ajtatum  We will be verifying the issue in our current sprint and will be fixing the breakages.
