### ISSUE TITLE
Expand API channel to send emails

### ISSUE THREAD

**Issue by zivmiz1** [chatwoot/chatwoot#3720]
Right now when you create a web widget if the contact is offline and the agent send a message it goes to the contact's email.
in API channel there is only option to add webhook but not forward_to_email.

My suggestion is to add the option of forward_to_email also to API channel, and then you will have the option to also to send the message that were created by agents to the contact's email

**Comment by sojan-official** [comment]
@zivmiz1  Could you provide more information on how you are using the API channel? 

Are you building a custom chat interface using the API channel?

**Comment by zivmiz1** [comment]
@sojan-official Exactly, I'm trying to build a custom chat that sends message using the API channel. And if the agent is sending a message back to the consumer and the consumer is offline I want to be able to send the message to the consumer's email instead

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4007 so that we can track everything in a single issue.
