### ISSUE TITLE
Customize conversation email template

### ISSUE THREAD

**Issue by teawithfruit** [chatwoot/chatwoot#3725]
I've just tested the SMTP conversation integration to which works very good.
Now I like to customize the email template which is used to. I've clicked through the repo and found the following file which I think of, that this is the email template:
[app/views/mailers/conversation_reply_mailer/email_reply.html.erb](https://github.com/chatwoot/chatwoot/blob/6a98a812e70cd76ad4ee1e9ca33af98ec4b7b3e9/app/views/mailers/conversation_reply_mailer/email_reply.html.erb)

Until now the emails which are send are just plain text, but I like to use a corporate style.
How would you suggest to customize the template and is it a thinkable enhancement to do this via the administration interface?

**Comment by pranavrajs** [comment]
> Until now the emails which are sent are just plain text, but I like to use a corporate style.

Can you please explain this part a little more? Are you looking for adding a signature or something similar?

**Comment by teawithfruit** [comment]
A signature would be helpfull in the first step, but I think that the best soulution should be something like MJML.
https://mjml.io/

What do you think?

**Comment by SHELA** [comment]
Agree with @teawithfruit that need any customizer of email templates.

**Comment by pranavrajs** [comment]
Closing this as we would not be taking this. Supporting a custom templating engine is an overhead and maintaining the code is not required for the core product.
