### ISSUE TITLE
[CW-363] feat: Show context of original tweet on retweet

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3726]
**Context**
When retweets come in conversations, it's difficult to understand what's the parent tweet or link about parent tweet.

![image](https://user-images.githubusercontent.com/1277421/148959318-a8968e23-a196-47e4-aa7f-e89f6c25fc7b.png)

<sub>[CW-363](https://linear.app/chatwoot/issue/CW-363/feat-show-context-of-original-tweet-on-retweet)</sub>

**Comment by pranavrajs** [comment]
Closing this here as Twitter is not supported now.
