### ISSUE TITLE
Zoho email parsing error

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3731]
> Hi, I'm trying to forward my emails from Zoho to the inbox and all of them are coming with "no content"

> I'm currently activating the inbox, to do it I need to receive one code from Zoho mail, and all the attempts are coming with no content, but all from the same place, I cannot activate and receive e-mails from any other place before activating the forwarding

> I also can see the email content here on the network tab

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please take a look at this?

**Comment by tejaswinichile** [comment]
Probably fixed by https://github.com/chatwoot/chatwoot/pull/3659 so we will ask them to test it after that is merged.

**Comment by tejaswinichile** [comment]
@pranavrajs This code has been fixed on develop branch, can you help me to test it?

**Comment by pranavrajs** [comment]
@tejaswinichile 

- Create a Zoho mail account
- Create a Chatwoot inbox with this mail
- Setup a forwarder in Zoho to the email address in Chatwoot. Zoho will ask for confirmation code.
- You would receive an email with confirmation in your `reply.chatwoot.com` email address. See if it is displayed correctly on the dashboard.

**Comment by tejaswinichile** [comment]
@sojan-official Can you have a look I am stuck here?
```
#<ActionMailbox::InboundEmail:0x0000560da446ed78
 id: 2286,
 status: "delivered",
 message_id:
  "CAFkiBVw11+_LCJaJtZWVmbU0msW2YsgPtg_d0hk0q_2D9GKQ2Q@mail.gmail.com",
 message_checksum: "87d44179ce1c0ed80da36350d9b7e5088a7e85c5",
 created_at: Thu, 27 Jan 2022 08:48:21.597464000 UTC +00:00,
 updated_at: Thu, 27 Jan 2022 08:48:22.035610000 UTC +00:00>
=> 
#<ActionMailbox::InboundEmail:0x0000560daaeb1d20
 id: 2283,
 status: "delivered",
 message_id: "17e9a48dbb4.1838e122902255471.1700316081021929824@zohomail.com",
 message_checksum: "184996026bd6b00fb196d656af5a714166e4806e",
 created_at: Thu, 27 Jan 2022 06:46:19.925966000 UTC +00:00,
 updated_at: Thu, 27 Jan 2022 06:46:20.321121000 UTC +00:00>
```
These are 2 email channels I created, I verified 2283 by checking `mail_object.body` records but it's not getting decoded in the presenter.
When I run it line by line it's working fine. I am not sure what is the issue.
When I verified the email address by manually checking the records, the email after that are working well.

**Comment by tejaswinichile** [comment]
@sojan-official I have found the issue, the HTML parser was removing the table and Zoho parser was sending the code inside the HTML table structure.

And while displaying the message we only considered the text_part[:reply] but now we are considering html_part[:reply] if text_part is not available.
