### ISSUE TITLE
[CW-362] Email customization

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3732]
> Is it possible to customize the email notification our users receive? We had one customer who didn't know who the notification was for, as there is no indication.

**Todo:** 

- [ ] Add Inbox name in the email content.
- [ ] Update the email copy.

 

<sub>[CW-362](https://linear.app/chatwoot/issue/CW-362/email-customization)</sub>

**Comment by nithindavid** [comment]
@pranavrajs 
1. Does User mean, Agents or customers ?
2. Any suggestion or idea about the copy?

**Comment by pranavrajs** [comment]
@nithindavid 

There are 3 customer-facing emails.

1. **Conversation Transcript:** You can initiate a conversation transcript from the dashboard or the web widget. This would send out an email. This email is shown below.

<img width="927" alt="Screenshot 2022-01-17 at 9 50 39 AM" src="https://user-images.githubusercontent.com/2246121/149817626-297c34f6-9bde-4c89-8c0e-470165925e0a.png">


2. **Reply email to the customer if they are offline:** 

<img width="926" alt="Screenshot 2022-01-17 at 9 57 09 AM" src="https://user-images.githubusercontent.com/2246121/149818349-d4503b91-febc-4cd4-bf92-878358d1f6d5.png">

3. **Reply to email messages:**

<img width="927" alt="Screenshot 2022-01-17 at 10 01 56 AM" src="https://user-images.githubusercontent.com/2246121/149818851-2c536fe8-95c4-40f8-aaea-1c5d77d7cefe.png">



Problem:
There is no information on where this conversation happened. This emails should have the context of the inbox where the conversation was initiated, include the URL from which the conversation started


Let me know if you need more information.

**Comment by scmmishra** [comment]
A few things that can be done

1. Update the footer to say something like "Sent by X via Chatwoot."
2. Apply the user-set brand colour to the email design
3. The copy for each email has to be improved.

**Comment by CristianDuta** [comment]
@pranavrajs is it possible to configure the template of any of these emails?
I've seen that the notifications emails can be configured (described here: https://www.chatwoot.com/docs/self-hosted/configuration/email-notifications/#2-create-a-new-template-for-the-emails-execute-the-following-commands) but it does not look like you can customise the email templates of the transcript. Am I wrong?
