### ISSUE TITLE
Filter conversations/contacts by custom attributes

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3735]
- [x] #3736
- [x] #3738

**Types & Support filters**

| Custom Attribute Type | Supported Filters |
| -- | -- |
| List | Is Equal, Is Not Equal, Is Present, Is not Present |
| Text | Is Equal, Is Not Equal, Contains, Does not contain |
| Number |  Is Equal, Is Not Equal, Is Present, Is not Present |
| Link | Is Equal, Is Not Equal, Is Present, Is not Present |
| Date | Is Equal, Is Not Equal, Is Greater Than, Is Less Than, Is Present, Is not Present |
| Checkbox | Is Equal, Is Not Equal, Is Present, Is not Present |

**Comment by tejaswinichile** [comment]
We have this structure for the filter request payload :
```js
[
  {
    attribute_key: 'browser_language',
    filter_operator: 'not_eq',
    values: ['en'],
    query_operator: 'AND',
  },
  {
    attribute_key: 'status',
    filter_operator: 'eq',
    values: ['pending'],
    query_operator: nil,
  },
]
```
So for the custom attribute, we can have a similar structure where `attribute_key` would be the custom attribute definition key.
Consider following example for custom attribute `"Signedup at"` we have attribute key: `"signedUpAt"` below is the record,
```rb
attribute_display_name: "Signedup at",
attribute_key: "signedUpAt"
attribute_model: "contact_attribute"
account
```

So if we want to filter contacts for the given account we would want below payload

```js
[
  {
    attribute_key: 'signedUpAt',
    attribute_model: 'custom_attributes'
    filter_operator: 'not_eq',
    values: ['date_format'],
    query_operator: 'AND',
  },
 {
    attribute_key: 'browser_language',
    attribute_model: 'standard'
    filter_operator: 'not_eq',
    values: ['en'],
    query_operator: 'AND',
  },
  {
    attribute_key: 'cloudCustomer',
    attribute_model: 'custom_attributes'
    filter_operator: 'eq',
    values: ['true'],
    query_operator: nil,
  },
]
```


I have added a new parameter attribute_model above in the payload, I can have a workaround for this at the backend but if possible it would be nice to send it from the frontend.

Please check this request payload and let me know if you have any different approaches to sending it to the backend.

cc @fayazara @muhsin-k @pranavrajs

**Comment by fayazara** [comment]
Do we needto send the `attribute_model` for other filters too?

**Comment by tejaswinichile** [comment]
@fayazara 
> Do we need to send the attribute_model for other filters too?
No.

You can just send it for the current filters and for the past filter, you can keep it `null`/`standard`/ or skip it.


@fayazara Is it possible to send the date-type filter in the `yyyy-mm-dd` format to the backend?

**Comment by tejaswinichile** [comment]
@fayazara For text, date, link, checkbox, number data type we would have single value wrapped in an array. 
E.g 

```
extra_ifo_text is text type of custom attribute,
priority_number is of number type,
customer_type is of list [regular, gold, platinum]
```

So the data would look like:
```
extra_ifo_text is_equal_to 'test user' AND number is_equal_to 5 AND customer_type equal_to 'regular'
```

Are we going to provide multiselect for the options anywhere?

**Comment by pranavrajs** [comment]
@tejaswinichile Sorry for missing this out. 

I guess the list option can have a multiselect. In all other cases, I don't see the need for multi-select. 

Let me know if you need more clarification.

**Comment by fayazara** [comment]
@pranavrajs Will all these filters have a free input field? or dropdowns to select like we have for agents, teams.

**Comment by pranavrajs** [comment]
For Text, Number and Link, we can have a free form text field. For List, Checkbox we can have a dropdown. For date field, we can have a date picker.

**Comment by pranavrajs** [comment]
Closing as done. Nice work folks. 🎉
