### ISSUE TITLE
Support the UI to have Custom Attributes as filters

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3738]
- Add a new section in the filters dropdown with the list of supported custom attributes.

eg: 
<img width="653" alt="Screenshot 2022-01-11 at 7 39 01 PM" src="https://user-images.githubusercontent.com/2246121/149060180-f24e33be-ecd0-4626-b408-e2b4336b218a.png">

**Comment by fayazara** [comment]
![image](https://user-images.githubusercontent.com/15716057/149792921-a3f99fb2-4de5-4fdc-a0c6-474990537a46.png)

Would using the HTML `optgroup` make sense? or just use the Vue Multiselect component, it does have [grouping option](https://vue-multiselect.js.org/#sub-option-groups) and search too.

**Comment by pranavrajs** [comment]
@fayazara I would suggest using Multiselect instead of optgroup.
