### ISSUE TITLE
Refresh contact attributes while selecting a different conversation

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3741]
**Context**
 -  Select a conversation which is from a  contact with custom attributes,
 -  The values work as expected
 -  but if you select another conversation from another contact having custom attributes, the values for custom attributes do not change.

**Comment by heroic** [comment]
Please see the attached screenshots

First conversation selected for a user with custom attribute(external id - as highlighted)
<img width="1440" alt="Screenshot 2022-01-13 at 5 24 15 PM" src="https://user-images.githubusercontent.com/523335/149326143-0a338700-0e6a-4a39-9c4b-3c157f646b23.png">

Second conversation selected for another user with custom attributes. Everything in the side bar updated, but custom attribute external id still shows the previous value(highlighted). Do not close the sidebar when selecting the second conversation
<img width="1440" alt="Screenshot 2022-01-13 at 5 24 23 PM" src="https://user-images.githubusercontent.com/523335/149326219-2173ba1d-48b9-4bce-a172-ee208a48824a.png">

Closing the sidebar and opening it again, shows the correct value.
<img width="1440" alt="Screenshot 2022-01-13 at 5 24 29 PM" src="https://user-images.githubusercontent.com/523335/149326341-cc0f7247-df4b-4369-8691-6526011e87cb.png">

**Comment by heroic** [comment]
@pranavrajs @nithindavid can this be opened?

**Comment by pranavrajs** [comment]
@heroic I can reproduce this error. Contact Attributes are not getting updated if there was an attribute shown previously.
