### ISSUE TITLE
chrome shows phishing alert on a new chatwoot installation.

### ISSUE THREAD

**Issue by pomarc** [chatwoot/chatwoot#3746]
**Describe the bug**
created a new ubuntu 20.04 VM, installed chatwoot as suggested with a custom domain ( at westeurope.cloudapp.azure.com), the app runs smoothly, but chrome blocks the page as phishing. in the search console, the page is rated as phishing.
Firefox happily shows the page. The application runs well on Firefox.

**To Reproduce**

Steps to reproduce the behaviour:
on a clean ubuntu VM install chatwoot as suggested in the docs.

**Expected behavior**

no security warning.

**Comment by vishnu-narayanan** [comment]
@pomarc did you set up SSL during the installation?

`*.westeurope.cloudapp.azure.com` looks like a domain managed by Microsoft. Are you able to generate SSL certs against this domain? My guess is no and In that case, I would suggest you use a domain you own.

**Comment by iammattmartin** [comment]
Probably not SSL related but that someone use has put a phishing page on a sub-domain of that domain and Chrome has just listed the whole lot.

Can you use a custom domain?

**Comment by vishnu-narayanan** [comment]
@pomarc If you are able to generate an SSL cert for that domain, I am not sure what might be causing the issue.

Let us know how it goes with a custom domain btw.

**Comment by scmmishra** [comment]
This issue has been inactive for a while, so I am closing this. If you're still facing this, feel free to re-open.

**Comment by vishnu-narayanan** [comment]
cc @tejaswinichile
