### ISSUE TITLE
email-channel mail-adresse is not used as smtp-sender -> instead "accounts@chatwoot.com" is used

### ISSUE THREAD

**Issue by Soundmagic** [chatwoot/chatwoot#3757]
- new mail-channel ist setup with adress shop@xxxx.de
- STMP is configured for this mail channel and succesfully saved
- when replying to a customer through this mail channel, all mails are send out as sender "accounts@chatwoot.com" instead of "shop@xxxx.de"

Expected Behavior:
smtp/mail sender of a mail channel is every time the mail-channels mail adress "here: shop@xxxx.de"

**Comment by sojan-official** [comment]
@aswindevps  could you take a look?

**Comment by Soundmagic** [comment]
similar discussion ongoing in https://github.com/chatwoot/chatwoot/issues/3304#issuecomment-1012777762

**Comment by tejaswinichile** [comment]
@Soundmagic can you check the output in your console ENV.fetch('MAILER_SENDER_EMAIL')
If you are using the self-hosted version.

**Comment by Soundmagic** [comment]
here the output:
Loading production environment (Rails 6.1.4.3)
3.0.2 :001 > ENV.fetch('MAILER_SENDER_EMAIL')
 => "Gastroshark <shop@gastroshark.de>"
3.0.2 :002 >

Looks correct

**Comment by sojan-official** [comment]
@Soundmagic  could you try the steps mentioned here https://github.com/chatwoot/chatwoot/issues/3304#issuecomment-1043240194 ? 

let's track this further over #3304
