### ISSUE TITLE
Advanced contacts filters - Phone filter does not work 

### ISSUE THREAD

**Issue by fayazara** [chatwoot/chatwoot#3770]
**Describe the bug**

Contacts advanced filter does not work for phone number `equal_to` as well as `contains`, returns empty array. 

1. Go to Contacts page
2. Click on the filters icon
3. Select phone number as the attribute and enter a phone number from your contacts list
4. See empty contacts screen

**Comment by tejaswinichile** [comment]
@fayazara The phone number works on number

**Comment by fayazara** [comment]
Okay, I'll add a small message on the input.

**Comment by pranavrajs** [comment]
@fayazara Is it still happening?

**Comment by fayazara** [comment]
Yes, the contains filter does not work.

**Comment by fayazara** [comment]
@tejaswinichile @aswindevps Can you please look into this.

PS, the `Phone-Contains` filter combo throws a 500, this was tested on app.chatwoot.com.

https://user-images.githubusercontent.com/15716057/155672505-1c7eabf5-b034-4371-a69e-5c4d25139842.mp4

**Comment by pranavrajs** [comment]
@fayazara Can you please confirm the bug again and close it out?

**Comment by fayazara** [comment]
This seems to be fixed. Closing this.
