### ISSUE TITLE
Display 360Dialog API key in WhatsApp Channel settings

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3772]
we are not able to get the 360dialog api key from whatsapp channel settings

if i generate the api key from 360dialog then i go to chatwoot and i add whatsapp channel i can enter the 360dialog api key but later if i want to copy the api key to from chtwoot its not showing even in 360dialog so i have to regenerate the api key from 360dialog again then i have to add new whatsapp channel with new api key 

it should i can see the api key in whatsapp channel settings

**Comment by pranavrajs** [comment]
**Potential enhancements here:**

- [ ] Create a component to display sensitive data - For eg: API Token, Access Credentials etc. (@nithindavid) to provide the design spec. 
  - [ ] By default show masked valye `A12*********`
  - [ ] Clicking on the show (eye icon), display the unmasked value.
  - [ ] Have a button to copy the value.
- [ ] Use the component in the inbox settings for 360Dialog.
- [ ] Use the same component in profile settings.

**Comment by voko3456** [comment]
@pranavrajs @nithindavid please any update to this

**Comment by voko3456** [comment]
Any update on this because we are not able to get api key Evan via api
