### ISSUE TITLE
[CW-359] App store reviews

### ISSUE THREAD

**Issue by heroic** [chatwoot/chatwoot#3775]
**Is your feature request related to a problem? Please describe.**
Customers for a mobile app tend to request support on reviews on app/play stores. A good to have feature would be to capture all reviews below 4 stars(configurable) to be captured as conversations, and replies to this conversation going as reply on the app/play store

**Describe alternatives you've considered**
We currently use Zendesk for this

<sub>[CW-359](https://linear.app/chatwoot/issue/CW-359/app-store-reviews)</sub>

**Comment by pranavrajs** [comment]
@heroic Thanks for the suggestion, it seems like a great addition, will have to investigate the APIs and how it can be implemented.

**Comment by heroic** [comment]
@pranavrajs Hi, is there any timeline for this?

**Comment by sojan-official** [comment]
@heroic We don't have an ETA for this yet.

**Comment by scmmishra** [comment]
We can build a plugin SDK, make some changes to our main project to allow the community to build channels as plugins. Looks like a good project to work on.

~ Discussing this with @pranavrajs on a live stream
