### ISSUE TITLE
Mobile embed code

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#3776]
**Is your enhancement request related to a problem? Please describe.**
Would there be a way for chat to be embedded in iOS, Android or cross-platfrom applications? I imagine such a use case would rise with increasing user mobile first requirements

**Comment by pranavrajs** [comment]
@tabrza We are working on the native integrations. You can see the progress for iOS here https://github.com/chatwoot/ios-sdk

If you looking for cross-platform applications, then you can use ReactNative SDK. Please see the document here. 
https://www.chatwoot.com/docs/product/channels/live-chat/integrations/react-native-widget/

Please feel free to re-open the issue if you have more information to add.
