### ISSUE TITLE
Add the support for canned responses in contact messages

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3779]
Right now we can't send template message as canned response after add new contact and send message 

![image](https://user-images.githubusercontent.com/20530550/149788240-8ae6cc9e-b561-4b81-9a4a-b68b05d73210.png)

**Comment by pranavrajs** [comment]
Todo: 

- [ ] Support canned responses in contact message modal
- [ ] Replace/insert the content with canned responses when the user press enter.
