### ISSUE TITLE
postback event for card button(interactive messages)

### ISSUE THREAD

**Issue by sumit-s03** [chatwoot/chatwoot#3783]
please help with message card issue. in create card message api, how to do with "postback" template is here :
 { "content": "card message", "content_type":"cards", "content_attributes":{ "items":[ { "media_url":"https://assets.ajio.com/medias/sys_master/root/hdb/h9a/13582024212510/-1117Wx1400H-460345219-white-MODEL.jpg", "title":"Nike Shoes 2.0", "description":"Running with Nike Shoe 2.0", "actions":[ { "type":"link", "text":"View More", "uri":"google.com" }, { "type":"postback", "text":"Add to cart", "payload":"ITEM_SELECTED" } ] } ] }, "private":false }

![image](https://user-images.githubusercontent.com/84705104/149778505-95471000-5239-4235-809a-c34df8701d35.png)

add to cart button is not triggering how can be do with it.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/1895
