### ISSUE TITLE
issue in pulling survey related translation files from crowdin

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3784]
issue in pulling survey related translation files from crowdin

![image](https://user-images.githubusercontent.com/20530550/149787940-fcad65c0-a17c-45eb-84ee-4115776b77f9.png)

![image](https://user-images.githubusercontent.com/20530550/149787985-cb277796-10ff-4fb0-82a9-36e9d9355b68.png)
 
im not able to find showing text in translation file

**Comment by pranavrajs** [comment]
@sojan-official I believe that the proofreading step is messing up the translation. Is there a way we can update the text which was proofread before?

**Comment by sojan-official** [comment]
if you have proofreading permissions, you can switch to proofreading view and update the translations which are already marked as done 


<img width="1103" alt="Screenshot 2022-02-07 at 6 30 31 PM" src="https://user-images.githubusercontent.com/73185/152906748-6995cfa9-ff99-4c3b-8c99-aadb2e627731.png">
<img width="1248" alt="Screenshot 2022-02-07 at 6 30 44 PM" src="https://user-images.githubusercontent.com/73185/152906754-ed57a4b8-3605-4ea1-b145-0e8c36e27056.png">

cc: @pranavrajs  @voko3456

**Comment by voko3456** [comment]
@sojan-official I try to select proofreading and show all but I'm still not able to find this syntax-> "Dear customer please take few moments to complete the feedback about the conversation "

**Comment by voko3456** [comment]
Hi @sojan-official please any updates on this?

**Comment by pranavrajs** [comment]
<img width="1114" alt="Screenshot 2022-02-25 at 4 27 29 PM" src="https://user-images.githubusercontent.com/2246121/155703678-aaf6af5f-943c-486c-a41a-aea062500c57.png">


@voko3456 This should be fixed now, can you please login to Crowdin and see if you still cannot see the strings?
