### ISSUE TITLE
Twitter images are not shown in conversation messages

### ISSUE THREAD

**Issue by ammad-fareed** [chatwoot/chatwoot#3788]
If there's a message containing the images, it will show as a link to the message(not to the image). So, to see that image, we have to follow the link to see it on Twitter itself. I need the images to be in the message, not the link. Any suggestion/help will be appreciated, thanks.

**Comment by nithindavid** [comment]
@sojan-official @tejaswinichile Any thoughts on this?

**Comment by sojan-official** [comment]
We can prioritize this for future releases. 
- one possible candidate could be a generic link preview for messages.

**Comment by pranavrajs** [comment]
Closing in favor of #3875
