### ISSUE TITLE
Add the posibility to use sendmail on linux system

### ISSUE THREAD

**Issue by SNatis** [chatwoot/chatwoot#3798]
I created a server with Chatwoot and Postfix.
Unfortunately, i couldn't find a way to configure Chatwoot to use sendmail.
I had to edit the "config/initializers/mailer.rb" file to change line 6 to config.action_mailer.delivery_method=:sendmail

**Comment by iammattmartin** [comment]
You shouldn't need to do that.

"relay" is the correct setting for any standard MTA. 

https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity

**Comment by SNatis** [comment]
Hi !
Sorry, I only followed the documentation on the environment (https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables ) where it is not mentioned this possibility. As I have not yet configured the e-mail channel I had not gone through it yet.
