### ISSUE TITLE
feat: Keep CC:ed emails in agent replies

### ISSUE THREAD

**Issue by Robinjoeh** [chatwoot/chatwoot#3815]
**Is your feature request related to a problem? Please describe.**
The list of CC:ed emails is always empty and the agent has to add the CC:ed contacts to every reply.

**Describe the solution you'd like**
Make sure to always include the latest email CC:ed emails in the field by default to make sure the agent does not forget to include them.

![image](https://user-images.githubusercontent.com/13225711/150218648-cd6ca14b-0b32-4c5f-afc4-18d7e09bbc46.png)

**Comment by pranavrajs** [comment]
@nithindavid Can you please take a look at this and estimate the effort required?

**Comment by nithindavid** [comment]
Two ways to do this.
1. Keep the first emails CC and BCC
2. Keep the CC and BCC of last incoming email

Either way it looks like 1 pointer.

**Comment by Robinjoeh** [comment]
@nithindavid BCC is hidden from the recipient, so you wouldn't be able to see these in the email that was sent by the user to Chatwoot.

The best is probably to get the CC:ed contacts from the last incoming message, since lengthy conversations may have different people added/removed throughout the lifetime of the conversation.

This is also how it works on most other email software, such as Gmail and Outlook, so that should be the way to go!

**Comment by nithindavid** [comment]
@Robinjoeh Thanks for the suggestion. We will go with as you suggested :)
