### ISSUE TITLE
How to I receive a gps position from telegram

### ISSUE THREAD

**Issue by adcosoft-gb** [chatwoot/chatwoot#3821]
Hello, on chatwoot when I receive a gps position from telegram, I have the following message: No content available

How can I receive them on chatwoot from telegram?

**Comment by iammattmartin** [comment]
Support would need to be added in.

**Comment by adcosoft-gb** [comment]
I'm new, how can i add the support please?

**Comment by iammattmartin** [comment]
Well, you can code it yourself or you''ll need to consider this a feature request - or contact chatwoot and ask for a paid-for integration.

**Comment by adcosoft-gb** [comment]
no problem, thank you for your answer

**Comment by sojan-official** [comment]
ref: #3398

**Comment by pranavrajs** [comment]
Duplicate of #3398. Closing it as we can track the progress there.
