### ISSUE TITLE
Conversation for authenticated user not showing as resolved on first load with no cookies

### ISSUE THREAD

**Issue by cgb** [chatwoot/chatwoot#3825]
**Describe the bug**

I've been testing with a Firefox browser and deleting cookies on close.  On newly opened Firefox, loading a Chatwoot URL that performs authentication via set_user, the chat popup will default to the previous conversation, with a texbox to write new messages, when the conversation is marked as resolved.

Refreshing the browser (without closing, so that the second page load includes the set cookies), shows the conversation resolved as expected.

**To Reproduce**

1. Have a pre-existing user in Chatwoot with a previous conversation, marked as resolved
2. Load new browser with no cookies
2. Open chatwoot URL that performs authentication via set_user.

e.g. for my testing, I am opening
https://chatwoot/chat/index.html?email=my@email.address&name=MyName&h=MyHash

3. Chat popup defaults to showing the last conversation, with user able to type in message textbox, and no indication that conversation is resolved

4. Refresh the page without closing browser window.
5. Updated message history replaces message text box with 'Start a new conversation'

**Expected behavior**

As the user has authenticated, and Chatwoot has returned the last known conversation, it should show in the state the conversation is marked (resolved).

**Screenshots**

New browser, open URL that performs auth via setUser, previous conversation shown, not in resolved state:

![image](https://user-images.githubusercontent.com/202961/150483402-ace64080-4a8f-4e05-91ca-c55c264f7df5.png)

Refresh tab without closing browser:

![image](https://user-images.githubusercontent.com/202961/150483514-46a9fd1d-8f6c-47c0-9b7d-8f676ab1bcac.png)

Conversation now correctly shows as resolved, with user forced to start a new conversation to restart communication.

**Comment by pranavrajs** [comment]
@cgb Missed this one, will investigate this and let you know whether there is a bug or not.

**Comment by cgb** [comment]
Thanks @pranavrajs , much appreciated.
