### ISSUE TITLE
Custom Views bugs/improvements

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3826]
### Segments

- [x] Change the name to segments everywhere instead of custom views
- [x] On saving segments in contact, it should redirect to the view and hide the option to save the filter again.
- [x] Pagination button in the contacts doesn't consider filter, it is bringing all the results
- [x] Filter returns unidentified contacts also
- [x] After saving (without refresh) if you click on the segment, it returns the result without applying the filters.
- [x] Loading a custom view fetches the contacts without filters first and then fetches the contacts with filters. See this video https://www.loom.com/share/fb9c4e55969b47d0b5b7a68dd5de2da3

### Folders

- [x] Change the name to folders everywhere instead of custom views
- [x] Change the text "Clear Filters" to "Clear filters"
- [x] Long button text on the delete modal is broken. Keep it simple "Yes, delete" & "No, keep it".
- [ ] Filter breaks when there are multiple pages (Re-opened the custom filter issue handled by Fayaz)
- [x] After saving the folder, it should redirect to the view instead of staying in the filter page.
- [x] Change the toast message from "Custom View deleted successfully" to "Folder deleted successfully"

**Comment by iamsivin** [comment]
Pending: https://github.com/chatwoot/chatwoot/issues/3739
