### ISSUE TITLE
bug: New account creation page get stuck even after account is created

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3829]
When a user who doesn't have any account user relationship logs in, Chatwoot shows up the account creation form. 
But after creating the account using the form, the user still ends up remaining on the same page, until they manually refresh. 

This leads to the user click create button multiple times and ends up creating multiple accounts

<img width="1333" alt="Screenshot 2022-01-21 at 5 18 47 PM" src="https://user-images.githubusercontent.com/73185/150619003-c8cb3c1a-c745-47df-81ac-a33ca7f574d1.png">

**Comment by scmmishra** [comment]
Tracking a related issue [here](https://linear.app/chatwoot/issue/CW-355/page-loads-infinitely-if-a-user-who-is-not-associated-to-any-account)
