### ISSUE TITLE
[CW-354] Merge Tags for Channel Greetings

### ISSUE THREAD

**Issue by ajtatum** [chatwoot/chatwoot#3833]
For this request, I'll provide an example.

Someone messages us via Chatwoot and we have their first name already, either through them being a previous contact or from their email or social media account, it would be awesome to be able to have the channel greeting be: "Hello {FirstName, 'there'}!"

What this would do is use the FIrstName of the contact and if that's not provided use some default text, ie: "there" as shown above.

Please let me know if you have any questions!

Thanks,
AJ

<sub>[CW-354](https://linear.app/chatwoot/issue/CW-354/merge-tags-for-channel-greetings)</sub>

**Comment by pranavrajs** [comment]
@ajtatum Sounds like a great enhancement. Adding this to the product discussions.

**Comment by sojan-official** [comment]
ref: #1886

**Comment by tejaswinichile** [comment]
If this is happening on new message on already resolved conversation we can handle it thorough conversation_opened event in automation.

cc @pranavrajs

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please confirm if we can close this issue with the latest release?

**Comment by tejaswinichile** [comment]
[https://github.com/chatwoot/chatwoot/pull/6971](https://github.com/chatwoot/chatwoot/pull/6971) Has been solved by this PR.
