### ISSUE TITLE
Support reply-to header in emails? Can make PR

### ISSUE THREAD

**Issue by robguthrie** [chatwoot/chatwoot#3834]
**Is your enhancement request related to a problem? Please describe.**
I recently tried to integrate chatwoot into our systems. We don't actually want real time chat (we don't have capacity to deliver on realtime support, we're a tiny team in an uncommon timezone). But I really love chatwoot as a issue tracking system. It beats all the other open-source products out there.

Our main communication channel is email. I tried integrating the live chat widget, but realized that we can't respond via email later on if the conversation is started in a chat channel, also the customers get disappointed when we can't respond in real time. Then i tried integrating your API, it required a lot of logic and network requests to create or search a contact, conversation, add message etc, and has the same problems as the chat channel.

By far the simplest way to integrate chatwoot, for us, is to have a web-form which sends an email. The FROM header is fixed (we can't spoof a from header from our server), but I can put the customer name and email into the REPLY-TO header. I have made a 2 line change to chatwoot to prefer the reply-to header when parsing an email in the IMAP processor. This way, our systems can send emails in from web-forms, and we can reply via email from within chatwoot. It works really well!

**Describe the solution you'd like**
2 changes are on my mind. Firstly, if you would like, I can make a pull request with my changes to prefer a REPLY-TO header before the FROM header in your email processor.

The other idea, is the ability to reply via email when a conversation is started in a chat or api channel, and I'm wondering what you think about that.

Thanks so much for this great product!

**Comment by pranavrajs** [comment]
@robguthrie Thanks for the feedback. This is a asked by other customers as well. If I understand this correctly, you are requesting to give preference for the `reply-to` header first and then the `from` header right? 

Please feel free to raise a PR. Happy to guide you if you need anything.
