### ISSUE TITLE
Add filter by date in custom views to filter the conversion by date

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3840]
- [ ] Add support for last_activity_at filter
- [ ] Add support for created_at filter

| Attribute | Supported Filters |
|-|-|
| created_at | Is greater than, Is less than, Is x days before |
| last_activity_at | Is greater than, Is less than, Is x days before  |

**Comment by pranavrajs** [comment]
@voko3456 I've updated the description so that this can be picked up easily.

**Comment by pranavrajs** [comment]
@tejaswinichile Can you please take a look at this and evaluate the effort to pickup this up in the next sprint?

**Comment by tejaswinichile** [comment]
- created_at: [is_less_than, is_grater_than]

```
attribute_name: created_at 
filter_operator: <> 
filter_value: date
```
- created_at: [x days before]

```
attribute_name: created_at 
filter_operator: 3_days_before/3_days
filter_value: date
```

@pranavrajs For the is_x_days_before filter should I return the conversation/contacts got created x_days before the filter value date?

I was thinking it would be proportional to today's date like conversation created 3_days_ago.

I am not able to understand the filter, we can have a call once you are back, till the time I am finishing first 2 filter operator.

**Comment by pranavrajs** [comment]
@tejaswinichile This is the use case. I want to see all the conversations that are in an open state that was created X days before. I want to look at this every day and see if we need to take any action on it. With the custom views, we can save this filter, and I can come back to this filter every day to see the conversations we need to take action on.

This would be an is_less_than filter, but the date is dynamically generated and is relative to the current date here. Let me know if this makes sense.
