### ISSUE TITLE
Add the API to change the status of multiple conversations at once

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3845]
- [ ] Accept conversation ids, status as the parameters
- [ ] Verify that the user has permission to resolve the conversation (should have access to the inbox / should be an admin). Return a 401 if conversation permissions are not available.
- [ ] Namespace under bulk_actions/status_change

**Additional thoughts:**
- Can be done as a job instead of doing it while calling the API.

**Comment by tejaswinichile** [comment]
@pranavrajs Just to confirm, when we say conversation_ids, are those conversations' display_id or primary id?

**Comment by pranavrajs** [comment]
@tejaswinichile Yes, display_ids not primary ids.
