### ISSUE TITLE
Add an option in the UI to select multiple conversations and change status

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3846]
- [ ] https://github.com/chatwoot/chatwoot/issues/4525
- [ ] https://github.com/chatwoot/chatwoot/issues/4523
- [ ] https://github.com/chatwoot/chatwoot/issues/4524
- [ ] https://github.com/chatwoot/chatwoot/issues/4522

----

- [ ] Update the UI to select multiple conversations at once.
- [ ] Update the store / actions to perform bulk action.

**Comment by pranavrajs** [comment]
@tejaswinichile Since the PR for API is merged, can you please make sure that APIs are documented and available for @nithindavid to start working on it.

**Comment by pranavrajs** [comment]
@nithindavid Please work on the design and UI flow for this ticket this sprint.

**Comment by nithindavid** [comment]
I have created couple of frontend tasks for the epic.

https://github.com/chatwoot/chatwoot/issues/4525
https://github.com/chatwoot/chatwoot/issues/4523
https://github.com/chatwoot/chatwoot/issues/4524
https://github.com/chatwoot/chatwoot/issues/4522

Let me know your thoughts @pranavrajs @sojan-official @fayazara

**Comment by nithindavid** [comment]
@pranavrajs Close this issue after reviewing the design?

**Comment by pranavrajs** [comment]
Let us keep this for now. If you need, we can create separate tickets for design next time.

**Comment by nithindavid** [comment]
Makes sense 👍
