### ISSUE TITLE
Can't send message for new contacts on 360Dialog

### ISSUE THREAD

**Issue by SamuelMoraesF** [chatwoot/chatwoot#3850]
**Describe the bug**

Message is not sent for new contacts

**To Reproduce**

Add a new contact and try to send a message using 360Dialog. AFAIK, we need to send user contact/phone to the following endpoint before sending a new message:

`https://waba.360dialog.io/v1/contacts`

**Environment**

Hosted server

**Comment by pranavrajs** [comment]
@SamuelMoraesF You can only send WhatsApp approved templates when you are sending an outbound message. Can you please confirm whether you are using a WhatsApp-approved message? Otherwise it wouldn't deliver the message.

**Comment by SamuelMoraesF** [comment]
Yes, it's an approved message.

I just can send messages to contacts that I already messaged before. For new contacts I receive the response "1006 Resource not found - unknown contact". According to API:

`Before sending a message, make sure you meet the prerequisites and use the /v1/contacts endpoint for each number. Otherwise, you may receive a 1006 "Resource not found - unknown contact" error` (https://docs.360dialog.com/whatsapp-api/whatsapp-api/messaging)

**Comment by sojan-official** [comment]
@SamuelMoraesF Thanks for reporting.  We will verify this and have a fix for the same.

**Comment by sojan-official** [comment]
ref: https://developers.facebook.com/docs/whatsapp/on-premises/reference/contacts
<img width="1104" alt="Screenshot 2022-08-18 at 5 46 54 PM" src="https://user-images.githubusercontent.com/73185/185392619-6d7d13f7-819c-4500-9e55-7db45a7537b6.png">
