### ISSUE TITLE
feat: Ability to customise prechat from text

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3856]
> I have a feature request for the chat widget/chatwoot UI Pre Chat form. Is it possible to change the text on the pre chat form so that we can choose the placeholder text in the message body. Currently it defaults to 'Please enter your message'. It would be great to be able to replace this with our own text. For example I would like to use 'How can we help you today'.

ref: https://discord.com/channels/647412545203994635/647729576427913228/934396944535650324

**Comment by scmmishra** [comment]
This is already done, refer screenshot below

<img width="876" alt="image" src="https://user-images.githubusercontent.com/18097732/225218099-4b95b950-bac7-4d8e-8921-30865223b811.png">
