### ISSUE TITLE
User info is not visible in the conversations

### ISSUE THREAD

**Issue by alejandroTecDam** [chatwoot/chatwoot#3863]
**Describe the bug**
User info is not visible 

**To Reproduce**
I pass a user info with the identifier_hash generated from by User Identity Validation, but I can't see the info in the user conversation.

There is the code I do to pass the info. The custom attributes is passed correctly.
I have activated the Enforce User Identity Validation in the config.

```
window.addEventListener('chatwoot:ready', function () {
   window.$chatwoot.setUser('Unique key', {
        name: '******', // Name of the user
        avatar_url: '', // Avatar URL
        email: '*****', // Email of the user
        identifier_hash: '********',
        phone_number: '66666666', // Phone Number of the user
     })

     window.$chatwoot.setCustomAttributes({
         accountId: 1,
          pricingPlan: 'paid',
      });
});
```

**Comment by pranavrajs** [comment]
@alejandroTecDam Can you please share if there are any errors in your browser console/network tab?

@muhsin-k I think we can throw an error event if there is any error in identifier_hash.

**Comment by alejandroTecDam** [comment]
Thanks for your answer,
I've tried to create a new event like 
`window.addEventListener('chatwoot:error', function (error) {
            console.log(error)
        });`
But doesn't display nothing in the console, I'm doing something wrong?

**Comment by pranavrajs** [comment]
@alejandroTecDam This is not implemented yet, @muhsin-k would take care of the implementation of the event.
