### ISSUE TITLE
[CW-352] enhancement: Track user across subdomains

### ISSUE THREAD

**Issue by nosovk** [chatwoot/chatwoot#3870]
**Describe the bug**

When we use chatwoot on a product with few domains involved in customer journey it seems that user session not tracked across subdomains.

**To Reproduce**

1. Go to https://www.mailcheck.co
2. Click on Start chat, write down test message
3. Go to https://app.mailcheck.co
4. Click Start chat

**Expected behavior**

I expect to see message from first chat. In common I expect that user chat session will move across subdomains.

**Environment**

We use selfhosted version at heroku, mapped to chat.mailcheck.co

<sub>[CW-352](https://linear.app/chatwoot/issue/CW-352/enhancement-track-user-across-subdomains)</sub>

**Comment by pranavrajs** [comment]
@nosovk Thanks for sharing this, we don't support subdomains at this as it creates confusion around where to store the cookies (whether it should be on the parent or on the subdomain). We need more time to investigate the best practices around this.

**Comment by nosovk** [comment]
Ok, in common we can allow to set cookie domain in script initialization as additional param, because common practice to split landing and application causes history flapping, which looks weird for visitors.

**Comment by nosovk** [comment]
Any additional information needed for investigation?

**Comment by sojan-official** [comment]
@nosovk not at the moment. It's just that we haven't been able to prioritize this yet.

**Comment by nosovk** [comment]
Ok, I just thought that it's common case when company splits functionality across domains
https://www.chatwoot.com/
https://app.chatwoot.com/
You can't track users between your own domains…, It means starting ticket on documentation page is bad idea, if you want to continue in app dashboard,

**Comment by yuri-mish** [comment]
We have the same issue, otk.in.ua and lab.otk.in.ua. We can't track users across domains :(

**Comment by destring** [comment]
This is much needed feature. we were using smartsupp which had this feature and users were able to continue the chat while navigating the site including subdomains... 

I think using custom values for cookie domain will do... https://docs.smartsupp.com/chat-box/configuration/#sub-domains-integration

**Comment by nosovk** [comment]
@sojan-official if it's been removed from 2.8.0 - any plans to include it to 2.10.0?

**Comment by sojan-official** [comment]
Note: pending ask for a long while.

**Comment by nosovk** [comment]
@scmmishra can you please add link to doc how it's could be fixed now with latest update? I don't found any doc updates in PR.

**Comment by scmmishra** [comment]
> @scmmishra can you please add link to doc how it's could be fixed now with latest update? I don't found any doc updates in PR.

Sure we will update the docs soon, for now you can set the baseDomain parameter in your window.chatwootSettings to use it

CC: @nithindavid
