### ISSUE TITLE
Support image previews in Twitter DM instead of rendering links

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3875]
I'm not able to preview twitter and Instagram dm images in chatwoot chat

**Comment by pranavrajs** [comment]
@aswindevps Let us investigate and implement the changes required to properly render images from Twitter instead of rendering it as a t.co link.

**Comment by Soundmagic** [comment]
Please extend the enhancement  to Mail channel as well.

**Comment by aswindevps** [comment]
Refer: https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/message-attachments/guides/retrieving-media
