### ISSUE TITLE
Cannot signup on Heroku deploy

### ISSUE THREAD

**Issue by pferder** [chatwoot/chatwoot#388]
After the one-click deploy I tried to create an account, and this is what I'm getting for response.

xhr.js:166 POST https://bioconstruccion-chat.herokuapp.com/api/v1/accounts.json 500 (Internal Server Error)

> {"error":"500 error","message":"Got unknown keys: [\"account_name\", \"email\"]; allowed keys: [:account_name, :email]"}

What could it be? Thanks!

**Comment by pranavrajs** [comment]
@pferder This looks like a bug, we will debug this. Meanwhile, were you able to login with this default credentials? https://www.chatwoot.com/docs/quick-setup#login-with-credentials

**Comment by pranavrajs** [comment]
@pferder This was a bug introduced in one of the recent changes. This has been fixed, you should be able to signup after you redeploy.
