### ISSUE TITLE
Video & Audio Chat Functionality

### ISSUE THREAD

**Issue by prononext** [chatwoot/chatwoot#3881]
Dear Chatwoot Team, 

are there any plans to include Video and Audio Chat into Chatwoot?
That would be really nice. Tawk.to has that function. 

You could use the existing Jitsi Meet Code to get it working https://github.com/jitsi/jitsi-meet

There is also a Jitsi Meeting Scheduling Application, which could run nicely together with Chatwoot:
https://github.com/H2-invent/jitsi-admin

Of course the Video and Audio Chat can not be used in every channel but Website Widget for sure...

Have a nice day!

**Comment by scmmishra** [comment]
Hey @prononext we already have merged [dyte.io](https://dyte.io) integration recently. The docs will be up soon. 

![image](https://user-images.githubusercontent.com/18097732/225215645-a4bf8c0d-f8c9-4524-be3f-c4467676f246.png)
