### ISSUE TITLE
CustomCSS in Live-Chat-Widget

### ISSUE THREAD

**Issue by prononext** [chatwoot/chatwoot#3882]
It would be nice to have the possibility to get injected CustomCSS working inside the Live-Chat-Widget. 

At the moment it is rendered in a frame, which does not allow any CSS. 
Allowing the CSS rendering in the widget shortcode would be really nice. 

Example: 
`    <script>
      (function(d,t) {
        var BASE_URL="https://app.chatwoot.com";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: 'XXXXXXXX',
            baseUrl: BASE_URL,
            customCSS: '.myclass{blah: blah;}.myAnotherClass{blah: blah;}'
          })
        }
      })(document,"script");
    </script>`

_I created this Issue as the following is not really going in the right direction and is really hard to find. 
https://github.com/chatwoot/chatwoot/issues/1598_

**Comment by sojan-official** [comment]
@prononext  closing in favour of https://github.com/chatwoot/chatwoot/issues/1598#issuecomment-1078927481

lets track this over the original issue #1598
