### ISSUE TITLE
[CW-367] Dialogflow - Custom Payload

### ISSUE THREAD

**Issue by prononext** [chatwoot/chatwoot#3883]
Is there any possibility to customize the payload on Dialogflow to hand over other data from dialogflow agent into Chatwoot?
The only custom payload that was working is the handoff https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow#creating-a-handoff-intent

With additional Payload possibilities, Context/Entities of the Dialogflow conversations could be filled into the contact/conversation info of the Chatwoot sender:

Data Examples would be:
- Sender Name
- Sender E-Mail
- Sender Phone
- Custom Attributes (Contact/Communication)

Does anyone have a idea how to get it done, maybe there is also a alternative way using Webhooks?

![image](https://user-images.githubusercontent.com/24569958/151866183-05b59562-7519-4734-a8e7-392906c228ab.png)

Have a nice day!

<sub>[CW-367](https://linear.app/chatwoot/issue/CW-367/dialogflow-custom-payload)</sub>

**Comment by ChrisvanChip** [comment]
Especially custom attributes will be really useful for this. The chatbot can easily fill in the contact information & properties while waiting for an agent. 

Natural-Language Processing feels more natural than a long contact form.

**Comment by prononext** [comment]
what specs are needed? The general handoff payload is working fine. 
I would suggest to give the possibility to hand over 

- all contact data which is available in Chatwoot including
- all contact attributes and
- conversation attributes; also
- handover customization to specific team or agent is needed

Via custom payload in Dialogflow.
Have a great day!
