### ISSUE TITLE
PDF,CSV,TXT,XLS documents not showing in whatsapp 360dialog chat

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#3886]
PDF,CSV,TXT,XLS documents not showing in whatsapp 360dialog 

@sojan-official 
@pranavrajs 

can you please check this bug.

**Comment by iammattmartin** [comment]
Best not to @ people directly as creates unneeded notifications.

**Comment by pranavrajs** [comment]
@voko3456 This must be solved via #3768. Let me test it out and come back.

**Comment by voko3456** [comment]
Hi @pranavrajs did you test it I see the PR is merged but still we can't receive csv and pdf and txt and xls

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/3701
