### ISSUE TITLE
Staff email template appears incorrectly

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#3896]
**Describe the bug**

Staff email notifications appear to be rendered incorrectly. The same does not happen for visitors.

The bubble appears to be underneath the text. Whereas in the visitor email the text is within the bubble.

![Screenshot 2022-02-02 at 6 50 15 PM](https://user-images.githubusercontent.com/15971590/152218667-135f1b7f-796e-48f2-808d-a55a965b827b.png)

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/3857

This case was also covered in the PR. This would be available in the next release.
