### ISSUE TITLE
No webhook Request on conversation opened

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot#3897]
We only Recive   [event] => message_created. 

i need an event for opening Conversation. conversation_status_changed is not sendet

**Comment by pranavrajs** [comment]
@sojan-official @muhsin-k I believe the conversation_created event is not firing in webhooks, let us add that as well and along with that please debug conversation_status_changed event.

**Comment by muhsin-k** [comment]
@drexlma I have tested the `conversation_status_changed` event, It seems like it is working whenever the conversation status changes.

https://user-images.githubusercontent.com/12408980/153139163-d93c5ca9-507d-4019-bb7e-873f6010509d.mov

Could you please share more details like whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot, Application version etc? It would be better to add a screencast too.


> @sojan-official @muhsin-k I believe the conversation_created event is not firing in webhooks, let us add that as well and along with that please debug conversation_status_changed event.

@pranavrajs Yes. The event `conversation_created` is missing. I will create PR for that.
