### ISSUE TITLE
[CW-370] Add a build ID to distinguish deployments based on develop branch

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#3905]
**Is your feature request related to a problem? Please describe.**
Currently, continuous deployments using the `develop` branch are not distinguishable since we don't create a tag for every merge to develop. 

**Describe the solution you'd like**
Generate a build number that is incremented for every merge to develop/master. Have this be displayed next to the version on the settings page. 

**Describe alternatives you've considered**
Use the commit hash as the build ID.

**Additional context**

![image](https://user-images.githubusercontent.com/3526167/152329765-42aeeea2-5661-4292-865e-1ed907ecbb7e.png)

<sub>[CW-370](https://linear.app/chatwoot/issue/CW-370/add-a-build-id-to-distinguish-deployments-based-on-develop-branch)</sub>

**Comment by sojan-official** [comment]
We could use the commit id. 
Could have it returned on the url/api end point as well

ref: https://blog.andrewvc.com/making-life-easier-with-git-shas-in-your-http
https://stackoverflow.com/questions/8407126/getting-current-git-commit-version-from-within-rails-app

**Comment by scmmishra** [comment]
@vn see if you can pick it up this sprint.
