### ISSUE TITLE
enhancement: Support additional custom payloads via dialogflow

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3911]
ref: https://discord.com/channels/647412545203994635/848225049059917834/936765422450147349

> Is there any way to customize the payload inside the  Dialogflow to hand over contexts and entities eg. data from the conversation to fill into the senders contact data and attributes?
![unknown](https://user-images.githubusercontent.com/73185/152462043-1fd2c58a-833b-472b-81cc-366bdcbb2061.png)

> also handing off to a specific team or agent would be helpful instead of just general handoff.

**Comment by pranavrajs** [comment]
Duplicate  https://github.com/chatwoot/chatwoot/issues/3883
