### ISSUE TITLE
feat: Scroll to the latest message automatically (autoscrolling)

### ISSUE THREAD

**Issue by ChrisvanChip** [chatwoot/chatwoot#3914]
**Is your feature request related to a problem? Please describe.**
For every message the customer sends, I have to scroll down to see the new message. This causes a lot of frustration in the end, because it just doesn't feel fluent and it gets boring over time.

**Describe the solution you'd like**
- When I'm already at the bottom & a new element (message) comes in -> Scroll to bottom
- When I'm not at the bottom (for example reading history) -> Do nothing

This has a significant benefit to the User Experience & efficiency without too much effort, from my perspective. 

**Describe alternatives you've considered**
There's no easy alternative to this, beside messing around with the interface myself (and break Chatwoot at some point, I'm not experienced with Ruby 😅).

**Comment by ChrisvanChip** [comment]
Looks like it's related to #3622, can be merged.

**Comment by sojan-official** [comment]
Closing in favour of #3622
