### ISSUE TITLE
Reset is resetting the user as well, won't keep things in one conversation

### ISSUE THREAD

**Issue by lilsweetkara** [chatwoot/chatwoot#3915]
First of all, I am a terrible coder. I learned a few things from my husband, who is a software engineer, but I am generally speaking terrible at this. Sorry.

I am trying to have the chat bubble appear only for logged in users. I have a simple (crappy) node app using EJS.

I am using app.chatwoot.com
I have three problems.

1) I am using a terrible hack to hide it if the user is not logged in. I am currently doing this:

````
<style>
...

    <%if(!session.loggedIn) { %>
    .woot-widget-bubble {
        display: none;
    }

</style>
````

Is there a better way of doing it?

2) I manage to have `setUser()` correctly. The result works. However, whenever a user logs out and logs in again, they don't see the old chats, but a new conversation.

![image](https://user-images.githubusercontent.com/83156400/152667273-7053d535-2a23-4d47-94d5-4fdf094441b7.png)

This is the code I have in my header:

````

<%if(session.loggedIn) { %>

<script>
    (function(d,t) {
      var BASE_URL="https://app.chatwoot.com";
      var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=BASE_URL+"/packs/js/sdk.js";
      g.defer = true;
      g.async = true;
      s.parentNode.insertBefore(g,s);
      g.onload=function(){
        window.chatwootSDK.run({
          websiteToken: 'XXXXXXXXXXXXXXXX,
          baseUrl: BASE_URL
        })
      }
    })(document,"script");

    window.addEventListener('chatwoot:ready', function () {
        debugger
        window.$chatwoot.setUser('<%=session.loggedInEmail%>', {
            email: '<%=session.loggedInEmail%>',
            name: '<%=session.loggedInEmail%> <%=session.subscriber ? 'PAID' : 'FREE'%>' 
            identifier_hash: '<%=hash%>',
        });
    });        

  </script>
  
  <% } else { // This happens if user is NOT logged in  %>    
    <script>
      let alreadyReset = false
      window.chatwootSettings = {
        showPopoutButton: false
      };      
        (function(d,t) {
          var BASE_URL="https://app.chatwoot.com";
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src=BASE_URL+"/packs/js/sdk.js";
          g.defer = true;
          g.async = true;
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            window.chatwootSDK.run({
              websiteToken: 'XXXXXXXXXXXXXXXXX',
              baseUrl: BASE_URL
            })
          }
        })(document,"script");
    
        window.chatwootSettings = {
        showPopoutButton: false
      };
      
        window.addEventListener('chatwoot:ready', function () {
            debugger
            if (!alreadyReset){
              window.$chatwoot.reset()
              alreadyReset = true
            }

        });
      </script>
    
  <% } %>
````
If a page is loaded and the user is not logged in, I run a reset() (which is why I still need the widget loaded).
I assumed that `reset()` would only clean up the user session. However, once `setUser()` is run, I expected the widget to resume with the user by that ID?

3) 
Also, I have to have that `alreadyReset()` variable there, since 1) I need to wait for `chatwood:ready` 2 After reset, the event `chatwoot:ready` is emitted again, and reset() is run again. And again. And again. and...

Am I doing it all wrong?

**Comment by lilsweetkara** [comment]
My husband just pointed out this ticket to me:

https://github.com/chatwoot/chatwoot/issues/1120

So yes. I had managed to stuff up the code (I was using the wrong token for HMAC) and that's why chat logs were not persistent.

I think you should add that to the documentation. I created my very first pull request _everrrrr_... please let me know what I did wrong :dagger: 

I am closing this ticket, and opening a new one with the two other issues I have (my husband won't help... grrrrrr)

**Comment by pranavrajs** [comment]
@lilsweetkara Closing this ticket as we would continue the discussions in #3918

**Comment by lilsweetkara** [comment]
Thank you!
