### ISSUE TITLE
New conversations do not appear after network reconnect from standby

### ISSUE THREAD

**Issue by Christilut** [chatwoot/chatwoot#3916]
**Describe the bug**

Chatwoot does not automatically reconnect after the network connection is lost. In this case from keeping the chatwoot tab open and putting the computer into standby.

**To Reproduce**

1. Open chatwoot dashboard. No conversations are pending.
2. Close laptop lid
3. Open laptop a while later
4. Go to chatwoot tab
5. No conversations appear
6. Refresh page: new conversations appear

**Expected behavior**

Chatwoot should automatically refresh the page or fetch the new conversations.

**Environment**

Managed chatwoot.com

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Chrome 97

**Comment by pranavrajs** [comment]
@Christilut Doesn't it show the alert as shown below to refresh once you disconnect from the network (close the lid)?  

![image](https://user-images.githubusercontent.com/2246121/152728253-2248de5a-9ca6-4563-aa02-a8cedd9d679f.png)

We don't have the mechanism to auto-fetch the conversations, however, the alert shown above seems to be enough to share there has been updates which you have not seen.

**Comment by Christilut** [comment]
I've seen that notification but it doesn't always show.
I just closed my macbook for an hour or so and then opened it while chatwoot was open, but no notification.

Maybe an idea to keep track of the last succesful ping/request to the server and with `navigator.onLine` to auto refresh the page, if the last ping was a certain amount of time ago? Maybe 5 minutes?

**Comment by pranavrajs** [comment]
@Christilut Makes sense, let me investigate this and update as necessary.

**Comment by giquieu** [comment]
I was looking at this function today and I noticed that it might be interesting not to show the close button... Showing only the refresh button will induce the user to click only the right button.
Of course, that is not the case in this issue.

**Comment by Christilut** [comment]
I think there might be more going on because I'm on my desktop right now (with 100% stable and reliable internet) and I still saw the "Chatwoot is disconnected" notification. Maybe it was a chatwoot server issue this time, I'm not sure.

I do think adding an automatic reconnect/resync feature is essential here because at the moment I can't rely on Chatwoot showing me the latest conversations so I always refresh the page just to be sure.

**Comment by sojan-official** [comment]
@Christilut Chatwoot receives real-time data via WebSockets. When your browser tab is in an inactive state, chrome ends up disconnecting this connection and hence the notification. 

We are looking into ways to resync the information in such cases.

**Comment by Christilut** [comment]
Okay understood. It would be great if it automatically resynced when the connection is restored.
Now I very frequently refresh the chatwoot site because I'm not sure if what I'm looking at is accurate.
