### ISSUE TITLE
bug: Line channel is not working for outgoing messages

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#3920]
**Describe the bug**

We are having problem sending message out to our customer in Line@ (official account) channel. Where our customer cannot see the message that we sent through Chatwoot.

**Additional context**

Reported by a customer on cloud account.

**Comment by sojan-official** [comment]
@nithindavid  verified that this is working on our end. 
Is there more specifics to this report like the message type ?


<img width="404" alt="Screenshot 2022-02-07 at 6 41 05 PM" src="https://user-images.githubusercontent.com/73185/152907810-0561a73c-a642-4a35-b2b2-d069e0d0040d.png">

**Comment by perry** [comment]
Can confirm this is not working for me either, on a fresh SaaS install. It was working originally, then stopped with no changes to settings.

<img width="1154" alt="Screen Shot 2022-02-27 at 18 39 03" src="https://user-images.githubusercontent.com/952316/155880891-a889223c-accc-499d-b04e-8f28590e5f8f.png">

![IMG_9670](https://user-images.githubusercontent.com/952316/155880929-9ee376aa-d51c-4e5b-835f-951dca82257f.PNG)

**Comment by perry** [comment]
Very strange, the messages just appeared in the LINE app after ~5 minutes of not appearing.

![IMG_DEEE1D28B854-1](https://user-images.githubusercontent.com/952316/155881011-a1e3affb-944e-4f29-a878-26932ca50f27.jpeg)

**Comment by sojan-official** [comment]
Let's reopen the issue if it still persists.
