### ISSUE TITLE
AudioContext warning when loading Chatwoot widget on Chrome

### ISSUE THREAD

**Issue by jschaf** [chatwoot/chatwoot#3930]
**Describe the bug**

Any use of chatwoot widget causes a warning in the console on Chrome about AudioContext.

**To Reproduce**

1. Go to https://www.chatwoot.com/
2. Open the console
4. See error: The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Expected behavior**

Chatwoot should not cause a warning.

**Browser logs**

The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

**Server logs**

N/A

**Environment**

Any installation of the Chatwoot widget.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 98.0.4758.80

**Additional context**

This looks like how Chrome prevents sites from auto-playing with out user interaction. Some relevant threads:

- Auto play policy in Chrome: https://developer.chrome.com/blog/autoplay/#webaudio
- Simple solution: https://www.mattmontag.com/web/unlock-web-audio-in-safari-for-ios-and-macos
- https://github.com/katspaugh/wavesurfer.js/issues/1531

My guess is you need to grab the audio context on click instead on window.onload here https://github.com/chatwoot/chatwoot/blob/9c31d7c672d4f9743ce3a18910d905fe841be7cf/app/javascript/packs/widget.js#L36

**Comment by pranavrajs** [comment]
@jschaf I can reproduce this, thanks for reporting this issue. Let us debug this further and come up with a solution.
