### ISSUE TITLE
Add support for Created At, Last Activity At filters in the UI

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3938]
As per https://github.com/chatwoot/chatwoot/issues/3840, the support in the API for last_activity_at and created_at is added. Add this to the UI for the conversation filter as well.

- [ ] For Is greater than, Is less than use date picker.
- [ ] For is X days before, use number input, validation number should be greater than 0, less than 999
- [ ] Support the filter both on conversation and contact.

**Comment by fayazara** [comment]
@pranavrajs If we're changing input types based on the filter operator, one conflict thats coming is, its not necessary that each operator will have its own fixed input type.

Example.
`equal to` for email can have input type as a free email field, the same `equal to` can expect a dropdown for selecting an agent or a label.

How do we handle this?
