### ISSUE TITLE
Add the API to change the assigned agent/teams of multiple conversations at once

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3940]
- [ ] Accept conversation ids, assignee_id, or team_id as the parameters
- [ ] Verify that the user has permission to assign the conversation (should have access to the inbox / should be an admin). Return a 401 if conversation permissions are not available.
- [ ] Namespace under bulk_actions/status_change

**Additional thoughts:**
- Can be done as a job instead of doing it while calling the API.

**Comment by tejaswinichile** [comment]
Will be fixed by #3934
