### ISSUE TITLE
Add the API to add/remove labels to/from multiple conversations at once

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3943]
- [ ] Accept conversation ids, labels, action (add/remove, can be done as POST/DELETE as well) as the parameters
- [ ] Verify that the user has permission to assign the conversation (should have access to the inbox / should be an admin). Return a 401 if conversation permissions are not available.
- [ ] Namespace under bulk_actions/status_change

Additional thoughts:

- Can be done as a job instead of doing it while calling the API.
- Should not remove an existing label while adding a label.

**Comment by tejaswinichile** [comment]
Will be fixed by #3934
