### ISSUE TITLE
Custom Filter: Use correct input type while rendering filter for custom attributes

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3944]
In Custom Filters, custom attributes use a text input irrespective of the type of the attribute. The attributes should use the following input types.

| Attribute Type | Input Type |
| -- | -- |
| List | Multi-Select |
| Number | Number input |
| Text | Input |
| Checkbox | A dropdown that has True/False as options |

**Comment by fayazara** [comment]
@pranavrajs For `List-Multiselect` combo, I think we should have `Plant text` because when setting a list type attribute to a conv, it just allows us to choose one.

**Comment by pranavrajs** [comment]
@fayazara I'm not sure whether I understand this, if we have multi select option is there a problem? 

I don't want people to be searching for other values when we only save a specific set of attributes.

**Comment by fayazara** [comment]
@pranavrajs let me know how to proceed on this.

**Comment by pranavrajs** [comment]
@fayazara I'm not sure if I understand this completely. 

If the custom attribute definition has only one value (eg: Priority attributes with only one accepted value P0), then the multi select also would have one value in the selection.
