### ISSUE TITLE
Automation enhancements

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3951]
**New events:**

- [ ] Contact Created
- [ ] Contact Updated
- [ ] Label Added
- [ ] Label Removed

**Conditions:**

- [x] #4458
- [x] #4459

**Actions**

- [x] #4015
- [x] #4179

**Comment by pranavrajs** [comment]
@tejaswinichile @fayazara Can you please take a look at this ticket and estimate the effort?

**Comment by fayazara** [comment]
@pranavrajs What conditions will `Label` events have?

**Comment by tejaswinichile** [comment]
@pranavrajs 

1. Adding new events and new conditions would 1.5-2 days task, can be done the current implementation
2. New conditions with custom attributes might need more time, the ballpark estimate would be 1.5 days efforts for the conditions part.

We can create 2 separate issues one for events and actions and the other for conditions then it would be easy to move ahead.
So we can fix 1st on priority and pick up the next one if we have the time.

**Comment by fayazara** [comment]
For frontend, it should take around 2 days for adding them. (+ 0.5 buffer)

> Conditions can build based on whether they are applied to a conversation or a contact.

I mean the conditions are related to the event type - Here's the [model](https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/dashboard/routes/dashboard/settings/automation/constants.js), for contacts, I will use the same `Filters`  we used in the Contacts filter, so I will need this for labels.

**Comment by fayazara** [comment]
Do we have an api which returns all the conversations at once? This is for `Mute conversation` and `Snooze/Resolve conversation` action. Need this to show the conversation list in a dropdown.

@tejaswinichile @pranavrajs

**Comment by pranavrajs** [comment]
@fayazara Why do you need the list of conversations?

Mute conversation or Snooze/resolve doesn't take any arguments.

**Comment by fayazara** [comment]
Oh understood, got it mixed with somehting else.

**Comment by voko3456** [comment]
#3995

**Comment by voko3456** [comment]
I hope you can add
 1-send attachment as action and
 2-update custom attributes as action and 
3-send message as action

**Comment by tejaswinichile** [comment]
@pranavrajs 

One doubt, We should check above mentioned conditions only for contact-related events, right?

**Comment by pranavrajs** [comment]
@fayazara Please create a separate ticket for the frontend changes.

**Comment by fayazara** [comment]
> @fayazara Please create a separate ticket for the frontend changes.

https://github.com/chatwoot/chatwoot/issues/4051
