### ISSUE TITLE
[Help] Linking Twitter has an authorization loop

### ISSUE THREAD

**Issue by Austinstevesk** [chatwoot/chatwoot#3953]
Hello, I am trying to link twitter using the self-hosted method on a linux server. I have already set the parameters required by the .env file and created a twitter app. My callback url is as of this format [https://mydomainurltochatwoot/twitter/callback](url) and I already have the frontend_url set on my .env as [https://mydomainurltochatwoot](url).

Just after creating the inbox, a pop up appears for me to authorize the application and I do so. Then it redirects to the same page instead of getting ahead to where I can add agents. 
What can be issue?

Attached is a screenshot showing the logs: Nothing yet, authorization is complete.

![Screenshot from 2022-02-09 22-21-05](https://user-images.githubusercontent.com/45067454/153274743-1164a95b-94ff-4ce2-9b77-e4398238cb9a.png)

**Comment by Austinstevesk** [comment]
Sorted this out; the development environment is key, that's the main problem, Head to products > Development environment and link you app; use the value provided as the name as the label for environment in .env

**Comment by sojan-official** [comment]
@Austinstevesk  Thanks for reporting back.
