### ISSUE TITLE
Email sent from chatwoot has a very bare FROM header

### ISSUE THREAD

**Issue by robguthrie** [chatwoot/chatwoot#3954]
**Is your enhancement request related to a problem? Please describe.**

When someone receives an email from us, via chatwoot, it comes from "contact@loomio.org". This feels a bit unfriendly.

Emails arrive in customer inboxes look like this:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/486367/153270421-752fe393-4215-4b9e-b509-71e54ba43eab.png">

**Describe the solution you'd like**
We would like them to be friendlier and more informative about the agent.

Maybe like: "Rob Guthrie (Loomio) \<contact@loomio.org\>" or even just "Loomio Support \<contact@loomio.org\>"

**Additional context**
If you can give me a pointer about where to start looking at this problem, I can probably make it happen!

**Comment by iammattmartin** [comment]
Something that is possible via command line. Can't find the email where I had this.

Would be nice for it to be Inbox defined...

**Comment by robguthrie** [comment]
Yea, that would be neat.

**Comment by albabar** [comment]
What is your `MAILER_SENDER_EMAIL` env value set to?

**Comment by pranavrajs** [comment]
@robguthrie Just to understand the scenario better, please share the details below. 

1. Is this the email inbox or website live-chat continuity?
2. Are you using SMTP/IMAP config in the email inbox?

We are already sending the name as "Pranav from Chatwoot <p...@chatwoot.com>" in most cases except the case where you have used SMTP/IMAP to connect the email.

**Comment by robguthrie** [comment]
Yes this is SMTP/IMAP via the web interface. IE: Both IMAP and SMTP boxes are ticked and configured.

The benefit of this is we can easily keep all our email correspondence in the gmail account, which has been useful when we've been migrating between support tools... (IE: from Zammad to Chatwoot). 

I guess.. we could have the same setup with the config via ENV's but, the UI kinda told me this was the way to go.

Thanks for your help!

**Comment by sojan-official** [comment]
closing in favour of https://github.com/chatwoot/chatwoot/issues/4315 so we can track all requests in one issue.
