### ISSUE TITLE
Use Command + Enter to send the message instead of Enter key

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#3972]
> Hi, when replying to a ticket, to create a new line you have to press Shift + Enter. Is it possible to reverse this, I would prefer the shortcut to be shift + enter to trigger the sending the message. It's more common to use just Enter to create a new line, so I am forever sending half my message when composing.

**Comment by ChrisvanChip** [comment]
I'd rather like to see a toggle instead of just changing the keybinds. I'm really used to Shift + Enter for new lines, due to other helpdesk software.

**Comment by hendrikrust** [comment]
I agree with @pranavrajs. Non-technical support users who are not used to keyboard shortcuts will press ENTER for a new line and will end-up sending many one-liner responses.

**Comment by pranavrajs** [comment]
Thanks for providing the feedback @hendrikrust @ChrisvanChip. We are also evaluating what is the best of both worlds. 

A toggle can be done which seems like the easiest option, but I'm uncertain about the visibility of the toggle to most of the users (I mean I couldn't still picture where and how someone would find this option).

**Comment by johanndrews** [comment]
Thinking of the mail channel, you send more likely longer text, instead of short replys.

**Comment by sebypelaez** [comment]
Why don't we keep it consistent with the private notes like below:
<img width="474" alt="Screen Shot 2022-03-11 at 12 13 14 PM" src="https://user-images.githubusercontent.com/87689902/157800828-7b7c7ee8-10af-44c6-88aa-a3899fcfa6b4.png">

**Comment by pranavrajs** [comment]
- [ ] Research about the popup plugin
- [ ] Fix the UI in the profile
- [ ] Check if the private note is following the same pattern
- [ ] Use the same settings for normal editor as well.

**Comment by jimmybrancaccio** [comment]
Just tossing in my 'I hit Enter instead of Enter + Shift' for a new line and it sent an email to the end-user 😝. I too would love to see a toggle for this so one could pick between hitting Enter or Enter + Shift for a new line.

**Comment by jordan-brough** [comment]
We've had the same issue with accidentally sending messages because of confusion around this setting.

For us, the most important aspect is having "enter to send" stay synchronized between Messages and Private Notes (_independent_ of whether the rich text editor is enabled).

Personally I feel like I've seen `command+enter` (macOS) / `control+enter` (Windows/Linux) as the default shortcut most often. Including here on github and in gmail.
