### ISSUE TITLE
chore: Webhook Url shouldn't be mandatory for API inbox

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3979]
In the case of API Channels, if a user is consuming events via WebSockets / API fetch, a webhook URL isn't a requirement. 
So we should make the field optional during inbox creation. 

## Changes required
- [ ] remove requirement of webhook URL for API inboxes
- [ ] Change code so the webhook events are fired only for API inboxes where webhook URL is configured

**Comment by pranavrajs** [comment]
@sojan-official The WebHook URL is not a mandatory field in the API inbox. Can you please recheck if this is still an issue?
