### ISSUE TITLE
Instagram Story mention not show on inbox

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#3981]
I've already set self-hosted server for Chatwoot and successfully integrating with Instagram (Messenger) according  according this [guide](https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup). After that i decided to submit Subscription on Facebook Developer page so my chatwoot can production-ready to serve our customer. Facebook have terms & condition to approve my requested Subscription.

As mention on that above, I must obtain the **_instagram_manage_messages_** & _**instagram_basic subscribtion**_ to go production-ready. To obtain that subscription I must implement :
1. Agent Handoff (already set with Dialogflow, although my apps flow desnt require bot agent and only serve customer with live agent)
2. Manage chat that come from Instagram Mention Story (this what i need to confirm)
Please refer this Facebook Guide for Production ready Instagram channel at [this link](https://developers.facebook.com/docs/messenger-platform/instagram/app-review)

At this time, are Chatwoot doesn't support mesages that came from IG mention story? if support please tell me how set up it
Thank you

**Comment by sojan-official** [comment]
@aldhielman  We don't support Instagram story mentions at the moment.  it will be available in future releases.

**Comment by aldhielman** [comment]
maybe i can add those functionality manually with webhook or someting like that ?

**Comment by sojan-official** [comment]
@aldhielman it will require a bit of work to get it working.  
ref: https://github.com/chatwoot/chatwoot/issues/2096

**Comment by sojan-official** [comment]
fixed by https://github.com/chatwoot/chatwoot/pull/4100
