### ISSUE TITLE
Adding Agent to One Inbox adds that Agent to all Inboxes

### ISSUE THREAD

**Issue by pzupan** [chatwoot/chatwoot#399]
**Describe the bug**
When you add an agent to one inbox, it adds that agent to all inboxes.

**To Reproduce**
1. Add two inboxes on the dashboard.  
2. Add a new Agent.  
3. Add that new agent to the last inbox.  

**Expected behavior**
The Agent should only be associated with the last inbox.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 79.0

**Comment by pranavrajs** [comment]
@pzupan Thanks for reporting this. I looks like it is an issue with the views getting cached in frontend. 
If you refresh the page, the list of agents would be correct. The agents are not added to other inboxes as described. We will have a fix for that soon. Meanwhile, you could refresh the settings page to see the correct list of agents who have access to the inbox.

**Comment by pzupan** [comment]
Thanks @pranavrajs.  I'll see if I can shake free some time to assist with this project.  I like what you're doing....
