### ISSUE TITLE
feat: Ability for dialogflow integration to start a conversation 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#3993]
> How can I set up dialogflow to initiate the conversation before user types a message? 

ref: https://discord.com/channels/647412545203994635/848225049059917834/941607941516177419

**Comment by ChrisvanChip** [comment]
Could be merged with #2993.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/2993
