### ISSUE TITLE
[CW-2004] feat: Ability to Block/Blacklist Contacts

### ISSUE THREAD

**Issue by sagararyal** [chatwoot/chatwoot#3996]
**Is your feature request related to a problem? Please describe.**
By default, all spam and marketing messages reach support desk.  In some cases this can be solved by deleting the contact. Other solution is to mark the issue as Resolved. If CSAT is enabled, this sends the email to the spammers, further encouraging for more spam content. 

**Describe the solution you'd like**
A Blacklist button next to Delete button on the side panel of the conversation. (above conservation actions)

By Blacklisting a contact, all new emails arriving from the user will skip unassigned queue, or even get deleted immediately.
No emails should be sent to that email, either through autoresponder, CSAT or response.

It should still be possible to view Blacklisted contacts by visiting /contacts and filtering by Blacklisted contacts.
  

<sub>[CW-2004](https://linear.app/chatwoot/issue/CW-2004/feat-ability-to-blockblacklist-contacts)</sub>

**Comment by pranavrajs** [comment]
- How do you ensure that there is visibility on mute on contacts? Accidental blocks

**Comment by JNajera** [comment]
Looking to the Freshdesk UI can be hidden and if you need to mark as "SPAM" the conversation, it should be possible.   

![Screenshot_3_29_22__9_33_AM](https://user-images.githubusercontent.com/616661/160649382-547f0861-fe91-49bc-a344-78d675016584.png)


Also, a nice feature to have after mark as SPAM a conversation, is to ask is the contact should be mark as SPAM. 

![Helpdesk___Actiun](https://user-images.githubusercontent.com/616661/160649825-5bacee00-ec9c-4a2f-9567-bdf58c0fbf9f.png)

**Comment by calebjacobson** [comment]
We have also noticed spam messages in our SMS channels (we have 42 of them). Being able to blacklist certain numbers would be beneficial. We use Twilio to manage SMS communications, and they do not allow us to blacklist numbers there, leaving it up to the client to manage that.

**Comment by sojan-official** [comment]
## Proposal  v1

### Acceptance 

- Ability to blacklist or block a contact 
- Conversations from blocked contacts shouldn't be visible in queues ( muting conversations will prevent this )
- Ability to view blacklisted contacts ( the contacts will still be visible in the CRM module )
- Ability to view conversations from blacklisted contacts ( conversations will be visible in the resolved queue / in previous conversations section of the blocked contacts )

### Change log

- [ ]  Add blocked attribute to contact with default value false
- [ ]  Ability to change the value of the attribute from UI
- [ ]  Mute all incoming conversations from the Contact automatically
- [ ]  Ability to filter blocked contacts. ( optional )

**Comment by ezequiel-moura** [comment]
Nothing about this feature?

**Comment by kesylo** [comment]
Any news ?

**Comment by masterking32** [comment]
Bump ...
