### ISSUE TITLE
Docker support for development and deployment

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#40]
- [ ] Create Docker images 
- [ ] Use docker compose for development

**Comment by MatheusRich** [comment]
@pranavrajs Can I tackle this one?

**Comment by pranavrajs** [comment]
@MatheusRich Please feel free to do it. I'm assigning this one to you.

**Comment by kkv98** [comment]
@MatheusRich Can I join with you?.I am going to start learning docker.

**Comment by MatheusRich** [comment]
@kkv98 You can take if you want to. 😄 I'll comment anything on your PR if I find something that could be improved.

**Comment by gerroon** [comment]
Is there a working Docker container for this?

**Comment by pranavrajs** [comment]
@gerroon No, we don't have it. You need to follow the instructions provided at chatwoot.com/docs for the project setup.

**Comment by gerroon** [comment]
@pranavrajs 

This is for deployment not for development, I am pretty sure that the docker question will come up frequently. In any case please update this issue once you guys find time to make an official Docker container.

**Comment by hsyntnc** [comment]
@MatheusRich if you're not working on it yet i'm planning to dockerize it tonight.
Can you please share current status?

**Comment by sojan-official** [comment]
@hsyntnc I don't think anyone is actively working on this. feel free to pick this up if you have time. 
Lets us know if you need any help.

**Comment by ptman** [comment]
How does #222 look?

**Comment by aadrian** [comment]
@ptman It looks great. Thank you for the quick solution!

**Comment by hsyntnc** [comment]
@ptman it looks great man. I've been working all day and got some time for it now but i guess i'm a bit late. 
wp.

**Comment by ptman** [comment]
@hsyntnc sorry, I didn't mean to steal it from you, but I wanted to try chatwoot myself

besides, it still need improvement, any ideas?

**Comment by aadrian** [comment]
> besides, it still needs improvement, any ideas?

A docker-compose file for a demo, to include the client (site) integration part too?

**Comment by ptman** [comment]
can you point me to documentation regarding that?

**Comment by sojan-official** [comment]
@ptman  thanks a lot for working on this.  I have added some review comments. will be happy to collaborate over the PR if you need help.  

My understanding of docker is a little limited.  So @hsyntnc  @MatheusRich  if you could have a look. that be super helpful.

**Comment by sony-mathew** [comment]
Hey guys, do you mind if I contribute to this.?

**Comment by aadrian** [comment]
@ptman unfortunately there doesn't seems to be any documentation regarding integration. 

As a matter of fact, the documentation seems to be quite "slim", and this is something the community can't really create, since we all need the documentation in first place to be able to further help :) .

**Comment by sojan-official** [comment]
@aadrian we didn't see the repo taking off suddenly. Hence there are some rough edges. At the moment we are working to improve the dev/product documentation and deployment instructions.  

We are openly listening to any feedback on this. Please feel free to reach out with any issues.  / ideas on improving this.

**Comment by sojan-official** [comment]
Hey guys, we just merged https://github.com/chatwoot/chatwoot/pull/270 

which covers the shortcomings that came up in various discussions. 
- remove the extra steps to set up the software
- docker for production and development 
- update the documentation all over. 

Let us know if you guys require anything in addition. Thanks a lot for the effort spent over this as well.  

@gerroon  @aadrian
