### ISSUE TITLE
[CW-2375] Add image in email signature for branding purpose

### ISSUE THREAD

**Issue by Soundmagic** [chatwoot/chatwoot#4001]
Since 2.2.0 mail signatures per profil can be define. Thats fine, but we need to add an image/logo for branding purpose as part of the mail signature.

As of now no image can be added to the signature in user profil.

<sub>[CW-2375](https://linear.app/chatwoot/issue/CW-2375/add-image-in-email-signature-for-branding-purpose)</sub>

**Comment by pranavrajs** [comment]
@nithindavid This might be a good place to see if we can split the signatures into plain text and HTML/rich content signature. Let us use Rich content on website live-chat and email, and plain text on rest of the channels.

**Comment by ErminMerdanovic** [comment]
Hello, will the raw HTML feature be implemented for the signature?
