### ISSUE TITLE
"No content available" for e-mail messages without body

### ISSUE THREAD

**Issue by jonas-hoebenreich** [chatwoot/chatwoot#4020]
**Describe the bug**
If a user sends an email to an inbox monitored by chatwoot, but only puts his question in the subject, with an empty message body, the email will not be processed properly. Instead, an empty chat history appears, in which it is not possible to read the message.

**To Reproduce**
Send a blank email to Chatwoot and only specify the subject line

**Expected behavior**
The message is displayed, you can see what the subject says

**Screenshots**
current behavior:
![image](https://user-images.githubusercontent.com/64426524/154800680-7af137d7-13c4-4138-b415-3d2b40e03600.jpg)

Expected behavior
![screenshot 2022-02-19 13-24-03](https://user-images.githubusercontent.com/64426524/154800690-1e671557-e734-4986-9cb9-9f6c7426ee57.png)

**Environment**
self hosted installation

**Comment by Ajay-joshi-mtr** [comment]
Hi @jonas-hoebenreich  As you mentioned specifically for empty message body this errors occurs, I would like to add that we are already facing the same issue along with the message body. So, I think this issue is in email inbox channel. Please get it resolved asap.

**Comment by sagararyal** [comment]
+1 @Ajay-joshi-mtr . 

I think this should be P1 issue. Affecting many messages with non empty body on email channel.
