### ISSUE TITLE
Display trends in the metrics

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4040]
### Context

Right now, Chatwoot supports the following metrics

- Total number of Conversations
- Total number of incoming messages
- Total number of outgoing messages
- Average resolution time
- Average first response time
- Resolution count

These are absolute metrics for that particular time period, it doesn't show what has changed from the previous time period.

An example can be seen here.
<img width="193" alt="Screenshot 2022-02-22 at 3 22 55 PM" src="https://user-images.githubusercontent.com/2246121/155107468-344e9672-2cbc-4fe2-998d-d69b35bdb81e.png">

#### API Changes
- [ ] Calculate the previous time period value along with the current time period value and return it in the summary API.

Now, the summary API returns the details as follows

```
{
  "conversations_count":133,
  "incoming_messages_count":370,
  "outgoing_messages_count":354,
  "avg_first_response_time":"4770.18802719496469575",
  "avg_resolution_time":"620946.011525262025",
  "resolutions_count":53
}
```

Change it to the following format.

```
{
  "current": {
    "conversations_count":10,
    "incoming_messages_count":20,
    "outgoing_messages_count":30,
    "avg_first_response_time":"20",
    "avg_resolution_time":"40",
    "resolutions_count":10
  },
  "previous: {
     "conversations_count":12,
     "incoming_messages_count":20,
     "outgoing_messages_count":30,
     "avg_first_response_time":"20",
     "avg_resolution_time":"40",
     "resolutions_count":10
  },
  "trends": {
     "conversation_count: 20,
     "incoming_messages_count":20,
     "outgoing_messages_count":30,
     "avg_first_response_time":"20",
     "avg_resolution_time":"40",
     "resolutions_count":10
  }
}
```

Trends should be returned in percentage values. The calculation is shown as follows 
```
change_in_value_as_percent = (current_value - prev_value)/pre_value * 100
```

#### Changes in the UI

<img width="209" alt="Screenshot 2022-02-22 at 3 27 39 PM" src="https://user-images.githubusercontent.com/2246121/155108321-a183b2f1-8c51-423d-b30b-89eb6e82df67.png">

Note: Show only 1 decimal place in the UI, use rounded logic.

**Comment by aswindevps** [comment]
@sojan-official We would return the summary response as below. 
{
  "current": {
    "conversations_count":10,
    "incoming_messages_count":20,
    "outgoing_messages_count":30,
    "avg_first_response_time":"20",
    "avg_resolution_time":"40",
    "resolutions_count":10
  },
  "previous: {
     "conversations_count":12,
     "incoming_messages_count":20,
     "outgoing_messages_count":30,
     "avg_first_response_time":"20",
     "avg_resolution_time":"40",
     "resolutions_count":10
  }
}
and calculate the trends in the frontend.

@pranavrajs do we need to store both current and previous summary in the frontend vuex store? This need bit of refactoring.

**Comment by pranavrajs** [comment]
@aswindevps Saving the values would be required. It would be good to show the previous value on hover.
