### ISSUE TITLE
Update chart values to use hr, minutes notation instead of hours

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4042]
We are displaying time in hours in reports. Instead of showing 3 minutes, we are displaying it as 0.05Hr. Change this to minutes/hours representation by the following logic.

If the value is < 60 - show the same value as seconds
If the value is > 60, less than 3600 - show the (value/60) as minutes
If the value is > 3600 - show (value / 3600) as hours and (value % 3600) as minutes
If the value is > 86400 - show (value / 86400) as days and (value % 86400) as hr

| New | Previous |
| -- | -- |
|  <img width="216" alt="Screenshot 2022-02-22 at 4 13 36 PM" src="https://user-images.githubusercontent.com/2246121/155116700-a1a880f1-734d-457f-943c-05d4c8fd5d42.png"> | <img width="204" alt="Screenshot 2022-02-22 at 4 13 46 PM" src="https://user-images.githubusercontent.com/2246121/155116754-3ad53776-9cbf-42cd-afb4-7009a5af8293.png"> |

#### Investigation
- [ ] Check if lodash has similar function to achieve this logic.

**Comment by aswindevps** [comment]
@pranavrajs Couldn't find lodash function to achieve this logic. So proceeding with custom logic.

**Comment by pranavrajs** [comment]
@aswindevps Sure, can you please try adding it in [@chatwoot/utils](https://github.com/chatwoot/utils)

**Comment by aswindevps** [comment]
@pranavrajs Checks are failing for below PR. How can we fix that?

https://github.com/chatwoot/utils/pull/11

**Comment by pranavrajs** [comment]
@aswindevps I have fixed the PR issues, please make sure you run `yarn lint` next time.

**Comment by aswindevps** [comment]
@pranavrajs Sure. 

Can we update the [README.md](https://github.com/chatwoot/utils#readme) for the same?

**Comment by pranavrajs** [comment]
Sure, please go ahead.
