### ISSUE TITLE
[CW-2210] Followup Response Time

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4043]
For all outgoing messages, create an event with the name 'followup_response_time' if the previous message (except template, activity) is an incoming message.

Exception: If there are are multiple incoming messages without an outgoing message, select the first one for computation.

Compute the average value of followup_response_time.

<sub>[CW-2210](https://linear.app/chatwoot/issue/CW-2210/followup-response-time)</sub>

**Comment by ammaraslam** [comment]
@pranavrajs I'm also looking for this, average response time of an agent on weekly/monthly or on custom dates. 

Would be great if it's incorporated.

**Comment by migarol** [comment]
Hey, i have a website widget with Dialogflow connected, when i go to agents Overview and check on First Response Time, it says 0 for every agent, why is this not working?

It should start working when the handoff event is triggered from dialogflow, correct ?
