### ISSUE TITLE
Notification view update

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4052]
- Create a widget for notifications in the sidebar.

### Acceptance:

- [ ] When you click on the bell icon, instead of navigating to a new route you would see a popup that shows unread messages.
- [ ] The popup should only show unread messages
- [ ] There should a button to "Mark read"
- [ ] At the end of the list, there should be a button to view previous notifications. Clicking on the button would redirect to the notifications page.

**Comment by iamsivin** [comment]
1. Good to show the name instead of id in the title.
2. Already we are showing the message type as an option but the message also it is showing the notification type.
3. Good to show the name instead of id in the message.
