### ISSUE TITLE
Add automation action send attachment 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4054]
Add automation action send attachment

**Comment by tejaswinichile** [comment]
The step to consider:

1. Add automation actions "Send attachment" to the automation rule
2. File will be attached to the automation rule via the automation page/API.
3. When an Automation event has been triggered call send_attachment action.
4. Send attachment will create a message with the attached file in the automation rule and send it in the conversation.

Basically, it will act similar to send_message with the attachment.

@pranavrajs This flow seems valid?

**Comment by pranavrajs** [comment]
@tejaswinichile Sounds good.
