### ISSUE TITLE
Add Sender Name in email channel when IMAP/SMTP is enabled

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#4056]
Currently, messages sent using email channels with IMAP/SMTP enabled  only have the email address in their header. They don't have sender name.
So instead of being sent from John Doe <johndoes@domain.com>, emails are currently sent from johndoes@domain.com.

I think it would be very important to have a new field like "Sender name" in the channel configuration.

**Comment by sojan-official** [comment]
@jean-philippeansel  Thanks for reporting, we will take this up for upcoming sprints. 
cc: @pranavrajs

**Comment by sojan-official** [comment]
closing in favour of https://github.com/chatwoot/chatwoot/issues/4315 so we can track all requests in one issue.
