### ISSUE TITLE
Delete contact without having to type name

### ISSUE THREAD

**Issue by Christilut** [chatwoot/chatwoot#4067]
**Is your feature request related to a problem? Please describe.**
Spam users come in through chat or Facebook chat and enter Chatwoot. I want to delete these so I delete the contact by clicking the button. Then a popup shows to ask if I'm sure. Then I have to type the name to confirm. I never type it, but I copy paste instead.

**Describe the solution you'd like**
There is already a confirm popup, that should be enough. I don't see a reason to add the annoying name type extra step.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot-mobile-app/issues/476

**Comment by pranavrajs** [comment]
@Christilut This is an irreversible action, so having a check is important as it deletes the entire data. I guess your issue would be solved if you could select the multiple accounts and delete instead of deleting one user.

**Comment by Christilut** [comment]
Yeah but that is what the confirm popup is for.
The name typing is just a popular anti pattern these days. A big red warning popup should already give pause to a user for a moment and obviously it should say with big letters "Are you sure you want to delete **contact x**?". But having to type it after that is just frustrating.

**Comment by sojan-official** [comment]
@Christilut Makes sense. We will remove the requirement to type the names in these boxes. 

cc: @iamsivin

**Comment by Christilut** [comment]
Awesome, thanks for listening! :)
