### ISSUE TITLE
Bug when uploading images in conversations: image not showing

### ISSUE THREAD

**Issue by vinch** [chatwoot/chatwoot#4084]
**Describe the bug**

When uploading an image in a conversation, the image doesn't show, it shows a broken image. After reloading the conversation (Cmd+R in the browser), it works fine. The problem happens with the admin and with the client as well (integration in the website).

We noticed that it seems to be working sometimes with smaller images (<50KB) but definitely fails all the time with bigger images (>100KB).

We use an S3 bucket for storage (described here: https://www.chatwoot.com/docs/self-hosted/deployment/storage/s3-bucket).

**To Reproduce**

1. Go to a conversation
2. Upload an image
3. Click on the send button
4. See the broken image in the conversation

**Expected behavior**

We should see the image in the conversation.

**Screenshots**

![Screenshot 2022-02-28 at 18 33 03](https://user-images.githubusercontent.com/155370/156030574-50a1ae7a-6afd-4180-9713-b1178ca552bc.png)

![Screenshot 2022-02-28 at 18 44 48](https://user-images.githubusercontent.com/155370/156032230-fb436775-596c-47c6-b63f-27674f5fd079.png)

**Browser logs**

The browser logs show a 404 for the admin.

![Screenshot 2022-02-28 at 18 34 18](https://user-images.githubusercontent.com/155370/156031012-8500514a-e352-4e79-84cc-9b17195d6568.png)

For the client, it shows a 500.

![Screenshot 2022-02-28 at 18 42 37](https://user-images.githubusercontent.com/155370/156032108-375b576d-40f8-45e0-b608-1c8ab16799a7.png)

**Environment**

We use a self-hosted installation on Heroku, and S3 for storage as I already explained earlier.

**Desktop**
 - OS: macOS
 - Browser: Chrome
 - Version: 98.0.4758.80

**Comment by sojan-official** [comment]
@vinch  could you specify the chatwoot version you are using? 
ref: https://github.com/chatwoot/chatwoot/issues/1372

**Comment by pranavrajs** [comment]
@vinch Closing this as this is not reproducible in the latest releases. Let us know if you find any further issues on this.

**Comment by vinch** [comment]
@pranavrajs Sure, thanks! It's fixed after upgrading to v2.
