### ISSUE TITLE
Add gmail like label marker in the conversation card

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#4085]
**Is your enhancement request related to a problem? Please describe.**
When we add labels to the conversation it won't show till we open details or apply the filter to the conversations.

**Describe the solution you'd like**
I want to see all the priority conversations at a glance and if we receive any new message from the particular customer or under the particular label. Similar to how Gmail shows us.
<img width="300" alt="gmail_labels" src="https://user-images.githubusercontent.com/10827585/156109755-923bb01a-0b73-4560-8326-45c2fe891226.png">

**Describe alternatives you've considered**
There should be a way to show labels on the conversation cards.

**Addition
<img width="300" alt="gmail_labels" src="https://user-images.githubusercontent.com/10827585/156109838-44182219-75dc-4192-8171-d5aa076f8372.png">
al context**

**Comment by pranavrajs** [comment]
@nithindavid Please add an estimate to the ticket before you pick this up in the next sprint.
