### ISSUE TITLE
bug: Impossible to sign in to the super admin dashboard

### ISSUE THREAD

**Issue by ChrisvanChip** [chatwoot/chatwoot#4088]
**Describe the bug**

When trying to sign in to the `/super_admin` panel, the page just refreshes without error message. I am not logged in either.

**To Reproduce**

1. Go to `<domain>/super_admin/sign_in`.
2. Try to log in with super admin credentials.
3. The log-in page refreshes without logging in, and no message shows up.

**Expected behavior**

Just like with `v2.1.1`, I should be logged in properly and have access to the super admin dashboard.

**Browser logs**

N/A

**Server logs**

`journalctl -u chatwoot-web.1.service -f`:
```
Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.485286 #687]  INFO -- : [798fa9f4-fa1f-4b6e-a7bc-0fc628f31c7a] Started POST "/super_admin/sign_in" for <IP_REDACTED> at 2022-03-01 07:54:19 +0000          

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.487257 #687]  INFO -- : [798fa9f4-fa1f-4b6e-a7bc-0fc628f31c7a] Processing by SuperAdmin::Devise::SessionsController#create as HTML                      

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.487340 #687]  INFO -- : [798fa9f4-fa1f-4b6e-a7bc-0fc628f31c7a]   Parameters: {"authenticity_token"=>"[FILTERED]", "super_admin"=>{"email"=>"<EMAIL_REDACTED>", "password"=>"[FILTERED]", "remember_me"=>"0"}}                       

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.623514 #687]  INFO -- : [798fa9f4-fa1f-4b6e-a7bc-0fc628f31c7a] Completed 401 Unauthorized in 136ms (ActiveRecord: 0.6ms | Allocations: 1923)            

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.626641 #687]  INFO -- : source=rack-timeout id=798fa9f4-fa1f-4b6e-a7bc-0fc628f31c7a timeout=15000ms service=142ms state=completed                       

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.810492 #687]  INFO -- : source=rack-timeout id=0d7b99bb-2899-4e27-8298-c6cde017936e timeout=15000ms state=ready                                         

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.811290 #687]  INFO -- : [0d7b99bb-2899-4e27-8298-c6cde017936e] Started GET "/super_admin/sign_in" for <IP_REDACTED> at 2022-03-01 07:54:19 +0000           

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.813473 #687]  INFO -- : [0d7b99bb-2899-4e27-8298-c6cde017936e] Processing by SuperAdmin::Devise::SessionsController#new as HTML                         

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.817488 #687]  INFO -- : [0d7b99bb-2899-4e27-8298-c6cde017936e]   Rendered super_admin/devise/sessions/new.html.erb (Duration: 1.2ms | Allocations: 427) 

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.817780 #687]  INFO -- : [0d7b99bb-2899-4e27-8298-c6cde017936e] Completed 200 OK in 4ms (Views: 2.2ms | ActiveRecord: 0.0ms | Allocations: 1966)         

Mar 01 07:54:19 <HOSTNAME_REDACTED> chatwoot-web.1[687]: I, [2022-03-01T07:54:19.818453 #687]  INFO -- : source=rack-timeout id=0d7b99bb-2899-4e27-8298-c6cde017936e timeout=15000ms service=8ms state=completed
```

**Environment**

Linux VM - release `v2.2.1`
• 4 GB RAM
• 2 GB SWAP
• 4 vCPU cores
• 100 GB SSD

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A52
 - OS: Android 12
 - Browser: Chrome
 - Version: 98.0.4758.101

**Additional context**

It worked in `v2.1.1`.

**Comment by sojan-official** [comment]
@ChrisvanChip with v2.2 we have unified the credentials of the agent dashboard as well as super admin accounts. So if you use the same email for the super admin and agent dashboard.  You can authenticate to super admin using your agent dashboard credentials. 

- [ ] Clear the browser session and give it a try with the dashboard credentials 
- [ ] Ensure that database migrations were run

**Comment by ChrisvanChip** [comment]
^ Apologies, misclicked it.

@sojan-official I can't log in with my admin credentials into the super admin dashboard. Is there any command I have to execute to run database migrations or suchlike?

I have initially installed Chatwoot on `v2.1.1` and upgraded using the recommended commands since then.

**Comment by sojan-official** [comment]
@ChrisvanChip could you open up a rails console and see if there are results for 
```
SuperAdmin.all
```

**Comment by ChrisvanChip** [comment]
> @ChrisvanChip could you open up a rails console and see if there are results for
> 
> ```
> SuperAdmin.all
> ```

It has returned 3 superadmins I had created recently, with IDs 7-9.

**Comment by sojan-official** [comment]
@ChrisvanChip  Could you try logging in from an incognito window?

**Comment by ChrisvanChip** [comment]
@sojan-official Logging in from an incognito tab doesn't resolve the issue: it still refreshes without error message when attempting a sign in.

I can eventually try an office computer that has never accessed Chatwoot?

**Comment by sojan-official** [comment]
@ChrisvanChip It would also be helpful if you could check logs and see what happens when the `signin` request is made to the server.

**Comment by ChrisvanChip** [comment]
The `chatwoot-web.1.service` logs are the same as above (first description). I'll record the `chatwoot-worker.1.service` now.

**Comment by ChrisvanChip** [comment]
@sojan-official Here are the logs of `journalctl -u chatwoot-worker.1.service -f` during sign in:

```
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.    
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: redis.pipelined do                                                                           
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]:   redis.get("key")                                                                           
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: end          
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: should be replaced by                                                                        
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: redis.pipelined do |pipeline|                                                                
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]:   pipeline.get("key")                                                                        
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: end          
Mar 01 11:22:15 <HOSTNAME_REDACTED> chatwoot-worker.1[684]: (called from /usr/local/rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:206:in `block in all'}
```

Above section is repeated a few times in the log history.

**Comment by ChrisvanChip** [comment]
@sojan-official That returns a `Validation failed: Password must contain at least 1 number character  (0..9), Password must contain at least 1 special character  (!@#$%^&*()_+-=[]{}|'"/ ^.,`<>:;?~)`.

I'll try with "NewPassword!1".

**Comment by ChrisvanChip** [comment]
@sojan-official That worked 🥳

Thanks for your help!

**Comment by Automated-Ninja** [comment]
I have also encountered this bug running Chatwoot 2.4.0. Everything is exactly as ChrisvanChip described it - I can create SuperAdmins with no issue in the ruby console, however, I am unable to log in via <my.domain>/super_admin, the page simply refreshes with no error or message.

Environment
Digital Ocean VM running Ubuntu 20.04 (LTS) x64 - Chatwoot version 2.4.0
- 4vCPU
- 8 GB memory
- 160 GB Storage

Like ChrisvanChip, running `journalctl -u chatwoot-worker.1.service -f` returns the following: 
`Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: redis.pipelined do
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]:   redis.get("key")
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: end
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: should be replaced by
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: redis.pipelined do |pipeline|
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]:   pipeline.get("key")
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: end
Apr 19 00:27:31 RHC-Chatwoot--ubuntu-s-4vcpu-8gb-sfo3-01 chatwoot-worker.1[37024]: (called from /usr/local/rvm/gems/ruby-3.0.2/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:206:in `block in all'}`

I have tried @sojan-official suggestion of updating the SuperAdmin's permissions `# replace with your email 
admin = User.where(email: 'john@acme.inc', type: 'SuperAdmin').first
# change new password accordingly
admin.password = "NewPassword"
`admin.save!` 
However, this has not resolved the issue.

I have tried multiple browsers and computers with the same result. Migrating the database has not helped. I have even completely reset and rebuilt the VM and did a fresh install of Chatwoot - the issue still persists. Any ideas or suggestions would be greatly appreciated.

Thanks!
