### ISSUE TITLE
If e-mail contains + sign, search is not working on Contacts page.

### ISSUE THREAD

**Issue by omercan** [chatwoot/chatwoot#4089]
**Describe the bug**

I am creating the contacts with + sign. For example, omercan+ikas@gmail.com is one of our contact's mail. After that, when I wrote omercan+ikas@gmail.com to the search bar no result comes.

When I check the search API call on the dashboard, query goes like that: 

omercan ikas@gmail.com

![Screen Shot 2022-03-01 at 15 16 13](https://user-images.githubusercontent.com/3155992/156167563-df188ada-c949-4b4e-bd0e-98187c44ed75.png)

**Comment by pranavrajs** [comment]
@omercan This seems like a bug during the initial investigation. @iamsivin The frontend is removing `+` sign while sending the query. Can you please take a look?

**Comment by iamsivin** [comment]
> @omercan This seems like a bug during the initial investigation. @iamsivin The frontend is removing the `+` sign while sending the query. Can you please take a look?

Done 👍🏻
