### ISSUE TITLE
chore: Fix redis deprecation warning from sidekiq cron

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4090]
Since the gem isn't actively maintained we might need to create a fork / use a community fork
```
   | (called from /Users/Sojan/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-cron-1.2.0/lib/sidekiq/cron/job.rb:206:in `block in all'}
worker   | Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
worker   |
worker   | redis.pipelined do
worker   |   redis.get("key")
worker   | end
worker   |
worker   | should be replaced by
worker   |
worker   | redis.pipelined do |pipeline|
worker   |   pipeline.get("key")
worker   | end
worker   | Pipelining commands on a Redis instance is deprecated and will be removed in Redis 5.0.0.
worker   |
worker   | redis.pipelined do
worker   |   redis.get("key")
worker   | end
worker   |
worker   | should be replaced by
worker   |
worker   | redis.pipelined do |pipeline|
worker   |   pipeline.get("key")
worker   | end
```

ref: https://github.com/ondrejbartas/sidekiq-cron/issues/310

**Comment by sojan-official** [comment]
explore moving to https://github.com/Moove-it/sidekiq-scheduler
ref: https://github.com/ondrejbartas/sidekiq-cron/issues/310#issuecomment-1068485657

**Comment by shivamsinghchahar** [comment]
@sojan-official Is this issue still relevant? Can I take this up?

**Comment by sojan-official** [comment]
@shivamsinghchahar yep.  I believe sidekiq-cron has this issue fixed in their main branch. let's switch to that and see if it resolves the warnings.

**Comment by shivamsinghchahar** [comment]
@sojan-official Just updated `sidekiq-cron` here: https://github.com/chatwoot/chatwoot/pull/4581 Looks like the warnings are gone.
