### ISSUE TITLE
character encoding of mails failed in the view 

### ISSUE THREAD

**Issue by jegade** [chatwoot/chatwoot#4094]
**Describe the bug**

We are using the mail channel with the relay, if we send some non-ascii-char like äüäß the ui shows only ??? instead.

**To Reproduce**

1. Send an email with utf8 characters which are non-ascii like äöüß  to a mail channel
2. The Chat will display the characters as ?

**Expected behavior**

The characters shoud display as send 

**Environment**

Self-Hosted, Docker-Dployment, chatwoot/chatwoot:v2.2.0

**Additional context**

We viewed at the storage (s3), there the files are properly encoded.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4381
