### ISSUE TITLE
Prevent conversation creation out of business hours

### ISSUE THREAD

**Issue by PyB1l** [chatwoot/chatwoot#4098]
Is there an easy way to prevent user (E.g, hide widget, hide message input ) in the scenario where user 
tries to chat out of business hours?

I can see that the correct message is displayed, but user can still send messages to this conversation.

**Comment by sojan-official** [comment]
@PyB1l  At the moment there isn't.

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/273
