### ISSUE TITLE
Support for Google Cloud Storage as storage for Chatwoot

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#41]
- [ ] Chatwoot supports only S3 as storage, allow users to configure GCS/S3/Azure Storage

**Comment by sojan-official** [comment]
once  #158 is done, this should be straightforward. we want to use active storage to handle this

**Comment by sojan-official** [comment]
ref : https://github.com/chatwoot/chatwoot/pull/393

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/393

**Comment by pranavrajs** [comment]
@sojan-official Please update the env variables in .env.example and the docs.

**Comment by pranavrajs** [comment]
Fixed via #439
