### ISSUE TITLE
Getting assets into S3 bucket?

### ISSUE THREAD

**Issue by darkpixel** [chatwoot/chatwoot#4105]
I'm not a rails guy, so I'm a bit stumped at the moment.
I'm playing around with ChatWoot on a DigitalOcean Kubernetes cluster at the moment.
I had the app deployed using local storage and everything was up and working.

Unfortunately since I had several replicas running and was using local storage, occasionally SMS images wouldn't display because they weren't on the filesystem of the pod that was serving my request.

I created a DigitalOcean Space (s3 compatible bucket) and got that part of the configuration working...but now it looks like ChatWoot is trying to serve all static assets from DigitalOcean Spaces...and I can't figure out how to get the assets uploaded.

I tried:
```RUBY_ENV=pruduction bundle exec rake assets:precompile``` and it appears to compile the assets, but it doesn't upload them.

When using Django apps (I'm more of a Python guy) you can run ```python manage.py collectstatic``` and it uploads the static assets to the CDN.  I'm not seeing anything in the documentation for performing that task using Rails/ChatWoot.  Am I missing something?

**Comment by darkpixel** [comment]
I should also mention that the storage appears to be configured properly.  If I send a picture via MMS, ChatWoot receives it and drops it into the bucket.  I just can't get static assets uploaded.

**Comment by pranavrajs** [comment]
@darkpixel I'm not sure if I understand the issue properly. Are the uploads in the widget/dashboard working properly?

**Comment by darkpixel** [comment]
There is a setting ```ASSET_CDN_HOST```.  It apparently doesn't have anything to do with ```ACTIVE_STORAGE``` (where things like MMS messages are stored) it just determines where to load static assets (like js and css files).

I don't see a way to "collect" the static files to put them on the CDN.

It seems sorta like the difference between ```STATIC_ROOT``` and ```MEDIA_ROOT``` in Django.  One is for static assets used by the application, and the other is for "user generated media" that gets uploaded.

Django has a ```collectstatic``` command that grabs all the assets and puts them into STATIC_ROOT (or pushes them to something like s3).

I'm not sure if there's a command for that in ruby/chatwoot.

**Comment by sojan-official** [comment]
@darkpixel  please refer: https://guides.rubyonrails.org/asset_pipeline.html#cdns 
the ASSET_CDN_HOST configuration is for having the static asset like js and  CSS be served from a CDN without the need of invoking the application server.  the CDN server will fetch the assets from the application server on the first request and from there on it will use the cached version. 

----

Now for the attachments, that's where active storage comes into play. for active storage, you can configure different storage other than local storage.  
https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

the older attachments will still remain in your old storage, only the newer ones be available in your new storage, so you might want to look into a way to migrate those files.  

also irrespective of the storage configuration, active storage will be hitting your rails end point first to get the original attachment URL from the underlying storage service.

**Comment by darkpixel** [comment]
Doing a bit more digging through the docs, it looks like my configuration is unsupported.

I'm using DigitalOcean Spaces for my CDN.

It expects you to 'push' (upload) the files to the CDN unlike the CloudFront example which appears to grab the assets on the first request.

No worries.  Thanks for the info.
