### ISSUE TITLE
Sort / Reorder Inboxes

### ISSUE THREAD

**Issue by racquetmaster** [chatwoot/chatwoot#4107]
**Is your feature request related to a problem? Please describe.**
We have 40+ inboxes (Different SMS phone numbers). It would be nice to be able to put them in a sensible order.

**Describe the solution you'd like**
I'd like for the list of inboxes to either be sorted by name or able to be manually ordered.

**Describe alternatives you've considered**
See above.

**Additional context**
NA

**Comment by iammattmartin** [comment]
Nice to add in #1127 too.

**Comment by sojan-official** [comment]
ref: #1098

**Comment by pranavrajs** [comment]
@fayazara Please check this out when you are available.

**Comment by pranavrajs** [comment]
As the first we would sort the inboxes based on the alphabetical order, the next iteration would have it sorted based on the number of open conversations.

**Comment by fayazara** [comment]
Should there be an option to sort? or is it sorted alphabetically by default?

**Comment by pranavrajs** [comment]
@fayazara Let us do a default alphabetical sort in the sidebar. If it is possible to add a sort option on the settings page, that would be good.
