### ISSUE TITLE
Error creating a superadmin account

### ISSUE THREAD

**Issue by lan894734188** [chatwoot/chatwoot#4109]
**Describe the bug**

Error for carete superadmin account

1.i read https://www.chatwoot.com/docs/self-hosted/monitoring/super-admin-sidekiq
2.installed chatwoot at k8s by helm install
3.pods all running
4.use clusterIP for chatwoot-web svc
5.Todo the step1
6.type in chatwoot-web pod console and errors
<img width="377" alt="image" src="https://user-images.githubusercontent.com/16399130/156707517-1347e7d0-f8f1-492f-8e32-4a2b99b16fe2.png">

**Expected behavior**

create a superadmin account

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)
self hosted ： Kubernetes ，install by helm

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome]
 - Version [98.0.4]

**Comment by sojan-official** [comment]
@lan894734188  the document is slightly outdated. please use 

```
SuperAdmin.where(:email => 'your email').first_or_create(name: 'your name', password: 'yourpassword')
```

**Comment by lan894734188** [comment]
> @lan894734188 the document is slightly outdated. please use
> 
> ```
> SuperAdmin.where(:email => 'your email').first_or_create(name: 'your name', password: 'yourpassword')
> ```

Then it sad :(Object doesn't support #inspect)

**Comment by sojan-official** [comment]
@lan894734188  could you try this ? 
```
SuperAdmin.create!(email: "email", password: "password" , name: "some name" )
```

**Comment by mohammedfarish** [comment]
> @lan894734188 could you try this ?
> 
> ```
> SuperAdmin.create!(email: "email", password: "password" , name: "some name" )
> ```

Super admin sucessfully created with this. But can't log in.

Here's what I see when I try to log in with the Superadmin credentials

![image](https://user-images.githubusercontent.com/62788088/157798887-8efd2c14-7c89-417f-94e0-f5cd19d4efa0.png)

**Comment by sojan-official** [comment]
@mohammedfarish  please try Logging in to  `yoururl/superadmin` 
- create an account from the accounts tab
- add your super admin as an account user to that account. 
- now access the dashboard

**Comment by mohammedfarish** [comment]
Please find the attachment below to see what I'm seeing.

![image](https://user-images.githubusercontent.com/62788088/158023842-af944e21-aa19-4ace-a95f-02d3b8455385.png)

**Comment by sojan-official** [comment]
> Please find the attachment below to see what I'm seeing.
> 
> ![image](https://user-images.githubusercontent.com/62788088/158023842-af944e21-aa19-4ace-a95f-02d3b8455385.png)

it's `super_admin`. my bad.

**Comment by sojan-official** [comment]
Closing this issue as it hasn't been active for a while. Feel free to reopen if it persisits

**Comment by psifertex** [comment]
Is this still valid? When I try this, I get:
```
>> SuperAdmin.create!(email: "EMAIL@DOMAIN.COM", password: "PASSWORD" , name: "some name" )
Nothing known about SuperAdmin.create!(email: "EMAIL@DOMAIN.COM", password: "PASSWORD" , name
```

**Comment by aiuoe** [comment]
ActionView::Template::Error (undefined method `super_admin_super_admins_path' for #<ActionView::Base:0x0000000003f4d0>
