### ISSUE TITLE
Manual refresh required to see new messages/updates

### ISSUE THREAD

**Issue by MichaelArriaga** [chatwoot/chatwoot#411]
**Describe the bug**
After Heroku one-click deployment and initial setup, I see new messages but only upon manual refresh (This includes initial an subsequent conversation updates)

**To Reproduce**
1. Take advantage of the 1-click deploy with heroku button
2. Complete initial setup as per docs and paste widget with correct app url into rails app layout (5.2).
3. Access chatwoot dashboard as an agent and view conversations list

**Expected behavior**
I expect to have chatwoot client open on standby and be able to see a visual update to conversations or for new ones to appear.

**Desktop (please complete the following information):**
MacOS Mojave (10.14.6)
Browser: Chrome
**Smartphone (please complete the following information):**
 
**Additional context**
As a first time using it, i'm not sure if this functionality is not yet implemented or if what i'm experiencing is intended.

**Comment by pranavrajs** [comment]
@MichaelArriaga This seems to be related to https://github.com/chatwoot/chatwoot/commit/f02d422b6af23d3bac4485249277daa50d80f444 commit. Did you deploy `master` branch or `develop` branch?

**Comment by MichaelArriaga** [comment]
HI @pranavrajs, I used the development branch. I'm not realizing that development is the default selected branch on the chatwoot repository.

**Comment by pranavrajs** [comment]
@MichaelArriaga I think there should not be any problem with the `master` branch, we will try to resolve this in `develop` soon.

**Comment by MichaelArriaga** [comment]
Thank you very much for being so responsive. I'm redeploying the master branch and will report shortly if the bug disappears

**Comment by MichaelArriaga** [comment]
That fixed the issue. Thanks!

**Comment by pranavrajs** [comment]
@MichaelArriaga Thanks for the update. This actually seems like a small issue, we will have a fix soon on `develop` branch.

**Comment by ngokevin** [comment]
For anyone else with this issue using Heroku, I had to enable the queue dyno in Heroku, it was disabled by default.
