### ISSUE TITLE
Browser Language filter does not work

### ISSUE THREAD

**Issue by rodenp** [chatwoot/chatwoot#4111]
**Describe the bug**

I created a custom attribute that represents the language of the browser.
If however I filter messages based on ‘Browser Language’ then I get no matches.

**To Reproduce**

Create custom attribute called locale. 
This should be the equivalent of the filter field ‘Browser Language’
1. On the site that hosts the chat widget, create a script and add it to the end of the server <head> Tag
<script>
window.addEventListener('chatwoot:ready', function () {  
  window.$chatwoot.setCustomAttributes({  
    locale: window.navigator.language
  });
});
</script>
2. Change the language of the browser you will use to interact with the chat widget
2. Visit the url of the site that hosts the chat widget
3. Create a new conversation.
4. On the Chatwoot server, check the locale attribute has been set
5. Try and filter messages based on ‘Browser Language’
**Expected behavior**

Messages are filtered properly based on the locale of the browser.

**Screenshots**
![DC5BF5BF-1F91-444B-9679-F0F6AEEC4144](https://user-images.githubusercontent.com/5136893/156788345-a5b611d7-530b-480f-bc7b-2d932364e91b.jpeg)
![2D5577AD-FC19-44D1-B75B-A61E0055C4B2](https://user-images.githubusercontent.com/5136893/156788400-ce25ff8a-aa9a-40e6-aa1b-18d336f065e0.jpeg)
![FDAF15C6-574E-4BA7-B30C-AB6627F61405](https://user-images.githubusercontent.com/5136893/156788672-bdd62a27-f401-4985-8eef-3db1033f2495.jpeg)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Self hosted
Docker
Version 2.2.1

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - Browser Firefox
 - Version 96

**Additional context**

**Comment by pranavrajs** [comment]
@rodenp This might be confusion around contact and conversation attributes. In the screenshot, you have set the attribute on contact, and on the filter you are trying to filter a conversation. Let me know if this is the case.

**Comment by rodenp** [comment]
Thank you @pranavrajs 
That makes sense.
But how then do i create a conversation custom attribute that is the equivalent of 'Browser Language'?
Is that possible?

**Comment by pranavrajs** [comment]
@rodenp I'm not sure what you meant by "equivalent of 'Browser Language'". You can create a custom attribute as shown here. https://www.chatwoot.com/docs/user-guide/features/custom-attributes#add-a-new-custom-attribute

**Comment by rodenp** [comment]
Hi @pranavrajs 
Basically i wanted to be able to create a conversation custom attribute that relates to the customers browser language.
I can see that you can do this through the web interface.
But there does not seem to be an equivalent to do this through the SDK.
The SDK only seems to create customer level custom attributes.
So is there a way of doing something similar to this, except for the conversation rather than the customer?
window.$chatwoot.setCustomAttributes({ locale: window.navigator.language })

**Comment by sojan-official** [comment]
@rodenp  At the moment there isn't a way in the SDK to set conversation level custom events. only custom events on contacts are supported. Its something which we are working on for future releases.

**Comment by rodenp** [comment]
@sojan-official Thank you for the heads up. Do you have any idea of when this is likely to be implemented?

**Comment by sojan-official** [comment]
@rodenp  We don't have an ETA for it yet. let's take this forward over https://github.com/chatwoot/chatwoot/issues/4210

**Comment by sojan-official** [comment]
closing in favor of #4210
