### ISSUE TITLE
Bug: Calling /dashboard/audios/ding.mp3 from widget's page

### ISSUE THREAD

**Issue by azyzio** [chatwoot/chatwoot#4113]
**Describe the bug**

It seems that PR #3956 introduced a bug. 

After every message from the operators, the widget plays a ding sound from /dashboard/audios/ding.mp3. The script is attempting to access this path based on caller url now. We can see lots of requests for this file directly on our server. And the sound doesn't play from the widget.

If the server has some anti-ddos security, the clients can get blocked after sending too many requests to non-existent paths.

**To Reproduce**
1. Create a simple website on localhost and add chatwoot widget
2. Open this website and go to insepct-network (in the browser)
3. Start the conversation from the widget
4. Respond from chatwoot dashboard
5. Close the conversation
6. You can see that ding.mp3 was requested from http://localhost:3000/dashboard/audios/ding.mp3

**Expected behavior**

ding.mp3 should be requested from the server hosting chatwoot.

**Screenshots**

![image](https://user-images.githubusercontent.com/1789131/156800042-d252479b-d1e1-4c1f-ac12-3e9c23812607.png)

**Environment**

Applies to all browsers and operating systems (tested on Chrome, Firefox and Safari, iOS and Android)

Best,
Adam

**Comment by jcomo** [comment]
This is happening for us as well. @pranavrajs could you please take a look?

It's causing a ton of bloat in our error logging. For now, we are going to redirect the path at the LB level

**Comment by sojan-official** [comment]
Thanks for the reports. Confirming that the team is working on a fix for this
