### ISSUE TITLE
In live chat widget, messages are occasionally rendered outside of a closed Chatwoot widget

### ISSUE THREAD

**Issue by aribn** [chatwoot/chatwoot#4114]
**Describe the bug**

Most of the time, the Chatwoot bubble appears in the bottom corner of the website, as expected. On occasion, however, the messages from inside the conversation are visible at load time, even though the menu has not been opened. See screenshot. (My best guess is that there may be some race condition in how I'm initializing the widget.) 

**To Reproduce**

Visit webpage with our self-hosted Chatwoot live widget embedded. 10-20% of the time, I see this issue. The rest of the time, the widget loads as expected. The following Javascript code is in a script tag immediately before the `</body>` tag:

```javascript
window.addEventListener('chatwoot:ready', function () {
  window.$chatwoot.setUser(email, {
    email: email,
    name: name,
    avatar_url: picture,
    identifier_hash: identifier_hash,
  })
});

(function(d,t) {
  var BASE_URL="https://...";
  var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
  g.src=BASE_URL+"/packs/js/sdk.js";
  g.defer = true;
  g.async = true;
  s.parentNode.insertBefore(g,s);
  g.onload=function(){
    window.chatwootSDK.run({
      websiteToken: '...',
      baseUrl: BASE_URL
    })
  }
})(document,"script");
```

**Expected behavior**

I expect the page to load with the Chatwoot button/bubble visible and no messages exposed, 100% of the time. 

**Screenshots**

<img width="331" alt="issue_screenshot" src="https://user-images.githubusercontent.com/34577/156811952-4883d382-1a9f-4f95-983a-3a6088736903.png">

**Browser logs**

No errors in the web console. 

**Server logs**

(No server errors)

**Environment**

Self-hosted installation of Chatwoot (Cloudron / Ubuntu 20.04.2 LTS / AWS EC2)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 98

**Additional context**

- User Identity Validation enforcement is enabled (and working properly.)
- Pre Chat form is enabled and box is checked requiring visitors to provide name and email address. 
- In the messenger script, the Chatwoot SDK is loaded asynchronously.

**Comment by sojan-official** [comment]
@aribn This is an intended behaviour when a contact has unread messages in the widget. It is to alert the user that they have received new messages from the agent with out taking any extra actions.

**Comment by aribn** [comment]
@sojan-official That makes sense, but this is happening at other times, too. (Note that the screenshot shows all past messages, not only new ones.)

**Comment by sojan-official** [comment]
@arib that sounds like a bug. let us take a look.

**Comment by sojan-official** [comment]
ref: https://discord.com/channels/647412545203994635/647729576427913228/955057182808870922
