### ISSUE TITLE
bug: unable to send audio messages on Telegram

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#4115]
Noticed that when sending any type of audio file (mp3, voice record, etc), it is not received by the user on Telegram, even that on Chatwoot it appears as if the message was sent successfully.

<img width="524" alt="Screen Shot 2022-03-06 at 12 23 07 PM" src="https://user-images.githubusercontent.com/66124192/156919070-d7e0ae56-e2dc-4a8f-988d-8f3c0eb6f9dc.png">

**Comment by sojan-official** [comment]
This behaviour has been reported for 360 Dialog integration as well.

**Comment by giquieu** [comment]
@sojan-official I can investigate this case.

**Comment by sojan-official** [comment]
@giquieu  thanks a lot.

**Comment by giquieu** [comment]
@sojan-official , 
The return of the request for the Telegram Bot is:
{"ok":false,"error_code":400,"description":"Bad Request: failed to get HTTP URL content"}
From what the documentation indicated to me, it is about incompatibility of the audio format.
Everything indicates that Telegram receives as Audio, only .MP3 or .M4A format (https://core.telegram.org/bots/api#sendaudio), or, .OGG file encoded with OPUS to send audio recording.

Going deeper, there is a method to receive recording audio, where the player is different.

This player is a recorded audio:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/9892674/159600227-ca2a536f-bbf8-4006-b5a3-b5480130301e.png">

This player is an audio file:
<img width="631" alt="image" src="https://user-images.githubusercontent.com/9892674/159600355-9f89d72f-6aaa-47b4-8f49-68b7e361517e.png">

It's the same format situation in the case of 360Dialog:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/9892674/159604063-a13ff68d-0e78-4be1-88f8-1b49a37ceff5.png">

I also imagine it's the same format situation for Twilio:
<img width="870" alt="image" src="https://user-images.githubusercontent.com/9892674/159604311-d042e9f7-08b3-4c33-b947-5504efd0f4c1.png">

After this research, I looked for a way to convert the audio and in the end I ended up finding a lib that records and converts the audio to .mp3 or .ogg, keeping the waveform visualization of the recording.
https://collab-project.github.io/videojs-record/#/
(Inside the videojs-recorder the same libs I used to record the audio are used)

I would like to propose an exchange. And start using videojs-recorder with conversion to .mp3 or .ogg.
In this way, it will serve 360Dialog, Twilio and Telegram.

What do you think? Can I change?

**Comment by sojan-official** [comment]
@giquieu  Thanks a lot for the detailed investigation.  I think we can go ahead with the  `videojs-record` library since it's also `MIT` licensed: https://github.com/collab-project/videojs-record

Also the options like record video, screen etc sounds promising towards future as you suggested. 
Please feel free to go ahead. let us know if you need any help from our end.

**Comment by giquieu** [comment]
@sojan-official 
To convert the recorded audio to ogg with Opus codec, I'm using opus-rencoder, recommended by video-js.
(https://github.com/chris-ruadmin/opus-recorder)
To do the conversion it is necessary to use encoder code provided by the lib, in this case, I needed to add the js file to the project.
In config/webpack/environment.js I added:
environment.loaders.append('opus', {
   test: /encoderWorker\.min\.js$/,
   loader: 'file-loader',
   options: {
     name: '[name].[ext]',
   },
});
What do you think about it? Is it possible to keep it like this?

**Comment by sojan-official** [comment]
@giquieu It should be okay to add it to the webpack environment.

**Comment by jtperez2** [comment]
Hello everyone , i think i'm having the same trouble with Whatsapp via Twilio. It's possible that this fix can help us?

**Comment by jtperez2** [comment]
we updated to v2.5.0 which includes this fix, but still I'm sending wav instead of ogg. 
Channel: Whatsapp by Twlio
Storage: S3
Is there something else to do in order to make it work??

Thanks team!
