### ISSUE TITLE
feat: Support additional authentication mechanisms for SMTP apart from :login

### ISSUE THREAD

**Issue by green-globe** [chatwoot/chatwoot#4118]
## Tasks

- [ ] Ability to select auth mechanism from a drop drown
At the moment the SMTP auth mechanism is hardcoded into chatwoot as :login
ref: https://github.com/chatwoot/chatwoot/blob/73d8073530a7dab8fa95b1deecb7fa3ad8028296/app/helpers/api/v1/inboxes_helper.rb#L33

support additional options : https://docs.ruby-lang.org/en/2.4.0/Net/SMTP.html#class-Net::SMTP-label-SMTP+Authentication

- [ ] Change `email` to `username` for both SMTP and IMAP.  : At the moment Chatwoot mandates that the username for IMAP and SMTP to be emails, which shouldn't be a requirement. 

--------

## original report

**Describe the bug**

Unable to add SMTP configuration in Inbox - Email

**To Reproduce**

1. Go to Settings
2. Select Inboxes
3. Add Inbox
4. Click on Email and fill in Details
5. Inbox Generated
6. Go to Settings
7. Select the EMAIL Inbox to configure
8. Click on Configuration tab
9. Fill in SMTP server details in the SMTP section
10. Enable SMTP configuration for this inbox

**Expected behavior**

Be able to add SMTP server details without issues

**Screenshots**

![image](https://user-images.githubusercontent.com/88571410/157020511-2fd13236-1986-4b5f-a136-38c4a341712d.png)
![image](https://user-images.githubusercontent.com/88571410/157020563-6aaafadf-aaf2-40ab-b806-d45ce8b7e450.png)

**Browser logs**

See screenshot of browser console

**Server logs**

See screenshot of browser console

**Environment**

Self hosted installation 2.2.1 on HEROKU

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by pranavrajs** [comment]
@green-globe Can you please share the server logs here? If you can share the logs behind the 500 server error, that would help in debugging the error.

**Comment by green-globe** [comment]
![image](https://user-images.githubusercontent.com/88571410/157659588-52f4a3fb-d0d4-41e3-b40a-26d48a1ba3f9.png)
@pranavrajs

**Comment by aswindevps** [comment]
@green-globe Currently we support only `LOGIN` as the authentication mechanism. Could you please share the authentication mechanism used by the mail server?

**Comment by colenh** [comment]
> @green-globe Currently we support only `LOGIN` as the authentication mechanism. Could you please share the authentication mechanism used by the mail server?

im fairly sure that the provider i use, Sendgrid, uses basic authentication

https://docs.sendgrid.com/for-developers/sending-email/authentication

**Comment by aswindevps** [comment]
SMTP authentication mechanisms.

- PLAIN
- LOGIN
- CRAM-MD5
- XOAUTH
- XOAUTH2
- NTLM
- GSSAPI
