### ISSUE TITLE
[Specs] Add Cypress tests

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#412]
**Is your enhancement request related to a problem? Please describe.**
It is not feasible to do manual QA every time a PR is merged. JS & Ruby specs do not cover all our integrations properly, we should aim to add cypress test for P1 flows in this sprint.

**Describe the solution you'd like**
1. Initialize Cypress test framework.
2. Add cypress tests

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/pull/2607 

we will create individual issues for specific cypress flows
