### ISSUE TITLE
Add Ability To Use Human Agent Tag by default. For Instagram Messages  after 24 hr

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4121]
After 24h, businesses can no longer reply to the message. This can be problematic if your business is closed during the weekend and the message goes unnoticed. Luckily, with the Human Agent Tag you can continue messaging the contact within the next 7 days.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3082#issuecomment-940239211
