### ISSUE TITLE
Widget requests "/dashboard/audios/ding.mp3"

### ISSUE THREAD

**Issue by manuelmeurer** [chatwoot/chatwoot#4122]
**Describe the bug**

I started seeing these errors in our console recently: 

* GET https://uplink.tech/dashboard/audios/ding.mp3 404
* Uncaught (in promise) DOMException: Unable to decode audio data

I'm pretty sure the bug was introduced here:
https://github.com/chatwoot/chatwoot/commit/a3cb26a317694b5d26ff5bc90cd970920422a847#diff-ebe43522c941faad9c0adad4ebb34b9878d0097057789340334323544a0fb056L19-R20

**To Reproduce**

* Use v2.2.1
* Click on the chat bubble

**Expected behavior**

No error...

**Screenshots**

[Screenshot](https://take.ms/mqjqM)

**Environment**

Chatwoot Cloud

**Comment by sojan-official** [comment]
@manuelmeurer Thanks for the report. We will track this over https://github.com/chatwoot/chatwoot/issues/4113
