### ISSUE TITLE
Add a confirmation note before deleting a note about a contact

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4124]
Right now, deleting a note on the contact does not have a confirmation popup. It leads to accidentally deleting the note which cannot be recovered.

**Todo:**

- [ ] Ask for confirmation before deleting the note.

**Comment by sojan-official** [comment]
@substr2837  please go ahead. let us know if you have any questions.

**Comment by substr2837** [comment]
@sojan-official  Could you please give me access to the repo cause I'm not able to push my commit

**Comment by sojan-official** [comment]
@substr2837  The workflow which we follow is that you create a fork of the repo, commit the changes over there and raise the PR from your fork.

**Comment by substr2837** [comment]
Thank you @sojan-official for the information

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/4294
