### ISSUE TITLE
Integration with autoresponder for Android

### ISSUE THREAD

**Issue by clanto007** [chatwoot/chatwoot#4126]
**Describe the solution you'd like**
 there is an app for Android that is named autoresponder.ai and do autoresponses for whatsapp, telegram, viber, facebook messenger, instagram and signal. This app also have API to connect to a server and responde to these apps with a server, I think that can be very useful to integrate this in chatwoot so that we can have more channels quickly and whatsapp business without the use of API, here the blog page that explian the API calls
 https://www.autoresponder.ai/post/connect-your-messengers-to-a-web-server-api-using-autoresponder

**Comment by pranavrajs** [comment]
@clanto007 Can you please share the use case you are trying to solve? Are you trying to add more channels to Chatwoot?

**Comment by clanto007** [comment]
Sorry for my bad English and misunderstanding.
Yes adding more channels using this app.

**Comment by pranavrajs** [comment]
@clanto007 Closing this issue as the proposed solution doesn't seem to have APIs. We will publish a framework to push plugins in Chatwoot soon, you can make use of that to extend Chatwoot.
