### ISSUE TITLE
New installation - Widget not appearing on website

### ISSUE THREAD

**Issue by kalamchi75** [chatwoot/chatwoot#4132]
Hi Guys, 

I am new to Chatwoot server. I have installed a self-hosted server following the official documentation. 
The server is running in Azure VM with Ubuntu 20.04 , nginx and postgres. 

The server is up and accessible. 
I am trying to add the chat widget to our website with WordPress. 

I have followed the instructions and created an inbox for Web Site. Copied the code to Wordpress snippets, and installed/activated/configured the plugin in Wordpress. 

However, the widget is not showing up on the webpage. 

Any advice please ?

Thanks in advance.

**Comment by vishnu-narayanan** [comment]
Could you check your browser console and see if there are any error logs ?

**Comment by kalamchi75** [comment]
Something like this : 

![image](https://user-images.githubusercontent.com/21124227/157259395-124bfaf4-6c3c-4b6e-9973-9776eba266ef.png)

**Comment by kalamchi75** [comment]
Hi Guys, 

Any advice on this ?

Thanks

**Comment by pranavrajs** [comment]
@kalamchi75 None of these errors seems like they originate from the widget SDK. Can you please use the official plugin for Wordpress? https://www.chatwoot.com/docs/product/channels/live-chat/integrations/wordpress

**Comment by kalamchi75** [comment]
Hi @pranavrajs , I did actually se the official plugin. Since this is my first Chatwoot server installation, I followed the exact steps in the documentation. 
Please see below the code insertion in Wordpress: 

![image](https://user-images.githubusercontent.com/21124227/157628210-e75744b9-bb5e-42ea-88c6-96fac4df903c.png)


and the Plugin configuration in Wordpress: 

![image](https://user-images.githubusercontent.com/21124227/157628467-94f1207d-02b8-4a9d-a0fa-7a25d58f544e.png)


Aside from HTTP, HTTPS, and TCP port 3000, are there any other protocols/ports that need to be opened in the Azure VM's firewall ?

The Chatwoot server  and the target Wordpress webpage are in two different domains, would that be an issue ?

Best Regards

**Comment by kalamchi75** [comment]
Hi Guys, 

Advice please ?

Best Regards

**Comment by sojan-official** [comment]
@kalamchi75 could you share the URL where you are loading the widget on `hello@chatwoot.com` so that our team can take a look?

**Comment by kalamchi75** [comment]
Hi @sojan-official 

you mean the target webage ? or the URL the Chatwoot server from which the widget is loaded ?

Thanks

**Comment by sojan-official** [comment]
@kalamchi75 the target webpage where you have the script added.

**Comment by kalamchi75** [comment]
[talia](https://taliacom.wpengine.com/)

The question is, would it work if the chatwoot server and the target webpage are on TWO DIFFERENT domains ?
and, are there and specific ports need to be opened between the two servers other that HTTP, HTTPS, and TCP 3000 ?

Thanks

**Comment by pranavrajs** [comment]
@kalamchi75 Thanks for sharing the URL. This is not working because your Chatwoot installation is on HTTP and your website is on HTTPS. Please use SSL with Chatwoot installation, then it would start working.

<img width="545" alt="Screenshot 2022-03-14 at 2 47 41 PM" src="https://user-images.githubusercontent.com/2246121/158141891-ae272bc4-8d00-4fc0-9bf6-ca9281474550.png">


You are trying to load an HTTP resource from HTTPS website which would be blocked by the browser.

**Comment by kalamchi75** [comment]
Hi @pranavrajs 

Thank you very much for the explanation. I will work on that. 
Where did you see those errors and how please ? That would be handy for future installation/testing. 

Best Regards

**Comment by sojan-official** [comment]
@kalamchi75 it is available in your browser console 
<img width="1851" alt="Screenshot 2022-03-14 at 5 58 45 PM" src="https://user-images.githubusercontent.com/73185/158172299-dcff8df6-3e9e-4d71-9413-ad28f31b28d2.png">

**Comment by kalamchi75** [comment]
Thank you so much Guys. Moving to HTTPS solved the issue. 

![image](https://user-images.githubusercontent.com/21124227/158185886-59dcf186-5fa3-4a9d-916b-6bc07108d2bf.png)
