### ISSUE TITLE
PHP SDK

### ISSUE THREAD

**Issue by ManojKiranA** [chatwoot/chatwoot#414]
**Is your feature request related to a problem? Please describe.**
I am working on a PHP (Laravel) Framework. 
It would be helpful SDK or Composer package

**Describe the solution you'd like**

1. May be Creation a Dedicted Package with Vue SPA like.
Examples:
[Telescope](https://github.com/laravel/telescope)
[Horizon](https://github.com/laravel/horizon)

2. Creating a Package that utilizes the **Api** form  chatwoot so that we can customize it

**Describe alternatives you've considered**
No Idea.

**Comment by egorsmkv** [comment]
What should this SDK do?

**Comment by pranavrajs** [comment]
@ManojKiranA Could you please elaborate this requirement? What is the exact use case you are looking for?

**Comment by sojan-official** [comment]
Closing because of no further activity.
