### ISSUE TITLE
Add authentication for rails active-storage direct upload

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#4147]
**Is your enhancement request related to a problem? Please describe.**
We have direct upload in place but the auth token check is not present in that particular controller.

**Describe the solution you'd like**
Extend the active-storage direct upload controller and auth token check.
Update the widget direct upload URL
Update the dashboard direct upload URL

**Describe alternatives you've considered**
NA

**Additional context**
People can misuse the AWS S3 by using the signed key.

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/pull/4160
