### ISSUE TITLE
Inconsistency in button design

### ISSUE THREAD

**Issue by RakeshPotnuru** [chatwoot/chatwoot#4150]
**Describe the bug**

I noticed an inconsistency in button text across the application. Some are title cases, some are sentence cases. See the image below.

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to the app [dashboard](https://app.chatwoot.com/app/accounts/68570/dashboard)
2. Check different buttons

**Expected behaviour**

Be consistence with one case

**Screenshots**

![issue chatwoot](https://user-images.githubusercontent.com/70439799/157685370-a64ca82d-ee46-4c50-b636-c4a02c51fb62.png)

**Environment**

IChatwoot cloud

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 99.0.1150.36 (Official build) (64-bit)

**Comment by RakeshPotnuru** [comment]
If the issue is valid, can I contribute?

**Comment by RakeshPotnuru** [comment]
@sojan-official 
You want them to be title case or sentence case. Also, almost all the buttons are inconsistent, so can I change all the buttons?

**Comment by sojan-official** [comment]
let's go with sentence cases. @RakeshPotnuru

**Comment by pranavrajs** [comment]
Closing this here as we will revisit the inconsistencies again with the re-design project.
