### ISSUE TITLE
Add received/read checkmarks

### ISSUE THREAD

**Issue by Giszmo** [chatwoot/chatwoot#4156]
**Is your enhancement request related to a problem? Please describe.**
Often when I reply clients on the spot (same minute) they do not reply back and one kept sending more messages clearly indicating he has not received my messages.

**Describe the solution you'd like**
Just like modern IMs, show checkmarks when server reports back, when client's browser reports back and when that window had focus. :white_check_mark:,  :white_check_mark: :white_check_mark:, :heavy_check_mark: :heavy_check_mark: 

**Describe alternatives you've considered**
show alert if their browser doesn't receive my messages: "We sent your message but their browser tab appears to be closed already but hang in there, we sent them an email, too"

**Additional context**
%%

**Comment by iammattmartin** [comment]
Similarly related to #2099 and nearly #1021

**Comment by Giszmo** [comment]
Yeah, it's a duplicate of #2099 which I had not found when I searched for existing issues. Frustrating to see it not getting addressed as I suspect bugs preventing clients to receive messages and without indicator I'm blind to this and feel stupid chatting with myself.

**Comment by sojan-official** [comment]
@Giszmo  we have it in our pipeline to add these receipts. Let's keep tracking this over #1021

**Comment by Giszmo** [comment]
#1021 mentions only "Facebook/Twitter/Whatsapp/SMS". I hope #2099 is "in the pipeline", too.
