### ISSUE TITLE
Prefilled Name and Mail

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot#4163]
Related to this: https://github.com/chatwoot/chatwoot/issues/1131

i will prefilled this fields

like: 

g.onload=function(){
			  window.chatwootSDK.run({
				websiteToken: 'xx',
				baseUrl: BASE_URL,
				  fullName: 'xxx',
				  email: 'xxx'
			  })
			}

**Comment by sojan-official** [comment]
@drexlma  have you looked at the `set_user` option available in the  SDK
ref: https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#set-the-user-in-the-widget

**Comment by drexlma** [comment]
i see the data in the backend but the user ned to insert infos
<img width="359" alt="Bildschirmfoto 2022-03-13 um 22 13 03" src="https://user-images.githubusercontent.com/7121202/158079497-3976847d-8136-431e-b49f-892e5c4457ef.png">

**Comment by sojan-official** [comment]
@drexlma  this should be a bug. for identified users the form shouldn't request the email and name again.  We will take a look.
cc: @nithindavid

**Comment by muhsin-k** [comment]
@drexlma Thank you for reporting. @sojan-official This is a confirmed bug. I will take care of this
