### ISSUE TITLE
Make responsive UI for mobli browser

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4165]
Right now I can't answer on message and use chatwoot via mobile browser I hope you can make responsive UI for mobile browser
![Screenshot_20220312-024610_Chrome](https://user-images.githubusercontent.com/20530550/157991878-344f165c-a5e8-48f9-ace2-00ef48e7cb1f.jpg)

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/2617
