### ISSUE TITLE
email channel not working with mailgun (param is missing or the value is empty: body-mime)

### ISSUE THREAD

**Issue by yairShiloach** [chatwoot/chatwoot#4166]
Hi, we've set up to receive emails using mailgun - everything seems to be set up correctly,
mailgun sends the message to the app via the link:
https://my.app/rails/action_mailbox/mailgun/inbound_emails/mime

And log has an error:
Mar 12 12:40:29 [78632e0e-3df1-4a33-a5fb-ea4e3383c008] ActionController::ParameterMissing (param is missing or the value is empty: body-mime
Mar 12 12:40:29 Did you mean? body-html
Mar 12 12:40:29 body-plain
Mar 12 12:40:29 domain

Installation using cloudron - the most up-to-date version

**Comment by nihey** [comment]
Any updates on this? It seems like it could be something to do with rails.

Probably mailgun is sending their webhook HTTP requests in a way that it cannot understand.

**Comment by nihey** [comment]
FYI: Solved it by adding the URL at the "forward" field in mailgun, just like stated at: https://github.com/rails/rails/issues/45363#issuecomment-1158576615

**Comment by sojan-official** [comment]
@nihey  Thanks a lot for posting back the update.

 @yairShiloach Closing this as we have a solution. Please feel free to reopen if it persists.
