### ISSUE TITLE
[CW-2876] Move Current class under ActiveSupport CurrentAttributes

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#4168]
Change the implementation of `module Current` according to the ActiveSupport::CurrentAttributes abstract class. 
Refer: https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

<sub>[CW-2876](https://linear.app/chatwoot/issue/CW-2876/move-current-class-under-activesupport-currentattributes)</sub>

**Comment by pranavrajs** [comment]
Moving it to internal tech debt pipeline.
