### ISSUE TITLE
chore: Explore IMAP IDLE

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4169]
Instead of polling, let's see if we can come up with a feasible solution using IMAP idle. 

ref: https://discord.com/channels/647412545203994635/654017096812068864/952115482222276638

**Comment by pranavrajs** [comment]
We need to figure out a better way in IMAP inboxes. However, IMAP IDLE doesn't seems to be the way to move forward as it would require concurrent connections to all the inboxes we have added in the server. We will explore other mechanism in the future.
