### ISSUE TITLE
bug: Start conversation is not working in pre-chat form

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#4177]
**To Reproduce**

Steps to reproduce the behaviour:
1. Enable pre-chat form and CSAT
2. Go to Widget and create conversation
3. Resolve conversation from dashboard
4. Go to widget and click on "Start new conversation"
5. Type message and submit the button

https://user-images.githubusercontent.com/12408980/158233670-1d36a080-168d-44df-b945-3f9012478d8e.mov

**Comment by pranavrajs** [comment]
@muhsin-k Since this is not bug on the prod/develop branch, can we close it?
