### ISSUE TITLE
Support conditions based on contacts in conversation/message events.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4179]
As a agent, I’m not able to create a workflow based on the contact. For eg: If the contact is from a company, or has a domain eg: google.com, then assign every conversation to a particular team. This requires contact filters/conditions to be added on the conversation/message event.

**Comment by tejaswinichile** [comment]
Add conditions based:

contacts:
1. email [equal_to, not_equal_to, contains, does_not_contain]
2. name  [equal_to, not_equal_to, contains, does_not_contain]
3. custom_attributes : 
                   - priority_customer
                   - is_priority_customer

@pranavrajs company_name would also be the additional_attributes/custom_attributes correct?

**Comment by pranavrajs** [comment]
@tejaswinichile At the moment, it is in additional_attributes.
