### ISSUE TITLE
Verification e-mails for agents not being received

### ISSUE THREAD

**Issue by kalamchi75** [chatwoot/chatwoot#4193]
Hi Guys

**Describe the bug**

Self-hosted server. I have noticed that none of the agent verification emails are being received (I also checked junk e-mails) regardless of the fact that the server confirms "an e-mail has  been sent"
I have created and configured an e-mail inbox, enabled SMTP and IMAP, and tested the channel. It works fine and I can receive e-mails and reply. So the connection between Chatwoot server  and the mail server is working. 
Yet, the problem is with the verification e-mails to agents. 
 
**To Reproduce**

1. Go to 'Agets'
2. Click on 'Edit'
3. Scroll down to 'reset Password'
4. Server confirms an e-mail with instructions has been sent

**Expected behavior**

An e-mail with the instructions should  be received by the agent. 

**Server logs**

Share the server logs to debug the issue further

**Environment**
Self hosted installation of Chatwoot. 
Linux 20.04 VM installation

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 98.0.1

**Additional context**
Please see below .env mail configuration
`     
    # The email from which all outgoing emails are sent
      MAILER_SENDER_EMAIL=chatwoot@OUR.DOMAIN
    
    #SMTP domain key is set up for HELO checking
    SMTP_DOMAIN=mail.OUR.DOMAIN
    # the default value is set "mailhog" and is used by docker-compose for development environments,
    # Set the value as "localhost" or your SMTP address in other environments
    SMTP_ADDRESS=mail.OUR.DOMAIN
    SMTP_PORT=25
    SMTP_USERNAME=chatwoot@OUR.DOMAIN
    SMTP_PASSWORD=SOME.PASSWORD
    # plain,login,cram_md5
    SMTP_AUTHENTICATION=login
    SMTP_ENABLE_STARTTLS_AUTO=false
    # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
    SMTP_OPENSSL_VERIFY_MODE=none
    # Comment out the following environment variables if required by your SMTP server
    # SMTP_TLS=
    # SMTP_SSL=

    # Mail Incoming
    # This is the domain set for the reply emails when conversation continuity is enabled
    MAILER_INBOUND_EMAIL_DOMAIN=mail.OUR.DOMAIN

`

**Comment by kalamchi75** [comment]
Any Advice ?

**Comment by pranavrajs** [comment]
@kalamchi75 Can you please share any logs from the server (worker logs) to help us debug the issue?

Also, have you set the FRONTEND_URL in the environment variables?

**Comment by sojan-official** [comment]
@kalamchi75 you could access  `chatwootinstalaltion/super_admin` -> navigate to sidekiq/dead and see if there are any errors reported over there?

**Comment by kalamchi75** [comment]
Hi @pranavrajs 

> @kalamchi75 Can you please share any logs from the server (worker logs) to help us debug the issue?
Where can Find them please ? 

> Also, have you set the FRONTEND_URL in the environment variables?
    # Replace with the URL you are planning to use for your app
    FRONTEND_URL=https://chatwoot.talia.net

**Comment by tejaswinichile** [comment]
This shows that connection can not be established for the mailer in particular:

https://github.com/chatwoot/chatwoot/issues/4193#issuecomment-1070846655

Can you check if your mailer setup is done correctly?
Seems like mail notification jobs and conversation reply mailer is also not working means that the mailer setup is now working.

Can you verify if you are able to receive any notification email from your server? from the mail domain that you have mentioned.

cc @sojan-official @pranavrajs

**Comment by kalamchi75** [comment]
Hi @tejaswinichile 

In fact yes, the Mail inbox (channel) is receiving emails and I can also reply. If that what you mean. 
It's just the Agent  verification mails are not going anywhere. 
 
Thanks

**Comment by kalamchi75** [comment]
Please see below successful email chat: 
From server side: 

![image](https://user-images.githubusercontent.com/21124227/158839358-36726c77-a9e4-4216-ac82-fac711fed5f6.png)

and from my outlook (as a customer) : 

![image](https://user-images.githubusercontent.com/21124227/158839607-2f89d4d5-d742-4142-9210-438c59e40dcf.png)


So basically the connection/authentication into the mail server on SMTP and IMAP are working correctly.

**Comment by sojan-official** [comment]
@kalamchi75 Did you restart the chatwoot service after updating the environment variables?

**Comment by kalamchi75** [comment]
As of today, even the E-mail channel that was working before (as seen in my previous comment) stopped working, with IMAP error connection closed. 
Trying to recreate the channel fails, and the server is unable to update/save IMAP and SMTP settings. 

![image](https://user-images.githubusercontent.com/21124227/158985240-d28f7517-5ede-4dd1-b533-88310cee9c61.png)

I have verified the connection between Chatwoot and the mailserver  using nmap.  SMTP and IMAP ports are open: 

![image](https://user-images.githubusercontent.com/21124227/158985670-65ef97b0-c27d-44d8-9f04-fdbd613285f7.png)

**Comment by hashlash** [comment]
I also encountered a similar issue (I'm using Mailjet).

I've tried to send the email using rails console, and the email is sent ([the log](https://gist.github.com/hashlash/74f952761289ba8c42433073ce7cd8d4#file-rails-console-log)). Perhaps @kalamchi75 can also try to verify using this method:

```ruby
ActionMailer::Base.mail(
  from: "admin@company.com",
  to: "myemail@gmail.com",
  subject: "Test",
  body: "Test"
).deliver_now
```

I've also made sure to restart the Chatwoot daemon:

```console
$ sudo systemctl restart chatwoot.target
```

And check both the [`chatwoot-web`](https://gist.github.com/hashlash/74f952761289ba8c42433073ce7cd8d4#file-chatwoot-web-log) and [`chatwoot-worker`](https://gist.github.com/hashlash/74f952761289ba8c42433073ce7cd8d4#file-chatwoot-worker-log) service logs when I try to create an Agent.

```
$ sudo journalctl -u chatwoot-web.1.service
$ sudo journalctl -u chatwoot-worker.1.service
```

The Sidekiq dead jobs only show errors from the previous misconfiguration:

![image](https://user-images.githubusercontent.com/23237214/159210027-41e080e4-c94e-44fb-af98-4878e6e9c4ac.png)

I've also checked the email dashboard, but the only email that shows up is the one that is sent from the rails console (end previous troubleshooting emails). This means that the emails are not even reaching the mail server.

![image](https://user-images.githubusercontent.com/23237214/159211337-413c1303-83cd-4e5e-8974-aa07aed250ea.png)

Note: my Mailjet's timezone is configured as GMT+01 by default somehow.

![image](https://user-images.githubusercontent.com/23237214/159211420-e3566d3f-8db1-43ee-8cda-584b902a40fe.png)

Relevant configuration (.env):

```env
# The email from which all outgoing emails are sent
# could user either  `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
MAILER_SENDER_EMAIL=


#SMTP domain key is set up for HELO checking
# SMTP_DOMAIN=chatwoot.com
# the default value is set "mailhog" and is used by docker-compose for development environments,
# Set the value as "localhost" or your SMTP address in other environments
SMTP_ADDRESS=in-v3.mailjet.com
SMTP_PORT=465
SMTP_USERNAME=<redacted>
SMTP_PASSWORD=<redacted>
# plain,login,cram_md5
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
# Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
SMTP_OPENSSL_VERIFY_MODE=none
# Comment out the following environment variables if required by your SMTP server
SMTP_TLS=true
# SMTP_SSL=
```

I'm on a self-hosted Chatwoot v2.3.1 with Ubuntu 20.04 VM installation on GCE.

Actually, I found something strange. Previously (March 3rd) I tried to use helm chart on GKE, and it worked. But now when I tried again, using the same (if I'm not mistaken) Chatwoot v2.2.0, and I got the same issue as my VM installation.

**Comment by sojan-official** [comment]
@hashlash seems like the `MAILER_SENDER_EMAIL` value is empty?

**Comment by hashlash** [comment]
Oh sorry, I forgot to mention that I've actually tried both but still doesn't work.

Updated the `.env` in my issue description to explicitly set the `MAILER_SENDER_EMAIL`.

**Comment by kalamchi75** [comment]
Hi Guys, 

Thanks for everybody for their feedback and advises.
Unfortunately, I have to drop this project since it has such issues since the start. I cannot rely on it, and will have to search for different options. 

I wish you guys all the success in your endeavor.

**Comment by hashlash** [comment]
Sorry to hear that @kalamchi75

For those who need a workaround for the verification process (especially if your agents are invite-only), you can manually set the password and the "confirmed at" fields from the superuser dashboard (`/super_admin/users`) and send the password to the agent.

![image](https://user-images.githubusercontent.com/23237214/159656095-e097c98c-52ff-4f4c-8b12-62598cdf37f7.png)

**Comment by hashlash** [comment]
@sojan-official I can receive the password reset email.

So it must be on the verification email process, right?

**Comment by sojan-official** [comment]
@hashlash  Both the reset password email and verification email works pretty much with the same configuration. So it's rare that one would work and the other won't.  Could you try the verification email again for a different email address ?

**Comment by hashlash** [comment]
Thanks for the idea.

After trying again some more, I found that the email verification can only be sent once for one email address. Even if I've deleted the **Agent** (from `/app/accounts/2/settings/agents/list`).

It seems deleting the **Agent** doesn't remove the corresponding **User** (which stores the verification and email data). Is this intentional? I tried to find something about it on the [product docs](https://www.chatwoot.com/docs/product/) but found nothing yet.

**Comment by sojan-official** [comment]
@hashlash Due to the multi-tenant nature of Chatwoot, User records are not deleted when you remove an agent from an account, Since the same User might have access to a different account. 

We will be adding the ability to delete users from super admin in upcoming sprints though
#4164

**Comment by hashlash** [comment]
Okay cool! I think the docs could also be improved. Perhaps by participating in [Google Season of Docs](https://opensource.googleblog.com/2022/02/the-2022-season-of-docs-application-for-organizations-is-open.html)? But sadly the submission deadline for this season is today at 18:00 UTC :cry:

**Comment by sojan-official** [comment]
@hashlash  no worries. Thanks for the suggestion about `Google Season of Docs`. We will take a look :D
