### ISSUE TITLE
fet: option to disable delete message function

### ISSUE THREAD

**Issue by silvaartur** [chatwoot/chatwoot#4197]
For companies compliance and audit is very important. Because of this is important exist a option to disable "delete" button on messages.

Put a variable inside .env or installation_config to disable this option (delete message).

**Comment by sojan-official** [comment]
This will be covered under https://github.com/chatwoot/chatwoot/issues/4216

**Comment by pranavrajs** [comment]
Closing this here as we would track the changes in #4216.
