### ISSUE TITLE
Ability to get active/Inactive for agents

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4199]
**Is your feature request related to a problem? Please describe.**
Currently chats are assigned to everyone added in the inbox - but if someone is logged in, suppose for any other tasks, chats should not be assigned to him until he selects active for chats. 

**Describe the solution you'd like**
A small button of "Active for chat" once clicked, chats will strat being assigned to that user till he clicks "Inactive button which will appear on the same place of Active for chat"

**Additional context**
Currently one would have to logout in order to for system to stop assigning chats to him/her but active/Inactive logic can oppose that, if no one is active, chats will go to unassign just like now.

**Comment by sojan-official** [comment]
- When the automatic assignment is enabled, chatwoot would always give priority to the online agents in the system.
- one can mark themselves as busy or offline if they don't want the chats to be assigned to them. 
<img width="256" alt="Screenshot 2022-03-18 at 8 15 17 PM" src="https://user-images.githubusercontent.com/73185/159024756-1cef9639-fc8f-446d-81ad-d7f1ed3b0752.png">


note: if none of the agents is online then chatwoot will start assigning conversations to busy or offline agents as well.
