### ISSUE TITLE
Support for Azure Cloud Storage as storage for Chatwoot

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#42]
Related #41

**Comment by sojan-official** [comment]
once  #158 is done, this should be straightforward. we want to use active storage to handle this

**Comment by sojan-official** [comment]
ref : https://github.com/chatwoot/chatwoot/pull/393

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/393

**Comment by pranavrajs** [comment]
@sojan-official Please add the variables to .env and to the docs.
