### ISSUE TITLE
Allow Whatsapp channel to run one-off campaign

### ISSUE THREAD

**Issue by ArijitWeird** [chatwoot/chatwoot#4201]
Currently Whatsapp channel are not supported in one-off campaign. This feature can increase usecases of chatwoot to another level.

**Comment by sojan-official** [comment]
@ArijitWeird Thanks for the suggestion

- Whatsapp doesn't support outbound messages to existing contacts after 24 hours apart from the approved template. 
- The API also states that you need to explicitly get permissions from contacts if you are initiating a conversation without them sending you the first message. 

So we are still looking into the ways of how we can implement this.

**Comment by skyycodes** [comment]
@sojan-official 
 For the first issue, we can take approval of the content from whatsapp.
And, for the second issue, it depends on the person/company using chatwoot. every company have it's own contact policy (sending whatsapp message in this case) in their t&c, privacy policy etc. They mention why and how they can contact the user in their policies.

**Comment by clairton** [comment]
Hi

I am need this feature and I would work on this.

An idea, at the form  when choose Whatsapp Channel, showing a select with the available templates e a input file to upload a csv with numbers will receive the message and a params to bind in template.

**Comment by sojan-official** [comment]
@clairton We can stick to the same format used for on-off campaigns for the SMS channels, where we allow selecting of specific labels.  As for importing the csv with numbers lets handle that in contact tab. (fix by #3462)

**Comment by clairton** [comment]
@sojan-official and templates params for whatsapp template mensages?

**Comment by muhsin-k** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/issues/6385.
