### ISSUE TITLE
Add custom attributes to conversation (not contact) through SDK

### ISSUE THREAD

**Issue by Deddy-SMSP** [chatwoot/chatwoot#4210]
**Is your feature request related to a problem? Please describe.**
I want to save utm data etc to the conversation not the contact - because it can change per conversation 

**Describe the solution you'd like**
Just like adding custom attribute to contact using SDK -> window.$chatwoot.setCustomAttributes(newUtm);
I want something like -> window.$chatwoot.conversation.setCustomAttributes(newUtm);

**Describe alternatives you've considered**
Maybe to simplify -> window.$chatwoot.setCustomAttributes(newUtm, "conversation");

**Additional context**
Please pardon me, I don't really understand about this section, my english is not very good because it's not my native language.

Thanks

**Comment by sojan-official** [comment]
@Deddy-SMSP  thanks for reporting. we will look into this.

**Comment by danghung-dev** [comment]
Do we have any update on this issue?
We can create a Conversation attribute, but we cannot set custom attribute to Conversation.

**Comment by serachung** [comment]
Hello there, do we have any updates on this? I'm also looking for this feat

**Comment by SteffeyDev** [comment]
I'd like this feature as well

**Comment by softcam-claiton** [comment]
Da seguinda forma funcionou para mim:

window.$chatwoot.setConversationCustomAttributes({
    key: value
});

Espero que ajude.

**Comment by sojan-official** [comment]
resolved in https://github.com/chatwoot/chatwoot/pull/6782

**Comment by gvargas9** [comment]
How to do it via API?   I have tried:
api/v1/accounts/8/conversations/9 end point 

with body 

{
    "custom_attributes": {
        "test": "1234"
    }
}

without success
