### ISSUE TITLE
bug: when a conversation exists - create a new one for same inbox generate a new conversation

### ISSUE THREAD

**Issue by silvaartur** [chatwoot/chatwoot#4214]
1. Currently into a conversation
2. Another user or the same user initiate a new conversation same inbox
3. Two conversation active for the same client and inbox
4. Only the first receive responses from the client

Expected behavior: not create a new conversation if exists for this client/inbox

**Comment by pranavrajs** [comment]
@silvaartur The issue is not clear, can you please share the details as per the issue template or a screencast which would help to understand the problem you are facing?

**Comment by silvaartur** [comment]
The problem was on my side. Sorry.
