### ISSUE TITLE
bug: update to 2.3.1 doen't enabled "record" button

### ISSUE THREAD

**Issue by silvaartur** [chatwoot/chatwoot#4215]
As expect and the behavior on new installation the record button doesn't show on conversation.

**Comment by pranavrajs** [comment]
@silvaartur Can you please share additional information here? Which inbox are you looking at? Can you please share a screencast?

**Comment by silvaartur** [comment]
Looking at API inbox. Into a new install I see this options (v2.3.0 not update to 2.3.1):

![Captura de Tela 2022-03-18 às 09 57 21](https://user-images.githubusercontent.com/12688324/159006894-178d1091-b37d-47ed-8bf1-6253b449f48d.png)

![Captura de Tela 2022-03-18 às 10 01 31](https://user-images.githubusercontent.com/12688324/159007459-d4b25552-fc15-4d26-a33b-565eac9d7723.png)

From a old one upgraded to v2.3.1 (API inbox type - same):

![Captura de Tela 2022-03-18 às 09 59 00](https://user-images.githubusercontent.com/12688324/159007089-d0767769-988e-41e3-8b63-dd320fc24638.png)

**Comment by sojan-official** [comment]
@silvaartur  if you are running a Linux installation. please try recompiling the assets. 
ref: https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

also, ensure that you have run yarn while updating to the newer version

**Comment by silvaartur** [comment]
Works @sojan-official. Tks.
