### ISSUE TITLE
Emails are sent using the signin email not the one set on the inbox.

### ISSUE THREAD

**Issue by mredbishop** [chatwoot/chatwoot#4218]
**Describe the bug**

When creating a new inbox for an SMTP account with an email alias e.g. **support@somecompany.com** where the sign in email is different e.g. **sign-in@somecompany.com** the email sender uses the sign in email not the one specified when creating the inbox.

**To Reproduce**

1. Create a new SMTP inbox.
2. Specify an email alias of the email address you are going to use.
3. Add the sign in details.
4. Send an email from this new inbox.

**Expected behavior**

The email "from" address should be the alias address but instead shows the sign in email as the from address.

**Environment**

Chatwoot self hosted installation on Docker
Chatwoot version v2.3.0

**Comment by sojan-official** [comment]
At the moment, the way email channels are built is in a way that it used the signing email as the sender email whenever SMTP is configured for an email inbox. maybe we should look into having a separate `FROM` address field for SMTP mailboxes?

cc: @aswindevps

**Comment by mredbishop** [comment]
Absolutely, this is what we would need as we have a number of aliased
domains in our organisation.
