### ISSUE TITLE
Add an internal name and external name for inboxes

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4228]
**Problem statement:**

Right now, the name field in the inbox is used for both internal and external use. This often creates a problem as the clients needs and internal name to identify the inbox and the brand name only to be visible to the customer.

A simple example is the Chatwoot dashboard inbox. The name given to the inbox is "Chatwoot InApp", the customer would receive and email with the name as "Pranav from Chatwoot InApp" which is not ideal.

**Todo:**

- Add a display name attribute to inboxes.
- Use the display name in the widget / public facing APIs / external emails.
- If display name is empty, use the name attribute as the fallback in all cases.

**Comment by sojan-official** [comment]
@pranavrajs should it be an attribute on the channel object instead, only for the channels which have a public-facing component.

**Comment by pranavrajs** [comment]
@sojan-official I thought about it but, it creates a broken experience with the customers as the display name becomes conditional. 

We have educate people that this is available only in website, email or API channels which oftens creates confusion. One instance from my experience speaking with customers is that they often confuse with the conversation continuity option. Every one expect it to be the flow in all channels.

**Comment by pranavrajs** [comment]
@sojan-official This name is not just used in email, the name would be used in the widget & survey forms also. I believe the requirement for disabling the sender is different from this one and cannot be combined. 

This approach might make it a little bit complex as we would need to one more attribute to store the name that needs to be displayed on the webwidget/surveys.

**Comment by gtmadev** [comment]
This also points to a usability issue within the chatwoot admin (for inboxes). For example, I might need to have 2-3 different website inboxes - one for in-app, one for the website, and one for the help site. I need them all showing the same brand. Thus, in the chatwoot admin, all of the inboxes have the same name and I have no idea which inbox this really represents (the app, the website, or the help/docs site). I can add conversation labels to help mitigate this, but ideal would be to see the inboxes with a label like "co name (in-app)", "co name (website)".. etc.

However, in each of those websites, the user always just sees "co name".

It seems like inbox name and then a separate public display name would be the best way to handle this.

**Comment by brundles** [comment]
I am not sure if my https://github.com/chatwoot/chatwoot/issues/5356 is a duplicate of this?

I 100% agree that we need a separation of the internal inbox name and the public displayname. A fallback as @pranavrajs suggests is of course even better.

**Comment by pranavrajs** [comment]
We will track this in #6309. If the sidebar name can be renamed, this issue will be solved.
