### ISSUE TITLE
bug: Formatting/rendering breaks when `code` is used in messages

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4249]
In our editor if we compose any formatting to add code as a reply and then sends it. The message bubble is rendering incorrectly.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/1277421/159620400-98553af8-5258-4c4d-beab-7a3e5a5e6d90.png">

**Comment by pranavrajs** [comment]
Closing this as this is fixed in the latest versions.
