### ISSUE TITLE
Conversations API returns wrong information about the sender of a message

### ISSUE THREAD

**Issue by fobos531** [chatwoot/chatwoot#4254]
**Describe the bug**

Hello, I noticed that the Conversations API (`https://app.chatwoot.com/api/v1/accounts/{account_id}/conversations/{conversation_id}/messages`) returns wrong information about the sender of a message. Namely, the `sender` field of a given message will **always** provide information about the contact (person who contacted the agent through the web widget), regardless of whether the message was sent by the contact or the agent. This is manifested in the Conversations API and subsequently in the web chat widget. So if I am the end user and I'm contacting an agent through the web widget, the agent's replies will have MY name at their chat bubble and not theirs.

**To Reproduce**

1. Initiate the conversation through a web chat widget.
2. Assign the conversation to an agent and reply to the conversation as that agent
3. Observe the agent's message in the web chat widget (from the end user's standpoint)
4. The agent's name and profile picture initials will be incorrect. It will list the name that YOU provided instead of the agents.

**Expected behavior**

When the agent sends a message my way, **their** name and initials should be used for their message bubble, and not mine.

**Screenshots**

N/A

**Browser logs**

N/A

**Server logs**

N/A

**Environment**

Self hosted installation - Heroku

**Desktop (please complete the following information):**
 All platforms and browsers.

**Smartphone (please complete the following information):**
 All platforms and browsers.

**Additional context**

Let me know if you need any additional information

**Comment by pranavrajs** [comment]
@fobos531 Can you please screencast? It seems like you are running a self-hosted Heroku. Have you changed any code on your end?

**Comment by fobos531** [comment]
@pranavrajs Hey, upon further investigation it seems my issue stems from the fact that I may be using the Create message in conversation API incorrectly.

I noticed that if I send a message as an agent through the agent dashboard, the initials and the agent name are indeed correct. 

However, I have a use case where I want to use the Chatwoot API directly to send messages on behalf of a given agent. The payload I'm sending when creating a new message in the conversation is fairly basic, i.e. 
```
 {
      content: "my message",
      message_type: 1,
    }
```

Which must mean that I'm missing something. Maybe in the way I authorize myself or something... Basically, I want to send a message as a specific agent, and  I created that agent using the Chatwoot dashboard. Could you point me in the right direction to achieve this?

**Comment by sojan-official** [comment]
@fobos531  try sending the message without the `message_type` parameter.

**Comment by fobos531** [comment]
> @fobos531 try sending the message without the `message_type` parameter.

Thank you @sojan-official ! That seems to work. Additionally, I figured out the name is inferred from the access_token that I use to authenticate with the API. After I started using the intended user's API token to authenticate myself, the sender's name is now that of the correct agent. Wohoo! I'm closing this, thank you for the help!
