### ISSUE TITLE
bug: Clipboard paste issue towards Firefox browser

### ISSUE THREAD

**Issue by iamsivin** [chatwoot/chatwoot#4255]
**Describe the bug**

The Firefox browser copy paste doesn't work as expected if we copy files or images from the finder or try to paste multiple files from the clipboard.

**To Reproduce**

1. Go to finder
2. Copy images or files from the finder
3. And open chatwoot app
4. And try to paste with if input filed has focus and also in a blur, both editors. (Rich and simple editors)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox and firefox dev edition
 - Version : 98+

**Comment by fayazara** [comment]
Tested cases

Firefox Mac OS (Simple editor and Rich text editor)

1. Single image file paste - Works
2. Multiple Image file paste - Does not work
3. Single PDF file paste - Does not work
4. Image + PDF - Does not work
5. Video paste Does not work
6. Video + Image - Does not work

Firefox Windows (Simple editor and Rich text editor)

1. Single image file paste -
   Works on Simple editor, but throws "132276 characters over" in Rich text editor
2. Multiple Image file paste - Does not work
3. Single PDF file paste - Does not work
4. Image + PDF - Does not work
5. Video paste Does not work
6. Video + Image - Does not work

**Comment by iamsivin** [comment]
Closing this issue as it's related to a specific browser.
