### ISSUE TITLE
(Hosting it in app.chatwoot.com) Always sends as mailer@chatwoot.com despite me adjusting SMTP settings

### ISSUE THREAD

**Issue by 23oijoifsd** [chatwoot/chatwoot#4263]
**Is your enhancement request related to a problem? Please describe.**
I am hosting chatwoot on app.chatwoot.com (your server). When I send mail through chatwoot, it always sends it as mailer@chatwoot.com despite me adjusting the SMTP settings. I know you can change the sender address when you are self hosting it, but hopefully this feature could be added in your server too, taht we have an option to change the from email address.

**Describe the solution you'd like**
Is there an option to change the from mailer address? Or rather, if there isn't a way is there like a quick fix you could do for us to change the sender email address so that we can send it as "this certain email address" when adjusting SMTP settings?

**Describe alternatives you've considered**
I've tried experimenting with the options in SMTP but none of it seems to change the sender address.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by sojan-official** [comment]
@23oijoifsd At the moment conversation continuity and account notification emails work using a generic chatwoot email on cloud accounts. But for email channels with `IMAP` and `SMTP` configured, the emails should be sent under the email address which you have configured. 

if that's not the case in your account, it should be a bug.  

cc: @aswindevps

**Comment by 23oijoifsd** [comment]
That's not the case for me, it only sends with mailer@chatwoot.com despite SMTP configured, I didn't configure IMAP though

**Comment by 23oijoifsd** [comment]
<img width="1129" alt="Screen Shot 2022-03-26 at 9 08 42 AM" src="https://user-images.githubusercontent.com/94162758/160218743-46fa848b-13f4-45ae-9bbb-934c805a7497.png">

**Comment by 23oijoifsd** [comment]
I also tried a different configuration with SMTP service smtp2go.com too with around the same configuration, but it still didn't work, here's a sample screenshot of the result.
<img width="1001" alt="Screen Shot 2022-03-26 at 9 16 13 AM" src="https://user-images.githubusercontent.com/94162758/160219039-f8adc387-94ee-4432-b715-273ecb3aeb3b.png">

**Comment by 23oijoifsd** [comment]
Update: Yay thank you it works when I add my IMAP configuration @sojan-official! Perhaps maybe the documentation could be a bit more specific that in order to send from a certain email address they need to setup IMAP and SMTP, since maybe some people won't configure IMAP since they will just set the email forwarding rule, and when they set up SMTP they will wonder why it sends as mailer@chatwoot.com

**Comment by sojan-official** [comment]
@23oijoifsd Thanks for the update
