### ISSUE TITLE
Webhook Events:  First message from client should send a 'conversation_opened' or 'conversation_status_changed' payload

### ISSUE THREAD

**Issue by Azfarrr** [chatwoot/chatwoot#4267]
As of now, when a new client send first message, as a new contact, it will only trigger the `message_created` event.

It is better if we can have another payload sent as per title, which is the `conversation_opened` or `conversation_status_changed`. I think this makes sense as if the conversation status is basically null or none at first, then it changed to open, a payload will be sent to webhook.

Or is there any other way to detect first message created in a conversation using the webhook?

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/3140

**Comment by sojan-official** [comment]
@Azfarrr  Thanks for the feedback, We will look into this or our upcoming sprints. 

At the moment the external system will have to keep track of the conversation id is to determine if it's a new one.

**Comment by pranavrajs** [comment]
@Azfarrr Along with the `message_created` event, a `conversation_created` event is triggered when a new conversation is created. 
https://www.chatwoot.com/docs/product/others/webhook-events#conversation_created

Let us know if it doesn't work. Please feel free to reopen if it doesn't solve your usecase.
