### ISSUE TITLE
Pre-built container images stops working 

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#427]
When using the above image the container stops working and outputs this to the log: Switch to inspect mode.

Reference #287

**Comment by sojan-official** [comment]
@SebastiaanKloos  could you help us with the steps you used to run the container?

**Comment by SebastiaanKloos** [comment]
I’ve just pulled the container in Plesk and ran it. I even tried it manually from the command line

**Comment by SebastiaanKloos** [comment]
I just installed it manually with the github repository by making my own docker image. Now it seems to work better. Now I see this: Cannot GET /

**Comment by sojan-official** [comment]
@SebastiaanKloos  did you set the environment variables as required ? 

https://www.chatwoot.com/docs/environment-variables

**Comment by SebastiaanKloos** [comment]
@sojan-official Yes I have! The env variables should be fine.

**Comment by SebastiaanKloos** [comment]
@sojan-official I just pulled the image and tried to run it

**Comment by aermike** [comment]
# docker-compose up
Building base
Step 1/35 : FROM ruby:2.6.5-alpine AS pre-builder
2.6.5-alpine: Pulling from library/ruby
e6b0cf9c0882: Pulling fs layer
39db6355b3f6: Pulling fs layer
e92d591b4e43: Pulling fs layer
150febec43bc: Waiting
f8893432dbd7: Waiting
ERROR: Service 'base' failed to build: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/15/1576e452985b7e88cf366882b58d00adcbcaf107bb0a281dcfb713acbbe33626/data?verify=1579017118-3DijBwF5cCz7fpjwV40X13MCAtM%3D: x509: certificate has expired or is not yet valid

**Comment by antodoms** [comment]
is this issue still happening?

**Comment by vishnu-narayanan** [comment]
@aermike  If this issue, still has not been resolved
1. Are you running this behind a proxy ?
2. Is your server time up to date ?

**Comment by aermike** [comment]
Issue has been resolvet after last update
Issue can be closed

**Comment by pranavrajs** [comment]
Closing this as it is complete.

**Comment by tjaoc** [comment]
I have the last image Docker and have the error Switch to inspect mode. I download today.

**Comment by qburst-vishnunarayanan** [comment]
@tjaoc Hello, Thank you for reaching out.

Could you share more details ?
1. Which platform are you running this ?
2. OS version ? Docker version ? Docker Comopse version ?
3. How have you tried to run the application ?
4. Could you share the complete log ?

**Comment by vishnu-narayanan** [comment]
@tjaoc Hello, Thank you for reaching out.

Could you share more details ?
1. Which platform are you running this ?
2. OS version ? Docker version ? Docker Comopse version ?
3. How have you tried to run the application ?
4. Could you share the complete log ?

**Comment by SebastiaanKloos** [comment]
> I have the last image Docker and have the error Switch to inspect mode. I download today.

Same issue.

I’m using docker with Plesk. The container logs show the same message.

Don’t use docker compose.

Just pulled the image and tried to run it.

**Comment by tjaoc** [comment]
> @tjaoc Hello, Thank you for reaching out.
> 
> Could you share more details ?
> 
> 1. Which platform are you running this ?
> 2. OS version ? Docker version ? Docker Comopse version ?
> 3. How have you tried to run the application ?
> 4. Could you share the complete log ?

@vishnu-narayanan 

1. DigitalOcean
2. Ubutnu 18.04, Docker 19.03.05, Docker Compose 1.22.0 build f46880fe
3. Yes i tried and the first run stop.
4. Only information in log is: Switch to inspect mode.

**Comment by SebastiaanKloos** [comment]
Check this out:
https://forums.docker.com/t/container-exiting-and-log-says-only-switch-to-inspect-mode/16431/2

**Comment by SebastiaanKloos** [comment]
You can fix this issue by running the container with -it option. 

For example:

`docker run -it chatwoot`

**Comment by sojan-official** [comment]
@SebastiaanKloos  @tjaoc apologies for not having this documented. 

chatwoot docker image at the moment has extra dependencies like redis, postgres etc and that's the reason why `docker run chatwoot/chatwoot` is failing when ran without these dependencies set up.  

we are working on making this process smoother and also adding some documentation on running chatwoot in production using docker.  Meanwhile, you can refer to the docker-compose file to see the required dependencies.

**Comment by SebastiaanKloos** [comment]
> I just installed it manually with the github repository by making my own docker image. Now it seems to work better. Now I see this: Cannot GET /

When doing it manually, I get the following error in the browser when navigating to the port

**Comment by sojan-official** [comment]
@SebastiaanKloos could you share the URL you are using to access the chatwoot service ?
 If you are trying this on your VM in the cloud, ensure the port is open to public via network settings.

**Comment by sojan-official** [comment]
Closing this since no recent updates on this ticket

**Comment by samzye** [comment]
Is this still not fixed, i just installed chatwoot image in plesk docker, and i get this. "Switch to inspect mode."

**Comment by hiagodotme** [comment]
I have the same problem = /

**Comment by Christilut** [comment]
Same problem here. Maybe one of my env vars is wrong or missing but I have no way to tell now.

**Comment by pranavrajs** [comment]
@hiagodotme @Christilut Can you please share logs?

**Comment by Christilut** [comment]
This is my docker-compose:
```
 postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: <pass>

  chatwoot:
    image: chatwoot/chatwoot:latest
    container_name: chatwoot
    environment:
      - DATABASE_URL=postgres://postgres:<pass>@postgres:5433/chatwoot
      - FRONTEND_URL=https://example.com
      - DEFAULT_LOCALE=en
      - REDIS_URL=redis://localhost
      - RAILS_ENV=production
      - SECRET_KEY_BASE=<secret>
    depends_on:
      - postgres
    restart: always
```

This is the only thing in the docker logs:
```
Switch to inspect mode.

Switch to inspect mode.

Switch to inspect mode.

Switch to inspect mode.

Switch to inspect mode.

Switch to inspect mode.
```

I can't `exec` into the container either because it's permanently restarting

**Comment by sojan-official** [comment]
we have updated docker deployment guides: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-docker . 
We will continue our work on documentation futher.
