### ISSUE TITLE
Need ability to customize Widget CSS

### ISSUE THREAD

**Issue by triptronics** [chatwoot/chatwoot#4274]
Hi there,

We need the ability to reposition the widget on our website and change other CSS such as color and etc. We attempted a possible solution here: https://github.com/chatwoot/chatwoot/issues/1598 but it didn't work - nothing was injected to the head tag for the iframe. The widget is covering our footer when the user scrolls down. 

Tawk allows us to customize the widget positioning, colors, text and etc. This is certainty a deal breaker for us and I'm sure for many others as well.

Thanks!

**Comment by sojan-official** [comment]
@triptronics  #1598 was a proposal. it is not implemented yet.

closing in favour of https://github.com/chatwoot/chatwoot/issues/1598#issuecomment-1078927481
let's track this over the original issue #1598
