### ISSUE TITLE
failed to load command: sidekiq

### ISSUE THREAD

**Issue by Austinstevesk** [chatwoot/chatwoot#4280]
I am trying to run the images I build from the provided Dockerfiles; worker and web images but I get an error **failed to load command: sidekiq**.

OS: Linux [Ubuntu]
Here are the Dockerfiles I used:

**Web Dockerfile:**

FROM chatwoot/chatwoot:latest
RUN chmod +x docker/entrypoints/rails.sh
RUN gem uninstall bundler
RUN gem install bundler -v 2.3.8
ENTRYPOINT ["docker/entrypoints/rails.sh"]
CMD bundle exec bundle exec rails s -b 0.0.0.0 -p 3000

Here is a screenshot of the error message:
![Screenshot from 2022-03-25 08-59-50](https://user-images.githubusercontent.com/45067454/160063490-351b2f0f-7b04-4141-b321-b40f25eb7674.png)

**Worker Dockerfile:**

FROM chatwoot/chatwoot:latest
RUN chmod +x docker/entrypoints/rails.sh
RUN gem uninstall bundler
RUN gem install bundler -v 2.3.8
ENTRYPOINT ["docker/entrypoints/rails.sh"]
CMD bundle exec sidekiq -C config/sidekiq.yml

Here is a screenshot of the error message
![Screenshot from 2022-03-25 08-58-50](https://user-images.githubusercontent.com/45067454/160063507-b418ddf2-6a8f-4064-8b2f-17b6a5600539.png)

**Reproducing the error:**
1. Build the docker images using the the Dockerfiles
2. Run a postgres image [I advice you use a server for this], you can try on your localhost though - Remember to note the username, host, password and database
3. Add a .env file from [https://github.com/chatwoot/chatwoot/.env-example] to the directory you are working with
4. Change the Postgres Configs/ hash them in the .env file. Switch connection to _DATABASE_URL=postgresql://[username]:[password]@[host]:[port]/[database]_
5. Run the docker images [Make sure you are in the directory where you have the .env file:
   Worker
    _sudo docker run --name [containername] --env-file=[.env] [worker-image-name]_
   
   Web 
   _sudo docker run --name [containername] --env-file=[.env] -p 3000:3000 [web-image-name]_

**Comment by Austinstevesk** [comment]
@vishnu-narayanan Yes, I was running both postgres and redis together. 

I'm not sure what's up with this since I managed to create the base image and the web + worker images out of it.

**Comment by sojan-official** [comment]
@Austinstevesk  have you made any customisations to the code ?

**Comment by Austinstevesk** [comment]
@sojan-official no, I just pulled it as it is. What I just did was create an image using the Dockefile provided, extended it to web and worker images but on running it I get the issues.

**Comment by vishnu-narayanan** [comment]
@Austinstevesk This is because your worker docker file has both `ENTRYPOINT` and `CMD` defined. Could you rebuild your worker image with this change and try again?


Worker Dockerfile:
```
FROM chatwoot/chatwoot:latest
RUN chmod +x docker/entrypoints/rails.sh
RUN gem uninstall bundler
RUN gem install bundler -v 2.3.8
#ENTRYPOINT ["docker/entrypoints/rails.sh"]
CMD bundle exec sidekiq -C config/sidekiq.yml
```

**Comment by Austinstevesk** [comment]
@vishnu-narayanan, perfect, this worked like a champ. Thank you.
