### ISSUE TITLE
Create Account Bug

### ISSUE THREAD

**Issue by sultanlive** [chatwoot/chatwoot#4284]
**Describe the bug**

From api create Account by /platform/api/v1/accounts/ - Self-Hosted

**To Reproduce**

**Expected behavior**

**Screenshots**

![Снимок экрана 2022-03-25 в 14 47 34](https://user-images.githubusercontent.com/47426878/160088334-9f49346d-275e-4b2a-9a2e-d6d51c911648.png)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sojan-official** [comment]
@sultanlive could you provide the following details
- the version of chatwoot you are using?
- is there any customizations done over the code?
- have you run all the migrations after updating chatwoot versions?

**Comment by sultanlive** [comment]
I updated to the latest version and everything worked.
