### ISSUE TITLE
chatwoot:ready event trigger twice

### ISSUE THREAD

**Issue by zawmn** [chatwoot/chatwoot#4286]
Hello 

I used window.$chatwoot.toggle(); in chatwoot:ready event to open chat windows on page load. 
It is working well with version v1.19.0.
But I upgraded my chatwoot version to v2.3.2 and it is no longer working. 
When I trace the code, chatwoot:ready event is trigger twice in new version and which result calling toggle function twice. 
With v1.19.0, chatwoot:ready event is trigger once on page load.

Below is my testing code:

I tested it in both chrome and firefox, both have same issue.
Now I change to window.$chatwoot.toggle('open');  and chat is open on page load.  But the chatwoot:ready event is still trigger twice. 

Thanks

```<html>
<body>
    <script>
      (function(d,t) {
        var BASE_URL="https://######################";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        g.defer = true;
        g.async = true;
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: '##########',
            baseUrl: BASE_URL
          })
        }
      })(document,"script");
	  window.addEventListener('chatwoot:ready', function () {
		  window.$chatwoot.toggle();
		  console.log(window.$chatwoot)
		});
	  
    </script>
	Hello
</body>
</html>

**Comment by pranavrajs** [comment]
@zawmn This is unexpected, I've added fix for the same.
