### ISSUE TITLE
feat: Widget Builder

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4287]
ref: https://github.com/chatwoot/product/issues/333 reported by @fayazara 

**Problem statement**: We see users and clients asking for custom widget changes, color customizations, height adjustments.

**Existing solution**: Only way to change this currently is writing code and make different templates

**Nature of the problem**: Nice to have

**Suggested solution**: We provide a widget builder and a preview section of how the widget looks in real time, giving user control of most of the styles of the widget. Which could look something like below mockup.

**Engineering considerations**: Save these styles, according to a pre defined css schema and load as soon as the chatwoot script is loaded. We could also save these as tailwind classes as widget is made tailwind css (Needs research, as we also use purge css)

**Design mocks**: ![widget-builder-idea](https://user-images.githubusercontent.com/15716057/156111714-6a497425-029f-48c5-a740-a2e2d923e649.png)

**List to tasks**:
1. Decide the elements we can allow to edit in this builder.
2. Frontend widget builder page.
3. Save these styles in backend.
4. Work on the widget to apply these styles.

**Comment by substr2837** [comment]
Can I work on this?

**Comment by sojan-official** [comment]
@substr2837 We don't have the full specs mapped out for this one. Will keep you posted once its updated

**Comment by prononext** [comment]
Just letting users inject their custom CSS would be the easy way to go first.
