### ISSUE TITLE
Unable to build base image in docker-compose.test.yaml

### ISSUE THREAD

**Issue by psschand16** [chatwoot/chatwoot#4290]
**Describe the bug**

Base Image build is failing in docker-compose.test.yaml
**To Reproduce**

build the base image in test docker file

cp docker-compose.test.yaml docker-compose.yaml
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
docker-compose up -d

**Expected behavior**

build should be successful.

**Screenshots**

**Server logs**
Step 16/40 : COPY package.json yarn.lock ./
 ---> 6b4725a55dbf
Step 17/40 : RUN yarn install
 ---> Running in 423323324dfe
yarn install v1.22.10

[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it
 from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding i
t from installation.
[4/5] Linking dependencies...
.
.
.
.
[5/5] Building fresh packages...
$ husky install
fatal: not a git repository (or any of the parent directories): .git
Done in 200.46s.
Removing intermediate container aa8683be670b
 ---> bbe1e5d1de02
Step 18/40 : COPY . /app
 ---> 5538dc17d3ab
.
.
.
.

ERROR: Service 'rails' failed to build : The command '/bin/sh -c if [ "$RAILS_ENV" = "produc
tion" ]; then   SECRET_KEY_BASE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle ex
ec rake assets:precompile   && rm -rf spec node_modules tmp/cache;   fi' returned a non-zero
 code: 1
Building base
[+] Building 17.3s (18/22)
 => [internal] load build definition from Dockerfile                                   1.2s
 => => transferring dockerfile: 32B                                                    0.1s
 => [internal] load .dockerignore                                                      0.8s
 => => transferring context: 35B                                                       0.0s
 => [internal] load metadata for docker.io/library/ruby:3.0.2-alpine                   0.0s
 => [internal] load build context                                                      1.2s
 => => transferring context: 291.31kB                                                  0.4s
 => [pre-builder  1/13] FROM docker.io/library/ruby:3.0.2-alpine                       0.0s
 => CACHED [stage-1 2/6] RUN apk add --update --no-cache     openssl     tzdata     p  0.0s
 => CACHED [stage-1 3/6] RUN if [ "production" != "production" ]; then   apk add node  0.1s
 => CACHED [pre-builder  2/13] RUN apk update   && apk add     openssl     tar     bu  0.0s
 => CACHED [pre-builder  3/13] WORKDIR /app                                            0.0s
 => CACHED [pre-builder  4/13] COPY Gemfile Gemfile.lock ./                            0.0s
 => CACHED [pre-builder  5/13] RUN apk add --no-cache musl ruby-full ruby-dev gcc mak  0.0s
 => CACHED [pre-builder  6/13] RUN bundle config set --local force_ruby_platform true  0.0s
 => CACHED [pre-builder  7/13] RUN if [ "production" = "production" ]; then   bundle   0.0s
 => CACHED [pre-builder  8/13] COPY package.json yarn.lock ./                          0.0s
 => CACHED [pre-builder  9/13] RUN yarn install                                        0.0s
 => [pre-builder 10/13] COPY . /app                                                    7.5s
 => [pre-builder 11/13] RUN mkdir -p /app/log                                          1.7s
 => ERROR [pre-builder 12/13] RUN if [ "production" = "production" ]; then   SECRET_K  4.7s

 [pre-builder 12/13] RUN if [ "production" = "production" ]; then   SECRET_KEY_BASE=precom
pile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   && rm -rf
spec node_modules tmp/cache;   fi:
18 4.673 bundler: failed to load command: rake (/gems/ruby/3.0.0/bin/rake)
18 4.674 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/definition.rb:481:in `materializ
e': Could not find rails-6.1.4.7, bootsnap-1.10.3, telephone_number-1.4.13, tzinfo-data-1.20
21.5, liquid-5.1.0, down-5.3.0, aws-sdk-s3-1.112.0, pg-1.3.2, redis-namespace-1.8.1, newreli
c_rpm-8.4.0, sentry-rails-5.1.0, sentry-ruby-5.1.0, sentry-sidekiq-5.1.0, geocoder-1.7.3, ac
tioncable-6.1.4.7, actionmailbox-6.1.4.7, actionmailer-6.1.4.7, actionpack-6.1.4.7, actionte
xt-6.1.4.7, actionview-6.1.4.7, activejob-6.1.4.7, activemodel-6.1.4.7, activerecord-6.1.4.7
, activestorage-6.1.4.7, activesupport-6.1.4.7, railties-6.1.4.7, aws-sdk-core-3.126.2, aws-
sdk-kms-1.54.0, bcrypt-3.1.16, sentry-ruby-core-5.1.0, concurrent-ruby-1.1.9, aws-partitions
-1.556.0, jmespath-1.6.0, google-cloud-env-1.5.0, signet-0.16.0, et-orbi-1.2.6, loofah-2.14.
0, grpc-1.43.1, unf_ext-0.0.8 in any of the sources (Bundler::GemNotFound)
18 4.674       from /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
18 4.674       from /usr/local/bundle/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (
required)>'
18 4.674       from /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:10
3:in `with_friendly_errors'
18 4.674       from /usr/local/bundle/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)
18 4.674       from /usr/local/bundle/bin/bundle:23:in `load'
18 4.674       from /usr/local/bundle/bin/bundle:23:in `<main>'

executor failed running [/bin/sh -c if [ "$RAILS_ENV" = "production" ]; then   SECRET_KEY_BA
SE=precompile_placeholder RAILS_LOG_TO_STDOUT=enabled bundle exec rake assets:precompile   &
& rm -rf spec node_modules tmp/cache;   fi]: exit code: 1
ERROR: Service 'base' failed to build : Build failed

**Environment**

docker on my windows 11 laptop

**Additional context**
I need build my own image of base to test the changes

**Comment by psschand16** [comment]
@pranavrajs @vishnu-narayanan please let me know your thoughts on this.

**Comment by sojan-official** [comment]
@psschand16  which version of Chatwoot are you using ? have you made any customizations to the code?

**Comment by psschand16** [comment]
@sojan-official Thankyou so much.
It works now after the fix from https://github.com/chatwoot/chatwoot/issues/1618.

But one question , is the docker image compatible with arm64

**Comment by sojan-official** [comment]
@psschand16  not at the moment. we are tracking this over https://github.com/chatwoot/chatwoot/issues/2575 
let's take the discussion forward over there if required.
