### ISSUE TITLE
[CW-2299] Display name and full name both are showing on widget

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4299]
**Describe the bug**

I've set Display name as **Sarah** and full name as test test ; considering the display name is Sarah, it should show Sarah everywhere on the widget - this seems like related to active agents where widget only shows the name of the active agent but when clicked on the widget, it switches to display name. 

**Expected behavior**

It should show the display name if it's set by user,  everywhere. 

**Recording**

https://user-images.githubusercontent.com/99071637/160279124-3541fb68-02cd-4202-869d-f869955822b3.mp4

OS : Windows 10
Browser : Chrome

<sub>[CW-2299](https://linear.app/chatwoot/issue/CW-2299/display-name-and-full-name-both-are-showing-on-widget)</sub>

**Comment by manovasanth-b** [comment]
Is it fixed ? 
or shall i take this and fix.

**Comment by ammaraslam** [comment]
> Is it fixed ? 
> or shall i take this and fix.

I doubt it was fixed, see if you're able to reproduce this.

cc : @sojan-official @pranavrajs

**Comment by LiamAshdown** [comment]
I cannot replicate this on develop branch.

Possibly fixed?

**Comment by sojan-official** [comment]
@LiamAshdown  Thanks for looking into this. I was able to replicate this in develop for campaigns
added a fix: #7631

**Comment by LiamAshdown** [comment]
> @LiamAshdown Thanks for looking into this. I was able to replicate this in develop for campaigns added a fix: #7631

Ahhhh! I see, I was looking at the conversation message instead of the campaign.

Nice one :)
