### ISSUE TITLE
Support custom message channels via REST APIs

### ISSUE THREAD

**Issue by alfredcogniwide** [chatwoot/chatwoot#430]
**Is your enhancement request related to a problem? Please describe.**
There should be an option to integrate the live chat to any custom channel using API integration.

**Describe the solution you'd like**
Provide an option to configure callback URLs. Also, provide documentation to initialize, chat and disconnect via API requests

**Comment by alfredcogniwide** [comment]
@sojan-official I'm ready to work on this feature. Can anybody give me a quick walkthrough of the source code or share any documentation?

**Comment by sojan-official** [comment]
@alfredcogniwide  sure. will do a loom video by this weekend.  The documentation is a little sparse and a work in progress.  But will try best to get to the queries asap. 

If you get the chance to go over the codebase and lets us know the questions.  we are also available on discord https://discord.gg/cJXdrwS if you need any immediate assistance.

**Comment by alfredcogniwide** [comment]
Ok

**Comment by sojan-official** [comment]
merged #1052  which covers this use case.
