### ISSUE TITLE
bug: Chatwoot does not show prechat form through campaigns

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4302]
**Describe the bug**

The pre chat form works when I start conversation from widget home. But when there's an active campaign and a bubble, and I start conversation by clicking the bubble, the prechat form does not show up.

**Comment by nithindavid** [comment]
@pranavrajs @muhsin-k @sojan-official Let me know your thoughts and if there's already an issue

**Comment by muhsin-k** [comment]
I just tested using cloud version and it is working fine

https://user-images.githubusercontent.com/12408980/160339030-112b4f27-a358-443d-b145-352eaa065275.mov

**Comment by sojan-official** [comment]
@nithindavid  can we get the details of whether self-hosted or cloud? as well the version if it self hosted?

**Comment by sojan-official** [comment]
duplicate: https://github.com/chatwoot/chatwoot/issues/3574
