### ISSUE TITLE
automate label

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#4307]
Automation is not working.
I am trying to assign a label for a specific content but it does not work.
I tryed also a simple rule but there is not effect.

![image](https://user-images.githubusercontent.com/62311149/160354428-0be47be1-615c-41b8-937f-4dde5e2313ad.png)

**Comment by pranavrajs** [comment]
@mattiamarras I see the condition has "message Type != incoming message", would this be the reason for it?

**Comment by sojan-official** [comment]
Closing this because of the lack of activity. Lets reopen if the issue persisits
