### ISSUE TITLE
Sidekiq error

### ISSUE THREAD

**Issue by Leocn** [chatwoot/chatwoot#431]
**Describe the bug**
I start this project local successfully through docker 
```
docker-compose run --rm --service-port rails
 docker-compose run --rm rails bundle exec sidekiq
```

**To Reproduce**
When i test 0.0.0.0/sidekiq, it redirects to 0.0.0.0/auth/sign_in, and shows 
`{"success":false,"error":{"Use POST /sign_in to sign in. Get is not supported"}}`
The same error happened 
https://queschainchatwoot.herokuapp.com/sidekiq

Did i miss sth?

**Comment by sojan-official** [comment]
The sidekiq url is 0.0.0.0/monitoring/sidekiq.
On production you need to set environment variables as mentioned in env.example to access 

SIDEKIQ_AUTH_USERNAME=
SIDEKIQ_AUTH_PASSWORD=

**Comment by Leocn** [comment]
> The sidekiq url is 0.0.0.0/monitoring/sidekiq.
> On production you need to set environment variables as mentioned in env.example to access
> 
> SIDEKIQ_AUTH_USERNAME=
> SIDEKIQ_AUTH_PASSWORD=

Its ok now.
The sidekiq url is 0.0.0.0/sidekiq.

**Comment by sojan-official** [comment]
@Leocn  thanks for the update. just for people referring to this in the future.  latest develop  has the above-mentioned changes where sidekiq url be at . 

`0.0.0.0/monitoring/sidekiq`

and production will need  the following env variables set to access sidekiq admin 

```
SIDEKIQ_AUTH_USERNAME=
SIDEKIQ_AUTH_PASSWORD=
```

this change will be there from v1.1.0

**Comment by sojan-official** [comment]
In the latest versions of chatwoot, sidekiq access was moved to our super admin area

In your rails console type the following to create a super admin
```
s = SuperAdmin.new(email: "admin@xyc.com", password: "yourpassword")
```
Access yourchatwoot.com/super_admin

authenticate and you can find sidekiq option on the sidebar

**Comment by crapthings** [comment]
s = SuperAdmin.new(email: "admin@xyc.com", password: "yourpassword")

(Object doesn't support #inspect)
