### ISSUE TITLE
Allow custom sort in conversations

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4312]
Right now, the conversations are sorted based on the last activity. The last active conversation would come at the top. 

This behavior often is a problem with customer service agents because the attention is by default going to the latest item, not the one which was created before. This results in a breach of SLA and poor experience with the support agents.

### Solution: 

- [x] #4800
- [x] Update the sort in the UI

**Comment by dmpanch** [comment]
It would be nice to add something similar to [Zammad SLA](https://admin-docs.zammad.org/en/latest/manage/slas.html).
Without SLA rules it's impossible to make a predictable support service.
