### ISSUE TITLE
[CW-1629] feat: Ability to customise the name of sender in emails sent from chatwoot

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4315]
Hi, i would like to hide the agent name in the sender of the emails, how can I do it?
I don't want that that customer see, for example, John from Corporate but only the name of the brand for all the agents.

Thanks.

M.

_Originally posted by @mattiamarras in https://github.com/chatwoot/chatwoot/discussions/4308_

<sub>[CW-1629](https://linear.app/chatwoot/issue/CW-1629/feat-ability-to-customise-the-name-of-sender-in-emails-sent-from)</sub>

**Comment by sojan-official** [comment]
All emails sent out by chatwoot are sent out as the email used in the smtp configuration.  
It would be much cleaner in terms of branding if the sender name would also be configurable next to the email-address.

This would make the emails received by our clients much more professional.

_Originally posted by @sdobbelaere in https://github.com/chatwoot/chatwoot/discussions/4340_

**Comment by MatthiasReinholz** [comment]
This may help to specify more closely what would be needed:

Many email providers with SMTP support offer auth which is not connected to the sender address.
You can use AWS SES, Gmail, Sendinblue... with one login but then specify and authenticate various sender email addresses that have nothing to do with your login email.

Currently, Chatwoot uses the SMTP login email as the sender address.
It would just be needed to allow the specification of sender email and sender name in the SMTP settings for each inbox.

**Comment by sojan-official** [comment]
@MatthiasReinholz In the recent versions of chatwoot, for the SMTP email channel, the email address used to create the inbox is used as from email address than the SMTP login email.  So you should be able to create multiple email inboxes which each of the required email addresses but with the same SMTP credentials.

**Comment by guiqis** [comment]
> @sojan-official is it possible to set a name as from, instead of using the email address?

Hi guys. Any changes on this? All my email channels are sending emails with the email address as sender name. Is it possible to change it?

**Comment by GuiVKDigital** [comment]
Hey everyone. I'm facing the same issue here: all my inboxes with IMAP and SMTP, are sending emails via SMTP correctly, but the sender's name is going as the sender's email. How can I set it up to go as the sender's name

**Comment by infiniziconsulting** [comment]
In my case, agent's display name is going as sender name. I dont want this, how can I fix it in the code?

Right now it is going like - Jason Walls From abc@gmail.com but I want only abc@gmail.com

**Comment by pranavrajs** [comment]
Closed as the feature is available in the latest versions. 
<img width="883" alt="Screenshot 2023-11-30 at 8 02 43 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/e265b3cd-8a8a-43f7-b1ce-178cf0dcd3d8">
