### ISSUE TITLE
feat:  HTML sanitizer component

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#4318]
**Problem**
There are many places we are using `v-html` to display HTML content, which may lead to **XSS** attacks. So we need to make sure that the HTML that's being rendered is sanitized and that it's safe to render in the browser.

**Solution**
- Create new component for displaying HTML content
- Pass element, content, class as props. Use `DomPurify` method to sanitize it.
- Whenever v-html has to be used, we will use the component instead.

**Comment by muhsin-k** [comment]
I am thinking of using [vue-dompurify-html](https://github.com/LeSuisse/vue-dompurify-html) for sanitizing the HTML content. It is a small wrapper around `DOMPurify`.

**Comment by muhsin-k** [comment]
@pranavrajs @nithindavid I am thinking of using [vue-dompurify-html](https://github.com/LeSuisse/vue-dompurify-html) for sanitizing the HTML content. It is a small wrapper around `DOMPurify`. Any thoughts?

**Comment by pranavrajs** [comment]
@muhsin-k Looks fine to me, please see if the dom purify versions match.
