### ISSUE TITLE
feat: Ability to Disable Chat widget with out deleting inbox

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4320]
**Describe the solution you'd like**
There should be an inbox disable option, suppose we do not want to take chat from this specfic inbox for a specific time (3 or 4 days), we would have to go with the inbox delete route or either removing code from the website to disable it. This feature can be beneficial for the larger audience.

Disable Inbox - No live chat widget on the website

**Comment by sojan-official** [comment]
ref: #https://github.com/chatwoot/chatwoot/issues/273

**Comment by pranavrajs** [comment]
We will track the progress over https://github.com/chatwoot/chatwoot/issues/5904
