### ISSUE TITLE
feat: Automatic widget color scheme as per the website theme

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4321]
**Describe the solution you'd like**
There should be an skinnable theme option for the chat widget to match the website theme, Inspiration can be taken from the Material You design language of Google. As of now, you have to select colours manually for the widget which are static until you change it.

**Describe alternatives you've considered**
None.

**Comment by sojan-official** [comment]
ref: #4287

**Comment by sojan-official** [comment]
@ammaraslam  thanks for the suggestion. This sounds like a pretty cool feature to have but might require significant engineering effort. We will keep it open for future releases.

**Comment by pranavrajs** [comment]
@ammaraslam Closing this as a part of routing issue cleanup. I don't think we will pick it up anytime soon and we are not interested in a community PR. Keeping this open doesn't makes. However, we have shipped a dark mode on the widget as you can see [here](https://www.chatwoot.com/hc/user-guide/articles/1677587636-how-to-enable-dark-mode-on-live_chat-widget).
