### ISSUE TITLE
Instagram handle CDN Url requirement

### ISSUE THREAD

**Issue by aldhielman** [chatwoot/chatwoot#4337]
Thank you for update that handle story mention, but on App review requirement on Facebook to get advanced access so my chatwoot can be production-ready I need to follow this [guide](https://developers.facebook.com/docs/messenger-platform/instagram/app-review). On section handle CDN Url, our apps are not permit to store data on local. instead only store link / url to content.
I've updated my bare-metal server chatwoot and already tested story mention and send attachment feature, but when i try to unsend (or delete story/attachment/media), attachment still stay in Conversation.

nb: I create new issue in order  to follow up my #3981 issue

Thank you

**Comment by sojan-official** [comment]
@aldhielman Thanks for the report. we will consider this for upcoming sprints.
