### ISSUE TITLE
add visual indicator when an integration is connected/active

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#4338]
**Is your enhancement request related to a problem? Please describe.**

Clear visual indication when an integration/application is connected/active.

Slack is fully connected and active at this stage. It would be nice to have a visual indicator on this page to know slack is connected without clicking on `configure` and navigating to another page.

![image](https://user-images.githubusercontent.com/3526167/160878377-4572e7a3-1538-41b6-a07b-3576b50f7100.png)

**Describe the solution you'd like**

a green checkmark ✅  or text that says enabled.  Or something similar to the DialogFlow integration page.

![image](https://user-images.githubusercontent.com/3526167/160879146-3ba4d7bd-487a-4d34-bc62-13c3d39de1c5.png)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sojan-official** [comment]
For integration pages at the moment, we have the indications inside the subpage of that integration.  

<img width="1601" alt="Screenshot 2022-03-30 at 9 45 57 PM" src="https://user-images.githubusercontent.com/73185/160882320-9295d1b7-6739-4d22-aba1-903b4754c5f5.png">


we should move both integrations and applications to one single tab with a similar indication as shown for Dialogflow

**Comment by Parthib314** [comment]
Hi,Is this issue still opened. I am new to open source and I would like to contribute on this issue?

**Comment by vishnu-narayanan** [comment]
@Parthib314 Sorry about the delayed response here. Please feel free to take this up.

cc: @sojan-official

**Comment by Narcos101** [comment]
Hi @vishnu-narayanan if this issue is still open. Please assign it to me!

**Comment by pranavrajs** [comment]
<img width="1182" alt="Screenshot 2023-11-30 at 9 36 11 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/b02232f4-b218-43b8-915f-b0d9d341bbe4">

Now it says enabled. Closing this here.
