### ISSUE TITLE
Add support for new automation actions

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4356]
**Missing Actions:**

- Send Message
- Send Attachment
- Send email to team

**Missing Conditions:**

- Add conditions based on contact and conversations for all the events

@tejaswinichile To provide a sample payload, Postman collection, description about attributes.
@fayazara to work on a custom component to implement the actions.

**Comment by tejaswinichile** [comment]
- [ ] new endpoint to upload_attachment
