### ISSUE TITLE
WhatsApp web integration 

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4361]
**Is your feature request related to a problem? Please describe.**
Hi, Would like to integrate chatwoot with whatsapp via Online Live Support

**Describe the solution you'd like**
Able to connect with users via whatsapp web (send and received whatsapp messages)

**Additional context**
API Docs: https://online-live-support.com/whatsapp-api-documentation/
User Guide: https://docs.online-live-support.com/

**Comment by pranavrajs** [comment]
@harismateen We only support official Business APIs with WhatsApp. APIs built on top of WhatsApp web are unofficial ones. If you need an integration with Chatwoot, please explore the API channel interface to build one. 

https://www.chatwoot.com/docs/product/channels/api/create-channel
