### ISSUE TITLE
Searchable Chat ID from all chats & contacts

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4400]
**Describe the solution you'd like**
I'm not sure if this already exists but there should be conversation ID with every chat generated visible in chat details and a 🔍 button with All chats so that someone can directly access that specific chat thought chat ID without trying to find it in resolved/open chats. 

**Problems it'd solve**
1. Straight forward way to find the required chats - one would only have to provide the chat ID and the other person can directly fetch it by clicking 🔍 button.

2. If necessary, we can add chat ID with transcript as well so that the person recieving transcript knows what this is all about, and can access that conversation on the app with the same Chat ID mentioned in that transcript. 

**Further Enhancement**
We can also add a filter :Search via Chat ID: in contacts where user will just put the same chat ID in a field and contacts from that chat will appear. 

Would love to hear thoughts of you guys on this.

**Comment by pranavrajs** [comment]
<img width="889" alt="Screenshot 2022-05-03 at 1 06 38 PM" src="https://user-images.githubusercontent.com/2246121/166418553-aa1f5496-da7a-44dc-9cb6-16fc348c408b.png">


Please feel free to reopen the issue if the filter is not usable in this case.

**Comment by ammaraslam** [comment]
@pranavrajs Thanks for replying. I explored the filter but I am not sure where to find the conversation ID? like I am not seeing it anywhere in Chat details.

**Comment by ammaraslam** [comment]
Seems related #3086
