### ISSUE TITLE
Grammatical mistakes in the "Enable channel greeting" field

### ISSUE THREAD

**Issue by iprithvitharun** [chatwoot/chatwoot#4408]
**Is your enhancement request related to a problem? Please describe.**
* Grammatical mistakes in the description. Subject pronoun **they** (plural) contradicts the verb **starts** (plural).

**Describe the solution you'd like**
Make the verb used (starts) singular.

**Additional context**
![Screenshot 2022-04-07 at 11 07 06 AM](https://user-images.githubusercontent.com/58725708/162128530-7293a7c4-3ce7-47a5-9c65-fd64cad699bf.png)

**Comment by sojan-official** [comment]
@iprithvitharun  thanks for reporting, we will take this up in upcoming releases
