### ISSUE TITLE
enhancement: Expanded reply box should not close when clicked outside

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4409]
While using the expanded reply box to compose a big message, The reply box will close if I accidentally click outside the reply box area or the backdrop. It's behaving similar to a modal now, would be better not to close it automatically.

@pranavrajs @sojan-official @fayazara Thoughts ?

**Comment by pranavrajs** [comment]
@nithindavid I'm not sure about the outside click, Stick box seems good to me, but I would prefer to keep the behaviour of closing it with an ESC button.

**Comment by fayazara** [comment]
Only close it via ESC or clicking on the close button?

**Comment by pranavrajs** [comment]
@fayazara I mean both, sorry I was not clear before.
