### ISSUE TITLE
Add helper text for custom fields in contact sidebars

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4411]
![image.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/ec4d7705-bf58-49fc-abd3-077155a91831/77f3c538-5de3-4872-a255-c049548c9673?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9lYzRkNzcwNS1iZjU4LTQ5ZmMtYWJkMy0wNzcxNTVhOTE4MzEvNzdmM2M1MzgtNWRlMy00ODcyLWEyNTUtYzA0OTU0OGM5NjczIiwiaWF0IjoxNzEzOTI2NDY5LCJleHAiOjMzMjg0NDg2NDY5fQ.bu6AKKiLpZT0B4svazcHnXM4oNTisHFNVb_jGSt9iqw)

**Comment by Vadorequest** [comment]
It looks great! 

If it can support Markdown, it'd be even better, as we could add links within the description. (assuming we could click on those), but that's a "nice to have" IMHO.
