### ISSUE TITLE
Quitar Powered by Chatwoot

### ISSUE THREAD

**Issue by mane06** [chatwoot/chatwoot#4417]
Hello, first of all I want to say that Chatwoot is a great software, and I would like to know if there is a way to remover Powered by Chatwoot del widgetincrustado con el sdk?

![IMG_20220407_214033](https://user-images.githubusercontent.com/50756282/162352450-794c2b45-616d-41cd-9a02-071d1859f18d.jpg)

**Comment by pranavrajs** [comment]
@mane06 You can edit the code to remove it. Closing this here as this is not an issue.
