### ISSUE TITLE
enhancement: persistent assign to me banner on conversation

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4418]
**The problem**

https://user-images.githubusercontent.com/1277421/162375496-a14c097e-cd22-41f9-ac7c-8ddb2c09a61f.mov

Also current logic is very primal and doesn't make much proactive appearance according to situations where it could be shown.

**Cases when the banner could be shown**

1. When conversation is unassigned
2. When conversation is assigned to another agent but no agent has sent any message
3. When conversation is assigned to another agent but all outgoing messages sent by you(current user)
4. When conversation is unassigned but you have sent an outgoing message along with other outgoing replies from other agents. 

@sojan-official @pranavrajs Let me know your thoughts

**Comment by pranavrajs** [comment]
Closing this here as we will not be picking this up due to the upcoming design changes in the product.
