### ISSUE TITLE
Page zooms in if we click on pre-chat form input

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4437]
<img width="411" alt="Screenshot 2022-04-11 at 11 39 48 AM" src="https://user-images.githubusercontent.com/2246121/162675287-82b3730a-602c-416c-b58f-3f8113b2f003.png">

> I've found a bug in the mobile version of the Website widget. When I try to fill Full Name or any other field it zooms in (all interface)
> Browser: chrome android

Context: https://app.chatwoot.com/app/accounts/1/conversations/14253

**Comment by pranavrajs** [comment]
@iamsivin Can you please test Safari on iPhone and Mac?

**Comment by iamsivin** [comment]
> @iamsivin Can you please test Safari on iPhone and Mac?

Tested with Chatwoot website. Not able to figure out this issue.
