### ISSUE TITLE
add ability to enable and disable official channels

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#4455]
**Is your feature request related to a problem? Please describe.**
Allow self-hosted users to enable/disable various channels. Facebook, Twitter and the likes have a lengthy approval process and it will be a much better user experience to enable channels once it is fully functional.

**Describe the solution you'd like**
Global setting to enable/disable certain channels viz Facebook, Twitter, Whatsapp and all. Either via environment variables or from the super-admin panel.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by sojan-official** [comment]
note: Disable Email channel forwarding method unless conversation continuity is configured.

**Comment by pranavrajs** [comment]
Closing this here for now. We will revisit this later.
