### ISSUE TITLE
Docker Security Issue – Public Redis Server

### ISSUE THREAD

**Issue by DavidSteinbauer** [chatwoot/chatwoot#446]
**Describe the bug**
I got a note from the German Institute of Cybersecurity who where scanning my server with Chatwoot on it:

> Redis is an open source in-memory database with a simple
> Key values ​​data structure, which is often associated with
> Web applications is used.
> 
> Is a Redis server openly accessible from the Internet and has been
> If no SASL authentication is configured, attackers can follow
> Read out, modify the data managed by Redis
> or delete. This may allow attackers to phase out
> sensitive information such as login details
> Web applications, customer data from online shops or others
> confidential content.
> 
> Affected systems in your network area:
> 
> Format: ASN | IP | Timestamp (UTC) | Redis version
> 24940 | xx.xxx.xx.xx | 2020-01-21 17:15:42 | 5.0.7
> 
> We would like to ask you to check the facts and take measures
> Protection of the Redis services on the affected systems
> take action or inform your customers accordingly.
> 
> If you have recently taken countermeasures and these
> Receive notification again, please note the specified
> Time stamp. If the countermeasure has been successfully implemented,
> 
> You don't get a timestamp notification after implementation
> received more.
> 
> For more information on this notification, notes on
> Correction of reported security problems and answers to common
> 
> You can find questions asked at:
> <Https://reports.cert-bund.de/>
> 
> This email is digitally signed using PGP.
> You can find information on the key used at:
> <Https://reports.cert-bund.de/digitale-signatur>
> 
> Please note:
> This is an automatically generated message. Answers to the
> Sender address <reports@reports.cert-bund.de> will NOT be read
> and automatically discarded. If you have any questions, please contact
> while maintaining the ticket number [CB-Report # ...] in the
> Subject line to <certbund@bsi.bund.de>.
> 
> !! Please read our HOWTOs and FAQ, which can be found below
> !! <https://reports.cert-bund.de/> are available.

**Comment by pranavrajs** [comment]
@DavidSteinbauer Could you please describe the deployment process you have followed?

**Comment by sony-mathew** [comment]
@DavidSteinbauer This issue has been resolved on priority and a hotfix has been merged with a new tagged release. You can find the new release here:  https://github.com/chatwoot/chatwoot/releases/tag/v1.0.3

The same fix has been merged to `develop` branch, if you are following the up-to-date changes.
With this hotfix, we now have an option to set a password to the `redis-server` which is run with docker-compose. We have also added options for authenticated redis connections from app and Sidekiq (service used for background job processing).

Thank you @DavidSteinbauer for bringing this up. 👍

**Comment by sony-mathew** [comment]
The documentation for the same has been updated here : 
https://www.chatwoot.com/docs/installation-guide-docker#development-environment

and here : 
https://www.chatwoot.com/docs/installation-guide-docker#development-environment
