### ISSUE TITLE
enhancement: Support embeddable URL for livechat widget in settings page

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4460]
Currently to embed chatwoot widget in a block or as an independent page we need to enable popout chat. [Sending Information into Chatwoot | Chatwoot](https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#enable-popout-window) And from the window that open up, We need to copy the url and use it within your frame. 

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/1277421/162993167-5eac16df-d8fc-4b2a-8718-d7672452502d.png">

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/4464

**Comment by pranavrajs** [comment]
Closing this as we will not be prioritizing this anytime soon.
