### ISSUE TITLE
Fetch old conversations when inside an IFrame

### ISSUE THREAD

**Issue by maartenvn** [chatwoot/chatwoot#4464]
**Is your feature request related to a problem? Please describe.**
My team is trying to embed the widget directly into our application without using the SDK using an IFrame.

However because of the line below the old conversations for the user with given `cw_conversation` token are not fetched.
https://github.com/chatwoot/chatwoot/blob/923b4637db3d255da9607b0b60206c23d4cee02c/app/javascript/widget/App.vue#L83

Is there a specific reason this fetch is not being executed on load?

**Describe the solution you'd like**
Execute the following line when inside an IFrame and also fetch 
https://github.com/chatwoot/chatwoot/blob/923b4637db3d255da9607b0b60206c23d4cee02c/app/javascript/widget/App.vue#L89

**Describe alternatives you've considered**
You can trigger the fetching of messages by sending a `config-set` event. However, sending this message adds an extra loading indicator to the widget causing some bad UX.

https://github.com/chatwoot/chatwoot/blob/923b4637db3d255da9607b0b60206c23d4cee02c/app/javascript/widget/App.vue#L230

**Comment by JWesorick** [comment]
@maartenvn Do you have an example of sending the `config-set` for the workaround?

**Comment by pranavrajs** [comment]
Closing this as we will not be prioritizing this anytime soon. The widget is intended to be used with the SDK, supporting any other implementation is not in the roadmap.
