### ISSUE TITLE
Incorrect query parameter in API documentation

### ISSUE THREAD

**Issue by hisunnymay** [chatwoot/chatwoot#4466]
**Describe the bug**

When I tried to use the query parameter`report_type` descibed in [Get Account reports summary(API)](https://www.chatwoot.com/developers/api/#operation/list-all-conversation-statistics), I got response: 
```
{
    "status": 500,
    "error": "Internal Server Error"
}
```
However, when I changed `report_type` to `type`, I got response:
```
{
    "conversations_count": 119,
    "incoming_messages_count": 0,
    "outgoing_messages_count": 334,
    "avg_first_response_time": 0,
    "avg_resolution_time": 0,
    "resolutions_count": 0,
    "previous": {
        "conversations_count": 119,
        "incoming_messages_count": 0,
        "outgoing_messages_count": 334,
        "avg_first_response_time": 0,
        "avg_resolution_time": 0,
        "resolutions_count": 0
    }
}
```
It seems that  [Get Account reports summary(API)](https://www.chatwoot.com/developers/api/#operation/list-all-conversation-statistics) needs to be corrected by changing  query parameter `report_type` to `type`

**Screenshots**

![image](https://user-images.githubusercontent.com/95261974/163091340-c4021592-b1c3-46aa-9b78-3d555cfb1659.png)

**Environment**

Chatwoot Cloud (app.chatwoot.com) 

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome

**Comment by vishnu-narayanan** [comment]
@hisunnymay Hey, thank you for reporting this. Would you like to raise a PR to fix this issue?

**Comment by shivamsinghchahar** [comment]
@vishnu-narayanan Can I take this up?

**Comment by hisunnymay** [comment]
> @hisunnymay Hey, thank you for reporting this. Would you like to raise a PR to fix this issue?

@vishnu-narayanan I tired to find the `QUERY PARAMETERS` defined in API documentation but it seems that there is no definition for `QUERY PARAMETERS` in [Summary API](https://github.com/chatwoot/chatwoot/blob/develop/swagger/paths/application/reports/summary.yml)

I am sorry but I don't know how to fix the issue because I don't know where I can fix it.

![image](https://user-images.githubusercontent.com/95261974/163670051-666dc49f-fdc3-4e7d-bb05-7aa38c37e3d2.png)

**Comment by shivamsinghchahar** [comment]
Raised a fix, please let me know if I'm missing something.

cc @vishnu-narayanan @sojan-official
