### ISSUE TITLE
Installing Chatwoot via Docker Compose

### ISSUE THREAD

**Issue by gulsenkeskin** [chatwoot/chatwoot#4467]
When I run `docker-compose up -d ` on https://www.chatwoot.com/docs/self-hosted/deployment/docker link I get a 302 response   
![image](https://user-images.githubusercontent.com/63197899/163111674-fbc64dd4-1567-4656-bf6a-c6bd474d9544.png)

When I paste the http://localhost:3000/installation/onboarding link into the browser, I get the response "This site cannot be reached. localhost refused to connect." What should I do?

**Comment by vishnu-narayanan** [comment]
@gulsenkeskin Welcome to Chatwoot. Please try to use the issue templates when creating issues. This helps us to understand and respond to your issue with better clarity.  Also, it would be best to avoid screenshots when sharing logs/errors and post them as text(This makes it searchable and improves readability for everyone involved).

**Comment by vishnu-narayanan** [comment]
> When I run docker-compose up -d on https://www.chatwoot.com/docs/self-hosted/deployment/docker[](https://user-images.githubusercontent.com/63197899/163111674-fbc64dd4-1567-4656-bf6a-c6bd474d9544.png) link I get a 302 response
> image
> 
> When I paste the http://localhost:3000/installation/onboarding link into the browser, I get the response "This site cannot be reached. localhost refused to connect." What should I do?

This information is not enough to debug.

1. Could you share the output of `docker ps` ?

**Comment by gulsenkeskin** [comment]
![image](https://user-images.githubusercontent.com/63197899/163169242-58151114-b81e-4422-a681-afebd0a976b3.png)
i had to send an image because copy paste didn't work

**Comment by gulsenkeskin** [comment]
I am trying to install on ubuntu server 20-04 in virtual machine

**Comment by gulsenkeskin** [comment]
Yes I am trying to access from the host machine. I will try. Thank you

**Comment by gulsenkeskin** [comment]
When I tried curl -I 127.0.0.1:3000/installation/onboarding I got 200 ok results. Maybe someone needs it.
