### ISSUE TITLE
Not getting messages from FB page

### ISSUE THREAD

**Issue by Rarora86** [chatwoot/chatwoot#4489]
**Messages are not coming into Chatwoot for one of the Facebook page**

We have around 9 FB pages synced with Chatwoot and suddenly on March 29, 2022, messages stopped coming from one our FB page 'Tier5' into Chatwoot. Page URL https://www.facebook.com/tier5development

I deleted that inbox and recreated it. Still the issue was there. 
As suggested by Pranav and Tejaswini, I checked the permissions and all were enabled. I then reauthorized the Tier5 page but still the messages the are not coming into Chatwoot. 
![image](https://user-images.githubusercontent.com/103764897/163591987-bc63223a-0fbd-44ce-810a-11a35787590e.png)

We are not using the self hosted installation hence there is no FB app created by us to integrate the FB pages. All the pages are connected directly from the 'Add Inbox' setup as we are on the Chatwoot cloud version.

After going on a call with Tejaswini, we have made Chatwoot the admin of our Tier5 FB page for further testing.
Here are few loom videos of the troubleshooting steps that we tried already:
March 29th: https://www.loom.com/share/7dc73257d98045b595ae20f11dea9551
April 5th: https://www.loom.com/share/864369edc8124dc78c33b60c78067501

Would appreciate if the team can look into this and resolve the issue on priority as it has already been two weeks.
Thanks

**Comment by tejaswinichile** [comment]
@Rarora86 

1. Can you make sure the Instagram account is not the owner of any of the other pages.
2. We are not able to get any events from Facebook for this particular page, can you verify since what is the difference between this page and other pages? Like as permission, ownership, and Instagram connectivity.

cc @sojan-official

**Comment by Rarora86** [comment]
> @Rarora86
> 
> 1. Can you make sure the Instagram account is not the owner of any of the other pages.
> 2. We are not able to get any events from Facebook for this particular page, can you verify since what is the difference between this page and other pages? Like as permission, ownership, and Instagram connectivity.
> 
> cc @sojan-official

@tejaswinichile This is a Facebook page and it is not connected with any Instagram account. 
![image](https://user-images.githubusercontent.com/103764897/163888709-d0ffa48f-8b2a-40a3-897b-4cc112860a53.png)

The permission for this 'Tier5' page is same as our other Facebook pages. As far as ownership is concerned, I am the 'Admin' for the Tier5 page and the 'Editor' for the rest of our pages.
![image](https://user-images.githubusercontent.com/103764897/163889104-d721f981-4e4a-42f6-a363-3cd1dc4cc235.png)

As per your request, I have removed the 'Tier5' inbox from our Chatwoot account so that you can test the same in your account.
Thanks

**Comment by tejaswinichile** [comment]
Notes:

Related errors: https://sentry.io/share/issue/ae7c2f45e6054ec38ba273209cd2b77b/
Cause: https://developers.facebook.com/docs/messenger-platform/handover-protocol/#exclusive-mode

**Comment by Rarora86** [comment]
Hi Team,
This issue got resolved in early May. We managed to get 'Chatfuel' disconnected from our FB account and that resolved the issue.
My apologies I could not update you all earlier. 
Thank you for all the help. I really appreciate it.
