### ISSUE TITLE
Chatwoot Production database uas unable to create

### ISSUE THREAD

**Issue by supriyapalaparthi98** [chatwoot/chatwoot#4491]
![image](https://user-images.githubusercontent.com/81329368/163689260-ae123d2b-c75d-4090-ba98-7fb0cbeca752.png)

I was trying to install chatwoot through docker using this link https://www.chatwoot.com/docs/self-hosted/deployment/dockerwhile installing I was getting this error

**Comment by sojan-official** [comment]
@supriyapalaparthi98  have you completed step 3 ? 
```
Tweak the .env and docker-compose.yaml according to your preferences. Refer to the available [environment variables](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables). You could also remove the dependant services like Postgres, Redis etc., in favor of managed services configured via environment variables.
```

You will need to have PostgreSQL and Redis installed in your server and the values need to be updated in `.env` file. I can see that the docs can be a little confusing, we will have it updated.

**Comment by sojan-official** [comment]
@vocuzi  thanks for the comment. 

Closing this issue since there haven't been recent reports. let's reopen in case the issue persists.

**Comment by vocuzi** [comment]
To replicate the issue try setting up chatwoot with docker compose on Ubuntu 20. Sorry forgot to mention this in the last comment itself.
