### ISSUE TITLE
Fix "similar-code" issue in app/javascript/src/store/modules/cannedResponse.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#45]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/store/modules/cannedResponse.js#issue_5d87480887cf19000100019c

**Comment by donquxiote** [comment]
I'll take this issue.

**Comment by pranavrajs** [comment]
@donquxiote Thanks, but please see the contributing guides.

https://github.com/chatwoot/chatwoot/blob/master/docs/contributing.md

**Comment by donquxiote** [comment]
I've had some IRL things come up so I can't guarantee I'll have time to work on this before the end of october. If some one else is looking for a hacktoberfest ticket, they should take it.
