### ISSUE TITLE
Toggle to hide the sidebar

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4501]
The toggle to hide the sidebar only appears when zoom is set on 125 or higher than that, but shouldn't it be there regardless of what the browser zoom is to achieve the cleaner look, as the sidebar doesn't concern agents - they only handle chats but the chat window is kinda small. 

https://user-images.githubusercontent.com/99071637/163845195-ed3cc2e7-5140-489a-b0d5-f02d8210639c.mp4

Gmail new UI is perfect example : 

https://user-images.githubusercontent.com/99071637/163845631-7119bf0e-2743-4666-a4af-944b39f477c3.mp4

**Comment by sojan-official** [comment]
@ammaraslam  Thanks for the feedback.  The team will keep it in mind for future design iterations.

**Comment by pranavrajs** [comment]
Closing as completed. 
<img width="663" alt="Screenshot 2023-01-19 at 9 32 10 PM" src="https://user-images.githubusercontent.com/2246121/213624460-6ef6397d-dba5-4a1f-8f8f-5ebd9ebcf2f0.png">
