### ISSUE TITLE
Automation Bug :  send message action was send without event trigger

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4504]
bug description 
we create rule base  chatbot with automation rules 

example if customer press 1 we will send -> hello
if he press 2 we send -> hi

 we create event message created and conditions = message type = incoming & message content = 1 or message content = ١ ( ١ =1 in arabic)

issue 1 : the issue is when customer start chat the send message is working fine but some times the send message action is sanded  to the customer without he pressing 1 or 2 or 3 so the customer receive the send message action multiple time from different rules at same time like rule 1 and 2   

issue 2 : when i assign the conversation to anther agent its also send message action to customer multiple times from different rules at same time like rule 1 and 2   

note : im sure about the automation are setup correctly with logical way also this issue its not happing with all customer its happen with some customers

**Comment by pranavrajs** [comment]
@voko3456 Would you be able to share some of the screenshots of such a conversation, it would be helpful to debug this faster.?

**Comment by voko3456** [comment]
![Screenshot_20220418-221413_WhatsAppBusiness](https://user-images.githubusercontent.com/20530550/163862810-546c57d0-f0f3-4a33-8278-e6943bf622d7.jpg)
@pranavrajs

**Comment by voko3456** [comment]
This live video for the issue : https://res.cloudinary.com/dxf8gs73d/video/upload/v1650324096/021722-720x1600_j7knbj.mp4

**Comment by pranavrajs** [comment]
Closing it here as the investigation steps are taken.
