### ISSUE TITLE
[CW-2376] Add signature for new email conversations

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#4506]
You added Rich text and Cc to new conversation and that's great!
Now it would be nice if we could also have signature for new email conversations.

<sub>[CW-2376](https://linear.app/chatwoot/issue/CW-2376/add-signature-for-new-email-conversations)</sub>

**Comment by pranavrajs** [comment]
@jean-philippeansel Thanks for the suggestion, we are working on a new UI for the message compose screen, will include this during that work.

**Comment by estherrath36** [comment]
+1 for this please

**Comment by pranavrajs** [comment]
@iamsivin Please fix the conflicts. @muhsin-k @scmmishra Can you please review this PR?

**Comment by iamsivin** [comment]
Fixed the conflicts

**Comment by pranavrajs** [comment]
@muhsin-k @scmmishra PTAL.

**Comment by scmmishra** [comment]
@scmmishra to review
