### ISSUE TITLE
no requests being made to webhook url configured in agent bot

### ISSUE THREAD

**Issue by udit-pandey** [chatwoot/chatwoot#4514]
I have created an agent bot and have attached it to an inbox. Messages from end user using chatwoot chat client are not coming to my bot server and therefore the end user is not getting any responses except from the once given by online agent. 

Response from list inbox api:
`{
            "id": <REMOVED PERSONALLY IDENTIFIABLE INFO>,
            "avatar_url": "",
            "channel_id": <REMOVED PERSONALLY IDENTIFIABLE INFO>,
            "name": "test",
            "channel_type": "Channel::WebWidget",
            "greeting_enabled": false,
            "greeting_message": "",
            "working_hours_enabled": false,
            "enable_email_collect": true,
            "csat_survey_enabled": true,
            "enable_auto_assignment": false,
            "out_of_office_message": null,
            "working_hours": [
                {
                    "day_of_week": 0,
                    "closed_all_day": true,
                    "open_hour": null,
                    "open_minutes": null,
                    "close_hour": null,
                    "close_minutes": null,
                    "open_all_day": false
                },
                {
                    "day_of_week": 1,
                    "closed_all_day": false,
                    "open_hour": 9,
                    "open_minutes": 0,
                    "close_hour": 17,
                    "close_minutes": 0,
                    "open_all_day": false
                },
                {
                    "day_of_week": 2,
                    "closed_all_day": false,
                    "open_hour": 9,
                    "open_minutes": 0,
                    "close_hour": 17,
                    "close_minutes": 0,
                    "open_all_day": false
                },
                {
                    "day_of_week": 3,
                    "closed_all_day": false,
                    "open_hour": 9,
                    "open_minutes": 0,
                    "close_hour": 17,
                    "close_minutes": 0,
                    "open_all_day": false
                },
                {
                    "day_of_week": 4,
                    "closed_all_day": false,
                    "open_hour": 9,
                    "open_minutes": 0,
                    "close_hour": 17,
                    "close_minutes": 0,
                    "open_all_day": false
                },
                {
                    "day_of_week": 5,
                    "closed_all_day": false,
                    "open_hour": 9,
                    "open_minutes": 0,
                    "close_hour": 17,
                    "close_minutes": 0,
                    "open_all_day": false
                },
                {
                    "day_of_week": 6,
                    "closed_all_day": true,
                    "open_hour": null,
                    "open_minutes": null,
                    "close_hour": null,
                    "close_minutes": null,
                    "open_all_day": false
                }
            ],
            "timezone": "UTC",
            "callback_webhook_url": null,
            "allow_messages_after_resolved": true,
            "widget_color": "#009CE0",
            "website_url": "https://www.test.com/",
            "hmac_mandatory": false,
            "welcome_title": "",
            "welcome_tagline": "",
            "web_widget_script": "\n    <script>\n      (function(d,t) {\n        var BASE_URL=\"https://app.chatwoot.com\";\n        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];\n        g.src=BASE_URL+\"/packs/js/sdk.js\";\n        g.defer = true;\n        g.async = true;\n        s.parentNode.insertBefore(g,s);\n        g.onload=function(){\n          window.chatwootSDK.run({\n            websiteToken: '<REMOVED PERSONALLY IDENTIFIABLE INFO>',\n            baseUrl: BASE_URL\n          })\n        }\n      })(document,\"script\");\n    </script>\n    ",
            "website_token": "<REMOVED PERSONALLY IDENTIFIABLE INFO>",
            "selected_feature_flags": [
                "attachments",
                "emoji_picker",
                "end_conversation"
            ],
            "reply_time": "in_a_few_minutes",
            "hmac_token": "<REMOVED PERSONALLY IDENTIFIABLE INFO>",
            "pre_chat_form_enabled": false,
            "pre_chat_form_options": {},
            "continuity_via_email": true,
            "phone_number": null
        }`

Response from list agent bots api:
`{
        "id": <REMOVED PERSONALLY IDENTIFIABLE INFO>,
        "name": "test",
        "description": "set to local",
        "outgoing_url": "http://0020-61-0-221-23.test.io/rasa",
        "account_id": <REMOVED PERSONALLY IDENTIFIABLE INFO>,
        "access_token": "<REMOVED PERSONALLY IDENTIFIABLE INFO>"
    }`

Have used the create integration hook api to attach agent to inbox.
Documentation that i referred: [rasa-agent-bot-demo](https://github.com/Chatwoot/rasa-agent-bot-demo).
Please point me in the right direction. Thanks.

**Comment by aksanoble** [comment]
Followed the same instructions. AgentBot doesn't call the outgoing_url. I don't see `outgoing_url` anywhere in the repo! Please help!

**Comment by aksanoble** [comment]
@udit-pandey I was facing the same issue. Are you using docker to run chat-woot? In which case you may have to bind ports or to call the endpoint on the host use `http://host.docker.internal:8000/rasa` also note that the endpoint should be `/rasa`

**Comment by udit-pandey** [comment]
I am currently using the SAAS version.
Also, when i hit their client APIs, it gives a 404 response. Dont know if its an issue in the way I am calling APIs or the API docs are'nt updated.

**Comment by aksanoble** [comment]
I checked with the team and they informed me that AgentBots are currently supported on the self-hosted version only. I've got it working on a self-hosted instance.

**Comment by udit-pandey** [comment]
great.

**Comment by udit-pandey** [comment]
Also, I have never seen big projects built using ruby (maybe because i dont have much industrial experience). Is it good to choose ruby over java, python to build products as large as this? Just want to get some opinions.

**Comment by sojan-official** [comment]
@udit-pandey the choice of language is a decision based on your team's expertise.  😃 But if you opt for ruby

<img width="1147" alt="Screenshot 2022-05-02 at 2 54 59 PM" src="https://user-images.githubusercontent.com/73185/166220240-6fae6510-5125-4db2-bc99-fc5950857799.png">

ref: https://rubyonrails.org/

**Comment by udit-pandey** [comment]
Nice. I think the stars have aligned finally and I'll be starting my journey in ruby soon :stuck_out_tongue_closed_eyes:. 
Thanks for all the answers. Will close the issue.
