### ISSUE TITLE
enhancement: Make conversation card selectable 

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#4522]
### Context
To bring in bulk actions for conversations list in chatwoot dashboard, we need to make the conversation card selectable. This would also need states for hovering the card.

**Current**
<img width="482" alt="image" src="https://user-images.githubusercontent.com/1277421/164382639-aa0d87e0-7c0a-4e97-8a4f-b0fc9e951a1d.png">

### New states for conversations card

**Default state**
Note: No changes from current design
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1277421/164383438-1a3e826a-a185-4e0c-8bbc-94442d062dcb.png">

**Hovered state**
When hovered the card would show a checkbox instead of the avatar
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1277421/164383553-0f31bf6b-e870-4e7c-a4f4-cc0e60ab35e4.png">

**Selected state**

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1277421/164383617-fd2a0080-44a6-4c8b-b53c-110bbde9f13d.png">

### Figma link to component 
https://www.figma.com/file/UGuR6jAQUnTm5IJxdENnGp/Design-system?node-id=17605%3A3206

**Deliverable**
Add the component entry in out storybook with the states

**Comment by nithindavid** [comment]
Need to finish #4523 before this

**Comment by pranavrajs** [comment]
Closing this as the change is completed.
