### ISSUE TITLE
bug: Have a setting to prevent IMAP fetching from being disabled when there is an error

### ISSUE THREAD

**Issue by jean-philippeansel** [chatwoot/chatwoot#4532]
Currently, thanks to  #4176 , when Chatwoot encounters an error while fetching IMAP, it automatically disables new email fetching.
But sometimes, IMAP servers can temporarily time out. For example, my IMAP server is on my Synology NAS, and around midnight, my NAS does a lot of backup tasks and my IMAP server times out. So every morning, I have to manually re-enable email fetching in Chatwoot.

So I think it would be great if we could have a setting to disable this behaviour if we are confident that our IMAP credentials are valid.

**Comment by sojan-official** [comment]
@jean-philippeansel Thanks for the feedback, We will have this prioritized for upcoming sprints based on the team's bandwidth.

**Comment by klipitkas** [comment]
Hello, we are experiencing the same issue using Google Suite (gmail). Sometimes it disconnects twice within a few minutes and we need to manually save the settings to re-enable it. Ideally we should be able to either set a timeout or number of email fetching attempts before considering the email inbox as disconnected.

**Comment by jgrau** [comment]
> Hello, we are experiencing the same issue using Google Suite (gmail). Sometimes it disconnects twice within a few minutes and we need to manually save the settings to re-enable it

We are experiencing the same thing with google suite on a fairly regular basis (once or twice a week).

**Comment by sojan-official** [comment]
Based on looking into this. The immediate changes which we can do 

- [ ] Increase the error threshold for email channels to a higher number of 15
- [ ] Reset the error threshold back to zero on successful fetches.
