### ISSUE TITLE
Upgrade wiped "Pre Chat Form" settings and won't now save options

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#4534]
**Describe the bug**

In trying to debug the other issue, I upgraded.

Now, the text we had set in the pre-chat form has been replaced with the default text and the "Visitors should provide their name and email address before starting the chat " option is now unchecked.

Even if we save/check that, it returns unchecked!

**Comment by iammattmartin** [comment]
Shows version: v2.4.1

**Comment by pranavrajs** [comment]
@iammattmartin Are you running develop branch? This feature is not released in 2.4.1

**Comment by iammattmartin** [comment]
It looks that way but that was originally what was deployed by your team :)

Safe to switch back to main?

**Comment by pranavrajs** [comment]
@muhsin-k Please advice.

**Comment by muhsin-k** [comment]
@iammattmartin We have added some changes in pre-chat form which is not released yet. Did you switch to develop branch to test out anything?

I just switched from develop to v2.4.1 and pre-chat form settings working as expected

https://user-images.githubusercontent.com/12408980/164725335-c7ef5b2f-e975-4aa9-b4f8-13e0e6513810.mov

**Comment by iammattmartin** [comment]
I've gone back to main.

The develop was the original branch checked out on the install from your team. It's not an issue but have reverted and all works now. Will leave on main.
