### ISSUE TITLE
$chatwoot.reset() t.t0.response is undefined

### ISSUE THREAD

**Issue by hploscar** [chatwoot/chatwoot#4536]
**Describe the bug**

when exec `window.$chatwoot.reset()`, this error appears in the js console.
![Captura de pantalla de 2022-04-22 11-26-32](https://user-images.githubusercontent.com/8766769/164755768-41aae634-5676-47d5-80e8-77ee7d859fca.png)

**To Reproduce**

1. run `window.$chatwoot.reset()` from js or browser console

**Expected behavior**

Chatwoot session should be refreshed without errors.

**Environment**

using self hosted installation of Chatwoot. Linux VM installation.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 97.0.1

**Additional context**

It seems similar to https://github.com/chatwoot/chatwoot/issues/2075

**Comment by hploscar** [comment]
more context:

this happens only if `window.$chatwoot.setUser()` has been executed previously

**Comment by pranavrajs** [comment]
@hploscar Thanks for reporting this, we will debug this further.

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/4702
