### ISSUE TITLE
Chat transcript history

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4538]
**Describe the solution you'd like**

History button with send transcript button to view what time transcript was sent on what email, why this is important? I've set the automation to send the transcripts but there's no way to know whether it was sent or not, however for that, I can check my email inbox.

But visitor on the website asked for a transcript and my team have sent it to him but there's no way to know whether it was received or not.

**Describe alternatives you've considered**
None

**Comment by ammaraslam** [comment]
Matches #4047

**Comment by sojan-official** [comment]
@ammaraslam  Thanks for the feedback. We will have this tracked over #4047
