### ISSUE TITLE
Remove agent from assigned converstion if they are removed from the account

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4555]
Bug: The agent is still assigned in a conversation even if they are removed from the account.

To reproduce: 

- Add an agent
- Assign a conversation
- Remove them from the conversation

Note: The agent cannot access the conversation as they don't have access to the account, hence it is not a security issue.

**Comment by shivamsinghchahar** [comment]
@pranavrajs Can I pick this up?

**Comment by sojan-official** [comment]
@shivamsinghchahar  please go ahead.
