### ISSUE TITLE
Emoji picker

### ISSUE THREAD

**Issue by startshineye** [chatwoot/chatwoot#4560]
I want to update the Following svg's   width and height. how can  I set it?

<img width="774" alt="image" src="https://user-images.githubusercontent.com/19678129/165341478-ad6d6365-7339-408c-b81f-6393b61977bf.png">

**Comment by pranavrajs** [comment]
The icon is rendered using the [FluentIcon](https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/shared/components/FluentIcon/Index.vue) component, it accepts size param. You can edit the code [here](https://github.com/chatwoot/chatwoot/blob/1bf2da180bc33074173063cbc813db3cd5fb62a1/app/javascript/widget/components/ChatAttachment.vue#L12).
