### ISSUE TITLE
Tweet Automations should be disabled due to Usage regulations

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4565]
Right now we have automation inbox condition to filter the inbox that we will send message action to it but we want to send message to twitter dm message not twitter tweets replies because twitter will suspend the app because sending replies on Twitter tweets replies mentions 

Automation actions should work with dm only

**Comment by pranavrajs** [comment]
Adding more context: 

> Thanks for that additional information. We can confirm that sending unsolicited @mentions is prohibited by our Automation Rules and the Twitter Rules on spam. We can only consider a request to reactivate your app after you agree to stop this behavior.
