### ISSUE TITLE
Telegram Messages not received

### ISSUE THREAD

**Issue by danielslyman** [chatwoot/chatwoot#4569]
Hello, first of al thank you for creating this amazing application!

I am running a self-hosted dockerized instance of Chatwoot on a public server.

Created Telegram bot (twice) as described in the docs, messages are not being received by Chatwoot instance.

Chatwoot via JavaScript integration runs smoothly, so Chatwoot "per se" is working.

Is there any other trick to get this running?

Basically the same issue as 

[https://github.com/chatwoot/chatwoot/issues/3813](https://github.com/chatwoot/chatwoot/issues/3813)

with exception of not being a run on a local machine. 

Thanks for any help!

**Comment by sojan-official** [comment]
could you follow the docs mentioned here to make sure that the webhook is properly registered?
https://www.chatwoot.com/docs/contributing-guide/telegram-channel-setup

you would need to make a call to the following URL to ensure that the telegram webhook registration is successful 

GET https://api.telegram.org/bot{your_bot_token}/getWebhookInfo

**Comment by danielslyman** [comment]
Thanks for your answer, am I correct in assuming, that I cannot integrate Telegram on a self-hosted version of Chatwoot without an ngrok server? The webhook works correctly. I am running quite a few docker services on that server instance so I'd rather not use ngrok, is there any workaround?

**Comment by danielslyman** [comment]
Okay, I managed to get it to work with Ngrok. May I suggest that you add to your documentation that "local machine" would actually include all forms of self-hosted solutions? Could you also explain how come the Heroku instance does not need to have this? I would love to learn.

**Comment by sojan-official** [comment]
@danielslyman  Thanks a lot for posting back the findings. Closing the original issue as it is resolved now.
