### ISSUE TITLE
Facebook messages not showing

### ISSUE THREAD

**Issue by MaoBueno** [chatwoot/chatwoot#4572]
Hello

I am trying to configure the facebook channel in chatwoot but the messages do not appear.
Created facebook app (Facebook developers) as described in docs, set environment variables FB_APP_ID, FB_APP_SECRET and FB_VERIFY_TOKEN. After the Facebook channel in chatwoot was created, but the Chatwoot instance is not receiving the messages.

The expectation is that a message will be sent through the Facebook page and displayed on chatwoot.
I am running an instance of chatwoot on heroku.
My current version of chatwoot is 2.4.1

Thanks for any help!

**Comment by rmundel** [comment]
Hey @MaoBueno 
How did you solve this issue?
