### ISSUE TITLE
Courier integration

### ISSUE THREAD

**Issue by Vadorequest** [chatwoot/chatwoot#4574]
**Is your feature request related to a problem? Please describe.**
Would it make sense for Chatwoot to integrate with [Courier](https://www.courier.com/)?
It manages so many channels, it could be a "one integration to rule them all".

https://www.courier.com/

[Discussion](https://discord.com/channels/647412545203994635/719548300868452362/968217058561122325)

**Comment by pranavrajs** [comment]
@Vadorequest How do you envision this integration? Is it for incoming messages, a channel like Facebook or Twitter or is it deliver the notifications?

**Comment by Vadorequest** [comment]
I don't know exactly, I simply found this, which seems to do something Chatwoot could use.

I guess, if Courier can be used to integrate faster with other providers (to lift some work Chatwoot woulnd't have to do) then it makes sense. But I'm not 100% sure, maybe it's rather a concurrent compared to Chatwoot?

I just wanted to bring some attention on it, since it might be useful.

**Comment by sojan-official** [comment]
@Vadorequest Thanks for creating the issue. Based on our research on Courier,  it seems like a solution to handle transactional notifications. It doesn't give APIs to handle the responses from these channels. So Chatwoot will have to work over the native APIs of these providers anyway.

**Comment by Vadorequest** [comment]
Okay, too bad. Thanks for following-up!
