### ISSUE TITLE
bug: Ghost Messages

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#4578]
**Describe the bug**

In the last two or three releases a nasty bug appears to have been introduced.

When someone starts a message, there are times when they then start another. We just assumed they were closing their browser and starting again. However, it showed both "people" online which wouldn't happen if they were different sessions as far as I can see.

We tried to replicate this yesterday and managed to do so. On a page refresh/reload, we were greeted with a new widget window asking for our name/message again.

The odd thing however, if we filled that in, we got a second message as expected, but if the staff replied to the very first message (and the widget was closed), the popup bubble would appear to that visitor (who had already started a second message and lost the previous/original content), for that conversation to appear.

It appears very random though so cannot be consistently replicated in our testing.

**Comment by pranavrajs** [comment]
@iammattmartin Do you have the "end conversation" button enabled on the widget, if so it would allow users to close the conversation?

**Comment by iammattmartin** [comment]
No, this is not enabled.

**Comment by pranavrajs** [comment]
@iammattmartin Since it is not reproducible as you mentioned, it would be good to have any additional information to debug this.

**Comment by iammattmartin** [comment]
https://cloud.custserv.net/f/6b6f1648cea642c5a1e8/?dl=1

Video showing the issue.

**Comment by pranavrajs** [comment]
@iammattmartin Can you please share if there was an error in the browser console?

**Comment by iammattmartin** [comment]
Nothing when the page is re-loaded and the chat vanishes.

But when the message is sent and the chat re-appears, I get this.
<img width="753" alt="Screenshot 2022-05-02 at 5 14 43 PM" src="https://user-images.githubusercontent.com/15971590/166268723-f9e813ed-e902-418b-afe6-982609a86d20.png">

**Comment by iammattmartin** [comment]
Is there any further debug we can do on this @pranavrajs ?

**Comment by sojan-official** [comment]
@iammattmartin The error displayed in the console should be harmless. it's not specific to this behavior.  
We will keep an eye on reports on our SaaS and update the thread with further findings.

**Comment by iammattmartin** [comment]
Thanks. Is there anyway we can try and debug the cause further? Simply because we're getting lots of duplicate messages and it is causing some level of frustration.

**Comment by iammattmartin** [comment]
Closing due to unrelated fix found from #4770.
