### ISSUE TITLE
feat: Support hours in Auto-resolve instead of days

### ISSUE THREAD

**Issue by urumat** [chatwoot/chatwoot#4590]
Is it possible to automatically close a conversation within hours instead of days?

**Comment by pranavrajs** [comment]
@matiasperes No it is supported, this can be added as an enhancement.

**Comment by matiasperes** [comment]
Thank you for your quick reply. Could you point me to the file where that is implemented?

**Comment by sojan-official** [comment]
@matiasperes  the attribute is available in the accounts model
ref: https://github.com/chatwoot/chatwoot/blob/11ea8a3032a7199c71308fbcc5d52056d73412a9/app/models/account.rb#L35

the logic is available over :

https://github.com/chatwoot/chatwoot/blob/develop/app/jobs/account/conversations_resolution_scheduler_job.rb
https://github.com/chatwoot/chatwoot/blob/develop/app/jobs/conversations/resolution_job.rb

**Comment by pranavrajs** [comment]
Closing this here. We will track the progress on https://github.com/chatwoot/chatwoot/issues/7363
