### ISSUE TITLE
Generate / Renew SSL automatically for a custom domain

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4595]
- Research on how to generate SSL automatically
- Can we use CertBot?
- Do we need to use a third-party provider like Cloudflare for Chatwoot Cloud?

**Comment by tejaswinichile** [comment]
Self-notes

Going forward with the below documents: 
1. Caddy https://caddy.community/t/https-for-dynamic-subdomains-and-custom-domains/7921
2. Cloudfare https://developers.cloudflare.com/dns/zone-setups/partial-setup/setup/

I will be testing both the setup on staging and will check which is easy for further setup when an actual client will use this.

**Comment by tejaswinichile** [comment]
Self-notes: 

1. We create CNAME records pointing to our domain server.
2. Find out about the SAN certificate the multidomain

**Comment by tejaswinichile** [comment]
According to Cloudfare for SaaS document https://developers.cloudflare.com/cloudflare-for-saas/start/

We can provide the SSL certificate under one host.

In our case host is `chatwoot.help` and the SaaS customer site is `customer.site` and we want to provide the portal information on `help.customer.site` domain.

Step 1: point CNAME record help.customer.site to chatwoot.help
Step 2: Add help.customer.site in custom hostname in Cloudflare dashboard https://dash.cloudflare.com/ 
Step 3: wait to activate hostname and certificate status


I am stuck at 520 cloudfare error which I am reaching out to it.

**Comment by tejaswinichile** [comment]
@pranavrajs @sojan-official 

This video is about, wow to serve custom-hostname from chatwoot.

https://www.loom.com/share/4b3d0c5018e34c7ea52da1e3b579c539


if you visit https://help.tejaswini.tech/hc/help-support.json it serves as the only portal record that they have with custom-domain "help.tejaswini.tech" and slug "help-support"

**Comment by tejaswinichile** [comment]
https://www.loom.com/share/c36a2925eebf40418e8ee61e1eb82f1b

Another test done for test.chatwoot.dev where this client DNS is on AWS and pointing to chatwoot.help

**Comment by pranavrajs** [comment]
@tejaswinichile Nice work. Please see if there are any limitations to the number of domains that can be added in Cloudflare and Heroku.

**Comment by tejaswinichile** [comment]
1. Heroku custom domain limitations: 1000 domains per app  
reference: https://devcenter.heroku.com/articles/limits#maximum-custom-domains-per-app

2. for Cloudflare at least 100 custom hostnames are allowed, as mentioned in one blog. The `Enterprise Plan`, is not mentioned anywhere but we will have to reach out to them for the same.

cc @pranavrajs

**Comment by pranavrajs** [comment]
@tejaswinichile Thanks, this is good enough for the initial stages.
