### ISSUE TITLE
Add APIs to list/edit/create/archive/destroy categories

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4597]
**Model**

- name
- description
- locale 
- position
- linked_category_id
- parent_category_id
- status - draft / published / archived
- slug

**Dashboard APIs:**

- [x] Create a category
- [x] Edit a category
- [x] Destroy a category
- [x] List all categories - Should support filter locale and pagination, order by position

**Comment by tejaswinichile** [comment]
Pending work: 

- Category self-association found one issue for many-to-many associations for the linked category 
- Parent-child category association and handling have been done.

**Comment by tejaswinichile** [comment]
@pranavrajs Assuming this should be the restrictions: 

1. Parent and child category should belong to the same portal
2. Linked categories should also belong to the same portal.
