### ISSUE TITLE
Is open source or not?

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#463]
**Is your feature request related to a problem? Please describe.**
When try to make an user appear 14days try.
Production version I cannot set
<img width="705" alt="Capture" src="https://user-images.githubusercontent.com/4247309/73658875-ceb50100-469d-11ea-9562-bee2bd90d15a.PNG">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pranavrajs** [comment]
@aermike This is completely opensource, you can host it on your own. Pardon me for not updating the text used in Signup page.

I've updated this in #464

**Comment by aermike** [comment]
Thank you
