### ISSUE TITLE
Show unattended conversations in Dashboard

### ISSUE THREAD

**Issue by aswindevps** [chatwoot/chatwoot#4643]
Frontend

- Add an unattended tab for conversations in the dashboard.
- Show unattended conversation count.
- Clicking on the Unattended tab should show the conversations.

The above changes should work with existing filters in the dashboard.

Depends on : 

- https://github.com/chatwoot/chatwoot/issues/4645
- https://github.com/chatwoot/chatwoot/issues/4707

**Comment by aswindevps** [comment]
@pranavrajs please update the issue description once the UX design is ready.

**Comment by pranavrajs** [comment]
Closing this as completed.
