### ISSUE TITLE
chatwoot opens a link to an attachment without a port in it.

### ISSUE THREAD

**Issue by beeyev** [chatwoot/chatwoot#4644]
I have chatwoot working using this address `http://localhost:3000/`
`FRONTEND_URL=http://localhost:3000/`
If I click a link to open an attachment:
![image](https://user-images.githubusercontent.com/326840/167291318-665e1e5e-c38d-4cf7-8179-35d00994a6b2.png)

chatwoot opens a link without `:3000` port in it, and as the result, it does not work.
![image](https://user-images.githubusercontent.com/326840/167291365-567e86a5-f499-474a-ab26-f87651bfb9ca.png)

Of course, if i manually add `:3000` port to the attachment link, it opens as expected.

**Comment by sojan-official** [comment]
let's track this together over https://github.com/chatwoot/chatwoot/issues/4278
