### ISSUE TITLE
[CW-2301] feat: Ability to send attachment in new conversation

### ISSUE THREAD

**Issue by angelolpa** [chatwoot/chatwoot#4646]
Hello how are you?

on the new conversation screen currently does not allow sending an attachment in an email conversation.

it would be very interesting already at the beginning of the email that you will send already send the attachment

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/f501ab07-501d-4565-9cef-9fe03666412b/f5b7ae5e-dbab-474c-97c7-b36dc1cb7514?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9mNTAxYWIwNy01MDFkLTQ1NjUtOWNlZi05ZmUwMzY2NjQxMmIvZjViN2FlNWUtZGJhYi00NzRjLTk3YzctYjM2ZGMxY2I3NTE0IiwiaWF0IjoxNjkwNDY2MTg2LCJleHAiOjE2OTA1NTI1ODZ9.PUx7gEOVdNw6aVISVFLY8mbidxWuQf_ANMwKeNR5MXA)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2301](https://linear.app/chatwoot/issue/CW-2301/feat-ability-to-send-attachment-in-new-conversation)</sub>

**Comment by Doodles2life** [comment]
I just created a github account just to suggest the same exact thing.  Many conversations in live chat need to be paused while customer support investigates a given subject. Often times the agent will need to send the customer a document once that research has completed.  Adding the given attachment to a new conversation would be ideal
![Snag_4ae34381](https://user-images.githubusercontent.com/105177137/167317974-2b507bc8-aeb8-43bb-80b4-c8f43cec719d.png)
.

**Comment by sojan-official** [comment]
@angelolpa @Doodles2life Thanks for the feedback. we are prioritizing this for upcoming releases.

**Comment by sojan-official** [comment]
ref: https://discord.com/channels/647412545203994635/654017096812068864/979338014994083841

**Comment by pranavrajs** [comment]
@scmmishra Please pair with @iamsivin to get this out.

**Comment by iamsivin** [comment]
Yeah

**Comment by pranavrajs** [comment]
@pranavrajs To test it.

**Comment by scmmishra** [comment]
@pranavrajs to review
