### ISSUE TITLE
Rasa Integration Url error :3000/widget_test 

### ISSUE THREAD

**Issue by Akshitkaushik** [chatwoot/chatwoot#4662]
Hi Chatwoot Team,

i want to integrate rasa chatbot to chatwoot. i follow your docs and youtube video and implement, At the end i run all services rasa and php and chatwoot services after i hit the url - localhost:3000/widget_test . i got the error pls help me 

NOTE ERROR:
                            The page you were looking for doesn't exist.
                            You may have mistyped the address or the page may have moved.
                            
                            If you are the application owner check the logs for more information.

**Comment by sojan-official** [comment]
the url should be `http://localhost:3000/widget_tests`

**Comment by jersonjunior** [comment]
> the url should be `http://localhost:3000/widget_tests`

The url works only in development?

**Comment by sojan-official** [comment]
@jersonjunior yes the URL is only accessible in development mode.

**Comment by jersonjunior** [comment]
Any plans to go into production? And the question of transferring to chatwoot, it would be very good for the community

**Comment by sojan-official** [comment]
@jersonjunior  the widget_test url is to debug development issues. in production, you can embed chatwidget on pages using the provided javascript.

https://www.chatwoot.com/docs/product/channels/live-chat/create-website-channel

**Comment by sojan-official** [comment]
closing the original issue since there hasn't been any further activity over the reported error
