### ISSUE TITLE
The close chat button on mobile doesn't work in firefox.

### ISSUE THREAD

**Issue by hiagodotme** [chatwoot/chatwoot#4669]
**Describe the bug**
The close chat button on mobile doesn't work in firefox.

**To Reproduce**

1. Create a web widget
2. Embed on your page.
3. Navigate to it using Firefox for Android.
4. Here is the error, it is impossible to close the conversation window.

**Expected behavior**

The close button should appear, just like in google chrome for android.

**Environment**

I'm using self hosted installation.

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 12
 - Browser: Mozilla Firefox
 - Version: 100.1.1

**Comment by pranavrajs** [comment]
@iamsivin Can you please check this out and see if can be reproduced?

**Comment by pranavrajs** [comment]
@hiagodotme Would you be able to share a screencast? It seems like the functionality is working as expected.

**Comment by hiagodotme** [comment]
@pranavrajs e @iamsivin i tried to reproduce but it worked, sorry for the alert. The boy sent a printscreen, he works remotely so he didn't have his equipment in hand to perform the test. If we can reproduce I reopen this issue, you can close! Sorry for the inconvenience.

![firefox-erro](https://user-images.githubusercontent.com/11755715/167915951-7e44d397-a029-46f8-8d88-92ef0bc5cc5a.png)

**Comment by hiagodotme** [comment]
@pranavrajs e @iamsivin i tried to reproduce but it worked, sorry for the alert. The boy sent a printscreen, he works remotely so he didn't have his equipment in hand to perform the test. If we can reproduce I reopen this issue, you can close! Sorry for the inconvenience.

![firefox-erro](https://user-images.githubusercontent.com/11755715/167915951-7e44d397-a029-46f8-8d88-92ef0bc5cc5a.png)

**Comment by pranavrajs** [comment]
@hiagodotme No worries, feel free to reopen if needed.
