### ISSUE TITLE
Couldn't configure outgoing mail server

### ISSUE THREAD

**Issue by a-varma-shopper** [chatwoot/chatwoot#4678]
**Describe the bug**

I've been trying to setup outgoing email server. I have tried both mailgun and SMTP methods, but both have not worked for me yet. I've attached my smtp conf below:
`MAILER_SENDER_EMAIL="MyCompany.com support@mycompany.com"
 SMTP_ADDRESS=smtp.gmail.com
 SMTP_USERNAME=xyz.mycomany@gmail.com
 SMTP_PASSWORD=eciiakoskohomhck
 SMTP_AUTHENTICATION=login
 SMTP_ENABLE_STARTTLS_AUTO=true
 SMTP_OPENSSL_VERIFY_MODE=peer
 SMTP_TLS=587
 SMTP_SSL=
`

I've also tried mailgun , here's the config below:

`SMTP_DOMAIN=support.mycompany.com ## verified on mailgun
SMTP_ADDRESS=smtp.eu.mailgun.org
SMTP_PORT=587
SMTP_USERNAME=support@support.mycompany.com
SMTP_PASSWORD=5874b9ce54d61bbab1d7c09dcefeda8c-100b5c8d-121sc78
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=peer
`

**To Reproduce**

- try the config above bar remove all default data, and add valid Passwords,
- add agent

**Expected behavior**
To receive verification email.

**Environment**

 selfhosted chatwoot server on an ubuntu 20LTS, created following [official documentation](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm).

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20 LTS]

**Comment by sojan-official** [comment]
@a-varma-shopper  could you access sidekiq and see if you have any error or dead jobs?
You can access sidekiq by going to installationurl/super_admin and clicking the sidekiq option in sidebar

**Comment by a-varma-shopper** [comment]
Thanks,
It worked, there was a dead job after all.
