### ISSUE TITLE
The links in the widget does not open a new tab

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4684]
![photo_2022-05-14 23 50 50](https://user-images.githubusercontent.com/2246121/168443860-f9b1efce-0515-4074-b9d4-f7dc78c52bf7.jpeg)

**Comment by CodeLeom** [comment]
@pranavrajs kindly close this issue, since it is now solved.

**Comment by sojan-official** [comment]
closed in https://github.com/chatwoot/chatwoot/pull/4685
