### ISSUE TITLE
Upgrading to 2.5 Aborted (core dumped)

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#4696]
Hi, in a local installation on Google Cloud Platform i have got this error short after giving this command: rake assets:precompile RAILS_ENV=production

7fc685ea5000-7fc685ea7000 r--p 00000000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685ea7000-7fc685eb8000 r-xp 00002000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685eb8000-7fc685ebe000 r--p 00013000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685ebe000-7fc685ebf000 ---p 00019000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685ebf000-7fc685ec0000 r--p 00019000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685ec0000-7fc685ec1000 rw-p 0001a000 08:01 9926                       /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
7fc685ec1000-7fc685ee3000 r--p 00000000 08:01 3453                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7fc685ee3000-7fc68605b000 r-xp 00022000 08:01 3453                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7fc68605b000-7fc6860a9000 r--p 0019a000 08:01 3453                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7fc6860a9000-7fc6860ad000 r--p 001e7000 08:01 3453                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7fc6860ad000-7fc6860af000 rw-p 001eb000 08:01 3453                       /usr/lib/x86_64-linux-gnu/libc-2.31.so
7fc6860af000-7fc6860b3000 rw-p 00000000 00:00 0 
7fc6860b3000-7fc6860b4000 r-xp 00000000 00:00 0 
7fc6860b4000-7fc6860b5000 r-xp 00000000 00:00 0 
7fc6860b5000-7fc6860bc000 r--s 00000000 08:01 3749                       /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7fc6860bc000-7fc6860ec000 r--p 00000000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc6860ec000-7fc68638e000 r-xp 00030000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc68638e000-7fc686493000 r--p 002d2000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc686493000-7fc686494000 ---p 003d7000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc686494000-7fc68649b000 r--p 003d7000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc68649b000-7fc68649e000 rw-p 003de000 08:01 2065455                    /usr/local/rvm/rubies/ruby-3.0.2/lib/libruby.so.3.0.2
7fc68649e000-7fc6864b1000 rw-p 00000000 00:00 0 
7fc6864b1000-7fc6864b2000 r--p 00000000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fc6864b2000-7fc6864d5000 r-xp 00001000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fc6864d5000-7fc6864dd000 r--p 00024000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fc6864dd000-7fc6864de000 r-xp 00000000 00:00 0 
7fc6864de000-7fc6864df000 r--p 0002c000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fc6864df000-7fc6864e0000 rw-p 0002d000 08:01 3449                       /usr/lib/x86_64-linux-gnu/ld-2.31.so
7fc6864e0000-7fc6864e1000 rw-p 00000000 00:00 0 
7fffdb6c5000-7fffdbec4000 rw-p 00000000 00:00 0                          [stack]
7fffdbf64000-7fffdbf68000 r--p 00000000 00:00 0                          [vvar]
7fffdbf68000-7fffdbf6a000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

Aborted (core dumped)

**Comment by pranavrajs** [comment]
@mattiamarras Can you please share the spec of your machine, how much RAM is available?

**Comment by mattiamarras** [comment]
Google Cloud Compute Engine n2-standard-4 has 4 cores and 16 memory

              total        used        free      shared  buff/cache
available
Mem:          16000         859        4888          39       10252
14801
Swap:             0           0           0

Something else to check?

Il giorno mar 17 mag 2022 alle ore 19:33 Pranav Raj S <
***@***.***> ha scritto:

**Comment by vishnu-narayanan** [comment]
Are you trying to upgrade your installation? Or Is this a fresh install?

**Comment by mattiamarras** [comment]
Hi, i am upgrading.

Il mer 18 mag 2022, 14:56 Vishnu Narayanan ***@***.***> ha
scritto:

**Comment by mattiamarras** [comment]
Hi, i'am trying again after stopping all services and it is going well but
i have some new problem sending emails that before was not shown.
Problem solved for this issue.

Il giorno mer 18 mag 2022 alle ore 17:56 Vishnu Narayanan <
***@***.***> ha scritto:

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4701
