### ISSUE TITLE
Fix "Rubocop/Metrics/ClassLength" issue in app/builders/messages/message_builder.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#47]
Class has too many lines. [118/100]

https://codeclimate.com/github/chatwoot/chatwoot/app/builders/messages/message_builder.rb#issue_5d87480b87cf190001000224

**Comment by jash-kothari** [comment]
Can i pick this up?

**Comment by pranavrajs** [comment]
Closing as it is completed.
