### ISSUE TITLE
Upgraded to 2.5

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#4701]
Hi, i upgraded to 2.5 and now when i respond to a message in a conversation a see this error:
![image](https://user-images.githubusercontent.com/62311149/169111310-bd6f5cb6-582f-4ef9-9bf6-6af3774e8959.png)

and if i search in the network chrome inspection tab i see a call failed to https://MYSITE/api/v1/accounts/1/conversations/928/messages
with this response
{"error":"PG::UndefinedColumn: ERROR:  column \"additional_attributes\" does not exist\nLINE 1: ...id\" = $1 AND \"messages\".\"message_type\" = $2 AND ((additional...\n                                                             ^\n"}

the message is delivered to the user but this error is very strange

Do you suggest to make a clean installation?
I am running Chatwoot in a dedicated machine on Google Cloud Platform.

M.

**Comment by sojan-official** [comment]
@mattiamarras  did you run the DB migrations? 
```
RAILS_ENV=production bundle exec rake db:migrate
```

**Comment by mattiamarras** [comment]
Yes

Il giorno mer 18 mag 2022 alle ore 20:05 Sojan Jose <
***@***.***> ha scritto:

**Comment by sojan-official** [comment]
@mattiamarras  the given error means that the following migration wasn't run
https://github.com/chatwoot/chatwoot/blob/develop/db/migrate/20220506163839_add_additional_attributes_to_message.r

```
{"error":"PG::UndefinedColumn: ERROR: column "additional_attributes" does not exist\nLINE 1: ...id" = $1 AND "messages"."message_type" = $2 AND ((additional...\n ^\n"}
```

-- 
please double-check running the migrations and see if its working properly.

**Comment by mattiamarras** [comment]
I made a fresh installation before reading your message, i will try for the
next upgrade.

Il giorno ven 20 mag 2022 alle ore 14:57 Sojan Jose <
***@***.***> ha scritto:

**Comment by sojan-official** [comment]
closing the issue for now. will reopen if it persists in future.

**Comment by egorky** [comment]
> @mattiamarras did you run the DB migrations?
> 
> ```
> RAILS_ENV=production bundle exec rake db:migrate
> ```

Hi! How do I run this command with the docker version? Thanks in advance.

**Comment by mattiamarras** [comment]
I am using Ubuntu not Docker.

M.

Il giorno dom 22 mag 2022 alle ore 00:17 egorky ***@***.***>
ha scritto:

**Comment by sojan-official** [comment]
@egorky ref:  https://www.chatwoot.com/docs/self-hosted/deployment/docker#running-rails-console

```
docker exec -it $(basename $(pwd))_rails_1 sh -c 'RAILS_ENV=production bundle exec rake db:migrate'
```

**Comment by egorky** [comment]
thanks, @sojan-official , that worked and now I don't have those errors either.
