### ISSUE TITLE
Contribution guidelines - missing permission for assigning issues

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#471]
**Describe the bug**
Contribution guidelines asks to assign issue before starting work to avoid conflicts. Normal users would be missing the assign permission on GitHub.

> Assign the corresponding issue to you whenever you start working on it. This helps in resolving collision (mutliple people working on the same item).

**To Reproduce**
1. Go to any issue
2. Try to assign an issue from a normal GitHub account

**Expected behavior**

**Screenshots**

**Additional context**
https://www.chatwoot.com/docs/contributing-guide#pull-request-guidelines

**Proposed solution**
Comment on a issue before starting work to call dibs on that. Maintainer can choose to assign issue to the developer.

**Comment by sojan-official** [comment]
@vishnu-narayanan  could you raise a PR to update the docs to reflect the change you suggested.  
the wording could be somewhere on the line `Comment on the issue that you are interested to work on. The maintainers will guide from there.`
