### ISSUE TITLE
bug: automation rules work on multiple accounts

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4717]
We received complain today account ID 19
He said that he have automation rules send message action was sanded with content not belong to his account ID

Then after I see his account I see that the content of send message action is belong to account ID 23 not 19

when i see the  automation in account ID 19 it's different from account ID 23 but the account ID 19 is sending messages belong to account 23

**Comment by pranavrajs** [comment]
@voko3456 This should be solved via https://github.com/chatwoot/chatwoot/pull/5768/files
