### ISSUE TITLE
Ability to assign team to inbox

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4718]
**Is your enhancement request related to a problem? Please describe.**
Nope. 

**Describe the solution you'd like**
Ability to assign teams to Inbox instead of single agent (having both options would also be great), It's easy to manage (add or remove) if a user has 100+ web inbox. 

I know it's possible to assign teams to inbox via automation but it's not feasible considering the amount of inboxes.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4718

**Comment by ammaraslam** [comment]
> closing in favor of https://github.com/chatwoot/chatwoot/issues/4718

Thankyou for replying, Sojan. Where can I track this considering this is #4718

**Comment by sojan-official** [comment]
@ammaraslam  wrong link. sorry : https://github.com/chatwoot/chatwoot/issues/2710
