### ISSUE TITLE
Auto-merging of contacts with different IDs shouldn't happen - Chatwoot mistakenly merges users

### ISSUE THREAD

**Issue by Vadorequest** [chatwoot/chatwoot#4728]
### **Is your enhancement request related to a problem? Please describe.**
Our users get overridden when we use "impersonate" our users, the conversation get attached to the most recently used user and so on. Here is a video that explains things with a bit more detail: https://watch.screencastify.com/v/HTnpujP9i1mAm6NKNtqm

It's a SaaS product, I have absolutely no control over how it behaves internally.
I cannot disable the widget when impersonating, because there is no way to differentiate impersonating from a normal user.
Also, the same happens when using the "direct auto-login link", basically when connecting to several users using the same browser sessions. 

### **Describe the solution you'd like**
Is it possible to enforce non-merging when the user ID is different? Could it become a new option?I don't see a simpler/better/easier way to achieve this than by comparing user ids.

I believe users with different IDs shouldn't be merged together.

### **Describe alternatives you've considered**
I cannot use `window.$chatwoot.reset()` during log out.

I understand the auto-merging behavior is necessary for merging contacts with no ID, but it shouldn't merge contacts with different IDs. I believe **not merging** should be the default behavior in such cases.

### **Additional context**
Reply from Sojan:
```
At the moment it is not possible to disable the merge.
- the reason why merge exist is that you might have an unidentified contact starting a conversation before signing up,
then they follow to finish signup and contact is identified, in this case, the merge makes the conversation into a single thread seamlessly.

- could you raise a GitHub issue for the same, we will look into adding an SDK setting to prevent merge if its an already identified contact

- in usual cases, users have reset window.$chatwoot.reset(); called on logout to prevent this case or in case of personalization they will have a conditional wrapping to ensure the setUser method is not called
```

**Comment by sojan-official** [comment]
@Vadorequest  thanks for creating the issue. We will have it prioritized.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/2811

**Comment by pranavrajs** [comment]
Proposed fix: If a session with another identified user is already available, the system should recreate the session and discard the previous history. It should not attempt to merge these contacts.

**Comment by Vadorequest** [comment]
Works for me, sound like exactly what I need :)

**Comment by RuiGuilherme** [comment]
> @RuiGuilherme contacts in chatwoot are shared across inboxes.  This lets us show conversations from various channels like WhatsApp, Email, etc under a single contact in chatwoot. 
> 
> In your case, you could try the following
> 
> - Instead of using the identifier,  use the customer email as the identifier in your setUser call. 
> - create separate website inboxes for each system. 
> - the customer will have separate chat sessions 
> - you agents will be able to see conversations from the same person across both systems under the same contact.
> - you could additionally use custom fields to add the user id information in both the systems to the contact if it's relevant for customer support.
> 
> _Originally posted by @sojan-official in https://github.com/chatwoot/chatwoot/issues/2811#issuecomment-1159146916_

It is not so simple to have two chatwoot instances for each of the systems.

it's inconvenient for the support team to have to be logged into two accounts (the team is the same for both cases), and will generating two separate reports which can complicate some things.

I can't use e-mail as identifier, for example: One client can have two accounts on different systems with the same email and one of his employees logged in. (This is part of our business rule)

In this scenario: two different people/employees with the same email, may end up seeing each other's messages. [See the video I left in my first comment.](https://github.com/chatwoot/chatwoot/issues/2811#issuecomment-1155612511)

And yes, I'm using different inboxes across the site.

The solution I adopted was to stop using the email features on one of the systems. And now I'm waiting for https://github.com/chatwoot/chatwoot/pull/4886

**Comment by Vadorequest** [comment]
I've tested the fix applied a few weeks ago. It works like a charm, I haven't noticed any issue so far. 👍 

Regarding @RuiGuilherme comment, I wonder if it is really related to this feature request, as I don't see any obvious link (was it posted in the wrong issue?)
