### ISSUE TITLE
question: How to Assign Agent Bot to inbox ?

### ISSUE THREAD

**Issue by guiqis** [chatwoot/chatwoot#4733]
Is it possible to assign an Agent Bot to an inbox via the API?

I've created the Bot using the Super admin console but I need to assign it to my inbox now so it can work (and I can't find a solution to do it).

I tried to create it using the rails console, but I receive the error:

```
[8] pry(main)> bot = AgentBot.create!(name: "Test Bot", outgoing_url: "http://localhost:8000")
ActiveRecord::NoDatabaseError: FATAL:  database "chatwoot_dev" does not exist

from /usr/local/rvm/gems/ruby-3.0.2/gems/activerecord-6.1.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:81:in `rescue in new_client'
Caused by PG::ConnectionBad: FATAL:  database "chatwoot_dev" does not exist

from /usr/local/rvm/gems/ruby-3.0.2/gems/pg-1.3.2/lib/pg/connection.rb:637:in `async_connect_or_reset'
```

How can I do it via the API (or any other screen)?

**Comment by sojan-official** [comment]
@guiqis  use this API https://www.chatwoot.com/developers/api/#operation/updateAgentBot 

------
when connecting to the rails console use the following command to connect to production database
```
RAILS_ENV=production bundle exec rails c
```

**Comment by guiqis** [comment]
@sojan-official thank you!! Solved all my issues. Just a last question. I'm using Dialogflow, but the bot name appears as 'Bot', not the name that I used when creating the bot (that is assigned to the inbox using Dialogflow).

Any ideas of how I can solve it?

**Comment by sojan-official** [comment]
@guiqis  it is not supported at the moment. I have added https://github.com/chatwoot/chatwoot/issues/4745 to track the same.
