### ISSUE TITLE
Pre-chat form overwrites the name of the contact

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4735]
**Context:**
https://github.com/chatwoot/chatwoot/pull/4421/files#r880180551

**To Reproduce:**
- Create a contact with an email address.
- Provide the same email in the pre-chat form and a different name.

**Comment by jhambach** [comment]
Is this issue related to not being able to change the pre-chat form? After we upgraded to the latest, we can't change the pre-chat form greeting or enable the option to require a name and email.

**Comment by pranavrajs** [comment]
@jhambach Can you please share a screencast for the same? I don't think it is related.

**Comment by jhambach** [comment]
https://share.snapcom.com/2Num1N8y

The pre-chat message and the email/name requirement checkbox settings don't save properly.

**Comment by sojan-official** [comment]
@jhambach  if you have upgraded to 2.5 the UI for the pre-chat form should be different. Please try recompiling assets 

https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

```
RAILS_ENV=production rake assets:clean assets:clobber assets:precompile
```
