### ISSUE TITLE
bug: Turbo + Stimulus issues.

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#4742]
ref: https://discord.com/channels/647412545203994635/647729773723779073/971483250470060102

> I am implementing Chatwoot on my site using hotwire, Turbo + Stimulus. The main point here is Turbo. Every time I navigate to another page the chat cannot load properly. It only loads fine the first time. What can I do? Thanks!

![unknown](https://user-images.githubusercontent.com/73185/170197258-e8c494e5-6bfb-4286-84e5-5ce2cde86a26.png)

> Hi, thanks for investigating
You can reproduce it as follows. Enter ment.cl. Now you can see that the chat loads correctly. Then click on any link, for example, "Empezar". The form to create an account should appear, but the chat disappears. This is where the error I just sent appears in the console.

notes: 

> Thank you! Essentially, what happens is that when a link is clicked, turbo replaces all the html in the body element with the one returned by the server, causing the chat to disappear as well. Turbo emits several events to control various aspects of the application. One of them is turbo:render, perhaps as a suggestion is that you could listen to this event and when it occurs re-embed the HTML elements of the chat. There are more turbo events that can help here. https://turbo.hotwired.dev/reference/events

**Comment by fayazara** [comment]
Ref - https://github.com/fayazara/hotwired-turbo-test

**Comment by brunoprietog** [comment]
[Here](https://github.com/brunoprietog/hotwire-chatwoot-bug) you can reproduce the bug. Only run `rails s` after `bundle install`. Thanks!

**Comment by sojan-official** [comment]
@fayazara  could you take a look?

**Comment by sojan-official** [comment]
ref : https://discord.com/channels/647412545203994635/996811932487122955/997442742252732418


```
hi, i investigating it a bit i found this problems and some solution:
Problems:
1) the script is creating a tag and add it to header without checking if there is existing one:
<script>
      (function(d,t) {
        var BASE_URL=“chatwootbase.url”;
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+“/packs/js/sdk.js”;
        g.defer = true;
        g.async = true;
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: ‘jo5QRDnq4tv4XGaKB7gzy9Rs’,
            baseUrl: BASE_URL
          })
        }
      })(document,“script”);
    </script>
d = document
t = ‘script’
g = ‘clean script tag on header’
s = “created script tag on header with sdk source”; 

this causes the problem of multiple sdk.js loaded ( every time a link is clicked a new line in the header is added  <script src:chatwootdSDKurl etc..></script>)

2) When we click link to go to page, turbo renders only body tag, not entire html page.
But when chatwoot loads firstly, it creates window.$chatwoot and window.chatwootSDK object.

3) On second click, page is not rendered entirely by Turbo. So, abvoe window objects has still been remained.
If you check Chatwoot's sdk js, you can realize that SDK doesn't create IFrame tag for chatwoot dialogbox, when window.$chatwoot is not null.
So this is the reason that not rendered on second click.

Temporary solution in our case:
1) Modified the script to check first if the tag script for chat wood already present.
2) To solve the frame laoding, we need to run statement window.$chatwoot = null before including chatwoot SDK. 
I hope this information is useful to you.

```

**Comment by narciero** [comment]
Any chance of getting this resolved in the SDK itself? Would be great to be able to use Chatwoot in a Rails app as Turbo is now the default setup. Thanks!
