### ISSUE TITLE
/api/v1/accounts/1/conversations Returning 500 resulting in Chatwoot not loading

### ISSUE THREAD

**Issue by kshitijkna** [chatwoot/chatwoot#4759]
**Describe the bug**

The main inbox (which is an API inbox) isn't loading and in the networks tab I can see 500 being returned in the "/api/v1/accounts/1/conversations" API

**To Reproduce**

Not sure how exactly to reproduce this as the app was working fine and suddenly it stopped working. One thing that I had done was create 4 agent bots in the account after which it started to break. Now I can't open any conversations or do anything in the account

**Expected behavior**

The inbox had 2 open conversations which should open up.

**Screenshots**

![Screenshot 2022-05-29 at 1 51 04 PM](https://user-images.githubusercontent.com/43352138/170858998-3b4d9d72-f9d2-43a8-8d6e-d37ea2c2c580.png)

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Not sure exactly where to look for the logs. Could you please help here as well? Thanks!

**Environment**

We are using a self-hosted version of Chatwoot. It's an AWS installation using EC2 (Ubuntu 20.04), RDS, and Elasticache.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 101.0.4951.64

**Additional context**

**Comment by pranavrajs** [comment]
@kshitijkna Can you please see if you can get the logs by logging into your EC2 instance and executing the following commands? https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#viewing-logs

**Comment by pranavrajs** [comment]
Closing this as the issue has been resolved via a call.
