### ISSUE TITLE
Facebook upgraded its API to v14

### ISSUE THREAD

**Issue by peejmio** [chatwoot/chatwoot#4762]
cannot downgrade to v13

![image](https://user-images.githubusercontent.com/29750198/170941561-39f81be6-b7aa-4dee-a2cc-681cc7d8ed90.png)
![image](https://user-images.githubusercontent.com/29750198/170941677-d57ed6f6-b56b-4633-b830-405473ed0ea7.png)
![image](https://user-images.githubusercontent.com/29750198/170941816-b9012486-51c6-450d-b10e-3424ccff0d7c.png)

**Comment by mattiamarras** [comment]
same problem, following

**Comment by grupale** [comment]
Hi there! Any news or workaround about this? I'm unable to integrate Facebook because of this. 2.5Version using docker

**Comment by mattiamarras** [comment]
> @grupale We are working on it, will push it ASAP, as we need to upgrade the out Facebook app version.

Hi, how can i update ma installation with this upgrade? There is a git command?

**Comment by grupale** [comment]
Hello, any update about this?
