### ISSUE TITLE
Contact model silently discards invalid attributes as of v2.5.0

### ISSUE THREAD

**Issue by jordan-brough** [chatwoot/chatwoot#4775]
In #4519 the Contact model was updated to silently ignore invalid phone numbers and email addresses, in order to address #4233.

I think this is surprising behavior at the model level, and unusual for a Rails app.  If I call `contact.update!(phone: 'invalid')` I expect to get an error if my change is invalid, rather than having my command to update be silently ignored.  i.e. when I tell the app to update a value, I don't want to have to always check every attribute afterward to confirm that it was actually updated, and wonder why it was ignored.

Instead of the change in #4519, could we instead possibly update just the API (controller) layer somehow, so that just the widget api has this behavior? (And even in that case it seems like it could be nice to return some extra data to indicate that some attributes were ignored)

**Comment by pranavrajs** [comment]
@jordan-brough The concern seems valid, @tejaswinichile / @sojan-official can you comment on this?
