### ISSUE TITLE
Favicon not changing on self hosted chatwoot

### ISSUE THREAD

**Issue by kshitijkna** [chatwoot/chatwoot#4782]
**Describe the bug**

The favicon for our self-hosted (hosted at https://cx.bitespeed.co) isn't changing even after changing the InstallationConfig's "LOGO_THUMBNAIL" parameter to "https://cdn.bitespeed.co/logo-lg.png". The favicon appearing on the tab is still the original Chatwoot favicon. We had also changed the "LOGO" variable and its change reflected perfectly fine.

**To Reproduce**

I logged into the production rails console using `RAILS_ENV=production bundle exec rails c` and followed the Brand Customization guideline to change the variables. I also restarted the Chatwoot service using `systemctl restart chatwoot.target`

**Expected behavior**

The favicon should have been changed to the icon at [this link](https://cdn.bitespeed.co/logo-lg.png)

**Screenshots**

![Screenshot 2022-06-02 at 4 36 18 PM](https://user-images.githubusercontent.com/43352138/171616349-d2c3d5e7-def9-4d43-a7aa-394fc101f933.png)

**Server logs**

`Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.266739 #81286]  INFO -- : RoomChannel#update_presence
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.792799 #81286]  INFO -- : source=rack-timeout id=a314ab64-7d57-4932-9dcc-9f29ffe20a75 timeout=15000ms state=ready
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.793332 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75] Started GET "/app/login" for 103.199.200.47 at 2022-06-02 11:20:20 +0000
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.795036 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75] Processing by DashboardController#index as HTML
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.795087 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75]   Parameters: {"params"=>"login"}
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.809226 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.0ms | Allocations: 4)
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.810497 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75]   Rendered layout layouts/vueapp.html.erb (Duration: 1.3ms | Allocations: 1506)
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.810758 #81286]  INFO -- : [a314ab64-7d57-4932-9dcc-9f29ffe20a75] Completed 200 OK in 16ms (Views: 1.7ms | ActiveRecord: 0.0ms | Allocations: 3615)
Jun 02 11:20:20 ip-10-0-2-21 chatwoot-web.1[81286]: I, [2022-06-02T11:20:20.811197 #81286]  INFO -- : source=rack-timeout id=a314ab64-7d57-4932-9dcc-9f29ffe20a75 timeout=15000ms service=18ms state=completed`

**Environment**

We are using a self-hosted version of Chatwoot. It's an AWS installation using EC2 (Ubuntu 20.04), RDS, and Elasticache.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 101.0.4951.64

**Comment by tejaswinichile** [comment]
Hey @kshitijkna I got your issue.
Instead of considering `LOGO_THUMBNAIL`, it's considering the `android-icon-192x192.png` in the original icon's meta header. Can you verify that DISPLAY_MANIFEST is set to false in your configuration?
