### ISSUE TITLE
feat: Export contacts from the dashboard

### ISSUE THREAD

**Issue by MaoBueno** [chatwoot/chatwoot#4788]
**Is your feature request related to a problem? Please describe.**
I want to export the contacts from the chatwoot dashboard

**Describe the solution you'd like**
I would like to be able to export all the contacts or the result of a contact filter from the dashboard in cvs format

**Describe alternatives you've considered**
I have thought that through the API to obtain the list of contacts and export them to a file with csv format but this is not very practical

**Additional context**
Instance on heroku

Thank you so much!

**Comment by sojan-official** [comment]
Thanks for the feedback, We will keep this in our backlog for prioritization.
We will share further updates when the team starts working on this.
