### ISSUE TITLE
Chatwoot (docker) problem with Dialogflow

### ISSUE THREAD

**Issue by eltodi** [chatwoot/chatwoot#4797]
Hi there,
Since I have the latest update, chatwoot only shows the first text response.
I've got a self hosted chatwoot server.
If I try my dialogflow on chatwoot cloud, it's run without problem, but the same config on docker, only show the first text response.
Example:

- TEXT RESPONSE 1
    -  Alternative 1
    - Alternative 2
    - Alternative 3
- TEXT RESPONSE 2
    - Alternative 1
    - ... ..
    -
In docker, only return text response 1. It never continues to the next (Text response 2)
Any ideas ?

Thanks,

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4721
