### ISSUE TITLE
Allow custom sort options for conversations in the API

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4800]
Support the following sort options in conversation API and filter APIs.

- **created_at**: Sort conversations based on created time. Allows agents to prioritize long-running conversations.
- **last_user_message_at**: Sort based on the last incoming message. Along with the unattended filter, this sort option allows agents to look at conversations where users are waiting for a long time.
- **last_activity_at**: Sort based on the last activity. This is the default sort right now.

**Comment by tejaswinichile** [comment]
@pranavrajs 

Few doubts:
1. These sort-options, will it be applicable in the mentioned conversations too?
2. Will it be applicable over conversation filters?
3. last_user_message_at filter ideally should work only on open status conversations, for other filters, it doesn't make sense, correct?

**Comment by pranavrajs** [comment]
@tejaswinichile As discussed over the call. 

> These sort-options, will it be applicable in the mentioned conversations too? Will it be applicable over conversation filters?

Yes, it is available in both conversation finder service and filter service.

> last_user_message_at filter ideally should work only on open status conversations, for other filters, it doesn't make sense, correct?

It is useful in open and snoozed cases, but I think we shouldn't restrict it in the API. If needed, we can hide that option for the resolved status.

No new APIs are added here, updates to existing API params are only done.
