### ISSUE TITLE
List all articles that are linked to the current article

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4803]
Add a param in the article - associated_article_id.

- List all the articles which are associated with the current articles.
- Create an association for the article 

Case: I'm associate es with fr.
- If fr has an associated article, put associated article id directly to es.
- If fr associated_article is nil, put fr id as associated_id for es.

```
Instead of en -> fr -> es

Save as
en -> fr
en -> es
```

**Comment by tejaswinichile** [comment]
[ ] Add the authorization for article 
[ ] Add authorization for category
