### ISSUE TITLE
Show HMAC and enforcement for identity validation for API inbox

### ISSUE THREAD

**Issue by SimonHausdorf** [chatwoot/chatwoot#4804]
**Is your enhancement request related to a problem? Please describe.**
In certain cases it can be important to know if the user is identified via HMAC token to provide required support. As example if the user has a problem with his user account on the platform the agent can make sure that the user is really the owner of the account in question.

**Describe the solution you'd like**
Same as for the website widget, add the option to see the HMAC token and the function to enforce identity validation.

I also would like to reference to the Identity verification badge which could maybe be part of this request. #1682

**Comment by sojan-official** [comment]
@SimonHausdorf  Thanks for the feedback, We will keep it in our backlog for prioritization.
We will share further updates once the team starts working on this.
