### ISSUE TITLE
Random identifier_hash identifies user as verified identity

### ISSUE THREAD

**Issue by SimonHausdorf** [chatwoot/chatwoot#4805]
**Describe the bug**

When providing a random `identifier_hash`, the warning icon, that the user is not identified isn't show. When not providing the `identifier_hash`, then the warning is shown.

**To Reproduce**

This user will show as verified (not verified badge is not visible)
```javascript
    window.$chatwoot.setUser("testUser", {
        name: "testUser",
        identifier_hash: "testUser",
    });
```

**Expected behavior**

2 possible options:
1. To avoid confusion with other inboxes a badge should only be shown if the identity is verified and not if the identity is not verified
2. By default conversations of all inboxes should show the user as not verified except if the hmac hash is valid. Telling an agent that only certain inboxes have a `not verified badge` causes confusion.

**Aditional context**

Referencing: https://github.com/chatwoot/chatwoot/issues/1682#issuecomment-1148381392

**Comment by pranavrajs** [comment]
@SimonHausdorf The HMAC validation will if an invalid identifier_hash is provided. Please free to reopen the issue with more information if it is not the case.

<img width="520" alt="Screenshot 2022-07-05 at 5 44 45 PM" src="https://user-images.githubusercontent.com/2246121/177311161-0be7b242-9b9b-4d32-87e6-000248797df8.png">
