### ISSUE TITLE
Development environment  - Docker

### ISSUE THREAD

**Issue by jersonjunior** [chatwoot/chatwoot#4823]
After run docker-compose build

=> ERROR [chatwoot-webpack:development internal] load metadata for docker.io/library/chatwoot:development                                                                                                0.6s
 => CANCELED [chatwoot:development internal] load metadata for docker.io/library/ruby:3.0.4-alpine                                                                                                        0.6s
 => CANCELED [chatwoot:development internal] load metadata for docker.io/library/ruby:3.0.0-alpine                                                                                                        0.6s
 > [chatwoot-webpack:development internal] load metadata for docker.io/library/chatwoot:development:
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by sojan-official** [comment]
@jersonjunior could you link the doc that you are following? 


ref: https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker

**Comment by jersonjunior** [comment]
> @jersonjunior could you link the doc that you are following?
> 
> ref: https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker

I'm using the link you mentioned!

**Comment by vishnu-narayanan** [comment]
@jersonjunior Please use the [issue template](https://github.com/chatwoot/chatwoot/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) when creating/reporting issues.

Could you share the output of `docker version`, `docker info` and `docker-compose --version`?

**Comment by jersonjunior** [comment]
Ubuntu: 22.04 LTS
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:23 2022
 OS/Arch:           linux/amd64
 Context:           default
Docker-Compose: 2.6
