### ISSUE TITLE
API message payload field 'created_at' is not in ISO 8601 date/time format

### ISSUE THREAD

**Issue by jimmyheaddon** [chatwoot/chatwoot#4827]
Hello, I've noticed that the `created_at` field in the API response for messages does not follow the ISO 8601 format that you see with other date/time fields.  Other APIs also appear to follow the standard ISO format, and I'm not sure what the EPOCH for the `created_at` field is, or if it should also follow the ISO formatting?

**To Reproduce**
1. Query any conversation for messages, and inspect the `created_at` field
2. Compare it to other date/time fields from the same API operation, or other API calls

```
metadata
	.agent_last_seen_at:'2022-06-08T18:45:24.519Z'
	.assignee_last_seen_at:'2022-06-08T18:45:24.522Z'
payload
	.message
		.created_at:1653919407
```

**Expected behavior**
In the example above I would expect the `payload.message.created_at` field to be the same ISO 8601 format as `metadata.agent_last_seen_at` or `metadata.assignee_last_seen_at`.

**Screenshots**
N/A

**Browser logs**
I can provide these if required, but it happens with cURL and Postman commands, as well as `fetch` for JavaScript code.

**Server logs**
I can also provide these if you like, though it doesn't seem like a behavioural bug, more an implementation issue or design choice?

**Environment**
This was recorded in a self-hosted GCP environment, installed using the Linux scripts.

Thanks again for your efforts, let me know if I can provide any more details.

**Comment by pranavrajs** [comment]
@jimmyheaddon Thanks for sharing this. 

We follow epoch timings in some parts of the codebase. It needs standardization.

**Comment by iammattmartin** [comment]
Based on the posted time, `1654797279` is now as I post this.

So it would be seconds since `1970-01-01T00:00:00Z`

**Comment by pranavrajs** [comment]
@jimmyheaddon The time is Unix time format. Please see the following code for conversion.

https://github.com/chatwoot/chatwoot/blob/c5c89449dd46e63fedf6ca7e59898152af592249/app/javascript/dashboard/mixins/time.js#L7-L10

**Comment by jimmyheaddon** [comment]
Thanks @iammattmartin and @pranavrajs that worked a treat.  I'll keep an ear out for if the APIs converge on a single format, but otherwise feel free to close this ticket.

**Comment by pranavrajs** [comment]
Closing this as the changes are significant without much return. We can revisit when we create a version of the API.
