### ISSUE TITLE
Spanish translation pendings

### ISSUE THREAD

**Issue by grupale** [chatwoot/chatwoot#4832]
Hi! I would like to know how can I contribute to the Spanish translation, there are several objects that are not translated when I change to Spanish language.

Thanks!

**Comment by vishnu-narayanan** [comment]
@grupale Hello, thank you for your interest in contributing to Chatwoot. Please take a look at our translation guidelines. 

We use a service called Crowdin to manage the same. 

https://www.chatwoot.com/docs/contributing-guide/translation-guidelines/

**Comment by pranavrajs** [comment]
Closing this here as this is not an issue/bug.

**Comment by grupale** [comment]
Hi there! I've just ended the suggestions for the missing translations. When you approve it, I'll need to do an update? I have a docker installation.
![image](https://user-images.githubusercontent.com/10934794/172926671-e6a9033a-cb6e-4e03-a571-f205544f315a.png)

I couldn't translate the Unassigned string from the Inbox section. I didn't find the string in Crowdin. Can you tell me where to find it please? 
![image](https://user-images.githubusercontent.com/10934794/172927374-19c4b465-3935-4367-a01c-9f966c449263.png)
![image](https://user-images.githubusercontent.com/10934794/172927826-0ee1a195-dac4-4304-9adc-34ca6244e1d9.png)

**Comment by grupale** [comment]
> Closing this here as this is not an issue/bug.

Hi @pranavrajs sorry to bother, were you able to check the translations mentioned? Where is located the "Unnasigned" string? Thanks
