### ISSUE TITLE
Add custom_attributes field in the API documentation

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#4845]
Conversation API is missing the attribute custom_attributes in the API documentation.

<img width="413" alt="Screenshot 2022-06-13 at 12 25 01 PM" src="https://user-images.githubusercontent.com/2246121/173296650-a69174ad-43d7-49dc-879f-19eb71c9cfb7.png">

**Comment by tejaswinichile** [comment]
Handled in #4852
