### ISSUE TITLE
Add email validation in the email field of New Contact

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#4849]
<img width="469" alt="Screenshot 2022-06-13 at 4 08 40 PM" src="https://user-images.githubusercontent.com/1219448/173336285-d85cce44-0d36-484c-9efd-bc38ef72062e.png">

**Comment by pranavrajs** [comment]
@iamsivin Let us ship a fix for this in the next sprint.

**Comment by chetan2796** [comment]
If this issue is fixed or not

**Comment by iamsivin** [comment]
> If this issue is fixed or not 

No, will ship a fix by next sprint.

**Comment by chetan2796** [comment]
Actually I am new in open source i want to try.
