### ISSUE TITLE
Feature: Add docker app deployment option

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#485]
**Is your feature request related to a problem? Please describe.**
A simple and less error-prone way to quickly try out Chatwoot.

**Describe the solution you'd like**
`$ docker app install chatwoot/chatwoot`

**Describe alternatives you've considered**

#### Flatpak
+1
- future of Linux app packaging
- looks promising and supported by community

-1 
- From primary research, not supporting webapps at the moment

#### Snap/Snapcraft
+1
- From primary research, should support webapps

-1
- Proprietary canonical development
- Fedora 31 dropped support for snap. Others might follow suit.

**Additional context**
Docker app packaging is based on CNAB - Cloud Native Application Bundle which is an evolving format. This is currently an experimental feature offered by Docker and things might change in future.

**Comment by vishnu-narayanan** [comment]
Will check and raise PR. 
cc: @sojan-official @pranavrajs

**Comment by sojan-official** [comment]
Closing this as we have other issues tracking this
