### ISSUE TITLE
Documentation Fix in the Updating Inbox Member Section

### ISSUE THREAD

**Issue by NusretOzates** [chatwoot/chatwoot#4851]
**Is your enhancement request related to a problem? Please describe.**
When I tried to update agents in an inbox, I get a 404 not found error. The problem was, that the documentation [here](https://www.chatwoot.com/developers/api/#operation/update-agents-in-inbox) was wrong.

**Describe the solution you'd like**
The url example https://app.chatwoot.com/api/v1/accounts/{account_id}/inbox_members/{inbox_id} must be https://app.chatwoot.com/api/v1/accounts/{account_id}/inbox_members/  and it makes sense because we already give inbox id in the request body

**Additional context**
![image](https://user-images.githubusercontent.com/19870022/173381533-d8d8d1dd-c625-405e-9180-9d27bff74576.png)
![image](https://user-images.githubusercontent.com/19870022/173381622-19e76555-1f39-45bb-bb4c-df15199e402b.png)

**Comment by pranavrajs** [comment]
@tejaswinichile Could you do take this one too in #4852
