### ISSUE TITLE
Grammatical errors in the help text under Inboxes --> Choose a channel

### ISSUE THREAD

**Issue by gk7700** [chatwoot/chatwoot#4865]
Grammatical errors in the help text under Inboxes --> Choose a channel

![image](https://user-images.githubusercontent.com/40832072/173782059-8fe11172-e356-408b-83aa-be6e2551336c.png)

**Comment by pranavrajs** [comment]
@gk7700 Can you please share what is wrong in the text?

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/4868
