### ISSUE TITLE
idea: WhatsApp CloudAPI Support

### ISSUE THREAD

**Issue by xLixon** [chatwoot/chatwoot#4869]
Hi

https://developers.facebook.com/docs/whatsapp/cloud-api/

This is the new WhatsApp API of Facebook.
It would be great if following things get addet to ChatWoot:

- a WebHook for Recieving the Messages
- >> Sorting of the Messages to Contacts and Chats like WhatsAppWeb

- For Sending WebHooks
- >> The token should automaticly renew (if it isnt permanent)
- >> Also the Messages should be shown in the Contacts like a Convo (again Like WhatsAppWeb)

Is this possible?

Regards

**Comment by pranavrajs** [comment]
Duplicate #4712
