### ISSUE TITLE
Grammatical error in the Inbox help-text description 

### ISSUE THREAD

**Issue by gk7700** [chatwoot/chatwoot#4871]
Grammatical error in the Inbox help-text description 

![image](https://user-images.githubusercontent.com/40832072/173831237-92746746-2e98-4a1c-a0fe-6fabae94d2f8.png)

**Comment by pranavrajs** [comment]
Closing this via https://www.chatwoot.com/docs/handbook/engineering/pr-guidelines#avoid-cosmetic-changes
