### ISSUE TITLE
Auto-save replies as drafts in conversations

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#4876]
**Is your feature request related to a problem? Please describe.**
When we decide to reply a customer later, we jot down points or draft a reply that has to be filled in and sent later after collecting appropriate information. These notes/draft content is lost when we visit the dashboard again.

**Describe the solution you'd like**
A "Save Draft" button or auto-save the replies for the conversation we are attending to. The drafts should be visible to the agent only.

**Describe alternatives you've considered**
Add these notes as private notes. But this causes unwanted redundancy in the conversation.

**Comment by pranavrajs** [comment]
@aslamabbas This would be fixed via #4440
