### ISSUE TITLE
automation api rule suddenly stop working

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4878]
hi please see this below image i try automation rules api before it was working now its stop not working 
 i also try to change /automation_rules -- to /automation_rule_definitions in url but same issue

![image](https://user-images.githubusercontent.com/20530550/174051976-b98e6b50-7258-4567-aeab-50e0daf2f0fd.png)

**Comment by pranavrajs** [comment]
@voko3456 There is an error in the URL, it should be `<installation-url>/api/v1/accounts/<account-id>/automation_rules` not `<installation-url>/v1/accounts/<account-id>/automation_rules`. `/api` is missing.

Hope this helps.
