### ISSUE TITLE
How to get chatwoot to start a conversation 

### ISSUE THREAD

**Issue by CelestineAkpanoko** [chatwoot/chatwoot#4881]
**Is your feature request related to a problem? Please describe.**
I am attempting to get the Chatwoot to start a conversation after the user clicks on the widget. Also, with the Email Collect Prompt functionality of the inbox, how can I enforce the user to type their email in.

**Describe the solution you'd like**
How to get the Chatwoot bot to start a conversation or send a message after the user clicks the "start a conversation" button.

**Describe alternatives you've considered**
I don't know yet. I need help

**Comment by pranavrajs** [comment]
> I am attempting to get the Chatwoot to start a conversation after the user clicks on the widget

@CelestineAkpanoko Please listen to webwidget.triggered event in webhook and create a conversation with the APIs.

> the Email Collect Prompt functionality of the inbox, how can I enforce the user to type their email in.

Please use [pre-chat](https://www.chatwoot.com/docs/user-guide/features/pre-chat-form) forms for this.
