### ISSUE TITLE
Heroku Deployment Error on 2.6.0 Upgrade

### ISSUE THREAD

**Issue by axiliquint** [chatwoot/chatwoot#4885]
**Describe the bug**

Heroku deployment error occurs when trying to upgrade from Chatwoot 2.5.0 to 2.6.0.

**To Reproduce**

1. Provision an on-click Heroku instance of Chatwoot on 2.5.0.
2. Upgrade to 2.6.0.
4. See error.

**Expected behavior**

The deployment succeeds, and revision is made.

**Server logs**

Deployment logs are available here: https://www.toptal.com/developers/hastebin/okukerakeq.yaml

**Environment**

Self-hosted one-click Heroku instance.

**Additional context**

**Comment by pranavrajs** [comment]
@axiliquint There doesn't seem to be an error in the logs you shared. Would you be able to share some more information to debug this?

**Comment by axiliquint** [comment]
Sorry - let me provide some more info. I agree that by looking at the logs the build did succeed, however, the line of: `Release command declared: this new release will not be available until the command succeeds.` makes it seems like something failed silently. Additionally, my Heroku dash shows that the deployment failed because the "Release command failed".![image](https://user-images.githubusercontent.com/99619198/174409446-1396355f-cb10-46a9-94e3-a93dd6c0331d.png)

**Comment by axiliquint** [comment]
After looking a bit further, it looks like the actual deployment failed, not the build. Editing to show that info.
![image](https://user-images.githubusercontent.com/99619198/174409587-5ce9bdcd-0001-4129-a72c-6a58f981aa8f.png)

**Comment by pranavrajs** [comment]
@axiliquint Closing this as the issue seems to be resolved. Please feel free to reopen the issue if it is not the case.
