### ISSUE TITLE
Feedback wont working on custom channel

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4889]
Hi,

We have added Custom Channel, and seems like Feedback/ Rating wont working, getting 404 error

Below are the screenshots

<img width="699" alt="image" src="https://user-images.githubusercontent.com/38554929/174430850-991d6708-de53-463e-afbf-f04dc3f5bfcb.png">

![image](https://user-images.githubusercontent.com/38554929/174430855-e974ffd2-f857-4ec7-9884-b3ca09d46c16.png)

**Comment by pranavrajs** [comment]
@harismateen We support CSAT in all channels. Once the response is submitted, it would not be able to share the response again.

**Comment by harismateen** [comment]
@pranavrajs for the first time also its not working. Ussr received feedback -- open URL - and cant submit their rating as on above screenshot

**Comment by pranavrajs** [comment]
@harismateen Closing this here as the team tested this functionality and the behavior could not be reproduced. Please feel free to reopen the issue with a screencast.
