### ISSUE TITLE
Project Setup on Local environment

### ISSUE THREAD

**Issue by ippezshelby** [chatwoot/chatwoot#4894]
Hey all, 
I have been trying to setup chatwoot on my local machine for days now but am still failing. Am using the documentations on https://www.chatwoot.com/docs/contributing-guide/project-setup for local setup and testing.

**Environments**

- ruby 3.0.4p208
- Windows 11
- Composer version 2.2.9
- Yarn 1.22.18
- Docker version 20.10.16, build aa7e414
- docker-compose version 1.29.2, build 5becea4c

The following steps ran without errors
[Install Ruby dependencies](https://www.chatwoot.com/docs/contributing-guide/project-setup#install-ruby-dependencies)
[Install JavaScript dependencies](https://www.chatwoot.com/docs/contributing-guide/project-setup#install-javascript-dependencies)
[Setup environment variables.](https://www.chatwoot.com/docs/contributing-guide/project-setup#setup-environment-variables)

Step where error is [Setup rails server](https://www.chatwoot.com/docs/contributing-guide/project-setup#setup-rails-server)
Command that failed ~ `bundle exec rake db:create`
**Errors from the above command**
```
PS D:\Dev\Support Chats\chatwoot> bundle exec rake db:create
rake aborted!
unknown binary format
D:/Dev/Support Chats/chatwoot/config/application.rb:5:in `<top (required)>'
D:/Dev/Support Chats/chatwoot/Rakefile:4:in `require_relative'
D:/Dev/Support Chats/chatwoot/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
Any assistance in running the system is highly appreciated.
Thanks and regards

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still having this issue.
