### ISSUE TITLE
Fix "method_lines" issue in babel.config.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#49]
Function `exports` has 69 lines of code (exceeds 25 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/babel.config.js#issue_5d87480387cf19000100018d

**Comment by nursoltan-s** [comment]
It seems fixed on Codeclimate. Is it necessary to work on this?

**Comment by sojan-official** [comment]
@pranavrajs  can you verify and close this ?
