### ISSUE TITLE
Can inboxes in the sidebar have channel type indicator ? 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#490]
**Is your enhancement request related to a problem? Please describe.**
When I see chatwoot dashboard , with multiple inboxes. its really hard to differenciate which inbox is which

![Screenshot 2020-02-14 at 12 09 33 AM](https://user-images.githubusercontent.com/73185/74467148-8cba6500-4ebe-11ea-8bdf-3558bf9566f8.png)

**Describe the solution you'd like**
an icon or color indicator next to the inbox that denotes the type of channel 

**Describe alternatives you've considered**
none 

**Additional context**
none

**Comment by pranavrajs** [comment]
Closed via #511
