### ISSUE TITLE
Improvements in whatsapp templates

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#4900]
**Is your enhancement request related to a problem? Please describe.**

Hi guys, how are you?

First, thank you very much for the whatsapp message templates search feature in version 2.6.0. It got pretty interesting.

However, it brought up another issue that could be improved.
On facebook there are some sample templates that are created automatically, but they are not useful.

![image](https://user-images.githubusercontent.com/99494469/174646009-dee9f8b9-d242-4cd1-b801-543ef2883f76.png)

**Describe the solution you'd like**

These examples cannot be deleted on facebook. I do not know why.

it would be interesting if in a future version chatwoot didn't synchronize these templates. It could be something that the user ADMIN parameterizes and chooses whether to use it or not.

Also because there are templates that should only be used by bot and not by agent.

**Comment by pranavrajs** [comment]
@glauberssoutodossantos It seems like we cannot distinguish between the default templates and the templates added by the user. Closing it for now.
