### ISSUE TITLE
how can i receive attachment message on api

### ISSUE THREAD

**Issue by aaxx255** [chatwoot/chatwoot#4907]
https://www.chatwoot.com/developers/api/#operation/create-a-message

I'm using this api, but it only accepts text messages. Is there anywhere to receive attachment messages?
![image](https://user-images.githubusercontent.com/49965566/174936638-01edde76-84c2-4de2-a038-cca31541a84d.png)

**Comment by sojan-official** [comment]
please refer: https://github.com/chatwoot/chatwoot/discussions/1809
