### ISSUE TITLE
Can I check if custom channel wont support feedback / Rating?

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4908]
We have added custom channel, but whenever user click on feedback URL, they are getting "Could not connect to woot server" and the API is giving 404 error as in below screenshot, 

![image](https://user-images.githubusercontent.com/38554929/174940448-353e583f-75c1-496a-b287-e7e2c97b0dfb.png)

**Comment by pranavrajs** [comment]
Duplicate #4889
