### ISSUE TITLE
Cannot start chatwoot install from docker

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#491]
**Describe the bug**
Try to run docker-compose run --rm rails bundle exec sidekiq
and get this error

2020-02-14T12:40:56.648Z pid=1 tid=gtdbqlmad INFO: Booted Rails 6.0.2.1 application in development environment
2020-02-14T12:40:56.648Z pid=1 tid=gtdbqlmad INFO: Running in ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux-musl]
2020-02-14T12:40:56.648Z pid=1 tid=gtdbqlmad INFO: See LICENSE and the LGPL-3.0 for licensing details.
2020-02-14T12:40:56.648Z pid=1 tid=gtdbqlmad INFO: Upgrade to Sidekiq Pro for more features and support: http://sidekiq.org
ERR Client sent AUTH, but no password is set
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:126:in `call'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:107:in `block in connect'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:286:in `block in info'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
/usr/local/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
/gems/ruby/2.6.0/gems/redis-4.1.3/lib/redis.rb:285:in `info'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq.rb:118:in `block in redis_info'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq.rb:97:in `block in redis'
/gems/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:65:in `block (2 levels) in with'
/gems/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `handle_interrupt'
/gems/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:64:in `block in with'
/gems/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `handle_interrupt'
/gems/ruby/2.6.0/gems/connection_pool-2.2.2/lib/connection_pool.rb:61:in `with'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq.rb:94:in `redis'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq.rb:112:in `redis_info'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/lib/sidekiq/cli.rb:61:in `run'
/gems/ruby/2.6.0/gems/sidekiq-6.0.4/bin/sidekiq:12:in `<top (required)>'
/gems/ruby/2.6.0/bin/sidekiq:23:in `load'
/gems/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vishnu-narayanan** [comment]
@aermike Have you set environment variable `REDIS_PASSWORD` in the `.env` file ?

**Comment by aermike** [comment]
No
I set it up and come with an update

**Comment by vishnu-narayanan** [comment]
@aermike We are not able to reproduce this issue. If you are still getting this error, could you please share the complete steps to reproduce this on our end ?

**Comment by aermike** [comment]
After set up Rail Password and docker-compose build 
it runs
Isssue na be closed

**Comment by vishnu-narayanan** [comment]
Glad that it now works. Thank you.

**Comment by sony-mathew** [comment]
I faced this issue again. Looks like a valid issue. When the the `.env` file has line with `REDIS_PASSWORD` set as empty, the value for this in the initializers comes as an empty string `""`. From the initial investigation, this is causing the issue. I will be opening a PR soon to resolve this.
