### ISSUE TITLE
Add support for location & contact group messages

### ISSUE THREAD

**Issue by lengmiguel** [chatwoot/chatwoot#4917]
Good morning, I report some details that I have seen in the whatsapp tray are the following:

When a location is sent by whatsapp, the platform is shown on the client side but the message never arrives in the tray.

whatsapp Movil
![image](https://user-images.githubusercontent.com/22181854/175316537-02d21c1f-2153-4701-ba81-cb2e4c597966.png)

inbox whatsapp chatwoot
![image](https://user-images.githubusercontent.com/22181854/175316744-23f3b34d-9e6e-4054-b47a-750027ea9c2a.png)
the message never arrives when it comes to location to the inbox

Also when contacts are sent the message does not arrive either.
And you cannot add the WhatsApp number that is linked to 360dialog chatwoot to WhatsApp groups.

**Comment by sojan-official** [comment]
@lengmiguel  closing this in favor of https://github.com/chatwoot/chatwoot/issues/3398 
Also, group messages are not supported by the Whatsapp APIs. so at the moment there is no workaround for that
