### ISSUE TITLE
Add Flowy or GoJS to gnerate CSML bot config code

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#4922]
it's easy for devolpers to gnerate csml bot config code but it's hard for end user ,
So we can use Flowy or GoJS or other flow chart framework to let end users draw his own bot via ui  then we can gnerate csml bot config code via Flowy or GoJS and submit it to agent bot

ref: https://github.com/alyssaxuu/flowy

**Comment by giquieu** [comment]
Hello,
As another draw flow option:

https://jerosoler.github.io/Drawflow/

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/9892674/175828485-61e4f5ca-5bb1-4b3d-9cf5-2b33d28a9098.png">

**Comment by giquieu** [comment]
This one is very interesting. The ease of creating nodes is really cool.
Several possibilities with this flow builder.
Nice that it's done in Vue.js.

https://github.com/newcat/baklavajs

![image](https://user-images.githubusercontent.com/9892674/177885719-c44e856a-eeb6-4980-8405-98607e2edc16.png)

**Comment by sojan-official** [comment]
@voko3456  awesome. Please go ahead.

**Comment by rodenp** [comment]
Wow I am excited about this possibility of using visual chatbot builders.
Is there any update on this?

**Comment by pranavrajs** [comment]
Closing this as we will be removing the CSML integration in the January release. No new bot can be added, although the existing ones would work.
