### ISSUE TITLE
Not getting messages for FB inbox even after configuring through given facebook guide on site

### ISSUE THREAD

**Issue by karzounapp** [chatwoot/chatwoot#4930]
![Screenshot 2022-06-27 103532](https://user-images.githubusercontent.com/107565124/175885251-79a17a86-4d60-4f0e-b48a-05d898e27552.png)
Hello 
i have problem with facebook messages 
I can't receive messages after configuring
I did everything right
I linked the page and gave it the required permissions
![Screenshot 2022-06-27 103352](https://user-images.githubusercontent.com/107565124/175885076-f7d74490-be6f-47ab-a016-d13f4ffd0554.png)
![Screenshot 2022-06-27 103326](https://user-images.githubusercontent.com/107565124/175885078-bd51ecfa-9c4f-4f5d-badc-41b1d0e481c2.png)

**Comment by pranavrajs** [comment]
Closing this as the review is complete.
