### ISSUE TITLE
CSAT for custom channels

### ISSUE THREAD

**Issue by SherefAbolmagd** [chatwoot/chatwoot#4935]
getting 404 when try to use the API for updating the CSAT for custom channel

<img width="1006" alt="Screen Shot 2022-06-27 at 8 56 28 PM" src="https://user-images.githubusercontent.com/40181573/176015173-cab1530f-da19-4fda-87fe-975bf4c0ea19.png">

**Comment by pranavrajs** [comment]
"404 Not found" is returned if the id you are passing is an invalid identifier. Please make sure that the identifier is valid. Closing this as I have tested the APIs with a valid conversation-uuid and is working fine. 

Please feel free to reopen the issue with a screencast/logs if needed.

**Comment by SherefAbolmagd** [comment]
May I know where exactly to get the identifier because i use the contact_inbox.source_id when the conv is resolved i get this request from the webhook
![6a7ebea3-ff8d-4ba4-80a0-78935607c435](https://user-images.githubusercontent.com/40181573/176128274-470f5b04-9868-448e-9d06-e56dbf703c8f.jpeg)
and i use the contact_inbox.source_id to add rating but it return not found
<img width="1009" alt="Screen Shot 2022-06-28 at 10 11 52 AM" src="https://user-images.githubusercontent.com/40181573/176128578-ff4ac71e-d3e2-4904-b7b5-c304ea523730.png">

**Comment by pranavrajs** [comment]
@SherefAbolmagd The unique key is `conversation.uuid`.

**Comment by SherefAbolmagd** [comment]
@pranavrajs I'm unable to find the conversation uuid in my payload

<img width="1013" alt="Screen Shot 2022-07-01 at 8 58 34 AM" src="https://user-images.githubusercontent.com/40181573/176841581-de8a8850-a768-4b94-9a33-194c09908ce8.png">

{
    "meta": {
        "sender": {
            "additional_attributes": {},
            "availability_status": "offline",
            "email": null,
            "id": 208,
            "name": "Sheref Abolmagd",
            "phone_number": "+6012345678",
            "identifier": "+6012345678",
            "thumbnail": "",
            "custom_attributes": {
                "status": "open",
                "conv_id": 203
            },
            "last_activity_at": 1656596325
        },
        "channel": "Channel::Api",
        "assignee": {
            "id": 1,
            "account_id": 1,
            "availability_status": "online",
            "auto_offline": true,
            "confirmed": true,
            "email": "************",
            "available_name": "*************",
            "name": "*************",
            "role": "administrator",
            "thumbnail": ""
        },
        "hmac_verified": false
    },
    "id": 203,
    "messages": [
        {
            "id": 2355,
            "content": "Hey",
            "account_id": 1,
            "inbox_id": 10,
            "conversation_id": 203,
            "message_type": 0,
            "created_at": 1656596325,
            "updated_at": "2022-06-30T13:38:45.646Z",
            "private": false,
            "status": "sent",
            "source_id": null,
            "content_type": "text",
            "content_attributes": {},
            "sender_type": "Contact",
            "sender_id": 208,
            "external_source_ids": {},
            "additional_attributes": {},
            "conversation": {
                "assignee_id": 1
            },
            "sender": {
                "additional_attributes": {},
                "custom_attributes": {
                    "status": "open",
                    "conv_id": 203
                },
                "email": null,
                "id": 208,
                "identifier": "+60123455678,
                "name": "Sheref Abolmagd",
                "phone_number": "+60123455678",
                "thumbnail": "",
                "type": "contact"
            }
        }
    ],
    "account_id": 1,
    "additional_attributes": {},
    "agent_last_seen_at": 1656658592,
    "assignee_last_seen_at": 1656658592,
    "can_reply": true,
    "contact_last_seen_at": 0,
    "custom_attributes": {
        "created": "1656509271507"
    },
    "inbox_id": 10,
    "labels": [],
    "muted": false,
    "snoozed_until": null,
    "status": "open",
    "timestamp": 1656596325,
    "unread_count": 0
}
