### ISSUE TITLE
May I know where exactly to get the identifier because i use the contact_inbox.source_id when the conv is resolved i get this request from the webhook

### ISSUE THREAD

**Issue by SherefAbolmagd** [chatwoot/chatwoot#4937]
May I know where exactly to get the identifier for csat because i use the contact_inbox.source_id when the conv is resolved i get this request from the webhook
![6a7ebea3-ff8d-4ba4-80a0-78935607c435](https://user-images.githubusercontent.com/40181573/176128274-470f5b04-9868-448e-9d06-e56dbf703c8f.jpeg)

and i use the contact_inbox.source_id to add rating but it return not found

<img width="1009" alt="Screen Shot 2022-06-28 at 10 11 52 AM" src="https://user-images.githubusercontent.com/40181573/176128578-ff4ac71e-d3e2-4904-b7b5-c304ea523730.png">

_Originally posted by @SherefAbolmagd in https://github.com/chatwoot/chatwoot/issues/4935#issuecomment-1168386194_

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/6328
