### ISSUE TITLE
ReferenceError: Can't find variable: AudioContext on Safari before desktop version 14.1 and mobile version 14.5

### ISSUE THREAD

**Issue by jschaf** [chatwoot/chatwoot#4942]
**Describe the bug**

window.AudioContext isn't defined on versions of desktop Safari prior to 14.1 and Mobile Safari prior to 14.5 [MDN](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext). The older versions use the prefixed form instead: `window.webkitAudioContext`.

The problem is that installing Chatwoot on a page means every user interaction will cause a console error.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/22385/176275321-c023b92e-17af-4b92-869f-d00d7018d0d4.png">

**To Reproduce**

On older versions of Safari prior to 14.1 for desktop or 14.5 for mobile, evaluate:

```
window.AudioContext
```

**Expected behavior**

No error.

**Browser logs**

The error appears for every user interaction on the page.

```
ReferenceError: Can't find variable: AudioContext
```

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22385/176274327-df8ed049-c271-4f18-bdc2-d87c971dd1f2.png">

**Environment**

I'm using Chatwoot Cloud but this issue is independent of the installation.

**Desktop (please complete the following information):**
 - OS: iOS and macOS
 - Browser: Safari
 - Version: Observed in 14.0 (from logs)

**Additional context**

Related threads: 

- https://news.ycombinator.com/item?id=24875959,     Fixed by using: `let AudioContext = window.AudioContext || window.webkitAudioContext`
- https://github.com/amaneureka/T-Rex/issues/5

**Comment by iamsivin** [comment]
@pranavrajs We are using both `window.AudioContext & window.webkitAudioContext`. You can se it here https://cs.github.com/chatwoot/ui/blob/959082f75576ab85841b7e3b59efa16b67b592a1/src/shared/helpers/AudioNotificationHelper.js#L7
