### ISSUE TITLE
Can use attachment link with send message attachment API

### ISSUE THREAD

**Issue by SherefAbolmagd** [chatwoot/chatwoot#4943]
attachment store on external vendor and want to pass it to chatwoot using links instead of uploading to form

<img width="1012" alt="Screen Shot 2022-06-29 at 12 23 15 AM" src="https://user-images.githubusercontent.com/40181573/176314677-10b17639-b66b-4790-bfe9-43d113c656b3.png">

**Comment by pranavrajs** [comment]
@SherefAbolmagd Please use the template to create the issue, it is not clear what the issue is.
