### ISSUE TITLE
Intagram as channel to add

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4950]
**Is your enhancement request related to a problem? Please describe.**
To connect Instagram and received messages from IG and reply via chatwoot,

**Comment by pranavrajs** [comment]
Please see these guides: 

Self-hosted App setup instructions: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup
Connect your Instagram Account: https://www.chatwoot.com/docs/product/channels/instagram
