### ISSUE TITLE
[CW-2377] Different email signature for different inboxes

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#4953]
**Is your feature request related to a problem? Please describe.**
Each inbox is the customer support for a particular product/service. Each requires a signature that is unique to that product/service.

**Describe the solution you'd like**
A setting in the Inbox, for the agent to set their email signature for that particular inbox.

**Describe alternatives you've considered**
None

**Additional context**

<sub>[CW-2377](https://linear.app/chatwoot/issue/CW-2377/different-email-signature-for-different-inboxes)</sub>

**Comment by andrsharov** [comment]
Hi, there.

We are also really needed this feature. 

Right now we have 20 email channels. And we use very simmilar signature for all channels

> Best Regards,
> Andrei Sharov

But we need to use different signatures for each channel separately 

Something like this:

> Best Regards,
> Andrei Sharov
> Sales manager from Company One 

> Best Regards,
> Andrei Sharov
> Sales manager from Company Two

> Best Regards,
> Andrei Sharov
> Sales manager from Company Three

P.S.: not only for emails channels , for all channels ( Telegramm, WhatsApp .... )

**Comment by nhadsall** [comment]
Bummer, was seriously considering chatwoot, but this is a must. We have multiple orgs we need to support from a single interface.

**Comment by pranavrajs** [comment]
@nhadsall We are shipping some message signature updates this week. If it doesn't solve the problem, we will get it re-opened.

**Comment by kolosek** [comment]
@pranavrajs Great!
