### ISSUE TITLE
Auto assign tickets to the first agent who responds to it

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#4954]
**Is your enhancement request related to a problem? Please describe.**
Currently, we have disabled the "Auto assignment" option in the Inbox settings. That feature should actually be named as "Distribute conversations among agents". 

And when tickets come under the "Unassigned" tab in inbox, the agent responds to it. A tiny grey box pops up asking if the conversation has to be assigned to the agent. 

That feels unnecessary. If an agent responds, he/she should be auto assigned. 

The grey box popup makes sense, if another agent tries to reply to the ticket. 
**Describe the solution you'd like**
Change the current "auto assignment" to "distribute among agents"
add a proper "auto assignment"

**Describe alternatives you've considered**
none

**Additional context**

**Comment by pranavrajs** [comment]
@aslamabbas Thanks for the suggestion. It seems like this could be possible automation rather than an option in the inbox settings.
