### ISSUE TITLE
Dashboard Apps - embed an entire system like Hubspot

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#4957]
Hey guys.

About dashboard apps I've realized is that I can embed an entire system, like Hubspot. See in the video below that it was super interesting to work with a single screen.

https://www.vidline.com/share/V00O6HG68K/9a2fedeab64692695a497fccc7d5d518

Only thing is that it always reloads to homepage.

It would be interesting for the dashboard apps in the future to save the last page accessed by message, which would greatly facilitate the day to day of the attendant.

**Comment by sojan-official** [comment]
Throwing thoughts here, We could evaluate URLs with dynamic params. 

``` 
http://examples.com/{{contact.custom_attribute.crm_id}}
```

So one could configure the identifier as an attribute to the contact.

**Comment by glauberssoutodossantos** [comment]
That would be very interesting.

See the hubspot case below. The user ID goes at the end of the url.

![image](https://user-images.githubusercontent.com/99494469/176950453-bf40249a-98bb-4e2b-8fc8-30187c5b5cbd.png)


When I open this lead in chatwoot, see how interesting it is to work in a single interface.

The only problem is that today every time I click on a new conversation I have to do all the search again in the CRM, because the apps dashboard always takes me to the CRM homepage.

![image](https://user-images.githubusercontent.com/99494469/176951581-afca5adc-ac94-41c6-8656-8ea5f55b3aab.png)

**Comment by pranavrajs** [comment]
@glauberssoutodossantos We will track it in https://github.com/chatwoot/chatwoot/issues/4974
