### ISSUE TITLE
Dashboard apps for different Inbox

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#4958]
**Describe the solution you'd like**

Ability to embed a separate dashboard app with a separate inbox. 

**Context**

A user has many inboxes of completely different industries and has a need to embed separate app with separate inbox to pass the information to it's users. 

Currently, It's not possible considering we're at V1 (development).

**Comment by pranavrajs** [comment]
Closing this, we will track it here https://github.com/chatwoot/chatwoot/issues/4974
