### ISSUE TITLE
Bug: Wrong error message when existing agent email is reused for a new agent

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#496]
**Describe the bug**
Wrong error message when existing agent email is reused for a new agent
" cannot connect to server " 

**To Reproduce**
1. Go to agents screen
2. add agent with email 'test@test.com'
3. try to add another agent with same email 'test@test.com'

**Expected behavior**
The error should say agent already exists 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all

**Comment by ghosteathuman** [comment]
Dropping a quick note about some investigation done, it is because the Axios call to the Agents Controller gets a 422 response, which causes it to error out and display the default API ERROR_MESSAGE.

**Comment by sojan-official** [comment]
@ghosteathuman  thanks for taking a look into this.
