### ISSUE TITLE
Compliance on Live Chat Widget

### ISSUE THREAD

**Issue by prononext** [chatwoot/chatwoot#4961]
As many countries have Data Protection Regulations it is mandatory to give the user information about your Compliance before he is making any data transmission like writing a chat. 

The Live Chat Widget of Chatwoot does not have this possibility. 
The pre-chat-form cannot be customized to show the user a short text with a link with a mandatory accept button to begin the chat. 

It would be really nice to have this and begin a compliant production state with chatwoot.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/1231
