### ISSUE TITLE
Docker: unable to run initial migrations

### ISSUE THREAD

**Issue by gonzalo** [chatwoot/chatwoot#4969]
**Describe the bug**

I'm following instructions to set up a docker-compose production environment to test chatwoot as it's shown on https://www.chatwoot.com/docs/self-hosted/deployment/docker/ but fails on step 4 migrating the DB fails during executions -> "rails not found"

$docker-compose run --rm rails bundle exec rails db:chatwoot_prepare

It seems that bundle install is unable to write on /root folder and from them is unable to run rails

**To Reproduce**

1. Follow instructions of docker-compose production environment (DB is initializated properly)
2. try to run chatwoot_prepare

**Expected behavior**

Migrations done 

**logs**

```
# docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
Starting chatwoot_postgres_1 ... done
+ rm -rf /app/tmp/pids/server.pid
+ rm -rf '/app/tmp/cache/*'
+ echo 'Waiting for postgres to become ready....'
Waiting for postgres to become ready....
+ docker/entrypoints/helpers/pg_database_url.rb
+ export 'POSTGRES_PORT=5432'
+ PG_READY='pg_isready -h postgres -p 5432 -U postgres'
+ pg_isready -h postgres -p 5432 -U postgres
postgres:5432 - accepting connections
+ echo 'Database ready to accept connections.'
Database ready to accept connections.
+ bundle install
`/root` is not writable.
Bundler will use `/tmp/bundler20220704-12-6vdap812' as your home directory temporarily.
Using rake 13.0.6
Using concurrent-ruby 1.1.10
...
...
...
Using working_hours 1.4.1
Bundle complete! 99 Gemfile dependencies, 202 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
+ BUNDLE='bundle check'
+ bundle check
The Gemfile's dependencies are satisfied
+ exec bundle exec rails db:chatwoot_prepare
bundler: command not found: rails
Install missing gem executables with `bundle install`

```

**Environment**

self hosted installation of Chatwoot: Docker

**Server (please complete the following information):**
 - OS: Ubuntu 16.04.5 LTS
 - Docker version 18.09.0, build 4d60db4
 - docker-compose version 1.24.0, build 0aa59064

**Additional context**

Also I tried to run command bundel from the container as follows: 
```
# docker-compose run --rm rails sh
... 
(inside container)
# bundle install
`/root` is not writable. -> but the fact is that /root IS writable, tested
....
```
Even if I use different location
```
... 
(inside container)
# mkdir my_folder
# HOME=my_folder
# bundle install
`my_folder` is not writable.
....
```

**Comment by pranavrajs** [comment]
@vishnu-narayanan Can you please take a look?

**Comment by vishnu-narayanan** [comment]
@gonzalo You are on older version of docker engine and docker compose. Could you please try this on a recent version of docker and docker-compose?

ref 1: https://www.chatwoot.com/docs/self-hosted/deployment/docker#pre-requisites
ref 2: https://github.com/chatwoot/chatwoot/issues/2845

**Comment by gonzalo** [comment]
You're right, running in a recent docker/docker-compose version solves the problem.

Regards

**Comment by gonzalo** [comment]
Also can confirm that Docker version 18.09.9, build 039a7df9ba its enough to run it
