### ISSUE TITLE
Bug:  Conversation counters aren't updated in real time 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#497]
**Describe the bug**
The conversation counter isn't updated in real-time when a new conversation comes into the system .

![Screenshot 2020-02-15 at 3 21 34 AM](https://user-images.githubusercontent.com/73185/74570355-6a017c80-4fa2-11ea-9c0a-bebb9cd219f3.png)

**To Reproduce**
1. Trigger an incoming message from widget to chatwoot platform
2. Watch the top counters aren't incremented when a new message comes in
3. Counter increments only on the subsequent request

**Expected behavior**
Conversation counters should be updated in real time

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] all
 - Browser [e.g. chrome, safari] all
 - Version [e.g. 22] all

**Additional context**
none

**Comment by sojan-official** [comment]
we will create an endpoint to fetch the meta

**Comment by meaziz** [comment]
Is that issue still there, would like to have a look at it. and @sojan-official can you describe the idea about the meta endpoint.

**Comment by sojan-official** [comment]
@meaziz yes, if you would like to work on it will assign it to you.  
As described in the issue, it has to do with this particular header.

![Screenshot 2020-02-15 at 3 21 34 AM](https://user-images.githubusercontent.com/73185/74570355-6a017c80-4fa2-11ea-9c0a-bebb9cd219f3.png)

so every time we get an event in our WebSockets,  we will have to send an API request to the backend to fetch the count of conversation in the three tabs with the current filters ( open / resolved )
`mine, unassigned, all`

during the initial page load, this information comes along with the conversations payload. Since we don't need the full payload for the subsequent requests, we will implement a new endpoint in the conversations controller that responds with counts of conversations alone.  

cc: @pranavrajs @nithindavid

**Comment by meaziz** [comment]
If I may propose an alternative.
Instead of sending an API Call every time we get an event in our WebSocket 
Why don't we send the data through over with the socket message?

or at least send a property with each socket message advising the Front-end whether it need to go fetch the data or not.

**Comment by pranavrajs** [comment]
@meaziz Please let me know your thoughts on the following one.

> Instead of sending an API Call every time we get an event in our WebSocket
> Why don't we send the data through over with the socket message? or at least send property with each socket message advising the Front-end whether it needs to go fetch the data or not.
> 

We thought about this approach initially, later figured that this will not work. There are a couple of reasons for this.

1. The counters in the frontend are dependant on the user, the type of filter the user has applied on the frontend.

We don't save the filters in the backend, so when we send the socket event, we don't have context about what the user is looking at right now. In effect, we will not be able to say whether there is a change in the view user is looking at.

2. Most of the socket events available right now represent only type of action, combining metadata inside the payload seems to be wrong approach, instead, we have to add a new socket event for metadata change which seems to a lot more complex than the API one.

Here we are not calling the API on every event. 3 type of events qualify for the same. `conversation.created`, `conversation.resolved` and `conversation.opened`

**Comment by pranavrajs** [comment]
@meaziz @sojan-official I'm taking this up
