### ISSUE TITLE
suport for google messages - GMB - maps

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#4971]
**Describe the solution you'd like**
Suport for chat that google my business has in google maps.

**Describe alternatives you've considered**

![image](https://user-images.githubusercontent.com/99494469/177224370-d8825279-390c-4c29-9f33-42054adb4f6d.png)

**Additional context**
https://developers.google.com/business-communications/business-messages/guides
https://businessmessages.google/
https://support.google.com/business-messages#topic=11040494
https://support.google.com/business-messages/community?hl=en

**Comment by pranavrajs** [comment]
Duplicate #2336
