### ISSUE TITLE
Enhancement:  Agent auto assignment setting

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#498]
**Is your enhancement request related to a problem? Please describe.**
It's really hard to understand agent auto-assign logic. 

**Describe the solution you'd like**
- [ ] admin setting to enable/disable agent auto-assign 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by pranavrajs** [comment]
@sojan-official Can you make Agent auto assignment a project and 3 separate tickets for the line item you mentioned?

**Comment by bfitec** [comment]
This would be really nice! Due to the severity of each request we get in we generally like our entire team to be notified about a support chat and the agent assignment right now doesn't work well if someone on our team is out of the office for lunch/vacation/sick or whatever reason.

**Comment by pranavrajs** [comment]
Fixed via #513
