### ISSUE TITLE
Invalid token Platform API

### ISSUE THREAD

**Issue by vitos88** [chatwoot/chatwoot#4985]
can't create registration using API
received the token using the command
app = PlatformApp.create(name: 'name')
app.access_token.token
token Nv8RQAfYFXFmdV5MYt4x3hVP1
  I use in postman

curl --location --request 
    POST 'https://chatwoot.
    gotoguybot.ru/platform/
    api/v1/accounts' \
--header 'Content-Type: 
    application/json' \
--header 'api_access_token: 
    Nv8RQAfYFXFmdV5MYt4x3hVP'
     \
--data-raw '{
    "name": "test666"
}'

result
inavalid access_token
use
Docker version 20.10.17, build 100c701
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0 x86_64)

**Comment by pranavrajs** [comment]
Closing this as there are clear steps to reproduce the issue. Please feel free to reopen using the issue template.
