### ISSUE TITLE
Import contact, attachament not working

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#4991]
Hi,

We are using Helm cart kubernetes GCP. 
Two issues which we are facing,
1. Unable to import users from csv (even tried sample file also, and still same) 
2. Unable to download attachment, throwing error "page can’t be found"

I have attached screenshots here

![image](https://user-images.githubusercontent.com/38554929/177794832-a31de6d8-148a-47ba-aaae-81b84c7695ce.png)
![image](https://user-images.githubusercontent.com/38554929/177794873-6ef49a63-1e46-4f65-bc57-9fe756c53aa4.png)
![image](https://user-images.githubusercontent.com/38554929/177794911-6b0c4a80-3bff-488a-90e3-d7a822b2dadf.png)

**Comment by vishnu-narayanan** [comment]
This is resolved after setting up ActiveStorage to GCS[1]. 

1. https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers#using-google-gcs
