### ISSUE TITLE
Whatsapp template missing variables for header and call to action urls

### ISSUE THREAD

**Issue by pucilpet** [chatwoot/chatwoot#4995]
**Describe the bug**

We can't send template messages with a variable in the header or in the call to action url. Should add the header variables at least because I think those are used a lot with the template messages.

Missing header object and button object from the spec.

Ref:
https://github.com/chatwoot/chatwoot/blob/a6c609f43db296ed55aecbc28503ddb4c96651a1/spec/services/whatsapp/providers/whatsapp_cloud_service_spec.rb#L69

https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#header-object

https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates#interactive

**To Reproduce**

1. Create a Whatsapp template message on Cloud API with variables in the header and or link
2. Send a Whatsapp template message from Chatwoot with the created template.
3. You will be asked for the body variables only
4. No message is sent

**Expected behavior**

Chatwoot should ask for the header and url variables, too on the template message send popup.

**Server logs**

Number of parameters does not match the expected number of params","type":"OAuthException","code":132000,"error_data":{"messaging_product":"whatsapp","details":"header: number of localizable_params (0) does not match the expected number of params (1)"},"error_subcode":2494073,

**Additional context**

Other option would be to add info to documentation that the used Whatsapp templates can only include variables in the body, not header or url.

**Comment by pranavrajs** [comment]
@pucilpet Does it show such templates? I believe we filter those set of WhatsApp templates in the UI.

**Comment by pucilpet** [comment]
@pranavrajs Yes, those templates with the header variables are shown. 

Some templates are missing though, but those are at the end of the list (so maybe there's a limit on how many we can get).

**Comment by sojan-official** [comment]
closing in favour of https://github.com/chatwoot/chatwoot/issues/6867
