### ISSUE TITLE
application won't restart after upgrade

### ISSUE THREAD

**Issue by leoniscsem** [chatwoot/chatwoot#4998]
**Describe the bug**

After upgrading Chatwoot to the latest version (2.6.0) and Ruby to 4.0.4, the system would not start anymore via systemd, as the journal log says there is already a server running.

**To Reproduce**

1. `sudo systemctl restart chatwoot.target`
2. go to domain
3. find nginx throwing an error 502

**Expected behavior**

Starting the systemd should deliver a Chatwoot instance.

**Log**
`journalctl -u chatwoot-web.1.service -f`

```
Jul 08 13:18:02 cloud systemd[1]: chatwoot-web.1.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 13:18:02 cloud systemd[1]: chatwoot-web.1.service: Failed with result 'exit-code'.
Jul 08 13:18:04 cloud systemd[1]: chatwoot-web.1.service: Scheduled restart job, restart counter is at 890.
Jul 08 13:18:04 cloud systemd[1]: Stopped chatwoot-web.1.service.
Jul 08 13:18:04 cloud systemd[1]: Started chatwoot-web.1.service.
Jul 08 13:18:06 cloud chatwoot-web.1[206996]: => Booting Puma
Jul 08 13:18:06 cloud chatwoot-web.1[206996]: => Rails 6.1.5.1 application starting in production
Jul 08 13:18:06 cloud chatwoot-web.1[206996]: => Run `bin/rails server --help` for more startup options
Jul 08 13:18:06 cloud chatwoot-web.1[206996]: A server is already running. Check /path/to/chatwoot/tmp/pids/server.pid.
Jul 08 13:18:06 cloud chatwoot-web.1[206996]: Exiting
```

**Environment**

Self hosted installation of Chatwoot. Linux VM on Ubuntu 20.04. Postgresql 14, Ruby 4.0.4 on rvm, 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 100]

**Comment by vishnu-narayanan** [comment]
@leoniscsem Some processes must have crashed. Could you try to kill the rails server process manually and then restart the `chatwoot` service?

```
kill -9 $(lsof -i tcp:3000 -t)
systemctl restart chatwoot.target
```

**Comment by vishnu-narayanan** [comment]
Please reopen if the issue persists.
