### ISSUE TITLE
View all notifications is broken 

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#5030]
**Describe the bug**

Text overflow in View all Notifications

**To Reproduce**

Send a long private note to another agent.

**Expected behavior**

Truncated text or show full text on hover.

**Screenshots**
![Screenshot 2022-07-13 at 4 17 00 PM](https://user-images.githubusercontent.com/1219448/178716686-060678d3-0690-4202-aa5e-510b913f0e94.png)

**Comment by pranavrajs** [comment]
@iamsivin Can you please take a look at this and see if you can reproduce the issue?

**Comment by iamsivin** [comment]
> @iamsivin Can you please look at this and see if you can reproduce the issue?
> 
> 
> 
> 
> 
> If it is an easy fix, let us push it on the update on Friday.

Sure
