### ISSUE TITLE
Hide widgets if all agents are offline

### ISSUE THREAD

**Issue by noezdev** [chatwoot/chatwoot#5063]
**Is your feature request related to a problem? Please describe.**
Some operators use Chatwoot only as a pure, instant live chat and not for continuous communication. Outside of agent online hours, some Chatwoot operators may want the customer to use an alternative contact method on the website and not send any further messages in the chat, as the user may then be frustrated by the lack of a response. 

**Describe the solution you'd like**
A Chatwoot operator should be able to specify that the live chat widget is hidden, optionally, if all agents are offline. Thus, no further requests can be made by customers. As soon as an agent is online again, the widget appears again. So that only positive & fast experiences are made with the live chat on the website.

**Describe alternatives you've considered**
All possibilities with the SDK have been tested & exhausted. Such a function does not exist.

**Additional context**

**Comment by sojan-official** [comment]
Tracking this over here: https://github.com/chatwoot/chatwoot/issues/273
