### ISSUE TITLE
Handoff Push

### ISSUE THREAD

**Issue by noezdev** [chatwoot/chatwoot#5077]
**Is your feature request related to a problem? Please describe.**
For example, if you have set up a bot via Dialogflow, an agent will no longer receive a push notification about a new conversation. In this respect, this also makes sense, since the bot can solve the problem on its own if necessary. However, such a push notification should be sent at the latest after the bot sets the chat to handoff mode. If no auto-assignment has been activated for a team, the conversation would otherwise be completely lost, since no one would be notified.

**Describe the solution you'd like**
Sending the initial push notification after the bot has set a call to handoff mode for the first time.

**Describe alternatives you've considered**
Currently, we also send a push notification via Telegram when creating a chat so that no message is lost.

**Additional context**

**Comment by Jatin-MYST** [comment]
@noezdev if you are on self-hosted see my solution on #7587

**Comment by sojan-official** [comment]
closing in favor of #7587
