### ISSUE TITLE
bug: Sending Audio messages not working in Whatsapp Cloud

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#5078]

**Comment by giquieu** [comment]
@sojan-official 
Anyone working on this? I can investigate if needed.

**Comment by sojan-official** [comment]
@giquieu  not at the moment. That would be super helpful. ❤️

**Comment by drdaga** [comment]
> @sojan-official Anyone working on this? I can investigate if needed.

i checked actually audio file type should not pass caption parameter

i written simple if else 

`def send_attachment_message(phone_number, message)

    attachment = message.attachments.first
    type = %w[image audio video].include?(attachment.file_type) ? attachment.file_type : 'document'
    attachment_url = attachment.download_url
    if type == "audio"
      response = HTTParty.post(
      "#{phone_id_path}/messages",
      headers: api_headers,
      body: {
        messaging_product: 'whatsapp',
        'to' => phone_number,
        'type' => message.attachment_type,
        message.attachment_type.to_s => {
          'link': attachment_url,
        }
      }.to_json
    )
    else
      response = HTTParty.post(
        "#{phone_id_path}/messages",
        headers: api_headers,
        body: {
          messaging_product: 'whatsapp',
          'to' => phone_number,
          'type' => message.attachment_type,
          message.attachment_type.to_s => {
            'link': attachment_url,
            'caption': message.content
          }
        }.to_json
      )
      end
    process_response(response)
  end`

**Comment by sojan-official** [comment]
@drdaga Thanks for the findings. Would you be interested in raising a PR? or should we take it up?

**Comment by giquieu** [comment]
@drdaga @sojan-official 
If you don't mind, I sent the PR.
As we send the media type as audio, Whatsapp renders it as a single audio file. To render as a recording, we would need to change the media type to voice to send as a voice recording.

**Comment by drdaga** [comment]
> I have consulted the documentation, and you are right not to send the caption to Cloud API. For Twilio it is not necessary. For D360 within the documentation it says nothing about captioning.
> 
> About the .amr serialization, did you get to validate or implement something?
> 
> Twilio

abt Twilio & D360 they are hosted whatsapp api so even if we send caption they will ignore it
and cloud whatsapp api it its send directly to meta server so it will have an error
@giquieu u can send the pr no problem as i dont knw much abt coding its jst as hobby by profession i am doctor implemented chatwoot for our hospital and our consulting doctors so using chatwoot

**Comment by drdaga** [comment]
> Nice @drdaga , I have consulted the documentation, and you are right not to send the caption to Cloud API. For Twilio it is not necessary. For D360 within the documentation it says nothing about captioning.
> 
> About the .amr serialization, did you get to validate or implement something?
> 
> Twilio ![image](https://user-images.githubusercontent.com/9892674/181249494-869b64be-b858-4b0c-8826-d544e2f694ff.png)
> 
> Cloud API ![image](https://user-images.githubusercontent.com/9892674/181249646-89cb8cf9-1d1f-464f-981e-015c6cbf608e.png)

also abt .amr its jst dont playback within chatwoot inteference
even .amr files gets uploaded bt doesnt playbacks thats only issue remaining
if we jst convert of even change .amr filename to .mp3 it can be played
