### ISSUE TITLE
Wrong report count

### ISSUE THREAD

**Issue by noezdev** [chatwoot/chatwoot#5085]
**Describe the bug**

If you have a conversation and then delete the contact, the sent messages still count in the report. However, the number of conversations and incoming messages are displayed correctly.

**To Reproduce**

1. Chat with a contact (Send 100 messages (in/out for example)
2. Delete the contact
3. Go to reports

**Screenshots**

X
**Browser logs**

X
**Server logs**

Share the server logs to debug the issue further

**Environment**

app.chatwoot & local

**Desktop (please complete the following information):**
X
**Smartphone (please complete the following information):**
X
**Additional context**

**Comment by substr2837** [comment]
Can I work on this issue?

**Comment by sojan-official** [comment]
This should be resolved in https://github.com/chatwoot/chatwoot/pull/5236. 
Since we fixed the issues with dependant, destroy of conversations and messages
