### ISSUE TITLE
Missing translation in widget

### ISSUE THREAD

**Issue by noezdev** [chatwoot/chatwoot#5089]
**Describe the bug**

If you had a conversation and open a new one as a contact you'll see a form which has a text, that is not translated.

"Share your queries or comments here."

**To Reproduce**

1. Open a conversation
2. Chat
3. Close
4. Open a new one

**Screenshots**

**Browser logs**

**Server logs**

**Environment**
app.chatwoot & self hosted linux

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
<img width="619" alt="Screenshot 2022-07-26 at 10 51 32 AM" src="https://user-images.githubusercontent.com/2246121/180929423-3e3fad42-5124-4cb0-9a00-9d0d7efd9d55.png">


@noezdev This content can be edited in Inbox Settings.

**Comment by noezdev** [comment]
Then you should convert my request into a bug report. Because the message is still shown also if you have disabled pre-chat form when a guest is opening a new conversation after a previous conversation has been resolved.

**Comment by pranavrajs** [comment]
Can you please share a screenshot?

**Comment by noezdev** [comment]
Sure,

![Bildschirmfoto 2022-07-28 um 08 08 50](https://user-images.githubusercontent.com/21970985/181432911-c38f05f1-a990-4959-a659-56cb1d3b80bf.png)
