### ISSUE TITLE
enhancement: Twitter channel: option to disable greeting and away messages for incoming tweets

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#5093]
**Is your enhancement request related to a problem? Please describe.**
Right now, the greeting and away messages are triggered for incoming tweets and DMs, which may sound inconvenient in the case of tweets.

**Describe the solution you'd like**
Add an option to disable greeting and away messages when the incoming conversation is a tweet.

**Describe alternatives you've considered**
Completely disabled greeting and away messages for Twitter channels.

**Comment by voko3456** [comment]
@pranavrajs If this really happened it should be fixed asap and disable greeting and away message for tweets otherwise the Twitter app will be restricted from Twitter and will not work again because it's vaioliting the twitter app policy

**Comment by sojan-official** [comment]
@WevrLabs, which version of Chatwoot are you using? 
Greeting and away messages won't get triggered for tweets.
