### ISSUE TITLE
After upgrade 2.7, unable to load chats

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5096]
Hi,
we are using GCP Helm Charts, after we upgraded from 2.5 to 2.7, somehow it stuck and unable to load the chats, but we can see the contacts. 
I have attached screenshots also - 

<img width="1206" alt="chatwoot stuck on loading" src="https://user-images.githubusercontent.com/38554929/180489046-c6c255ae-8071-4ea6-af6d-67fd03b6e225.png">

Logs - 
![image](https://user-images.githubusercontent.com/38554929/180489110-d44c7242-a713-4a3e-b352-0d6f90f9c3a9.png)

**Comment by sojan-official** [comment]
@harismateen, the error noted in the screenshot looks unrelated.  Could you go to the network console in your browser and see if there are any errors there while loading the /conversations endpoints ?

**Comment by harismateen** [comment]
@sojan-official we received 500 status code, with internal server error

**Comment by sojan-official** [comment]
@harismateen Could you share the error logs of that?  The logs currently shared are of dashboard apps, which seem different.

**Comment by DoctorOnCall** [comment]
![image](https://user-images.githubusercontent.com/41385546/183350835-77a7530a-0aa0-43f3-a019-6c7bb6d6825d.png)

**Comment by DoctorOnCall** [comment]
![image](https://user-images.githubusercontent.com/41385546/183384516-7e86d91b-1d21-4d0d-bd99-91455980c56c.png)
This is what we received on our console logs

**Comment by sojan-official** [comment]
@DoctorOnCall  could you share the server logs instead? The browser logs don't have the information about what is triggering the 500 errors on the server side.

**Comment by h33raj** [comment]
![image](https://user-images.githubusercontent.com/9161506/183553624-0980cf20-4060-4bad-8bd1-e6b2028ab673.png)

This is what I could get from server logs

**Comment by h33raj** [comment]
Any further updates on this, anyone else facing this issue?

**Comment by harismateen** [comment]
@sojan-official Hi sojan - can assist us on above issue please?

**Comment by sojan-official** [comment]
@h33raj  it seems like one of the migrations hasn't been run properly. Could you try running `bundle exec rake db:migrate`  in your installation?

**Comment by harismateen** [comment]
@sojan-official the above solution works but we encountered one more issue now, 
We cant add new channel, and network showing 500

PFA as attached screenshot: 
![image](https://user-images.githubusercontent.com/38554929/185059414-61c4a29a-ba77-43af-895e-850dd589da2a.png)

**Comment by sojan-official** [comment]
@harismateen  make sure the information you provide for the WhatsApp channel is correct. 
ref: https://www.chatwoot.com/docs/product/channels/whatsapp/whatsapp-cloud 
ref: https://github.com/chatwoot/chatwoot/issues/5094 

Closing this issue as original problem is resolved

**Comment by harismateen** [comment]
@sojan-official we cant even add any channel now, included webchat, whatsapp etc. it throws 500 error. This happened after we upgraded from 2.5 to 2.7

**Comment by sojan-official** [comment]
@harismateen, could you share the logs from the server instead? the current screenshots doesn't have enough information to debug.

**Comment by harismateen** [comment]
@sojan-official PFA I have attached screenshots here,
Here we tried to add live chat and email channel, and still same error.

Pls do let me know if need more logs 
![image](https://user-images.githubusercontent.com/38554929/185352178-58ec642f-5988-44b7-a947-cf5d134eff91.png)
![image](https://user-images.githubusercontent.com/38554929/185352224-929ffc2c-4c01-4b05-923c-f4e2b8aceaf4.png)

**Comment by sojan-official** [comment]
@harismateen Seems like some of the migrations haven't been properly applied in your setup. Could you watch the logs when you are running `bundle exec rake db:migrate` and see if shows any errors? 

Also did you try restarting the instances after running `rake db:migrate`

**Comment by harismateen** [comment]
@sojan-official Thanks - this is resolved now :)
