### ISSUE TITLE
Fix "Rubocop/Metrics/MethodLength" issue in app/models/attachment.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#51]
Method has too many lines. [26/10]

https://codeclimate.com/github/chatwoot/chatwoot/app/models/attachment.rb#issue_5d87480c87cf190001000397

**Comment by jash-kothari** [comment]
Can i pick this up?

**Comment by pranavrajs** [comment]
Closing as it is completed.
