### ISSUE TITLE
Allow case insentitive start phrase for private notes from Slack integration

### ISSUE THREAD

**Issue by Ysajid** [chatwoot/chatwoot#5100]
**Is your enhancement request related to a problem? Please describe.**
I used capital-lettered "Note:" to have a private note to the team on a customer query from slack. But unfortunately, it was sent as an email.

**Describe the solution you'd like**
Allow both "Note:" and "Private:" to leave an internal msg from Slack.

**Describe alternatives you've considered**
N/A

**Additional context**
If this gets approved I can submit a PR. Probably a change in [this line](https://github.com/chatwoot/chatwoot/blob/develop/lib/integrations/slack/incoming_message_builder.rb#L80) will fix the issue.

**Comment by sojan-official** [comment]
@Ysajid  Sure. Please go ahead.

**Comment by Ysajid** [comment]
@sojan-official I've submitted a PR for this.
