### ISSUE TITLE
Plesk and Docker

### ISSUE THREAD

**Issue by genonioff** [chatwoot/chatwoot#5124]
Hello, how are you? I would like to know if your tool is available and functional on servers using Plesk & Docker? Thanks

**Comment by vishnu-narayanan** [comment]
@genonioff
> I would like to know if your tool is available and functional on servers using Plesk & Docker? 

We don't officially support running on Plex. We publish official docker images which you can use with your favourite orchestration tool. 

 Please find the list of officially supported deployment options at https://www.chatwoot.com/deploy/
