### ISSUE TITLE
whatsapp cloud api and 360dialog templates not loaded in chatwoot after approved and wait more than 24 hr 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5129]
i have identified the issue that only if i create template via api it will not load in chatwoot but when i create it via whatsapp manager it load after 15 minutes this case is only for cloud api but for 360dialog its not load even if i create it from 360dialog gui its better to make cron job to call message_templates endpoint and load them in chatwoot write now i think its load template via template created webhook event

**Comment by burhankashour** [comment]
+1

**Comment by sojan-official** [comment]
Closing this as there hasn't been a recent occurrence of this.
