### ISSUE TITLE
Infinite looping with mailboxes with no-reply addresses

### ISSUE THREAD

**Issue by hiagodotme** [chatwoot/chatwoot#5131]
**Is your feature request related to a problem? Please describe.**
When an email arrives and the reply is set to a no-reply box, chatwoot and the server that originated the message keep exchanging messages non-stop. Literally an "infinite loop". This is because chatwoot inbox has auto reply setting.

**Describe the solution you'd like**
A solution would be to analyze the subjects and the email addresses, ignoring standard boxes like noreply, no-reply... This of course allowing administrators to create complementary rules, I believe that a tab in the configuration of the email box with the name of "filter".

The interesting thing is that sometimes these emails can even arrive, what could be disabled is just the auto-response and messages from the attendants.

**Describe alternatives you've considered**
Currently I have disabled auto-response.

**Additional context**
![](https://cdn.discordapp.com/attachments/650257251856285707/1001848366059245668/unknown.png)

**Comment by pranavrajs** [comment]
@hiagodotme Can you please share the version of Chatwoot you are using?

**Comment by hiagodotme** [comment]
@pranavrajs the last version `2.7.0-ce`.

**Comment by sojan-official** [comment]
We have added changes to prevent email looping in latest releases. hence closing this issue. We will reopen if this persists !!!
