### ISSUE TITLE
Overflow set to scroll on various places on dashboard

### ISSUE THREAD

**Issue by venarius** [chatwoot/chatwoot#514]
**Describe the bug**
When you hover certain areas in the dashboard UI with your mouse, a scrollbar comes up even though the content is not overflowing. That is caused on various places because of the `overflow: scroll` on :hover. A better option would be `overflow: auto` so that it only scrolls when the content is actually overflowing.

If that's an actual bug and not intended I will happily fix this issue 😀 

**To Reproduce**
1. Hover with mouse on e.g. the sidebar in the dashboard UI.
2. You will see a scrollbar popup

**Expected behavior**
The scrollbar should only popup if the content is actually overflowing. Otherwise it just looks bad.

**Screenshots**
https://i.gyazo.com/6dc6f39817ca0d923b2b6bdec3a8ffac.mp4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 80.0.3987.106

**Comment by nithindavid** [comment]
Hey @venarius, I couldn't reproduce this on my side but it looks like your suggestion is better. You can take this up :) Thanks 👍
