### ISSUE TITLE
stop at linking with Facebook

### ISSUE THREAD

**Issue by chenlei9907** [chatwoot/chatwoot#5147]
I am setuping up with Facebook,
Chatwoot run in docker-compose dev mode, self hosted.

In FB app side, i have setup Handover Protocol to use my App as primary. All APP id/secret/verify token has setup on both FB side and Chatwoot env side. Also turn on the "Require app secret" in FB APP adv settings.

When i add messager as Inbox in Chatwoot,  normal login FB, everything looks good. Until FB windows close, then Chatwoot just showing "Authenticating you with Facebook..." and stop here 
![Screen Shot 2022-07-28 at 11 02 49 PM](https://user-images.githubusercontent.com/43410994/181693243-875fe4ed-7691-4bb8-86b0-d6fb074a859d.png)

And docker logs shows that 

`rails_1     | Started POST "/api/v1/accounts/1/callbacks/facebook_pages.json" for 207.81.205.22 at 2022-07-29 05:49:09 +0000
rails_1     | Cannot render console from 207.81.205.22! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails_1     | Processing by Api::V1::Accounts::CallbacksController#facebook_pages as JSON
rails_1     |   Parameters: {"omniauth_token"=>"[FILTERED]", "account_id"=>"1", "callback"=>{"omniauth_token"=>"[FILTERED]"}}
rails_1     | Completed 500 Internal Server Error in 239ms (ActiveRecord: 1.9ms | Allocations: 7055)
rails_1     |
rails_1     |
rails_1     |
rails_1     | Koala::Facebook::ClientError (type: GraphMethodException, code: 100, message: API calls from the server require an appsecret_proof argument, x-fb-trace-id: B40ChqGx50w [HTTP 400]):
rails_1     |
rails_1     | /app/app/controllers/api/v1/accounts/callbacks_controller.rb:23:in `facebook_pages'
rails_1     | /app/app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | /app/app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
rails_1     | /app/app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
rails_1     | /app/app/controllers/concerns/switch_locale.rb:24:in `set_locale'
rails_1     | /app/app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
rails_1     | Started GET "/cable" for 207.81.205.22 at 2022-07-29 05:49:13 +0000
rails_1     | Cannot render console from 207.81.205.22! Allowed networks: 127.0.0.0/127.255.255.255, ::1
rails_1     | Started GET "/cable/" [WebSocket] for 207.81.205.22 at 2022-07-29 05:49:13 +0000
rails_1     | Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
rails_1     | Finished "/cable/" [WebSocket] for 207.81.205.22 at 2022-07-29 05:49:13 +0000
rails_1     | RoomChannel#update_presence
rails_1     | RoomChannel#update_presence
`
When i first time setup with FB is working, but didn't receive message from FB page. so I delete the old one in Chatwoot. When I 2nd time to create the FB as inbox in Chatwoot, then it stop there.

Also when use FB webhook send test message to my Chatwoot server /bot, it works, Chatwoot can receive it, so it looks like the issue on Chatwoot side 

`RoomChannel#update_presence
RoomChannel#update_presence
RoomChannel#update_presence
Started POST "/bot" for 69.63.189.120 at 2022-07-29 06:08:04 +0000
Cannot render console from 69.63.189.120! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Enqueued Webhooks::FacebookEventsJob (Job ID: ba6891b7-4c27-43cc-a9b2-214a38796139) to Sidekiq(default) with arguments: "{\"messaging\":{\"sender\":{\"id\":\"12334\"},\"recipient\":{\"id\":\"23245\"},\"timestamp\":\"1527459824\",\"message\":{\"mid\":\"test_message_id\",\"text\":\"test_message\"}}}"
Started GET "/cable" for 207.81.205.22 at 2022-07-29 06:08:07 +0000
Cannot render console from 207.81.205.22! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Started GET "/cable/" [WebSocket] for 207.81.205.22 at 2022-07-29 06:08:07 +0000
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
Finished "/cable/" [WebSocket] for 207.81.205.22 at 2022-07-29 06:08:07 +0000`

Any idea where is wrong ? 

Also, there is one more thing, What's the difference between 3 FB related varible in ENV and the setting in super_admin?
![Screen Shot 2022-07-28 at 11 13 07 PM](https://user-images.githubusercontent.com/43410994/181694597-5be6de86-e498-4167-91e1-c2b7a65b32dd.png)

Thanks

**Comment by sojan-official** [comment]
@chenlei9907 apologizes for missing out on this issue. are you still facing it? 

There is no difference between the configuration apart from that environment variables have higher priority than the installation config.

**Comment by AronikTV** [comment]
I'm facing the same issue. I closed the Facebook login window. Now when I try to redo the instagram setup process it just waits for the authentication with Facebook but doesn't open the window.

![image](https://user-images.githubusercontent.com/68695323/228790287-060f98b4-cebb-46a0-acc4-609938e252a7.jpeg)

**Comment by sojan-official** [comment]
@AronikTV see if you have pop up blockers enabled ?

**Comment by sojan-official** [comment]
@AronikTV  Thanks for the revert. Closing this since original issue is resolved
