### ISSUE TITLE
Feature: Send an email to all inbox members if auto assignment is turned off for the inbox

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#515]
### Premise

If you have an inbox with auto assignment turned off, all members of the inbox should get a notification saying that there is a new conversation in the inbox.

@sojan-official We need to decide the content of the email.

**Comment by sony-mathew** [comment]
@pranavrajs I'm taking this up and starting work on this.

**Comment by sojan-official** [comment]
We will be introducing email notification settings for each agent where they can control the emails which they want to receive.

**Comment by sojan-official** [comment]
agents can opt for email notifications on conversation creation now.

![Screenshot 2020-03-01 at 7 06 55 PM](https://user-images.githubusercontent.com/73185/75626704-d52c8f00-5bef-11ea-8411-8620f58eec54.png)
