### ISSUE TITLE
Search requests timeouts, backing up other requests in queue. 

### ISSUE THREAD

**Issue by kurtsudonumcom** [chatwoot/chatwoot#5161]
**Describe the bug**

Wanted to report a possible issue with the frontend search utilising the the `api/v1/conversation/search/` endpoint. 

We have over ~4M messages, and what we experience when agents hit the search endpoint to frequently, there seems to be a delay and eventual timeout - looking at the logs the tasks exceeds the 15s and timesout, and subsequent requests such as `toggle_status` or `assignment` would also eventually timeout. For agent using the frontend they would logged out.

**To Reproduce**

I managed to replicate this on our staging, where we hit the search endpoint atleast 10 times, while sending atleast 1000 toggle statuses from pending to open to simulate when the box is under load. Within that loop to complete 10 search - all returns 500s, while the first ~250 requests to toggle status returns 200s and then the rests of returns 500s.

**Expected behavior**

Could search in particular be able to hit up an elasticsearch instance instead? 

**Server logs**

```
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: F, [2022-07-27T05:27:17.775501 #2125258] FATAL -- : [3a25ccb2-cd44-49dc-aeb8-4fe517af0544]
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: [3a25ccb2-cd44-49dc-aeb8-4fe517af0544] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ): <--- notice this is 15sec for awaiting 
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: [3a25ccb2-cd44-49dc-aeb8-4fe517af0544]
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: [3a25ccb2-cd44-49dc-aeb8-4fe517af0544] app/finders/conversation_finder.rb:118:in `set_count_for_all_conversations'
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: [3a25ccb2-cd44-49dc-aeb8-4fe517af0544] app/finders/conversation_finder.rb:26:in `perform'
Jul 27 05:27:17 chatwoot chatwoot-web.1[2125258]: [3a25ccb2-cd44-49dc-aeb8-4fe517af0544] app/controllers/api/v1/accounts/conversations_controller.rb:20:in `search'
```

**Environment**

- Self hosted installation of Chatwoot. 
- Linux VM installation
- 2x EC2 instances behind AWS loadbalancer

**Additional context**

We've increase the default `10` concurrency to `20` and this seems to be working for now, we've also added a rate linter to `*/conversations/search*` path to be safe.

**Comment by sojan-official** [comment]
@kurtsudonumcom Thanks for the detailed write up.  We are reworking the current search under https://github.com/chatwoot/chatwoot/issues/5913 . Let's track the progress over there.
