### ISSUE TITLE
gpg: keyserver receive failed: no keyserver available

### ISSUE THREAD

**Issue by TuxADN** [chatwoot/chatwoot#5165]
**Describe the bug**

I'm trying to install Chatwoot on a fresh ubuntu 20.04 but I'm receiving this error in the installation log:

gpg: keyserver receive failed: no keyserver available

The installation stops and exits to the console.

Please advise how to resolve this situation.

**To Reproduce**

Just plain brand new installation in a fresh Ubuntu server, following instructions described here:
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

**Expected behavior**

A complete new Chatwoot installation

**Screenshots**

N/A

**Browser logs**

N/a

**Server logs**
/var/log/chatwoot-setup.log

...
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
postgresql is already the newest version (12+214ubuntu0.1).
postgresql-contrib is already the newest version (12+214ubuntu0.1).
redis-server is already the newest version (5:5.0.7-2ubuntu0.1).
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
nginx is already the newest version (1.18.0-0ubuntu1.3).
certbot is already the newest version (0.40.0-1ubuntu0.1).
nginx-full is already the newest version (1.18.0-0ubuntu1.3).
python3-certbot-nginx is already the newest version (0.40.0-0ubuntu0.1).
The following package was automatically installed and is no longer required:
  libfwupdplugin1
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1000
**gpg: keyserver receive failed: No keyserver available**

**Environment**

Ubuntu 20.04 brand new server

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

N/A

**Comment by vishnu-narayanan** [comment]
Could you please confirm the version of the install script you are using?

```
./install.sh --version
```

**Comment by TuxADN** [comment]
Hello, this is the output:

cwctl v2.1.0 alpha build

Thanks
R

**Comment by TuxADN** [comment]
I've comment out lines related to keyserver (# 242 and 243)
Then issued these commands at the console
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

They were successfully applied.
But not sure if this will work fine, please advise.

Then I run the installation again and this time it completed successfully.

I'll stand by your comments, before I continue configuring this instance.
I rather prefer start all over again with a proper solution or confirmation from your side.

**Comment by vishnu-narayanan** [comment]
@TuxADN I just tried to replicate this and was unable to. The installation went fine. I assume the keyservers must have timed out or something when you ran.

>Then issued these commands at the console
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
They were successfully applied.
But not sure if this will work fine, please advise.
Then I run the installation again and this time it completed successfully.
I'll stand by your comments, before I continue configuring this instance.

The instance should be good to use since you were able to complete the installation.

**Comment by TuxADN** [comment]
If one try to run the related command, listed in the installation script in the lines 242 and 243

Command:
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

Response:
gpg: keyserver receive failed: No keyserver available


BUT, if I run the above mentioned command that I found as an alternative:
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

Response:
Executing: /tmp/apt-key-gpghome.x6tHwr6Xeo/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: Total number processed: 1
gpg:              imported: 1


So far the instance is working fine, as the result of running the alternative command.

**Comment by vishnu-narayanan** [comment]
>If one try to run the related command, listed in the installation script in the lines 242 and 243
Command:
gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
Response:
gpg: keyserver receive failed: No keyserver available

I am not able to reproduce this issue. As you can see, the `gpg` command is successful.
```
ubuntu@ip-172-31-75-119:~$ gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: directory '/home/ubuntu/.gnupg' created
gpg: keybox '/home/ubuntu/.gnupg/pubring.kbx' created
gpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created
gpg: key 3804BB82D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

>BUT, if I run the above mentioned command that I found as an alternative:
So far the instance is working fine, as the result of running the alternative command.

That is perfectly fine. The instance is good to go. 

Thank you for reporting this issue. Will keep a watch if other users are experiencing and modify the installer accordingly.
