### ISSUE TITLE
http links are not visible in vistor windows

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#519]
**Describe the bug**
When an agent send to visitor an link, at the visitor is white text on white
**To Reproduce**

**Expected behavior**
See link text
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aermike** [comment]
<img width="2320" alt="chatwoot" src="https://user-images.githubusercontent.com/4247309/74829086-eedcf500-5318-11ea-9941-475c9e3fe96b.png">

**Comment by venarius** [comment]
Will try to recreate it 👍
