### ISSUE TITLE
Small Screen Resolution => Tab PopUp

### ISSUE THREAD

**Issue by hugodeco** [chatwoot/chatwoot#5193]
This Tab is not useful for agents, and should be popup or collapsed on small screen resolutions.
This will improve the conversations view tab. 

This is not an issue on wide screen resolutions.

![2022-08-03](https://user-images.githubusercontent.com/2934665/182632778-a128571d-a7d8-4ffd-89aa-fa6d97ac87d3.png)

Maybe, popup this tab on click at chatwoot logo ?!

**Comment by iamsivin** [comment]
Closing this issue since it's fixed by PR https://github.com/chatwoot/chatwoot/pull/5400
