### ISSUE TITLE
vuex-router-sync has known security issues

### ISSUE THREAD

**Issue by dragma** [chatwoot/chatwoot#5199]
Hi everyone !

Today, the actual version of [vuex-router-sync](https://github.com/vuejs/vuex-router-sync/tree/v4.1.0) used for chatwoot has a high severity security issue of type Cross-site Scripting (XSS).

![image](https://user-images.githubusercontent.com/4975026/182801808-8bad9454-f700-4841-9b5d-283ac657c08f.png)

The only solution we have is to migrate `vuex-router-sync v0.4.2` to version [`6.0.0-rc.1`](https://github.com/vuejs/vuex-router-sync/tree/v6.0.0-rc.1), which seems no being impacted by any security issues (for now).

Since this upgrade implies breaking changes, and because I'm not a vue developper, this issue is more or like a request.

**Comment by pranavrajs** [comment]
@dragma Can you please post the link to the vulnerability? I couldn't find any relevant discussion in the repo.

**Comment by sojan-official** [comment]
Closing this as we have this in our internal tracker for upgrading the dependencies 
ref: https://github.com/chatwoot/chatwoot/pull/7953
