### ISSUE TITLE
Fix "Rubocop/Metrics/AbcSize" issue in app/controllers/passwords_controller.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#52]
Assignment Branch Condition size for set_headers is too high. [25.71/15]

https://codeclimate.com/github/chatwoot/chatwoot/app/controllers/passwords_controller.rb#issue_5d87480b87cf190001000335

**Comment by jash-kothari** [comment]
Can i pick this up?

**Comment by pranavrajs** [comment]
@jash-kothari Please go ahead, assign this issue to yourself and please start working on it, if you are interested. 

Please read the contributing guide as well. https://github.com/chatwoot/chatwoot/blob/master/docs/contributing.md

**Comment by AlexisChavez97** [comment]
Is this still open?
