### ISSUE TITLE
Log if the visitor has left/returned to the chat

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#5203]
**Is your feature request related to a problem? Please describe.**

Currently, we can't know for sure if the visitor is still on our widget or s/he has left the chat. 

**Describe the solution you'd like**

Log if the visitor has left/returned to the chat. 

![log](https://user-images.githubusercontent.com/99071637/182859801-5dd9418f-3186-4b5b-950a-b7de6352938a.JPG)

**Comment by substr2837** [comment]
Can I work on this issue?

**Comment by pranavrajs** [comment]
@ammaraslam @substr2837 We don't have the concept of leaving the chat. The customer can be online or offline. They can resolve the conversation themselves if they need. Leaving the conversation is a concept in live-chat providers where the session is not persistent. Let me know what you think

**Comment by ammaraslam** [comment]
@pranavrajs just tested the online/offline feature & its working perfectly. 

Closing this, thanks.
