### ISSUE TITLE
agent list not shown all agents

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#521]
**Describe the bug**
Am conversation is assigned to an agent
If I want to assign to other agent list is blank
**To Reproduce**

**Expected behavior**
<img width="964" alt="chatwoot-bug1" src="https://user-images.githubusercontent.com/4247309/74829256-509d5f00-5319-11ea-86b3-21670924b343.PNG">
<img width="2320" alt="chatwoot-bug2" src="https://user-images.githubusercontent.com/4247309/74829267-55621300-5319-11ea-9e3e-9f458eafff23.png">

All agents that are in same inbox are shown

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by venarius** [comment]
Hello @aermike,
have the agents you want to assign verified their email? You can only assign a conversation to a verified agent.

**Comment by aermike** [comment]
No
I don't have an agent with mail verified
Default user, which is an admin, can be assigned?

**Comment by venarius** [comment]
Yes

**Comment by pranavrajs** [comment]
@venarius Thanks for looking into this issue. 

@aermike Conversation can be assigned only to the verified agents or administrators. Hope that should resolve your query.

**Comment by aermike** [comment]
Yes
Thank you
