### ISSUE TITLE
Ghost notification?

### ISSUE THREAD

**Issue by arladmin** [chatwoot/chatwoot#5229]
The notification counter shows a non-zero value even though there aren't any notifications.

![image](https://user-images.githubusercontent.com/64059154/183565069-1792823e-a30c-47af-95e2-7a82d047dd69.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sojan-official** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot/issues/4285#issuecomment-1078874738 
We will track this in #4285
