### ISSUE TITLE
Installation Script (Linux VM)

### ISSUE THREAD

**Issue by gib1991** [chatwoot/chatwoot#5233]
**Describe the bug**

install.sh does not operate with 20:04 LTS download of ubuntu.

**To Reproduce**

1. Go to ubuntu - download latest 20:04 LTS image - install fresh in Hyper-V, static IP, pull the install.sh script.
2. Run the ./install.sh with tails open in another terminal
3. Wait a few moments
4. See error "## Your distribution, identified as "jammy", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support"

**Expected behavior**

Install fresh 20:04 LTS ubuntu, download and run install.sh and have a working instance afterwards.

**Screenshots**

N/A

**Browser logs**

Not browser related

**Server logs**

N/A

**Environment**

Self hosted, hyper-v vm with pre-requesits and ample resources attributed and assigned.

N/A

**Comment by gib1991** [comment]
[chatwoot-setup.log](https://github.com/chatwoot/chatwoot/files/9289496/chatwoot-setup.log)

**Comment by vishnu-narayanan** [comment]
@gib1991 Could you share the output of `lsb_release -a` ?

**Comment by gib1991** [comment]
![image](https://user-images.githubusercontent.com/100914854/183633307-a432f348-dbf6-417f-ab1b-741a1e0ae8aa.png)

**Comment by vishnu-narayanan** [comment]
The installer is supported and maintained on `Ubuntu 20.04` as of now. Could you please try this on a `Ubuntu 20.04` instance?

**Comment by gib1991** [comment]
I've had an awful morning, first my .iso selection was wrong, then i opted for a minimal install and cried wolf for not checking 
![image](https://user-images.githubusercontent.com/100914854/183635591-b36cd56a-2a19-4562-806c-ce2dfeb5eb32.png)
smh - i need coffee IV drip

**Comment by vishnu-narayanan** [comment]
haha no worries 😅 happens to all of us
