### ISSUE TITLE
SMTP authentication issue 535 when different smpt port is provided

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#5238]
**Describe the bug**

Chatwoot fails to send an email when the default SMTP port is changed from 587 to 25.

**To Reproduce**

1. Deploy chatwoot using helm charts
2. Change the SMTP related variables to the following
```
SMTP_ADDRESS="xxxxxxxx"
SMTP_PORT="25"
SMTP_USERNAME=""
SMTP_PASSWORD=""
SMTP_AUTHENTICATION= plain
SMTP_ENABLE_STARTTLS_AUTO= true
SMTP_OPENSSL_VERIFY_MODE= none
```
The username and password are expected to be empty here and should work as this config is working on other applications.

4. Try to send a password reset email.
6. See error
```
Net::SMTPAuthenticationError: 535 5.7.0 authentication failed
```

**Expected behavior**

Email should be sent.

**Screenshots**

n/a

**Browser logs**

n/a

**Server logs**

Share the server logs to debug the issue further

**Environment**

- Self-hosted
- Helm Charts version
- Chatwoot version 2.7.0

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Reported from a self-hosted user.

We were using Chatwoot `2.5.0` earlier and the error from sidekiq used to different. After updating to 2.7, we have the `535 Authentication error` from SMTP.

Previous error in `v2.5.0`
![image(1)](https://user-images.githubusercontent.com/3526167/183846187-fa31c0b7-ec84-409a-94d5-3b9c1332891c.png)

**Comment by vishnu-narayanan** [comment]
@aswindevps Could you please take a look?
cc: @pranavrajs

**Comment by vishnu-narayanan** [comment]
@dragma Could you try to update the deployment by removing  SMTP_USERNAME, SMTP_PASSWORD and SMTP_AUTHENTICATION variables and see if that helps?

ref: https://calvin.my/posts/rails-smtp-setting-without-authentication

cc: @pranavrajs

**Comment by dragma** [comment]
@vishnu-narayanan You were right !
It seems to be working just fine. Thank you very much  for your help !
I think we can close this issue.

**Comment by pranavrajs** [comment]
@dragma Great! Closing this.
