### ISSUE TITLE
When integrate  Dialogflow  

### ISSUE THREAD

**Issue by skyblue** [chatwoot/chatwoot#5248]
sorry, my mistake...

-----------------------
Follow the doc 
[dialogflow](https://www.chatwoot.com/docs/product/channels/live-chat/integrations/dialogflow)

**Server logs**

`
I, [2022-08-18T04:22:02.705537 #1]  INFO -- : [ActiveJob] [EventDispatcherJob] [5c0c125a-bc25-41da-8e15-946c0c3e9aa0] Enqueued HookJob (Job ID: 81a9cc17-fbe1-486c-867b-79d4b67e91be) to Sidekiq(integrations) with arguments: #<GlobalID:0x00007f1585768990 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/4>>, "message.created", {:message=>#<GlobalID:0x00007f158575fc00 @uri=#<URI::GID gid://chatwoot/Message/492661>>}

I, [2022-08-18T04:22:02.707901 #1]  INFO -- : [ActiveJob] [HookJob] [81a9cc17-fbe1-486c-867b-79d4b67e91be] Performing HookJob (Job ID: 81a9cc17-fbe1-486c-867b-79d4b67e91be) from Sidekiq(integrations) enqueued at 2022-08-18T04:22:02Z with arguments: #<GlobalID:0x00007f1585369c40 @uri=#<URI::GID gid://chatwoot/Integrations::Hook/4>>, "message.created", {:message=>#<GlobalID:0x00007f1585368fc0 @uri=#<URI::GID gid://chatwoot/Message/492661>>}

E, [2022-08-18T04:22:03.820139 #1] ERROR -- : [ActiveJob] [HookJob] [81a9cc17-fbe1-486c-867b-79d4b67e91be] undefined local variable or method `agent_bot' for #<Integrations::Dialogflow::ProcessorService:0x00007f1585357f90 @event_name="message.created", @hook=#<Integrations::Hook id: 4, status: "disabled", inbox_id: 4, account_id: 1, app_id: "dialogflow", hook_type: "inbox", reference_id: nil, access_token: "xxxxxxxxxxx", created_at: "2022-08-11 07:14:32.710750000 +0000", updated_at: "2022-08-11 07:14:32.710750000 +0000", settings: {"project_id"=>" faq-mnrk", "credentials"=>{"type"=>"service_account", "auth_uri"=>"https://accounts.google.com/o/oauth2/auth", "client_id"=>"106232592524815928083", "token_uri"=>"https://oauth2.googleapis.com/token", "project_id"=>"faq-mnrk", "private_key"=>"-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkxxxxxxx\n-----END PRIVATE KEY-----\n", "client_email"=>"xxxxx@faq-mnrk.iam.gserviceaccount.com", "private_key_id"=>"xxxxxx", "client_x509_cert_url"=>"https://www.googleapis.com/robot/v1/metadata/x509/faqbot2%40faq-mnrk.iam.gserviceaccount.com", "auth_provider_x509_cert_url"=>"https://www.googleapis.com/oauth2/v1/certs"}}>, @event_data={:message=>#<Message id: 492661, content: "HI", account_id: 1, inbox_id: 4, conversation_id: 76911, message_type: "incoming", created_at: "2022-08-18 04:22:02.619443000 +0000", updated_at: "2022-08-18 04:22:02.619443000 +0000", private: false, status: "sent", source_id: nil, content_type: "text", content_attributes: {}, sender_type: "Contact", sender_id: 1, external_source_ids: {}, additional_attributes: {}>}, @conversation=#<Conversation id: 76911, account_id: 1, inbox_id: 4, status: "pending", assignee_id: nil, created_at: "2022-08-18 04:22:02.594456000 +0000", updated_at: "2022-08-18 04:22:02.623571000 +0000", contact_id: 1, display_id: 76911, contact_last_seen_at: nil, agent_last_seen_at: nil, additional_attributes: {"browser"=>{"device_name"=>"Unknown", "browser_name"=>"Chrome", "platform_name"=>"macOS", "browser_version"=>"103.0.0.0", "platform_version"=>"10.15.7"}, "referer"=>nil, "initiated_at"=>{"timestamp"=>"Thu Aug 18 2022 12:22:02", "browser_language"=>"en"}, contact_inbox_id: 316108, uuid: "3909a36e-d4d0-42b8-bc3e-6173a67efb53", identifier: nil, last_activity_at: "2022-08-18 04:22:02.619443000 +0000", team_id: nil, campaign_id: nil, snoozed_until: nil, custom_attributes: {}, assignee_last_seen_at: nil, first_reply_created_at: nil, label_list: nil>>
`

**Environment**

chatwoot@2.7 on docker-compose

**Comment by pranavrajs** [comment]
@skyblue Can you please share the logs before and after this line?

**Comment by skyblue** [comment]
@pranavrajs  The log is updated.

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.

**Comment by sojan-official** [comment]
@skyblue Please try with the latest versions of Chatwoot meanwhile
