### ISSUE TITLE
Resolving a conversation should hide it from left pane

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#5256]
**Is your enhancement request related to a problem? Please describe.**
After resolving a conversation, it still shows in left pane

**Describe the solution you'd like**
On resolve, navigate from conversation detail
https://app.chatwoot.com/app/accounts/68045/inbox/16877/conversations/2
to inbox view
https://app.chatwoot.com/app/accounts/68045/inbox/16877

Thanks!

**Comment by pranavrajs** [comment]
@mariusa, I couldn't reproduce this. Would you be able to share a screencast of the behavior?

**Comment by mariusa** [comment]
Hi, thanks for looking into it. 
With the last conversation in inbox, at https://app.chatwoot.com/app/accounts/68045/inbox/16877/conversations/2
I clicked Resolve.
Conversation subject disappears from left pane, but remains on the right, and URL remains unchanged.
Attaching 2 screens, right before and after clicking Resolve.

![2022-08-18_13-17](https://user-images.githubusercontent.com/1283842/185373296-d8e66456-3aab-47be-99aa-0290b461d13d.png)
![2022-08-18_13-18](https://user-images.githubusercontent.com/1283842/185373309-2bd85b3d-6aa6-46ef-bec3-3ecdbc6712b8.png)

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/4068
