### ISSUE TITLE
[CW-1720] Poor error throwing in conversation filter api

### ISSUE THREAD

**Issue by shawshankkumar** [chatwoot/chatwoot#5266]
**Is your enhancement request related to a problem? Please describe.**
https://app.chatwoot.com/api/v1/accounts/{account_id}/conversations/filter When a user hits this route, more often than not the server responds with 500, ISR error. The error should be more descriptive, and proper validation should be put in place to check for attributes, define what the error and help the developer debug the mistake. 

**Describe the solution you'd like**
Currently, in process of going through the code base. Ruby is extremely new for me.

**Describe alternatives you've considered**
For my project, I shifted to another API and filtered the data myself on my server. Not ideal but had to be done.

**Additional context**
What I was trying to do is search a conversation of a particular contact in a particular inbox. Couldn't find anything on that and even this route has improper error throwing. Shifted to fetching all conversations and filtered them myself. 

<sub>[CW-1720](https://linear.app/chatwoot/issue/CW-1720/poor-error-throwing-in-conversation-filter-api)</sub>

**Comment by pranavrajs** [comment]
@shawshankkumar, Can you please share the payload you sent to the API?

**Comment by guiqis** [comment]
@pranavrajs I'm facing the same issue here. I've tried several payloads, here's the last one: 

`[
  {
    "attribute_key": "browser_language",
    "filter_operator": "contains",
    "values": [
      "en"
    ]
  }
]`

And it returned:

`{
    "status": 500,
    "error": "Internal Server Error"
}`

**Comment by AnTxXx** [comment]
Hi all,

we encounter the same issue, here the stacktrace from the web server:

`I, [2023-02-03T11:13:18.228299 #1]  INFO -- : [45e26448b54598bfc59592644ba233c6] Started POST "/api/v1/accounts/10/contacts/filter" for 192.168.78.160 at 2023-02-03 11:13:18 +0000
I, [2023-02-03T11:13:18.249859 #1]  INFO -- : [45e26448b54598bfc59592644ba233c6] Processing by Api::V1::Accounts::ContactsController#filter as JSON
I, [2023-02-03T11:13:18.249925 #1]  INFO -- : [45e26448b54598bfc59592644ba233c6]   Parameters: {"_json"=>[{"attribute_key"=>"[FILTERED]", "filter_operator"=>"contains", "values"=>["M"], "query_operator"=>"nil"}], "account_id"=>"10", "contact"=>{}}
I, [2023-02-03T11:13:18.258806 #1]  INFO -- : [45e26448b54598bfc59592644ba233c6] Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.9ms | Allocations: 2065)
F, [2023-02-03T11:13:18.259391 #1] FATAL -- : [45e26448b54598bfc59592644ba233c6]   
[45e26448b54598bfc59592644ba233c6] NoMethodError (undefined method `each_with_index' for nil:NilClass):
[45e26448b54598bfc59592644ba233c6]   
[45e26448b54598bfc59592644ba233c6] app/services/contacts/filter_service.rb:16:in `contact_query_builder'
[45e26448b54598bfc59592644ba233c6] app/services/contacts/filter_service.rb:5:in `perform'
[45e26448b54598bfc59592644ba233c6] app/controllers/api/v1/accounts/contacts_controller.rb:56:in `filter'
[45e26448b54598bfc59592644ba233c6] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[45e26448b54598bfc59592644ba233c6] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
[45e26448b54598bfc59592644ba233c6] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[45e26448b54598bfc59592644ba233c6] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[45e26448b54598bfc59592644ba233c6] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'`

Even if you send an empty payload, it will crash with 500.

**Comment by imskr** [comment]
Getting same 500 error:

```curl
curl --location --request POST 'http://localhost:3000/api/v1/accounts/1/conversations/filter' \
--header 'api_access_token: <token>' \
--header 'Content-Type: application/json' \
--data-raw '{
  "attribute_key": "status",
  "filter_operator": "equal_to",
  "values": ["open", "pending"],
  "query_operator": "OR"
}'
```

**Comment by arladmin** [comment]
Hi.
Why is this API endpoint still not operational?

It always returns `500 Internal Server Error`.
Also, there doesn't seem to be any other way of searching/filtering contacts.

**Comment by sojan-official** [comment]
We are looking into this. The current payload structure is a little complex, and errors often occur when there are mistakes in the payload. One thing which you can try is the filter over the UI. Look into the network tab and copy the exact payload which is being sent. Replicate the same in your API calls

**Comment by pranavrajs** [comment]
@tejaswinichile Let us do a JSON schema validator initially and see if it helps.

**Comment by pranavrajs** [comment]
Hey folks, 

There was an issue with the payload documentation. I have fixed it for now. You have wrap the array within a payload attribute to get this to working. Please see the update documentation [here](https://www.chatwoot.com/developers/api/#tag/Conversations/operation/conversationFilter).
