### ISSUE TITLE
Docker I can not login after upgrading

### ISSUE THREAD

**Issue by HT-Moh** [chatwoot/chatwoot#5267]
After upgrading to the last version, I can not login anymore. 
* I pulled the last docker version 
* I ran `RAILS_ENV=production bundle exec rails c`

Everything seems to work besides login, the chat from the website seems to be working as well. 

![image](https://user-images.githubusercontent.com/34759569/184552006-b3ce92af-bc2c-40b0-94c5-c58bfa295933.png)

**Comment by pranavrajs** [comment]
@HT-Moh Did you run the migrations? Please see the step here. https://www.chatwoot.com/docs/self-hosted/deployment/docker#upgrading

**Comment by HT-Moh** [comment]
I did `docker exec 94b35f712f7d  sh -c 'RAILS_ENV=production bundle exec rails c'

**Comment by sojan-official** [comment]
@HT-Moh  you need to do  `docker exec 94b35f712f7d sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare' instead. 

`rails c` is so open up the rails console
ref: https://www.chatwoot.com/docs/self-hosted/deployment/docker#upgrading

**Comment by HT-Moh** [comment]
@sojan-official  thanks my bad
