### ISSUE TITLE
FB Previous conversations are missing

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5268]
Hi,
It seems like for Facebook Channel, we cant see "Previous conversation" 
As the screenshot attached, we have closed the conversation, and then started again, and tested three times, but still cant see old convo under "Previous Conversations" Is this expected? 

![image](https://user-images.githubusercontent.com/38554929/184578129-59bf7416-ae3d-46ab-96f0-22108fee8d31.png)

**Comment by iammattmartin** [comment]
Facebook is one continuous conversation, similar to twitter.

**Comment by iammattmartin** [comment]
Facebook is one continuous conversation.

**Comment by sojan-official** [comment]
as @iammattmartin  mentioned, This is expected behavior for Facebook. Chatwoot maintains only a single thread.
