### ISSUE TITLE
support interactive session messages with csml on all channels

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5278]
hello right now csml is text base chat bot only and its not look good, can you support interactive session messages on WhatsApp then others channels  with csml

**Comment by joseph0063** [comment]
+1
Pretty please 🙏🏼🙏🏼

**Comment by pranavrajs** [comment]
Closing this as we will be removing the CSML integration in the January release. No new bot can be added, although the existing ones would work.
