### ISSUE TITLE
New Langauge to add: Bahasa Melayu

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5282]
Hi,

Can we request to add Malaysian local language (bahasa melayu) ?

**Comment by pranavrajs** [comment]
Closing as the language is added to Crowdin. 

https://chatwoot.crowdin.com/chatwoot/ms
https://chatwoot.crowdin.com/chatwoot-mobile-app/ms

**Comment by harismateen** [comment]
@pranavrajs is this included in mobile app only or web as well?

**Comment by pranavrajs** [comment]
Both in mobile and web app.
