### ISSUE TITLE
Chatwook 1-Click Heroku fails deployment

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5284]
The Chatwoot 1-Click Heroku install fails at the deployment stage. Could you advise?

**Comment by vishnu-narayanan** [comment]
<img width="938" alt="image" src="https://user-images.githubusercontent.com/3526167/185105872-0c7ddb74-6f2d-4017-a12e-fb1abd654989.png">

**Comment by vishnu-narayanan** [comment]
Fresh deployment failing on `hotfix/fix-linux-install` branch

<img width="890" alt="image" src="https://user-images.githubusercontent.com/3526167/185109719-c0af63fb-d168-4e05-83d2-2b53430ab2d4.png">

**Comment by vishnu-narayanan** [comment]
![image](https://user-images.githubusercontent.com/3526167/185109843-92e682ab-511a-496b-b61e-250c6e41f0d9.png)

**Comment by vishnu-narayanan** [comment]
Not able to fetch release logs as the app is not created since its a fresh deployment.

```
$ heroku releases:output v8 -a floating-headland-24095
 ▸    Couldn't find that app.
```

**Comment by sojan-official** [comment]
Could this be due to the slug size?

**Comment by pranavrajs** [comment]
@sojan-official I don't think so. We have the same warning in the production instance.

**Comment by barroscicero** [comment]
Same here

**Comment by telesth** [comment]
I have the same problem! Any updates?

**Comment by barroscicero** [comment]
Guys, I found the issue.

Line 398 on schema.rb file should be replaced from
`t.uuid "uuid", default: -> { "public.gen_random_uuid()" }, null: false`
to 
`t.uuid "uuid", default: -> { "gen_random_uuid()" }, null: false`

**Comment by sojan-official** [comment]
@barroscicero Thanks for the info we will have a look.

**Comment by vishnu-narayanan** [comment]
```
What are we announcing?

    Public roadmap: Launch of our [interactive product roadmap for Heroku on Github](https://github.com/heroku/roadmap).
    Focus on what's mission-critical: Removal of free dynos, hobby-dev Heroku Postgres and hobby-dev Heroku Data for Redis plans starting November 28, 2022 and inactive account deletion starting October 26, 2022.
    Student and nonprofit program: An upcoming program to support students and nonprofits in conjunction with our nonprofit team.
    Open-source support: We will continue to contribute to open-source projects, notably [Cloud-Native Buildpacks](https://buildpacks.io/). We will be offering Heroku credits to select open-source projects through Salesforce's Open Source Program Office.

```

https://help.heroku.com/RSBRUH58/removal-of-heroku-free-product-plans-faq

**Comment by vishnu-narayanan** [comment]
#5338 failing
<img width="855" alt="image" src="https://user-images.githubusercontent.com/3526167/186765259-219e5d69-375f-4a11-8805-336b076d7fb0.png">

**Comment by fullbright** [comment]
Same issue here.
