### ISSUE TITLE
Remove CSV from attachments in the Twilio WhatsApp Channel

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5289]
https://www.twilio.com/docs/whatsapp/guidance-whatsapp-media-messages 

![image](https://user-images.githubusercontent.com/2246121/185198250-d7759424-4cfc-46e2-926e-616b14d6fcca.png)

- [ ] Remove the option to upload CSV files in the UI for Twilio WhatsApp channel

**Comment by sojan-official** [comment]
link: https://github.com/chatwoot/chatwoot/issues/2971
