### ISSUE TITLE
[CW-41] Message events are not received: CSAT, Greeting Messages and Business Hours in API Channel

### ISSUE THREAD

**Issue by intelnexoec** [chatwoot/chatwoot#5291]
Hello friends, I have detected that I am not receiving the event messages through an api channel:

*Enable channel greeting
*Enable CSAT
*Business Hours

I want to pass those messages to my app using the api channel but it is not passing it.

Automation works fine!

![image](https://user-images.githubusercontent.com/84194459/185257071-e0ac6d78-53d4-4321-b8a0-a9e7e5c2c18b.png)

Self-Hosted
V: 2.7

<sub>[CW-41](https://linear.app/chatwoot/issue/CW-41/message-events-are-not-received-csat-greeting-messages-and-business)</sub>

**Comment by pranavrajs** [comment]
@sojan-official Is this happening because we block template messages in the webhooks?

**Comment by sojan-official** [comment]
at the moment we are only delivering `incoming` and `outgoing` messages in the webhooks.

ref: https://github.com/chatwoot/chatwoot/blob/a788e7ac7ab4b8bc358981124694676b413849fd/app/models/concerns/message_filter_helpers.rb#L8

cc: @pranavrajs

**Comment by guiqis** [comment]
CSAT would be really import for me! The token or the link for the CSAT would be great!

**Comment by grupale** [comment]
Hi @pranavrajs and @sojan-official ! Is there any way to make this work? Like @guiqis this feature would be great in API Channel!

**Comment by rogeriorizzo** [comment]
csat is just sending the link to whoever makes the first conversation, when in the next sequential ones, it doesn't send it. Has anyone gone through this or is there some variable that I have to modify?

**Comment by robert0825** [comment]
how about it?

**Comment by sojan-official** [comment]
@grupale It will be available in our upcoming release for self-hosted.
