### ISSUE TITLE
chore: Ability to change default account

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#5297]
**Problem**
Suppose a user has two accounts. Whenever the user logs into the account, it is always redirected to the account that the user created first. 

**Solution**
Add the ability to set the default user account. So that user can access their favorite account in the dashboard

**Comment by sojan-official** [comment]
## Note

- Account_user object has an attribute `active_at`.  We need to update the value of this attribute through an API call whenever someone switches the account.  
   -  introduce a new API endpoint in auth which accepts the account id and mark the corresponding account user object active at set to the current time
 - The dashboard URLs are based on fetching the first element from the accounts array.  ref: https://github.com/chatwoot/chatwoot/blob/27a980681743afb6f8ee34cdbeb7ba9d5b1a8d8c/app/javascript/dashboard/helper/URLHelper.js#L17
 Instead use the account_id value available in the payload which returns last active account
https://github.com/chatwoot/chatwoot/blob/27a980681743afb6f8ee34cdbeb7ba9d5b1a8d8c/app/views/api/v1/models/_user.json.jbuilder#L2
  - We can also alternatively sort the accounts array based on active at. ref: https://github.com/chatwoot/chatwoot/blob/27a980681743afb6f8ee34cdbeb7ba9d5b1a8d8c/app/views/api/v1/models/_user.json.jbuilder#L19
