### ISSUE TITLE
feat: Reply box should be cleared when conversation context changes

### ISSUE THREAD

**Issue by duongvanphung** [chatwoot/chatwoot#5301]
**Save content chat in reply chatbox of agent**

I'm agent. When i typing in reply chatbox then click to another conversation
Content of typing is not clear. so I may be mistakenly sent to another conversation

![Screenshot_1](https://user-images.githubusercontent.com/49987543/185538890-f0afe4f5-493c-4671-962b-2c3b8bdedfaa.png)
![Screenshot_2](https://user-images.githubusercontent.com/49987543/185538897-94208767-0fcc-4bda-9b68-39e764210dcb.png)

=> I want save content of reply each conversation like messenger, telegram,...

**Comment by duongvanphung** [comment]
@sojan-official Thank you very much!

**Comment by sojan-official** [comment]
ref: #4876

**Comment by duongvanphung** [comment]
Thank you!

**Comment by iamsivin** [comment]
Closing this issue since the PR is merged (https://github.com/chatwoot/chatwoot/pull/4440)
