### ISSUE TITLE
Unable to install on Ubuntu 20.04

### ISSUE THREAD

**Issue by azharumar** [chatwoot/chatwoot#5312]
**Installation terminates at ➥ 6/9 Installing Chatwoot. This takes a long while.**

While trying to install Chatwoot as per the documentation on Linux VM. The installation terminates at
➥ 6/9 Installing Chatwoot. This takes a long while.

`[4/5] Linking dependencies...
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@*".
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@*".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
$ husky install
husky - Git hooks installed
Done in 47.37s.
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.17). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.17`.
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@*".
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@*".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[5/5] Building fresh packages...
Done in 15.26s.
Compiling...
#<Thread:0x0000562c6811de70 /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:295 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:295:in `read': stream closed in another thread (IOError)
	from /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:295:in `block (2 levels) in capture3'
#<Thread:0x0000562c6811d830 /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:296 run> terminated with exception (report_on_exception is true):
/usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:296:in `read': stream closed in another thread (IOError)
	from /usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/open3.rb:296:in `block (2 levels) in capture3'
rake aborted!
SignalException: SIGHUP
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker/compiler.rb:70:in `run_webpack'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker/compiler.rb:23:in `compile'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker/commands.rb:51:in `compile'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker.rb:35:in `compile'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:23:in `block (4 levels) in <main>'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker.rb:28:in `ensure_log_goes_to_stdout'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:22:in `block (3 levels) in <main>'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/webpacker.rb:20:in `with_node_env'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:21:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-3.0.4/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/webpacker-5.4.3/lib/tasks/webpacker/compile.rake:14:in `block in enhance_assets_precompile'
/usr/local/rvm/gems/ruby-3.0.4/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)
`

**Comment by 503Dev** [comment]
@azharumar This happened to me when running on a VM with inadequate memory.  2GB was not enough, I upgraded to 3 and the same issue.  Finally, at 4GB+ ram everything runs just fine, installer included.  Your issue could be something else but just a thought.

There may be some alternate ways to control memory usage such as those cited here: https://github.com/rails/webpacker/issues/2143

**Comment by azharumar** [comment]
@503Dev Thanks for the response. Probably that is the issue. This VM i am trying to install on is a 4 vCPU and 8GB RAM. 

The one-click install on Digital Ocean recommends  3 nodes / 8GB RAM / 4 CPU / 120GB Disk. This is a 72$/month instance. That is quiet expensive for us. Kinda dropping the whole plan of Chatwoot.

**Comment by pucilpet** [comment]
Chatwoot can run on low resources, too. Try to run it on docker or caprover.

**Comment by vishnu-narayanan** [comment]
@azharumar The above error is when webpacker runs out of memory during the asset pre-compilation stage. 

> Thanks for the response. Probably that is the issue. This VM i am trying to install on is a 4 vCPU and 8GB RAM.

You mentioned that you are getting this error on 4vCPU/8GB RAM machine. 8 GB RAM should have worked. Could you maybe try again and see if it succeeds?


> The one-click install on Digital Ocean recommends 3 nodes / 8GB RAM / 4 CPU / 120GB Disk. This is a 72$/month instance. That is quiet expensive for us. Kinda dropping the whole plan of Chatwoot.

The 3-node recommendation is for a Kubernetes deployment in DigitalOcean(1-click k8s app). 

As @pucilpet suggested, you could use the docker-based deployments to bring down the instance requirements even further as you can avoid the compilation stage.

**Comment by vishnu-narayanan** [comment]
Please reopen if the issue persists.
