### ISSUE TITLE
Chatwoot does not save informations

### ISSUE THREAD

**Issue by curufinwefeanor** [chatwoot/chatwoot#5315]
Hello everyone,

I installed chatwoot with docker. After typing docker-compose up,  i was redirected to super-admin page. In here, i wrote related informations and i created super-admin.  After that, i logged in chatwoot, i created agents,inboxes, conversations with no problem. But, when i restarted pc, my conversations,agents,contacts were lost and i  was redirected to super-admin page. How can i solve this problem ?

**Comment by pranavrajs** [comment]
@curufinwefeanor There is not enough information to debug this. Please use the issue template to report a bug/error. Please share logs, versions, and anything that would help debug this further.
