### ISSUE TITLE
 Your distribution, identified as "jammy", is not currently supported during installation

### ISSUE THREAD

**Issue by gaurav-ingalkar** [chatwoot/chatwoot#5320]
**Describe the bug**
Not able to install chatwoot on a fresh ubuntu instance.

ruby version - 3.0.2p107
node version - v12.10.0
os - Ubuntu 22.04.1 LTS

![Screenshot 2022-08-22 at 5 17 37 PM](https://user-images.githubusercontent.com/108403643/185914104-8d4950de-7a9a-443f-b0c0-b2fab5c14cce.png)

**Comment by sojan-official** [comment]
@gaurav-ingalkar The installer only supports ubuntu 20.04 at the moment.
https://www.chatwoot.com/docs/self-hosted/deployment/requirements#supported-linux-distribution
