### ISSUE TITLE
Adding a private note clears the CC field in an Email inbox

### ISSUE THREAD

**Issue by jordan-brough** [chatwoot/chatwoot#5325]
If you add a private note to an Email Conversation that has CC fields, the CCs disappear from the Reply form.

<img width="581" alt="image" src="https://user-images.githubusercontent.com/23050/186017031-ae198e59-9478-487d-81b0-184aef23d172.png">

# Configs

Chatwoot version 2.7.0

# Repro

1. Send an email into Chatwoot with some CC addresses on the email
2. Open the conversation in Chatwoot and observe that the Reply form has CCs in it
3. Click on Private Note and add a private note
4. Click back to Reply

Expected: CCs are still in the Reply form
Actual: CCs have been removed.

Reloading the page or switching to another conversation and then switching back fixes the issue.

# Screen recording

Here's a screen recording of the behavior:

https://user-images.githubusercontent.com/23050/186017447-81a21c52-9f9e-4b17-8bce-f89ce40a5b00.mov

**Comment by iamsivin** [comment]
@pranavrajs Verified this issue, I Will add a fix for it.
