### ISSUE TITLE
Fix flaky tests related to user email 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#533]
https://app.circleci.com/jobs/github/chatwoot/chatwoot/1134 
```
message.user ||= create(:user, account: message.account)
```

throws email taken error. let's fix this flaky test

**Comment by pranavrajs** [comment]
@sojan-official Is this still required?

**Comment by sojan-official** [comment]
haven't seen this is a long while. let's reopen if this occurs.
