### ISSUE TITLE
Could not connect to Woot Server, Please try again later

### ISSUE THREAD

**Issue by sinapse-i-a** [chatwoot/chatwoot#5330]
I recently updated the version of Chatwoot on my server. With that I followed all the steps [LINK ](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm/)that is in the topic UPGRADIN.

Now I can not login, it is showing the message **Could not connect to Woot Server, Please try again later**, but when in SUPER_ADMIN, it is connecting.

I realized it is related to the USER, because inside SUPER_ADMIN, the USER listing started to show errors.

obs: I know there are other topics open with this topic. I've run all the previous commands, and none worked.

Error trying to login

![image](https://user-images.githubusercontent.com/93362855/186337616-15b6b6b7-7299-40f4-bd19-c4e305df35af.png)

User listing error

![image](https://user-images.githubusercontent.com/93362855/186337736-c086523c-b9ff-4ca5-80a4-9547010cec39.png)

Request URL: localhost/super_admin/users/16
Request Method: GET
Status Code: 500 
Referrer Policy: strict-origin-when-cross-origin

**I'm using version 2.7.0**

**Actions Taken**
#700
#1863

**Log**
```
ActionView::Template::Error
 (undefined method `message_signature' for #<User email: "my_mail@mail.com", uid: "my_mail@mail.com", id: 1, provider: "email", name: "Francisco", display_name: nil, created_at: "2021-07-23 14:02:23.
364504000 +0000", updated_at: "2022-08-24 06:03:17.899077043 +0000", pubsub_token: "WpA...", availabili
ty: "online", ui_settings: {"enter_to_send_enabled"=>true, "is_contact_sidebar_open"=>true, "display_rich_content_editor"
=>true}, custom_attributes: {}, confirmed: nil>
```

**Comment by sinapse-i-a** [comment]
Guys, I identified that the problem is in the MIGRATIONS. When you update from an older version to newer ones, you are not executing migrations correctly, which causes a lot of system failures.

Is there a method that I can FORCE migrations to run?

Because I'm doing a manual job of getting the migrations and executing them one by one.

Thanks.

**Comment by sojan-official** [comment]
@sinapse-i-a You must perform the upgrades sequently for the migrations to work correctly. Could you share the following details

- version you are upgrading from
- version you are upgrading to ? 

running `rake db:chatwoot_prepare` should migrate all remaining migrations.

**Comment by sojan-official** [comment]
We are closing this issue since there haven't been any recent updates. Please feel free to open a new one if the problem persists.
