### ISSUE TITLE
ERROR POSTBACK EVENT FOR CARD BUTTON NOT WORKING

### ISSUE THREAD

**Issue by ngalai** [chatwoot/chatwoot#5331]
I'm using Payload Samples  in **https://www.chatwoot.com/docs/product/others/interactive-messages#2-form**
with **content_type = cards**
Example: 
{
   "content": "card message",
   "content_type":"cards",
   "content_attributes":{
      "items":[
         {
            "media_url":"",
            "title":"Welcome to CamCamShop",
            "description":"Running with Nike Shoe 2.0",
            "actions":[
               {
                  "type":"link",
                  "text":"View More",
                  "uri":"google.com"
               },
               {
                  "type":"postback",
                  "text":"Add to cart",
                  "payload":"?ic_button123077"
               }
            ]
         }
      ]
   },
   "private":false
}

**When clicking the button with type postback but not happen event**

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/1895
