### ISSUE TITLE
Use expanded layout as the default layout in the mobile view

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5332]
hi after i test switch layout on mobile browser the view become more responsive can you make the switch layout as default layout on mobile browser

also there's small bug : when switch layout I'm not bale to scroll down  

![image](https://user-images.githubusercontent.com/20530550/186400348-c47f58db-6af6-415a-9cad-a5cbf36a8d0c.png)

**Comment by BhavyaT-135** [comment]
Hi @pranavrajs, can I take up this issue if no one else is working on it? 😊

**Comment by pranavrajs** [comment]
@BhavyaT-135 Sure, please go ahead.

**Comment by BhavyaT-135** [comment]
Hi @pranavrajs, would changing the default value of `isOnExpandedLayout` props, in the `SwitchLayout` file, to `true` be a solution to this issue? Sorry for the late response, had been occupied with college 😅

**Comment by pranavrajs** [comment]
@BhavyaT-135 It requires a little more work. Assigning this to @iamsivin for now, as it needs a fix soon. Let me know if you are interested, we can find another issue for you.

**Comment by BhavyaT-135** [comment]
Hey @pranavrajs, thanks for asking. I'll go through the documentation and look for an issue that I could contribute too. 😃
