### ISSUE TITLE
Fast contact search with meilisearch 

### ISSUE THREAD

**Issue by ajay01994** [chatwoot/chatwoot#5333]
Hi guys, the contact search needs to faster as a  dropdown feature  currently it is like this 

![image](https://user-images.githubusercontent.com/31235529/186453790-45cb5042-c814-477d-b209-a0beb5240099.png)

with no dropdown ,can you integrate your search with open source Meiliserach 

Link -https://www.meilisearch.com/

**Comment by pranavrajs** [comment]
Closing in favor of #6021
