### ISSUE TITLE
Rename "Bot"

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot#5336]
Free Name für "Bot"
<img width="374" alt="Bildschirmfoto 2022-08-25 um 16 15 58" src="https://user-images.githubusercontent.com/7121202/186689350-2531976e-cc3a-4f83-999d-2753b36c8768.png">

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/3531
