### ISSUE TITLE
Make Dialogs Persistent (no autoclose on outside click)

### ISSUE THREAD

**Issue by cod3master** [chatwoot/chatwoot#5340]
**Is your enhancement request related to a problem? Please describe.**
Dialogs close automatically when clicked outside, it's really annoing when entering data and it closes itself just because of a missclick. It happends a lot when I select something from a input field and the mouse goes outside of the dialog.

**Describe the solution you'd like**
Make all modal dialogs persistent

**Comment by pranavrajs** [comment]
@cod3master This is the default behavior of modals in most places. Let me know if you have any specific instances where the outside click is creating major issues. Closing this out as we might not change this behavior.
