### ISSUE TITLE
Support easy deployment on Heroku competitors

### ISSUE THREAD

**Issue by lowlyocean** [chatwoot/chatwoot#5344]
**Is your feature request related to a problem? Please describe.**
Heroku will be demising their [free compute](https://techcrunch.com/2022/08/25/heroku-announces-plans-to-eliminate-free-plans-blaming-fraud-and-abuse/), so any hobbyists deploying Chatwoot to Heroku via [this approach](https://github.com/chatwoot/chatwoot#heroku-one-click-deploy) will be stuck looking for an alternative.

**Describe the solution you'd like**
Would be great if there's support for easily switching Chatwoot deployment from Heroku to alternatives (Fly.io? Railway.app?)

**Describe alternatives you've considered**
Of course, hobbyists can choose to pay for Heroku's compute. Or deploy Chatwoot on their own baremetal. Or do their own configuration to deploy Chatwoot on Heroku's competitors :(

**Additional context**
N/A

**Comment by lauriejefferson** [comment]
Is this issue still open? I would like to contribute.

**Comment by lauriejefferson** [comment]
@pranavrajs @lowlyocean Is this pull request still open?

**Comment by sojan-official** [comment]
@lauriejefferson the issue is still open. but could you give a proposal on the changes you are looking to add ?

**Comment by lauriejefferson** [comment]
You can deploy Chatwoot on Railway using the Railway button page, which allows you to [create templates to offer a 1-click deploy on Railway experience](https://docs.railway.app/reference/templates).  Templates allow you to define the services for your project in a reusable format.  You can create a Railway template for the Chatwoot project and add the Deploy to Railway button to the README.md to give users a 1-click deployment of Chatwoot on Railway.  

You can create Chatwoot app on Fly.io by running ```fly launch``` at the command line.  It will launch a wizard where you can create a name for the app, choose a default region, and choose to launch and attach either or both a PostgreSQL  and Redis database.  To deploy the app, run ```fly deploy```.  The instructions on setting up Chatwoot on Fly.io are [given in the Fly.io docs](https://fly.io/docs/rails/getting-started/existing/).

**Comment by sojan-official** [comment]
> You can deploy Chatwoot on Railway using the Railway button page, which allows you to [create templates to offer a 1-click deploy on Railway experience](https://docs.railway.app/reference/templates). Templates allow you to define the services for your project in a reusable format. You can create a Railway template for the Chatwoot project and add the Deploy to Railway button to the README.md to give users a 1-click deployment of Chatwoot on Railway.
> 
> You can create Chatwoot app on Fly.io by running `fly launch` at the command line. It will launch a wizard where you can create a name for the app, choose a default region, and choose to launch and attach either or both a PostgreSQL and Redis database. To deploy the app, run `fly deploy`. The instructions on setting up Chatwoot on Fly.io are [given in the Fly.io docs](https://fly.io/docs/rails/getting-started/existing/).

Sounds good. I have added you as the assignee if you are interested in contributing.

**Comment by lauriejefferson** [comment]
Thanks.  I'll get started.

**Comment by brody192** [comment]
A community template already exits here [](https://railway.app/template/chatwoot)
and the markdown button would be this
```
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/chatwoot)
```

disclaimer, I created the template

**Comment by lauriejefferson** [comment]
@sojan-official @lowlyocean @brody192 Can this PR be closed?
