### ISSUE TITLE
WhatsApp replay mention not showing 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5350]
hi if i send message then the client mention it as replay its not showing in conversation

**Comment by glauberssoutodossantos** [comment]
Hi,

I belive @voko3456 is talking about sothing like the imagens below. It will be very nice if chatwoot could suport replay messages like WhatsApp.

![image](https://user-images.githubusercontent.com/99494469/187806243-ec8be98a-3bff-4681-9105-3e72ae67c409.png)

![image](https://user-images.githubusercontent.com/99494469/187806259-776954e9-37e4-457d-9d43-c06bd2e4d0a4.png)

**Comment by glauberssoutodossantos** [comment]
Just out of curiosity, I've been testing and at least the WhatsApp Businnes cloud API sends the context field with the ID of the replied message.

So the field in blue highlighted below is the message I replied about. The one in red is the current message.

In this specific case Chatwoot should save all WhatsApp message IDs (I don't know if this is done).

And you also have to think about how not to send a message to dialogflow that the user might respond to from the bot.

![image](https://user-images.githubusercontent.com/99494469/187807365-6e68f3f3-db8a-4fa2-afdd-3001be54e5c6.png)

**Comment by sojan-official** [comment]
Let's track the conversation over https://github.com/chatwoot/chatwoot/issues/3627
