### ISSUE TITLE
hide the inboxes bar

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#5360]
**Is your enhancement request related to a problem? Please describe.**

Hello,

I would like the bar that shows the inboxes and bookmarks of the first screen to be hidden.

For accounts that only have 1 inbox and few tags this ends up polluting the screen and taking up a lot of space unnecessarily.

**Describe the solution you'd like**

You can collapse and expand the bar according to the user's preference.

![image](https://user-images.githubusercontent.com/99494469/187805679-3ca369c8-ff93-44b6-aaef-ac141dfb571a.png)

**Comment by jacsonsantospht** [comment]
Hi @sojan-official .
Is anyone working on this feature?

Have this example to hide secondary sidebar in conversations.
![Peek 17-11-2022 15-03](https://user-images.githubusercontent.com/87338089/202525611-2ee522d7-2684-4ba1-af0a-20ba9a725ac5.gif)
