### ISSUE TITLE
Whatsapp message campaign

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#5361]
**Is your feature request related to a problem? Please describe.**
Today in chatwoot we can create a campaign for sending bulk SMS messages. This in the USA may even be valid, but in countries like Brazil WhatsApp is much stronger, practically no one uses SMS.

**Describe the solution you'd like**

Being able to bulk send a pre-approved WhatsApp template, according to the segmentation of my contacts (tags), similar to SMS campaigns

**Comment by jeremylwf** [comment]
+1

**Comment by vagner-dias** [comment]
+1

**Comment by ramosicaro** [comment]
+1

**Comment by luiszxcv** [comment]
Deixo meu apoio a este recurso, importantíssimo.

**Comment by ajaydivvela** [comment]
Any updates or ETA?

**Comment by glauberssoutodossantos** [comment]
Hi chatwoot team, how are you?

Any updates in this feature request?

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4201
