### ISSUE TITLE
Reassign chats of DC agents. 

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#5362]
**Is your feature request related to a problem? Please describe.**

Suppose there are few agents handling chats but one had Internet disconnect issue, now administrator doesn't know who got disconnected & what happened to the chats which were being handled by that agent. Since we know, no one waits more than a minute on the web if there's no reply from the other side considering chats are meant for quick answers. 

**Describe the solution you'd like**

1. After agent gets DC and doesn't refresh/reconnect within 60 seconds threshold, system would consider that agent offline.

2. Admin would be notified that agent got offline if agent doesn't refresh/reconnect within 60 seconds.

3. Not answered tab in reports, which would take the admin to the chats, which were being handled by that agent, so that admin can reassign those chats. 

**Describe alternatives you've considered**

Alternative would be to add this in automation.

Event - Agent DC
Action - Assign chats to supervisor/admin - If team is working on custom roles. 

Looking forward to hearing team's views on this.

**Comment by pranavrajs** [comment]
@ammaraslam Having action triggered on the user's availability might not be the right approach. Unlike other live-chat providers, we support the chat history to be available in the browser even after the refresh.

We are building SLA (service level agreement) as a feature where you would be able to set the limits of first response time, and resolution time and get an alert if it breaches. I'm closing it here for now.
