### ISSUE TITLE
Can I use other API instead of using Twillio?

### ISSUE THREAD

**Issue by mvaqasuddin** [chatwoot/chatwoot#5394]
**Can I use another API instead of using Twillio?.**
As per my project requirement, I need to integrate  gupshup.io. How I can integrate that one?

Thanks

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/discussions/2759

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/discussions/2759

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/discussions/2759
