### ISSUE TITLE
Cordova/Capacitor plugin (or does it exist?)

### ISSUE THREAD

**Issue by sneko** [chatwoot/chatwoot#5395]
Hi,

I would like to integrate Chatwoot into an hybrid application but I was not able to find an official plugin nor someone in the community having done such a plugin.

Do you know if that's something on the roadmap? Or if you already saw somewhere?

If not, I guess it can become a feature request :)

Thank you,

**Comment by sojan-official** [comment]
At the moment, we don't have a Cordova plugin. 
there is a flutter SDK if you are interested: https://github.com/chatwoot/chatwoot-flutter-sdk

**Comment by pranavrajs** [comment]
@sneko Doesn't the web widget code directly work with Corodva?

**Comment by sneko** [comment]
@pranavrajs it depends on the JS script used:
* downloading a full script through network is problematic when using a native app
* making it a raw copy locally can be a solution (it depends what the script does... some like the Google ones themselves download other things sometimes...)

In all cases, having the web widget as a NPM package is always better for managing versions locally...

+ having a native plugin would allow to use Push Notification when a new message is receive...

I went with another player in the meantime, but I think a plugin would be worth it.
