### ISSUE TITLE
I get an error when I put the website widget script to my website.

### ISSUE THREAD

**Issue by QKJIN** [chatwoot/chatwoot#5402]
I have deployed chatwoot in my vm server. It's ok. And I tested in a blank index.html page, it's ok. It's amazing to chat with server agent. But when I put the website widget script to an index page in a complex website, I got an error. Below is the error in detailed.

Uncaught TypeError: i[u].split is not a function
    at Function.i [as set] (js.cookie.js:103:66)
    at B (IFrameHelper.js:37:11)
    at Object.loaded (IFrameHelper.js:143:7)
    at window.onmessage (IFrameHelper.js:97:37)

I don't know where is wrong.

**Comment by QKJIN** [comment]
It seems some conflict with a js file. I have found how to solved them. Markup here.

**Comment by sojan-official** [comment]
marking this as resolved since its fixed
