### ISSUE TITLE
Notification Sound does not play sometimes

### ISSUE THREAD

**Issue by kubre** [chatwoot/chatwoot#5403]
**Describe the bug**

When you've selected that you want to be notified by notification sound by either mine or all in profile settings.
The notification sound only plays when the Chatwoot Tab is not in focus and the new conversation comes in but when the tab is in focus or if you're inside a chat then the sound does not play this happens consistently even on the latest version.

**To Reproduce**
1. Open Dashboard as an agent
2. Turn on notifications sounds for all or mine
3. Sit on the Mine Tab or All (Keep the chatwoot tab in focus)
4. Trigger a new chat

**Expected behavior**

No matter what is happening even if browser windows is minimized or you're on the chat screen or inside the chat itself the notification should always play as otherwise agent would miss new incoming conversations

**Environment**
Latest Chatwoot Version

**Comment by pranavrajs** [comment]
@kubre This is by design. Sending audio alerts when the browser tab is often chaotic, hence it would trigger the alerts only when you are out of focus.

Please feel to share any additional thoughts here.
