### ISSUE TITLE
Search by conversation number

### ISSUE THREAD

**Issue by aslamabbas** [chatwoot/chatwoot#5406]
**Is your enhancement request related to a problem? Please describe.**
Sometimes, we wish to search by conversation number.

**Describe the solution you'd like**
Searching by #100 in the top search bar or in shortcut COMMAND + K, for 100 should show the 100th ticket.

**Additional context**
This became necessary, when we share the whole ticket link to our team. In this scenario, agents share the links from their custom view.

Since custom view of one agent is not visible to others, it is not possible to open the ticket. Hence we need to search by the conversation number, which is present in the link

**Comment by pranavrajs** [comment]
We will track it at https://github.com/chatwoot/chatwoot/issues/5910.
