### ISSUE TITLE
SMTP Configuration not working

### ISSUE THREAD

**Issue by ankwad** [chatwoot/chatwoot#5409]
tried all things.. but cannot configure SMTP 

Can someone tell how to go about it.. 

keep getting server 500 error

**Comment by sojan-official** [comment]
please refer https://www.chatwoot.com/docs/self-hosted/faq#how-to-debug-smtp-email-errors-in-chatwoot

**Comment by pranavrajs** [comment]
Closing the issue as there is no further activity.

**Comment by davodsaraei** [comment]
@sojan-official 
Hi. I have the same issue.

smtp_settings = {
  address: 'smartermail.bertina.us',
  port: '3030',
  user_name: 'info@affili.ir',
  password: 'myPass',
  domain: 'smartermail.bertina.us',
  enable_starttls_auto: 'true',
  tls: 'true',
  ssl: 'false',
  'openssl_verify_mode': 'none',
  'authentication': 'login'
}

![Uploading image.png…]()

**Comment by sojan-official** [comment]
@davodsaraei  check https://stackoverflow.com/questions/61991618/wrong-version-number-opensslsslsslerror-in-simple-ruby-ssl-client .
