### ISSUE TITLE
bug: Dialogflow does not send response when message is not text

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#5410]
**Describe the bug**

Noticed that when a user sends a type of message other than text (image, file, audio, etc) in a conversation being handled by Dialogflow, then it does not send a response to the user, leaving them hanging and confused.

**To Reproduce**

1. Setup Dialogflow on an inbox and initiate a conversation (or change status of existing to pending).
2. Send an image in that conversation as the user.
3. Dialogflow does not respond back.

**Expected behavior**

At the very least, when a user sends a message which type is not text and is bot handled, Chatwoot should pass a response to Dialogflow that contains a specific text string, so that this string can be configured in an intent which contains a proper reply to be sent by Dialogflow in response to the user (eg: an intent contains a response indicating that image/files cannot be recognized by the bot).

**Comment by pranavrajs** [comment]
@WevrLabs, I think you should set up a fallback intent if the message is empty. Otherwise, it wouldn't work. Please reopen the issue after setting a fallback intent and confirming that the issue still exists. https://cloud.google.com/dialogflow/es/docs/intents-default#fallback
