### ISSUE TITLE
enhancement: Include search by email address for message search

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#5413]
**Is your enhancement request related to a problem? Please describe.**
Currently the top search bar works only for message content. It would be really helpful if one could search with an email address to get the mail address is sent/received/involved to make the best out of search

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1277421/189356005-6d82fff8-84be-4b3d-b4c6-3ec9ecd0b6cc.png">

**Comment by jochenstu** [comment]
For our use case, being able to find find contacts by name would be really useful.

**Comment by duongvanphung** [comment]
I need search by name, too
