### ISSUE TITLE
My recent upgrade experience

### ISSUE THREAD

**Issue by darkpixel** [chatwoot/chatwoot#5415]
I'm up and running now, but the upgrade was a nightmare.

I figured I would toss some information into a bug report to help others that might be running into similar issues and/or the devs might want to make a few tweaks.

I was running Helm Chart 0.8.9 and tried to upgrade all the way to 1.0.2.
The migrate job kept failing.

I started stepping through the updates:
* 0.8.9 to 0.9.0 succeeded
* 0.9.0 to 1.0.0 failed.

```
Rspec gem is missing. Install it.
Flay gem is missing. Install it.
Rspec gem is missing. Install it.
FATAL:  password authentication failed for user "postgres"
FATAL:  no pg_hba.conf entry for host "10.138.184.152", user "postgres", database "postgres", no encryption
Couldn't create 'chatwoot_production' database. Please check your configuration.
rails aborted!
ActiveRecord::NoDatabaseError: FATAL:  password authentication failed for user "postgres"
FATAL:  no pg_hba.conf entry for host "10.138.184.152", user "postgres", database "postgres", no encryption
/app/lib/tasks/db_enhancements.rake:29:in `rescue in block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:19:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
```

After doing a bunch of digging, it looks like the chatwoot-env secrets got messed up during the 0.9.0 to 1.0.0 upgrade.

```POSTGRES_USERNAME``` got reset to ```postgres```, ```POSTGRES_PASSWORD``` got reset to ```postgres```, and ```POSTGRES_DATABASE``` got reset to ```chatwoot_production```.

It looks like that's because the Helm chart changed from storing those under:
```
postgres:
   postgresqlDatabase
```
to:
```
postgres:
  auth:
    postgresqlDatabase:
```

I rolled back the database, fixed the chart settings, and the upgrade succeeded and all containers started without errors.

Maybe I missed something in the release notes, but I can't find anything about the change.

After it completed, I was getting a gateway error when accessing the site.
More digging revealed the chatwoot endpoint was backwards.  It had a source port of 3000 and a target port of 5-something...even though the web container is listening on 3000.  I manually edited the endpoint and got the site back up.  I see there's a change that might be related in the helm chart, but I ignored it because the site is back up.

When I tried to access the site, it started redirecting me to ```/installation/onboarding``` even though the database migrated successfully and things appear to be working--I can see the embedded "Chat With Us" from various sites loading and accepting messages.  I can see inbound texts reaching the server.  Just can't sign in to the UI because we get redirected.

Filling out the form is useless because my account already exists in the database.  I don't want to use a different account as completing the onboarding process might blow away my existing data and start me over from scratch.

I saw bug #642 where it was said:
```
When you run rake db:chatwoot_prepare , we create a Redis key CHATWOOT_INSTALLATION_ONBOARDING with the value true
The application checks for this key on init to decide whether it should redirect users to the onboarding page or whether to the login page
This step is done only in environments where the RAILS_ENV value is set as production
so a couple of things you can look at

whats the value of rails env
whether you are running the rake db:chatwoot_prepare task
whether the redis instance is the same one against which the task was run
```

I only see the key:

```
alfred:CHATWOOT_INSTALLTION_ONBOARDING
```

It was set to "true".
I changed it to "false".
No effect.
I deleted the key, and now my site is back up.

No idea why the onboarding wizard is dependent on a REDIS key.  Maybe ChatWoot should look at the actual database to see if things are set up.

Anyways--that was the struggle this morning.  Great work on ChatWoot.  I love it, and we use it daily.

**Comment by pranavrajs** [comment]
@darkpixel Sorry about the experience. @vishnu-narayanan Can you please take a look at this issue and see if there are any improvements we can pickup in the helm-charts deployment?

**Comment by vishnu-narayanan** [comment]
@darkpixel Apologies for the inconvenience, and thank you for taking the time to write this up and share. 

There were some breaking changes due to switching to a recent version of Postgres and Redis. We are using the `postgres` and `redis` charts packaged by Bitnami which had a couple of breaking changes between versions.

This was mentioned both under the upgrade section on the website (https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts#upgrading) and as well as the GitHub readme(https://github.com/chatwoot/charts/tree/main/charts/chatwoot#upgrading)  for charts. I missed mentioning the breaking change under the GitHub releases page.  My bad. Updated it now.

>After it completed, I was getting a gateway error when accessing the site.
More digging revealed the chatwoot endpoint was backwards. 

I am not sure why this happened. There was no change in charts related to changing the port.

>No idea why the onboarding wizard is dependent on a REDIS key. Maybe ChatWoot should look at the actual database to see if things are set up.

Yeah, currently it is dependent on that redis key and shows the onboarding page if it is present. Will look into how we can improve this part.

**Comment by sojan-official** [comment]
closing this since the chart changes are merged.
 https://github.com/chatwoot/charts/issues/91
