### ISSUE TITLE
Unable to create automation rule based on contact conditions

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#5432]
Hello,

I am currently using the chatwoot docker installation (V 2.8.1) - self hosted - Installed from scratch 5 days ago.

I found this feature improvement (https://github.com/chatwoot/chatwoot/pull/4230) to create automation rules based on contact conditions which has been implemented in March/2022, but I could not find a way to use it in my installation.

Is this a restricted feature? Or can I enable it somehow in my installation?

Regards,

**Comment by pranavrajs** [comment]
@vagner-dias There is an open PR for the frontend which we will be merging soon. https://github.com/chatwoot/chatwoot/pull/4548
