### ISSUE TITLE
WhatsApp Cloud repeated messages issue

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5433]
*Describe the bug*

Repeated message

*To Reproduce*

1. Go to 'Whatsapp cloud inbox'
2. User send picture
5. See error in the inbox

*Expected behavior*

It does not repeat the same message.

*Screenshots*
as attached
![image](https://user-images.githubusercontent.com/38554929/190058423-ad057abb-7709-455a-bdcf-9b2478a0b6e3.png)
![image](https://user-images.githubusercontent.com/38554929/190058437-5da7c4e2-a0f4-4e45-a216-415dafccf8b8.png)

**Comment by sojan-official** [comment]
@harismateen, Could you check your server logs for any errors? We can't seem to reproduce this issue in our installation.

**Comment by sojan-official** [comment]
- We recently observed a case where the installation received duplicate webhook events from meta for Whatsapp messages. So will be adding a fix for this.
