### ISSUE TITLE
Question: How to send attachment messages using Chatwoot API

### ISSUE THREAD

**Issue by lexemekenya** [chatwoot/chatwoot#5438]
### Discussed in https://github.com/orgs/chatwoot/discussions/1809

<div type='discussions-op-text'>

<sup>Originally posted by **NitinNR** February 19, 2021</sup>
self hosted on linux</div>

Hi, I am still not able to send attachments using the API even after making sure everything is as per the screenshot shared for Postman.

**Comment by sojan-official** [comment]
Could you share error messages or more information about the issue?

**Comment by lexemekenya** [comment]
Thanks @sojan-official for your quick response. I am actually not sure how to identify where the error is so far all it does in postman is return a response as below but no message arrives in Chatwoot

{
    "id": <READACTED>,
    "content": null,
    "inbox_id": <READACTED>,
    "conversation_id": <READACTED>,
    "message_type": 1,
    "content_type": "text",
    "content_attributes": {},
    "created_at": 1663233856,
    "private": false,
    "source_id": null,
    "sender": {
        "id": 3,
        "name": "<READACTED>",
        "available_name": "<READACTED>",
        "avatar_url": "<READACTED>",
        "type": "user",
        "availability_status": "online",
        "thumbnail": "<READACTED>"
    }
}

![image](https://user-images.githubusercontent.com/28090322/190367984-7a141850-606f-4446-ada0-29944c4c29f1.png)

![image](https://user-images.githubusercontent.com/28090322/190368077-137347d3-3715-4415-b565-d7c748eeae35.png)

**Comment by sojan-official** [comment]
@lexemekenya  could you try generating the curl code for your request so that we can compare it against

```
curl --location --request POST 'http://localhost:3000/api/v1/accounts/1/conversations/2/messages' \
--header 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundary' \
--header 'api_access_token: uBJjA56hAuS6fWEt6V1XRei8' \
--form 'attachments[]=@"K6aITBLXf/chatwoot.png"'
```

**Comment by lexemekenya** [comment]
@sojan-official I have used the curl code you send me and it works!!...thank you let me adopt that, I am not so sure why mine wasn't working but at this point am ok.
