### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by vcborsolan** [chatwoot/chatwoot#5440]
Hello folks, I'm opening this issue to discuss if this repository will participate in the 2022 digital ocean [hacktoberfest](https://hacktoberfest.com/participation/#maintainers).

If so, let's review the issues and add the labels/tags for valid contributions.

## Issues
- [x] https://github.com/chatwoot/chatwoot/issues/5450
- [ ] https://github.com/chatwoot/chatwoot/issues/3089
- [ ] https://github.com/chatwoot/chatwoot/issues/3086
- [ ] https://github.com/chatwoot/chatwoot/issues/36
- [x] https://github.com/chatwoot/chatwoot/issues/2819
- [x] https://github.com/chatwoot/chatwoot/issues/4012

**Comment by pranavrajs** [comment]
@vcborsolan Thanks for opening this issue, we will add more information :)

**Comment by pranavrajs** [comment]
Closing this as the Hacktoberfest event is complete.
