### ISSUE TITLE
Unable to Connect Facebook, Whatsapp, Instagram and Twitter

### ISSUE THREAD

**Issue by ali-ocean** [chatwoot/chatwoot#5446]
**Describe the bug**
On prem Ubuntu20.04 Chatwoot Instance
**Facebook:**
I'm able to authenticate to facebook while creating Inbox, but it doesn't list any FB pages during inbox setup.
**Whatsapp:**
I want to register my own cell number or twillio phone number with whatsapp so whenever someone send message to that number it must be received in chatswood inbox but unable to process this.

**To Reproduce**

**Expected behavior**

Facebook inbox setup must show the pages associated with the account.
**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further

**Server logs**

Share the server logs to debug the issue further

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self hosted installation of Chatwoot. If you are using a self hosted installation of Chatwoot describe the type of deployment (Docker/Linux VM installation/Heroku)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@ali-ocean Have you completed the steps mentioned here? https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup

**Comment by ali-ocean** [comment]
> @ali-ocean Have you completed the steps mentioned here? https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup

Hello @Pranavraj thansk buddy for your reply.
yes i've followed these steps. before this while adding a messenger "inbox" i was getting authentication errors. but now it opens up a popup screen to login to my facebook account. but the pages list showed empty.
moreover if my other mates open chatwoot panel with same user i logged in, and tries to add messenger inbox the login in popup apears with error page. that's another issue. i'm using on prem version with ubuntu 20.04LTS.
SCOND ISSUE: i'm also unable to register whatsapp with twillio. share me exact steps how can i register with Twillio generated number OR my own whatsapp number.
thanks alot. waiting to hear from you soon.

best regards
Usman

**Comment by pranavrajs** [comment]
@ali-ocean Hey Usman, there is not much information to debug this properly. Can you please share the server logs, browser logs, and a screencast?

**Comment by sojan-official** [comment]
We are closing this issue since there haven't been any recent updates. Please feel free to open a new one if the problem persists.
