### ISSUE TITLE
Article count is not correct if the portal has multiple locales.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5472]
To reproduce: 

- Create a portal with 2 locales
- Add 1 article on each of the locale
- Refresh the portal page, and you will see the all article count as 2, even though you have selected only one locale

**Comment by tejaswinichile** [comment]
@pranavrajs The article count in the sidebar fetches from portal JSON where the search or filter is not working, if we can just change the sidebar fetching to `articles/index.json.jbuilder` it will fix the issue.

Like we have it in the sidebar for category labels

![Uploading Screenshot 2022-09-23 at 4.28.25 PM.png…]()


All article represents all articles and the count beside the category represents the article in that particular category.
