### ISSUE TITLE
Unable to send template message from Contacts --> New Message [WhatsApp Cloud]

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5481]
**Describe the bug**

**To Reproduce**

1. Contacts --> New Contacts --> Add new Contact - Open User
2. Click on --> Send Message --> Selected template message and sent message --> Message sent (but no message recieved by the user unless open conversation and then select the template again)
<img width="480" alt="image" src="https://user-images.githubusercontent.com/38554929/191650756-a49dfe09-50f9-48a1-94c0-e1227394b2f2.png">

**Expected behavior**

1. Contacts --> New Contacts --> Add new Contact - Open User
2. Click on --> Send Message --> Selected template message and sent message --> Message sent --> user recieve message 

**Screenshots**

![image](https://user-images.githubusercontent.com/38554929/191645790-b20ab9e4-4702-4faa-9972-641ded0eab16.png)

Chatwoot version: v2.7.0
Helm chart infrastructure GCP

**Comment by pranavrajs** [comment]
@harismateen Please upgrade to 2.9.0, the latest version and report if you still face the issue.

**Comment by harismateen** [comment]
@pranavrajs Still same - we have updated to v2.9.1, but still unable to send template message 

**Actual**: 
Click on --> Send Message --> Selected template message and sent message --> Message sent (but no message recieved by the user unless open conversation and then select the template again)

**Expected behavior**
Contacts --> New Contacts --> Add new Contact - Open User
Click on --> Send Message --> Selected template message and sent message --> Message sent --> user recieve message

![image](https://user-images.githubusercontent.com/38554929/194202934-04318337-e326-4ad8-9b50-8cb2cc63f4c6.png)

**Comment by grupale** [comment]
> Hello @pranavrajs - just an update - I am using v2.10.0 and I am facing the exact same problem.

I'm using v2.10 and I'm having the same issue.

**Comment by harismateen** [comment]
@pranavrajs is this the issue already settled in current release or still in-progress to fix?

**Comment by sojan-official** [comment]
tracking this over: https://github.com/chatwoot/chatwoot/issues/5128
