### ISSUE TITLE
Bug: Meta tags input in help center clears the input value after clicking outside.

### ISSUE THREAD

**Issue by fayazara** [chatwoot/chatwoot#5482]
**Describe the bug**
Happens in help center article editor page.  When we add some meta tags and click outside the input, the tags just get cleared on its own.

https://user-images.githubusercontent.com/15716057/191674697-d946530f-2998-4f81-b206-3940bbe9b47b.mov

**To Reproduce**

1. Go to Help center
2. Click on "New Article"
3. Add some meta tags and click outside
4. You can see that the meta tags get cleared.

**Comment by BikashSah999** [comment]
Hello @fayazara  @pranavrajs, from my spec I found that we need to support auto adding new tags when user press comma, and also add the tags in the input when user blurs the input. WDYT, would this be an acceptable resolution strategy?

**Comment by iamsivin** [comment]
@BikashSah999 Thanks for the findings. I think we can go with the `preserveSearch` prop in multi-select. 
CC: @pranavrajs @nithindavid 

@BikashSah999 Are you working on this issue? If you are, I can assign this issue to you, and you can raise a PR.
