### ISSUE TITLE
Chatwoot does not update email from profile settings

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#5492]
**Describe the bug**

Assume your current email is `current@mail.com` and you want to update it to `new.one@mail.com`. To do this you goto your profile settings page and update the email in the first section. Once you click update the app logout and send a confirmation to your new email `new.one@mail.com`. After clicking the confirm link, We will need to login again. If I try my `new.one@mail.com` it does not happen but will login with  `current@mail.com` .

**Comment by sojan-official** [comment]
Verified in local and app.chatwoot.com that this is working as intended. 

- updating the profile email will log you out of the app
- click on the confirmation link, which gets send to the new email, and you will be automatically logged into the app
- this action confirms the new email
- subsequent logins only work with the newly verified email 

note:  if there is an existing account with `new_email`  profile won't get updated with the email 'couldn't not connect to woot server` error is shown. 

Lets reopen if there any subsequent reports of this
