### ISSUE TITLE
Chatwoot doesn't respect user full name passed in request to create conversation

### ISSUE THREAD

**Issue by Higher08** [chatwoot/chatwoot#5496]
**Describe the bug**

I can enable the pre-chat form on the site widget. In it, you can add a request for the user's full name. When the user enters it and the message (starts a conversation), Chatwoot should set the name that the user entered in the contact parameters.

Using developer tools I found why it happens
1. When a user visits the site (even don't open the widget), the widget automatically creates a contact using random name.
2. Later, user fills the pre-chat form, widget sends request to create conversation with this body
`{"contact":{"name":"test","email":null},"message: {"content":"gfgfdhfgdhgf","timestamp":"time","referer_url":"site"},"custom_attributes":{}}
`
Here you can see the contact param, but the server-side part of Chatwoot doesn't change contact according to it.

**To Reproduce**

1. Create website channel
2. Enable pre-chat form in settings and enable full name field
3. Embed widget to the site
4. Start a conversation
5. Open Chatwoot and see unchanged name of user

**Expected behavior**

Full user name set from field that user entered

**Screenshots**
![Pre-chat form](https://user-images.githubusercontent.com/68398868/192149387-50431157-b31e-436c-80ca-40aacedf780c.png)

**Browser logs**

Share the browser logs to debug the issue further
![Снимок экрана 2022-09-25 в 17 21 10](https://user-images.githubusercontent.com/68398868/192149419-a1784e18-1f17-4795-8f17-8b96359e4b10.png)
![Снимок экрана 2022-09-25 в 17 26 08](https://user-images.githubusercontent.com/68398868/192149439-6913f1cf-666d-4c93-9fcf-98d9e6e699f0.png)

**Server logs**

Share the server logs to debug the issue further

**Environment**

Self-hosted in Docker

**Comment by Higher08** [comment]
I can record video of the bug, if you need

**Comment by muhsin-k** [comment]
@Higher08 Yes. That would be very helpful.

**Comment by Higher08** [comment]
@muhsin-k

**Comment by rocktimsaikia** [comment]
Yes. The same issue is happening in our product too. @Higher08 Did you find a way around it?

**Comment by muhsin-k** [comment]
@Higher08 Apologies for the delay here. We could be able to reproduce this issue from our side, and the team has already started working on it.

**Comment by rocktimsaikia** [comment]
@muhsin-k Do we have a timeline for when this will be fixed?

**Comment by muhsin-k** [comment]
We will fix this issue in v2.11.0

**Comment by muhsin-k** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot/issues/5705
