### ISSUE TITLE
Whatsapp inbox quoted reply

### ISSUE THREAD

**Issue by EthanYWK** [chatwoot/chatwoot#5498]
**Is your feature request related to a problem? Please describe.**
The quoted reply feature is missing in whatsapp inbox, causing us unable to know what message they were referring to when the conversation gets too long and complicated

**Describe the solution you'd like**
Whatsapp inbox should have the quoted reply feature

**Comment by sojan-official** [comment]
closing in favor https://github.com/chatwoot/chatwoot/issues/3627
