### ISSUE TITLE
Would like to be able to have a campaign apply on all pages of a website like URL/*

### ISSUE THREAD

**Issue by pgrandmaison** [chatwoot/chatwoot#5504]
**Is your enhancement request related to a problem? Please describe.**
Currently, in order to have a campaign show up on all pages of a website, we must enter individually all website individual pages into chatwoot's system. 

**Describe the solution you'd like**
It would be nice if it supported wildcard character like * to match either entire subfolders or an entire website
such as https://websiteurl/* or https://websiteurl/subfolder/*

**Describe alternatives you've considered**
Instead of implementing this in a campaign, it could be added as a feature of the chat system itself for a global setting. Seeing an agent person offer a chat to the website visitor is a very nice touch

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/3192
