### ISSUE TITLE
Slack integration not working (won't install without any message)

### ISSUE THREAD

**Issue by softmarshmallow** [chatwoot/chatwoot#5517]
On console, integrations, slack, once redirected to slack page, integration failes with no other messages.

Error on console
```
https://app.chatwoot.com/api/v1/accounts/xxxx/integrations/slack
{"status":500,"error":"Internal Server Error"}
```

Payload
```
{ code : "xxxxxx" }
```

**Comment by softmarshmallow** [comment]
@vishnu-narayanan need support

**Comment by pranavrajs** [comment]
@softmarshmallow Can you please reach out to hello@chatwoot.com with your account information? It would be helpful to debug the issue with your account information. Closing this here as we would take in the cloud support channel.
