### ISSUE TITLE
Dialogflow is triggered on tweets

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#5522]
**Describe the bug**

Dialogflow is triggered on tweets.

**To Reproduce**

1. Link a twitter account inbox.
3. Configure Dialogflow on this twitter inbox
4. Make a tweet to that account or a retweet any of the tweets
5. See Dialogflow being triggered for the tweet

**Expected behavior**

Dialogflow should not be triggered for tweets, only direct messages.

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
