### ISSUE TITLE
As a user on a website, have the option to recieve push notifications when an agent messages me.

### ISSUE THREAD

**Issue by JWesorick** [chatwoot/chatwoot#5525]
**Is your feature request related to a problem? Please describe.**

- User messages during non-business hours.
- Agent replies back many hours later but the user is no longer on the website.

**Describe the solution you'd like**

- User messages during non-business hours.
- Agent replies back many hours later but the user is no longer on the website.
- User receives push notification allowing them to easily return to the site and continue the conversation.

**Describe alternatives you've considered**

**Additional context**

iOS 16 will support web push notifications in 2023.
Android has supported it for a long time.

https://caniuse.com/push-api

**Comment by JWesorick** [comment]
👀 https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

**Comment by pranavrajs** [comment]
@JWesorick Saw this post. Let us see if we test it out :)

**Comment by JWesorick** [comment]
@pranavrajs Cool this got enabled for the dashboard, but can it be enabled for users on the widget side of things? We have people leave us a message and then bounce before we can respond. It would be nice for those people to get a push notification so they open the website again and continue the conversation.

**Comment by mmojadad** [comment]
@JWesorick
The same request
