### ISSUE TITLE
api endpoint for account feature flags

### ISSUE THREAD

**Issue by mkmk89** [chatwoot/chatwoot#5529]
Is that possible to apply feature flags to account with a use of api? 
https://www.chatwoot.com/developers/api/#tag/Accounts/operation/create-an-account

I can see it is possible in super_admin api endpoint, but seems not supported in standard api

**Comment by pranavrajs** [comment]
@mkmk89 Features flags are used for internal and billing purposes only, making it public would prevent us from making changes there.
