### ISSUE TITLE
Upgrade chatwoot from 2.7 to 2.9 giving account suspend issue

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#5534]
**Describe the bug**
Upgrade chatwoot from 2.7 to 2.9 giving account suspend issue
We tried to update from 2.7 to 2.8.2 still having the same account suspend issue. 

**Screenshots**

![image](https://user-images.githubusercontent.com/38554929/193180903-f243d827-6044-4d98-9222-d47d805089b7.png)

**Comment by pranavrajs** [comment]
@harismateen Please run the database migrations as shown here. https://www.chatwoot.com/docs/self-hosted/runbooks/migrate-chatwoot-database
