### ISSUE TITLE
Missing option to add an attachment

### ISSUE THREAD

**Issue by giladno** [chatwoot/chatwoot#556]
I have the proper setup for `ACTIVE_STORAGE_SERVICE=amazon` (including access keys), but there is no attachment button or anything similar to allow users to send screenshots. I also tried dragging a file to the chat window - but no luck.

**Comment by pranavrajs** [comment]
@giladno Thanks for the feedback, the UI for file upload is still in development.

Closing this as it is a duplicate for #252 and #253
