### ISSUE TITLE
feat: Ability to manage account features from API

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5561]
Now we can manage the acount features via super admin ui it will be greate to manage it via api while creating the account

![Screenshot_20221005-175936_Chrome](https://user-images.githubusercontent.com/20530550/194093929-59fff017-7052-4428-8e3e-a215a37f2fda.jpg)

**Comment by sojan-official** [comment]
duplicate https://github.com/chatwoot/chatwoot/issues/5529
