### ISSUE TITLE
[CW-1508] Telegram: how to get username?

### ISSUE THREAD

**Issue by iwex** [chatwoot/chatwoot#5570]
Hello! I want to see Telegram usernames in the contact info. How is it possible?

<sub>[CW-1508](https://linear.app/chatwoot/issue/CW-1508/telegram-how-to-get-username)</sub>

**Comment by dearkafka** [comment]
would be nice to have this finally worked out. right now chatwoot does store this attribute, just no UI and also is not enough to auto-create contact when conversation is initiated by user. is there a chance to include that?

**Comment by sojan-official** [comment]
closing in favour of https://github.com/chatwoot/chatwoot/issues/8214
