### ISSUE TITLE
Macros enhancement

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#5584]
- [ ]  Admins can see all the macros irrespective of the visibility.
- [ ]  An agent can change the visibility of another agent's macro. Let us disable the edit/delete function if the agent does not create the macro
- [x]  Order of execution of macros is not as per the order in which it is defined.
- [x]  Duplicate activity messages in some cases.
- [x]  Enable Send Email Transcript, Send Attachment.

**Comment by tejaswinichile** [comment]
> Admins can see all the macros irrespective of the visibility.
 - This is already there; display all the macros in the account for the account admin.
 
> An agent can change the visibility of another agent's macro. Let us disable the edit/delete function if the agent does not create the macro.
 -  set_visibility/update_visibility is part of the macro update. Should I add it as a separate endpoint, as we can not set different policies in the same method?

@pranavrajs Have doubts about the above two enhancements.

**Comment by tejaswinichile** [comment]
https://user-images.githubusercontent.com/10827585/195107216-c305f5fc-5ab2-4cf7-81cc-30ebdd56a273.mov

**Comment by pranavrajs** [comment]
@tejaswinichile I'll create a separate product request for the first 2 with the context.
