### ISSUE TITLE
Take Screenshot from Widget or Paste Image

### ISSUE THREAD

**Issue by punyaikhwan** [chatwoot/chatwoot#5594]
Sometimes client need to show what problem they are facing by sending screenshot.
Currently, to do this they should save it first to disk then select the image using attachment.

**Solution**
It will be better if Chatwoot has internal screenshot tool that the client can use it directly from the widget.

**Alternative**
If the solution above can't be delivered, another alternative is allowing client to paste the image after taking screnshot from external tool, without saving it first to disk and attach it using attachment button.

**Comment by XuJinNet** [comment]
> If the solution above can't be delivered, another alternative is allowing client to paste the image after taking screnshot from external tool, without saving it first to disk and attach it using attachment button.

+1
