### ISSUE TITLE
feat: Internal Inbox for the team to communicate

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#5598]
> Yes, the goal would be to introduce an internal chat communication like Slack or Teams so that Chatwoot becomes the central hub of all text-based internal and external communication. Private notes and @mentions work fine for any communication that is about a ticket or conversation however it does not work well when you want to ask a simple question unrelated to any current conversations.

**Comment by SirRodney** [comment]
+1

**Comment by AndersonOuverney** [comment]
+1

**Comment by clairton** [comment]
👍

**Comment by NLSARCOS** [comment]
+1

**Comment by pranavrajs** [comment]
Closing this here as we will not build / accept PRs on this issue near future.
