### ISSUE TITLE
Requesting integration of WATI.IO WhatsApp solution with Chatwoot.

### ISSUE THREAD

**Issue by Nearpeer** [chatwoot/chatwoot#5602]
Wati.io is one of the most used WhatsApp business solution providers. It will be awesome if we can get 1 click integrations with their system just like Twilio and WhatsApp Cloud API.

**Comment by vishnu-narayanan** [comment]
@Nearpeer Please have a look at this. 
https://github.com/orgs/chatwoot/discussions/2759
