### ISSUE TITLE
Send message with "enter" also do \n

### ISSUE THREAD

**Issue by ssteeltm** [chatwoot/chatwoot#5622]
**Describe the bug**

Send message with "enter" also do \n, when it should only send the message.

**To Reproduce**

1. Send message or private message 
2. write "something to test"
3. put the cursor on "somethi | ng to test"
4. See error: 
somethi \n
ng to test

**Expected behavior**

Should only send the message and not \n too

**Screenshots**
![image](https://user-images.githubusercontent.com/17302120/195617312-3a1c90d4-9a3e-4613-ba71-161b4acc9975.png)

![image](https://user-images.githubusercontent.com/17302120/195617356-d5d7eac2-d79d-4f3e-a4b0-09c16dc82366.png)

**Comment by sojan-official** [comment]
@ssteeltm This should be fixed in the editor fixes that's will be available in our upcoming release

**Comment by pranavrajs** [comment]
@ssteeltm This is a confirmed bug, we will prioritize a fix in the upcoming sprints.

**Comment by ssteeltm** [comment]
Hello, upgraded to v2.10. 
Issue with message works fine now.
But with private message it persists, continue to break line.

**Comment by JanCizmar** [comment]
+1
