### ISSUE TITLE
[CW-38] bug: Fix border color for CSAT component in widget

### ISSUE THREAD

**Issue by nithindavid** [chatwoot/chatwoot#5630]
**Prerequisites**
1. This happens for widget channel
2. Enable CSAT for the widget
3. Change the system theme to see dark mode (https://support.apple.com/en-us/HT208976)
4. On dark-mode when a conversation is resolved the below border appears over the tell us more field. 

We need to come up with a dark variant colour for this. 
Look `app/javascript/shared/assets/stylesheets/colors.scss` file for color references.

![image](https://user-images.githubusercontent.com/1277421/195719418-f1136388-d4bc-470c-9a52-ff53b20f7e43.png)

<sub>[CW-38](https://linear.app/chatwoot/issue/CW-38/bug-fix-border-color-for-csat-component-in-widget)</sub>

**Comment by SamalaSumanth0262** [comment]
Hi @nithindavid  can i work on this issue ?

**Comment by nithindavid** [comment]
Sure @SamalaSumanth0262 :) Assigning to you

**Comment by SamalaSumanth0262** [comment]
@nithindavid  my rails server is up, do we have any micro repository for the front end?

**Comment by SamalaSumanth0262** [comment]
<img width="1139" alt="Screenshot 2022-10-14 at 8 53 35 PM" src="https://user-images.githubusercontent.com/40859181/195930882-c517207c-1876-4b96-8c7c-b0eb14a695ed.png">

**Comment by SamalaSumanth0262** [comment]
@nithindavid  
<img width="1417" alt="Screenshot 2022-10-15 at 9 09 07 PM" src="https://user-images.githubusercontent.com/40859181/196005781-133cc050-e0db-4dab-84a2-d8b7724a947c.png">
My Local setup is done, can you guide me how to create a CSAT widget please ?

**Comment by nithindavid** [comment]
@SamalaSumanth0262 Please see the guides here - https://www.chatwoot.com/docs/product/channels/live-chat/create-website-channel

The issue is only for dark mode, please make sure you test this on both modes.


Once channel is created, you can
1.  Enable CSAT from the settings page of the created inbox.
2.  Visit `http://localhost:3000/widget_tests` to see the demo widget and start a conversation 
3. From dashboard resolve the conversation 
4. Check the widget page to see the component

**Comment by SamalaSumanth0262** [comment]
#5643 Please find the Fix PR, Thanks, and let me know if you want me to look at any p1 or p0 issues.
