### ISSUE TITLE
Recipient's profile photo - WhatsApp Cloud API

### ISSUE THREAD

**Issue by brunosfg** [chatwoot/chatwoot#5634]
A good improvement would be the ability to retrieve and show the recipient's profile picture in the conversation, just like a regular WhatsApp chat would do.

I couldn't find details in the API documentation, so I'm not sure if it is technically possible.

**Comment by sojan-official** [comment]
Currently, there isn't an API for WhatsApp cloud that will allow us to fetch avatars for WhatsApp Chats. 
We will reopen this when it becomes available.
