### ISSUE TITLE
Could not connect to Woot server

### ISSUE THREAD

**Issue by DanielGannage** [chatwoot/chatwoot#5635]
Upon setting up the Linux VM, the server was running fine. However, when it idled for a day or two (after a series of setup/testing, we cannot sign in). 

**The the chatwoot sign in interface said something along the lines of:**
"Cannot connect to Woot server."

**The chatwoot worker logs said:**
"ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use)" 

I tried to increase the MAX_RAILS_THREADS  in .env from 5 to 20 and the same thing happened a day later.

While inspecting the redis-cli we looked at the client-list, which always contained 20 or less client id's. Some of the have flag=b, which means they are in a blocking state. 

**Restarting the redis server resolves the issue.**

Additional Information:
Since we are running on one container, the WEB_CONCURRENCY is not set in the .env file and it defaults to 0 as per puma.rb

We are wondering if we should increase the number of workers to a higher number. We dont understand why the connections are in a blocking state.

**Expected behavior**

A sign in that brings you to chatwoot dashboard

**Server logs -- redis client list**

127.0.0.1:6379> client list
id=395 addr=127.0.0.1:49390 fd=20 name= age=55742 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=scard
id=403 addr=127.0.0.1:35218 fd=8 name= age=8 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=26 qbuf-free=32742 obl=0 oll=0 omem=0 events=r cmd=client
id=401 addr=127.0.0.1:41872 fd=25 name=ActionCable-PID-1986712 age=53889 idle=8168 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=publish
id=396 addr=127.0.0.1:49398 fd=21 name= age=55742 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=brpop
id=397 addr=127.0.0.1:49412 fd=22 name= age=55742 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
id=384 addr=127.0.0.1:49292 fd=9 name= age=55744 idle=2 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
id=385 addr=127.0.0.1:49294 fd=10 name= age=55744 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=get
id=386 addr=127.0.0.1:49302 fd=11 name=ActionCable-PID-1986596 age=55744 idle=130 flags=P db=0 sub=3 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=unsubscribe
id=402 addr=127.0.0.1:34066 fd=26 name= age=52583 idle=1849 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0events=r cmd=ping
id=387 addr=127.0.0.1:49306 fd=12 name=ActionCable-PID-1986596 age=55743 idle=8087 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=publish
id=400 addr=127.0.0.1:51190 fd=24 name= age=54385 idle=17894 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hget
id=388 addr=127.0.0.1:49322 fd=13 name= age=55742 idle=1 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
id=389 addr=127.0.0.1:49334 fd=14 name= age=55742 idle=2 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
id=390 addr=127.0.0.1:49350 fd=15 name= age=55742 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=brpop
id=391 addr=127.0.0.1:49354 fd=16 name= age=55742 idle=2 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
id=392 addr=127.0.0.1:49360 fd=17 name= age=55742 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=brpop
id=398 addr=127.0.0.1:52624 fd=23 name= age=55735 idle=8086 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0events=r cmd=lpush
id=393 addr=127.0.0.1:49370 fd=18 name= age=55742 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 obl=0 oll=0 omem=0 events=r cmd=brpop
id=394 addr=127.0.0.1:49374 fd=19 name= age=55742 idle=1 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=brpop
127.0.0.1:6379> exit

**Environment**

LINUX VM, Self hosted in Azure (one contianer)
Local redis server
External postgres database in AWS

**Comment by pranavrajs** [comment]
```
ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use)
```

@DanielGannage It seems that Postgres is down. Can you please check if the Postgres database is running properly?

**Comment by DanielGannage** [comment]
Yes, postgres is running properly. Simply running `redis server restart` always solves the issue. Its required every 3 days, otherwise we get the error

**Comment by pranavrajs** [comment]
@DanielGannage Can you try running using a dedicated Redis/Postgres service? It seems like your Redis and Postgres might be running out of memory if you are using the default Linux VM installation method.

**Comment by DanielGannage** [comment]
We have a dedicated postgres server on aws and the vm for redis is on azure. Do you mean to use something like Elasticache on Aws for redis?

After todays crash i took screenshots of what sidekiq looks like. Doesnt seem to be a memory leak.

**Before Restart**
Processes: 1
Threads: 10
Busy: 7
Usage: 70%
RSS: 427 MB

Version: 5.0.7
Uptime: 0 days
Connections: 19
Memory Usage: 1.82 M
Peak Memory Usage: 2.17 M

**After Crash/Restart**
Processes: 1
Threads: 10
Busy: 2
Usage: 20%
RSS: 427 MB

Version: 5.0.7
Uptime: 0 days
Connections: 8
Memory Usage: 1.6 M
Peak Memory Usage: 1.68 M

I get the sense that the number of connections gets filled and cant accommodate new connections.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/pull/5574
