### ISSUE TITLE
Update the source of `json_refs` gem

### ISSUE THREAD

**Issue by sony-mathew** [chatwoot/chatwoot#565]
For the swagger documentation, we had used `json_refs` gem to combine the fragmented files and resolve the references in them.

At the time of using, this gem did not have the ability to recursively resolve the references. So we had to fork this into one of our own and make the required changes. So this fork was used as the source for the gem.

Along with this, we had raised a PR (https://github.com/tzmfreedom/json_refs/pull/1) in the original repo so as to push the recursive dereferencing changes upstream. This was merged in the gem's parent repo. All thanks to @tzmfreedom for this. 

With these changes being merged, we no longer need the fork thus avoiding the necessity to maintain the fork as well. We should update the gem to its original source.

**Comment by sojan-official** [comment]
ref : https://github.com/tzmfreedom/json_refs/pull/1
