### ISSUE TITLE
docker not sending emails

### ISSUE THREAD

**Issue by arielesp** [chatwoot/chatwoot#5651]
Hi
I am using chatwoot docker version.
Its working ok, aparently... but is not sending emails, like user agent activation

I already stopped docker, and redo smtp data in .env
I tested credentials in external app, and its working .. but not in chatwoot.
I am using sendinblue smtp service.

How to solve this? thanks in advance

**Server logs**
```
I, [2022-10-17T13:31:03.876050 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63]   Parameters: {"name"=>"new - admin", "email"=>"xxx@xxx.xxx", "role"=>"administrator", "account_id"=>"1", "agent"=>{"name"=>"Ariel - admin", "email"=>"xxx@xxx.xxx", "role"=>"administrator"}}
I, [2022-10-17T13:31:04.025035 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63] [ActiveJob] Enqueued Avatar::AvatarFromGravatarJob (Job ID: 65ae06cb-253c-457f-b92f-71e90ffdf9f9) to Sidekiq(low) at 2022-10-17 13:31:34 UTC with arguments: #<GlobalID:0x00007fd2994cc1b0 @uri=#<URI::GID gid://chatwoot/User/2>>, "xxx@xxx.xxx"
I, [2022-10-17T13:31:04.026966 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63] [ActiveJob] Enqueued ActionMailer::MailDeliveryJob (Job ID: fdbf2624-2c3d-4f10-b189-1f5b9d32f561) to Sidekiq(mailers) with arguments: "Devise::Mailer", "confirmation_instructions", "deliver_now", {:params=>{:account=>#<GlobalID:0x00007fd2994de3b0 @uri=#<URI::GID gid://chatwoot/Account/1>>}, :args=>[#<GlobalID:0x00007fd2994ddde8 @uri=#<URI::GID gid://chatwoot/User/2>>, "wqDexdrXL1dWsxVRaDox", {:client_config=>"default", :redirect_url=>nil}]}
I, [2022-10-17T13:31:04.035389 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63] [ActiveJob] Enqueued EventDispatcherJob (Job ID: 1d02bb25-3972-420d-85c5-947a50fb79ba) to Sidekiq(events) with arguments: "agent.added", Mon, 17 Oct 2022 13:31:04.034451623 UTC +00:00, {:account=>#<GlobalID:0x00007fd299514f00 @uri=#<URI::GID gid://chatwoot/Account/1>>}
I, [2022-10-17T13:31:04.039091 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63]   Rendered api/v1/accounts/agents/create.json.jbuilder (Duration: 2.6ms | Allocations: 581)
I, [2022-10-17T13:31:04.040549 #1]  INFO -- : [04d5d188-34fb-4537-9393-c3ec170e9e63] Completed 200 OK in 164ms (Views: 2.9ms | ActiveRecord: 10.5ms | Allocations: 11646)
I, [2022-10-17T13:31:04.041075 #1]  INFO -- : source=rack-timeout id=04d5d188-34fb-4537-9393-c3ec170e9e63 timeout=15000ms service=168ms state=completed

```

**Comment by arielesp** [comment]
# docker logs sidekiq

2022-10-17T18:43:09.703Z pid=1 tid=2dgp class=Avatar::AvatarFromUrlJob jid=c64e8341638a81a675f1b40e elapsed=5.025 INFO: done
2022-10-17T18:43:25.545Z pid=1 tid=2dgp class=ActionMailer::MailDeliveryJob jid=107b8ba3812dbea566367d58 INFO: start
I, [2022-10-17T18:43:25.550152 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [470c4146-456f-49d2-b496-c543c497ea90] Performing ActionMailer::MailDeliveryJob (Job ID: 470c4146-456f-49d2-b496-c543c497ea90) from Sidekiq(mailers) enqueued at 2022-10-17T18:42:34Z with arguments: "Devise::Mailer", "confirmation_instructions", "deliver_now", {:params=>{:account=>#<GlobalID:0x00007ff3bd735e20 @uri=#<URI::GID gid://chatwoot/Account/1>>}, :args=>[#<GlobalID:0x00007ff3bd735858 @uri=#<URI::GID gid://chatwoot/User/2>>, "QDfEzbpkFrhVBRvzsM2z", {:client_config=>"default", :redirect_url=>nil}]}
I, [2022-10-17T18:43:25.568280 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [470c4146-456f-49d2-b496-c543c497ea90]   Rendered devise/mailer/confirmation_instructions.html.erb within layouts/mailer/base (Duration: 10.2ms | Allocations: 2023)
I, [2022-10-17T18:43:25.569543 #1]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [470c4146-456f-49d2-b496-c543c497ea90]   Rendered layout layouts/mailer/base.liquid (Duration: 11.5ms | Allocations: 2431)






-- super admin console

mailers | Devise::Mailer#confirmation_instructions | {"_aj_globalid"=>"gid://chatwoot/User/2"}, "QDfEzbpkFrhVBRvzsM2z", {"client_config"=>"default", "redirect_url"=>nil, "_aj_symbol_keys"=>["client_config", "redirect_url"]} | Net::OpenTimeout: execution expired
-- | -- | -- | --

**Comment by pranavrajs** [comment]
`Net::OpenTimeout: execution expired` This seems like the SMTP configuration is wrong. Can you please confirm that you have added the variables correctly?

**Comment by arielesp** [comment]
.env file, this file is in root folder as the docker guide - I dont know if I need setup in another path :
MAILER_SENDER_EMAIL="Chatwoot <livechat@mydomain.com>"
SMTP_DOMAIN=mydomain.com
SMTP_ADDRESS=mysmtphost
SMTP_PORT=587
SMTP_USERNAME=livechat@mydomain.com
SMTP_PASSWORD=mypassword

--
using sendinblue smtp data
--

**Comment by vishnu-narayanan** [comment]
@arielesp Could you verify connectivity to Sendinblue?

```
telnet smtp-relay.sendinblue.com 587
```


Also,
>.env file, this file is in root folder as the docker guide - I dont know if I need setup in another path :
MAILER_SENDER_EMAIL="Chatwoot [livechat@mydomain.com](mailto:livechat@mydomain.com)"
SMTP_DOMAIN=mydomain.com
SMTP_ADDRESS=mysmtphost

Could you share the value for `SMTP_ADDRESS` ?

**Comment by arielesp** [comment]
Hi
I am fixed ... first, I changed to gmail account ... and not sending.. but I received another error ... searching about, the problem was MAILER_SENDER_EMAIL="Chatwoot <livechat@mydomain.com>"

So, I change just to email, like this:
MAILER_SENDER_EMAIL="my@gmail.com"

and now it's working.
