### ISSUE TITLE
Push notifications dont come even for conversations assigned

### ISSUE THREAD

**Issue by ankwad** [chatwoot/chatwoot#5654]
Can anyone help with Push notification
it doesnt work for new messages for an assigned conversation
also if a team is assigned to a conversation .- why doesnt the team get notification for the new messages
Whats the logic of getting push notifications

Also No notifications come for an API chanel - I have assigned the chanel conversation to an agent - still they dont get any notification

**Comment by pranavrajs** [comment]
@ankwad Can you please share the following information? 

- Are you using Chatwoot Cloud or self-hosted Chatwoot?
- Did the user enable the notifications for assigned conversations? (Check profile settings)
- Where are you testing the notifications? (On mobile or On web)

**Comment by ankwad** [comment]
Are you using Chatwoot Cloud or self-hosted Chatwoot?
 -- Self hosted
Did the agent enable the notifications for assigned conversations? (Check profile settings)
-- Yes have made sure the agent has enabled the notifications... all of them 
Where are you testing the notifications? (On mobile or On the web)
-- Testing the notifications.. both on mobile and web

I am using chatwoot public apps.. 
I do get notifications when the super admin assigns the conversation to the agent.
however, I dont get notifications on the following scenarios:-

- notification for New messages in the same assigned conversation
- Messages in API chanel - this doesn't seem to be working at all

**Comment by pranavrajs** [comment]
@ankwad Can you please share a screencast explaining the problem (please include the notification settings you have enabled and the action you are taking in the video)?

**Comment by ankwad** [comment]
Alrite while trying to reproduce I tried few things and figured it out.. 

basically even though the inbox is assigned to the agent every new conversation needs to be owned upon receiving first new conversation notification

For the second I was doing the error of sending message_type as outgoing rather as incoming.

**Comment by ankwad** [comment]
closing
