### ISSUE TITLE
integrate user autentication with OAuth2 solution like keycloak

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#567]
**Is your feature request related to a problem? Please describe.**
users can only autenticate with chatwoot mechanism
**Describe the solution you'd like**

**Describe alternatives you've considered**
If, it's possible would be nice to have an external auth solution, like OAth2 server, which can be used to authenticate users in chatwoot

**Additional context**

**Comment by xgp** [comment]
+1 for wanting this. It would be easier for a lot of orgs to use Chatwoot if it was easier to integrate their existing IdPs. It might be overly restrictive to do this just for Keycloak, as opposed to a more general integration of OpenID or JWT-based systems. 

Alternatively, auth could be replaced with something like [OmniAuth](https://github.com/omniauth/omniauth), which could either use a standard username/password strategy (to be compatible with what is there today), or be configured by the user to use their strategy of choice. There is already a [Keycloak strategy](https://github.com/ccrockett/omniauth-keycloak) and [many](https://github.com/omniauth/omniauth/wiki/List-of-Strategies).

A few ideas:
- Whatever solution you pick should allow some mechanism of using roles from the remote auth system (e.g. picking them out of one of the JWT claims)
- This may require refactoring of the current DB model to migrate away from using a local `user` table, or simplifying that table to be a local map of which IdP the user came from and their remote user ID in that system.

Happy to help out with this if I can.

**Comment by cromulus** [comment]
+1 for Omniauth.

Why not? Omniauth and devise work seamlessly alongside each other, and omniauth will open up a bunch of auth possibilities.

**Comment by XuJinNet** [comment]
+1 OAuth2 and OIDC

**Comment by sojan-official** [comment]
Thanks for the feedback, We will keep this in our backlog for prioritization.
We will share further updates when the team starts working on this.

**Comment by pranavrajs** [comment]
Closing this as #5420 would cover identity related queries.
