### ISSUE TITLE
document use of crowdin cli tool with selfhosted chatwoot to fetch latest translations

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#5679]
**Is your enhancement request related to a problem? Please describe.**
```
Dear Chatwoot Support Team,

Thank you for creating Chatwoot. I am the official and only translator/proofreader of Chatwoot <redacted> language branch. 
Our company has implemented a self-hosted on-premises Chatwoot server via Linux VM and would like to synchronize translate.chatwoot.com translations with the self-hosted server. 
We require this functionality for finetuning <redacted> translation. The server is hosted on-premises, is using Ubuntu 20.04 LTS and its DNS A name is "chatwoot.<redacted>.tld".
Unfortunately, we do not use GitHub, GitLab or any other VCS. The CLI tool is installed and it would be greatly appreciated if you could help us with configuring the CLI tool's configuration file (crowdin init). 

Thank you in advance and hope to hear from you soon.

Production deployment guide for Linux VM
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

Console Client (CLI)
https://developer.crowdin.com/cli-tool/#configuration

Yours sincerely,
Eduards

```

**Describe the solution you'd like**
Use crowdin cli tool to pull latest translations to self-hosted servers.

**Describe alternatives you've considered**
n/a

**Additional context**
Originally reported at https://app.chatwoot.com/app/accounts/1/conversations/19249

**Comment by pranavrajs** [comment]
@vishnu-narayanan I'm not sure if I understand the issue properly. For contributions, they can directly log into the Crowdin instance directly. For production usage, they can pull the latest version from Chatwoot. What is the use case for pulling the translations? The string may have changed in between even if they tried pulling the latest.

**Comment by vishnu-narayanan** [comment]
@pranavrajs To fetch the latest translations for a language from Crowdin before it is merged and available in Chatwoot `develop` branch.

**Comment by pranavrajs** [comment]
@vishnu-narayanan This is not possible and it would create unnecessary stability issues with the installation which would be hard to debug. We would not allow users to manually pull the changes from Crowdin. It has to be updated in the codebase for them to use it.
