### ISSUE TITLE
Huge, slow and unecessary payload on /api/v1/accounts/x/contacts/x/conversations endpoint

### ISSUE THREAD

**Issue by julienmarie** [chatwoot/chatwoot#5685]
**Is your enhancement request related to a problem? Please describe.**
Noticed big slow downs on this endpoint and realized that it was loading the content of all messages in the conversations which is not needed at this point. It's mainly email based conversations that are heavy.

Attached a screenshot from NewRelic

**Describe the solution you'd like**
I don't think the messages of conversations are needed at this point. They should be loaded per conversation on display.

**Describe alternatives you've considered**
No alternative considered. I temporarily fix the issue by resolving problematic email threads as soon as possible so it doesn't pile up.

**Additional context**
Self hosted.
![CleanShot 2022-10-20 at 11 33 27](https://user-images.githubusercontent.com/189369/196850398-366e7c0b-919a-480a-9164-aaf920272911.png)

**Comment by pranavrajs** [comment]
@julienmarie Thanks for reporting this, we will investigate this.

**Comment by pranavrajs** [comment]
@tejaswinichile Please take a look at this whenever you have time in the next sprint. It seems like we might be missing the pagination param. Paginating the conversations/message would solve the issue IMO.

**Comment by julienmarie** [comment]
Thanks @pranavrajs  :) Pagination seems ok, it's just the json object is returning all messages inside each conversation. In our case, we often receive html emails, and it seems quite heavy for the Rails JSON encoder.

**Comment by julienmarie** [comment]
@pranavrajs @tejaswinichile Would you like me to send you an example of the JSON response that took a minute ? Please tell me where to send it securely

**Comment by pranavrajs** [comment]
@julienmarie Please send the payload to hello@chatwoot.com.

**Comment by julienmarie** [comment]
@pranavrajs Sent! Thank you!

**Comment by tejaswinichile** [comment]
This will not cause the issue, as we have introduced the limit of (20) to the conversation, and if there are unread_messages available in conversations, we fetch the last 10 messages and if all the messages are in read state then we fetch only the last message with an attachment. 

@julienmarie Please confirm and reopen if you are still facing the issues
