### ISSUE TITLE
Push notifications and attachments

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5689]
Hi all,

since yesterday I am using a self hosted docker version of chatwoot.
My situation now:

- I can access the agent interface and the user interface (website widget) over my own domain and https
- Communication between user and agent works
- my iphone app (as agent) works

What does not work:
- Push Notifications with Firefox / Safari (normal?) - With Google Chrome it works

![Bildschirmfoto 2022-10-20 um 08 35 00](https://user-images.githubusercontent.com/17011498/196924986-917f1ce3-9ddf-44eb-9c25-a0f7fd1da6e4.png)

- If I upload a new avatar image for my profile - the upload works, but If reload the page, the avatar is not visible - only a blue circle as placeholder

- If I or a user via Widget sent a attachment - it looks like this:

![Bildschirmfoto 2022-10-20 um 11 53 16](https://user-images.githubusercontent.com/17011498/196925569-2a55e615-ad1d-4a9d-b43b-49f81d35d3bb.png)

This is my picture header.jpg. If I click "Herunterladen" (=download) it will open the follwoing page:
`
https://myChatwoodDomain.tld/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhZbm93WW10dFozVnBkRzB5Y0dScmFHczBZbnBzY0hodGJITjRNd1k2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpUDJsdWJHbHVaVHNnWm1sc1pXNWhiV1U5SW1obFlXUmxjaTVLVUVjaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkoyaGxZV1JsY2k1S1VFY0dPd1pVT2hGamIyNTBaVzUwWDNSNWNHVkpJZzlwYldGblpTOXFjR1ZuQmpzR1ZEb1JjMlZ5ZG1salpWOXVZVzFsT2dwc2IyTmhiQT09IiwiZXhwIjoiMjAyMi0xMC0yMFQwOTo1OToxMS42OTBaIiwicHVyIjoiYmxvYl9rZXkifX0=--89593b3952f30ca5785263dbb9f6210fbe31d16d/header.JPG`

And no picture. because the link is invalid.

**Comment by Ghost108** [comment]
nobody?

**Comment by vishnu-narayanan** [comment]
Have you tried using an external cloud storage service for ActiveStorage?
ref: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

**Comment by vishnu-narayanan** [comment]
>Push Notifications with Firefox / Safari (normal?) - With Google Chrome it works
I am using Firefox and notification are working for me. Could you share your FF version and OS?

**Comment by vishnu-narayanan** [comment]
Does FF prompt you to allow notifications when clicking on the `Enable Push Notifications` button?
![image](https://user-images.githubusercontent.com/3526167/1971
91165-3ab7df45-9139-48a9-b68a-ab3d283f9c1d.png)

**Comment by Ghost108** [comment]
Yes and I allowed this

**Comment by Ghost108** [comment]
any updates here?
