### ISSUE TITLE
Stuck in webpacker:compile in 'rake assets:precompile RAILS_ENV=production'

### ISSUE THREAD

**Issue by Azfarrr** [chatwoot/chatwoot#5696]
I don't know if it is permitted to post an issue that has been solved but I'll just post for other's reference.

This past week, I am trying to update my self hosted chatwoot installation, on AWS ubuntu 20.04 instance.I followed the official [guide](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm/) on how to update my chatwoot version, and stuck on step `rake assets:precompile RAILS_ENV=production`. 

The longest I let the command run is around 3 hours. Tried many times. Also tried running 
`RAILS_ENV=production rake assets:clean assets:clobber assets:precompile` as in the guide, still to no avail. I tried also to run `./bin/webpack --debug`, this just run/test the webpacker compilation step, but to no avail.

My instance in aws is using spec as follows:

type: t3.small
CPU: 2 vCPU
RAM: 2GB
storage: 64GB

Then I read somewhere in stackoverflow that other users are having similar issues, stuck in webpacker assets compiling due to memory leak etc. I tried upgrading my instance to t3.medium, same CPU but with 4GB of RAM, then tried again. 
Well the compilation completed successfully! I think it took less around 20 to 30 minutes to finish, but nevertheless the job is done.

Conclusion: The recommended spec (minimum 8GB of RAM) is there for a reason.

**Comment by vishnu-narayanan** [comment]
@Azfarrr Thank you for taking the time and effort to share this. 😅 Yeah, the assets compilation is quite resource-heavy, and we are looking into ways to bring that down.

A solution is to use docker-based deployment to skip the compilation stage from your end altogether.

**Comment by theguy147** [comment]
Any news on this issue apart from the suggestion of using the docker deployment instead? Thanks

**Comment by vishnu-narayanan** [comment]
@theguy147 increasing the ram to 8GB or more will solve the problem.
