### ISSUE TITLE
Some error in install.sh --install

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#5701]
When i try install chatwoot on a fresh ubuntu 20.04 i get following error :

wget https://get.chatwoot.app/linux/install.sh
chmod +x install.sh

# ./install.sh --install
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Some error has occured. Check '/var/log/chatwoot-setup.log' for details.

**Comment by vishnu-narayanan** [comment]
@mmojadad This information is not enough to debug. Could you share more details?

https://github.com/chatwoot/chatwoot/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by mmojadad** [comment]
@vishnu-narayanan

Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
-------------------
docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-131-generic
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.84GiB
 Name: nwalinux
 ID: PLBU:HY4Z:CHG2:WQ7Q:453K:36PZ:QDDT:DNGK:BG42:5GTV:RIM6:37CK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://registry.docker.ir/
 Live Restore Enabled: false

WARNING: No swap limit support
---------------------
docker-compose version 1.25.0, build unknown

---------------------
chatwoot-setup.log is generated but its empty!

Please let me know if more info is need

**Comment by paginare** [comment]
just install curl 

sudo apt-get install curl

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.

**Comment by ramstein74** [comment]
I have the same problem
I installed virtual box then ubuntu 22.04 and i get the same error
![image](https://github.com/chatwoot/chatwoot/assets/1210858/0c9f0c00-05e8-49dc-a8c3-a7dc586d9572)
the var/log/chatwoot-setup.log is empty!
any help ?

**Comment by vishnu-narayanan** [comment]
@ramstein74 It should be `./install.sh --install`.

**Comment by ramstein74** [comment]
yes you are correct , i wrote -install instead of --install 
but with --install i get the same python error. 

regards
