### ISSUE TITLE
Error 429 after aktivating pre chat

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5703]
**Describe the bug**
I activated the option pre chat for the widget (fields fullname).
After click on "Unterhaltung beginnen" nothing happens.
If I disable the option "pre chat" it works.

**Screenshots**
![Bildschirmfoto 2022-10-21 um 12 51 05](https://user-images.githubusercontent.com/17011498/197179396-5970f338-4a59-4d62-a7a7-e012623dca3d.png)

**Browser logs**
[Error] Failed to load resource: the server responded with a status of 429 () (conversations, line 0)

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [X] Self-hosted
- - [x] Docker

**Desktop (please complete the following information)** (If applicable)
 - OS: [MacOS]
 - Browser [firefox,safari]
 - Version [newest version]

**Comment by pranavrajs** [comment]
@Ghost108 There is a limit on the number of conversations you can create per hour. If you exceed that you would be blocked by the system. Is it happening on the first try?

**Comment by Ghost108** [comment]
No, not on the first try. but why it will block with active pre chat option and will not block, if I disable the pre chat option?

**Comment by Ghost108** [comment]
any updates here?
