### ISSUE TITLE
The full name is not updating when creating a conversation from the widget

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5705]
Self hosted via Docker

If you activate the pre chat option wit the fields fullname and email, it works fine:
<img width="971" alt="Bildschirmfoto 2022-10-21 um 15 22 22" src="https://user-images.githubusercontent.com/17011498/197206436-f2efca36-0f48-4deb-a583-31475ac2cc90.png">

<img width="333" alt="Bildschirmfoto 2022-10-21 um 15 21 25" src="https://user-images.githubusercontent.com/17011498/197206515-812c2860-cd54-468e-88bf-ce9d1a122a47.png">

As a agent, I get all values:
<img width="324" alt="Bildschirmfoto 2022-10-21 um 15 21 50" src="https://user-images.githubusercontent.com/17011498/197206620-d875f321-6cf6-40ae-ac07-2f00404c2a63.png">

But If I would only set fullname active in the pre chat:
<img width="955" alt="Bildschirmfoto 2022-10-21 um 15 22 32" src="https://user-images.githubusercontent.com/17011498/197206709-c790d544-4589-4592-a5fc-8deec8ef544e.png">

<img width="328" alt="Bildschirmfoto 2022-10-21 um 15 23 00" src="https://user-images.githubusercontent.com/17011498/197206739-2d75f9e8-1d40-40c9-8d10-5921563cdeda.png">

Do I not get the name transmitted
<img width="256" alt="Bildschirmfoto 2022-10-21 um 15 23 18" src="https://user-images.githubusercontent.com/17011498/197206917-99e0ab3b-36fd-4ff9-ae8c-a5b7e13821d4.png">

**Comment by pranavrajs** [comment]
@Ghost108 Thanks for reporting the issue. @muhsin-k Can you please check if you can reproduce the behaviour?

**Comment by muhsin-k** [comment]
The issue is reproducible.

**Comment by muhsin-k** [comment]
Currently, the contact name will only add if an email ID exists.

Reference
https://github.com/chatwoot/chatwoot/blob/develop/app/controllers/api/v1/widget/base_controller.rb#L53 

We could do something like this,
```
def contact_name
   permitted_params.dig(:contact, :name) || (contact_email.split('@')[0] if contact_email.present?)
end
```

 The issue with this approach is that the contact name will be rewritten if the contact already exists.

@pranavrajs @sojan-official

**Comment by muhsin-k** [comment]
> Currently, the contact name will only add if an email ID exists.
> 
> Reference https://github.com/chatwoot/chatwoot/blob/develop/app/controllers/api/v1/widget/base_controller.rb#L53
> 
> We could do something like this,
> 
> ```
> def contact_name
>    permitted_params.dig(:contact, :name) || (contact_email.split('@')[0] if contact_email.present?)
> end
> ```
> 
> The issue with this approach is that the contact name will be rewritten if the contact already exists.
> 
> @pranavrajs @sojan-official

@sojan-official / @pranavrajs  What would be the better approach here?

**Comment by pranavrajs** [comment]
@muhsin-k 

- If the contact is already identified, ie: we have a contact that exists in the database with the same email address or phone number or identifier, then we should not overwrite the information from the pre-chat form as it might mess up the existing contact.
- If the contact is new, we can use the pre-chat form information directly.
