### ISSUE TITLE
Ability to disable inbox on a website

### ISSUE THREAD

**Issue by Christilut** [chatwoot/chatwoot#5708]
**Is your feature request related to a problem? Please describe.**
It would be nice if I could disable an inbox.

**Describe the solution you'd like**
A toggle button in the inbox configuration to disable an inbox so it no longer appears on my website, without having to remove the chatwoot code.

**Describe alternatives you've considered**
The only other way is to remove/update the code from the website

**Additional context**
This is especially useful when going on vacation or deprecating a website

**Comment by iammattmartin** [comment]
dupe of #4320 and nearly #273.

Long asked feature but nothing coming it seems.

**Comment by pranavrajs** [comment]
We will track the progress over https://github.com/chatwoot/chatwoot/issues/5904
