### ISSUE TITLE
Support CSML Messages Wait & Url 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5709]
- Add support for CSML functions Wait, URL

**Comment by sojan-official** [comment]
At the moment, it is not supported. We will take this up for future iterations

**Comment by giquieu** [comment]
@sojan-official 
I find the Wait function very interesting.
I'd like to look into it, but I'd rather hear your ideas first. Any initial ideas on how to do it?

**Comment by giquieu** [comment]
@sojan-official @pranavrajs 
The easiest solution would be to use sleep, but it doesn't seem ideal...
What are the impacts of using sleep?

**Comment by sojan-official** [comment]
@giquieu  We could enqueue follow-up jobs in sidekiq with the wait time 
sleep is a very inefficient solution, as it will block the thread until further execution.

**Comment by pranavrajs** [comment]
Closing this as we will be removing the CSML integration in the January release. No new bot can be added, although the existing ones would work.
