### ISSUE TITLE
Bug when editing words

### ISSUE THREAD

**Issue by GyR4uk** [chatwoot/chatwoot#5716]
Bug when editing words

[Запись экрана от 23.10.2022 15:13:07.webm](https://user-images.githubusercontent.com/35705596/197391480-bbdf71ce-3567-4f6e-9b06-61c4190dfcec.webm)

**Comment by pranavrajs** [comment]
Thanks for reporting the issue. Closing this as this is a duplicate of https://github.com/chatwoot/chatwoot/issues/5622
