### ISSUE TITLE
feat: support Oauth for Email Channel

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#5724]
Microsoft has already begun deprecating basic authentication for office 365 using IMAP and SMTP. Unfortunately, there are no workaround app passwords like Gmail. It will be completely removed the first week of 2023. For reference,

https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online

**Comment by Jatin-MYST** [comment]
@sojan-official Since it was removed from v2.11.
Whats the expected release of this feature now?

**Comment by pranavrajs** [comment]
@Jatin-MYST This would be released before January 2023 as Microsoft would permanently disable the basic auth feature. For now, you can enable it using this guide. https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-september/ba-p/3609437

**Comment by pranavrajs** [comment]
https://developer.microsoft.com/en-us/graph/graph-explorer
https://learn.microsoft.com/en-us/graph/outlook-mail-concept-overview

**Comment by kry** [comment]
Any updates on this topic? I'm not able to connect to my office 365 IMAP.

**Comment by GuiVKDigital** [comment]
My IMAP is working but SMTP is not. And there's no information in the logs

**Comment by kry** [comment]
Both Outlook en Gmail IMAP are not working for me.

**Comment by vishnu-narayanan** [comment]
https://github.com/chatwoot/chatwoot/pull/6183

**Comment by vishnu-narayanan** [comment]
fixed by https://github.com/chatwoot/chatwoot/pull/6227

**Comment by kry** [comment]
I have upgraded to version 2.13.0 with support for microsoft oauth.
I followed the guides here:
- https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup
- https://www.chatwoot.com/docs/product/channels/email/microsoft/create-channel

When I connect to my microsoft oauth the callback is called correctly but I return back to the main page of chatwoot and not the email-channel I'm setting up.

The callback url I use is this: https://<chatwoot-url>/microsoft/callback

Any idea what I'm doing wrong?

**Comment by kry** [comment]
@tejaswinichile I think my issue is the same as this one: [https://github.com/chatwoot/chatwoot/issues/6353](url)

**Comment by evolve2k** [comment]
Checking in on this one. 

On 7 Jan @GuiVKDigital said:

> My IMAP is working but SMTP is not. And there's no information in the logs

On 12 Jan @vishnu-narayanan said:

> fixed by https://github.com/chatwoot/chatwoot/pull/6183
> fixed by https://github.com/chatwoot/chatwoot/pull/6227

But https://github.com/chatwoot/chatwoot/pull/6183 was closed by @sojan-official without merging.
Was https://github.com/chatwoot/chatwoot/pull/6183 included in https://github.com/chatwoot/chatwoot/pull/6227 ?


As at today, IMAP is working for us but SMTP is not. 
Together are the changes https://github.com/chatwoot/chatwoot/pull/6183  https://github.com/chatwoot/chatwoot/pull/6183  resolved or sort of still open?

Where are we at?

**Comment by vishnu-narayanan** [comment]
@evolve2k The changes in #6183 were split into two PRs and merged. 

    https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup
    https://www.chatwoot.com/docs/product/channels/email/microsoft/create-channel


cc: @sojan-official @tejaswinichile

**Comment by jordan26** [comment]
> I have upgraded to version 2.13.0 with support for microsoft oauth. I followed the guides here:
> 
>     * https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup
> 
>     * https://www.chatwoot.com/docs/product/channels/email/microsoft/create-channel
> 
> 
> When I connect to my microsoft oauth the callback is called correctly but I return back to the main page of chatwoot and not the email-channel I'm setting up.
> 
> The callback url I use is this: https://chatwoot-url/microsoft/callback
> 
> Any idea what I'm doing wrong?

Did you manage to resolve? I am some others are having the same issue, redirected but no inbox created.

**Comment by sojan-official** [comment]
There are some changes from Microsoft's end for email channels; we have an updated doc for this. please follow : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/

also ensure your chatwoot installation is on the latest version.

**Comment by sojan-official** [comment]
Closing this issue since we have Microsoft Channel available
