### ISSUE TITLE
Macros - Allow adding a private note

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5733]
“Add private note” with content. (Use rich content editor, support @mentions as well).

Similar to "Send Message". Allow the agents to add an action to add private notes. Rich content or @mentions are not needed in v1. Those are good to have.

**A sample use case:**
We get invalid chats in our cloud. We can close it directly by sending a message to the customer and adding a private note on why we thought of closing it directly (generally falls into one or two categories. Having a pre-defined text in a private note helps with the quick scan of conversation)

**Comment by tejaswinichile** [comment]
Rich content will be handled later.
