### ISSUE TITLE
Test the community plugin for Nuxt 3/Vue 3 and add it to the docs

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5739]
- Test the plugin available at https://opensource.huntersofbook.com/guide/nuxt-packages/chatwoot/
- Add it to the docs with the label `community maintained`.

**Comment by pranavrajs** [comment]
@fayazara Please take a look at this whenever you have time.

**Comment by productdevbook** [comment]
Vue 3: https://github.com/huntersofbook/huntersofbook/tree/main/packages/chatwoot-vue

Nuxt 3: https://github.com/huntersofbook/huntersofbook/tree/main/packages/chatwoot-nuxt

**Comment by pranavrajs** [comment]
Closing this as the documentation is live.
