### ISSUE TITLE
[CW-2585] Help Center: Support logo upload for the header

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5754]
- [ ] Allow admins to upload the logo on the header.

<sub>[CW-2585](https://linear.app/chatwoot/issue/CW-2585/help-center-support-logo-upload-for-the-header)</sub>

**Comment by sojan-official** [comment]
[https://discord.com/channels/647412545203994635/1161392826781814885/1161392826781814885](https://discord.com/channels/647412545203994635/1161392826781814885/1161392826781814885)
