### ISSUE TITLE
Help Center: Fix the article view count

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5756]
- The count is always 0 

<img width="1110" alt="Screenshot 2022-10-25 at 7 34 52 PM" src="https://user-images.githubusercontent.com/2246121/197920938-43a219c0-2788-4e61-a552-f6fd68ef117f.png">

**Comment by murtaza-bagwala** [comment]
@pranavrajs shall I pick this up ?

**Comment by pranavrajs** [comment]
@murtaza-bagwala Sure, please.
