### ISSUE TITLE
Problem adding email channel inbox

### ISSUE THREAD

**Issue by walderfranco** [chatwoot/chatwoot#5765]
Hello, I have Chatwoot installed in Caprover but when I try to connect an email and it generates the forwarder it appears like this and google workspace does not accept it.

Is it some missing or misplaced environment variable?
xxxxxxxxxxx795a9aa@false

![image](https://user-images.githubusercontent.com/49401126/198051994-a37aa507-eb43-4898-be3b-77fbbaa63b2c.png)

**Comment by vishnu-narayanan** [comment]
It should be of the format `<random-hex-code>@domain.com`. Have you configured the conversation continuity-related variables?

https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity

**Comment by vishnu-narayanan** [comment]
Please reopen if you are facing this issue now.
