### ISSUE TITLE
WA (Cloud API) Messages are sometimes not being delivered

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#5770]
**Describe the bug**

WA messages dispatched through the web interface (not tested on mobile) using the WA Cloud API are regularly not being delivered for unknown reasons. This is correctly acknowledged in the interface, the checkmark being missing.
**To Reproduce**

Unclear. I have not been able to see a pattern. What *is* clear is that a message is never being delivered outside of the 24 hour contact window (which is expected, of course). However delivery also fails on template messages (in an attempt to open that window) as well as with messages inside an open 24 hour window. 

This will also happen regardless of the content type of the message (i.e. a single picture or just text both failing to deliver)

**Expected behavior**

Either actionable and obvious feedback as to why the delivery failed or automatic retries, until it works.

**Server logs**
[web.log](https://github.com/chatwoot/chatwoot/files/9880821/web.log)
[worker.log](https://github.com/chatwoot/chatwoot/files/9880822/worker.log)

Both logs have been isolated to timewise coincide roughly with this situation:

<img width="369" alt="image" src="https://user-images.githubusercontent.com/1176036/198333986-6b532042-2e22-4200-b78e-d4f6ab0fd7e5.png">

First a template message that did not get delivered, then one that does. In this instance the first one was triggered through the contact screen (which is not a requirement for this bug to trigger, but there was no ongoing conversation).

**Environment**

- [x] Self-hosted
- - [x] Linux VM

Hosted on a dedicated CPX21 Hetzner instance, load ~0, mem 40%, plenty disc space

**Desktop (please complete the following information)** (If applicable)
 - OS: MacOS
 - Browser: Current Chrome

**Comment by weppa-cloud** [comment]
The problem occurs when I send the template from this interface
![imagen](https://user-images.githubusercontent.com/69656828/199254201-bb9052ba-bc69-4af0-8fc7-234e5adc6685.png)

![imagen](https://user-images.githubusercontent.com/69656828/199254459-293b34b8-cec1-4303-a8aa-958d3d484c87.png)


When I have already created the new conversation and send the template like this, it is sent correctly
![imagen](https://user-images.githubusercontent.com/69656828/199254653-cb83d6bc-1afd-434c-8e56-8f24c1a346c3.png)

**Comment by sojan-official** [comment]
@weppa-cloud @jochenstu  Thanks for the detailed reports.
let's track his over https://github.com/chatwoot/chatwoot/issues/5481
