### ISSUE TITLE
web widget is not showing on iOS

### ISSUE THREAD

**Issue by arielesp** [chatwoot/chatwoot#5781]
The start chat, web widget is not showing when on iOS device

Works fine in Android and desktop browsers

Just paste widget code in html page, example
https://meu-servidor.com/teste1.html

Using chatwoot docker version, latest update to now.

**Docker** 
Please share the output of the following.
- `docker version` Docker version 20.10.5+dfsg1, build 55c4c88
- `docker info`
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc., v2.12.2)

Server:
 Containers: 8
  Running: 7
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 20.10.5+dfsg1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1.4.13~ds1-1~deb11u2
 runc version: 1.0.0~rc93+ds1-5+deb11u2
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: ns576389.servidor101.xyz
 ID: 4ECK:W6HY:7OOY:T6IU:DSJZ:SS5N:OP3F:LTXY:2IXT:H6DA:JM2T:WITV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: Support for cgroup v2 is experimental

- `docker-compose version`
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022

thanks in advanced

**Comment by pranavrajs** [comment]
@arielesp This seems to be a problem with the SSL configuration. The URL `https://livechat.cactusgaming.net/` is not accessible in safari. Fixing the SSL certificates should fix this issue. Please feel free to reopen if it is not the case.
