### ISSUE TITLE
Strange behavior when API channel uses business hours

### ISSUE THREAD

**Issue by fhonline** [chatwoot/chatwoot#5794]
I would like to report a strange situation with Chatwoot: when we create an API-type channel and use the ENABLE BUSINESS HOURS part (we put the message and the time intervals) the messages triggered in the channel's webhook vary from company to company.

Today I use Chatwoot in SaaS mode, and for example, company 1 fires a json in the channel's webhook with the created conversation + created message, and this created message comes in 2 parts in the json: 1 with welcome (programmed in automations) at the top and another with the away message. I registered company 2, and programmed the time of absence, this same message repeatedly comes with welcome in both parties (the absence message does not appear). In company 3, for example, the welcome comes at the top and below comes the message that the contact himself sent, a “hello” or “good afternoon”.

SUMMARY: there is a strange behavior, there is no pattern in receiving the away message, when the channel is API.
If you need evidence, videos or other situations I can raise it.

Version 2.6.0
installed via NPM

I speak in Portuguese, I can make a video demonstrating

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199839521-cc19038d-968f-4697-9527-b996e01dd8fa.png)

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199839731-cb154b5a-48fd-4726-9b10-406ebb82ee65.png)

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199840152-50be07bb-0534-4f54-9658-e70397d53475.png)

**Comment by fhonline** [comment]
The example above is from account 1

**Comment by fhonline** [comment]
The example above is from account 1

Now below I will show the shipments of company 2:

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199841249-65283b05-5102-43ea-8c71-94745ba46b15.png)

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199841384-7c900b70-80ff-4191-a258-f2ad570f72cd.png)

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199841587-60110cac-dcb3-4917-b3a5-6a15ee8ecd6f.png)

**Comment by fhonline** [comment]
now i will show you account 3

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199842712-cb9f618c-4709-4558-89d5-38c9c6b80bdb.png)

**Comment by fhonline** [comment]
![image](https://user-images.githubusercontent.com/95591514/199842895-c5cd2c14-8868-4629-adf8-d84957cde019.png)

**Comment by fhonline** [comment]
the 3 accounts have the same automation configuration and business hours, but both behave differently, not being possible to capture the automation message and the business hours message... in short, that would be the problem

I would like to know the pattern of this!

**Comment by pranavrajs** [comment]
@fhonline Can you please share the webhook event you are listening to?

**Comment by fhonline** [comment]
Here we go: when a conversation is created outside of business hours, 3 events are triggered in the webhook: 

1-conversation created 
2-message created of the outbound type 
3-message created of the incoming type

As I said in the previous images, the problem is that the messages created (outbound and incoming) when out of scheduled business hours do not follow a “standard” to be followed, it varies from company to company.

 To reproduce the test, do the following:

 1- create 3 companies in chatwoot (accounts)
 2- in each account, create a conversation type automation rule created with open status and a welcome message
 3- set a business hours for each one
 4- monitor the webhook of each account when opening a new conversation: you observe that each account will have different webhook content

 Any questions, let me know.

**Comment by sojan-official** [comment]
Should be fixed by https://github.com/chatwoot/chatwoot/pull/7620 

Note: for the business hours away message: it will be triggered to the user only once every 24 hours
