### ISSUE TITLE
Is there any feature about chat button icon change?

### ISSUE THREAD

**Issue by nhsdigigate** [chatwoot/chatwoot#5815]
I need to change the "Chat Button Icon" on the website as the first entry point for the user. Is there already an option in the settings or is there a parameter for the chatwoodSDK to use a fontawesome icon or custom defined svg ?

Sadly, I can't find anything in the handbook or in the chatwood app settings.

I would be very excited if you could provide me further information.

Best regards,

Sourab

**Comment by iammattmartin** [comment]
#4490

**Comment by sojan-official** [comment]
closing in favour of #4490
