### ISSUE TITLE
central support

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5817]
** Englisch Version **
Hi all!

I would like to draw attention to this forum => www.chatwoot-community.com 
It's new and should serve as a central point for Chatwoot support, instead of multiple platforms (Github, Discord, ...).

These platforms are still available - however, I would find a central platform better and clearer.
I would be happy if you would support this idea. Support will be available in english and german.

Thank you very much - let's make chatwoot better together!

++ For this platform I got permission from Chatwoot support (Contact: Nithin David Thomas) ++

----------------------------------------

** Deutsche Version **
Hallo zusammen!

Ich möchte gerne auf dieses Forum aufmerksam machen => www.chatwoot-community.com 
Es ist neu und soll als zentrale Anlaufstelle für Chatwoot-Support dienen, anstelle von mehreren Plattformen (Github, Discord, ...).

Diese Plattformen stehen zwar weiterhin zur Verfügung - ich fände aber eine zentrale Plattform besser und übersichtlicher.
Ich würde mich freuen, wenn ihr diese Idee unterstützen würdet. Der Support wird in englisch und deutsch verfügbar sein.

Vielen Dank - lassen Sie uns gemeinsam Chatwoot besser machen!

++ Für diese Plattform habe ich die Erlaubnis vom Chatwoot-Support (Kontakt: Nithin David Thomas) ++

**Comment by sojan-official** [comment]
Closing this as this isn't an issue. 
also duplicate: https://github.com/chatwoot/chatwoot/discussions/5818
