### ISSUE TITLE
WhatsApp New Message not sending

### ISSUE THREAD

**Issue by GKG4** [chatwoot/chatwoot#5834]
When selecting a contact from the list and selecting the WhatsApp channel.
The first message selected as the template is not actually sent to the contact and only shows in the conversation history, however, sending another message template from the conversation window is working.

So basically, the first template sends request is not executing if sent from contacts.

**Comment by pranavrajs** [comment]
@GKG4 This was already a reported bug as you can see in #5128. The fix is already merged in #5802. You should be able to get this patch in the next update on Nov 15.

**Comment by iammattmartin** [comment]
We updated last night and this still remains a problem with templates. Attempted many times but the user never gets message.

If the WhatsApp contact sends one to the number in CW, two way messages then work fine.

**Comment by pranavrajs** [comment]
Please see this comment. https://github.com/chatwoot/chatwoot/issues/5128#issuecomment-1316231093
