### ISSUE TITLE
detect when users change twitter username or delete their accounts and notify in chatwoot

### ISSUE THREAD

**Issue by notnotrishi** [chatwoot/chatwoot#5839]
Currently when Chatwoot syncs tweets to Twitter Inbox there's no way to know if the user deleted their account or changed their username since they sent the tweet. When we reply the tweet thus gets posted on the main timeline causing confusion

e.g.
![image](https://user-images.githubusercontent.com/6056505/201118983-2c1ae23f-2a6f-4452-9a25-e59e7b766318.png)

Either we need a way to know that the user is no longer active or changed username, or the tweet reply should fail when that happens.

**Comment by pranavrajs** [comment]
@notnotrishi Thanks for the suggestion. 

We might need to do a user lookup before sending the tweets and warn the agent. 
https://developer.twitter.com/en/docs/twitter-api/users/lookup/introduction

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
