### ISSUE TITLE
Duplicate conversations and contacts (WA and Brazil numbers)

### ISSUE THREAD

**Issue by ASchneiderBR** [chatwoot/chatwoot#5840]
**Describe the bug**

Hello. Here in Brazil, we had a change on mobile numbers a few years ago, they've added an extra leading digit to account the total numbers growth over the last years. The general change was to add a leading 9 over all current numbers. Most WA users have their accounts registered to the old number, without the leading digit. When we start a conversation with Chatwoot, we add the correct number, with the leading digit but when the user responds, Chatwoot creates both a new contact and a new conversation ticket with the registered, old number, without the leading number. This is a major problem, because it breaks the ticket flow and duplicates contacts.

**To Reproduce**

Create a contact with the "new", correct number, then start a conversation, wait for them to respond, check conversations and contacts.

**Expected behavior**

Contacts and conversations should not duplicate.

**Environment**

I'm currently using Chatwoot cloud.

**Comment by tejaswinichile** [comment]
@ASchneiderBR If you edit the contact before the customer reaches out to you with a new number does it work?

<img width="150" alt="Screenshot 2022-11-15 at 9 57 18 AM" src="https://user-images.githubusercontent.com/10827585/201826387-70fcd47a-661b-41cd-b864-6f503e19dae9.png">

**Comment by glauberssoutodossantos** [comment]
Hi @tejaswinichile i have the same problem. Follow the images bellow.



For exemple:

I create a contact with WhatsApp number +55 41 **9** 8888-7777 (notice the 9 after the country code).

The user respond my message and chatwoot create another contact and another conversation with number +55 41 8888-7777 (notice we do not have the 9 after the country code).


My first message.

![image](https://user-images.githubusercontent.com/99494469/202171670-c69d1e7b-6287-45c9-b0a4-880ba071924f.png)

When chatwoot create another contact with another number. Is almost the same, but with out the 9.

![image](https://user-images.githubusercontent.com/99494469/202171887-f50ee287-5f40-4e90-be22-f4b3ec966135.png)

It problem only in Brazil, because this new format number. Some WhatsApp account have the 9 and another ones does not have this number :(

**Comment by ASchneiderBR** [comment]
Hello @tejaswinichile, if you want to test this with me, using my persona mobile phone, I'll see the exact behavior of this issue. Just let me know of how can I send my mobile number privately. Thanks.

**Comment by glauberssoutodossantos** [comment]
Hi @tejaswinichile how are you.

We resolve this problem here in our self-host app.

Let me know if can we do pullrequest for chatwoot.

**Comment by ASchneiderBR** [comment]
Hello @tejaswinichile, can you please take a look at this? It seems that @glauberssoutodossantos has the solution to this problem, it would be great to fix this problem for WhatsApp users from Brazil. Thanks!

**Comment by sojan-official** [comment]
@glauberssoutodossantos  could you do a pull request ? We will take a look.

**Comment by glauberssoutodossantos** [comment]
@sojan-official @jacsonsantospht from my team will open the PR today.

**Comment by jacsonsantospht** [comment]
[PR opened](https://github.com/chatwoot/chatwoot/pull/6222)

@glauberssoutodossantos @ASchneiderBR @sojan-official

**Comment by sojan-official** [comment]
@jacsonsantospht  Thanks a lot. We will take it forward.

**Comment by ASchneiderBR** [comment]
Hello @sojan-official, sorry to ask: is this added to the latest 2.13.0 version? That would be great since this is a real problem for us, Brazilian WA users. Thanks!

**Comment by sojan-official** [comment]
@ASchneiderBR  it wasn't added in 2.13.0 as the team didn't have the bandwidth QA it. We will keep it for 2.14.0

**Comment by ASchneiderBR** [comment]
Hello @sojan-official. I've noticed that milestone 2.15 was updates in this issue. Does this fiz was included on the latest 2.14 release? Thanks.

**Comment by sojan-official** [comment]
@ASchneiderBR, we are waiting to add some specs to the PR before merging it. Hence it didn't make it to the 2.14.0 . We will be merging it to develop in the coming weeks.

**Comment by ASchneiderBR** [comment]
Hello @sojan-official, sorry but it seems that the latest update did not fixed the issue. Maybe @glauberssoutodossantos could help us all? Thanks.

**Comment by glauberssoutodossantos** [comment]
Hi @ASchneiderBR 

To me it seems to be working normally.

See the example below.

I registered my number in the format:

+55 41 9 8502-xxxx

My personal WhatsApp is in the format

+55 41 8502-xxxx.

Still he managed to associate the conversation with the same contact.
![image](https://user-images.githubusercontent.com/99494469/225987741-0fc95fa0-8456-404a-9e27-ad07d26f828a.png)

**Comment by ASchneiderBR** [comment]
Hello @glauberssoutodossantos, I can confirm that I no longer receive the message when I start a conversation with the added 9 digit, only with the "old" number, without the leading 9. Thanks.
