### ISSUE TITLE
Docker image build issue

### ISSUE THREAD

**Issue by sunilravilla** [chatwoot/chatwoot#5842]
**Describe the bug**

**To Reproduce**

4. See the error

**Expected behavior**

Share a clear and concise description of what you expected to happen.

```
 docker build ./docker
[+] Building 41.6s (12/22)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 2.77kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ruby:3.0.4-alpine                                              41.5s
 => [pre-builder  1/13] FROM docker.io/library/ruby:3.0.4-alpine@sha256:435349b6ab0da1bf157db4ae40a07a505dbeace30  0.0s
 => => resolve docker.io/library/ruby:3.0.4-alpine@sha256:435349b6ab0da1bf157db4ae40a07a505dbeace30506f4810dfbaaa  0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 3.10kB                                                                                0.0s
 => CACHED [pre-builder  2/13] RUN apk add --no-cache     openssl     tar     build-base     tzdata     postgresq  0.0s
 => CACHED [pre-builder  3/13] WORKDIR /app                                                                        0.0s
 => ERROR [pre-builder  4/13] COPY Gemfile Gemfile.lock ./                                                         0.0s
 => CACHED [pre-builder  5/13] RUN apk add --no-cache musl ruby-full ruby-dev gcc make musl-dev openssl openssl-d  0.0s
 => CACHED [pre-builder  6/13] RUN bundle config set --local force_ruby_platform true                              0.0s
 => CACHED [pre-builder  7/13] RUN if [ "production" = "production" ]; then   bundle config set without 'developm  0.0s
 => ERROR [pre-builder  8/13] COPY package.json yarn.lock ./                                                       0.0s
------
 > [pre-builder  4/13] COPY Gemfile Gemfile.lock ./:
------
------
 > [pre-builder  8/13] COPY package.json yarn.lock ./:
------
failed to compute cache key: "/yarn.lock" not found: not found
```

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - Browser [e.g. stock browser, firefox, safari]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

**Comment by vishnu-narayanan** [comment]
@sunilravilla Could you please update the issue with steps to reproduce, information about your environment, and the details on your `docker` version?

**Comment by vishnu-narayanan** [comment]
Please reopen if you are facing this issue now.
