### ISSUE TITLE
Ability to send the same whatsapp template to multiple contacts

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#5851]
**Is your enhancement request related to a problem? Please describe.**
Currently there is no option to send the same whatsapp template to multiple contacts at the same time

**Describe the solution you'd like**
The ability to select multiple contacts and send the same template for them

**Comment by tejaswinichile** [comment]
We don't have `send WhatsApp templates` to multiple contacts integrated with us.

But we can consider this as a new feature, we will pick it up in the next release.

**Comment by vagner-dias** [comment]
Great @tejaswinichile - Thank you for the attention !

**Comment by glauberssoutodossantos** [comment]
+1

**Comment by glauberssoutodossantos** [comment]
This resolve this feature-request here: https://github.com/chatwoot/chatwoot/issues/5361

**Comment by mayssam961** [comment]
+1

**Comment by luiszxcv** [comment]
1+

**Comment by ajaydivvela** [comment]
+1

**Comment by fejorca** [comment]
+1

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/4201
