### ISSUE TITLE
"Bots" section

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5854]
Hi all,

I know that this section is beta but is it normal that I have no content on this page?
![Bildschirm­foto 2022-11-15 um 09 22 45](https://user-images.githubusercontent.com/17011498/201868948-6b9f33ce-b3ae-4ba8-bd38-7d0603aed6ee.png)

I am using the self hosted docker version.

**Comment by iamsivin** [comment]
@Ghost108 We are working on it. You can disable it in the Super Admin console if needed.

**Comment by iamsivin** [comment]
Closing this issue since we are working on this.
