### ISSUE TITLE
[CW-2348] Ability to send the user identification on whatsapp messages

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#5855]
Is your enhancement request related to a problem? Please describe.
When a user has a signature defined, this signature (or the user display name) could be appended to the whatsapp text sent to the customer

Describe the solution you'd like
The "signature" button could be enabled on the text field to append the user signature when writing whatsapp messages

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/3741e8ff-7e7f-4821-9fe6-5cb045c5eaff/bbbdc909-ff46-45f3-adae-0f5f7636b3cd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8zNzQxZThmZi03ZTdmLTQ4MjEtOWZlNi01Y2IwNDVjNWVhZmYvYmJiZGM5MDktZmY0Ni00NWYzLWFkYWUtMGY1Zjc2MzZiM2NkIiwiaWF0IjoxNjkxMTY1NTg3LCJleHAiOjE2OTEyNTE5ODd9.aeUqNOTGfWZt92OHQMRvFvAqMoX4oRkNHcw8PhHvou4)

Example:
When the signature is set, like this example

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/46a65fcf-6f14-4682-9cb0-e4f83e782e20/b9973a9c-daa4-4d08-b30e-4385df103c04?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi80NmE2NWZjZi02ZjE0LTQ2ODItOWNiMC1lNGY4M2U3ODJlMjAvYjk5NzNhOWMtZGFhNC00ZDA4LWIzMGUtNDM4NWRmMTAzYzA0IiwiaWF0IjoxNjkxMTY1NTg3LCJleHAiOjE2OTEyNTE5ODd9.CWyIia5PHNyCwMylD56cr_dklJRUnD6ZixkAWTVNGio)

The "signature" button can be enabled when the user writes the message and the signature appended to the message:

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/56705e39-4c61-4336-8598-3094d391fdc4/c05cd9b2-9a51-43d5-83bb-6f5f44e09be1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi81NjcwNWUzOS00YzYxLTQzMzYtODU5OC0zMDk0ZDM5MWZkYzQvYzA1Y2Q5YjItOWE1MS00M2Q1LTgzYmItNmY1ZjQ0ZTA5YmUxIiwiaWF0IjoxNjkxMTY1NTg3LCJleHAiOjE2OTEyNTE5ODd9.bi2fQbbMNkAdJ38TybCS0kkGf0TmUr7YKweUuvTT4FA)

So that the customer would know the agent responsible for that specific message - very useful in conversations where multiple agents are talking simultaneously to the same customer

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/c178062e-e7ea-4d60-a2c3-172df94c3a02/c9ec2c95-8b34-48fe-8a31-33049f1cc36d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9jMTc4MDYyZS1lN2VhLTRkNjAtYTJjMy0xNzJkZjk0YzNhMDIvYzllYzJjOTUtOGIzNC00OGZlLThhMzEtMzMwNDlmMWNjMzZkIiwiaWF0IjoxNjkxMTY1NTg3LCJleHAiOjE2OTEyNTE5ODd9.UTxIof8mvmWoB8RjaS8hEpmJ3N2EQAX1xl17TPRhjdo)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2348](https://linear.app/chatwoot/issue/CW-2348/ability-to-send-the-user-identification-on-whatsapp-messages)</sub>

**Comment by glauberssoutodossantos** [comment]
+1

**Comment by sojan-official** [comment]
@vagner-dias Thanks for the feedback. We will have it in the pipeline for upcoming releases.

**Comment by glauberssoutodossantos** [comment]
Some days ago this feature was request in discord channel :) :) 


![image](https://user-images.githubusercontent.com/99494469/202260317-3c968b2d-23df-4ac8-9eff-9f87b87ad16f.png)

**Comment by WEBudoGT** [comment]
If it's not too much to ask, is it possible to include an option to make the "signature" on top of the message instead of at the bottom?
This way it looks cleaner (but it's just my opinion)
Thanks!

**Comment by vagner-dias** [comment]
> If it's not too much to ask, is it possible to include an option to make the "signature" on top of the message instead of at the bottom? This way it looks cleaner (but it's just my opinion) Thanks!

Makes sense. It is stetically cleaner

**Comment by rogeriorizzo** [comment]
this function already exists even pre-configured in the profile, when sending the message in the service, when you activate this signature, it fills in the fields with blank space, there must be something like shipped, missing some detail to recognize this field filled in there by the user

**Comment by vagner-dias** [comment]
> this function already exists even pre-configured in the profile, when sending the message in the service, when you activate this signature, it fills in the fields with blank space, there must be something like shipped, missing some detail to recognize this field filled in there by the user

I believe you are referring to what happens at the code level, but at the UI level what I see at the moment is that the signature button is replaced by the whatsapp template button. Maybe just a small tweak in the code can create this feature?

**Comment by glauberssoutodossantos** [comment]
@rogeriorizzo this feature exist but only works for email chaneel. For WhatsApp it does not works.

Exemple:
![image](https://user-images.githubusercontent.com/99494469/208687854-a60c3675-6d7c-40f3-a380-805311506cf4.png)

In WhatsApp:
![image](https://user-images.githubusercontent.com/99494469/208688072-0d830450-3ea5-4392-95ad-3ac13c868643.png)


What @vagner-dias want is, when agent say something, for costumer the message will be something like:

```
Agent name:

The message
```

Or

![image](https://user-images.githubusercontent.com/99494469/208688365-fa0404ff-3b07-4b73-9b41-b0a4f0904129.png)

**Comment by rogeriorizzo** [comment]
this type would be very interesting, because when it comes to several attendants, the person on the other side does not know who he is talking to. regardless of whether it is above, below, or in the line of the message, and this is also saved by default for all channels

**Comment by sojan-official** [comment]
One temporary workaround could be that once the https://github.com/chatwoot/chatwoot/pull/6077 is merged. you will be able to define canned responses with template variables.  

- Define a canned response : `whatsapp-reply`  with content "{{agent.name}}:  "
- Your support agents can then  select this canned response by typing in `/` and selecting this canned response before replying on whatsapp. Chatwoot will automatically fill in the agent name.

**Comment by TecCapital** [comment]
+1

**Comment by vagner-dias** [comment]
@sojan-official , considering the features already in place in chatwoot, would it be possible to create an automation rule to notify the customer every time the agent changes?

Something like: "Your case is now being dealt by" {{agent.name}}

**Comment by pauloricardotech** [comment]
is there any way to add the variable with the name of the agents by the code referring to the whatsapp cloud api channel?

**Comment by tiagocordeiro** [comment]
I am really looking forward to this feature. It will help a lot in chatwoot adoption.

**Comment by kvasconcelos** [comment]
Hello everyone,

Any updates on this feature?

**Comment by pedromvf** [comment]
Hello everyone,

Any updates on this feature?²²

**Comment by ldss95** [comment]
Any updates on this feature?

**Comment by vagner-dias** [comment]
It works!

Thank you team!

**Comment by WEBudoGT** [comment]
> It works!
> 
> Thank you team!

How does it work? I'm using latest version (3.2) and WhatsApp does not use signature or puts agent's name.
Am I missing something?

**Comment by vagner-dias** [comment]
> > It works!
> > Thank you team!
> 
> How does it work? I'm using latest version (3.2) and WhatsApp does not use signature or puts agent's name. Am I missing something?

Just create the signature in the profile section and enable it on the chat box

![image](https://github.com/chatwoot/chatwoot/assets/86367839/8b6d75dd-3704-4a01-b6aa-22cb9ec07204)

**Comment by WEBudoGT** [comment]
I don't have that button on my instance
[image: image.png]
