### ISSUE TITLE
Ability to add images to articles

### ISSUE THREAD

**Issue by gogobossStampolidis** [chatwoot/chatwoot#5868]
**Is your feature request related to a problem? Please describe.**
The ability to be able to add images to articles

**Describe the solution you'd like**
Add like a "upload image" button so we can add an image and below it more text if we want

**Describe alternatives you've considered**
Add options to add images boxes and then you add a url to the image and you can customize the size and the position

**Additional context**

**Comment by pranavrajs** [comment]
@gogobossStampolidis Thanks for the suggestion. We are already tracking this here. https://github.com/chatwoot/chatwoot/issues/5755
