### ISSUE TITLE
Option to skip the "Welcome" screen before the chat begins

### ISSUE THREAD

**Issue by baptisteArno** [chatwoot/chatwoot#5884]
I'd like to be able to directly display the chat instead of the Welcome screen. An option for this would be great!

I'm willing to contribute if someone tells me how to tackle this 😀

**Comment by fayazara** [comment]
@baptisteArno We currently do not have this feature. But We'd be happy to accept a pr if you're able to do it. To get started, you can try looking at widget sdk.js file `app/javascript/packs/sdk.js` and proceed to add a flag for this behaviour
