### ISSUE TITLE
Macros -> Send email to customer

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#5891]
**Is your enhancement request related to a problem? Please describe.**

Now that we have the macros, there are opportunities for improvement.

**Describe the solution you'd like**
I would like, when registering a macro, to have the option to send an email with the conversation directly to the registered consumer's email. This action is still manual.

![image](https://user-images.githubusercontent.com/99494469/202594225-1ae1f0f6-8b88-47dd-8695-1229025d0eef.png)

**Describe alternatives you've considered**

Keep it manual and put a private note reminding the agent to email the conversation to the customer.

**Additional context**
For customer service operations, for reasons of complicity and transparency, it is necessary to send the email to the customer with the entire history of the conversation.

**Comment by pranavrajs** [comment]
As the underlying action is the same we will track the progress over https://github.com/chatwoot/chatwoot/issues/5892
