### ISSUE TITLE
Macros -> Use dynamic variables in message

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#5893]
**Is your enhancement request related to a problem? Please describe.**

Macros is a very interesting feature that should save the agent a lot of time. To make it even better, it could have some basic treatments, such as automatically inserting the customer's name in messages as variables.

**Describe the solution you'd like**

**Describe alternatives you've considered**
For actions like sending a message, allow variables present in chatwoot to be included.

Very similar to what we have in this demand already mapped: https://github.com/chatwoot/chatwoot/pull/3729

requester_name
requester_email
requester_phone
requester_#{any external attribute name}

![image](https://user-images.githubusercontent.com/99494469/202597146-7c5adb30-2a1a-458c-9ffd-3e12be290077.png)

As in the example above, I would not need to manually type the username, as it is already registered in the system.

**Comment by muhsin-k** [comment]
@glauberssoutodossantos We are working on it. You can track the progress here https://github.com/chatwoot/chatwoot/issues/5894
