### ISSUE TITLE
feat: Pass current agent context to Dashboard apps

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#5898]
ref: https://discord.com/channels/647412545203994635/1039643762856570881

> Hi guys, how are you?

> 
> Could anyone help me?
> 
> I'm developing an embedded application using Chatwoot's "Dashboard Apps". When sharing an inbox with a certain agent, is it possible to capture that agent's email by the window event? Chatwoot user email.

---

We are developing our CRM embedded in Chatwwot, and if we had this user context, it would make the query in our CRM a lot easier.
Could you evaluate this implementation from the user's context? Would there be a deadline to implement?

It would help us a lot, @sojan.

Our customers are loving Chatwoot and this addition would be a great upgrade for our customers/agents using Chatwoot.

---
Hi @sojan ! Wow, of course!

We are using the WhatsApp channel (Cloud API WhatsApp) to communicate with the customer, and with the context of the contact's phone number, performing a query in our CRM. Returning all customer information and details from our CRM to Chatwoot and enriching the lead and conversation. Helping the agent resolve queries much more efficiently without having to query multiple URLs in different tabs.

Below is a short video of our CRM application embedded in Chattwoot:

https://www.loom.com/share/48c0e123b9a44ddd97307a13989cfce0

The need to get the agent context (email) would be essential to validate the Chattwoot agent in our CRM. With this, we will be able to scale the application and reach more agents. Today in our application only one agent is allowed to use our incorporated application.

Our biggest difficulty today is that Chatwoot does not provide the agent's context. Our customers are loving Chattwoot and this addition would be a huge upgrade for our customers/agents who use Chattwoot and our CRM.
Would it be possible to implement it, @sojan Jose?

**Comment by jhonyrdesouza** [comment]
Wow! Thank you so much, @sojan-official! I will be following the issue. This feature will help us a lot!

**Comment by pranavrajs** [comment]
@nithindavid Any reason why this was reopened?

**Comment by nithindavid** [comment]
Might have been an accident.
