### ISSUE TITLE
Rest api avatar not working

### ISSUE THREAD

**Issue by josep112** [chatwoot/chatwoot#5908]
**Describe the bug**

I'm trying to create a contact with rest api and put an avatar by url, the contact is created but the avatar doesn't appear

**To Reproduce**

curl --location --request POST 'http://localhost:3000/api/v1/accounts/1/contacts' \
--header 'api_access_token: exxxxhRsisWh6mVd33wvkk' \
--header 'Content-Type: application/json' \
--data-raw '{
"inbox_id": 1,
"name": "Jose",
"phone_number": "+5511900000000",
"avatar_url": "https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png"
}'

**Screenshots**

<img width="1512" alt="Captura de Tela 2022-11-21 às 16 42 34" src="https://user-images.githubusercontent.com/12038013/203144643-f1ddd1a2-5854-4265-974d-9c025b91e60b.png">

**Server logs**

Share the server logs to debug the issue further.
{
    "payload": {
        "contact": {
            "additional_attributes": {},
            "availability_status": "offline",
            "email": null,
            "id": 17,
            "name": "Jose",
            "phone_number": "+5511900000000",
            "identifier": null,
            "thumbnail": "",
            "custom_attributes": {},
            "contact_inboxes": [
                {
                    "source_id": "bb738668-6ed2-473f-a077-be8b5e26932f",
                    "inbox": {
                        "id": 1,
                        "avatar_url": "",
                        "channel_id": 1,
                        "name": "WhatsApp1",
                        "channel_type": "Channel::Api",
                        "greeting_enabled": false,
                        "greeting_message": null,
                        "working_hours_enabled": false,
                        "enable_email_collect": true,
                        "csat_survey_enabled": false,
                        "enable_auto_assignment": true,
                        "auto_assignment_config": {},
                        "out_of_office_message": null,
                        "working_hours": [
                            {
                                "day_of_week": 0,
                                "closed_all_day": true,
                                "open_hour": null,
                                "open_minutes": null,
                                "close_hour": null,
                                "close_minutes": null,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 1,
                                "closed_all_day": false,
                                "open_hour": 9,
                                "open_minutes": 0,
                                "close_hour": 17,
                                "close_minutes": 0,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 2,
                                "closed_all_day": false,
                                "open_hour": 9,
                                "open_minutes": 0,
                                "close_hour": 17,
                                "close_minutes": 0,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 3,
                                "closed_all_day": false,
                                "open_hour": 9,
                                "open_minutes": 0,
                                "close_hour": 17,
                                "close_minutes": 0,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 4,
                                "closed_all_day": false,
                                "open_hour": 9,
                                "open_minutes": 0,
                                "close_hour": 17,
                                "close_minutes": 0,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 5,
                                "closed_all_day": false,
                                "open_hour": 9,
                                "open_minutes": 0,
                                "close_hour": 17,
                                "close_minutes": 0,
                                "open_all_day": false
                            },
                            {
                                "day_of_week": 6,
                                "closed_all_day": true,
                                "open_hour": null,
                                "open_minutes": null,
                                "close_hour": null,
                                "close_minutes": null,
                                "open_all_day": false
                            }
                        ],
                        "timezone": "UTC",
                        "callback_webhook_url": null,
                        "allow_messages_after_resolved": true,
                        "widget_color": null,
                        "website_url": null,
                        "hmac_mandatory": false,
                        "welcome_title": null,
                        "welcome_tagline": null,
                        "web_widget_script": null,
                        "website_token": null,
                        "selected_feature_flags": null,
                        "reply_time": null,
                        "messaging_service_sid": null,
                        "phone_number": null,
                        "hmac_token": "5N7YyJKDhSxUkpQApGfKj7Lj",
                        "webhook_url": "http://localhost:3001/tx.php",
                        "inbox_identifier": "5Eft1YDnT6f3W8ecH87tGSEe",
                        "additional_attributes": {}
                    }
                }
            ]
        },
        "contact_inbox": {
            "inbox": {
                "id": 1,
                "channel_id": 1,
                "account_id": 1,
                "name": "WhatsApp1",
                "created_at": "2022-11-21T16:22:21.939Z",
                "updated_at": "2022-11-21T16:22:21.939Z",
                "channel_type": "Channel::Api",
                "enable_auto_assignment": true,
                "greeting_enabled": false,
                "greeting_message": null,
                "email_address": null,
                "working_hours_enabled": false,
                "out_of_office_message": null,
                "timezone": "UTC",
                "enable_email_collect": true,
                "csat_survey_enabled": false,
                "allow_messages_after_resolved": true,
                "auto_assignment_config": {}
            },
            "source_id": "bb738668-6ed2-473f-a077-be8b5e26932f"
        }
    }
}

**Comment by josep112** [comment]
I saw that this avatar problem was solved as shown here -> https://github.com/chatwoot/chatwoot/commit/827f977a37b7d1caa813846cc53db6bd0576a60c , it is possible to change it via the web but via the api I can't create the contact or update it, I don't get an error either in the cwctl --logs web log, I tried updating with the api:
curl --location --request PATCH 'http://localhost:3000/api/v1/accounts/1/contacts/34' \
--header 'api_access_token: eaGApinhRsisWh6mVd33wvkk' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Jose",
    "phone_number": "+5511900000000",
    "avatar_url": "http://192.168.50.50/imagem.png"
}'

cwctl --logs

Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.672635 #9816]  INFO -- : source=rack-timeout id=6cd30a9a-9bde-45e4-82a1-e795510a75e1 timeout=15000ms state=ready
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.673459 #9816] DEBUG -- : source=rack-timeout id=6cd30a9a-9bde-45e4-82a1-e795510a75e1 timeout=15000ms service=1ms state=active
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.674072 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] Started PATCH "/api/v1/accounts/1/contacts/34" for 192.168.40.70 at 2022-11-24 08:35:00 -0600
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.676096 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] Processing by Api::V1::Accounts::ContactsController#update as JSON
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.676378 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Parameters: {"name"=>"Jose", "phone_number"=>"+5511900000000", "avatar_url"=>"http://192.168.50.50/imagem.png", "account_id"=>"1", "id"=>"34", "contact"=>{"name"=>"Jose", "phone_number"=>"+5511900000000"}}
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.679145 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   AccessToken Load (0.6ms)  SELECT "access_tokens".* FROM "access_tokens" WHERE "access_tokens"."token" = $1 LIMIT $2  [["token", "eaGApinhRsisWh6mVd33wvkk"], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.681068 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.682548 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Account Load (0.3ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.684313 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   InstallationConfig Load (0.5ms)  SELECT "installation_configs".* FROM "installation_configs" WHERE "installation_configs"."name" = $1 ORDER BY "installation_configs"."created_at" DESC LIMIT $2  [["name", "ACCOUNT_LEVEL_FEATURE_DEFAULTS"], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.687741 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   AccountUser Load (0.4ms)  SELECT "account_users".* FROM "account_users" WHERE "account_users"."account_id" = $1 AND "account_users"."user_id" = $2 LIMIT $3  [["account_id", 1], ["user_id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.690479 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Contact Load (0.4ms)  SELECT "contacts".* FROM "contacts" WHERE "contacts"."account_id" = $1 AND "contacts"."id" = $2 LIMIT $3  [["account_id", 1], ["id", 34], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.692689 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   ContactInbox Load (0.7ms)  SELECT "contact_inboxes".* FROM "contact_inboxes" WHERE "contact_inboxes"."contact_id" = $1  [["contact_id", 34]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.694678 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Inbox Load (0.5ms)  SELECT "inboxes".* FROM "inboxes" WHERE "inboxes"."id" = $1  [["id", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.697264 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   TRANSACTION (0.2ms)  BEGIN
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.698298 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   ActiveStorage::Attachment Load (0.4ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 34], ["record_type", "Contact"], ["name", "avatar"], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.700247 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Contact Exists? (0.5ms)  SELECT 1 AS one FROM "contacts" WHERE "contacts"."phone_number" = $1 AND "contacts"."id" != $2 AND "contacts"."account_id" = $3 LIMIT $4  [["phone_number", "+5511900000000"], ["id", 34], ["account_id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.703978 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   ActsAsTaggableOn::Tagging Load (0.9ms)  SELECT "taggings".* FROM "taggings" WHERE "taggings"."taggable_id" = $1 AND "taggings"."taggable_type" = $2  [["taggable_id", 34], ["taggable_type", "Contact"]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.704892 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   TRANSACTION (0.2ms)  COMMIT
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.707375 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]    (0.5ms)  SELECT "users"."pubsub_token" FROM "users" INNER JOIN "account_users" ON "users"."id" = "account_users"."user_id" WHERE "account_users"."account_id" = $1 AND "account_users"."role" = $2  [["account_id", 1], ["role", 0]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.709035 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]    (0.5ms)  SELECT "users"."pubsub_token" FROM "users" INNER JOIN "account_users" ON "users"."id" = "account_users"."user_id" WHERE "account_users"."account_id" = $1 AND "account_users"."role" = $2  [["account_id", 1], ["role", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.711051 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   ActiveStorage::Attachment Load (0.4ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "User"], ["name", "avatar"], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.712761 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   AccountUser Load (0.3ms)  SELECT "account_users".* FROM "account_users" WHERE "account_users"."user_id" = $1  [["user_id", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.715264 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: d2c5ed16-a5d4-4a44-9bbc-9ccd9171b121) to Sidekiq(default) with arguments: ["c8ZKtwJ5soiUudv1TdxYniuS", "dRgDZeeGfdTnnmuQ68tHnrMW"], "contact.updated", {:additional_attributes=>{"description"=>"", "company_name"=>"", "social_profiles"=>{"github"=>"", "twitter"=>"", "facebook"=>"", "linkedin"=>""}}, :custom_attributes=>{}, :email=>nil, :id=>34, :identifier=>nil, :name=>"Jose", :phone_number=>"+5511900000000", :thumbnail=>"", :type=>"contact", :account_id=>1, :performer=>{:id=>1, :name=>"Chatbots", :available_name=>"Chatbots", :avatar_url=>"", :type=>"user", :availability_status=>"online", :thumbnail=>""}}
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.716769 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] [ActiveJob] Enqueued EventDispatcherJob (Job ID: aa4f9d60-f08e-4e25-b109-fb9cd58af8bb) to Sidekiq(events) with arguments: "contact.updated", Thu, 24 Nov 2022 14:35:00.705214317 UTC +00:00, {:contact=>#<GlobalID:0x00007f8c4c39d980 @uri=#<URI::GID gid://chatwoot/Contact/34>>}
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.718283 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] [ActiveJob] Enqueued Avatar::AvatarFromUrlJob (Job ID: 9329a7c3-de0d-4ca7-8ce9-2d517d1e5081) to Sidekiq(default) with arguments: #<GlobalID:0x00007f8c4c30b990 @uri=#<URI::GID gid://chatwoot/Contact/34>>, "http://192.168.50.50/imagem.png"
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.719371 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Rendering api/v1/accounts/contacts/update.json.jbuilder
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.722487 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   ActiveStorage::Attachment Load (0.5ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Inbox"], ["name", "avatar"], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.724846 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   WorkingHour Load (0.6ms)  SELECT "working_hours"."day_of_week", "working_hours"."closed_all_day", "working_hours"."open_hour", "working_hours"."open_minutes", "working_hours"."close_hour", "working_hours"."close_minutes", "working_hours"."open_all_day" FROM "working_hours" WHERE "working_hours"."inbox_id" = $1 ORDER BY "working_hours"."day_of_week" ASC  [["inbox_id", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.727602 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Channel::Api Load (0.5ms)  SELECT "channel_api".* FROM "channel_api" WHERE "channel_api"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.728551 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Rendered api/v1/models/_inbox.json.jbuilder (Duration: 8.0ms | Allocations: 1501)
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.728819 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Rendered api/v1/models/_contact_inbox.json.jbuilder (Duration: 8.4ms | Allocations: 1591)
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.729093 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Rendered api/v1/models/_contact.json.jbuilder (Duration: 9.3ms | Allocations: 1805)
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.729940 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   Rendered api/v1/accounts/contacts/update.json.jbuilder (Duration: 10.3ms | Allocations: 2522)
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:00.731771 #9816] DEBUG -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1]   SuperAdmin Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."type" = $1 AND "users"."id" = $2 LIMIT $3  [["type", "SuperAdmin"], ["id", 1], ["LIMIT", 1]]
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.732840 #9816]  INFO -- : [6cd30a9a-9bde-45e4-82a1-e795510a75e1] Completed 200 OK in 56ms (Views: 10.0ms | ActiveRecord: 9.7ms | Allocations: 11521)
Nov 24 08:35:00 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:00.733327 #9816]  INFO -- : source=rack-timeout id=6cd30a9a-9bde-45e4-82a1-e795510a75e1 timeout=15000ms service=61ms state=completed
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.452572 #9816]  INFO -- : source=rack-timeout id=ec8d0b0c-9289-4743-bf64-8b311713e5bb timeout=15000ms state=ready
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.452731 #9816] DEBUG -- : source=rack-timeout id=ec8d0b0c-9289-4743-bf64-8b311713e5bb timeout=15000ms service=0ms state=active
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.453478 #9816]  INFO -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb] Started GET "/api/v1/accounts/1/contacts/34/contactable_inboxes" for 172.16.10.21 at 2022-11-24 08:35:01 -0600
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.455267 #9816]  INFO -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb] Processing by Api::V1::Accounts::ContactsController#contactable_inboxes as JSON
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.455532 #9816]  INFO -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Parameters: {"account_id"=>"1", "id"=>"34"}
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.457902 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."uid" = $1 LIMIT $2  [["uid", "chatbots@chatbots.net.br"], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.459851 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Account Load (0.3ms)  SELECT "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.461604 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   InstallationConfig Load (0.4ms)  SELECT "installation_configs".* FROM "installation_configs" WHERE "installation_configs"."name" = $1 ORDER BY "installation_configs"."created_at" DESC LIMIT $2  [["name", "ACCOUNT_LEVEL_FEATURE_DEFAULTS"], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.467537 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   AccountUser Load (3.1ms)  SELECT "account_users".* FROM "account_users" WHERE "account_users"."account_id" = $1 AND "account_users"."user_id" = $2 LIMIT $3  [["account_id", 1], ["user_id", 1], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.470170 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Contact Load (0.5ms)  SELECT "contacts".* FROM "contacts" WHERE "contacts"."account_id" = $1 AND "contacts"."id" = $2 LIMIT $3  [["account_id", 1], ["id", 34], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.471732 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   ContactInbox Load (0.4ms)  SELECT "contact_inboxes".* FROM "contact_inboxes" WHERE "contact_inboxes"."contact_id" = $1  [["contact_id", 34]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.473113 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Inbox Load (0.3ms)  SELECT "inboxes".* FROM "inboxes" WHERE "inboxes"."id" = $1  [["id", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.475426 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Inbox Load (0.3ms)  SELECT "inboxes".* FROM "inboxes" WHERE "inboxes"."account_id" = $1  [["account_id", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.478749 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   ContactInbox Load (0.4ms)  SELECT "contact_inboxes".* FROM "contact_inboxes" WHERE "contact_inboxes"."inbox_id" = $1 AND "contact_inboxes"."contact_id" = $2 ORDER BY "contact_inboxes"."id" DESC LIMIT $3  [["inbox_id", 1], ["contact_id", 34], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.480824 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   AccountUser Load (0.6ms)  SELECT "account_users".* FROM "account_users" WHERE "account_users"."user_id" = $1  [["user_id", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.482723 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Rendering api/v1/accounts/contacts/contactable_inboxes.json.jbuilder
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.485570 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   ActiveStorage::Attachment Load (0.5ms)  SELECT "active_storage_attachments".* FROM "active_storage_attachments" WHERE "active_storage_attachments"."record_id" = $1 AND "active_storage_attachments"."record_type" = $2 AND "active_storage_attachments"."name" = $3 LIMIT $4  [["record_id", 1], ["record_type", "Inbox"], ["name", "avatar"], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.487996 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   WorkingHour Load (0.5ms)  SELECT "working_hours"."day_of_week", "working_hours"."closed_all_day", "working_hours"."open_hour", "working_hours"."open_minutes", "working_hours"."close_hour", "working_hours"."close_minutes", "working_hours"."open_all_day" FROM "working_hours" WHERE "working_hours"."inbox_id" = $1 ORDER BY "working_hours"."day_of_week" ASC  [["inbox_id", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.490433 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Channel::Api Load (0.5ms)  SELECT "channel_api".* FROM "channel_api" WHERE "channel_api"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.491373 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Rendered api/v1/models/_inbox.json.jbuilder (Duration: 7.7ms | Allocations: 1480)
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.492151 #9816]  INFO -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   Rendered api/v1/accounts/contacts/contactable_inboxes.json.jbuilder (Duration: 9.1ms | Allocations: 2167)
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: D, [2022-11-24T08:35:01.494238 #9816] DEBUG -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb]   SuperAdmin Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."type" = $1 AND "users"."id" = $2 LIMIT $3  [["type", "SuperAdmin"], ["id", 1], ["LIMIT", 1]]
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.495167 #9816]  INFO -- : [ec8d0b0c-9289-4743-bf64-8b311713e5bb] Completed 200 OK in 39ms (Views: 9.1ms | ActiveRecord: 8.7ms | Allocations: 7754)
Nov 24 08:35:01 baileys chatwoot-web.1[9816]: I, [2022-11-24T08:35:01.496267 #9816]  INFO -- : source=rack-timeout id=ec8d0b0c-9289-4743-bf64-8b311713e5bb timeout=15000ms service=44ms state=completed



I checked that when I send it through the web it is being saved in /chatwoot/storage, but when I send it through the api it is not being saved there

**Comment by sojan-official** [comment]
https://user-images.githubusercontent.com/73185/203954093-6efdb4ef-fcaa-4216-8468-2ba754a136a7.mov

@josep112  when specifying avatar URLs, the processing happens in a background job. So the avatar URL will only be available for the contact in a subsequent get request.
