### ISSUE TITLE
Chat Widget shows "we are away"

### ISSUE THREAD

**Issue by panaras10** [chatwoot/chatwoot#5918]
Chat widget shows "We are away" even though I have 3 agents logged in right now. We haven't set up business hours as we work 24/7 and there's no option for it (?!)

Can you please fix it? 
<img width="796" alt="Screenshot 2022-11-22 at 16 35 44" src="https://user-images.githubusercontent.com/56270780/203341554-dcd8dfa2-708e-45e2-948b-b15fc36d8feb.png">
<img width="462" alt="Screenshot 2022-11-22 at 16 35 07" src="https://user-images.githubusercontent.com/56270780/203341562-5c456508-a399-4f1e-a390-06c6ad00b9e9.png">

**Comment by vishnu-narayanan** [comment]
Could you check if you have business hours enabled for your inbox? If yes, please disable it to be always shown online.

![image](https://user-images.githubusercontent.com/3526167/203343445-af866a8d-4281-4c9b-bcfa-6b2340cabb84.png)

**Comment by panaras10** [comment]
As I said on my initial message, we have **NOT** enabled business hours.

<img width="2054" alt="Screenshot 2022-11-22 at 16 49 16" src="https://user-images.githubusercontent.com/56270780/203344571-21af856a-1af4-4f10-b3c1-f8706dc71864.png">

**Comment by pranavrajs** [comment]
@panaras10 Have you added any of the online users as collaborators in the inbox?

**Comment by panaras10** [comment]
Yes, all of them. I think it has something to do with redis as if I manually do a flushall, it fixes itself.

**Comment by pranavrajs** [comment]
@iamsivin Can you please test this behavior on our staging and see if you can reproduce it?

**Comment by iamsivin** [comment]
@pranavrajs I tested it in staging not able to find it.
https://www.loom.com/share/e859af15cc544c6c8ab6219d58a0f698

**Comment by iamsivin** [comment]
@panaras10 Closing this issue as we added a new feature called Mark offline automatically. In this case, you need to toggle off the settings, which helps to solve this issue if you are facing this issue still.

You can see it here -
<img width="255" alt="image" src="https://user-images.githubusercontent.com/64252451/215809616-4c1b310c-cd69-4ce2-ac9e-9e28c053fab9.png">
