### ISSUE TITLE
Latvian language not present in Site language list

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#5919]
**Describe the bug**

Latvian language does not appear in Chatwoot v2.11.0 Site language list, despite the fact that the translation is fully complete. 

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Site language (Beta)' language list.
3. Latvian language will not be present in the list.

**Expected behavior**

Site language list should contain Latvian language.

**Screenshots**

<img width="960" alt="AvailableLanguages" src="https://user-images.githubusercontent.com/118850916/203409579-70559a39-4b95-44e3-b218-35b1048b2b45.png">

**Environment**

Self-hosted installation of Chatwoot Linux VM

**Comment by pranavrajs** [comment]
@Diplomat-LV Thanks for creating the issue, this will be fixed via #5920
