### ISSUE TITLE
Help Center root domain redirection & Footer Tip (cloudron)

### ISSUE THREAD

**Issue by akzeronet** [chatwoot/chatwoot#5923]
> This was [reported](https://forum.cloudron.io/topic/8058/alias-web-domain-for-chatwoot) on the Cloudron package. I can confirm that once we added alias support in the chatwoot package, it just works. i.e chatwoot itself works fine without any changes.

It's great, just one thing, I was trying with the web domain alias... but the second domain by default redirects to docs.chatdron.com/**app/login** (like the first one), instead of docs.chatdron.net/hc/* ( Help Center)

...
Also, since cloudron is a read-only system in the part of the source code, it would be nice if we could use our corporate identity in the footer of the help center without detracting from chatwoot, it's only for branding reasons... you can something like that:

If (BrandName != '') {
BrandName (BrandURL)
} else { 
Made with [Chatwoot](https://www.chatwoot.com/) 💙
}

_Originally posted by @akzeronet in https://github.com/chatwoot/chatwoot/issues/5799#issuecomment-1324432364_

**Comment by fayazara** [comment]
CC: @vishnu-narayanan could you please help on this.

**Comment by vishnu-narayanan** [comment]
@akzeronet This seems like a Cloudron specific request. Could you please post it on the Cloudron forum?
