### ISSUE TITLE
Agent bot has no access to account

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5926]
Hi!

Maybe it is my mistake OR I found a bug.

1. super admin login
2. create an agent bot
![Bildschirm­foto 2022-11-24 um 07 47 19](https://user-images.githubusercontent.com/17011498/203713201-f045f4cb-7513-413a-af0c-fd88317509ed.png)

Now I have two access tokens. My user token and the new bot token:

![Bildschirm­foto 2022-11-24 um 07 47 14](https://user-images.githubusercontent.com/17011498/203713208-960a1361-7be8-4f37-bb15-0fac48a0b298.png)

Now I would like to send (as my created bot) a message via chatwoot api to a conversation, which was started by the web widget.

Response:
`[error] => You are not authorized to access this account`

I checked the table "access_tokens" in the database, which looks like this:

![Bildschirm­foto 2022-11-24 um 07 48 39](https://user-images.githubusercontent.com/17011498/203713438-4788381d-ba97-4876-a705-e4805d0ce2d5.png)

As you can see, the agent bot has a owner id, which doesnt exist.
My User has ID 1 and not 2.
I set owner ID to 1 manually:

![Bildschirm­foto 2022-11-24 um 07 50 43](https://user-images.githubusercontent.com/17011498/203713718-f5efe669-8042-45f7-929b-6a47f8c85554.png)

And NOW my bot can send messages via API.
Response:

```
    [id] => 15
    [content] => Hello World
    [inbox_id] => 1
    [conversation_id] => 2
    [message_type] => 1
    [content_type] => text
    [content_attributes] => Array
        (
        )
    [created_at] => 1669272670
    [private] => 
    [source_id] => 
```

I am using the self hosted docker version v2.11.0

**Comment by pranavrajs** [comment]
@Ghost108 You need to add the bot to an inbox to get access. Please use this API. https://www.chatwoot.com/developers/api#tag/Inboxes/operation/updateAgentBot

**Comment by Ghost108** [comment]
sorry but here is still something unclear to me. I create a bot via GUI, but then I have to assign it via API, because there is no GUI for this?

If so, I am still confused:

I created a new agent bot via the super_admin interface. Here you can see it with the ID 6.
![Bildschirm­foto 2022-11-25 um 07 19 56](https://user-images.githubusercontent.com/17011498/203914807-49604e8c-40aa-4631-a9d7-61ac0129e166.png)


At the same time a new entry was automatically created under Access Tokens, with the ID 7.
![Bildschirm­foto 2022-11-25 um 07 20 03](https://user-images.githubusercontent.com/17011498/203914818-93871c49-5a3a-4939-900e-af963d9fa54c.png)

Now I should assign the bot via API - as you said.

But the api url https://mydomain.de/api/v1/accounts/1/inboxes/1/set_agent_bot
does not exist:
![Bildschirm­foto 2022-11-25 um 07 35 19](https://user-images.githubusercontent.com/17011498/203915928-a71ffc55-4084-435e-ad13-4f62d6a3722f.png)
