### ISSUE TITLE
optical issue - interactive message "cards"

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5936]
Hi!

I am using this interactive message:
https://www.chatwoot.com/docs/product/others/interactive-messages#3-cards

If you send this type of interactive message without the paramter "media_url" the border / frame of the image is still displayed:

<img width="258" alt="Bildschirm­foto 2022-11-24 um 20 34 15" src="https://user-images.githubusercontent.com/17011498/203854978-4e1c248b-638d-4514-94fe-f936b8d259fa.png">

**Comment by Ghost108** [comment]
I would be happy to receive a response

**Comment by Ghost108** [comment]
okay :)

**Comment by fayazara** [comment]
Closing this for now
