### ISSUE TITLE
Feature: Support card options in widget and dashboard

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#594]
Render messages with a link with a message and description as a card.

<img width="540" alt="Screenshot 2020-03-04 at 10 13 35 AM" src="https://user-images.githubusercontent.com/2246121/75845988-d254b880-5e00-11ea-8e92-7539babc991b.png">

**Comment by tds-1** [comment]
{
   "content_type":"cards",
   "content_attributes":{
      "items":[
         {
            "media_url":"https://assets.ajio.com/medias/sys_master/root/hdb/h9a/13582024212510/-1117Wx1400H-460345219-white-MODEL.jpg",
            "title":"Nike Shoes 2.0",
            "description":"Running with Nike Shoe 2.0",
            "actions":[
               {
                  "type":"link",
                  "text":"View More",
                  "uri":"google.com"
               },
               {
                  "type":"postback",
                  "text":"Add to cart",
                  "payload":"ITEM_SELECTED"
               }
            ]
         }
      ]
   },
   "private":false
}
I am sending the above data to https://app.chatwoot.com/api/v1/accounts/'+account_id+'/conversations/'+conv_id+'/messages'
I can not see any card type message in chatwoot.
