### ISSUE TITLE
Bot get no avatar

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5948]
Hi all, 

I am using the self hosted docker version 2.11.0
I set this ENV to true
![Bildschirm­foto 2022-11-25 um 11 49 50](https://user-images.githubusercontent.com/17011498/203967457-f42a9306-e012-4c1c-9f14-b9e5772f7780.png)

But my Bot doesnt show the correct avatar (green circle with speech bubbles)
![Bildschirm­foto 2022-11-25 um 11 28 28](https://user-images.githubusercontent.com/17011498/203967634-a2ea564b-270b-401e-a9b1-c4c171801d8b.png)

**Comment by Ghost108** [comment]
@pranavrajs 
I would be happy to receive a response

**Comment by vishnu-narayanan** [comment]
@Ghost108 Could you please follow the issue templates when creating the issue? Please include steps to reproduce this issue.

**Comment by Ghost108** [comment]
Okay for the next time. But I guess my explaniation is clear?
If you have any question, please contact me :)

**Comment by Ghost108** [comment]
More Information:

1. Created a Bot: https://www.chatwoot.com/developers/api#tag/Account-AgentBots/operation/create-an-account-agent-bot
2. Then I assigend the bot to my inbox: https://www.chatwoot.com/developers/api#tag/Inboxes/operation/updateAgentBot
3. I added the env USE_INBOX_AVATAR_FOR_BOT = TRUE

Result: NO AVATAR

**Comment by Ghost108** [comment]
REMINDER!

**Comment by Ghost108** [comment]
@pranavrajs
no support since 7 days :(

**Comment by Ghost108** [comment]
Update: Not solved in v2.12.0
@pranavrajs

**Comment by pranavrajs** [comment]
@Ghost108 Agent bot doesn't have the field for an avatar. We will consider it in future releases.

**Comment by Ghost108** [comment]
@pranavrajs and for what is the env USE_INBOX_AVATAR_FOR_BOT ?

**Comment by sojan-official** [comment]
closing in favor : https://github.com/chatwoot/chatwoot/issues/7129
