### ISSUE TITLE
Heroku build failed when change Chatwoot to Chatbot text

### ISSUE THREAD

**Issue by chatquick** [chatwoot/chatwoot#5951]
**Describe the bug**

**To Reproduce**

1. find ./ -type f -readable -writable -exec sed -i "s/Chatwoot/Chatbot/g" {} \;
2. https://heroku.com/deploy?template=https://github.com/chatbot/chatbot/tree/master
4. See the error
`-----> Detecting rake tasks

-----> Preparing app for Rails asset pipeline

       Running: rake assets:precompile

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : No configuration file loaded, and no configuration found in ENV. For assistance configuring Scout, visit https://docs.scoutapm.com/#ruby-configuration-options

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : Scout Agent [5.2.0] Initialized

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : Not Loading Instruments

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : Scout Agent [5.2.0] Installed

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : Monitoring isn't enabled for the [production] environment.

       [Scout] [11/25/22 17:33:23 +0000 run.2348 (2536)] INFO : Deferring agent start. Standing by for first request

       rake aborted!

       NameError: uninitialized constant ChatbotApp

       /tmp/build_e7d6c2c7/config/routes.rb:231:in `block in <main>'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:409:in `draw'

       /tmp/build_e7d6c2c7/config/routes.rb:1:in `<main>'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:39:in `load'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `each'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:47:in `load_paths'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:21:in `reload!'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:35:in `block in updater'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/file_update_checker.rb:83:in `execute'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/routes_reloader.rb:10:in `execute'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'

       /tmp/build_e7d6c2c7/config/environment.rb:5:in `<main>'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/elastic-apm-4.5.1/lib/elastic_apm/spies.rb:111:in `require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:367:in `require_environment!'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:61:in `block (2 levels) in define'

       /tmp/build_e7d6c2c7/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'

       Tasks: TOP => environment

       (See full trace by running task with --trace)

 !

 !     Precompiling assets failed.

 !

 !     Push rejected, failed to compile Ruby app.

 !     Push failed`
**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

![Screenshot 2022-11-26 at 00-41-02 Create New App Heroku](https://user-images.githubusercontent.com/119020384/204034705-4481f447-0ee7-446e-acb6-7f76973330d1.png)

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ X] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - Browser [e.g. stock browser, firefox, safari]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

**Comment by pranavrajs** [comment]
@chatquick It is hard for us to debug the issues when there is a change in the code. We can't support it. If any of the Chatwoot branches (develop or master) in its original form, please let us know.
