### ISSUE TITLE
Failed to open TCP connection to graph.facebook.com:443 (getaddrinfo: Try again)

### ISSUE THREAD

**Issue by juanbits** [chatwoot/chatwoot#5953]
Hi, i deployed chatwoot via docker

when i try to add a new Facebook Messenger inbox
- Ok. click on the button to login
- Ok. Login via facebook and finish the popup wizard
- Error. On auto-close the popup wizard, the main screen only shows "Authenticating you with Facebook..."
![image](https://user-images.githubusercontent.com/5168033/204065378-2f19f837-4e81-4b8b-b615-03853d6d1cd3.png)

- 
- i got the next error via the container rails logs: Failed to open TCP connection to graph.facebook.com:443 (getaddrinfo: Try again)
![image](https://user-images.githubusercontent.com/5168033/204065343-7df1f1a1-0877-44f8-86f1-8b0d081baf37.png)

how can i fix that?

thanks in advance by your help!

**Comment by iammattmartin** [comment]
Do you have an adblocker enabled?

**Comment by juanbits** [comment]
@iammattmartin at the web browser? no

**Comment by fayazara** [comment]
CC: @tejaswinichile can you please help here?

**Comment by sojan-official** [comment]
ref: https://stackoverflow.com/questions/37144544/failed-to-open-tcp-connection
