### ISSUE TITLE
messages api - send message template or add message tag for whatsapp messages

### ISSUE THREAD

**Issue by wiliammbr** [chatwoot/chatwoot#5958]
I would like to send updates to my customers via Power Automate using WhatsApp Message Templates or Message tags (https://developers.facebook.com/docs/messenger-platform/reference/send-api).

Allow the Messages API endpoint for creating messages to allow passing tags or whatsapp templates with variables.

**Comment by grupale** [comment]
+1

**Comment by ASchneiderBR** [comment]
I would also like that! Thanks.

**Comment by nithindavid** [comment]
@wiliammbr Can you bit more context for the end product? Are you expecting this to be as an improvement on the existing API?

**Comment by wiliammbr** [comment]
Hey @nithindavid ,

Yes, this is an improvement for the existing Messages API.
Basically, I wanted to send regular updates over user progress in a selection process via WhatsApp. But if I can't send approved WhatsApp templates, the user won't receive the messages since it falls in the 24 hour rule from Facebook. Also, I can try using Tags from the WhatsApp API, but I'm unable to pass those tags via the Chatwoot API.

**Comment by wiliammbr** [comment]
Updating to not lose track.

**Comment by munawar050** [comment]
+1
Currently there is no way to send whatsapp template messages through chatwoot API.
Would appreciate this improvement or feature

**Comment by nithindavid** [comment]
@sojan-official @tejaswinichile Can you share your thoughts on this?

**Comment by munawar050** [comment]
Hey @wiliammbr,

If I understand you correctly you want to send template messages via API Send Message.
If this is the case you can send the following in the body of API Send Message, and it will just work fine.

I use it without any issue, hope this helps.

`"content": "WRITE YOUR CONTENT HERE",
                    "template_params": {
                        "name": "template name",
                        "category": "TRANSACTIONAL",
                        "language": "en_US",
                        "processed_params": {
                            "1": "write your field value here",
                            "2": "Write your field value here"
                        }
                    }`

**Comment by wiliammbr** [comment]
> Hey @wiliammbr,
> 
> If I understand you correctly you want to send template messages via API Send Message. If this is the case you can send the following in the body of API Send Message, and it will just work fine.
> 
> I use it without any issue, hope this helps.
> 
> `"content": "WRITE YOUR CONTENT HERE", "template_params": { "name": "template name", "category": "TRANSACTIONAL", "language": "en_US", "processed_params": { "1": "write your field value here", "2": "Write your field value here" } }`

Hey @munawar050 , appreciate your time and response :)

Is this JSON you passed using the actual WhatsApp Templates? Do you know if that piece is covered in the Chatwoot documentation?

cc @ASchneiderBR

**Comment by munawar050** [comment]
Yes, this is JSON.
Unfortunately I didn't find this in the documents and had to figure it out myself.

Currently I use this feature to send TEMPLATE messages to my customers via API.

**Comment by ahmedwali** [comment]
@munawar050 
How do I get the status of a particular message (sent, delivered, read, failed, deleted) if I sent it via API if the webhook is connected to chatwoot

**Comment by munawar050** [comment]
@ahmedwali , I am not exactly sure, as I don't have this in my usecase.

**Comment by grupale** [comment]
Hi @munawar050 can you tell me how do you handle to create new conversations and send the template messages via API? 

I'm trying first creating a new conversation in the WhatsApp Cloud inbox id and then posting the template message, the message is correctly posted but is not delivered. I think is becouse I'm not doing the conversation creation and sending the message in the same action.

**Comment by grupale** [comment]
Can you give me more details abount your conversations creations?  

I'm trying as follows:

1) I create a conversation in the WhatsApp Cloud API inbox_id

{{host}}/{{api_version}}/accounts/{{account_id}}/conversations

{
    "source_id": "10621",
    "inbox_id": 59,
    "contact_id": "10621",
    "status": "open"
}

Then I take the generated conversation_id and post a message

**Comment by munawar050** [comment]
For me in creation, I just login to UI of chatwoot and create a conversation and send the first template message.

Then I use API to send all the updates via the API. This fits my usecase very well.

Furthermore, your code seems fine, have you tried updating to the latest chatwoot?

**Comment by grupale** [comment]
> For me in creation, I just login to UI of chatwoot and create a conversation and send the first template message.
> 
> Then I use API to send all the updates via the API. This fits my usecase very well.
> 
> Furthermore, your code seems fine, have you tried updating to the latest chatwoot?

Thanks for your comments. In my use case I need to create the conversation via API and post the template message. 

@pranavrajs @sojan-official can you tell me please how can I achive this? Thanks

**Comment by Amelchorll** [comment]
i have the same problem, i am using postman, but message dont sent, but when i send by IU it sent with no problem, any idea.
![apiwhatsapp](https://user-images.githubusercontent.com/17705441/228057614-fb21def7-44af-4839-8c26-b76cd26567b0.jpg)
![image](https://user-images.githubusercontent.com/17705441/228057820-243fda72-d1e7-4194-934f-140a7e2f564e.png)

**Comment by grupale** [comment]
Hi @Amelchorll, please refer to https://github.com/chatwoot/chatwoot/issues/6704 I just posted there the APIs that works fine acordinly the video mentioned in that issue

**Comment by sojan-official** [comment]
closing in favor of #6704
