### ISSUE TITLE
bug: super admin account features

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#5964]
every time i edit the account features and press save there's no effect the feature still enabled after i disable it and press save

**Comment by fayazara** [comment]
@voko3456 Could you please share us some logs and provide more information to look into this.

**Comment by lpadula** [comment]
Hi, same problem here. Can someone review the fix from @voko3456 ?

**Comment by fayazara** [comment]
Closing this in favor of https://github.com/chatwoot/chatwoot/pull/5959
