### ISSUE TITLE
Esc key doesn't close the command bar

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#5988]
The escape key used to work before. With the recent changes, this key is not working when the command bar is open.

**Comment by iamsivin** [comment]
@pranavrajs I have debugged this issue and found that this issue occurred from the Grammarly extension in the browser.
When I try disabling it and now it is working.

**Comment by fayazara** [comment]
> @pranavrajs I have debugged this issue and found that this issue occurred from the Grammarly extension in the browser. When I try disabling it and now it is working.

Tested this, Grammarly is the culprit.
