### ISSUE TITLE
frequently disconnection

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5993]
**Describe the bug**

I have the agent chatwoot webinterface on my pc permanently open. Sometime - when I don't have the tab actively open, this error message comes up:
<img width="418" alt="Bildschirm­foto 2022-11-30 um 11 07 27" src="https://user-images.githubusercontent.com/17011498/204782758-141f083c-061f-4fb1-81e4-9fd8fdedf3f4.png">
(=Disconnected from chatwoot)

Here I have to do a manual reconnect again and again.

**Expected behavior**
No disconnection or automatically reconnection

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X] Self-hosted
- - [ ] Linux VM
- - [X] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: macOS
 - Browser Firefox
 - Version 107.0

**Comment by Ghost108** [comment]
Update:

I still receive chat messages, although the message said that I am not connected
<img width="994" alt="Bildschirm­foto 2022-11-30 um 12 27 40" src="https://user-images.githubusercontent.com/17011498/204784794-ec53fd71-4c96-4836-87f1-30ce78e920d9.png">

**Comment by pranavrajs** [comment]
@Ghost108 Can you please share your Nginx config? This is most likely a problem with the Nginx or load balancer configuration. You need to configure the keep-alive connection timeout properly.

**Comment by Ghost108** [comment]
Hi @pranavrajs 
Here my nginx config:

`server {
    listen 443 ssl;
    listen [::]:443 ssl;
    underscores_in_headers on;

    server_name chat.mydomain.de ;

    if ( $host !~ "(^chat.mydomain.de$)" ) { return 404; }

    include /usr/syno/etc/www/certificate/ReverseProxy_995f5f9d-dee2-4a9b-b30f-7c09ecc69c71/cert.conf*;

    include /usr/syno/etc/security-profile/tls-profile/config/ReverseProxy_995f5f9d-dee2-4a9b-b30f-7c09ecc69c71.conf*;

    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location / {

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        Upgrade            $http_upgrade;

        proxy_set_header        Connection            upgrade;

        proxy_set_header        Host            $host;

        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_set_header        X-Forwarded-Ssl            on;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_pass http://localhost:8888;

    }

    error_page 403 404 500 502 503 504 /dsm_error_page;

    location /dsm_error_page {
        internal;
        root /usr/syno/share/nginx;
        rewrite (.*) /error.html break;
        allow all;
    }

}

`

**Comment by Ghost108** [comment]
no support since 3 days :(

**Comment by panaras10** [comment]
Same issue here

**Comment by sojan-official** [comment]
@Ghost108 When the browser tab is not active,  there might be moments when Chatwoot was disconnected from the socket for short intervals. There is a chance that the frontend might have missed some events during this period and is not in sync with the state in the backend.  Hence the warning. 

ref: https://github.com/chatwoot/chatwoot/issues/5182#issuecomment-1301520796

closing in favor of https://github.com/chatwoot/chatwoot/issues/995
