### ISSUE TITLE
Change more colors of web widget

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#5997]
Hi all,

It would be nice, If I can change more colors of the web widget in the web widget configurator.
There must be a option to configure the colors for the light version and a seperted configurarion of colors for the dark mode.

<img width="396" alt="Bildschirm­foto 2022-11-30 um 19 10 18" src="https://user-images.githubusercontent.com/17011498/204876655-cfac97bb-13c5-410a-aeeb-779d6502272a.png">

For example:

> background color / font color of the header
> background color / font color of user speech bubble
> background color / font color of agent speech bubble
> background color of chat widget

**Comment by pranavrajs** [comment]
@Ghost108 At the moment, dark mode implementation is in the early stages. Once we complete the implementation in the dashboard, we can revisit this. Closing it for now as we will not be prioritizing it in the near feature.
