### ISSUE TITLE
Restrict agents to only see messages assigned to their own teams

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#5998]
Hello,

As per my understanding on how Chatwoot works, agents can see all messages of a specific inbox, so if I assign an agent to a specific team, this agent will still be able to see all messages from all the other teams if they click in "All conversations" and after that, in the "All" pane.

As an example: If I have one whatsapp inbox and two teams (sales and support), the support team will be able to see all messages assigned to the sales team because all agents must be allowed to see that specific whatsapp inbox.

Due to that, here is my question: Is there a way to restrict the agents to only see messages assigned to their teams?

Regards,

**Comment by pranavrajs** [comment]
@vagner-dias The permissions are now available only via inbox. Team permissions are not available. We will take it up in the #4216

**Comment by vagner-dias** [comment]
Great, thank you!
