### ISSUE TITLE
Can't use local URL for webhook 

### ISSUE THREAD

**Issue by vxm5091** [chatwoot/chatwoot#5999]
![image](https://user-images.githubusercontent.com/57078583/204926566-979c26d7-6318-45e5-b91b-5f49b746691d.png)

It looks like this field is validating for a standard URL, unless I'm missing something. Same validation error when using `localhost` as well.

**Comment by iamsivin** [comment]
@vxm5091 You can use ngrok or any other tunnelling mechanism.

**Comment by pranavrajs** [comment]
@vxm5091 Closing this as we are not supporting URLs localhost or local URLs as the production instance cannot access these URLs.
