### ISSUE TITLE
Unable to save Automation

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#6007]
Just did a bit of testing on Cloud Version & I was unable to save the "Send an email to team" Action in Automation. 

Before Saving: 

![image](https://user-images.githubusercontent.com/99071637/205178594-c6de737f-fa56-48a1-8cd0-569e76e6b72c.png)

After Saving:

![image](https://user-images.githubusercontent.com/99071637/205178774-54129e3e-edf1-4b66-979a-1bb6a11af891.png)

**Comment by pranavrajs** [comment]
@ammaraslam Thanks for reporting this. I can reproduce this. We will fix it soon.
