### ISSUE TITLE
Automation activity messages not being generated

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#6008]
**Is your enhancement request related to a problem? Please describe.**
Currently, we do not have Automation Activity message for these actions.

- Send an email to the team
- Send transcript
- Sent Attachment
- Send message 
- Send webhook 

**Describe the solution you'd like**
To bring consistency to the automation feature, there should be an activity message generated for each action that is performed. 

**Describe alternatives you've considered**
None.

**Comment by pranavrajs** [comment]
@ammaraslam We will track it here. #6015
