### ISSUE TITLE
get no welcome message / outside business hour message

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#6010]
**Describe the bug**

- If a user starts a conversation, no channel greeting will be send
- If a user write a message outside business hours, no message will be send (text: "We are not available at the moment....")

**Screenshots**
![Bildschirm­foto 2022-12-02 um 08 07 41](https://user-images.githubusercontent.com/17011498/205236430-d036a7f7-8deb-4cb0-9446-9ee71f804ab6.png)

![Bildschirm­foto 2022-12-02 um 08 12 24](https://user-images.githubusercontent.com/17011498/205236443-1b8d4834-9e1b-49b4-b585-1d72e7560df9.png)

![Bildschirm­foto 2022-12-02 um 08 07 52](https://user-images.githubusercontent.com/17011498/205236448-868e3f5c-74a6-4aac-be2e-22976a01e655.png)

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X] Self-hosted
- - [ ] Linux VM
- - [X] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**UPDATE**
I created a second test widget.
The test widget has no problems and it works like expected.

Live and test widget has got the same configs.
The only difference: the live widget has an agent bot assigend

**Comment by pranavrajs** [comment]
@Ghost108 This is by design. The system won't send any additional messages if a bot is connected. It is the responsibility of the bot to respond accordingly.

**Comment by Ghost108** [comment]
thank you! I could not find this in the api.

**Comment by Ghost108** [comment]
I see! is there already an api solution that the bot send a chat history via email? or do I have to create this myself?
