### ISSUE TITLE
Audit Logs

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6015]
The audit log shows the change in the Chatwoot since the account was created. It creates a record of these changes (we can keep it until they delete the account) and an admin can view these changes from the dashboard.

**Type of the feature:** Enterprise

This feature needs to be in the EE edition, we give it to the cloud users who are on the Business plan, but there is no requirement to make this an open-source one.

### How **do we record an event?**

An audit log would have the following properties.

- **Recorded Time:** This says when the event happened.
- **User:** Who did this action? We might need to store the name of the user and user_id seperately, so that even after the deletion of a user from the account, logs are available.
- **Type:** The type of the event ****record_created, record_updated, record_deleted, took_export (for reports), sign_in.
- **IP Address:** The IP address at which this action was taken.
- **Record:** The item which was changed. (We can show which db model changed)
- **Change/Activity:** A JSON that shows what happened.

### Which events are recorded?

- User login, signup, reset password
- User invitation to Chatwoot
- Account updation
- Conversation updation / (deletion - not available now, will be in future)
- Message deletion.
- Inbox creation / updation / deletion
- Webhook creation / updation / deletion.
- Download reports from Chatwoot
- Automation creation / updation / deletion
- Macro updation (public macro - only if other user’s is updated)

https://github.com/collectiveidea/audited

**Comment by harismateen** [comment]
@pranavrajs Can put this feature for open source also? many thanks in advance.

**Comment by vishnu-narayanan** [comment]
https://github.com/paper-trail-gem/paper_trail

**Comment by harismateen** [comment]
@pranavrajs  Is it available under Self hosted solution also?

**Comment by pranavrajs** [comment]
@harismateen This is only available in the enterprise version.
