### ISSUE TITLE
Create triggers for widget

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#603]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Posibility to create some triggers for widget 
Data triggers (time trigger, scroll trigger, page trigger, on page leave trigger)
**Describe alternatives you've considered**

**Additional context**

**Comment by aermike** [comment]
https://ro.wordpress.org/plugins/wp-live-chat-support/

**Comment by pranavrajs** [comment]
@aermike This would be covered in https://github.com/chatwoot/chatwoot/issues/274 Please close this if #274 includes your query.
