### ISSUE TITLE
Discrepancy in chatwoot client and DB data

### ISSUE THREAD

**Issue by sbiswas2209** [chatwoot/chatwoot#6035]
**Describe the bug**

The conversation id in the client URL does not match the conversation ID stored in the database. For example - the client's URL is `/app/accounts/1/conversations/33081` indicating the conversation id is `33081` but the id for the same conversation in the DB is `33100`. This increment in the conversation ID is inconsistent across all table elements.

**Expected behavior**

The conversation ID in the database should be consistent with what is being shown on the client's website.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- - [ ] app.chatwoot.com (Chatwoot Cloud)
- - [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Docker** (If applicable)

Please share the output of the following.
docker version - `20.10.18`
docker info - 
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)
WARNING: Plugin "/home/dev/.docker/cli-plugins/docker-compose" is not valid: failed to fetch metadata: fork/exec /home/dev/.docker/cli-plugins/docker-compose: permission denied

Server:
 Containers: 31
  Running: 15
  Paused: 0
  Stopped: 16
 Images: 306
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.45GiB
 Name:<NAME>
 ID: 5SZX:ZFWB:QCUI:3SB5:TIZH:IOXO:IMGM:VMDB:AKA6:FM7J:JF4K:DYEI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
docker-compose version - `1.29.2`

**Cloud Provider** (If applicable)
- [] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [x] Others

**Comment by pranavrajs** [comment]
@sbiswas2209 There are 2 id for a conversation. Primary key id and display ID. You would see the display id of a conversation in the URL, not the primary key id. Hope this helps.
