### ISSUE TITLE
Duplicando Conversas

### ISSUE THREAD

**Issue by EngajamentoFlow** [chatwoot/chatwoot#6046]
Estou com problemas de duplicação de conversas, chegam 3 a 5 por vez, e as vezes ate duplica o ticket.

![image](https://user-images.githubusercontent.com/91642837/206522878-f33c6e91-8871-4740-86f5-f68869b7888d.png)

Isso acontece apenas Whatsapp api oficial

open source 
Versão v2.11.0

**Comment by gruposocialinsta** [comment]
![image](https://user-images.githubusercontent.com/91642837/206522682-183217cc-aff6-4669-aeac-4c68510abd92.png)

**Comment by gruposocialinsta** [comment]
#duplicando

**Comment by gruposocialinsta** [comment]
![IMG-20221220-WA0053.jpg](https://user-images.githubusercontent.com/91642837/208747191-2b688d5f-8c34-472f-bddc-90296c960bef.jpg)
- [ ] -

**Comment by migarol** [comment]
we're having the same issue.

**Comment by gruposocialinsta** [comment]
it could be some chatwoot bug

**Comment by gruposocialinsta** [comment]
it could be some chatwoot bug

**Comment by ahmedwali** [comment]
I have the same issue

**Comment by iamsivin** [comment]
@pranavrajs Any idea?

**Comment by pranavrajs** [comment]
@migarol @EngajamentoFlow We have seen reports of duplicate webhook calls from Facebook and as result, we have added a check here in this PR https://github.com/chatwoot/chatwoot/pull/6220 to remove the message even though the same webhook events triggered multiple times. 

Please check out the latest release. I'm closing this for now. Please feel free to reopen the ticket if it still fix the issue.
