### ISSUE TITLE
Ubuntu 22.04 Jammy Jellyfish Not Supported 

### ISSUE THREAD

**Issue by nasiralamreeki** [chatwoot/chatwoot#6047]
The installer says Ubuntu 22.04 Jammy Jellyfish is not supported even though its a currently supported Ubuntu LTS

**Comment by sojan-official** [comment]
@nasiralamreeki At the moment, the installer only supports 20.04. We will upgrade the installer in future releases. 
If you can only work with 22.04, you could check our docker installation : https://www.chatwoot.com/docs/self-hosted/deployment/docker

**Comment by vishnu-narayanan** [comment]
@nasiralamreeki On a side note, Ubuntu 20.04 is still LTS which will be supported till 2025.

**Comment by vishnu-narayanan** [comment]
Closing this for now. Right now, we don't are a small team and don't have the capacity to maintain the installer for multiple OS'es. We will add support for 22.04 down the line, but for now, please use docker if you cannot use Ubuntu 20.04 LTS.
