### ISSUE TITLE
Unauthorized after creating account

### ISSUE THREAD

**Issue by tomjohnburton** [chatwoot/chatwoot#605]
**Describe the bug**
My password is not saved correctly. I can't log back in.
**To Reproduce**
I deployed using Heroku. Changed my password and I confirmed I received a `200`. Logged out and when trying to log back in I receive 401.
**Expected behavior**
To be able to log in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] chrome

![image](https://user-images.githubusercontent.com/39559415/76261386-283ebb80-625a-11ea-88eb-166a1a85a6a5.png)
![image](https://user-images.githubusercontent.com/39559415/76261452-558b6980-625a-11ea-8ada-737d6997904d.png)

**Comment by tomjohnburton** [comment]
UPDATE:
Same deployment, different login. These are the logs
```
2020-03-09T22:29:13.792654+00:00 app[web.1]: D, [2020-03-09T22:29:13.792559 #4] DEBUG -- : [97976add-7cfa-4802-a62f-c7d855308c13]   [1m[36mUser Load (1.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."email" = $1 AND "users"."provider" = $2 LIMIT $3[0m  [["email", "tomjohnburton@hotmail.com"], ["provider", "email"], ["LIMIT", 1]]
2020-03-09T22:29:13.793909+00:00 app[web.1]: I, [2020-03-09T22:29:13.793824 #4]  INFO -- : [97976add-7cfa-4802-a62f-c7d855308c13] Completed 401 Unauthorized in 32ms (Views: 0.2ms | ActiveRecord: 11.6ms | Allocations: 2892)
```

**Comment by pranavrajs** [comment]
@tomjohnburton Have you verified the account?

**Comment by tomjohnburton** [comment]
I’m not receiving any emails to do so

**Comment by sojan-official** [comment]
@tomjohnburton   let's ensure that the email configuration is done right.  you can do that by setting the appropriate environment variables of your email provider. [ref](https://www.chatwoot.com/docs/environment-variables#configure-emails )

My assumption is that you have signed up for an account and got auto logged in. You went into the profile settings and changed the password. Signed out an tried to log in again, In this case, the system isn't allowing to log in because the email wasn't confirmed yet. 

A couple of options available here. 
- Configure email and make things work as intended  
- if you are comfortable using rails console, mark the user verified via script 

```
u = User.find_by(email: 'youremailaddress')
u.confirm!
```

let us know if you need more help.

**Comment by tomjohnburton** [comment]
I've added the environment variables to the Heroku deployment. Do I need to redeploy?

**Comment by sojan-official** [comment]
@tomjohnburton  you won't have to.  But, ensure that your worker dyno is running as well. The mails are sent out from the sidekiq worker.

**Comment by tomjohnburton** [comment]
Dyno is up as far as I can see. Still no emails sadly. I'm using my personal gmail with an App Password configured

**Comment by sojan-official** [comment]
@tomjohnburton  anything showing up in the logs ?  I haven't given it a try with the gmail smtp settings. I will try it out and let you know if there is anything that's missing.  
the easiest options will be sendgrid, ses, mailgun etc.

**Comment by tomjohnburton** [comment]
Found this while trying to link SendGrid
```
2020-03-10T16:23:09.070093+00:00 app[worker.1]: D, [2020-03-10T16:23:09.070017 #4] DEBUG -- : Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true excluded from capture: DSN not set
```

**Comment by sojan-official** [comment]
@tomjohnburton  could you try setting the 'FRONTEND_URL' environment variable as well?  [ref](https://www.chatwoot.com/docs/environment-variables#configure-frontend-url)

The value of this variable should be the URL of your Heroku installation.

**Comment by tomjohnburton** [comment]
@sojan-official that fixed it! thanks for your help!!!
