### ISSUE TITLE
Can`t approve permission request for App

### ISSUE THREAD

**Issue by Kr00t** [chatwoot/chatwoot#6053]
Trying to approve permission for "instagram_manage_messages".
FB engineer sent reply: Improper handling of media CDN URLs - https://disk.yandex.ru/i/l_DCSpGHsgSNYQ
Is it possible to improve it in CW?

**Comment by tejaswinichile** [comment]
@Kr00t We have just merged the PR for the same and are using the CDN URL. 

https://github.com/chatwoot/chatwoot/pull/5300/

**Comment by iamsivin** [comment]
Closing this issue as we have shipped a fix https://github.com/chatwoot/chatwoot/pull/5300
