### ISSUE TITLE
Send audio longer than 10 seconds in WhatsApp Cloud API

### ISSUE THREAD

**Issue by jhonyrdesouza** [chatwoot/chatwoot#6054]
**Describe the bug**

I can't send audio longer than 10 seconds! How to send audio longer than 10 seconds in WhatsApp Cloud API inbox? I can only send 10 seconds?

**To Reproduce**

1. Go to open conversation
2. Click send audio
3. See that only 10 seconds of audio is sent

**Expected behavior**

I expected it to be possible to send audios longer than 10 seconds!

Our service team talks a lot with our customers with WhatsApp audios and I thought that migrating to Chatwoot was also possible!

**Screenshots**

![image](https://user-images.githubusercontent.com/58796224/206712419-63e6810e-746f-4bc1-a9a0-baceeb41e2f0.png)

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [x] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: Windows
 - Browser: Chrome
 - Version: 108.0.5359.99 (64 bits)

**Comment by giquieu** [comment]
Hello @pranavrajs  can i do this feature.
How long do you think it could be released for recording?
Or could a feature flag be created to configure the time?

**Comment by jhonyrdesouza** [comment]
Wow thanks guys!

On WhatsApp @giquieu, each audio can be a maximum of 15 minutes. If you can bring that same experience, I think that's ideal.

**Comment by pranavrajs** [comment]
@giquieu I'm only concerned about the size of the file. If the size of the file is less than 40MB for 15 minutes, that should be fine. Let me know what you think.

**Comment by pranavrajs** [comment]
Also, please see if there is any restriction in the WhatsApp Cloud API about the file size.

**Comment by pranavrajs** [comment]
> What do you think about allowing the audio to be recorded until it reaches 15MB or 16MB?

Sounds good. 15 minutes or 16MB whichever comes first would work.

**Comment by giquieu** [comment]
I sent a PR to be validated. Some settings worked as expected.
I'm validating the possibility of keeping the size along with the recording time text.
Ex:
![image](https://user-images.githubusercontent.com/9892674/208609620-e7f17e00-23aa-4b2f-b3cf-356ee4118075.png)

**Comment by jhonyrdesouza** [comment]
Fantastic, @giquieu! Thank you very much. This update will help us a lot here.
