### ISSUE TITLE
wrong order of message

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#6058]
**Describe the bug**
Is this a bug? or normal behavior ?
My bot writes a interactive message (content type input_select).
The user replies with a text message instead of selecting one of the bot options.
My bot will answer with a fallback message. AFTER this, the user select one of this option, but the selected answer will not be shown as last message (at the bottom), but directly below the interactive message.

**Expected behavior**
I guess it should be shown as the last massage.

** Secreenshots / Video**
http://www.giphy.com/gifs/YLz8nmcBy6V6LsHhvj

![Bildschirm­foto 2022-12-10 um 08 25 39](https://user-images.githubusercontent.com/17011498/206838499-54b36d37-eda9-48ec-9dcb-4d6c54c505c0.jpg)

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Comment by pranavrajs** [comment]
@Ghost108 Yes, this is expected as the response is shown next to the question itself for now. At the moment, there will not be any change in this behavior. Please feel free to reopen if it still needs to be discussed.

**Comment by Ghost108** [comment]
if this is what you expected, then I would like to disabled the user text field at that moment, so that they can only click on one of the options. What do you think?
