### ISSUE TITLE
whatsapp official api

### ISSUE THREAD

**Issue by marcelocaciatori** [chatwoot/chatwoot#6069]
I'm having trouble connecting official whatsapp api

[`****`](https://www.awesomescreenshot.com/video/13254631?key=3f51243074fe5b35ac30b95e24658dc4)

**Comment by sinapse-i-a** [comment]
detail more what this problem would be

**Comment by gruposocialinsta** [comment]
> detalhe mais o que seria esse problema

see which video did not participate make the connection via webhook

**Comment by pranavrajs** [comment]
@gruposocialinsta In the video, I can see that the URL is not generated properly, which means that the installation is not properly done. Can you please share the logs from the servers?
