### ISSUE TITLE
Heroku: hostname does not match the server certificate excluded from capture: DSN not set

### ISSUE THREAD

**Issue by weblle** [chatwoot/chatwoot#607]
**Describe the bug**
I'm trying to use herkou to host chatroot. So I am figuring out setting configurations for SMTP. But i've run into this snag. It's not working with my smtp server for sending emails. I keep getting this debug information on heroku log.
hostname "mail.<domain>.com" does not match the server certificate excluded from capture: DSN not set

What should i do? Should I use sendgrid?

**To Reproduce**
1. Setup app using Heroku
2. Setup SMTP details as configuration variables as described here:
https://www.chatwoot.com/docs/environment-variables#configure-emails
3. Create a new agent with their email

**Expected behavior**
Should send the activation/verification email to the newly registered Agent

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sojan-official** [comment]
@weblle  I think it's an ssl mismatch problem with your SMTP server.  could you verify the SMTP settings locally?  Sendgrid, SES, mailgun should work. could you give SendGrid a try and let us know ?

**Comment by weblle** [comment]
Thank you for a prompt reply. 
Do you suggest i add it as an Heroku addon or just add the smtp details as config variables?

**Comment by sojan-official** [comment]
@weblle  the SMTP details as environment variables is the suggested approach.

**Comment by weblle** [comment]
thank you very much @sojan-official. it worked
