### ISSUE TITLE
Account has exceeded the Gmail bandwidth limit for downloads via IMAP

### ISSUE THREAD

**Issue by dmpanch** [chatwoot/chatwoot#6082]
**Describe the bug**

3 days ago, Chatwoot sent us the first email saying "Your email inbox has been disconnected due to configuration errors".

We're using Google Workspace for email, in admin panel we found an error "Account has exceeded the Gmail bandwidth limit for downloads via IMAP" with link to [Gmail bandwidth limits](https://support.google.com/a/answer/1071518?hl=en#zippy=), for IMAP this limit is 2.5 Gb per day.
Account was blocked for a day, after which it can be automatically unblocked. Also, 5 manual unlocks are available per month.
Our daily flow is up to 50 letters maximum, the total volume of mail in the account is 4 Gb.

Today we got the same error again and spent 1 more manual unblock.

The mailbox used in Chatwoot is not used anywhere else, so perhaps Chatwoot is not optimally picking up mail from the mailbox?
Are there any settings in the system that can affect the strategy of working with the mailbox?

**To Reproduce**

1. Connect Google Workspace account for IMAP/SMTP with 4Gb+ emails inside.
2. Use it within a few days.3. 3. 
3. Get blocked.

**Expected behavior**

1. The mailbox is not blocked by Google2. 
**Screenshots**

<img width="859" alt="image" src="https://user-images.githubusercontent.com/4539449/208086819-26698215-8a98-4a85-b030-5c839ec79d76.png">

**Server logs**
[rails.log](https://github.com/chatwoot/chatwoot/files/10245335/rails.log)

Rails logs included, all personal information was removed.

**Environment**
- Self-hosted
- - Docker

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```
- `docker info`
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 257
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-104-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.89GiB
 Name: chatwoot
 ID: RSDZ:QM32:T5G7:DAMK:OQHG:CVBK:VHSP:RIWJ:KFXR:ZN6V:JWFV:WEAD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
- `docker-compose version`
```
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by pranavrajs** [comment]
@dmpanch Did this happen when you connected it initially or a later point in time?

**Comment by dmpanch** [comment]
@pranavrajs It happened in some time after using it.  After that I updated the server to the latest version and got the same error within 3 days as described above. 

I also wrote to workspace support to get more information about how the service could use mail in this way (dates, amount of data, etc.), but have not yet received a response.

**Comment by pranavrajs** [comment]
@dmpanch This seems a bit weird. I can see that we are not fetching all the messages every time. Instead, we only fetch the latest messages (last 10 read or unread). Is there any chance that the latest messages have some attachments which would cross this bandwidth?

**Comment by nickmonad** [comment]
@dmpanch We have experienced this issues as well. In our case, we didn't get these notifications until after about a month and a half of use. Please let us know what you hear from Google support!

**Comment by pranavrajs** [comment]
@sojan-official Can we think of migrating it to GMail APIs instead of IMAP? Since we are doing this for Microsoft email, it should be good place to see if we standardize such integrations.

**Comment by dmpanch** [comment]
@nickmonad just received response from them:

> We have exhausted our resources and consulted my colleagues as well regarding your concern/request. We are deeply sorry to inform you that as much as we would like to process your request, we do not have a way to do it because what you hit (bandwidth limit) is the set limit within the Google environment meaning, we cannot identify which specifically.

**Comment by nickmonad** [comment]
@pranavrajs @sojan-official That seems like a solid possibility. In the meantime, is there any way to currently adjust the rate at which chatwoot fetches new emails on an inbox? We deploy with helm and I looked closely to see if there are any options related to this and found none.

Could exposing that as an option be a temporary stop-gap in the next release if it's not currently possible?

**Comment by pranavrajs** [comment]
@nickmonad Sure that makes sense. Let us have an investigation and get back here

**Comment by bfuchs** [comment]
Maybe this is related to issue #5081 ?

**Comment by nickmonad** [comment]
@pranavrajs @sojan-official Any updates on traction for this issue? We've been bitten by this again and it seems like the concerns raised in #5081 are quite valid.

Even having the option to adjust the email fetch rate would be a big help.

**Comment by pranavrajs** [comment]
@nickmonad We are working on an improvement, just shipped a separate integration for Microsoft in the last update, and will pick up Gmail in the next releases. 

Updating the rate might not fix the problem completely. Can you please check if the issue is happening if there are any attachments and the size of the emails exceeded the limit somehow?

**Comment by nickmonad** [comment]
@pranavrajs Thanks for the update.

It's definitely due to the size of attachments. Our support team can sometimes receive video attachments (most recently we had one at around 25 MB) and since it appears that chatwoot is downloading those same emails repeatedly, we very quickly hit that 2500 MB per day IMAP limitation posted by Gmail.

We'd be happy to change how we integrate with Gmail once the APIs are supported over IMAP. Out of curiosity, is there an easy fix for the current IMAP issue? (in the sense that it seems to be downloading the same emails over and over again, especially those with attachments)

**Comment by bfuchs** [comment]
I also think the underlying issue of infinite fetch loops needs to be addressed. It is a big problem with attachments and a potential attack vector, but it should not happen regardless of the available disc space or traffic quota.

**Comment by nickmonad** [comment]
@pranavrajs Sorry to bother, just curious if there is planned work or a timeline for a fix here. We love what you guys have built and would really like to keep using it!

**Comment by pranavrajs** [comment]
@nickmonad We have been looking at the Oauth with Google and using Google APIs. It seems like quite a lot of work and can take time. However, there is a community PR https://github.com/chatwoot/chatwoot/pull/6498/files which might solve the problem, but it needs a bit of testing before getting it out. We will have at least a dirty fix to solve this problem by next release.

**Comment by Double-Click-ERP** [comment]
Hello @pranavrajs  , i am using this and it is work perfect with me (ps. not gmail)

>Mail.find(what: :last, count: 10, order: :asc, keys: ['UNSEEN']).each do |inbound_mail|

**Comment by jdabeau** [comment]
exactly the same issue... did you solve @dmpanch ?

**Comment by dmpanch** [comment]
@jdabeau still go over google's limits sometimes, but I haven't had to communicate with their support so far.
