### ISSUE TITLE
contact block list

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#6085]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Unfortunately on WhatsApp it is quite common for people to forward random messages to everyone in the contact list.

This type of person is clearly not a customer and just annoys the agent at the time of the call.

To resolve this, it would be interesting to have a list of blocked contacts, where when receiving a message from the customer, this conversation is always closed, or even deleted.

![image](https://user-images.githubusercontent.com/99494469/208186681-3ff815b6-64af-4373-aa79-c4ebe045c929.png)

**Describe alternatives you've considered**
We are using automations with a custom attribute to analyze if the contact is on the blocked list and automatically close the conversation.

But this is subterfuge, not standard.

In addition, even when doing this, the agent receives the notification, which bothers the service team.

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/3996
