### ISSUE TITLE
Location using WPPConnect Server - Chatwoot

### ISSUE THREAD

**Issue by ram0ng1** [chatwoot/chatwoot#6087]
I'm trying to receive location (feature only available in Official API) on WPPConnect Server (Whatsapp API).

I'm trying to do it like this:

```
        if (message.type == 'location') {
          let locationData = {
              lat: message.lat,
              Ing: message.Ing,
              address: message.address
          };

          let conversation_id = conversation.id;
          let contact_id = contact.id;

          await
          this.api.post(`api/v1/accounts/${this.account_id}/conversations/${conversation_id}/messages`,

          {
            type: 'location',
            data: locationData,
            contact_id: contact_id
            });
        };
```

But I just get the error: "Content Unavailable"

Could you help me with the correct location reception?

Complet File: https://pastebin.com/Zpc1AJqx
Link Original: https://github.com/wppconnect-team/wppconnect-server/blob/98cf94582c4c78fce6f09e6a6e8296a6790fa2b0/src/util/chatWootClient.js

**Comment by pranavrajs** [comment]
@ram0ng1 It would be good to create the issue at the wppconnect-server repo as we don't have much context on how it is designed.
