### ISSUE TITLE
Installation stops at 6/9

### ISSUE THREAD

**Issue by adbasanta** [chatwoot/chatwoot#6099]
Hi,

I hope someone can help me with this.
I have ubuntu 20.0.4 VM installed in VMWare.

I have installed all pre-requisites, curl, ruby 3.0.4, nodejs 14.21.1, postgresql but still the installation stops on 6/9.
Anybody knows the reason why? Thanks for helping.

Screenshots below with the log trail.
![install screen](https://user-images.githubusercontent.com/89345000/208403524-2b0f6a1b-46ad-4310-9034-d7af59339821.PNG)
![log trail](https://user-images.githubusercontent.com/89345000/208404479-fd91a6d9-9ad3-4bfc-a505-1a02baa802fc.PNG)

**Comment by sojan-official** [comment]
@adbasanta  How much ram is allocated for your VM ?

**Comment by Aghiles97** [comment]
you need to have at leat 4go of ram to install chatwoot.

**Comment by adbasanta** [comment]
upgrading the RAM fixed this issue. Thanks a lot.
