### ISSUE TITLE
Fix "Rubocop/Metrics/MethodLength" issue in app/models/conversation.rb

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#61]
Method has too many lines. [14/10]

https://codeclimate.com/github/chatwoot/chatwoot/app/models/conversation.rb#issue_5d87480c87cf1900010003c7

**Comment by MatheusRich** [comment]
I'm refactoring this file! So I'll tackle the issues related to `conversation.rb`
