### ISSUE TITLE
Enhancement: Move to the next conversation when i resolve a the current conversation

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#612]
**Is your enhancement request related to a problem? Please describe.**
When I resolve a conversation I would like the system to redirect me to the next conversation.

**Describe the solution you'd like**
When I resolve a conversation I would like the system to redirect me to the next conversation.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by wwwbruno** [comment]
I would like to take this issue as my first contribution 😄
