### ISSUE TITLE
Failure to deliver multiple images per message (WhatsApp Cloud API)

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#6120]
**Describe the bug**

Chatwoot fails to deliver multiple images in one messages on Whatsapp (via WhatsApp Cloud API). Instead, only one of the images will be sent. This is particularly bad, because there is no indication of this happening on the sender side.

On the sender side:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/1176036/209077471-f652c41e-2ee0-4b47-b323-4a68c7c7b283.png">

Receiver:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/1176036/209077529-f0683989-585d-4c5f-81a9-7f1d305e2cc7.png">

**To Reproduce**

1. Attach multiple images to one messages
2. Send it through the Web Interface
3. Check on the receiving WA account

**Environment**

chatwoot 2.12 (was also present in 2.11)

- [x] Self-hosted
- [x] Linux VM

**Comment by tejaswinichile** [comment]
Closing in favour of https://github.com/chatwoot/chatwoot/pull/6428
