### ISSUE TITLE
SMTP Not Working

### ISSUE THREAD

**Issue by oc7opu5** [chatwoot/chatwoot#6122]
Hi, I just installed Chatwoot via CapRover. The issue I am facing is I am not receiving account verification emails.
Can someone help, please?
*Hi, Do I have to add the SMTP variables in both Web interface and Worker?

**Comment by vishnu-narayanan** [comment]
You need to configure email-related environment variables. Yes, you would need to configure it for both containers.

ref: https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-emails

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still facing the issue.
