### ISSUE TITLE
api whatsapp, after finishing a conversation

### ISSUE THREAD

**Issue by rogeriorizzo** [chatwoot/chatwoot#6124]
api whatsapp, after finishing a conversation, when you open a new one, it stays open in the codigod and conversation market, and does not create a new one to continue, like the other inboxes.

![image](https://user-images.githubusercontent.com/76704479/209133445-fc644e3a-e8a5-4cd0-bf7c-0419343a85aa.png)

**Comment by fayazara** [comment]
Hey @rogeriorizzo If you mean locking conversations to a single thread, you can enable this from the inbox settings.

Here's a demo of how it can be enabled - https://www.loom.com/share/c9e1e563c8914837a4139dfdd2503fef

Closing for now, please reopen if you need any further help
