### ISSUE TITLE
StandardError: An error has occurred, this and all later migrations canceled

### ISSUE THREAD

**Issue by aliverio** [chatwoot/chatwoot#6135]
I have Chatwoot 2.0 and I am updating to the latest 2.12.0, I have been stopped by this problem after executing the database migration.
Chatwoot I have it on Linux Ubuntu 20.04.

RAILS_ENV=production bundle exec rake db:migrate

** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
I, [2022-12-26T11:01:56.022294 #2215449]  INFO -- : Migrating to AddAllowMessagesAfterResolvedToInbox (20211216110209)
== 20211216110209 AddAllowMessagesAfterResolvedToInbox: migrating =============
-- add_column(:inboxes, :allow_messages_after_resolved, :boolean, {:default=>true})
   -> 0.0035s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined local variable or method `auto_assignment_config' for #<Inbox id: 132, channel_id: 18, account_id: 27, name: "ChatBot Web - Chatzeus", created_at: "2021-12-09 18:16:20.659047000 +0000", updated_at: "2022-01-13 20:29:52.434618000 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: false, greeting_enabled: false, greeting_message: "", email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: true, allow_messages_after_resolved: false>
/usr/local/rvm/gems/ruby-3.0.4/gems/activemodel-6.1.6.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
/home/chatwoot/chatwoot/enterprise/app/models/enterprise/inbox.rb:15:in `ensure_valid_max_assignment_limit'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:603:in `catch'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:199:in `block in halting'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:512:in `invoke_before'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:105:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_validate_callbacks'
/usr/local/rvm/gems/ruby-3.0.4/gems/activemodel-6.1.6.1/lib/active_model/validations.rb:406:in `run_validations!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activemodel-6.1.6.1/lib/active_model/validations/callbacks.rb:117:in `block in run_validations!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_validation_callbacks'
/usr/local/rvm/gems/ruby-3.0.4/gems/activemodel-6.1.6.1/lib/active_model/validations/callbacks.rb:117:in `run_validations!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activemodel-6.1.6.1/lib/active_model/validations.rb:337:in `valid?'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/validations.rb:68:in `valid?'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/validations.rb:84:in `perform_validations'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/validations.rb:53:in `save!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:302:in `block in save!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:302:in `save!'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/suppressor.rb:48:in `save!'
/home/chatwoot/chatwoot/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:12:in `block (2 levels) in update_csat_enabled_inboxes'
/home/chatwoot/chatwoot/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `each'
/home/chatwoot/chatwoot/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:10:in `block in update_csat_enabled_inboxes'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/batches.rb:138:in `block in find_in_batches'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/batches.rb:245:in `block in in_batches'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/batches.rb:229:in `loop'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/batches.rb:229:in `in_batches'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/home/chatwoot/chatwoot/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:9:in `update_csat_enabled_inboxes'
/home/chatwoot/chatwoot/db/migrate/20211216110209_add_allow_messages_after_resolved_to_inbox.rb:5:in `change'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:867:in `exec_migration'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:851:in `block (2 levels) in migrate'
/usr/local/rvm/rubies/ruby-3.0.4/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:850:in `block in migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:849:in `migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1037:in `migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1329:in `block in execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1380:in `block in ddl_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/usr/local/rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:209:in `transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1380:in `ddl_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1328:in `execute_migration_in_transaction'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1302:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1302:in `migrate_without_lock'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1251:in `block in migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1401:in `block in with_advisory_lock'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1416:in `block in with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1416:in `with_advisory_lock_connection'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1397:in `with_advisory_lock'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1251:in `migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1086:in `up'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:1061:in `migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/tasks/database_tasks.rb:237:in `migrate'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/railties/databases.rake:92:in `block (3 levels) in <main>'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/railties/databases.rake:90:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/railties/databases.rake:90:in `block (2 levels) in <main>'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/sentry-ruby-core-5.3.1/lib/sentry/rake.rb:24:in `execute'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/rvm/gems/ruby-3.0.4/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-3.0.4/bin/rake:25:in `load'
/usr/local/rvm/gems/ruby-3.0.4/bin/rake:25:in `<main>'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `eval'
/usr/local/rvm/gems/ruby-3.0.4/bin/ruby_executable_hooks:22:in `<main>'

**Comment by pranavrajs** [comment]
@aliverio You cannot directly upgrade from 2.0 to 2.12. You need to upgrade from 2.1 to 2.2 to 2.3 and so on. Migrations are not running due to this issue.

Please migrate sequentially, it should work. Please feel free to reopen if it is not the case.
