### ISSUE TITLE
Graph api and chatwoot not mached for whatsapp

### ISSUE THREAD

**Issue by dhwaj1902** [chatwoot/chatwoot#6140]
When I used the graph api to send the template message to users, they are not shown on chatwoot.

Is there any separate API for send the template message which are visible to chatwoot.

**Comment by fayazara** [comment]
CC: @sojan-official @tejaswinichile

**Comment by fayazara** [comment]
Hey @dhwaj1902 If I am not wrong, I believe you're trying to send messages directly using the native whatsapp api and trying to see them in chatwoot dashboard, I believe these will not be shown in Chatwoot.

Please share some more details and we'll look into this and assist. Thanks

**Comment by dhwaj1902** [comment]
Yes @fayazara you got it right, I am using the native whatsapp api, but not able to see the message in chatwoot. So my ask is can you please provide me with some API so that I can send the message through that, so that it will be visible in chatwoot.

**Comment by grupale** [comment]
Hi! I'm looking for the same, I think we should use the API post to send a massage in a conversation with the aditional parameters to send an specific WhatsApp template.

**Comment by dhwaj1902** [comment]
> Hi! I'm looking for the same, I think we should use the API post to send a massage in a conversation with the aditional parameters to send an specific WhatsApp template.

Yes please update me as soon as it is done.

**Comment by sojan-official** [comment]
You can hit the Chatwoot Message APIs directly so the message records will remain in Chatwoot. Chatwoot will further deliver the message to Whatsapp endpoints. 

https://www.chatwoot.com/developers/api/#tag/Messages/operation/create-a-new-message-in-a-conversation

In the case of Whatsapp templates, use the following params as an example



```
{
   "content":"Hi Sojan. Were we able to solve the issue that you were facing?",
   "template_params":{
      "name":"sample_issue_resolution",
      "category":"ISSUE_RESOLUTION",
      "language":"en_US",
      "processed_params":{
         "1":"Sojan"
      }
   }
```

Content : The processed message body 
Template prams : Matches to the WhatsApp template params

**Comment by webmaster-gk2** [comment]
> You can hit the Chatwoot Message APIs directly so the message records will remain in Chatwoot. Chatwoot will further deliver the message to Whatsapp endpoints.
> 
> https://www.chatwoot.com/developers/api/#tag/Messages/operation/create-a-new-message-in-a-conversation
> 
> In the case of Whatsapp templates, use the following params as an example
> 
> ```
> {
>    "content":"Hi Sojan. Were we able to solve the issue that you were facing?",
>    "template_params":{
>       "name":"sample_issue_resolution",
>       "category":"ISSUE_RESOLUTION",
>       "language":"en_US",
>       "processed_params":{
>          "1":"Sojan"
>       }
>    }
> ```
> 
> Content : The processed message body Template prams : Matches to the WhatsApp template params

Hi, I try something like that but the template message dont send with the processed_params.
Can u help me?

`{
   "content":"Test message here Almir",
   "template_params":{
      "name":"teste",
      "category":"TRANSACTIONAL",
      "language":"pt_BR",
      "processed_params":{
         "1":"Almir"
      }
   }
}`

**Comment by sojan-official** [comment]
> > You can hit the Chatwoot Message APIs directly so the message records will remain in Chatwoot. Chatwoot will further deliver the message to Whatsapp endpoints.
> > https://www.chatwoot.com/developers/api/#tag/Messages/operation/create-a-new-message-in-a-conversation
> > In the case of Whatsapp templates, use the following params as an example
> > ```
> > {
> >    "content":"Hi Sojan. Were we able to solve the issue that you were facing?",
> >    "template_params":{
> >       "name":"sample_issue_resolution",
> >       "category":"ISSUE_RESOLUTION",
> >       "language":"en_US",
> >       "processed_params":{
> >          "1":"Sojan"
> >       }
> >    }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Content : The processed message body Template prams : Matches to the WhatsApp template params
> 
> Hi, I try something like that but the template message dont send with the processed_params. Can u help me?
> 
> `{ "content":"Test message here Almir", "template_params":{ "name":"teste", "category":"TRANSACTIONAL", "language":"pt_BR", "processed_params":{ "1":"Almir" } } }`

Is it an approved template ? can you post a screenshot of the approved template on facebook ?

**Comment by webmaster-gk2** [comment]
> > > You can hit the Chatwoot Message APIs directly so the message records will remain in Chatwoot. Chatwoot will further deliver the message to Whatsapp endpoints.
> > > https://www.chatwoot.com/developers/api/#tag/Messages/operation/create-a-new-message-in-a-conversation
> > > In the case of Whatsapp templates, use the following params as an example
> > > ```
> > > {
> > >    "content":"Hi Sojan. Were we able to solve the issue that you were facing?",
> > >    "template_params":{
> > >       "name":"sample_issue_resolution",
> > >       "category":"ISSUE_RESOLUTION",
> > >       "language":"en_US",
> > >       "processed_params":{
> > >          "1":"Sojan"
> > >       }
> > >    }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Content : The processed message body Template prams : Matches to the WhatsApp template params
> > 
> > 
> > Hi, I try something like that but the template message dont send with the processed_params. Can u help me?
> > `{ "content":"Test message here Almir", "template_params":{ "name":"teste", "category":"TRANSACTIONAL", "language":"pt_BR", "processed_params":{ "1":"Almir" } } }`
> 
> Is it an approved template ? can you post a screenshot of the approved template on facebook ?

Yeah, see below:
![image](https://user-images.githubusercontent.com/83838686/212082610-9f3174a5-21ea-46f0-a4ab-560a87ab706e.png)

**Comment by webmaster-gk2** [comment]
Hi, I solved the problem, i forgort to change the API Key. Thanks

**Comment by tejaswinichile** [comment]
> Hi, I solved the problem, i forgort to change the API Key. Thanks

Closing it as it seems that the problem has been resolved.
