### ISSUE TITLE
CSML bot buttons error

### ISSUE THREAD

**Issue by ammaraslam** [chatwoot/chatwoot#6143]
**Describe the bug**

Just tested out the new CSML bot feature on the cloud version.

`CSML Bot

start:

say Question(
  "I am a test bot, how may I help?", // equivalent to title="I am a test bot, how may I help?",
  buttons=[Button("Help"), Button("Doucumentation")] 
goto end`

![1](https://user-images.githubusercontent.com/99071637/209864619-0424f26c-edf5-4c2a-b6d2-41ef17bd79ab.PNG)

If I click a button on the widget, the bot question & user's selection, both gets shown in the same message on the web app. 

![2](https://user-images.githubusercontent.com/99071637/209864723-11aae836-9847-4cb3-b2f9-7893bc8255af.PNG)

Due to this, the user's selection isn't showing in the chat transcript. 

![3](https://user-images.githubusercontent.com/99071637/209864926-16d29a87-909f-466f-8bd9-acdb7c1ffb7b.PNG)

**Expected behavior**

The bot question and user's input selection, both should be in a different message. Not together like shown in the above SS. 

 - OS: [Windows]
 - Browser [Firefox]
 - Version [108.0.1]

**Comment by iamsivin** [comment]
@ammaraslam Currently, we only support text, images, and delay. Button/questions are not supported now.

**Comment by pranavrajs** [comment]
Closing this as we will be removing the CSML integration in the January release. No new bot can be added, although the existing ones would work.
