### ISSUE TITLE
Chatwoot is not sending WhatsApp audio through chrome. 

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6146]
Chatwoot is not sending WhatsApp audio through chrome. It generates a .webm file and doesn't send the audio that should be .oga.

My version: 2.12

Some friends who used version 2.11 and updated to 2.12 reported the same problem.

**Comment by pranavrajs** [comment]
@udsonassis Let us check it out. It should .webm for the website live chat and .oga for WhatsApp.

**Comment by udsonassis** [comment]
@pranavrajs Thanks for the feedback. Will you report us here if an update comes out with the solution to the problem?

**Comment by pranavrajs** [comment]
@udsonassis I've checked these. It doesn't seem to be reproducible. Can you please share a screencast?

**Comment by udsonassis** [comment]
@pranavrajs I recorded a video demonstrating the problem.: https://youtu.be/Qn2wV8wH_ew

**Comment by pranavrajs** [comment]
@udsonassis I believe this should be solved by https://github.com/chatwoot/chatwoot/pull/6108

**Comment by pranavrajs** [comment]
The latest version doesn't have this issue. I will create a hot fix release by the end of the day.

**Comment by pranavrajs** [comment]
Please see this tag. https://github.com/chatwoot/chatwoot/releases/tag/v2.12.1
