### ISSUE TITLE
cwctl --upgrade not upgrading, despite appearances

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#6153]
cwctl --upgrade does not actually perform an upgrade (at the very least not to 2.12.0) while acting like it does.

Unfortunately, I do not have a log of the first run but here is the output of a retry, according to which everything seems to be going just fine. Since none of the new features appear, that's however not the case.

https://gist.github.com/jochenstu/aaa289c74baa17191913f5ea91b4af6e

Self-hosted on Ubuntu 20.04.5 LTS, Linux VM. I tried rebooting the server (and thus also restarting everything Chatwoot), which didn't fix the issue. It's unclear to me, when this regression started and I can't say with confidence, that the previous upgrade _did_ still work.

[According to the release discussion](https://github.com/chatwoot/chatwoot/discussions/6104) there is at least one other person reporting the same issue.

**Comment by grupale** [comment]
+1

**Comment by jochenstu** [comment]
I just rerun this for the chatwoot 2.12.1 update – still not working. Here is the gist: https://gist.github.com/jochenstu/7a7bd86310ec287fdea3115c6f02ed2c

I run the cwctl v2.2.0 alpha build, which seems to be the current version.

**Comment by pranavrajs** [comment]
```
Compiling...
	Compilation failed:
```

What is the RAM size of the machine you are using? It looks like the compilation is failing.

**Comment by jochenstu** [comment]
4GB (Hetzner CPX21)

**Comment by jochenstu** [comment]
I used a backup prior to the upgrade attempt to be able to run a full cwctl --upgrade (including compilation) again. I also added 2GB of swap. 

Polling a the swap utilization a few times during the process, roughly 500MB were being used at peak (swapiness at Ubuntus default 60)

<img width="290" alt="image" src="https://user-images.githubusercontent.com/1176036/210166150-9368df1d-5cd3-40f1-85e9-052500d83593.png">

The upgrade completed successfully. Thoughts:

1. Add another 1GB of swap to the requirements in the manual
2. Being able to retrigger compilation would be neat (or if that just happened when re-running cwctl --upgrade)

**Comment by pranavrajs** [comment]
@jochenstu Thanks for following up on this.

> Add 1GB of swap to the minimum requirements in the manual

Yes, this makes sense. I've added it here. https://www.chatwoot.com/docs/self-hosted/deployment/requirements#memory

> Being able to retrigger compilation would be neat (or if that just happened automatically when re-running cwctl --upgrade, because it feels like it should)

@vishnu-narayanan This seems like a good one to add or `upgrade --rerun` should also work.
