### ISSUE TITLE
Chatwoot not send Whatsapp audio

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6155]
@pranavrajs thank you for your attention to my case. I did what you advised, I updated to version 2.12.1 but the problem continues. I made another video demonstrating the problem. https://youtu.be/0B9y33Q4mRM

**Comment by giquieu** [comment]
@udsonassis , Hello, I was following the messages and I noticed that you are using an API channel...
The API channel will use Webm, just like a web channel.

@pranavrajs 
What could be done in this case?
A suggestion, maybe create a configuration on the channel, signaling the format of the audio that will be sent?

**Comment by udsonassis** [comment]
@pranavrajs using the firefox browser I was successful in sending. https://youtu.be/x9sgOY8PC2I

**Comment by giquieu** [comment]
@udsonassis 
Redirect your webhook from your channel to a hook created at https://webhook.site/ and view the contents of the attachments.
Paste the result here, your audios must be .oga.
Do this in Chrome and Firefox please.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/9892674/210153069-ffab6cb1-fb89-41b7-8781-46673cec5671.png">

**Comment by udsonassis** [comment]
--------------- Result of sending by Google Chrome ------------
        "attachments": [
          {
            "id": 233,
            "message_id": 1589,
            "file_type": "audio",
            "account_id": 1,
            "extension": null,
            "data_url": "https://appchat.xgrowthdigital.com.br/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZTg9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--149a357ece3d4ea9454692d3897ab8ef0595d1d0/1672616123763.webm",
            "thumb_url": "",
            "file_size": 19360
          }
        ],
--------------- Result of sending by Firefox ------------
        "attachments": [
          {
            "id": 234,
            "message_id": 1590,
            "file_type": "audio",
            "account_id": 1,
            "extension": null,
            "data_url": "https://appchat.xgrowthdigital.com.br/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZkE9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cdaded4600c4405c8fe84608ecb357dc6a1b85bf/1672616414286.oga",
            "thumb_url": "",
            "file_size": 59825
          }
        ],

**Comment by pranavrajs** [comment]
@udsonassis Can you please make sure that the upgrade was successful?

**Comment by udsonassis** [comment]
@pranavrajs did you release a new update? Here on github the version is still 2.12.1. This is already my current version.

**Comment by jochenstu** [comment]
As an aside, what is the definite way to confirm the currently running version?

**Comment by udsonassis** [comment]
> As an aside, what is the definite way to confirm the currently running version?

@jochenstu you can check your Chattwoot version in Account Settings page

**Comment by giquieu** [comment]
@udsonassis 
I tried to simulate and I still couldn't reset it.. all environments are sending normal...
What is your version of Chrome? Are you in the last? If it's on the latest version, could you downgrade and validate?
My version is 105.0.5195.125 (Linux) (64-bit)

**Comment by udsonassis** [comment]
@giquieu my chrome version is Version 108.0.5359.124 (Official Version) 64 bits. Version of Chatwoot is 2.12.1. Ubuntu 24.04 64bit.

**Comment by giquieu** [comment]
@udsonassis Ok, I'll refresh my browser and check.

**Comment by pranavrajs** [comment]
@udsonassis It seems like the precompiling might have failed, and you are looking at a previous version of build assets. Can you please run this command in the chatwoot folder and see if it helps? https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

**Comment by udsonassis** [comment]
@pranavrajs ...
Error:

root@vmi1132072:/home/chatwoot/chatwoot# RAILS_ENV=production rake assets:clean assets:clobber assets:precompile
Warning: the running version of Bundler (2.2.33) is older than the version that created the lockfile (2.3.16). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.16`.
I, [2023-01-02T20:26:29.446948 #127196]  INFO -- : Removed /home/chatwoot/chatwoot/public/assets
Removed webpack output path directory /home/chatwoot/chatwoot/public/packs
yarn install v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 2.15s.
I, [2023-01-02T20:26:38.654912 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-b84bfa46a33d7f0dc4d2e7b8889486c9a957a5e40713d58f54be71b66954a1ff.js
I, [2023-01-02T20:26:38.655364 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/manifest-b84bfa46a33d7f0dc4d2e7b8889486c9a957a5e40713d58f54be71b66954a1ff.js.gz
I, [2023-01-02T20:26:38.655875 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-9eeb8687c7ddf2c627b558f5ece27ee816b822c366b28478e48276d4f226d09e.css
I, [2023-01-02T20:26:38.656229 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-9eeb8687c7ddf2c627b558f5ece27ee816b822c366b28478e48276d4f226d09e.css.gz
I, [2023-01-02T20:26:38.656539 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-15415a60389705f0e6e2bf7114bcb8df41d5b64c9e1285efdf1ed5bdbf608050.eot
I, [2023-01-02T20:26:38.658519 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-15415a60389705f0e6e2bf7114bcb8df41d5b64c9e1285efdf1ed5bdbf608050.eot.gz
I, [2023-01-02T20:26:38.659016 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-64da709cee30cc2d0f694fb5b2558d2e4b99e18be0faa9d8f04d6cd0dfb441c7.woff
I, [2023-01-02T20:26:38.662469 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-2d41026d28df88dd547243cfb38ce91b6937b50ffaf7e2c19a76d75119de61e8.ttf
I, [2023-01-02T20:26:38.664243 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-2d41026d28df88dd547243cfb38ce91b6937b50ffaf7e2c19a76d75119de61e8.ttf.gz
I, [2023-01-02T20:26:38.664737 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-159b5da43cd075c538889e1b84883da31c7f6b2e3608bfc4d424d810a773f034.svg
I, [2023-01-02T20:26:38.665784 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/bootstrap/glyphicons-halflings-regular-159b5da43cd075c538889e1b84883da31c7f6b2e3608bfc4d424d810a773f034.svg.gz
I, [2023-01-02T20:26:38.666740 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-fd630306cbbd45eb1c3f8827966072fd1a3f86a4e42f77d700576d097ad8a9b5.js
I, [2023-01-02T20:26:38.676830 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-fd630306cbbd45eb1c3f8827966072fd1a3f86a4e42f77d700576d097ad8a9b5.js.gz
I, [2023-01-02T20:26:38.677299 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-aa2a9947f4ec7f9df72106ac91490043439bed9dc9853f4a2de3358f44c51e90.js
I, [2023-01-02T20:26:38.677719 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-aa2a9947f4ec7f9df72106ac91490043439bed9dc9853f4a2de3358f44c51e90.js.gz
I, [2023-01-02T20:26:38.685171 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-aa2a9947f4ec7f9df72106ac91490043439bed9dc9853f4a2de3358f44c51e90.js
I, [2023-01-02T20:26:38.685648 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/dashboardChart-aa2a9947f4ec7f9df72106ac91490043439bed9dc9853f4a2de3358f44c51e90.js.gz
I, [2023-01-02T20:26:38.686845 #127196]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/administrate/application-fd630306cbbd45eb1c3f8827966072fd1a3f86a4e42f77d700576d097ad8a9b5.js.gz
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/chatwoot/chatwoot/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chatwoot/chatwoot/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

root@vmi1132072:/home/chatwoot/chatwoot#

**Comment by pranavrajs** [comment]
@udsonassis What's the memory size you are using? We recommend at least 4GB of RAM with 1GB of swap memory.

**Comment by udsonassis** [comment]
@pranavrajs 
Contabo RAM 16GB and CPU 6 Core

**Comment by udsonassis** [comment]
@pranavrajs I decided to format the VM and install everything from scratch and now everything is working! Thanks for your help. Your support is fantastic! I intend to hire your support. I'll finish structuring everything here and get in touch.
