### ISSUE TITLE
Can receive but can't send message whatsapp wppconnect

### ISSUE THREAD

**Issue by melakhvision** [chatwoot/chatwoot#6161]
**Describe the bug**

I have installed chatwoot  using VM installation script. I have wppconnect running on my server. I have added an API channel and intiate a chat. I can receive message but can't send. Message are likely send but not.

**To Reproduce**

1.  The API with wppconnect is working fine via swagger. I can send message.  But when I add it to chatwoot no message is send

**Expected behavior**

Months ago I have mad another installation a another server. But it worked.

**MY nginx config**

```bash
upstream backend {
  zone upstreams 64K;
  server 127.0.0.1:3000;
  keepalive 32;
}

map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}
server {
  listen 443 ssl http2 reuseport;
  listen [::]:443 ssl http2 reuseport;
  server_name mydomain.com www.mydomain.com;

  underscores_in_headers on;

  access_log /var/log/nginx/chatwoot_access_443.log;
  error_log /var/log/nginx/chatwoot_error_443.log;

  location / {
    proxy_pass http://backend;
    proxy_redirect off;
    proxy_pass_header Authorization;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Ssl on; # Optional
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;

    client_max_body_size 100M;
    proxy_read_timeout 360000s;
  }
  ssl_certificate /etc/letsencrypt/live/chat.psync.media/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/chat.psync.media/privkey.pem; # managed by Certbot
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers off;
  ssl_dhparam /etc/ssl/dhparam;
  ssl_early_data on;
  ssl_buffer_size 4k;
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 1d;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
}
```
**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM

**Desktop (please complete the following information)** (If applicable)
 - OS: [Windows]
 - Browser [e.g. chrome, firefox, safari]

**Comment by pranavrajs** [comment]
@melakhvision We do not support unofficial WhatsApp APIs. Hence we are not able to debug this request. If you can share if the Chatwoot APIs are not working, we will be happy to debug. Please feel to reopen with more details.
