### ISSUE TITLE
Inconsistent design in Macros

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6167]
![image](https://user-images.githubusercontent.com/2246121/210489238-89d331ec-7d03-4b71-852f-11644a4cd2da.png)

![image](https://user-images.githubusercontent.com/2246121/210489240-f2b009aa-380c-47ff-99a2-af7961279ac9.png)

![image](https://user-images.githubusercontent.com/2246121/210489249-8a22fc7d-6e89-4f14-93c3-ae08c1d9f5ba.png)

**Comment by nithindavid** [comment]
@pranavrajs I couldn't reproduce the mentioned label issue 
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/1277421/210549061-a932d8ae-591b-4949-be15-effe0808c9d8.png">

Let me know what's broken here in the first image.

![image](https://user-images.githubusercontent.com/1277421/210549122-dc9a4a53-3171-4f54-932f-d7dc45fe6da6.png)
