### ISSUE TITLE
Facebook set up error

### ISSUE THREAD

**Issue by tomjohnburton** [chatwoot/chatwoot#617]
When I try to set up a facebook inbox I get the following error

![image](https://user-images.githubusercontent.com/39559415/76779506-bca1a480-67ab-11ea-872d-9bd155901b3c.png)

**Comment by sojan-official** [comment]
@tomjohnburton  configuring Facebook integration in the self-hosted version requires setting a few additional environment variables [ref](https://www.chatwoot.com/docs/environment-variables#configure-fb-channel). But the current documentation we have on that isn't comprehensive. 

we will release an. updated documentation page in the upcoming days on configuring the facebook channel.

**Comment by tomjohnburton** [comment]
Thanks Sojan!
