### ISSUE TITLE
Official WhatsApp API Cloud Inbox not receiving Vcard

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6173]
The user shares a contact from his phonebook, but chatwoot is not receiving the information to the inbox.

![image](https://user-images.githubusercontent.com/4209678/210602803-a2736805-c728-4bcc-840a-47171503ae83.png)

**Comment by glauberssoutodossantos** [comment]
This gay here make something to resolve this problem

![image](https://user-images.githubusercontent.com/99494469/210784428-74f5f2c3-940b-466d-a312-1dc904960949.png)


You can track the conversation here: https://discord.com/channels/647412545203994635/719548300868452362/threads/1060305873450319882

**Comment by pranavrajs** [comment]
Closed by https://github.com/chatwoot/chatwoot/pull/6330
