### ISSUE TITLE
Webhook events for contacts

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6176]
> Hello, I'm using a self-hosted version and want to sync the contact list whenever a contact is added or updated. I need a webhook event for that. Now we only have conversations and message events. Contact will be a great feature to keep our CRM updated.

**Todo:** 

- [ ] Create a webhook event for the following
- [ ] contact.created
- [ ] contact.updated
- [ ] contact.destroyed

**Comment by imskr** [comment]
Can I work on this?
