### ISSUE TITLE
Chat icon image to use png base 64 instead of svg path

### ISSUE THREAD

**Issue by Azfarrr** [chatwoot/chatwoot#6178]
**Is your feature request related to a problem? Please describe.**
Since the latest chatwoot [version 2.12](https://github.com/chatwoot/chatwoot/discussions/6104), the chat icon uses svg format, the changes mainly in IFrameHelper.js

**Describe the solution you'd like**
I modified a bit of the code to use for my use case, where I check for the websiteToken, then if website token is for alligator website then I should use a custom chat icon, an alligator.

The code of that part is 

```
    let bubbleImage = '';
    if (websiteToken === 'tZ8zmh3dVQ2vA6Y9bqArXvBC' || websiteToken === 'xwkzDtYNYoWX9R163WBmGKHb') {
      bubbleImage = bubbleImgCat;
      className += ' cat-icon';
    } else if (websiteToken === 'VAsEbeapyKqWeL3UpHxSo5wi') {
      bubbleImage = bubbleImgGojupiter;
      className += ' gojupiter-icon';
    } else {
      bubbleImage = bubbleImg;
    }
```

Is it possible if I maintain to use png base 64 instead of the new svg format, but still I want pull the latest updates from the chatwoot repo. This is due to I can't obtain the svg version of the png image I'm currently using, and to retrace the image seems impossible as the design is just complex enough.

**Describe alternatives you've considered**
...

**Additional context**
...

Thanks.

**Comment by vishnu-narayanan** [comment]
@fayazara, any thoughts on this?

**Comment by fayazara** [comment]
Hey @Azfarrr I believe you can make changes and host the same, and keep pulling the updates from origin. If you're self hosting.

Any specific reason for using image hash? What's the use case?

**Comment by iammattmartin** [comment]
Would be better if we could just set this re: #4490

**Comment by Azfarrr** [comment]
> Hey @Azfarrr I believe you can make changes and host the same, and keep pulling the updates from origin. If you're self hosting.

Yes but I'm worried if there is more to the changes in 2.12 than simply changing icon to use svg instead of png. If I modified the code too a lot maybe something will break. Didn't got much time to look at the code currently.

> Any specific reason for using image hash? What's the use case?

As mentioned in the thread opener.

> This is due to I can't obtain the svg version of the png image I'm currently using, and to retrace the image seems impossible as the design is just complex enough.



> Would be better if we could just set this re: #4490

I also think it is best if chatwoot can add this feature, but idk maybe they only offered it to premium customers or something. Or maybe it will clash with their business strategy.

**Comment by sojan-official** [comment]
@Azfarrr  We will track it as a feature on #4490 .  Modifying the source code will always involve merge conflicts when pulling in the upstream changes. But since this is a smaller change, you should be okay.  

Closing this in favour of #4490
