### ISSUE TITLE
Copy buttons not working

### ISSUE THREAD

**Issue by floatingpurr** [chatwoot/chatwoot#6184]
**Describe the bug**

Copy button do not copy to the clipboard. An error is logged into the JS console upon click.

**To Reproduce**

1. Go to one of the copy buttons of chatwoot

<img width="935" alt="bug" src="https://user-images.githubusercontent.com/14820600/210802276-0696db57-24bd-4694-8ba9-3d946be66b6c.png">

3. Click on the button
4. ~Scroll down to~
5. See the error in the console (nothing is copied)

**Expected behavior**

Text copied to the clipboard

**Screenshots**

See screenshot above

**Browser logs**

```js
vue.common.prod.js:659 Error: Unable to copy text to clipboard: Cannot read properties of undefined (reading 'writeText')
    at clipboard.js:12:11
    at c (videojs.record.js:2868:27)
    at Generator._invoke (videojs.record.js:3088:32)
    at L.forEach.e.<computed> [as next] (videojs.record.js:2921:31)
    at a (application-1c516c439d0656573511.js:2:1437813)
    at s (application-1c516c439d0656573511.js:2:1438384)
    at application-1c516c439d0656573511.js:2:1438443
    at new Promise (<anonymous>)
    at application-1c516c439d0656573511.js:2:1438324
    at clipboard.js:8:33
```

**Server logs**

n/a

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [x] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: MacOS
 - Browse: Chrome
 - Version: 108.0.5359.124

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - Browser [e.g. stock browser, firefox, safari]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`: 20.10.22, build 3a2c30b
- `docker info` n/a
- `docker-compose version`: v2.14.1

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

n/a

**Comment by nithindavid** [comment]
Thanks for reporting this. I'll create a fix for this.

**Comment by floatingpurr** [comment]
No, I'm just using a sandbox over http. That can be the problem, in my case.
