### ISSUE TITLE
Not receiving CloudAPI WhatsApp messages after updating from 2.11 to 2.12.1! 

### ISSUE THREAD

**Issue by munawar050** [chatwoot/chatwoot#6198]
**Describe the bug**
I have stop receiving messages from Whatsapp Numbers when using CloudAPI right after updating from 2.11 to 2.12.1
I have also tried to reinstall complete chatwoot on my VM of Digital Ocean, however, still facing the exact same issue.

I am not facing any issue in sending the Whatsapp Messages, its just the receiving part.

Have reset the webhook too, but even that is not working.

**Environment**

Using Linux VM Self Hosted, installed it from https://get.chatwoot.app/linux/install.sh in digital ocean on Ubuntu 20.04

**Comment by adbasanta** [comment]
I also faced the same issue again but in a self-hosted machine.
I thought removing and adding the number from the business settings fix my issue but now I faced the same problem again.

@munawar050, did you find a solution?

Thanks.

**Comment by munawar050** [comment]
Not yet, I have tried the same from Business Setting Facebook, on various numbers, I guess the issue is with ChatWoot Side.

**Comment by munawar050** [comment]
@adbasanta I have checked via GLITCH that the issue is from Facebook side, not chatwoot.
https://developers.facebook.com/docs/whatsapp/sample-app-endpoints, try this.

I am trying to report bug on Facebook now.

**Comment by adbasanta** [comment]
@munawar050, I will try to do the same to populate the bug. Thanks for the information.

**Comment by sojan-official** [comment]
@munawar050  @adbasanta  Did you get any updates on the bug reports reported to facebook?

**Comment by munawar050** [comment]
@sojan-official not yet.
There many people with the similar issue, you can subscribe to the support request here https://developers.facebook.com/support/bugs/856675538926230/

We are waiting for META team to look into this issue.

**Comment by sojan-official** [comment]
@munawar050, thanks for linking the report.

**Comment by adbasanta** [comment]
@munawar050, I remove the WhatsApp app in meta and add it again and it worked. It's been more than 24 hours and still working.
It's just annoying to do it every time this happened. Meta should check the issue as many are affected.

**Comment by munawar050** [comment]
@adbasanta Thank you for the heads up, however, my app is associated with a number that has been verified.
If I delete the WhatsApp app in meta, wouldn't that delete my number too? And then I would have to reregister and wait for verification too.
