### ISSUE TITLE
SHIPMENT CSTAT

### ISSUE THREAD

**Issue by rogeriorizzo** [chatwoot/chatwoot#6202]
Another thing that sends to apis, they appear cstat information, however the message is not sent, it just appears as sent. this one from csat. started after the last version released  

![image](https://user-images.githubusercontent.com/76704479/211202068-778533f8-5bb9-461c-85a0-e33de18f86b5.png)

as we can see, it appears in the e-send, but it does not arrive on the other side, using the inbox api.

**Comment by rogeriorizzo** [comment]
@sojan-official  I identified that when I use the "API" type inbox, it is not sending the csat link, but in the other inboxes it sends the same, the strange thing is that, in the conversation it appears that it was sent, however to the user arrives, would have to activate something like that. in the official whatsapp api inbox it sends 100%, the problem is only in this one of the API

**Comment by sojan-official** [comment]
tracking this on https://github.com/chatwoot/chatwoot/issues/5291
