### ISSUE TITLE
A message comes from a Whatsapp number that is not connected to the chatwoot portal.

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#6206]
**Describe the bug**
A message comes from a Whatsapp number that is not connected to the chatwoot portal.

**To reproduce**
1. There are two phone numbers that are connected as a Whatsapp Cloud chatwoot v2.12.1
2. +79130440698 connected app1.chatwoot
3. +79148928232 connected app2.chatwoot
4. When sending a message to +79148928232, a conversation is created in app1.chatwoot and app2.chatwoot. It is not right.

**Expected behavior**
The conversation should have been created only on the app2.chatwoot portal.

**Screenshots**

https://i.imgur.com/PlBSXXt.png 

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Docker** (If applicable)

Please share the output of the following.
- `docker version  20.10.18`
- `docker info`
- `docker-compose version v2.2.2`

**Comment by pranavrajs** [comment]
@aerostovtsev I think there needs to be more information to debug this. The logs shared don't mean that the conversation is created. It just says that the webhook is received on the instance.

1. Is it two different instances or one instance with two domains pointed to the same Chatwoot instances?
2. Can you please check if the webhook URLs are properly configured in the Facebook developer Portal?
3. Can you please confirm on the UI that the message sent to the second number creates a conversation in the first number's inbox or vice-versa?

**Comment by aerostovtsev** [comment]
Hi @pranavrajs 
 
1. Is it two different instances or one instance with two domains pointed to the same Chatwoot instances?

These are two different instances:
1. App 1 https://app.chatwoot.com/app/accounts/76030
2. App 2 https://chizcase.bitcdp.ru/

2. Can you please check if the webhook URLs are properly configured in the Facebook developer Portal?

Screenshots of the application settings on the portal https://developers.facebook.com/:
1. App 1 https://i.imgur.com/w411U5J.png
2. App 2 https://i.imgur.com/y2YASTs.png

3. Can you please confirm on the UI that the message sent to the second number creates a conversation in the first number's inbox or vice-versa?

Screen recording https://loom.com/share/11e80a69ae5148f2b67eb8d55f08a7a2

**Comment by aerostovtsev** [comment]
@pranavrajs Any news on this issue?

**Comment by sojan-official** [comment]
@aerostovtsev  In the earlier screenshot you have provided as well as comparing the facebook developer screenshots, it seems that even though your number `- +79130440698` is connected app.chatwoot.com, but Facebook is still sending webhooks to your self-hosted installation. 

<img width="771" alt="Screenshot 2023-01-18 at 5 21 58 PM" src="https://user-images.githubusercontent.com/73185/213164736-593102da-7f6b-4587-869d-1ee2935047b4.png">

Please double-check whether you have any Facebook developer apps with this number connected to it and have configured your installation URL as the webhook URL.  

----

Notes 

- Incoming webhooks are sent by facebook, Chatwoot doesn't have any control over there. ( you could check with facebook support to see the case for duplicate webhooks for both instances )
- We only process the webhooks for channels created in Chatwoot with the correct phone number, So if you intend to use ` +79130440698` on Chatwoot, you can delete the the Channel created with this number in your self hosted installation.

**Comment by aerostovtsev** [comment]
Problem solved, WABA account was subscribed to two applications.
