### ISSUE TITLE
Desktop Chrome Notifications by new incoming chat

### ISSUE THREAD

**Issue by nickkuijpers** [chatwoot/chatwoot#6209]
**Describe the solution you'd like**
It would be nice if there is a function to allow the browser to send notifications when a new message arrives like the App does now.

**Comment by glauberssoutodossantos** [comment]
Hi @nickkuijpers.

I believe this feature already exist.

![image](https://user-images.githubusercontent.com/99494469/211315933-a389d306-810c-4e47-afa9-1bbe4ffbb271.png)

**Comment by sojan-official** [comment]
@nickkuijpers let us know if the expectation is any different.

**Comment by nickkuijpers** [comment]
Yes like that but then in the browser instead of the mobile app. Like this: https://support.google.com/chrome/answer/3220216?hl=en&co=GENIE.Platform%3DDesktop

**Comment by sojan-official** [comment]
@nickkuijpers  its is already available @glauberssoutodossantos  stated. You can click on the bottom profile avatar, navigate to profile settings and enable the notifications.

**Comment by nickkuijpers** [comment]
Ah i see! Perfect! Thank you for the fast response!
