### ISSUE TITLE
Different values between number of conversation in "Conversations" reports and SQL query count from conversations table

### ISSUE THREAD

**Issue by luissakihama** [chatwoot/chatwoot#6213]
**Describe the bug**

I am finding different values between number of conversation in "Conversations" reports and SQL query count from conversations table using the same data range values. The value in report is about 10% bigger than the value obtained by the a query like:

select count(*)
from conversations
where inbox_id = 14
and created_at between '2023-01-02 00:00:00' and '2023-01-06 23:59:59'

I using the Custom Data Range filter in the report with the same date limits from the query.

**To Reproduce**

1. Go to 'Reports -> Conversations'
2. Select the Custom Date Range filter and select the date range. Take note of the number of conversations shown.
3. Connect to chatwoot database and count the number of conversations for the same inbox and date range (user the query shown above as reference)
4. Compare both values

**Expected behavior**

The number of conversations in the report is bigger than the number of conversation count from the conversations table

**Environment**
- [X] Self-hosted
- - [X] Linux VM

**Desktop (please complete the following information)** (If applicable)
 - OS: Ubuntu Linux
 - Browser: Brave [Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (arm64)

**Comment by luissakihama** [comment]
Thanks @vishnu-narayanan 

I run the query following your guidelines. The result is a value slightly different from my previous query but still far from the value shown in the Report view.

Here there is the new query I run:

select count(*)
from conversations
where account_id = 8
and created_at between '2023-01-02 00:00:00+05:00' and '2023-01-06 23:59:59+05:00'

**Comment by vishnu-narayanan** [comment]
@luissakihama I am not able to reproduce this. Please share a screenshot of the reports page and the output via the query.

**Comment by luissakihama** [comment]
Sure @vishnu-narayanan . I am attaching the screenshots. Also my chatwoot instance version is 2.7

<img width="1410" alt="Query" src="https://user-images.githubusercontent.com/26125876/211978347-6a818c44-498f-44e9-9896-30abe2eaeedb.png">

<img width="1185" alt="Report1" src="https://user-images.githubusercontent.com/26125876/211978322-ea89d900-17ae-467c-b3ba-2bf5ad65937b.png">

**Comment by vishnu-narayanan** [comment]
@luissakihama From your domain, it seems you are based out of Peru. If that is correct and you are in the Peru timezone(GMT-5), could you try this query?

```
SELECT
	count(*)
FROM
	conversations
WHERE
	account_id = 8
	AND created_at BETWEEN '2023-01-02 00:00:00-05:00'
	AND '2023-01-06 23:59:59-05:00';
```

**Comment by luissakihama** [comment]
Yes @vishnu-narayanan  I am in Peru. I am attaching screenshot from the suggested query. The value remains the same, I thinks that's because this customer only works at office hours.

<img width="1401" alt="Screen Shot 2023-01-12 at 10 06 37" src="https://user-images.githubusercontent.com/26125876/212103015-d12ad91e-aaec-4fae-95d1-cb0d09967269.png">

**Comment by luissakihama** [comment]
Hi @vishnu-narayanan please let me know if you could replicate the issue, or do you need more information from my side. Thanks!

**Comment by vishnu-narayanan** [comment]
@luissakihama This is confirmed and I was able to replicate the bug. We will prioritize a fix in the coming sprints. Thank you raising this issue.
