### ISSUE TITLE
Enhancement: Use tokens specific to accounts to while encrypting data related to it

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#622]
**Is your enhancement request related to a problem? Please describe.**
Right now `Widget::TokenService` use rails secret to encrypt the tokens. This would cause issues in case of data migrations: 
- between accounts on different installations 
-  hosted solution -> self hosted & vice versa

**Describe the solution you'd like**
Generate account-specific tokens and use these tokens to encode/decrypt the identifiers  & other data

**Describe alternatives you've considered**
This particular case was observed in relation to `Widget::TokenService` ,  in this case, maybe the whole exercise of encoding tokens in unnecessary since the only source_id is required to identify a contact. 

We can probably remove the whole logic here and just switch it to saving source_id in the cookies and identifying contacts based on that. 

**Additional context**
none

**Comment by pranavrajs** [comment]
Closing this here for now, doesn't make sense to keep it open. Let us re-open if we re-prioritize.
