### ISSUE TITLE
Instagram inbox not receiving message

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6223]
I'm not sure I get Instagram messages in the inbox, but the message appears in the LOGS.

![image](https://user-images.githubusercontent.com/4209678/211564475-8812b0a4-8b16-4135-a5e5-83f5908174f6.png)

Application approved by Facebook.

Facebook Messenger messages arrive normally, only instagram does not arrive.

![image](https://user-images.githubusercontent.com/4209678/211564765-d6a9de62-43c7-4e8a-b059-46cb8088a0a8.png)

![image](https://user-images.githubusercontent.com/4209678/211564964-db05fa52-84a3-49bb-ae77-6818eaab9414.png)

![image](https://user-images.githubusercontent.com/4209678/211565074-a7dec8bf-f922-4f68-9ad1-846691582415.png)

Messenger:
![image](https://user-images.githubusercontent.com/4209678/211565268-50a467f5-99c5-4632-83a0-e1eaac2ef994.png)

Instagrram:
![image](https://user-images.githubusercontent.com/4209678/211565478-6d27edbf-40b2-4c3d-a048-af8b9c493984.png)

![image](https://user-images.githubusercontent.com/4209678/211565928-99d3fc9a-6910-4951-8137-dd6af5dfd095.png)

**Comment by fayazara** [comment]
@tejaswinichile could you please have a look at this.

**Comment by Lucasmartinspg** [comment]
@udsonassis como você conseguiu a aprovação da Meta para liberar as permissões necessárias?

**Comment by udsonassis** [comment]
@Lucasmartinspg me chame no discord que te oriento. 
Discord: Udson Assis#1569

**Comment by Lucasmartinspg** [comment]
@udsonassis muito obrigado, te enviei uma notificação lá amigo.

**Comment by udsonassis** [comment]
@Lucasmartinspg não recebi sua mengagem no Discord, qual seu usuario por la?

**Comment by pranavrajs** [comment]
Folks, Thanks for the collaboration here. I'm closing this here for now. Please feel free to reopen if it is still an issue.
