### ISSUE TITLE
[CW-1945] Add a default for the country code in the account

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6228]
> In the pre-form number field, it is required to add +(country phone indicator) is there a way to disable this, my business is 100% local, and adding the +xx is not relevant.

<sub>[CW-1945](https://linear.app/chatwoot/issue/CW-1945/add-a-default-for-the-country-code-in-the-account)</sub>

**Comment by Aghiles97** [comment]
Thank you for creating this, i hope we can see a work around soon.

**Comment by nithindavid** [comment]
This is a good suggestion. 

@tejaswinichile @sojan-official Which model should be used to add a field to save the country code?

**Comment by pranavrajs** [comment]
@Aghiles97 Moving this to our backlog, so that this is not missed.
