### ISSUE TITLE
Whatsapp Template from Twilio

### ISSUE THREAD

**Issue by fsentinel** [chatwoot/chatwoot#6237]
Hi, is not updating the whatsapp templates from twilio inbox.  

version 2.12.0

**Comment by muhsin-k** [comment]
There still needs to be more information to debug the issue. Could you provide more context?

**Comment by fsentinel** [comment]
The template created on twilio not sync on chatwoot, i can't see the tab template on inbox porperties and conversations options.

![image](https://user-images.githubusercontent.com/122453070/211821384-382a2cf8-2ffd-40c0-ba7a-9389ff047ad2.png)
![image](https://user-images.githubusercontent.com/122453070/211821721-a14e866c-827f-41a4-be88-923b21c4dfeb.png)
![image](https://user-images.githubusercontent.com/122453070/211821859-04d053af-29b5-4ac9-958e-f11a023567ac.png)

**Comment by pranavrajs** [comment]
@fsentinel This is expected as there is no API to fetch the templates from Twilio. Template synchronization works only with WhatsApp Cloud API and 360Dialog APIs.

**Comment by muhsin-k** [comment]
https://github.com/chatwoot/chatwoot/pull/12277
