### ISSUE TITLE
Issues with bot UI screens

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#6242]
I am not sure if these are bugs or as intended?

Issue 1 - Once you've configured the bot, you can't delete it in super_admin
Issue 2 - If you assign a bot to an org, and assign the bot to an inbox, you can't "unassign" it.

Issue 2 screenshot
<img width="760" alt="image" src="https://user-images.githubusercontent.com/25242465/211997740-c951711b-5b08-416b-b401-2e59ba2d3c39.png">

This is a self hosted, up to date version of Chatwoot.

**Comment by fayazara** [comment]
@sanjayws This looks a like bug, thank you for raising the issue, will create a fix for this.

**Comment by sanjayws** [comment]
thanks @fayazara for looking into this. Also, even if i disassociate it from the org, it appears to be still applied. Meaning, i assign the bot to another org, and when i go to that particular inbox, it's no longer there (as i've deleted in super_admin), but  somehow, it still gets triggered. 

The bot i am working on is integrating with botpress while the integration works well, this is one kink needs to fix where dissociation removes it from the backend when done with UI. 

Thanks again. Have a pleasant day.
