### ISSUE TITLE
Unable to create Whatsapp 360Dialog Inbox

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#6247]
**Describe the bug**

**To Reproduce**

1. Go to Settings > Inboxes > Add Inbox > Whatsapp  > 360Dialog 
2. Fill forms
3. Click  Create WhatsApp Channel
4. See the error

We were not able to save the WhatsApp channel

**Expected behavior**

I expected the inbox to be created without error, as it did on my other Chatwoot instance.

**Server logs**

> jan 12 15:36:29 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:29.043008 #25565]  INFO -- : [7c793fec-2bae-4400-b999-cfc8fb71f030] Started POST "/api/v1/accounts/2/inboxes" for 10.0.0.78 at 2023-01-12 15:36:29 +0200
> jan 12 15:36:29 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:29.044461 #25565]  INFO -- : [7c793fec-2bae-4400-b999-cfc8fb71f030] Processing by Api::V1::Accounts::InboxesController#create as JSON
> jan 12 15:36:29 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:29.044649 #25565]  INFO -- : [7c793fec-2bae-4400-b999-cfc8fb71f030]   Parameters: {"name"=>"DoubleClick ERP Solutions", "channel"=>{"type"=>"whatsapp", "phone_number"=>"+20100xxxxxxx", "provider_config"=>{"api_key"=>"[FILTERED]"}}, "account_id"=>"2", "inbox"=>{"name"=>"DoubleClick ERP Solutions"}}
> jan 12 15:36:29 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:29.322282 #25565]  INFO -- : [7c793fec-2bae-4400-b999-cfc8fb71f030] Completed 422 Unprocessable Entity in 277ms (Views: 0.7ms | ActiveRecord: 2.0ms | Allocations: 4538)
> jan 12 15:36:29 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:29.325239 #25565]  INFO -- : source=rack-timeout id=7c793fec-2bae-4400-b999-cfc8fb71f030 timeout=15000ms service=284ms state=completed
> jan 12 15:36:32 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:32.342200 #25565]  INFO -- : RoomChannel#update_presence
> jan 12 15:36:52 chat-VirtualBox chatwoot-web.1[25565]: I, [2023-01-12T15:36:52.342563 #25565]  INFO -- : RoomChannel#update_presence

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x ] Self-hosted
- - [ x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Additional context**

OS : ubuntu-20.04.5-desktop-amd64
Host OS : Windows 10
VM app : Oracle VM VirtualBox

**Comment by movilreup** [comment]
Hi i have the same problem with WhatsApp cloud channel no possible create channel

@sojan-official @nithindavid 

![213835647-a543dd7a-1809-4c0b-8d29-efffd7adf2f5](https://user-images.githubusercontent.com/96675665/213937512-39eb26e8-b49f-406c-a6fd-a837d4d9e0a8.png)

**Comment by Double-Click-ERP** [comment]
any update ?

**Comment by movilreup** [comment]
@Double-Click-ERP i ready solved the problem i change to used whatapp cloud and working properly now. You check the api key on 360 dialog is ready and approved?

**Comment by Double-Click-ERP** [comment]
@movilreup  yes the 360Dialog key is already used on another platform

**Comment by movilreup** [comment]
To me is better changes to official whatsapp API directly from meta to me work now perfect

**Comment by Double-Click-ERP** [comment]
how can i change ?

**Comment by movilreup** [comment]
> 

Check this links

https://m.youtube.com/watch?v=qAzhxOpv5JY

https://www.chatwoot.com/docs/product/channels/whatsapp/whatsapp-cloud

https://developers.facebook.com/docs/whatsapp/cloud-api/get-started

**Comment by Double-Click-ERP** [comment]
Thank you .
Can i use my same already working  "WhatsApp Business API" number?

**Comment by movilreup** [comment]
Yes, but you must log out of 360dialog and you have control of your account.  because if you use 360 ​​they are the ones who manage your account

**Comment by Double-Click-ERP** [comment]
@sojan-official any update for 360Dialog ??

**Comment by sojan-official** [comment]
@Double-Click-ERP  are you still facing issues saving inbox ? Could you check your browser console and see if there are any errors when creating the inbox ?

**Comment by Double-Click-ERP** [comment]
@sojan-official  
Here you are .

xhr.js:184          POST http://10.0.0.69:3000/api/v1/accounts/2/inboxes 422 (Unprocessable Entity)
(anonymous) @ xhr.js:184
e.exports @ xhr.js:20
e.exports @ dispatchRequest.js:39
c.request @ Axios.js:111
a.forEach.c.<computed> @ Axios.js:142
(anonymous) @ bind.js:11
value @ ApiClient.js:46
(anonymous) @ inboxes.js:143
c @ videojs.record.js:2868
(anonymous) @ videojs.record.js:3088
L.forEach.e.<computed> @ videojs.record.js:2921
Vl @ application-acb87d792a04f1b252cb.js:2
o @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ inboxes.js:140
(anonymous) @ vuex.js:778
S.dispatch @ vuex.js:497
S.dispatch @ vuex.js:416
(anonymous) @ 360DialogWhatsapp.vue:92
c @ videojs.record.js:2868
(anonymous) @ videojs.record.js:3088
L.forEach.e.<computed> @ videojs.record.js:2921
KS @ application-acb87d792a04f1b252cb.js:2
o @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
createChannel @ application-acb87d792a04f1b252cb.js:2
submit @ 360DialogWhatsapp.vue?3004:1
We @ vue.common.prod.js:638
n @ vue.common.prod.js:748
i._wrapper @ vue.common.prod.js:2568

**Comment by Double-Click-ERP** [comment]
application-acb87d792a04f1b252cb.js:2 [Violation] 'load' handler took 225ms

xhr.js:184          POST http://10.0.0.69:3000/api/v1/accounts/2/inboxes 422 (Unprocessable Entity)
(anonymous) @ xhr.js:184
e.exports @ xhr.js:20
e.exports @ dispatchRequest.js:39
c.request @ Axios.js:111
a.forEach.c.<computed> @ Axios.js:142
(anonymous) @ bind.js:11
value @ ApiClient.js:46
(anonymous) @ inboxes.js:143
c @ videojs.record.js:2868
(anonymous) @ videojs.record.js:3088
L.forEach.e.<computed> @ videojs.record.js:2921
Vl @ application-acb87d792a04f1b252cb.js:2
o @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ inboxes.js:140
(anonymous) @ vuex.js:778
S.dispatch @ vuex.js:497
S.dispatch @ vuex.js:416
(anonymous) @ 360DialogWhatsapp.vue:92
c @ videojs.record.js:2868
(anonymous) @ videojs.record.js:3088
L.forEach.e.<computed> @ videojs.record.js:2921
KS @ application-acb87d792a04f1b252cb.js:2
o @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
(anonymous) @ application-acb87d792a04f1b252cb.js:2
createChannel @ application-acb87d792a04f1b252cb.js:2
submit @ 360DialogWhatsapp.vue?3004:1
We @ vue.common.prod.js:638
n @ vue.common.prod.js:748
i._wrapper @ vue.common.prod.js:2568

application-acb87d792a04f1b252cb.js:2 [Violation] 'setTimeout' handler took 51ms

application-acb87d792a04f1b252cb.js:2 [Violation] 'setTimeout' handler took 214ms

**Comment by sojan-official** [comment]
@Double-Click-ERP when saving the 360dialog inbox, Chatwoot will query the 360dialog API to ensure that it's a valid API key.  422 error means that 360dialog didn't acknowledge it as a valid API key. 

ref: https://github.com/chatwoot/chatwoot/blob/c5b245977a353584ee591e2df51774ebd250f6d8/app/services/whatsapp/providers/whatsapp_360_dialog_service.rb#L29

Please make sure that you are using a production API key.  Also make sure that your 360dialog API base URL is `https://waba.360dialog.io/v1`

**Comment by Double-Click-ERP** [comment]
![2023-02-09_13h32_06](https://user-images.githubusercontent.com/121224467/217801452-701e517d-b2c2-4d3c-94b3-b8cbdbb6dba0.png)

@sojan-official

**Comment by Double-Click-ERP** [comment]
@sojan-official , sorry how to do that ? .

**Comment by Double-Click-ERP** [comment]
@sojan-official , you are talking about the The .env File ?
My FRONTEND_URL is local VM IP

**Comment by Double-Click-ERP** [comment]
> Could you try the following from your rails console?
> 
> ```
> 
> api_key = 'your api key'
> phone_number = 'your phone number'
> response = HTTParty.post(
>       "https://waba.360dialog.io/v1/configs/webhook",
>       headers: {'D360-API-KEY': api_key, 'Content-Type': 'application/json' },
>       body: {
>         url: "#{ENV.fetch('FRONTEND_URL', nil)}/webhooks/whatsapp/#{phone_number}"
>       }.to_json
>     )
> response.success?
> ```

how to test this ?

**Comment by sojan-official** [comment]
@Double-Click-ERP, it wouldn't work with your local VM IP since 360 dialogue will require a valid domain where it can send the webhook events.

**Comment by Double-Click-ERP** [comment]
@sojan-official , what about official whatsapp API ?

**Comment by sojan-official** [comment]
@Double-Click-ERP will also require a valid domain where the service can deliver the webhook events. 

closing the issue since their is conclusion on the original issue.
