### ISSUE TITLE
ERROR: undefined local variable or method `agent_bot' for #<Integrations::Dialogflow::ProcessorService:0x000055a0d3d80080 @event_name="message.created"

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#6256]
Noticed today that messages on inboxes or conversations linked with Dialogflow are not working and no responses received from Dialogflow.

This is a snippet of what I observed in the logs:

```ERROR -- : [ActiveJob] [HookJob] [5c163b1b-0454-4c9b-9e7a-0f5b078a8188] undefined local variable or method 'agent_bot' for #<Integrations::Dialogflow::ProcessorService:0x000055a0d3d80080 @event_name="message.created"```

No changes were made to system or settings and it was working fine until around 13 hours ago.

**Comment by pranavrajs** [comment]
@WevrLabs Can you please share the surrounding errors?

**Comment by WevrLabs** [comment]
> @WevrLabs Can you please share the surrounding errors?

```Jan 14 08:24:16 comms chatwoot-worker.1[626]: E, [2023-01-14T08:24:16.851801 #626] ERROR -- : [ActiveJob] [HookJob] [b34bdd38-1a08-40ea-9a74-bff46e99bade] undefined local variable or method `agent_bot' for #<Integrations::Dialogflow::ProcessorService:0x0000557eb0818cb8 @event_name="message.created", @hook=#<Integrations::Hook id: 14, status: "disabled", inbox_id: 138, account_id: 1, app_id: "dialogflow", hook_type: "inbox", reference_id: nil, access_token: "xxxxxxxxxxxxxx”, created_at: "2022-09-25 23:28:14.605931000 +0000", updated_at: "2022-09-25 23:28:14.605931000 +0000", settings: {"project_id"=>"xxxxxxxxxxxx", "credentials"=>{"type"=>"service_account", "auth_uri"=>"https://accounts.google.com/o/oauth2/auth", "client_id"=>"xxxxxxxxxxxxx”, "token_uri"=>"https://oauth2.googleapis.com/token", "project_id"=>"xxxxxxxxxx", "private_key"=>”xxxxxxxxxxxxxxxx”, "client_email"=>"xxxxx@xxxxxxxx.iam.gserviceaccount.com", "private_key_id"=>"xxxxxxxxxxxxxxxxx”, "client_x509_cert_url"=>"https://www.googleapis.com/robot/v1/metadata/x509/xxxxxxxxxxxx.iam.gserviceaccount.com", "auth_provider_x509_cert_url"=>"https://www.googleapis.com/oauth2/v1/certs"}}>, @event_data={:message=>#<Message id: 66404, content: "/start", account_id: 1, inbox_id: 138, conversation_id: 2103, message_type: "incoming", created_at: "2023-01-14 06:20:21.397557000 +0000", updated_at: "2023-01-14 06:20:21.397557000 +0000", private: false, status: "sent", source_id: "15031", content_type: "text", content_attributes: {}, sender_type: "Contact", sender_id: 22854, external_source_ids: {}, additional_attributes: {}, label_list: nil>}, @conversation=#<Conversation id: 2103, account_id: 1, inbox_id: 138, status: "pending", assignee_id: nil, created_at: "2021-09-10 22:07:26.508730000 +0000", updated_at: "2023-01-14 06:20:21.412346000 +0000", contact_id: 22854, display_id: 1971, contact_last_seen_at: nil, agent_last_seen_at: "2023-01-14 06:16:58.724737000 +0000", additional_attributes: {"chat_id"=>xxxxxxxx}, contact_inbox_id: 22845, uuid: "ada7486c-dd6e-4023-bff4-50f530a039c8", identifier: nil, last_activity_at: "2023-01-14 06:20:21.397557000 +0000", team_id: nil, campaign_id: nil, snoozed_until: nil, custom_attributes: {}, assignee_last_seen_at: "2023-01-07 12:08:26.067490000 +0000", first_reply_created_at: "2021-09-25 09:03:55.046568000 +0000", label_list: nil>>```
