### ISSUE TITLE
add support for coolify as a deployment option

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#6258]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Add support for [coolify](https://coolify.io/) as a deployment option

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by vishnu-narayanan** [comment]
Hey Community, please upvote this issue if you are interested to have this. We will prioritize this in a future sprint if there is enough interest.

**Comment by benrobinsonuk** [comment]
I believe it's the dev team at coolify who decide what they will add, but it would be great if you could contact them. 

They also have a voting system, lets al get voting too. 

Here is the link!

https://feedback.coolify.io/posts/15/service-chatwoot

**Comment by vishnu-narayanan** [comment]
@benrobinsonuk Thank you for sharing that.

**Comment by pranavrajs** [comment]
Closing this issue for now as it doesn't seem to be a task a community member can pickup.
