### ISSUE TITLE
One click deploy does not work as intended - conversations not updated live

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#626]
**Describe the bug**
When deploying app through one click deploy, app gets created as intended. Conversations between the agent and a user are not updated in real time forcing the user to refresh the page on each occasion.

**To Reproduce**
1. One click deploy
2. Embed the script into the body of an html page
3. Start conversation
4. Notice that messages remain grey until page refresh for client. Messages received by agent when page refreshed.

**Expected behavior**
Live conversation between agent and user without refresh

**Error in client console**
```
action_cable.js:259 WebSocket connection to 'wss://chatflo-devflo.herokuapp.com/cable' failed: WebSocket is closed before the connection is established.
```

**Comment by MajesteitBart** [comment]
You probably have to turn on one of the dynos, by default, one is turned off.

**Comment by tabrza** [comment]
@MajesteitBart that was it! thank you

**Comment by MajesteitBart** [comment]
That's great! The dyno, frontend url and db:migrate bugged me for hours :smile:
