### ISSUE TITLE
New conversations as Attack and blocking

### ISSUE THREAD

**Issue by edmsamuel** [chatwoot/chatwoot#6273]
Hello, the same thing happens to me :(

https://github.com/chatwoot/chatwoot/issues/4177

Container logs reporting Attacks but it's me :(, exists some solution for this?, i am using a LAN setup, have no domain, and i am not permitted or the server no permitted to setup a domain.

**Comment by iamsivin** [comment]
@edmsamuel, Can you share much more info? Which is your app version? Can you share a screen recording?

**Comment by edmsamuel** [comment]
Hola, nos acaba de volver a pasar disculpa la tardanza, a veces tarda en que vuelva a pasar este problema.

Te comparto dos gifs uno es donde está implementado chatwoot y el otro donde se ven los logs al intentar iniciar un nuevo chat.

Implementation on docusaurus project
![ixl6AzfrGd](https://user-images.githubusercontent.com/14112893/213565273-0ce63443-61e3-4315-8eb2-4a201775e739.gif)

Logs on docker
![mstsc_UyI53oyNLQ](https://user-images.githubusercontent.com/14112893/213565328-afa89c75-b486-4427-b480-5ba4d580d355.gif)

Gracias por la ayuda.

**Comment by iamsivin** [comment]
CC @sojan-official @vishnu-narayanan

**Comment by sojan-official** [comment]
@edmsamuel  Chatwoot by default restricts the number of requests that you can make from a single IP. to specific endpoints to prevent spam.  

ref: https://www.chatwoot.com/docs/self-hosted/monitoring/rate-limiting 
https://github.com/chatwoot/chatwoot/blob/d9a11549779689eca5d7fe6a1704f0bb08321d76/config/initializers/rack_attack.rb#L99

In your case if its not relevant, you can disable this protection by configuring following environment variable 

```
ENABLE_RACK_ATTACK=false
```

**Comment by edmsamuel** [comment]
Hello good morning.
Thank you very much for the help, I will change the value right now, I really appreciate it very much.

I'll feed you back in a few hours.

**Comment by iamsivin** [comment]
@edmsamuel Closing this issue as it is resolved https://github.com/chatwoot/chatwoot/issues/6273#issuecomment-1401771166
