### ISSUE TITLE
WhatsAppChannel: You cannot reply due to 24 hour message window restriction

### ISSUE THREAD

**Issue by Jorgelig** [chatwoot/chatwoot#6274]
**Describe the bug**

The 24 hour restriction does not affect when a message is sent from the template using the WhatsApp Business Platform Cloud API

**Expected behavior**
Enable the Respond tab, and only allow sending templates and not free text

**Comment by sojan-official** [comment]
@Jorgelig  The current behaviour allows you to choose a template and respond ( the respond tab is already enabled ) .  Do you want the tab to be disabled ?

<img width="869" alt="Screenshot 2023-01-18 at 3 38 14 PM" src="https://user-images.githubusercontent.com/73185/213143691-7258f91b-c46b-4fad-a5c3-5f24aeb0d62c.png">

**Comment by Jorgelig** [comment]
The Reply tab is inactive and disabled, when I click the reply tab nothing happens, it still leaves me in the Private Note tab.

If it is not an expected functionality, what do you think could be the problem?

![image](https://user-images.githubusercontent.com/581672/213600997-1d9508f5-08b4-438f-9c4d-db0e5ab41a61.png)

**Comment by sojan-official** [comment]
@Jorgelig could you specify the following details ?

Could you specify the Chatwoot version which you are using? 
also, confirming that the channel provider is `Whatsapp Cloud` ?  
also, do you have approved Whatsapp templates in your account?

**Comment by sojan-official** [comment]
We are closing this issue since there haven't been any recent updates. Please feel free to reopen if the problem persists.
