### ISSUE TITLE
How can I get unread messages count? JS

### ISSUE THREAD

**Issue by kolesnikova-tavi** [chatwoot/chatwoot#6276]
**Is your enhancement request related to a problem? Please describe.**
**Describe the solution you'd like**

I need to show unread messages count in main menu of website.
There are only chatwoot:ready and chatwoot:error events. Maybe there is more? 
![tg_image_3541713445](https://user-images.githubusercontent.com/3088258/213109934-95ffe031-343d-4ff4-9bfa-d186c6c91693.jpeg)

**Comment by pranavrajs** [comment]
@kolesnikova-tavi This is not supported and will not be planned in the future, as we are going to support multiple conversations in the live-chat widget. Total number of unread messages wouldn't make much sense in that case

**Comment by kolesnikova-tavi** [comment]
@pranavrajs  OK, I got it. Thank You!

**Comment by kolesnikova-tavi** [comment]
@pranavrajs Are there any other events? Maybe chatwoot:new_message?
Or Can I get the number of unread conversations? Maybe in the future?

**Comment by sojan-official** [comment]
@kolesnikova-tavi  you can listen to the new messages with 
```
window.addEventListener('chatwoot:on-message', function(e) {
  console.log('chatwoot:on-message', e.detail)
})
```

ref: https://github.com/chatwoot/chatwoot/pull/6425

**Comment by kolesnikova-tavi** [comment]
@sojan-official Thank you very much!
