### ISSUE TITLE
DYTE integration cross site mic & video request issue

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#6277]
So i managed to get Dyte to work and it does work fine in principle, but there's one big caveat. This is something i am not sure how to solve. I will try to explain the issue briefly here.

Problem statement:
When an agent hits on the video icon, to start a video/audio, the other side where customer reside (say on website www.bestbakers.com) gets a prompt inside their chat a video request is made. So when i accept the request, it doesn't prompt to allow video/mic. I can imagine this is due to the frame in which the chat resides is requesting it (via JS snippet) is not from bestbakers.com but instead, where the chatwoot instance is.

Expected behavior:
From website bestbakers.com, it is suppose to prompt the browser to allow mic and video. Agent side, chatwoot.deliverycompany.com does prompt. 

Workaround:
I had to access chatwoot.delivercompany.com first, allow the cam/mic first, then the embedded chat in bestbakers.com works as its accepted, naturally. 

Env: Self hosted, Ubuntu, CW - Latest.

Any advice is highly appreciated.

**Comment by pranavrajs** [comment]
@sanjayws I've test this with our production. app.chatwoot.com and chatwoot.netlify.app. It works without issues there.

**Comment by pranavrajs** [comment]
Can you please share any additional information or a screencast to debug this?

**Comment by sanjayws** [comment]
Actually, i just tested it, it does prompt now. Weird it didn't earlier. Please do close this for now, if anything i will raise it again with more info.

Thanks
Sanjay
