### ISSUE TITLE
feat: Keyboard shortcuts for conversation actions

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#628]
**Is your enhancement request related to a problem? Please describe.**
don't have Keyboard shortcuts for conversation actions

**Describe the solution you'd like**
- Need to have Keyboard shortcuts for conversation actions
  - Resolve conversation
  - Reopen conversation
  - Go to the next conversation
  - Go to the previous conversation
  - Go to 
    - all conversations tab
    - mine tab
    - unassigned tab
  - Toggle sidebar
  - Switch to private note tab
  - Focus on reply box

**Comment by pranavrajs** [comment]
@muhsin-k Just take a look at this and let me know if you need any more information.

**Comment by muhsin-k** [comment]
@pranavrajs Sure

**Comment by aherrera31** [comment]
@pranavrajs @muhsin-k -- any update on this feature? Superhuman's keyboard shortcuts could be great inspiration here

**Comment by pranavrajs** [comment]
- [ ] Open conversation - J up K down
- [ ] Resolve Conversation - Shift + E
- [ ] Resolve and move to next - Shift + Cmd + E
- [ ] Switch to Private Note - Shift + P
- [ ] Switch to Reply - Shift + L
- [ ] Add Attachment - Shift + A
- [ ] Toggle Sidebar - Shift + O
- [ ] Toggle Rich Content editor - Shift + W
- [ ] Move to next tab in conversation list - Shift + N
- [ ] Switch Conversation status - Shift + B
- [ ] Go to Conversation Dashboard - Shift + C
- [ ] Go to Contacts Dashboard - Shift + V
- [ ] Go to Reports sidebar - Shift + R
- [ ] Go to Settings - Shift + S
