### ISSUE TITLE
API Inbox Error: The 422 error should respond with exactly what part of the contact object is "bad" or incorrect so users can know how to fix it

### ISSUE THREAD

**Issue by ayamkampung** [chatwoot/chatwoot#6280]
**Is your enhancement request related to a problem? Please describe.**
API Inbox Error:  The 422 error should respond with exactly what part of the contact object is "bad" or incorrect so users can know how to fix it

**Additional context**
info: CW REQUEST: 200 get http://localhost:3000/api/v1/accounts/1/contacts/search?q=6X4562149394&sort=phone_number undefined {"timestamp":"2023-01-18T02:22:23.239Z"}
error: Request failed with status code 422 {"config":{"data":"{\"identifier\":\"6X1232016777@c.us\",\"name\":\"You\",\"phone_number\":\"+6X1232016777\",\"avatar_url\":\"https://pps.whatsapp.net/v/t61.24694-24/308453810_602532928282875_8935023911658664976_n.jpg?ccb=11-4&oh=01_...[TRUNCATED]...","headers":{"Accept":"application/json, text/plain, /","Content-Length":1296,"Content-Type":"application/json","User-Agent":"axios/0.25.0","api_access_token":"[REDACTED]"},"maxBodyLength":-1,"maxContentLength":-1,"method":"post","timeout":0,"transformRequest":[null],"transformResponse":[null],"transitional":{"clarifyTimeoutError":false,"forcedJSONParsing":true,"silentJSONParsing":true},"url":"http://localhost:3000/api/v1/accounts/1/contacts","xsrfCookieName":"[REDACTED]","xsrfHeaderName":"X-XSRF-TOKEN"},"name":"Error","stack":"Error: Request failed with status code 422\n    at createError (/home/osboxes/.npm/_npx/2111/lib/node_modules/@open-wa/wa-automate/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/hom...[TRUNCATED]...","status":422,"timestamp":"2023-01-18T02:22:23.261Z"}
TypeError: Cannot read property 'id' of undefined
    at ChatwootClient.<anonymous> (/home/osboxes/.npm/_npx/2111/lib/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:492:93)
    at Generator.next (<anonymous>)
    at fulfilled (/home/osboxes/.npm/_npx/2111/lib/node_modules/@open-wa/wa-automate/dist/cli/integrations/chatwoot.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by tejaswinichile** [comment]
@ayamkampung If there is any error while get request that means the contact associated record is not present and JSON is throwing error.

To get the detailed error I suggest you to configure sentry to track the error and exception or configure rails production logger.
