### ISSUE TITLE
Main interface doesn`t update after chatwoot upgrade.

### ISSUE THREAD

**Issue by Kr00t** [chatwoot/chatwoot#6292]
**Describe the bug**

Main interface doesn`t update after chatwoot upgrade.
I try twice update, but failed. Interface is old, but version number in settings was changed.

**Expected behavior**

New updated interface

**Screenshots**

![2023-01-19_13-17-58](https://user-images.githubusercontent.com/35505986/213416909-7904bc47-aec9-4a50-8fde-4f465cd187b9.png)
![2023-01-19_13-17-38](https://user-images.githubusercontent.com/35505986/213416915-eb354a0c-3db4-4b19-aad4-4f66a4414608.png)
![2023-01-19_13-17-21](https://user-images.githubusercontent.com/35505986/213416918-6656894e-812c-4905-81df-13624c94be85.png)

**Server logs**

[chatwoot-setup-reinstall.log](https://github.com/chatwoot/chatwoot/files/10455838/chatwoot-setup-reinstall.log)
[chatwoot-setup-second-time-update.log](https://github.com/chatwoot/chatwoot/files/10455839/chatwoot-setup-second-time-update.log)

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** 
 - OS: Windows
 - Browser: Chrome
 - Version: Version 109.0.5414.75 (Official Build) (64-bit)

**Additional context**

**Comment by nithindavid** [comment]
@Kr00t Can you check the browser console and see if there's any error?

Also, there was a package update. Can you please do a `yarn install --force` and see if it fixes the issue?

**Comment by Kr00t** [comment]
root@cw:~# yarn install --force
yarn install v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...

success Saved lockfile.
Done in 0.15s.
root@cw:~#

No changes on interface.

**Comment by nithindavid** [comment]
@Kr00t Any console errors in browser?

**Comment by Kr00t** [comment]
@nithindavid no console error https://www.youtube.com/watch?v=AtQm27ffucg

**Comment by Kr00t** [comment]
@nithindavid I can give you ssh access to see what`s ahppen. It starts from 2.11 version. If you give me your publish ssh key, i`ll make root access.

**Comment by sojan-official** [comment]
@Kr00t  could you try a force recompile and then do a restart ? 
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

**Comment by Kr00t** [comment]
@sojan-official Interface updated now, but with some dasplay 
![2023-01-25_12-41-28](https://user-images.githubusercontent.com/35505986/214529956-e528ce23-a26a-4c61-910e-2a480de50447.png)
problem

**Comment by pranavrajs** [comment]
@Kr00t This doesn't seem to be reproducible on the latest version. Closing this issue for now. Please feel free to reopen it if the issue still exists.
