### ISSUE TITLE
Grammatical typo in "Email Channel" inboxes pages

### ISSUE THREAD

**Issue by iprithvitharun** [chatwoot/chatwoot#6307]
**Is your enhancement request related to a problem? Please describe.**

`Email where your customers sends you support tickets` 

- "Sends" doesn't agree with the plural subject.
- Punctuation at the end is missing.

<img width="831" alt="Screenshot 2023-01-20 at 8 51 34 AM" src="https://user-images.githubusercontent.com/58725708/213611165-e197739d-9fca-48dd-9941-f6e679b36891.png">

**Comment by nithindavid** [comment]
@iprithvitharun Thanks for reporting this. Let me know if you're picking up this issue.

**Comment by iprithvitharun** [comment]
@nithindavid PR is already raised - https://github.com/chatwoot/chatwoot/pull/6308

**Comment by nithindavid** [comment]
Thanks a lot :)
