### ISSUE TITLE
[CW-1436] Prioritizing the conversations, custom views and redesigning the sidebar

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6309]
### Context 

To prioritize conversations, we need to provide better tools for the agent and the admin. This ticket is written based on the interaction we had for the https://github.com/chatwoot/chatwoot/pull/6186. It feels that the sidebar needs a revamp. These are my initial thoughts on the same. Some of the points which community raised also need to be considered (I will link the tickets later on)
  - The inboxes are not shown in the order in which it needs attention. It should be ordered based on the number of unassigned/unattended conversations. (https://github.com/chatwoot/chatwoot/issues/4107)
  - The inbox uses the same name for both external communication and internal communication. (https://github.com/chatwoot/chatwoot/issues/4228)
  - Unread inboxes/teams are still listed in the sidebar (https://github.com/chatwoot/chatwoot/issues/1127)
  - If there is a long list of labels, the sidebar is pretty much unusable.
  - Adding custom views is not user-friendly. The sidebar is not helping this case.
  - There is no count shown in the sidebar. The agents don't know what is happening inside until and unless they click the link.
 
#### A menu item

![image](https://user-images.githubusercontent.com/2246121/213620125-7d2f64e4-4598-4800-9b21-1f8021c0d214.png)

### A menu section

<img width="802" alt="Screenshot 2023-01-19 at 9 12 23 PM" src="https://user-images.githubusercontent.com/2246121/213622094-593c5fe4-d784-404c-8ea9-d32f38f3c82b.png">

### Nested views

<img width="828" alt="Screenshot 2023-01-19 at 9 19 34 PM" src="https://user-images.githubusercontent.com/2246121/213622917-b64e1c71-5697-4948-98a4-9aaaac1033e0.png">

The complete sidebar would look like the following: 
<img width="313" alt="Screenshot 2023-01-19 at 9 22 49 PM" src="https://user-images.githubusercontent.com/2246121/213623330-442da783-0c77-4bc0-97b3-17f81fcd7cc9.png">

**Challenges/To be discussed:**

- Rework the custom view backend so that we can find out if a conversation matches a particular view (sort of reverse query, find all the custom views that a conversation has matches)
- Permissions on the view. 
  - Can an admin create a view for all the agents?
  - Can agents create private views?
  - How can we ensure that the agents have access to the inbox/team when they create a view?
- Can there be some standard views that cannot be removed? (Mine/Unattended/Mentions etc)
  

<sub>[CW-1436](https://linear.app/chatwoot/issue/CW-1436/prioritizing-the-conversations-custom-views-and-redesigning-the)</sub>

**Comment by tejaswinichile** [comment]
Backend Findings: 

- Save custom views with ActiveRecord migration custom_views
- We can update the views whenever we have a new record
- dispatch to update the conversation count and records. - this will take more cycles

If not using DB views

- Whenever the record is updated, we dispatch the event for counts[All, unassigned, mine] - similarly, we do this for the filter sidebar
- For views, we update the count only when the views have been clicked or the request came from the `/custom_views`


I tried to find something query-based to determine whether the conversation was part of the filter, but I could not.

**Comment by scmmishra** [comment]
@tejaswinichile I can pick this up with you, we can pair on this. 

@pranavrajs what would be the priority of this?

**Comment by pranavrajs** [comment]
I was thinking of getting this prioritized in the next or next to next sprints along with the [CW-1469](https://linear.app/chatwoot/issue/CW-1469/notifications-upgrade)
