### ISSUE TITLE
Help center articles should be shown by last_edited first.

### ISSUE THREAD

**Issue by fayazara** [chatwoot/chatwoot#6312]
**Is your enhancement request related to a problem? Please describe.**
Help center articles currently are displayed in an in order - First created article, instead it should be either sorted by Last edited or Last created. 

<img width="1440" alt="Screenshot2023-01-20 at 13 18 32@2x" src="https://user-images.githubusercontent.com/15716057/213643832-af47c7fe-cec4-4d4c-9c05-95672534c185.png">

**Describe the solution you'd like**
Sort them by last created or last edited, or have a sort option on the table header to do this.

**Comment by fayazara** [comment]
Note: The endpoint `/<PORTAL>/articles` does not support this yet

**Comment by imskr** [comment]
@fayazara I've created the PR for this feature :)

**Comment by fayazara** [comment]
> @fayazara I've created the PR for this feature :)

Thank for the contribution @imskr, let me take a look at this.

**Comment by imskr** [comment]
Thanks @fayazara
