### ISSUE TITLE
Access token should be hidden/masked by default

### ISSUE THREAD

**Issue by iprithvitharun** [chatwoot/chatwoot#6322]
When working in a collaborative environment or screen sharing unmasked values creates panic and makes it harder to work.

### Expected behavior

Use a show/hide icon to show the access token in plain text. 

<img width="951" alt="Screenshot 2023-01-21 at 11 14 57 PM" src="https://user-images.githubusercontent.com/58725708/213880157-ee371a35-5029-4139-90df-057c061b4e41.png">

**Comment by raph941** [comment]
My assumption is that the feature to hide/mask access tokens by default should be applied consistently across all instances of access token usage. I just wanted to confirm with you, @sojan-official, if this is correct. For example, this would also include the super administrator's access token page in addition to the use case displayed above.

<img width="1220" alt="Screenshot 2023-02-10 at 11 14 53 AM" src="https://user-images.githubusercontent.com/45232708/218067103-de68b558-b1b0-4581-a626-fbd8b259aee0.png">

Additionally, I think the `Account ID` might also be considered sensitive, do you think this feature is also useful for it?

<img width="973" alt="Screenshot 2023-02-10 at 11 28 44 AM" src="https://user-images.githubusercontent.com/45232708/218069242-1e35d081-533a-48ff-bacf-d8c63108327d.png">

cc: @iprithvitharun

**Comment by scmmishra** [comment]
> My assumption is that the feature to hide/mask access tokens by default should be applied consistently across all instances of access token usage.

@raph941 yes that would be the intended behaviour

**Comment by raph941** [comment]
Great, thanks for clarifying @scmmishra.

**Comment by nithindavid** [comment]
@iprithvitharun Thanks for these great improvements 🔥
