### ISSUE TITLE
[CW-39] Ability to update CSAT over Message API for Inbox with channel type API

### ISSUE THREAD

**Issue by CristianDuta** [chatwoot/chatwoot#6328]
**Is your enhancement request related to a problem? Please describe.**
Currently it is not possible for contacts to answer to the CSAT message.

**Describe the solution you'd like**
1. I'd like to be able to update the CSAT message over the Message API. For example:
```
      patch "/public/api/v1/inboxes/#{api_channel.identifier}/contacts/#{contact_inbox.source_id}/conversations/" \
                  "#{conversation.display_id}/messages/#{message.id}",
            params: { submitted_values: { csat_survey_response: { rating: 4, feedback_message: 'amazing experience' } } },
            as: :json
```

2. I would also expose the conversation uuid, for future use in the undocumented API endpoint `/public/api/v1/csat_survey/#{conversation.uuid}`. 
3. I would also document this hidden endpoint `/public/api/v1/csat_survey/#{conversation.uuid}`.
4. I would still enforce the rule that CSAT messages can't be updated after 14 days.

**Describe alternatives you've considered**
I tried using an undocumented endpoint but that requires the conversation UUID, which is not exposed with the conversation object.

**Additional context**
I'm trying to build an UI on top of an Inbox with channel type API.

<sub>[CW-39](https://linear.app/chatwoot/issue/CW-39/ability-to-update-csat-over-message-api-for-inbox-with-channel-type)</sub>

**Comment by rogeriorizzo** [comment]
mine also does not send, for api type channel, I believed that there could be a problem, but from what you reported, by default it does not send at all, right?

**Comment by sojan-official** [comment]
@CristianDuta, we will have the uuid exposed in the conversations API

**Comment by CristianDuta** [comment]
@sojan-official would it not be better to update the current messages endpoint to allow updating the csat survey ?
Since the `/public/api/v1/csat_survey` endpoint was never documented, we could get away with removing it altogether.
What do you think?

**Comment by sojan-official** [comment]
@CristianDuta  We could have both the options. The public endpoint could be used by customer facing clients to update the survey. At the same time, the message endpoint can be used by integrations syncing data from other sources, depending on the use case. 

I see that you have raised a PR for the same ❤️  . Will review and get it merged once its ready.

**Comment by CristianDuta** [comment]
Hey @sojan-official Thank you so much for taking care of this. I've been extremely busy over the last few weeks and was planning to take care of this next week. Cheers for being proactive and merging this even if it still had an issue. 🚀

**Comment by sojan-official** [comment]
@CristianDuta, no worries :D looked like a low-hanging fruit. Thanks again for the changes.

**Comment by tejaswinichile** [comment]
@sojan-official Can you add the information on this and related PR if you can find it?

**Comment by sojan-official** [comment]
Remaining Tasks

* Expose conversation uuid in application & public APIs


* update api documentation 

other changes are covered over [https://github.com/chatwoot/chatwoot/pull/6470](https://github.com/chatwoot/chatwoot/pull/6470)
