### ISSUE TITLE
Ability to close conversations from an Inbox with channel type API

### ISSUE THREAD

**Issue by CristianDuta** [chatwoot/chatwoot#6329]
**Is your enhancement request related to a problem? Please describe.**
Currently, you can't close the conversation from the side of the contact, for an Inbox with channel type API. The endpoint is simply not there and I assume this was never something the API channel allowed.

**Describe the solution you'd like**
Similar to the website widget, I'd like:
1. A feature flag on the API channel which allows of blocks requests to close the conversation if this is not allowed.
2. New endpoint, for the Inbox with channel type API, where you can update the conversation and set the status to 'Resolved'.

**Describe alternatives you've considered**
I have tried to do this using a technical user over an external API which had other means of authenticating the contacts. It works but I'd rather not have this complex setup.

**Additional context**
I'm trying to build a UI on top of the Inbox with channel type API.

**Comment by tejaswinichile** [comment]
@CristianDuta We will have discussion over this of we want this feature to be included.

**Comment by pranavrajs** [comment]
@CristianDuta Can you please share if the toggle status API doesn't work here? https://www.chatwoot.com/developers/api/#tag/Conversations/operation/toggle-status-of-a-conversation

**Comment by CristianDuta** [comment]
@pranavrajs This has nothing to do what the chatwoot API but rather the Channel API:
https://www.chatwoot.com/developers/api/#tag/Conversations-API
