### ISSUE TITLE
Inboxes disappear after upgrade to 2.13.0

### ISSUE THREAD

**Issue by luizeof** [chatwoot/chatwoot#6332]
**Describe the bug**

All Inboxes disappear after upgrade to 2.13.0

**To Reproduce**

1. Upgrade to latest docker version
2. Login to chatwoot
3. No previously configured inbox is there

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - Browser [e.g. stock browser, firefox, safari]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [x] DigitalOcean
- [ ] Others

**Additional context**

**Comment by pranavrajs** [comment]
@luizeof 

1. Is there any logs you can share? There needs to be more information to debug this.
2. Did you run the DB migrations after upgrading the server?

**Comment by neliocaa** [comment]
@luizeof docker-compose run --rm rails bundle exec rails db:chatwoot_prepare

it worked perfectly here

**Comment by pranavrajs** [comment]
Closing this here as the issue would generally be related to missing migration. Please feel free to reopen if it is not the case.
