### ISSUE TITLE
Chatwoot does not receive replies from user messages on WhatsApp Cloud And Telegram

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6333]
If user reply a message in your whatsapp or telegram application, the mentioned message does not appear in chatwoot.

https://user-images.githubusercontent.com/4209678/213957690-673d8bbd-9246-4254-8d3f-acfdb69fdf98.PNG
![image](https://user-images.githubusercontent.com/4209678/214142802-36c38c71-4aaa-4639-b33d-e2f1f9577272.png)
![image](https://user-images.githubusercontent.com/4209678/214142819-b0aa19d1-063f-42bf-94b4-152e7f38725d.png)

**Comment by clanto007** [comment]
I have Self-Hosted Linux VM, here the log of the problem with Telegram.

When I send a normal messagge here the log:
Feb 17 23:41:52 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:41:52.224456 #9789]  INFO -- : RoomChannel#update_presence
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.524436 #9789]  INFO -- : source=rack-timeout id=c86ab779-8a93-4681-a16f-cd0cf6419eb0 timeout=15000ms state=ready
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.525806 #9789]  INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Started POST "/webhooks/telegram/1503268451:AAHsfenHM2c7qPkVsw78YucUS5zhELVJIuI" for X.X.X.X at 2023-02-17 23:42:00 +0000
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.528570 #9789]  INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Processing by Webhooks::TelegramController#process_payload as HTML
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.528658 #9789]  INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0]   Parameters: {"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"name", "last_name"=>"surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "bot_token"=>"[FILTERED]", "telegram"=>{"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}}}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.529959 #9789]  INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] [ActiveJob] Enqueued Webhooks::TelegramEventsJob (Job ID: e4740b2b-35ee-432f-bec8-2f276f503124) to Sidekiq(default) with arguments: {"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "controller"=>"webhooks/telegram", "action"=>"process_payload", "bot_token"=>"1503268451:AAHsfenHM2c7qPkVsw78YucUS5zhELVJIuI", "telegram"=>{"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}}}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.530170 #9789]  INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 655)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.530383 #9789]  INFO -- : source=rack-timeout id=c86ab779-8a93-4681-a16f-cd0cf6419eb0 timeout=15000ms service=6ms state=completed
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.789427 #9789]  INFO -- : source=rack-timeout id=dc484b43-d351-4d1f-8c8e-b1975d68a8f9 timeout=15000ms state=ready
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.790048 #9789]  INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Started POST "/api/v1/accounts/1/conversations/1/update_last_seen" for X.X.X.X at 2023-02-17 23:42:00 +0000
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.792374 #9789]  INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.792424 #9789]  INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9]   Parameters: {"account_id"=>"1", "id"=>"1"}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.851681 #9789]  INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9]   Rendered api/v1/accounts/conversations/update_last_seen.json.jbuilder (Duration: 26.7ms | Allocations: 8840)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.852914 #9789]  INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Completed 200 OK in 60ms (Views: 22.4ms | ActiveRecord: 29.8ms | Allocations: 13249)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.853557 #9789]  INFO -- : source=rack-timeout id=dc484b43-d351-4d1f-8c8e-b1975d68a8f9 timeout=15000ms service=64ms state=completed


When I reply to a message here the log:
Feb 17 23:42:12 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:12.237114 #9789]  INFO -- : RoomChannel#update_presence
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.708605 #9789]  INFO -- : source=rack-timeout id=f67d81b6-86ce-4588-8ead-3bbd9b2ee061 timeout=15000ms state=ready
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.708976 #9789]  INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Started POST "/webhooks/telegram/1503268451:AAHsfenHM2c7qPkVsw78YucUS5zhELVJIuI" for X.X.X.X at 2023-02-17 23:42:28 +0000
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.711472 #9789]  INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Processing by Webhooks::TelegramController#process_payload as HTML
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.711622 #9789]  INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061]   Parameters: {"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}, "bot_token"=>"[FILTERED]", "telegram"=>{"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}}}
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713205 #9789]  INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] [ActiveJob] Enqueued Webhooks::TelegramEventsJob (Job ID: 73dd6199-2cc2-42b1-9231-ca4efe0e76c4) to Sidekiq(default) with arguments: {"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}, "controller"=>"webhooks/telegram", "action"=>"process_payload", "bot_token"=>"1503268451:AAHsfenHM2c7qPkVsw78YucUS5zhELVJIuI", "telegram"=>{"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}}}
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713425 #9789]  INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Completed 200 OK in 2ms (ActiveRecord: 0.0ms | Allocations: 909)
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713649 #9789]  INFO -- : source=rack-timeout id=f67d81b6-86ce-4588-8ead-3bbd9b2ee061 timeout=15000ms service=5ms state=completed
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.861242 #9789]  INFO -- : source=rack-timeout id=14a826f7-ea2a-4e7a-a228-21bca40ec8e2 timeout=15000ms state=ready
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.861590 #9789]  INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Started POST "/api/v1/accounts/1/conversations/1/update_last_seen" for X.X.X.X at 2023-02-17 23:42:28 +0000
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.863867 #9789]  INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.863914 #9789]  INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2]   Parameters: {"account_id"=>"1", "id"=>"1"}
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.991508 #9789]  INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2]   Rendered api/v1/accounts/conversations/update_last_seen.json.jbuilder (Duration: 28.5ms | Allocations: 8840)
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.992676 #9789]  INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Completed 200 OK in 129ms (Views: 24.6ms | ActiveRecord: 95.9ms | Allocations: 13565)
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.993281 #9789]  INFO -- : source=rack-timeout id=14a826f7-ea2a-4e7a-a228-21bca40ec8e2 timeout=15000ms service=132ms state=completed
Feb 17 23:42:32 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:32.237578 #9789]  INFO -- : RoomChannel#update_presence

Chatwoot don't know that this is a reply.

**Comment by clanto007** [comment]
I have Self-Hosted Linux VM, here the log of the problem with Telegram.

When I send a normal messagge here the log:
Feb 17 23:41:52 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:41:52.224456 #9789] INFO -- : RoomChannel#update_presence
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.524436 #9789] INFO -- : source=rack-timeout id=c86ab779-8a93-4681-a16f-cd0cf6419eb0 timeout=15000ms state=ready
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.525806 #9789] INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Started POST "/webhooks/telegram/KEY" for X.X.X.X at 2023-02-17 23:42:00 +0000
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.528570 #9789] INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Processing by Webhooks::TelegramController#process_payload as HTML
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.528658 #9789] INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Parameters: {"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"name", "last_name"=>"surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "bot_token"=>"[FILTERED]", "telegram"=>{"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}}}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.529959 #9789] INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] [ActiveJob] Enqueued Webhooks::TelegramEventsJob (Job ID: e4740b2b-35ee-432f-bec8-2f276f503124) to Sidekiq(default) with arguments: {"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "controller"=>"webhooks/telegram", "action"=>"process_payload", "bot_token"=>"KEY", "telegram"=>{"update_id"=>633411745, "message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}}}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.530170 #9789] INFO -- : [c86ab779-8a93-4681-a16f-cd0cf6419eb0] Completed 200 OK in 1ms (ActiveRecord: 0.0ms | Allocations: 655)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.530383 #9789] INFO -- : source=rack-timeout id=c86ab779-8a93-4681-a16f-cd0cf6419eb0 timeout=15000ms service=6ms state=completed
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.789427 #9789] INFO -- : source=rack-timeout id=dc484b43-d351-4d1f-8c8e-b1975d68a8f9 timeout=15000ms state=ready
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.790048 #9789] INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Started POST "/api/v1/accounts/1/conversations/1/update_last_seen" for X.X.X.X at 2023-02-17 23:42:00 +0000
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.792374 #9789] INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.792424 #9789] INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Parameters: {"account_id"=>"1", "id"=>"1"}
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.851681 #9789] INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Rendered api/v1/accounts/conversations/update_last_seen.json.jbuilder (Duration: 26.7ms | Allocations: 8840)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.852914 #9789] INFO -- : [dc484b43-d351-4d1f-8c8e-b1975d68a8f9] Completed 200 OK in 60ms (Views: 22.4ms | ActiveRecord: 29.8ms | Allocations: 13249)
Feb 17 23:42:00 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:00.853557 #9789] INFO -- : source=rack-timeout id=dc484b43-d351-4d1f-8c8e-b1975d68a8f9 timeout=15000ms service=64ms state=completed

When I reply to a message here the log:
Feb 17 23:42:12 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:12.237114 #9789] INFO -- : RoomChannel#update_presence
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.708605 #9789] INFO -- : source=rack-timeout id=f67d81b6-86ce-4588-8ead-3bbd9b2ee061 timeout=15000ms state=ready
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.708976 #9789] INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Started POST "/webhooks/telegram/KEY" for X.X.X.X at 2023-02-17 23:42:28 +0000
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.711472 #9789] INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Processing by Webhooks::TelegramController#process_payload as HTML
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.711622 #9789] INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Parameters: {"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}, "bot_token"=>"[FILTERED]", "telegram"=>{"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}}}
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713205 #9789] INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] [ActiveJob] Enqueued Webhooks::TelegramEventsJob (Job ID: 73dd6199-2cc2-42b1-9231-ca4efe0e76c4) to Sidekiq(default) with arguments: {"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}, "controller"=>"webhooks/telegram", "action"=>"process_payload", "bot_token"=>"KEY", "telegram"=>{"update_id"=>633411746, "message"=>{"message_id"=>13437, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677348, "reply_to_message"=>{"message_id"=>13436, "from"=>{"id"=>153341074, "is_bot"=>false, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "language_code"=>"it"}, "chat"=>{"id"=>153341074, "first_name"=>"Name", "last_name"=>"Surname", "username"=>"Username", "type"=>"private"}, "date"=>1676677320, "text"=>"Message1"}, "text"=>"Reply"}}}
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713425 #9789] INFO -- : [f67d81b6-86ce-4588-8ead-3bbd9b2ee061] Completed 200 OK in 2ms (ActiveRecord: 0.0ms | Allocations: 909)
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.713649 #9789] INFO -- : source=rack-timeout id=f67d81b6-86ce-4588-8ead-3bbd9b2ee061 timeout=15000ms service=5ms state=completed
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.861242 #9789] INFO -- : source=rack-timeout id=14a826f7-ea2a-4e7a-a228-21bca40ec8e2 timeout=15000ms state=ready
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.861590 #9789] INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Started POST "/api/v1/accounts/1/conversations/1/update_last_seen" for X.X.X.X at 2023-02-17 23:42:28 +0000
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.863867 #9789] INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
Feb 17 23:42:28 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.863914 #9789] INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Parameters: {"account_id"=>"1", "id"=>"1"}
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.991508 #9789] INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Rendered api/v1/accounts/conversations/update_last_seen.json.jbuilder (Duration: 28.5ms | Allocations: 8840)
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.992676 #9789] INFO -- : [14a826f7-ea2a-4e7a-a228-21bca40ec8e2] Completed 200 OK in 129ms (Views: 24.6ms | ActiveRecord: 95.9ms | Allocations: 13565)
Feb 17 23:42:29 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:28.993281 #9789] INFO -- : source=rack-timeout id=14a826f7-ea2a-4e7a-a228-21bca40ec8e2 timeout=15000ms service=132ms state=completed
Feb 17 23:42:32 chatwoot chatwoot-web.1[9789]: I, [2023-02-17T23:42:32.237578 #9789] INFO -- : RoomChannel#update_presence

Chatwoot don't know that this is a reply.

**Comment by UsVfxArtia** [comment]
sad, is there any workaround or is it planned to change this in the future?

**Comment by pranavrajs** [comment]
Closing this favour of https://github.com/chatwoot/chatwoot/issues/6740
