### ISSUE TITLE
Azure App Setup not working

### ISSUE THREAD

**Issue by GuiVKDigital** [chatwoot/chatwoot#6336]
I followed this guide: https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup and after adding the variables in .env file, I still don't see microsoft option inside my chatwoot installation. I did restarted chatwoot, the server, even recompiled to see if it worked, but nothing. Any ideas of why the option is not appearing?

**Comment by sojan-official** [comment]
@tejaswinichile  could you help ?

**Comment by tejaswinichile** [comment]
@GuiVKDigital Did you take the latest pull? Because the option is available for everyone.

**Comment by tejaswinichile** [comment]
@GuiVKDigital Could you confirm if it's still the issue for you?

**Comment by tejaswinichile** [comment]
@GuiVKDigital Please reopen the issue if it still case for you.
