### ISSUE TITLE
[CW-1578] feat: Display the message to which customer is responding

### ISSUE THREAD

**Issue by felipemonari** [chatwoot/chatwoot#6339]
When the customer replies to a message on chatwoot, the message is not marked and does not appear

![mensagem](https://user-images.githubusercontent.com/49285301/214313162-4719b904-0bb4-4cdf-bf30-7efbc5cac95c.png)

this is a resource that many people use in a conversation and ends up being necessary on a daily basis

## Notes
Relevant for multiple channels like facebook, Instagram, telegram etc

<sub>[CW-1578](https://linear.app/chatwoot/issue/CW-1578/feat-display-the-message-to-which-customer-is-responding)</sub>

**Comment by grupale** [comment]
+1

**Comment by sojan-official** [comment]
note: To create the product spec / document required APIs and create appropriate sub issues.

**Comment by sojan-official** [comment]
will be covered in https://github.com/chatwoot/chatwoot/pull/8107
