### ISSUE TITLE
web widget - white text color on white background

### ISSUE THREAD

**Issue by jvJens** [chatwoot/chatwoot#6352]
**Describe the bug**

Inside web widget file attachment message, the user can't see any information (text / icon) from agent message. It's white text color on white background, see screenshots. 
it's own attachments are visible

**To Reproduce**

1. Start a conversation
2. sent an attachment as agent
3. check message bubble in web widget

**Expected behavior**

Text and Icon should be visible

**Screenshots**

<img width="400" alt="Bildschirmfoto 2023-01-26 um 11 12 41" src="https://user-images.githubusercontent.com/62691504/214812315-da8a9e02-3804-4383-bc02-84277c489fca.png">

<img width="403" alt="Bildschirmfoto 2023-01-26 um 11 12 55" src="https://user-images.githubusercontent.com/62691504/214812359-363697a8-a56e-4b8a-b28e-67a5908ba8e2.png">

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: MacOS
 - Browser chrome
 - Version 109

**Comment by Artur-Illarionov** [comment]
I also had that issue, thats why we moved to old version

**Comment by fayazara** [comment]
@jvJens We're looking into this issue, will try to reproduce this asap and update.
