### ISSUE TITLE
Can't create Inbox via Azure / Microsoft OAuth

### ISSUE THREAD

**Issue by fealXX** [chatwoot/chatwoot#6353]
**Describe the bug**
After completing the Azure App setup according to the docs, then creating a new inbox & following the OAuth flow, I just get redirected to the frontpage of my chatwoot-instance, but no inbox is created.

**To Reproduce**

Unclear, need help to further investigate the source of the issue.

**Expected behavior**

Inbox should be created / Browser should show errors.

**Server logs**
```rails_1     | I, [2023-01-27T13:20:03.869717 #1]  INFO -- : [b87a578c-5cb1-462d-a8cc-b55bd302a16f] Started POST "/api/v1/accounts/1/microsoft/authorization" for 185.199.104.14 at 2023-01-27 13:20:03 +0000
rails_1     | I, [2023-01-27T13:20:03.871650 #1]  INFO -- : [b87a578c-5cb1-462d-a8cc-b55bd302a16f] Processing by Api::V1::Accounts::Microsoft::AuthorizationsController#create as JSON
rails_1     | I, [2023-01-27T13:20:03.871703 #1]  INFO -- : [b87a578c-5cb1-462d-a8cc-b55bd302a16f]   Parameters: {"email"=>"hallo@myinstance.de", "account_id"=>"1", "authorization"=>{"email"=>"hallo@myinstance.de"}}
rails_1     | I, [2023-01-27T13:20:03.878440 #1]  INFO -- : [b87a578c-5cb1-462d-a8cc-b55bd302a16f] Completed 200 OK in 7ms (Views: 0.2ms | ActiveRecord: 1.0ms | Allocations: 2378)
...
rails_1     | I, [2023-01-27T13:20:08.508213 #1]  INFO -- : [60bd8940-1e3c-4de8-a303-215dd62a0696] Started GET "/microsoft/callback?code=0.AS8Agi..._0uLZ...&session_state=d0f00dd7-36d7-..." for 185.199.104.14 at 2023-01-27 13:20:08 +0000
rails_1     | I, [2023-01-27T13:20:08.509797 #1]  INFO -- : [60bd8940-1e3c-4de8-a303-215dd62a0696] Processing by Microsoft::CallbacksController#show as HTML
rails_1     | I, [2023-01-27T13:20:08.509862 #1]  INFO -- : [60bd8940-1e3c-4de8-a303-215dd62a0696]   Parameters: {"code"=>"0.AS8Agi..._0uLZ...", "session_state"=>"d0f00dd7-36d7-...."}
rails_1     | OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
rails_1     | E, [2023-01-27T13:20:08.832621 #1] ERROR -- : [60bd8940-1e3c-4de8-a303-215dd62a0696] Couldn't find Account without an ID
rails_1     | I, [2023-01-27T13:20:08.832846 #1]  INFO -- : [60bd8940-1e3c-4de8-a303-215dd62a0696] Redirected to http://chat.myinstance.de/
rails_1     | I, [2023-01-27T13:20:08.833044 #1]  INFO -- : [60bd8940-1e3c-4de8-a303-215dd62a0696] Completed 302 Found in 323ms (ActiveRecord: 0.0ms | Allocations: 4143)
rails_1     | I, [2023-01-27T13:20:08.833604 #1]  INFO -- : source=rack-timeout id=60bd8940-1e3c-4de8-a303-215dd62a0696 timeout=15000ms service=326ms state=completed
rails_1     | I, [2023-01-27T13:20:08.942365 #1]  INFO -- : source=rack-timeout id=5611981d-6034-41f2-8d3b-57be816deee6 timeout=15000ms state=ready
rails_1     | I, [2023-01-27T13:20:08.942780 #1]  INFO -- : [5611981d-6034-41f2-8d3b-57be816deee6] Started GET "/" for 185.199.104.14 at 2023-01-27 13:20:08 +0000
```

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Docker** (If applicable)

Please share the output of the following.
***docker version***
```
Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:22 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:26:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
***docker info***
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)

Server:
 Containers: 6
  Running: 4
  Paused: 0
  Stopped: 2
 Images: 4
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-9-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 62.8GiB
 Name: SENTOU
 ID: IAVX:EIJX:7U2Z:JKOE:UCLW:7NTR:5SSC:KHMF:PG34:Q6M7:XEGU:GR4C
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
***docker-compose version***
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional context**

The account is managed through a third party - godaddy.com - and only the smallest tier (Microsoft 365 Essentials) & I am logged in to multiple accounts in this organisation.

**Comment by fealXX** [comment]
After retrying some times, the error message changed to the following, for no apparent (to me) reasons. 
```
rails_1     | E, [2023-01-27T14:07:48.684746 #1] ERROR -- : [117b403d-0081-49be-af5c-f4d8f7e642db] Validation failed: Name can't be blank, Name should not start or end with symbols, and it should not have < > / \ @ characters.
```

**Comment by tejaswinichile** [comment]
@fealXX Does the email inbox given_name contains any inbox, we create a Microsoft azure inbox with email given_name https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens Could you check step 5 in this document we have missed it before.

**Comment by kry** [comment]
My issue I have with the email service for microsoft here: [https://github.com/chatwoot/chatwoot/issues/5724](url) is the same. I also get the validation failed for the oauth.

OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
E, [2023-01-30T20:32:39.327764 #1] ERROR -- : [29d78f00-5916-49fa-82fd-439d948e09ac] Validation failed: Name can't be blank, Name should not start or end with symbols, and it should not have < > / \ @ characters.

I followed the updated guide to add optional claims as in step 5 here [https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup](url)

**Comment by evolve2k** [comment]
We're getting the same error messages, both showing consecutivley in the logs:
`OAuth2::AccessToken.from_hash: hash contained more than one 'token' key (["access_token", "id_token"]); using "access_token".`
`Validation failed: Name can't be blank, Name should not start or end with symbols, and it should not have < > / \ @ characters.`

Checking the Active Directory, the user clearly has a `Display Name`, `First name` and `Last name`.
Token Configuration double-checked and clearly has a record for `given_name`, enabled.

**Comment by moxvallix** [comment]
My PR listed above fixes the inbox not creating, it does not fix the error: `OAuth2::AccessToken.from_hash: hash contained more than one 'token' key (["access_token", "id_token"]); using "access_token".`

Might be best moved to a separate issue, however, it seems not to be breaking anything afaict.

**Comment by fealXX** [comment]
@tejaswinichile sorry for not getting back to you, somehow I missed the notification - yes the given_name is in the optional claims of the token configuration, but it might be empty as the account is managed by GoDaddy and I cant access or edit them.
