### ISSUE TITLE
[CW-44] Should first_reply_created_at include private note date?

### ISSUE THREAD

**Issue by mnort9** [chatwoot/chatwoot#6354]
When a private note is the first message in a conversation, the created time is used to update the conversation `first_reply_created_at`. Is this by design or should only non-private messages be included?

<sub>[CW-44](https://linear.app/chatwoot/issue/CW-44/should-first-reply-created-at-include-private-note-date)</sub>

**Comment by sojan-official** [comment]
cc: @pranavrajs  thoughts ?
