### ISSUE TITLE
Custom attributes view get messy when including large description text

### ISSUE THREAD

**Issue by luissakihama** [chatwoot/chatwoot#6355]
**Describe the bug**

Custom attributes page get messy when you create a custom attribute with  large description text.

**To Reproduce**

1. Go to Custom Attributes
2. Create a Custom Attribute and write a long text as description, for instance: "this is a long description here. this is a long description here. this is a long description here."
3. Save the attribute and check the page view.

**Screenshots**

<img width="1186" alt="Screen Shot 2023-01-27 at 19 06 49" src="https://user-images.githubusercontent.com/26125876/215228790-c9a8512d-761a-4cb9-8a12-a5b9d119db0d.png">

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ X] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS: MacOS
 - Browser Brave 
 - Version [Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (arm64)](https://brave.com/latest/)

**Comment by muhsin-k** [comment]
@luissakihama Please share your chatwoot version. It is already fixed in `v2.13.0`.
