### ISSUE TITLE
v3 Release

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6366]
Hey folks, 

It has been some time since Chatwoot had a major update. We are planning for an update in March/early April. Here are the main topics we will work on in the next two months. As you can see, it is an extensive list of updates that have been pending for quite some time. We will create individual issues in the coming weeks when we pick them up. Please feel free to tag/comment on the issues you want us to prioritize. 

As always, keep the feedback coming. 👍 

<img width="550" alt="Screenshot 2023-01-31 at 1 04 54 PM" src="https://user-images.githubusercontent.com/2246121/215882868-00084d37-71a2-4c56-a31b-3319997a42f7.png">

**Comment by sanjayws** [comment]
#bots baby #bots

**Comment by movilreup** [comment]
Email channel configuration. The current email channel no easy to configure.

Dasboard customization with each branch example colors on chat bubbles, select own logo on login and inside panel , option to custom css

**Comment by glauberssoutodossantos** [comment]
@pranavrajs take a look to this issuses:

https://github.com/chatwoot/chatwoot/issues/5903
https://github.com/chatwoot/chatwoot/issues/5903

I belive this is a messaging experience for agentes :D

Great job and lets make a great v3 release.

**Comment by balawa** [comment]
Email channel configuration
Once inbound_inbox is setup without SMTP/IMAP, we should have the option to specific if the from_address is based on the @account.support_email or simply @channel.email.

**Comment by clairton** [comment]
voip channel

**Comment by clairton** [comment]
conversation between team, agent to agent

**Comment by udsonassis** [comment]
Agents and teams can see conversations from other teams even if they are not assigned. #6422

https://github.com/chatwoot/chatwoot/issues/6422

**Comment by udsonassis** [comment]
Agents and teams can see conversations from other teams even if they are not assigned. #6422

**Comment by balawa** [comment]
Extend the functionality of facebook/instagram Inbox to reply to comments / messages on posts /advertising.

In order to deliver true omnichannel support, the agents should be able to answer / reply to comment made on posts in a similar manner as we currently have the ability to response on mention in instagram stories.

**Comment by WallacyBR** [comment]
- VOIP Support
- Atendee's name on WhatsApp Channel
- Atendee to atendee chat, like Microsoft Teams
- Restriction to access contacts by privileges

**Comment by hadifarnoud** [comment]
VOIP support would be actually huge. Asterisk via NodeRED integration

**Comment by netizen-id** [comment]
Please add Live Chat widget with help center. Chenge the UI in Live chat widget. I hope 😀

**Comment by KonsoleLabs** [comment]
Wouldn't it be good to give users the option of subscribing to (related) news (newsletters) from a channel for the different inboxes? 
Billing sounds great - but who gets the bill? The users for getting support (or a newsletters) ?

**Comment by grupale** [comment]
Please if it possible, add an "Unread Conversations" filter by Inbox Channel

**Comment by shivamkb17** [comment]
If able to add whatsapp through scan, It will be too helpful, For many website, That are not able to get whatsapp API. 
I know it also increase the load on the server.

**Comment by Ghost108** [comment]
Live chat UX
Mobile app UX
Bots and UX around bots

Thank you very much!

**Comment by Geomiesie** [comment]
@pranavrajs #6394 Would be really helpfull. Also really looking forward to the Shopify integration. And VOIP of course but it's OK to log phonecalls in notes for now as long the show in the sidebar.

**Comment by wokawoka** [comment]
> voip channel

+1

**Comment by lastwall** [comment]
**two suggestions:**
- editing agent messages
- reply with quotes style

**Comment by jcmatoskx** [comment]
> * VOIP Support
+1

**Comment by hadifarnoud** [comment]
VOIP Support can be done with a NodeRED Plugin for Asterisk.

btw do you guys have a deadline/release date for V3?

**Comment by migarol** [comment]
> Please add Live Chat widget with help center. Chenge the UI in Live chat widget. I hope 😀
> 
> ![IMG_20230218_001334](https://user-images.githubusercontent.com/83263168/219706659-7e6ec24c-0941-4dcb-a0c0-d74f6bb73cf5.jpg)

+1

**Comment by adbasanta** [comment]
Suggestion only,
Prevent agents from deleting messages in Whatsapp.
Thank you!

**Comment by SirRodney** [comment]
It would be great to have the Internal Inbox for the team to communicate
#5598 

Thank you

**Comment by hexclann** [comment]
Support for ARM architecture

**Comment by hadifarnoud** [comment]
> Support for ARM architecture
I don't think that's related.

**Comment by Shalashtein** [comment]
Hey, is early April still the planned release date? I'm migrating from intercom and I'm checking if I should wait a couple of weeks before starting to use Chatwoot till the v3 release is ready

**Comment by lauraceciliavp** [comment]
Hi, are you going to launch this early april version? also, #5598 is going into this version?

**Comment by IGNOR90** [comment]
We will be grateful if a function appears: Telegram integration as a separate Telegram client

**Comment by Leandroledledled** [comment]
Is the release out today?

**Comment by LiamAshdown** [comment]
Any updates on this?

**Comment by lastwall** [comment]
OpenAI integration?

**Comment by Noah-Haf** [comment]
Any updates?

**Comment by ivangdavila** [comment]
It would be awesome to be able to set the pannel apps as a split view where you can see at the same time the app and the conversation!

**Comment by pranavrajs** [comment]
Hey folks, 

I want to update you on the progress and the direction forward. 

We started V3 as a step to fix the problems we have identified in Chatwoot and provide a better experience to the users. Some of them were significant changes and included the system's performance, usability issues, permissions hierarchy, etc., hence version 3. 

I sense the disconnect between the community and team members on the v3 update. So, I'd like to add more context to this. Once we started the effort for v3, we identified many avenues where we could improve and possibly be the best solution out there for support. Instead of adding more features to get parity with the competitors (and getting bloated with many features), we figured we could work only on solving the core problem we believe in and solving it better than everyone else. This direction changed the effort we estimated initially and the dates planned for the release. I should have updated it here. Moving off of GitHub for planning the project further escalated this.

So here is the direction we are heading, the changes you can expect going forward.

The core problem we are working on is to make the support accessible to everyone on the team and promote all-hand support. The changes planned revolve around the same concept. In this update, we plan to solve mainly three problems. 

**1/ Help all the employees to become better at communicating with customers and allow the managers/supervisors to provide meaningful feedback to the employees.**

The features planned in this section are as follows:
- Help with AI rephrasing the content and summarizing the conversation. Open AI integration is already shipped, and we are working on improving it further.
- Helping with the quality of the conversation. This feature would give insights to the admins about the tone and efficiency of a conversation, which would allow them to provide feedback to the employees involved, thus further improving the service quality.
- Improve the working as a team, better permissions structure, and custom roles.

**2/ Improve the visibility of what is happening across the conversations.** 

One of the major feedback is that "all conversations" is a static list and doesn't help with prioritizing the conversations. We plan to address this by the following changes: 
- **Implement SLA feature**: The conversations that breach SLA can be prioritized in the views. 
- Create queues based on different parameters to provide a better understanding of the conversations. This involves improving the search experience and the custom view/filter implementation to make it faster and more performant. It also involves a revamp of the sidebar (https://github.com/chatwoot/chatwoot/issues/6309)
- **Better notification inbox**: Right now, the notifications of each user are a long list and are not actionable. A revamp to the existing notification center is being done to improve it.

**3/ Help employees to gather information and share it with the team to improve the product/service.** 

This includes an option to generate the reports dynamically and review the work done in the past week. 


In the next couple of days, I will make the issues public from Linear to gather feedback and give you more context. 

**Timeline:** We expect this to take around one more month to complete. A reasonable expectation would be July 15 as a release date for V3. 

A couple more clarifications: 

- Are we building a separate repo for v3? No, we see v3 as a natural extension of the previous version and an incremental update. Everything will be available in the main repository only.
- Are we making it private? No, as we have done over the years, v3 is also open-source + enterprise edition. While most of the features are open-source, some would be under the enterprise license and require our business license to use it. 
- Are they any breaking changes? We are keeping everything as backward-compatible as possible. However, there might be some changes that will be appropriately communicated.

I hope this brings some clarity here. Let me know if you have further questions.

**Comment by rogeriorizzo** [comment]
@pranavrajs We need a more specific function, which is message responses, as it is not yet supported by chatwoot. I don't know if it will interfere much, but it is a situation that helps us a lot with usability.

**Comment by pranavrajs** [comment]
@rogeriorizzo, If you are talking about https://github.com/chatwoot/chatwoot/issues/6726, yes, we have that covered. It needs a bit of investigation on our end as we need to support it on multiple channels. Not just the WhatsApp one.

**Comment by rolymaz** [comment]
Will v3 include the functionality to run outbound whatsapp campaigns? It would be great if i could import a list of contacts, select a whatsapp templated message (business initiated message) and send it to my list of contacts.

**Comment by pranavrajs** [comment]
> Will v3 include the functionality to run outbound whatsapp campaigns? It would be great if i could import a list of contacts, select a whatsapp templated message (business initiated message) and send it to my list of contacts.

Campaigns are not planned for v3, even though it was in the initial discussion. The scope was too big that we have initially estimated. We will get to it after the release.

**Comment by movilreup** [comment]
Hi ! The email channel if is including on V3 version and hiw this work easy integration to foward emails to the chatwoot portal ? Thanks

**Comment by mani-zur** [comment]
Azure AD User authentication

**Comment by hexclann** [comment]
Support ARM architecture

**Comment by NLSARCOS** [comment]
an internal chat between users is important as they can help users a lot

**Comment by LiamAshdown** [comment]
> an internal chat between users is important as they can help users a lot

I am curious to why you would need this feature? Isn't this where Slack and MS Teams come in to solve that?

**Comment by zmartell** [comment]
Is it still planned to be released tomorrow?

**Comment by pranavrajs** [comment]
@zmartell No, it is delayed by a week. This month's release would 3.0. There are still some rough edges. We are trying to get it as soon as possible. A release candidate rc-1 would be available by July 21st.

**Comment by rogeriorizzo** [comment]
@pranavrajs  in v3, the problem with the whatsapp channel not closing the conversation, when is the ticket closed? currently the single conversation option is not functional. every time a message arrives, it reopens the 1st conversation that was held in that contact.

**Comment by pranavrajs** [comment]
Closing this issue as a stable v3 release will be out today. We will take the individual comments in separate discussions.
