### ISSUE TITLE
Create a conversation button in an inbox.

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#6367]
**Is your enhancement request related to a problem? Please describe.**

We create quite a few outgoing conversations.
Its tedious to always have follow these steps:
1. switch to contacts tab
2. create a contact
3. find the just created contact
4. click the blue button to start a conversation

**Describe the solution you'd like**

It would nice to have a "Create conversation" Button somewhere on the conversations tab.
Where we can search/create contacts and initiate a conversation right there and then.

For new contacts, a name and number/email is all we use.

![image](https://user-images.githubusercontent.com/72418976/215673711-c8b9112c-1e57-449b-90ff-e738f755eb5f.png)

**Describe alternatives you've considered**

The button doesnt have to be where I mentioned. Just need a button to start a new conversation with existing/new contact.

**Comment by vishnu-narayanan** [comment]
@Jatin-MYST Thank you for this feature request. 

cc: @sojan-official @nithindavid

**Comment by vishnu-narayanan** [comment]
Related https://github.com/chatwoot/chatwoot/issues/6542

**Comment by VSinghhh** [comment]
In this ticket it still requires adding an email and name. 
In my ticket ( #6542  ) it would have been desirable to make do with only the email adress (or number)

**Comment by pranavrajs** [comment]
Closing in favour of #6542
