### ISSUE TITLE
Microsoft OAuth / Azure App Questions

### ISSUE THREAD

**Issue by banglashi** [chatwoot/chatwoot#6371]
After following this guide https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup
and discussing the Azure App setup with our IT Contact 2 questions arose that you could perhaps clarify. 

1. Why does the App need to be a multi-tenant app and not single tenant if it only needs access to one account?
2. It says in the documentation that the app needs to be verified by Azure. Does that mean that a Microsoft Partner Network (MPN) is strictly required in order to do so?

Thanks for feedback

**Comment by tejaswinichile** [comment]
1. We support multiple accounts if you are using them just for your self-use. Single tenant also works.
  - This is mostly your call on how you use your chatwoot instance for multiple accounts and how your want to setup your Microsoft account.
  - Multi-tenant works for a single account, and if you want to add multiple accounts, it works well. So we kept it simple.
  - https://learn.microsoft.com/en-us/azure/active-directory/develop/single-and-multi-tenant-apps

2. It says in the documentation that the app needs to be verified by Azure. Does that mean a Microsoft Partner Network (MPN) is strictly required?

- As Microsoft shows in their documentation, the app needs to be verified to have the verified publisher checkbox in your authorization dialogue box
- If you are using this for internal use, and just for a single email account, then it works with the unverified app.
- If you want to keep your account unverified, then please create an account in portal.azure.com with your chatwoot inbox email address itself. Else it won't work as Microsoft don't allow reading from other email address until the app is verified.

Please refer to microsoft document for more details and regulations: https://learn.microsoft.com/en-us/azure/active-directory/develop/publisher-verification-overview

**Comment by banglashi** [comment]
Hi @tejaswinichile 
thank you for the detailed answer and your time. This clarifies all points. And Kudos for the product you are creating!

**Comment by banglashi** [comment]
Hi @tejaswinichile 

Two more questions arose after speaking to the IT Contact:

1. When using single tenant I get following error when trying to authenticate:

```Generic IMAP SMTP OAuth2 application) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.```

Is there a setting I need to change for it to work in single-tenant mode?

2. Could you clarify if you are using the IMAP-Protocol or the Microsoft Graph API? Same goes for SMTP-Protocol or Microsoft Graph API?

Thanks and best regards
