### ISSUE TITLE
Lock threads shouldn't run on forks

### ISSUE THREAD

**Issue by imskr** [chatwoot/chatwoot#6376]
**Is your enhancement request related to a problem? Please describe.**

I'm constantly getting messages Lock Threads: All jobs have failed on my fork repository

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions you've considered.

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by fayazara** [comment]
Hey @imskr are you referring to sidekiq jobs?

cc: @tejaswinichile

**Comment by tejaswinichile** [comment]
@imskr Could you add the logs or screenshot for the same, that would be easy for us to debug.

**Comment by sojan-official** [comment]
@fayazara  @tejaswinichile  I believe it's the GitHub jobs we run over the repo. @vishnu-narayanan  could you see if we can disable them on forks?

**Comment by imskr** [comment]
@sojan-official @vishnu-narayanan I have created a PR to prevent this :)
