### ISSUE TITLE
Unable to re-assign oneself to conversation after unassign

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#638]
**Describe the bug**
An agent is unable to re-assign themselves to a conversation they have un-assigned themselves from.

**To Reproduce**
1. In conversation, click on drop down and select un-assign
2. Click on drop down and agent will not be able to find themselves in the list 

**Expected behavior**
If agent un-assigns themselves, they should be able to see themselves in the dropdown list. Additionally, I can't see any other agents in the drop down but I imagine that is because they are offline.

**Comment by pranavrajs** [comment]
@tabrza I tried to reproduce this, couldn't reproduce this issue. Could you please post a screencast if possible?

**Comment by tabrza** [comment]
@pranavrajs sorry, it's been an absolutely crazy week. Please note the image below - I can't re-assign myself once i have un-assigned myself
![image](https://user-images.githubusercontent.com/21217850/77744721-d5c41400-703b-11ea-89c4-9fc1d67991ff.png)

**Comment by pranavrajs** [comment]
@tabrza Have you verified your account?

**Comment by tabrza** [comment]
i tried using the following but get a nomethod error:
```
u = User.find_by(email: 'youremailaddress')
u.confirm
```

steps taken:
heroku run rails c
u = User.find_by(email: 'youremailaddress')
u.confirm

response:
NoMethodError (undefined method `confirm' for nil:NilClass)

**Comment by sojan-official** [comment]
@tabrza could you see if there is any output when you enter 
```
u = User.find_by(email: 'youremailaddress')
```

alternatively, you can just print the variable `u` after assigning it.  This error basically says that there is no user assigned to the `u` variable.   The other possibility is that you are not using the correct value for  `youremailaddress` .  that value should be replaced by the email address of user you are trying to confirm.

**Comment by tabrza** [comment]
Thanks for getting back to me so quickly @sojan-official ! 
Getting the following response:
```
D, [2020-03-28T14:50:19.911890 #4] DEBUG -- :   User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 LIMIT $2  [["email", "1@2.com"], ["LIMIT", 1]]
=> nil
```

**Comment by tabrza** [comment]
never mind. misspelling in the find. very smart at my end... 
regardless, good to know that unverified users cannot log back in nor have conversations assigned to them. 
have a great weekend @sojan-official
