### ISSUE TITLE
Dyte Integration

### ISSUE THREAD

**Issue by panaras10** [chatwoot/chatwoot#6386]
Is there a documentation for this please? Just adding the credentials doesn't seem to do anything.

**Comment by iamsivin** [comment]
@panaras10 Currently, we don’t have documentation for Dyte integration. You can add the credentials from Dyte to Chatwoot.
**Steps**
1. Go to the Chatwoot dashboard.
2. Open settings and navigate to the applications section.
3. And you can see Dyte there and click configure button and click connect.
4. Add the Organization ID and API key from Dyte and click create.
5. After successful configuration, you can navigate to the conversation view.
6. Open a chat; now, you can see the video call icon in the reply box.

**NB**: Currently, Dyte video call is supported only on Website and API inboxes

CC: @pranavrajs

**Comment by panaras10** [comment]
I have done all this and the icons don't show on the chatbox

**Comment by iamsivin** [comment]
> I have done all this and the icons don't show on the chatbox

Can you share which inbox type are you using? Currently, Dyte video call is supported only on Website and API inboxes

**Comment by panaras10** [comment]
> > I have done all this and the icons don't show on the chatbox
> 
> Can you share which inbox type are you using? Currently, Dyte video call is supported only on Website and API inboxes

It's a website inbox indeed.

**Comment by iamsivin** [comment]
> > > I have done all this and the icons don't show on the chatbox
> > 
> > 
> > Can you share which inbox type are you using? Currently, Dyte video call is supported only on Website and API inboxes
> 
> It's a website inbox indeed.

Is it possible to share a screencast?

**Comment by panaras10** [comment]
<img width="664" alt="Screenshot 2023-02-03 at 10 33 49" src="https://user-images.githubusercontent.com/56270780/216579500-e3740a74-2917-45fc-b467-f8d723738947.png">
<img width="1120" alt="Screenshot 2023-02-03 at 10 33 24" src="https://user-images.githubusercontent.com/56270780/216579542-b6fd3917-a5f4-4d1f-b722-df6cde37e6a8.png">

**Comment by iamsivin** [comment]
Hey @panaras10, you can only initiate the video call from the dashboard. Here is the quick loom video.
https://www.loom.com/share/aea68774a3f142b896ae06d5794cad1d

**Comment by panaras10** [comment]
Thanks - makes sense now

**Comment by iamsivin** [comment]
Closing this issue as it is resolved.
