### ISSUE TITLE
null current_conversation object on webwidget_triggered event

### ISSUE THREAD

**Issue by gavisharora-lexit** [chatwoot/chatwoot#6387]
I'm trying to build a chatbot by utilising chatwoot's webhook events. The issue I'm facing is that, I want to send a message to the user as soon as they open the widget.

This works fine EXCEPT on the very first time the user is using the widget, when a user visiting for the first time opens the widget, I receive a webwidget_triggered event on my backend, however, the current_conversation object is null and hence I dont have the necessary information to send a message to the user using the API channel.

Is there a way around this? A way to create a conversation in such a way that the first message is automated and not from the user?

**Comment by sojan-official** [comment]
@gavisharora-lexit  You can use the conversations API to create a conversation in this case before sending the message

The source id will be available in your event payload. 
```
 post "/api/v1/accounts/#{account.id}/conversations",
               headers: agent.create_new_auth_token,
               params: { source_id: contact_inbox.source_id },
               as: :json
```

**Comment by sojan-official** [comment]
closing as this is not an issue.
