### ISSUE TITLE
CC in email inbox, filled with the old one.

### ISSUE THREAD

**Issue by nannyfarina** [chatwoot/chatwoot#6391]
i found the bug, in email inbox:
1. when we click one of conversation in chat list
2. in Reply, there is CC filled with let say "firstchat@email.com", then we go to Private Note
3. we click another conversation in chat list
4. from Private Note, we go to Reply
5. this is the Bug, cc form was still filled with "firstchat@email.com" not the new one

thanks...

**Comment by pranavrajs** [comment]
Closing this as this is similar to #7010
