### ISSUE TITLE
Problem with displaying 25+ Macros

### ISSUE THREAD

**Issue by GyR4uk** [chatwoot/chatwoot#6410]
Problem with displaying 25+ Macros

API
/api/v1/accounts/2/macros

![image](https://user-images.githubusercontent.com/35705596/217222626-87a421a8-bc54-427a-9093-c6d73b4f5f07.png)

**Comment by tejaswinichile** [comment]
Could you try params for pagination?

<img width="400" alt="Screenshot 2023-02-07 at 4 45 59 PM" src="https://user-images.githubusercontent.com/10827585/217230451-5e76caea-c0ef-4653-a55b-4bbec2bdd1c7.png">

**Comment by GyR4uk** [comment]
True, but there is no pagination on the macros frontend page
