### ISSUE TITLE
[CW-1957] Web app disconnects and doesn't notify about incoming messages anymore

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#6411]
**Describe the bug**

Using https://app.chatwoot.com/app/

**To Reproduce**
No steps, sorry, it happens sometimes while leaving the browser tab open and not visiting it, including after browser restart.

When visiting it, the page renders and there's a Chatwoot message at top-right "Disconnected from Chatwoot" and a link to Refresh.

**Expected behavior**

Instead of showing the "Disconnected" message, auto-refresh / connect again.
If offline after 3 tries, continue trying every 1 minute to connect again.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [x] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)** (If applicable)
 - OS:  Linux
 - Browser Chrome
 - Version 1098

<sub>[CW-1957](https://linear.app/chatwoot/issue/CW-1957/web-app-disconnects-and-doesnt-notify-about-incoming-messages-anymore)</sub>

**Comment by arladmin** [comment]
I keep experiencing this, on both, Chatwoot cloud app as well Self-hosted one.

**Comment by arladmin** [comment]
@pranavrajs
Is there any fix for this, so far?

Without a fix, it actually doesn't make much sense to continue using Chatwoot for various types of inboxes, eg. Whatsapp, Website, and others, where an incoming message is expected to pop-up/create a notification, immediately upon its arrival!

**Comment by tyler-wright** [comment]
Surprised this one is marked as low priority, it actually significantly reduces the usefulness particularly of the mobile app which you would expect to notify you in the background like many other apps when a chat comes through.

**Comment by pranavrajs** [comment]
This configuration would allow you to automatically resolve the conversation after a specific time period. Configure the time frame and personalized message to the user below.

When a disconnect occurs, the web-socket events intended for the UI are discarded and lost.

* Caches are present for Agents, Labels, Inboxes, and Teams. We need to verify whether these caches have been invalidated. If they have, we should use the APIs to refetch the models. This logic already exists in `account.cache_invalidated`.
* For the currently active conversation, fetch the messages were added / updated after the disconnection time.
* Retrieve the conversations that were updated after the disconnection time based on the active filters in the UI.

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
Finding on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)For the conversation list I think we don't have time based

**Comment by iamsivin** [comment]
@pranavrajs 

I had some findings on this issue

> * If the user is on the conversation screens, fetch the latest conversation list based on the filters applied. Check if the conversations API supports the updated attributes (fetch only the conversations that were changed after the disconnected time)

For the conversation list I think we don't support time based fetching. So can we fetch all the conversations with page value 1 when the action cable reconnects? Same for all filters.

> * If a conversation is active, fetch the conversation details and the messages from the time of disconnection. When you are adding the message to the store, check if there are duplicated.

For the active chat screen, Muhsin has worked on it and its live in production [PR](https://github.com/chatwoot/chatwoot/pull/6790) . Fetching of message is working based on the last message ID, which we will save in disconnect and fetch the messages with last message ID when action cable reconnects

> * Fetch the latest notifications.

Where should we the fetch the latest notifications? In the inbox view or the old notification page.

**Comment by iamsivin** [comment]
@sojan-official Here is the PR [https://github.com/chatwoot/chatwoot/pull/9453](https://github.com/chatwoot/chatwoot/pull/9453) . Could you test it out?
