### ISSUE TITLE
[Question] Helm Chart?

### ISSUE THREAD

**Issue by MaheshCasiraghi** [chatwoot/chatwoot#642]
**Is your enhancement request related to a problem? Please describe.**
I have been trying to setup Chatwoot on Kubernetes, but I ran into some problems when translating docker-compose to helm charts. 

**Describe the solution you'd like**
Is there a plan to provide an official helm chart within the main repo?

**Comment by pranavrajs** [comment]
@MaheshCasiraghi This came up in our discussion earlier, we didn't pursue because none asked for it. We will take it up in the next sprints. However, if you think you could contribute this, please feel free to do it.

**Comment by ayushin** [comment]
anybody working on this?

**Comment by Syleron** [comment]
Any update on this?

**Comment by pranavrajs** [comment]
@Syleron @ayushin We will get to this in the next release (v1.13.0)

**Comment by gustavosbarreto** [comment]
Any update on this?

**Comment by sojan-official** [comment]
Work on this is slightly delayed amidst the other higher priority items. If anyone from the community has already put in effort into this, the team will be happy to review and work with them. 

Otherwise, please bear with us for a little bit longer.

**Comment by sojan-official** [comment]
@thundersparkf  Internally this is still in our backlog. I don't know anyone from the community working on this at the moment.

If you are interested, feel free to pick it up.

**Comment by thundersparkf** [comment]
Hey! Yes so I have managed to build a Helm chart but I'm facing an issue. When I deploy the application, it is seemingly skipping the onboarding of the first user. Any reason why that can happen?

**Comment by sojan-official** [comment]
@thundersparkf the onboard step works like this 
- When you run `rake db:chatwoot_prepare` , we create a Redis key `CHATWOOT_INSTALLATION_ONBOARDING` with the value true 
- The application checks for this key on init to decide whether it should redirect users to the onboarding page or whether to the login page 
- This step is done only in environments where the RAILS_ENV value is set as `production`

so a couple of things you can look at 
- whats the value of rails env
- whether you are running the `rake db:chatwoot_prepare` task
- whether the redis instance is the same one against which the task was run

**Comment by pranavrajs** [comment]
@thundersparkf I just created a repo here https://github.com/chatwoot/helm-chart. If you could raise a PR, we can definitely collaborate on the same. :)

**Comment by thundersparkf** [comment]
Wonderful! Thanks @sojan-official and @pranavrajs. I'll try to fix this for a while and the raise a PR there!

**Comment by thundersparkf** [comment]
Hey! I'm a bit new to this. I can't see a clone or a fork button for the helm chart repo. How do I raise a PR?

**Comment by pranavrajs** [comment]
@thundersparkf Sorry about that, the repository was empty. That's why you couldn't fork it. Please check it out now.

**Comment by ayushin** [comment]
We'll be happy to contribute and be an early adopter.

Next step perhaps a terraform module so we can take advantage of managed cloud services, like cloud sql

**Comment by sojan-official** [comment]
@ayushin  Let us know if you need any help from the team.

**Comment by ayushin** [comment]
we are not using chatwoot as of yet, but really considering switching to it, as we've used a few other tools that were not ideal.

helm charts, terraform module and flutter client would definitely get us on board :-)

i'll see if when we can contribute, i'm monitoring these issues and will get in touch as soon as we have resources/ready

**Comment by sojan-official** [comment]
We will track further progress of Helm Charts in https://github.com/chatwoot/helm-chart
