### ISSUE TITLE
Links in Pre-chat Message and Form Fields

### ISSUE THREAD

**Issue by zeitrechnen** [chatwoot/chatwoot#6432]
**Is your feature request related to a problem? Please describe.**
The topic of data protection and GDPR has already been discussed in detail in several tickets, and there are also some suggestions on how the user's consent can be given in the pre-chat form. However, what is still a challenge is that there is no way that I know of to link to a privacy policy page in the pre-chat form. Neither in the pre-chat message nor in the form fields.

I think it would be good if there was the possibility to insert links in the pre-chat message and in the form fields. Apart from that, it is of course much more user-friendly to provide a link.

**Describe the solution you'd like**
I think it would be good if there was the possibility to insert links in the pre-chat message and in the form fields.

**Comment by muhsin-k** [comment]
@zeitrechnen 
Currently, the widget doesn't support for GDPR consent form at the moment. We already have one issue tracking [here](https://github.com/chatwoot/chatwoot/issues/1231).

But you could create a custom attribute (type checkbox) and add it to the pre-chat form. 

**1. Create custom attribute**
![1](https://user-images.githubusercontent.com/12408980/218105255-40c4d0e9-d7d2-42d3-83a1-8b3f454a8cee.png)

**2. Enable pre-chat form** 
![2](https://user-images.githubusercontent.com/12408980/218105276-db4c2559-09e9-4bd7-8a76-c45934c2fdc0.png)


![CleanShot 2023-02-10 at 19 05 47@2x](https://user-images.githubusercontent.com/12408980/218105287-02c05462-fbfa-4e6a-b725-ec666c66b363.png).

If this works, we will add clickable support to the links.

**Comment by zeitrechnen** [comment]
This is exactly what I did. The only missing part is that the link is not clickable at the moment. It would be perfect if you could make this happen!

**Comment by muhsin-k** [comment]
@zeitrechnen Apologies for the delay here. We got many requests for a consent form. The team decided to spec out properly, and we can expect it in the upcoming releases.

**Comment by muhsin-k** [comment]
@zeitrechnen Please check [this](https://github.com/chatwoot/chatwoot/pull/6511) solution worked for the time being.

**Comment by zeitrechnen** [comment]
@muhsin-k, this looks so great! Many thanks! Does this only work for checkbox fields or also for text fields? In some countries, there is the opt-in requirement and in some countries it is sufficient to inform about the data processing.

**Comment by muhsin-k** [comment]
Yes. It works for text fields as well. Also the checkbox is not mandatory.

**Comment by zeitrechnen** [comment]
I love it!
