### ISSUE TITLE
CSAT suddenly stop sending on all accounts 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#6437]

**Comment by ASchneiderBR** [comment]
Hello, have you managed to fix this? Thanks.

**Comment by muhsin-k** [comment]
I'm sorry for the delay here.
@voko3456 @ASchneiderBR  Are you still getting this issue? If yes, what types of channels are you using?

**Comment by ASchneiderBR** [comment]
Hello @muhsin-k. The issue that I am reporting is related to WhatsApp inboxes. When I use WhatsApp inboxes, either directly connected to meta business or through API manual inbox, I do not receive any CSAT or out of office hours alert messages from the purple bot. This problem does not occur with other types of inboxes. I would appreciate your assistance in resolving this issue. Thank you.

**Comment by muhsin-k** [comment]
@ASchneiderBR We have tested CSAT in WhatsApp cloud API, and it working fine. Can you confirm you have enabled CSAT in your inbox settings?
<img width="642" alt="CleanShot 2023-03-20 at 19 40 46@2x" src="https://user-images.githubusercontent.com/12408980/226366153-25e0a55b-94e8-407a-861d-1e0b0b2743c9.png">

**Comment by ASchneiderBR** [comment]
@muhsin-k, this issue is specific to inboxes that rely on WPP-Connect for WhatsApp integration (https://github.com/wppconnect-team/wppconnect-server).

**Comment by tiagocordeiro** [comment]
Same here.

**Comment by ASchneiderBR** [comment]
Hello guys! Any news on this issue? All of my bot messages (out of hour, CSAT, welcome) are being sent anymore... Thanks.

**Comment by sojan-official** [comment]
@ASchneiderBR  are you still facing this issue ?

**Comment by ASchneiderBR** [comment]
Hello @sojan-official. Yes. I actually gave up on Chatwoot, sadly. I was also facing problems with the extra 9 digit WhatsApp numbers from brazil (there are others with the problem as well, even with the issue solved and closed) and duplicated messages using a third party WP server. I appreciate your help and effort and wish all the best for you guys :) Cheers!
