### ISSUE TITLE
postfix inbound email on Conversation Continuity

### ISSUE THREAD

**Issue by lastwall** [chatwoot/chatwoot#6438]
Hi
I've got a problem with the configuration of Conversation Continuity and the document [here ](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity)seems a little confusing

I have a custom SMTP server for sending emails and all outgoing emails are correct and all things work
but I have a problem receiving emails for conversation continuity

MAILER_INBOUND_EMAIL_DOMAIN=support.domain.com
on email when replay to reply+{random}@support.domain.com it says Recipient address rejected: User unknown in local recipient table

MX records are already set and also I've installed postfix on the same machine
Does anyone know what should I do next to fix this?
should I set anything on postfix?

Regards

**Comment by lastwall** [comment]
As I've checked also here: https://github.com/chatwoot/chatwoot/issues/1496
I've set pip on postfix but here is the log:
validate_ruby!': Your Ruby version is 2.7.0, but your Gemfile specified 3.0.4 

even I'm running it on chatwoot user

what is the cause?

**Comment by lastwall** [comment]
Does anyone have any similar experience with this?
Pip postfix not woking
let me know if anyone managed to work this

**Comment by movilreup** [comment]
@lastwall I have the same problem. You get to solved the problem ? You ready solved this problem ?

Thanks because have the same problem.

**Comment by lastwall** [comment]
@movilreup still nothing, tried almost everything but still nothing
update here if you also find anything on this issue

**Comment by mixneko** [comment]
`cwctl --console`
3.1.3 :001 > `Account.find(0).support_email`
=> "chatwoot <chatwoot@chatwoot.com>" 
3.1.3 :002 > `Account.update(id: 1, support_email: "no-reply <no-reply@example.com>")

**Comment by lastwall** [comment]
@mixneko 
the support email is ok on my server
And your postfix configuration is not opening on discord, seems something wrong on discord link

**Comment by mixneko** [comment]
> @mixneko the support email is ok on my server And your postfix configuration is not opening on discord, seems something wrong on discord link

You may need to join the [official Chatwoot Discord](https://discord.gg/chatwoot-647412545203994635) group before being able to access this [link](https://discord.com/channels/647412545203994635/1063240028542742638).

**Comment by lastwall** [comment]
It helped a lot, but still, some problems that finally I managed to fix, anyone else has a problem follow the below tutorial I tried to explain it from scratch:

1- install postfix
`https://my.sitejungle.net/store/web-hosting`
**set the right domain name during the installation wizard ( email domain )**

2-edit **/etc/postfix/main.cf**
only change the below items:
```
smtpd_tls_cert_file = /etc/letsencrypt/live/YOURDOMAIN/fullchain.pem
smtpd_tls_key_file = /etc/letsencrypt/live/YOURDOMAIN/privkey.pem

smtp_tls_CApath=/etc/letsencrypt/live/YOURDOMAIN/
```
and add these at bottom of the file:
`
transport_maps = hash:/etc/postfix/transport
virtual_alias_maps = hash:/etc/postfix/virtual_aliases
`

3- create this file : **/etc/postfix/virtual_aliases** and add the below :
`
@YOUR_DOMAIN   chatwoot@YOUR_DOMAIN
`
4- create this file : **/etc/postfix/transport** and add the below :
`
YOUR_DOMAIN    forward_to_rails:
`

5- run below codes:
`
sudo postmap /etc/postfix/virtual_aliases
sudo postmap /etc/postfix/transport
`

6- add below lines at the end of **/etc/postfix/master.cf**
`
forward_to_rails unix  -       n       n       -       -       pipe
  flags=Xhq user=chatwoot:chatwoot argv=bash /home/chatwoot/chatwoot/bin/import_mail_to_chatwoot
  ${nexthop} ${user}
`

7- Now login with chatwoot user:
`
sudo -i -u chatwoot
`
8- go to chatwoot folder and edit .env file : `nano /home/chatwoot/chatwoot/.env`
Set below items:
`
SMTP_DOMAIN=YOUR_DOMAIN
SMTP_ADDRESS=localhost
SMTP_PORT=25
#SMTP_USERNAME=
#SMTP_PASSWORD=
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=none
MAILER_INBOUND_EMAIL_DOMAIN=YOUR_DOMAIN
RAILS_INBOUND_EMAIL_SERVICE=relay
RAILS_INBOUND_EMAIL_PASSWORD=YOUR_PASSWORD
`

9- now create this file : /home/chatwoot/chatwoot/bin/import_mail_to_chatwoot

`nano /home/chatwoot/chatwoot/bin/import_mail_to_chatwoot`

content:
`
INGRESS_PASSWORD=YOUR_PASSWORD
URL=http://YOUR_CHATWOOT_DOMAIN/rails/action_mailbox/relay/inbound_emails

curl -sS -u "actionmailbox:$INGRESS_PASSWORD" \
 -A "Action Mailbox curl relayer" \
 -H "Content-Type: message/rfc822" \
 --data-binary @- \
 $URL
`

10- Now exit to root again and restart both postfix and chatwoot services.
`
exit
sudo services postfix restart
sudo systemctl restart chatwoot.target
`

Now it should work, and if it's not working you can also check the postfix logs below code to see what is wrong:
`
tail -f /var/log/syslog | grep postfix
`

**Comment by mixneko** [comment]
@lastwall Great! You got it. Can you imagine how excited I was when I found this answer and succeeded at the beginning?

**Comment by vishnu-narayanan** [comment]
@lastwall @mixneko Thank you for the update 🙇‍♂️
