### ISSUE TITLE
Send more than one file in conversation

### ISSUE THREAD

**Issue by jhonyrdesouza** [chatwoot/chatwoot#6453]
**Is your feature request related to a problem? Please describe.**

Chatwoot does not allow the sending of several photos at the same time, I did the test by attaching 4 photos, I received only 1 file. And it is also not possible to delete the photo. :(

**Describe the solution you'd like**

When more than one file is added, all files must be sent.

**Comment by jochenstu** [comment]
See https://github.com/chatwoot/chatwoot/issues/6120

**Comment by jhonyrdesouza** [comment]
Strange @jochenstu, I tried to attach several images and only ONE arrives on the sender side. Could you verify, @jochenstu?

![image](https://user-images.githubusercontent.com/58796224/219240565-73696bc8-41ad-44a7-aeb5-d37b7cb9f7fe.png)


![image](https://user-images.githubusercontent.com/58796224/219240719-165d5867-71df-4776-848c-b622219b6d1b.png)


**To Reproduce:**

- [ ] Attach multiple images to one messages;
- [ ] Send it through the Web Interface;
- [ ] Check on the receiving WA account;


**Environment:**

Chatwoot v2.13.1
Self-hosted.
Windows.

**Comment by jochenstu** [comment]
The PR has not made it into a release yet

**Comment by jhonyrdesouza** [comment]
Thank you very much! Is there any definition of date for the release of the fix?
