### ISSUE TITLE
[CW-1962] Add ticks for send, received, unread and read message, like whatsapp

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#6456]
The ticks like WhatsApp for send, received, unread and read message, to help users verify the status of messages sent, via API.
![WhatsApp Image 2023-02-15 at 10 17 40](https://user-images.githubusercontent.com/88042866/219038083-a2905787-c55e-4100-b877-16cd043d5411.jpeg)

<sub>[CW-1962](https://linear.app/chatwoot/issue/CW-1962/add-ticks-for-send-received-unread-and-read-message-like-whatsapp)</sub>

**Comment by jmelati** [comment]
This is very important for template messages - helps to know if was received and read.

**Comment by sojan-official** [comment]
@jmelati We support it for some of the channels like Whatsapp and web widget. We will be looking for the same in other channels in future

**Comment by jmelati** [comment]
Ok. My suggestion is to create endpoints to do this in api, so we can use in our platforms. Thanks for your answer.

**Comment by HermesMacedo** [comment]
@pranavrajs Hi, any update on this? Has this option already been implemented? at least for whatsapp?

**Comment by pranavrajs** [comment]
Closing this via https://www.chatwoot.com/docs/product/channels/supported-features#outgoing-message-delivery-status
