### ISSUE TITLE
Run javascript code as automation action

### ISSUE THREAD

**Issue by msahinciftci** [chatwoot/chatwoot#6460]
**Is your feature request related to a problem?**
I always think of new possibilities for this great app to make it greater. One of those is running a js code to open a door to a whole new world. By adding this feature, people like us who does not know Ruby to contribute would apply our own solution and do whatever we want.

**Describe the solution you'd like**
A new action option for automation rule to run a javascript code. But we would need some variables like account id, conversation id, inbox id, contact info etc. to pass the info to the receiver.

Is it possible? Thanks in advance and thank you for this amazing app.

**Comment by jochenstu** [comment]
How is this not (more generally) solved by webhooks for you?

**Comment by msahinciftci** [comment]
Because webhooks do not include authentication. Also I don't want to write a webhook receiver every time I need something from a 3rd party service.

**Comment by LeonAlvarez** [comment]
What authentication are you referring to here? IMO webhooks work better as not tied to an specific language

**Comment by msahinciftci** [comment]
JWT authentication but any authentication type is valid for this topic.

**Comment by BabaraBrenes7mc** [comment]
It is technically possible to add a new action option for automation rule to run a JavaScript code and pass variables such as account id, conversation id, inbox id, and contact info to the receiver. However, it would require some development work to implement this feature. It would also be important to consider security and ensure that the JavaScript code being executed does not have any negative impact on the app or user data. Overall, it is an interesting idea, but would require careful consideration and implementation.

**Comment by pranavrajs** [comment]
@msahinciftci Thanks for the suggestion. However, we will not be pursuing this further as webhook as already available. The feature adds additional complexity to the app which doesn't add a big difference in the user experience. The authentication header on webhook will be taken care in this issue. https://github.com/chatwoot/chatwoot/issues/4732. 

Please feel free to share additional thoughts if you have any.
