### ISSUE TITLE
Instagram mention story

### ISSUE THREAD

**Issue by julioarmenta10** [chatwoot/chatwoot#6473]
Hello, good afternoon, I am trying to get the instagram_manage_messages permission but it has been rejected several times, I think I know why and it is because of the following, in an instagram conversation when the mention of the story arrives, it appears as follows:

![image](https://user-images.githubusercontent.com/45075611/219487831-d68b7fe4-11b4-4be7-9d66-6b2e32f4a142.png)

Once I update the page, the image is already visible, but if I have the conversation open, it looks like that,
I don't know if you can help me with this, thank you very much

**Comment by manovasanth-b** [comment]
can I take and fix this issue ?

**Comment by matiasperes** [comment]
@manovasanth-b Hello, could you fix it?

**Comment by matiasperes** [comment]
@julioarmenta10 Hello, did you manage to get the app approved?

**Comment by shivamkb17** [comment]
Is there any solution regarding this issue?

**Comment by pranavrajs** [comment]
@tejaswinichile Is it still an issue? Didn't we fix this in the recent releases?

**Comment by matiasperes** [comment]
@pranavrajs Yes, this is still an issue. I could not get the app approved because of this.

**Comment by ouzbalkn** [comment]
any of you approved yet?

**Comment by pranavrajs** [comment]
> @pranavrajs Yes, this is still an issue. I could not get the app approved because of this.
@matiasperes Are you on 2.17.1 ?

**Comment by matiasperes** [comment]
@pranavrajs I am on 2.14.0

**Comment by shivamkb17** [comment]
> > @pranavrajs Yes, this is still an issue. I could not get the app approved because of this.
> 
> @matiasperes Are you on 2.17.1 ?

Also I checked it again on 2.17.1, Same issue is still showing.

**Comment by pranavrajs** [comment]
This is resolved in the latest releases. Please update to 2.18.
