### ISSUE TITLE
Missing WhatsApp Template after 2.14.0 update

### ISSUE THREAD

**Issue by adbasanta** [chatwoot/chatwoot#6488]
Hi to all.
Does anyone have experienced the same issue?
A WhatsApp template does not appear in version 2.14.0 but was visible in version 2.13.1.
It seems that Chatwoot is not picking up the templates under "**Utility**" Category in version 2.14.0.

This is the missing template.
![WhatsApp Template](https://user-images.githubusercontent.com/89345000/219932152-737dafa9-a1c7-4a0a-8d16-f9916b86c894.PNG)

**Comment by muhsin-k** [comment]
@adbasanta Sorry to hear that. We couldnt be able to reproduce this issue from our side. The templates are loading correctly.

**Comment by sojan-official** [comment]
@adbasanta  the recent version of Chatwoot will only show the supported templates under the section. ie the ones with  ['DOCUMENT', 'IMAGE', 'VIDEO'] components will be ignored. please check if that's the case. 

ref: https://github.com/chatwoot/chatwoot/pull/6331

**Comment by adbasanta** [comment]
@sojan-official thank you for pointing this out. It turns out that the template has a document header. Thank you!
