### ISSUE TITLE
Fix "SpaceBeforeBrace" issue in app/javascript/src/assets/scss/widgets/_billing.scss

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#65]
Opening curly brace `{` should be preceded by one space

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/assets/scss/widgets/_billing.scss#issue_5d87481187cf190001000647

**Comment by kirillarutyunov** [comment]
I will do it 🧐
