### ISSUE TITLE
NoMethodError (undefined method `selected_email_flags=' for #<NotificationSetting:0x00005600229eb1c8>

### ISSUE THREAD

**Issue by thg303** [chatwoot/chatwoot#654]
**Describe the bug**
it's not possible to create an agent.

**To Reproduce**
0. drop and recreate the database, run migrations and seed the database.
1. Login to the panel using "john@acme.inc" and "123456"
2. Click on 'settings'
3. Click on 'Add Agent'
3. Fill the form with valid information, Agent Name: "Jiim", email: "jim.johnson@gmail.com", Agent Type: "Administrator"
4. See the error "could not connect to Woot server, please try again later"

**Expected behavior**
the agent should be created, without any error.

**Screenshots**
[https://pasteboard.co/J1llHQR.png](https://pasteboard.co/J1llHQR.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X Catlina
 - Browser chrome
 - Version 80.0.3987.149

**Additional context**
as the log file of the server shows:
NoMethodError (undefined method `selected_email_flags=' for #<NotificationSetting:0x00005600229eb1c8>
app/models/user.rb:106:in `create_notification_setting'
[9ec1a6a1-8eb4-4690-b139-5f3d34b24905] app/controllers/api/v1/agents_controller.rb:21:in `create'
[9ec1a6a1-8eb4-4690-b139-5f3d34b24905] app/controllers/application_controller.rb:21:in `handle_with_exception'

**Comment by thg303** [comment]
btw, I faced this on "Master" branch as well as "v1.2.4" release tag

**Comment by sojan-official** [comment]
@thg303  do either `rake schema:load` or `rake db:setup` instead of running all the migrations, then do the seeding. Since the old part of the codebase is still in. some of the migrations are out of sync. 

Also, it's advisable to set up a database using `rake schema:load` or `rake db:setup`  at the setup than running all the migrations 😄  . Let us know if you still face any issues.

**Comment by thg303** [comment]
thank you @sojan-official it worked.
