### ISSUE TITLE
Webhook message_created doesnt work

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#6544]
Hi all!

is it possible, that the webhook message_created doesnt work any more (2.14.0)?
My system gets webhooks for conversation_created, conversation_updated, message_updated, ...) but now webhook for message_created.

<img width="527" alt="Bildschirm­foto 2023-02-25 um 14 55 15" src="https://user-images.githubusercontent.com/17011498/221360781-f185c712-0fae-4abe-9d88-881f6d937f06.png">

**Comment by Ghost108** [comment]
no log for message.webhook_sendable in my rail console.
But I found this error messages:

![Bildschirm­foto 2023-02-27 um 12 14 12](https://user-images.githubusercontent.com/17011498/221549528-e239fa36-bd2a-4217-ab10-9db7f13803b0.png)

**Comment by Ghost108** [comment]
And this hint was important!
I found the mistake - my docker container "watchtower" updates automatically the chatwoot containers.

But I have to update manually the database with:

`docker exec -it rails sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'`

Is there an way that watchtower can handle this also automatically or should I disable automatically updates with watchtower?

**Comment by sojan-official** [comment]
@Ghost108  not super familiar with watchtower. but you should be able to hook the command for db:migrate on lifecycle events post the image update. 

https://containrrr.dev/watchtower/lifecycle-hooks/
