### ISSUE TITLE
First Response Time

### ISSUE THREAD

**Issue by parastoo-zakeri** [chatwoot/chatwoot#6548]
Hello, have a good time I am currently using Chatwoot in my call center, but I have some problems that I would be grateful if you could check and tell me the reason. One is about the First Response Time, the average time it shows is very high if my experts respond very quickly. And the second thing is that a series of unread chats are not displayed and my psychologists constantly have to refresh so that the chats are clear. Thank you for giving me a solution to solve these problems.
Currently, in chat reports, it shows me the first response time of about 3 hours, if the response time of our experts is much shorter than this value, but I want to know what is the cause of this problem? And the next thing is that our inbox is a series of The messages sent by the customer are not displayed, and when my experts see that the messages have gone to zero, they refresh, a series of messages are displayed, for example, for the past 1 hour or half an hour, and I think that this is one of the reasons for the long response time.
I would like to thank you if the case of this slowness is investigated and a solution is provided
And also if it is possible, the customer's messages will not reach us with a delay and will be shown quickly and without the need of constant refreshing in our inbox.

**Comment by tejaswinichile** [comment]
@parastoo-zakeri 

Is this a self-hosted installation?

If yes..

First Response Time: Is calculated with business hours, so you should check the set business hours for your account.

Unattended chats are not working for you, and if you have received messages on some other platform. it takes time to send a webhook to send it to chatwoot.

**Comment by parastoo-zakeri** [comment]
Thank you for your reply
I checked the settings and in the working hours part, the settings were 7 days a week, 24 hours a day, so is that the problem? I deactivated it, does that mean it will be OK from now on? @tejaswinichile

**Comment by tejaswinichile** [comment]
Yes, disabling it or adding more accurate business time would help.

This is how we calculate:

It's the average of all the conversation's first response_time in the account:

ReportingEvent.value = (First human outgoing message created - Conversation created) 
It will create a ReportEvent record for every conversation and 

For average: we take grouped values with a given period. And if business_hours present, we take the business_hours average.
If business_hours is not present, we take the average of ReportingEvent.value

**Comment by parastoo-zakeri** [comment]
Thank you very much for your explanation
One thing only, for example, if the customer starts a conversation and closes the conversation and exits before the operator answers, will the time of this conversation be calculated in the first response?  @tejaswinichile

**Comment by tejaswinichile** [comment]
@parastoo-zakeri If a bot reply is available, it will consider that; if not, it will 0. Which means we will not consider that.

If you are satisfied with the answers please feel free to close the issue.
