### ISSUE TITLE
[CW-43] CSAT not working on 360 dialog

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#6553]
CSAT not working on 360 dialog

<sub>[CW-43](https://linear.app/chatwoot/issue/CW-43/csat-not-working-on-360-dialog)</sub>

**Comment by muhsin-k** [comment]
@voko3456 We are closing this issue since we already discussed it in discord. Please don't hesitate to reopen this if it still needs to be addressed.
