### ISSUE TITLE
set avatar for agent bot

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#6555]
Hi!

I would like to set an avatar for my agent bot:
![Bildschirm­foto 2023-02-27 um 13 48 24](https://user-images.githubusercontent.com/17011498/221568167-625e5c96-4bc4-40c6-b000-639f83858af2.png)

Can anyone explain how?

I am using the docker version 2.14.0

**Comment by pranavrajs** [comment]
Duplicate #5948
