### ISSUE TITLE
[CW-5] Followup from Search Improvements

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#6583]
### Issues with the UI

* Going back to the search screen shows the last search result (we don't need to persist that as it feels like a bug)
* Highlight the search term in the results.
* Message overflow ![image](https://user-images.githubusercontent.com/2246121/224106384-4d9771bc-d590-464b-8d7e-473cea9b6315.png)
* Email rendering issues:  ![image](https://user-images.githubusercontent.com/2246121/224106488-7e1637b3-4e61-44d7-a08d-c49b54efb223.png)
* Back button navigates to the dashboard. It should ideally take me to the previous page (if it was an open conversation, go back to that)
* Move the search to the sidebar, as it is a universal search now. It doesn't need to be in the search page only.

### Order of search results

* Order the messages by the latest message first and oldest message at the end. Now it is shown in the reverse order. The oldest one is shown at the top.
* Order the contacts by last activity. The most recent contact with activity would get the preference and should be shown at the top.
* Order the conversations by created time in descending order.

### Other backend changes

* If possible, let us remove unidentified contacts from the results. (Also the lesser number of contacts to search from). Showing the results as withered-violet-23 doesn't make much sense.

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-5](https://linear.app/chatwoot/issue/CW-5/followup-from-search-improvements)</sub>

**Comment by nithindavid** [comment]
I'll prioritise the UI issues for today and tomorrow

**Comment by sojan-official** [comment]
@nithindavid  it would be super helpful if we could isolate each API calls so that we can optimise the performance for each query separately.

**Comment by pranavrajs** [comment]
@nithin @scmmishra Please prioritize fixing the design.

**Comment by scmmishra** [comment]
@pranavrajs noted

**Comment by scmmishra** [comment]
Nopes, not started
