### ISSUE TITLE
Update an Heroku chatwoot instance?

### ISSUE THREAD

**Issue by weblle** [chatwoot/chatwoot#660]
**Is your feature request related to a problem? Please describe.**
My chatwoot instance is setup with heroku. When a new release is made, it would be nice to be able to update the heroku instance as well. I'm not sure how to go about this. 

**Describe the solution you'd like**
A documentation of how to go ahead with the update process

**Describe alternatives you've considered**
None, as i don't want to break anything

**Additional context**

**Comment by pranavrajs** [comment]
@weblle We will add documentation on deployment to Heroku and monthly updates in the following week.

**Comment by sojan-official** [comment]
documentation to update Heroku instances  is now available here: https://www.chatwoot.com/docs/deployment/deploy-chatwoot-with-heroku

we have also added the release step so that heroku handles the `db:migration` automatically.
