### ISSUE TITLE
Hide widget welcome message for 24 hours after the close button clicked.

### ISSUE THREAD

**Issue by mxsxs2** [chatwoot/chatwoot#6600]
**Is your enhancement request related to a problem? Please describe.**
When a user visits a page with an active Chatwoot widget then the user will see a welcome popup. The user can close this popup. However, when the user reloads this page then the popup will come up again. 

**Describe the solution you'd like**
I would like the popup to stay hidden for a certain amount of time (maybe 24h) when the welcome message close button is clicked.  Maybe a cookie that lives for 24H could work here.

**Additional context**
The button that says _Schließen_
![image](https://user-images.githubusercontent.com/13612429/222417028-c88e19cf-57c8-4fd2-88a0-8b67d62ea2cc.png)

**Comment by pranavrajs** [comment]
Duplicate #3363
