### ISSUE TITLE
Instagram channel don´t delete messages from Chatwoot

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#6601]
**Describe the bug**

When you delete (unsend) a message in instagram, the chatwoot chat writes "MESSAGE WAS DELETED". It´s fine. But if in Chatwoot channel you delete a message, nothing happend in instagram. 
**To Reproduce**

1. Send a message from Chatwoot to Instagram
2. Click on DELETE - in message from Chatwoot
3. In the Chatwoot chat appears "MESSAGE WAS DELETED", it´s ok.
4. In the Instagram, nothing heappens.

**Expected behavior**

When you delete a message in Chatwoot chat this message have to disappear in Instagram.

**Screenshots**

https://www.loom.com/share/f87530625eb24a98a21ec0ec0f09eb6b

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ X ] Self-hosted
- - [ X ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)**
 - OS: Windows
 - Chrome
 - Versão 110.0.5481.178 (Versão oficial) 64 bits

**Comment by tejaswinichile** [comment]
@jmelati We don't have a delete message API event configured for Facebook Channel in our system.
This is an enhancement, we would consider in the next release.

**Comment by tejaswinichile** [comment]
@jmelati Sorry, but the Facebook messenger platform does not have an API endpoint to delete messages.
Until and unless that is available, we can not send any requests to perform delete or update operations.

For more details, please check the Facebook Graph API  document https://developers.facebook.com/docs/graph-api/reference/v13.0/message
