### ISSUE TITLE
[CW-30] Emails not routed based on x-original-to

### ISSUE THREAD

**Issue by singpolyma** [chatwoot/chatwoot#6608]
**Describe the bug**

Sometimes an email comes in for an email address but it is not reflected in the to or cc headers, this is the envelope to and happens with bcc or certain other forwarding patterns.  Mailservers can easily be configured to add this to x-original-to header, which actionmailbox knows how to read, but chatwoot currently ignores.

Here is an example patch to fix:

```
diff --git a/app/finders/email_channel_finder.rb b/app/finders/email_channel_finder.rb
index 1c8eaeaf..d39452dc 100644
--- a/app/finders/email_channel_finder.rb
+++ b/app/finders/email_channel_finder.rb
@@ -5,7 +5,7 @@ class EmailChannelFinder
 
   def perform
     channel = nil
-    recipient_mails = @email_object.to.to_a + @email_object.cc.to_a
+    recipient_mails = @email_object.recipients_addresses.to_a.map(&:to_s)
     recipient_mails.each do |email|
       channel = Channel::Email.find_by('lower(email) = ? OR lower(forward_to_email) = ?', email.downcase, email.downcase)
       break if channel.present?
```

**To Reproduce**

1. Bcc and email to the chatwoot inbox email address
2. Click on the mailbox

**Expected behavior**

See the email.  Actually, you don't because EmailChannelFinder did not find it.

**Environment**

- [x] Self-hosted
- - [x] Linux VM

<sub>[CW-30](https://linear.app/chatwoot/issue/CW-30/emails-not-routed-based-on-x-original-to)</sub>

**Comment by pranavrajs** [comment]
@singpolyma Thanks for flagging this. We will take a look and update it soon.

**Comment by tejaswinichile** [comment]
@singpolyma You mean when the inbox email is present as cc_email or bcc_email the channel finder should work, correct?

**Comment by singpolyma** [comment]
@tejaswinichile Bcc is an example of this, sure, but also if an email is forwarded by a forwarding system, etc, the recipient will be found in `x_original_to` to get envelope recipient.

**Comment by pranavrajs** [comment]
@tejaswinichile I will compare the behaviour with other products and get back here.
