### ISSUE TITLE
Cannot configure SMTP other than Gmail's smtp (smtp.gmail.com)

### ISSUE THREAD

**Issue by ancozzz** [chatwoot/chatwoot#6609]
I tried to configure SMTP for mail inbox but all failed. Although the configuration information is accurate (configuration information by other mail or telnet browsers are working well). The unusual thing is that when I was the same configuration, most of the newspaper "Unable Update ..." and occasionally report ".... Updated Successfully" but still not working. When I try to configure with Gmail account, everything works ok. Is this Bug?

Cannot configure SMTP other than Gmail's smtp (smtp.gmail.com).

1. Go to 'Settings'
2. Click on 'Inboxes/Add Inboxs'
3. Select "Email Channel"
4. Config Imap and SMTP

Proceed to configure IMAP successfully, then configure SMTP to receive failure

Share a clear and concise description of what you expected to happen.

https://media.discordapp.net/attachments/654017096812068864/1080534625224499250/Screen_Shot_2023-03-01_at_23.50.18.png?width=1848&height=1262
https://media.discordapp.net/attachments/654017096812068864/1080534625505525840/Screen_Shot_2023-03-01_at_23.50.47.png?width=1848&height=1262

Chatwoot Version v2.14.0

**Comment by pranavrajs** [comment]
@ancozzz Can you please share any server logs? There is not much information to debug this further.
