### ISSUE TITLE
Application start with 127.0.0.1:3000 and cannot be accessed

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#661]
**Describe the bug**
20:15:53 backend.1  | Puma starting in single mode...
20:15:53 backend.1  | * Version 4.3.3 (ruby 2.6.5-p114), codename: Mysterious Traveller
20:15:53 backend.1  | * Min threads: 100, max threads: 100
20:15:53 backend.1  | * Environment: development
20:15:53 backend.1  | * Listening on tcp://127.0.0.1:3000
20:15:53 backend.1  | * Listening on tcp://[::1]:3000
20:15:53 backend.1  | Use Ctrl-C to stop

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pranavrajs** [comment]
@aermike Could you please provide more context?

**Comment by aermike** [comment]
OS: CentOS 7.7
Install after manual
Set enviroments variable after manual(if you want i put history , and .env file)
When start server I can't connect to 3000 port(It accept connection only from localhost I think)
Firewall is stopped

**Comment by aermike** [comment]
[root@guacamole ~]# screen -r
20:16:09 frontend.1 | ℹ ｢wdm｣: Hash: e5dee66890c767d436e1
20:16:09 frontend.1 | Version: webpack 4.42.0
20:16:09 frontend.1 | Time: 20188ms
20:16:09 frontend.1 | Built at: 04/01/2020 8:16:09 PM
20:16:09 frontend.1 |                                                                                      Asset       Size       Chunks                         Chunk Names
20:16:09 frontend.1 |                                                     js/application-e5dee66890c767d436e1.js   7.25 MiB  application  [emitted] [immutable]  application
20:16:09 frontend.1 |                                                 js/application-e5dee66890c767d436e1.js.map   6.38 MiB  application  [emitted] [dev]        application
20:16:09 frontend.1 |                                                                                  js/sdk.js    404 KiB          sdk  [emitted]              sdk
20:16:09 frontend.1 |                                                                              js/sdk.js.map    453 KiB          sdk  [emitted] [dev]        sdk
20:16:09 frontend.1 |                                                          js/widget-e5dee66890c767d436e1.js   2.92 MiB       widget  [emitted] [immutable]  widget
20:16:09 frontend.1 |                                                      js/widget-e5dee66890c767d436e1.js.map   2.83 MiB       widget  [emitted] [dev]        widget
20:16:09 frontend.1 |                                                                              manifest.json   5.62 KiB               [emitted]
20:16:09 frontend.1 |                   media/dashboard/assets/images/agent-aa76bb40e41e0e737cf0e929e8c66d20.svg   14.8 KiB               [emitted]
20:16:09 frontend.1 |                  media/dashboard/assets/images/canned-87a4e4e0032b5b27557c494d9cf1fc2d.svg   3.81 KiB               [emitted]
20:16:09 frontend.1 |       media/dashboard/assets/images/channels/facebook-4cbc901356e134d542a94a991cdbf4cf.png   12.4 KiB               [emitted]
20:16:09 frontend.1 | media/dashboard/assets/images/channels/facebook_login-cdbce77d96b5fe3ce2dc084764b4d5e9.png     16 KiB               [emitted]
20:16:09 frontend.1 |           media/dashboard/assets/images/channels/line-15ace046ed5a35b4304b37d0c077b8e3.png     15 KiB               [emitted]
20:16:09 frontend.1 |       media/dashboard/assets/images/channels/telegram-8967c418781f558f249f84faffbc8e02.png   49.9 KiB               [emitted]
20:16:09 frontend.1 |        media/dashboard/assets/images/channels/twitter-fef946b8bba756359e2a1e87ccd915ea.png    4.2 KiB               [emitted]
20:16:09 frontend.1 |        media/dashboard/assets/images/channels/website-2a4b439c3609ca48ab20c2714333ba77.png    5.9 KiB               [emitted]
20:16:09 frontend.1 |                    media/dashboard/assets/images/chat-55f282b2485b821d927f5228722f48af.svg   8.61 KiB               [emitted]
20:16:09 frontend.1 |            media/dashboard/assets/images/chatwoot_bot-62c9ab12f414819da40717a051fba38d.png   2.11 KiB               [emitted]
20:16:09 frontend.1 |                media/dashboard/assets/images/fb-badge-7a4add817f6e7fe207ffe52c428f3305.png   12.8 KiB               [emitted]
20:16:09 frontend.1 |                    media/dashboard/assets/images/flag-10c114599f84077e6edf5f3def7f8855.svg   6.99 KiB               [emitted]
20:16:09 frontend.1 |                 media/dashboard/assets/images/inboxes-93fdc823fcdf1f10bbb277cefb9de069.svg   5.57 KiB               [emitted]
20:16:09 frontend.1 |      media/dashboard/assets/images/integrations/cable-919dd72f5beb76a3205940c8a1862702.svg      3 KiB               [emitted]
20:16:09 frontend.1 |                    media/dashboard/assets/images/lock-f25fa6d8307d8bad7ed1e7be31a9197a.svg    4.2 KiB               [emitted]
20:16:09 frontend.1 |           media/dashboard/assets/images/twitter-badge-bd1252eb601e3a57a6fd4d5acd45228b.png   21.5 KiB               [emitted]
20:16:09 frontend.1 |               media/dashboard/assets/images/woot-logo-d6ec4f18194acc9e590c511b9ae51974.svg   12.2 KiB               [emitted]
20:16:09 frontend.1 |                                                          media/fonts/ionicons-19e65b89.eot    118 KiB               [emitted]
20:16:09 frontend.1 |                                                          media/fonts/ionicons-28df6ee7.svg    326 KiB               [emitted]
20:16:09 frontend.1 |                                                         media/fonts/ionicons-2c159d0d.woff   66.3 KiB               [emitted]
20:16:09 frontend.1 |                                                          media/fonts/ionicons-dd4781d1.ttf    184 KiB               [emitted]
20:16:09 frontend.1 |                media/shared/assets/fonts/Inter-Bold-741dc4163a97ffa354979f18802f6ca8.woff2    105 KiB               [emitted]
20:16:09 frontend.1 |                 media/shared/assets/fonts/Inter-Bold-895ddea987172f5a34a727cb0b559c9d.woff    140 KiB               [emitted]
20:16:09 frontend.1 |              media/shared/assets/fonts/Inter-Italic-449b5a389ef8e2a922fe903429f9bce3.woff2    105 KiB               [emitted]
20:16:09 frontend.1 |               media/shared/assets/fonts/Inter-Italic-c4d61b7aaa09d1f0cc71690530e06db2.woff    139 KiB               [emitted]
20:16:09 frontend.1 |          media/shared/assets/fonts/Inter-Light-BETA-5f9d6b274506c531a7a4f3576b9028f5.woff2    106 KiB               [emitted]
20:16:09 frontend.1 |           media/shared/assets/fonts/Inter-Light-BETA-8a49915cef00ba4fbf0965e434cf7302.woff    141 KiB               [emitted]
20:16:09 frontend.1 |               media/shared/assets/fonts/Inter-Medium-592a30dc78f8586ad4149dfdc3f73312.woff    139 KiB               [emitted]
20:16:09 frontend.1 |              media/shared/assets/fonts/Inter-Medium-900f31022873fa16552980d331bebfcc.woff2    104 KiB               [emitted]
20:16:09 frontend.1 |              media/shared/assets/fonts/Inter-Regular-41cd7069d7f578a69690178b818c0a2c.woff    131 KiB               [emitted]
20:16:09 frontend.1 |             media/shared/assets/fonts/Inter-Regular-77812e2fead777db0dc806b1eaabc7fd.woff2   97.7 KiB               [emitted]
20:16:09 frontend.1 |            media/shared/assets/fonts/Inter-SemiBold-3d011804596fb2ccde4af51830a9a7d5.woff2    105 KiB               [emitted]
20:16:09 frontend.1 |             media/shared/assets/fonts/Inter-SemiBold-8a12c702fa5c5e3ceed33f78e72b9bee.woff    140 KiB               [emitted]
20:16:09 frontend.1 |            media/shared/assets/fonts/Inter-Thin-BETA-a493fa52cdfc2741c36e6c8f984ee229.woff    142 KiB               [emitted]
20:16:09 frontend.1 |           media/shared/assets/fonts/Inter-Thin-BETA-be75564b3b35a82591e995ffdfa47408.woff2    108 KiB               [emitted]
20:16:09 frontend.1 |                       media/widget/assets/images/logo-a1bb9ce7a33ef8e3b17f28d79a48cb28.svg  916 bytes               [emitted]
20:16:09 frontend.1 | ℹ ｢wdm｣: Compiled successfully.

**Comment by pranavrajs** [comment]
@aermike Are you running in development mode?

**Comment by aermike** [comment]
@pranavrajs  Yes
I attach database.yml (without passsword and user settings), and .env if you please, help me to find my
[files.zip](https://github.com/chatwoot/chatwoot/files/4425413/files.zip)

 mistake
Thank you

**Comment by aermike** [comment]
This is from docker install 
| /gems/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
rails_1     | Puma starting in single mode...
rails_1     | * Version 4.3.3 (ruby 2.7.0-p0), codename: Mysterious Traveller
rails_1     | * Min threads: 5, max threads: 5
rails_1     | * Environment: development
**rails_1     | * Listening on tcp://0.0.0.0:3000**
rails_1     | Use Ctrl-C to stop

**Comment by pranavrajs** [comment]
@aermike You have to run it in production mode if you want to use it in a website. 

Please see this doc.
https://www.chatwoot.com/docs/installation-guide-docker#production-environment

**Comment by aermike** [comment]
Modifiyng Procfile.dev 
backend: bin/rails s -p 3000 **-b 0.0.0.0**
