### ISSUE TITLE
platform api does not work with newly issued platform access key

### ISSUE THREAD

**Issue by dearkafka** [chatwoot/chatwoot#6611]
### Discussed in https://github.com/orgs/chatwoot/discussions/6607

<div type='discussions-op-text'>

<sup>Originally posted by **dearkafka** March  4, 2023</sup>
So, I have a self-hosted chatwoot. I created a platform app via Super-user. I have obtained access key for a platform. I'm trying to access this `platform/api/v1/accounts/1/account_users` or this `platform/api/v1/accounts/2/account_users` (created via web), but I always got  `body={'error': 'Non permissible resource'} ` - 401. why? nginx underscore is set on.

to clarify, nginx correctly pass headers. user specific token works fine on user specific api methods.

using latest docker image and compose https://github.com/eremeye/helpdesk-workshop/blob/master/chatwoot/docker-compose.yml</div>

Also, looking into console (I dont know ruby so sorry for mistakes if any)
```

app = PlatformApp.create(name: 'name')
a = AccessToken.find_by(token: app.access_token.token)
```
and then
```

a.owner
=>
#<PlatformApp:0x00007f2a3944d8c8
 id: 2,
 name: "name",
 created_at: Sat, 04 Mar 2023 03:04:55.528756000 UTC +00:00,
 updated_at: Sat, 04 Mar 2023 03:04:55.528756000 UTC +00:00>
```
but
```

a.owner.platform_app_permissibles
=> []

@resource = Account.find(1)
a.owner.platform_app_permissibles.find_by(permissible:@resource)
=> nil
```

sorry for doubling in discussion, just thought it's an issue, indeed

**Comment by pranavrajs** [comment]
Platform APIs would only be able to access the accounts that are created using the platform API token. Platform App doesn't give access to all the accounts in the system. This is intentional.

Please create an account using the APIs here. https://www.chatwoot.com/developers/api/#tag/Accounts 

Closing this as it doesn't seem to be an issue. Happy to discuss if it is not the case.
