### ISSUE TITLE
fix: Chats by agents not showing up

### ISSUE THREAD

**Issue by josep112** [chatwoot/chatwoot#6620]
**Describe the bug**

Chats by agents not showing up!

**To Reproduce**

1. Click on reports
2. click on generated view

**Expected behavior**

Appear the agents with the information

**Screenshots**

<img width="1494" alt="Captura de Tela 2023-03-06 às 16 42 25" src="https://user-images.githubusercontent.com/12038013/223217379-14818101-7261-463f-a663-bc79c4eb1d6c.png">

**Environment**

- [X ] Self-hosted

**Desktop (please complete the following information)** (If applicable)
I tested it on
  - OS: [e.g. Linux, Windows, MacOS]
  - Browser [e.g. chrome, firefox, safari]

**Comment by pranavrajs** [comment]
@josep112 Can you please open the browser console and see if there are any errors in the console? Also, please share any additional server logs if you have any.

**Comment by pranavrajs** [comment]
@scmmishra Can you please debug this further?

**Comment by josep112** [comment]
@tejaswinichile from what I observed it is something related to postgresql

**Comment by josep112** [comment]
I have updated to version v2.14.0 but the problem persists

**Comment by josep112** [comment]
Hi @tejaswinichile 
I saw how this happens, when I create the agents, they appear at the overview (conversations by agents) but if I delete an agent then it stops showing the conversations by agents data

**Comment by josep112** [comment]
Anyone going through the same problem already tried several changes but without success

**Comment by sojan-official** [comment]
@josep112  are you still experiencing this on the latest version of Chatwoot ?

**Comment by josep112** [comment]
@sojan-official The problem I detected is when I delete the agent via the API, if the agent has an open conversation, the viewing screen no longer works, this also happens in the latest version

**Comment by sojan-official** [comment]
@josep112  Could you list the API call which you are making to delete the agent?

**Comment by sojan-official** [comment]
@josep112  Please don't make modifications to the database directly from the rails console; instead, rely on the product APIs as it could have unintended consequences. 

Please use remove agent APIs rather than directly modifying content from the database. using `.delete` won't trigger database callbacks which are used by chatwoot. Doing this will leave over references to the deleted object which can cause breakages.
