### ISSUE TITLE
[CW-1973] chore: upgrade node to 18.x

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#6629]
Node 14.xx and 16.xx will reach EOL towards the end of 2023. Switch to node18.x.

Release | Status | Codename | Initial Release | Active LTS Start | Maintenance Start | End-of-life
-- | -- | -- | -- | -- | -- | --
14.x | Maintenance | Fermium | 2020-04-21 | 2020-10-27 | 2021-10-19 | 2023-04-30
16.x | Maintenance | Gallium | 2021-04-20 | 2021-10-26 | 2022-10-18 | 2023-09-11
18.x | LTS | Hydrogen | 2022-04-19 | 2022-10-25 | 2023-10-18 | 2025-04-30
19.x | Current |   | 2022-10-18 | - | 2023-04-01 | 2023-06-01
20.x | Pending |   | 2023-04-18 | 2023-10-24 | 2024-10-22 | 2026-04-30

ref: https://github.com/nodejs/release#release-schedule

<sub>[CW-1973](https://linear.app/chatwoot/issue/CW-1973/chore-upgrade-node-to-18x)</sub>

**Comment by haszankauna** [comment]
hello @vishnu-narayanan can you please give more clarification on this?
