### ISSUE TITLE
WhatsApp Templates API missing pagination

### ISSUE THREAD

**Issue by aman400** [chatwoot/chatwoot#6651]
**Describe the bug**

Chatwoot fetches only the latest 25 templates from the Facebook cloud APIs.

It seems the WhatsApp template fetching API is paginated and there is no pagination added for the same on Chatwoot.

**To Reproduce**

Steps to reproduce the behaviour:

Add more than 25 Whatsapp templates on the Facebook cloud. And you only see the latest 25 templates on Chatwoot.

Not sure if it is the intended behaviour.

**Expected behavior**

Expecting WhatsApp templates to get paginated on demand(Infinite scroll)

**Environment**

- [Kubernetes] Self-hosted

**Desktop (please complete the following information)** (If applicable)
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [110.0.5481.177 (Official Build) (arm64)]

**Cloud Provider**
- GCP

**Comment by tejaswinichile** [comment]
@aman400 Thanks for reporting, we will look into this issue.

**Comment by Aribaskar-jb** [comment]
Hi let me work on this issue

**Comment by pranavrajs** [comment]
Closing this via https://github.com/chatwoot/chatwoot/pull/6880
