### ISSUE TITLE
Inconsistent name of the entrance header and page greeting in Help Center

### ISSUE THREAD

**Issue by Aakankshawrites** [chatwoot/chatwoot#6652]
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/99027437/224525188-d30ed7b6-f97b-4440-a570-9f612ec0cdb0.png">

**Comment by Aakankshawrites** [comment]
Expressions and the name of the pages must be consistent. 

The entrance greeting can be revised to:

'Hey 👋 , welcome to our Help Center'

**Comment by pranavrajs** [comment]
@Aakankshawrites Thanks for the suggestion. Closing as this is completed. https://www.chatwoot.com/help-center
