### ISSUE TITLE
Investigation: ISO 639-3 Codes

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#666]
Do we really need to use ISO 639-3 codes? Isn't ISO 639-1 sufficient?

**Comment by sojan-official** [comment]
https://iso639-3.sil.org/about/relationships

> The language identifiers in ISO 639-3 were devised for use in a wide range of applications, especially in computer systems where there is potential need to support a large number of the languages that are known to have ever existed. Whereas ISO 639-1 and ISO 639-2 are intended to focus on the major languages of the world that are most frequently represented in the total body of the world's literature, ISO 639-3 attempts to provide as complete an enumeration of languages as possible, including living, extinct, ancient and constructed languages, whether major or minor. As a result, ISO 639-3 lists a very large number of lesser-known languages. Languages designed exclusively for machine use, such as computer-programming languages, and reconstructed languages are not included in this code. Constructed languages that have not come into general use beyond a generation are also excluded.

just chose it after the idea that ISO 639-3 is more intended for computer systems. there isn't any strong argument for either when you are dealing with around 20 -30 languages.

**Comment by sojan-official** [comment]
closing this since are using both the codes internally now.
