### ISSUE TITLE
[CW-353] Improve email inbox creation flow

### ISSUE THREAD

**Issue by scmmishra** [chatwoot/chatwoot#6669]
The email inbox creation flow requires the following UX improvements

1. Add other options like "GMail", "Zoho" and others on the first step, with prefilled information wherever possible

   ![image.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/e736d1f1-4b2c-44be-a36c-02cb0643f444/0f99a2c4-ab40-4ab2-a235-bf8930d755c6)

2. The final step just shows the forward email, and a button to the config, but it's not apparent that the IMAP and STMP can be configured. 
   1. We can either take this step early on.
   2. If the user selects IMAP+SMTP based integration, no need to show them the forward details upfront

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-353](https://linear.app/chatwoot/issue/CW-353/improve-email-inbox-creation-flow)</sub>

**Comment by pranavrajs** [comment]
@scmmishra Let us do a product spec in the next sprint.
