### ISSUE TITLE
[CW-1270] Bug: Add string escape for the message content based rules

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#6674]
https://chatwoot-p3.sentry.io/issues/4000545921/?project=4504814961098762&query=is%3Aunresolved&referrer=issue-stream

<sub>[CW-1270](https://linear.app/chatwoot/issue/CW-1270/bug-add-string-escape-for-the-message-content-based-rules)</sub>

**Comment by tejaswinichile** [comment]
- Validation on automation rule

**Comment by pranavrajs** [comment]
@tejaswinichile Please see if this is still an issue.
