### ISSUE TITLE
Enhancement: Text area should expand when i am typing a large message on dashboard

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#668]
**Is your enhancement request related to a problem? Please describe.**
It's really hard to type a message containing multiple sentences. 

**Describe the solution you'd like**
The text area should expand once agent types a lengthy message

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by somedayrainbows** [comment]
would like to claim this please 😺

**Comment by sojan-official** [comment]
@somedayrainbows  have assigned it to you. thanks a lot for picking it up 😃
