### ISSUE TITLE
[CW-1281] Search contacts stopped to work after upgrade to v2.15.0

### ISSUE THREAD

**Issue by mtrofimiuk** [chatwoot/chatwoot#6680]
**Describe the bug**

500 error when calling the `/contacts/search` API.
Web service logs:
```
 [b447af02-572f-4b6d-912d-4165d3aafb93] ActiveRecord::StatementInvalid (PG::InvalidParameterValue: ERROR:  invalid value for parameter "default_text_search_config": "zulip.english_us_search"
CONTEXT:  while setting parameter "default_text_search_config" to "zulip.english_us_search"
[b447af02-572f-4b6d-912d-4165d3aafb93] app/controllers/api/v1/accounts/contacts_controller.rb:30:in `search'
[b447af02-572f-4b6d-912d-4165d3aafb93] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[b447af02-572f-4b6d-912d-4165d3aafb93] app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
[b447af02-572f-4b6d-912d-4165d3aafb93] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
[b447af02-572f-4b6d-912d-4165d3aafb93] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
```

**To Reproduce**

1. Install 2.15.0
2. Make API call to `/contacts/search?q=foo@bar.com`

**Expected behavior**

Return non-500 code response. 

**Screenshots**

![image](https://user-images.githubusercontent.com/10255360/225594196-a744ff4d-8261-473e-86bf-2918a0885d00.png)

**Environment**

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

<sub>[CW-1281](https://linear.app/chatwoot/issue/CW-1281/search-contacts-stopped-to-work-after-upgrade-to-v2150)</sub>

**Comment by pranavrajs** [comment]
@tejaswinichile @sojan-official Can you please check if this is something related to the missing indices we had in the last release?

**Comment by sojan-official** [comment]
@mtrofimiuk  could you post the curl request of the API call which you are making? 
also, have you made any changes to the code base?

**Comment by tejaswinichile** [comment]
I have checked this on our API endpoint; it's working well for us.

**Comment by mtrofimiuk** [comment]
The issue was caused by shared settings in Postgres indeed. Thanks!
