### ISSUE TITLE
[CW-1271] Icelandic translation missing for web chat widget

### ISSUE THREAD

**Issue by grimurd** [chatwoot/chatwoot#6681]
When setting chatwoot to icelandic the chat widget isn't translated. Setting the locale manually to "is" in the widget doesn't change anything, it stays in english.

Changing the locale to anything other than icelandic works.

This is in v2.15.0

<sub>[CW-1271](https://linear.app/chatwoot/issue/CW-1271/icelandic-translation-missing-for-web-chat-widget)</sub>

**Comment by muhsin-k** [comment]
@grimurd We didn't enable the language in the codebase. We will add it soon.

**Comment by grimurd** [comment]
@muhsin-k Will we have to wait another month for a minor release or will there be a patch release?

**Comment by muhsin-k** [comment]
@grimurd We are planning for a minor release next week.
