### ISSUE TITLE
[CW-1393] Help Center: Support video upload in articles

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#6698]
Help Center: Support video upload in articles

<sub>[CW-1393](https://linear.app/chatwoot/issue/CW-1393/help-center-support-video-upload-in-articles)</sub>

**Comment by pranavrajs** [comment]
Initially we could support embedding Youtube and Loom. Uploading and serving videos might not be a good option at the moment.

**Comment by tejaswinichile** [comment]
Uploading I can take a look, for embedding I will need help from @sivin / @muhsin-k .

**Comment by muhsin-k** [comment]
Yes. I can work on the frontend part.

**Comment by pranavrajs** [comment]
> Uploading I can take a look

Let us know upload the videos to our S3 at the moment. Only work with Loom / Youtube / Vimeo links for now.

**Comment by scmmishra** [comment]
@nithin lets pair on this, could be a good place to do some context transfer on how prosemirror works

**Comment by pranavrajs** [comment]
Doesn't looking at an implementation like this help? [https://github.com/CenterForOpenScience/markdown-it-video](https://github.com/CenterForOpenScience/markdown-it-video)
