### ISSUE TITLE
Sending whatsapp Cloud templates via API

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6704]
Friends, I couldn't find documentation on how to send Official WhatsApp Cloud template through the chatwoot api. It's possible? If yes, could you tell me how?

**Comment by iamsivin** [comment]
@udsonassis You can use this format for sending the WhatsApp cloud template by using the **POST** method.
```
{
    "inbox_id": 11251,
    "contact_id": 29109930,
    "source_id": "918288210621",
    "additional_attributes": {},
    "message": {
        "content": "ó tu paquete. La entrega se realizará en test dí.",
        "template_params": {
            "name": "sample_shipping_confirmation",
            "category": "SHIPPING_UPDATE",
            "language": "es",
            "processed_params": {
                "1": "test"
            }
        }
    },
    "assignee_id": 3994
}
```

**Comment by udsonassis** [comment]
@iamsivin Thanks for your feedback.
What could be wrong with my request?
The variables are not being filled in, the message is not getting to the client either.

# Request made via postman

{
    "inbox_id": 12,
    "source_id": "5531994172272",
    "additional_attributes": {},
    "message": {
        "content": "Olá {{1}}, nossos serviços estão com {{2}} de desconto na semana do consumidor. Aproveite e contrate o seu agora mesmo e garanta já o seu desconto!",
        "message_type": "outgoing",
        "private": false,
        "template_params": {
            "name": "promo_dia_do_consumidor",
            "category": "MARKETING",
            "language": "pt_BR",
            "processed_params": {
                "1": "Udson",
                "2": "20%"
            }
        }
    },
    "assignee_id": 1
}

#Return

{
    "meta": {
        "sender": {
            "additional_attributes": {},
            "availability_status": "offline",
            "email": null,
            "id": 79,
            "name": "udsonassis",
            "phone_number": "+553194172272",
            "identifier": null,
            "thumbnail": "",
            "custom_attributes": {},
            "last_activity_at": 1679185157,
            "created_at": 1678813020
        },
        "channel": "Channel::Whatsapp",
        "hmac_verified": false
    },
    "id": 30,
    "messages": [
        {
            "id": 4716,
            "content": "Olá 1, nossos serviços estão com 2 de desconto na semana do consumidor. Aproveite e contrate o seu agora mesmo e garanta já o seu desconto!",
            "account_id": 3,
            "inbox_id": 12,
            "conversation_id": 30,
            "message_type": 1,
            "created_at": 1679340764,
            "updated_at": "2023-03-20T19:32:44.513Z",
            "private": false,
            "status": "sent",
            "source_id": null,
            "content_type": "text",
            "content_attributes": {},
            "sender_type": "User",
            "sender_id": 15,
            "external_source_ids": {},
            "additional_attributes": {
                "template_params": {
                    "name": "promo_dia_do_consumidor",
                    "category": "MARKETING",
                    "language": "pt_BR",
                    "processed_params": {
                        "1": "Udson",
                        "2": "20%"
                    }
                }
            },
            "label_list": null,
            "conversation": {
                "assignee_id": 1,
                "unread_count": 0
            },
            "sender": {
                "id": 15,
                "name": "Felipe Monari",
                "available_name": "Felipe Monari",
                "avatar_url": "",
                "type": "user",
                "availability_status": "online",
                "thumbnail": ""
            }
        }
    ],
    "account_id": 3,
    "additional_attributes": {},
    "agent_last_seen_at": 0,
    "assignee_last_seen_at": 0,
    "can_reply": false,
    "contact_last_seen_at": 0,
    "custom_attributes": {},
    "inbox_id": 12,
    "labels": [],
    "muted": false,
    "snoozed_until": null,
    "status": "pending",
    "created_at": 1679340764,
    "timestamp": 1679340764,
    "first_reply_created_at": 0,
    "unread_count": 0,
    "last_non_activity_message": {
        "id": 4716,
        "content": "Olá 1, nossos serviços estão com 2 de desconto na semana do consumidor. Aproveite e contrate o seu agora mesmo e garanta já o seu desconto!",
        "account_id": 3,
        "inbox_id": 12,
        "conversation_id": 30,
        "message_type": 1,
        "created_at": 1679340764,
        "updated_at": "2023-03-20T19:32:44.513Z",
        "private": false,
        "status": "sent",
        "source_id": null,
        "content_type": "text",
        "content_attributes": {},
        "sender_type": "User",
        "sender_id": 15,
        "external_source_ids": {},
        "additional_attributes": {
            "template_params": {
                "name": "promo_dia_do_consumidor",
                "category": "MARKETING",
                "language": "pt_BR",
                "processed_params": {
                    "1": "Udson",
                    "2": "20%"
                }
            }
        },
        "label_list": null,
        "conversation": {
            "assignee_id": 1,
            "unread_count": 0
        },
        "sender": {
            "id": 15,
            "name": "Felipe Monari",
            "available_name": "Felipe Monari",
            "avatar_url": "",
            "type": "user",
            "availability_status": "online",
            "thumbnail": ""
        }
    }
}

#chatwoot
![image](https://user-images.githubusercontent.com/4209678/226449538-f1644599-5099-48e0-b365-892e50e92fe3.png)

#Facebook Tamplate
![image](https://user-images.githubusercontent.com/4209678/226449084-16f405b1-455c-4915-8113-b487be6d4f07.png)

**Comment by grupale** [comment]
Hi @iamsivin Can you give please some details about how you create conversations to send template messages?

I'm trying as follows:

I create a conversation in the WhatsApp Cloud API inbox_id
{{host}}/{{api_version}}/accounts/{{account_id}}/conversations

{
"source_id": "10621",
"inbox_id": 59,
"contact_id": "10621",
"status": "open"
}

Then I take the generated conversation_id (5495 in this example) and post a message


{{host}}/{{api_version}}/accounts/{{account_id}}/conversations/5495/messages

{
"content": "Welcome and congratulations!! This message demonstrates your ability to send a WhatsApp message notification from the Cloud API, hosted by Meta. Thank you for taking the time to test with us.",
"template_params": {
"name": "hello_world",
"category": "ACCOUNT_UPDATE",
"language": "en_US"
},
"message_type": "outgoing"
}

The message is correctly posted in chatwoot but not delivered in whatsapp


I'll apreciate any comment. Thanks!

**Comment by udsonassis** [comment]
> oi@iamsivinVocê pode fornecer alguns detalhes sobre como criar conversas para enviar mensagens de modelo?
> 
> Estou tentando da seguinte forma:
> 
> Eu criei uma conversa na caixa de entrada do WhatsApp Cloud API_id {{host}}/{{api_version}}/accounts/{{account_id}}/conversations
> 
> { "source_id": "10621", "inbox_id": 59, "contact_id": "10621", "status": "aberto" }
> 
> Em seguida, pego o conversation_id gerado (5495 neste exemplo) e posto uma mensagem
> 
> {{host}}/{{api_version}}/accounts/{{account_id}}/conversations/5495/messages
> 
> { "content": "Bem-vindo e parabéns!! Esta mensagem demonstra sua capacidade de enviar uma notificação de mensagem do WhatsApp a partir da Cloud API, hospedada pela Meta. Obrigado por dedicar seu tempo para testar conosco.", "template_params" : { " name": "hello_world", "category": "ACCOUNT_UPDATE", "language": "en_US" }, "message_type": "de saída" }
> 
> A mensagem foi postada corretamente no chatwoot, mas não foi entregue no whatsapp
> 
> Eu aprecio qualquer comentário. Obrigado!

Amigo, eu consegui exatamente assim:

curl --location 'https://app.chatwoot.xyz/api/v1/accounts/2/conversations' \
--header 'api_access_token: e8945ds5gyTX3p9ivj2zNL' \
--header 'Content-Type: application/json' \
--data '{
    "inbox_id":2,
    "source_id":"5531994172272",
    "additional_attributes":{},
    "message":{
        "content":"Your message....",
        "template_params":{"name":"your_template_name",
        "category":"UTILITY",
        "language":"pt_BR",
        "processed_params":{}
        }
    },
    "status": "pending"
 }'

**Comment by udsonassis** [comment]
@grupale, I got it like this:

curl --location 'https://app.chatwoot.xyz/api/v1/accounts/2/conversations'
--header 'api_access_token: e8945ds5gyTX3p9ivj2zNL'
--header 'Content-Type: application/json'
--data '{
"inbox_id":2,
"source_id":"5531994172272",
"additional_attributes":{},
"message":{
"content":"Your message....",
"template_params":{"name":"your_template_name",
"category":"UTILITY",
"language":"pt_BR",
"processed_params":{}
}
},
"status": "pending"
}'

**Comment by grupale** [comment]
Hi @udsonassis thank for you answer, I just tryed this CURL

curl --location 'https://xx.xxx.com./api/v1/accounts/2/conversations' \
--header 'Content-Type: application/json' \
--header 'api_access_token: asdasDSWSDASgwdasdWDSD6p' \
--data '{
    "inbox_id": 59,
    "source_id": "+5493855061551",
    "additional_attributes": {},
    "message": {
        "content": "Welcome and congratulations!! This message demonstrates your ability to send a message notification from WhatsApp Business Platform’s Cloud API. Thank you for taking the time to test with us.",
        "template_params": {
            "name": "hello_world",
            "category": "ACCOUNT_UPDATE",
            "language": "en_US"
        }
    },
    "status": "open"
}'

And I got this response 

    "meta": {
        "sender": {
            "additional_attributes": {},
            "availability_status": "offline",
            "email": null,
            "id": 10056,
            "name": "ACOSTA,JUAN JOSE",
            "phone_number": "+5493855061551",
            "identifier": null,
            "thumbnail": "",
            "custom_attributes": {
                "DNI": "21479115"
            },
            "last_activity_at": 1679529856,
            "created_at": 1677617411
        },
        "channel": "Channel::Api",
        "hmac_verified": false
    },
    "id": 5697,
    "messages": [
        {
            "id": 145269,
            "content": "Welcome and congratulations!! This message demonstrates your ability to send a message notification from WhatsApp Business Platform’s Cloud API. Thank you for taking the time to test with us.",
            "account_id": 2,
            **_"inbox_id": 31,_** <------ **_The post created the conversation in a diferent inbox_id_**
            "conversation_id": 5697,

**Comment by udsonassis** [comment]
@grupale

Removal "+" only in source_id, also check if your account_id is really 2.

Let me know if it worked.

**Comment by grupale** [comment]
@udsonassis 

![image](https://user-images.githubusercontent.com/10934794/227081787-799e74f2-5ef2-4004-a5a5-859b205143b0.png)

Account_id is 2 indeed

**Comment by iamsivin** [comment]
@grupale Here is the demo of how you can use it in UI. You can see the payload in the attached loom video.
https://www.loom.com/share/f05e567f40924a5295ca453a00133f2b

CC: @sojan-official
