### ISSUE TITLE
HTTP Erros v2.15.0 - 422, 500, 502, 503

### ISSUE THREAD

**Issue by zhiru** [chatwoot/chatwoot#6714]
**Describe the bug**

When using version v2.15.0, I found several times that it generates error 500, 502, 503 and 422.

I was using docker, using the latest version of docker hub.

When returning to version v2.14.0, there were no more problems, I found that through N8N, that several times chatwoot was offline, even the proxy was right and the navigation was working.

Another apparently in the apis or webhook there was some problem that causes it to start generating these errors.

**To Reproduce**

Try creating by n8n input boxes or using api requests

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [X] Self-hosted (Plesk + Litespeed Proxy)
- - [X] Docker

**Desktop (please complete the following information)** (If applicable)
 - OS: Windows
 - Browser: Chrome
 - Version: Lastest

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- `docker info`
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 17
  Running: 14
  Paused: 0
  Stopped: 3
 Images: 28
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-425.3.1.lve.3.el8.x86_64
 Operating System: CloudLinux 8.7 (Valeri Polyakov)
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.6GiB
 Name: server
 ID: DO36:4NLX:DAJL:DQAA:XQYS:ND4O:4EP6:QPFK:Q6LA:BRF5:5Q5D:RRKD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

- `docker-compose version`
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Cloud Provider** (If applicable)
- [X] Hetzner - AX101

**Comment by pranavrajs** [comment]
@zhiru Would it be possible to share any logs from the servers during the 5xx and 4xx requests?

**Comment by zhiru** [comment]
<img width="1854" alt="image" src="https://user-images.githubusercontent.com/4226997/227383996-a768e8b4-a564-4863-a38b-a35804a2a483.png">


Here a exemplo just get down :(

**Comment by zhiru** [comment]
i think i find the problem.

The litespeed server is killing the reverse proxy. the same that is on their docs, so mande manually
