### ISSUE TITLE
[CW-1395] cloud api new templates categories not loaded 

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#6730]
whatsapp cloud api release new template categories types they new 3 types 

and new categories not loaded to chatwoot
https://developers.facebook.com/docs/whatsapp/updates-to-pricing

<sub>[CW-1395](https://linear.app/chatwoot/issue/CW-1395/cloud-api-new-templates-categories-not-loaded)</sub>

**Comment by scmmishra** [comment]
CC: @tejaswinichile

**Comment by pranavrajs** [comment]
@voko3456 It seems that there is no change required from Chatwoot's end to support the new templates. As far as I understand, this change has no effect on the API structure. Meta is limiting the categories to 3 categories and there is a pricing change associated with the templates. However, the payload used in the APIs doesn't have any change. Closing this here for now. Let me know if it is not the case.
