### ISSUE TITLE
[CW-1394] delete-agent-in-inbox inbox_id in path and body

### ISSUE THREAD

**Issue by dearkafka** [chatwoot/chatwoot#6731]
### Discussed in https://github.com/orgs/chatwoot/discussions/6689

<div type='discussions-op-text'>

<sup>Originally posted by **dearkafka** March 17, 2023</sup>
Both path for "delete agent" and body has "inbox_id" param. why? Does it mean the same thing? can it be set to different values? whats the logic?

It seems a little bit confusing or redundant.

https://www.chatwoot.com/developers/api/#tag/Inboxes/operation/delete-agent-in-inbox</div>

<sub>[CW-1394](https://linear.app/chatwoot/issue/CW-1394/delete-agent-in-inbox-inbox-id-in-path-and-body)</sub>

**Comment by pranavrajs** [comment]
@dearkafka Agreed, this is confusing and this seems like a mistake in the implementation. We will update it.

**Comment by tejaswinichile** [comment]
I will check and update the API doc and the endpoint params.
