### ISSUE TITLE
Not able to set working hours from 9pm to 2am

### ISSUE THREAD

**Issue by voko3456** [chatwoot/chatwoot#6733]
When I try to set working time from 9pm till 2am it's showing error invalid time

**Comment by pranavrajs** [comment]
@voko3456 If you want to 9pm - 2am on Monday. You can select 9-12pm on Monday and 12-2am on Tuesday.

**Comment by pranavrajs** [comment]
Let me know if it helps.

**Comment by danielthedifficult** [comment]
@voko3456 what do you think about 'cheating' by setting a different time zone that is 2-3 hours behind, so your hours would be 7pm-12pm GMT, for example, but would represent 9pm-2am GMT+2

**Comment by pranavrajs** [comment]
Closing this as a workaround is available.
