### ISSUE TITLE
[CW-2000] Conversations Filter via API retornando Internal Server Error

### ISSUE THREAD

**Issue by udsonassis** [chatwoot/chatwoot#6739]
Friends, I'm trying to make a Conversation Filter via API following the guidelines in the documentation, but the query returns the following error:

{
"status": 500,
"error": "Internal Server Error"
}

\#query via postman

curl --location '[https://app.chatwoot.xyz/api/v1/accounts/1/conversations/filter](https://app.chatwoot.xyz/api/v1/accounts/1/conversations/filter)'
\--header 'api_access_token: xxx'
\--header 'Content-Type: application/json'
\--data '\[
{
"attribute_key": "inbox_id",
"filter_operator": "equal_to",
"values": \[
"6"
\],
"query_operator": "AND"
},
{
"attribute_key": "status",
"filter_operator": "equal_to",
"values": \[
"open"
\],
"query_operator": "OR"
},
{
"attribute_key": "status",
"filter_operator": "equal_to",
"values": \[
"pending"
\]
}
\]'

\#Return
{
"status": 500,
"error": "Internal Server Error"
}

# another query

\[
{
"attribute_key": "inbox_id",
"filter_operator": "equal_to",
"values": \[
"6"
\],
"query_operator": "AND"
},
{
"attribute_key": "status",
"filter_operator": "equal_to",
"values": \[
"open"
\]
}
\]

\#Return
{
"status": 500,
"error": "Internal Server Error"
}

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2000](https://linear.app/chatwoot/issue/CW-2000/conversations-filter-via-api-retornando-internal-server-error)</sub>

**Comment by pranavrajs** [comment]
@udsonassis This was an issue with the documentation. Can you please try the following? You need to wrap the array inside a payload object. I've updated the documentation.
The data would change to following. 

```
curl 'https://app.chatwoot.xyz/api/v1/accounts/<account-id>/conversations/filter' \
  -H 'Content-Type: application/json' \
  -H 'api_access_token: <api-token>' \
  --data-raw '{"payload":[{"attribute_key":"status","filter_operator":"equal_to","values":["open"],"query_operator":"and"},{"attribute_key":"inbox_id","filter_operator":"equal_to","values":[1]}]}'
```

Updated in https://github.com/chatwoot/chatwoot/pull/7245

See the updated query here. https://www.chatwoot.com/developers/api/#tag/Conversations/operation/conversationFilter
