### ISSUE TITLE
message_created event not triggered for interactive messages for an Inbox with AgentBot attached

### ISSUE THREAD

**Issue by saravanan-thirumuruganathan** [chatwoot/chatwoot#6745]
Hello,

Thanks a lot for the wonderful product and great API system.

I am working on a chatbot built on top of chatwoot and using the AgentBot api.  Currently, it is a simple echo bot. When testing on a web inbox, it works great. Every message that I send in the web widget gets a reply from the agent box. 

However, this does not work when interactive messages are involved. I am using the sample payload for input_select from the interactive messages doc. When I trigger it, I am able to see two button (Option 1 and Option 2) in the web widget. However, when I select one of them, I see that the message is sent from the front end - however, in my backend, the corresponding message_created or message_updated is not triggered. 

Interestingly, when i use the browser inspect tool and the networking tab, I do not see any messages being sent to backend.  Attaching the picture below.

<img width="739" alt="Screenshot 2023-03-24 at 12 41 15" src="https://user-images.githubusercontent.com/792699/227450522-8582daee-5a6c-41a1-98f5-9b393b8b1321.png">

Of course, there is a work around by using webhooks but it is a heavier duty approach as it bombards my script with events for all inboxes. 

Thanks again for the great product.

**Comment by saravanan-thirumuruganathan** [comment]
Addendum: I wrote a quick script to see what happens using a webhook. I subscribed to messaged_created and message_updated events. If I click on one of the options, chatwoot does trigger an event for *message_updated* but not message_created. However, this happens only for webhook and not for agentbot events. The sidekiq logs also seems to corroborate this. Hope this helps.

**Comment by pranavrajs** [comment]
@saravanan-thirumuruganathan I cannot reproduce this issue on my end. I tried setting up the agent bot. Both message_created and message_updated events are received with any issues. 

Can you please share the server side logs, a screencast on how you create the messages and a sample message payload?

**Comment by saravanan-thirumuruganathan** [comment]
Hello Pranav, I created some workarounds that seems to solve this issue. Since it happened few months ago, i do not have the server / sidqkiq logs. I am closing the issue. Will reopen if it recurs. Thanks again.
