### ISSUE TITLE
Chore: APIs for Agent Bot

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#675]
I would like to have APIs 
- to  connect and disconnect an Agent Bot to an inbox
- to list all the agent bots available

**Comment by sojan-official** [comment]
https://github.com/chatwoot/chatwoot/pull/676.

**Comment by fiantinangon** [comment]
Hi wana ask about this issue @sojan-official , is there any API to create agent bot ?

**Comment by sojan-official** [comment]
@fiantinangon  At the moment there isn't an API to create agent bots. You have to create them via the rails console.  We are evaluating how to structure the APIs for this.  let us know if you have specific use cases that you would like to have support for.

**Comment by fiantinangon** [comment]
> @fiantinangon At the moment there isn't an API to create agent bots. You have to create them via the rails console. We are evaluating how to structure the APIs for this. let us know if you have specific use cases that you would like to have support for.

Thanks, @sojan-official I've opened a discussion on discord and open ticket related to the issue while implementing agent bot #1510
