### ISSUE TITLE
Feature: Ability to use chatwoot with multiple languages

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#677]
**Is your feature request related to a problem? Please describe.**
I use chatwoot across multiple regions and hence I should be able to use chatwoot in multiple languages. 

**Describe the solution you'd like**

- [ ]   Accounts can have multiple allowed languages apart from the primary language
- [ ]   if users browser settings give any of the values in the allowed languages, we will show the widget in that language
- [ ]   if the language setting doesn't match allowed languages we will fall back to the default language 
- [ ]  Same for the dashboard as well 
- [ ]  emails will get sent in the default language

**Describe alternatives you've considered**
none 

**Additional context**
ref: #307

**Comment by sojan-official** [comment]
https://phrase.com/blog/posts/rails-i18n-setting-and-managing-locales/

**Comment by pranavrajs** [comment]
Closing this as we already support multiple languages.
