### ISSUE TITLE
Chatwoot not loading all WhatsApp template messages

### ISSUE THREAD

**Issue by emanuellopess** [chatwoot/chatwoot#6771]
**Describe the bug**

Some WhatsApp template messages are not appearing in the 'new conversation' page.

**To Reproduce**

1. Add new [WhatsApp templates](https://business.facebook.com/wa/manage/message-templates) until you have more than 43 message templates;
2. Now add a new WhatsApp message template;
3. Go to the Chatwoot contact list page;
4. Select a contact that have a registered WhatsApp number;
5. Open a new conversation with a WhatsApp inbox;
6. Try to send a message with the new message template you created and Facebook approved;
7. You will not find the new template in the send new message page.

**Expected behavior**

The new approved WhatsApp message template appears

**Screenshots**

![Captura de tela de 2023-03-28 11-57-35](https://user-images.githubusercontent.com/74307223/228280223-a8ed6089-b5ed-43a0-ab09-aaefb27f1ef5.png)

![Captura de tela de 2023-03-28 11-58-00](https://user-images.githubusercontent.com/74307223/228280306-568ab006-6326-4607-b9dd-3bc7e0c79cee.png)

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [x] Self-hosted
- - [x] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Desktop (please complete the following information)**
 - OS: Linux
 - Browser: Brave Browser (chromium)
 - Version: Brave version v1.49.128 and chromium 111.0.5563.110

**Cloud Provider** (If applicable)
- [x] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

After some testing I found that the API to get the message templates from facebook have a hard limit to the quantity of templates, I found my approved template after modifying the limit in the GET request, here is query URL below:

```json
https://graph.facebook.com/{{Version}}/{{WABA-ID}}/message_templates?access_token={{User-Access-Token}}&limit=200
```
Maybe add a configuration with the limit the quantity of templates to get? Or a button to get all the templates and clean the cache? If you can please explain how often the message template query is sent maybe we could help to find a solution to this.

**Comment by emanuellopess** [comment]
For anybody who is having this problem, I fixed it by changing a line in the following file:

_**chatwoot/app/services/whatsapp/providers/whatsapp_cloud_service.rb**_

This line:
```ruby
    response = HTTParty.get("#{business_account_path}/message_templates?access_token=#{whatsapp_channel.provider_config['api_key']}")
```
To:
```ruby
    response = HTTParty.get("#{business_account_path}/message_templates?access_token=#{whatsapp_channel.provider_config['api_key']}&limit=200")
```

After changing the line restart your Chatwoot instance, for anyone using the Chatwoot cli it is:
```
cwctl --restart
```


I'm waiting for a more permanent solution.

**Comment by mufeeer** [comment]
hi, facing the same issue as well. 

Waiting for the permanent solution for this.

**Comment by rgon** [comment]
This seems like the same issue as #6651

**Comment by maykolc** [comment]
I have the same problem, I can see 3 templates. I used the workaround but doesn't work

    response = HTTParty.get("#{business_account_path}/message_templates?access_token=#{whatsapp_channel.provider_config['api_key']}&limit=200")

**Comment by pranavrajs** [comment]
Folks, the issue with pagination is already solved in https://github.com/chatwoot/chatwoot/pull/6880/files. You should be see all the templates without any issues. 

Now if you still don't see the templates. Please check the following. 
- Templates that are approved are only shown.
- Templates that include multimedia will not be shown as we don't support it now.
- Templates that include variables in headers will not be shown.

**Comment by pranavrajs** [comment]
Closing this here for now. Please feel free to raise the issue again if needed with more information.
