### ISSUE TITLE
[CW-1431] Allow setting custom attributes to conversations from the SDK

### ISSUE THREAD

**Issue by scmmishra** [chatwoot/chatwoot#6781]
The SDK allows setting custom attributes to a contact, but not for conversation

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1431](https://linear.app/chatwoot/issue/CW-1431/allow-setting-custom-attributes-to-conversations-from-the-sdk)</sub>

**Comment by arladmin** [comment]
@scmmishra 
In the latest release, 2.16.0, the API call isn't able to go through.

Error:
![image](https://user-images.githubusercontent.com/64059154/232744624-f8de2fd4-19bd-4755-bd7b-ab42529e1445.png)
