### ISSUE TITLE
ARM Support Docker

### ISSUE THREAD

**Issue by arig4m3r** [chatwoot/chatwoot#6787]
### Discussed in https://github.com/orgs/chatwoot/discussions/6073

<div type='discussions-op-text'>

Hey, is there any or the plan to support self-hosted Chatwoot in a Docker container?
The docker image of chatwoot has no build for arm64, that would be awesome to deploy on clouds like Oracle Cloud, where a tier of arm is free.

Thanks!</div>

**Comment by hexclann** [comment]
Will chatwoot v3 support ARM images?

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/2575

**Comment by vishnu-narayanan** [comment]
Official Chatwoot` arm` docker images are now available.

1. https://github.com/chatwoot/chatwoot/pull/10789
2. https://github.com/chatwoot/chatwoot/pull/10891
