### ISSUE TITLE
[CW-1459] Active campaign does not show complete pre chat form

### ISSUE THREAD

**Issue by cfelbertp** [chatwoot/chatwoot#6795]
**Describe the bug**

A campaign bypasses the pre chat form.

- I have created a custom attribute that is a checkbox.
- The checkbox contains the text: "I agree to the processing of my data in accordance with the Privacy Policy."
- I activated the pre chat form in the inbox and entered the following text in the "pre chat message" field there: "Data entered into this chat will be transferred outside the EU/EEA (including the US). Please note that the level of data protection outside Europe may be lower, and it may be easier for authorities in these countries to access the collected data, while it may be more difficult for you to take legal action to prevent such access. For more details, please see our Privacy Policy."

I put this text in the "pre chat message" field, because there I have the possibility to turn "Privacy Policy" into a link that leads to the corresponding web page.

This works exactly the way I want it to!

However, when I create a campaign and the user then clicks on the displayed text, the chat widget opens, but it doesn't show the pre chat form, but the "misleading" text (in my case): "Please proivide your name and email before starting the conversation". The checkbox is also displayed. But the pre chat message is missing and I don't need the "please proivide your name and email" text, because our chat is supposed to be anonymous.

**Expected behavior**

I would have expected that in a campaign, the chat widget would behave the same as usual after opening.

**Screenshots**
The pre chat from I configured:

<img width="382" alt="Bildschirmfoto 2023-03-30 um 15 15 05" src="https://user-images.githubusercontent.com/31688556/228857984-db9cb658-4e5d-4bab-a1f3-ee7d49d44fa7.png">

The active campaign:

<img width="215" alt="Bildschirmfoto 2023-03-30 um 15 25 05" src="https://user-images.githubusercontent.com/31688556/228857978-446fd8ba-3650-4e8e-a14a-f4c77c6b6c3c.png">

The following screenshot shows the widget without the pre chat message but with additional text that I don't know why it's there.

<img width="431" alt="Bildschirmfoto 2023-03-30 um 15 25 23" src="https://user-images.githubusercontent.com/31688556/228857968-c21d0d34-de24-4ff1-84e5-5faca42931bd.png">

**Version**

Chatwoot 2.15.0

<sub>[CW-1459](https://linear.app/chatwoot/issue/CW-1459/active-campaign-does-not-show-complete-pre-chat-form)</sub>

**Comment by muhsin-k** [comment]
@cfelbertp Could you please share your pre-chat settings as well?

**Comment by cfelbertp** [comment]
@muhsin-k Sure!

<img width="918" alt="Bildschirmfoto 2023-03-31 um 08 00 05" src="https://user-images.githubusercontent.com/31688556/229036085-51e9cff2-570f-40ea-acb9-45b59dcbbadd.png">
