### ISSUE TITLE
[CW-1448] Refactor: advanced filter and automation conditions filter frontend changes

### ISSUE THREAD

**Issue by tejaswinichile** [chatwoot/chatwoot#6797]
1. Check conditions.json and filter_keys.json
2. There are multiple files like automation/constant.json which can be refactored

Refactoring on key-value attributes used in automations and advanced filters.

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1448](https://linear.app/chatwoot/issue/CW-1448/refactor-advanced-filter-and-automation-conditions-filter-frontend)</sub>

**Comment by tejaswinichile** [comment]
Refactoring the code

**Comment by pranavrajs** [comment]
@tejaswinichile Please add more context here.
