### ISSUE TITLE
New Env Vars (BRAND_NAME, LOGO, BRAND_URL ...)

### ISSUE THREAD

**Issue by zhiru** [chatwoot/chatwoot#6804]
Check if the environment variables below are set and use, otherwise use the default configuration

BRAND_NAME
INSTALLATION_NAME
WIDGET_BRAND_URL
BRAND_URL
LOGO
LOGO_THUMBNAIL
PRIVACY_URL
TERMS_URL

**Comment by pranavrajs** [comment]
Closing this as these are internal variable and we never intend to expose this as environment configuration.
