### ISSUE TITLE
Update some default Files to custom

### ISSUE THREAD

**Issue by zhiru** [chatwoot/chatwoot#6805]
Hey guys,

It's possible this changes?

in file /chatwoot/app/views/installation/onboarding/index.html.erb

`<img src="/brand-assets/logo.svg" alt="Chatwoot logo" class="hero__logo" /> `
made use LOGO data

`<h2 class="hero--title">Howdy, Welcome to Chatwoot 👋</h2>`
convert to translatable or editable using env vars

in file /chatwoot/app/views/layouts/vueapp.html.erb

Add the possbility of custom  meta name="description" and custom favicon (or custom favicon start url)

**Comment by pranavrajs** [comment]
@zhiru Closing this as we don't support brand customizations at the moment.
