### ISSUE TITLE
feat: Ability to have automated QnA for repetitive questions 

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#682]
**Is your feature request related to a problem? Please describe.**
Live agents face a lot of repetitive questions. In order to avoid having to deal with this, the bot could provide the ability for the administrator to set either QnA or decision tree questions (clickable questions that drive you down to your answer). If the user still is not satisfied, could be transferred to a live agent

**Describe the solution you'd like**
Admin is able to upload frequently asked questions/create a decision tree for questions which can eventually be 'elevated' to live agent.

**Comment by tabrza** [comment]
An alternative to the above is how [intercom](https://www.intercom.com/) handles it. Users can either search for an 'article' or if they were to scroll down, see news updates/QnAs 
![image](https://user-images.githubusercontent.com/21217850/90014584-c8dd4f80-dcc0-11ea-9db2-56180ef4864b.png)

another example is from freshworks:
![image](https://user-images.githubusercontent.com/21217850/90014745-0c37be00-dcc1-11ea-9fa8-7ba7cd0f6e89.png)

**Comment by sojan-official** [comment]
@tabrza  this should be covered in #1002

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/714
