### ISSUE TITLE
Selft Hosted Heroku GMAIL SMTP Setup

### ISSUE THREAD

**Issue by tahmidbintaslim** [chatwoot/chatwoot#6831]
Hi, Anyone have done the SMTP setup with Gmail in Self Hosted Version in Heroku

**Comment by architechpro** [comment]
Unfortunately, we failed to set up Chatwoot with Gmail business email account. Chatwoot instructions may work with regular gmail accounts, so if you are using Gmail, it's better to look at [Frorntapp](https://help.front.com/t/m229xj/how-to-add-a-gmail-account) as they have Google API authentication for Gmail accounts, which fetches history (up to 50k emails), provides 2-way sync, etc.

**Comment by tahmidbintaslim** [comment]
I understand now. Thank you for explanation. I followed the recommended one, Sendgrid and now everything works fine.
