### ISSUE TITLE
Self Hosted Heroku Active Storage Issue

### ISSUE THREAD

**Issue by tahmidbintaslim** [chatwoot/chatwoot#6832]
Hi, I am using Heroku One Click Deployed version of self hosted ChatWoot. I put the Config Vars as

ACTIVE_STORAGE_SERVICE = local

But when a user try to send a file (pdf or image) it show like below:
![image](https://user-images.githubusercontent.com/45480402/230052822-f4822b71-643d-47e7-bb1c-76380e39b3ff.png)

But the receiver can not open the file and the sender also can not download the file. It shows Error Failed to load Pdf (For Pdf File) or This page can't be found (For Images)

Console logs show that active storage 500 (Internal Server Error)

https://domain.com/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBYUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c06aee48b4a9ea3dcfc1b08a8a78f215b835def5/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2d0eVpYTnBlbVZKSWd3eU5UQjRNalV3QmpzR1ZBPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--d420c83edf37ccbe4ce09030c8a91dddcd3115be/0h7n3Ya06jaEEeIHzAY9kWPm5ways9UTFTMBVzJnhyYXYmGShCZkUkIX4hNXFxFSxFMxNzdCJwP3QSMx8nAHaUdRkQNnYnFy4RM0ckpg 500 (Internal Server Error)

**Comment by vishnu-narayanan** [comment]
@tahmidbintaslim Heroku has an "ephemeral" hard disk. The files uploaded to Chatwoot would not persist after the application is restarted. By default, Chatwoot uses local disk as the upload destination. To overcome this problem, you will have to [configure a cloud storage](https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers).

ref: https://www.chatwoot.com/docs/self-hosted/deployment/heroku#known-limitations

**Comment by tahmidbintaslim** [comment]
I did the S3 Bucket Setup now. But it still show Error 500.
One more issue is when send an images from Line Inbox, sender can see the image. But Line User (receiver) can not see the image

**Comment by tahmidbintaslim** [comment]
I do not see any more Error 500 for Image urls. Any images send from the chat is now stored to S3 Bucket. But I have another issue showing up now, using Line Channel when send an pdf file or image file it is send from the sender side. But receiver side did not receive it.

**Comment by tahmidbintaslim** [comment]
I found a reference to a problem. But in my case it is happening to pdf only when sending from Line Channel to Line Users. Ref: https://github.com/chatwoot/chatwoot/issues/6424

**Comment by tahmidbintaslim** [comment]
Hello, any update to this? I still have the same issue as User try to send image or file through Line Channel. The end user in the Line, can not see the image or file.

**Comment by pranavrajs** [comment]
@tahmidbintaslim Please share logs after you configured the S3 bucket with Chatwoot. If you are still using local with Heroku, it wouldn't work.

**Comment by vishnu-narayanan** [comment]
@tahmidbintaslim Looks like the initial issue is now resolved as you are using s3. Could you open up a new issue for the Line channel attachments issue?
