### ISSUE TITLE
Hyperlinks in reply messages

### ISSUE THREAD

**Issue by kalebwd** [chatwoot/chatwoot#6836]
**Describe the bug**

Anytime I insert a URL into a message, the message the recipient gets does not work. It looks like the majority of the time, it's automatically adding a '\' (backslash) character to the end of the URL, and then formatting that as '%5C' in the actual hyperlink. Even if my URL ends with '/' it will add the '\' also. The resulting URL when clicked does not work.

**To Reproduce**

1. Insert a URL into the message you are sending in Chatwoot.
2. Hit send

**Expected behavior**

The link I insert shouldn't be changing.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [X] Self-hosted
- - [X] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Comment by kalebwd** [comment]
I am using v15.0
<img width="79" alt="Screenshot 2023-04-05 at 1 28 54 PM" src="https://user-images.githubusercontent.com/25017170/230171935-5f888ca5-546b-490a-87d2-33d2b35871e3.png">

**Comment by kalebwd** [comment]
This seems to only be happening when replying to a conversation. For example, if I paste a link into a new conversation, it does not happen. Perhaps this has something to do with the encoding of the message received when the conversation is initially opened?

**Comment by pranavrajs** [comment]
@kalebwd The latest version has a fix for it. Please see if that works for you. If not, please feel free to reopen the issue.

**Comment by pranavrajs** [comment]
https://github.com/chatwoot/chatwoot/pull/7069
