### ISSUE TITLE
FB disconnected and unable to connect again

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#6844]
**Describe the bug**

Hi guys - FB get disconnected automatically and when we are trying to connect again we are geting this error
(as attached in screenshot) 

Settings --> Inboxes -- FB settings --> Continue with Facebook --> Feature unavailable 

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

<img width="599" alt="image" src="https://user-images.githubusercontent.com/38554929/230401805-db30c1fb-550c-4314-ad67-a2a36b33fb08.png">

**Environment**

- [ ] Self-hosted
- - [] Kubernetes

**Cloud Provider** (If applicable)
- [ ] GCP

**Comment by pranavrajs** [comment]
@harismateen Can you please check the developer portal and see if there are any errors? It is hard to debug with the information available here.

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
