### ISSUE TITLE
Feature: Implement RTL language support

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#686]
- Feature: Add Arabic language
- Implement RTL support

# implementation 

 - add the RTL attribute to the language config.
-  Append the html with `dir="rtl"` based on the config. 
- iron out the layout breakages and css fixes

**Comment by mohammad362** [comment]
any new news for this feature?

**Comment by MiLaDTechS** [comment]
is there any plans to implement this feature ?

**Comment by sojan-official** [comment]
@MiLaDTechS @mohammad362 This is still in our backlog for prioritization.
We will share further updates when the team starts working on this.

**Comment by hadifarnoud** [comment]
We are waiting on this as well. If you have any working version, I can help with the CSS issues

**Comment by hadifarnoud** [comment]
for testing purpose you can use phrase below in editor. it must show up in the same order you can see here

تست فارسی و English با هم

**Comment by sojan-official** [comment]
@hadifarnoud, you can have a look at #6430 and #6369

**Comment by hadifarnoud** [comment]
I commented on their respective issues.

**Comment by iamsivin** [comment]
> I commented on their respective issues.

@hadifarnoud Thank you. The UI issues that you mentioned were fixed.
Here is the updated loom video.
https://www.loom.com/share/53e305e7d58e4576ae6014c7dcc0554d

**Comment by hadifarnoud** [comment]
Awesome. I found no issue in the new video. LGTM

**Comment by smshuja** [comment]
Ideally the language switcher should be part of the UI and user profile/preferences. Multiple people with different locale preferences can work on the same site. This way all agents are not forced to use a single locale.

**Comment by smshuja** [comment]
Also for the Widget, the SDK should provide an option to set the direction. `isRTL`?

**Comment by pranavrajs** [comment]
Closing this as the core feature is merged. We will address the feedback on this thread separately.

**Comment by pranavrajs** [comment]
https://github.com/chatwoot/chatwoot/issues/678
