### ISSUE TITLE
Twillio Voice & User Contact Options

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#6864]
Greetings Support.  I am writing to request two new features for chatwoot

Chatwoot is the best customer support tool on the market.

1. First request is to integrate a voice channel with Twilio to be able to accept calls through the script.

2. Second request is an option of whether or not after a conversation the person who spoke with us is saved as a contact.  It is currently saved as a contact automatically after making contact.  make this option an option and not be saved automatically.

3. a maintenance option that can free up space in the database and previous chats in the super admin area that can delete and delete old conversations en masse from a certain date

Thanks

**Comment by pranavrajs** [comment]
@movilreup

> First request is to integrate a voice channel with Twilio to be able to accept calls through the script.

We are focussing only on the text based channels at the moment. We will not add a voice channel in the near future.

> Second request is an option of whether or not after a conversation the person who spoke with us is saved as a contact. It is currently saved as a contact automatically after making contact. make this option an option and not be saved automatically.

The foundation of a conversation is built on top of contact, it is not feasible to give this as option at the moment.

> a maintenance option that can free up space in the database and previous chats in the super admin area that can delete and delete old conversations en masse from a certain date
 
If you delete the contacts from the contacts tab, it would delete the associated conversations as well.
