### ISSUE TITLE
There should be option for setting regex for validation of custom attribute

### ISSUE THREAD

**Issue by Anim12** [chatwoot/chatwoot#6866]
**Is your feature request related to a problem? Please describe.**
If I add custom attributes. There is no valdation. For core attributes there is but we cannot change as per requirements.

**Describe the solution you'd like**
There should be option for setting regex for validation of custom attribute. Or in environment variable.

**Comment by pranavrajs** [comment]
@Anim12 Thanks for the suggestion. Happy to accept the PR if you would like to contribute.

**Comment by surabhisuman** [comment]
Hello @pranavrajs, I can take this up to contribute. Can you please assign this issue to me if there isn't any active development.
