### ISSUE TITLE
[CW-1978] Add support for Whatsapp Cloud API's Media-Based Message Templates in Chatwoot API

### ISSUE THREAD

**Issue by aris-infradigital** [chatwoot/chatwoot#6867]
**Is your feature request related to a problem? Please describe.**
Currently, Chatwoot API does not support Whatsapp Cloud API's Media-Based Message Templates. It is nice if I can only use Chatwoot API to send Whatsapp media-based templates so the message is visible in the Customer Support's dashboard and the sent status is valid.

in **send_on_whatsapp_service.rb**
```
  def validated_body_object(template)
    # we don't care if its not approved template
    return if template['status'] != 'approved'

    # we only care about text body object in template. if not present we discard the template
    # we don't support other forms of templates
    template['components'].find { |obj| obj['type'] == 'BODY' && obj.key?('text') }
  end
```

**Describe the solution you'd like**
Add extra non-text parameter for Media-based template

<sub>[CW-1978](https://linear.app/chatwoot/issue/CW-1978/add-support-for-whatsapp-cloud-apis-media-based-message-templates-in)</sub>

**Comment by pedromoter** [comment]
Any updates on this?

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/6351
