### ISSUE TITLE
Error sending email with attachment when S3 is configured.

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#6871]
**Describe the bug**

When sending an outgoing email with an attachment, an error occurs in the console and the email is not sent to the recipient. [Inboxes::FetchImapEmailsJob] [f541fc5e-845e-483a-899b-94bcbb6e6e7b] The request signature we calculated does not match the signature you provided. Check your key and signing method.

**To Reproduce**

1. Connected S3.
2. Enable conversation continuity via email.
3. Send outgoing email with attachments, the letter is not sent with an error in the console

**Expected behavior**

I think it should be like this. When sending an outgoing email with attachments and connected S3, there should be no errors in the console, as a result, the email should be sent to the recipient via the configured smtp server

**Screenshots**

Bucket https://i.imgur.com/IvAgZFG.png
Error in console https://i.imgur.com/QjHsZgk.png

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [x] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)

**Docker** (If applicable)

Please share the output of the following.
- `docker version` 20.10.21
- `docker info`
- `docker-compose version` v2.12.2

Chatwoot v2.14.0

**Comment by pranavrajs** [comment]
@aerostovtsev Sorry about the delay here. `Chatwoot v2.14.0` is a bit old. Could you please try upgrading to 2.17.1 and see if the issue is still there?

**Comment by aerostovtsev** [comment]
Hi! Now it's usually 2.17.1, there is no error.
