### ISSUE TITLE
Rest Api agent none

### ISSUE THREAD

**Issue by josep112** [chatwoot/chatwoot#6872]
**Is your enhancement request related to a problem? Please describe.**
At the end of the service, I wanted to disconnect the agent who is in the service through the API

**Describe the solution you'd like**
https://app.chatwoot.com/api/v1/accounts/{account_id}/conversations/{conversation_id}/toggle_status
"status": "resolved"
"agent": "none"

**Describe alternatives you've considered**
Include the agent in the api as none

**Comment by pranavrajs** [comment]
@josep112 Please use this API https://www.chatwoot.com/developers/api/#tag/Conversation-Assignment/operation/assign-a-conversation to unassign an agent. 

We will not be combing the toggle_status and assignment APIs. I hope this helps.
