### ISSUE TITLE
Feature: Add French language

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#688]
Feature: Add French language

**Comment by jtraulle** [comment]
I can work on this :slightly_smiling_face:

**Comment by sojan-official** [comment]
@jtraulle  thanks a lot for offering your help. we use crowdin to manage the translations now and believe we have received some help over there already. could you double-check the translations over there before we can bring it into the codebase ? 

https://translate.chatwoot.com/chatwoot/fr

**Comment by jtraulle** [comment]
@sojan-official Thanks, I registered on crowdin and I am currently reviewing current translations :wink:

**Comment by jtraulle** [comment]
Is it possible to slightly increase the width of the sidebar from 23rem to 26rem ? "Canned response" is translated into "Réponses pré-enregistrées" or, shorter by "Réponses standardisées". But 23rem is not enough. As well as "Account Settings" -> "Paramètres du compte" and "Inboxes" -> "Boîtes de réception"

|                  | 23rem | 26rem |
|------------------|---------|--------|
| **Main** sidebar | ![main-sidebar-23rem](https://user-images.githubusercontent.com/613615/79697564-c83d2b00-8283-11ea-87ee-ae798fbaf058.png) | ![main-sidebar-26rem](https://user-images.githubusercontent.com/613615/79697570-cd9a7580-8283-11ea-8fd1-5f1cf2206604.png) |
| **Settings** sidebar | ![settings-sidebar-23rem](https://user-images.githubusercontent.com/613615/79697577-ddb25500-8283-11ea-993e-6b41c8640d46.png) | ![settings-sidebar-26rem](https://user-images.githubusercontent.com/613615/79697583-e440cc80-8283-11ea-8673-b1b33d569e90.png) |

**Comment by jtraulle** [comment]
I just finished the review :tada:
