### ISSUE TITLE
One-off campaigns through email instead of email

### ISSUE THREAD

**Issue by VSinghhh** [chatwoot/chatwoot#6891]
**Is your feature request related to a problem? Please describe.**
We want to email all of our customers in chatwoot an informational message. While the one-off campaigns could support it, it seems that they only support sending of SMS rather than email

**Describe the solution you'd like**
Add support to do one-off campaigns through email and not sms

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pranavrajs** [comment]
@VSinghhh At the moment, we don't intend to build the campaigns on email as it is a bigger product by itself. Even without the campaigns in email, the Spam rates are trouble for us. We will let you know if it becomes a priority later.

**Comment by VSinghhh** [comment]
Makes perfect sense! 
One idea that I thought of afterwards was that self-hosted instances could input their own SMTP-details (i.e the tarnish their own reputation If they engage in spam) - but it makes perfect sense for this solution not to have it, as well 👍

**Comment by pranavrajs** [comment]
@VSinghhh  _self-hosted instances could input their own SMTP-details_. This makes sense, however if we can put in our cloud then the effort is of no use, right? :)

**Comment by VSinghhh** [comment]
Very very true!
