### ISSUE TITLE
[CW-1541] Adding dynamic fields to channel greeting and business hours

### ISSUE THREAD

**Issue by estherrath36** [chatwoot/chatwoot#6910]
**Is your enhancement request related to a problem? Please describe.**
You currently have dynamic fields for canned responses and text editor, I would like the same functionality to be added to the channel greeting and business hours messages. Our channel greeting is very impersonal starting with something like "Hi there" or not addressing the customer at all. For business hours there is also no personality or humanity to the messages we are able to write. They are generic and don't feel very nice.

**Describe the solution you'd like**
I would like to have the option to add dynamic fields to the channel greeting and business hours set messages. For instance a channel greeting might say: 

"Hi {first name}, thanks for reaching out! We're currently taking about 10 minutes to ...."

and a business hours message out of hours might say:
"Hi {first name}, you've written in outside of our usual business hours ... " another variable for this example could be changing the opening hours to the customers timezone (if different)

<sub>[CW-1541](https://linear.app/chatwoot/issue/CW-1541/adding-dynamic-fields-to-channel-greeting-and-business-hours)</sub>

**Comment by pranavrajs** [comment]
@muhsin-k Don't we support this already via [https://github.com/chatwoot/chatwoot/pull/6215](https://github.com/chatwoot/chatwoot/pull/6215)? I tested both of these cases, it doesn't seem to be working properly. Can you please take a look?

![Screenshot 2023-04-17 at 3.52.47 PM.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/cac598b5-ac3e-426e-a3a9-5cd0b769b04a/bdd85462-bfc0-4467-8b18-d9414c15b723)

**Comment by tejaswinichile** [comment]
@pranavrajs @sojan-official I want to show allowed variable in greeting template like

{{inbox.name}}, {{account.name}} and {{contact.name}} where should I put this information.

Should this be a part of document are help text?

**Comment by sojan-official** [comment]
![Screenshot 2023-04-25 at 4.01.57 PM.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/e0c24d92-9ee0-4356-8cce-a51d755b725e/cf91ce95-15c1-4bab-884e-2b9a4185d22d)

@tejaswinichile  can't this be a part of the editor like how we handle in other areas. if some one opens up the {{ it lists out all the available options ? 

cc: @muhsin-k

**Comment by muhsin-k** [comment]
Yup. Our editor support the variable select option. @tejaswinichile I can help you on this.

**Comment by tejaswinichile** [comment]
@muhsin-k If we can add this that would be great 👍 Can you enable it in this PR for greeting message editor box.
