### ISSUE TITLE
Feature: Add Korean language

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#692]
Feature: Add Korean language

**Comment by pranavrajs** [comment]
https://translate.chatwoot.com

**Comment by amblerkr** [comment]
> Closing as the translations are moved to https://translate.chatwoot.com

I added a Korean translation. Could you add Korean to the site?
https://translate.chatwoot.com/chatwoot/ko

**Comment by pranavrajs** [comment]
@amblerkr Sure will do.

**Comment by amblerkr** [comment]
> @amblerkr Sure will do.

thanks. If Korean is supported, I will promote this service widely.

**Comment by sojan-official** [comment]
@amblerkr We have enabled Korean on the latest release. Thanks a lot for the translations. Do let us know if you find something missing :D

**Comment by amblerkr** [comment]
> @amblerkr We have enabled Korean on the latest release. Thanks a lot for the translations. Do let us know if you find something missing :D

thanks. 
By the way, can I change the front phrase of the chat window? I've changed it a bit more smoothly.
Typically 일반적으로 → 보통
