### ISSUE TITLE
Feature: Add Portuguese language

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#693]
Feature: Add Portuguese language

**Comment by robson-jardim** [comment]
I'd like to work on this feature. What is the best way to contribute?

**Comment by pranavrajs** [comment]
@robson-jardim Thanks for taking an interest in the contribution. I will try to write a guideline on how to contribute to languages by tonight. 

Meanwhile, you can start with the following. 

The dashboard uses the language files in the directory app/javascript/dashboard/i18n/locale

https://github.com/chatwoot/chatwoot/tree/develop/app/javascript/dashboard/i18n/locale

Backend uses https://github.com/chatwoot/chatwoot/tree/develop/config/locales

you could make a copy of the en folder, rename it to `pt`

**Comment by robson-jardim** [comment]
Great! I'll be starting right now!

I'd like to become part of the ChatWoot team. I think we have a great space to grow in Brazil. 

How can I be part of that?

**Comment by kimus** [comment]
please distinguish between `pt` (`pt-pt`) and `pt-br`.

**Comment by pranavrajs** [comment]
@kimus We were not aware of this variant. Thanks for informing this. We will add the variants also in the supported list of languages.

**Comment by pranavrajs** [comment]
@robson-jardim Could you please schedule a call here? https://calendly.com/chatwoot

We would like to chat about how we can take this forward.

**Comment by sojan-official** [comment]
https://translate.chatwoot.com/ is available in case someone wants to work on this using a UI tool.

**Comment by robson-jardim** [comment]
It's done! Pls, let me know if it's ok. 
Best Regards.

**Comment by robson-jardim** [comment]
> https://translate.chatwoot.com/ is available in case someone wants to work on this using a UI tool.

Done! Pls, let me know if it's ok.
Best Regards.

**Comment by robson-jardim** [comment]
Hello @pranavrajs , could you tell me if the translation was ok? 

Best Regards.

**Comment by pranavrajs** [comment]
@robson-jardim We will bring that up to the codebase and see if something is missing.

**Comment by robson-jardim** [comment]
> @robson-jardim We will bring that up to the codebase and see if something is missing.

Thanks a lot!
