### ISSUE TITLE
Error creating Telegram channel Webhook version v2.16.0 Chatwoot

### ISSUE THREAD

**Issue by mane06** [chatwoot/chatwoot#6936]
**Describe the bug**

Hello, when I register a telegram channel, the process does not seem to finish correctly, but the Webhook does not register and therefore does not receive the messages from the bot channel.

in the logs I see this line but I am not sure if it is the problem and if it is how to solve it

**Server logs**
```
Apr 19 19:22:17 localhost chatwoot-worker.1[37755]: I, [2023-04-19T19:22:17.571045 #37755]  INFO -- : [ActiveJob] [EventDispatcherJob] [687959ff-3139-47b9-8ce9-6a72e6de8554] Performing EventDispatcherJob (Job ID: 687959ff-3139-47b9-8ce9-6a72e6de8554) from Sidekiq(events) enqueued at 2023-04-19T19:22:17Z with arguments: "account.cache_invalidated", Wed, 19 Apr 2023 19:22:17.555539183 UTC +00:00, {:cache_keys=>{:label=>"0000000000", :inbox=>"1681932137", :team=>"0000000000"}, :account=>#<GlobalID:0x00007f2ac498adc8 @uri=#<URI::GID gid://chatwoot/Account/1>>}
Apr 19 19:22:17 localhost chatwoot-worker.1[37755]: I, [2023-04-19T19:22:17.571483 #37755]  INFO -- : [ActiveJob] [EventDispatcherJob] [687959ff-3139-47b9-8ce9-6a72e6de8554] Performed EventDispatcherJob (Job ID: 687959ff-3139-47b9-8ce9-6a72e6de8554) from Sidekiq(events) in 0.16ms
Apr 19 19:22:17 localhost chatwoot-worker.1[37755]: {"ts":"2023-04-19T19:22:17.571Z","pid":37755,"tid":"1mkz","lvl":"INFO","msg":"done","ctx":{"class":"EventDispatcherJob","jid":"feb8389157fb635769695f2f","elapsed":0.004}}
```
**Environment**

- - [x] Linux VM

**Desktop (please complete the following information)** (If applicable)
 - OS: MacOS
 - Browser: chrome

**Comment by pranavrajs** [comment]
@mane06 The logs shared don't indicate any errors. Can you please try again and share the relevant parts of the logs related to the inbox creation?

**Comment by mane06** [comment]
Hi, sorry I haven't answered before, I hope I didn't find a solution and it seems that it's not an issue with which the webhook is not registered, but I haven't been able to get it to work, when I check if the webhook is registered it shows me this:

{"ok":true,"result":{"url":"","has_custom_certificate":false,"pending_update_count":0}}

This is the worker log when creating the Telegram channel:

Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.284205 #140086]  INFO -- : [ActiveJob] [Channels::Whatsapp::TemplatesSyncSchedulerJob] [1fde72b4-f1fd-49bd-87e7-5ff3eb47d267] Performing Channels::Whatsapp::TemplatesSyncSchedulerJob (Job ID: 1fde72b4-f1fd-49bd-87e7-5ff3eb47d267) from Sidekiq(low) enqueued at 2023-04-27T18:25:07Z
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.281334 #140086]  INFO -- : [ActiveJob] [Account::ConversationsResolutionSchedulerJob] [cfa731f7-7786-4645-8822-52b1840529d2] Performing Account::ConversationsResolutionSchedulerJob (Job ID: cfa731f7-7786-4645-8822-52b1840529d2) from Sidekiq(scheduled_jobs) enqueued at 2023-04-27T18:25:07Z
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.287314 #140086]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [79b85e0c-ee7f-44c4-9a8f-6caf070c29bf] Enqueued Inboxes::FetchImapEmailsJob (Job ID: 1eff56a8-98b6-452d-91c0-a1f27345a847) to Sidekiq(low) with arguments: #<GlobalID:0x00007f27080062a8 @uri=#<URI::GID gid://chatwoot/Channel::Email/2>>
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.288977 #140086]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [79b85e0c-ee7f-44c4-9a8f-6caf070c29bf] Performed Inboxes::FetchImapEmailInboxesJob (Job ID: 79b85e0c-ee7f-44c4-9a8f-6caf070c29bf) from Sidekiq(scheduled_jobs) in 11.72ms
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.289Z","pid":140086,"tid":"50y6","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"f6d782f6360b5a367bd39f8d"}}
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.292Z","pid":140086,"tid":"521q","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"1a9f5b0314e120d11e0cda91","elapsed":0.018}}
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.288783 #140086]  INFO -- : [ActiveJob] [Channels::Whatsapp::TemplatesSyncSchedulerJob] [1fde72b4-f1fd-49bd-87e7-5ff3eb47d267] Performed Channels::Whatsapp::TemplatesSyncSchedulerJob (Job ID: 1fde72b4-f1fd-49bd-87e7-5ff3eb47d267) from Sidekiq(low) in 4.49ms
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.295Z","pid":140086,"tid":"51z2","lvl":"INFO","msg":"done","ctx":{"class":"Channels::Whatsapp::TemplatesSyncSchedulerJob","jid":"dc832d6b4215b1e82c406a58","elapsed":0.011}}
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.291353 #140086]  INFO -- : [ActiveJob] [Conversations::ReopenSnoozedConversationsJob] [a395f104-0665-4eb8-99f6-d83b54023c52] Performed Conversations::ReopenSnoozedConversationsJob (Job ID: a395f104-0665-4eb8-99f6-d83b54023c52) from Sidekiq(low) in 8.54ms
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.295Z","pid":140086,"tid":"52wq","lvl":"INFO","msg":"done","ctx":{"class":"Conversations::ReopenSnoozedConversationsJob","jid":"6baf24340116552a08feaabf","elapsed":0.016}}
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.307488 #140086]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [1eff56a8-98b6-452d-91c0-a1f27345a847] Performing Inboxes::FetchImapEmailsJob (Job ID: 1eff56a8-98b6-452d-91c0-a1f27345a847) from Sidekiq(low) enqueued at 2023-04-27T18:25:07Z with arguments: #<GlobalID:0x00007f27033c6f00 @uri=#<URI::GID gid://chatwoot/Channel::Email/2>>
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.316362 #140086]  INFO -- : [ActiveJob] [Account::ConversationsResolutionSchedulerJob] [cfa731f7-7786-4645-8822-52b1840529d2] Performed Account::ConversationsResolutionSchedulerJob (Job ID: cfa731f7-7786-4645-8822-52b1840529d2) from Sidekiq(scheduled_jobs) in 31.82ms
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.316Z","pid":140086,"tid":"52qi","lvl":"INFO","msg":"done","ctx":{"class":"Account::ConversationsResolutionSchedulerJob","jid":"190d7468e15ca486e7d33924","elapsed":0.036}}
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:07.721950 #140086]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [1eff56a8-98b6-452d-91c0-a1f27345a847] Performed Inboxes::FetchImapEmailsJob (Job ID: 1eff56a8-98b6-452d-91c0-a1f27345a847) from Sidekiq(low) in 414.32ms
Apr 27 18:25:07 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:07.722Z","pid":140086,"tid":"50y6","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"f6d782f6360b5a367bd39f8d","elapsed":0.433}}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:10.287Z","pid":140086,"tid":"52ye","lvl":"INFO","msg":"start","ctx":{"class":"ActionCableBroadcastJob","jid":"7dc9b3fb5d519aa507cfbcae"}}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:10.288150 #140086]  INFO -- : [ActiveJob] [ActionCableBroadcastJob] [828862b9-bff7-4134-bd67-17270bded335] Performing ActionCableBroadcastJob (Job ID: 828862b9-bff7-4134-bd67-17270bded335) from Sidekiq(default) enqueued at 2023-04-27T18:25:10Z with arguments: ["MroQaSHXdZe22xe6Ro5uLmyN", "i8YKozwR4ngfPBLyzgmAm9qu", "ixjcHdpk9JjK85EvDMuHPxCk"], "account.cache_invalidated", {:cache_keys=>{:label=>"0000000000", :inbox=>"1682619910", :team=>"0000000000"}, :account_id=>1, :performer=>{:id=>1, :name=>"Manuel", :available_name=>"Manuel", :avatar_url=>"", :type=>"user", :availability_status=>"online", :thumbnail=>""}}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:10.289635 #140086]  INFO -- : [ActiveJob] [ActionCableBroadcastJob] [828862b9-bff7-4134-bd67-17270bded335] Performed ActionCableBroadcastJob (Job ID: 828862b9-bff7-4134-bd67-17270bded335) from Sidekiq(default) in 0.94ms
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:10.289Z","pid":140086,"tid":"534i","lvl":"INFO","msg":"start","ctx":{"class":"EventDispatcherJob","jid":"1f23f4ee7111edfca2d40dc5"}}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:10.291Z","pid":140086,"tid":"52ye","lvl":"INFO","msg":"done","ctx":{"class":"ActionCableBroadcastJob","jid":"7dc9b3fb5d519aa507cfbcae","elapsed":0.004}}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:10.293571 #140086]  INFO -- : [ActiveJob] [EventDispatcherJob] [4a6234f5-a0ba-44b9-b1f6-a8be869d4094] Performing EventDispatcherJob (Job ID: 4a6234f5-a0ba-44b9-b1f6-a8be869d4094) from Sidekiq(events) enqueued at 2023-04-27T18:25:10Z with arguments: "account.cache_invalidated", Thu, 27 Apr 2023 18:25:10.280903946 UTC +00:00, {:cache_keys=>{:label=>"0000000000", :inbox=>"1682619910", :team=>"0000000000"}, :account=>#<GlobalID:0x00007f2703176cf0 @uri=#<URI::GID gid://chatwoot/Account/1>>}
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: I, [2023-04-27T18:25:10.293803 #140086]  INFO -- : [ActiveJob] [EventDispatcherJob] [4a6234f5-a0ba-44b9-b1f6-a8be869d4094] Performed EventDispatcherJob (Job ID: 4a6234f5-a0ba-44b9-b1f6-a8be869d4094) from Sidekiq(events) in 0.14ms
Apr 27 18:25:10 localhost chatwoot-worker.1[140086]: {"ts":"2023-04-27T18:25:10.293Z","pid":140086,"tid":"534i","lvl":"INFO","msg":"done","ctx":{"class":"EventDispatcherJob","jid":"1f23f4ee7111edfca2d40dc5","elapsed":0.004}}

This is the log of the web app when creating the Telegram channel:

Apr 27 18:25:15 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:15.059474 #139960]  INFO -- : RoomChannel#update_presence
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.571940 #139960]  INFO -- : source=rack-timeout id=e7cff18f-adfa-4534-a529-40c387192907 timeout=15000ms state=ready
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.572289 #139960]  INFO -- : [e7cff18f-adfa-4534-a529-40c387192907] Started PATCH "/api/v1/accounts/1/inbox_members" for 189.243.57.83 at 2023-04-27 18:25:19 +0000
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.575492 #139960]  INFO -- : [e7cff18f-adfa-4534-a529-40c387192907] Processing by Api::V1::Accounts::InboxMembersController#update as JSON
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.575571 #139960]  INFO -- : [e7cff18f-adfa-4534-a529-40c387192907]   Parameters: {"inbox_id"=>11, "user_ids"=>[2, 1, 3], "account_id"=>"1", "inbox_member"=>{"inbox_id"=>11}}
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.614689 #139960]  INFO -- : [e7cff18f-adfa-4534-a529-40c387192907]   Rendered api/v1/accounts/inbox_members/update.json.jbuilder (Duration: 10.6ms | Allocations: 3352)
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.615958 #139960]  INFO -- : [e7cff18f-adfa-4534-a529-40c387192907] Completed 200 OK in 40ms (Views: 9.3ms | ActiveRecord: 10.8ms | Allocations: 12030)
Apr 27 18:25:19 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:19.616475 #139960]  INFO -- : source=rack-timeout id=e7cff18f-adfa-4534-a529-40c387192907 timeout=15000ms service=45ms state=completed
Apr 27 18:25:35 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:35.061072 #139960]  INFO -- : RoomChannel#update_presence
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.499570 #139960]  INFO -- : source=rack-timeout id=d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d timeout=15000ms state=ready
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.502021 #139960]  INFO -- : source=rack-timeout id=5c45e181-9da2-47d6-9bf2-675a01ee9313 timeout=15000ms state=ready
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.503069 #139960]  INFO -- : [5c45e181-9da2-47d6-9bf2-675a01ee9313] Started GET "/api/v1/accounts/1/dashboard_apps" for 189.243.57.83 at 2023-04-27 18:25:40 +0000
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.503742 #139960]  INFO -- : source=rack-timeout id=705c205d-4caa-4843-b7b4-70bacc95dcf1 timeout=15000ms state=ready
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.504779 #139960]  INFO -- : [d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d] Started GET "/api/v1/accounts/1/conversations?inbox_id=11&status=open&assignee_type=me&page=1" for 189.243.57.83 at 2023-04-27 18:25:40 +0000
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.505748 #139960]  INFO -- : [705c205d-4caa-4843-b7b4-70bacc95dcf1] Started GET "/api/v1/accounts/1/agents" for 189.243.57.83 at 2023-04-27 18:25:40 +0000
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.508535 #139960]  INFO -- : [5c45e181-9da2-47d6-9bf2-675a01ee9313] Processing by Api::V1::Accounts::DashboardAppsController#index as JSON
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.510300 #139960]  INFO -- : [5c45e181-9da2-47d6-9bf2-675a01ee9313]   Parameters: {"account_id"=>"1"}
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.510051 #139960]  INFO -- : [d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d] Processing by Api::V1::Accounts::ConversationsController#index as JSON
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.511614 #139960]  INFO -- : [d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d]   Parameters: {"inbox_id"=>"11", "status"=>"open", "assignee_type"=>"me", "page"=>"1", "account_id"=>"1"}
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.514356 #139960]  INFO -- : source=rack-timeout id=02d20727-64a1-47aa-96f8-07c77ab345da timeout=15000ms state=ready
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.515360 #139960]  INFO -- : [705c205d-4caa-4843-b7b4-70bacc95dcf1] Processing by Api::V1::Accounts::AgentsController#index as JSON
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.516720 #139960]  INFO -- : [705c205d-4caa-4843-b7b4-70bacc95dcf1]   Parameters: {"account_id"=>"1"}
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.521692 #139960]  INFO -- : [02d20727-64a1-47aa-96f8-07c77ab345da] Started GET "/api/v1/accounts/1/custom_filters?filter_type=conversation" for 189.243.57.83 at 2023-04-27 18:25:40 +0000
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.526300 #139960]  INFO -- : [5c45e181-9da2-47d6-9bf2-675a01ee9313]   Rendered api/v1/accounts/dashboard_apps/index.json.jbuilder (Duration: 1.1ms | Allocations: 196)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.530987 #139960]  INFO -- : [02d20727-64a1-47aa-96f8-07c77ab345da] Processing by Api::V1::Accounts::CustomFiltersController#index as JSON
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.531047 #139960]  INFO -- : [02d20727-64a1-47aa-96f8-07c77ab345da]   Parameters: {"filter_type"=>"conversation", "account_id"=>"1"}
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.534231 #139960]  INFO -- : [5c45e181-9da2-47d6-9bf2-675a01ee9313] Completed 200 OK in 24ms (Views: 3.7ms | ActiveRecord: 12.2ms | Allocations: 9182)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.535052 #139960]  INFO -- : source=rack-timeout id=5c45e181-9da2-47d6-9bf2-675a01ee9313 timeout=15000ms service=33ms state=completed
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.573838 #139960]  INFO -- : [705c205d-4caa-4843-b7b4-70bacc95dcf1]   Rendered api/v1/accounts/agents/index.json.jbuilder (Duration: 15.7ms | Allocations: 5966)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.578545 #139960]  INFO -- : [d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d]   Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 2.5ms | Allocations: 880)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.579147 #139960]  INFO -- : [705c205d-4caa-4843-b7b4-70bacc95dcf1] Completed 200 OK in 62ms (Views: 11.4ms | ActiveRecord: 24.1ms | Allocations: 20549)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.580997 #139960]  INFO -- : source=rack-timeout id=705c205d-4caa-4843-b7b4-70bacc95dcf1 timeout=15000ms service=77ms state=completed
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.582706 #139960]  INFO -- : [d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d] Completed 200 OK in 71ms (Views: 2.0ms | ActiveRecord: 30.7ms | Allocations: 24114)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.585117 #139960]  INFO -- : source=rack-timeout id=d52bbe0e-4ec2-4b1e-acf7-9fa735160f0d timeout=15000ms service=86ms state=completed
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.586498 #139960]  INFO -- : [02d20727-64a1-47aa-96f8-07c77ab345da]   Rendered api/v1/accounts/custom_filters/index.json.jbuilder (Duration: 2.1ms | Allocations: 567)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.588397 #139960]  INFO -- : [02d20727-64a1-47aa-96f8-07c77ab345da] Completed 200 OK in 57ms (Views: 1.8ms | ActiveRecord: 18.8ms | Allocations: 18988)
Apr 27 18:25:40 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:40.589303 #139960]  INFO -- : source=rack-timeout id=02d20727-64a1-47aa-96f8-07c77ab345da timeout=15000ms service=75ms state=completed
Apr 27 18:25:55 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:25:55.059952 #139960]  INFO -- : RoomChannel#update_presence
Apr 27 18:26:16 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:26:16.456730 #139960]  INFO -- : RoomChannel#update_presence
Apr 27 18:26:37 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:26:37.453689 #139960]  INFO -- : RoomChannel#update_presence
Apr 27 18:26:55 localhost chatwoot-web.1[139960]: I, [2023-04-27T18:26:55.450555 #139960]  INFO -- : RoomChannel#update_presence

and this is the response from the webhook after sending /start:

{"ok":true,"result":{"url":"","has_custom_certificate":false,"pending_update_count":1}}

I use this url to know the status of the webhook:
GET https://api.telegram.org/bot{your_bot_token}/getWebhookInfo
