### ISSUE TITLE
[CW-1579] Improving automatic replies UX

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#6945]
Automatic replies are best when they do not feel automatic. Here are a few ideas and designs to that end:

a) Have an option to trigger automatic responses after a set amount of time (instead of firing them instantly). On top of this, add an option to entirely skip an automatic responses, when an agent interacts with the conversation before the timer runs out. When an agent is available and engaged, a lot of automatic responses (i.e. "we will look into this and get back to you") do not make a lot of sense and just feel off.

This could both be implemented by a "Timer" condition with a checkbox to cancel on agent interaction. It feels like there might be a more general abstraction I am missing, but I think this would work and seems like a good upgrade over the status quo.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1176036/233368915-238c4197-bd52-4ab5-afd5-f58cfc1bf66b.png">

c) Being able to add some language fuzziness to automatic replies, by cycling between semantically identical versions (i.e. "hello, how can we help", "hi, what can we do for you")

<img width="878" alt="image" src="https://user-images.githubusercontent.com/1176036/233371896-3aa85c4d-fa7a-4ea4-8158-d60bc568020b.png">

After clicking "Add variant"

<img width="885" alt="image" src="https://user-images.githubusercontent.com/1176036/233371737-d0c24d09-3562-4089-84c7-49a8ffb3eb41.png">

<sub>[CW-1579](https://linear.app/chatwoot/issue/CW-1579/improving-automatic-replies-ux)</sub>

**Comment by vishnu-narayanan** [comment]
@jochenstu Thank you for the feature request.

**Comment by scmmishra** [comment]
@pranavrajs PTAL and see if we need to prioritise this.

**Comment by pranavrajs** [comment]
@scmmishra @tejaswinichile Can we combine this with time-based automations as requested in [CW-1563](https://linear.app/chatwoot/issue/CW-1563/move-conversation-resolution-to-automations)?
