### ISSUE TITLE
send an audio that can be opened with a player

### ISSUE THREAD

**Issue by douglasalves0** [chatwoot/chatwoot#6954]
I saw [this](https://github.com/chatwoot/chatwoot/issues/1458) issue on github, but didn't see a way that I can do this on chatwoot docs or chatwoot postman.

I saw [this](https://www.postman.com/chatwoot/workspace/chatwoot-apis/request/162770-e22922ab-27e5-4d82-a672-a52f6555ed21) post example to send a file, but always that I send an audio like that the audio appears on the UI like a common file that has no player.

So, there is some way that I can send an audio that can be opened with a play button and not by downloading it and playing locally?

**Comment by glauberssoutodossantos** [comment]
Hi @douglasalves0 how are you?

I have this python function here that works fine to me.

```
def send_audio(audio, conversation_id, fromMe):
    global account_id
    message_type = 'incoming'
    private = False
    content = ''
    if fromMe:
      message_type = 'outgoing'
    files = {
        "attachments[]": (
            'audio.oga',b64decode(audio),'audio/mpeg'
        ),
    }
    response = requests.post(
        base_url+ str(account_id) + '/conversations/' + str(conversation_id) + '/messages',
        files = files, 
        data = {
            'message_type': message_type,
            'file_type':'audio',
            'private':private,
            'content': content
        },
        headers = {'api_access_token': userApiKey}, 
    )
```

**Comment by glauberssoutodossantos** [comment]
if your audio is from a web url use this.

```
response = requests.get(audio_url)
audio = base64.b64encode(response.content)
send_audio(audio, conversation_id, fromMe)
```

**Comment by douglasalves0** [comment]
Yeah, I see now, I was having trouble trying to send a .ogg file, it seems that chatwoot cannot handle with that, but when I tried to send a .mp3 file it worked, it seems that I'll have to convert the file before try to send it.

Thank you.
