### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by mattos123** [chatwoot/chatwoot#6965]
while compiling i got a break error from the compiler, heres the log
<br />
[5/5] Building fresh packages...
Done in 7.38s.
Compiling...
Compilation failed:
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/chatwoot/chatwoot/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/chatwoot/chatwoot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/chatwoot/chatwoot/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0

**Comment by vishnu-narayanan** [comment]
@mattos123 Could you please share the following?

```
**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)


**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, firefox, safari]
 - Version [e.g. 22]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

Add any other context about the problem here.

```

**Comment by mattos123** [comment]
Browserslist: caniuse-lite is outdated. Please run:

> lem here.

> @mattos123 Could you please share the following?
> 
> ```
> **Describe the bug**
> 
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 1- ./install.sh --install
> 2- no dns
> 3- install dependencies
> 
> **Expected behavior**
> 
> expected to compile the web aplication
> 
> **Screenshots**
> 
> none
> 
> **Browser logs**
> 
> none
> 
> **Server logs**
> 
> none
> 
> **Environment**
> 
> Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).
> 
> - [ ] app.chatwoot.com (Chatwoot Cloud)
> - [x] Self-hosted
> - - [x] Linux VM
> - - [ ] Docker
> - - [ ] Kubernetes
> - - [ ] Heroku
> - - [ ] Other (Please specify)
> 
> 
> **Desktop (please complete the following information)** (If applicable)
> none
> 
> **Smartphone (please complete the following information)** (If applicable)
> none
> 
> **Docker** (If applicable)
> none
> 
> **Cloud Provider** (If applicable)
> - [ ] AWS
> - [ ] GCP
> - [ ] Azure
> - [ ] DigitalOcean
> - [x] Others
> 
> **Additional context**
> 
> full log on next answer
> ```

**Comment by mattos123** [comment]
Browserslist: caniuse-lite is outdated. Please run:

> lem here.

> @mattos123 Could you please share the following?
> 
> ```
> **Describe the bug**
> 
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 1- ./install.sh --install
> 2- no dns
> 3- install dependencies
> 
> **Expected behavior**
> 
> expected to compile the web aplication
> 
> **Screenshots**
> 
> none
> 
> **Browser logs**
> 
> none
> 
> **Server logs**
> 
> none
> 
> **Environment**
> 
> Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).
> 
> - [ ] app.chatwoot.com (Chatwoot Cloud)
> - [x] Self-hosted
> - - [x] Linux VM
> - - [ ] Docker
> - - [ ] Kubernetes
> - - [ ] Heroku
> - - [ ] Other (Please specify)
> 
> 
> **Desktop (please complete the following information)** (If applicable)
> none
> 
> **Smartphone (please complete the following information)** (If applicable)
> none
> 
> **Docker** (If applicable)
> none
> 
> **Cloud Provider** (If applicable)
> - [ ] AWS
> - [ ] GCP
> - [ ] Azure
> - [ ] DigitalOcean
> - [x] Others
> 
> **Additional context**
> 
> full log on next answer
> ```

**Comment by mattos123** [comment]
Bundle complete! 118 Gemfile dependencies, 301 gems now installed.  
Use \`bundle info \[gemname\]\` to see where a bundled gem is installed.  
1 installed gem you directly depend on is looking for funding.  
 Run \`bundle fund\` for details  
yarn install v1.22.19  
\[1/5\] Validating package.json...  
\[2/5\] Resolving packages...  
\[3/5\] Fetching packages...  
\[4/5\] Linking dependencies...  
warning "@chatwoot/prosemirror-schema > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".  
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".  
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".  
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".  
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".  
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".  
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@\*".  
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".  
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".  
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".  
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".  
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".  
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".  
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@\*".  
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@\*".  
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".  
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".  
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".  
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".  
\[5/5\] Building fresh packages...  
$ husky install  
husky - Git hooks installed  
Done in 115.23s.  
yarn install v1.22.19  
\[1/5\] Validating package.json...  
\[2/5\] Resolving packages...  
\[3/5\] Fetching packages...  
\[4/5\] Linking dependencies...  
warning "@chatwoot/prosemirror-schema > prosemirror-utils@0.9.6" has incorrect peer dependency "prosemirror-tables@^0.9.1".  
warning " > babel-loader@8.2.2" has unmet peer dependency "webpack@>=2".  
warning " > foundation-sites@6.5.3" has unmet peer dependency "jquery@>=2.2.0".  
warning " > foundation-sites@6.5.3" has unmet peer dependency "what-input@>=4.1.0".  
warning " > url-loader@2.3.0" has unmet peer dependency "webpack@^4.0.0".  
warning " > vue-easytable@2.5.5" has unmet peer dependency "lodash@^4.17.20".  
warning " > vue-loader@15.9.6" has unmet peer dependency "css-loader@\*".  
warning " > vue-loader@15.9.6" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".  
warning " > vuex-router-sync@4.1.3" has incorrect peer dependency "vue-router@^2.0.0".  
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning " > @storybook/addons@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/api@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/theming@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".  
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-links > @storybook/router@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@15.5.0" has unmet peer dependency "react@>= 0.14.0".  
warning "@storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".  
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/core-common@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/preview-web@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/source-loader@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > @storybook/store@6.5.9" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".  
warning "@storybook/addon-docs > babel-loader@8.2.5" has unmet peer dependency "webpack@>=2".  
warning " > @storybook/vue@6.5.9" has unmet peer dependency "css-loader@\*".  
warning "@storybook/vue > ts-loader@8.2.0" has unmet peer dependency "typescript@\*".  
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".  
warning " > eslint-import-resolver-webpack@0.11.1" has unmet peer dependency "webpack@>=1.11.0".  
warning "eslint-plugin-storybook > @typescript-eslint/experimental-utils > @typescript-eslint/utils > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".  
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".  
\[5/5\] Building fresh packages...  
Done in 57.59s.  
Compiling...  
Compilation failed:  
Browserslist: caniuse-lite is outdated. Please run:  
npx browserslist@latest --update-db

Why you should do it regularly:  
https://github.com/browserslist/browserslist#browsers-data-updating

warn - The \`conservative\` purge mode will be removed in Tailwind 2.0.  
warn - Please switch to the new \`layers\` mode instead.
