### ISSUE TITLE
bug: video attachment does not load in chrome - docker installation

### ISSUE THREAD

**Issue by Bravo0795** [chatwoot/chatwoot#6969]
**Describe the bug**

We have an integration with whatsapp and the issue is with video. Client send us video and we can watch it, but we can`t watch it later. 
This problem is only in Chrome, in Mozilla it works fine.

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/131441904/234034224-3b0d719a-afea-47bd-99b6-1f9fc0a96c79.png)
![image](https://user-images.githubusercontent.com/131441904/234034556-12b2a4cd-0bfa-43ae-bd42-5fa019ff3d2f.png)

**Browser logs**
```
Failed to load resource: the server responded with a status of 404 ()
https://example.com/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhhalJvYlhsc09HaHBlSFJ2WVRkck1IWndlRFZvYW1KeWRtNWhPQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpWDJGMGRHRmphRzFsYm5RN0lHWnBiR1Z1WVcxbFBTSTVOVEZqTkdSaVltSmpOR1ZtTXpGaU5HVTFPRFkzTlRFaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6azFNV00wWkdKaVltTTBaV1l6TVdJMFpUVTROamMxTVFZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURuWnBaR1Z2TDIxd05BWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjMtMDQtMjRUMTQ6MDE6MTguODgzWiIsInB1ciI6ImJsb2Jfa2V5In19--3848e750456bcd02a2a7221283a4a67f4c9058e3/951c4dbbbc4ef31b4e586751
```

Share the browser logs to debug the issue further.

**Server logs**  _ip is changed it is not real ip_
```
I, [2023-04-24T13:56:37.231567 #1]  INFO -- : [b4329a7f-b6e8-4012-9d82-8b2cd2962817] Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3NSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96e069b360add5055b448449f75d322aa5dc5ab4/951c4dbbbc4ef31b4e586751" for 10.10.10.10 at 2023-04-24 13:56:37 +0000
I, [2023-04-24T13:56:37.235929 #1]  INFO -- : [b4329a7f-b6e8-4012-9d82-8b2cd2962817] Processing by ActiveStorage::Blobs::RedirectController#show as */*
I, [2023-04-24T13:56:37.236011 #1]  INFO -- : [b4329a7f-b6e8-4012-9d82-8b2cd2962817]   Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ3NSIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--96e069b360add5055b448449f75d322aa5dc5ab4", "filename"=>"951c4dbbbc4ef31b4e586751"}


I, [2023-04-24T13:56:37.247602 #1]  INFO -- : [b4329a7f-b6e8-4012-9d82-8b2cd2962817] Redirected to https://example.com/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhhalJvYlhsc09HaHBlSFJ2WVRkck1IWndlRFZvYW1KeWRtNWhPQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpWDJGMGRHRmphRzFsYm5RN0lHWnBiR1Z1WVcxbFBTSTVOVEZqTkdSaVltSmpOR1ZtTXpGaU5HVTFPRFkzTlRFaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6azFNV00wWkdKaVltTTBaV1l6TVdJMFpUVTROamMxTVFZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURuWnBaR1Z2TDIxd05BWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjMtMDQtMjRUMTQ6MDE6MzcuMjQ2WiIsInB1ciI6ImJsb2Jfa2V5In19--98f18c00a454c2e19260f94e34d83d8891a99b28/951c4dbbbc4ef31b4e586751


I, [2023-04-24T13:56:37.321238 #1]  INFO -- : [6d167d02-6bb7-486c-bbbf-72858d75280f] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhhalJvYlhsc09HaHBlSFJ2WVRkck1IWndlRFZvYW1KeWRtNWhPQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpWDJGMGRHRmphRzFsYm5RN0lHWnBiR1Z1WVcxbFBTSTVOVEZqTkdSaVltSmpOR1ZtTXpGaU5HVTFPRFkzTlRFaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6azFNV00wWkdKaVltTTBaV1l6TVdJMFpUVTROamMxTVFZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURuWnBaR1Z2TDIxd05BWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjMtMDQtMjRUMTQ6MDE6MzcuMjQ2WiIsInB1ciI6ImJsb2Jfa2V5In19--98f18c00a454c2e19260f94e34d83d8891a99b28/951c4dbbbc4ef31b4e586751" for 10.10.10.10 at 2023-04-24 13:56:37 +0000
I, [2023-04-24T13:56:37.325100 #1]  INFO -- : [6d167d02-6bb7-486c-bbbf-72858d75280f] Processing by ActiveStorage::DiskController#show as */*
I, [2023-04-24T13:56:37.325175 #1]  INFO -- : [6d167d02-6bb7-486c-bbbf-72858d75280f]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"951c4dbbbc4ef31b4e586751"}
I, [2023-04-24T13:56:37.326757 #1]  INFO -- : [6d167d02-6bb7-486c-bbbf-72858d75280f] Completed 206 Partial Content in 1ms (ActiveRecord: 0.0ms | Allocations: 777)


I, [2023-04-24T13:57:20.724745 #1]  INFO -- : [564f3a66-8a94-4716-97af-3872e91b7dff] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhhalJvYlhsc09HaHBlSFJ2WVRkck1IWndlRFZvYW1KeWRtNWhPQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpWDJGMGRHRmphRzFsYm5RN0lHWnBiR1Z1WVcxbFBTSTVOVEZqTkdSaVltSmpOR1ZtTXpGaU5HVTFPRFkzTlRFaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6azFNV00wWkdKaVltTTBaV1l6TVdJMFpUVTROamMxTVFZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURuWnBaR1Z2TDIxd05BWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjMtMDQtMjRUMTQ6MDE6MzcuMjQ2WiIsInB1ciI6ImJsb2Jfa2V5In19--98f18c00a454c2e19260f94e34d83d8891a99b28/951c4dbbbc4ef31b4e586751" for 10.10.10.10 at 2023-04-24 13:57:20 +0000
I, [2023-04-24T13:57:20.728161 #1]  INFO -- : [564f3a66-8a94-4716-97af-3872e91b7dff] Processing by ActiveStorage::DiskController#show as HTML
I, [2023-04-24T13:57:20.728240 #1]  INFO -- : [564f3a66-8a94-4716-97af-3872e91b7dff]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"951c4dbbbc4ef31b4e586751"}
I, [2023-04-24T13:57:20.730505 #1]  INFO -- : [564f3a66-8a94-4716-97af-3872e91b7dff] Completed 200 OK in 2ms (ActiveRecord: 0.0ms | Allocations: 761)



I, [2023-04-24T14:02:33.324211 #1]  INFO -- : [5b1f7ab4-9d93-4009-aac6-be5ed024e3cc] Started GET "/rails/active_storage/disk/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdDVG9JYTJWNVNTSWhhalJvYlhsc09HaHBlSFJ2WVRkck1IWndlRFZvYW1KeWRtNWhPQVk2QmtWVU9oQmthWE53YjNOcGRHbHZia2tpWDJGMGRHRmphRzFsYm5RN0lHWnBiR1Z1WVcxbFBTSTVOVEZqTkdSaVltSmpOR1ZtTXpGaU5HVTFPRFkzTlRFaU95Qm1hV3hsYm1GdFpTbzlWVlJHTFRnbkp6azFNV00wWkdKaVltTTBaV1l6TVdJMFpUVTROamMxTVFZN0JsUTZFV052Ym5SbGJuUmZkSGx3WlVraURuWnBaR1Z2TDIxd05BWTdCbFE2RVhObGNuWnBZMlZmYm1GdFpUb0tiRzlqWVd3PSIsImV4cCI6IjIwMjMtMDQtMjRUMTQ6MDE6MTguOTY3WiIsInB1ciI6ImJsb2Jfa2V5In19--1e9dc4b59ca0390f0455efe5b792b162d05cb63f/951c4dbbbc4ef31b4e586751" for 10.10.10.10 at 2023-04-24 14:02:33 +0000
I, [2023-04-24T14:02:33.326593 #1]  INFO -- : [5b1f7ab4-9d93-4009-aac6-be5ed024e3cc] Processing by ActiveStorage::DiskController#show as */*
I, [2023-04-24T14:02:33.326649 #1]  INFO -- : [5b1f7ab4-9d93-4009-aac6-be5ed024e3cc]   Parameters: {"encoded_key"=>"[FILTERED]", "filename"=>"951c4dbbbc4ef31b4e586751"}
I, [2023-04-24T14:02:33.327770 #1]  INFO -- : [5b1f7ab4-9d93-4009-aac6-be5ed024e3cc] Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 738)
```
Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- Self-hosted
- - Docker

**Desktop (please complete the following information)** (If applicable)
 - OS: [ Windows]
 - Browser [chrome]
 - Version 112.0.5615.138

**Docker** (If applicable)

Please share the output of the following.
- `docker version 20.10.7
- `docker info` Server:
 Containers: 10
  Running: 7
  Paused: 0
  Stopped: 3
 Images: 273
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-136-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.746GiB
 Name: chatwoot
 ID: RSDZ:QM32:T5G7:DAMK:OQHG:CVBK:VHSP:RIWJ:KFXR:ZN6V:JWFV:WEAD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
- `docker-compose version 1.25.0

**Comment by vishnu-narayanan** [comment]
@Bravo0795 Could you try using an active storage service with your docker installation? 
Ref: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

**Comment by Bravo0795** [comment]
> @Bravo0795 Could you try using an active storage service with your docker installation? Ref: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers

Could you please explain why we need to do this?

**Comment by Bravo0795** [comment]
> > @Bravo0795 Could you try using an active storage service with your docker installation? Ref: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers
> 
> Could you please explain why we need to do this?

Hi. Could i get an answer?

**Comment by pranavrajs** [comment]
@Bravo0795 You need to configure an external storage provider like Amazon S3 or Google Cloud Storage. We don't have support for permanent storage with the Docker builds. Closing this here for now. Please re-open if it is still not resolved after configuring a storage provider.
