### ISSUE TITLE
add romanian language

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#697]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sojan-official** [comment]
@aermike  would you be able to contribute to this ? :)

**Comment by aermike** [comment]
Yes

**Comment by aditzasv** [comment]
I will help too

**Comment by sojan-official** [comment]
Hey guys, we are in the process of setting up crowdin to make this process easier for you guys. If you aren't comfortable with the raising PR workflow, I will share the details of it once we finish the set up.

**Comment by sojan-official** [comment]
https://translate.chatwoot.com/  is available in case you want to work using a UI to do translations.

**Comment by aermike** [comment]
It's done

**Comment by sojan-official** [comment]
@aermike  we will merge in the translations to the codebase over this week :)
 thanks a lot for the contribution.

**Comment by aermike** [comment]
Ypu're welcome
Thanks for this application
