### ISSUE TITLE
Slack integration issue: Ubuntu 22 has new SSL

### ISSUE THREAD

**Issue by Baseform** [chatwoot/chatwoot#6973]
**Describe the bug**
Chatwoot Slack integration is not working on Ubuntu 22.
We have depended on slack "customer conversations" integration for a while, on a private, self-hosted deployment of chatwoot. Since the update of the Ubuntu OS, it no longer works. Trying to disconnect/reconnect did not solve it.
Looking through logs, the issue is related to #6377 - a compatibility problem of Slack-Ruby-client chatwoot is leaning on and the latest Ubuntu deps.

**To Reproduce**

1. Click on Settings, then Integrations
2. Under Slack, click on connect
3. Authorize on slack
4. "Connect" option is still on

**Expected behavior**
For slack integration to work...

**Server logs**

Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3] Faraday::SSLError (SSL_CTX_load_verify_file: system lib):
Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3]
Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3] lib/integrations/slack/hook_builder.rb:34:in `fetch_access_token'
Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3] lib/integrations/slack/hook_builder.rb:9:in `perform'
Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3] app/controllers/api/v1/accounts/integrations/slack_controller.rb:12:in `block in create'
Apr 24 17:40:37 chat chatwoot-web.1[1077443]: [68aa98d9-9beb-401e-8c73-cab26d4d48b3] app/controllers/api/v1/accounts/integrations/slack_controller.rb:6:in `create'

**Environment**
Self-hosted, Linux VM
- [X] Self-hosted
- - [X] Linux VM

**Comment by Baseform** [comment]
Basically re-opening #6377.
I didn't find a working solution for ubuntu 22 self-hosted vms.

**Comment by iamsivin** [comment]
CC: @vishnu-narayanan

**Comment by vishnu-narayanan** [comment]
@Baseform Could you please share the following?

```
**Describe the bug**

A clear and concise description of what the bug is.

**To Reproduce**

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error

**Expected behavior**

Share a clear and concise description of what you expected to happen.

**Screenshots**

If applicable, add screenshots to help explain your problem.

**Browser logs**

Share the browser logs to debug the issue further.

**Server logs**

Share the server logs to debug the issue further.

**Environment**

Describe whether you are using Chatwoot Cloud (app.chatwoot.com) or a self-hosted installation of Chatwoot. If you are using a self-hosted installation of Chatwoot, describe the type of deployment (Docker/Linux VM installation/Heroku/Kubernetes/Other).

- [ ] app.chatwoot.com (Chatwoot Cloud)
- [ ] Self-hosted
- - [ ] Linux VM
- - [ ] Docker
- - [ ] Kubernetes
- - [ ] Heroku
- - [ ] Other (Please specify)


**Desktop (please complete the following information)** (If applicable)
 - OS: [e.g. Linux, Windows, MacOS]
 - Browser [e.g. chrome, firefox, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information)** (If applicable)
 - Device: [e.g. iPhone6, Pixel7]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, firefox, safari]
 - Version [e.g. 22]

**Docker** (If applicable)

Please share the output of the following.
- `docker version`
- `docker info`
- `docker-compose version`

**Cloud Provider** (If applicable)
- [ ] AWS
- [ ] GCP
- [ ] Azure
- [ ] DigitalOcean
- [ ] Others

**Additional context**

Add any other context about the problem here.

```

**Comment by Baseform** [comment]
Just updated the description.

**Comment by vishnu-narayanan** [comment]
@Baseform Which version of Ubuntu are you on?

**Comment by Baseform** [comment]
Ubuntu 22.04.2 LTS

**Comment by vishnu-narayanan** [comment]
@Baseform There are a couple of dependency issues associated with Ubuntu 22.04/Chatwoot, and we recommend everyone use Ubuntu 20.04 for now when opting for the Linux installation. 

If you need a different OS/version, please use the docker installation.

**Comment by vishnu-narayanan** [comment]
@Baseform, Could you let me know if you got it working?

**Comment by filipgraniczny** [comment]
We are experiencing a similar issue with Ubuntu 22.04.2 and are hoping for a patch or at least a temporary workaround., Thanks for starting the discussion.

**Comment by sojan-official** [comment]
> Hey. Thanks for reaching back. It's an hassle for use to open an exception for the chatwoot machine and reinstalling on a Ubuntu 20 server, so not yet. We were hoping for a patch or some solution to running it on the 2022 LTS system. Do you have plan to update "Slack-Ruby-client"?

We are upgrading the slack-ruby-client in our upcoming release.

**Comment by Baseform** [comment]
The new version works fine with slack, so, solved.
(we had to upgrade redis on ubuntu - `add-apt-repository ppa:redislabs/redis`)

**Comment by pranavrajs** [comment]
Closing this as the issue seems to be resolved. Please feel free to re-open the issue if it is not the case.
