### ISSUE TITLE
Feature: Integration to zendesk

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#698]
**Is your feature request related to a problem? Please describe.**
Integrate chatwoot to zendesk 

**Describe the solution you'd like**
Build an integration with zendesk

**Comment by NikhilGupta1997** [comment]
Hi Sojan. Is there any plans to have this issue part of release 1.8.0?
FreshDesk and Zendesk are very useful tools and integration with them will make it so much easier for the agents.

**Comment by sojan-official** [comment]
@NikhilGupta1997  As email conversations are coming into chatwoot, we are still evaluating how we can make a useful integration out of this. So at the moment it's still in spec phase.
