### ISSUE TITLE
Fix "LeadingZero" issue in app/javascript/src/assets/scss/widgets/_emojiinput.scss

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#70]
`0.6` should be written without a leading zero as `.6`

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/assets/scss/widgets/_emojiinput.scss#issue_5d87481187cf1900010006df

**Comment by kirillarutyunov** [comment]
I will do it 🙃
