### ISSUE TITLE
[CW-1728] Wrong cache information for GCS storage

### ISSUE THREAD

**Issue by hugodeco** [chatwoot/chatwoot#7000]
### Describe the bug

Attachments in conversations wont be available after a few minutes;

![image](https://user-images.githubusercontent.com/2934665/234691570-17c997b2-70be-4dc4-aa4f-90751f89b704.png)
![image](https://user-images.githubusercontent.com/2934665/234691708-22905b8b-b754-49ad-ba8b-b511d141a62b.png)
![image](https://user-images.githubusercontent.com/2934665/234691819-408603c4-363d-4913-bfbb-4ecfb2ab844d.png)

### To Reproduce

1. Using the GCS storage
2. Receive an Audio Attachment OGG
3. Wait a few minutes
4. It wont be available anymore

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

<sub>[CW-1728](https://linear.app/chatwoot/issue/CW-1728/wrong-cache-information-for-gcs-storage)</sub>

**Comment by artbras** [comment]
Os áudios não estão sendo reproduzidos + de uma 1x. O atendente não consegue ouvir os áudios das mensagens pela segunda vez. Vocês poderiam verificar isso por favor?

**Comment by pranavrajs** [comment]
I can reproduce this. There is a report of the same from a paid customer as well.
