### ISSUE TITLE
sync messages history when adding a new channel

### ISSUE THREAD

**Issue by djeber** [chatwoot/chatwoot#7001]
### Is your feature or enhancement related to a problem? Please describe.

adding a new channel should sync messages history, currently I'm testing chatwoot and i was surprised when i added my facebook page i didn't get the messages history just new messages this behavior makes it hard to use the software because i dont know if the person who is messaging me is a new customer or and old customer so i have to go to facebook and check the conversation history, not syncing the conversations history makes it hard for me to transition to chatwoot i get like 400 to 500 conversations every day and i need to keep track to everything, without the conversation history i cant do that and thus render the software useless to me.

### Describe the solution you'd like

i would like the option to sync the conversation history or a way to import them

**Comment by pranavrajs** [comment]
@djeber Unfortunately this is not supported in the APIs. We only get the latest message information. Fetching the previous history is not possible. 

https://developers.facebook.com/docs/graph-api/reference/page/messages/
