### ISSUE TITLE
Upgrading to 2.16 using Helm is not working

### ISSUE THREAD

**Issue by luis-notifai** [chatwoot/chatwoot#7002]
### Describe the bug

I had a chatwoot instance v2.15 running on an AWS EKS Cluster. I installed using helm. So, I tried to upgrade it to version 2.16 following this procedure: https://www.chatwoot.com/docs/self-hosted/deployment/upgrade/ 

it seems that everything went right, also I can see the right version in helm (APP Version: v2.16.0) but when I login in my instance it still in 2.15.0 version. 

I also tried using the flag --force in the helm upgrade command but it didn't work either.

### To Reproduce

Chatwoot 2.15 deployed on an AWS EKS Cluster with ingress-nginx as Load Balancer. The chatwoot and the  ingress-nginx were both deployed using helm.

To upgrade to 2.16, I ran the procedure in the docs:
# update helm repositories
helm repo update
# list your current installed version
helm list
# show the latest version of charts that is going to be installed
helm search repo chatwoot

helm upgrade notifai-chatwoot chatwoot/chatwoot -f notifai_values_final.yaml 

No errors was shown. 

helm list shows this:

 helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
notifai-chatwoot   default         6               2023-04-26 23:46:25.323865341 +0000 UTC deployed        chatwoot-1.0.18         v2.16.0    
ingress-nginx   default         7               2023-04-26 22:29:20.70738307 +0000 UTC  deployed        ingress-nginx-4.6.0     1.7.0     

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22.04.2 LTS

### Docker (if applicable)

docker version
Client: Docker Engine - Community
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:21:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:21:07 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker info

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 5
 Server Version: 23.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc version: v1.1.5-0-gf19387a
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.19.0-1024-aws
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 965.7MiB
 Name: ip-10-0-0-54
 ID: c04a14ea-fc4e-4482-a9fc-72fb9001a4d6
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by luis-notifai** [comment]
Also, I've just tried to delete the helm deployment and install again but with the helm repo updated. I got the same result. According to helm I am in v2.16, but when I login to chatwoot is in version 2.15.

**Comment by luis-notifai** [comment]
very sorry, it was my fault, I forgot to change the version in the yaml file 🤦‍♂️

**Comment by vishnu-narayanan** [comment]
@luis-notifai Thank you for the update.
