### ISSUE TITLE
Inboxes do not persist across sessions.

### ISSUE THREAD

**Issue by vitellolabs** [chatwoot/chatwoot#7005]
### Describe the bug

Inbox, once created, allows me to configure and set things up but there is no ability to go back to settings page after I logout. Additionally, inboxes, although present in the backend, may not be picked in the frontend. As if they didn't exist. 
Audit log shows the inbox creation and updates.
### To Reproduce

Script deployment on Ubuntu 20.04. There doesn't seem to be any errors. 

### Expected behavior

Inboxes should persist in the frontend. 

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Firefox 112.0

**Comment by pranavrajs** [comment]
@vitellolabs Can you please share a screencast if possible? I'm not sure if I understand the issue completely?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
