### ISSUE TITLE
Twitter v2 API

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#7006]
### Is your feature or enhancement related to a problem? Please describe.

It is not clear but Chatwoot needs to support Twitter API v2.

With them limiting v1 access, can you confirm that immediate support will be added for v2.

Whilst some may not be able to use it, due to limits and not wanting to pay, others are within the free limits or happy to pay for access and CW needs to support that if so, urgently, given actions of the last few days.

### Describe the solution you'd like

As above.

**Comment by sanjayws** [comment]
I got a message from Twitter dev that they're suspending my App. I went into dev dashboard, enabled the free tier and it still seem to work, DMs, Tweets are fine so far. But i think they'll move to V2 soon and CW might have problems.

**Comment by pranavrajs** [comment]
https://github.com/orgs/chatwoot/discussions/6983

The account activity API is available only in the enterprise version of 2.0. This plan costs $42,000 per month. https://developer.twitter.com/en/docs/twitter-api/enterprise/account-activity-api/overview

We are still researching what would be the best way to fix this.

**Comment by sanjayws** [comment]
+MessageBird also removed support for Twitter!

**Comment by pranavrajs** [comment]
Closing this, we are putting Twitter Inboxes on hold. It doesn't make sense financially (none of the self-hosted users would be able to afford this) and technically to maintain the integration.

**Comment by akzeronet** [comment]
> Closing this, we are putting Twitter Inboxes on hold. It doesn't make sense financially (none of the self-hosted users would be able to afford this) and technically to maintain the integration.

hello @pranavrajs. do you think it is possible to integrate mastodon natively?

**Comment by pranavrajs** [comment]
Eventhough there is usage and interest in Mastadon. I have not seen a signficant size of businesses using Mastadon. Considering Chatwoot is business support tool, we might not prioritize it for now.
