### ISSUE TITLE
Review logging

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#701]
- [ ] v1.3.0 throws an error with logging 

```
3l5vrfv /usr/local/lib/ruby/2.7.0/logger/log_device.rb:95:in `initialize': No such file or directory @ rb_sysopen - /app/log/production.log (Errno::ENOENT)
```

### Options to review:

1. Update documentation to use `RAILS_LOG_TO_STDOUT `
2. Review and update the log rotate mechanism.

References: #699

**Comment by sojan-official** [comment]
when in docker you will have to set env variable `RAILS_LOG_TO_STDOUT` to be true. we will add this as the default value.

**Comment by sojan-official** [comment]
close via #787
