### ISSUE TITLE
Introduce config for login page

### ISSUE THREAD

**Issue by memorycancel** [chatwoot/chatwoot#7012]
### Is your feature or enhancement related to a problem? Please describe.

The default login page of Chatwoot is like below

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/10057052/235203306-b3f63c85-7627-4a84-a424-b77912d36351.png">

yeah, it's simple and good-looking, and I'd like to deploy a self-host Chatwoot which has customized logo and title, so I have to have a `hard modification` for them, like:

<img width="1709" alt="image" src="https://user-images.githubusercontent.com/10057052/235205891-14fd2643-17de-44d6-b909-a51b0788e693.png">

But question is if when I sync the latest codes of Chatwoot, need to resolve the conflict.

### Describe the solution you'd like

To do once for all, I suppose add some configs for this, or add page in Admin console to config this?

My thought is not very mature, I'm looking forward that there are maintainers to discuss.

### Describe alternatives you've considered

 I suppose add some configs for this

**Comment by vishnu-narayanan** [comment]
@memorycancel This discussion should help. 
https://github.com/orgs/chatwoot/discussions/2701

I am closing this issue for now.

**Comment by memorycancel** [comment]
Thanks! It works @vishnu-narayanan
