### ISSUE TITLE
[CW-1692] App creation failed. Please ensure you have valid values in the above form fields / Heroku one-click deploy 

### ISSUE THREAD

**Issue by antongavrilenkov** [chatwoot/chatwoot#7014]
### Describe the bug

Heroku one-click deploy - I got an error: “App creation failed. Please ensure you have valid values in the above form fields.”

<img width="1286" alt="Screen Shot 2023-04-27 at 18 12 17" src="https://user-images.githubusercontent.com/11135741/235267716-0a4e5e1d-b8c0-45e5-90c9-94016640954e.png">

### To Reproduce

1. Click "Heroku one-click deploy" button
2. Set "App name"
3. Change "FRONTEND_URL" variable
4. Click "Deploy app"

### Environment

Heroku

### Cloud Provider

None

### Platform

Browser

### Operating system

MacOS Monterey

### Browser and version

Chrome 112.0.5615.121 (Official Build) (arm64)

<sub>[CW-1692](https://linear.app/chatwoot/issue/CW-1692/app-creation-failed-please-ensure-you-have-valid-values-in-the-above)</sub>

**Comment by vishnu-narayanan** [comment]
Please reopen if the issue persists.
