### ISSUE TITLE
Most of /Widget Requests are stay pending and then timeout  

### ISSUE THREAD

**Issue by miladbonakdar** [chatwoot/chatwoot#7015]
### Describe the bug

After deploying the Chatwoot self-hosted application and connecting it to a website with a high load of 10,000 users per second, we encountered issues with the conversation dashboard not loading. Additionally, most of the requests to "/widget" are pending, and even after refreshing the page, the status remains pending, although sometimes we receive a 200 response. However, if the status shows as pending, it does not resolve and remains there until a timeout occurs.

We have observed that the database load and application load, such as CPU and memory, are within normal levels, and we deployed the Chatwoot Helm chart on Kuber. On the other hand, everything works fast when we disable the API Gateway and test with port forwarding on the local machine.

We would greatly appreciate it if you could provide us with some tips or assistance in resolving this issue. Additionally, we are considering implementing a cache on the "/widget" API. However, we are unsure if this will solve the problem.

### To Reproduce

There is no specific way to reproduce this unless under a huge load

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Mac

### Browser and version

Chrome

**Comment by sojan-official** [comment]
ref: https://www.chatwoot.com/docs/self-hosted/deployment/requirements 
https://www.chatwoot.com/docs/self-hosted/deployment/performance/optimizing-configurations

Depending on the number of requests which you receive, you will have to scale the number of web and worker servers accordingly. There is a specific number of requests the webserver can handle at once; you will have to tweak the configuration to provide the necessary number of instances.
