### ISSUE TITLE
Error configuration Inbox email IMAP

### ISSUE THREAD

**Issue by maykolc** [chatwoot/chatwoot#7032]
### Describe the bug

I' triyng to configure email inbox with IMAP and get this message, internal server error.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/22329269/236322228-a5283a75-7ab4-44c1-8664-20c7b20e998c.png">

### To Reproduce

1. Add inbox
2. select email
3.  Enable IMAP configuration for this inbox

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Debian

**Comment by tejaswinichile** [comment]
Can you post the what the IMAP details that you are entering onto the page here.

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
