### ISSUE TITLE
Help with Chatgpt integration

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#7034]
### Describe the bug

Hello Support.

I have self hosted chatwoot but no have the option to add chatgpt , chatgpt no is available on selft hosted?

I ready have the ast version 2.16.1

Thanks

![2023-05-05-22-54-support movilreup com](https://user-images.githubusercontent.com/96675665/236595051-bfd4239d-ebee-4a15-b74f-6dfb8ea8e255.png)

### To Reproduce

Ready describe 

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by sojan-official** [comment]
2.16.1 is a hotfix release; OpenAI integration is not enabled in it. The integration will be available in the 2.17.0 release
