### ISSUE TITLE
Multiple Device

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot#7036]
### Describe the bug

I use the chat for my customers. sue log in with us.
they often chat with multiple devices. however, not everything ends up in the same chat. several chats are started.

### To Reproduce

1. docker install
2. Set userid x and hash for user x
3. Open 2 different browser as end-user
4. Chat with support

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
@drexlma Am I getting this right?

1. You create a web inbox.
2. .Users open chats from different browsers passing in the same email.
3. Multiple conversations are created for all browsers sessions.

**Comment by XindongYan** [comment]
I am currently facing the same problem. May I ask how you resolved it later

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.

**Comment by drexlma** [comment]
Needed!
