### ISSUE TITLE
[CW-1689] Conversations filter is not working properly

### ISSUE THREAD

**Issue by miladbonakdar** [chatwoot/chatwoot#7039]
## Description

When filtering conversations based on the assignee's name, the filtered results initially display conversations assigned to the selected assignee correctly. However, subsequent updates introduce conversations assigned to other assignees, causing inconsistency in the filtered list.

fixes: #7039

## Actual Behavior

Upon filtering conversations by assignee, the conversation list initially displays the conversations assigned to the selected assignee correctly. However, subsequent updates introduce conversations assigned to other assignees, resulting in inconsistency within the filtered list.

### To Reproduce

Access the conversation filtering feature.
Select the "Assignee" filter option.
Specify the name of an assignee to filter the conversations.
Observe the conversation list and note the initially correct filtering.
Receive updates or new conversations.
Notice that conversations assigned to other assignees are included in the filtered list.

### Expected behavior

After applying the assignee filter, the conversation list should only show conversations assigned to the selected assignee. Subsequent updates or new conversations should adhere to the applied filter, maintaining the consistency of the filtered results.

### Environment

[app.chatwoot.com](http://app.chatwoot.com)

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Mac

### Browser and version

Chrome

### Docker (if applicable)

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1689](https://linear.app/chatwoot/issue/CW-1689/conversations-filter-is-not-working-properly)</sub>

**Comment by miladbonakdar** [comment]
Additionally, I must mention that we face the same problem with other filters. Initially, they work fine, but things start to go wrong when we receive new conversations.

**Comment by vishnu-narayanan** [comment]
@miladbonakdar This is confirmed. I was able to reproduce this.

**Comment by hmoghtafari** [comment]
Hi @vishnu-narayanan , 
It there any update on this issue? 
Thanks

**Comment by sojan-official** [comment]
@hmoghtafari  We have it in our backlog for upcoming releases.

**Comment by hmoghtafari** [comment]
Hello guys, Is there any update on this issue? Thanks

**Comment by shubhamkumbhakar** [comment]
Is there any update?

**Comment by shubhamkumbhakar** [comment]
https://github.com/chatwoot/chatwoot/pull/7775

**Comment by shubhamkumbhakar** [comment]
I am using this PR changes in my self hosted chatwoot to fix this issue.
https://github.com/chatwoot/chatwoot/pull/7775

@sojan-official This could be potential fix for the issue. Can you review it and confirm once?

**Comment by sojan-official** [comment]
@shubhamkumbhakar  Thanks for the PR we will take a look and get back
