### ISSUE TITLE
X-Frame-options has invalid value "ALLOWALL"

### ISSUE THREAD

**Issue by josephjoice** [chatwoot/chatwoot#704]
**Describe the bug**

Websocket is not working and agent messages are not received at the widget side. 
This is what I see in the console.
`Invalid X-Frame-Options: “ALLOWALL” header from “http://localhost:3000/widget?website_token=wwc2hHmZdXZvZr28uG8SZB4S” loaded into “http://localhost:3000/widget_tests”.`

**To Reproduce**
1. Go to http://localhost:3000/widget_tests in an incognito tab
2. In the console the X-Frame-Error can be seen.

**Screenshots**

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/7153064/78928916-1c475300-7abf-11ea-9609-13cc785e2437.png">

**Desktop (please complete the following information):**
 - OS: Macos Mojave
 - Browser Firefox
 - Version 74.0.1

**Comment by josephjoice** [comment]
`ALLOWALL` is not a valid header option according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options.

https://github.com/chatwoot/chatwoot/blob/6c0076665a7c4a9eb4038a7fbd744261f8ed3e53/config/application.rb#L30-L31

To allow the iframe to be loaded in different origin, 
```
    config.action_dispatch.default_headers.clear
```
I cleared the `SAMEORIGIN` set by rails, as X-Frame-Options not set means allow the iframe to be loaded everywhere.

**Comment by justinclift** [comment]
Yeah.  That above line in `config/application.rb` seems like it should be replaced. :smile:

**Comment by sojan-official** [comment]
@josephjoice  @justinclift will take this for the upcoming release.
