### ISSUE TITLE
[CW-1837] problems sending audios by whatsapp

### ISSUE THREAD

**Issue by gborgoni** [chatwoot/chatwoot#7048]
### Describe the bug

when i record an audio to send it on whatsapp using the 360dialog integration, the audio is not sent. I understand that it must be saved in opus format, but in all the browsers I tried it is saved in wav format and I would understand that this is the problem. However, I don't know where I can configure so that the audios are recorded in opus format

### To Reproduce

version: v2.16.0
browser: all (chrome, firefox) windows or linux

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

<sub>[CW-1837](https://linear.app/chatwoot/issue/CW-1837/problems-sending-audios-by-whatsapp)</sub>

**Comment by muhsin-k** [comment]
@gborgoni The Chatwoot uses `audio/ogg` format for audio files in WhatsApp, which works fine in all the WhatsApp channels. Could you please share the screencast?

**Comment by gborgoni** [comment]
yes.. i see that. but i don't know howto chage the format audio recording to audio/ogg... the audio is recorded in wav format.

May 16 21:06:44 vps-2219684-x chatwoot-web.1[3875]: I, [2023-05-16T21:06:44.393769 #3875]  INFO -- : [0e634eb9-bc47-4695-8367-6b9220301eb9] [ActiveJob] Enqueued Webhooks::WhatsappEventsJob (Job ID: 91fa2bd7-0f13-4749-9bab-cfc27cf453aa) to Sidekiq(low) with arguments: {"statuses"=>[{"errors"=>[{"code"=>1000, "title"=>"Audio file format unsupported audio/x-wav for file /tmp/www/c3/772a1bfd424d598fb3b46ec470cff8"}], "id"=>"gBGHVJEVMoIhjwIJr3enWED3XXjl", "message"=>{"recipient_id"=>"*********"}, "status"=>"failed", "timestamp"=>"1684282003", "type"=>"message"}], "controller"=>"webhooks/whatsapp", "action"=>"process_payload", "phone_number"=>"+********", "whatsapp"=>{"statuses"=>[{"errors"=>[{"code"=>1000, "title"=>"Audio file format unsupported audio/x-wav for file /tmp/www/c3/772a1bfd424d598fb3b46ec470cff8"}], "id"=>"gBGHVJEVMoIhjwIJr3enWED3XXjl", "message"=>{"recipient_id"=>"********"}, "status"=>"failed", "timestamp"=>"1684282003", "type"=>"message"}]}}

**Comment by fhonline** [comment]
in version 2.16 ogg was generated, now in 2.17 it generates .wav - it broke all my rule with whatsapp

**Comment by fhonline** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/95591514/f7d8e982-371f-4f03-a1c5-233fc6fa75a2)

Before version 2.16 or earlier, audios were generated in this format, which provided full compatibility with whatsapp
Now that I've updated to 2.17, the audios come as .wav
I don't understand why @sojan-official  changed???

**Comment by muhsin-k** [comment]
@fhonline @gborgoni  Could you let me know which API provider(WhatsApp Cloud/Twilio/360 dialog) you're using?

We have tested and it only records and sends `ogg` files.

[CleanShot 2023-05-19 at 10 10 59](https://github.com/chatwoot/chatwoot/assets/12408980/48e79a96-1070-4b6d-a35a-e6aeaf4f9905)

**Comment by ssteeltm** [comment]
Hello, I use API Channel, and in .17 ita recording .wav instead of oga

**Comment by gborgoni** [comment]
Hi @muhsin-k i’m using 360dialog… One question, does the recording format not depend on the browser?

**Comment by muhsin-k** [comment]
> Hello, I use API Channel, and in .17 ita recording .wav instead of oga

@ssteeltm Our most recent update to Chatwoot utilizes the `oga` format exclusively for all channels, except WhatsApp. Have you implemented an API channel for WhatsApp usage?

**Comment by muhsin-k** [comment]
>  i’m using 360dialog… One question, does the recording format not depend on the browser?


@gborgoni, No. It all depends on the inbox channel type.

We have tested using 360dialgoue, and it is recording in Ogg format.

![CleanShot 2023-05-22 at 16 45 25](https://github.com/chatwoot/chatwoot/assets/12408980/8abde623-e7a2-417c-9a4a-eebffa145e5a)

**Comment by CosmoAbdon** [comment]
Sup! We're facing this exact same issue on 2.17.1.
We have an API Channel to integrate with WhatsApp.

We saw that: 
![image](https://github.com/chatwoot/chatwoot/assets/3496248/cc129b31-53d0-478a-a1db-344142f00426)

Looking for the future of chatwoot.. All API integrations are going to receive .wav files?
Or should me make .ogg default? Or could we have an selector for things like that?

**Comment by muhsin-k** [comment]
We have reverted the audio format to `Ogg` in API channels. This change is available in the development branch.

**Comment by gborgoni** [comment]
@muhsin-k hello! I ask you a question... how do I configure chatwoot to record audio in ogg format?
