### ISSUE TITLE
[CW-1727] mark message as read by API

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#7049]
### Is your feature or enhancement related to a problem? Please describe.

Its not a problem

### Describe the solution you'd like

mark message as read by API

Hello guys, how are you?

I'm using the chatwoot API channel for an application.

In this type of inbox, by default does not have the double check to show that the message has been read.

Is it possible to update the status of a message by API? I didn't find it in the chatwoot documentation.

<sub>[CW-1727](https://linear.app/chatwoot/issue/CW-1727/mark-message-as-read-by-api)</sub>

**Comment by nagorsky** [comment]
I need the same feature

**Comment by grupale** [comment]
+1

Following this one

**Comment by CristianDuta** [comment]
@glauberssoutodossantos wouldn't the "update_last_seen" endpoint help with this? I imagine that any type of activity would end up with the contact reading the message

**Comment by arthurrferroni** [comment]
the update_last_seen doesn't helps, it needs to mark a message in conversation as read.
this endpoint marks the conversation as read
