### ISSUE TITLE
Feature: API to create incoming messages from contact

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#706]
**Is your enhancement request related to a problem? Please describe.**
I use chatwoot to manage customer messages from my app. i want to create an incoming message inside chatwoot when a customer sent me a message

**Describe the solution you'd like**
I would like to have an API to create incoming messages from a contact

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by alfredfrancis** [comment]
any update on this ?

**Comment by sojan-official** [comment]
@alfredfrancis  We are still trying to spec this out along with the API channel. Might make it to the cut for `1.6.0` or the subsequent release.

**Comment by sojan-official** [comment]
@alfredfrancis  we have merged #1052  which should take care of this.
