### ISSUE TITLE
[CW-1726] feat: possibility to change the avatar of agent bots in super admin GUI.

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#7060]
### Is your feature or enhancement related to a problem? Please describe.

Currently it is only possible to change the agent bots avatar via Rails console.

Add an avatar to your bot (optional)
https://www.chatwoot.com/docs/product/others/agent-bots/

avatar_file = Down.download("image url")
bot.avatar.attach(io: avatar_file, filename: avatar_file.original_filename, content_type: avatar_file.content_type)

### Describe the solution you'd like

A perfect solution would be the ability to change the agents bots avatar via Super admin GUI.

<sub>[CW-1726](https://linear.app/chatwoot/issue/CW-1726/feat-possibility-to-change-the-avatar-of-agent-bots-in-super-admin-gui)</sub>

**Comment by vishnu-narayanan** [comment]
@Diplomat-LV Thank you for the request. This will be a good addition to have. We will prioritise this in the coming sprints.

**Comment by Ghost108** [comment]
@sojan-official 
<img width="526" alt="Bildschirmfoto 2023-05-31 um 16 49 34" src="https://github.com/chatwoot/chatwoot/assets/17011498/0b4190d3-e136-4627-8ec0-926b8c22022c">

this command doens't work :/

**Comment by Ghost108** [comment]
Where is mistake? :(
<img width="1069" alt="Bildschirmfoto 2023-05-31 um 17 20 50" src="https://github.com/chatwoot/chatwoot/assets/17011498/3b8acc99-af74-471d-a8ac-32b2f396dacc">

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan Why was this ticket closed?

**Comment by vishnu-narayanan** [comment]
@Diplomat-LV This ticket is still open. A related duplicate ticket was closed.

**Comment by Ghost108** [comment]
this is not my own ticket, but I gues this topic should not be closed.
this is a feature request:

It should be possible to change the avatar of a bot with a GUI instead the command line:
`avatar_file = Down.download("image url")
bot.avatar.attach(io: avatar_file, filename: avatar_file.original_filename, content_type: avatar_file.content_type)`
