### ISSUE TITLE
[CW-1732] Instalation not working (docker compose)

### ISSUE THREAD

**Issue by sjcotto** [chatwoot/chatwoot#7064]
### Describe the bug

Running the command from documentation

4) Prepare the database by running the migrations.

docker compose run --rm rails bundle exec rails db:chatwoot_prepare

It's showing error

```
Using tzinfo-data 1.2022.1
Using uglifier 4.2.0
Using valid_email2 4.0.3
Using web-push 3.0.0
Using webpacker 5.4.3
Using wisper 2.0.0
Using working_hours 1.4.1
Bundle complete! 118 Gemfile dependencies, 245 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `/gems`
+ BUNDLE='bundle check'
+ bundle check
The Gemfile's dependencies are satisfied
+ exec bundle exec rails db:chatwoot_prepare
fatal: not a git repository (or any of the parent directories): .git
Loading Installation config
```

Running on ubuntu and docker version

```
root@vmi901137:~/chatwoot# docker --version
Docker version 20.10.17, build 100c701
```

### To Reproduce

1 - follow documentation https://www.chatwoot.com/docs/self-hosted/deployment/docker/
2 - first step fails

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu

### Docker (if applicable)

```
root@vmi901137:~/chatwoot# docker --version
Docker version 20.10.17, build 100c701
```

```
root@vmi901137:~/chatwoot# docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 34
  Running: 31
  Paused: 0
  Stopped: 3
 Images: 95
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-105-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.63GiB
 Name: vmi901137.contaboserver.net
 ID: 7Y2E:23WU:JDUU:XUFP:JJRP:ATAZ:CXCY:FZG6:SFYL:55FK:KKME:WN3R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: goshops
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

<sub>[CW-1732](https://linear.app/chatwoot/issue/CW-1732/instalation-not-working-docker-compose)</sub>

**Comment by politsin** [comment]
have the same problem with update from 2.16 to 2.17 when run `chatwoot_sidekiq_1`

**Comment by vishnu-narayanan** [comment]
@politsin Could you try `2.17.1`? Also could you share the redis version?

**Comment by zhiru** [comment]
here te problem is with high usage suddenly needs to stop and start the container again

**Comment by marlonsena** [comment]
Hi, @vishnu-narayanan I tried with `2.17.1` and the problem persists. Redis version, as DockerCompose.yaml is: `redis:alpine`

**Comment by vishnu-narayanan** [comment]
@marlonsena @zhiru @politsin  could you ssh into your redis container and share  the redis version?

Starting with v2.17+. chatwoot needs redis version 7+.

**Comment by vishnu-narayanan** [comment]
@sjcotto Are you still facing this issue? I am not able. to reproduce this.

**Comment by marlonsena** [comment]
@vishnu-narayanan just checked, and it seems right. 
`Redis server v=7.0.11`

Still getting the error message: `fatal: not a git repository (or any of the parent directories): .git`

After I follow the step 4 command: `docker compose run --rm rails bundle exec rails db:chatwoot_prepare`

**Comment by vishnu-narayanan** [comment]
@sjcotto @marlonsena I tried a fresh deployment and am also getting this error message. Even though this error message is thrown, the migrations are successful. The database is being created, and migrations are being run.

After this, please run the following to bring the app online.
```
docker compose up -d
```

I am closing this ticket for now. Please feel free to reopen if the migrations are not run/the database is not being created for you. Will address the error message during this stage in a separate issue.
