### ISSUE TITLE
[Rack::Attack][Blocked] remote_ip: "xxxx", path: "/widget"

### ISSUE THREAD

**Issue by drexlma** [chatwoot/chatwoot#7066]
### Describe the bug

Can't use my own User-Chat :D  i will debugging some problems

### To Reproduce

set user, and try other evil thins :) 

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment]
@drexlma Rack attack is enabled by default. If you are testing something, set the `ENABLE_RACK_ATTACK` env variable to `false` to prevent requests from getting throttled.
