### ISSUE TITLE
Private note is returned from Public API

### ISSUE THREAD

**Issue by ellicodan** [chatwoot/chatwoot#7075]
### Describe the bug

Private note is returned from the Public API as a message. There also isn't any way to distinguish between public messages and private notes, since there is no "private" field associated with any messages using the Public API.

### To Reproduce

Make a GET request to the Public API -> [hostname]/public/api/v1/inboxes/[inbox_identifier]/contacts/[source_id]/conversations

### Expected behavior

If the Public API is intended for client-facing UIs, then it risks displaying unwanted/sensitive information to the client/customer.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

**Comment by sojan-official** [comment]
working on a fix for this: 
note for team : https://linear.app/chatwoot/issue/CW-1294/private-notes-are-exposed-in-conversation-apis
