### ISSUE TITLE
[CW-1790] List of Agent Online, Busy and Offline

### ISSUE THREAD

**Issue by denirusdiaman** [chatwoot/chatwoot#7087]
### Is your feature or enhancement related to a problem? Please describe.

Hi,

On the reports and overview menu, I found the Agent Status table which provides information on the number of agents who are online, busy or offline.

But we can't see a list of who is online and busy. 
This can make it difficult for leaders to monitor their team.

### Describe the solution you'd like

Can you provide some areas to display the list agents that are online and busy?
so that we can find out which agents are online, busy or offline.

<sub>[CW-1790](https://linear.app/chatwoot/issue/CW-1790/list-of-agent-online-busy-and-offline)</sub>

**Comment by muhsin-k** [comment]
@denirusdiaman The conversations by agents filters will give you insight into the agent's online status. We hope this section is helpful to you.
![CleanShot 2023-05-16 at 12 51 58](https://github.com/chatwoot/chatwoot/assets/12408980/c9e4ee56-4333-430a-a7ef-93462405cba3)

**Comment by denirusdiaman** [comment]
Hi @muhsin-k ,

i can't see the button or section to do the filter.
As you can see, in the Conversation by Agent section, Online and Offline status are still one section.

is it possible if there is a section that only shows only online agents and only busy or offline agents?
Fyi, I'm currently using version 2.15

Thank you.
![stat agent](https://github.com/chatwoot/chatwoot/assets/25449044/f93f7378-1858-459f-a4f6-09fb026e91a7)

**Comment by muhsin-k** [comment]
Thanks for the feedback, and we will keep it in mind for further UX iterations. But this is not an immediate priority. We will keep the issue open in case anyone from the community shares similar feedback.

**Comment by michnovka** [comment]
This is really one of main show-stoppers for us to switch from livezilla to chatwoot. The workaround here only applies to Admins, as regular agents cant access reports. We have team of 10+ people, and they need to know who is online and who is offline. Even the most junior CSR must have at all times information about which colleagues are online in the app, who are unavailable etc. How can I achieve that?
