### ISSUE TITLE
[CW-1779] 2.17.0 - Cron and chat no longer working

### ISSUE THREAD

**Issue by LiamAshdown** [chatwoot/chatwoot#7090]
### Describe the bug

After running
```sudo cwctl -u```
and waiting for the CLI to upgrade Chatwoot.

The chat is not working correctly. When sending a message from either the customer facing chat or the agent chat, the chat does not update with the latest recent message, I have to refresh the page to get the recent message.

When visiting /monitoring/sidekiq/cron - I get a fatal error in the web server log.
```
 [b10cba06-8096-441e-a711-2cc2b3a4d4af] NoMethodError (undefined method `merge' for ["cron", "*/5 * * * *", "last_enqueue_time", "2023-05-16 08:40:01 +0000", "name", "trigger_scheduled_items_job", "description", "", "message", "{\"retry\":true,\"queue\":\"scheduled_jobs\",\"class\":\"TriggerScheduledItemsJob\",\"args\":[]}", "args", "[]", "status", "enabled", "klass", "TriggerScheduledItemsJob", "symbolize_args", "false", "active_job", "false", "queue_name_delimiter", "", "queue_name_prefix", ""]:Array):
```

I assume the cron is responsible for updating the chat states, which is the reason why the chats are no longer fetching messages.

I am now stuck with a broken chat, and cannot downgrade.

### To Reproduce

Upgrade to latest version through CLI.

### Environment

Docker

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Chrome

<sub>[CW-1779](https://linear.app/chatwoot/issue/CW-1779/2170-cron-and-chat-no-longer-working)</sub>

**Comment by vishnu-narayanan** [comment]
@LiamAshdown Sorry you had to face this. A couple of questions?

1. Was the `cwctl upgrade` complete?
2. You mention your environment as docker while you said to have used `cwctl`. Could you confirm your installation setup?
3. Could you share the output of`<your-chatwoot-installation-url>/api`?

**Comment by LiamAshdown** [comment]
> @LiamAshdown Sorry you had to face this. A couple of questions?
> 
> 1. Was the `cwctl upgrade` complete?
> 2. You mention your environment as docker while you said to have used `cwctl`. Could you confirm your installation setup?
> 3. Could you share the output of`<your-chatwoot-installation-url>/api`?

1. Yes the `cwctl upgrade` ran to completion with no errors.
2. This is the installation process I used: https://www.chatwoot.com/docs/self-hosted/deployment/gcp
3. ```{"version":"2.17.0","timestamp":"2023-05-16 10:31:52","queue_services":"ok","data_services":"ok"}```

**Comment by vishnu-narayanan** [comment]
@LiamAshdow  Have you tried `cwctl --restart`?  Also, could you share the output of  `lsb_release -a`?

**Comment by minholi** [comment]
Same here. I'm getting this on my worker logs:

```
May 16 14:22:21 omni systemd[1]: chatwoot-worker.1.service: Main process exited, code=exited, status=1/FAILURE
May 16 14:22:21 omni systemd[1]: chatwoot-worker.1.service: Failed with result 'exit-code'.
May 16 14:22:22 omni systemd[1]: chatwoot-worker.1.service: Scheduled restart job, restart counter is at 158.
May 16 14:22:22 omni systemd[1]: Stopped chatwoot-worker.1.service.
May 16 14:22:22 omni systemd[1]: Started chatwoot-worker.1.service.
```

**Comment by LiamAshdown** [comment]
> @LiamAshdow Have you tried `cwctl --restart`? Also, could you share the output of `lsb_release -a`?

Yes, I've tried `cwctl --restart` and it did not rectify the issue.

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

**Comment by vishnu-narayanan** [comment]
@LiamAshdown Could you confirm your Redis version? `redis-server --version`?

**Comment by LiamAshdown** [comment]
> redis-server --version

`Redis server v=5.0.7 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=66bd629f924ac924`

**Comment by vishnu-narayanan** [comment]
@minholi Was the upgrade successful for you as well? Could you share which version are you upgrading from?

**Comment by vishnu-narayanan** [comment]
@LiamAshdown Could you try upgrading your Redis version to something 6+?

**Comment by minholi** [comment]
> @minholi Was the upgrade successful for you as well? Could you share which version are you upgrading from?

Yes. I did the upgrade from 2.16.1

But I got an error during upgrade. I was using NodeJS 12, so I upgraded to NodeJS 14 and ran cwctl --upgrade again. Also rebooted the server a few minutes after the successful upgrade.

**Comment by minholi** [comment]
> @LiamAshdown Could you try upgrading your Redis version to something 6+?

It works. Upgraded redis to 7.0.11 here and received all messages. Thanks!

**Comment by LiamAshdown** [comment]
> > @LiamAshdown Could you try upgrading your Redis version to something 6+?
> 
> It works. Upgraded redis to 7.0.11 here and received all messages. Thanks!

Could you share how you've upgraded your redis? I am afraid to uninstall my current version of redis, and then install the latest version.

**Comment by minholi** [comment]
> > > @LiamAshdown Could you try upgrading your Redis version to something 6+?
> > 
> > 
> > It works. Upgraded redis to 7.0.11 here and received all messages. Thanks!
> 
> Could you share how you've upgraded your redis? I am afraid to uninstall my current version of redis, and then install the latest version.

```
sudo add-apt-repository ppa:redislabs/redis
sudo apt update
sudo apt install redis
```
