### ISSUE TITLE
[CW-1786] Can't use OpenAI

### ISSUE THREAD

**Issue by maccup** [chatwoot/chatwoot#7094]
### Describe the bug

Hello there,

I recently upgraded Chatwoot to the latest version v2.17.0, but I'm having trouble trying to enable the OpenAI integration. According to the documentation, the OpenAI integration should be available in the Applications section, but it's not appearing there. However I can see it in the Integrations.

Here are the steps I followed:

- I went to the settings and selected integration.
- I clicked on "OpenAI" and then selected the "Configure" option.
- The screen shows that Open AI is already connected, but it's not working. I clicked "DELETE," but it didn't help.

Could you help me resolve this issue? Thank you in advance.

<img width="1506" alt="Screenshot 2023-05-16 at 15 00 21" src="https://github.com/chatwoot/chatwoot/assets/57940197/a589550c-9113-4448-acda-05dd4caaa496">

<img width="1447" alt="Screenshot 2023-05-16 at 15 04 12" src="https://github.com/chatwoot/chatwoot/assets/57940197/7e51de20-2664-4700-9af7-b7f341f08f82">

### To Reproduce

1. Go to settings, integration
2. Click OpenAI -> Configure
3. It shows that Open AI is already connected, but it's not, clicking DELETE doesn't help.

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Chrome Version 113.0.5672.92 (Official Build) (arm64)

<sub>[CW-1786](https://linear.app/chatwoot/issue/CW-1786/cant-use-openai)</sub>

**Comment by noremac09** [comment]
I have same issue

**Comment by vishnu-narayanan** [comment]
@maccup @noremac09 I am not able to reproduce this. Also, the `open-ai` config should be in the application section. Could you share your build id(available under account>settings>under version)?

![image](https://github.com/chatwoot/chatwoot/assets/3526167/c7657025-b35e-4862-80d3-245859614d2a)


cc: @sojan-official @muhsin-k

**Comment by noremac09** [comment]
My version is: v2.17.0 Build de1fb6ba4e9723217eef5ef8be04daa7c2091333.

Before this, I encountered an issue with dialogues after updating. The "cwctl -u" command didn't update my Redis to version 7. My system is Debian 11. (https://github.com/chatwoot/chatwoot/issues/7090#issuecomment-1549811241).

I'm unable to install a clean version since I have a lot of data in the database.

**Comment by marcelgoya** [comment]
> 



> 1. I used the "git stash" command in the /home/chatwoot/chatwoot/ directory to address potential image overwriting issues in the frontend.
> 2. Additionally, I updated the permissions for all files in the /home/chatwoot/chatwoot directory using the command: "chown -R chatwoot:chatwoot chatwoot."
> 3. I downgraded from Node 18 to Node 14.
> 4. By running "ctwcl -u," I rebuilt the frontend, which resulted in OpenAI appearing in the correct location and working.
> 5. I also updated "cwctl" from version 2.1.0 alpha build to the latest version.
> 
> @marcelgoya, I recommend trying these steps as well. They might help us make progress towards identifying and resolving the issue you're experiencing.

Thanks, I've tried your suggestions but unfortunately it didn't work. I assumed it had something to do with the static assets not beeing updated and that's what it  was in my case. 

This is the command to re-generate the static assets:

`RAILS_ENV=production rake assets:clean assets:clobber assets:precompile`

Now the OpenAI app is being shown in the console:

![Screenshot 2023-05-17 192443](https://github.com/chatwoot/chatwoot/assets/3046751/cb9efc26-ec11-40fb-b5c2-5c5f538118ec)

**Comment by cruz4d3r** [comment]
> > 
> 
> > 1. Utilicé el comando "git stash" en el directorio /home/chatwoot/chatwoot/ para abordar posibles problemas de sobrescritura de imágenes en la interfaz.
> > 2. Además, actualicé los permisos para todos los archivos en el directorio /home/chatwoot/chatwoot usando el comando: "chown -R chatwoot:chatwoot chatwoot".
> > 3. Bajé de Nodo 18 a Nodo 14.
> > 4. Al ejecutar "ctwcl -u", reconstruí la interfaz, lo que resultó en que OpenAI apareciera en la ubicación correcta y funcionara.
> > 5. También actualicé "cwctl" de la versión 2.1.0 alpha build a la última versión.
> > 
> > @marcelgoya, recomiendo probar estos pasos también. Podrían ayudarnos a avanzar en la identificación y resolución del problema que está experimentando.
> 
> Gracias, probé tus sugerencias pero desafortunadamente no funcionó. Supuse que tenía algo que ver con que los activos estáticos no se actualizaran y eso fue lo que sucedió en mi caso.
> 
> Este es el comando para volver a generar los activos estáticos:
> 
> `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile`
> 
> Ahora la aplicación OpenAI se muestra en la consola:
> 
> ![Captura de pantalla 2023-05-17 192443](https://user-images.githubusercontent.com/3046751/239030771-cb9efc26-ec11-40fb-b5c2-5c5f538118ec.png)

Excuse my ignorance but I know little about ruby, where you put this command to recompile the static files "RAILS_ENV=production rake assets:clean assets:clobber assets:precompile"

Thanks for the attention.

**Comment by cruz4d3r** [comment]
> > 
> 
> > 1. Utilicé el comando "git stash" en el directorio /home/chatwoot/chatwoot/ para abordar posibles problemas de sobrescritura de imágenes en la interfaz.
> > 2. Además, actualicé los permisos para todos los archivos en el directorio /home/chatwoot/chatwoot usando el comando: "chown -R chatwoot:chatwoot chatwoot".
> > 3. Bajé de Nodo 18 a Nodo 14.
> > 4. Al ejecutar "ctwcl -u", reconstruí la interfaz, lo que resultó en que OpenAI apareciera en la ubicación correcta y funcionara.
> > 5. También actualicé "cwctl" de la versión 2.1.0 alpha build a la última versión.
> > 
> > @marcelgoya, recomiendo probar estos pasos también. Podrían ayudarnos a avanzar en la identificación y resolución del problema que está experimentando.
> 
> Gracias, probé tus sugerencias pero desafortunadamente no funcionó. Supuse que tenía algo que ver con que los activos estáticos no se actualizaran y eso fue lo que sucedió en mi caso.
> 
> Este es el comando para volver a generar los activos estáticos:
> 
> `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile`
> 
> Ahora la aplicación OpenAI se muestra en la consola:
> 
> ![Captura de pantalla 2023-05-17 192443](https://user-images.githubusercontent.com/3046751/239030771-cb9efc26-ec11-40fb-b5c2-5c5f538118ec.png)

Excuse my ignorance but I know little about ruby, where you put this command to recompile the static files "RAILS_ENV=production rake assets:clean assets:clobber assets:precompile"

Thanks for the attention.

**Comment by cruz4d3r** [comment]
> > > 
> > 
> > 
> > > 1. Utilicé el comando "git stash" en el directorio /home/chatwoot/chatwoot/ para abordar posibles problemas de sobreescritura de imágenes en la interfaz.
> > > 2. Además, actualicé los permisos para todos los archivos en el directorio /home/chatwoot/chatwoot usando el comando: "chown -R chatwoot:chatwoot chatwoot".
> > > 3. Bajé de Nodo 18 a Nodo 14.
> > > 4. Al ejecutar "ctwcl -u", reconstruí la interfaz, lo que resultó en que OpenAI apareció en la ubicación correcta y funcionó.
> > > 5. También actualicé "cwctl" de la versión 2.1.0 alpha build a la última versión.
> > > 
> > > @marcelgoya, recomiendo probar estos pasos también. Podrían ayudarnos a avanzar en la identificación y resolución del problema que está experimentando.
> > 
> > 
> > Gracias, probé tus sugerencias pero desafortunadamente no sobraron. Supuse que tenía algo que ver con que los activos estáticos no se actualizaran y eso fue lo que sucedió en mi caso.
> > Este es el comando para volver a generar los activos estaticos:
> > `RAILS_ENV=production rake assets:clean assets:clobber assets:precompile`
> > Ahora la aplicación OpenAI se muestra en la consola:
> > ![captura de pantalla 2023-05-17 192443](https://user-images.githubusercontent.com/3046751/239030771-cb9efc26-ec11-40fb-b5c2-5c5f538118ec.png)
> 
> Disculpe mi ignorancia, pero sé poco sobre Ruby, donde pone este comando para volver a compilar los archivos estáticos "RAILS_ENV = activos de rake de producción: activos limpios: activos de clobber: precompilación"
> 
> Gracias por la atención.

I execute the command and have this message : "Your Ruby version is 2.7.0, but your Gemfile specified 3.2.2"

**Comment by moerdowo** [comment]
hi @marcelgoya @noremac09  , did you solve this issue?

I also experienced the same error after upgrading to v2.18.0 

I've tried all the steps above but didn't work, I can't reinstall a clean version since I have a lot of data in the database.
