### ISSUE TITLE
Fatal error after 2.17.0 upgrade

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#7097]
### Describe the bug

We can no longer send or receive messages (at least on WA and SMS) after the 2.17.0 upgrade (self-hosted on hetzner, through cwctl --upgrade)

I suspect it has to do with this log entry in the worker: 
May 16 15:45:15 chatwoot chatwoot-worker.1[2852745]: redis-client requires Redis 6+ with HELLO command available (redis://localhost:6379/0)

Log excerpt in https://gist.github.com/jochenstu/52ef652b6b0438e69b20903b662b6d61

This excerpt is being retried and repeated.

### To Reproduce

-

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

**Comment by LiamAshdown** [comment]
You need to update your Redis version to 7.x

See below for the command to update your redis version.
#7090

**Comment by jochenstu** [comment]
Unfortunately, that did not fix the issue.

`root@chatwoot:~# redis-server --version
Redis server v=7.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3af367a78d5e21e9`

**Comment by LiamAshdown** [comment]
Did you restart the redis server?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jochenstu** [comment]
I think that was it (I actually ended up rebooting the machine). Thanks a lot for your help!
