### ISSUE TITLE
[CW-1785] API Inbox with POST Webhook and Parameters

### ISSUE THREAD

**Issue by hugodeco** [chatwoot/chatwoot#7098]
### Is your feature or enhancement related to a problem? Please describe.

After update for 2.17, there is a limitation of 250 caracters at webhook from api channels.
We need to pass some parameters, variables and fixed ones, to the external system, so our whatsapp api (quepasa) stops to work after that. 

### Describe the solution you'd like

We need a post webhook with parameters or no limitation for the webhook url.
I Think that a POST Webhook will be better and more integrated.

### Describe alternatives you've considered

For now we are changing some names of parameters trying to reach these number.

### Additional context
Would be nice if we can avoid SSL Checks (CheckBox) for use in localhost.
A Checkbox to IGNORE SSL issues.

_No response_

<sub>[CW-1785](https://linear.app/chatwoot/issue/CW-1785/api-inbox-with-post-webhook-and-parameters)</sub>

**Comment by pedroherpeto** [comment]
getting same here!

**Comment by bejaranoaqp** [comment]
Hola, si a roto la integracion con esta nueva actualizacion

**Comment by pedroherpeto** [comment]
@vishnu-narayanan some update about that?

**Comment by sojan-official** [comment]
We will have the limit for webhook URLs updated

**Comment by sojan-official** [comment]
auth for webhook will be handled in https://github.com/chatwoot/chatwoot/issues/4732
