### ISSUE TITLE
Incoming messages not visible in the Email conversation

### ISSUE THREAD

**Issue by saduni-udeshika** [chatwoot/chatwoot#7102]
### Describe the bug

I have set up an email inbox using IMAP. Although emails are being delivered to the email inbox, I am unable to see the message bubbles. Only the reply messages are visible in the inbox. currently we are using Chatwoot v2.12.

![image-20230515-103152](https://github.com/chatwoot/chatwoot/assets/60056888/b68c0a98-3fee-4efb-b30d-d9814db38baf)

### To Reproduce

1. Create Email inbox.
2. Enable IMAP configuration.
3. See the Email inbox.

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

ubuntu 20.04

### Browser and version

Chrome 93

### Docker (if applicable)

- docker version - 23.0.4
- docker info - ![Screenshot 2023-05-17 at 11 41 46 am](https://github.com/chatwoot/chatwoot/assets/60056888/17ac09a3-569e-4259-bbbc-99a8bc5f551c)
- docker-compose version - 1.29.2

**Comment by vishnu-narayanan** [comment]
@saduni-udeshika Could you upgrade to the latest version and see if you are still facing the issue?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
