### ISSUE TITLE
[CW-1822] BUG: Confirmation of receipt and reading of files in whatsapp - after 2.17

### ISSUE THREAD

**Issue by glauberssoutodossantos** [chatwoot/chatwoot#7115]
### Describe the bug

after upgrading to version 2.16 and then also to 2.17 the confirmation of sending and reading files in whatsapp stopped working.

![image](https://github.com/chatwoot/chatwoot/assets/99494469/1d6d3e2c-1bf9-4510-8051-fcf09381358d)

In the image above it is possible to see that the messages that have files have only '1 check'. Text messages have '2 checks' and a read confirmation.

### To Reproduce

using self-host in GCP just send a image to contact.

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

### Operating system

All

### Browser and version

All

<sub>[CW-1822](https://linear.app/chatwoot/issue/CW-1822/bug-confirmation-of-receipt-and-reading-of-files-in-whatsapp-after-217)</sub>

**Comment by tejaswinichile** [comment]
![Screenshot 2023-06-26 at 7.02.44 PM.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/dd74653c-5d3a-4534-b893-6dc3ab804cb8/e1ed4f02-2e30-4251-8a7d-dda216b96ad6)

@sojan-official I am facing this issue while creating whatsapp business account .

Can you attach one on staging, if you already have one?

**Comment by tejaswinichile** [comment]
Findings: For twilio Inboxes, we don't handle the processing read_receipt status at all, I have checked the last two years of messages and there is not read receipts tick [https://app.chatwoot.com/app/accounts/1/inbox/444/conversations/7655](https://app.chatwoot.com/app/accounts/1/inbox/444/conversations/7655)

**Comment by tejaswinichile** [comment]
It's working in 2.18 [https://app.chatwoot.com/app/accounts/4096/conversations/91](https://app.chatwoot.com/app/accounts/4096/conversations/91)

Closing this ticket as no longer the issue: 

![Screenshot 2023-06-27 at 3.55.26 PM.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/7f4be133-7fd9-45c9-8c0a-37ae8e5653c8/a2d83daf-e804-4641-a451-c8c8f7c02626)
