### ISSUE TITLE
Bot has no avatar

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7129]
### Describe the bug

The option "Use inbox name and avatar for the bot" is enabled.
<img width="412" alt="Bildschirmfoto 2023-05-19 um 11 29 17" src="https://github.com/chatwoot/chatwoot/assets/17011498/4c2d9a8b-4717-4e21-8fa1-eca98bb9f43f">

But the bot has no avatar:
<img width="391" alt="Bildschirmfoto 2023-05-19 um 11 29 06" src="https://github.com/chatwoot/chatwoot/assets/17011498/9980ec42-ba1e-43e4-af82-69b1dc751029">

### To Reproduce

Settings > Inboxes > edit Inbox > Enable "Use inbox name and avatar for the bot"
The Bot in the Widget has no avatar.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

macOS 13.4

### Browser and version

Firefox 113.0.1

**Comment by Ghost108** [comment]
No response?

**Comment by Ghost108** [comment]
@sojan-official

**Comment by Ghost108** [comment]
@sojan-official 
no errors :/

**Comment by sojan-official** [comment]
@Ghost108  Also note that the configuration in inbox is only for the bot which sends welcome messages and CSAT. 
if you are using an agent bot, you will have to set its avatar via rails console 

ref: https://github.com/chatwoot/chatwoot/issues/4535

**Comment by Ghost108** [comment]
I created an agent bot via super admin console:
<img width="1206" alt="Bildschirmfoto 2023-05-31 um 16 31 15" src="https://github.com/chatwoot/chatwoot/assets/17011498/3506b5a0-0d33-4593-985c-a52426fb5388">

I only have to add the env "USE_INBOX_AVATAR_FOR_BOT" = true and than it should work?

**Comment by sojan-official** [comment]
@Ghost108  nope. the environment variable is deprecated. please update the avatar from rails console. 

```
bot = AgentBot.find('bot id')
avatar_file = Down.download("image url")
bot.avatar.attach(io: avatar_file, filename: avatar_file.original_filename, content_type: avatar_file.content_type)
```

ref: https://github.com/chatwoot/chatwoot/issues/4535#issuecomment-1136916669

**Comment by Ghost108** [comment]
I am using the docker version.
If i open the console of the rails container and try the first command I get this error:

<img width="552" alt="Bildschirmfoto 2023-05-31 um 16 37 38" src="https://github.com/chatwoot/chatwoot/assets/17011498/99cf73a7-bae0-4386-97cb-5fb4bf6122e3">

**Comment by Ghost108** [comment]
ahhh I see. sorry I am learning ;)
But new error:
<img width="528" alt="Bildschirmfoto 2023-05-31 um 16 41 29" src="https://github.com/chatwoot/chatwoot/assets/17011498/f6d4bd64-c158-4172-8996-c64ae929e78e">

**Comment by Ghost108** [comment]
ahhh I see! Sorry I am learning ;)
But now the new error:
<img width="553" alt="Bildschirmfoto 2023-05-31 um 16 43 00" src="https://github.com/chatwoot/chatwoot/assets/17011498/4bdecbe1-b20f-4467-899e-ac3ec69e51df">

**Comment by sojan-official** [comment]
@Ghost108  There is type in the command you are typing
it should be 
```
AgentBot.find('id)  # you are missing the `.`
```

also closing this as we will be tracking this over: https://github.com/chatwoot/chatwoot/issues/7060
