### ISSUE TITLE
feat: Add footer partitial into vueapp layout

### ISSUE THREAD

**Issue by memorycancel** [chatwoot/chatwoot#7139]
### Is your feature or enhancement related to a problem? Please describe.

To feel free to add any changes into footer  without resolving the conflict which hard change in vueapp layout

### Describe the solution you'd like

New feat: Add footer `partitial` into `vueapp` layout

### Additional context

For example:

https://github.com/TommyTechWorkshop/chatwoot/commit/968642da40fe82636e576ac1e63112decb3d073d
https://github.com/TommyTechWorkshop/chatwoot/commit/4a5db26593e1c485449c11947d65a15cabaf501f

**Comment by pranavrajs** [comment]
@memorycancel As suggested in the previous thread, would you please share the use case here?

**Comment by memorycancel** [comment]
> @memorycancel As suggested in the previous thread, would you please share the use case here?

I'm Chatwoot fan and plan to promote Chatwoot in China. I built https://crm.tommytech.online.
For me , I'd like to puts some links like Record information, Copyright info and terms in my footer page in China， it's customary, every online website must append these messages in footer.

like:

---

<img width="1033" alt="image" src="https://github.com/chatwoot/chatwoot/assets/10057052/7f6a24e2-63a8-40b2-badb-1efb3a693d0d">

---

<img width="1038" alt="image" src="https://github.com/chatwoot/chatwoot/assets/10057052/1147a307-e07f-4409-bb60-ac766bde43b5">

---

<img width="1038" alt="image" src="https://github.com/chatwoot/chatwoot/assets/10057052/93205f54-0a82-4251-9383-663dec1841c1">

**Comment by pranavrajs** [comment]
@memorycancel As I said in the PR. It feels like a custom use-case and doesn't add much value to the product. We can re-open the PR in future if there is a strong community ask.
