### ISSUE TITLE
[CW-1921] Chat Widget Not Supporting RTL Languages

### ISSUE THREAD

**Issue by maximbaran** [chatwoot/chatwoot#7141]
### Describe the bug

The current chat widget does not provide proper support for RTL languages. When using the chat widget in an RTL language, such as Arabic or Hebrew, the text alignment and direction are incorrect, leading to a poor user experience.

![image](https://github.com/chatwoot/chatwoot/assets/43070955/6db70a90-1dd2-4119-b646-43cb4f9630f0)
![image](https://github.com/chatwoot/chatwoot/assets/43070955/9746fb0a-6574-464e-ba96-4b72f76212eb)

### To Reproduce

1. Set the language of the chat widget to an RTL language, such as Hebrew.
2. Initiate a conversation or view an existing conversation in the chat widget.
3. Observe the text alignment, direction, and handling of RTL-specific characters.

### Expected behavior

The chat widget should have proper RTL language support, including correct text alignment, direction, and handling of RTL-specific characters. This would ensure that users in RTL language environments can use the chat widget seamlessly and enjoy a consistent user experience.

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome version 90.0.4430.212

<sub>[CW-1921](https://linear.app/chatwoot/issue/CW-1921/chat-widget-not-supporting-rtl-languages)</sub>

**Comment by vishnu-narayanan** [comment]
@maximbaran Thank you for the feature request. We will prioritize this in the upcoming sprints.

**Comment by hosnas** [comment]
@vishnu-narayanan is there any eta for this?
