### ISSUE TITLE
can not edit / remove campaigns

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7144]
### Describe the bug

Yo can not edit / remove campaigns
Docker version of chatwoot (2.17.1)

<img width="1440" alt="Bildschirmfoto 2023-05-20 um 21 04 07" src="https://github.com/chatwoot/chatwoot/assets/17011498/58eb1651-2b1a-40d5-9b81-23db03a3e159">

### To Reproduce

Create a campaign and save it.
After that, you have no option to disable / edit / remove this campaign

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

macOS 13.4

### Browser and version

Firefox 113.0.1

**Comment by Ghost108** [comment]
No response?

**Comment by pranavrajs** [comment]
@Ghost108 Can you please share the issue in the proper format? Please include a screencast if possible. There is too little information to debug what is going on.

**Comment by Ghost108** [comment]
since 2.17.1 it works!
