### ISSUE TITLE
sort conversations RTL menu cut off

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#7146]
### Describe the bug

![2023-05-21_12h05_57](https://github.com/chatwoot/chatwoot/assets/121224467/d6a477c5-541f-422f-b1ba-46189743635b)

self hosted

### To Reproduce

sort conversations RTL menu

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
Fixed via https://github.com/chatwoot/chatwoot/pull/7118
