### ISSUE TITLE
Assigned Conversation Number

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#7148]
### Is your feature or enhancement related to a problem? Please describe.

Chatwoot is a great solution but found some very useful details missing.

It would be nice if I added a conversation number to the conversations.  to have better control over cases

An option is needed to convert the chats is support tikects.  Everything is not always solved in one conversation, so most of the time it takes more time to resolve a customer situation.  Therefore, chatwoot must have an area to create support tickets and thus convert the conversations into them, giving better follow-up to the cases.

Thanks Support.

### Describe the solution you'd like

Explain above.

**Comment by akzeronet** [comment]
Hi, you can use API/Webhook or integrate a external Ticket System via Dashboard Apps... I think the chatwoot team should focus on improving what they already have, for example adding more channels (Mastodon, LinkedIn, Mattermost, Tiktok), reintegrating twitter...

**Comment by pranavrajs** [comment]
@movilreup If you are talking about a unique identifier for the conversation. We do have it. You can see it in the URL. Let me know if it is something else.

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
