### ISSUE TITLE
Can't send any mail

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#716]
**Describe the bug**
Set smtp account, but 
**To Reproduce**
1. Go to '...'agent->reset passw0rd
2. Click on '....'reset passw0rd
Is in screen shot. Mail is not send
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Cent)S7.7
 - Browser [e.g. chrome, safari]Firefox

**Smartphone (please complete the following information):**

**Additional context**
Chatwoot installed manual
[Pictures.zip](https://github.com/chatwoot/chatwoot/files/4477593/Pictures.zip)

**Comment by pranavrajs** [comment]
![image](https://user-images.githubusercontent.com/2246121/79336645-bb49d000-7f41-11ea-8144-f9a4ee027d1a.png)

It shows wrong authentication, could you please check the password?

**Comment by aermike** [comment]
Try on other smtp server and it works
ticket can be closed.
