### ISSUE TITLE
Can't delete inboxes after upgrading 2.17.0

### ISSUE THREAD

**Issue by rolymaz** [chatwoot/chatwoot#7160]
### Describe the bug

I upgraded to 2.17.0 using the cwctl --upgrade command

post upgrade, I followed these guidelines,  https://github.com/orgs/chatwoot/discussions/7113

I then created test inboxesfor whatsapp & Mail (Microsoft)

The inboxes display as usual

When i try delete them by navigating to Settings > Inboxes, the system prompts to confirm and i type in the confirm message. Thereafter the system confirms deletion. 

When i refresh the home page, the inboxes return

I have attempted this on Firefox and Chrome

### To Reproduce

Selfhosted on Ubuntu linux
Using standard inbox config

### Expected behavior

I expect the inboxes to be deleted and removed entirely from chatwoot. 

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu Linux

### Browser and version

Firefox 113.0

**Comment by rolymaz** [comment]
I was able to resolve the issue by rebooting the VM. After rebooting, the inboxes marked for deletion where removed

**Comment by ZHconsultores** [comment]
> I was able to resolve the issue by rebooting the VM. After rebooting, the inboxes marked for deletion where removed

Restarting didn't work for me. Cannot delete Whatsapp Inbox. Same behavior as described above.

**Comment by rolymaz** [comment]
Check if there are any API errors when you try delete the whatsapp account. To do this open Chatwoot in your browser and open up the browser's development tools. (Firefox you press F12). Try and delete the account and watch if there are any errors in the Consol. If there are, I suggest you open a new issue and share. I used this method to fix another issue with the whatsapp inbox. Chatwoot kept saying my setting change was successful but it actually wasn't (my out of office message was larger than 255 char). Hope this helps?
