### ISSUE TITLE
No fuciona mensajes al agregar cuenta de whatsapp con 360Dialog

### ISSUE THREAD

**Issue by nicvalencia** [chatwoot/chatwoot#7165]
### Describe the bug

Al agregar la cuenta con 360Dialog se envia un mensaje con plantilla aprovada y se recibe un error de error de verificacion de token

creo que es por que no se genero ese token al crear la cuenta como podria realizarlo ya que el sistema fallo adjunto imagen

![image (3)](https://github.com/chatwoot/chatwoot/assets/3187898/478b0526-f47e-4d17-9a3c-d47eb10c72e2)

### To Reproduce

{
  "error": "Error; wrong verify token"
}

### Environment

Other [please specify in the description]

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by movilreup** [comment]
Hola ese token te lo da 360 donde esta el número en los detalles aparece el token

**Comment by nicvalencia** [comment]
Si el token del número lo tengo pero el token del webhook no aparece cuando
creo la cuenta es más el sistema no me deja crear el canal sin el número
del token de WhatsApp el inconveniente es que los mensajes no salen ni
ingresan por ese token.

Nicolás Valencia

**Comment by movilreup** [comment]
Que versión estás usando 2 17 de chatwoot?

También es solo una opinión es mejor utilizar la versión oficial de WhatsApp

**Comment by movilreup** [comment]
![Screenshot_20230522_125817_Chrome](https://github.com/chatwoot/chatwoot/assets/96675665/b8000639-36d7-49d6-9de3-28891110d4fa)

Es q se supone que se vea asi si escogiste la opción de 360dialog

**Comment by nicvalencia** [comment]
Si estoy usando la 2.17 y también estoy buscando la forma de migrar esos
números a la versión cloud de WhatsApp

Nicolás Valencia

**Comment by movilreup** [comment]
Si cambia a la versión WhatsApp si los números son twillio son fáciles de migrar a cloud whatapp debes crear tu cuenta de facebook business manager y lo mejor verificarla. 

Lo q te recomiendo es q crees una cuenta en chatwoot.com ya q tiene dos agentes gratis y pruebes tu api en el portal de ellos directamente a ver si te llegan entonces si te llegan con la cuenta de chatwoot directamente ahi un problema en el script. 

Si necesitas ayuda tengo conocimiento q te puedo dar la mano para esos estamos me puedes escribir por telegram mi usuario es mormig35 con mucho gusto te ayudo.

**Comment by pranavrajs** [comment]
Apologies if I'm mistaken here as I don't understand the language (and have used Google Translate). I believe the issue was solved as per the conversation. If it is not case, please feel free to reopen with more information.
