### ISSUE TITLE
[CW-1902] User can send message in resolved conversation

### ISSUE THREAD

**Issue by mesutrk95** [chatwoot/chatwoot#7166]
### Describe the bug

I disabled the "Allow messages after conversation resolved" option in the inbox settings, and I expected that users wouldn't be able to send any messages to a conversation that had already been resolved by an agent. 
However, I've noticed that when a user loses their internet connection and reconnects later, they're still able to send messages to a conversation that had been previously resolved.
 

https://github.com/chatwoot/chatwoot/assets/113113417/caee3705-bca5-4047-acd7-f3692c0b5bfb

### To Reproduce

1. Make a web inbox 
2. go to the newly created inbox settings
3. set "Allow messages after conversation resolved" to "Disabled"
4. Start a conversation in the Messenger
5. Write something and send it
6. Enter your email
  7. Disconnect the Messenger from the internet and, Let the Messenger tab be open in your browser (In this step, I have used Chromes offline throttling mode to virtually disconnect the messenger's socket connection)
8. Resolve the conversation In the conversations panel
9. Go to the messenger tab and set Throttling mode to "No throttling"
10. Write something in the messenger and send it.
11. You will have that message in your resolved conversation panel and the user still can send & receive messages there.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

<sub>[CW-1902](https://linear.app/chatwoot/issue/CW-1902/user-can-send-message-in-resolved-conversation)</sub>

**Comment by hmoghtafari** [comment]
Hello @sojan-official, Is there any update about this issue?

**Comment by sebwalk** [comment]
This is a major issue for our use case, as we rely on the 'conversation created' webhook being fired when a customer starts interacting with our chat. We need this in order to notify our agents to have a look.

I think it definitely is a bug that a customer can send messages in resolved chats, even if this is explicitly disabled in the settings. Why are there no plans to fix it? @sojan-official
