### ISSUE TITLE
Add tag to a specific message in a conversation

### ISSUE THREAD

**Issue by DangHuyen** [chatwoot/chatwoot#7171]
### Is your feature or enhancement related to a problem? Please describe.

My customers request several related features/ updates or notify us about several issues at then we have to mark each of them with different tags. And, usually, they emphasize a feature multiple times in the conversation making me want to count the number of times the feature is mentioned to make a decision on whether to do it right away or not.

### Describe the solution you'd like

Add a tag to a specific message in a conversation and count the times it was added to let us make decisions easier.

**Comment by pranavrajs** [comment]
@DangHuyen Wouldn't this be solved by the conversation labels? Is there a specific reason why it is required on messages? 

The way I see it is that a user requested a feature multiple times and I would interested to see how many conversations are there related to the same request.

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
