### ISSUE TITLE
[CW-1856] Add variable input placeholders to canned responses

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#7173]
### Is your feature or enhancement related to a problem? Please describe.

What I am requesting is basically the same functionality for canned responses, that is being offered for whatsapp template messages work right now.

### Describe the solution you'd like

1. You can place (multiple) variable input placeholders anywhere in a canned response
2. When using the canned response, the user is prompted to fill in the placeholders

EDIT: Making this request a little clearer

<sub>[CW-1856](https://linear.app/chatwoot/issue/CW-1856/add-variable-inputs-to-canned-responses)</sub>

**Comment by vishnu-narayanan** [comment]
@jochenstu Thank you for the feature request. We will prioritize this in the coming sprints.

**Comment by scmmishra** [comment]
@tejaswinichile check if we already do this or not
