### ISSUE TITLE
[CW-1855] Whatsapp audio recording in .mp3 instead of .oga

### ISSUE THREAD

**Issue by ram0ng1** [chatwoot/chatwoot#7177]
### Is your feature or enhancement related to a problem? Please describe.

I would like to make a small change in chatwoot so that the audio recordings of the whatsapp type box are sent to the client in a *.mp3 format instead of the current one (*.oga).

Just for internal reasons.

### Describe the solution you'd like

I want the transmitted message to be forwarded already in .mp3 format instead of the current .oga.

### Describe alternatives you've considered

It would be nice to have an option to select what audio format should be delivered. (mp3, ova, ogg)

### Additional context

Just for internal reasons, I need to change the format from .oga to .mp3 for more familiarity and internal issues with clients.
I already considered some open issues like:

https://github.com/chatwoot/chatwoot/issues/7048
https://github.com/chatwoot/chatwoot/issues/6327
https://github.com/chatwoot/chatwoot/pull/7046

<sub>[CW-1855](https://linear.app/chatwoot/issue/CW-1855/whatsapp-audio-recording-in-mp3-instead-of-oga)</sub>

**Comment by pranavrajs** [comment]
@ram0ng1 OGA works well with WhatsApp. We can't support both recording formats at the moment. Please feel free to reopen if there is a use case that's helpful for the community. 

As an alternative, you can use the ffmpeg libraries to convert the output from Chatwoot to an mp3 format yourselves.
