### ISSUE TITLE
[CW-1850] Private Note list hasn’t been closed after selecting the agent

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7182]
### Describe the bug

When we use Private Note, the list which provides agents is not closing after selecting one of the agent

### To Reproduce

1. Navigate to any conversation
2. Click on Private note
3. Select one of the members from the list

### Expected behavior

After selecting an agent from the list, it should be displayed anymore

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

IOS

### Browser and version

Chrome 112

### Additional context

https://www.loom.com/share/55f8b46856d24db7a1127ca3eb3fbcdf

<sub>[CW-1850](https://linear.app/chatwoot/issue/CW-1850/private-note-list-hasnt-been-closed-after-selecting-the-agent)</sub>

**Comment by muhsin-k** [comment]
@Edik-Apoyan Can you please type the "@" symbol in the private note section instead of in the reply ?

**Comment by Edik-Apoyan** [comment]
@muhsin-k as you mentioned, it is working by that way, but if it is possible can you fix the way which I had mentioned, or it’s impossible?

**Comment by muhsin-k** [comment]
@Edik-Apoyan Thank you for your valuable feedback. We will address this issue in our upcoming releases.

**Comment by LiamAshdown** [comment]
@sojan-official This appears to be fixed. I cannot replicate this.
