### ISSUE TITLE
Notification "The identity of the user is not verified" although CD fields are filled 

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7183]
### Describe the bug

The notification "The identity of the user is not verified" is showing, although CD fields are filled 

### To Reproduce

1. Navigate to conversations
2. Make sure you have a conversation
3. Open contact details
4. Fill up all the fields

### Expected behavior

If the user's contact detail fields are filled up, there shouldn’t be displayed a notification that user hasn’t been verified.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

IOS

### Browser and version

Chrome 112

### Additional context

https://www.loom.com/share/2e9dcb4f32174816995c5cdaa1b675df

**Comment by vishnu-narayanan** [comment]
@Edik-Apoyan The `verification` tag is not based on the contact details.  Refer https://www.chatwoot.com/docs/product/channels/live-chat/sdk/identity-validation/ to learn more.

**Comment by Edik-Apoyan** [comment]
@vishnu-narayanan thanks a lot, you can close this issue
