### ISSUE TITLE
[CW-1920] Chat widget closes inactive conversations in about 130 seconds with "Closed by timeout." message.

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#7188]
### Describe the bug

Inactive chat widget conversations end automatically after approximately 130 seconds.

### To Reproduce

In self-hosted environment, start a conversation in any chat widget and wait for approximately 130 seconds. A "Closed by timeout." message should appear and the conversation should automatically end.

### Expected behavior

Idle chat widget conversations have a timeout limit of 3600 seconds.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 10 Enterprise, Version 10.0.19045 Build 19045

### Browser and version

Mozilla Firefox 113.0.1

<sub>[CW-1920](https://linear.app/chatwoot/issue/CW-1920/chat-widget-closes-inactive-conversations-in-about-130-seconds-with)</sub>

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan To our knowledge, there is no load balancer between the self-hosted Chatwoot and the chat widget. The self-hosted Chatwoot's built-in nginx webserver's "keepalive_timeout" and "proxy_read_timeout" is configured as 3600s. Could you please direct us to a correct test procedure?

**Comment by pranavrajs** [comment]
@Diplomat-LV Can you please share a screencast?

**Comment by Diplomat-LV** [comment]
@pranavrajs The following link contains an unedited video of two chat widgets who reside on the same self-hosted server and produce the same timeout results.

Widget Timeout
[https://failiem.lv/u/cpmagh7ff](url)

**Comment by vishnu-narayanan** [comment]
@Diplomat-LV The timeout message seems to come from the bot. Could you share more details about your bot setup?
![image](https://github.com/chatwoot/chatwoot/assets/3526167/f0c200da-ca90-47a1-a0e3-c6eaa266591f)

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan The following screenshot contains our bot settings and we will be glad to provide additional information.

<img width="960" alt="Bot Settings" src="https://github.com/chatwoot/chatwoot/assets/118850916/1f340d56-c82b-45f6-be11-39f070673f9e">

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan Can we provide additional information to help solve this issue?

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan Any news?

**Comment by Diplomat-LV** [comment]
@vishnu-narayanan After intensive testing and troubleshooting it was concluded that the timeout was caused by adapter which resides betwean Chatwoot API and our custom chat API. Appologies for opening the ticket.

**Comment by vishnu-narayanan** [comment]
@Diplomat-LV thank you for reporting back.
