### ISSUE TITLE
Unable to update Inbox preferences

### ISSUE THREAD

**Issue by danielthedifficult** [chatwoot/chatwoot#7191]
### Describe the bug

When attempting to update values, I get a 500 error.

### To Reproduce

1. Visit Inbox preferences (`/app/accounts/#/settings/inboxes/#`)
2. Change a value
3. Click "Update" button

### Expected behavior

Updating preferences should work :)

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Linux

### Browser and version

Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (x86_64)

### Docker (if applicable)

```
root@gv-cicd-test1-u64:/opt/app/chatwoot# docker version
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.3
 Built:             Thu Apr 27 05:57:17 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.1
  Git commit:       20.10.21-0ubuntu1~22.04.3
  Built:            Thu Apr 27 05:37:25 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3.1
  GitCommit:        
 runc:
  Version:          1.1.4-0ubuntu1~22.04.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
root@gv-cicd-test1-u64:/opt/app/chatwoot# docker info
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 24
  Running: 11
  Paused: 0
  Stopped: 13
 Images: 26
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: journald
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-72-generic
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.883GiB
 Name: gv-cicd-test1-u64
 ID: HKJP:B3ZM:NVVK:OPGP:6XPM:O6T3:LZ55:OUX5:CD25:TFU3:LR4R:WWLX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: true

root@gv-cicd-test1-u64:/opt/app/chatwoot# docker-compose version
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.6
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
root@gv-cicd-test1-u64:/opt/app/chatwoot# 
```

### Additional context

I am seeing that my browser's PATCH request is sending `portal_id: null` (among other variables also null) as part of the payload, and the logs on the server confirm that is part of the problem.

<img width="673" alt="Screen Shot 2023-05-25 at 12 31 24 PM" src="https://github.com/chatwoot/chatwoot/assets/1290033/d477d247-97bb-476c-9a5a-a1582935ab5d">

<img width="1317" alt="Screen Shot 2023-05-25 at 12 28 10 PM" src="https://github.com/chatwoot/chatwoot/assets/1290033/08d0afb2-c4c4-4bee-b8ef-4f036a85256b">

**Comment by pranavrajs** [comment]
@danielthedifficult Did you run the database migrations properly? It seems like the database is missing the portal_id attribute.

**Comment by danielthedifficult** [comment]
Hi @pranavrajs, I ran the following because this was similar to a problem I had before with Chatwoot

```

docker-compose down
docker-compose pull
docker-compose up -d
docker exec -it $(basename $(pwd))-rails-1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'
```

**Comment by pranavrajs** [comment]
@danielthedifficult Sorry about missing this out. Are you still having this issue?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.

**Comment by danielthedifficult** [comment]
@pranavrajs my apologies for not following up. Yes, the db migration script worked. Thanks!
