### ISSUE TITLE
[CW-1900] UI issue on Confirm Deletion pop up window

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7197]
### Describe the bug

There is an UI issue on "Confirm Deletion" pop up window

### To Reproduce

1. Add a new label
2. Navigate to Label's page and delete

### Expected behavior

When the length of the label is max, it should be displayed with 3 dots

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

IOS

### Browser and version

Chrome 112

### Additional context

<img width="1347" alt="Screenshot 2023-05-26 at 12 19 31" src="https://github.com/chatwoot/chatwoot/assets/104565086/3b185928-9708-437a-bc5c-1c4ce551f0c7">

<sub>[CW-1900](https://linear.app/chatwoot/issue/CW-1900/ui-issue-on-confirm-deletion-pop-up-window)</sub>

**Comment by memorycancel** [comment]
Can I pick this? I create a PR #7386 @vishnu-narayanan

**Comment by vishnu-narayanan** [comment]
@memorycancel Sure, thank you.
