### ISSUE TITLE
[CW-1898] Additional Widget position options in chatwootSettings

### ISSUE THREAD

**Issue by robertjkeck2** [chatwoot/chatwoot#7199]
### Is your feature or enhancement related to a problem? Please describe.

I have an entire page dedicated to chat support on my website and even with the `.toggle` method, I am only able to show the widget on the left or right side of the screen. This looks really wonky since there is nothing else on the screen at that time.

### Describe the solution you'd like

I'd like for the widget to have an option to be positioned center (preferably vertically and horizontally centered on the page). This could be done with a `position: center` setting.

### Describe alternatives you've considered

I've attempted to use the iframe URL to do this, but as others have mentioned (see #1237) this seriously restricts the user experience and is still a pain to style.

<sub>[CW-1898](https://linear.app/chatwoot/issue/CW-1898/additional-widget-position-options-in-chatwootsettings)</sub>

**Comment by pranavrajs** [comment]
Closed this in favor of https://linear.app/chatwoot/issue/PR-891/feat-dynamic-widget-repositioning-based-on-webpage-layout
