### ISSUE TITLE
Fix "method_complexity" issue in app/javascript/src/helper/APIHelper.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#72]
Function `parseErrorCode` has a Cognitive Complexity of 6 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/helper/APIHelper.js#issue_5d87480387cf19000100018c

**Comment by alvintang** [comment]
Hi. I'd like to help out with this. Is there a way I can check via codeclimate if the submitted PR passes the Cognitive Complexity allowed?

**Comment by n1rna** [comment]
pushed my refactor on this function.
