### ISSUE TITLE
Unable deactivate Enable auto assignment Whatsapp Inbox setting

### ISSUE THREAD

**Issue by rolymaz** [chatwoot/chatwoot#7201]
### Describe the bug

Version 2.17
I have a Whatsapp Inbox. When I try disable the Enable auto assignment (untick it), i receive the pop-up that says Inox Settings Successfully Updated. but when i leave the Settings page, and return to it, it is still enabled.

Here is the log:
May 28 17:15:48 chatwoot-voachat chatwoot-web.1[1617]: I, [2023-05-28T17:15:48.486952 #1617]  INFO -- : [8b90bc92-0acf-4eea-955d-c8871282950f] Processing by Api::V1::Accounts::InboxesController#update as JSON

May 28 17:15:48 chatwoot-voachat chatwoot-web.1[1617]: I, [2023-05-28T17:15:48.487018 #1617]  INFO -- : [8b90bc92-0acf-4eea-955d-c8871282950f]   Parameters: {"enable_auto_assignment"=>false, "auto_assignment_config"=>{"max_assignment_limit"=>nil}, "account_id"=>"1", "id"=>"1", "inbox"=>{"enable_auto_assignment"=>false, "auto_assignment_config"=>{"max_assignment_limit"=>nil}}}

May 28 17:15:48 chatwoot-voachat chatwoot-web.1[1617]: I, [2023-05-28T17:15:48.498440 #1617]  INFO -- : [8b90bc92-0acf-4eea-955d-c8871282950f] Completed 422 Unprocessable Entity in 11ms (Views: 0.2ms | ActiveRecord: 2.6ms | Allocations: 3851)

May 28 17:15:48 chatwoot-voachat chatwoot-web.1[1617]: I, [2023-05-28T17:15:48.498870 #1617]  INFO -- : source=rack-timeout id=8b90bc92-0acf-4eea-955d-c8871282950f timeout=15000ms service=15ms state=completed

May 28 17:15:53 chatwoot-voachat chatwoot-web.1[1617]: I, [2023-05-28T17:15:53.269997 #1617]  INFO -- : source=rack-timeout id=0082754f-5eb1-47dc-99f7-f989def98b3b timeout=15000ms state=ready

### To Reproduce

I have restarted the VM, and chatwoot service. 
I navigated back to inbox settings, and attempted to deactivate the setting. 
After navigating away and return back to the setting, the setting is still enabled

### Expected behavior

The setting should be disabled

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu Linux

### Browser and version

Firefox 113.0

**Comment by rolymaz** [comment]
I upgraded to 2.17.1 and issue still persists.

**Comment by sojan-official** [comment]
@rolymaz could you check the browser console and see if the API returns any error message ?

**Comment by rolymaz** [comment]
Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
    be VueJS
    Ms index.js:86
    O vuex.js:771
    commit vuex.js:470
    commit vuex.js:469
    _withCommit vuex.js:574
    commit vuex.js:468
    commit vuex.js:420
    updateConversationLastActivity actions.js:342
    O vuex.js:778
    dispatch vuex.js:497
    dispatch vuex.js:416
    onMessageCreated actionCable.js:114
    onReceived BaseActionCableConnector.js:86
    h action_cable.js:536
    notify action_cable.js:535
    message action_cable.js:369
3 [vue.common.prod.js:404](webpack:///node_modules/vue/dist/vue.common.prod.js)

**Comment by rolymaz** [comment]
TypeError: this.inbox.auto_assignment_config is undefined
[vue.common.prod.js:659:10](webpack:///node_modules/vue/dist/vue.common.prod.js)

**Comment by rolymaz** [comment]
Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
    be VueJS
    Ms index.js:86
    O vuex.js:771
    commit vuex.js:470
    commit vuex.js:469
    _withCommit vuex.js:574
    commit vuex.js:468
    commit vuex.js:420
    updateConversationLastActivity actions.js:342
    O vuex.js:778
    dispatch vuex.js:497
    dispatch vuex.js:416
    onMessageCreated actionCable.js:114
    onReceived BaseActionCableConnector.js:86
    h action_cable.js:536
    notify action_cable.js:535
    message action_cable.js:369
3 vue.common.prod.js:404:6
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 4
vue.common.prod.js:659:10
Uncaught TypeError: right-hand side of 'in' should be an object, got undefined
    be VueJS
    Ms index.js:86
    O vuex.js:771
    commit vuex.js:470
    commit vuex.js:469
    _withCommit vuex.js:574
    commit vuex.js:468
    commit vuex.js:420
    updateConversationLastActivity actions.js:342
    O vuex.js:778
    dispatch vuex.js:497
    dispatch vuex.js:416
    onMessageCreated actionCable.js:114
    onReceived BaseActionCableConnector.js:86
    h action_cable.js:536
    notify action_cable.js:535
    message action_cable.js:369
4 vue.common.prod.js:404:6
XHRPATCH
https://vodachat.coactivate.co.za/api/v1/accounts/1/inboxes/1
[HTTP/2 422 Unprocessable Entity 31ms]

TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 10
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    promise callback*yB/< index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    push vue-router.esm.js:2497
    push vue-router.esm.js:2911
    O vue-router.esm.js:1131
    VueJS 33
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 10
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    promise callback*yB/< index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    push vue-router.esm.js:2497
    push vue-router.esm.js:2911
    O vue-router.esm.js:1131
    VueJS 33
vue.common.prod.js:659:10
    VueJS 13
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    (Async: promise callback)
    yB index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    push vue-router.esm.js:2497
    push vue-router.esm.js:2911
    O vue-router.esm.js:1131
    VueJS 33
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 10
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    promise callback*yB/< index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    push vue-router.esm.js:2497
    push vue-router.esm.js:2911
    O vue-router.esm.js:1131
    VueJS 33
vue.common.prod.js:659:10
XHRPATCH
https://vodachat.coactivate.co.za/api/v1/accounts/1/inboxes/1
[HTTP/2 422 Unprocessable Entity 31ms]

TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 10
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    promise callback*yB/< index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    a vue-router.esm.js:2476
vue.common.prod.js:659:10
TypeError: this.inbox.auto_assignment_config is undefined
    setDefaults CollaboratorsPage.vue:129
    inbox CollaboratorsPage.vue:120
    VueJS 10
    init vue-router.esm.js:2878
    init vue-router.esm.js:2877
    updateRoute vue-router.esm.js:2321
    transitionTo vue-router.esm.js:2186
    confirmTransition vue-router.esm.js:2308
    r vue-router.esm.js:1947
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2301
    r vue-router.esm.js:1947
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    be vue-router.esm.js:2089
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1951
    _ vue-router.esm.js:2289
    bB index.js:89
    bB index.js:116
    yB index.js:143
    promise callback*yB/< index.js:134
    _ vue-router.esm.js:2270
    r vue-router.esm.js:1950
    r vue-router.esm.js:1954
    r vue-router.esm.js:1954
    Oe vue-router.esm.js:1959
    confirmTransition vue-router.esm.js:2297
    transitionTo vue-router.esm.js:2185
    push vue-router.esm.js:2497
    push vue-router.esm.js:2911
    O vue-router.esm.js:1131
    VueJS 33
vue.common.prod.js:659

**Comment by rolymaz** [comment]
I see I get a 422 Unprocessable Entity error, with reason: Out of office message is too long (maximum is 255 characters)

I will correct this and revert. 


<html><body>
<span class="message-body-wrapper">

PATCH | https://vodachat.coactivate.co.za/api/v1/accounts/1/inboxes/1
-- | --


</span>
</body>
</html>

Status
422
Unprocessable Entity

{"enable_auto_assignment":false,"auto_assignment_config":{"max_assignment_limit":null}}

I get this error:
{"message":"Out of office message is too long (maximum is 255 characters)","attributes":["out_of_office_message"]}

**Comment by sojan-official** [comment]
@rolymaz  in the latest release we have added a limit to all the text fields as a security fix. in your case it seems like the out of office message saved on your inbox is lengthier than the allowed value. could you try updating that to be under 255 limit ?

**Comment by rolymaz** [comment]
Many thanks for the quick response and support.

I suggest that to prevent this again, it would be great if this error message is displayed, instead of the Inbox Settings Successfully Updated pop up.
