### ISSUE TITLE
[CW-1995] No message_created webhook for auto-reply messages

### ISSUE THREAD

**Issue by ksdfg-navana** [chatwoot/chatwoot#7206]
### Describe the bug

We have enabled auto-reply messages for greeting and business hours for an API channel. However, we receive no `message_created` webhooks any of the messages even though the messages show up in the chat for the agent.
![image](https://github.com/chatwoot/chatwoot/assets/81582101/38433b16-4659-43fd-80f1-9a44921442cc)

Instead, we _sometimes_ receive the following `message_created` webhook for the incoming message, which contains the auto-reply message in the `messages` field. This behaviour is not consistent, and we sometimes receive the incoming message webhook with just the incoming message details. Please check the logs below for the webhook payloads (logged as `request_body`) of incoming messages outside of business hours
- [Logs for webhook with auto-reply message](https://katb.in/oveqesukopo.json)
- [Logs for webhook without auto-reply message](https://katb.in/imohasutala.json)

The same behaviour is observed for the greeting message.

### To Reproduce

1. Setup greeting message and/or business hours for an API channel inbox.
2. Start a conversation.
3. Send an initial message.

### Expected behavior

We should get a `message_created` webhook with
- `message_type: outgoing`
- `content: {{inbox.out_of_office_message}}` or `content: {{inbox.greeting_message}}`

### Environment

Kubernetes

### Cloud Provider

Azure

### Platform

None

<sub>[CW-1995](https://linear.app/chatwoot/issue/CW-1995/no-message-created-webhook-for-auto-reply-messages)</sub>

**Comment by vishnu-narayanan** [comment]
@tejaswinichile Could you take a look?
