### ISSUE TITLE
[CW-1904] [CW-1823] Custom attribute date value is not working properly

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#7207]
I have added a custom attribute to our contacts of type Date. Regardless of how I set the value of this attribute (SDK or attribute calendar picker GUI), the displayed date is incorrect. It's showing a date that's 1-2 days earlier than whatever I set. I suspect it has something to do with serializing/deserializing the date object across different timezones.

[https://discord.com/channels/647412545203994635/1109141697327284294/1109141697327284294](https://discord.com/channels/647412545203994635/1109141697327284294/1109141697327284294)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1823](https://linear.app/chatwoot/issue/CW-1823/custom-attribute-date-value-is-not-working-properly)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1823](https://linear.app/chatwoot/issue/CW-1823/custom-attribute-date-value-is-not-working-properly)</sub>

**Comment by muhsin-k** [comment]
[https://www.loom.com/share/1e302845f7834d399b48e9b0763e020d](https://www.loom.com/share/1e302845f7834d399b48e9b0763e020d)

*I can reproduce this. I believe it's the issue with the date and time format. May be we should only save it as the date without the time.*

**Comment by muhsin-k** [comment]
@pranavrajs will check the PR and do the investigation.

**Comment by deyvisenrique** [comment]
thanks for this update.
I am testing and now I have noticed that when saving change the format to:
month / day / Year.
Can you please keep the correct order:
day - month - Year

<img width="342" alt="Screenshot 2023-06-18 at 23 25 11" src="https://github.com/chatwoot/chatwoot/assets/15927272/b79854d1-23df-405b-bdb7-e7bf091602ef">
<img width="345" alt="Screenshot 2023-06-18 at 23 25 17" src="https://github.com/chatwoot/chatwoot/assets/15927272/f017d104-05a8-421b-ad05-2902dcd8a2ca">
