### ISSUE TITLE
Conversations between agents

### ISSUE THREAD

**Issue by sinapse-i-a** [chatwoot/chatwoot#7208]
### Is your feature or enhancement related to a problem? Please describe.

.

### Describe the solution you'd like

I've been searching the ISSUE logs to understand if it's possible to carry out a conversation between agents, that is, agent A starting a conversation directly with agent B. Could someone tell me if this task has been developed in Chatwoot?

### Describe alternatives you've considered

Perhaps it would be interesting to have this option, where the agent could click on other agents online, and start a conversation directly with them.

### Additional context

.

**Comment by vishnu-narayanan** [comment]
@sinapse-i-a This feature has yet to be available in Chatwoot, i.e. private conversation between agents. 

However, Agents could collaborate over a conversation using the private notes feature. 
Ref: https://www.chatwoot.com/docs/user-guide/conversation-workflow/#private-chat-with-agents

**Comment by sojan-official** [comment]
ref: https://github.com/orgs/chatwoot/discussions/5121
