### ISSUE TITLE
Implement a mechanism to override the same name file in views

### ISSUE THREAD

**Issue by memorycancel** [chatwoot/chatwoot#7212]
can we implement a mechanism to override the same name file which like 

`custom/app/views/dashboard/_footer.html.erb` 
 override 
`app/views/dashboard/_footer.html.erb`

@sojan-official @pranavrajs

_Originally posted by @memorycancel in https://github.com/chatwoot/chatwoot/issues/7140#issuecomment-1566700986_

**Comment by pranavrajs** [comment]
@memorycancel Can you please share a use-case why this is required?

**Comment by memorycancel** [comment]
> @memorycancel Can you please share a use-case why this is required?

@pranavrajs Thank you for reply!  I think this mechanism is required for the Community or Enterprise user to custom their views page in `custom` folder, this allows custom code to be decoupled through a separate folder, which is like `custom` folder, this inspiration comes from `Gitlab`，this is a successful precedent. reference

+ https://gitlab.com/gitlab-org/gitlab/-/tree/master/ee
+ https://gitlab.com/gitlab-jh/gitlab/-/tree/main-jh/jh (`jh` folder is equivalent to `custom` folder)

## background information

I'm Chatwoot fan and plan to promote Chatwoot in China. I built `https://crm.tommytech.online`.
 For me , I'd like to puts some links like `Record information`, `Copyright info` and `terms` in my `footer` page in China， it's customary, every online website must append these messages in footer.

So I created  a commit https://github.com/TommyTechWorkshop/chatwoot/commit/9c349a36b000ba32e549d1393220d14c445f234d . This commit include mechanism to override the same name file in views.If we have this mechanism, the Community or Enterprise user can custom the widgets page in custom folder, admin area layouts etc.. like:

`app/views/widgets/show.html.erb` 
`custom/app/views/widgets/show.html.erb`

Long for short,  this mechanism can make chatwoot more flexible in technology and business, and link with companies in more regions. How do you think? @pranavrajs 

## What's more

We also need a lot of mechanisms like this in the future.like:

+ model controller( I see the `enterprise` had implemented in https://github.com/chatwoot/chatwoot/blob/develop/config/initializers/01_inject_enterprise_edition_module.rb )
+ migration
+ spec
+ helper
+ javascript

etc..

Sorry, I talked too much, I'm clear that it's a tough task and happy to work on it. Thank you so much again for reply @pranavrajs
