### ISSUE TITLE
Custom redis DB number 

### ISSUE THREAD

**Issue by hexclann** [chatwoot/chatwoot#7215]
### Describe the bug

Is it possible to set custom redis DB number? I don't see any option in the .env example file

### To Reproduce

Have not installed chatwoot yet

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

None

**Comment by vishnu-narayanan** [comment]
@hexclann What do you mean by custom Redis DB number?

**Comment by hexclann** [comment]
Sorry for the confusing description. Redis supports logical database index right? Is it possible to define the index?

https://www.digitalocean.com/community/cheatsheets/how-to-manage-redis-databases-and-keys#managing-databases

Because I use one redis instance with multiple self-hosted services and I don't want to use one index for all of them (to avoid key collisions)

**Comment by sojan-official** [comment]
@hexclann We work under the assumption that the Redis instance is dedicated to Chatwoot Installation.

**Comment by hexclann** [comment]
If I want to host multiple instances of chatwoot, do I need to have seperate redis instances for each chatwoot?

**Comment by sojan-official** [comment]
@hexclann Chatwoot supports multi-tenancy. You can have separate accounts for each of your businesses in a single chatwoot installation.

**Comment by hexclann** [comment]
@sojan-official that is great, I will check it out. Which redis databases does chatwoot use by default to store the keys? If it's database 0, then I will configure my other apps to use different redis databases instead of 0

**Comment by vishnu-narayanan** [comment]
@hexclann Could you try if this works? Use the `REDIS_URL` env variable to define the index.

For example, `redis://[:PASSWORD@]HOST[:PORT][/DATABASE]` where `DATABASE` is the index you want to use.

**Comment by vishnu-narayanan** [comment]
I am closing this for now. Please reopen if this did not work
