### ISSUE TITLE
[CW-1913] Home page is showing instead of message view when send message via API

### ISSUE THREAD

**Issue by muhsin-k** [chatwoot/chatwoot#7217]
The user click on the "chat with us" button and trigger the open widget event. My process for the webhook get contact id and source id to create an conversation with api and sends after creation a message. But the user see in this moment this: Instead of the conversation and the message, which I did with the api, only the button change from "Start conversation" to "Continue conversation". The user have to click on "Continue ..." and than it looks like as it should be (picture 3) How can I skip the "Continue ..." step?

[https://discord.com/channels/647412545203994635/1109064375190433862](https://discord.com/channels/647412545203994635/1109064375190433862)

[596553a0-6a32-44a5-98a0-b9ea404c3d93](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/d87060ff-556a-4b97-b978-68b96a055858/596553a0-6a32-44a5-98a0-b9ea404c3d93)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-1913](https://linear.app/chatwoot/issue/CW-1913/home-page-is-showing-instead-of-message-view-when-send-message-via-api)</sub>

**Comment by Ghost108** [comment]
as long as there is no fix yet, there might be a workaround?
