### ISSUE TITLE
ERROR in ./node_modules/chart.js/src/elements/element.arc.js

### ISSUE THREAD

**Issue by robson-jardim** [chatwoot/chatwoot#722]
**Describe the bug**
Every time that I stop the server and try to restart I'm getting this error

**To Reproduce**
1. git clone https://github.com/chatwoot/chatwoot.git
2. $ cp .env.example .env
3. $ docker-compose build
4. $ docker-compose run --rm rails bundle exec rails db:reset
5. $ docker-compose up
6. Ctrl+C
7. $ docker-compose build
8. $ docker-compose run --rm rails bundle exec rails db:reset

**Expected behavior**
After restart the server should works again.

**Screenshots**
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/elements/element.arc.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/elements/element.line.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/elements/element.point.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/elements/element.rectangle.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.bar.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.bubble.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.doughnut.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.line.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.polarArea.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/controllers/controller.radar.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Bar.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Bubble.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Doughnut.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Line.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.PolarArea.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Radar.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/charts/Chart.Scatter.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: EEXIST: file already exists, mkdir '/app/tmp/cache/webpacker/babel-loader-node-modules'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.interaction.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/085859b4195648a02d67eb125bdde6a3.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.scaleService.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/314c73de625ab6be2e304468edc7430a.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.scale.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/32454ef39a3e5d2f9979fd0ca19ca638.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/scales/scale.logarithmic.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/349fc8a46e227b7a2347a43023310660.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/scales/scale.linear.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/437ad8e07f9526e6c1b01947b1e64b6b.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.layoutService.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/46a0dbc5c674320d6776e0d26413b46d.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.canvasHelpers.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/5930f9dabb905e5f8ec4b55c76c63567.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.helpers.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/65a0429b1ab432ab5f098ed37a58042f.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/scales/scale.category.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/775b006e6f979d59a5c4ff6749d4dde5.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.legend.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/7c67f9ddc9af3e4184f5214338722fe5.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.title.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/97fdfac048783084d206914eac15300a.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.datasetController.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/a801db2c5eb955656bb5753eda75eb36.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.element.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/b09c7a453a6302c05260db0d01e77153.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.controller.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/b23f687d6b17d7c336b5f3e780338d16.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.animation.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/d08a8e0d6b35bd6aa61d5bb93059db53.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/scales/scale.radialLinear.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/da599526e42afc85a63b78262d5f4778.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/core/core.tooltip.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
webpack_1   | Error: ENOENT: no such file or directory, open 'tmp/cache/webpacker/babel-loader-node-modules/daaa8d08d5043da15a63bc3ac9c12b01.json'
webpack_1   | 
webpack_1   | ERROR in ./node_modules/chart.js/src/scales/scale.time.js
webpack_1   | Module build failed (from ./node_modules/babel-loader/lib/index.js):
**Desktop (please complete the following information):**

**Comment by pranavrajs** [comment]
looks like yarn command has not run, @robson-jardim Are you sure that the steps followed are as per the doc?

**Comment by pranavrajs** [comment]
@robson-jardim Closing this as there is no response from your end. Please feel free to re-open if you have additional information.
