### ISSUE TITLE
Webhook url is too long (maximum is 255 characters)

### ISSUE THREAD

**Issue by lsouzapedroso** [chatwoot/chatwoot#7221]
### Describe the bug

I received this message after updating to version 2.17.1. Is it possible to remove this character limiter?
![image](https://github.com/chatwoot/chatwoot/assets/44585389/4003ffe0-4017-4c93-9ae5-03dbf2c26b4c)

### To Reproduce

1. In settings
2. Inboxes
3. Inboxes Settings
4. Webhook URL

### Expected behavior

Save with any number of characters.

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Brave 1.51.118

### Additional context

Hosted on a Vm in Proxmox

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/7098
