### ISSUE TITLE
Realtime chat translation

### ISSUE THREAD

**Issue by robson-jardim** [chatwoot/chatwoot#723]
**Is your feature request related to a problem? Please describe.**
Enable conversation between two people that speak in different languages.

**Describe the solution you'd like**
Let's take an example where a US company I'd run business in Brazil. To improve the customer experience the US company could offer Portuguese support once all the notes was translated before being presented to the customer, and all the customer messages should be translated to English before be presented to Agent.

We could use any integrated translate API to offer this service.

**Describe alternatives you've considered**

**Additional context**

**Comment by imantonio** [comment]
@robson-jardim you basically described what we do at [Unbabel](https://unbabel.com/)!

We already integrate with several platforms (Salesforce, Zendesk, Freshdesk, Helpshift, Kustomer, and others) and you can check our API docs [here](https://developers.unbabel.com/). Chat API is the real-time, machine-translation endpoint and Ticket API is our asynchronous, human-translation endpoint. 

I'd be super keen to support the Chatwood team or the community in building an integration with our service.

**Comment by brundles** [comment]
Hi @robson-jardim - is this basically the same as https://github.com/chatwoot/chatwoot/issues/2011 ?

**Comment by pranavrajs** [comment]
Closing this in favour of #2011
