### ISSUE TITLE
Error while trying to deserialize arguments

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#7237]
### Describe the bug

When a new user send a message in Facebook Messager channel, the avatar does not appear.
![image](https://github.com/chatwoot/chatwoot/assets/88042866/7c5890d4-3f3e-4e42-b094-0ede0008b10e)

### To Reproduce

Configure a channel Messenger in CW.
Send a message via Facebook Messenger.

### Expected behavior

The avatar must appear, but i receive this error:
May 29 13:52:58 ip-172-31-80-242 chatwoot-worker.1[101259]: E, [2023-05-29T13:52:58.323084 #101259] ERROR -- : Skipping job because of ActiveJob::DeserializationError (Error while trying to deserialize arguments: Couldn't find Contact with 'id'=155360)
May 29 13:52:58 ip-172-31-80-242 chatwoot-worker.1[101259]: E, [2023-05-29T13:52:58.323814 #101259] ERROR -- : Discarded Avatar::AvatarFromUrlJob due to a ActiveJob::DeserializationError.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Debian

### Browser and version

Chrome Latest

**Comment by pranavrajs** [comment]
Duplicate: https://github.com/chatwoot/chatwoot/issues/6761. We will track it here.
