### ISSUE TITLE
[CW-1994] Channel greeting message not showing for agents

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7239]
### Describe the bug

On a new conversation, there is a greeting message that comes through as well. (Website Channel)
But for some reason it doesn't show for all agents. I have seen it show for some and not others.
Agent have to refresh chatwoot to be able to see the greeting message.

P.S. We use the greeting message's read status to tell which conversation is real when we get duplicate message #6128 .
Hopefully it gets fixed soon.

### Before refreshing - No greeting

![image](https://github.com/chatwoot/chatwoot/assets/72418976/d3652a9e-4d82-4c92-a93b-852ba94a6e51)

### After refreshing - The greeting appears

![image](https://github.com/chatwoot/chatwoot/assets/72418976/b4c10342-3960-43c9-8522-047190ce348a)

### To Reproduce

1. Have multiple agents logged into chatwoot.
2. Start a new conversation via website. (Dont know if this happens for other channels)
3. For some agents the greetings will show and for some it wont.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

<sub>[CW-1994](https://linear.app/chatwoot/issue/CW-1994/channel-greeting-message-not-showing-for-agents)</sub>

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if there are more reports of this in latest versions.
