### ISSUE TITLE
Chatwoot Power Ups

### ISSUE THREAD

**Issue by robson-jardim** [chatwoot/chatwoot#724]
**Is your feature request related to a problem? Please describe.**
Create an API for 3 parties to create Power-Ups to improve chat capabilities. Each Power-Up could be free or billable.

**Describe the solution you'd like**
Similar to Trello (www.trello.com)
![image](https://user-images.githubusercontent.com/10334548/79418211-65e5e100-7f8a-11ea-9f80-9f1373e0efaa.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by pranavrajs** [comment]
https://developer.atlassian.com/cloud/trello/guides/power-ups/managing-power-ups/

**Comment by pranavrajs** [comment]
Closing this as we have [Dashboard Apps](https://www.chatwoot.com/docs/product/others/dashboard-apps/) now.
