### ISSUE TITLE
[CW-1992] 100s of Push Notifications all at once

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7240]
### Describe the bug

Hey, 
We use the following push notification settings.
![image](https://github.com/chatwoot/chatwoot/assets/72418976/f4bf7675-ce48-4105-b339-dcc4e8444283)

Our customer support is 24/7 so when an agents starts their shift the next day.
As soon as they open the browser they get overwhelmed by the number of notifications.

### To Reproduce

1. have push notifications configured
2. start a new conversation in an another browser (acting as customer)
3. and assign yourself to it in chatwoot
4. close the chatwoot browser (chrome in my case)
5. Type a bunch of messages in the customer chat window
6. Open the chatwoot browser
7. The notifications for all those messages will come up all at once.

### Expected behavior

Now I understand whats happening here. 
The agents are getting notifications exactly how they have set them in settings.

We do want push notifications when agents are live and available.
But getting 100s of notifications as soon as I start my browser for conversations that are already resolved is meaningless.

I wonder if this solution will work:
If an agent is offline/busy, push notifications shouldn't get sent to that agent.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome

<sub>[CW-1992](https://linear.app/chatwoot/issue/CW-1992/100s-of-push-notifications-all-at-once)</sub>

**Comment by vishnu-narayanan** [comment]
@Jatin-MYST Thank you for the feature request.  We will prioritise this in the coming weeks.
