### ISSUE TITLE
[CW-1993] Push notifications after logging out

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7241]
### Describe the bug

Hey,
I am getting push notifications even after logging out. 
This is a potential security risk because the push notifications have the message text.

### To Reproduce

1. Setup push notifications
2. Log out of chatwoot
3. Do an action that should generate a notification for you e.g. start a new conversation (acting as customer)
4. Push notification comes up

### Expected behavior

After logging out, push notifications should no longer be generated.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome

<sub>[CW-1993](https://linear.app/chatwoot/issue/CW-1993/push-notifications-after-logging-out)</sub>

**Comment by muhsin-k** [comment]
[https://github.com/chatwoot/chatwoot-mobile-app/issues/430](https://github.com/chatwoot/chatwoot-mobile-app/issues/430)
