### ISSUE TITLE
Support for MinIO

### ISSUE THREAD

**Issue by tobsowo** [chatwoot/chatwoot#7246]
### Is your feature or enhancement related to a problem? Please describe.

Add the option of Hetzner Storage Box to the current list of storage.

### Describe the solution you'd like

The ability to use Hetzner Storage Box.

**Comment by pranavrajs** [comment]
@tobsowo Is Hetzner Storage Box similar to S3/GCS? I don't think the products are comparable. Please feel free to add more context here.

**Comment by tobsowo** [comment]
No, they are not similar and Hetzner will not work as S3/GCS but maybe supporting MinIO will be a good alternative.
Let me update tye title if I can.

**Comment by vishnu-narayanan** [comment]
@tobsowo Minio is already supported along with any s3 API compatible service.

ref: https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers#using-amazon-s3-compatible-service
