### ISSUE TITLE
Email Inbox Getting Disconnected too frequently

### ISSUE THREAD

**Issue by infiniziconsulting** [chatwoot/chatwoot#7247]
### Describe the bug

I have two email inboxes - one on gmail and other on amazon workmail. They both were working fine before I updated to latest version of 2.17 from version 2.14

Now, I am getting that email inbox is disconnected due to configuration error. After I click on update settings, it starts working for few minutes and then again after few minutes, it stops working.

<img width="671" alt="Screenshot 2023-06-03 at 7 54 15 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/6d8efc4e-e22f-4024-be9b-0cf052e50a6a">

<img width="983" alt="Screenshot 2023-06-03 at 7 53 10 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/34c11eaa-9f14-4b75-936a-19ea79faffae">

<img width="608" alt="Screenshot 2023-06-03 at 7 57 56 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/83b2f6b4-c44b-4a04-922f-36e54e697281">

<img width="566" alt="Screenshot 2023-06-03 at 7 58 45 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/7fd0943b-17c5-4e11-adff-3f6c786659f2">

<img width="725" alt="Screenshot 2023-06-03 at 7 52 13 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/470fbe96-2c06-44e7-b310-1076d84f7fb2">
<img width="1041" alt="Screenshot 2023-06-03 at 8 01 31 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/37042e0a-dade-4bad-84da-43b632084b40">

### To Reproduce

No steps to reproduce

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

**Comment by pranavrajs** [comment]
@infiniziconsulting Can you please share the server side logs or error logs related to disconnection? There is too little information to debug this issue.

**Comment by infiniziconsulting** [comment]
I checked sidekiq also, it is also choking again and again.

There are no error in the logs, may be I m looking at wrong place. If you can help me to check the logs at correct location, I can check and share the logs.


<img width="1253" alt="Screenshot 2023-06-04 at 2 15 37 AM" src="https://github.com/chatwoot/chatwoot/assets/45553037/486eaa02-742b-4fc8-8b77-cf95114d5073">

**Comment by pranavrajs** [comment]
Please see this to get the logs. https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl/#viewing-logs

**Comment by infiniziconsulting** [comment]
Attaching Logs of Worker and Web both. 

<img width="1440" alt="Screenshot 2023-06-04 at 2 37 16 AM" src="https://github.com/chatwoot/chatwoot/assets/45553037/00842a45-bbb6-4497-9e1a-de0400a78173">
<img width="1440" alt="Screenshot 2023-06-04 at 2 37 46 AM" src="https://git
<img width="1440" alt="Screenshot 2023-06-04 at 2 40
<img width="1308" alt="Screenshot 2023-06-04 at 2 40 58 AM" src="https://github.com/chatwoot/chatwoot/assets/45553037/37512675-5d2e-447c-b7f0-7c702c4d3f9c">
 28 AM" src="https://github.com/chatwoot/chatwoot/assets/45553037/04fd0c8d-235b-46d3-9852-126f43cae2b0">
hub.com/chatwoot/chatwoot/assets/45553037/360bfb6a-7e2f-4767-8d91-132d49b79bda">

**Comment by infiniziconsulting** [comment]
<img width="1265" alt="Screenshot 2023-06-04 at 2 44 01 AM" src="https://github.com/chatwoot/chatwoot/assets/45553037/8dec5471-1265-48d3-b450-893931bed40a">
<img width="1440" alt="web" src="https://github.com/chatwoot/chatwoot/assets/45553037/8f0b1f9b-39cf-4bbb-a514-8f9b8369b566">

**Comment by pranavrajs** [comment]
@infiniziconsulting There is not enough information on this suggesting an error. I would suggest to save the configuration once again which would reset the authorization error. Please fetch the logs around the time when the inbox disconnection happens.

**Comment by infiniziconsulting** [comment]
I have not received any disconnection error in last 2-3 hours but it is not fetching emails. Why is sidekiq choking now suddenly after the update?

Is it possible to downgrade the version to 2.14 which was working smooth?

**Comment by infiniziconsulting** [comment]
Is there any one time support plan where your team can solve the issue via screensharing?

**Comment by nicke** [comment]
Hello. Is there a solution for this? Thank you

**Comment by infiniziconsulting** [comment]
> @infiniziconsulting There is not enough information on this suggesting an error. I would suggest to save the configuration once again which would reset the authorization error. Please fetch the logs around the time when the inbox disconnection happens.

Hello, I have tried to put logs to see where the code is dying. I figured it out that emails are being fetched by the code but the code is not going to function "process_mail". I am attaching screenshot of both logs and changes in code.

<img width="1044" alt="Screenshot 2023-06-16 at 4 10 38 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/e3a56aff-d92d-4426-acfa-cc2c1cbe025f">
<img width="1440" alt="Screenshot 2023-06-16 at 4 11 22 PM" src="https://github.com/chatwoot/chatwoot/assets/45553037/382f6def-c68b-442d-8f7e-a9ad015716af">

**Comment by sojan-official** [comment]
@tejaswinichile  could you take a look ?
