### ISSUE TITLE
Feature: Add custom colors to color picker

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#725]
**Is your feature request related to a problem? Please describe.**
Website may want to match color to certain font color or logo etc.

**Describe the solution you'd like**
As a user, I would like to be able to select a color outside of the suggested color picker solutions.

**Describe alternatives you've considered**
Couldn't see where to adjust color in the code..

**Comment by pranavrajs** [comment]
We just went ahead with the default color swatch, let us see we can do a `Sketch` like color-picker

**Comment by tabrza** [comment]
Cool. Could perhaps also use this as a chance to edit the welcome message and chatbot font?

**Comment by pranavrajs** [comment]
With 1.4.0 release, we have added a feature to customise the welcome message and welcome title.

Chatbot font can be a separate ticket, we can discuss how and what all things are going to be customised.
