### ISSUE TITLE
Dashboard apps being refreshed when switching tabs

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7251]
### Describe the bug

We love the dashboard apps feature in Chatwoot.

I am not sure if this is intentional or a bug.
But when switching between messages the dashboard app.
It refreshes the dashboard app. It makes you lose all the progress on the app.

At the moment, we have put up an internal wiki on chatwoot using dashboard apps.
But relaying information back and forth between the wiki and the customer is very inconvenient at the moment.
Every time the agent has to start all over again to find the relevant information on the wiki.

In the future, we plan on putting more dashboard apps. 
But we can't because of the refresh that happens when switching between the tabs.

E.g. 
Having a form is impracticable to use in the app. 
As it would lose all progress if agent wants to get more info from the customer and needs to switch tabs.

Chatwoot version v2.17.1

### To Reproduce

1. have a dashboard app.
2. nagivate inside the app, fill a form, etc.
3. go to messages and back to the app

Loses all progress and goes back to the homepage of the app

### Expected behavior

Dashboard app should not refresh when switching between tabs.

### Environment

app.chatwoot.com

### Cloud Provider

AWS

### Platform

Browser

**Comment by muhsin-k** [comment]
@Jatin-MYST Are you experiencing the issue consistently? We have taken care of this and it should be resolved. Could you try accessing a different webpage to confirm if the issue persists? Additionally, can you provide a screencast to assist us in troubleshooting further?

**Comment by Jatin-MYST** [comment]
Hey @muhsin-k ,

Yes this is a constant issue. 

Here is a video of me using https://www.chatwoot.com as a dashboard app.

https://github.com/chatwoot/chatwoot/assets/72418976/fadb4047-bc00-47a4-bb55-c942306efb0d

PS. I was a bit surprised that chatwoot allows this iframe behaviour on their website as this is a security risk. See [here](https://auth0.com/blog/preventing-clickjacking-attacks/). 
Should probably fix that.

**Comment by Jatin-MYST** [comment]
@muhsin-k 

ahh.. I just realised that me using the word tab was probably a bit confusing. 
Apologies. I meant the dashboard app tabs.

**Comment by muhsin-k** [comment]
@Jatin-MYST We just tested using our staging environment, and it works fine. 

https://github.com/chatwoot/chatwoot/assets/12408980/3bb787ac-dcfa-4748-99ba-cd0d69bfb067

**Comment by Jatin-MYST** [comment]
@muhsin-k

huh.. then I wonder why it's refreshing like that for me 🤔. I tested it on chrome and firefox. it was refreshing on both.

Do you have any suggestions?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by muhsin-k** [comment]
Have you tried using incognito mode? It's possible that certain extensions are causing the problem. Additionally, please provide the browser logs.

**Comment by Jatin-MYST** [comment]
Hey @muhsin-k ,

I had a chance to try it on many browsers across multiple devices.
Here is what I tested:
- firefox and vivaldi with incognito and no extensions.
- chrome on 2nd pc
- on Edge on 3rd pc
- Firefox and Brave on my phone

Sorry but it didn't work anywhere and here are the logs that I was able to get.

Firefox:
It looks like something went wrong here but these seem unrelated because it didnt work on others.
![image](https://github.com/chatwoot/chatwoot/assets/72418976/013e9d08-e541-48a8-8594-36c3591a28e1)

Vivaldi(Chromium): 
Has built-in trackers and ads blocker.
Tried disabling it as well and then it produced no browser logs 
![image](https://github.com/chatwoot/chatwoot/assets/72418976/9f7add54-b887-4652-bcd2-5c3567218b11)

Chrome: 2nd pc
No logs produced.

**Comment by Jatin-MYST** [comment]
@muhsin-k I figured this one out.
my rake assests were outdated.
Turns out `cwctl --upgrade` does not do `rake assets:clean assets:clobber ` before doing `rake assets:precompile`.
(Please fix)

So, I was still serving the older version but website was showing it was on v2.17.1
I did the upgrade manually and now this is fixed.
