### ISSUE TITLE
Reverse proxy chatwoot different port

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7256]
### Describe the bug

I would like to realize, that chatwoot will be accessable over port 9999 instead of 443.
For that I am configure a reverse proxy on my synology nas:

![Bildschirmfoto 2023-06-06 um 07 01 45](https://github.com/chatwoot/chatwoot/assets/17011498/513d3df7-01aa-40c8-bf1d-90492eedf622)
(explanation: my rails container has the local port 8888)

This works.

But I have a problem with rails because it continues to use the url https://meineDomain.de instead of https://meineDomain.de:9999

The devloper console of firefox shows this error if I open the page with the web widget:

![grafik](https://github.com/chatwoot/chatwoot/assets/17011498/92da3c02-4e00-49f2-9e4a-fbb4be8ef0c6)

Also all images will not be shown:

![grafik](https://github.com/chatwoot/chatwoot/assets/17011498/e5670186-7798-44d3-90ab-c3ff9aae939e)
(left top corner shows "avatar" instead of the image)

And if the user send an image via widget, this image will not be shown in the widget and also not in the agent interface:

![grafik](https://github.com/chatwoot/chatwoot/assets/17011498/203331b8-3ff1-4cb9-99ff-94cdf030754d)

The link for "Herunterladen" (=Download) shows in the widget (without port):
https://myDomain.de/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjRFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e95be4ea08c670a6641ab259fe91f771c67934c/Bildschirmfoto%202023-06-06%20um%2006.51.38.png

and in the agent interface (with port):
https://chat.it-neuss.de:9999/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjRFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3e95be4ea08c670a6641ab259fe91f771c67934c/Bildschirmfoto%202023-06-06%20um%2006.51.38.png

But in both cases: A click on "Herunterladen" will show an page not found 404

Any idea how can I fix this?

### To Reproduce

I updated the env FRONTEND_URL of my docker containers:

Old: https://myDomain.de
New: https://myDomain.de:9999

I updated the the webwidget code: 

Old: var BASE_URL="https://myDomain.de";
New: var BASE_URL="https://myDomain.de:9999";

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

macOS 13.4

### Browser and version

Firefox 113.0.2

**Comment by pranavrajs** [comment]
@Ghost108 If you are trying to use the chatwoot app with a port, we do not support it officially. You would need a full qualified domain without a port or a subdirectory.

I would suggest using chatwoot.mydomain.de instead of mydomain.de:9999

Closing this here as this is not supported officially.
