### ISSUE TITLE
OpenAI suggestion different language

### ISSUE THREAD

**Issue by rodrigo-p-a** [chatwoot/chatwoot#7261]
### Describe the bug

I am using Chatwoot in pt_BR, but when I request suggestions using the OpenAI API, the suggestions come in English. How can I change this?

### To Reproduce

Only use suggestion button using openai official integration

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux debian 11 x64

### Browser and version

chrome 114 windows

**Comment by pranavrajs** [comment]
@rodrigo-p-a This is already covered here and will be available in the next update.


https://github.com/chatwoot/chatwoot/pull/7092
