### ISSUE TITLE
Error when sending multiple attachments for Inbox API

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#7266]
### Describe the bug

Hello!
I'm doing an API integration with Chatwoot and N8N service to send a message with an attachment. 

I use the method https://example.com/public/api/v1/inboxes/inbox_identifier/contacts/contact_identifier/conversations/id_converstation/messages. Data in form-data format. 

When sending one file, everything is OK, when there is more than one file, then an error with code 404 from the Chatwoot server. Here is information and screenshots for the N8N form https://community.n8n.io/t/http-request-sending-attachment-error-in-chatwoot-api/26814

When testing N8N sending more than one file to the test server, there are no errors. Used the service https://i.imgur.com/Of8zACP.png  
https://i.imgur.com/nndGqkQ.png

What could be the problem?

### To Reproduce

1. Sending files via N8N POST API https://{{host}}/{{api_version}}/accounts/{{account_id}}/conversations/{{conversation_id}}/messages
2. Data to send in "form-data" format
3. First attachment sent successfully to Chatwoot
4. Sending the second and subsequent attachments with an error, Chatwoot responds with a 404 error

### Expected behavior

There are no errors when sending multiple attachments

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22.04.2 LTS

### Docker (if applicable)

Version:23.0.6

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.17.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 8
  Paused: 0
  Stopped: 3
 Images: 11
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: b3lx94ymxhswiqxwoum90w3iw
  Is Manager: true
  ClusterID: jmi2rs1sa0inumb2vwbpe906u
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8  
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 10.129.0.18
  Manager Addresses:
   10.129.0.18:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-72-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.928GiB
 Name: fb-chatwoot
 ID: 2UPV:JAH3:W4JU:SJAP:IHXL:JJID:VERP:ITPM:5QWC:X7IW:NY2R:LN2R
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: atomantkras
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

Compose version v2.2.2

**Comment by vishnu-narayanan** [comment]
@aerostovtsev Which version of Chatwoot are you on? Could you confirm your axios version?

**Comment by aerostovtsev** [comment]
Hi @vishnu-narayanan 

- Chatwoot 2.17.1

- in the repositories, the N8N group has the axios dependency: 0.21.1. Found here https://github.com/n8n-io/n8n/blob/master/packages/core/package.json
