### ISSUE TITLE
Chore: Message should be able to support multiple attachments

### ISSUE THREAD

**Issue by sony-mathew** [chatwoot/chatwoot#727]
**Problem Definition**
As it stands today, a message supports only one attachment. And in many places, we assume that a message can have either some content or is just an attachment. The message model is bonded to the attachment model by a `has_one` relationship. Because of this implementation, when we add channels and have incoming channels supporting a message with multiple attachments, we might lose the context in the sense that the content and the attachments were part of one single message rather than a couple of unconnected messages.

**Solution**
To rectify this problem we might have to change the relationship to `has_many` so that the message model can now support multiple attachments. This will be greatly beneficial when we implement the email channels and build integrations to third-party apps like slack.

**Comment by sony-mathew** [comment]
@pranavrajs  @muhzi4u This could potentially affect all the API clients that we have including our mobile apps.

**Comment by muhzi4u** [comment]
Ath onnum oru prashnamey alla ;)
