### ISSUE TITLE
event "conversation_created" will not be fired

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7274]
### Describe the bug

The webhook event "conversation_created" will not be fired

### To Reproduce

I configured the webhook options like this:
<img width="516" alt="Bildschirmfoto 2023-06-08 um 14 15 04" src="https://github.com/chatwoot/chatwoot/assets/17011498/64ee0d5d-16fe-4015-8603-c49cec7b7cd5">

If you now open the website with the chat widget, the event "contact_created" will be fired:

```
+++++++ START WEBHOOK +++++++

Array
(
    [account] => Array
        (
            [id] => 1
            [name] => XXX
        )

    [additional_attributes] => Array
        (
            [created_at_ip] => XXX
        )

    [avatar] => 
    [custom_attributes] => Array
        (
        )

    [email] => 
    [id] => 1537
    [identifier] => 
    [name] => snowy-sun-611
    [phone_number] => 
    [thumbnail] => 
    [event] => contact_created
)


 +++++++ END WEBHOOK +++++++
```

If you click on the chat bubble, the event "webwidget_triggered" will be fired:

```
+++++++ START WEBHOOK +++++++

Array
(
    [id] => 1802
    [contact] => Array
        (
            [account] => Array
                (
                    [id] => 1
                    [name] => XXX
                )

            [additional_attributes] => Array
                (
                    [created_at_ip] => XXX
                )

            [avatar] => 
            [custom_attributes] => Array
                (
                )

            [email] => 
            [id] => 1537
            [identifier] => 
            [name] => snowy-sun-611
            [phone_number] => 
            [thumbnail] => 
        )

    [inbox] => Array
        (
            [id] => 10
            [name] => Beta
        )

    [account] => Array
        (
            [id] => 1
            [name] => XXX
        )

    [current_conversation] => 
    [source_id] => XXX
    [event] => webwidget_triggered
    [event_info] => Array
        (
            [initiated_at] => Array
                (
                    [timestamp] => Thu Jun 08 2023 14:12:59 GMT+0200 (Mitteleuropäische Sommerzeit)
                )

            [referer] => XXX
            [widget_language] => en
            [browser_language] => de
            [browser] => Array
                (
                    [browser_name] => Chrome
                    [browser_version] => 114.0.0.0
                    [device_name] => Unknown
                    [platform_name] => macOS
                    [platform_version] => 10.15.7
                )

        )

)


 +++++++ END WEBHOOK +++++++
```

But If you click now on "Start Conversation", the "conversation_created" will not be fired.

A video of my steps:

https://github.com/chatwoot/chatwoot/assets/17011498/447f2305-8842-4b88-a8c4-e8d33f8b8920

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

macOS 13.4

### Browser and version

Firefox 113.0.1

**Comment by pranavrajs** [comment]
@Ghost108 This is a misunderstanding. The conversation created event will be fired only after a message is sent on the live chat. The "Start Conversation" button navigates you to the page, however it doesn't create the conversation. 

Please send a message and see if you receive the webhook event. 

Closing this here for now as it doesn't seem to be a bug. Feel free to reopen the issue if it is not the case.
