### ISSUE TITLE
database table contacts - many entries

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7276]
### Describe the bug

Every time a new user opens the website with the chat widget, a contact is created in the database in the background.
But if this user will never start a chat, this contact get now values as email, name or something like this. only a placeholder name.

Fact:
My database has many of this unused contacts in database (1420)

<img width="405" alt="Bildschirmfoto 2023-06-08 um 18 41 52" src="https://github.com/chatwoot/chatwoot/assets/17011498/970074a9-5d38-4b5d-945c-de50aed9fbff">

And the web interface shows only the used contacts (where a conversation was started).
This is okay, but should all the unused contacts stored in the database for all the time?

### To Reproduce

...

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@Ghost108 This is correct. These are just the unidentified sessions. The web-ui only shows the contacts that have an email or a phone number or an identifier.
