### ISSUE TITLE
Messages only load after manual refresh after deploying latest-ce chatwoot image

### ISSUE THREAD

**Issue by chinnu0505** [chatwoot/chatwoot#7277]
I'm having the same issue from another supposedly fixed old issue: 

_Manual refresh required to see new messages/updates by @pranavrajs in https://github.com/chatwoot/chatwoot/issues/411#issuecomment-572381611_

I followed the docker deployment instructions here https://www.chatwoot.com/docs/self-hosted/deployment/docker/

I'm able to get chatwoot running on 3000 but after setting up an inbox when I start new chats messages only load after manually refreshing. I am using latest-ce which I believe is the master branch. The old issue reports this is only a problem on development and was fixed but I'm still encountering it. 

Also: not sure if this is related/normal but one of my docker containers 'base-1' which runs for like 2 seconds and quits after outputting 'Switch to inspect mode'
           

Video of the problem:

https://github.com/chatwoot/chatwoot/assets/122245112/c505c7e2-f7eb-423e-8f79-e5fe5487aa90

I have tried with 3 different chatwoot docker tags now, all the same issue. I've used latest-ce, latest, and v2.17.1

**Comment by sojan-official** [comment]
@chinnu0505  could add details on how the issue was fixed if possible ?
