### ISSUE TITLE
Option to inject custom css and js to portal

### ISSUE THREAD

**Issue by marcellov7** [chatwoot/chatwoot#7281]
### Is your feature or enhancement related to a problem? Please describe.

At the moment the style of the portal appears way immature, this does not yet, in my opinion, allow it to be used in production, but only for internal documentation.

### Describe the solution you'd like

It would be enough to be able to set up a custom field to insert custom css and js styles to have the ability to enhance the style of the portal based on one's needs.

**Comment by pranavrajs** [comment]
@marcellov7 At the moment, it is too hard to support this level of customization without changing the code. We will not be supporting these. If there is a change required, you can fork the repository and make the changes.
