### ISSUE TITLE
[CW-2047] Microsoft Email Channel is not getting created.

### ISSUE THREAD

**Issue by shivamkb17** [chatwoot/chatwoot#7284]
### Describe the bug

I am creating an email channel of Microsoft mail. 
I setup a complete azure app registration. (I tested in both single or multi-tenant applications)
I follow the guidelines of the Azure APP setup in chatwoot website. 

I setup the AZURE APP ID and SECRET in the environment file. 
And Ijn email channel it show logo to create Microsoft mail channel. 
On clicking sign-in with Microsoft work, and open the Microsoft consent page. 
After approving the consent form of the app, it predicted back to app website, but no any mail channel is created. 
It simply redirect to chatwoot website URL. 

I am using Contabo VPS. 

### To Reproduce

1. Latest chatwoot version. 
2. Follow the guide to setup AZURE APP.  [link](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup)
3.  get app details and setup in the environment file. 
4.  restart chatwoot, and login to chatwoot app. Create Microsoft email channel. 
5. login with Microsoft credentials in consent screen, 
6. After that It redirect to chatwoot installation website, but no any email is created. 

### Expected behavior

The expected behavior to create mail channel. 

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

ubuntu 20.04 LTS

<sub>[CW-2047](https://linear.app/chatwoot/issue/CW-2047/microsoft-email-channel-is-not-getting-created)</sub>

**Comment by grupale** [comment]
+1 having this issue too

**Comment by tejaswinichile** [comment]
@shivamkb17 Can you make sure you use the same email address you used to create the email channel?
Then verify the token configuration and client secret expiry time.

If you have access to the server please check the server logs if there are any errors then we will know.

**Comment by shivamkb17** [comment]
In multi tenant app, I used another email to create email inbox, in Single tenant app, I used Same Email ID to login into app. 

I am just grabbed the LOGS of the app.

`journalctl -u chatwoot-web.1.service -f`
[logs 1.md](https://github.com/chatwoot/chatwoot/files/11721697/logs.1.md)

`journalctl -u chatwoot-worker.1.service -f`
[Log2.md](https://github.com/chatwoot/chatwoot/files/11721701/Log2.md)

**Comment by MichelN89** [comment]
+1 same issue

**Comment by shivamkb17** [comment]
Is there Anyone is working on this?
As User can't add SMTP credential for Microsoft mail, For this they need to verify through app. 
Fixing this issue is important.

**Comment by tejaswinichile** [comment]
> As User can't add SMTP credential for Microsoft mail, For this they need to verify through app.
Fixing this issue is important.

It's automatically populated with the authentication token and refresh token.


You can either use the single tenant app with the tenant id
- you can not use the normal address for single tenant app; it should be assigned to the verified organization email on outlook - 

or multi-tenant app with Microsoft partner verification with any email address and the same email address.

**Comment by hostworldly** [comment]
> > As User can't add SMTP credential for Microsoft mail, For this they need to verify through app.
> > Fixing this issue is important.
> 
> It's automatically populated with the authentication token and refresh token.
> 
> You can either use the single tenant app with the tenant id
> 
> * you can not use the normal address for single tenant app; it should be assigned to the verified organization email on outlook -
> 
> or multi-tenant app with Microsoft partner verification with any email address and the same email address.

https://github.com/chatwoot/chatwoot/issues/7445
please look into this i tried single tenant app also too and well i have verified partner..

**Comment by hostworldly** [comment]
how long ?

**Comment by shivamkb17** [comment]
This issue is fixed now, and working perfectly.
