### ISSUE TITLE
no data from webhook

### ISSUE THREAD

**Issue by sadden3194** [chatwoot/chatwoot#7289]
### Describe the bug

Hi!

I get no data anymore via webhook.
If open the widget, write a message or something like that, a webhook will be fired to my webhook.php

a litte part of that:

```
$chatData = json_decode(file_get_contents('php://input'), true);
$myfile = fopen("log.txt", "a") or die("Unable to open file!");
fwrite($myfile, "+++++++ START WEBHOOK +++++++\n\n".print_r($chatData, true)."\n\n +++++++ END WEBHOOK +++++++\n\n");
fclose($myfile);
```

chatData = content which I get via webhook.
This works without problems.
but now, I get only an empty content:

this is my log.txt
```
+++++++ START WEBHOOK +++++++



++++++++ END WEBHOOK ++++++++
```

only the comments, which I write with my phpcode, but between this line has to be the webhook content, which is empty.

this is my nginx config:
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    underscores_in_headers on;

    server_name myDomain.de;

    if ( $host !~ "(^myDomain.de$)" ) { return 404; }

    include /usr/syno/etc/www/certificate/ReverseProxy_995f5f9d-dee2-4a9b-b30f-7c09ecc69c71/cert.conf*;

    include /usr/syno/etc/security-profile/tls-profile/config/ReverseProxy_995f5f9d-dee2-4a9b-b30f-7c09ecc69c71.conf*;

    add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload" always;

    proxy_ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

    location / {

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        Upgrade            $http_upgrade;

        proxy_set_header        Connection            upgrade;

        proxy_set_header        Host            $host;

        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_set_header        X-Forwarded-Ssl            on;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_pass http://localhost:8888;

    }

    error_page 403 404 500 502 503 504 /dsm_error_page;

    location /dsm_error_page {
        internal;
        root /usr/syno/share/nginx;
        rewrite (.*) /error.html break;
        allow all;
    }

}
```

I need very quick support, because my bot doesnt work, without webhooks.

### To Reproduce

-

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
Please use a tool like https://webhook.site/#!/c75597ed-4794-4cbe-88ee-38cf5d8345c9 to debug whether the webhooks are successfully fired from chatwoot. 
also check if there are any errors in your sidekiq process

**Comment by nikhilmuz** [comment]
We have the same issue after updating using cwctl

**Comment by nikhilmuz** [comment]
webhooks are not getting fired from chatwoot

**Comment by nikhilmuz** [comment]
For me it seemed to be Redis issue. The Redis version was older. Also one more thing I observed it doesn't work on managed Redis. i.e. GCP Memorystore it uses some calls like `CLIENT` etc which are infrastructure level not data level. I am unsure if we require such call. Or maybe sidekiq using it internally. In such case I think we can't do much.

**Comment by sojan-official** [comment]
@nikhilmuz  you can disable CLIENT calls on GCP memory store by configuring the environment variable `REDIS_DISABLE_CLIENT_COMMAND`

https://github.com/chatwoot/chatwoot/blob/35dfff0a5b5df08ef416fefa0b5fb832ad19fdcf/config/initializers/actioncable.rb#L13
https://github.com/chatwoot/chatwoot/pull/4422
