### ISSUE TITLE
Facebook Messenger callback url error

### ISSUE THREAD

**Issue by maxihoster** [chatwoot/chatwoot#7290]
### Describe the bug

Hello,

I have follow the docs https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup

But impossible to setup the callback url into the facebook apps into the dev console. I have everytime this error:

The callback URL or verify token couldn't be validated. Please verify the provided information or try again later.

On the url I use this value:
https://chat.maxihoster.com/bot

But nothing work!

Whatsapp setup work perfectly! It's only this Facebook Messenger not work!

### To Reproduce

1: Self-Hosted
2: Chatwoot version: 2.17.1 (fresh install)
3: Facebook Apps newly created and API version 17.0

### Expected behavior

Setup the facebook messenger with chatwoot

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu 20.04

### Browser and version

Chrome

### Docker (if applicable)

Linux Ubuntu 20.04 fresh install

**Comment by maxihoster** [comment]
I have the same issue for Instagram! I begin to be crazy!

**Comment by vishnu-narayanan** [comment]
@maxihoster Did you configure the FB_VERIFY_TOKEN env variable and provide the same on facebook developer portal?

ref: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup#configuring-the-environment-variables-in-chatwoot

**Comment by maxihoster** [comment]
I have found the bug!
The bug is into the chatwoot 2.17.1! When we setup the FB_APP_ID, FB_VERIFY_TOKEN, FB_APP_SECRET   into the super-admin console this value are note saved into the conf at this location
/home/chatwoot/chatwoot/.env file
I have added manually here into the correct field and now it work!

**Comment by vishnu-narayanan** [comment]
@maxihoster Values in `.env` always take precedence. Closing this for now.
