### ISSUE TITLE
Free space before question mark

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7295]
### Describe the bug

On the all Confirm deletion windows there is a free space before question mark

### To Reproduce

1. Open the Admin
2. Make sure you have an inbox
3. Remove the inbox

### Expected behavior

There shouldn’t be a free space before question mark

<img width="619" alt="Screenshot 2023-06-12 at 11 02 21" src="https://github.com/chatwoot/chatwoot/assets/104565086/24495f22-ac77-4c01-bd73-11d4626e3a93">

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by Aditay2002** [comment]
@Edik-Apoyan i will like to solve this isssue ,can you please assing it to me?
