### ISSUE TITLE
[CW-2071] Label UX Improvements

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#7299]
### Is your feature or enhancement related to a problem? Please describe.

It would be nice if I could organize the LABEL list alphabetically.

### Describe the solution you'd like

https://discord.com/channels/647412545203994635/650257251856285707/1116089635513311262

### Describe alternatives you've considered

https://media.discordapp.net/attachments/650257251856285707/1116089635274240100/image.png

<sub>[CW-2071](https://linear.app/chatwoot/issue/CW-2071/order-label-list-alphabetic)</sub>

**Comment by scmmishra** [comment]
Would love to have some smart suggestions on this, like Linear does when creating a issue. One of those features that feel magical. Maybe start with synonyms. If someone types "Here's your invoice" in the reply box. We could automatically suggest "billing" label. Probably a big feature and out of scope for this card, but would be great UX.
