### ISSUE TITLE
Fix "method_complexity" issue in app/javascript/src/routes/index.js

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#73]
Function `validateAuthenticateRoutePermission` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/chatwoot/chatwoot/app/javascript/src/routes/index.js#issue_5d87480387cf190001000189

**Comment by fluffynuts** [comment]
I'd like to give this a go (:

**Comment by fluffynuts** [comment]
Ok, I have something that looks right to me -- I don't see Javascript tests in the project (perhaps I'm just missing them?), however I do see rails tests -- do they test the frontend too? I'd really like to confirm that my logic is the same. I don't mind starting on some Javascript tests if that would be acceptable.

**Comment by fluffynuts** [comment]
I've attached a zip file with the spec I wrote to prove the new function works like the old. It would be neat if I could also add tests to your app -- if you open a new issue, I'll set it up to have tests running and get this suite in there too (:

**Comment by pranavrajs** [comment]
@fluffynuts Thanks for the update. I've created an issue for the same. https://github.com/chatwoot/chatwoot/issues/97
