### ISSUE TITLE
Inbound mail webhook URL returning a 422 error 

### ISSUE THREAD

**Issue by Shalashtein** [chatwoot/chatwoot#7302]
### Describe the bug

```
MAILER_SENDER_EMAIL=Hi <hello@xx.co.uk>

SMTP_DOMAIN=xx.co.uk
SMTP_ADDRESS=smtp.postmarkapp.com
SMTP_PORT=587
SMTP_USERNAME=...
SMTP_PASSWORD=...
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_OPENSSL_VERIFY_MODE=peer

MAILER_INBOUND_EMAIL_DOMAIN=xx.co.uk
RAILS_INBOUND_EMAIL_SERVICE=postmark

RAILS_INBOUND_EMAIL_PASSWORD=DummyPassword

# Storage
ACTIVE_STORAGE_SERVICE=amazon
S3_BUCKET_NAME=hybr-chatwoot
AWS_ACCESS_KEY_ID=...
AWS_SECRET_ACCESS_KEY=...'
AWS_REGION=eu-west-2
```

My MX records are setup and pointing to postmark and I'm receiving the emails correctly on Postmark

And in postmark I setup the webhook URL to forward the mail to

`https://actionmailbox:DummyPassword@xx.co.uk/rails/action_mailbox/postmark/inbound_emails`
(This URL was not in the documentation, but I used the sengrid example and replaced sendgrid with postmark this should be documented)

Two issues:
1- The webhook returns an error 422 without further clarification on what's wrong
2- The email generated by chatwoot as the reply-to email `reply+<random_hex>@xx.co.uk` doesn't exist so when I reply to it gmail says the email doesn't exist

### To Reproduce

1- Setup ENVs to use Postmark and mailing server
2- Setup MX records to point to postmark
3- Setup chatwoot postmark webhook inside Postmark
4- Try to reply to an email sent from Chatwoot via Postmark

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

OSX

### Browser and version

Chrome Latest

**Comment by pranavrajs** [comment]
@Shalashtein Can you please share the logs from the service when you hit the URL?

**Comment by Shalashtein** [comment]
I'm getting an empty body in the response, both on Postman and on the Postmark

**Comment by Shalashtein** [comment]
I've solved the issue by ticking the `Send raw JSON body` option, I noticed the sendgrid docs have a similar comment. I can update the docs to add the Postmark setup instructions.

But now that the webhook is working and I can see emails in the chatwoot inbox and I can reply from chatwoot to those emails, I still have the issue that the reply+<random_hex>@.... reply-to address doesn't exist. Can you give me any insight on why that is?

<img width="870" alt="Screenshot 2023-06-15 at 12 43 17 PM" src="https://github.com/chatwoot/chatwoot/assets/22685714/29d8cacc-ae4f-4aed-82c9-7a8f648e15a3">

**Comment by Shalashtein** [comment]
This issue has also been fixed by setting up a subdomain notifications.mydomain.com and adding an MX record for that subdomain to point to Postmark and then postmark forwards that to Chatwoot, cheers
