### ISSUE TITLE
Allow inbox conversation sorting in FIFO ordering

### ISSUE THREAD

**Issue by FabriceCastel** [chatwoot/chatwoot#7305]
### Is your feature or enhancement related to a problem? Please describe.

Conversations in an inbox are shown with the latest at the top (latest based on the last time it was updated). For users that receive a large volume of inbound conversations, it may be preferable to sort this list in FIFO order (ie. the reverse of the current order) to ensure customers that reach out first receive responses first.

### Describe the solution you'd like

A toggle at the top of an inbox to sort conversations in either latest, or oldest ordering.

Something like this, or similar:

<img width="452" alt="Screenshot 2023-06-13 at 1 52 02 PM" src="https://github.com/chatwoot/chatwoot/assets/2886675/99c1eaae-d973-4955-8b6c-51a52ac42fa5">

### Describe alternatives you've considered

As far as I know there is no way to do this in the app currently.

**Comment by pranavrajs** [comment]
@FabriceCastel I believe you are on an older version of Chatwoot. The sort is already available via https://github.com/chatwoot/chatwoot/pull/6853
