### ISSUE TITLE
Import CSV on the contacts page is not working properly

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7307]
### Describe the bug

When I want to import many contacts which are in CSV file, the whole contacts are not importing, and at the same time I receive an email on which are not any information about imported file

### To Reproduce

1. Open the Account
2. Navigate to the contacts page
3. Click on Import button
4. Import CVS file with many contacts

### Expected behavior

Import should work correct, and you should receive an email about imported file where should be right description

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

IOS

**Comment by pranavrajs** [comment]
@Edik-Apoyan You should receive an email with an error message against the rows which broke if the import failed. Let me know if you don't see the emails.
