### ISSUE TITLE
There is no validation in Website Domain field

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7309]
### Describe the bug

There is no validation in Website Domain field

### To Reproduce

1. Open the account
2. Add a new inbox
3. Select website
4. In the Website Domain field put wrong domain

### Expected behavior

There may be a validation

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@Edik-Apoyan This is intentional at the moment, we will revisit this later.
