### ISSUE TITLE
Ter a opção responder  na conversa enviada no whatsapp.

### ISSUE THREAD

**Issue by alexlutke** [chatwoot/chatwoot#7311]
### Is your feature or enhancement related to a problem? Please describe.

Um recurso que faz falta é a opção de clicar nos 3 pontinhos  quando a pessoa envia uma resposta e vc poder responder naquela frase também... 
![WhatsApp Image 2023-06-14 at 11 56 04](https://github.com/chatwoot/chatwoot/assets/136273570/d51e3262-a7f3-4999-9074-e19cc7f7f24e)

### Describe the solution you'd like

ter a opção de responder na resposta enviada.

**Comment by pranavrajs** [comment]
@alexlutke I believe this is a duplicate of https://github.com/chatwoot/chatwoot/issues/6726. Please feel free to re-open if it is not the case.
