### ISSUE TITLE
CSML agent bot conversations do not close on resolving or exiting conversations

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7313]
### Describe the bug

When a conversation with a CSML bot is ongoing (before the handoff),
If the user exits the conversation or the Agent opens then resolves the conversation.
The conversation does not close on the CSML engine.

This can lead to a scenario where new conversations can get assigned to those old CSML ghost conversations.
If the customers use the same browser to start a new conversation, they will get assigned the old CSML ghost conversation.

### To Reproduce

Close via Web widget way:

1. Have CSML all setup
2. Customer starts a conversation. (Conversation is in pending status)
3. Customer exits the conversation using the 'End Conversation' button built into the widget. (Conversation was not closed in CSML engine.)
4. A new or the same customer comes and starts a conversation on the same browser.
5. The new conversation gets treated as the older conversation by the CSML engine.

Close via agent:
All steps same except for step 3:
3. Agent opens and resolves the conversation. (Conversation was not closed in CSML Engine)

### Expected behavior

Agent closing or customer exiting a conversation before a CSML handoff should close that conversation in CSML engine.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Additional context

v2.17.1

**Comment by pranavrajs** [comment]
Closing this as we will be removing the CSML integration in the January release. No new bot can be added, although the existing ones would work.
