### ISSUE TITLE
Only space as a character is allowing in required fields

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7328]
### Describe the bug

When an end user see the required fields, for example, name, ID or Message, he/she can type only space

### To Reproduce

1. Open the Bot
2. Make sure that pre-chat fields are active and required
3. Fill in only space in the required fields

### Expected behavior

It will not allow an user type only space as a character

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@Edik-Apoyan Custom field validations are not supported now. We will reopen this if there is enough interest.
