### ISSUE TITLE
Bug? Access Token returns 502 error

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#7333]
### Describe the bug

When i access/open the Super Admin Console, i can no longer access the "Access Token" and website returns 502. Since i am on cloudflare, it shows a cloudflare error page instead.

![image](https://github.com/chatwoot/chatwoot/assets/25242465/2a79142c-9882-4969-8cb5-5f0e00f36e96)

### To Reproduce

1. Login to admin dashboard
2. Click Access Token

### Expected behavior

Access token shows up to manage it

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 21.04

### Browser and version

MS Edge 114.0.1823.51

### Additional context

CW Version 2.18 (updated just now) on two separate instances.

**Comment by sojan-official** [comment]
@sanjayws  please share the server logs

**Comment by sojan-official** [comment]
@sanjayws  seems like a 200-okay response from Chatwoot. Could you try directly without the cloudflare proxy?

**Comment by sanjayws** [comment]
So i bypassed Cloudflare; here's what i get:

![image](https://github.com/chatwoot/chatwoot/assets/25242465/12a918db-1053-4215-bd16-3b3472500ae2)

**Comment by sojan-official** [comment]
> upstream sent too big header while reading response header from upstream, client: [redacted], server: [redacted], request: "GET /super_admin/access_tokens HTTP/2.0", upstream: "http://127.0.0.1:3000/super_admin/access_tokens", host: "[redacted]", referrer: "https://[redacted]/super_admin"

Should be okay generally. Just keep an eye out on memory/disk usage.

----

closing this since it's more of a nginx config issue
