### ISSUE TITLE
Missing translation in Spanish

### ISSUE THREAD

**Issue by efrancou** [chatwoot/chatwoot#7338]
### Describe the bug

Spanish translation missing.

![image](https://github.com/chatwoot/chatwoot/assets/6466600/be6723c8-ded5-4511-9c25-5301b1ebc87b)

### To Reproduce

Start a chat in Spanish.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Win

### Browser and version

Chrome latest

### Additional context

Hosted on Hetzner

**Comment by vishnu-narayanan** [comment]
@efrancou Could you help us with that? We manage translations via https://chatwoot.crowdin.com

**Comment by vishnu-narayanan** [comment]
Ref: https://www.chatwoot.com/docs/contributing-guide/translation-guidelines

**Comment by efrancou** [comment]
Sure!

**Comment by vishnu-narayanan** [comment]
@efrancou Closing this for now. We routinely pull changes from crowdin and merge them into Chatwoot. New translations will be available in the next monthly release(15th of every month).
