### ISSUE TITLE
Contacts connection

### ISSUE THREAD

**Issue by selanji** [chatwoot/chatwoot#7353]
### Is your feature or enhancement related to a problem? Please describe.

I was trying to import contacts, because we have almost 2000 contacs. Although i was thinkig that when a new customer is registered in the website, we dont have his contact in chatwoot. We're a B2B company. 

### Describe the solution you'd like

I was thinking about a way of connecting our databases. From the Website to chatwoot, straigh. We work in Prestashop. 

### Describe alternatives you've considered

Other alternative i was thinking was using a connector like Make, integromat or something that can work eith webhooks. 

### Additional context

not much for now, just a idea.

**Comment by vishnu-narayanan** [comment]
@selanji You should able to build an integration using the Chatwoot APIs, which will add the contacts to Chatwoot when it is registered in your website.

**Comment by selanji** [comment]
Hello, 

 

Thanks for the answer. Do you have any documentation about this?

 

Kind regards

 



 

SAID JIMENEZ

 ***@***.***> ***@***.***

 

Dietisur
Carretera Cádiz Km 555-9 
Tlf: 955 111 500 

 <http://www.dietisur.es/> www.dietisur.es/

 

De: Vishnu Narayanan ***@***.***> 
Enviado el: miércoles, 21 de junio de 2023 14:38
Para: chatwoot/chatwoot ***@***.***>
CC: selanji ***@***.***>; Mention ***@***.***>
Asunto: Re: [chatwoot/chatwoot] Contacts connection (Issue #7353)

 

@selanji <https://github.com/selanji>  You should able to build an integration using the Chatwoot APIs, which will add the contacts to Chatwoot when it is registered in your website.

**Comment by dandumit** [comment]
I am interested as well. Thank you,
Daniel

**Comment by sojan-official** [comment]
You can either use the contact API: https://www.chatwoot.com/developers/api/#tag/Contacts/operation/contactCreate
or you can export the contacts as a CSV file and import it into Chatwoot

Another option is to include the widget SDK in your website and use `setUser` when user logs in. 
https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup/#set-the-user-in-the-widget
