### ISSUE TITLE
Statuses are not displayed properly

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7368]
### Describe the bug

When the Admin user is online it is showing "We are away at the moment" on the chat page

### To Reproduce

1. Open your Chatwoot account
2. Navigate to the Profile and set status online
3. Open the webpage where has been embedded Chatwoot
4. Start a new conversation

### Expected behavior

Statuses should be displayed properly

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
@Edik-Apoyan do you have business hours configured for the inbox ?

**Comment by Edik-Apoyan** [comment]
no it’s disabled

**Comment by sojan-official** [comment]
@Edik-Apoyan  since you are using app.chatwoot.com , could you raise a Chat ticket via the in product support. We will take a look, at the moment there is no bugs reported around this.

**Comment by Edik-Apoyan** [comment]
@sojan-official can you clarify where may I open the ticket? I didn’t get it, where is product support?
Thanks

**Comment by pranavrajs** [comment]
@Edik-Apoyan Please reach out to us via the live-chat support. We will take a look at the account. Closing this here for now.
