### ISSUE TITLE
Chore: Twitter Profile images are not stored to the inbox

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#737]
Chatwoot usually stores an avatar for each of the inboxes connect, this is missing for the twitter inboxes. 

to get the user avatar we might need to make a separate API call to https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show 

hence the method will have to be added to https://github.com/chatwoot/twitty

**Comment by thundersparkf** [comment]
Hey! Can I try to take this up?

**Comment by pranavrajs** [comment]
@thundersparkf Sure! Do you have enough information on the ticket to start working on this?

**Comment by thundersparkf** [comment]
Yes, first another method(users/show) has to be added to the Twitty repo of chatwoot and then the response of that endpoint has user's "profile_image_url_https" which will be used as an avatar. Right?

**Comment by sojan-official** [comment]
@thundersparkf  I have assigned the issue.  let us know if you need any help while working on this.

**Comment by thundersparkf** [comment]
@sojan-official  Hey! Sorry for delay got caught up elsewhere. Was just trying it out and need a little bit of clarity. I presumed that you mean the customer's profile picture. I've already added the user_show method in twitty but now I'm a bit lost on where im supposed to use it.

**Comment by sojan-official** [comment]
@thundersparkf  no worries. 
if you navigate to the setting -> inboxes. you can see that the inboxes have avatars that were fetched from their original channel. We are looking to have twitter avatars updated here as well. 

let me know if you have any questions.
