### ISSUE TITLE
edit inbox rule in code

### ISSUE THREAD

**Issue by lepokoloko** [chatwoot/chatwoot#7389]
### Is your feature or enhancement related to a problem? Please describe.

Where is the file for editing the front end of the inbox listing

### Describe the solution you'd like

I edited the file app/javascript/dashboard/components/layout/sidebarComponents/Secondary.vue

but the modifications do not take effect, it continues as if nothing happened, even deleting the file and restarting the server. I installed it on linux using the installation script, do I need to run a command to update these modifications?

**Comment by sojan-official** [comment]
Please use Discord for help with custom modifications. 
https://discord.gg/cJXdrwS
