### ISSUE TITLE
[CW-2177] Two 'All' in Automations

### ISSUE THREAD

**Issue by Jatin-MYST** [chatwoot/chatwoot#7391]
### Describe the bug

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/2cf4cf88-7aaf-452c-ac4b-e06396307159/fe0b4102-f794-47d8-92e5-9c14844828c2)

[Source image](https://github.com/chatwoot/chatwoot/assets/72418976/d1de1c46-1a58-4f97-b3f2-e3d7d7ffe756)

### To Reproduce

1. Go to Automation page
2. Click Add automation rule
3. For status condition, there are two 'All'

### Expected behavior

A single 'All'

### Environment

[app.chatwoot.com](http://app.chatwoot.com)

### Cloud Provider

None

### Platform

None

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2177](https://linear.app/chatwoot/issue/CW-2177/two-all-in-automations)</sub>

**Comment by masoud-arabi** [comment]
Hi, Is this issue still open? I am new to open source and I would like to contribute to this issue.

**Comment by pranavrajs** [comment]
@masoud-arabi Please feel free to contribute a fix if you can :)
