### ISSUE TITLE
"Private" or "Restricted" teams

### ISSUE THREAD

**Issue by RubyFreez** [chatwoot/chatwoot#7398]
### Is your feature or enhancement related to a problem? Please describe.

Currently, there is no clear system for handling permissions within a team. All agents have access to conversations in all account teams to which they belong. This can potentially lead to security and privacy issues, especially when certain conversations need to be restricted to only certain agents on a team.

### Describe the solution you'd like

We suggest the conversations that belong to a team marked as "restricted" or "private" would only be available to admins and agents specifically added to that team.

### Additional context

The change we propose will not affect the current teams because the "private" flag that I propose to add will default to "false"

**Comment by RubyFreez** [comment]
Related https://github.com/chatwoot/chatwoot/issues/6422

**Comment by pranavrajs** [comment]
@RubyFreez We are updating the team permissions which should solve the need for private and public teams. Please see the post [here](https://www.chatwoot.com/blog/team-permissions). Closing this here for now. Please feel free to re-open if it doesn't solve this.
