### ISSUE TITLE
Fix "Rubocop/Style/StringLiterals" issue in bin/webpack-dev-server

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#74]
Prefer single-quoted strings when you don't need string interpolation or special symbols.

https://codeclimate.com/github/chatwoot/chatwoot/bin/webpack-dev-server#issue_5d87480d87cf190001000492

**Comment by sdesani** [comment]
@pranavrajs, created PR for same - https://github.com/chatwoot/chatwoot/pull/89
