### ISSUE TITLE
Spelling checker 

### ISSUE THREAD

**Issue by rolymaz** [chatwoot/chatwoot#7401]
### Is your feature or enhancement related to a problem? Please describe.

When our agents compose their messages, they often make spelling mistakes. This creates a poor impression with customers. 

### Describe the solution you'd like

As agents compose their messages, i would like them to be warned if their words are incorrectly spelt. This could achieved by underlining the incorrect word with red, as they type. Clicking on the incorrect word, should provde correct options. This is similiar to how Outlook and MS Word operate. 

### Describe alternatives you've considered

Some examples of implentations: 

https://vuejsexamples.com/a-simple-vuejs-spell-checker-app/

https://www.tiny.cloud/docs/enterprise/check-spelling/

**Comment by pranavrajs** [comment]
@rolymaz This requires an integration with a third party tool. Closing this here for now. We will reopen this if it gains enough interest.
