### ISSUE TITLE
Single Facebook App Multiple Whatsapp Numbers Fails after 4 numbers

### ISSUE THREAD

**Issue by kj2222** [chatwoot/chatwoot#7404]
### Describe the bug

According to https://github.com/chatwoot/chatwoot/issues/4712
having multiple numbers under the same Facebook app is also supported, you can inbox for each number In chatwoot. but need to configure the webhook URL for only one of the inboxes in your Facebook app

We had no trouble adding our first 4 Whatsapp numbers in this manner. All have the same webhook, same Facebook app and same business ID.

But for the 5th number that we added, we are not receiving any messages on Chatwoot. Is there some limit on the number of Whatsapp numbers of a particular Facebook app?

### To Reproduce

1. Create more than 4 Whatsapp inboxes where all of them belong to the same Facebook app and share the same webhook.
2. On the 5th inbox you won't be able to see any conversations. 

### Expected behavior

Expect to receive and view conversations on Chatwoot for any Whatsapp Cloud API number added

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by pranavrajs** [comment]
@kj2222 There is no limitation on the numbers. Is it happening for any number or just a specific number only? This issue has too little information at the moment to start debugging. Please share any relevant logs and your Facebook business settings to help further debug this.

**Comment by kj2222** [comment]
@pranavrajs this happens after adding the 4th inbox. The 4th inbox works fine. But the 5th and onwards don't work. We tried with multiple numbers and we noticed that 5th and 6th inboxes added in this manner don't work.

It's definitely a bug because we resolved it in this manner (even though it doesn't make sense):
For the 5th and 6th inboxes, we deleted the inbox, we added the inbox again but used the temporary access token instead of the permanent system access token. Then we messaged the inbox and received the text successfully.
Then we again deleted the inbox and re-added it back with the permanent access token and now it works fine and messages get received fine.

This applies for any inbox after the 4th inbox.

**Comment by pranavrajs** [comment]
@kj2222 Thanks! However, I still don't think there is enough information for us to debug this issue. Please re-open the issue if you can reproduce this with a different account. Please make sure that this is not a issue related to your number.
