### ISSUE TITLE
Bug: Website SDK not working

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#742]
what i am doing wrong  ???

(function(d,t) {
    var BASE_URL = "http://chatwoot.hmu.gr";
    var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src= BASE_URL + "/packs/js/sdk.js";
    s.parentNode.insertBefore(g,s);
    g.onload=function(){

      window.chatwootSDK.run({
        websiteToken: 'PJLMrAsk9sUQYLm9wVhzPPCg',
        baseUrl: BASE_URL
      });

      setTimeout(
        function() {
          console.log("try user set");
          window.$chatwoot.reset();
          window.$chatwoot.setUser('vfasoulas@hmu.gr', {
              email: 'vfasoulas@hmu.gr',
              name: 'fasoulas vasilis',
              avatar_url: '',
          });
          console.log("user set");
        }, 5000);
    }
  })(document,"script");

but the user identified as **Dawn-Cloud-318** without any more information, see attachment

![image](https://user-images.githubusercontent.com/33730406/79643239-b9cf1080-81aa-11ea-8b4e-48d92bc13a94.png)

**Comment by pranavrajs** [comment]
@vfasoulas Could you please post the console errors if there are any?

**Comment by vfasoulas** [comment]
not any console errors.
But I noticed that if I remove line window.chatwoot$.reset(); works as expected.
Also the problem reapears if I call setUser directly without using setTimeout.

**Comment by pranavrajs** [comment]
```
window.$chatwoot.reset();
```

This should be used only when the user logouts of your web application.

> Also the problem reappears if I call setUser directly without using setTimeout.

This must because the SDK has not loaded yet, we will provide a listener to see if the SDK is ready in the next release.

**Comment by pranavrajs** [comment]
Closing this as a separate ticket would be added for onListener

**Comment by drexlma** [comment]
try this https://github.com/chatwoot/chatwoot/blob/develop/app/views/widget_tests/index.html.erb
