### ISSUE TITLE
Images and formatting in canned responses

### ISSUE THREAD

**Issue by arthurbarret0** [chatwoot/chatwoot#7424]
### Is your feature or enhancement related to a problem? Please describe.

In some cases, it is necessary to provide guidance to the visitor. While I understand that the help center serves this purpose, there are situations where the content is so brief that creating an entire article may not be worthwhile. In such cases, a canned response would suffice, but it still requires an accompanying image to make the guidance clearer.

### Describe the solution you'd like

Adding the option to insert images and formatting into canned responses would be a valuable enhancement. This feature would allow users to enrich their responses visually and structurally, making them more engaging and effective. By incorporating relevant images and utilizing formatting options like bullet points, headings, and bold text, canned responses would become more versatile and provide a better user experience. This addition would provide greater flexibility in conveying information and ensuring that the responses are visually appealing and easy to understand.

**Comment by pranavrajs** [comment]
@arthurbarret0 Thanks for creating the issue. The formatting you mentioned is already supported. For the images, are you talking about inline images? 

<img width="582" alt="Screenshot 2023-08-15 at 1 52 26 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/84e78381-387d-4467-9b5b-042f6c522940">

Alternatively, have you explored the Macros option which would allow you to send a message and an attachment together.

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
