### ISSUE TITLE
Is there any way to trigger a chat programmatically?

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#7429]
### Is your feature or enhancement related to a problem? Please describe.

This is a question to current features (or hacks).

Is there any way to trigger a chat programmatically? Ie if I want to force a chat to be opened at a specific place/time.

### Describe the solution you'd like

It would be ok for me if I can just do som Javascript or similar myself to force a chat - ideally I could do it like if the chat-agent had triggered the chat, but I am interested in any way possible

**Comment by Jatin-MYST** [comment]
@brundles See https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#programatically-open-the-popout-window

**Comment by brundles** [comment]
Thank you @Jatin-MYST 👍
