### ISSUE TITLE
undefined method `locale' for nil:NilClass

### ISSUE THREAD

**Issue by Gabriel-Denys** [chatwoot/chatwoot#7433]
### Describe the bug

If an article doesn't have a category it will throw an internal server error. 

See the error thrown below. It results in the article not being viewable at all. 

```
INFO -- : [80616177-7211-4ebc-94de-08e8b1208da3] Completed 500 Internal Server Error in 8ms (ActiveRecord: 2.5ms | Allocations: 1812
FATAL -- : [80616177-7211-4ebc-94de-08e8b1208da3]
ActionView::Template::Error (undefined method `locale' for nil:NilClass):
   17:     <div>
   18:       <a
   19:         class="text-slate-700 hover:underline leading-8 text-sm font-semibold"
   20:         href="/hc/<%= @portal.slug %>/<%= @article.category.locale %>"
   21:       >
   22:         Home
   23:       </a>
app/views/public/api/v1/portals/articles/show.html.erb:20
app/controllers/public/api/v1/portals/base_controller.rb:35:in `switch_locale_with_article'
app/controllers/public/api/v1/portals/base_controller.rb:8:in `set_locale'
```

### To Reproduce

ChatWoot version: cwctl v2.3.0 alpha build

1. Create a portal in the help centre. 
2. Create an Article inside the portal (without creating or assigning a category)
3. Try to view the article

### Expected behavior

Uncategorized articles should display without errors but instead a 500 fatal error is thrown.

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 20.04.6 LTS

**Comment by karthi07** [comment]
created a temporary UI fix for this issue. the uncategorized article is not handled in other places 

->  `uncategorized `  is not displayed on Portal UI ->  hc/portal/en/categories/

https://github.com/chatwoot/chatwoot/pull/7504

@team please review the PR and let me know if we need to handle the other related cases.
