### ISSUE TITLE
Issue with green badge which shows user status (online) 

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7439]
### Describe the bug

When the user is online the Green badge displays late and sometimes disappears 

### To Reproduce

1. Open the Admin page
2. Open the conversation page
3. Navigate to the website where the user has the inbox
4. Start a new conversation
5. Open that webpage on a new tab and start a new conversation
6. Navigate to the conversation page simultaneously 

### Expected behavior

The green badge should be displayed properly

<img width="403" alt="Screenshot 2023-06-30 at 17 39 43" src="https://github.com/chatwoot/chatwoot/assets/104565086/42578381-0193-42dc-9639-8d031a0633c1">

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

IOS

### Browser and version

Chrome 114

**Comment by Aditay2002** [comment]
@Edik-Apoyan is want to create aPR for this issue .can please assign it to me?

**Comment by Edik-Apoyan** [comment]
@Aditay2002 I think you mentioned me by mistake ))

**Comment by pranavrajs** [comment]
@Edik-Apoyan The presence update can take as long as 90seconds to update. Do you see the user offline after this time period?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
