### ISSUE TITLE
Microsoft mail : Issue with callback redirection after granting permission on Microsoft sign page

### ISSUE THREAD

**Issue by hostworldly** [chatwoot/chatwoot#7445]
### Describe the bug

I have correctly configured the Microsoft mail settings in the .env file of my Chatwoot installation, following the instructions provided in the Chatwoot documentation

https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup

In my .env file, the Microsoft mail configuration is as follows:

The email from which all outgoing emails are sent
You can use either `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
MAILER_SENDER_EMAIL=Chatwoot <support@********>

...

MS OAUTH creds
AZURE_APP_ID=***********
AZURE_APP_SECRET=*************

However, I'm encountering an issue with the callback after granting permission on the Microsoft sign page. The expected behavior is that it should redirect back to the Chatwoot application's home page. But in my case, it takes me to the home page without completing the authentication process.

To provide more context, I have followed all the steps mentioned in the Chatwoot documentation, including the images shared below:

https://prnt.sc/t2GmKgIRql19
https://prnt.sc/msFg_RG8HiOs
https://prnt.sc/MZsw5gIcwOxK
https://prnt.sc/9J36noad9K_0

I have also referred to the (https://www.chatwoot.com/docs/assets/images/ms-oauth-email-config-944168e1a16f474954f37321193e5f73.gif), which demonstrates the callback process.

https://drive.google.com/file/d/1rLISzsVUGd71UVYgwKI82HmODuC_mb5I/view?usp=sharing (
please look the video )

### To Reproduce

Ensure that you have a Chatwoot installation with Microsoft mail integration configured.

Open your application and navigate to the area where the Microsoft mail integration is used (e.g., composing an email, accessing mailbox, etc.).

Perform an action that triggers the authentication flow. 

redirected to the Microsoft sign page for authentication.

On the Microsoft sign page, enter your credentials and proceed.

After entering your credentials, you should see a page asking for permission to access your Microsoft account. Grant the necessary permissions.

Once you have granted permission, observe the behavior after the redirection.

If the issue occurs, you will be redirected to the home page of your Chatwoot application without completing the authentication process.

Note down any error messages, unexpected behaviors, or inconsistencies encountered during this process.

https://drive.google.com/file/d/1rLISzsVUGd71UVYgwKI82HmODuC_mb5I/view?usp=sharing (
please look the video )

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04.6 LTS

### Browser and version

chrome 114.0.5735.198 latest

**Comment by shivamkb17** [comment]
I have the same issue, already created a post, about 33 week ago. 
https://github.com/chatwoot/chatwoot/issues/7284

**Comment by grupale** [comment]
+1 same issue

**Comment by Marlonms** [comment]
+1

**Comment by rolymaz** [comment]
+1

**Comment by rolymaz** [comment]
+1

**Comment by hostworldly** [comment]
I'm waiting

**Comment by hostworldly** [comment]
how long ?

**Comment by pranavrajs** [comment]
@hostworldly Apologies for the delay here. Here are the common issues.

1/ If you have created the Azure app from a different email, then trying to add a different email would not work in Chatwoot. You would have to get the app verified by Microsoft.

2/ Token configuration is invalid (I see the screenshot, so I think we can rule this out).

3/ Domains / redirect URLs are incorrect and are not registered in the application.

If none of these seems to be the issue, please share the server logs, also please share the Chatwoot version you are using.

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
