### ISSUE TITLE
Trigger Agent (or visitor) message programatically?

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#7449]
### Is your feature or enhancement related to a problem? Please describe.

I would like to be able to proactively engage a visitor, programatically.

### Describe the solution you'd like

One relatively simple way to do this, would be if you would open up the campaigns to an API trigger. This way anything could almost be possible, ie. I could trigger Campaign 2234 if the user has done specific things on my site, etc.

Generally I think the campaigns is a good idea, but it needs a little more before it is truely useful.

### Describe alternatives you've considered

Alternatives could be something like opening API for reading/sending messages, which could also solve it.

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/3997
