### ISSUE TITLE
Add RegEx commands to URL's in campaigns

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#7450]
### Is your feature or enhancement related to a problem? Please describe.

As a feature improvement that will solve **a lot** of use cases, while still being relatively quick to implement, I suggest you add Regex option to you current wildcard URL's in campaigns.

### Describe the solution you'd like

Add RegEx option to your existing wildcard URL's (https://www.chatwoot.com/docs/product/features/campaigns/wild-card-url-in-campaigns), so users with more advanced requirements can cook more of their own URLS.

This could as an example also allow us to add a variable to a URL to 'force' a campaign, allow us to popup campaign chat for visitors coming from facebook, google adwords, etc.

**Comment by pranavrajs** [comment]
@brundles Can you please share the cases which cannot be solved using the wildcard URLs?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
