### ISSUE TITLE
Scroll issue on embedded webpage (Mobile)

### ISSUE THREAD

**Issue by Edik-Apoyan** [chatwoot/chatwoot#7452]
### Describe the bug

When the user opens the chat on the embedded webpage, the scroll is displayed. And when on the chat page scrolls up and down under the chat is displayed and worked webpage scroll.

### To Reproduce

1. Open the Admin account
2. Make sure you have a webpage inbox
3. Navigate to the webpage with mobile
4. Open the chat
5. Scroll up and down

### Expected behavior

When the chat is opened, the scroll should work only for opened page

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Mobile

### Operating system

IOS

**Comment by pranavrajs** [comment]
@Edik-Apoyan Can you please share a Loom video of the issue? It is not clear from the description what the issue is. Thanks.

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
