### ISSUE TITLE
Bug active_storage amazon s3

### ISSUE THREAD

**Issue by ycarooliveira** [chatwoot/chatwoot#7453]
### Describe the bug

After upgrading to either 2.17 or 2.18, none of my files are loading up, when I downgrade back to 2.16 it loads again.

I sent this on v2.18
![Captura de Tela 2023-07-03 às 10 58 53](https://github.com/chatwoot/chatwoot/assets/71798108/5b139e2d-7b42-491e-8f57-735cd9ebdfa9)

now when I open the same conversation on v2.16
![Captura de Tela 2023-07-03 às 10 58 30](https://github.com/chatwoot/chatwoot/assets/71798108/1f84346b-ddd6-426d-931e-94cae4305889)

### To Reproduce

1. Ubuntu 20.04
2. ACTIVE_STORAGE_SERVICE='amazon'
3. DIRECT_UPLOADS_ENABLED=false

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu

**Comment by vishnu-narayanan** [comment]
@ycarooliveira This is possibly due to a missing image processing library called `libvips`.  Did you use the latest `cwctl` to upgrade?

You can check your version with
```
cwctl --version
```

**Comment by ycarooliveira** [comment]
I have installed the libvips myself, I dont use _cwctl_ CLI, I always follow the file _setup_20.04.sh_ and this time saw the [topic](https://github.com/orgs/chatwoot/discussions/7113) as well. 

I dont have this problem with only images 

on 2.18
![Captura de Tela 2023-07-04 às 09 53 57](https://github.com/chatwoot/chatwoot/assets/71798108/28d3949a-db1d-4618-ade9-5575009484f0)

on 2.16

![Captura de Tela 2023-07-04 às 09 55 23](https://github.com/chatwoot/chatwoot/assets/71798108/4dcb73e3-e91c-48c9-a65a-19e2b0a719c4)

I was wondering if could be something in the redirect link formation, because the hash generated are different between versions.

**Comment by ycarooliveira** [comment]
@vishnu-narayanan Did you find anything about this?

**Comment by willihangga** [comment]
getting the same issue after upgrading to 3.0, working fine in versin 2.18

```
ACTIVE_STORAGE_SERVICE=s3_compatible
```

**Comment by dnl4** [comment]
> @vishnu-narayanan Did you find anything about this?

I had the same issue. I resolved it by changing the bucket to a region closer to my chatwoot server.

**Comment by darker0n** [comment]
I have the same issue when using external S3 storage. I've already tried a couple of providers. It seems that frontend is trying to get the image before S3 is ready to send it by API. This happens in 20-30% of cases. 
In the browser console, I can see a 404 error. If I refresh the chat page, it will load fine. So, I think the solution is to make frontend try to load images from S3 after getting a 404 error.

<img width="466" alt="Screenshot 2024-09-25 at 2 02 49 PM" src="https://github.com/user-attachments/assets/a6b8d8c3-ca67-4a04-8b07-0d5d119523ff">
<img width="169" alt="Screenshot 2024-09-25 at 2 02 30 PM" src="https://github.com/user-attachments/assets/76868846-bc96-43e8-9361-237dc9962f1f">

**Comment by sojan-official** [comment]
closing this since the original reporter hasn't followed up. if there are other reports lets take it up in new issue
