### ISSUE TITLE
Wrong Translation to Portuguese PT - Mine -> Minerar

### ISSUE THREAD

**Issue by PPaiva** [chatwoot/chatwoot#7454]
### Describe the bug

There is a wrong translation for the word Mine, it's translated to Minerar but it should be Minhas

### To Reproduce

1. All

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

All

**Comment by PPaiva** [comment]
There is a wrong translation for the word Mine, it's translated to Minerar but it should be Minhas

**Comment by PPaiva** [comment]
File app/javascript/dashboard/i18n/locale/pt/chatlist.json should be edited.

**Comment by PPaiva** [comment]
I've download the xliff file, I've made the translations on my PC and then uploaded the, need someone to check Crowdin and confirme that everithing is alltright.

**Comment by PPaiva** [comment]
Portuguese Translation Updated on Crowndin

**Comment by pranavrajs** [comment]
<img width="106" alt="Screenshot 2023-08-17 at 9 34 26 AM" src="https://github.com/chatwoot/chatwoot/assets/2246121/9746c514-dd1e-4f1e-b575-23d418a0f9c5">

@PPaiva Thanks for reporting this. This is fixed in the latest version.
