### ISSUE TITLE
Slovenian language

### ISSUE THREAD

**Issue by thatdudewithfood** [chatwoot/chatwoot#7459]
### Is your feature or enhancement related to a problem? Please describe.

I would like a new language to be added to Crowdin.

### Describe the solution you'd like

Kindly ask you to add the Slovenian language to Crowdin.

**Comment by pranavrajs** [comment]
@thatdudewithfood Thanks for the request. Added the languages here. 

https://chatwoot.crowdin.com/chatwoot/sl
https://chatwoot.crowdin.com/chatwoot-mobile-app/sl
