### ISSUE TITLE
sdk.js TypeError: promise.finally is not a function

### ISSUE THREAD

**Issue by mariusleu** [chatwoot/chatwoot#7461]
### Describe the bug

Got an existing EmberJS app which uses ember-data as well.

After injecting the chatwoot script, the app stops working with the following error being thrown by the ember-data module

```
Uncaught (in promise) TypeError: promise.finally is not a function
```

Looks like the sdk.js provided by chatwoot does some object manipulation that affects the framework.

### To Reproduce

1. Create an ember-data app
2. Add the chatwoot widget script

### Environment

Kubernetes

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@mariusleu There seems to very less information on the issue to take any action. The error doesn't seem to be originating from Chatwoot.

1/ Can you please share the code snippet you are using to add Chatwoot?
2/ Can you specify the version of Chatwoot you are using?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
