### ISSUE TITLE
Limit message storage for each account

### ISSUE THREAD

**Issue by FabioCapobianchi** [chatwoot/chatwoot#7472]
### Is your feature or enhancement related to a problem? Please describe.

In Chatwoot the storage space for conversations is unlimit, so that, we cant choose storage size. That situation will cause space problems.

### Describe the solution you'd like

i want to limit storage space for each account, to prevent storage problems. 

### Describe alternatives you've considered

New feature that works like a Active Directory,  limit storage for each account.

**Comment by pranavrajs** [comment]
@FabioCapobianchi Thanks for creating the issue. Any specific reasons behind this thought? At the moment, we would not be limiting the message storage as we expect our users to preserve their conversation history as long as they need. 

Happy to revisit this if there is a real-world scenario which I'm missing. Thanks.
