### ISSUE TITLE
Assigning a bot to an inbox  - possible to view the conversation between chatbot and user?

### ISSUE THREAD

**Issue by taewookim** [chatwoot/chatwoot#7473]
### Is your feature or enhancement related to a problem? Please describe.

Currently, the conversation between bot and user doesn't show up anywhere until a hand off.
But it's ultra critical to see what the chatbot was saying to the user so the human operator can intervene if necessary (for example, the chatbot is saying wrong things). I modified the code from https://github.com/chatwoot/rasa-agent-bot-demo/ to just "echo" the user - the conversation (to and from chatbot to user) shows up in the website chat widget but does not show up on the conversation dashboard.

Is there a workaround?

### Describe the solution you'd like

In conversations, there should be an conversation between the agent bot and the user

**Comment by PPaiva** [comment]
You can't see it by filtering the state Pending?

**Comment by taewookim** [comment]
ah... didnt realize that it's there. thanks for that.
is there a way to show "Pending" state messages by default? or have the conversation automatically labelled as open?
this way the agent doesn't have to "search" for it
