### ISSUE TITLE
Agent Bot can't assign conversations to Teams

### ISSUE THREAD

**Issue by PPaiva** [chatwoot/chatwoot#7474]
### Describe the bug

Can't use a bot token to Assign Conversation.
API {host}}/{{api_version}}/accounts/{{account_id}}/conversations/{{conversation_id}}/assignments returns  "error": "Access to this endpoint is not authorized for bots"

### To Reproduce

1. Self Hosted

### Expected behavior

No limitations on bot tokens

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

All

**Comment by PPaiva** [comment]
I've edited the app/controllers/concerns/access_token_auth_helper.rb lines from 2 to 5 changed from:

  BOT_ACCESSIBLE_ENDPOINTS = {
    'api/v1/accounts/conversations' => %w[toggle_status create],
    'api/v1/accounts/conversations/messages' => ['create']
  }.freeze

to:
  BOT_ACCESSIBLE_ENDPOINTS = {
    'api/v1/accounts/conversations' => %w[toggle_status create],
    'api/v1/accounts/conversations/messages' => ['create'],
    'api/v1/accounts/conversations/assignments' => %w[set_team create]
  }.freeze

systemctl daemon-reload
systemctl restart chatwoot.target

And then it worked as I expected, now I can Assign Conversation to a team with the bot API token.

**Comment by taewookim** [comment]
same here

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: http://localhost:3000/api/v1/accounts/1/conversations/3/assignments
`

**Comment by giquieu** [comment]
@pranavrajs Hello, I sent a PR with task.

**Comment by nathanmoura** [comment]
Hi there! Is this feature under development? 

My team would highly benefit from it.
