### ISSUE TITLE
[CW-2195] ip_lookup geocoding using maxmind db is not working on docker and linux installations

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#7479]
### Describe the bug

After setting the maxmind api key and enabling `ip_lookup` to true, geocoding is not working.  

### To Reproduce

1. Spin up a new linux/docker installation
2. Configure maxmind API key and enable ip_lookup
3. Start a new conversation
4. Location information is not displayed against the contact

### Expected behavior

Geocoding works seamlessly once keys are configured.

### Environment

Docker

### Cloud Provider

AWS

### Platform

None

### Operating system

Ubuntu 20.04

### Browser and version

n/a

### Docker (if applicable)

n/a

<sub>[CW-2195](https://linear.app/chatwoot/issue/CW-2195/ip-lookup-geocoding-using-maxmind-db-is-not-working-on-docker-and)</sub>

**Comment by hostworldly** [comment]
+1 same issue

**Comment by hostworldly** [comment]
how long ?

**Comment by mredodos** [comment]
if you active ip_lookup you cant login again on caprover docker

**Comment by vishnu-narayanan** [comment]
Fixed by https://github.com/chatwoot/chatwoot/pull/8052

**Comment by Fstream7** [comment]
Fixed in release [v3.15.0](https://github.com/chatwoot/chatwoot/releases/tag/v3.15.0)

**Comment by sojan-official** [comment]
> Fixed in release [v3.15.0](https://github.com/chatwoot/chatwoot/releases/tag/v3.15.0)
