### ISSUE TITLE
I have created Telegram channel but i didnot receive message so where is the problem  

### ISSUE THREAD

**Issue by Haashimi** [chatwoot/chatwoot#7485]
### Describe the bug

I have created Telegram channel but i didnot receive message so where is the problem  
i checked my webhook 

### To Reproduce

I have created Telegram channel but i didnot receive message so where is the problem  
i checked my webhook 

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

linux 

### Browser and version

Chrome is up to date Version 114.0.5735.199 (Official Build) (64-bit)

### Docker (if applicable)

self hosted

**Comment by pranavrajs** [comment]
@Haashimi 

1/ Can you please confirm if you have followed this guide?  https://www.chatwoot.com/docs/product/channels/telegram
2/ Please share the version of Chatwoot you are using.

**Comment by dv336699** [comment]
@pranavrajs just having this save issue, checked a few issues here about webhook not set.

Brand new installation 2.18.0

Webhook is not being set.
![image](https://github.com/chatwoot/chatwoot/assets/930792/5435f7a4-eff8-4458-9463-09198dde84cf)


Using Docker

![image](https://github.com/chatwoot/chatwoot/assets/930792/638a46d8-4a86-4363-a90e-f26fd5392325)
![image](https://github.com/chatwoot/chatwoot/assets/930792/bca22b41-2bc2-458a-a9ec-bd0368ebe1f2)
![image](https://github.com/chatwoot/chatwoot/assets/930792/0b7e4577-fbbe-4644-b610-f87743b6cef7)


I have tried to set the webhook using `https://api.telegram.org/bot{botToken}/setWebhook?url=https://example.domain.com` and it's returning 404.

![image](https://github.com/chatwoot/chatwoot/assets/930792/4a96b288-62c2-46fe-b26c-136e373bd067)


What's the webhook for Telegram?

Thanks

**Comment by dv336699** [comment]
Ok, I manged to fix it by setting the webhook manually.

```
https://api.telegram.org/bot{bot_token}/setWebhook?url=https://{frontend_url}/webhooks/telegram/{bot_token}
```

**Comment by sojan-official** [comment]
for debugging telegram errors on self hosted 

ref: https://www.chatwoot.com/docs/contributing-guide/telegram-channel-setup

**Comment by dv336699** [comment]
tjamls @sojan-official and @pranavrajs I think it might have been an issue with URL, but now that's all working, I think this can be closed.

Thanks

**Comment by Haashimi** [comment]
@pranavrajs i followed this guide? https://www.chatwoot.com/docs/product/channels/telegram 

the problem was telegram only supportes these Ports  for webhooks: 443, 80, 88, 8443. then i set one of them
