### ISSUE TITLE
support for .webp image format in attachment

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#7487]
### Is your feature or enhancement related to a problem? Please describe.

Already visitors attache big size images ( screenshots ) as attachment and this will fat chatwoot day by day. 

### Describe the solution you'd like

If Chatwoot convert and keep attachments as .webp on fly , Size on disk and database will be reduce by %80
Also an option in setting automatically keep or delete the original screenshot will be good future.

**Comment by pranavrajs** [comment]
@mmojadad IMO this is not a major concern as we limit the size of the attachments people can add. This could be picked up as an enhancement later. Closing this for now as it wouldn't be picked on priority soon.
