### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#7488]
### Is your feature or enhancement related to a problem? Please describe.

Agents need to have Chatwoot on mobiles with push notification support

### Describe the solution you'd like

Add PWA support in Chatwoot plus Web Push by VAPID can be all in one solution for Chatwoot agents mobilability.

**Comment by pranavrajs** [comment]
@mmojadad This is already supported. You can use "Add to Home screen" option on the device. This would work for the push as well. We expect people to use mobile app mainly as it is much more performant that PWA.
