### ISSUE TITLE
Agent limity by device

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#7489]
### Describe the bug

Already chatwoot not notice or limit if an agent login via several devices at once with same credentials .Must be a mechanismto for limitation agent per device. 

### To Reproduce

No error

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@mmojadad The limit is already present. You would be logged out of the devices based on the activity when you have quite a lot of active sessions.
