### ISSUE TITLE
Ability to support multiple organizations (not teams)

### ISSUE THREAD

**Issue by taewookim** [chatwoot/chatwoot#7490]
### Is your feature or enhancement related to a problem? Please describe.

If I wanted to support 2 orgs (that have nothing to do with each other) on same install but ensure that they do not share data whatsoever, what would be the easiest way to accomplish this other than installing chatwoot on different servers? 

in other self hosted software, simply changing the database based on server name would achieve this but chatwoot has other dependencies (like redis).

### Describe the solution you'd like

As admin, have ability to create multiple brands / organizations

### Describe alternatives you've considered

multiple installations of chatwoot, which is significantly more ineffcient

**Comment by sojan-official** [comment]
@taewookim Chatwoot installations support multitenancy; you can have multiple accounts added from super admin. Each organization can have dedicated accounts, and the data will be isolated within that account.
