### ISSUE TITLE
Can't send an email with exterior smtp server

### ISSUE THREAD

**Issue by aermike** [chatwoot/chatwoot#751]
**Describe the bug**
Started POST "/auth/password" for 10.0.x.y. at 2020-04-22 10:33:51 +0300
Cannot render console from 10.0.x.y! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by DeviseOverrides::PasswordsController#create as HTML
  Parameters: {"email"=>"admin@domain", "password"=>{"email"=>"admin@domain"}}
Can't verify CSRF token authenticity.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aermike** [comment]
add in .env file parameter 
SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
openssl_verify_mode=NONE

but get this error
Error performing ActionMailer::MailDeliveryJob (Job ID: 9e5f98fc-01cd-49a3-9a47-4c6b6441d1c8) from Sidekiq(mailers) in 129.49ms: OpenSSL::SSL::SSLError (hostname "domain" does not match the server certificate):

**Comment by pranavrajs** [comment]
@aermike We will investigate if something is missing in SMTP authentication, the config we have right should work with most of the providers.

**Comment by aermike** [comment]
Thank you

**Comment by sojan-official** [comment]
@aermike  while noticing the params just spotted that `Parameters: {"email"=>"admin@domain"}`

`admin@domain` doesn't seem like a valid email. could you double-check?

**Comment by aermike** [comment]
Hi 
admin@domain was an example
domain =3clicks.ro
so mail is
admin@3clicks.ro

**Comment by sojan-official** [comment]
ref:
 
https://github.com/mikel/mail/issues/550 

https://stackoverflow.com/questions/27795484/sslerror-hostname-w-x-y-z-does-not-match-the-server-certificate

https://serverfault.com/questions/908410/opensslsslsslerror-hostname-smtp-gmail-com-does-not-match-the-server-cert

**Comment by aermike** [comment]
It wotks after modify .env with 
openssl_verify_mode=NONE
