### ISSUE TITLE
Whatsapp template with multimedia content not showing in chatwoot

### ISSUE THREAD

**Issue by MaoBueno** [chatwoot/chatwoot#7517]
### Describe the bug

Approved templates with multimedia content (image or video in the header) are not displayed in chatwoot, only those with only text appear

### To Reproduce

Environment: CapRover
Version: 2.18.0

Approved template
![error template](https://github.com/chatwoot/chatwoot/assets/50222850/fe49514e-c6ea-442f-ba15-07d6655a8b16)

It does not appear in chatwoot
![error template2](https://github.com/chatwoot/chatwoot/assets/50222850/8520d7a5-9795-4347-89fa-5e3530af6458)

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@MaoBueno Thanks for creating the issue. This is not supported at the moment. We will revisit this whenever we add campaigns feature.
