### ISSUE TITLE
Chatwoot Upgradation 

### ISSUE THREAD

**Issue by khushalalnafi21040** [chatwoot/chatwoot#7531]
### Is your feature or enhancement related to a problem? Please describe.

We have a chatwoot application and need to upgrade this application to new features. Need a skilled person with Roby on Rails work experience. 

### Describe the solution you'd like

I need to add following features on the Chatwoot:

1.      Add contact numbers of new leads.

2.      Create customized messages.

3.      Send bulk messages to all leads.

4.      Separate inboxes for marketing team (if possible)

5.      We can respond to leads via chatwoot as well as mobile phone

6.      Integration of chatwoot WhatsApp messages log with CRM so sales team can find the update in the CRM.

7.      Option to create groups (Pakistan, India, Bangladesh, UAE, Ghana etc. )

8.      SMS service

(This required for WhatsApp, telegram, wechat, SMS, Facebook messenger )

**Comment by sojan-official** [comment]
@khushalalnafi21040, please look into the discord forums if you are looking for Chatwoot developers
In case of any feature requests, please raise individual issues for each.

**Comment by Khushaldas21040** [comment]
> 

@sojan-official can please guide me where can I update this.
