### ISSUE TITLE
docker-compose run --rm rails bundle exec rails db:reset

### ISSUE THREAD

**Issue by KasunAssetDidital** [chatwoot/chatwoot#755]
**Describe the bug**
After run "docker-compose build" or "docker-compose up" or "docker-compose down" i'm having following error
_________________________________________________________________________________________________________
Removing chatwoot_webpack_1
ERROR: container b7e98b6bb6f5d61de8978cc2df64a94884466b9f80e42195877fd3d64c94dabd: driver "overlay2" failed to remove root filesystem: unlinkat /var/lib/docker/overlay2/a3ef3aad0c5fade9f811304ae56f5c0c1496ccfaf482125b9b5e8aa16adedfbb/merged: device or resource busy
_________________________________________________________________________________________________________

How do i fix this issue? Why i'm getting that?

Thank You

**Comment by pranavrajs** [comment]
@vishnu-narayanan / @sojan-official Could you please look into this?

**Comment by KasunAssetDidital** [comment]
![bandicam 2020-04-23 12-37-58-694](https://user-images.githubusercontent.com/64188066/80069670-5c96de80-855f-11ea-8e0f-cde03b51b82b.jpg)

**Comment by KasunAssetDidital** [comment]
i think this
![bandicam 2020-04-23 14-05-35-456](https://user-images.githubusercontent.com/64188066/80077778-97067880-856b-11ea-848b-50a06c6099ac.jpg)
 will be the cause for the issue

**Comment by vishnu-narayanan** [comment]
@KasunAssetDidital Hello, Could you share the output of `docker version`, `docker-compose version` and `docker info` ?

**Comment by KasunAssetDidital** [comment]
Docker version 19.03.8, build afacb8b
docker-compose version 1.25.5, build 8a1c60f6

here is my docker and compose versions

**Comment by KasunAssetDidital** [comment]
**Docker Info**
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 27
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.18.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.551GiB
 Name: whuk-53665.whukhost.com
 ID: 4ISQ:IX6J:G4QG:S24W:QG2I:RK6A:FLYZ:5GJV:EAQL:OBIJ:MXP7:WMLQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by vishnu-narayanan** [comment]
@KasunAssetDidital This might have to do with your kernel version and is a known issue. 

The docker-compose is not able to bring the container down the filesystem have leaked.

You should be able to fix this in two ways:
1. Find the processes that owns the filesystem and kill that process.
2. or restart the docker daemon if you can afford it. (`sudo service docker restart`)

Ref: https://github.com/moby/moby/issues/22260

**Comment by KasunAssetDidital** [comment]
Thank you for helping me,Some how it works,but not completely removed running containers,following are remain as it is.

 

- chatwoot_redis_1

- chatwoot_postgres_1

After i execute "**docker-compose run --rm rails bundle exec rails db:reset**" i still get following error

Creating network "chatwoot_default" with the default driver
Starting chatwoot_postgres_1 ... error
Starting chatwoot_redis_1    ... error

ERROR: for chatwoot_postgres_1  Cannot start service postgres: container is marked for removal and cannot be started
ERROR: for postgres  Cannot start service postgres: container is marked for removal and cannot be started

ERROR: for redis  Cannot start service redis: container is marked for removal and cannot be started
ERROR: Encountered errors while bringing up the project.


how ever i manage to remove that containers by using following commands

01.sudo service docker stop
02.sudo rm -rf /var/lib/docker/containers/ContainerId + TAB
03.sudo service docker start
