### ISSUE TITLE
Configure SMTP for Microsoft Inbox channel

### ISSUE THREAD

**Issue by guiqis** [chatwoot/chatwoot#7556]
### Describe the bug

I've successfully connected my Microsoft account using this guide:
https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/

But it only setup the IMAP settings. When I try to add SMTP it keeps saying "It was not possible to save SMTP settings". Where can I find a guide with the correct SMTP settings that I should add to the inbox channel?

### To Reproduce

1. Inboxes
2. Settings
3. Settings
4. Enable STMP
5. Add settings
6. Save

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by pranavrajs** [comment]
@guiqis If you setup the Azure app properly, you would see an option for Microsoft provider as shown [here](https://www.chatwoot.com/docs/product/channels/email/microsoft/create-channel/). The basic auth SMTP / IMAP wouldn't work for Microsoft.
