### ISSUE TITLE
ENV Force https Not Working(Request block by browser)

### ISSUE THREAD

**Issue by KasunAssetDidital** [chatwoot/chatwoot#756]
**Describe the bug**
I change my .env to send request through https but its not working
![bandicam 2020-04-23 15-00-23-050](https://user-images.githubusercontent.com/64188066/80085838-6e37b080-8576-11ea-947d-3edddbcdb6b2.jpg)

**Comment by KasunAssetDidital** [comment]
![https error](https://user-images.githubusercontent.com/64188066/80085880-81e31700-8576-11ea-9dc6-0594756a28a4.jpg)

**Comment by sojan-official** [comment]
@KasunAssetDidital  could you check the value for the `FRONTEND_URL` and ensure that is set with `https://` as well ?

**Comment by KasunAssetDidital** [comment]
Hi Sojan,

I also tried that way but didn't work for me,Is that required to install SSL Certificate on this app,If so tell me how to do that?

**Comment by sojan-official** [comment]
@KasunAssetDidital  depends on your set up. One of the solutions is having a ngnix web server handling the incoming traffic and routing the traffic to the port 3000 at which chatwoot runs.  

You can have the SSL certificate installed at the Nginx side.

**Comment by aermike** [comment]
And another solution?

**Comment by KasunAssetDidital** [comment]
@sojan-official I'm working on I'll let you know if I make any progress

**Comment by sojan-official** [comment]
@KasunAssetDidital  we no have chatwoot available as a one-click installation on caprover. you can explore that as well. https://caprover.com/docs/get-started.html  

this automates everything for you, the Nginx part and event the cert management using letsencrypt.

**Comment by pranavrajs** [comment]
@sojan-official @KasunAssetDidital Is there any additional info/action required here, otherwise please close this ticket.

**Comment by sojan-official** [comment]
let's reopen this if the issue persists.

**Comment by yani94** [comment]
I have tried set both the followings env to 
`FRONTEND_URL=https://mydomain.com`
`FORCE_SSL=true` 

but it redirects the images attachment to https://127.0.0.1:3000 instead and not my domain.

**Comment by sojan-official** [comment]
@yani94  could you reopen this as a separate issue?  
also, did you restart the server after setting the environment variables ?

**Comment by yani94** [comment]
@sojan-official okay I will create a separate issue and I restart the server after change the settings
