### ISSUE TITLE
Support ARM architecture 

### ISSUE THREAD

**Issue by hexclann** [chatwoot/chatwoot#7565]
### Is your feature or enhancement related to a problem? Please describe.

The current public container images for chatwoot do not work on ARM64 servers.

### Describe the solution you'd like

Provide multi-architecture images so that chatwoot can be run on ARM64 servers.

**Comment by Startouf** [comment]
Duplicate of https://github.com/chatwoot/chatwoot/issues/7470

**Comment by pranavrajs** [comment]
Closing this as the issue is a duplicate.
