### ISSUE TITLE
[CW-2260] Unavailable message for visitors - no client validation

### ISSUE THREAD

**Issue by LiamAshdown** [chatwoot/chatwoot#7573]
### Describe the bug

There's no client validation, screenshot below:
<img width="1623" alt="Screenshot 2023-07-21 at 09 03 18" src="https://github.com/chatwoot/chatwoot/assets/43280985/45fc7700-5273-49cc-86cc-266502e3ee68">

As you can see there's a backend validation error:
`{
    "message": "Out of office message is too long (maximum is 255 characters)",
    "attributes": [
        "out_of_office_message"
    ]
}`

### To Reproduce

1. Enable `Enable business availability for this inbox`
2. Write more than 255 characters for the field `Unavailable message for visitors`
3. You will notice on the client side the alert box will say `Inbox settings updated successfully` but on the ajax request server responds with a 422 with a validation error.

### Expected behavior

I am expecting client side validation on the text area field, and the alert box should not be saying `Inbox settings updated successfully` if the server did not respond with a 200.

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Latest

<sub>[CW-2260](https://linear.app/chatwoot/issue/CW-2260/unavailable-message-for-visitors-no-client-validation)</sub>

**Comment by sojan-official** [comment]
@LiamAshdown  Thanks for the report, we will get this fixed

**Comment by LiamAshdown** [comment]
Thank you @sojan-official.

I would like to start contributing to this project. Would it be okay if I have ago at this issue? (No problem if it's not!)

**Comment by pranavrajs** [comment]
@LiamAshdown Sure. Please go ahead. I would suggest increasing the limits to 10k rather than keeping it at 255.

**Comment by LiamAshdown** [comment]
@pranavrajs Thank you. I've created a pull request #7583
