### ISSUE TITLE
Mail Configuration Not Working(Agent Verification Pending)

### ISSUE THREAD

**Issue by KasunAssetDidital** [chatwoot/chatwoot#758]
**Describe the bug**
Even I Configured .env file mails not working,
01.How do i get agent verification email?
02.Can i verify agent manually inside chatwoot dashboard?  

this is my .env Configuration
![bandicam 2020-04-24 12-37-45-033](https://user-images.githubusercontent.com/64188066/80184919-18701080-8629-11ea-967b-cf7adeb0c650.jpg)

**Comment by pranavrajs** [comment]
> 01.How do i get agent verification email?

You have to configure the variables required, I think you have configured everything. Could you please see if there is any error in the console.

> 02.Can i verify agent manually inside chatwoot dashboard?

Please see if this helps.
https://github.com/chatwoot/chatwoot/issues/638#issuecomment-605420967

**Comment by KasunAssetDidital** [comment]
@pranavrajs  how do i execute this `u = User.find_by(email: 'youremailaddress')` command on my CLI
actually i really new to this rails,Could u tell me

I tried this `docker-compose run rails -it chatwoot bin/rails c u = User.find_by(email: 'myemail@email.com')`

but didn't work

**Comment by KasunAssetDidital** [comment]
Hi @pranavrajs 
 I'm using Dedicated Server to run this application on linux ,rails with docker
 could u help me to configure mail server or verify agent manually  if it possible

**Comment by sojan-official** [comment]
@KasunAssetDidital  You will have to connect to the Docker container that is running rails first.  
the following command on a machine will give you the container id
```
docker ps
```
using the id obtained  run
```
# replace <id>
docker exec -it <id> /bin/sh
```
start rails console by typing the following in the shell
```
bundle exec rails c
```
Now you can try the user.find command inside the console. 

Let us know if you need more help.

**Comment by aermike** [comment]
Hi
I have same problem with manual install  #751
Resolved with help of @sojan-official (Thanks)
ref:

mikel/mail#550

https://stackoverflow.com/questions/27795484/sslerror-hostname-w-x-y-z-does-not-match-the-server-certificate

https://serverfault.com/questions/908410/opensslsslsslerror-hostname-smtp-gmail-com-does-not-match-the-server-cert
Conrect: 
put in .env at mail setup last line
openssl_verify_mode=NONE

**Comment by KasunAssetDidital** [comment]
Hi @sojan-official  
It worked. thank you soo much. Could You help me to configure the mail server if you can? I think that would be the best way to work with "chatwoot".

**Comment by KasunAssetDidital** [comment]
Hi @sojan-official it worked for me. Thank you soo much and @aermike thank you too for trying to help me. I really appreciate it.
