### ISSUE TITLE
CSAT message is not changed after recompiling chatwoot

### ISSUE THREAD

**Issue by flavioxx** [chatwoot/chatwoot#7597]
### Describe the bug

Hello
I want to modify the CSAT message and when I recompile chatwoot the modification is not applied.

remains the same as it comes by default in chatwoot

### To Reproduce

edit ../chatwoot\chatwoot\config\locales\pt_BR.yml

comands for recompile:
sudo -i -u chatwoot
cd chatwoot
rake assets:precompile RAILS_ENV=production
exit
systemctl daemon-reload && systemctl restart chatwoot.target

### Expected behavior

I expected the CSAT message to change.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

**Comment by MatijaTerzic** [comment]
rake assets:clean assets:clobber assets:precompile RAILS_ENV=production
