### ISSUE TITLE
Remove deprecated scope from Facebook channel flow

### ISSUE THREAD

**Issue by andreipopovici** [chatwoot/chatwoot#760]
https://github.com/chatwoot/chatwoot/blob/5736f687e8bbbe9e4b61a256ad5bc90248dcbb79/app/javascript/dashboard/routes/dashboard/settings/inbox/channels/Facebook.vue#L199

See:

![Screen Shot 2020-04-24 at 12 24 23](https://user-images.githubusercontent.com/1143417/80196920-a5659a80-8626-11ea-820e-34bf71ff6d99.png)

**Comment by andreipopovici** [comment]
Guess deadline would be June 30, 2020 🤷‍♂️

**Comment by pranavrajs** [comment]
@andreipopovici Thanks for the issue and PR. FB was developed long back, it might have some unused scope, thanks for the cleanup.
