### ISSUE TITLE
Website Avatar Update

### ISSUE THREAD

**Issue by movilreup** [chatwoot/chatwoot#7602]
### Describe the bug

Hello Support 

It can be corrected that the Channel Avatar is not automatically configured with the Website Avatar of the widget, because if one wants to use a different avatar in the website chat that is not the same to identify the channel, it is not possible since both are changed automatically.

both can be configured to be individual

### To Reproduce

ready explay above

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@movilreup At the moment, we don't support this. The avatar is only used in the inboxes section and is not shown anywhere else in the dashboard UI. Happy to reopen if there is a strong request from the community around this.
