### ISSUE TITLE
previous conversations anda telegram 

### ISSUE THREAD

**Issue by dennispesce** [chatwoot/chatwoot#7610]
### Describe the bug

Issue reported: Unable to view previous conversations on Chatwoot platform when integrated with Telegram inputs.

### To Reproduce

Unable to view previous conversations on Chatwoot platform when integrated with Telegram inputs.

### Environment

app.chatwoot.com

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by pranavrajs** [comment]
@dennispesce Thanks for creating the issue. We don't fetch the conversation history before Chatwoot is integrated with Telegram. You can receive only the new messages in the channel.
