### ISSUE TITLE
Email inbox reply not send Net::ReadTimeout

### ISSUE THREAD

**Issue by guiqis** [chatwoot/chatwoot#7611]
### Describe the bug

Instead of using SMTP to deliver emails (since I can't setup Microsoft SMTP) I've added SendGrid info to my .env file.

Reset password emails are being sent, but email inbox emails are not being delivered. Inside chatwoot it says sent successfully, but I see the task killed inside Sidekiq with error: Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>

What does it mean and how can I solve it?

### To Reproduce

1. Reply to any conversation

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

None

**Comment by pranavrajs** [comment]
@guiqis Thanks for reporting the issue. 

1/ Can you please share the full error logs? 
2/ ReadTimeout usually means that the port/credentials are invalid. I see that you are using Sendgrid. Based on my limited knowledge, I don't think they have proper IMAP implementation? Their implementation is based on inbound parse webhooks. For that you have to setup conversation continuity as described [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity).

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.
