### ISSUE TITLE
Profile settings context menu z index issue

### ISSUE THREAD

**Issue by LiamAshdown** [chatwoot/chatwoot#7613]
### Describe the bug

<img width="564" alt="Screenshot 2023-07-25 at 23 17 14" src="https://github.com/chatwoot/chatwoot/assets/43280985/2ae458b1-e2ce-496a-817b-626e6ff108ae">

As the screen above, you can see the 'Reply' and 'Private Note' button is above the context menu.

This is because the context menu and the buttons have the same z-10 index.

### To Reproduce

1. Go into tablet view
2. Open profile context menu
3. Notice how the 'Reply' and 'Private Note' is appearing above the context menu

### Environment

Other [please specify in the description]

### Cloud Provider

None

### Platform

Mobile

### Browser and version

Chrome Version 114.0.5735.106 (Official Build) (arm64)

**Comment by pranavrajs** [comment]
Nice catch.
