### ISSUE TITLE
Incoming whatsapp messages are not displayed

### ISSUE THREAD

**Issue by mane06** [chatwoot/chatwoot#7624]
### Describe the bug

When a Whatsapp message is received and in the logs it is shown correctly, but said message is not shown in the channel/web interface, it is worth mentioning that the chatwoot instance was installed with docker compose, the other channels work perfectly, it just happens With whats app, I can also tell that this happens with a manual installation using the install.sh script. I don't know if it is a problem with version 2.18.0, I clarify that it is using twilio in version 2.17.0 this configuration worked perfectly

This is an extract of the logs where the WhatsApp message is received correctly:

```
haphat-rails-1     | I, [2023-07-27T00:35:07.225132 #1]  INFO -- : [62c768c9-c051-41de-8707-b97e97b5a132]   Parameters: {"SmsMessageSid"=>"SM9af4c332c7e80b55b5954da3534d1f5b", "NumMedia"=>"0", "ProfileName"=>"iDesiIng", "SmsSid"=>"SM9af4c332c7e80b55b5954da3534d1f5b", "WaId"=>"5214436835797", "SmsStatus"=>"received", "Body"=>"test message", "To"=>"whatsapp:+5214432647547", "NumSegments"=>"1", "ReferralNumMedia"=>"0", "MessageSid"=>"SM9af4c332c7e80b55b5954da3534d1f5b", "AccountSid"=>"xxxxxxxxxxx", "From"=>"whatsapp:+5214436835797", "ApiVersion"=>"2010-04-01"}
```

### To Reproduce

.

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu 22.04

### Browser and version

Chrome

### Docker (if applicable)

`Docker version 24.0.5, build ced0996`

`Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-78-generic
 Operating System: Ubuntu 22.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 11.64GiB
 Name: localhost
 ID: 9902edfa-c134-485e-9ad0-30159e8e4db5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false`

`Docker Compose version v2.20.2`

**Comment by pranavrajs** [comment]
@mane06 Sorry about the delay in response. Was this resolved? I don't think there is enough to debug here. Can you please try it out on our Cloud version and see if it helps?

**Comment by pranavrajs** [comment]
Closing the issue here due to inactivity. Please feel free to reopen it if it is still an issue.

**Comment by eduardosantanna** [comment]
@pranavrajs Do you have any idea why this happens? Could it be some blockage on the part of Meta or some internal chatwoot bug with the use of test numbers?

![image](https://github.com/chatwoot/chatwoot/assets/93081796/6449a639-614d-4495-93ca-f00fd17eb996)

I can receive messages normally on chatwoot, but I cannot send any messages via chatwoot. This occurs using the WhatsApp Cloud API test number.
