### ISSUE TITLE
[CW-2298] Error when recompiling Chatwoot for v3 version node 18

### ISSUE THREAD

**Issue by jtayrone** [chatwoot/chatwoot#7626]
### Describe the bug

When trying to recompile Chatwoot for version v3, I get the following error:

```
Compiling...
Compilation failed:
node:internal/crypto/hash:69
   this[kHandle] = new _Hash(algorithm, xofLen);
                   ^

Error: error:0308010C:digital envelope routines::unsupported
     at new Hash (node:internal/crypto/hash:69:19)
     at Object.createHash (node:crypto:133:10)
     at module.exports (/home/chatroot/chatroot/node_modules/webpack/lib/util/createHash.js:135:53)
     at NormalModule._initBuildHash (/home/chatwoot/chatwoot/node_modules/webpack/lib/NormalModule.js:417:16)
     at /home/chatroot/chatroot/node_modules/webpack/lib/NormalModule.js:452:10
     at /home/chatroot/chatroot/node_modules/webpack/lib/NormalModule.js:323:13
     at /home/chatroot/chatroot/node_modules/loader-runner/lib/LoaderRunner.js:367:11
     at /home/chatroot/chatroot/node_modules/loader-runner/lib/LoaderRunner.js:233:18
     at context.callback (/home/chatroot/chatroot/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
     at /home/chatroot/chatroot/node_modules/babel-loader/lib/index.js:59:103 {
   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
   library: 'digital envelope routines',
   reason: 'unsupported',
   code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

My current setup uses Node version 18, because n8n requires that version, I have integration with an API that needs n8n, so I'm using version 18 of Node.

### To Reproduce

Follow the manual update process:

```
sudo -i -u chatwoot
cd chatwoot
git checkout develop && git pull
bundle
yarn
rake assets:precompile RAILS_ENV=production
```

### Expected behavior

*No response*

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2298](https://linear.app/chatwoot/issue/CW-2298/error-when-recompiling-chatwoot-for-v3-version-node-18)</sub>

**Comment by nithindavid** [comment]
@jtayrone Could you try again with node version `16.17.0`?

**Comment by pranavrajs** [comment]
[https://github.com/webpack/webpack/issues/14532](https://github.com/webpack/webpack/issues/14532)

**Comment by pranavrajs** [comment]
@pranavrajs Add the findings we had during the Webpacker to Vite migration.

**Comment by pranavrajs** [comment]
@scmmishra If the less secure path to migrate to latest node version works, we can explore that too.

**Comment by LiamAshdown** [comment]
@pranavrajs Another way we could combat this is to add a flag in the `webpack` and `webpack-dev-server`.

`ENV['NODE_OPTIONS'] = '--openssl-legacy-provider'`

**Comment by pranavrajs** [comment]
Sure, let us go ahead. Would you be able to send a PR for the same?

**Comment by scmmishra** [comment]
Sure

**Comment by sojan-official** [comment]
Closing this since  `--openssl-legacy-provider` merged
