### ISSUE TITLE
Agent online/offline

### ISSUE THREAD

**Issue by tabrza** [chatwoot/chatwoot#763]
**Is your enhancement request related to a problem? Please describe.**
If agent online send a pre-defined response, otherwise send another type of response

**Describe the solution you'd like**
If agent is online, let user the know that agent x would be with them shortly.
If agent is offline, let user know that there are no agents currently online and collect user data.

When bot sends a message, show 'typing' to delay response 

**An enhancement to the above when agents are online could be**
Additionally, could state agents are currently busy and will be with you in 'x' minutes..

**Comment by sojan-official** [comment]
ref : #718

**Comment by pranavrajs** [comment]
@tabrza We are working on to improve this flow, typing indicator would be added soon.

**Comment by tabrza** [comment]
cool!

**Comment by tabrza** [comment]
If you could point me to certain files I can see about experimenting with this feature?
