### ISSUE TITLE
Unable to change brand variables from superadmin dashboard

### ISSUE THREAD

**Issue by gavisharora** [chatwoot/chatwoot#7650]
### Describe the bug

I have deployed the chatwoot community edition using the one-click deploy button on Heroku. 

I would like to change the BRAND_NAME and BRAND_URL variables to my own values instead, I believe these are the same ones that appear on the widget. 

When I try to create a BRAND_NAME variable from the Installation Config panel inside the superadmin dashboard, it gives me a 500 error

<img width="1440" alt="Screenshot 2023-08-01 at 5 52 11 AM" src="https://github.com/chatwoot/chatwoot/assets/11664830/17172606-4365-4fbc-9388-f77590314770">

### To Reproduce

1. Login to superadmin dashboard
2. Click on the installation config tab
3. Click on new installation config
4. Enter name as BRAND_NAME and value as desired value

### Expected behavior

BRAND_NAME variable gets set as the desired value

### Environment

Heroku

### Cloud Provider

None

### Platform

Browser

**Comment by sojan-official** [comment]
https://www.chatwoot.com/docs/self-hosted/faq/#how-can-i-customise-the-chatwoot-branding-
