### ISSUE TITLE
[CW-2373] v3.0.0 - Widget Background Missing

### ISSUE THREAD

**Issue by amplitudesxd** [chatwoot/chatwoot#7656]
### Describe the bug

On Chatwoot v3.0.0, the background colour of the Chat widget is missing (set to 0.02% opacity).

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/0aa665f8-aaaf-4372-9080-75ed0d02311c/4e296dcc-0814-4eec-a916-adb4db73a5e2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8wYWE2NjVmOC1hYWFmLTQzNzItOTA4MC03NWVkMGQwMjMxMWMvNGUyOTZkY2MtMDgxNC00ZWVjLWE5MTYtYWRiNGRiNzNhNWUyIiwiaWF0IjoxNjkxNDkwMjg0LCJleHAiOjE2OTE1NzY2ODR9.-gPcOc78EwnsyaN02Ljc2oDL309SplVqsfPklfHCUtw)

I've found the cause to be this, which tries to check if the current page is a portal page (I think?):
[https://github.com/chatwoot/chatwoot/blob/ef33c6065258a34c36e55987021e26dbfa1b142b/app/javascript/widget/components/layouts/ViewWithHeader.vue#L5](https://github.com/chatwoot/chatwoot/blob/ef33c6065258a34c36e55987021e26dbfa1b142b/app/javascript/widget/components/layouts/ViewWithHeader.vue#L5)

As the `portal` field is an object even on the widget page, it sets the background to be mostly transparent.

### To Reproduce

1. Use latest Chatwoot v3.0.0 version
2. Setup web chat widget
3. See lack of background

### Expected behavior

1. A background

### Environment

Linux VM

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2373](https://linear.app/chatwoot/issue/CW-2373/v300-widget-background-missing)</sub>

**Comment by amplitudesxd** [comment]
I've looked into this a little more and I don't believe it's due to dark mode. From what I can tell, `background-color: rgba(100, 82, 217, 0.02);` is somehow set on the widget property. I assume it's because of this line:

https://github.com/chatwoot/chatwoot/blob/ef33c6065258a34c36e55987021e26dbfa1b142b/app/javascript/widget/components/layouts/ViewWithHeader.vue#L5

**Comment by vishnu-narayanan** [comment]
@amplitudesxd Thank you for the bug report.

**Comment by iamsivin** [comment]
Fix for this [issue](https://github.com/chatwoot/chatwoot/pull/7654)

**Comment by pranavrajs** [comment]
Closed it via https://github.com/chatwoot/chatwoot/pull/7654
