### ISSUE TITLE
automatic reconnect (v2.18.0)

### ISSUE THREAD

**Issue by Ghost108** [chatwoot/chatwoot#7663]
### Describe the bug

The chatwoot agent webinterface should automatically starts a reconnect when the connection has been disconnected.
![Bildschirmfoto 2023-08-03 um 08 43 57](https://github.com/chatwoot/chatwoot/assets/17011498/261343dc-3175-45ef-a7cd-2f16cf1fae36)

(Disconnected from chatwoot)

### To Reproduce

1. Open the agent web interface and login
2. Disconnect from Internet to simulate a "disconncet"
3. Message (like the screenshot) shoud appears. And the developer console shows this:
![Bildschirmfoto 2023-08-03 um 09 41 57](https://github.com/chatwoot/chatwoot/assets/17011498/79285912-f5be-4424-a8b6-694b2e4d7c7e)
4. Connect to internet again.
5. The message (banner top right, content: Disconnected from chatwoot) will not disappear

### Expected behavior

There should be an auto reconnection function, which should check everty X seconds the connection.
If the connection is available again, the banner message should disappear

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Browser and version

Firefox 116.0

**Comment by iammattmartin** [comment]
This isn't a new thing and is a long standing issue.  #6411

**Comment by pranavrajs** [comment]
Closing this as it is a duplicate of #6411. We are working on sync mechanism. Retries and reconnects are buggy at the moment and it is reason why we show the alert to the user that they are aware that the data may be stale.

**Comment by arladmin** [comment]
@pranavrajs 
Is there any fix for this, so far?

Without a fix, it actually doesn't make much sense to continue using Chatwoot for various types of inboxes, eg. Whatsapp, Website, and others, where an incoming message is expected to pop-up/create a notification, immediately upon its arrival!
