### ISSUE TITLE
[CW-2346] New messages should create new conversation in WhatsApp if lock to single conversation is disabled and existing conversation is resolved

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#7669]
ref: [https://app.chatwoot.com/app/accounts/1/conversations/23260](https://app.chatwoot.com/app/accounts/1/conversations/23260)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2346](https://linear.app/chatwoot/issue/CW-2346/new-messages-should-create-new-conversation-in-whatsapp-if-lock-to)</sub>

**Comment by pranavrajs** [comment]
Closing this as the issue on Github doesn't have any context, we can follow up on Linear.

**Comment by ycarooliveira** [comment]
How it going this issue? and is about this right https://github.com/chatwoot/chatwoot/issues/6556!?
