### ISSUE TITLE
Messages not getting delivered or received till refresh the screen

### ISSUE THREAD

**Issue by santoshvarma4u** [chatwoot/chatwoot#7674]
### Describe the bug

I have installed it in ubuntu using an easy panel template. But when sending messages either of the side messages is showing only when the page or screen is refreshed. 

### To Reproduce

1. Just install using the chatwoot template form the easy panel 

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

MAC

**Comment by sojan-official** [comment]
@santoshvarma4u Easypannel is a community-contributed installation method. Please reach out to their support in cases of issues.
