### ISSUE TITLE
Super_admin is inaccessible (chatwoot/chatwoot:lastest image)

### ISSUE THREAD

**Issue by austinibele** [chatwoot/chatwoot#7678]
### Describe the bug

Navigating to FRONTEND_URL/super_admin does not work in either safari nor google Chrome. (note: This is the link for 'profile settings' -> 'Super Admin Console', that you can find by clicking on the icon in the lower left after entering the normal chatwoot console). It appears that after checking that the super_admin has not been authenticated, that you should be redirected to FRONTEND_URL/super_admin/sign_in. This redirect does not function properly. After manually navigating to the sign-in page and entering credentials, an internal server error occurs in the rails service.

UPON NAVIGATING TO FRONTEND_URL/super_admin

Error message in Safari:

Safari Can't Open the Page
Safari can't open the page "FRONTEND_URL/super_admin" because the page's address isn't valid.

Error message in Chome:
(Attempts to redirect to "FRONTEND_URL, FRONTEND_URL/super_admin/sign_in" (which is a malformed URL))
This site can't be reached.
Check if there is a typo in FRONTEND_URL%2C%20FRONTEND_URL
DNS_PROBE_FINISHED_NXDOMAIN

Rails Logs:

I, [2023-08-06T22:27:21.442470 #1]  INFO -- : [baba092a-fc13-4f61-85ab-75bb67f29338] Started GET "/super_admin" for 172.21.0.6 at 2023-08-06 22:27:21 +0000
I, [2023-08-06T22:27:21.445502 #1]  INFO -- : [baba092a-fc13-4f61-85ab-75bb67f29338] Processing by SuperAdmin::DashboardController#index as HTML
I, [2023-08-06T22:27:21.447220 #1]  INFO -- : [baba092a-fc13-4f61-85ab-75bb67f29338] Completed 401 Unauthorized in 1ms (ActiveRecord: 0.0ms | Allocations: 729)
I, [2023-08-06T22:27:21.449640 #1]  INFO -- : source=rack-timeout id=baba092a-fc13-4f61-85ab-75bb67f29338 timeout=15000ms service=8ms state=completed
I, [2023-08-06T22:27:21.877112 #1]  INFO -- : Finished "/cable" [WebSocket] for 172.21.0.6 at 2023-08-06 22:27:21 +0000
I, [2023-08-06T22:27:21.877336 #1]  INFO -- : RoomChannel stopped streaming from A7CLoU3BNVwtcE4hCwJqndaM

_________

Upon navigating directly to FRONTEND_URL/super_admin/sign-in

The sign in page renders correctly and I am able to enter my credentials. After pressing "Login", the following error is displayed:

"
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.
"

This displays identically in both safari and google chrome

_____

Rails Logs in CHROME (there is no "no route matches /favicon" error with Chrome strangely):

I, [2023-08-06T22:09:17.066062 #1]  INFO -- : [d096da04-5f3d-41b5-b3a8-7ba8e4edb7b5] Started GET "/super_admin/sign_in" for 172.19.0.6 at 2023-08-06 22:09:17 +0000
I, [2023-08-06T22:09:17.070082 #1]  INFO -- : [d096da04-5f3d-41b5-b3a8-7ba8e4edb7b5] Processing by SuperAdmin::Devise::SessionsController#new as HTML
I, [2023-08-06T22:09:17.074273 #1]  INFO -- : [d096da04-5f3d-41b5-b3a8-7ba8e4edb7b5]   Rendered super_admin/devise/sessions/new.html.erb (Duration: 1.5ms | Allocations: 680)
I, [2023-08-06T22:09:17.074794 #1]  INFO -- : [d096da04-5f3d-41b5-b3a8-7ba8e4edb7b5] Completed 200 OK in 5ms (Views: 2.4ms | ActiveRecord: 0.0ms | Allocations: 2026)
I, [2023-08-06T22:09:17.075772 #1]  INFO -- : source=rack-timeout id=d096da04-5f3d-41b5-b3a8-7ba8e4edb7b5 timeout=15000ms service=11ms state=completed
I, [2023-08-06T22:09:24.279447 #1]  INFO -- : RoomChannel#update_presence
I, [2023-08-06T22:09:24.289428 #1]  INFO -- : RoomChannel#update_presence
I, [2023-08-06T22:09:24.566665 #1]  INFO -- : RoomChannel#update_presence
I, [2023-08-06T22:09:40.297012 #1]  INFO -- : source=rack-timeout id=765595b9-8717-46cc-a7c1-b964921cf4fe timeout=15000ms state=ready
I, [2023-08-06T22:09:40.297834 #1]  INFO -- : [765595b9-8717-46cc-a7c1-b964921cf4fe] Started POST "/super_admin/sign_in" for 172.19.0.6 at 2023-08-06 22:09:40 +0000
I, [2023-08-06T22:09:40.303193 #1]  INFO -- : [765595b9-8717-46cc-a7c1-b964921cf4fe] Processing by SuperAdmin::Devise::SessionsController#create as HTML
I, [2023-08-06T22:09:40.303315 #1]  INFO -- : [765595b9-8717-46cc-a7c1-b964921cf4fe]   Parameters: {"authenticity_token"=>"[FILTERED]", "super_admin"=>{"email"=>"my.visa.usa.org@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"1"}}
I, [2023-08-06T22:09:40.468203 #1]  INFO -- : [765595b9-8717-46cc-a7c1-b964921cf4fe] Redirected to 
I, [2023-08-06T22:09:40.468883 #1]  INFO -- : [765595b9-8717-46cc-a7c1-b964921cf4fe] Completed 500 Internal Server Error in 165ms (ActiveRecord: 4.8ms | Allocations: 3460)
F, [2023-08-06T22:09:40.469963 #1] FATAL -- : [765595b9-8717-46cc-a7c1-b964921cf4fe]   
[765595b9-8717-46cc-a7c1-b964921cf4fe] ActionController::Redirecting::UnsafeRedirectError (Unsafe redirect to "http://chatwoot.mydomain.com, chatwoot.mydomian.com/super_admin/users", pass allow_other_host: true to redirect anyway.):
[765595b9-8717-46cc-a7c1-b964921cf4fe]   
[765595b9-8717-46cc-a7c1-b964921cf4fe] app/controllers/super_admin/devise/sessions_controller.rb:13:in `create'
[765595b9-8717-46cc-a7c1-b964921cf4fe] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[765595b9-8717-46cc-a7c1-b964921cf4fe] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
I, [2023-08-06T22:09:40.470547 #1]  INFO -- : source=rack-timeout id=765595b9-8717-46cc-a7c1-b964921cf4fe timeout=15000ms service=174ms state=completed
I, [2023-08-06T22:09:43.130153 #1]  INFO -- : RoomChannel#update_presence

Rails Logs in SAFARI (showing 200 response from manually navigating to FRONTEND_URL/super_admin/sign-in and then 500 error):

I, [2023-08-06T22:31:04.167154 #1]  INFO -- : [50699434-8c62-4597-8111-8d63daeffaaa] Started GET "/super_admin/sign_in" for 172.21.0.6 at 2023-08-06 22:31:04 +0000
I, [2023-08-06T22:31:04.170926 #1]  INFO -- : [50699434-8c62-4597-8111-8d63daeffaaa] Processing by SuperAdmin::Devise::SessionsController#new as HTML
I, [2023-08-06T22:31:04.174848 #1]  INFO -- : [50699434-8c62-4597-8111-8d63daeffaaa]   Rendered super_admin/devise/sessions/new.html.erb (Duration: 1.4ms | Allocations: 680)
I, [2023-08-06T22:31:04.175766 #1]  INFO -- : [50699434-8c62-4597-8111-8d63daeffaaa] Completed 200 OK in 5ms (Views: 2.2ms | ActiveRecord: 0.0ms | Allocations: 1997)
I, [2023-08-06T22:31:04.177575 #1]  INFO -- : source=rack-timeout id=50699434-8c62-4597-8111-8d63daeffaaa timeout=15000ms service=11ms state=completed
I, [2023-08-06T22:31:21.878408 #1]  INFO -- : source=rack-timeout id=8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810 timeout=15000ms state=ready
I, [2023-08-06T22:31:21.879960 #1]  INFO -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] Started POST "/super_admin/sign_in" for 172.21.0.6 at 2023-08-06 22:31:21 +0000
I, [2023-08-06T22:31:21.886924 #1]  INFO -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] Processing by SuperAdmin::Devise::SessionsController#create as HTML
I, [2023-08-06T22:31:21.887052 #1]  INFO -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810]   Parameters: {"authenticity_token"=>"[FILTERED]", "super_admin"=>{"email"=>"my.visa.usa.org@gmail.com", "password"=>"[FILTERED]", "remember_me"=>"0"}}
I, [2023-08-06T22:31:21.920041 #1]  INFO -- : source=rack-timeout id=132f81ac-8354-4106-85d3-f92daef41bb7 timeout=15000ms state=ready
I, [2023-08-06T22:31:21.921366 #1]  INFO -- : [132f81ac-8354-4106-85d3-f92daef41bb7] Started GET "/favicon.ico" for 172.21.0.6 at 2023-08-06 22:31:21 +0000
F, [2023-08-06T22:31:21.924385 #1] FATAL -- : [132f81ac-8354-4106-85d3-f92daef41bb7]   
[132f81ac-8354-4106-85d3-f92daef41bb7] **ActionController::RoutingError (No route matches [GET] "/favicon.ico"):**
[132f81ac-8354-4106-85d3-f92daef41bb7]   
I, [2023-08-06T22:31:21.925320 #1]  INFO -- : source=rack-timeout id=132f81ac-8354-4106-85d3-f92daef41bb7 timeout=15000ms service=5ms state=completed
I, [2023-08-06T22:31:22.050538 #1]  INFO -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] Redirected to 
I, [2023-08-06T22:31:22.051091 #1]  INFO -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] Completed 500 Internal Server Error in 164ms (ActiveRecord: 3.5ms | Allocations: 4431)
F, [2023-08-06T22:31:22.051957 #1] FATAL -- : [8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810]   
[8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] **ActionController::Redirecting::UnsafeRedirectError (Unsafe redirect to "http://chatwoot.mydomain.com, chatwoot.mydomain.com/super_admin/users", pass allow_other_host: true to redirect anyway.):**
[8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810]   
[8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] app/controllers/super_admin/devise/sessions_controller.rb:13:in `create'
[8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] app/controllers/concerns/switch_locale.rb:24:in `set_locale'
[8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810] app/controllers/concerns/switch_locale.rb:11:in `switch_locale'
I, [2023-08-06T22:31:22.052402 #1]  INFO -- : source=rack-timeout id=8140d1b3-1f38-4c1f-a6a0-a7a6e77f6810 timeout=15000ms service=174ms state=completed
I, [2023-08-06T22:31:24.121332 #1]  INFO -- : RoomChannel#update_presence
I, [2023-08-06T22:31:24.121944 #1]  INFO -- : RoomChannel#update_presence
I, [2023-08-06T22:31:24.318751 #1]  INFO -- : RoomChannel#update_presence

____

It appears I am being routed to a malformed URL when pressing the sign-in button. It looks like the FRONTEND_URL env var is being placed in a tuple with the correct redirect url, and that I am then trying to be redirected to "url, url/super_admin".

Everything else appears to be working correctly. I've successfully added WhatsApp, email, website, and Facebook channels to my dockerized chatwoot instance. I rebuilt the services today from the latest image. I can't remember if I've been into the super_admin console before.. I don't think I have (I've only been running Chatwoot for 1 month).

### To Reproduce

1. Configure your chatwoot domain with SSL. Set FRONTEND_ENV var to your chatwoot domain.
2. Spin up chatwoot docker services on a GCP VM

version: '3'

services:
  rails:
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - ./chatwoot_data/storage:/app/storage
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    image: chatwoot/chatwoot:latest
    env_file: .env
    volumes:
      - ./chatwoot_data/storage:/app/storage
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: postgres:12
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./chatwoot_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=.....

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
    env_file: .env
    volumes:
      - ./chatwoot_data/redis:/data
    ports:
      - '6379:6379'

  chatwoot-nginx-service:
    image: chatwoot-nginx-service:latest
    build:
      context: .
      dockerfile: nginx/Dockerfile
    expose:
      - 3000
    ports:
      - 80:80
      - 443:443
    depends_on:
      - redis

3. Follow steps described in the description.

### Expected behavior

1. Link to FRONTEND_URL/super_admin should work, or at least I should be redirected to the sign-in page without error
2. I should be able to sign in with my super_admin credentials (note: I verified that my user [1st created] is a super_admin through the Rails console)

### Environment

Docker

### Cloud Provider

GCP

### Platform

Browser

### Operating system

5.10.0-23-cloud-amd64

### Browser and version

Chrome 114.0.5735.248 AND Chrome Version 115.0.5790.170 (latest), Safari 16.5.2

### Docker (if applicable)

$ docker-info

Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 9
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.0-23-cloud-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.77GiB
 Name: chatwoot
 ID: e1e24c70-4e86-4f44-b63d-251a8def3e25
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 
 
 
 ____
 
 $ docker-compose --version
docker-compose version 1.29.2, build 5becea4c

**Comment by austinibele** [comment]
Also experiencing the issue on chatwoot v2.18.0 and v2.17.0-ce, which makes me think the problem is my environment.

This is my CI/CD deployment script.

#!/bin/bash
# deploy.sh

# Deleting DB
# Running 'deploy.sh delete_db true' will delete the db data directory
vm_ip=${1:-34.148.117.13}

# Remove old scripts
echo "Removing old deployment scripts on vm..."
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "sudo rm -r austin_ibele/chatwoot/nginx"
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "sudo rm austin_ibele/chatwoot/privkey.pem"
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "sudo rm austin_ibele/chatwoot/fullchaim.pem"
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "sudo rm austin_ibele/chatwoot/.env"

# Copy new scripts to VM
echo "Copying new deployment scripts to vm..."
scp -r chatwoot/nginx austin.ibele@$vm_ip:~/austin_ibele/chatwoot/
scp chatwoot/docker-compose.yaml austin.ibele@$vm_ip:~/austin_ibele/chatwoot
scp chatwoot/.env austin.ibele@$vm_ip:~/austin_ibele/chatwoot

# Transfer ssl certificates to VM and replace them
echo "Transferring ssl certificates to VM..."
scp secrets/chatwoot_privkey.pem austin.ibele@$vm_ip:~/austin_ibele/chatwoot/privkey.pem
scp secrets/chatwoot_fullchain.pem austin.ibele@$vm_ip:~/austin_ibele/chatwoot/fullchain.pem

# Stop all running containers on VM
echo "Stopping all running containers and pruning docker system on VM..."
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip 'docker stop $(docker ps -q)'
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip 'docker system prune -f'

# Prepare chatwoot database
echo "Preparing chatwoot database..."
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "cd austin_ibele/chatwoot && docker compose run --rm rails bundle exec rails db:chatwoot_prepare"

# Start chatwoot service on vm
echo "Starting chatwoot service..."
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip "cd austin_ibele/chatwoot && docker-compose build && docker-compose up -d postgres redis sidekiq rails"

sleep 30

# Start nginx
echo "Starting nginx service..."
ssh -i ~/.ssh/id_rsa austin.ibele@$vm_ip 'docker run -d --name chatwoot-nginx-service --network chatwoot_default -p 80:80 -p 443:443 -p 3000 --entrypoint "nginx" chatwoot-nginx-service -g "daemon off;"'

**Comment by austinibele** [comment]
I experience the same errors in v2.14.0, however when I manually navigate to "https://chatwoot.mydomain.com/super_admin/users" after pressing the Login button, I am actually logged in and can view the super-admin dashboard.


When I do the same for v2.18.0, I get a 404 not found error for "https://chatwoot.mydomain.com/super_admin/users".

**Comment by vishnu-narayanan** [comment]
@austinibele Looks like this has something to do with SSL and proxy server infront of Chatwoot.

Could you try experimenting with the following environment variables?

```
FORCE_SSL=false/true
FRONTEND_URL=http/https version of your domain
```
