### ISSUE TITLE
Remove Widget Referece From the Page

### ISSUE THREAD

**Issue by matheus-rodrigues00** [chatwoot/chatwoot#7711]
### Is your feature or enhancement related to a problem? Please describe.

It's an enhancement. We want he hability to remove the widget once launched.

### Describe the solution you'd like

I want to have a method that cleans up whe window references of the widget and removes the widget baloon element from the page.

### Describe alternatives you've considered

I hard-code am removing the widget because I need to launch it again with different configurations.
What I'm doing is like:

``` javascript
delete window.chatwootSDK;
delete window.$chatwoot;
const BASE_URL = "https://chat.wellon.digital/packs/js/sdk.js";
const allsuspects = document.getElementsByTagName("script");
const wootWidgetHolder = document.querySelector(".woot-widget-holder");
const wootBubbleHolder = document.querySelector(".woot--bubble-holder");
if (wootWidgetHolder) wootWidgetHolder.remove();
if (wootBubbleHolder) wootBubbleHolder.remove();
for (let i = allsuspects.length; i >= 0; i--) {
  if (
    allsuspects[i] &&
    allsuspects[i].getAttribute("src") != null &&
    allsuspects[i].getAttribute("src").indexOf(BASE_URL) != -1
  ) {
    allsuspects[i].parentNode.removeChild(allsuspects[i]);
  }
}
```

**Comment by pranavrajs** [comment]
@matheus-rodrigues00 I believe you can use the toggleBubbleVisibility method in the SDK as described [here](https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup#toggle-the-widget-bubble-visibility). 

Closing this as it doesn't seem to be something we need to work on. Please feel free to reopen if it doesn't solve the issue.

**Comment by matheus-rodrigues00** [comment]
I think misunderstood what I said. I want the COMPLETELY remotion of the chatwoot, from the application. 
I want to te be able to launch again the chatwoot. With different configurations. I don't want to toggle visibility. Do you get it?
@pranavrajs

**Comment by matheus-rodrigues00** [comment]
There are references to the chatwoot on the window object, also the bubble is on the page still. I don't want those anymore. I want the completely remotion of the chatwoot, every single component or method added to my application.

**Comment by pranavrajs** [comment]
@matheus-rodrigues00 Are you looking to disable the widget temporarily? I'm sorry I couldn't understand the use case. Why is it required to remove the references? Also, I didn't get the part where you mentioned that you need to launch with multiple configuration. 

Can you please share a screencast explaining the use case? That would be helpful to take this forward.

**Comment by matheus-rodrigues00** [comment]
Okay @pranavrajs, here's the video explaining, let me tell if you got this:
https://www.youtube.com/watch?v=MC6BnxHN3-Q&ab_channel=MatheusRodrigues
