### ISSUE TITLE
[CW-2427] Cannot create microsoft email inbox for a shared mailbox

### ISSUE THREAD

**Issue by DwanW** [chatwoot/chatwoot#7722]
### Describe the bug

we followed the steps to setup azure app, it is able to create a microsoft inbox for a person's account, it works.

but when creating a microsoft email inbox for a shared mailbox, it will just redirect back to the chatwoot main page, and nothing gets created.

I also looked at the logs for web, and the only error I see is this.
Can anyone explain to me what this implies? Is there any work around for microsoft shared mailbox?

```
Aug 14 18:54:19 chatwoot-web.1[584689]: OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
Aug 14 18:54:19 chatwoot-web.1[584689]: E, [2023-08-14T18:54:19.263915 #584689] ERROR -- : [bc1ad953-f5aa-4f68-98a0-743560bc4858] Couldn't find Account without an ID
Aug 14 18:54:19 chatwoot-web.1[584689]: I, [2023-08-14T18:54:19.264412 #584689]  INFO -- : [bc1ad953-f5aa-4f68-98a0-743560bc4858] Redirected to 
```

### To Reproduce

1. create a microsoft shared mailbox  [steps](https://learn.microsoft.com/en-us/microsoft-365/admin/email/create-a-shared-mailbox?view=o365-worldwide) e.g. shared@domain.com
2. give access for a few members for the shared mailbox, permission full access. e.g. user1@domain.com now has access to shared@domain.com email
3. go to chatwoot and try creating a microsoft email inbox using the shared email shared@domain.com
4. enter the shared email (shared@domain.com), then sign in with microsoft, select user1@domain.com and allow access.

result:  chatwoot redirect to main page, and nothing gets created

### Expected behavior

go to next step and select collaborators, microsoft email inbox gets created with (shared@domain.com).

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

<sub>[CW-2427](https://linear.app/chatwoot/issue/CW-2427/cannot-create-microsoft-email-inbox-for-a-shared-mailbox)</sub>

**Comment by pranavrajs** [comment]
@DwanW 

Have you gone through the production ready steps as described [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/#going-into-production)? You would not be able to access any other account other than the one which you used to create before you get verified.

Please share the Chatwoot version as well. Let me know.

**Comment by DwanW** [comment]
@pranavrajs 

Yes, we have gone through the production ready steps, as for the emails that worked, I have tested with other people's email as well, they all work. The only email that doesn't work is when creating microsoft email inbox with a shared microsoft mailbox.

the Chatwoot version is 
v2.18.0
Build e204fe1c1f5cb57499459f22d7a70885a7db4b3f

**Comment by pranavrajs** [comment]
@DwanW I'm not sure about the shared emails in Microsoft. This needs an investigation. I will get this prioritized in the upcoming sprints.

**Comment by thibaultjunin** [comment]
Hi, I've just come across this issue and I'm having the same problem configuring a Microsoft inbox for a shared mailbox. Are there any updates or fixes?
Thanks so much for looking into this!

**Comment by pranavrajs** [comment]
Closing this here and combining this #8869.
