### ISSUE TITLE
couldn't receive emails

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#7724]
### Describe the bug

couldn't receive emails with error :

> ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [bab9dc29-1dc6-4b61-841c-2052378b01ae] Selected auth method not supported

### To Reproduce

IMAP setting :

address : xxxxx.smarterasp.net
port : 993
log in : xxxxxx
password : xxxxxx
enable ssl : yes

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@Double-Click-ERP 

1/ Can you please share the Chatwoot version? 
2/ Is it a custom mail server? If so, don't you support 'PLAIN' authentication type?
3/ Can you please share the full logs as well?

**Comment by Double-Click-ERP** [comment]
Hello @pranavrajs ,

> 1/ Can you please share the Chatwoot version? 

v2.18.0

> 2/ Is it a custom mail server? If so, don't you support 'PLAIN' authentication type? 

yes , yes (the channel was created successfully)

> 3/ Can you please share the full logs as well?

here you are (after delete some whatsapp jobs)


> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.205Z","pid":128676,"tid":"303o","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"7db5164d999209beafe40421"}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.205980 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Performing Inboxes::FetchImapEmailInboxesJob (Job ID: 1009ed77-54cd-4c23-a1ce-c5704416d19d) from Sidekiq(scheduled_jobs) enqueued at 2023-08-16T06:34:01Z
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.210978 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Enqueued Inboxes::FetchImapEmailsJob (Job ID: 8dba13d3-0f41-4e15-9f0a-b3d158739a90) to Sidekiq(scheduled_jobs) with arguments: #<GlobalID:0x00007fb976f27fb0 @uri=#<URI::GID gid://chatwoot/Channel::Email/8>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.211Z","pid":128676,"tid":"30ck","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"0f2454bef2ba21885623907d"}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.213212 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Enqueued Inboxes::FetchImapEmailsJob (Job ID: 6a3a7655-7454-4f58-a63a-10e330daa498) to Sidekiq(scheduled_jobs) with arguments: #<GlobalID:0x00007fb9780bd1a8 @uri=#<URI::GID gid://chatwoot/Channel::Email/9>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.222057 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [8dba13d3-0f41-4e15-9f0a-b3d158739a90] Performing Inboxes::FetchImapEmailsJob (Job ID: 8dba13d3-0f41-4e15-9f0a-b3d158739a90) from Sidekiq(scheduled_jobs) enqueued at 2023-08-16T06:34:01Z with arguments: #<GlobalID:0x00007fb97a62e310 @uri=#<URI::GID gid://chatwoot/Channel::Email/8>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.213Z","pid":128676,"tid":"30l0","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"3d6d59f48b797b991b15ce53"}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.224Z","pid":128676,"tid":"30jk","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"5c558e81e0c1abced33c4008"}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.225413 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Enqueued Inboxes::FetchImapEmailsJob (Job ID: c93d410a-3848-4786-a586-843760473b7a) to Sidekiq(scheduled_jobs) with arguments: #<GlobalID:0x00007fb979e762f8 @uri=#<URI::GID gid://chatwoot/Channel::Email/10>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.226262 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [6a3a7655-7454-4f58-a63a-10e330daa498] Performing Inboxes::FetchImapEmailsJob (Job ID: 6a3a7655-7454-4f58-a63a-10e330daa498) from Sidekiq(scheduled_jobs) enqueued at 2023-08-16T06:34:01Z with arguments: #<GlobalID:0x00007fb979f136c0 @uri=#<URI::GID gid://chatwoot/Channel::Email/9>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.228629 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [6a3a7655-7454-4f58-a63a-10e330daa498] Performed Inboxes::FetchImapEmailsJob (Job ID: 6a3a7655-7454-4f58-a63a-10e330daa498) from Sidekiq(scheduled_jobs) in 4.22ms
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.229102 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [c93d410a-3848-4786-a586-843760473b7a] Performing Inboxes::FetchImapEmailsJob (Job ID: c93d410a-3848-4786-a586-843760473b7a) from Sidekiq(scheduled_jobs) enqueued at 2023-08-16T06:34:01Z with arguments: #<GlobalID:0x00007fb97a7e4600 @uri=#<URI::GID gid://chatwoot/Channel::Email/10>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.229Z","pid":128676,"tid":"302k","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"143b24c297b10dccf3190502"}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.229512 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Enqueued Inboxes::FetchImapEmailsJob (Job ID: 6ade24e9-5524-499a-aaf8-e94540538469) to Sidekiq(scheduled_jobs) with arguments: #<GlobalID:0x00007fb97a819800 @uri=#<URI::GID gid://chatwoot/Channel::Email/15>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.228Z","pid":128676,"tid":"30l0","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"3d6d59f48b797b991b15ce53","elapsed":0.015}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.233745 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [6ade24e9-5524-499a-aaf8-e94540538469] Performing Inboxes::FetchImapEmailsJob (Job ID: 6ade24e9-5524-499a-aaf8-e94540538469) from Sidekiq(scheduled_jobs) enqueued at 2023-08-16T06:34:01Z with arguments: #<GlobalID:0x00007fb978245908 @uri=#<URI::GID gid://chatwoot/Channel::Email/15>>
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.236295 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [1009ed77-54cd-4c23-a1ce-c5704416d19d] Performed Inboxes::FetchImapEmailInboxesJob (Job ID: 1009ed77-54cd-4c23-a1ce-c5704416d19d) from Sidekiq(scheduled_jobs) in 30.36ms
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.236Z","pid":128676,"tid":"303o","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"7db5164d999209beafe40421","elapsed":0.031}}
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: E, [2023-08-16T09:34:01.668283 #128676] ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [6ade24e9-5524-499a-aaf8-e94540538469] SSL_connect returned=1 errno=0 peeraddr=208.118.63.40:143 state=error: wrong version number
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:01.668493 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [6ade24e9-5524-499a-aaf8-e94540538469] Performed Inboxes::FetchImapEmailsJob (Job ID: 6ade24e9-5524-499a-aaf8-e94540538469) from Sidekiq(scheduled_jobs) in 438.32ms
> أغس 16 09:34:01 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:01.668Z","pid":128676,"tid":"302k","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"143b24c297b10dccf3190502","elapsed":0.44}}
> أغس 16 09:34:02 chat-VirtualBox chatwoot-worker.1[128676]: E, [2023-08-16T09:34:02.600469 #128676] ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [8dba13d3-0f41-4e15-9f0a-b3d158739a90] Selected auth method not supported
> أغس 16 09:34:02 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:02.600622 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [8dba13d3-0f41-4e15-9f0a-b3d158739a90] Performed Inboxes::FetchImapEmailsJob (Job ID: 8dba13d3-0f41-4e15-9f0a-b3d158739a90) from Sidekiq(scheduled_jobs) in 1388.52ms
> أغس 16 09:34:02 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:02.600Z","pid":128676,"tid":"30ck","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"0f2454bef2ba21885623907d","elapsed":1.39}}
> أغس 16 09:34:03 chat-VirtualBox chatwoot-worker.1[128676]: E, [2023-08-16T09:34:03.693303 #128676] ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [c93d410a-3848-4786-a586-843760473b7a] Selected auth method not supported
> أغس 16 09:34:03 chat-VirtualBox chatwoot-worker.1[128676]: I, [2023-08-16T09:34:03.693648 #128676]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [c93d410a-3848-4786-a586-843760473b7a] Performed Inboxes::FetchImapEmailsJob (Job ID: c93d410a-3848-4786-a586-843760473b7a) from Sidekiq(scheduled_jobs) in 2467.84ms
> أغس 16 09:34:03 chat-VirtualBox chatwoot-worker.1[128676]: {"ts":"2023-08-16T06:34:03.694Z","pid":128676,"tid":"30jk","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"5c558e81e0c1abced33c4008","elapsed":2.469}}
>

**Comment by Double-Click-ERP** [comment]
@pranavrajs  any update ?

**Comment by Double-Click-ERP** [comment]
@pranavrajs any update ?

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/7145#issuecomment-1921354640
