### ISSUE TITLE
Allow an option to lock the conversation to a single thread in API channels

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#7726]
### Is your feature or enhancement related to a problem? Please describe.

In API channel, I don´t want who my agents create new conversations in a contact. Only continue with the already created conversation.

### Describe the solution you'd like

I can manipulate this via the API, but the frontend lets my agents create new conversations. If I had that possibility, I could block the API channel so that agents don't create new conversations in the same channel for the contact.

### Describe alternatives you've considered

A simple option, in channel configuration, with true or false, who enable or disable create new conversations.

### Additional context

https://discord.com/channels/647412545203994635/1138794306057027634

**Comment by pranavrajs** [comment]
@jmelati It looks like a nice improvement. Happy to take that as an enhancement if anybody is willing to contribute.

**Comment by giquieu** [comment]
@pranavrajs Can I work on this?

**Comment by sojan-official** [comment]
@giquieu  please go ahead

**Comment by eliezerazevedo** [comment]
@giquieu have you made any progress on this topic? It’s something I’m really interested in, and it can make a big difference in managing conversations.

**Comment by giquieu** [comment]
@eliezerazevedo I have sent a PR. We will wait for the Review.

**Comment by eliezerazevedo** [comment]
@giquieu Thank you, I am following along, but your PR still doesn't have any new updates. I believe it can still be evaluated.
