### ISSUE TITLE
Adding an Office 365 mailbox

### ISSUE THREAD

**Issue by nalvio** [chatwoot/chatwoot#7727]
### Describe the bug

Whenever I try to add an Office 365 mailbox after logging in and authorizing the account, I'm redirected to the dashboard.
Checking the log, I can see the following message:
`undefined method 'downcase' for nil:NilClass`

### To Reproduce

1. Access the `new inbox` screen
2. Select Email > Microsoft
3. Add mailbox address
4. Authenticate

### Expected behavior

Proceed to *Add Agent* step

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Safari

**Comment by pranavrajs** [comment]
@nalvio 

1/ Can you please share the version of Chatwoot and the full error log?

2/ Can you please share if you have completed the steps described [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup) and have a working integration already?

3/ If not, can you please check if you have missed any of the steps written in the document above?

**Comment by nalvio** [comment]
Sure, below are the answers
1. Version 2.18.0
For security reasons, I'll hide some data
```
Aug 15 18:09:55 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:55.201138 #44488]  INFO -- : [dbda02d9-da67-4603-a711-5f7edee4423d] Started POST "/api/v1/accounts/1/microsoft/authorization" for {public_ip} at 2023-08-15 18:09:55 +0000
Aug 15 18:09:55 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:55.202658 #44488]  INFO -- : [dbda02d9-da67-4603-a711-5f7edee4423d] Processing by Api::V1::Accounts::Microsoft::AuthorizationsController#create as JSON
Aug 15 18:09:55 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:55.202703 #44488]  INFO -- : [dbda02d9-da67-4603-a711-5f7edee4423d]   Parameters: {"email"=>"{hidden}", "account_id"=>"1", "authorization"=>{"email"=>"hidden"}}
Aug 15 18:09:55 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:55.206858 #44488]  INFO -- : [dbda02d9-da67-4603-a711-5f7edee4423d] Completed 200 OK in 4ms (Views: 0.1ms | ActiveRecord: 0.6ms | Allocations: 2286)
Aug 15 18:09:55 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:55.207223 #44488]  INFO -- : source=rack-timeout id=dbda02d9-da67-4603-a711-5f7edee4423d timeout=15000ms service=6ms state=completed
Aug 15 18:09:56 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:56.175297 #44488]  INFO -- : Finished "/cable" [WebSocket] for {public_ip} at 2023-08-15 18:09:56 +0000
Aug 15 18:09:56 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:09:56.175597 #44488]  INFO -- : RoomChannel stopped streaming from M65Fh3UV72NkPSvjCVJH8eZn
Aug 15 18:10:16 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:16.862648 #44488]  INFO -- : source=rack-timeout id=962259f6-ce18-43ad-9512-64d7dadd1655 timeout=15000ms state=ready
Aug 15 18:10:16 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:16.863181 #44488]  INFO -- : [962259f6-ce18-43ad-9512-64d7dadd1655] Started GET "/microsoft/callback?code={hidden}&session_state={hidden}Aug 15 18:10:16 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:16.864606 #44488]  INFO -- : [962259f6-ce18-43ad-9512-64d7dadd1655] Processing by Microsoft::CallbacksController#show as HTML
Aug 15 18:10:16 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:16.864667 #44488]  INFO -- : [962259f6-ce18-43ad-9512-64d7dadd1655]   Parameters: {"code"=>"{hidden}", "session_state"=>"hidden"}
Aug 15 18:10:17 chatwoot chatwoot-web.1[44488]: OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".
Aug 15 18:10:17 chatwoot chatwoot-web.1[44488]: E, [2023-08-15T18:10:17.163401 #44488] ERROR -- : [962259f6-ce18-43ad-9512-64d7dadd1655] undefined method `downcase' for nil:NilClass
Aug 15 18:10:17 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:17.163710 #44488]  INFO -- : [962259f6-ce18-43ad-9512-64d7dadd1655] Redirected to {site}
Aug 15 18:10:17 chatwoot chatwoot-web.1[44488]: I, [2023-08-15T18:10:17.163909 #44488]  INFO -- : [962259f6-ce18-43ad-9512-64d7dadd1655] Completed 302 Found in 299ms (ActiveRecord: 0.0ms | Allocations: 4019)
```
2. Sure. I have other keys configured and running
3. N/A

**Comment by pranavrajs** [comment]
@nalvio It seems like you have missed the token configuration step. `users_data['email']` is missing. 

![image](https://github.com/chatwoot/chatwoot/assets/2246121/91c8d126-afa4-4468-b914-6d9f0f7e91ce)
https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.

**Comment by jordan26** [comment]
I have the exact same error and issue, I'd like to re-open this issue. I checked the instructions and nothing is missing, here is my token configuration screen for reference:

I have followed the App Registration instructions exactly as described, every single step matches the guide.

`Feb 06 17:15:57 chatwoot chatwoot-web.1[230693]: OAuth2::AccessToken.from_hash: `hash` contained more than one 'token' key (["access_token", "id_token"]); using "access_token".`

`Feb 06 17:15:57 chatwoot chatwoot-web.1[230693]: E, [2024-02-06T17:15:57.922556 #230693] ERROR -- : [18faae79-e994-41d7-b921-81af1c7c62c3] undefined method `downcase' for nil:NilClass`

`Feb 06 17:15:57 chatwoot chatwoot-web.1[230693]: I, [2024-02-06T17:15:57.923180 #230693]  INFO -- : [18faae79-e994-41d7-b921-81af1c7c62c3] Redirected to https://chatwoot.e-bedding.co.uk/``

`Feb 06 17:15:57 chatwoot chatwoot-web.1[230693]: I, [2024-02-06T17:15:57.923496 #230693]  INFO -- : [18faae79-e994-41d7-b921-81af1c7c62c3] Completed 302 Found in 182ms (ActiveRecord: 0.0ms | Allocations: 4091)`
