### ISSUE TITLE
[CW-2401] Top right button inconsitent behavior when a banner is present

### ISSUE THREAD

**Issue by kubre** [chatwoot/chatwoot#7733]
### Describe the bug

If there is a banner like billing or update chatwoot, a button in the top right corner moves.

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/0315dd00-0bc5-4b34-956f-6455a6fc9079/848452b4-3646-4c6b-998d-80facf55593b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8wMzE1ZGQwMC0wYmM1LTRiMzQtOTU2Zi02NDU1YTZmYzkwNzkvODQ4NDUyYjQtMzY0Ni00YzZiLTk5OGQtODBmYWNmNTU1OTNiIiwiaWF0IjoxNjkyMjA5NDU5LCJleHAiOjE2OTIyOTU4NTl9.F1Tev38c28o64QzWgIAX0KaABkN2lVpBRN2GgpaXfyU)

### To Reproduce

1. Have any banner enabled like upgrade or billing at top
2. Scroll

### Expected behavior

The button should stay with the top nav bar itself.

### Environment

[app.chatwoot.com](http://app.chatwoot.com)

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows

### Browser and version

Firefox 116

### Docker (if applicable)

*No response*

### Additional context

You can check this video for a better idea

[https://github.com/chatwoot/chatwoot/assets/20380094/2d254d67-f7ad-4ec7-b444-c85a3da45b90](https://github.com/chatwoot/chatwoot/assets/20380094/2d254d67-f7ad-4ec7-b444-c85a3da45b90)

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2401](https://linear.app/chatwoot/issue/CW-2401/top-right-button-inconsitent-behavior-when-a-banner-is-present)</sub>

**Comment by pranavrajs** [comment]
@iamsivin Can you please take a look at this issue? It seems like a bug and should be minor fix.
