### ISSUE TITLE
MaxmindDB does not work, and cannot download db.

### ISSUE THREAD

**Issue by nanedi** [chatwoot/chatwoot#7734]
### Describe the bug

MaxmindDB does not work, and cannot download db.

### To Reproduce

Just followed
https://www.chatwoot.com/docs/self-hosted/configuration/enable-ip-logging

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 20.04

### Additional context

I have other things want to know.

What is the `Widget API Throttling`? Like this chat window?

`RAILS_INBOUND_EMAIL_SERVICE=mailgun` Correct?

Thank you.

**Comment by pranavrajs** [comment]
@nanedi 

1/ Can you please confirm if you have added the MaxmindDB key as per the documentation [here](https://www.chatwoot.com/docs/self-hosted/configuration/enable-ip-logging/)? 

2/ Can you please share any error logs related to the download?

**Comment by nanedi** [comment]
@pranavrajs 
1/ Yes. `IP_LOOKUP_API_KEY=xxxxxxxxxxx`
2/ I don't see any error logs. Am I not finding any logs related to it?

**Comment by nanedi** [comment]
@pranavrajs 

I think this one is the same problem.
https://github.com/chatwoot/chatwoot/issues/7479

**Comment by sojan-official** [comment]
@nanedi  could you try running `bundle exec rails ip_lookup:setup` in the root folder of Chatwoot ?

**Comment by nanedi** [comment]
@sojan-official 

Just did it.
```
# sudo -i -u chatwoot
# cd chatwoot
# bundle exec rails ip_lookup:setup
```

And looks like it working now?!
![alt text](https://i.imgur.com/ykDYKql.png)

**Comment by pranavrajs** [comment]
Great! Closing it here in that case. Feel free to re-open if it is not the case.

**Comment by nanedi** [comment]
@sojan-official @pranavrajs 

But it looks like the flag is not showing.
