### ISSUE TITLE
[CW-2400] Lithuanian language does not work in v3.0.0

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#7735]
### Describe the bug

Lithuanian language is present in "Settings -> Acount Settings -> Site language" list, but once selected, all text is in English.

### To Reproduce

1. Self-Hosted Linux VM environment, using the latest Chatwoot v3.0.0
2. Navigate to "Settings -> Acount Settings -> Site language", select Lithuanian language and select "Update Settings"
3. Site language will be shown as Lithuanian but all text of the site will be in English

### Expected behavior

Site text is in Lithuanian, once Lithuanian language is selected as Site language.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Microsoft Windows 10 Enterprise; Version 10.0.19045; Build 19045

### Browser and version

Firefox 116.0.2

<sub>[CW-2400](https://linear.app/chatwoot/issue/CW-2400/lithuanian-language-does-not-work-in-v300)</sub>

**Comment by pranavrajs** [comment]
<img width="780" alt="Screenshot 2023-08-16 at 11 04 00 AM" src="https://github.com/chatwoot/chatwoot/assets/2246121/00592f8e-0014-4757-ad66-640cbfd874f2">

Tested this and it seems to be working fine without any issues. I hope this would be related to the error you posted [here](https://github.com/chatwoot/chatwoot/issues/7736). 

I will close this one for now.
