### ISSUE TITLE
Error message is displayed after Logout from Agent Dashboard while using the latest Chatwoot v3.0.0

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#7736]
### Describe the bug

An error message of "We're sorry, but something went wrong. If you are the application owner check the logs for more information." is displayed after Logout from Agent Dashboard while using the latest Chatwoot v3.0.0

Web log-file indicates "ActionView::Template::Error (Webpacker can't find v3app.js in /home/chatwoot/chatwoot/public/packs/manifest.json".

Upon further investigation it was noticed that there is no mention of v3app.js in "/home/chatwoot/chatwoot/public/packs/manifest.json" and v3app.js is present in "/home/chatwoot/chatwoot/app/javascript/packs/v3app.js"

### To Reproduce

1. Self-Hosted Linux VM, using the latest Chatwoot v3.0.0
2. Sign in to Agent Dashboard and then Logout
3. A message of "We're sorry, but something went wrong. If you are the application owner check the logs for more information." will be shown immediately after signing out.

### Expected behavior

Logout from Agent Dashboard does not cause error

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Microsoft Windows 10 Enterprise; Version 10.0.19045; Build 19045

### Browser and version

Firefox 116.0.2

### Additional context

We upgraded from v2.18.0 to v3.0.0 using the latest cwctl

**Comment by pranavrajs** [comment]
@Diplomat-LV It seems like the upgrade process broke in between. Can you please try [this command](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails) and see if it helps?
