### ISSUE TITLE
Fatal error after create new inbox

### ISSUE THREAD

**Issue by gadonski** [chatwoot/chatwoot#7738]
### Describe the bug

After update  to version 3, i been try create a new inbox to test, but throw this error on log:

`I, [2023-08-16T19:58:07.713981 #1]  INFO -- : source=rack-timeout id=155e4d3f-a15a-494a-bd66-dc22fdeffb3f timeout=15000ms service=59ms state=completed
I, [2023-08-16T19:58:07.792766 #1]  INFO -- : source=rack-timeout id=ce3111c5-c5e0-4a47-b704-65d9a6a33d50 timeout=15000ms state=ready
I, [2023-08-16T19:58:07.795742 #1]  INFO -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50] Started GET "/api/v1/accounts/1/inboxes" for 172.68.191.144 at 2023-08-16 19:58:07 +0000
I, [2023-08-16T19:58:07.801233 #1]  INFO -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50] Processing by Api::V1::Accounts::InboxesController#index as JSON
I, [2023-08-16T19:58:07.801378 #1]  INFO -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50]   Parameters: {"account_id"=>"1"}
I, [2023-08-16T19:58:07.834205 #1]  INFO -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50]   Rendered api/v1/accounts/inboxes/index.json.jbuilder (Duration: 13.6ms | Allocations: 1432)
I, [2023-08-16T19:58:07.835515 #1]  INFO -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50] Completed 500 Internal Server Error in 34ms (ActiveRecord: 6.6ms | Allocations: 4019)
F, [2023-08-16T19:58:07.837962 #1] FATAL -- : [ce3111c5-c5e0-4a47-b704-65d9a6a33d50]   
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50] ActionView::Template::Error (undefined method `business_name' for #<Inbox id: 14, channel_id: 13, account_id: 1, name: "xama01", created_at: "2023-08-16 19:51:16.047952000 +0000", updated_at: "2023-08-16 19:51:16.047952000 +0000", channel_type: "Channel::Api", enable_auto_assignment: true, greeting_enabled: false, greeting_message: nil, email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: false, allow_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: nil, sender_name_type: nil>):
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     17: json.allow_messages_after_resolved resource.allow_messages_after_resolved
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     18: json.lock_to_single_conversation resource.lock_to_single_conversation
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     19: json.sender_name_type resource.sender_name_type
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     20: json.business_name resource.business_name
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     21: 
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     22: if resource.portal.present?
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]     23:   json.help_center do
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50]   
[ce3111c5-c5e0-4a47-b704-65d9a6a33d50] app/views/api/v1/models/_inbox.json.jbuilder:2`

### To Reproduce

1. Docker enviroment running v3.0.0
2. Go to Settings > Inbox > add api inbox
3. Type a an name and left the webhook field empty.
4. After command the creation, that message will throw on log and screen show a error message

### Expected behavior

A new inbox created

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 

### Docker (if applicable)

docker version

```
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:57 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:57 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
````

**Comment by sojan-official** [comment]
Did you run the database migrations ?

**Comment by vishnu-narayanan** [comment]
@nestordavalos Could you share the server logs when you try to create an inbox?

**Comment by gadonski** [comment]
@sojan-official  Yep, that1s the log:
https://gist.github.com/gadonski/8b8fc860f5cd8f9f22e50ed13293b835

I created a new inbox today. The error occurs, however it is created.

This is the log:
https://gist.github.com/gadonski/0f6bd1f123af3ca3b100cb9665502f30

**Comment by sojan-official** [comment]
> https://gist.github.com/gadonski/8b8fc860f5cd8f9f22e50ed13293b835

seems like the migration  for  adding `business_name` has been run from your logs. did you restart the services after db migrate ?

**Comment by gadonski** [comment]
@sojan-official nope... and that was the problem.

thanks for your help.
