### ISSUE TITLE
How do I understand the codebase?

### ISSUE THREAD

**Issue by AniketBajpai** [chatwoot/chatwoot#774]
Hello. I am looking to contribute to this repo. I have deployed the code locally and have gone through the docs but am not able to find any link to understand the codebase. Please could anyone point me in the right direction? Thanks!

**Comment by sojan-official** [comment]
Hey @AniketBajpai  thanks for your interest in Chatwoot.  I totally understand your pain when it comes to docs and its something which we are working hard to improve. while we are at it let me try to give a quick brief.  

if you have the code up and running locally, I would suggest you explore the features and UI first, understand the business cases we are solving. 
https://www.chatwoot.com/developers/api/  describes the API ends points that are used in the app. 

Once you have the understanding I guess you can get started with the code,  the backend for chatwoot is primarily done in ruby on rails and front end in vue.js 

if you aren't familiar with the frameworks, the following docs should help you. 
vue.js : https://vuejs.org/v2/guide/
ruby on rails: https://www.learnenough.com/ruby-on-rails-4th-edition-tutorial/beginning

### If you are already comfortable with the frameworks, you can get started right away. 
- the Vue code resides in `app/javascript`
- the repo's parent directory follows standard structure of ruby on rails apps

### Once you feel you are ready to contribute
- Look through the GitHub issues to see if there is anything you feel confident to work on : https://github.com/chatwoot/chatwoot/issues
   - Post a comment on the issue and a team member will assign it to you, with further instructions. 
- You can always reach out to the team on discord if you need help finding issues to work on or have any questions. : https://discord.gg/cJXdrwS - Feel free to report bugs as new issues on GitHub. 
 
Let us know if you need any further help.

**Comment by pranavrajs** [comment]
Closing this as no further action is required.
