### ISSUE TITLE
Feature: Avoid Agent collision

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#775]
**Is your feature request related to a problem? Please describe.**
When I have multiple agents in my system, there is a chance that agents end up working on the same ticket.

**Describe the solution you'd like**
We need typing indicator above the input area showing that another agent is working on the conversation.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by pranavrajs** [comment]
Closing this as the typing indicator is already shipped, let us reopen if we have further things to be done here.
