### ISSUE TITLE
Docker installation

### ISSUE THREAD

**Issue by FrancisMorelli** [chatwoot/chatwoot#7768]
### Describe the bug

Hi there.
I'm trying to install Chatwoot with Docker, but I'm getting the following error message. I already opened the port, as for postgres. What should I do to fix it?

Error response from daemon: driver failed programming external connectivity on endpoint chatwoot-redis-1 (dd0fd9b8607b337e24e9702836aa205040f5c0cbe9f3f6aa39e565a059e72f38): Error starting userland proxy: listen tcp4 204.216.145.71:6379: bind: cannot assign requested address

### To Reproduce

Oracla Cloud with Docker, ARM

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 22.04

### Docker (if applicable)

Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:54 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:54 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by vishnu-narayanan** [comment]
@FrancisMorelli From the error, it seems like port 6379 is not available. Are you running something else on 6379?

**Comment by FrancisMorelli** [comment]
@vishnu-narayanan I was able to installed it using the image that I built. I don't know why, but I started over and it worked. Thanks.

**Comment by FrancisMorelli** [comment]
@vishnu-narayanan I was able to installed it using the image that I built. I don't know why, but I started over and it worked. Thanks.

**Comment by dougpiv** [comment]
Hi, how did you run it in Oracle ARM?
