### ISSUE TITLE
Error with CapRover Installation

### ISSUE THREAD

**Issue by FrancisMorelli** [chatwoot/chatwoot#7769]
### Describe the bug

Hi there.

I tried to install Chatwoot with CapRover, but I was not able to do so. I'm getting the following error. What should I do to fix it and make it possible to install it?

Failed: Error: {"code":1,"message":"The command '/bin/sh -c chmod +x docker/entrypoints/rails.sh' returned a non-zero code: 1"} The command '/bin/sh -c chmod +x docker/entrypoints/rails.sh' returned a non-zero code: 1

### To Reproduce

Step - Deploying chatwoot-web (might take up to a minute)

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 22.04

### Additional context

Oracle Cloud - ARM VPS

**Comment by vishnu-narayanan** [comment]
@FrancisMorelli The `arm` architecture might be causing the issue. The official images only have x86 support. Would you be able to try on an x86 machine? If not, you can try building the arm images on your end and use it with Caprover.

**Comment by FrancisMorelli** [comment]
@vishnu-narayanan I built the images and I was able to install and run using docker. I'll try with CapRover. Why don't the official image support arm? Do you know?

**Comment by vishnu-narayanan** [comment]
@FrancisMorelli We use DockerHub as a CI to build and publish official images. DockerHub does not support building ARM images at the moment. You should be able to build the images on a machine with ARM architecture and use it.

Please reopen if you are still having issues after that.
