### ISSUE TITLE
no goodput ratio 

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#7782]
### Describe the bug

Hello
I am using latest build ( v2.18.0) of chatwoot on Docker environment, On a SSL enabled domain.
As i can see all TLS connection to my chatwoot marked as no goodput ratio in pfsense firewall.
Any idea ?

### To Reproduce

Docker

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@mmojadad Can you please share the issue in detail? I'm sorry I couldn't understand what you were trying to do and what the expectation was?

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
