### ISSUE TITLE
Teams and Inboxes not consistent

### ISSUE THREAD

**Issue by xreal** [chatwoot/chatwoot#7784]
### Describe the bug

I have a freshly installed 3.0 Chatwoot instance on an new Ubuntu 20.04 (Hetzner Cloud CPX31 8GB RAM 4CPU) server.

The following problem now occurs again and again.

Created teams as well as mailboxes are not displayed in the web interface. 
However, when I query the mailboxes via API, they are available.

Most of the time the mailboxes and teams are displayed again after a certain time. However, this behaviour prevents us from putting the chat into production.

![CleanShot 2023-08-23 at 09 05 35](https://github.com/chatwoot/chatwoot/assets/1552214/9384b38d-e040-41ea-9c16-9229fe5bbf82)
![CleanShot 2023-08-23 at 09 05 47](https://github.com/chatwoot/chatwoot/assets/1552214/e11e0732-aa98-4fed-b35d-5d56f881335e)
![api](https://github.com/chatwoot/chatwoot/assets/1552214/93764ffe-2959-4ac3-9c96-9346d5fc68b7)

### To Reproduce

Freshly installed Chatwoot 3.0
Create Inbox
Wait for some time 
Created Inboxes are not showing in UI.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Macos

### Browser and version

Chrome 116

**Comment by pranavrajs** [comment]
@xreal 

1/ Can you please share if there are any errors in the browser console?
2/ Does it appear after a refresh?

**Comment by xreal** [comment]
There is no errors in logs logs (web/worker) and no errors in the browser console.
I think the problem was that i added a agent and clicked on the "Confirm my account" this opens the Browser (where i logged in with the Administrator Account).
After that, the Mailboxes in my Administrator accounts are gone.

When i cleared site data in chrome. The Mailboxes are back. 

Maybe this helps.

**Comment by pranavrajs** [comment]
@xreal Do you still face the issue? Was there a reproducible pattern?

**Comment by xreal** [comment]
I think we can close this issue. It was only one time at the registration.
