### ISSUE TITLE
Upgrading from 2.2.1 to v2.18.0 and/or 3.0.0

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#7795]
### Describe the bug

Hi

Everything goes smooth except during DB migration with the following error

While running RAILS_ENV=production bundle exec rake db:migrate
![image](https://github.com/chatwoot/chatwoot/assets/25242465/a6ffa2b4-1923-46ea-a0d6-fc096cdb2210)

![image](https://github.com/chatwoot/chatwoot/assets/25242465/69342126-20ce-40c0-b80b-3292fc7f1584)

![image](https://github.com/chatwoot/chatwoot/assets/25242465/69523137-d69e-462e-a9f5-9b78450c06fe)

Any assistance will be greatly appreciated

### To Reproduce

1) Use version 2.2.1
2) Run upgrade using cwctl or manually

### Expected behavior

DB migrate should go past successfully

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

Ubuntu 21.04

**Comment by sojan-official** [comment]
@sanjayws  Please do a sequential migration (2 versions at a time, etc) when migrating from a really old version.
