### ISSUE TITLE
Chore: Ability to serve the application css and js from CDN

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#780]
**Is your enhancement request related to a problem? Please describe.**
 Ability to serve the application css and js from cloudfron

**Describe the solution you'd like**
would like to serve the rails app assets from a CDN

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by pranavrajs** [comment]
Closing this as it is completed in #1191

**Comment by duartemvix** [comment]
> Closing this as it is completed in #1191

Chatwoot currently can't properly render all of its assets through Rails `àsset_host` configuration. I'm having broken fonts and my icons can't be rendered. Everything else, seems to be fine. Apart from ActiveStorage uploads which still can't render files aren't hosted locally. Any directions going forward around this?

This is one of the files which is not currently using Rails asset_url helpers but, rather, using a relative path.
https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/shared/assets/fonts/inter.scss#L6
