### ISSUE TITLE
I want to know how to run production mode with docker

### ISSUE THREAD

**Issue by lybtt** [chatwoot/chatwoot#781]
hi, chatwoot is very good, but it's docment may not be perfect.
I want to run production mode with docker,and I edit **RAILS_ENV=production** and **SECRET_KEY_BASE=secret** in .env, then I run docker-compose up,but it doesn't work.
What should I do?

**Comment by sojan-official** [comment]
@lybtt we are working on improving the production deployment documentation. meanwhile, You could you give it a try with caprover ? 

https://caprover.com/docs/get-started.html  

the installation takes a couple of steps and chatwoot is available as a one-click install app inside that.  

Meanwhile, if you want to debug the current error, could you post the logs?

**Comment by lybtt** [comment]
Right now, I just want to know how to run chatwoot in production mode with docker.

I follow the document, [https://www.chatwoot.com/docs/installation-guide-docker](https://www.chatwoot.com/docs/installation-guide-docker).

I already set **SECRET_KEY_BASE** and **RAILS_ENV** environment variable in my .env file and then run the below commands:

```bash
$ docker-compose -f docker-compose.production.yaml build
$ docker-compose -f docker-compose.production.yaml up
```

![image](https://user-images.githubusercontent.com/38394058/80661569-9c127d00-8ac1-11ea-9b0c-abf858a73086.png)

![image](https://user-images.githubusercontent.com/38394058/80661531-83a26280-8ac1-11ea-8261-0df1800d975f.png)

so, what should I do if I want to run chatwoot in production mode ?

**Comment by sojan-official** [comment]
@lybtt could you ensure the `.env` file contain the following value as true `RAILS_LOG_TO_STDOUT`  before running docker commands. 

There is a bug that causes docker images to fail with the environment variable is not present, This will be addressed in our upcoming release.

**Comment by lybtt** [comment]
@sojan-official after I set **RAILS_LOG_TO_STDOUT=true**, I have another problem.

![image](https://user-images.githubusercontent.com/38394058/80663453-8bb0d100-8ac6-11ea-8cd1-797f9c925825.png)


![image](https://user-images.githubusercontent.com/38394058/80663309-32e13880-8ac6-11ea-8bfd-6c37ee810707.png)

this is my .env:

```
SECRET_KEY_BASE=replace_with_your_own_secret_string
# Force all access to the app over SSL, default is set to false
FORCE_SSL=

RAILS_LOG_TO_STDOUT=true

# This lets you control new sign ups on your chatwoot installation
# true : default option, allows sign ups
# false : disables all the end points related to sign ups
# api_only: disables the UI for signup, but you can create sign ups via the account apis
ENABLE_ACCOUNT_SIGNUP=

#redis config
REDIS_URL=redis://redis:6379
# If you are using docker-compose, set this variable's value to be any string,
# which will be the password for the redis service running inside the docker-compose
# to make it secure
REDIS_PASSWORD=

# Postgres Database config variables
POSTGRES_HOST=postgres
POSTGRES_USERNAME=postgres
POSTGRES_PASSWORD=
RAILS_ENV=production
RAILS_MAX_THREADS=5

#mail
MAILER_SENDER_EMAIL=accounts@chatwoot.com
SMTP_PORT=1025
SMTP_DOMAIN=chatwoot.com
# if you are running docker-compose, set SMTP_ADDRESS value as "mailhog",
# else set the value as "localhost"
SMTP_ADDRESS=mailhog
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_AUTHENTICATION=
SMTP_ENABLE_STARTTLS_AUTO=


#misc
FRONTEND_URL=182.61.188.168:3000
ACTIVE_STORAGE_SERVICE=local

#s3
S3_BUCKET_NAME=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=

#sentry
SENTRY_DSN=

#Log settings
LOG_LEVEL=info
LOG_SIZE=500

# Credentials to access sidekiq dashboard in production
SIDEKIQ_AUTH_USERNAME=
SIDEKIQ_AUTH_PASSWORD=

### This environment variables are only required if you are setting up social media channels
#facebook 
FB_VERIFY_TOKEN=
FB_APP_SECRET=
FB_APP_ID=

#twitter
TWITTER_APP_ID=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_ENVIRONMENT=

####  This environment variables are only required in hosted version which has billing
ENABLE_BILLING=

## chargebee settings
CHARGEBEE_API_KEY=
CHARGEBEE_SITE=
CHARGEBEE_WEBHOOK_USERNAME=
CHARGEBEE_WEBHOOK_PASSWORD=
```

**Comment by pranavrajs** [comment]
@sojan-official Is this ticket still needed? I guess the issue has been merged to develop

**Comment by sojan-official** [comment]
fix for this is merged
