### ISSUE TITLE
in chatwoot sending interactive messages For Facebook

### ISSUE THREAD

**Issue by Haashimi** [chatwoot/chatwoot#7813]
### Describe the bug

i have connected facebook in box in my chatwoot account  and also that inbox i connect agent bot so my agent bot sends button messages in other inboxes such as chat interface channel , telegram channel, whatsapp channel but only facebook channel can't send button messages

### To Reproduce

i have connected facebook in box in my chatwoot account  and also that inbox i connect agent bot so my agent bot sends button messages in other inboxes such as chat interface channel , telegram channel, whatsapp channel but only facebook channel can't send button messages

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

### Operating system

linux 

### Browser and version

Chrome is up to date Version 114.0.5735.199 (Official Build) (64-bit)

```[tasklist]
### Tasks
```

**Comment by pranavrajs** [comment]
This is not support yet, we will re-open this if there is a lot of request from the community.

**Comment by Haashimi** [comment]
@pranavrajs Thanks
