### ISSUE TITLE
Bot Avatar can be changed in Super Admin Console, but changes don't reflect in chat Widget replies

### ISSUE THREAD

**Issue by Diplomat-LV** [chatwoot/chatwoot#7814]
### Describe the bug

Upon changing the Bot Avatar in Super Admin Console, previous avatar is displayed in the chat Widget replies. The new avatar picture is visible in "Super Admin Console -> Agent Bots", but chat Widget replies display the previous avatar picture.

### To Reproduce

1. Self Hosted Linux VM
2. One Bot and one Inbox to whom the bot is assigned
3. Open "Super Admin Console -> Agent Bots" and change the avatar of a bot. The new avatar picture should be visible in "Super Admin Console -> Agent Bots", but chat Widget replies should display the previous avatar picture.

### Expected behavior

New Agent Bot avatar picture is displayed in the chat Widget replies.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Microsoft Windows 10 Enterprise, Version 10.0.19045, Build 19045

### Browser and version

Firefox 116.0.3

### Additional context

The problem was first noticed after upgrading Chatwoot from v2.17.0 to v2.18.0. Currently we are using Chatwoot v3.0.0.

**Comment by pranavrajs** [comment]
@Diplomat-LV This is not supported at the moment. Please use the "Use inbox name and avatar for bot" option in the inbox settings for now.

<img width="464" alt="Screenshot 2023-09-22 at 12 52 00 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/283dcb13-7a46-4dc2-946c-0d672e7da4f3">
