### ISSUE TITLE
[CW-2458] Problems with the CDN when requesting permission from Instagram

### ISSUE THREAD

**Issue by VonJdamian** [chatwoot/chatwoot#7816]
### Describe the bug

I have been requesting the permission for instagram_manage_messages but Facebook rejects my request due to CDN

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/62c017f3-d078-4c79-90fb-d2655ca85896/e63d17dc-e841-424c-8f98-905bc74c4d21?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi82MmMwMTdmMy1kMDc4LTRjNzktOTBmYi1kMjY1NWNhODU4OTYvZTYzZDE3ZGMtZTg0MS00MjRjLThmOTgtOTA1YmM3NGM0ZDIxIiwiaWF0IjoxNjkzOTUwOTM0LCJleHAiOjE2OTQwMzczMzR9.jbKsrCetB7QdS6t2LKLJJPeg_UBP8F5_qdpN9M4f-34)

I have sent several times and they always reject me by the CDN.

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/f42d2112-6c88-4292-9515-4c5d9597b2fd/c20b9bfe-d451-4bd9-8e23-310f8a3be81e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9mNDJkMjExMi02Yzg4LTQyOTItOTUxNS00YzVkOTU5N2IyZmQvYzIwYjliZmUtZDQ1MS00YmQ5LThlMjMtMzEwZjhhM2JlODFlIiwiaWF0IjoxNjkzOTUwOTM0LCJleHAiOjE2OTQwMzczMzR9.4GqTlYF2wG_8yHrM59TmYNNrwWtGzknqH0YBQuG3HC4)

They also reject my instagram_basic use case. Does anyone have an example that they have approved?

### To Reproduce

1: Self-Hosted
2: Chatwoot version: 3
3: Facebook Review

### Expected behavior

*No response*

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

None

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2458](https://linear.app/chatwoot/issue/CW-2458/problems-with-the-cdn-when-requesting-permission-from-instagram)</sub>

**Comment by VonJdamian** [comment]
When I make a mention, it loads the image but it takes about 1 second to display, before the image is displayed, the image above appears.

**Comment by VonJdamian** [comment]
When I open the browser inspector I get this story mentions.

![image](https://github.com/chatwoot/chatwoot/assets/142674805/6d6b2de5-5aa3-4381-98bc-1c4f878064a2)

**Comment by VonJdamian** [comment]
I have written to Facebook about at what point in the review is that they reject me and this is what they replied.

![image](https://github.com/chatwoot/chatwoot/assets/142674805/6a22987f-f835-4f29-a672-97379571d884)

**Comment by pranavrajs** [comment]
@sojan-official Let us prioritize and see if we can reproduce the issue.

**Comment by sojan-official** [comment]
@muhsin-k could you help me test this if you already have an Instagram set up for the delivery reports ?

**Comment by pranavrajs** [comment]
<img width="420" alt="Screenshot 2023-10-27 at 5 23 56 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/a5b537ca-eb0c-42c3-9e81-d0b2fb513956">

UI would show this now.
