### ISSUE TITLE
[CW-2441] Search for a contact by the "Company" field

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#7818]
### Is your feature or enhancement related to a problem? Please describe.

Hi!  Finding a contact by company name would be a good feature. Currently, the search for the "Company" field is not working. Is there a company search development?

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/f6bc8147-36de-4c92-9553-79fe283f3ce6/bb613cbd-a0de-49a7-b764-bb8e3c39c308?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9mNmJjODE0Ny0zNmRlLTRjOTItOTU1My03OWZlMjgzZjNjZTYvYmI2MTNjYmQtYTBkZS00OWE3LWI3NjQtYmI4ZTNjMzljMzA4IiwiaWF0IjoxNjkzNTI0NzI1LCJleHAiOjE2OTM2MTExMjV9.Vc6_nGfZvzs0gTrTU2yR8yd03Cr0n_CM2zadu_1KK3w)

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/ad225437-f25e-4310-9991-5ba3ff68ba74/199cc75c-7847-46e9-b10a-bce163d4bd94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9hZDIyNTQzNy1mMjVlLTQzMTAtOTk5MS01YmEzZmY2OGJhNzQvMTk5Y2M3NWMtNzg0Ny00NmU5LWIxMGEtYmNlMTYzZDRiZDk0IiwiaWF0IjoxNjkzNTI0NzI1LCJleHAiOjE2OTM2MTExMjV9.WuM1ixwMOP9UXeDYax1mpllpduVaKDIYmmSls1F76kw)

### Describe the solution you'd like

When entering a value in the search field, you need to additionally search for a match in the "Company" field and display it in the list of found contacts if there is a match.

### Describe alternatives you've considered

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2441](https://linear.app/chatwoot/issue/CW-2441/search-for-a-contact-by-the-company-field)</sub>

**Comment by sojan-official** [comment]
@LiamAshdown, thanks for taking a look. Have assigned it you.
