### ISSUE TITLE
[CW-2451] Attachment thumbnails are not present in emails sent via chatwoot

### ISSUE THREAD

**Issue by vedant-k7** [chatwoot/chatwoot#7820]
### Describe the bug

I was trying chatwoot's email integration using gmail SMTP on v2.17.1
Initially I was not able to send attachments with email in the first message of conversation.
Eventually, I tried creating the later first and then sent first message separately.

The email was received successfully but it failed to load attachment thumbnails, and instead appended a link to view the attached file.

### To Reproduce

1. Configure an email channel in chatwoot and link your email using gmail SMTP.
2. Using that inbox, try to send an email, firstly the message modal doesn't have any option to link attachment in the first email.
3. After the conversation is created, try attaching jpeg/pdf or any other file format in the conversation.
4. Instead of thumbnail, a hyperlink is displayed on email conversation.

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/04454146-f530-40fb-9902-e226f91af1a1/91c14e4a-4461-4923-ad76-398fadc42cfa?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8wNDQ1NDE0Ni1mNTMwLTQwZmItOTkwMi1lMjI2ZjkxYWYxYTEvOTFjMTRlNGEtNDQ2MS00OTIzLWFkNzYtMzk4ZmFkYzQyY2ZhIiwiaWF0IjoxNjkzODM4OTU4LCJleHAiOjE2OTM5MjUzNTh9.eTVYXC3c_fgD7tLWxPWRR0olFKaoAGojQjEzAwVSbfc)

### Expected behavior

The thumbnails of attachments linked in the conversation should be displayed, Also is it possible to send attachments with the first message of the conversation?

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2451](https://linear.app/chatwoot/issue/CW-2451/attachment-thumbnails-are-not-present-in-emails-sent-via-chatwoot)</sub>

**Comment by pranavrajs** [comment]
We don't attach the attachments directly at the moment, instead it is a sent as a link. I'll add this to the feature requests.

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/7820
