### ISSUE TITLE
[Installation] Failed to fetch some archives 

### ISSUE THREAD

**Issue by pedrofnts** [chatwoot/chatwoot#7824]
### Describe the bug

I'm getting this error while trying to install Chatwoot on Ubuntu 22.04:

```
E: Failed to fetch https://deb.nodesource.com/node_16.x/pool/main/n/nodejs/nodejs_16.20.2-deb-1nodesource1_amd64>
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

Already ran apt-get update, apt-get update --fix-missing and apt-get upgrade.

Also tried on two different VPS.

### To Reproduce

sudo apt update && apt upgrade -y
init 6
wget https://get.chatwoot.app/linux/install.sh
chmod +x install.sh
./install.sh --install

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

None

### Operating system

Ubuntu 22.04

**Comment by shivamkb17** [comment]
Chatwoot Documentation clearly mention that, Chatwoot is working on ubuntu 20.04 LTS. 

Install chatwoot on 20.04 LTS.

**Comment by pedrofnts** [comment]
> Chatwoot Documentation clearly mention that, Chatwoot is working on ubuntu 20.04 LTS.
> 
> Install chatwoot on 20.04 LTS.

That had nothing to do with Ubuntu version. The problem was Nodesource temporary unavailable.

Fixed some hours later.
