### ISSUE TITLE
Website channel is not working in some case

### ISSUE THREAD

**Issue by shivamkb17** [chatwoot/chatwoot#7829]
### Describe the bug

The  Website channel incoming message not working on chatwoot with multiple agency in same chatwoot instance. 

I added the chatwoot webserver logfile. just after sending message. 

[chatwootwebserverlogfile.log](https://github.com/chatwoot/chatwoot/files/12483546/chatwootwebserverlogfile.log)

### To Reproduce

1. Install chatwoot in linux VM with the Chatwoot official installation guide.
2. Setup Chatwoot
3. Login to chatwoot
4. create website channel, (Here incoming and outgoing message works perfectly)
5. Login to Super Admin panel. 
6. Create new agency and user , and assign that agency to new user.
7. Login with newly created user
8. Now again create website channel
9. Go to codepen, and start conversation. (screenshot from website https://ibb.co/hYPtktt )
10. No any message come to the new inbox. 

### Expected behavior

Expected behaviour is to it must send and receive from newly created inbox. 

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 20.04 LTS

### Browser and version

Chrome (116.0.5845.110)

**Comment by sojan-official** [comment]
@shivamkb17  Could you add a screencast?

**Comment by shivamkb17** [comment]
@sojan-official Screenshot of agent panel or what?

In Agent panel no any message recieving in this case.

**Comment by pranavrajs** [comment]
@shivamkb17 

```
NameError (undefined local variable or method `response_sources' for #<Inbox id: 2, channel_id: 2, account_id: 2, name: "Demo 2", created_at: "2023-08-31 06:54:26.048720000 +0000", updated_at: "2023-08-31 06:54:26.048720000 +0000", channel_type: "Channel::WebWidget", enable_auto_assignment: true, greeting_enabled: false, greeting_message: "", email_address: nil, working_hours_enabled: false, out_of_office_message: nil, timezone: "UTC", enable_email_collect: true, csat_survey_enabled: false, allow_messages_after_resolved: true, auto_assignment_config: {}, lock_to_single_conversation: false, portal_id: nil, sender_name_type: "friendly", business_name: nil>):
```

This is what I can find in the error logs. It seems like you are missing the DB migrations. Please run the DB migration and it should work as usual.

**Comment by shivamkb17** [comment]
I run DB migration several times, Even Deleted DB And again migrated using  
this command 

`RAILS_ENV=production bundle exec rake db:migrate`

Also Migrate using this command:
`RAILS_ENV=production  bundle exec rails db:chatwoot_prepare`

For testing It, I again found this issues, 

Even I installed fresh chatwoot installation several times. found same issue in it.

**Comment by shivamkb17** [comment]
I think there are some issue in database migration in v3.0.0 , I also faced  similar whatsapp inbox issue in V3.0.0 , 
In the first account on which created just after installation of chatwoot. On that account, all inbox is working properly, but When I create new business Account and try to create new whatsapp inbox, Neither I am receiving message nor able to send template message to user. 

But from First created account, I can send and receive message smoothly.

**Comment by sojan-official** [comment]
@shivamkb17  do you have `response bot` fature enabled on the account in super admin ? if that's the case please disable it.
