### ISSUE TITLE
In API Channel new conversations are created with pending status instead of open

### ISSUE THREAD

**Issue by grupale** [chatwoot/chatwoot#7834]
### Describe the bug

In API Channels when I post to create a new conversation with the status = Open its created with Pending status.

### To Reproduce

New Self Hosted Installation - 3.0 version

Create a new conversation via API in API Channel as follow:

 curl --location 'https://chatwoot.domain/api/v1/accounts/1/conversations' \
--header 'Content-Type: application/json' \
--header 'api_access_token: ACCESS_TOKEN' \
--data '{
"source_id": "source_id",
"inbox_id": "inbox_id of API CHANNEL",
"contact_id": "any contact id",
"status": "open"
}

### Expected behavior

The conversation should be created with the Open status but its created with Pending status. 

![image](https://github.com/chatwoot/chatwoot/assets/10934794/9f218424-99fa-4bfa-a482-aa3293ce8728)
![image](https://github.com/chatwoot/chatwoot/assets/10934794/ac631c18-38c6-467f-90f9-e0d782476693)

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 20

### Browser and version

Google Chrome

**Comment by sojan-official** [comment]
@grupale  do you have an agent bot connected to the inbox ?

**Comment by CristianDuta** [comment]
@sojan-official Does something like this not happen when a conversation without a message is created?

@grupale I would suggest trying to create the conversation only once the first message is sent.

**Comment by grupale** [comment]
> @grupale do you have an agent bot connected to the inbox ?

Hi @sojan-official, no I havent. This is a fresh install that I'm trying before upgrading my production hosts.

This API comes from the WPPCONNECT integration for Chatwoot and its working since v2 to 2.16

**Comment by sojan-official** [comment]
@CristianDuta only if there is a bot connected to the inbox. 
ref: https://github.com/chatwoot/chatwoot/blob/9ebabb983200ff15c74d18ea5404df66f373b874/app/models/conversation.rb#L228

@grupale  please try creating a new API channel and take a look. With out any external integrations connected.

**Comment by grupale** [comment]
Hi @sojan-official I manage to solve this by creating a New api channel and deleting bots. Everything is working as expected. You can close this
