### ISSUE TITLE
Filter by Custom Attribute of the  Contacts with Problem 

### ISSUE THREAD

**Issue by JoubertVieira** [chatwoot/chatwoot#7836]
### Describe the bug

I created a custom attribute for contacts and I would like to filter by it in a certain period, but it is not filtering correctly.

![image](https://github.com/chatwoot/chatwoot/assets/25936476/57e80c36-2305-4623-ad26-9f6cc99195a9)

### To Reproduce

1) Create a custom attribute for contacts
2) Link to a contact
3) Create a filter considering the attribute
4) Filter
5) Brings the wrong information

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

v3.0.0

### Browser and version

Chrome

### Additional context

I set up chatwoot on my Linux server - Contabo

**Comment by JoubertVieira** [comment]
So there is no error but the behavior is wrong as it is not filtering correctly.

**Comment by doug-fsg** [comment]
I have the same problem. Filter returns wrong result.


contacts/filter?include_contact_inboxes=false&page=1&sort=name 500
(Internal Server Error)

**Comment by JoubertVieira** [comment]
Hello, are you need more information? How can i to resolve this? Thanks

**Comment by nicolasokumabe** [comment]
Conseguiu arrumar o problema?

**Comment by JoubertVieira** [comment]
Eu tive ajuda de um colega mas resolveu parcialmente, porque ainda não está levando em consideração a data do último movimento, Minha ideia era de que eu pudesse saber os contatos que cancelaram sua assinatura no mês de setembro por exemplo. Eu usaria um campo adicional para isso. Obrigado por perguntar. Eu espero ainda que seja resolvido por completo.

**Comment by pranavrajs** [comment]
We have identified the issue, the fix would be available soon.

**Comment by JoubertVieira** [comment]
Is this fix already available? Uow, very good
