### ISSUE TITLE
flag to deactivate automatic marking as read in a chat without answering it

### ISSUE THREAD

**Issue by facuxt** [chatwoot/chatwoot#7838]
### Is your feature or enhancement related to a problem? Please describe.

Now, when you enter a chat, it automatically mark as read the conversation. 
![image](https://github.com/chatwoot/chatwoot/assets/7550822/40c76fcb-78ec-431b-b02c-c582414150c7)

This behavior is making ur agents to ignore those chats. 

It would be nice to try replicate other onmichannel apps (like zenvia conversion). They doesnt mark as read the conversation until the agent reply to that conversation.

### Describe the solution you'd like

Maybe it would be nice to include a variable in super admin console to disable that feature.

### Describe alternatives you've considered

The other altenative should be when entering a chat (that is not assigned to any agent) is to put a button in the chat (assign to me and start chatting). Then normal behavior (maybe not so good solution).

**Comment by pranavrajs** [comment]
<img width="315" alt="Screenshot 2023-09-04 at 8 00 16 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/fbd5f7a2-ef39-4db1-88c1-099419bd75db">

There is a mark as unread option if you right click on the conversation list. You can mark as unread if you accidentally opened it. We will not be taking it up unless this is a serious concern for most of the users.

**Comment by facuxt** [comment]
yes i know about that option, but the agent has to voluntarly do that... so i guess it would be nicer to copy other omnichanel software (like zenvia) that does this behaviour (OP).
