### ISSUE TITLE
[CW-2450] When I delete an Instagram message it is not deleted in chatwoot

### ISSUE THREAD

**Issue by VonJdamian** [chatwoot/chatwoot#7850]
### Describe the bug

When I delete an Instagram message it is not reflected that it was deleted in chatwoot, this only happens when I use Instagram from the web but if I use the Instagram App from the smartphone if I delete the message in chatwoot. This is why they are canceling my review for the Instagram permit.

![](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/a58b0025-3eb6-4a12-9ab2-67a81aa5cdef/d786b7ff-328a-4d6a-b8a8-b6249277ea71?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9hNThiMDAyNS0zZWI2LTRhMTItOWFiMi02N2E4MWFhNWNkZWYvZDc4NmI3ZmYtMzI4YS00ZDZhLWI4YTgtYjYyNDkyNzdlYTcxIiwiaWF0IjoxNjkzODM3NTQ3LCJleHAiOjE2OTM5MjM5NDd9.OU6rFizZvVJEgpLjl2piaVzcr4fiwYXEEBztf_GVs2c)

### To Reproduce

1. Write a message from Instagram Web
2. Delete the message from Instagram Web
3. The message is not deleted from chatwoot

### Expected behavior

Delete the message in chatwoot

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

Browser

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

*No response*

### Additional context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2450](https://linear.app/chatwoot/issue/CW-2450/when-i-delete-an-instagram-message-it-is-not-deleted-in-chatwoot)</sub>

**Comment by pranavrajs** [comment]
@VonJdamian As far as the implementation is concerned, it should delete both the message. We will get this investigated.

**Comment by VonJdamian** [comment]
I've been searching the internet and found this:

https://developers.facebook.com/support/bugs/1995324517467115/
https://developers.facebook.com/support/bugs/837843677783959/

It also happens to other people that they delete the message from the Instagram application but from the web it does not.

**Comment by VonJdamian** [comment]
Any news with deleted messages from the web?
