### ISSUE TITLE
Integration with Asterisk PBX

### ISSUE THREAD

**Issue by physx2494** [chatwoot/chatwoot#7855]
### Is your feature or enhancement related to a problem? Please describe.

Currently, it is not possible to interface Cloud/on-prem PBXs. Chatwoot currently doesn't provide a native interface for making and receiving SIP calls to contacts. This fragments the CRM efforts as call logs, recordings are not available for the contact in Chatwoot.

### Describe the solution you'd like

Having a native Asterisk chatwoot channel connecting to a Asterisk server which is a free and open source framework for building communications applications, would open up possibilities for customer care and sales agents to further consolidate their marketing and after-sales efforts as it would enable call origination directly from Chatwoot browser. Asterisk powers a whole lot of IP PBX systems, voip gateways, conference servers, and is used by SMBs, enterprises, call centers, carriers and governments worldwide. So having this functionality will instantly provide integration to these devices present at various facilities.

### Additional context

Chatwoot could benefit from integrating the Asterisk Manager Interface (AMI), a standardized interface/API for Asterisk servers. This interface, operating over TCP, enables various functionalities like PBX control, call origination, and more.

**Comment by pranavrajs** [comment]
@physx2494 Thanks for the note. People have been requesting this for sometime. However, we are looking at building text-only support/CRM solution for now. 

Although we will have integrations with Voice/Video chat solution, we will not support an Asterisk integration in the near future. Closing this for now.
