### ISSUE TITLE
Reply to a certain message, like in WhatsApp

### ISSUE THREAD

**Issue by jhonyrdesouza** [chatwoot/chatwoot#7865]
### Is your feature or enhancement related to a problem? Please describe.

Inclusion to select and reply to a certain message, like in WhatsApp.

![pasted image 0 (1)](https://github.com/chatwoot/chatwoot/assets/58796224/9eb66a2e-5c20-4ade-950b-feec79755d2c)

### Describe the solution you'd like

Is it possible to add functionality to select a particular message and reply only to that selected message?

**Comment by muhsin-k** [comment]
Closing in favor of https://github.com/chatwoot/chatwoot/issues/6740.
