### ISSUE TITLE
Support for WhatsApp Templates that have media header and dynamic link URLs in footer

### ISSUE THREAD

**Issue by physx2494** [chatwoot/chatwoot#7878]
### Is your feature or enhancement related to a problem? Please describe.

Currently, Chatwoot only supports plain text templates with body variables. Templates with media headers or dynamic URL footers are not available.

### Describe the solution you'd like

Enable users to choose and send these media-based message templates to their customers.

### Additional context

WhatsApp offers comprehensive APIs for engaging with media-based message templates in their [documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates/).

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/6867
