### ISSUE TITLE
Can't load logger-1.min.js

### ISSUE THREAD

**Issue by arthurrferroni** [chatwoot/chatwoot#7880]
### Describe the bug

The chatwoot application on web can't load the file 
logger-1.min.js

![image](https://github.com/chatwoot/chatwoot/assets/93339779/ae497814-fa42-46cc-aa85-05b7fb8806f7)

Because this the interface are not ok, like this. And de the filter option doesn't work
![image](https://github.com/chatwoot/chatwoot/assets/93339779/0bef2eb2-0412-4fb9-a242-1e0fa2d13a9f)

### To Reproduce

VPS - ubuntu 20.04 with no firewall (all ports opened) on peramix with 4cpu and 8gb ram

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

windows

### Browser and version

chrome 116

**Comment by muhsin-k** [comment]
There is still not enough information to debug the error. Would you be able to provide more details about the issue that you are facing?
