### ISSUE TITLE
The WebSocket connection is successful, but new messages cannot be received. The page must be manually refreshed to view the messages

### ISSUE THREAD

**Issue by XindongYan** [chatwoot/chatwoot#7882]
### Describe the bug

Recently, we have noticed a delay in messages appearing for both customer support and users, even though it was working fine before. I have checked the network, and WebSocket connections are normal. I'm not sure where the issue is coming from. I am running it using Docker.

### To Reproduce

There are no reproduction steps; it happened suddenly. My version is 2.18.0.

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

**Comment by muhsin-k** [comment]
@XindongYan Is this issue occurring only with message events, or are conversation creation events working properly?

**Comment by XindongYan** [comment]
@muhsin-k  Whether I initiate a new conversation or join an existing one, I do not receive any messages.

**Comment by XindongYan** [comment]
After I restarted the service, it started working properly.
