### ISSUE TITLE
Login page translation failed pt_BR

### ISSUE THREAD

**Issue by jtayrone** [chatwoot/chatwoot#7892]
### Describe the bug

When setting the default language in .env to pt_BR and configuring the dashboard to use the default Brazilian Portuguese (pt-BR) language, the login page still remains in English.

Chatwoot version v3.0.0 develop

### To Reproduce

Set default language in .env file `pt_BR`
Choose the defined language on the user dashboard
Go to the login page.

![dashboard](https://github.com/chatwoot/chatwoot/assets/34479816/3dbe5426-4008-46d8-a362-1c01cfcc8860)

### Expected behavior

Show the login page according to the chosen language!

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Additional context

Note: I checked for the existence of translation files, and they were present, however, the login page was not translated.

The same problem persists in both the develop and master versions!

![arquivo login](https://github.com/chatwoot/chatwoot/assets/34479816/89183466-d0dd-48af-9b45-2a77197f4767)

**Comment by pranavrajs** [comment]
@jtayrone This is for the account. If you want to change the installation language, please use set DEFAULT_LOCALE=pt_BR in the environment variables.

**Comment by jtayrone** [comment]
Done! Define the .env and the login page is still in English.

![image](https://github.com/chatwoot/chatwoot/assets/34479816/81198694-0265-4db4-a92f-8cada1a1f12d)

![image](https://github.com/chatwoot/chatwoot/assets/34479816/9587c761-dfaa-4ec9-98f5-f62ebafc3511)

**Comment by marcelocaciatori** [comment]
my screen is like this too
Variable set: DEFAULT_LOCALE=pt_BR

More login screen and EN

**Comment by pranavrajs** [comment]
@marcelocaciatori @jtayrone This seems like a bug, I will get it addressed.

**Comment by mssmello** [comment]
Hi, Yes, DEFAULT_LOCALE=pt_BR all accounts are ok in pt_BR, but Login, Register and Password recover remain in English. 
I´ve already do a clear cache to redis, but nothing changed. 

Any tip?

**Comment by pranavrajs** [comment]
@mssmello This was a bug in the latest version, and it was fixed in https://github.com/chatwoot/chatwoot/pull/8002. From the next version, it should show the correct locale.

**Comment by mssmello** [comment]
Thanks!!
