### ISSUE TITLE
[CW-2487] DEFAULT_LOCALE=pt_BR in the environment variables.

### ISSUE THREAD

**Issue by marcelocaciatori** [chatwoot/chatwoot#7894]
@jtayrone This is for the account. If you want to change the installation language, please use set DEFAULT_LOCALE=pt_BR in the environment variables.

_Originally posted by @pranavrajs in https://github.com/chatwoot/chatwoot/issues/7892#issuecomment-1713781331_
            

<sub>[CW-2487](https://linear.app/chatwoot/issue/CW-2487/default-locale=pt-br-in-the-environment-variables)</sub>

**Comment by marcelocaciatori** [comment]
[](https://www.awesomescreenshot.com/video/20669628?key=7f5fd3dadcc8e8c7329f65fd796f06ac)

we are big problem screen no translation in brazil

see video is it configured correctly

**Comment by marcelocaciatori** [comment]
@pranavrajs

**Comment by marcelocaciatori** [comment]
[](https://www.awesomescreenshot.com/video/20669628?key=7f5fd3dadcc8e8c7329f65fd796f06ac)

**Comment by HermesMacedo** [comment]
configure time zone display in 24-hour format for Brazil

**Comment by marcelocaciatori** [comment]
Hello chatwoot team, we would like to request on behalf of the BRAZIL WhatsApp group, for this adjustment as quickly as possible, this is hindering sales for thousands of people who use chatwoot.
@pranavrajs
