### ISSUE TITLE
[CW-2485] Serbian translation missing

### ISSUE THREAD

**Issue by hheexx** [chatwoot/chatwoot#7897]
### Describe the bug

Serbian translation is missing from interface. (I need it for widget mostly).

When I checked the code at chatwoot/app/javascript/widget/i18n I see that Serbian translation file is present in locale directory but it is not included in index.js

### To Reproduce

/

### Environment

Docker

### Cloud Provider

None

### Platform

None

<sub>[CW-2485](https://linear.app/chatwoot/issue/CW-2485/serbian-translation-missing)</sub>

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/7905
