### ISSUE TITLE
Bug: pt-PT and pt-BR are overwritten by Crowdin

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#792]
Crowdin supports pt-PT and pt-BR while exporting the files are merged in random order.

**Comment by sojan-official** [comment]
fixed the issue in crowdin config by setting a custom code mapping for pt-BR. 
since we were using two-letter codes in integration. the pt & pt-BR was getting merged.

**Comment by sojan-official** [comment]
ref : https://support.crowdin.com/configuration-file/#language-mapping
