### ISSUE TITLE
database files are incompatible with server

### ISSUE THREAD

**Issue by sadden3194** [chatwoot/chatwoot#7927]
### Describe the bug

- database files are incompatible with server
- The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).

### To Reproduce

I am using postgres:latest docker image

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@Ghost108 Did you upgrade the Postgres Version? Can you please provide more context on the issue? We do not support Postgres 16 yet.

**Comment by vahidhashemi** [comment]
same problem here I use following docker image : 
postgres:alpine3.18

**Comment by adva-mo** [comment]
Had the same issue. Using different versions of Postgres' image helped me. changes the image to--> postgres:15

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
