### ISSUE TITLE
[CW-2520] The engine "node" is incompatible with this module. Expected version "20.x". Got "16.20.2"

### ISSUE THREAD

**Issue by nanedi** [chatwoot/chatwoot#7928]
### Describe the bug

```
yarn install v1.22.19
[1/5] Validating package.json...
error @chatwoot/chatwoot@3.1.0: The engine "node" is incompatible with this module. Expected version "20.x". Got "16.20.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### To Reproduce

1. Run `yarn`

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Additional context

I tried upgrade nodejs, use these 
```
# apt-get remove nodejs
# curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
# apt-get install -y nodejs
```

Is it necessary for me to run the following command?
```
# apt-get install gcc g++ make
# curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
# echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# sudo apt-get update && sudo apt-get install yarn
```

<sub>[CW-2520](https://linear.app/chatwoot/issue/CW-2520/the-engine-node-is-incompatible-with-this-module-expected-version-20x)</sub>

**Comment by amplitudesxd** [comment]
All you should have to do is make sure your node is on version 20. Ensure you're not using any virtual environment with an older version, or that any older versions are installed.

What is the output of `node -v`?

**Comment by nanedi** [comment]
I restored it to an earlier backup and then upgraded nodejs and everything looks fine.
```
node -v
v20.5.1
```

I tried upgrade nodejs, use these
```
# apt-get remove nodejs
# curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
# apt-get install -y nodejs
```

Is it necessary for me to run the following command?
```
# apt-get install gcc g++ make
# curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
# echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# sudo apt-get update && sudo apt-get install yarn
```

**Comment by amplitudesxd** [comment]
You shouldn't have to do that for it to work, I don't think? No harm in trying though, I guess.

**Comment by nanedi** [comment]
```
# apt-get install gcc g++ make
# curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/yarnkey.gpg >/dev/null
# echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
# sudo apt-get update && sudo apt-get install yarn
```

I didn't run them and it seems to have been successfully upgraded.

**Comment by pranavrajs** [comment]
The node version was updated to 20.x. The installer should have handled it. Upgrading the node version to 20.x and re-running the upgrade command should fix the issue. 

@vishnu-narayanan Please take a note. If the cwctl command is updated, please provide the instructions for the same.

**Comment by hoangmy92** [comment]
alpine 3.18 already includes nodejs 20.x
<img width="788" alt="image" src="https://github.com/chatwoot/chatwoot/assets/4986602/63748f96-90dd-4c43-b5b5-4a1d1ce171d6">

I think you should rebuild `chatwoot:development` for latest base image
`docker-compose build --no-cache base`

**Comment by nanedi** [comment]
@pranavrajs @vishnu-narayanan 

It is still 16.x in your document.

https://www.chatwoot.com/docs/self-hosted/deployment/requirements
`We recommend Node 16.x, as it's faster.`

====

This command `git stash` seems missing from the update section.
https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#upgrading-to-a-newer-version-of-chatwoot

```
# sudo -i -u chatwoot
# cd chatwoot
# git stash
# git checkout master && git pull
...
```

**Comment by vishnu-narayanan** [comment]
@nanedi The node version should be 20.x starting from Chatwoot version `3.1.0`. If you are still having issues, please upgrade `cwctl` and run `--upgrade`.

1.  Upgrade `cwctl` via https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#install-or-upgrade-chatwoot-cli
2. Run Chatwoot upgrade with
```
sudo cwctl --upgrade
```

> OS Ubuntu
> It is still 16.x in your document.
> https://www.chatwoot.com/docs/self-hosted/deployment/requirements

Thank you for pointing this out. We have updated the docs to reflect `v20` now.

**Comment by grupale** [comment]
Hi @sojan-official , after running

# apt-get remove nodejs
# curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
# apt-get install -y nodejs

I was able to run the cwctl --upgrade tool with no further issues

**Comment by nanedi** [comment]
I have upgraded it successfully using this.

```
# sudo -i -u chatwoot
# cd chatwoot
# git stash
# git checkout master && git pull
***
```

**Comment by nanedi** [comment]
@vishnu-narayanan 
But...
```
3.2.2 :002 > sudo cwctl --upgrade
(irb):2:in `<main>': undefined local variable or method `upgrade' for main:Object (NameError)
```

**Comment by nanedi** [comment]
@vishnu-narayanan 
```
# cp /home/chatwoot/chatwoot/deployment/chatwoot-web.1.service /etc/systemd/system/chatwoot-web.1.service
# cp /home/chatwoot/chatwoot/deployment/chatwoot-worker.1.service /etc/systemd/system/chatwoot-worker.1.service
# cp /home/chatwoot/chatwoot/deployment/chatwoot.target /etc/systemd/system/chatwoot.target
# systemctl daemon-reload
# systemctl restart chatwoot.target
```

Do I still need to run them manually?

Thank you.

**Comment by vishnu-narayanan** [comment]
@nanedi Are you upgrading everything manually? If yes, you would have to do that.

Else, just run `cwctl --upgrade`

**Comment by nanedi** [comment]
@vishnu-narayanan 

Thanks

**Comment by vishnu-narayanan** [comment]
Closing this for now. Please reopen if you are having other issues.

**Comment by jochenstu** [comment]
I am having the "same" issue, however, none of the above steps seem to work.

root@chatwoot:~# node -v
v20.7.0

then

https://gist.github.com/jochenstu/8ecae43ca9ea86148fe44a4afccbcc31
