### ISSUE TITLE
[CW-2519] Message signature duplicates on chat switch

### ISSUE THREAD

**Issue by amplitudesxd** [chatwoot/chatwoot#7929]
### Describe the bug

Every time you switch the currently selected chat, your signature duplicates.

### To Reproduce

1. Install chatwoot v3.1.0
2. Set a message signature
3. Create 2 conversations
4. Switch between them
5. See signature duplicate
![image](https://github.com/chatwoot/chatwoot/assets/62763456/e02d464a-f228-45de-b833-916ee3e73967)

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

<sub>[CW-2519](https://linear.app/chatwoot/issue/CW-2519/message-signature-duplicates-on-chat-switch)</sub>

**Comment by pranavrajs** [comment]
@scmmishra Please take a look at this issue.

**Comment by scmmishra** [comment]
@timcowlishaw thanks for reporting this, I've fixed it here: https://github.com/chatwoot/chatwoot/pull/7935
This shall be merged to the develop branch soon
