### ISSUE TITLE
[CW-2527] contact and conversation attribute filters do not work in automation;

### ISSUE THREAD

**Issue by HermesMacedo** [chatwoot/chatwoot#7931]
### Describe the bug

contact and conversation attribute filters do not work in automation;

### To Reproduce

creates any filter and especially automation, it doesn't work.

### Expected behavior

I can't filter or create automation with Conversation Attributes and Contacts and Tags.

### Environment

ChatWoor 3.0 - 3.1 | In 2.18 it worked correctly.
### Cloud Provider

Contabo VPS SSD   Debian 11 (64 Bit)
### Platform

###Browser

Opera, Firefox and Chrome
_No response_

### Additional context

@sojan-official 

<sub>[CW-2527](https://linear.app/chatwoot/issue/CW-2527/contact-and-conversation-attribute-filters-do-not-work-in-automation)</sub>

**Comment by jmelati** [comment]
Same here, with Self hosted Linux, CW 3.1.0.
The filter is not function at all.
these is a error in postgre call - ORDER BY

**Comment by javierkusse** [comment]
Hi! I have the same problem Self Hosted CW 3.1.0 contacts filter does not work. Same SQL Error.

**Comment by jmelati** [comment]
Found this errors:
https://discord.com/channels/647412545203994635/1153412218549977199

**Comment by jmelati** [comment]
Can you tell us how this Postgres request that has the ORDER BY call with problems is made (and where, by which file)? So we can try to resolve it here, until we have a definitive solution. I looked in the github files, but I didn't find where the script that accesses the DB is.
