### ISSUE TITLE
Enhancement Request: New {{conversation.id}} After Resolution in Chatwoot

### ISSUE THREAD

**Issue by macolym** [chatwoot/chatwoot#7933]
### Is your feature or enhancement related to a problem? Please describe.

Yes. Currently, when an agent resolves a conversation in Chatwoot and subsequently, the user sends a new message, the system automatically reopens the previous conversation instead of creating a new one. This can complicate tracking and organizing conversations. Agents anticipate that after closing a conversation, any new message would be addressed as a fresh query or issue, rather than continuing in the prior thread.

### Describe the solution you'd like

I would like that, once a conversation has been resolved by the agent, any new message from the user should result in the creation of a new conversation (with a new {{conversation.id}}). The only individual who should have the ability to reopen a previously resolved conversation should be the agent themselves, if deemed necessary. This clear distinction would help to avoid confusion and ensure that new user messages are always treated with due attention.

Moreover, it should be possible to configure this behavior either for each individual inbox or universally for all inboxes. I noticed that for the web chat inbox, this issue was addressed with ticket #2830, but a more granular control over this behavior can be beneficial.

### Describe alternatives you've considered

Configuration Option: An alternative solution would be to introduce an option within Chatwoot's settings that allows administrators to determine the default behavior after a message is sent in an already resolved conversation (i.e., whether it reopens the prior chat or starts a new one). This would provide flexibility for companies to tailor the system according to their preferences or desired workflow.

Regardless of the chosen approach, it's crucial to keep the user experience intuitive and ensure that any implemented change doesn't lead to confusion or additional complications for the agents.

### Additional context

![image](https://github.com/chatwoot/chatwoot/assets/115957403/434f07ce-fa42-4b96-bfd9-0bf59285262e)

**Comment by pranavrajs** [comment]
@macolym If you are on website live chat channel, please disable the option "Allow messages after resolved" to force a user to start a new conversation. On other channels, please disable the "Lock to single conversation" setting.

Please feel free to re-open this ticket if it doesn't resolve the issue.
