### ISSUE TITLE
Feature: API Channel

### ISSUE THREAD

**Issue by JijeshP** [chatwoot/chatwoot#794]
**Is your feature request related to a problem? Please describe.**
how can we create a new channel  ?

**Comment by sojan-official** [comment]
@JijeshP  at the moment we only support the default enabled channels in chatwoot.  Custom channels that can be used for API integration are on our roadmap.  

Let me know if that's the use case you are looking for.

**Comment by JijeshP** [comment]
Yes @sojan-official, option to integrate any channels using APIs and web-hooks.

**Comment by sojan-official** [comment]
@JijeshP  we will take this up for the next release.

**Comment by pranavrajs** [comment]
Duplicate #430
