### ISSUE TITLE
First message in conversation undeliverable (potentially connected with WA)

### ISSUE THREAD

**Issue by jochenstu** [chatwoot/chatwoot#7955]
### Describe the bug

When trying to start a new conversation (meaning: The first message in the entire conversation) with a WA message template, we get the following:

> Sep 21 09:45:27 chatwoot chatwoot-web.1[5403]: I, [2023-09-21T09:45:27.287617 #5403]  INFO -- : [9d578af2-0960-43e4-bd68-dd10c5c46d61] Started POST "/api/v1/accounts/1/conversations/undefined/messages" for 88.152.43.195 at 2023-09-21 09:45:27 +0000
Sep 21 09:45:27 chatwoot chatwoot-web.1[5403]: I, [2023-09-21T09:45:27.294428 #5403]  INFO -- : [9d578af2-0960-43e4-bd68-dd10c5c46d61] Processing by Api::V1::Accounts::Conversations::MessagesController#create as JSON
Sep 21 09:45:27 chatwoot chatwoot-web.1[5403]: I, [2023-09-21T09:45:27.294599 #5403]  INFO -- : [9d578af2-0960-43e4-bd68-dd10c5c46d61]   Parameters: {"private"=>"[FILTERED]", "cc_emails"=>"", "bcc_emails"=>"", "to_emails"=>"", "account_id"=>"1", "conversation_id"=>"undefined", "message"=>{"private"=>"[FILTERED]"}}
Sep 21 09:45:27 chatwoot chatwoot-web.1[5403]: I, [2023-09-21T09:45:27.313649 #5403]  INFO -- : [9d578af2-0960-43e4-bd68-dd10c5c46d61] Completed 404 Not Found in 19ms (Views: 2.0ms | ActiveRecord: 3.4ms | Allocations: 2480)

In the frontend it says:

<img width="180" alt="image" src="https://github.com/chatwoot/chatwoot/assets/1176036/1e5c37ef-9871-4c5c-9424-4a3e523055f5">

This happened after upgrading to 3.0.0. This does not happen when we are responding in a conversation, that an external user sent to us. I am also not certain, that this an isolated WA issue, since it's the only channel, we are using.

Resending does not work. Creating an internal note does not work.

I am going to try to upgrade to 3.1.0 tonight and see if that changes things, but, since I could not find an issue with a quick search, I am going to leave this here just in case.

### To Reproduce

Not certain. For us it's consistently reproducible as described above.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Linux/Ubuntu

### Browser and version

Chrome

**Comment by pranavrajs** [comment]
@jochenstu Thanks for reporting this. Can you please share the error logs if possible? It doesn't seem to be reproducible on our end.

**Comment by jochenstu** [comment]
Happy to. 

Looking at the server logs, the conversations are not masked. Is there any built in way to produce a log that I can share on here without compromising user information, that would still be useful for you? Do you have a guide for that?

**Comment by sojan-official** [comment]
@jochenstu  are you still facing this on the latest versions ?

**Comment by jochenstu** [comment]
I am not 100%, but have not received any reports no this lately, so let's say it's fixed for now, can always reopen!

**Comment by jochenstu** [comment]
Had this issue again today.

This is from the log.

`Feb 20 17:53:07 chatwoot chatwoot-web.1[3250396]: I, [2024-02-20T17:53:07.176455 #3250396]  INFO -- : [156e0f35-9535-42db-82a6-90b165e87c04] Started POST "/webhooks/whatsapp/+REDACTED" for 69.171.251.7 at 2024-02-20 17:53:07 +0000
Feb 20 17:53:07 chatwoot chatwoot-web.1[3250396]: I, [2024-02-20T17:53:07.180248 #3250396]  INFO -- : [156e0f35-9535-42db-82a6-90b165e87c04] Processing by Webhooks::WhatsappController#process_payload as */*
Feb 20 17:53:07 chatwoot chatwoot-web.1[3250396]: I, [2024-02-20T17:53:07.180558 #3250396]  INFO -- : [156e0f35-9535-42db-82a6-90b165e87c04]   Parameters: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"108306125346890", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"REDACTED", "phone_number_id"=>"REDACTED"}, "statuses"=>[{"id"=>"wamid.HBgNNDkxNzY0NTg1ODYzNhUCABEYEkRDQUQ4QkY4M0U4ODIyNEJFNwA=", "status"=>"failed", "timestamp"=>"1708451586", "recipient_id"=>"REDACTED", "errors"=>[{"code"=>131026, "title"=>"Message Undeliverable."}]}]}, "field"=>"messages"}]}], "phone_number"=>"REDACTED", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"108306125346890", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"REDACTED", "phone_number_id"=>"REDACTED"}, "statuses"=>[{"id"=>"wamid.HBgNNDkxNzY0NTg1ODYzNhUCABEYEkRDQUQ4QkY4M0U4ODIyNEJFNwA=", "status"=>"failed", "timestamp"=>"1708451586", "recipient_id"=>"REDACTED", "errors"=>[{"code"=>131026, "title"=>"Message Undeliverable."}]}]}, "field"=>"messages"}]}]}}
Feb 20 17:53:07 chatwoot chatwoot-web.1[3250396]: I, [2024-02-20T17:53:07.184337 #3250396]  INFO -- : [156e0f35-9535-42db-82a6-90b165e87c04] [ActiveJob] Enqueued Webhooks::WhatsappEventsJob (Job ID: c9aa7238-bb7a-45e6-b642-a5e646d7040d) to Sidekiq(low) with arguments: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"108306125346890", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"REDACTED", "phone_number_id"=>"REDACTED"}, "statuses"=>[{"id"=>"wamid.HBgNNDkxNzY0NTg1ODYzNhUCABEYEkRDQUQ4QkY4M0U4ODIyNEJFNwA=", "status"=>"failed", "timestamp"=>"1708451586", "recipient_id"=>"REDACTED", "errors"=>[{"code"=>131026, "title"=>"Message Undeliverable."}]}]}, "field"=>"messages"}]}], "controller"=>"webhooks/whatsapp", "action"=>"process_payload", "phone_number"=>"REDACTED", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"108306125346890", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"REDACTED", "phone_number_id"=>"REDACTED"}, "statuses"=>[{"id"=>"wamid.HBgNNDkxNzY0NTg1ODYzNhUCABEYEkRDQUQ4QkY4M0U4ODIyNEJFNwA=", "status"=>"failed", "timestamp"=>"1708451586", "recipient_id"=>"REDACTED", "errors"=>[{"code"=>131026, "title"=>"Message Undeliverable."}]}]}, "field"=>"messages"}]}]}}
`
