### ISSUE TITLE
Message never reaches the recipient

### ISSUE THREAD

**Issue by executivotelemed** [chatwoot/chatwoot#7963]
### Describe the bug

I created an instance using the integration of the Evolution API for WhatsApp with Chatwoot. The instance is set up, and I connect my number through the generated QR code. I receive all messages normally in my inbox, but when I try to reply using Chatwoot, the message never reaches the recipient.

### To Reproduce

run in a docker using easypanel to configure
version 3.1.0

### Expected behavior

the msg get recive in the whatsapp

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

win

### Browser and version

chrome

### Docker (if applicable)

easypanel

**Comment by pranavrajs** [comment]
@executivotelemed Can you please share more information on the setup? There is too little information to debug here.

1/ Do you use a webhook from Chatwoot to send messages back to the user?
2/ Have you configured the webhooks properly? Did you see the webhook events from Chatwoot on the URL configured?

**Comment by sojan-official** [comment]
@executivotelemed Please raise the issue with evolution API.
