### ISSUE TITLE
Error sending email message from contact card v3.0.0 and v3.1.0

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#7964]
### Describe the bug

The error sending an email message occurs only from the “Contact” card if you send messages in the “Conversations” section in a created conversation from the Email channel, then there is no error.

I checked on version v3.0.0, same error
I checked on version v2.18.0 there is no error, everything is sent correctly.

There is an error in the console: 
<img width="1442" alt="Screenshot 2023-09-22 at 09 59 43" src="https://github.com/chatwoot/chatwoot/assets/57803974/f7de7823-a006-4efc-b6aa-deca6d48a969">

### To Reproduce

1. I go to the "Contacts" section
2. From a contact card that has an email address
3. I'm creating a new conversation
4. I select a channel to send "Email"
5. Fill in the subject and text of the message
6. I click on the "Send message" button, a modal window "Couldn't send, try again" appears

### Expected behavior

Sending a message when creating a dialogue from the Email channel should be without errors, the email is sent to the contact.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

Safari 16.4

### Docker (if applicable)

Docker version 23.0.6, build ef23cbc
Docker Compose version v2.2.2

**Comment by pranavrajs** [comment]
@aerostovtsev This seems like you have enabled the response_bot feature without running the migrations required for it. Can you please turn off the feature from super-admin console? It should work without any issues.

**Comment by aerostovtsev** [comment]
That's right, I turned off "response bot", now an email message is sent.
thank you!
