### ISSUE TITLE
Help Center missing from sidebar

### ISSUE THREAD

**Issue by Chipzstar** [chatwoot/chatwoot#7971]
### Describe the bug

Can't see the help center menu option in chatwoot dashboard

### To Reproduce

1. Create an account on chatwoot
2. Enroll on the Hacker plan 

### Expected behavior

Expected to see the Help Center menu option in the sidebar as shown in the docs

![chatwoot-help-center-example](https://github.com/chatwoot/chatwoot/assets/15787864/c9c1550e-a7dc-47c6-860d-2112f26adda4)

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows OS

### Browser and version

Google Chrome (Version 116.0.5845.188)

### Additional context

![chatwoot-no-help-center-option](https://github.com/chatwoot/chatwoot/assets/15787864/84f3e51a-cb62-4957-bc33-0314e37b2891)

**Comment by pranavrajs** [comment]
@Chipzstar This is only available in the paid plans. Please reach out in the app-support for Chatwoot cloud queries.
