### ISSUE TITLE
Average First Time Response

### ISSUE THREAD

**Issue by Parnia-Varzdar** [chatwoot/chatwoot#7978]
### Is your feature or enhancement related to a problem? Please describe.

![Screenshot from 2023-09-25 17-34-36](https://github.com/chatwoot/chatwoot/assets/112281951/8d6d382d-2e20-4f82-adeb-c62dbd9936fb)

In this photo, as you can see, the number of assigned conversations is zero, but the average first response time has value, what is the problem?

### Describe the solution you'd like

very complete and fluent

**Comment by pranavrajs** [comment]
@Parnia-Varzdar This is possible scenario. If the agent has replied to a conversation that is not assigned to them, then the response rate would be calculated against them. Can you please confirm if the agents are assigning the conversations themselves before replying?
