### ISSUE TITLE
Albanian Language

### ISSUE THREAD

**Issue by erosai** [chatwoot/chatwoot#7989]
### Is your feature or enhancement related to a problem? Please describe.

I would like a new language to be added to Crowdin.

### Describe the solution you'd like

Kindly ask you to add the Albanian language to Crowdin.

### Describe alternatives you've considered

No response

### Additional context

No response

**Comment by pranavrajs** [comment]
Added it here 👍 

https://translate.chatwoot.com/chatwoot/sq

https://translate.chatwoot.com/chatwoot-mobile-app/sq
