### ISSUE TITLE
Presence/availability goes back to online after setting offline

### ISSUE THREAD

**Issue by marcelstoer** [chatwoot/chatwoot#7992]
### Describe the bug

This is a replication of https://discord.com/channels/647412545203994635/1156214624136470638/1156214624136470638 where @sojan-official suggested to track this in an issue.

I am helping out debugging an issue with the availability status on a self-hosted Docker-based installation.

There is a certain configuration, set of constraints or maybe race conditions that lead to presence/availability going back to online after setting it offline.

I captured the sequence of events I observed in the attached sequence diagram. I can't know for sure how the Chatwoot backend interacts with Redis and Postgres. So far, I haven't been given access to the database of an environment that shows the faulty behavior. 
However, what I want to monitor is `USERS.availability` and  `ACCOUNT_USERS.availability` as well as their respective `updated_at` timestamps. On other systems I noticed that only `ACCOUNT_USERS.availability` is updated with the new status when I change the availability in the user profile.

<img width="185" alt="Screenshot_2023-09-26_at_14 54 08" src="https://github.com/chatwoot/chatwoot/assets/624195/b2b2e8e6-7a7e-4c67-8b3b-efc8009dfd09">
<img width="297" alt="Screenshot_2023-09-26_at_14 52 22" src="https://github.com/chatwoot/chatwoot/assets/624195/57e126ac-12fb-4d71-9e66-6fcb2b27cb45">

### To Reproduce

The issue is only reproducible on certain installations. What sets those apart from the others we don't know yet.

- agents sets herself offline through the "Profile settings" context menu (see attachment)
- availability goes from green to gray i.e. she's offline
- OPTIONAL she navigates to some other page (reproducible with and without this step)
- after a few seconds her availability goes back to green

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Additional context

References/hints I found, they sound relevant:

- https://github.com/chatwoot/chatwoot/issues/3504#issuecomment-988702709
- https://github.com/chatwoot/chatwoot/issues/7439#issuecomment-1679594085

**Comment by marcelstoer** [comment]
I was able to query the Postgres database `USERS.availability` and `ACCOUNT_USERS.availability` in an environment and a user where this issue is reproducible using the following query.

```sql
SELECT u.name,
       u.display_name,
       u.email,
       CASE u.availability
         WHEN 0 THEN 'online'
         WHEN 1 THEN 'offline'
       END AS user_availability,
       u.updated_at  AS user_updated_at,
       CASE au.availability
         WHEN 0 THEN 'online'
         WHEN 1 THEN 'offline'
       END AS account_users_availability,
       au.updated_at AS account_users_updated_at
FROM   users u,
       account_users au
WHERE  u.id = au.user_id
```

We saw that `USERS.availability` remained `online` the whole time. I don't understand what this represents but it's the same value for all users. `ACCOUNT_USERS.availability`, however, was correctly set to `offline` (through `POST /api/v1/profile/availability` I guess). 

Yet, the websocket action `update_presence` returned `online`. This is the situation documented in the sequence diagram above.

Any ideas what might cause this?

**Comment by LiamAshdown** [comment]
Interesting.

I will have a look at this tonight.

**Comment by CristianDuta** [comment]
An inconsistent online status issue was observed, linked to Redis key management. Specific keys related to online status, such as alfred:ONLINE_PRESENCE::1::USERS and alfred:ONLINE_STATUS::1, were identified. 

A comparison between environments revealed a missing key alfred:ONLINE_STATUS::1 in one environment, which reappeared post Redis restart, resolving the issue. It's suspected that over time, Redis might be losing or removing these keys, possibly due to configurations or space limitations.

Does anyone know how these keys are managed in Chatwoot? What can be causing the key to disapear?

**Comment by marcelstoer** [comment]
As suspected it turned out to be a configuration issue on some of the environments.

Redis was set to `maxmemory-policy = noeviction` for some reason which resulted in presence updates not being persisted after some time (persisted in Postgres but not in Redis). Setting it to `allkeys-lru` fixed this issue.

**Comment by kubre** [comment]
> As suspected it turned out to be a configuration issue on some of the environments.
> 
> Redis was set to `maxmemory-policy = noeviction` for some reason which resulted in presence updates not being persisted after some time (persisted in Postgres but not in Redis). Setting it to `allkeys-lru` fixed this issue.

Still facing this issue after week or so
