### ISSUE TITLE
[CW-2672] Disable OpenAI Label Suggestion on a Per-Feature Basis

### ISSUE THREAD

**Issue by jmelati** [chatwoot/chatwoot#7996]
### Is your feature or enhancement related to a problem? Please describe.

I would like to request the implementation of a configuration option that allows users to choose whether the system will call OpenAI to suggest LABELS. Currently, I receive around 2000 calls every day, and the label suggestion feature is consuming a significant amount of API usage. To optimize API consumption, I suggest adding a configuration button to enable or disable the OpenAI label suggestion function.

### Describe the solution you'd like

Introduce a configuration option or environment variable that users can set to enable or disable the OpenAI label suggestion feature. This way, users can customize their API usage based on their specific needs.

### Describe alternatives you've considered

I want to utilize OpenAI's functions such as summarize and others without using the label suggestion feature. However, the current setup does not provide the flexibility to disable label suggestions on a per-feature basis.

### Additional context

At present, it is not possible to disable label suggestions for specific features, and having a per-feature toggle would greatly enhance the usability of the OpenAI API. This could potentially be implemented as an environment variable to offer users more control over the API behavior.

Feel free to discuss and contribute to this feature request. Your feedback and support are highly appreciated.

Additional Notes
In addition to the feature request, it would be immensely helpful to include a reporting mechanism that allows users to track the count of API calls. This reporting feature could provide users with insights into their API usage, aiding in better management and understanding of their consumption patterns.

Proposed Reporting Feature
API Usage Count: Display the total number of API calls made within a specified time frame.

Usage Breakdown by Feature: Provide a breakdown of API usage across different features (e.g., summarize, label suggestion).

Customizable Reporting Periods: Allow users to specify the reporting period, enabling them to analyze usage trends over days, weeks, or custom time intervals.

API Consumption Trends: Visualize the historical trend of API consumption, helping users identify peak usage periods.

Use Case
By having access to detailed API usage reports, users can make informed decisions about feature utilization and resource allocation. This reporting feature would empower users to optimize their OpenAI API consumption based on their application's requirements and budget constraints.

Implementation Considerations
Implementing a reporting feature might involve the introduction of additional API endpoints or integration with existing OpenAI API endpoints that provide usage statistics. Users could then retrieve these statistics programmatically or through a dedicated user interface.

How to Access Reports
Specify any proposed methods or endpoints through which users can access the API usage reports.

Feedback Encouraged
Community feedback on the proposed reporting feature is encouraged. Users can share their thoughts on the usefulness of such reports and suggest additional metrics or functionalities that would enhance the reporting feature.

<sub>[CW-2672](https://linear.app/chatwoot/issue/CW-2672/disable-openai-label-suggestion-on-a-per-feature-basis)</sub>

**Comment by jmelati** [comment]
Today has no agents in office. No work in chatwoot. And this happen:
![image](https://github.com/chatwoot/chatwoot/assets/88042866/ffd59b1c-aea5-4029-93df-d12ad35e5aa4)

There is a way to disable or log this feature?

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/8374. Please update to the latest version 3.3.1
