### ISSUE TITLE
Allow customizing "reply" name in reply-to email

### ISSUE THREAD

**Issue by panta82** [chatwoot/chatwoot#8005]
### Is your feature or enhancement related to a problem? Please describe.

I want to route email replies via my postmark inbound email address, which is something like `xyz@inbound.postmarkapp.com`.

Chatwoot currently only allows reply addresses like `reply+abc@my-domain.com`.

So I would like to be able to set: `xyz+abc@inbound.postmarkapp.com`.

### Describe the solution you'd like

![image](https://github.com/chatwoot/chatwoot/assets/4291324/b49295f1-b2e1-4ede-b4e7-b53b62736ce2)

Make the "reply" part here customizable via settings.

### Describe alternatives you've considered

Setting up a whole new domain and using cloudflare workers to redirect to postmark. Flaky, not sure it'd work, and I don't have spare domains laying around.

**Comment by pranavrajs** [comment]
@panta82 Thanks for the suggestion. However, including a configuration here is not essential for regular users and does not provide significant value. This is a core piece of the application. Adding more configuration there makes it confusing. We would not support this. If you need to make the necessary change, you can fork the repository.
