### ISSUE TITLE
Company Variable Password Reset Screen

### ISSUE THREAD

**Issue by marcelocaciatori** [chatwoot/chatwoot#8021]
### Is your feature or enhancement related to a problem? Please describe.

on the user password reset screen, add a variable to get Brand Name instead of the ChatWoot name

### Describe the solution you'd like

Show company name on password reset screen

![image](https://github.com/chatwoot/chatwoot/assets/91642837/797146c1-8bdc-4b6b-a8d1-d472b3bb047a)

### Describe alternatives you've considered

```bash
"DESCRIPTION": "Enter the email address you use to log in to ['BRAND_NAME'] to get the password reset instructions.",
```

### Additional context

Additional improvements

**Comment by pranavrajs** [comment]
Closing this as we will not support this. You can create a fork if needed.
