### ISSUE TITLE
When a new admin user is created, the qr code does not generate

### ISSUE THREAD

**Issue by Daan2022** [chatwoot/chatwoot#8025]
### Describe the bug

When a new admin user is created, the qr code does not generate. using the evolution api, the box is created within chatwoot, the instance is created in the api, but within chatwoot the qrcode is not generated.

### To Reproduce

When a new admin user is created, the qr code does not generate. using the evolution api, the box is created within chatwoot, the instance is created in the api, but within chatwoot the qrcode is not generated.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

ubuntu 22

**Comment by sojan-official** [comment]
@Daan2022 Evolution API is not an official product from the Chatwoot team. Please raise the issue on their repo instead.
