### ISSUE TITLE
I can't install Chatwoot via script

### ISSUE THREAD

**Issue by Sollydus** [chatwoot/chatwoot#8026]
### Describe the bug

```
Compiling...
Compilation failed:
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($num, $num * 0 + 1) or calc($num / ($num * 0 + 1))

More info and automated migrator: https://sass-lang.com/d/slash-div
[...]
```

### To Reproduce

1. apt updade && apt upgrade -y
2. wget https://get.chatwoot.app/linux/install.sh
3. ./install.sh --install

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 20.04 LTS

**Comment by pranavrajs** [comment]
@Sollydus, Can you please share the specs of the machine? Please see if it matches this. https://www.chatwoot.com/docs/self-hosted/deployment/requirements

**Comment by Sollydus** [comment]
> @Sollydus, Você pode compartilhar as especificações da máquina? Por favor, veja se corresponde a isso. https://www.chatwoot.com/docs/self-hosted/deployment/requirements

I discovered the problem, it was because I was using an AMD processor, I installed it from scratch again using Intel and compiled it successfully
