### ISSUE TITLE
Web widget not updating 

### ISSUE THREAD

**Issue by rnehrboss** [chatwoot/chatwoot#8027]
### Describe the bug

I changed the widget bubble to expanded bubble, but it doesn't change.  Also tried to move from left to right and it didn't change.   
Any suggestions?

### To Reproduce

Update widget.

### Expected behavior

Widget should change when updated.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 20

**Comment by rnehrboss** [comment]
Solved.  If it helps anyone, when using wordpress, the bottom settings on the widget builder only are affected by changing them in the wordpress plugin.

**Comment by pranavrajs** [comment]
Closing this issue here as the config needs to be updated in the wordpress plugin settings.
