### ISSUE TITLE
Pre chat message placeholder

### ISSUE THREAD

**Issue by supervard23** [chatwoot/chatwoot#8028]
### Describe the bug

The placeholder for the pre chat message in Swedish is wrong (it's talking about name instead of message).
I have suggested the right translation here: https://chatwoot.crowdin.com/translate/fbb5808ca57a3143c45072c55b94eb2f/all/en-sv/8?filter=basic&value=0#q=v%C3%A4nligen%20ange%20dit%20fullst%C3%A4ndiga%20namn

Hopefully this can be updated in the next release.

### To Reproduce

.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@supervard23 Closing this as the translation is already updated in the code base.
<img width="344" alt="Screenshot 2023-10-24 at 12 32 11 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/3b09e532-ea31-49d4-97a9-3649e5286d03">
