### ISSUE TITLE
[CANNED RESPONSES] Every new line is like a new Paragraph

### ISSUE THREAD

**Issue by facuxt** [chatwoot/chatwoot#8036]
### Describe the bug

Everytime we do enter or Ctrl+enter in canned response, it enters a new line in the database... then when the message is sent is interpreted as new paragraph, so every enter in the editor looks like this in whatsapp.

![image](https://github.com/chatwoot/chatwoot/assets/7550822/2f2b849c-780e-4ea0-bba1-bca9bf52f9f2)

A minor extra bug, is that double enter is not saved, it just save one new line.

What you see in the capture, should be sent like this.
![image](https://github.com/chatwoot/chatwoot/assets/7550822/535d3b85-6965-4cdd-9be0-a426ed623329)

### To Reproduce

1. Enter in canned responses.
2. add a new response
3. just do some enters to break some lines, press two enters in one line to make a blank line
4. save
5. send it via whatsapp.

### Expected behavior

it should look like this.
![image](https://github.com/chatwoot/chatwoot/assets/7550822/5ce92bc5-50f0-40df-9f59-f289e559ec67)

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Chrome Versión 117.0.5938.132 (Build oficial) (64 bits)

**Comment by pranavrajs** [comment]
@facuxt We follow standard Markdown rendering. Please use `Shift+Enter` if you need the text to be in the next line than a paragraph. Please feel free to reopen the issue if it is not the case.
