### ISSUE TITLE
[CW-2662] Sort Conversations by Creation Date for Fair Client Handling

### ISSUE THREAD

**Issue by macolym** [chatwoot/chatwoot#8049]
### Is your feature or enhancement related to a problem? Please describe.

On the Chatwoot web platform, the user's chosen conversation sort preference doesn't persist. Every time a user logs in or refreshes the page, the sorting defaults to the system's setting, requiring the user to manually set their preferred sort order again. In contrast, the mobile version retains this preference, providing a more seamless experience.

### Describe the solution you'd like

1. User Preference Storage: Implement a mechanism to store the user's sorting preference either as a browser cookie or in the user's profile settings on the server side.
2. Consistency across Platforms: Ensure that the behavior on the web platform matches the mobile platform, where the sort preference is retained.
3. Default to User Preference: Whenever a user logs in or navigates within the Chatwoot web platform, conversations should be sorted based on the user's last chosen preference.
4. Modification in ChatList.vue: Change the default sorting mechanism of conversations to CREATED_AT. This can be done by updating the file chatwoot/app/javascript/dashboard/components/ChatList.vue on line 276 from activeSortBy: wootConstants.SORT_BY_TYPE.LATEST to use the appropriate constant that represents creation date.
5. By making this change, conversations will be presented in the order they were initiated, ensuring that agents address client queries in a first-come-first-serve basis, which is a fairer approach.

### Describe alternatives you've considered

While there might be certain scenarios where picking up the latest conversations can be beneficial, it would be ideal to give administrators the option to choose the sorting mechanism based on their operational preferences. This provides flexibility while ensuring that the default behavior is set to a fair approach.

### Additional context

For a support platform, it's vital to ensure that every client feels valued. Addressing conversations based on their creation date ensures that no client is left waiting unduly, improving overall client satisfaction and trust in the support process.

![order_by](https://github.com/chatwoot/chatwoot/assets/115957403/14422ae4-8768-4cdc-8e8c-a9b8c3d3a9db)

<sub>[CW-2662](https://linear.app/chatwoot/issue/CW-2662/sort-conversations-by-creation-date-for-fair-client-handling)</sub>

**Comment by pranavrajs** [comment]
@macolym Thanks for the feedback. We will pick it up in the next sprint. @iamsivin Please see if you can work on this in the next sprint.
