### ISSUE TITLE
Verification emails won't send

### ISSUE THREAD

**Issue by softshape** [chatwoot/chatwoot#8064]
### Describe the bug

We don't have email inboxes yet. But Chatwoot still needs to send verification emails. Is https://www.chatwoot.com/docs/product/channels/email/configure-smtp/ valid to setup Chatwoot for sending verification emails also?

### To Reproduce

-

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@softshape Can you please share the server error logs, without which we cannot help?

**Comment by pranavrajs** [comment]
If you have not setup ENV variables as described [here](https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables/#configure-emails), please set it up.

**Comment by mredodos** [comment]
i had set the env variables but i had same problem side kick report Mail::Sendmail::DeliveryError: Delivery failed with exitstatus 1: "/usr/sbin/sendmail -i -f \"accounts@chatwoot.com\" -- \"xxxx@aifb.ch\""

**Comment by pranavrajs** [comment]
@mredodos Please check if you have configured MAILER_SENDER_EMAIL. If not, please configure it. Otherwise, please share a sample env file where we can reproduce the issue. Closing this here for now.

**Comment by mredodos** [comment]
> @mredodos Please check if you have configured MAILER_SENDER_EMAIL. If not, please configure it. Otherwise, please share a sample env file where we can reproduce the issue. Closing this here for now.

I have setball the staff in documentation and in other opened or closed issue, i have restart the systems i lost 15 hour of sleep for try without success.

All time chatwoot try to send the sustem email via default/fallback account

**Comment by mredodos** [comment]
@pranavrajs it seems ignore the settings from rails console is al set correctly but chatwoot ignore all the setting
