### ISSUE TITLE
Hetzner IMAP Mail Problem: AUTHENTICATE mechanism not supported, mate

### ISSUE THREAD

**Issue by Lyra1337** [chatwoot/chatwoot#8065]
Hi chatwoot team,
I'm running the current docker version of chatwoot and want to add inbound mails.

I tired to configure chatwoot by using a mailbox in our exchange online account, but I wasn't able to select 'Microsoft' in the E-Mail provider setup process (there is no documentation on how to add it neither).

So i went the route and ordered a new webspace with mail support and a dedicated domain for chatwoot. Outgoing mails work fine with my SMTP setup. But the inbound mails does not work.

Here is the log:

`{"ts":"2023-10-06T14:21:07.700Z","pid":1,"tid":"5hdl","lvl":"INFO","msg":"start","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"880a6fa9e89943c6c7ed80e3"}}
I, [2023-10-06T14:21:07.700397 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [9322f1ef-f3bb-43a1-bbfa-6eeecc28322e] Enqueued Inboxes::FetchImapEmailsJob (Job ID: e44fe403-433d-417d-914c-29c19797cb4b) to Sidekiq(scheduled_jobs) with arguments: #<GlobalID:0x00007fc9f382bdf0 @uri=#<URI::GID gid://chatwoot/Channel::Email/7>>
I, [2023-10-06T14:21:07.701650 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailInboxesJob] [9322f1ef-f3bb-43a1-bbfa-6eeecc28322e] Performed Inboxes::FetchImapEmailInboxesJob (Job ID: 9322f1ef-f3bb-43a1-bbfa-6eeecc28322e) from Sidekiq(scheduled_jobs) in 8.33ms
{"ts":"2023-10-06T14:21:07.702Z","pid":1,"tid":"5h2h","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailInboxesJob","jid":"af5588db4ddc8fced8e2d256","elapsed":0.01}}
I, [2023-10-06T14:21:07.703749 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [e44fe403-433d-417d-914c-29c19797cb4b] Performing Inboxes::FetchImapEmailsJob (Job ID: e44fe403-433d-417d-914c-29c19797cb4b) from Sidekiq(scheduled_jobs) enqueued at 2023-10-06T14:21:07Z with arguments: #<GlobalID:0x00007fc9f3823a60 @uri=#<URI::GID gid://chatwoot/Channel::Email/7>>
E, [2023-10-06T14:21:07.815549 #1] ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [e44fe403-433d-417d-914c-29c19797cb4b] AUTHENTICATE mechanism not supported, mate
I, [2023-10-06T14:21:07.815846 #1]  INFO -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [e44fe403-433d-417d-914c-29c19797cb4b] Performed Inboxes::FetchImapEmailsJob (Job ID: e44fe403-433d-417d-914c-29c19797cb4b) from Sidekiq(scheduled_jobs) in 114.91ms
{"ts":"2023-10-06T14:21:07.816Z","pid":1,"tid":"5hdl","lvl":"INFO","msg":"done","ctx":{"class":"Inboxes::FetchImapEmailsJob","jid":"880a6fa9e89943c6c7ed80e3","elapsed":0.116}}`

This line contains the error description:

`E, [2023-10-06T14:21:07.815549 #1] ERROR -- : [ActiveJob] [Inboxes::FetchImapEmailsJob] [e44fe403-433d-417d-914c-29c19797cb4b] AUTHENTICATE mechanism not supported, mate`

![image](https://github.com/chatwoot/chatwoot/assets/8735461/be65cf5f-98c3-48f7-8d83-734730fcbb1d)

PS: The Setup process of an E-Mail inbox in chatwoot is also weird. In the first step you add a name of the inbox and the e-mail address. But then chatwoot creates an <hash>@my-domain.ext e-mail address?

Thank you in advance. ♥

### To Reproduce

1. Install Chatwoot
2. Configure Environment Variables
3. Add Inbox
4. Use a hetzner.de mail account
5. IMAP will fail

### Expected behavior

IMAP works

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 22.04 + docker ce

### Browser and version

latest Firefox

### Docker (if applicable)

docker version:
`
  Client: Docker Engine - Community
   Version:           24.0.6
   API version:       1.43
   Go version:        go1.20.7
   Git commit:        ed223bc
   Built:             Mon Sep  4 12:31:44 2023
   OS/Arch:           linux/amd64
   Context:           default
  
  Server: Docker Engine - Community
   Engine:
    Version:          24.0.6
    API version:      1.43 (minimum version 1.12)
    Go version:       go1.20.7
    Git commit:       1a79695
    Built:            Mon Sep  4 12:31:44 2023
    OS/Arch:          linux/amd64
    Experimental:     false
   containerd:
    Version:          1.6.24
    GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
   runc:
    Version:          1.1.9
    GitCommit:        v1.1.9-0-gccaecfc
   docker-init:
    Version:          0.19.0
    GitCommit:        de40ad0
`

docker info:
`
  Client: Docker Engine - Community
   Version:    24.0.6
   Context:    default
   Debug Mode: false
   Plugins:
    buildx: Docker Buildx (Docker Inc.)
      Version:  v0.11.2
      Path:     /usr/libexec/docker/cli-plugins/docker-buildx
    compose: Docker Compose (Docker Inc.)
      Version:  v2.21.0
      Path:     /usr/libexec/docker/cli-plugins/docker-compose
  
  Server:
   Containers: 6
    Running: 5
    Paused: 0
    Stopped: 1
   Images: 7
   Server Version: 24.0.6
   Storage Driver: overlay2
    Backing Filesystem: extfs
    Supports d_type: true
    Using metacopy: false
    Native Overlay Diff: true
    userxattr: false
   Logging Driver: json-file
   Cgroup Driver: systemd
   Cgroup Version: 2
   Plugins:
    Volume: local
    Network: bridge host ipvlan macvlan null overlay
    Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
   Swarm: inactive
   Runtimes: runc io.containerd.runc.v2
   Default Runtime: runc
   Init Binary: docker-init
   containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
   runc version: v1.1.9-0-gccaecfc
   init version: de40ad0
   Security Options:
    apparmor
    seccomp
     Profile: builtin
    cgroupns
   Kernel Version: 5.15.0-79-generic
   Operating System: Ubuntu 22.04.3 LTS
   OSType: linux
   Architecture: x86_64
   CPUs: 3
   Total Memory: 3.726GiB
   Name: ubuntu-chatwoot
   ID: 87fc5b4e-bf14-49c3-a454-f2dab52d6f37
   Docker Root Dir: /var/lib/docker
   Debug Mode: false
   Experimental: false
   Insecure Registries:
    127.0.0.0/8
   Live Restore Enabled: false
`

docker-compose version:
`
  docker-compose version 1.29.2, build unknown
  docker-py version: <module 'docker.version' from '/usr/local/lib/python3.10/dist-packages/docker/version.py'>
  CPython version: 3.10.12
  OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
`

**Comment by pranavrajs** [comment]
@Lyra1337 For Microsoft Emails, you would have to setup an Azure app as described in the document below. SMTP basic auth is deprecated by Microsoft. https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup

**Comment by vagner-dias** [comment]
> @Lyra1337 For Microsoft Emails, you would have to setup an Azure app as described in the document below. SMTP basic auth is deprecated by Microsoft. https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup

Hello, @pranavrajs ,

About the **hetzner issue** @Lyra1337 described. Is there a workaround for that ?
