### ISSUE TITLE
Message response function with problems REPLY

### ISSUE THREAD

**Issue by marcelocaciatori** [chatwoot/chatwoot#8071]
### Describe the bug

https://github.com/chatwoot/chatwoot/assets/91642837/2dc797d7-2342-4edb-9eed-bfb1fe018b90

We simulate the message being answered and it does not appear as answered

@pa

### To Reproduce

1 Access Chatwoot
2 Reply to a message

### Expected behavior

Reply selected answer

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 22.04

**Comment by pranavrajs** [comment]
@marcelocaciatori This is a work in progress, the feature will be available once it is complete.
