### ISSUE TITLE
Old chat is remembered even after deleting or exiting it

### ISSUE THREAD

**Issue by adrianwix** [chatwoot/chatwoot#8101]
### Describe the bug

Even if as an admin I delete the chat or the user clicks "exit chat" the chat is still there even after refreshing

<img width="423" alt="image" src="https://github.com/chatwoot/chatwoot/assets/37629556/ea52787e-90cf-4452-a23a-b52bde1e80dd">

### To Reproduce

1. Start a chat
2. Exit it
3. Refresh the page
4. Chat is still there

------
1. Start a chat
2. Delete it as an admin
3. Refresh the page of the user using the widget
4. Chat is still there

### Expected behavior

I should be prompted to start a new conversation

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@adrianwix Can you please try disabling this option in the inbox settings? It would be resolved afterwards.


<img width="506" alt="Screenshot 2023-10-17 at 5 14 12 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/c5fd7d8f-71b2-4240-bc55-a182670e18a2">

**Comment by pranavrajs** [comment]
Please feel free to re-open if it is not the case.
