### ISSUE TITLE
Webhook when answering CSAT

### ISSUE THREAD

**Issue by arthurbarret0** [chatwoot/chatwoot#8114]
### Is your feature or enhancement related to a problem? Please describe.

It would be interesting to have a webhook for when receiving a response to the CSAT survey. This way, we can automate contact with the user whenever we receive a poor rating, allowing us to address the situation and resolve the user's dissatisfaction.

### Describe the solution you'd like

In "Webhooks," there should be the option to input an endpoint that will receive a request whenever a user responds to the CSAT survey, and in the request body, it should contain the conversation_id, the user's response (good, bad, etc), and other relevant information related to the conversation.

### Describe alternatives you've considered

Discontinue the use of Chatwoot's CSAT and use one that I can automate the handling process, such as https://survicate.com/

**Comment by pranavrajs** [comment]
@arthurbarret0 You can listen to the message_updated event to get the updates on CSAT survey update. You will see the following JSON structure in the payload.


<img width="293" alt="Screenshot 2023-10-17 at 5 12 16 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/3b4e5c09-16a6-4af8-ae6e-2a62bcf26db9">
