### ISSUE TITLE
Cannot save Auto-send greeting messages 

### ISSUE THREAD

**Issue by Eugenia9117** [chatwoot/chatwoot#8139]
### Describe the bug

After I write Auto-send greeting message in the field and try to save it, there is a message “Greeting message is too long (maximum is 255 characters)”, although I typed 234 of them.

### To Reproduce

1. Go to inboxes
2. Scroll to the Auto-send greeting messages 
3. Compose message with 230 symbols for example
4. Try saving it

### Expected behavior

Auto-send greeting messages  is saved correctly without mistakes, allowing to save at least 255 symbols.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows

### Browser and version

Last version of Chrome

**Comment by pranavrajs** [comment]
@Eugenia9117 It seems like you are on an older version of Chatwoot. Please upgrade to the latest version. This issue has been fixed already, and you can write up to 10000 characters now.
