### ISSUE TITLE
[CW-2664] Canned responses are not working

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#8142]
### Describe the bug

We have some canned responses configured, however, after typing **/** in the message window, these responses are not available anymore.

We are using the docker installation.

### To Reproduce

(Docker Installation)

1. Create some canned responses
2. Go to the message window
3. Type /
Nothin happens

### Expected behavior

After typing / in the message window, a list should appear over the messagebox showing the possible canned responses.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome - 117.0.5938.149

### Docker (if applicable)

**docker version**
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~22.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       24.0.5-0ubuntu1~22.04.1
  Built:            Mon Aug 21 19:50:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

**docker info**
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 11
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-86-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.726GiB
 Name: docker01
 ID: 36dce6aa-6541-4e48-81fe-4348ac85af70
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**docker-compose version**
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

<sub>[CW-2664](https://linear.app/chatwoot/issue/CW-2664/canned-responses-are-not-working)</sub>

**Comment by pranavrajs** [comment]
@vagner-dias Which channel is it?

**Comment by vagner-dias** [comment]
@pranavrajs - After you mention the message signature, I ran a quick test here and I found that the canned responses are working only if I disable the message signature.

**Comment by vagner-dias** [comment]
![2023-10-18_17h53_48](https://github.com/chatwoot/chatwoot/assets/86367839/7f918d1d-c1a6-4625-9e2b-19d34f86752a)

**Comment by pranavrajs** [comment]
@vagner-dias Can you please confirm the channel?

**Comment by pranavrajs** [comment]
@vagner-dias I can confirm the bug, we will have a resolution soon.
