### ISSUE TITLE
[CW-2686] Upgrade Warning

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#8151]
### Describe the bug

How can I handle this warning?
![image](https://github.com/chatwoot/chatwoot/assets/62311149/a4ed6c57-8d00-4bcc-93c5-23cb6820006c)

### To Reproduce

Upgrade with cwctl --upgrade

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

None

<sub>[CW-2686](https://linear.app/chatwoot/issue/CW-2686/upgrade-warning)</sub>

**Comment by pranavrajs** [comment]
@vishnu-narayanan It looks like we need to update the PPA for Node.js.

**Comment by mattiamarras** [comment]
> @vishnu-narayanan It looks like we need to update the PPA for Node.js.

How?

**Comment by vishnu-narayanan** [comment]
@mattiamarras We will take care of this in the next update of cwctl. For now, you should be able to continue the installation/upgrade by waiting for 60 seconds.

**Comment by mattiamarras** [comment]
The upgrade with cwctl failed without showing errors. I had to manual upgrade following Pranav instructions.
