### ISSUE TITLE
Microsoft and Gmail channel is not getting creating

### ISSUE THREAD

**Issue by yoges24** [chatwoot/chatwoot#8153]
### Describe the bug

I am creating an email channel of Microsoft mail.
I setup a complete azure app registration. (I tested in both single or multi-tenant applications)
I follow the guidelines of the Azure APP setup in chatwoot website.

I setup the AZURE APP ID and SECRET in the environment file.
Restarted the chatwoot.

On clicking sign-in with Microsoft work, and open the Microsoft consent page.
After approving the consent form of the app, it predicted back to app website, but no any mail channel is created.
It simply redirect to chatwoot website URL.

Then I tried with my personal email to integrate with the chatwoot. On that I didn't receive any verification code from the chatwoot side.

### To Reproduce

Restarted the service whenever I made a change in the .env.
Need to integrate the microsoft and gmail with chatwoot

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Linux

### Browser and version

22.04

**Comment by pranavrajs** [comment]
@yoges24 Can you please check the server logs to see if there are any errors? There is no information here that help us to debug the issue.

**Comment by yoges24** [comment]
> @yoges24 Can you please check the server logs to see if there are any errors? There is no information here that help us to debug the issue.



I have attached the server logs. While adding a microsoft channel sign-in with Microsoft work, and open the Microsoft consent page.
After approving the consent form of the app, it predicted back to app website, but no any mail channel is created.
It simply redirect to chatwoot website URL.




Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.261967 #125890]  INFO -- : [b6987354-585d-4a6b-95d2-adb946776127] Completed 200 OK in 34ms (Views: 0.2ms | ActiveRecord: 22.6ms | Allocations: 10092)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.262651 #125890]  INFO -- : source=rack-timeout id=b6987354-585d-4a6b-95d2-adb946776127 timeout=15000ms service=44ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.282596 #125890]  INFO -- : source=rack-timeout id=aeb3e385-7341-4d91-af76-0161d8d77d7e timeout=15000ms state=ready
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.288770 #125890]  INFO -- : [787ddc40-5011-4c69-8c79-b3fd83de7eae]   Rendered api/v1/accounts/integrations/apps/index.json.jbuilder (Duration: 32.6ms | Allocations: 10478)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.289077 #125890]  INFO -- : [aeb3e385-7341-4d91-af76-0161d8d77d7e] Started PUT "/api/v1/profile" for 194.233.87.165 at 2023-10-25 16:25:30 +0530
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.299347 #125890]  INFO -- : [aeb3e385-7341-4d91-af76-0161d8d77d7e] Processing by Api::V1::ProfilesController#update as JSON
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.299447 #125890]  INFO -- : [aeb3e385-7341-4d91-af76-0161d8d77d7e]   Parameters: {"profile"=>{"ui_settings"=>{"rtl_view"=>false, "is_conv_actions_open"=>true, "show_secondary_sidebar"=>true, "is_contact_sidebar_open"=>false, "last_active_locale_code"=>"", "conversation_display_type"=>"expanded", "previously_used_sidebar_view"=>true, "previously_used_conversation_display_type"=>"expanded"}}}
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.307004 #125890]  INFO -- : [787ddc40-5011-4c69-8c79-b3fd83de7eae] Completed 200 OK in 163ms (Views: 17.5ms | ActiveRecord: 54.3ms | Allocations: 46794)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.313294 #125890]  INFO -- : source=rack-timeout id=787ddc40-5011-4c69-8c79-b3fd83de7eae timeout=15000ms service=186ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.336642 #125890]  INFO -- : source=rack-timeout id=138bda93-3d3e-4cb7-a487-cb9a97c8d7cd timeout=15000ms state=ready
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.342752 #125890]  INFO -- : [138bda93-3d3e-4cb7-a487-cb9a97c8d7cd] Started GET "/cable" for  at 2023-10-25 16:25:30 +0530
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.346938 #125890]  INFO -- : [138bda93-3d3e-4cb7-a487-cb9a97c8d7cd] Started GET "/cable" [WebSocket] for  at 2023-10-25 16:25:30 +0530
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.347390 #125890]  INFO -- : [138bda93-3d3e-4cb7-a487-cb9a97c8d7cd] Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: upgrade, HTTP_UPGRADE: websocket)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.351695 #125890]  INFO -- : source=rack-timeout id=138bda93-3d3e-4cb7-a487-cb9a97c8d7cd timeout=15000ms service=15ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.356618 #125890]  INFO -- : [aeb3e385-7341-4d91-af76-0161d8d77d7e]   Rendered api/v1/profiles/update.json.jbuilder (Duration: 36.2ms | Allocations: 11761)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.364581 #125890]  INFO -- : [aeb3e385-7341-4d91-af76-0161d8d77d7e] Completed 200 OK in 65ms (Views: 10.8ms | ActiveRecord: 41.6ms | Allocations: 20550)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.368248 #125890]  INFO -- : source=rack-timeout id=aeb3e385-7341-4d91-af76-0161d8d77d7e timeout=15000ms service=86ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.368764 #125890]  INFO -- : [e94ef03b-06c6-4fe1-b024-3bc7b2bbd905]   Rendered api/v1/profiles/update.json.jbuilder (Duration: 34.0ms | Allocations: 9561)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.380883 #125890]  INFO -- : [e94ef03b-06c6-4fe1-b024-3bc7b2bbd905] Completed 200 OK in 207ms (Views: 24.2ms | ActiveRecord: 73.5ms | Allocations: 58976)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.382771 #125890]  INFO -- : source=rack-timeout id=e94ef03b-06c6-4fe1-b024-3bc7b2bbd905 timeout=15000ms service=235ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.384966 #125890]  INFO -- : [874d8337-2c8d-461b-8300-016eab3b13d8] Completed 200 OK in 225ms (ActiveRecord: 106.5ms | Allocations: 64491)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.385558 #125890]  INFO -- : source=rack-timeout id=874d8337-2c8d-461b-8300-016eab3b13d8 timeout=15000ms service=250ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.398730 #125890]  INFO -- : source=rack-timeout id=5932040d-a46e-4e7d-9a18-b6c772e54672 timeout=15000ms state=ready
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.399700 #125890]  INFO -- : [5932040d-a46e-4e7d-9a18-b6c772e54672] Started GET "/api/v1/accounts/1/labels" for 194.233.87.165 at 2023-10-25 16:25:30 +0530
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.401937 #125890]  INFO -- : [5932040d-a46e-4e7d-9a18-b6c772e54672] Processing by Api::V1::Accounts::LabelsController#index as JSON
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.402191 #125890]  INFO -- : [5932040d-a46e-4e7d-9a18-b6c772e54672]   Parameters: {"account_id"=>"1"}
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.424622 #125890]  INFO -- : [5932040d-a46e-4e7d-9a18-b6c772e54672]   Rendered api/v1/accounts/labels/index.json.jbuilder (Duration: 7.2ms | Allocations: 2077)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.430992 #125890]  INFO -- : [5932040d-a46e-4e7d-9a18-b6c772e54672] Completed 200 OK in 29ms (Views: 9.0ms | ActiveRecord: 7.3ms | Allocations: 9486)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.431735 #125890]  INFO -- : source=rack-timeout id=5932040d-a46e-4e7d-9a18-b6c772e54672 timeout=15000ms service=33ms state=completed
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.460718 #125890]  INFO -- : RoomChannel is streaming from NvP9JQhVuY84krkgBvhWjCfa
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.541094 #125890]  INFO -- : [6b940425-e8c4-45ed-b2d3-d42410fc4a45]   Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 467.0ms | Allocations: 160158)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.543622 #125890]  INFO -- : [6b940425-e8c4-45ed-b2d3-d42410fc4a45] Completed 200 OK in 482ms (Views: 262.3ms | ActiveRecord: 210.4ms | Allocations: 164167)
Oct 25 16:25:30 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:30.547608 #125890]  INFO -- : source=rack-timeout id=6b940425-e8c4-45ed-b2d3-d42410fc4a45 timeout=15000ms service=489ms state=completed
Oct 25 16:25:50 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:50.095751 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:25:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:25:53.283572 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:07 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:07.958491 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:10 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:10.288940 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:21 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:21.582485 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:31 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:31.282184 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:52 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:52.283205 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:26:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:26:53.292123 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:27:07 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:27:07.961866 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:27:21 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:27:21.581551 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:27:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:27:53.290196 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:27:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:27:53.290836 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:28:07 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:28:07.951720 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:28:21 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:28:21.583608 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:28:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:28:53.287951 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:28:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:28:53.291867 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:29:07 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:29:07.941972 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:29:21 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:29:21.582449 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:29:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:29:53.285131 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:29:53 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:29:53.285606 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:30:07 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:30:07.957970 #125890]  INFO -- : RoomChannel#update_presence
Oct 25 16:30:21 ip-172-31-15-79 chatwoot-web.1[125890]: I, [2023-10-25T16:30:21.582974 #125890]  INFO -- : RoomChannel#update_presence

**Comment by sojan-official** [comment]
There are some changes from Microsoft's end for email channels; we have an updated doc for this. please follow : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/

also ensure your chatwoot installation is on the latest version.
