### ISSUE TITLE
I cant answer on the chat messenger and instagram

### ISSUE THREAD

**Issue by mredodos** [chatwoot/chatwoot#8160]
### Describe the bug

when i try to answer to the messenger or instagram chat the messagge appear on the chat screen but is not sent to the user. 

i try to approve my app but they write is not necessary for this.

### To Reproduce

try to send a message to the users

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

linux

### Browser and version

chrome latest

### Docker (if applicable)

docker latest

**Comment by mv-developer** [comment]
I have the same issue with version v3.2.0 
AWS marketplace AMI

**Comment by pranavrajs** [comment]
Please follow these guides to set up the Facebook developer app. 

https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup
https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup

**Comment by mredodos** [comment]
@pranavrajs i followed the entire guide and not work or i dont write here. i can just receive but i cant send message

**Comment by pranavrajs** [comment]
@mredodos Have you gotten approval from Facebook?

**Comment by mredodos** [comment]
@pranavrajs  
no because they told me that it is not necessary, and that it is not clear how to use it(I shared documentations, explanations and videos of chatwoot)

also previously I used manychat with the same functions and it did not require publishing or advanced permission to interact with users.
