### ISSUE TITLE
Attach file to macro

### ISSUE THREAD

**Issue by mattiamarras** [chatwoot/chatwoot#8163]
### Describe the bug

I try to attach a file to macro but it does not work.

Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.697187 #514994]  INFO -- : source=rack-timeout id=7ccaa54c-e7c6-4131-b583-ba5e1cade9d4 timeout=15000ms state=ready
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.697674 #514994]  INFO -- : [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4] Started POST "/api/v1/accounts/1/automation_rules/attach_file" for 217.133.39.88 at 2023-10-22 08:36:16 +0000
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: F, [2023-10-22T08:36:16.699496 #514994] FATAL -- : [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4]
**Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4] ActionController::RoutingError (No route matches [POST] "/api/v1/accounts/1/automation_rules/attach_file"):**
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4]
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.699954 #514994]  INFO -- : source=rack-timeout id=7ccaa54c-e7c6-4131-b583-ba5e1cade9d4 timeout=15000ms service=3ms state=completed

In the frontend i see this
![image](https://github.com/chatwoot/chatwoot/assets/62311149/d7f59370-7910-48c9-a77b-97574779edd1)
POST https://help.it/api/v1/accounts/1/automation_rules/attach_file 404 (Not Found)

### To Reproduce

Go to macro
Upload a PDF

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

None

**Comment by pranavrajs** [comment]
@mattiamarras As shared in the https://github.com/chatwoot/chatwoot/issues/8113, this is not reproducible on our end. If you have changed any code, please reset it to our develop branch and try it again. 

This endpoint is not where referenced in our code. <img width="381" alt="Screenshot 2023-10-24 at 12 19 50 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/28262723-f3d5-498a-a616-baf121fbb11d">

If you still have issue, please try this command. https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm#if-precompile-fails

**Comment by mattiamarras** [comment]
The end point is correct. I change the url for privacy, MYSITE /api/v1/accounts/1/automation_rules/attach_file.
Is somethin relateed to api permission? Witch log could I check?

This is not usefull?
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.697187 #514994] INFO -- : source=rack-timeout id=7ccaa54c-e7c6-4131-b583-ba5e1cade9d4 timeout=15000ms state=ready
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.697674 #514994] INFO -- : [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4] Started POST "/api/v1/accounts/1/automation_rules/attach_file" for 217.133.39.88 at 2023-10-22 08:36:16 +0000
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: F, [2023-10-22T08:36:16.699496 #514994] FATAL -- : [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4]
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4] ActionController::RoutingError (No route matches [POST] "/api/v1/accounts/1/automation_rules/attach_file"):
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: [7ccaa54c-e7c6-4131-b583-ba5e1cade9d4]
Oct 22 08:36:16 chatwoot chatwoot-web.1[514994]: I, [2023-10-22T08:36:16.699954 #514994] INFO -- : source=rack-timeout id=7ccaa54c-e7c6-4131-b583-ba5e1cade9d4 timeout=15000ms service=3ms state=completed

**Comment by mattiamarras** [comment]
Problem solved: the version of ruby and node was not correct and upgrade with cwctl was failing without showing error. In the manual update process i found the errors and fixed them. Thanks for support.
