### ISSUE TITLE
Feature: Typing Indicator to Twitter

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#817]
- [ ] Use use typing event to toggle Typing indicator in Twitter
- [ ] Use Twitter API webhook events to display user typing indicator in agent dashboard

**Comment by akashdotsrivastava** [comment]
@pranavrajs I'd like to give this a shot if it is still needed.

**Comment by pranavrajs** [comment]
@akashdotsrivastava Sure, you might need to take a look at the Twitty gem as well. https://github.com/chatwoot/twitty

I don't think we have implmented the method to toggle typicing indicator in the gem.

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
