### ISSUE TITLE
on creating messenger inbox it stucks on authenticating you with facebook

### ISSUE THREAD

**Issue by Georgemalima** [chatwoot/chatwoot#8180]
### Describe the bug

on creating facebook messenger inbox, it stucks on authenticating you with facebook, i have used chrome, and safari but no success.
the version of chatwoot i am using is latest from docker image.

### To Reproduce

the same ones on the documentations

### Expected behavior

i expected the inbox channel to authenticate and let me proceed with my usages.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Mac Os vantura 13.6

### Browser and version

safari, chrome

### Docker (if applicable)

Docker version 24.0.6

### Additional context

![Screenshot 2023-10-24 at 15 30 29](https://github.com/chatwoot/chatwoot/assets/67302866/e3cf1872-6c80-4751-9224-ec4cc8c7443d)

**Comment by pranavrajs** [comment]
Please set up the Facebook app properly as described in the documentation here. https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup

This error happens when there is a misconfiguration.
