### ISSUE TITLE
agent status via slack status

### ISSUE THREAD

**Issue by psifertex** [chatwoot/chatwoot#8184]
### Is your feature or enhancement related to a problem? Please describe.

Right now I have to login to the web UI before the interface shows me as active in our web chat box. I would rather the "offline" / "online" agent status be pulled directly from their slack status which is a far more accurate representation for us

### Describe the solution you'd like

See above.

### Describe alternatives you've considered

The alternative is to separately login via the web UI every time I am online/offline which is MUCH more cumbersome than simply normally using slack which tracks my online/offline status. 

### Additional context

Here's a link to the slack API for this particular feature:

https://api.slack.com/docs/presence-and-status#user-presence-and-status__user-presence

**Comment by pranavrajs** [comment]
@psifertex Thanks for the suggestion. This is not supported via webhook events, as far as I understand. Querying information about all the users in the system via APIs is feasible as it would the rate limits easily. 

https://api.slack.com/docs/presence-and-status#user-presence-and-status__determining-user-presence__presence-subscriptions-over-events-api

Closing it for now as it doesn't seem to have a feasible technical solution.

**Comment by psifertex** [comment]
That's not my understanding at all. RTM is specifically a websocket based _event_ API that doesn't trigger polling limits. It 

See the text:
```
RTM API Presence is now only available via subscription. As of January 2018, [presence_change](https://api.slack.com/events/presence_change) events are not dispatched without [presence subscriptions](https://api.slack.com/docs/presence-and-status) established with [presence_sub](https://api.slack.com/events/presence_sub). Relatedly, current user presence status is no longer communicated in [rtm.start](https://api.slack.com/methods/rtm.start). [Learn more](https://api.slack.com/changelog/2018-01-prese).
```

That's rather the point of a subscription isn't it? It's done via events? 

The accompanying API:

https://api.slack.com/events/presence_sub

**Comment by psifertex** [comment]
Oh, I see what you're suggesting. Yes, if you only want to implement it via a webhook then it's not possible. So consider this a request for an RTM based plugin that would be more featureful and is certainly feasible as it's the intended event-based-way to receive this data!
