### ISSUE TITLE
Chore: Review attachment handling in Twitter.

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#819]
- [ ] Verify that the media type are handled properly in Twitter integration

**Comment by tejaswinichile** [comment]
1. Check the attachment type
2. save the media and display the URL as it is in the attachment object; use twitter CDN.
3. Then render it in the frontend.

**Comment by pranavrajs** [comment]
Closing this for now as we have put the Twitter integration on hold due to the API and pricing changes.
