### ISSUE TITLE
Axios error - 3000ms timeout

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#8195]
### Describe the bug

Hi,

We are using Kubernetes Engine GKE infra for Chatwoot using GCP - 
Problem: we are using custom channel API and getting 3000ms timeout issue as attached

![error](https://github.com/chatwoot/chatwoot/assets/38554929/81e4da9a-807b-4e0e-84a3-2d119059cba0)

Cluster having 6 nodes & 24GB (we are getting around 5K conversations per month from different channels. 

Currently allocated pods are this (as screenshots)

Do we have to imporve our Pods ? if yes, any recommendations?

![image](https://github.com/chatwoot/chatwoot/assets/38554929/3a451178-7310-4f07-919d-0c40fbb20d66)

Chatwoot v2.12.0

### To Reproduce

As shared above

### Expected behavior

As shared above

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu

### Docker (if applicable)

Chatwoot v2.12.0

**Comment by pranavrajs** [comment]
@harismateen This is a quite old version of Chatwoot. Please upgrade to the latest.
