### ISSUE TITLE
We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by laravel920** [chatwoot/chatwoot#8218]
### Describe the bug

Hello, I have seen that someone has raised this issue before, but there is no specific solution. Can you help explain the specific solution? Convenient for those who encounter problems in the future to quickly solve them?

### To Reproduce

I installed it in Docker mode based on official documents. After installing according to the steps, this error is reported when accessing the domain name

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22.04 LTS上安装Chatwoot

**Comment by pranavrajs** [comment]
@laravel920 Please share the logs from the server without which we cannot debug the underlying issue.

**Comment by laravel920** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/64994491/fdd05654-7d8d-4d30-b308-584341f4e44a)
![image](https://github.com/chatwoot/chatwoot/assets/64994491/1ea7b28b-a9c4-497f-b1d7-4e983ff96f75)
Now, the main deployment is based on documents. Why is using a domain name to access after deployment a prerequisite? The image error during the deployment cannot reach the registration page。

**Comment by laravel920** [comment]
Could you please reply as soon as possible? Thank you

**Comment by laravel920** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/64994491/b5c0682f-0728-4063-bfa4-3906241f5ee5)
This mistake has always been

**Comment by laravel920** [comment]
> 请共享来自服务器的日志，否则我们无法调试根本问题。

Hello, can you reply?

**Comment by cifuentesmx** [comment]
> Why is using a domain name to access after deployment a prerequisite? The image error during the deployment cannot reach the registration page。

I've seen this message when the database is not ready. Did you run the migration?

**Comment by sojan-official** [comment]
Closing this since there hasn't been any activity on this for a while. Let's reopen if required.
