### ISSUE TITLE
Office365 SMTP is not working

### ISSUE THREAD

**Issue by yoges24** [chatwoot/chatwoot#8221]
### Describe the bug

After integrated the Office365 with chatwoot. I receive mails from the integrated outlook account. If reply back on the inbox channel having an error. I have attached the image of the error. Please kindly help me to fix the issue.
![Screenshot from 2023-10-26 18-03-19](https://github.com/chatwoot/chatwoot/assets/148360361/24ed3f76-0a37-4944-901b-15333200282b)

### To Reproduce

SMTP with office365 account.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Linux

### Browser and version

22.04

**Comment by pranavrajs** [comment]
Microsoft has deprecated the SMTP basic auth flow. Please setup an Azure App as described [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/).

**Comment by yoges24** [comment]
I Exactly done as per the documentation. But reply is not received to the
another end

**Comment by yoges24** [comment]
> Microsoft has deprecated the SMTP basic auth flow. Please setup an Azure App as described [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/azure-app-setup/).

I setup an Azure APP and added the APP ID and Secret key to the .env file. The inbox is added. I receive mails to the chatwoot inbox channel. But my reply message is not to another end. Its failing. How to fix this?
