### ISSUE TITLE
Migration Error: NameError: undefined local variable or method `locked' for #<InstallationConfig id: nil, name: "INSTALLATION_NAME", serialized_value: "{}", created_at: nil, updated_at: nil> Did you mean?  lock!

### ISSUE THREAD

**Issue by SherefAbolmagd** [chatwoot/chatwoot#8225]
### Describe the bug

trying to migrate from v2.12.0 to latest version but getting error when running bundle exec rake db:migrate, I have a lot of data inside the db so I'm unable to do fresh start.
![image](https://github.com/chatwoot/chatwoot/assets/40181573/6bd13b24-715c-43c5-bef7-bb5b393a18e2)
 

### To Reproduce

1. run bundle exec rake db:migrate from version v2.12.0 to latest version

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

### Operating system

windows

### Browser and version

edge 119.0.2151.24

**Comment by pranavrajs** [comment]
@SherefAbolmagd 2.12.0 is quite old. You would have to manually migrate it step by step. 2.12 -> 2.13 -> 2.14 and so on.
