### ISSUE TITLE
Email inbox reply not send Net::ReadTimeout

### ISSUE THREAD

**Issue by yoges24** [chatwoot/chatwoot#8227]
### Describe the bug

Instead of using SMTP to deliver emails (since I can't setup Microsoft SMTP) I've added Mailgun info to my .env file.

Reset password emails are being sent, but email inbox emails are not being delivered. Inside chatwoot it says sent successfully, but I see the task killed inside Sidekiq with error: Net::ReadTimeout: Net::ReadTimeout with #Socket:(closed)

What does it mean and how can I solve it?
![Screenshot from 2023-10-26 18-03-19](https://github.com/chatwoot/chatwoot/assets/148360361/1927b273-1f4c-4570-acca-c2ab1321e7b4)

### To Reproduce

1. Reply to any conversation

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Linux

### Browser and version

22.04

### Additional context

Worker Logs

Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: I, [2023-10-27T12:40:34.537188 #150606]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0] Delivered mail conversation/23d2be61-16c8-4755-a678-69a58802dfc4/messages/ (5077.0ms)
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: E, [2023-10-27T12:40:34.537610 #150606] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0] Error performing ActionMailer::MailDeliveryJob (Job ID: 86fbdf6b-5fb7-4070-af5a-86e6dfcfd5e0) from Sidekiq(default) in 5178.2ms: Net::ReadTimeout (Net::ReadTimeout with #<Socket:(closed)>):
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:229:in `rbuf_fill'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:199:in `readuntil'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/net/protocol.rb:209:in `readline'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1057:in `recv_response'
Oct 27 12:40:34 ip-172-31-15-79 chatwoot-worker.1[150606]: /usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0/gems/net-smtp-0.3.3/lib/net/smtp.rb:1051:in `get_response'

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/8226, a setup issue.
