### ISSUE TITLE
Cloud storage data is not replicated to local storage

### ISSUE THREAD

**Issue by frerej** [chatwoot/chatwoot#8228]
### Describe the bug

Going back from cloud storage to local storage doesn't replicate the data

### To Reproduce

Enable any cloud storage provider
Store any data on the cloud storage
Disable the cloud storage, enable local storage
Data from cloud storage is not replicated to local storage

### Expected behavior

Data should be replicated to local storage upon disabling cloud storage

### Environment

app.chatwoot.com

### Cloud Provider

AWS

### Platform

None

**Comment by pranavrajs** [comment]
@frerej This is expected. You would have to manually move everything to local storage. The system won't automatically copy everything over to the local machine.

**Comment by frerej** [comment]
So, if we switch to a different cloud storage provider or decide to revert to local storage, we have to manually copy all the data. That's not really a friendly option. Shall we move this from bug to requested feature?
