### ISSUE TITLE
[CW-2698] Design: Adjust colors in email messages in dark mode

### ISSUE THREAD

**Issue by jtayrone** [chatwoot/chatwoot#8232]
### Describe the bug

When we use dark mode, messages received in the email channel are affected by the white background and lack of contrast in the content.

![image](https://github.com/chatwoot/chatwoot/assets/34479816/6c2b2cf6-4ceb-4262-848d-c5bdda620e1d)

### To Reproduce

1. Activate an email inbox
2. Send a new message to account
3. Open message

### Expected behavior

![image](https://github.com/chatwoot/chatwoot/assets/34479816/f6a261f0-1085-4e8c-944a-02b114f5261f)

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

<sub>[CW-2698](https://linear.app/chatwoot/issue/CW-2698/design-adjust-colors-in-email-messages-in-dark-mode)</sub>

**Comment by iamsivin** [comment]
@pranavrajs I faced some issues here that the email is rendering inside `vue-letter` so we don't have controls over it to change the background and the text color. If we forced it to change then there will be breakage in the UI. 

The possible solution is to limit the background of email message to light and the text color to dark. Thoughts?
CC: @scmmishra

**Comment by scmmishra** [comment]
@pranavrajs Let us know your thoughts
CC: @absurdiya

**Comment by pranavrajs** [comment]
As discussed in the sprint call, let us consider the email in white mode only for now, until we figure out a better plan.

**Comment by muhsin-k** [comment]
@scmmishra will do the QA.
