### ISSUE TITLE
[CW-2725] External links from helpdesk being opened in livechat widget

### ISSUE THREAD

**Issue by eddietoth1** [chatwoot/chatwoot#8241]
### Describe the bug

When I have external links in help center articles, and they show in my live chat, if someone clicks them the link tries to load inside the widget in an iframe, which 99% of the time does not work.

### To Reproduce

In the live chat widget if you have articles add a link in one click on it and then it tries to load in an iframe and may get blocked and not load

### Expected behavior

For the external link to open in a new tab

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Additional context

Solution: on all external links in help center, just add "target"="_blank"

<sub>[CW-2725](https://linear.app/chatwoot/issue/CW-2725/external-links-from-helpdesk-being-opened-in-livechat-widget)</sub>

**Comment by pranavrajs** [comment]
@eddietoth1 Thanks for reporting this, we will get it fixed.

**Comment by eddietoth1** [comment]
Hi, this issue is still not fixed. External links in the help center still try to load inside the iframe in the widget. Please fix @pranavrajs, thanks.
![image-redacted_dot_app (1)](https://github.com/chatwoot/chatwoot/assets/121629496/8bbac9c2-4ee5-4655-9f2d-9dd5246ff5f8)

**Comment by eddietoth1** [comment]
I am on the latest version 3.3.1
