### ISSUE TITLE
Can I run the front-end independently and connect to the remote back-end? There are too many things that need to be installed locally

### ISSUE THREAD

**Issue by yuexiajiayan** [chatwoot/chatwoot#8246]
### Is your feature or enhancement related to a problem? Please describe.

Can I run the front-end independently and connect to the remote back-end? There are too many things that need to be installed locally?

### Describe the solution you'd like

like this https://github.com/chatwoot/ui

**Comment by pranavrajs** [comment]
Nope, this is not supported at the moment.
