### ISSUE TITLE
[CW-2713] The agent's personal signature is added to all channels

### ISSUE THREAD

**Issue by aerostovtsev** [chatwoot/chatwoot#8247]
### Is your feature or enhancement related to a problem? Please describe.

Hi!
Since version 3.x, when the signature is enabled in the agent's private messages, it has become enabled by default for all connected channels (email/api/website and others), previously it was enabled only for the email channel. In our company, the agent's signature consists of 6 lines https://i.imgur.com/esjSpXW.png , in the dialogs from the online chat channel, you must disable the signature, and in the dialogs from the email channel, you must enable it. In such a user case, we observe problems:

1. in an online chat, in addition to a 3-6-line message, an agent's signature of 6 lines is also added, and the operator's message is not always displayed in the window in the area visible to the client https://i.imgur.com/S08YMkj.png , has to scroll , and the client does not need the agent's signature information in each message.
2. the constant switching on and off of the signature leads to the fact that the agent must remember and perform additional actions.

Discussion https://discord.com/channels/647412545203994635/1166610034977931295

![esjSpXW](https://github.com/chatwoot/chatwoot/assets/57803974/56acda7a-5f83-4e64-bbda-f35ced69e610)
![S08YMkj](https://github.com/chatwoot/chatwoot/assets/57803974/3230a1f8-0b4c-4d22-aade-122a5fa5bd8a)

### Describe the solution you'd like

When you enable or disable agent signature in each channel, save the settings.

<sub>[CW-2713](https://linear.app/chatwoot/issue/CW-2713/the-agents-personal-signature-is-added-to-all-channels)</sub>

**Comment by pranavrajs** [comment]
@aerostovtsev Thanks for the feedback, we will address this in the next release.

**Comment by pranavrajs** [comment]
@scmmishra Please share your thoughts here.

**Comment by scmmishra** [comment]
> @scmmishra Please share your thoughts here.

We can make the toggle signature button specific to inbox, as a first step. Later we can properly implement a signature per-inbox
