### ISSUE TITLE
Forward e-mail address doesn't work

### ISSUE THREAD

**Issue by Apacalipto** [chatwoot/chatwoot#8265]
### Describe the bug

3294@see-docs.cloudron.io

I think i'm missing something. I'm checking the docs, but can't find the right article on how to solve this.

I created an inbox and a forwarding address is generated. : XXXXXXXX3294@see-docs.cloudron.io.

But it doesn't work of course. How can I make it work?

So I can create group in my Google Workspace that forwards the emails to this address.

I would like to avoid needing to create another workspace user in my Google account. 

### To Reproduce

Fresh chatwood install of docker.

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

None

### Browser and version

Chrome

### Docker (if applicable)

Docker installation

### Additional context

We are running the latest version: 3.2.0

https://github.com/chatwoot/chatwoot/releases/tag/v3.2.0

**Comment by danielthedifficult** [comment]
@Apacalipto can you share what you've done on the Google end of things?

Also, in order for the forwarding address to work, I think you need some MX/IMAP setup. Personally, I have it connected to my own Google workspace user via IMAP, but I also configured all support email to automatically go into a certain folder and skip the inbox.

**Comment by Apacalipto** [comment]
@danielthedifficult But we have 3 companies.

So we need 3 different email inboxes in Chatwoot.

If i set up 1 gmail account with IMAP. 

How can I separate the different email boxes.

And i don't understand how this would enable the forwarding function. But i'm going to create a Personal Gsuite account and connect it using IMAP and play around with it.

**Comment by pranavrajs** [comment]
@danielthedifficult I'm not sure if I understand the issue here. Can you please describe the issue in detail? There is little information on where this issue happens and how to reproduce it. Please add relevant screenshots & screencasts to help reproduce the behavior.

**Comment by Apacalipto** [comment]
@pranavrajs 
![444](https://github.com/chatwoot/chatwoot/assets/23662152/1d338788-2350-4bb7-8e4a-9762a7da13fc)

The problem is there is no working forwarding e-mail address. We rather not use IMAP because then we would need to create server e-mail address, but this is blocked by digital ocean. We use g-Suite for everything, and then i would have to create multiple fictional user's in Gsuite and pay monthly fee's for it.

So if the forwarding e-mail address would work, that would help me a lot :). Then i can create forwarding filters in an existing e-mail box.

**Comment by sojan-official** [comment]
@Apacalipto, we don't support forwarding with IMAP at the moment.   It should either be 
- using forward to : enable conversation continuity ( https://www.chatwoot.com/docs/product/channels/live-chat/conversation-continuity ) 
- or imap & smpt

**Comment by Apacalipto** [comment]
I don't understand.

Currently, i'm working on a new Chatwoot installation.

Same issue: 

![image](https://github.com/chatwoot/chatwoot/assets/23662152/71a2bffe-c8ba-495e-b943-4951df510161)

No working forwarding address (IMAP disabled).

How do i set up a forwarding address that works?

All the documentation on the Chatwoot website regarding setting up the e-mail have a working forwarding email address from the start. No information on what to do if the email address in the box isn't valid.

Or does the e-mail forwarding function only work if you host at Chatwoot?
