### ISSUE TITLE
Fails when trying to install node on chatwoot

### ISSUE THREAD

**Issue by marcelocaciatori** [chatwoot/chatwoot#8267]
### Describe the bug

Fails when trying to install node on chatwoot

<img width="952" alt="contabo" src="https://github.com/chatwoot/chatwoot/assets/91642837/eedde661-de27-4814-b040-99f54b19ec5a">
<img width="743" alt="hetzner" src="https://github.com/chatwoot/chatwoot/assets/91642837/181562d5-4532-458d-8bde-f2f6d3192b71">

### To Reproduce

We tried to install chatwoot on two different vps following the script below:

https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

1 Contabo
2 Hetzner

8 GB RAM memory
4 CPU

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 22.04

**Comment by JulianMelzig** [comment]
I am experiencing the exact same issue

**Comment by MoreiraTv** [comment]
Install the separate node by running these commands, and then run the installer again.


```
sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
NODE_MAJOR=20
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
sudo apt-get update && sudo apt-get install nodejs -y
```

**Comment by GabrielDevSilva** [comment]
> Install the separate node by running these commands, and then run the installer again.
> 
> ```
> sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg
> curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
> NODE_MAJOR=20
> echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
> sudo apt-get update && sudo apt-get install nodejs -y
> ```

It worked for me, thanks

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/8151
