### ISSUE TITLE
Restrict the viewing and modification of conversations by agent assigned to the agent type user

### ISSUE THREAD

**Issue by Sollydus** [chatwoot/chatwoot#8274]
### Is your feature or enhancement related to a problem? Please describe.

Any agent can view, resolve and receive conversations that are not assigned to them, causing permission and privacy issues among collaborators.

### Describe the solution you'd like

The solution to this problem would be to separate and restrict conversations by designated agent, making it possible to view and change only conversations that were assigned to the agent themselves.

**Comment by alexmsaraiva1** [comment]
can't wait to see it

**Comment by jtayrone** [comment]
fix: https://github.com/chatwoot/chatwoot/pull/7649
