### ISSUE TITLE
Instagram Linked page is not showing while adding inbox

### ISSUE THREAD

**Issue by psujit775** [chatwoot/chatwoot#8282]
### Describe the bug

I'm trying to setup inbox for Instagram. following this document: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup

Currently i'm at this step **(Testing the Instagram channel)**.

While adding the inbox I can see the list of Facebook pages which are not linked to Instagram but as soon as i link the page to Instagram it stop's showing the linked Facebook page.

I'm the admin of Facebook page and Instagram id. so i have all the rights. I can see Instagram messages in my linked Facebook page messages.

### To Reproduce

Steps to reproduce:

Go to Inboxes and Add New Inbox
Click on Messenger and Authorize both IG and FB pages and accounts.
Now after the modal close, click on the "Choose Page" select box it should show Instagram linked page and Facebook page both but only showing Facebook page not Instagram page.

### Expected behavior

Instagram linked page should be shown

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

macOS 13.5

### Browser and version

Google Chrome Version 118.0.5993.117 (Official Build) (x86_64)

### Docker (if applicable)

# Docker Version
Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:07:41 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24
  GitCommit:        61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc:
  Version:          1.1.9
  GitCommit:        v1.1.9-0-gccaecfc
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  # Docker Info
Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 61f9fd88f79f081d64d6fa3bb1a0dc71ec870523
 runc version: v1.1.9-0-gccaecfc
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-1012-aws
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.882GiB
 Name: ip-192-168-3-88
 ID: 016d81f6-7352-4f35-86e2-999c6d767fcf
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

# Docker compose version
using docker compose plugin comes default

### Additional context

For Facebook page it's working perfectly as expected. Only issue is i'm not able to add Instagram linked Facebook page.

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/8004
