### ISSUE TITLE
Instagram history mention - Image Not refresh 

### ISSUE THREAD

**Issue by pelucapampa** [chatwoot/chatwoot#8284]
### Describe the bug

System no show instagram story mentioned image when you are into conversation panel.

### To Reproduce

Self Hosted
3.2 Version

Hi, i'm trying to obtain facebook approval, when I making a screen recorder and i'm into a converstation panel, system cannot show Story Image and show a text with asset....

![image](https://github.com/chatwoot/chatwoot/assets/120580431/f842d7ee-4df7-4c90-8f1a-4609380c2a92)

if i'm on another section and go to converstation panel or refresh page, the app show the image.

I'm Chatwoot 3.2 version and selfhosted

### Expected behavior

System refresh and show Image, not text and download link (Because Facebook reject request approval)

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@pelucapampa This is fixed already in https://github.com/chatwoot/chatwoot/pull/8240, and it will be available in the Nov 15 release.

**Comment by pelucapampa** [comment]
> @pelucapampa This is fixed already in #8240, and it will be available in the Nov 15 release.

Hi @pranavrajs , have any news about Nov 15 Release? 
Thanks
