### ISSUE TITLE
Address Not Found - Email reply

### ISSUE THREAD

**Issue by MoreiraTv** [chatwoot/chatwoot#8290]
### Describe the bug

When a conversation transcript is sent by email I am receiving it normally, but the sender address is written reply+ at the beginning of the email that I configured in the .env with this when the user tries to reply to the email and returned address not found.

![image](https://github.com/chatwoot/chatwoot/assets/54282051/609d6bd4-32fb-43bc-bab2-3242dcf3d79e)

### To Reproduce

I've set up all the smtp in the .env file and I'm using brevo for professional email use.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@MoreiraTv The configuration is wrong here. It seems that you have not set up conversation continuity using [inbound parse ](https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity/). Please disable the features `inbound_emails`, `custom_reply_email` and `custom_reply_domain` from the super_admin panel

**Comment by MoreiraTv** [comment]
I haven't set up conversation continuity as I don't have cloud storage set up yet. 
In my dashboard super_admin doesn't have these variables mentioned: ''inbound_emails'' ''custom_reply_email'' ''custom_reply_domain''

Should I create them in the dashboard? And how should I set it up?

**Comment by pranavrajs** [comment]
<img width="1148" alt="Screenshot 2023-11-08 at 4 54 15 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/18d9512b-ac12-4e8d-9e83-35b3183b7537">

Please edit an account, and you will see the list of all features.

**Comment by MoreiraTv** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/54282051/fbf3d250-b9d0-49d2-a130-24617baaa924)

I edited as directed and tested an email on this same account which I edited by sending a transcript of the conversation by email, and it continues to be sent an email with "reply+" in the email address
