### ISSUE TITLE
Change logo chatwoot 3.2

### ISSUE THREAD

**Issue by jordaoluiz** [chatwoot/chatwoot#8292]
### Is your feature or enhancement related to a problem? Please describe.

How can i change the logo ? Chatwoot 3.2.0

### Describe the solution you'd like

How can i change the logo ? Chatwoot 3.2.0

**Comment by sojan-official** [comment]
https://www.chatwoot.com/docs/self-hosted/faq#how-can-i-customise-the-chatwoot-branding-
