### ISSUE TITLE
set default locale

### ISSUE THREAD

**Issue by vfasoulas** [chatwoot/chatwoot#830]
**Is your enhancement request related to a problem? Please describe.**
I can not specify locale for login screen, other than english

**Describe the solution you'd like**
define default locale as enviroment variable for example DEFAULT_LOCALE .

**Describe alternatives you've considered**
using system variable for example LC_ALL.

**Additional context**
Also it seems that agent locale is allways english, even if account locale defined as greek (for example)

#### 1. Ability to define a default language on the installation. 

Define an environment variable `DEFAULT_LOCALE`.
1. If the variable is set, all non-authenticated pages would fallback to the default locale. 
2. Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en

#### 2. Ability to select different locale in non-authenticated pages
There is will be a dropdown at the bottom of the page to change the locale. If the user changes the locale, save it in the local storage and use this locale in his next visit.

**Comment by sojan-official** [comment]
@vfasoulas  we will explore a solution for this in the upcoming release

**Comment by enderahmetyurt** [comment]
I can do something about it.

**Comment by pranavrajs** [comment]
@enderahmetyurt Please feel free to take it.

**Comment by enderahmetyurt** [comment]
I want to ask making clear the issue. The user can change the locale when she is loggedin but we talk about in here login page. How can we understand the user's locale which set before? Should we use system locale? For example, the user chould have chosen german for their account, but she use her browser in english. Which language will she on login page?

**Comment by pranavrajs** [comment]
@enderahmetyurt Sorry about being unclear about the expectations. 

> The user can change the locale when she is logged in but we talk about in here login page. 

Yes, this is correct. We are only talking about non-authenticated pages. Login/Signup/ResetPassword/SetNewPassword

I've updated the acceptance criteria in the issue.

**Comment by pranavrajs** [comment]
@enderahmetyurt Please let me know your thoughts on Acceptance Criteria, if you think it is too much, let us create smaller issues on top of this issue.

**Comment by enderahmetyurt** [comment]
`DEFAULT_LOCALE` should be in `application.yml` or `/config/installation_config.yml`?

**Comment by sojan-official** [comment]
@enderahmetyurt  should be .env file. So it's easily changeable on a chatwoot installation.

**Comment by pranavrajs** [comment]
Moving this to the next sprint as it will not completed by EOD today.

**Comment by pranavrajs** [comment]
@enderahmetyurt unassigning this from you as it was not picked up for a long time.

**Comment by enderahmetyurt** [comment]
Sorry i could not work it

**Comment by azyzio** [comment]
I took it
