### ISSUE TITLE
Facebook page choose dropdown is empty

### ISSUE THREAD

**Issue by erfanjahanshahlo** [chatwoot/chatwoot#8302]
### Describe the bug

Hello,
I have installed chatwoot through Docker and with easypanel and I have a problem in setting up the Facebook connection, (of course I have to say that I have installed it through Docker without easypanel and the problem is the same and the matter is not related to easypanel)
The selection list of the Facebook page is empty after connecting through login with Facebook, while I have completed all the documentation steps (my app is in the testing stage and the confirmation request has not been sent to Facebook yet) and connecting Instagram to the Facebook page. And placing them in the test list is complete, but the page selection list is empty.

I have found this error in browser console from facebook sdk.js:
<" You are overriding current access token, that means some other app is expecting different access token and you will probably break things. Please consider passing access_token directly to API parameters instead of overriding the global settings. ">

<img width="907" alt="Screenshot_1402-08-12_at_14 07 53" src="https://github.com/chatwoot/chatwoot/assets/44373747/7c2aad64-8f6d-44b3-b18f-1c980c4c0bdd">

### To Reproduce

Go to Inboxes and Add New Inbox
Click on Messenger and Authorize both IG and FB pages and accounts.
Now after the modal close, click on the "Choose Page" and select box is empty

### Expected behavior

IG linked page and FB page should be shown

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Additional context

Facebook app is in test state

**Comment by pranavrajs** [comment]
Closed via #8004

**Comment by pranavrajs** [comment]
@erfanjahanshahlo The latest API versions need one more permission for this to work. You can get the changes in the next update on Nov 15.
