### ISSUE TITLE
chat message swap after send the message from widget

### ISSUE THREAD

**Issue by lydenn** [chatwoot/chatwoot#8309]
### Describe the bug

![photo_2023-11-07 17 35 28](https://github.com/chatwoot/chatwoot/assets/102777811/b387a0bc-ed92-4118-8d1e-e4fee2466802)

### To Reproduce

user send message from chat widget

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Mobile

### Operating system

Android

**Comment by pranavrajs** [comment]
@lydenn, Can you please explain the issue? I couldn't understand the issue here.

**Comment by Ericmagsllonstrigs** [comment]
Thank

**Comment by Ericmagsllonstrigs** [comment]
```

```````
> 
````

**Comment by Ericmagsllonstrigs** [comment]
> Provider
> 
> AWS
> 
> Platform
> 
> Mobile

@sojan-official

**Comment by Ericmagsllonstrigs** [comment]
Ty I @sojan-official

**Comment by pranavrajs** [comment]
Closing this as there is not much information here to proceed. Please re-open this with more info that would help us to debug the issue.

**Comment by Ericmagsllonstrigs** [comment]
Good morning

**Comment by Ericmagsllonstrigs** [comment]
Yoissa
