### ISSUE TITLE
How can we send WhatsApp button message and normal message by chatwoot api

### ISSUE THREAD

**Issue by harsh1109** [chatwoot/chatwoot#8312]
### Describe the bug

Hi,

Can suggest , how can we send  button WhatsApp message and normal WhatsApp message by chatwoot api. If have any script then please share with us 

### To Reproduce

1. Bot found any documents 

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by glauberssoutodossantos** [comment]
Hi @harsh1109 try this PR here:

https://github.com/chatwoot/chatwoot/pull/6886

**Comment by pranavrajs** [comment]
@harsh1109 As @glauberssoutodossantos suggested, please use the input_select payload described [here](https://www.chatwoot.com/docs/product/others/interactive-messages/).
