### ISSUE TITLE
Missing inbox when create a campaign

### ISSUE THREAD

**Issue by beefixi** [chatwoot/chatwoot#8315]
### Describe the bug

When I create a campaign I don't see any inboxes even if I have at least one inbox, it's just nothing in the dropdown menu. Has anyone had this issue before?

### To Reproduce

Create a new campaign >> click to "Select inbox"

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome

**Comment by pranavrajs** [comment]
Ongoing campaigns are currently supported only in Website channel and one-off campaigns are only supported in the SMS channel.
