### ISSUE TITLE
Email channel

### ISSUE THREAD

**Issue by chinyaev** [chatwoot/chatwoot#832]
Hello! You write in 1.4 version "Conversation continuity through Email (αlpha)", I understand correctly that this is an email channel? I install chatwoot via Docker, but don't see the email channel in the settings (https://imgur.com/a/9z8fJDF)

**Comment by pranavrajs** [comment]
@chinyaev This is under a feature flag, we were expecting it to be beta tested this month and release publically in the next release. There were some issues with some type of attachments, so we figured we will iron out those.

Hope that helps.
