### ISSUE TITLE
Bug: The icons in widget are not aligned

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#833]
<img width="458" alt="Screenshot 2020-05-07 20 57 36" src="https://user-images.githubusercontent.com/2246121/81313405-7418b000-90a5-11ea-94c5-5dcb4e7d0970.png">

Browser: Firefox 76.0

**Comment by RonWalker22** [comment]
@nithindavid have you already started working on this?

**Comment by pranavrajs** [comment]
@RonWalker22 Nope, if you want to pick it up, you can do that :)

**Comment by RonWalker22** [comment]
@pranavrajs  Yes, I'll take it. Thanks!
