### ISSUE TITLE
Receive contact on whatsapp inbox

### ISSUE THREAD

**Issue by IcaruuS22** [chatwoot/chatwoot#8331]
### Describe the bug

I don't receive contact cards sent via WhatsApp. Has anyone ever experienced this?

The contact card is normally sent between one WhatsApp to another, but in the Chatwoot conversation the contact card does not appear.

![Screenshot_1](https://github.com/chatwoot/chatwoot/assets/88380824/d730e978-4124-4cc5-8db8-a65bd07c07d9)

### To Reproduce

1 - Sending contact on WhatsApp
2 - The contact card is not sent to chatwoot, only the contact name.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by ssteeltm** [comment]
In mine,  I use api channel to use whatsapp.
![image](https://github.com/chatwoot/chatwoot/assets/17302120/9795127f-8240-4d7b-a73d-8b8db27c7cb3)
Have done this integration, reads the vcard and shows to the agent, and then import on chatwoot.

Woud be great if Chatwoot have some better way to draw one "card" on screen, with buttons, to the user start conversation with.
as I used Api channel, it would need to have api to draw/manage this type of message too

**Comment by pranavrajs** [comment]
@IcaruuS22 You are using an API channel, please check the payload when calling the APIs. It seems to be an issue with the API channel setup and not a bug.
