### ISSUE TITLE
Performance Issues with Chatwoot - Try Again

### ISSUE THREAD

**Issue by pedrofnts** [chatwoot/chatwoot#8334]
### Describe the bug

Hello, I am using Chatwoot on an Ubuntu VPS at Digital Ocean with the following specifications:

16 GB Memory / 4 AMD vCPUs / 100 GB Disk / SFO3 - Ubuntu 22.04 (LTS) x64

I have an average of 7 agents online, across 3 inboxes, handling a high volume of messages. Several times throughout the day, the error below occurs:

"Message could not be sent! Please try again."

The message bubble turns red, and it is necessary to click on retry multiple times to send the message.

What could be the issue?

The VPS CPU load is averaging 20%, RAM at 24%, Disk I/O write vda at 470kB/s, and outbound bandwidth at 650 kB/s.

### To Reproduce

Idk

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 22.04

### Browser and version

Chrome

**Comment by pedrofnts** [comment]
![WhatsApp Image 2023-11-09 at 17 02 24](https://github.com/chatwoot/chatwoot/assets/63073772/5cbf0f9c-0be4-4d30-a97d-a6a049f451de)

**Comment by pranavrajs** [comment]
@pedrofnts 

1/ Can you please share the error logs?
2/ Which channel is it?

**Comment by shivamkb17** [comment]
can you check, do you enable response bot in this account, If yes, disable it, and retry sending message. 

![image](https://github.com/chatwoot/chatwoot/assets/76581658/c6c75fbf-86c0-4501-bfa9-0568ce8d9dbc)

If this is enabled, try sending message after disabling it. 
I am also facing similar issue, Then incoming and outgoing message start working perfectly.

**Comment by pedrofnts** [comment]
> @pedrofnts
> 
> 1/ Can you please share the error logs? 2/ Which channel is it?

1. How I can see the error logs?
2. It's an API channel.

**Comment by pedrofnts** [comment]
> can you check, do you enable response bot in this account, If yes, disable it, and retry sending message.
> 
> ![image](https://user-images.githubusercontent.com/76581658/281982210-c6c75fbf-86c0-4501-bfa9-0568ce8d9dbc.png)
> 
> If this is enabled, try sending message after disabling it. I am also facing similar issue, Then incoming and outgoing message start working perfectly.

Where I can enable/disable this?

**Comment by pedrofnts** [comment]
@pranavrajs 
![WhatsApp Image 2023-11-10 at 10 53 47](https://github.com/chatwoot/chatwoot/assets/63073772/2ebffe11-f53d-4ece-ae3f-7541f70e7c19)
 here's the console. It says 429 too many requests.

**Comment by hheexx** [comment]
https://www.chatwoot.com/docs/self-hosted/monitoring/rate-limiting

**Comment by pedrofnts** [comment]
Solved by setting ENABLE_RACK_ATTACK and ENABLE_RACK_ATTACK_WIDGET_API env variables to false.
