### ISSUE TITLE
whatsapp integration replace http with https

### ISSUE THREAD

**Issue by politsin** [chatwoot/chatwoot#8338]
### Describe the bug

whatsapp integration breaks links in original message 

### To Reproduce

1 Install chatwoot 3.1.0
2 Send whatsapp message with link http://example.com
3 See message in whatsapp application http://example.com
4 Ok when goto

1 Install chatwoot 3.2.0
2 Send whatsapp message with link http://example.com
3 See message in whatsapp application http://example.com
4 But on copy or goto with link you get https://example.com

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@politsin We don't change the URL on our end. Please check if this is getting updated on Meta's end.

**Comment by sojan-official** [comment]
@moeburn  Thanks for reporting back. closing this since there isn't any actions needed from our end
