### ISSUE TITLE
VoipMS SMS

### ISSUE THREAD

**Issue by ikifar2012** [chatwoot/chatwoot#8345]
### Is your feature or enhancement related to a problem? Please describe.

We are currently using VoipMS for our business phone number, they now offer SMS

### Describe the solution you'd like

 I would really appreciate it if VoipMS SMS support could be added to Chatwoot

### Describe alternatives you've considered

I have considered using Twilio but SIP Trunking with VoipMS is cheaper, and we want to use the same DID for SMS and Voice 

### Additional context

API Documentation:
https://voip.ms/m/apidocs.php

**Comment by pranavrajs** [comment]
@ikifar2012 Thanks for the feedback. We are focusing only on text-based messaging at the moment. We will not be adding this feature.
