### ISSUE TITLE
Enterprise::SentimentAnalysisJob	error.

### ISSUE THREAD

**Issue by rp2566** [chatwoot/chatwoot#8347]
### Describe the bug

Enterprise::SentimentAnalysisJob fails. My metrics for the last 8h:
Success 3279
Failure 8738
Total Execution Time 45.13 seconds
Average Execution Time 0.01 seconds

LoadError: Could not open library '/gems/ruby/3.2.0/gems/onnxruntime-0.7.6/vendor/libonnxruntime.so': Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /gems/ruby/...

My overall stats:
Processed 1,987,677
Failed 197,336
I don't know if the failures all come from SentimentAnalysisJob or not. On my last 8h metrics, only SentimentAnalysisJob has failures.

### To Reproduce

I use docker installation. Chatwoot v3.2.0. Installing using the steps from the installation guide.

### Expected behavior

All jobs are successful

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Debian 12

### Browser and version

Chrome

### Docker (if applicable)

Docker version 24.0.7
Docker Compose version v2.21.0

**Comment by dannylessio** [comment]
Hi there, I'm experiencing exactly the same issue with exactly the same config.

**Comment by pranavrajs** [comment]
@dannylessio @rp2566 The job shouldn't execute if you haven't set SENTIMENT_FILE_PATH. Please check for an environment value for this. If it exists, delete it. The problem arises when the job runs without the actual model, causing the issue.

**Comment by dannylessio** [comment]
@pranavrajs , thank you for your reply. In my .env file, this variable is set without any value. I will try completely removing it and I will let you know.

# Sentiment analysis model file path
SENTIMENT_FILE_PATH=

**Comment by pranavrajs** [comment]
@dannylessio Sure, let me know.

**Comment by pranavrajs** [comment]
@dannylessio Anyway I have added [a check here](https://github.com/chatwoot/chatwoot/pull/8401) to avoid false positives.

**Comment by dannylessio** [comment]
@pranavrajs, awesome, thanks. I can confirm that without the 'SENTIMENT_FILE_PATH' environment variable, the job Enterprise::SentimentAnalysisJob is not starting anymore.
