### ISSUE TITLE
Unable to create database

### ISSUE THREAD

**Issue by matthewwwillard** [chatwoot/chatwoot#836]
**Describe the bug**
Unable to run 'bundle exec rake db:create'

**To Reproduce**
Following instructions on Quick Setup

**Expected behavior**
Init database

**Screenshots**

**Additional context**
Ubuntu Server (Latest as of 5/8)
RAILS_ENV set to production.
[db_results.txt](https://github.com/chatwoot/chatwoot/files/4601702/db_results.txt)

**Comment by pranavrajs** [comment]
@matthewwwillard 

1. What is the version of Chatwoot you are using?
2. Did you complete the dependency installation step? https://www.chatwoot.com/docs/quick-setup#install-ruby-dependencies

**Comment by matthewwwillard** [comment]
@pranavrajs 

1. Latest, pulled yesterday.
2. Yep! Followed the quick setup! 
![Screen Shot 2020-05-09 at 12 51 26 PM](https://user-images.githubusercontent.com/30221119/81479837-d5e73000-91f3-11ea-9f75-3d95782f4d43.png)

**Comment by pranavrajs** [comment]
@sojan-official Can you please take a look at this?

```
NameError: uninitialized constant ActiveSupport::EventedFileUpdateChecker::Listen
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:9:in `without_bootsnap_cache'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `rescue in load_missing_constant'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:59:in `load_missing_constant'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3/lib/active_support/evented_file_update_checker.rb:113:in `boot!'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3/lib/active_support/evented_file_update_checker.rb:68:in `initialize'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/factory_bot_rails-5.2.0/lib/factory_bot_rails/reloader.rb:24:in `new'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/factory_bot_rails-5.2.0/lib/factory_bot_rails/reloader.rb:24:in `build_reloader'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/factory_bot_rails-5.2.0/lib/factory_bot_rails/reloader.rb:16:in `run'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/factory_bot_rails-5.2.0/lib/factory_bot_rails/railtie.rb:22:in `block in <class:Railtie>'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `instance_exec'
/home/cadenzait/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3/lib/rails/initializable.rb:32:in `run'
```

**Comment by sojan-official** [comment]
@matthewwwillard just found this -> https://github.com/rails/rails/issues/36158  while investigating. This could be a problem with the installation somehow. can you check the GEM_PATH that's being set ?

btw if you are intending to use in production, I would suggest using caprover .  we also have a ubuntu installation script https://github.com/chatwoot/chatwoot/blob/develop/deployment/setup.sh , the documentation is still lacking on both these options. we are still working on that.  

meanwhile, let me continue investigating this further.

**Comment by matthewwwillard** [comment]
Thanks for the updates! I'll try giving caprover a try!

I tried the install script and it seems that RVM is having issues in sudo, as well as issues with the GEM_PATHs. Checking that out!

**Comment by matthewwwillard** [comment]
So dropping down to Ubuntu Server 18.04 LTS from 20.04 LTS seems to have resolved this issue.

**Comment by sojan-official** [comment]
@matthewwwillard  thanks for reporting this. we will debug the script over a 20.04 machine.

**Comment by pranavrajs** [comment]
@matthewwwillard We have updated the script to work on 20.04. Can you please take a look and see if it is working for you? Please see the updated documentation at https://www.chatwoot.com/docs/deployment/deploy-chatwoot-in-linux-vm
