### ISSUE TITLE
November Docker release ?

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#8363]
### Describe the bug

Hello, folks.

I am looking forward some fixes made last month, and Since I am used to see the prod releases being published every 15th, do you expect to publish the november release anytime soon?

Regards,

### To Reproduce

November Docker Release

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
@vagner-dias  We will be publishing the image on 17 th friday
