### ISSUE TITLE
 v3.3.0 :: The message pane DISAPEARED! :: Docker installation :: Whatsapp Channel 

### ISSUE THREAD

**Issue by vagner-dias** [chatwoot/chatwoot#8379]
### Describe the bug

After the update to  v3.3.0 on Docker installation, the message pane **disapeared** on Chrome and Firefox

I have already tried to clean the browser cache, but that did not fix the issue.

Here is the screenshot:

![image](https://github.com/chatwoot/chatwoot/assets/86367839/270d9295-3492-4099-ad30-88618c9f8f8c)

### To Reproduce

1. stop chatwoot docker
2. Update the docker installation
**My update process:**
docker-compose down
docker pull chatwoot/chatwoot:latest
docker-compose run --rm rails bundle exec rails db:chatwoot_prepare
docker-compose up -d

4. Start chatwoot docker
5. Open chatwoot in the browser

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome 119.0.6045.160 / Firefox 119.0.1 

### Docker (if applicable)

**docker version**
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.3
 Git commit:        24.0.5-0ubuntu1~22.04.1
 Built:             Mon Aug 21 19:50:14 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.3
  Git commit:       24.0.5-0ubuntu1~22.04.1
  Built:            Mon Aug 21 19:50:14 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.2
  GitCommit:        
 runc:
  Version:          1.1.7-0ubuntu1~22.04.1
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        

<br><br><br><br><br><br><br>

**docker info**
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 11
  Running: 11
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-86-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 3.726GiB
 Name: docker01
 ID: 36dce6aa-6541-4e48-81fe-4348ac85af70
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

<br><br><br><br><br><br><br>

**docker-compose version**
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

**Comment by vagner-dias** [comment]
@sojan-official , Just FYI, I believe this is a serious bug, since it is prevents users from using the app.

**Comment by jtayrone** [comment]
The same happens in the non-containerized version! Serious bug.

**Comment by jtayrone** [comment]
![falha exebir mensagem](https://github.com/chatwoot/chatwoot/assets/34479816/ee1bd4e2-74ca-4686-8396-3c34c1292dbc)

@pranavrajs

**Comment by agebeyaw** [comment]
It happens also for Website and Telegram inboxes, and I think it is not specific to WhatsApp.

**Comment by hheexx** [comment]
Website chat WFM

**Comment by clairton** [comment]
fix with PR #8381 8381
