### ISSUE TITLE
Keycloak SSO Integration for User Authentication in Chatwoot

### ISSUE THREAD

**Issue by david-billian** [chatwoot/chatwoot#8385]
### Is your feature or enhancement related to a problem? Please describe.

Experiencing difficulties with Chatwoot user authentication, specifically the lack of a smooth integration with Keycloak Single Sign-On (SSO).

### Describe the solution you'd like

Desire a seamless integration between Chatwoot and Keycloak Single Sign-On (SSO) to elevate the user authentication experience.

### Describe alternatives you've considered

Explored alternatives such as custom authentication solutions, investigated the potential exclusivity of the SSO feature to the enterprise version, and evaluated other identity providers. However, a direct integration with Keycloak SSO is the preferred and optimal solution for our specific needs.

### Additional context

**Questions:**
- Can Chatwoot be integrated with Keycloak Single Sign-On (SSO) for user authentication?
- If not available, is this feature exclusive to the enterprise version?
- What are the plans or considerations for implementing Keycloak SSO integration in Chatwoot?

**Context:** Seeking clarification on the feasibility of integrating Chatwoot with Keycloak Single Sign-On (SSO). Any available context or screenshots would be helpful in understanding the feature request.

**Comment by pranavrajs** [comment]
SSO integration is available in the enterprise edition. Please reach out to us sales@chatwoot.com if you are interested.
