### ISSUE TITLE
listen to facebook/instagram events

### ISSUE THREAD

**Issue by pablopolanco6** [chatwoot/chatwoot#8392]
### Is your feature or enhancement related to a problem? Please describe.

how can i listen or consume the fb or ig events because apart from the messages i need to consume other events through another application and meta only allows me one webhook so it would be to consume it directly from chatwoot.

### Describe the solution you'd like

any webhook to consume these services

**Comment by pranavrajs** [comment]
@pablopolanco6 We don't support any other events other than the ones that are required for the application. 

The ideal way to do it is to set up a webhook to an application outside of Chatwoot and forward the ones that are relevant to Chatwoot.
