### ISSUE TITLE
ArgumentError: invalid uri scheme

### ISSUE THREAD

**Issue by MatheusRich** [chatwoot/chatwoot#84]
I'm trying to get chatwoot runinng locally and during the setup I got this error (`ArgumentError: invalid uri scheme ''`)  after running `bundle exec rake db:create`.

This happens because when the redis initializer runs it calls `uri = URI.parse(ENV['REDIS_URL'])`, and the env REDIS_URL is empty (see `application.yml`).

How to get this working in development?

**Comment by pranavrajs** [comment]
@MatheusRich Hope you have followed the setup guide. Please see the following section to setup the redis URL. If it works please feel free to close the issue.

https://docs.chatwoot.com/#/development/project-setup/environment-variables?id=configure-redis-url

**Comment by MatheusRich** [comment]
Whoops, I didn't know this exist at all :sweat_smile:. Maybe we should link it on README.md (which was what I was following)

**Comment by pranavrajs** [comment]
@MatheusRich Added a link to detailed documentation [here](https://github.com/chatwoot/chatwoot#detailed-documentation)

I've also added a Common errors section [here](https://docs.chatwoot.com/#/development/project-setup/errors?id=argumenterror-invalid-uri-scheme) 

I'm closing this issue, please feel free to reopen the issue if the above didn't fix the issue.
