### ISSUE TITLE
Support for LinkedIn Page Message

### ISSUE THREAD

**Issue by tobsowo** [chatwoot/chatwoot#8403]
### Is your feature or enhancement related to a problem? Please describe.

New inbox for LinkedIn.

### Describe the solution you'd like

LinkedIn just introduced messages for Pages, I believe it will be a great add to Chatwoot.

https://www.linkedin.com/help/linkedin/answer/a1356464

**Comment by pranavrajs** [comment]
There are no APIs, unless they offer one we cannot support it.
