### ISSUE TITLE
 WhatsApp Cloud Templates with Media do not appear.

### ISSUE THREAD

**Issue by sebavieira** [chatwoot/chatwoot#8411]
### Describe the bug

All templates with WhatsApp Cloud API text and buttons appear in chatwoot, however, when I look for a template with media, be it PDF, Image or Video, it does not appear.

### To Reproduce

![bug 1](https://github.com/chatwoot/chatwoot/assets/24707969/dd84ed46-cf49-403b-b825-566ff1cd5531)

![bug 2](https://github.com/chatwoot/chatwoot/assets/24707969/dcceb441-1ee2-418b-8d58-b492e1db03f9)

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by pranavrajs** [comment]
Duplicate #6867
