### ISSUE TITLE
404 error in Reports

### ISSUE THREAD

**Issue by fabiocmazzo** [chatwoot/chatwoot#842]
** 404 error in reports page **
I'm using a docker version 1.4.1 of chatwoot and when i open reports numbers dont update. 
I check network conections and get 404 errors in this URLs:

`/api/v1/accounts/3/reports/1/account_summary?since=1588636800&until=1589241599`

and 

`/api/v1/accounts/3/reports/account?metric=conversations_count&since=1588636800&until=1589241599`

I checked code and found account_summary method in reports_controller in  v2 API. 

Do I need to change the call to the new endpoint in VueJs? 

Thank you

**Comment by pranavrajs** [comment]
@fabiocmazzo This has been fixed and released as a separate release v1.4.2
