### ISSUE TITLE
Line group chat

### ISSUE THREAD

**Issue by aekasamo** [chatwoot/chatwoot#8427]
### Is your feature or enhancement related to a problem? Please describe.

Line allow group chat and need to new contact as group

### Describe the solution you'd like

 - New contact by groupid/roomid
 - Display profile of group
 - Reply to groupid/roomid

```[tasklist]
### Tasks
```

**Comment by pranavrajs** [comment]
Chatwoot is intended to be used for 1:1 conversations except in the email channels. We will not support this.
