### ISSUE TITLE
Instagram: instagram_manage_messages Facebook approval rejected

### ISSUE THREAD

**Issue by pelucapampa** [chatwoot/chatwoot#8434]
### Describe the bug

When i submit a facebook app review for instagram_manage_messages, facebook team rejected and add this comment on rejecting process.

Have you any suggestions about that?

**Hi Team!

We have determined that your app's use case for the requested permission is valid. Upon reviewing the application, we found that your app does not comply with the quality guidelines and other specific requirements for Instagram Messaging in our technical documentation.

To resolve this issue, visit our Instagram Messaging documentation and ensure that your app meets our requirements, including:

- Proper handling of media CDN URLs by not storing/caching the media content.

For more details on submission requirements please visit our app review documentation for Instagram Messaging:
https://developers.facebook.com/docs/messenger-platform/instagram/app-review
https://developers.facebook.com/docs/messenger-platform/instagram**

### To Reproduce

Chatwoot Version: 3.2.1

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by shivamkb17** [comment]
I have the same problem, when I talked to support and send them the story mention and story reply media file URL. they told me that, images that are sent to you by customer , also must have CDN url, not to save any media file in your storage.

**Comment by pelucapampa** [comment]
Hi @pranavrajs could you re-open this issue and merge with #8512 created for me, and #8498 
I think it's same problem, history image CDN URL it's resolved but Image sent need to save CDN URL similar than History Image to obtain facebook approval.
Thank you so much
