### ISSUE TITLE
[CW-2818] Docker image triggers 40+ CVE because package.json/yarn.lock

### ISSUE THREAD

**Issue by thgh** [chatwoot/chatwoot#8436]
### Describe the bug

These files should not be included in the Docker image as they trigger irrelevant warnings.

### To Reproduce

* docker pull chatwoot/chatwoot
* Open docker desktop > Images
* Result:

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/ace52e90-5523-4009-80e1-59a58e746b58/a53c7b28-434a-404b-a415-ff7d43c59d72?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi9hY2U1MmU5MC01NTIzLTQwMDktODBlMS01OWE1OGU3NDZiNTgvYTUzYzdiMjgtNDM0YS00MDRiLWE0MTUtZmY3ZDQzYzU5ZDcyIiwiaWF0IjoxNzAxMzk5OTk1LCJleHAiOjE3MDE0ODYzOTV9.rylOnmyjYUIsoAe8VgqP9dkJJBMsDAil9zbcUpH1cgI)

### Expected behavior

No vulnerabilities

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

*No response*

### Browser and version

*No response*

### Docker (if applicable)

Docker  24.0.6

### Additional context

Note that all layers are scanned, so removing the files in the final layer does not resolve this. I think a multi-stage build would resolve this and result in a smaller image.

<sub>From [SyncLinear.com](https://synclinear.com) | [CW-2818](https://linear.app/chatwoot/issue/CW-2818/docker-image-triggers-40-cve-because-packagejsonyarnlock)</sub>

**Comment by pranavrajs** [comment]
@thgh Most of the listed packages are not used in production; they are just build dependencies. We have a project underway to switch from Webpack to a newer build tool, such as Vite, which should resolve these issues.
