### ISSUE TITLE
web hook send attachments URLs incorrectly formated when using AMAZON storage.

### ISSUE THREAD

**Issue by cifuentesmx** [chatwoot/chatwoot#8437]
### Describe the bug

In a docker self-hosted environment using a docker image `chatwoot/chatwoot:v3.2.0`, when using Amazon storage the webhook sends a malformed URL for attachments.

### To Reproduce

1. using `chatwoot/chatwoot:v3.2.0` docker image
2. with Amazon storage configured `ACTIVE_STORAGE_SERVICE=amazon`
3. with the `message created` webhook enabled sends an image message
4. the webhook sends a malformed URL in the payload.

``` js
{
  attachments: [
    {
      id: 22,
      message_id: 502,
      file_type: 'image',
      account_id: 1,
      extension: null,
      data_url: 'http://https/rails/active_storage/blobs/redirect/eyJfcm...[cropped]...28.png',
      thumb_url: 'http://https/rails/active_storage/representations/redirect/eyJfcm...[cropped]...28.png',
      file_size: 61186
    }
  ]
}
```

### Expected behavior

The attachments URLs should be correctly formed, e.g. 'https://chatwoot.com/rails/active_storage/blobs/redirect/eyJfcm...[cropped]...28.png'

instead of 
'http://https/rails/active_storage/blobs/redirect/eyJfcm...[cropped]...28.png'

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

using docker on linux

### Browser and version

edge latest (irrelevant)

### Docker (if applicable)

docker chatwoot v3.2.0 running on railway.app

**Comment by pranavrajs** [comment]
@cifuentesmx We can't reproduce this issue on our end. We use Amazon in our production systems. It's possible that the text is truncated in the logs, not in the actual payload.

**Comment by cifuentesmx** [comment]
this is the actual payload that I'm receiving from chatwoot web hook. Logs are not incomplete , 
I cropped the last part of the URL. the problem is the start part of the URL: `http://https/rails` instead of `https://mydomain.com/rails`

```js
{
  attachments: [
    {
      id: 22,
      message_id: 502,
      file_type: 'image',
      account_id: 1,
      extension: null,
      data_url: 'http://https/rails/active_storage/blobs/redirect/eyJfcm...[cropped]...28.png',
      thumb_url: 'http://https/rails/active_storage/representations/redirect/eyJfcm...[cropped]...28.png',
      file_size: 61186
    }
  ]
}
```

**Comment by cifuentesmx** [comment]
It was working fine with local storage, but as soon as I implemented aws-s3 I noticed failures in my endpoint handling the webhook.

**Comment by cifuentesmx** [comment]
It turned out that as always my bad.
It was a misconfiguration issue. My apologies for the time taken! Thanks.
