### ISSUE TITLE
Chatwoot shouldn´t alter file name

### ISSUE THREAD

**Issue by luiztonucci** [chatwoot/chatwoot#8440]
### Is your feature or enhancement related to a problem? Please describe.

Chatwoot has altered the file name, this is bad.

### Describe the solution you'd like

keep the file name because the user prefer like this.

**Comment by pranavrajs** [comment]
@luiztonucci, Can you please describe the issue in detail? There is not much information on where this issue happens and how we can reproduce it. Please add relevant screenshots & screencasts to help reproduce the behavior.

**Comment by luiztonucci** [comment]
Hi, @pranavrajs, sorry, I identified the problem is witch the API Evolution and isn´t witch Chatwoot. I opened an issue on the API Evolution resquesting altered. Thank you for your attention.

**Comment by luiztonucci** [comment]
It's not a problem with chatwoot but with the API used.
