### ISSUE TITLE
broken (websocket) chat receive in v3.3.0 , v3.3.1

### ISSUE THREAD

**Issue by w0aw** [chatwoot/chatwoot#8483]
### Describe the bug

on fresh install, when create first contact with name & email and an api inbox , select the contact and send message. message sent sometimes ,but most of the times it fails after some time, when i inspected "/cable" websocket connection there was infinite message update event coming with a failed state. and when i sent message using public api (as an contact) they got sent but on dashboard websocket never receive those untill i refresh the page. 

### To Reproduce

env- k8s (using official helm chart)

Config - everything is default only redis and postgres are selfhosted.

reproduce - install helm chart with image tag v3.3.0 & v3.3.1 and login to dashboard , create a contact , create api inbox , send message to contact using api inbox and inspect websocket messages in network tab, copy the contact source_id and inbox_id & conversation_id from dashboard and use postman to hit public message api "/public/api/v1/inboxes......" and send message it will return success but never comes on dashboard untill we do a page refresh.

### Expected behavior

after revert back to v3.2.0 , everything is working smooth

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

### Operating system

macos sonoma

### Browser and version

chrome latest

### Docker (if applicable)

v3.3.1

**Comment by sojan-official** [comment]
@w0aw  Ddi you run the migrations post upgrading ? could you share server error logs ?

**Comment by w0aw** [comment]
@sojan-official thanks for responding quickly.

 i was running chatwoot using your official helm chart, i think this chart automatically handle migrations, everything was normal in log, eg.- websocket conn established and etc, (because each api was working wine). even i tried to find some error or verbose logs but just normal.

now i think issue chould be with your websocket implementation. by inspecting websocket messages in network tab, browser actually sends update_presence event but not receives even response back (each 20-30 seconds). however browser receives ping & welcome messages from server and then after some time websocket ping messages got flooded like 10-20 messages per sec.    

i think issue chould be like in code websocket connection is not closed properly. [ i had seen these issues whenever chatwoot server runs idle].  now i dont know still these bugs exists or not as i moved to other solutions. 

you guys can close issue if others are not facing this issue, my jab was to let you know. thats it. 

Again Thank you

**Comment by w0aw** [comment]
@sojan-official i have reinstalled and tried again. same problem. here i have logs - 

browser network tab- 
<img width="1093" alt="Screenshot 2024-02-25 at 4 28 29 PM" src="https://github.com/chatwoot/chatwoot/assets/103448473/ac0d3a28-eb8e-40d1-94b7-b0008b5b0c18">

POD - chatwoot-web
<img width="1615" alt="Screenshot 2024-02-25 at 4 29 00 PM" src="https://github.com/chatwoot/chatwoot/assets/103448473/ff54e8d0-0809-4647-b3d7-4951b53bb576">

POD - chatwoot-worker
<img width="748" alt="Screenshot 2024-02-25 at 4 31 16 PM" src="https://github.com/chatwoot/chatwoot/assets/103448473/39568f13-4b94-47a6-bd14-8a42d4b94b46">

i hope it will help, but there is nothing wrong in logs
