### ISSUE TITLE
Telegram - Unable to Send Audio Clips from Agent Side

### ISSUE THREAD

**Issue by saduni-udeshika** [chatwoot/chatwoot#8499]
### Describe the bug

Currently, within the Telegram channel integration, agents are experiencing difficulties sending audio messages. Despite successful attempts to send audio clips from the agent side, users are not receiving these messages in their Telegram inbox.

### To Reproduce

1. Access the Chatwoot platform with a Telegram channel integrated.
2. Navigate to the agent interface.
3. Attempt to send an audio message to a user through the Telegram channel.
4. Verify that the audio message is sent successfully from the agent side.
5. Check the user's Telegram inbox to confirm that the audio message is not received.

### Expected behavior

Audio messages sent by agents through the Telegram channel should be successfully delivered to users' Telegram inboxes, allowing for seamless communication.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

ubuntu 20.04

### Browser and version

Chrome 93

**Comment by saduni-udeshika** [comment]
I'm interested in working on this issue. Could you please assign it to me? I'll start working on it right away.

**Comment by amaljosea** [comment]
Facing the same issue here


<img width="1512" alt="Screenshot 2023-12-16 at 4 30 35 PM" src="https://github.com/chatwoot/chatwoot/assets/26934320/2cfce384-c6fa-4587-ae5e-6e81c3413301">
