### ISSUE TITLE
Write documentation for setup in Mac OS

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#85]
We have a dependencies section in our development guide. We currently have the Ubuntu installation guide. We need to add macOS development guide

https://www.chatwoot.com/docs/installation-guide-ubuntu

**Comment by enderahmetyurt** [comment]
I can write could you assign me this issue?

**Comment by enderahmetyurt** [comment]
Thanks @pranavrajs 🙏

**Comment by pranavrajs** [comment]
Please read the contributing guidelines as well :) 

https://github.com/chatwoot/chatwoot/blob/master/docs/contributing.md

**Comment by moises995** [comment]
Hello, do you still need help? By the way a question how do you work to do the documentation?

**Comment by enderahmetyurt** [comment]
no thanks. i will do it @moises995

**Comment by Mardiie** [comment]
You can't really speak of an installation guide if you only help people with setting up dependencies. I'm pretty sure most people are able to install ruby or nodejs. I do not think that most people know how to actually get YOUR project up and running. And for that no info is available at all.

**Comment by pranavrajs** [comment]
@Mardiie https://www.chatwoot.com/docs/quick-setup/ Please see if this helps.

**Comment by Mardiie** [comment]
I have read everything and repeat my statement. You only install dependencies

**Comment by sojan-official** [comment]
@Mardiie Installation of the rails app and seeding the default data is usually enough for a chatwoot to be up and running. you can further customize the installation via environment variables https://www.chatwoot.com/docs/environment-variables  

If you could share the areas which you found difficult in terms of setting up chatwoot, the team can work on improving it.

**Comment by Mardiie** [comment]
> 
> 
> @Mardiie Installation of the rails app and seeding the default data is usually enough for a chatwoot to be up and running. you can further customize the installation via environment variables https://www.chatwoot.com/docs/environment-variables
> 
> If you could share the areas which you found difficult in terms of setting up chatwoot, the team can work on improving it.

At what point of your quick setup do you point to your own files on github and what to do with those?
I know what ruby is, i know you use it in your app, thats about it.
How am i going to setup your application without that information?
I get a source from github, help with installing dependencies, but no information about what to do with your source next to were to setup the environmental variables.
Do i run a node file? Do i compile first? I assume? Your guide does not say anything about it!
I don't understand why you have a guide if you dont step by step go through your progress.
How can someone decide if they want to use your product if it's not even clear how to completely set it up?
