### ISSUE TITLE
feat: (Export ) Add Confirmation and Limit the Email to Initiating User

### ISSUE THREAD

**Issue by LiamAshdown** [chatwoot/chatwoot#8504]
On the contacts page, when the export button is used, there should ideally be a confirmation dialog. Additionally, the current export functionality emails all administrators, whereas I expected it to only email the exported contacts to the user who initiated the action (myself), not everyone.

<img width="1560" alt="Screenshot 2023-12-06 at 11 19 02" src="https://github.com/chatwoot/chatwoot/assets/43280985/439bb55e-481b-450f-aed9-47cd096e6bc0">

### Describe the solution you'd like

1. Show a confirmation modal before actioning the export: this would prevent a misclick or unintentional clicking of the export button.
2. Only send the exported contacts to the logged-in user who actioned the export, not to all administrators.

**Comment by sojan-official** [comment]
@LiamAshdown, this makes sense. We will have this on our backlog for the upcoming release. Would be happy to accept any community PRs for this as well.
