### ISSUE TITLE
Image Rotation on Preview

### ISSUE THREAD

**Issue by brunosfg** [chatwoot/chatwoot#8507]
### Is your feature or enhancement related to a problem? Please describe.

Every time a customer sends an image that is upside down or sideways, you have to right-click, save the image, and use an image viewer that supports the rotation function. 

This process can be quite time-consuming, particularly when dealing with multiple images or when the image in question is a document containing extensive text.

Here is an example:

![Example](https://github.com/chatwoot/chatwoot/assets/88198838/d640ebb1-b3a5-4a5f-a052-f379dd7d85fe)

### Describe the solution you'd like

It would be great to have a rotate button on image preview screen.

### Describe alternatives you've considered

It would be helpful if the media viewer had a button (maybe next to download button) that simply rotates the image without leaving Chatwoot.

**Comment by pranavrajs** [comment]
@brunosfg Thanks for the suggestion, this would a nice addition. We would accept a PR if there is anyone interested in contributing this feature.

**Comment by LiamAshdown** [comment]
@pranavrajs I'll have a crack at this :)

**Comment by pranavrajs** [comment]
@LiamAshdown Sure, go ahead.

**Comment by LiamAshdown** [comment]
> @LiamAshdown Sure, go ahead.

Pull request opened.
