### ISSUE TITLE
Issue with Chatwoot Syncing and GSuite Email

### ISSUE THREAD

**Issue by dannylessio** [chatwoot/chatwoot#8514]
### Describe the bug

Description:
I have been using Chatwoot for over a week, but this morning, I noticed that the entire Chatwoot platform was essentially unusable. After investigating, I discovered that the synchronization with one of our GSuite email accounts had become unusually slow, taking over 10-15 minutes to complete. This slow sync triggered a new job in Sidekiq for the same task, effectively blocking all other processes.

Temporary Solution:
To mitigate the issue, I temporarily disabled the IMAP credentials for that particular GSuite email account, cleared the Sidekiq queues, and restarted Sidekiq. This seemed to resolve the problem temporarily.

Issue Recurrence:
However, when I re-enable the IMAP credentials for the GSuite email account, the problem resurfaces. It takes over 10 minutes to complete (without errors)

### To Reproduce

I cannot reproduce this with another email (i'm receiving almost the same email amount, and the other email is syncing below 30s)

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Windows 10

### Browser and version

Chrome 119.0.6045.200

### Docker (if applicable)

Docker version 20.10.21
Docker Compose version v2.12.0

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.12.0)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 15
  Running: 14
  Paused: 0
  Stopped: 1
 Images: 15
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.63GiB
 ID: LCUU:QDEX:GWJN:ENH3:H4SX:EY47:R6XA:7BL3:PFS6:FFSF:KTVI:O6FH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by dannylessio** [comment]
Strange, the following day everything was syncing correctly

**Comment by dannylessio** [comment]
I'm re-experiencing this issue, it also happened with another email account (Gsuite)

**Comment by dannylessio** [comment]
@pranavrajs, Could you please help me on how can I debug this? I've tried adding debug environment logging variables, but they do not help me understand what is going on. Many thanks

**Comment by pranavrajs** [comment]
@dannylessio Sorry, this was overlooked. We have added a fix for this here. https://github.com/chatwoot/chatwoot/pull/8730 The fetch is stabilized now. You should be able to use it in 3.6.0 (Feb 15 release)

Closing this for now. We will re-open if this issue still persist after the release.
