### ISSUE TITLE
Out of Memory during install on Linux VM

### ISSUE THREAD

**Issue by HClausing** [chatwoot/chatwoot#8555]
### Describe the bug

I'm trying to install into a 4vCores and 3,5 GB VRam Virtual Machine, and getting "Javascript heap out of memory" error during 6/9 stage (Installing chatwoot):

![image](https://github.com/chatwoot/chatwoot/assets/15158923/6d73039c-95fa-496d-b6be-73a363808aaa)

I've read another issues recommending to use at least 2GB RAM, 2Cores and 1GB Swap, but my VM is higher than that requirements.

Is there any task missing from my part?

Thanks.

### To Reproduce

1) Created a clean Linux VM into Hyper-V (Windows Server 2019);
2) [Followed these instructions](https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm)

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

Windows Server 2019 as host, Ubuntu Server 20.04.3 VM

**Comment by jochenstu** [comment]
"4GB RAM is the required minimum memory size"

"Note: Add at least 1GB of swap memory to the machine to ensure that the machine doesn't run out of resources during an upgrade."

https://www.chatwoot.com/docs/self-hosted/deployment/requirements#memory

**Comment by pranavrajs** [comment]
@HClausing We have added a perf improvement here to fix the build issues. https://github.com/chatwoot/chatwoot/pull/8394 We will have a release on Dec 15 with this update. I will close it until the release. If it is still an issue, we can reopen it.

**Comment by HClausing** [comment]
> @HClausing We have added a perf improvement here to fix the build issues. https://github.com/chatwoot/chatwoot/pull/8394 We will have a release on Dec 15 with this update. I will close it until the release. If it is still an issue, we can reopen it.

Thank you. With 5.5gb It worked also.
