### ISSUE TITLE
Undefined Table: "response_documents" does not exist 

### ISSUE THREAD

**Issue by atlcodecommandr** [chatwoot/chatwoot#8556]
### Describe the bug

Just setup 3.3.1 and getting this when clicking on Documents in Super Admin

### To Reproduce

Login to Super Admin
Select Documents of Responses

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
Please disable `response_bot` feature from your admin console. This is happening because of missing pg_vector extension in your database. The feature is not ready for production yet.
