### ISSUE TITLE
action cable not change chatwootPubsubToken in setUser

### ISSUE THREAD

**Issue by s00d** [chatwoot/chatwoot#8567]
### Describe the bug

Good day, there is currently a huge problem with setUser. When it's called, the pubsubToken doesn't change.

That is, your logic is currently like this, the page loads, the token is set in window.onload

```js
window.actionCable = new ActionCableConnector(
    window.WOOT_WIDGET,
    window.chatwootPubsubToken
  );
```
If you call setUser in the SDK after this, the chat dies and to restore it, you need to reload the page to get a new token.

https://github.com/chatwoot/chatwoot/blob/e5c8a68a7663d2653985e7333db0ec4b07e3cc81/app/javascript/packs/widget.js#L50

### To Reproduce

1. Launch the chat
1. Set a new user
1. After this, the chat dies

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

any

### Browser and version

any

**Comment by s00d** [comment]
o restore functionality, it's enough to reload the page, but essentially, the chat is completely broken right now.

**Comment by s00d** [comment]
Please take a look at my fix.

**Comment by pranavrajs** [comment]
Thanks for raising this. However, I don't think the token should change when the setUser is called. Can you please share a screencast of the issue?

**Comment by s00d** [comment]
> Thanks for raising this. However, I don't think the token should change when the setUser is called. Can you please share a screencast of the issue?

The problem is very relevant; it's enough to just call setUser without a restart, and the chat will die until the page is reloaded. I'm also attaching my test script.

![2023-12-15 23 53 49](https://github.com/chatwoot/chatwoot/assets/2684895/5f05ad1d-4036-4c7b-b16a-4eab0bac32b9)
[chatwoot_local2.html.zip](https://github.com/chatwoot/chatwoot/files/13688852/chatwoot_local2.html.zip)

**Comment by pranavrajs** [comment]
@s00d We don't change the session identifier (contact_inbox) when you use setUser. Only the associated contact is changed. I'm not sure if this change makes sense. It seems that you have customized the codebase. Can you reproduce this in Chatwoot cloud?

**Comment by s00d** [comment]
> @s00d We don't change the session identifier (contact_inbox) when you use setUser. Only the associated contact is changed. I'm not sure if this change makes sense. It seems that you have customized the codebase. Can you reproduce this in Chatwoot cloud?

The issue is also reproducible in the cloud. I made some adjustments to the script to pinpoint the problem. When changing the user, the chat dies and the token gets changed.

[chatwoot_local2.html.zip](https://github.com/chatwoot/chatwoot/files/13711125/chatwoot_local2.html.zip)

**Comment by s00d** [comment]
An example situation when this occurs for a client:

The user visits the website as a guest.
The user logs in to their account.
If the website uses a single-page application (SPA), then the chat functionality dies.

**Comment by muhsin-k** [comment]
https://github.com/chatwoot/chatwoot/pull/8568#issuecomment-3355365143
