### ISSUE TITLE
Unable to Access Super Admin Account

### ISSUE THREAD

**Issue by YasserSpeed** [chatwoot/chatwoot#8575]
### Describe the bug

 I encountered while attempting to access the Super Admin account. Below are the details of the error message:

Couldn't find SuperAdmin with [WHERE "users"."type" = $1 AND "users"."email" = $2]

Steps to Reproduce:

Error Details:

The error suggests a problem in locating the Super Admin user with the specified conditions. It appears to be related to the query logic used to fetch the Super Admin user from the database.

Expected Behavior:

I expect to access the Super Admin account without encountering any errors.

Actual Behavior:

The error message mentioned above prevents successful access to the Super Admin account.

Environment:

    System/Platform Version: Docker Version
    Browser/Device: Firefox
    Operating System:  Ubuntu 20.04

### To Reproduce

    Log in to the system/platform.
    Attempt to access the Super Admin account.
    Encounter the error message mentioned above.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Firefox  120.0.1 (64-bit)

### Docker (if applicable)

root@Chatwoot:~# docker version
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:07:41 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by pranavrajs** [comment]
@YasserSpeed This is expected. There are no users associated with the given credentials. We have updated the error message [here](https://github.com/chatwoot/chatwoot/pull/8406/files).

**Comment by pranavrajs** [comment]
Closing it here for now. Feel free to reopen the issue if you think there is a bug.
