### ISSUE TITLE
Email notification to agent is not working

### ISSUE THREAD

**Issue by shivamkb17** [chatwoot/chatwoot#8577]
### Describe the bug

Email notification to agent is not working in all type of notification. 
Inbox assignment mail notification recieve by the agent's mail, 
But when new message in inbox and agent is offline, Then I think , agent must be notified, but in this case, agent is not getting mail related to new message in inbox. 

### To Reproduce

I am using ubuntu 20.04 LTS Linux installation. 
1. Install chatwoot using official guide. 
2. add SMTP credential in the chatwoot configuration. 
3. restart chatwoot
4. Add several agent in the new installation
5. create a new inbox, and assign a conversation to the agent. ( Here agent is getting notification on mail new conversation assign )
6. now after sometime agent is offline, also status is marked as offline, 
7. send new message in that same conversation. 
8. now assigned conversation agent in not getting email notification. 
9.

### Expected behavior

The agent must get notification, when new message in assigned conversation arrived.

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 20.04 LTS

**Comment by pranavrajs** [comment]
If the notification for new messages is not turned on, the agent will get the email notification. This is disabled by default. 

If this is not the case, please share any relevant error logs to debug this further.

**Comment by RashRAJ** [comment]
@pranavrajs i have a similar issue and i keep getting this error from the logs. p.s my maling configurations are correct

`ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [7d96297b-63a3-44bf-b79a-79f65cdf581b] Error performing ActionMailer::MailDeliveryJob (Job ID: 7d96297b-63a3-44bf-b79a-79f65cdf581b) from Sidekiq(default) in 59.4ms: SocketError (getaddrinfo: Name does not resolve):`

**Comment by pranavrajs** [comment]
@RashRAJ, please check your SMTP credentials. They are failing. `SocketError (getaddrinfo: Name does not resolve)`

**Comment by RashRAJ** [comment]
@pranavrajs I have confirmed my SMTP credentials over and over; they are accurate.

**Comment by shivamkb17** [comment]
I have email notification is not turned on.

**Comment by shivamkb17** [comment]
Now it is working fine.
