### ISSUE TITLE
Instagram approval rejected via handling of media CDN URLs by not storing/caching the media content

### ISSUE THREAD

**Issue by ultraza4** [chatwoot/chatwoot#8583]
### Describe the bug

re-opening issue from this https://github.com/chatwoot/chatwoot/issues/8434
When i submit a facebook app review for instagram_manage_messages, facebook team rejected and add this comment on rejecting process.

**Hi Team!
We found that your app does not comply with the quality guidelines and other specific requirements for Instagram Messaging in our technical documentation.

To resolve this issue, visit our Instagram Messaging documentation and ensure that your app meets our requirements, including:

- Proper handling of media CDN URLs by not storing/caching the media content.
**

Hi @pranavrajs, History image CDN URL it's resolved but Image sent need to save CDN URL similar than History Image to obtain facebook approval.

![photo](https://github.com/chatwoot/chatwoot/assets/103424892/2cc3727e-f4b4-4dcf-bf56-dcc304b203cb)

Thank you so much

### To Reproduce

Chatwoot Version: 3.2.1

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by galamshar** [comment]
Hi, @ultraza4, i have same problem. If you find any solution, keep updated!

**Comment by pranavrajs** [comment]
We are deleting the attachments and everything related to the message if the message is deleted from Instagram. If this is still an issue, I would suggest looking at the logs and see if there is an error which can help us debug the issue. 

Closing this here to as there is no information helping us to debug this properly.

**Comment by pelucapampa** [comment]
Hello @pranavrajs , if sending images within messages is treated the same as Stories in terms of saving the image URL, it will surely be corrected, but when saving the image URL locally when it is sent via Instagram Direct, I think that's the drawback.
Is it possible not to save the local URL of the sent image and use the same logic as in Instagram Stories?

**Comment by pranavrajs** [comment]
@pelucapampa I'm not sure about this requirement. For stories you can't store it because it would expire in 24hr. However, for images or other attachment sent as regular message, there is no reason to complicate the setup to fetch dynamically from the CDN everytime.

**Comment by pelucapampa** [comment]
@pranavrajs thanks for your reply, but facebook reject instagram message approval process because chatwoot save image URL locally for image on Instagram Direct. on #8512 I refer and show that.
Thanks

**Comment by egejo** [comment]
@pranavrajs Please reopen the issue as it is not solved and as such Instagram advance permits revision is impossible to pass on current version of chatwoot. Here we are having same issue and response from Meta, improper handling of media and CDN, chatwoot still caching images locally and that is a big NO for meta.

**Comment by ultraza4** [comment]
> @pranavrajs Please reopen the issue as it is not solved and as such Instagram advance permits revision is impossible to pass on current version of chatwoot. Here we are having same issue and response from Meta, improper handling of media and CDN, chatwoot still caching images locally and that is a big NO for meta.

Totally agree, @pranavrajs it is impossible to get advance Instagram permits without fixing it. Please help us

**Comment by deivisonrpg** [comment]
@pranavrajs @sojan-official please take a look at this.

**Comment by pixelsstudiove** [comment]
Hello. Has anyone been able to resolve this?

**Comment by ultraza4** [comment]
> Hello. Has anyone been able to resolve this?

unfortunately, no. Just waiting)

**Comment by pixelsstudiove** [comment]
Temporal solution: #8512
