### ISSUE TITLE
wrong numbers of conversations in the overview page

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#8588]
### Describe the bug

wrong numbers of conversations in the overview page

### To Reproduce

wrong numbers of conversations in the overview page

![2023-12-20_09h02_55](https://github.com/chatwoot/chatwoot/assets/121224467/5ac68408-be53-4854-9ca9-72c94db0201c)

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
@Double-Click-ERP There is no information to debug the issue. Please reopen the issue with any relevant logs.
