### ISSUE TITLE
Identifier is too long (maximum is 255 characters)

### ISSUE THREAD

**Issue by toantk911** [chatwoot/chatwoot#8593]
### Describe the bug

When the website reloaded, the api "/api/v1/notification_subscriptions" call got error 422 with message "Identifier is too long (maximum is 255 characters)"
![Screenshot 2023-12-21 at 14 14 26](https://github.com/chatwoot/chatwoot/assets/23357519/75e298f8-3303-4ce2-a82d-6f1ef6a13281)

### To Reproduce

1. Refresh browser webapp

### Expected behavior

No error and browser can show notifications

### Environment

Kubernetes

### Cloud Provider

None

### Platform

Browser

### Operating system

MacOS

### Browser and version

Edge

**Comment by pranavrajs** [comment]
Closed this as this is no longer an issue. Please test the latest version to see if you can reproduce the error.
