### ISSUE TITLE
After upgrade to >= 3.1 version, high bandwidth call to US

### ISSUE THREAD

**Issue by thanhpd56** [chatwoot/chatwoot#8595]
### Describe the bug

After we upgrade to version >= 3.1, our monthly Google cloud billing increase significantly.
We investigate by Grafana and see that the outgoing traffic increased significantly after upgrade.
I already disable telemetry, but nothing changes.

### To Reproduce

Upgrade to version 3.1, and see the traffic analytic.

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

None

### Docker (if applicable)

3.1

**Comment by sojan-official** [comment]
@thanhpd56 We haven't added anything additional in telemetry. Please share additional information on network calls being made.

**Comment by thanhpd56** [comment]
> @thanhpd56 We haven't added anything additional in telemetry. Please share additional information on network calls being made.

Hi, thanks for your response.
Below are the grafana network metric:
Before upgrade:
![image](https://github.com/chatwoot/chatwoot/assets/3794898/af635ef0-8cff-49b4-b6fd-8ff734ba9ccc)
After upgrade:
![image](https://github.com/chatwoot/chatwoot/assets/3794898/68172a2e-32ef-4359-82ad-a26a125c9580)
From gcloud billing:
<img width="411" alt="image" src="https://github.com/chatwoot/chatwoot/assets/3794898/f2aa180f-1835-4a05-a255-bfdfc30b2550">

**Comment by sojan-official** [comment]
@thanhpd56 I can't spot anything specific from the provided information. Which channels do you use primarily in your Chatwoot installation ? the only calls Chatwoot should be making to external services would the required API calls for external channels like whatsapp and also for integrations like openai

**Comment by thanhpd56** [comment]
The first time we faced to this issue, then I had to downgrade to version 3.0. Recently I upgraded to version 3.2 but the issue still happend, so I have to downgrade again. :(

**Comment by pranavrajs** [comment]
Closing this here as we don't have enough information to debug this further. Please feel free to re-open this with information to debug.
