### ISSUE TITLE
Allow programmatically to send a message from the widget

### ISSUE THREAD

**Issue by virus2016** [chatwoot/chatwoot#8601]
### Is your feature or enhancement related to a problem? Please describe.

It's necessary for us to have the capability to programmatically send a message (either public or private) from the website the visitor is on. For instance, if they click on a help button, we should automatically transmit a message in the widget saying, "Hey, type here for help," and simultaneously compose a private message as an option for an agent to provide assistance.

### Describe the solution you'd like

user does something > we send them a message direct to chatwoot using widget functions > we take notes on what they are struggling on (also widget)

No requirement for SDK integration

**Comment by pranavrajs** [comment]
Similar [https://github.com/chatwoot/chatwoot/issues/8143](https://github.com/chatwoot/chatwoot/issues/8143)
