### ISSUE TITLE
Upgrade Warning

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#8606]
### Describe the bug

Upgrade Warning :
> /usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/imap_xoauth_authenticator.rb:31: warning: Net::IMAP.add_authenticator is deprecated.  Use Net::IMAP::SASL.add_authenticator instead.

> /usr/local/rvm/gems/ruby-3.2.2/gems/gmail_xoauth-0.4.2/lib/gmail_xoauth/imap_xoauth2_authenticator.rb:24: warning: Net::IMAP.add_authenticator is deprecated.  Use Net::IMAP::SASL.add_authenticator instead.

> I, [2023-12-24T08:58:08.694979 #233075]  INFO -- : Migrating to AddSnoozedUntilToNotifications (20231129091149)
> == 20231129091149 AddSnoozedUntilToNotifications: migrating ===================
> -- add_column(:notifications, :snoozed_until, :datetime)
>    -> 0.2852s
> == 20231129091149 AddSnoozedUntilToNotifications: migrated (0.2854s) ==========
> 
> I, [2023-12-24T08:58:09.026660 #233075]  INFO -- : Migrating to RemoveNotificationsWithMessagePrimaryActor (20231201014644)
> == 20231201014644 RemoveNotificationsWithMessagePrimaryActor: migrating =======
> 2023-12-24T06:58:09.066Z pid=233075 tid=56br INFO: Sidekiq 7.2.0 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379", :password=>nil, :reconnect_attempts=>2, :timeout=>1}
> I, [2023-12-24T08:58:09.068281 #233075]  INFO -- : [ActiveJob] Enqueued Migration::RemoveMessageNotifications (Job ID: be00d7be-6758-4291-ba11-44af0a910458) to Sidekiq(scheduled_jobs)
> == 20231201014644 RemoveNotificationsWithMessagePrimaryActor: migrated (0.0401s) 
> 
> I, [2023-12-24T08:58:09.087731 #233075]  INFO -- : Migrating to AddCachedLabelsList (20231211010807)
> == 20231211010807 AddCachedLabelsList: migrating ==============================
> -- add_column(:conversations, :cached_label_list, :string)
>    -> 0.0977s
> == 20231211010807 AddCachedLabelsList: migrated (0.5375s) =====================
> 
> I, [2023-12-24T08:58:09.653831 #233075]  INFO -- : Migrating to ReRunCacheLabelJob (20231219000743)
> == 20231219000743 ReRunCacheLabelJob: migrating ===============================
> I, [2023-12-24T08:58:12.321220 #233075]  INFO -- : [ActiveJob] Enqueued Migration::ConversationCacheLabelJob (Job ID: 765284a4-ca85-4751-b121-e46cb8836365) to Sidekiq(async_database_migration) with arguments: #<GlobalID:0x00007f99a80d4398 @uri=#<URI::GID gid://chatwoot/Account/2>>
> == 20231219000743 ReRunCacheLabelJob: migrated (2.6658s) ======================
> 
> Loading Installation config

### To Reproduce

upgrade from v3.3.1 to v3.4.0

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
This is a known warning, there will not be any issue with these.
