### ISSUE TITLE
Issue with Message Duplication and Failed Send in Facebook Messenger Inbox

### ISSUE THREAD

**Issue by YasserSpeed** [chatwoot/chatwoot#8607]
### Describe the bug

I have encountered after upgrading to version 3.4.0 of the system.

The problem arises when responding to Facebook Messenger inbox messages through Chatwoot. Upon replying, the text appears duplicated in the Chatwoot interface, with one instance indicating a failed send and an adjacent "retry" icon. Interestingly, upon clicking the retry icon, the message is successfully sent to the customer. However, the duplicated text and the need for manual retry are causing inconvenience.

Attached is a screenshot illustrating the appearance of the message in question.
![01](https://github.com/chatwoot/chatwoot/assets/5084983/70823fc8-64e1-4004-85ec-f4d05c967d32)

### To Reproduce

just reply to any massage from messenger facebook inbox

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu

### Docker (if applicable)

latest

**Comment by pranavrajs** [comment]
@YasserSpeed Can you please share any error logs which help us to debug the issue?

**Comment by shivamkb17** [comment]
@YasserSpeed Please check, do you enabled response bot for this in superadmin panel, If enabled, remove this.

**Comment by sojan-official** [comment]
We are closing this since there hasn't been a follow-up on this issue. Will reopen if this persists even after updating Chatwoot to the latest version.
