### ISSUE TITLE
Cant send message via website widget  getting NameError (undefined local variable or method `response_sources' f

### ISSUE THREAD

**Issue by RashRAJ** [chatwoot/chatwoot#8609]
@civilcoder55   I am facing the same issue refrenced here, please how do i disable response_bot cant find the feature anywhere  
 
              
Try to disable response_bot for the account and try again, it should solve the problem 
If you want to enable the feature, make sure your database is migrated and response_bot related tables are created
![image](https://github.com/chatwoot/chatwoot/assets/58332033/83fe15a1-8982-43a9-9e50-59431b3d73fe)

_Originally posted by @civilcoder55 in https://github.com/chatwoot/chatwoot/issues/7767#issuecomment-1685030804_

**Comment by r0bbie** [comment]
Disabling response\_bot also fixed this issue for me, although I'm not sure why it was happening on a fresh install? What migration needs to be run exactly to create the response\_bot required tables referenced? (or was this a bug that's being fixed in an upcoming release etc?)
