### ISSUE TITLE
Super Admin CSS issue

### ISSUE THREAD

**Issue by DblK** [chatwoot/chatwoot#8615]
### Describe the bug

Since I updated to `3.4.0` there are some issues :
![Screenshot 2023-12-26 at 19 31 20](https://github.com/chatwoot/chatwoot/assets/832617/d7897e7b-8f1e-4a0b-992a-ed47a7116b79)

The class `h-10` is no where to be found in any css file.
On top of that `Super Admin` is not working at all...

However the whole app seems to work as expected for the `Chat` part.

### To Reproduce

1. Install a previous version (`3.1.0`)
2. Run `cwctl --upgrade`
3. Watch `3.4.0` Super-Admin
4. Bad design and nothing is working

### Expected behavior

Working as previous...

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux (Ubuntu 22.04)

### Browser and version

Chrome 120

**Comment by pranavrajs** [comment]
We can't reproduce this issue, please re-install or re-compile the assets.
