### ISSUE TITLE
Video call in client inbox not showing

### ISSUE THREAD

**Issue by sandisunandar99** [chatwoot/chatwoot#8617]
### Describe the bug

Dear chatwoot team. 

I have issue while using feature video call with dyte integration. This issue I found from inbox client that not show when start meet. But in chatwoot console its not problem, just in inbox client.

![Screenshot 2023-12-27 (2)](https://github.com/chatwoot/chatwoot/assets/6767399/1e551885-a699-438b-93b4-a49e6856914d)

image from chatwoot console not problem :

![Screenshot 2023-12-27 (3)](https://github.com/chatwoot/chatwoot/assets/6767399/bedc3011-9351-4be8-ae1f-f7479b04224a)

I hope any solution or advice. thanks before

### To Reproduce

1. fixing bug when start video call in inbox client

### Expected behavior

video call in client inbox can show

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Chrome : Version 120.0.6099.130, Firefox :  Version 121.0

**Comment by SamuelFCorrea** [comment]
Same problem here :'(

### Browser and version
Microsoft Edge Version 120.0.2210.91

**Comment by pranavrajs** [comment]
This is a confirmed bug, we will have a resolution soon.

**Comment by sandisunandar99** [comment]
thanks @pranavrajs
