### ISSUE TITLE
New WhatsApp messages not appear in notifications until after refresh page.

### ISSUE THREAD

**Issue by iiihexiii** [chatwoot/chatwoot#8620]
### Is your feature or enhancement related to a problem? Please describe.

New messages not appear in notifications until after refresh page.

### Describe the solution you'd like

how to make it appear in the same time it sent and no need to refresh page.

**Comment by shivamkb17** [comment]
did you checked your chatwoot application in diffrent browser , Also check is web-socket connection showing error?

**Comment by iiihexiii** [comment]
checked but same

**Comment by pranavrajs** [comment]
@iiihexii There is no information to debug the issue or even to understand what the issue. Please re-open the issue with a screencast and the relevant logs to help us debug what the issue.
