### ISSUE TITLE
Iphone app not notice me 

### ISSUE THREAD

**Issue by sunkeinfo** [chatwoot/chatwoot#8630]
### Describe the bug

iPhone app does not notice me when 

a new customer starting talk on websites!!!

### To Reproduce

Iphone app not notice me when a new customer starting talk on websites !!!

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Mobile

### Operating system

Iphone

### Browser and version

chrome   last

**Comment by sunkeinfo** [comment]
when i login IOS APP ,  and after 1 minite ,   the website showing me as  OFFLINE  !! 

How to keep me online ?????   then my website visitors aways talking a  online support ???

**Comment by pranavrajs** [comment]
Please disable this option. 

![Screenshot 2024-01-05 at 12.12.21 PM.png](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/e14f803e-086d-4ab6-a655-1965d56f526b/e36f28fc-2671-402a-bc19-ae9ab332023d)

**Comment by sunkeinfo** [comment]
> Please disable this option.
> 
> ![Screenshot 2024-01-05 at 12.12.21 PM.png](https://camo.githubusercontent.com/963d016411b62e6f96c3a2b0b6d320604624852b8169167e2d872fb9c4878cb1/68747470733a2f2f75706c6f6164732e6c696e6561722e6170702f32383437663762392d326361612d343734632d623236312d3163396264633261356461362f65313466383033652d303836642d346162362d613635352d3139363564353666353236622f65333666323866632d323637312d343032612d626331392d616539616233333230323364)

Thanks for your reply !    But your screenshot picture can not be open . can u add the picture again ???

**Comment by pranavrajs** [comment]
Updated.
