### ISSUE TITLE
Instagram messages are received, but not sending

### ISSUE THREAD

**Issue by vasilibrutsky** [chatwoot/chatwoot#8634]
### Describe the bug

Dear Chatwoot team, 

I'm trying to set up Messenger inbox for Instargam Business account. I receive messages, but can't send them.
I get error that inbox can't be found, however, I am able to see it in the database. Upgrading to latest version didn't help.

ERROR -- : [ActiveJob] [Avatar::AvatarFromUrlJob] [fc89d4aa-7326-488e-9bd4-ccc54259bc69] Skipping job because of ActiveJob::DeserializationError (Error while trying to deserialize arguments: Couldn't find Inbox with 'id'=26)

![image](https://github.com/chatwoot/chatwoot/assets/5662401/25fad49e-ea17-4ddd-99a9-9ba085398861)

### To Reproduce

1. Set up Chatwoot Linux VM Instance
2. Set up instagram business acc
3. Set up Inbox in Chatwoot
4. Send Message from Instagram acc to chatwoot
5. Message will be received, but reply does not work

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

**Comment by shivamkb17** [comment]
@vasilibrutsky  how did you fix this?

**Comment by vasilibrutsky** [comment]
@shivamkb17 the problem was with test mode, it's not available to receive webhooks from Chatwoot. To fix this, use production mode and have conversation between two admins: instagram and facebook

**Comment by jordan26** [comment]
@vasilibrutsky - have you successfully gone through the Facebook verification process for the API etc? I'm in that process currently, so any step by step process you took to complete (if so) would be appreciated. Happy to discuss outside of GH if easier too.
