### ISSUE TITLE
Whatsapp Template doesnot auto sync with Meta ( No Media file in template ) 

### ISSUE THREAD

**Issue by shivamkb17** [chatwoot/chatwoot#8636]
### Describe the bug

Hi team,  I Am facing it in chatwoot self hosted, 
The Whatsapp Template is not auto syncing from facebook bussiness. While creating channel, 

### To Reproduce

1. Install Chatwoot latest version
2. Create Whatsapp Channel
3. Go to Meta bussiness and create a new whatsapp message template , Wait for some time, whatsapp template is approved. 
4. Now come into chatwoot, and try to send message to newly created template. 
5. The newly created whatsapp template is not showing there. 

### Expected behavior

Expected behavior will be the whatsapp new template must show in the template message. 

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

### Operating system

UBUNTU 20.04 LTS

### Additional context

I Have also check by restarting chatwoot, and VPS for the template update, but newly created template is not syncing with the chatwoot.

**Comment by pranavrajs** [comment]
Duplicate #8569

**Comment by muhsin-k** [comment]
Fixing via https://github.com/chatwoot/chatwoot/pull/12007
