### ISSUE TITLE
Misstake in word "visitors" (vistors)

### ISSUE THREAD

**Issue by topisun** [chatwoot/chatwoot#8638]
### Describe the bug

Outside available hours **vistors** can be warned with a message and a pre-chat form.

### To Reproduce

Settings -> inboxes -> Business Hours

### Expected behavior

Outside available hours **visitors** can be warned with a message and a pre-chat form.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by sojan-official** [comment]
@topisun  Thanks for the report. We will have this fixed
