### ISSUE TITLE
Facebook Integration not Receive Messages

### ISSUE THREAD

**Issue by fabiocmazzo** [chatwoot/chatwoot#864]
**Version 1.4.2**
I'm integrate with Facebook following instructions and a valid Facebook Application. Facebook validates webhook em my_end_poing/bot. 

After create inbox and trying receive a message, inbox dont receive the message and i view in log this messages:

`Ignoring read (no hook registered)
Ignoring message (no hook registered)`
![Screenshot from 2020-05-14 21-10-27](https://user-images.githubusercontent.com/3148792/81997877-6627d980-9627-11ea-9ccd-b73af9bba95d.png)

Thank You

**Comment by pranavrajs** [comment]
@fabiocmazzo What is the API version you are using? We are debugging the issue with v7.0. API version until v6.0 works fine.

**Comment by fabiocmazzo** [comment]
@pranavrajs I'm using version v7.0, i'm go back to v6.0 to test.

**Comment by fabiocmazzo** [comment]
Same result :(

**Comment by sojan-official** [comment]
@fabiocmazzo  we have a fix for this in work. it should be merged in by today/tomorrow.

**Comment by pranavrajs** [comment]
Fixed via #863

**Comment by pranavrajs** [comment]
@fabiocmazzo Could you please try the develop branch build, there was an error with auto_loading. Now the feature is working fine and is upgraded to use v7.0 API
