### ISSUE TITLE
Whatsapp Reaction

### ISSUE THREAD

**Issue by Cauen** [chatwoot/chatwoot#8656]
### Is your feature or enhancement related to a problem? Please describe.

Today, Whatsapp reactions hit the backend, but nothing happens in the conversation. It would be ideal to have a message demonstrating the customer's reaction so as not to lose this information.

### Describe the solution you'd like

A new message on the conversation, like replies.

**Comment by pranavrajs** [comment]
@Cauen We will not be building this as it would require us to support other platforms as well. I understand the need for feature, however we will not prioritize anytime soon.
