### ISSUE TITLE
Ability to disable username/password if OAuth is available

### ISSUE THREAD

**Issue by jgupta** [chatwoot/chatwoot#8657]
### Is your feature or enhancement related to a problem? Please describe.

We have Google OAuth enabled. We want to disable usual username/password for security reasons.

### Describe the solution you'd like

A environment flag that would disable usual username/password

**Comment by pranavrajs** [comment]
@jgupta Can you please share the security concerns, you can disable the signup if you would like using the ENABLE_ACCOUNT_SIGNUP flag? 

Closing this here for now as we would not be prioritizing it immediately. I can re-open this if there is a major security concern.
