### ISSUE TITLE
Feature: Organize Agents into teams 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#866]
It's difficult to manage agents in chatwoot system if the number of agents is huge. Let's introduce teams/permission management at a higher level to mitigate this.  

todo: explore the idea further.

**Comment by AwakenTheJaken** [comment]
+1 for this, we were planning on using chatwoot 🚀 as a replacement for Livezilla 🤮 but without this feature and the ability to route a user to a specified team it makes it difficult for us to make the jump.

**Comment by pranavrajs** [comment]
API for this is merged, will be continuing the work in 1.13.0
