### ISSUE TITLE
Option to disable the visibility of agents from the All tab

### ISSUE THREAD

**Issue by luiztonucci** [chatwoot/chatwoot#8662]
### Is your feature or enhancement related to a problem? Please describe.

Currently, agents can see all conversations through the everyone tab. When the company has sectors, especially sectors such as finance and management, the conversation becomes visible, it's not cool.
In the company I work for, we have the financial and management sectors, where conversations must be restricted. However, an agent can see the conversation if it is not assigned.

### Describe the solution you'd like

Create an option for the Admin to enable and/or disable the visualization of agents in relation to important sectors of the company.

**Comment by hereck** [comment]
Esse link tem alguma solução para o caso? É possível liberar acesso ao workspace?
[PR-838 Option to disable the visibility of agents from the All tab](https://linear.app/chatwoot/issue/PR-838/option-to-disable-the-visibility-of-agents-from-the-all-tab)

> [PR-838 Option to disable the visibility of agents from the All tab](https://linear.app/chatwoot/issue/PR-838/option-to-disable-the-visibility-of-agents-from-the-all-tab)

Esse link da acesso a alguma solução para o caso? Se sim é possível liberar o acesso ao workspace?

**Comment by pranavrajs** [comment]
duplicate [https://github.com/chatwoot/chatwoot/issues/4216](https://github.com/chatwoot/chatwoot/issues/4216)
