### ISSUE TITLE
Telegram bot chats are not loading

### ISSUE THREAD

**Issue by fulminet** [chatwoot/chatwoot#8665]
### Describe the bug

I installed Chatwoot through CapRover, then I configured my telegram bot and configured it through api:

> https://api.telegram.org/bot[TOKEN]/setWebhook?url=https://[FRONTEND]/webhooks/telegram/[TOKEN]

And then I set a default message that must respond as soon as the bot is started. So far everything is working fine. Except that when I click on the messages to Read the loading no longer ends. I've been trying for a few days but nothing, solutions?

### To Reproduce

1

### Expected behavior

![ProvaChatWoot](https://github.com/chatwoot/chatwoot/assets/151919499/e86438db-2e3a-4598-958a-ab9e26d18ebc)

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Caprover

**Comment by fulminet** [comment]
![issue](https://github.com/chatwoot/chatwoot/assets/151919499/d62b7af4-3a97-4e62-8231-9e43e2166c33)

**Comment by sojan-official** [comment]
@fulminet did you enable web socket support. ? 

ref: https://www.chatwoot.com/docs/self-hosted/deployment/caprover/#3-finish-the-setup

**Comment by theMeysam** [comment]
> @fulminet did you enable web socket support. ?
> 
> ref: https://www.chatwoot.com/docs/self-hosted/deployment/caprover/#3-finish-the-setup

I have same problem.
I checked Websocket Support but unfortunately I cant receive message from telegram bot

**Comment by sojan-official** [comment]
please refer https://discord.com/channels/647412545203994635/1190544035149000704/1194493243400917023

**Comment by theMeysam** [comment]
> please refer #7485

according this refer I check my bot webhook by:
GET https://api.telegram.org/bot{your_bot_token}/getWebhookInfo
and all thing is correct but I cant receive any message yet :-(
![Screenshot 2024-01-11 031621](https://github.com/chatwoot/chatwoot/assets/42879302/37634b3d-7dc9-471c-93df-d0cbed15794d)

**Comment by theMeysam** [comment]
also when I make an api Chanel, when I try [Create New Conversation](https://www.chatwoot.com/developers/api/#tag/Conversations/operation/newConversation) it show bellow error:

`{
"body": 
{
"status": 
500,
"error": 
"Internal Server Error"
},
"headers": 
{
"server": 
"nginx",
"date": 
"Thu, 11 Jan 2024 00:16:31 GMT",
"content-type": 
"application/json; charset=UTF-8",
"content-length": 
"46",
"connection": 
"close",
"x-request-id": 
"40e6f575-23de-49e5-8aac-9d6d56197e53",
"x-runtime": 
"0.033645"
},
"statusCode": 
500,
"statusMessage": 
"Internal Server Error"
}`

**Comment by fulminet** [comment]
Enabling "websocket" works, i.e. I send a message and see the messages. The problem happens if I leave the chat and return it no longer loads anything and gives me the following error.
![screen issue](https://github.com/chatwoot/chatwoot/assets/151919499/dc27f833-5e33-4044-b4fc-d409ce83ce5e)
