### ISSUE TITLE
Feature: Ability to mute contacts

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#867]
Use Case
-------------
Sometimes the agents might get spam messages through the widget. In order for it to not affect the productivity of the agent, the system should give the ability to temporarily block the contact. 

Acceptance Criteria
--------------
When an agent blocks a conversation,  the conversation should get marked as resolved.  Any new incoming messages to the conversation wouldn't reopen it until the block period is expired. 

There wouldn't be any visual indicator on the widget side, the contact will still be able to keep sending the messages. 

UI Mock
----------

![Screenshot 2020-05-21 at 8 16 21 AM](https://user-images.githubusercontent.com/73185/82517741-664e3a80-9b3b-11ea-8d2e-cbb3892d268b.png)

to be refined by : @nithindavid  @pranavrajs 

Implementation Guidelines 
----------------

- Add a constant for the mute period, let's explore with `6 hours`.
- a new API endpoint in conversations controller for blocking/muting the conversation 
  - when the endpoint is hit the conversation is marked as resolved 
  - the conversation id is added to a Redis set which denoted muted conversation 
- Change the existing `reopen_conversation` method in `message.rb` to add additional logic that ensures muted conversations aren't reopened. 
- Front End code to handle the click on mute contact trigger

**Comment by kadir96** [comment]
@sojan-official  Is there any implementation details, acceptance criteria regarding this feature? I might be interested in working on this feature.

**Comment by sojan-official** [comment]
@kadir96 I have updated the issue with acceptance criteria and an implementation guideline. But feel free to explore better approaches at your discretion. 
Feel free to ask additional questions if you have any.

**Comment by kadir96** [comment]
@sojan-official Thanks for the details! As you know, you can start new conversation using incognito mode. What should we do if someone muted starts new conversation through incognito mode?

**Comment by pranavrajs** [comment]
@kadir96 This has to be dealt with IP address blocking. At the moment we are not including that in the scope considering the privacy policy updates required. This can be done once the steps for GDPR/CCPA compliance measures are in place.

**Comment by kadir96** [comment]
@sojan-official @pranavrajs Is unmuting also in the scope?

**Comment by sojan-official** [comment]
@kadir96  let's take that up in the next iteration. With the way the current block link is positioned, the chances of accidental blocking seem to be very less. 
So let's get on with an MVP and work over it based on the feedback.

**Comment by kadir96** [comment]
Sure! I just completed the backend logic and started implementing frontend logic. Most Probably I will PR tomorrow.
