### ISSUE TITLE
Ability to customize push notifications, just like email notifications

### ISSUE THREAD

**Issue by hipur** [chatwoot/chatwoot#8690]
### Is your feature or enhancement related to a problem? Please describe.

Push notifications for my use case, specially on mobile, don't show essential information.

### Describe the solution you'd like

Fields to customize the notification on the account settings page.

### Describe alternatives you've considered

A runbook describing the procedures to customize push notifications, just like there's a runbook on how to customize email notifications.
https://www.chatwoot.com/docs/self-hosted/configuration/email-notifications/

### Additional context

![image](https://github.com/chatwoot/chatwoot/assets/44179292/502c9486-a7ff-4757-9538-039ed381c4d0)

**Comment by pranavrajs** [comment]
We will not support customization here in fact we are going to deprecate the customization email notifications as it is creating unnecessary maintenance overhead for us. 

Having said, understood the point around not having the data. Please check [this](https://twitter.com/chatwootapp/status/1760760779207537079) and see if you find anything missing there which we should add.
