### ISSUE TITLE
Agent Analytics Message Received Count  always 0

### ISSUE THREAD

**Issue by saduni-udeshika** [chatwoot/chatwoot#8696]
### Describe the bug

The Agent Analytics module is displaying an inaccurate count for the "Message Received" metric, consistently showing 0 despite active communication.

![image](https://github.com/chatwoot/chatwoot/assets/60056888/0a086c9b-9175-4fb6-9456-3b8333acaa32)

### To Reproduce

1. Access the Chatwoot dashboard.
2. Navigate to the "Reports" section.
3. Navigate to the "Agents" section.
4. Observe that the count is consistently displayed as 0, even when agents are actively receiving messages.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

ubuntu 20.04

### Browser and version

Chrome 93

**Comment by adayush** [comment]
I'm also facing this issue. I only use the API channel with chatwoot, not sure if it occurs for other channels too

**Comment by sojan-official** [comment]
Note: This section in the reports is intended to be displayed only for conversation reports and not for the other reports. This is a bug. We will be removing this section from other reports.

**Comment by jmelati** [comment]
Same problem here. Any solution?

**Comment by abehnamfard** [comment]
fixed by https://github.com/chatwoot/chatwoot/pull/10415

**Comment by sojan-official** [comment]
> #10415
