### ISSUE TITLE
Accounts cant be confirmed because the link in the email is not working. (CAPROVER)

### ISSUE THREAD

**Issue by JakubJeziorski** [chatwoot/chatwoot#8697]
### Describe the bug

I was able to recive the confirmation email, but when I click it, I am moved to: https://chatwoot.domainname.com/app/auth/confirmation?confirmation_token=ASL4JxKj4ARrBmc7Ndg3
When visiting this link, I see the following error:
![image](https://github.com/chatwoot/chatwoot/assets/32456116/3d9287d4-a5f2-449d-be3c-083bc01100ed)

### To Reproduce

1. Install Chatwoot using 1 click app on Caprover using version v3.4.0 - Hosted on Hetzner
2. Add SMTP credentials (SendGrid)
3. Get a confirmation email
4. Click on it, see error as shown above

### Expected behavior

That link should somehow lead to a website where I can confirm agent account. 

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows

### Browser and version

Vivaldi	6.5.3206.53 (Stable channel) (64-bit)

**Comment by JakubJeziorski** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/32456116/6917dbc5-4b3b-4063-a6ca-deab270bc350)

Chatwoot-web:
![image](https://github.com/chatwoot/chatwoot/assets/32456116/b246193e-095d-415f-b6b4-dd519f98c78a)

Here is Chatwoot Worker:
![image](https://github.com/chatwoot/chatwoot/assets/32456116/1d53451f-bbdc-49fd-b7f4-e8fbf51476d7)


I wasnt sure where those SMTP environment variables should be added, so I added them to a worker.

**Comment by pranavrajs** [comment]
@JakubJeziorski Unfortunately, we are not maintaining this ourselves anymore. So we can't help much. 

General issues we have seen: 

1 - Both web and worker should have exact copy of the environment variables.
2 - Web or worker is not running
3 - FRONTEND_URL is not configured properly (missing config or invalid path added here)
