### ISSUE TITLE
Microsoft Email Channel is not getting created

### ISSUE THREAD

**Issue by csyedbilal** [chatwoot/chatwoot#8698]
### Describe the bug

Completed Azure App registration, testing in both single and multi-tenant applications.
Adhered to the Azure APP setup guidelines on the Chatwoot website.
Set up the Azure App ID and Secret in the environment file.
Restarted Chatwoot.
However, the problem arises after clicking "Sign-in with Microsoft Work" and opening the Microsoft consent page. Upon approving the consent form, the system redirects back to the app website, but unfortunately, no mail channel is created. Instead, it simply redirects to the Chatwoot website URL.

### To Reproduce

Set up Azure App registration.
Follow Chatwoot guidelines for Azure APP setup.
Configure Azure App ID and Secret in the environment file.
Restart Chatwoot.
Click "Sign-in with Microsoft Work."
Approve the consent form.
Observe the redirection issue and the absence of the expected mail channel.

### Expected behavior

After approving the consent form, the system should create the Microsoft Mail channel instead of redirecting to the Chatwoot website URL without any channel creation.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04 LTS

### Browser and version

Latest 

### Additional context

domain is also verified and Publisher verification done

**Comment by csyedbilal** [comment]
anyone can help me with this issue ?

**Comment by jordan26** [comment]
I have the same issue.

**Comment by pranavrajs** [comment]
Hey everyone, closing this here in favor of https://github.com/chatwoot/chatwoot/issues/8869
