### ISSUE TITLE
Deployment Failure in Heroku

### ISSUE THREAD

**Issue by HO3OH** [chatwoot/chatwoot#8707]
### Describe the bug

no error message, click the Deploy button to start execution, are the default configuration, please check.

### To Reproduce

1. clicking the deply button to heroku

### Environment

Heroku

### Cloud Provider

Other [please specify in the description]

### Platform

None

**Comment by rafaelstelles** [comment]
Hi,

    Any news about this problem ? I went to test today, but error persistence.

**Comment by vishnu-narayanan** [comment]
@rafaelstelles @HO3OH Could you please share the error you are getting in heroku?

**Comment by pranavrajs** [comment]
Closing this here for now due to inactivity.
