### ISSUE TITLE
Help Center articles no longer accessible for editing after authoring Agent is deleted

### ISSUE THREAD

**Issue by aribn** [chatwoot/chatwoot#8718]
### Describe the bug

One of our internal users authored and published a set of Help Center articles, and everything initially behaved corrected in the editor and in the published Help Center. The author's Agent account was subsequently removed when they left the support team. 

Expectation: 
I expected their Help Center articles to continue to be available for editing/publishing by other active Help Center authors. 

What happened instead: 
The article listing for Help Center authors was missing/broken. No server-side errors were logged, but one client-side error prevented the app from working properly. 

The six articles are missing from the article list, presumably due to missing `o.articleAuthorName` client-side. 
![Screenshot 2024-01-16 at 9 18 23 PM](https://github.com/chatwoot/chatwoot/assets/34577/8869977a-5bb2-4e37-877d-fc38e743d905)

### To Reproduce

1. **Agent A** composes a new Help Center article. 
2. **Agent A** publishes article. 
3. Verify that article is accessible to **Agent B** in the Help Center editing tool and is accessible in the public Help Center. 
4. An admin (other than **Agent A**) deletes **Agent A** from Agents page in Chatwoot Settings. 
5. **Agent B** visits the Help Center article listing in the editing tool and can no longer see or edit the article. 

### Expected behavior

I would expect a Help Center article that was authored by a subsequently-deleted author should still be accessible in the Editor, and: 
- the author name is replaced by something generic like "Team Member", and/or 
- the Author field for the article can be updated to an existing Agent. 

### Environment

Other [please specify in the description]

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 20.04.2 LTS

### Browser and version

Chrome 120

### Docker (if applicable)

Chatwoot 3.5.0 running on Cloudron v7.6.3. 

### Additional context

I did find that if I can guess the full route of the individual article in the editor, I am able to access the editor and update the author. This isn't a real solution, but it does indicate that the issue is isolated to the article list.

**Comment by sojan-official** [comment]
@aribn  thanks for the report we will have this investigated and fixed

**Comment by aribn** [comment]
Very impressed by your team's speed on closing this!

**Comment by pranavrajs** [comment]
@aribn Noticed the comment today, couldn't judge whether this was a sarcasm. I thought I'd add a note on the fix as well . Here is the change which would fix the issue.https://github.com/chatwoot/chatwoot/pull/8756
