### ISSUE TITLE
API Access not Authorized After Upgrading to 3.5.0

### ISSUE THREAD

**Issue by cfelbertp** [chatwoot/chatwoot#8719]
### Describe the bug

Since version 3.5.0, I can no longer perform API queries that require admin rights with the access token of a user, even though this user is an admin.

### To Reproduce

Up to and including version 3.4.0, I can perform the following API query with an admin user and their access token, for example:

https://<domain>/api/v1/accounts/2/conversations/806/messages

The request is answered with status 200 and I get the expected result.

As of version 3.5.0, I receive a 401 response with the same request: "error": "Access to this endpoint is not authorised for bots"

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Docker (if applicable)

Chatwoot is installed via Cloudron.
Cloudron version: 7.6.3.
Host: Ubuntu 22.04.2 LTS

**Comment by TalisonSantana** [comment]
I have the same problem when using the API with a superAdm user token.
Hi, when trying to consult a contact on Chatwoot via API with an ADM user token, I am receiving the following error: "error": "Access to this endpoint is not authorized for bots", following request:
![image (1)](https://github.com/chatwoot/chatwoot/assets/88020776/ce2165a3-2333-4305-8419-1b7ee3173012)

cURL:
curl --location 'http://localhost:3000/api/v1/accounts/457/contacts/search?q=557999730139&sort=phone_number' \
--header 'api_access_token: HSckqdvGssm8RJcNknJoMe2e' \
User:
![image (1)](https://github.com/chatwoot/chatwoot/assets/88020776/40bcfd48-ad56-40c5-89bf-01a1268f1d39)

and I'm also getting 500 when trying to send a message with the token if super user:
NoMethodError (undefined method `assigned_inboxes' for nil:NilClass):
10:50:01 backend.1 |
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/policies/inbox_policy.rb:27:in `show?'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/api/v1/accounts/conversations/base_controller.rb:8:in `conversation'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/concerns/switch_locale.rb:24:in `set_locale'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/concerns/switch_locale.rb:16:in `switch_locale_using_account_locale'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/concerns/switch_locale.rb:24:in `set_locale'
10:50:01 backend.1 | /home/talison/Documentos/repositorios/chatroot/app/controllers/concerns/switch_locale.rb:11:in `switch_locale'

![image (3)](https://github.com/chatwoot/chatwoot/assets/88020776/b27beb23-d572-4dec-bbd9-f09e14772a82)

**Comment by sojan-official** [comment]
- This seems to be a case where the access token used belongs to a SuperAdmin. We are working on a fix for the same. meanwhile please use an admin token until then.

**Comment by sojan-official** [comment]
- we will be cutting a new hotfix release with this change
