### ISSUE TITLE
Campo obrigatório não informado na documentação

### ISSUE THREAD

**Issue by AlexSzefezuk** [chatwoot/chatwoot#8725]
### Describe the bug

No endpoint https://www.chatwoot.com/developers/api/#tag/Conversations-API/operation/newConversation
o campo contact_id não esta destacada como obrigatório. 

Porém em meus testes a criação de conversas só funciona com o envio dele. 

### To Reproduce

Post para /conversations

sem o envio do contact_id no body

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
Please use the following API calls 

```
# create contact 
curl  -X POST \
  'http://localhost:3000/public/api/v1/inboxes/ShWNVKJtQXb2hnq3WFQzDG1g/contacts' \
  --header 'Accept: */*' \
  --header 'Content-Type: application/json' \
  --data-raw '{

}'

# contact identifier is the source id which you received in response of the previous API call

# create conversation
curl  -X POST \
  'http://localhost:3000/public/api/v1/inboxes/ShWNVKJtQXb2hnq3WFQzDG1g/contacts/f2f8ce34-1a6d-470e-b65f-bc8e279ed718/conversations' \
  --header 'Accept: */*' \
  --header 'Content-Type: application/json' 
```
