### ISSUE TITLE
Can't send emails via sendgrid, failed emails marked as delivered

### ISSUE THREAD

**Issue by rbndg** [chatwoot/chatwoot#8727]
### Describe the bug

I'm reporting 2 issues.

1. I can't seem to be able to send emails using sendgrid, i have the following setup.

I am running chatwoot via docker image
env variables:

```
MAILER_SENDER_EMAIL=support@company.com
SMTP_DOMAIN=company.com
SMTP_ADDRESS=smtp.sendgrid.net
SMTP_PORT=587
SMTP_USERNAME=apikey
SMTP_PASSWORD=<SENDGRID API KEY>
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=true
```
```
ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [caeedf67-99b6-4024-9805-fc596e0a67d8] Error performing ActionMailer::MailDeliveryJob (Job ID: caeedf67-99b6-4024-9805-fc596e0a67d8) from Sidekiq(default) in 335.28ms: Net::SMTPFatalError (550 The from address does not match a verified Sender Identity. Mail cannot be sent until this error is resolved. Visit https://sendgrid.com/docs/for-developers/sending-email/sender-identity/ to see the Sender Identity requirements
```

I attempted to send emails via sendgrid using telnet and api key, so this confirms that sender email and api key is verified correctly on sendgrid

2. Emails are marked as delivered successfully with chatwoot UI, even though it has failed to deliver.  Within the logs this is considered as a warning which i think is incorrect. This is a false positive, since the email was never actually delivered

### To Reproduce

1. Setup a new instance of chatwoot
2. Verify domain and singe sender in sendgrid
3. Generate API key
4. Set .env variables as above
5. attempt to reply to support emails

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu 22.04.1 LTS

**Comment by rbndg** [comment]
I was able to send an email via sendgrid also via a small script with `node-mailer`, so the issue is something in chatwoot and/or config

**Comment by sojan-official** [comment]
- emails getting marked as delivered even when they are not is fixed in https://github.com/chatwoot/chatwoot/pull/8790
- for email inboxes / conversation continuity in website live Chat, please ensure that you have conversation continuity configured : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/conversation-continuity 

The env variables only take care of password reset and agent email. we can reopen the issue if those emails are not working.
