### ISSUE TITLE
Heroku Deploy Reaching Max Redis Connections

### ISSUE THREAD

**Issue by Voldemorten** [chatwoot/chatwoot#8738]
### Describe the bug

This is the exact same problem as this [previous issue](https://github.com/chatwoot/chatwoot/issues/6909), which was never answered
> With the default Heroku deploy, after moderate use for about 10-15 minutes the maximum Redis connection limit gets reached and the app crashes for about 5 minutes, then goes back online. The error in the logs is Redis::CommandError (ERR max number of clients reached):.
The Redis dyno is a small sized one and it looks like it has a maximum of 20 connections on Heroku.
Are there any environment variables I can use to make Chatwoot play nice with the 20 connection Redis dyno limit?

And @vishnu-narayanan asked
> How many agents/inboxes do you have?

But that was never answered. 

- I'm running self hosted on v.3.5
- Number of agents: 2
- Number of inboxes: 6 right now (4 email, 2 messenger), but the same problem happened with just two inboxes.
- The problem startet to appear as soon as we were 2 agents working on the site at the same time.

This is the instance stats:
<img width="421" alt="image" src="https://github.com/chatwoot/chatwoot/assets/8776117/8384cbaf-dc18-495d-9d89-b8655e68410e">

### To Reproduce

1. Run 3.5.0 self hosted
2. Add another agent besides admin
3. Add an inbox
4. When both agents are using the site, the redis error appers `Redis::CommandError (ERR max number of clients reached):`

### Environment

Heroku

### Cloud Provider

AWS

### Platform

Browser

**Comment by sojan-official** [comment]
@Voldemorten  Please try reducing the `RAILS_MAX_THREADS` environment variable.  the default is set to 5. each chatwoot thread takes up around 10 connections,

**Comment by Voldemorten** [comment]
Thanks. If any one is in doubt this is [heroku's redis performance characteristics](https://devcenter.heroku.com/articles/heroku-redis-technical-characterization) right now, so I adjusted the max threads accordingly to my setup.

**Comment by rafaelstelles** [comment]
@Voldemorten Hi, I'm performing installation the chatwoot in the heroku, but my initial installation timeout. You had this problem ?

**Comment by Voldemorten** [comment]
@rafaelstelles. No. No issues.
