### ISSUE TITLE
Image uploaded do S3 only show after I refresh the page

### ISSUE THREAD

**Issue by dnl4** [chatwoot/chatwoot#8760]
### Describe the bug

I use S3 for storing Chatwoot files; however, I am facing an issue where sometimes some files only appear after I refresh the page. I imagine that what is happening is that the frontend displays the message that includes the image as soon as the message is received, but the upload to S3 takes a few seconds longer.

Any ideas on how to resolve this?

[Cloud Provider]
Vultr

https://github.com/chatwoot/chatwoot/assets/23690346/b6e4c61b-4024-4fd3-9e57-c8f266a929dc

### To Reproduce

- Configure s3 to storage files
- Send to the current opened chat a file that would take some seconds to upload (mine has 8mb)

### Expected behavior

See image without refresh the page

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

MacOS 14.1.2 (23B92), but happens in any OS

### Browser and version

Chrome (also happens in any OS)

**Comment by vishnu-narayanan** [comment]
@dnl4 Could you try enabling `DIRECT_UPLOADS_ENABLED` and see if it helps?

ref: https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables/#enable-direct-upload-to-storage-cloud

**Comment by sojan-official** [comment]
This is a known issue : https://github.com/chatwoot/chatwoot/issues/1372 
Closing this since we have `DIRECT_UPLOADS` available
