### ISSUE TITLE
Migrate to Vite

### ISSUE THREAD

**Issue by sidwebworks** [chatwoot/chatwoot#8781]
### Is your feature or enhancement related to a problem? Please describe.

I think its high time we should start looking into replacing the build tooling with Vite instead of Webpack/Webpacker. HMR doesn't really work anymore, legacy webpack plugins which keep leaking memory, takes forever to build, etc.

### Describe the solution you'd like

this project https://vite-ruby.netlify.app/guide/migration.html#webpacker-%F0%9F%93%A6 

### Describe alternatives you've considered

Switching to RS pack and the new rust toolchain does not make sense as the ecosystem is still very new at the moment where as Vite is battletested.

### Additional context

I am willing to work on this during my free time as we use Chatwoot in the company I work at https://farmako.in . Though I would need some form of green light on this to understand if this change aligns with the project and it's current maintainers or not (Don't really want my PR to go to waste)

**Comment by pranavrajs** [comment]
@sidwebworks, Sharing the response here as well for visibility.

> This has been in the works for some time. We got hit with EMFILE error. https://vite-ruby.netlify.app/guide/troubleshooting.html#requests-to-vite-sporadically-return-a-500-error-response

> I believe this is specifically an issue with vite-ruby and not with vite which is why we started working on a monorepo concept. You can see the progress [here](https://github.com/chatwoot/chatwoot-ui-monorepo). 

Closing this here for now.
