### ISSUE TITLE
About the creation of inbox of type api

### ISSUE THREAD

**Issue by kingszhe9664** [chatwoot/chatwoot#8792]
### Describe the bug

I don't know how to create an inbox of type api for each account through this interface [](https://www.chatwoot.com/developers/api/#tag/Inboxes/operation/inboxCreation)

type  only provide  web_widget  and return 500   
can give me  a  api type request demo

### To Reproduce

request
```
{
  "name": "www",
  "avatar": "string",
  "channel": {
    "type": "web_widget",
    "website_url": "string",
    "welcome_title": "string",
    "welcome_tagline": "string",
    "agent_away_message": "string",
    "widget_color": "string"
  }
}
```

return 

```
{
    "status": 500,
    "error": "Internal Server Error"
}
```

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
ref: 
```
post "/api/v1/accounts/#{account.id}/inboxes",
             headers: { provide api token }
             params: { name: 'API Inbox', channel: { type: 'api', webhook_url: 'http://test.com' } },
             as: :json
 ```
 
 tip : 
 
You can do the action from your browser with the network tab open.  copy the same payload structure and use it on the APIs.

**Comment by kingszhe9664** [comment]
tks
