### ISSUE TITLE
edit sent messages

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#8796]
### Is your feature or enhancement related to a problem? Please describe.

 When you make a mistake, or simply change your mind, you can not edit your sent messages.

### Describe the solution you'd like

Can edit sent messages

**Comment by pranavrajs** [comment]
@mmojadad We won't support this feature as we can't recall the message that is delivered to third-party solution. A good option is allow unsend with a 5s delay. However, from the discussions I had with people, this is only expected in emails where the text is long and aren't instantly read.
