### ISSUE TITLE
Can't install with docker compose, webpack crashes

### ISSUE THREAD

**Issue by Kiskadee-dev** [chatwoot/chatwoot#8798]
### Describe the bug

Followed the guide on https://www.chatwoot.com/docs/self-hosted/deployment/docker, 

built the base first, then followed the rest normally, when starting the whole project the issue arises.

I've tested with the latest version, v3.5.2 and v3.5.0.

> webpack-1   | The Gemfile's dependencies are satisfied
webpack-1   | Ready to run webpack development server.
webpack-1   | ℹ ｢wds｣: Project is running at http://0.0.0.0:3035/
webpack-1   | ℹ ｢wds｣: webpack output is served from /packs/
webpack-1   | ℹ ｢wds｣: Content not from webpack is served from /app/public/packs
webpack-1   | ℹ ｢wds｣: 404s will fallback to /index.html
webpack-1   | Browserslist: caniuse-lite is outdated. Please run:
webpack-1   | npx browserslist@latest --update-db
webpack-1   | 
webpack-1   | Why you should do it regularly:
webpack-1   | https://github.com/browserslist/browserslist#browsers-data-updating
webpack-1   | node:internal/crypto/hash:68
webpack-1   |   this[kHandle] = new _Hash(algorithm, xofLen);
webpack-1   |                   ^
webpack-1   | 
webpack-1   | Error: error:0308010C:digital envelope routines::unsupported
webpack-1   |     at new Hash (node:internal/crypto/hash:68:19)
webpack-1   |     at Object.createHash (node:crypto:138:10)
webpack-1   |     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:135:53)
webpack-1   |     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:417:16)
webpack-1   |     at /app/node_modules/webpack/lib/NormalModule.js:452:10
webpack-1   |     at /app/node_modules/webpack/lib/NormalModule.js:323:13
webpack-1   |     at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
webpack-1   |     at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
webpack-1   |     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
webpack-1   |     at /app/node_modules/babel-loader/lib/index.js:59:103 {
webpack-1   |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
webpack-1   |   library: 'digital envelope routines',
webpack-1   |   reason: 'unsupported',
webpack-1   |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
webpack-1   | }
webpack-1   | 
webpack-1   | Node.js v20.8.1
webpack-1 exited with code 1

Related to #6578, #6560, #7626 and PR #8714

### To Reproduce

clone the repo

docker compose build base
docker compose build
docker compose run --rm rails bundle exec rails db:chatwoot_prepare
docker compose up

Result:

![image](https://github.com/chatwoot/chatwoot/assets/10299707/d24cb2f2-e496-4421-8f50-190478739534)

### Expected behavior

Webpack shouldn't crash

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux pop-os 6.6.10-76060610-generic #202401051437~1704728131~22.04~24d69e2 SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux

### Docker (if applicable)

Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:46 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:46 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

----

Docker Compose version v2.24.2

**Comment by danatlri** [comment]
Followed the same steps and had the same issue with the latest build. I’m just testing so I’m not sure if this is a good/permanent fix, but it worked by adding the following under the environment section for both rails and webpack in the docker-compose.yaml file:

- NODE_OPTIONS=--openssl-legacy-provider

It took a good amount of time before the application came online after making this change.

**Comment by vishnu-narayanan** [comment]
@Kiskadee-dev Hey, it will be fixed by https://github.com/chatwoot/chatwoot/pull/8714

For now, please pass `NODE_OPTIONS=--openssl-legacy-provider` to the webpack container as @danatlri mentioned.

**Comment by vishnu-narayanan** [comment]
This should be fixed now. Please reopen if you are still facing issues.

- https://github.com/chatwoot/chatwoot/pull/8714
