### ISSUE TITLE
OpenAPI spec is broken

### ISSUE THREAD

**Issue by gsemyong** [chatwoot/chatwoot#8811]
### Describe the bug

As far as I understand features from >=3.0.0 version are being used, which makes code generators to produce invalid/inconsistent results. Obviously it would be better if it is possible to migrate the spec to 3.1. Attaching errors screenshot for the current spec:

![image](https://github.com/chatwoot/chatwoot/assets/46911188/11e7b353-a88f-449b-8c47-4a343e9ea11d)

I am willing to provide any help needed to resolve this ASAP, since I am building product around your API and it is crucial for me to have understandable interface to work with.

Thank you in advance!

P.S. Your product is awesome overall :)

### To Reproduce

Paste the current spec into https://editor.swagger.io/

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@gsemyong The version used in Chatwoot the Open API is 2.0 not 3.0. Can you please try to use 2.0 in swagger? It should work.

**Comment by gsemyong** [comment]
I am pasting with the 2.0 version field (I just copy/paste the file), so editor recognizes it correctly as 2.0, but there features in the spec which are not supported in 2.0, like "oneOf" for example

**Comment by gsemyong** [comment]
@pranavrajs Here is the link to a file where "oneOf" is used https://github.com/chatwoot/chatwoot/blob/648c4caca188a4fdaa9c953950f01a8b66ffec8e/swagger/definitions/request/public/message/update_payload.yml

**Comment by pranavrajs** [comment]
It's now auto generated. Let our team take look at this.

**Comment by gsemyong** [comment]
I actually fixed the issue for myself, I guess the problem is not in generation step, since I found all the causes in the source yml files. The problems are following:

1. Incorrect indentation on line 39 here https://github.com/chatwoot/chatwoot/blob/648c4caca188a4fdaa9c953950f01a8b66ffec8e/swagger/paths/application/contacts/filter.yml
2. Invalid "oneOf" usage here https://github.com/chatwoot/chatwoot/blob/648c4caca188a4fdaa9c953950f01a8b66ffec8e/swagger/definitions/request/public/message/update_payload.yml
3. Missing "portal_id" include here https://github.com/chatwoot/chatwoot/blob/develop/swagger/parameters/index.yml

I can submit a PR

**Comment by pranavrajs** [comment]
Please go ahead. I can review and merge it.
