### ISSUE TITLE
ArgumentError (wrong authentication type xoauth2)

### ISSUE THREAD

**Issue by jonaski** [chatwoot/chatwoot#8840]
### Describe the bug

No e-mail get's sent after upgrading from 3.3.1 to 3.5.2.

I can see the following in the sidekiq logs:

`E, [2024-02-01T13:39:30.512759 #1] ERROR -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [ba8f0dda-af7a-4ca3-a5bb-38fa68fba9c3] Error performing ActionMailer::MailDeliveryJob (Job ID: ba8f0dda-af7a-4ca3-a5bb-38fa68fba9c3) from Sidekiq(default) in 53.13ms: ArgumentError (wrong authentication type xoauth2):`

### To Reproduce

Set up Chatwoot with Sendgrid SMTP and SMTP_AUTHENTICATION to plain.

Configuration:

```
SMTP_DOMAIN=<domain.com>
SMTP_ADDRESS=smtp.sendgrid.net
SMTP_PORT=587
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_AUTHENTICATION=plain
SMTP_USERNAME=apikey
SMTP_PASSWORD=<password>
```

### Expected behavior

E-mail is sent using SMTP with plain authentication.

### Environment

Kubernetes

### Cloud Provider

Azure

### Platform

None

**Comment by pranavrajs** [comment]
@jonaski, I am closing this as it is already fixed via https://github.com/chatwoot/chatwoot/pull/8790. We will see if we can put out an interim release next week, as it became a critical bug.

**Comment by jonaski** [comment]
I applied the patch and it looks to be working, at least for new outgoing messages, but so far messages that failed previously is not re-sent, are they lost?

**Comment by pranavrajs** [comment]
@jonaski, it would be in the dead queue as the retries would also have failed.

Could you please check the dead jobs in the Sidekiq console from the super admin console? You should be able to see the messages there. You can retry this, which should send the messages again.
