### ISSUE TITLE
Error deleting Instagram messages - instagram_manage_messages Permission

### ISSUE THREAD

**Issue by pixelsstudiove** [chatwoot/chatwoot#8842]
### Describe the bug

In order to cancel messages sent from Instagram, it is necessary to use the URLs provided by the same platform, but in Chatwoot we use local storage or use of CDNs such as Amazon or Google.

This policy is new, how could we pass Meta review for this permission to be approved if Chatwoot doesn't delete the media file?

### To Reproduce

1- Send a message from Instagram to a test account

2- Receive the message in your Chatwoot inbox

3- Delete the message from Instagram

4- Notice how the message says that it was deleted in Chatwoot but the file is still kept in the chat.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu

**Comment by sojan-official** [comment]
tracking it here : https://github.com/chatwoot/chatwoot/issues/8512
