### ISSUE TITLE
Change the address of the logger-1.min.js

### ISSUE THREAD

**Issue by shuaiplus** [chatwoot/chatwoot#8848]
### Is your feature or enhancement related to a problem? Please describe.

The official program didn't have a good connection speed in my region, so I deployed my own Dokcer image, but **logger-1.min.js** still made the site slow to load because it used Cloudflare.
![image](https://github.com/chatwoot/chatwoot/assets/100134295/b2c78177-9602-4957-9366-44312641b7e9)

### Describe the solution you'd like

I want to put logger-1.min.js on my own server to make it load faster.

### Describe alternatives you've considered

Can you please show me how to modify the corresponding code in the docker container to solve this problem?

**Comment by pranavrajs** [comment]
@shuaiplus This is not coming from Chatwoot. Please check your setup.
