### ISSUE TITLE
Sockets are disconnected periodically

### ISSUE THREAD

**Issue by numb7** [chatwoot/chatwoot#8888]
### Describe the bug

Sockets are disconnected periodically and we can't see new messages in the admin without refreshing the page in the browser.
The problem is solved by overloading the self-hosted chatwoot server.

The monitoring system detected an error.
Label:
trigger = PodThrottlingGreaterThan100mCpuWithin10Min
Alert Description:
Container in service chatwoot-workers throttling greater than 0.1 CPU within 10 minutes: 0.16 CPU

Can you tell me what can cause 

Self-hosted chatwoot v 3.0.0

Translated with DeepL.com (free version)

### To Reproduce

you can't retrace the steps 

### Environment

Kubernetes

### Cloud Provider

None

### Platform

Browser

### Operating system

3.0.0

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/6411

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/6411

**Comment by pranavrajs** [comment]
This configuration would allow you to automatically resolve the conversation after a specific time period. Configure the time frame and personalized message to the user below.

When a disconnect occurs, the web-socket events intended for the UI are discarded and lost.

* Caches are present for Agents, Labels, Inboxes, and Teams. We need to verify whether these caches have been invalidated. If they have, we should use the APIs to refetch the models. This logic already exists in `account.cache_invalidated`.
* For the currently active conversation, fetch the messages were added / updated after the disconnection time.
* Retrieve the conversations that were updated after the disconnection time based on the active filters in the UI.
