### ISSUE TITLE
Conversation filters are not working correctly

### ISSUE THREAD

**Issue by numb7** [chatwoot/chatwoot#8890]
### Describe the bug

I create a filter with certain parameters. After some time, even without refreshing the page, new chats are added to the filter that do not fit the specified conditions of the filter

### To Reproduce

1. Open conversations
2. Pressing the button Filter Conversations
3. Adding conditions to the filter
4. Pressing the button Apply filters
5. Dialogs that match the filter condition are displayed
6. I create a new dialog using the widget
7. The created dialog that does not fit the filter is displayed in the filter

### Environment

Kubernetes

### Cloud Provider

None

### Platform

None

### Operating system

3.0.)

**Comment by jordan26** [comment]
I have a similar issue too, mentioning for visibility (https://github.com/chatwoot/chatwoot/issues/8877)
