### ISSUE TITLE
Dialogs are periodically self-updated

### ISSUE THREAD

**Issue by numb7** [chatwoot/chatwoot#8891]
### Describe the bug

A user types a text to reply to a message and the dialog is self-updated. The user does not refresh the browser page, everything happens automatically.
<img width="1376" alt="Снимок экрана 2024-02-08 в 15 47 27" src="https://github.com/chatwoot/chatwoot/assets/17248062/5be9bb44-02b8-47a0-9053-b9b327de6c74">

### To Reproduce

you can't retrace the steps

### Environment

Kubernetes

### Cloud Provider

None

### Platform

Browser

### Operating system

3.0.0

**Comment by sojan-official** [comment]
Seems like this is a customised instance.  Please try on the latest version of Chatwoot without any customizations. We haven't received any similar reports.
