### ISSUE TITLE
Unable to build docker image on Macbook M1

### ISSUE THREAD

**Issue by FranciscoJBrito** [chatwoot/chatwoot#8904]
### Describe the bug

`docker-compose build` fails on Macbook M1

### To Reproduce

Following the steps in the documentation REF: https://www.chatwoot.com/docs/contributing-guide/environment-setup/docker/#development-environment
1 - Clone the repository.
2 - Make a copy of the example environment file and modify it as required.
3 - Build the images.

Failure in step 3 to build the image

### Expected behavior

Docker build must be successfull.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

macOS - Sonoma 14.2.1 [M1 Chip]

### Browser and version

Microsoft Edge

### Docker (if applicable)

```
Client:
 Cloud integration: v1.0.35+desktop.10
 Version:           25.0.2
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Thu Feb  1 00:18:45 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.27.1 (136059)
 Engine:
  Version:          25.0.2
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       fce6e0c
  Built:            Thu Feb  1 00:23:21 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```
Docker Compose version v2.24.3-desktop.1
```

### Additional context

LOGS: 
```
=> ERROR [webpack internal] load metadata for docker.io/library/chatwoot:development                                                         2.0s
=> CANCELED [sidekiq internal] load metadata for docker.io/library/ruby:3.2.2-alpine3.18                                                 2.5s
------
 > [webpack internal] load metadata for docker.io/library/chatwoot:development:
------
failed to solve: chatwoot:development: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Comment by FranciscoJBrito** [comment]
I reported the issue so that it is recorded, but I already resolved it.
The problem is in the docker image. The image being used is `chatwoot:development`, I searched for this image on Docker Hub, and can only find [one](https://hub.docker.com/layers/umar482/chatwoot/development/images/sha256-cc01cfc8cf7c42bd18310520b7a8dd72204f3c3c3af649b9a4a1796370742042?context=explore) and is not from the user chatwoot.
To fix it, change the image tag to develop and specify the user, the final image looked like this: [chatwoot/chatwoot:develop](https://hub.docker.com/layers/chatwoot/chatwoot/develop/images/sha256-b9430a2f18dc08b0ba1189a256bb7f147bcfe46e88a1ef7eb266f677a0642aba?context=explore).

We must replace the image in these three files:
1-docker-compose.yml
2 - docker/dockerfiles/webpack.Dockerfile
3 - docker/dockerfiles/rails.Dockerfile

After making these modifications, run the `docker-compose build` command again and the issue should be resolved.

---
**PS:** I also got an error when running the `docker-compose up` command. The error came from the docker/entrypoints/webpack.sh file on line 7, the `yarn install --check-files` command is no longer supported in the latest versions of yarn. To fix this you can modify the webpack.sh file by removing the --check-files flag, or reverting to version 1 of yarn.

**Comment by FranciscoJBrito** [comment]
I don't know if anyone is already working on this, but if not, I can gladly send a PR with the modifications to the docker files.

**Comment by shivamkb17** [comment]
@FranciscoJBrito  using chatwoot:develop instead of chatwoot:development, It is actually solve problem. 
If any custom changes made in your PC, That code is not used to build the docker image, Instead of using it, It is just fetching chatwoot develop branch image from chatwoot repositories.

**Comment by jyotman** [comment]
I'm not sure this is the solution @shivamkb17 
chatwoot:development is used to build a local image by the name and rails and webpack dockerfiles should be able to fetch this local image? But apparently it fails because rails and webpack dockerfile tries to pull this image from dockerhub because the local chatwoot:development image does not exist yet. Its like a race condition if I'm not wrong.

Also, I'm using docker compose v2, maybe that's the problem?
cc: @FranciscoJBrito

**Comment by jyotman** [comment]
Making the base image myself first and then running docker compose build worked for me as suspected - 
```docker build -t chatwoot:development --build-arg BUNDLE_WITHOUT='' --build-arg EXECJS_RUNTIME='Node' --build-arg RAILS_ENV='development' --build-arg RAILS_SERVE_STATIC_FILES='false' -f ./docker/Dockerfile .```

**Comment by FranciscoJBrito** [comment]
Hi @jyotman 👋🏻, sounds good to me, let me try it, maybe this will solve the problem in a better way.

**Comment by FranciscoJBrito** [comment]
@jyotman you are totally right, it worked perfect for me.
