### ISSUE TITLE
Enhancement: Auto-assign closed conversation to last assigned agent while re-opening

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#892]
If a conversation is opened by the system, auto-assign the conversation to the last agent who has interacted to the customer.

@sojan-official Thoughts?

**Comment by kadir96** [comment]
Would like to implement this if you decide to have this enhancement.

**Comment by pranavrajs** [comment]
We are still working on the acceptance criteria, I was just throwing out the idea as an when I saw this issue. If you can look at any other issue, that would be great.

**Comment by kadir96** [comment]
Yeah I know its just an idea now. This is why I put the `if` in my comment :)

**Comment by pranavrajs** [comment]
Closing this as most of this should be covered in automation.
