### ISSUE TITLE
Feature: Support MinIO as Storage

### ISSUE THREAD

**Issue by kadir96** [chatwoot/chatwoot#893]
Currently chatwoot supports cloud storages from AWS, GCP, Azure and this means the users are required the pay for storage. There is a project called [MinIO](https://github.com/minio/minio) and it is a S3 compatible storage service. I was thinking that if a MinIO service deployed along with other services, there would be no need for payment for storage. What do you think?

**Comment by pranavrajs** [comment]
@kadir96 Does this work automatically?

**Comment by kadir96** [comment]
@pranavrajs Yes it does work automatically since it is s3 compatible but there is no need for supporting MinIO. I did not know Chatwoot uses local disk by default for storage while thinking about this issue so I closed

**Comment by lucasilverentand** [comment]
Hi, I would very much like to see this feature. As I'm using DigitalOcean Spaces which is S3 compatible and it just requires chatwoot to use a different endpoint for accessing the buckets.

**Comment by pranavrajs** [comment]
https://github.com/chatwoot/chatwoot/issues/968

@lucasilverentand I've created an issue for it, let us track the progress there.

**Comment by lucasilverentand** [comment]
@pranavrajs Thank you very much 👍
