### ISSUE TITLE
Instagram messages are not sent

### ISSUE THREAD

**Issue by pelucapampa** [chatwoot/chatwoot#8930]
### Describe the bug

I am receiving Instagram messages, but when I try to respond to them, they do not reach their destination (On Facebook messenger the messages do go out and are delivered).

I have advanced Facebook permissions in my app.
The advanced permissions I have are:
pages_messaging OK
pages_show_list OK
Business Asset User Profile Access OK
pages_manage_metadata OK
pages_read_engagement OK
instagram_manage_messages OK
instagram_basic OK
business_management OK

Could someone tell me what is missing?

### To Reproduce

Add facebook/instagram messenger.

Send message to instagram from Non app admin instagram account.

Try to respond this message

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pelucapampa** [comment]
@pranavrajs could you help me.
I'm trying to use Chatwoot since 6 month, recently I ve all of facebook/instagram advance permission, but only can send messege to instagram if user it's an facebook dev admin. For other instagram users i can't send message.
Have you any idea why?

**Comment by pranavrajs** [comment]
@pelucapampa 

Please check the server logs and see if you find any errors there. If the message is not sent the error would be available in the logs, in the recent versions we show in the UI itself. There is no information which can help us to debug the issue. 

1 - Which version of Chatwoot are you using?
2 - Have you made any recent changes now? Did you upgrade recently?
3 - What is the API version you see on your developer app configuration?

Also, can you please confirm the following? 
1 - You can connect any page in Facebook (the user who connects the page should not be associated with the developer app)
2 - Your app is live in Facebook developer console.
3 - ENABLE_MESSENGER_CHANNEL_HUMAN_AGENT is set to false in the environment variables.

**Comment by pelucapampa** [comment]
> @pelucapampa
> 
> Please check the server logs and see if you find any errors there. If the message is not sent the error would be available in the logs, in the recent versions we show in the UI itself. There is no information which can help us to debug the issue.
> 
> 1 - Which version of Chatwoot are you using? 2 - Have you made any recent changes now? Did you upgrade recently? 3 - What is the API version you see on your developer app configuration?
> 
> Also, can you please confirm the following? 1 - You can connect any page in Facebook (the user who connects the page should not be associated with the developer app) 2 - Your app is live in Facebook developer console. 3 - ENABLE_MESSENGER_CHANNEL_HUMAN_AGENT is set to false in the environment variables.

Hi, 

1 - Which version of Chatwoot are you using?
Chatwoot 3.6.0
2 - Have you made any recent changes now? Did you upgrade recently?
No, i'm never can use for instagram
3 - What is the API version you see on your developer app configuration?
API 19

Also, can you please confirm the following?
1 - You can connect any page in Facebook (the user who connects the page should not be associated with the developer app)
when i'm trying to connect page with user not app admin, i'm received this error
![image](https://github.com/chatwoot/chatwoot/assets/120580431/d18782bc-ae82-4c7c-9ae7-8ede80ea7124)

But i'm received and send facebook messenger to all users. 
2 - Your app is live in Facebook developer console.
YES
3 - ENABLE_MESSENGER_CHANNEL_HUMAN_AGENT is set to false in the environment variables.**
OK

**Comment by shivamkb17** [comment]
Did your instagram advance messaging is approved or not, check in facebook app and update here.

**Comment by shivamkb17** [comment]
For instagram manage message, advance permission doesn't work for all incoming message, untill your advance permission is verified by facebook app review team.

**Comment by pelucapampa** [comment]
> For instagram manage message, advance permission doesn't work for all incoming message, untill your advance permission is verified by facebook app review team.

Yes. I've advance access to instagram_manage_messages

![Screenshot_2024-02-25-20-36-54-624_com android chrome](https://github.com/chatwoot/chatwoot/assets/120580431/1c5df339-0a24-44be-8f54-30affe618134)

**Comment by pelucapampa** [comment]
Hi @pranavrajs i'm trying other method to check if i need some permission, I test POST from Facebook API Graph and I CAN send messege with my permision to user

![image](https://github.com/chatwoot/chatwoot/assets/120580431/c5a40fa4-3478-4e79-bf8b-be34d574b795)

Have any suggestion about this problems?
On chatwoot i can't see simple or doble check on message
![image](https://github.com/chatwoot/chatwoot/assets/120580431/6bca2b99-8654-4ca1-92dc-331ad822a71b)
(Two last message i sent from Facebook API Graph)

**Comment by pelucapampa** [comment]
Hi !!. Maybe someone have any time to review my problem on a short meeting.
After 6 month to obtain facebook advance permission, now we cannot use chatwoot for instagram and we haven't idea why.

Thanks

**Comment by pelucapampa** [comment]
Hi @pranavrajs 
 i'm continuing looking something to resolve my issue, and now i try to look all messages from chatwoot api and compare Instagram messages sent and not

I found difference only on "source_id" when message to app admin are sent, the message on chatwoot api have 'source_id' and the message to other user (no FB app admin), the message haven't source_id.

May be this is the error?

Message not send

{
            "id": 10667,
            "content": "Jpa",
            "inbox_id": 87,
            "conversation_id": 117,
            "message_type": 1,
            "content_type": "text",
            "status": "sent",
            "content_attributes": {},
            "created_at": 1710184817,
            "private": false,
            "source_id": null,
            "sender": {
                "id": 1,
                "name": "Integraciones",
                "available_name": "Ignacio Navarro",
                "avatar_url": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg",
                "type": "user",
                "availability_status": "online",
                "thumbnail": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg"
            }
        },
        {
            "id": 10668,
            "content": "Prueba",
            "inbox_id": 87,
            "conversation_id": 117,
            "message_type": 1,
            "content_type": "text",
            "status": "sent",
            "content_attributes": {},
            "created_at": 1710185011,
            "private": false,
            "source_id": null,
            "sender": {
                "id": 1,
                "name": "Integraciones",
                "available_name": "Ignacio Navarro",
                "avatar_url": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg",
                "type": "user",
                "availability_status": "online",
                "thumbnail": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg"
            }
        }


**Message are sent**
{
            "id": 10670,
            "content": "Hola",
            "inbox_id": 87,
            "conversation_id": 115,
            "message_type": 1,
            "content_type": "text",
            "status": "read",
            "content_attributes": {},
            "created_at": 1710185874,
            "private": false,
            "source_id": "aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDA5MjI3NTgxMjUyOjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI1OTI2NTA3NDY4OTQ3MDQ5NzozMTU0NzM2MTE2MzU5NDc1MDkxODY4NzczMDU0NzI5NDIwOAZDZD",
            "sender": {
                "id": 1,
                "name": "Integraciones",
                "available_name": "Ignacio Navarro",
                "avatar_url": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg",
                "type": "user",
                "availability_status": "online",
                "thumbnail": "https://chat.aadesa.com.ar/rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4edb3b5c822f748d144ba5ca644f66a445de7ea3/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lJYW5CbkJqb0dSVlE2RTNKbGMybDZaVjkwYjE5bWFXeHNXd2RwQWZvdyIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--6d67cc85ee1ef5607c0fd1f48989b596f125a667/DSC_0176-2%20(2021_05_09%2014_01_08%20UTC).jpg"
            }
        }

**Comment by pelucapampa** [comment]
Hi all? someone have same error on your instance or only I have this issue?

Thanks

**Comment by pelucapampa** [comment]
Hello everyone, can someone help me understand the problem I have with sending Instagram messages.
I have all the required permissions.
What else should I check?
Where can I see the log on a server with Docker?

**Comment by pelucapampa** [comment]
Hi @pranavrajs could you help me with this issue? i reviewed all of different things, but i couldn't fine why my chatwoot installation, didn't sent instagram messages.
Thanks

**Comment by pelucapampa** [comment]
Hi all.
We reinstalled with data deletion and now everything is fine, we cannot detect why it happened or what information it stores or where to stop it from sending Instagram messages.
