### ISSUE TITLE
Can't hyperlink text on new conversation started from Contacts

### ISSUE THREAD

**Issue by dmasiero** [chatwoot/chatwoot#8939]
### Describe the bug

When starting a new conversation from Contacts, the hyperlink icon doesn't do anything when clicked.

### To Reproduce

1.) Create a contact.
2.) Click the blue New Conversation button in the contact view.
3.) In the new conversation pop-up, type text in the message section and highlight a portion.
4.) Attempt to click the link (chain icon) on toolbar.
5.) Nothing happens.

### Expected behavior

A dialogue box should pop up prompting for hyperlink.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

macOS 14

### Browser and version

Arc 1.29.0 / Chromium Engine Version 121.0.6167.160

**Comment by pranavrajs** [comment]
This seems like a bug. @sivin Can you please take a look?
