### ISSUE TITLE
Option Whatsapp API Cloud Single conversation

### ISSUE THREAD

**Issue by yvescleuder** [chatwoot/chatwoot#8946]
### Describe the bug

Hi,

When I enabled the "Block for single conversation" option, new conversations that arrive on official WhatsApp continue with the same "Agent assigned" as your last conversation, even though the Automatic distribution option is unchecked.
The correct thing to do would be, when ending a conversation or when opening that conversation again, to remove the "Assigned Agent" that is in it so that another agent can receive the conversation.

### To Reproduce

Enable in Inbox last option
![image](https://github.com/chatwoot/chatwoot/assets/15827896/69cb9341-6156-40ec-b580-4e854c02d82e)

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22

**Comment by pranavrajs** [comment]
This could be done with the automation. Please check the following automation. I will close this here for now. Please feel free to reopen if it doesn't solve it.

<img src="https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/300bf1eb-3a48-4ffc-93ae-e1fe82e889de/a662414f-0ea6-4880-8966-52a4828ea31d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8zMDBiZjFlYi0zYTQ4LTRmZmMtOTNhZS1lMWZlODJlODg5ZGUvYTY2MjQxNGYtMGVhNi00ODgwLTg5NjYtNTJhNDgyOGVhMzFkIiwiaWF0IjoxNzA4MDQ5MzM4LCJleHAiOjMzMjc4NjA5MzM4fQ.DFrBjnGmxjyr8NivnAzFcyaYzjrLNctkgunuO8OTTmc " alt="Screenshot 2024-02-15 at 6.08.07 PM.png" width="869" height="769" />
