### ISSUE TITLE
Custom notification sound

### ISSUE THREAD

**Issue by jordan26** [chatwoot/chatwoot#8949]
### Is your feature or enhancement related to a problem? Please describe.

Feature. When chatwoot is not active and I am aware of new conversations purely from the audio notification, it's hard to know if the latest incoming message is a live chat, which needs responding to immediately or an email which can sometimes wait longer as the customer is not live.

### Describe the solution you'd like

The ability to choose different audio sounds for each inbox / conversation type such as Live Chat vs Email.

**Comment by pranavrajs** [comment]
<img width="988" alt="Screenshot 2024-02-15 at 6 06 31 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/81542a7a-3ad6-4412-8b5c-a50d2e41ebdd">


@jordan26 There is already an option to change the sound to a higher volume one. Please check it out on profile settings.

**Comment by jordan26** [comment]
@pranavrajs - This does not solve my use case. For example I would want to set "Ding" for certain inboxes, and "Bell" for other inboxes. Different tones for different inboxes. I know a unique use case but could be helpful to distinguish between what type of incoming message has arrived.

**Comment by pranavrajs** [comment]
@jordan26 Thanks for the context. However, this seems to be specific cases and we wouldn't be solving this. I would recommend using push notifications instead.
