### ISSUE TITLE
Enhancement: Add a notification for new messages in the conversation assigned to you

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#895]
**Problem** 

I'm getting alerts whenever a new conversation is assigned to me or a new one is created. However, I do not when a new message is received in the conversation which I'm handling.

**Solution**

Add a push/email notification when a new message is received in the assigned conversations

**Acceptance Criteria**

<img width="806" alt="Screenshot 2020-05-27 at 5 36 26 PM" src="https://user-images.githubusercontent.com/2246121/83017052-9a949000-a040-11ea-9285-dead43258449.png">

Add 2 new options in the profile settings:-

1. Send email notifications when a new message is received in the conversations assigned to me
2. Send push notifications when a new message is received in the conversations assigned to me

Email/Push has to be sent when the above options are enabled.

**Comment by WevrLabs** [comment]
Any ETA for this feature? It'll probably be one of the most crucial additions to Chatwoot.

**Comment by pranavrajs** [comment]
@WevrLabs We will take this one in the next sprint.
