### ISSUE TITLE
Read time out from server

### ISSUE THREAD

**Issue by backbonedev27** [chatwoot/chatwoot#8952]
### Describe the bug

i use version 3.5.2 and integrate with evolution api, for whatsapp unofficial. when i send message , error timeout out from server.
![WhatsApp Image 2024-02-16 at 14 21 31 (1)](https://github.com/chatwoot/chatwoot/assets/129310821/7c8940b4-22d2-48ac-9649-182c2b8f63f2)

### To Reproduce

i dont know , send message cant. before that, i've work for send message

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

None

### Operating system

Ubuntu 20.04

**Comment by sojan-official** [comment]
Hi @backbonedev27,

Thanks for reaching out! Based on the error you mentioned, it appears that the API server might not be responding within the expected 5 seconds timeframe when Chatwoot attempts to make the API call. It could be beneficial to investigate and improve the API's response times on your end.

Also, I wanted to mention that we currently do not offer official support for the `evolution` API. For issues specifically related to their service, we recommend contacting their support team directly for further assistance.

Hope this help !
