### ISSUE TITLE
Allow changing the z-index of the Chatwoot widget

### ISSUE THREAD

**Issue by amplitudesxd** [chatwoot/chatwoot#8957]
### Is your feature or enhancement related to a problem? Please describe.

Hi there,

I've ran into issues with the Chatwoot widget where we don't want it to overlay certain elements, and have our own system for defining z-indexes in place.

Chatwoot sets the z-index to `2147483000`, which is the highest possible value, making it impossible to have an element above it. The z-index attribute additionally has the `!important` specifier on it, which prevents you from overriding the z-index using your own CSS, so you have to resort to tampering with the element or the injected CSS using JS, which is far from ideal.

### Describe the solution you'd like

It would be great if the z-index of the widget could be controlled from the JavaScript SDK, which would then replace the z-index in the CSS, before injecting it into the site. Alternatively, even just removing the `!important` specifier would allow more control, as then it's possible to override the z-index in your own CSS.

**Comment by jordan26** [comment]
Question for the chatwoot team - If needed, how might we be able to edit the CSS ourselves? Mainly, what is the process of re-compiling assets when changed (just in case it's a method some people choose).

**Comment by amplitudesxd** [comment]
> Question for the chatwoot team - If needed, how might we be able to edit the CSS ourselves? Mainly, what is the process of re-compiling assets when changed (just in case it's a method some people choose).

For the widget, you can edit it in https://github.com/chatwoot/chatwoot/blob/develop/app/javascript/sdk/sdk.js

**Comment by pranavrajs** [comment]
@amplitudesxd If there is an issue with the z-index, recommend way is to implement an button to open the chat window yourself and use the hideMessageBubble option in the SDK. We will not provide an option to change this. https://www.chatwoot.com/docs/product/channels/live-chat/sdk/setup/#sdk-settings

**Comment by amplitudesxd** [comment]
@pranavrajs what would the reason for that be? I can't see any downsides of allowing the z-index to be configurable.

**Comment by pranavrajs** [comment]
@amplitudesxd This is an additional configuration that we need to consider in all future design changes, which makes it tricky. If there were no other options, it would be okay to consider this as config. However, we have an alternative path to implement the same change.
