### ISSUE TITLE
Updating from 3.3.1 to 3.4.0 and newer

### ISSUE THREAD

**Issue by whoqmi** [chatwoot/chatwoot#8959]
### Describe the bug

After updating to 3.4.0 and newer releases from 3.3.1 and lower (we're started from 3.0.0), we have an error with lables:
![image](https://github.com/chatwoot/chatwoot/assets/46215604/03f039ae-7e6d-468d-87aa-5710bd02c78a)

### To Reproduce

1. Just docker pull with ChatWoot version 3,3,1

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 20

### Docker (if applicable)

VERSION: 
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
INFO:
  Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-94-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.566GiB
 Name: gribland.net
 ID: f5107684-65ba-47f6-895e-2d874c1e0fd0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by vishnu-narayanan** [comment]
@whoqmi Have you run all the migrations? Could you check the instance health page and see if migrations are complete?

https://<your-chatwoot-domain>/super_admin/instance_status

<img width="1168" alt="image" src="https://github.com/chatwoot/chatwoot/assets/3526167/f995d5be-d800-47dc-9233-427a72ec7fb6">
