### ISSUE TITLE
reopened  conversation notifications 

### ISSUE THREAD

**Issue by Double-Click-ERP** [chatwoot/chatwoot#8962]
### Describe the bug

if I have been mentioned by someone else in a conversation , after that the conversation is closed and reopened
i still get notifications for this conversation

### To Reproduce

1. WhatsApp conversation by another agent
2. the agent mentioned you and continue conversation
3. conversation is now closed 
4. reopened after while 

on your side you will receive all new notifications for this conversation

related to ?
https://github.com/chatwoot/chatwoot/pull/8435

### Expected behavior

reopened  conversation is a new conversation  with new agent and new participating 

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
This appears to be a specific requirement. As a conversation participant, you will receive notifications. If you prefer not to get these notifications, you can remove yourself from the participants or disable notifications for participating conversations.
