### ISSUE TITLE
IMAP connections not getting closed or re-used

### ISSUE THREAD

**Issue by af7567** [chatwoot/chatwoot#8968]
### Describe the bug

The IMAP mailbox is getting checked by chatwoot, but emails are not getting picked up because chatwoot has too many open connections to the IMAP server. New connections will only be allowed after the IMAP server has closed the inactive connection which can take a while.

IMAP server log:
```
Feb 19 17:17:30 mail dovecot: imap-login: Disconnected: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<hello>, method=PLAIN, rip=12.12.12.246, lip=12.12.12.242, TLS, session=<F6/ERL8RMO5SRor2>
Feb 19 17:18:02 mail dovecot: imap-login: Disconnected: Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10): user=<hello>, method=PLAIN, rip=12.12.12.246, lip=12.12.12.242, TLS, session=<rk6rRr8RyNpSRor2>
Feb 19 17:18:18 mail dovecot: imap(hello)<25824><yt5Y3L4RYpVSRor2>: Disconnected: Inactivity - no input for 1800 secs in=125 out=22242 deleted=0 expunged=0 trashed=0 hdr_count=4 hdr_bytes=11113 body_count=1 body_bytes=9964
```
Output of `netstat | grep imap` in the chatwoot VM
```
tcp        0      0 chatwoot:34600          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:53066          mail.example.:imaps CLOSE_WAIT 
tcp        0      0 chatwoot:35058          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:35436          mail.example.:imaps CLOSE_WAIT 
tcp        0      0 chatwoot:35238          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:41402          mail.example.:imaps CLOSE_WAIT 
tcp        0      0 chatwoot:39630          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:58892          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:49162          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:43262          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:60308          mail.example.:imaps ESTABLISHED
tcp        0      0 chatwoot:45826          mail.example.:imaps ESTABLISHED
```
I only have 1 inbox configured using IMAP but 9 or 10 connections are open. Using chatwoot 3.5.2

### To Reproduce

Create an email inbox and set it up to recieve mail from an IMAP server

### Expected behavior

The IMAP connection should either be closed after the messages are processed, or kept open and re-used on the next poll.

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by af7567** [comment]
Sorry, I just checked the version and I have 3.6.0 apparently.
I thought I had 3.5.2 because cwctl -u shows `Upgrading Chatwoot to v3.5.2`

**Comment by theresistance2** [comment]
I'm on V3.6.0 and i have exactly the same problem. Is there any fix I can apply?

**Comment by af7567** [comment]
I fixed it for myself in my fork at https://github.com/af7567/chatwoot but I never really used ruby before so wouldn't trust it to be right :)

What I did was create a disconnect method in the fetch_email service and then call it after the emails had been processed. It's been working OK for me until a proper fix is made.

**Comment by theresistance2** [comment]
Sounds good, but as i never worked with chatwoot or ruby before, how can i apply that method in my installation?
excuse the mega-noob question..

**Comment by af7567** [comment]
I'm afraid there is no simple way to apply the changes I made to your own installation, so you would be better waiting for an official fix.

The only way I can think of to work around the problem in 3.6.0 is to increase the limits on the IMAP server if possible. For dovecot IMAP server that seems to be in the file `/etc/dovecot/conf.d/20-imap.conf` where you can uncomment and change the `mail_max_userip_connections` variable.

If you are just testing things at the moment, you could also restart the chatwoot server every hour or so which would close the connections.

**Comment by theresistance2** [comment]
unfortunately, i have no access to the imap server.

i added your disconnect-method to the .rb file in the services folder, and i have to use your fetch_imap_emails_job.rb as well?

Thanks so much!

**Comment by af7567** [comment]
Yes, if you add the disconnect method to `app/services/imap/base_fetch_email_service.rb` you would also need to modify `app/jobs/inboxes/fetch_imap_emails_job.rb` too so it actually calls it. You could also just take a copy of those 2 files from my fork and overwrite your ones.

After updating the files you may just need to restart chatwoot for it to use them. 

I'm not sure if you need to rebuild anything before restarting chatwoot but I always did anyway with the commands taken from the cwctl script:
```
bundle
yarn
rake assets:precompile RAILS_ENV=production NODE_OPTIONS=--openssl-legacy-provider
```

**Comment by theresistance2** [comment]
Seems to be working, thank you **SO** much!

**Comment by pranavrajs** [comment]
@af7567 Thanks for reporting the issue and the work done here. Appreciate the investigation. I've made changes for the same in the PR. https://github.com/chatwoot/chatwoot/pull/9225#issue-2238441401.

You could use the main branch from the next version instead of the fork.

**Comment by af7567** [comment]
I have upgraded CW now and IMAP is working correctly without getting throttled thanks. I did notice though that the connections still stick around in the state CLOSE_WAIT. Maybe because `logout` is used which causes the server to close the connection but the client still keeps the connection open.
This doesn't seem to affect the operation of IMAP fetching, but I think the client should also be closing the connection maybe.
```
 # netstat -n | grep 993
tcp       25      0 192.168.1.29:38532      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:41666      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:36048      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:39198      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:60676      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:49742      12.34.56.42:993       CLOSE_WAIT 
tcp       25      0 192.168.1.29:51212      12.34.56.42:993       CLOSE_WAIT 
```

**Comment by pranavrajs** [comment]
@af7567 Thanks, let me take a look and see if there is any thing which I missed.
