### ISSUE TITLE
Send Email Transcript Macro Action No Longer Working

### ISSUE THREAD

**Issue by Seanytype** [chatwoot/chatwoot#8992]
### Describe the bug

When adding the Action "Send Email Transcript" to a Macro sequence, nothing is sent to the intended recipient. 

### To Reproduce

1. Setup a new Macro
2. Add the "Send Transcript" Action to the sequence
3. Test the Macro on a message
4. See that a transcript is not delivered to the intended email address 

### Expected behavior

1. A transcript should be sent to the desired email address
2. That transcript should include all crucial information, like the original senders email address 
_(see Additional Context section)_

### Additional context

The feature in question previously had some level of functionality, but now it appears to be _completely_ inoperative. 

My previous concern stemmed from an unresolved issue highlighted here: https://github.com/chatwoot/chatwoot/pull/7694

Specifically: **include the sender's email address in the transcript** 

Unfortunately, it seems this aspect was somehow overlooked. This is a critical issue because the "send transcript" feature is rendered essentially useless without it. Given that Chatwoot currently lacks the ability to forward or cc an entire conversation, the inclusion of the sender's email address is crucial for the feature's practicality. 

Resolving this matter is essential for maintaining the basic quality of existing features.

### Environment

app.chatwoot.com

### Platform

Browser

### Operating system

Mac Sonoma

### Browser and version

Firefox

**Comment by pranavrajs** [comment]
This seems to be working fine. Please take a look. https://www.loom.com/share/c0a46cece95f4f6fa106a91d8fad3e4b

If you are on a self-hosted installation, please share additional logs so that we can help to debug this. 
If you are on our cloud, please reach out to us via in-app support so that we can look at the logs. 

The PR mentioned in this issue seems to be unrelated. It's not solving forward or cc if I understand it correctly.

**Comment by Seanytype** [comment]
Hi Pranav,

Thank you for your response. Unlike the demonstration in your video, no new
email window opens in my instance. Instead, a brief prompt appears, stating
"macro executed successfully." However, as I mentioned in my bug report, no
message is received at the designated email address. There's no error, so
I'm uncertain about how to provide logs as you suggested.

Your video did not clarify whether the email was actually received in the
recipient's inbox though.

Regarding the "forwarding or cc" feature and pull request: in Chatwoot,
forwarding is not an available feature. The CC function only sends the last
message in the conversation, not the entire exchange. Therefore, "send
email transcript" could be an alternative, but it didn't function as
expected. This was the issue I previously raised in our past email
exchange. I also highlighted it once again in the additional context of my
bug report.

Again to remind it was that "send email transcript" macro fails to include
complete information in the recipient's inbox, notably the original
sender's email address. Consequently, the recipient cannot reply to the
original sender. I hope this clarifies the situation.

Thanks again,

Angelo

**Comment by sojan-official** [comment]
@Seanytype  Thanks for the follow up
