### ISSUE TITLE
Feature: Show a setup installation page when no superadmin/accounts are available

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#900]
**Problem**

The current installation process in Heroku/any other provider is hard. After the installation is up and running user has to go to DB to create an admin account.

**Solution**

To make this process easier, create a setup page where the user can provide an email address and password.

**Comment by pranavrajs** [comment]
@sojan-official Can't we close this issue?

**Comment by sojan-official** [comment]
Closing this since admin accounts are created during installation flow. We can revisit creating super admin accounts at a later point.

**Comment by ChrisvanChip** [comment]
> Closing this since admin accounts are created during installation flow. We can revisit creating super admin accounts at a later point.

Isn't it an idea to make the first admin automatically super admin? If a company requires more super admin accounts, they can do so through the console.

**Comment by sojan-official** [comment]
@ChrisvanChip Starting from the upcoming release, the first user account on chatwoot will automatically be a super admin as well.
