### ISSUE TITLE
Helpcenter API: Retrieve Articles via API

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#9001]
### Is your feature or enhancement related to a problem? Please describe.

This is a small extra feature. The current Help Center API allows me to add new articles, but it would also be nice to be able to retrieve the articles, similar to how i can retrieve from https://www.chatwoot.com/developers/api/#tag/Help-Center/operation/get-portal etc.

### Describe the solution you'd like

Just a "get-article" API operation similar to  https://www.chatwoot.com/developers/api/#tag/Help-Center/operation/get-portal etc. where i just define the ID of the article.

**Comment by pranavrajs** [comment]
@brundles Thanks for the note. We haven't documented the APIs because they are subject to upcoming changes. A publicly documented API undergoing drastic changes wouldn't be effective. I'll close this for now as lack of documentation is intended at the moment and we would open it up once stabilized.

**Comment by brundles** [comment]
Hi @pranavrajs ok - but is there currently any way to retrieve the "help center" articles via API? I can insert them I can see, so if I could just pull them out in the same format, that would be excellent :)

**Comment by sojan-official** [comment]
@brundles  you can mimic the same APIs which the Chatwoot frontend uses.  Just take a peak into the network tab in your browser console.

**Comment by brundles** [comment]
Yes - that is super, thank you @sojan-official - that works for me :)
