### ISSUE TITLE
Android app no notifications

### ISSUE THREAD

**Issue by subngrill** [chatwoot/chatwoot#9007]
### Describe the bug

Hello Support
The android app have issues the app received the email channels message inside but not received push notifications in the app after the message arrived in the app this have issues with push notifications I have Samsung S24 Ultra and not working and the all permissions is allowed

I take screenshot and upload here
![Screenshot_20240224_083804_Settings](https://github.com/chatwoot/chatwoot/assets/150310679/5ff86076-1d44-4539-b78d-352cfe7efe24)

### To Reproduce

I describe above 

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Mobile

### Operating system

Android 14

**Comment by subngrill** [comment]
@flavioxx I solved uninstall the app and install the app and get permissions after login in the settings app un the notifications tab enable push notifications and working

**Comment by flavioxx** [comment]
> @flavioxx I solved uninstall the app and install the app and get permissions after login in the settings app un the notifications tab enable push notifications and working

I did this and it didn't solve it, I also noticed that on the computer the notification sound is not playing even though I enable notifications, is it because of docker? , I was using normal installed directly on the server, I installed it in Docker and everything works perfect, the only problem is the service notifications on both PC and Android.

**Comment by subngrill** [comment]
If you change it to docker then you have to configure the FCM files of the vapid keys in the env, which are not installed when it is in dcoker, that is why I prefer and use it directly in Ubuntu

**Comment by flavioxx** [comment]
> If you change it to docker then you have to configure the FCM files of the vapid keys in the env, which are not installed when it is in dcoker, that is why I prefer and use it directly in Ubuntu

Can you explain to me what I put in the docker env friend? , it would help a lot. Thanks for the feedback
