### ISSUE TITLE
Cancelling Google OAuth signup redirects user to `/auth/sign_in`

### ISSUE THREAD

**Issue by Nuzair46** [chatwoot/chatwoot#9012]
### Describe the bug

Cancelling the signup process in the Google OAuth screen redirects the user to `/auth/sign_in` route. This is usually a devise error.
![image](https://github.com/chatwoot/chatwoot/assets/38219313/f4cd1ad4-7a4c-4dd6-baa2-aad20446e2b4)

This will only happen when its a new user and needs to accept terms to continue. But if cancelled the user is redirected to this page.

### To Reproduce

1. Production or local
2. Login via gmail and use a new user.
3. During the initial Google app policy and terms page, click cancel instead of continue.
4. This will trigger this bug.

### Expected behavior

For a better UX, it is better to redirect the user to the login page or some other landing page. And the actual error should be logged for the developers.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

MacOS Ventura

### Browser and version

MS Edge (Chromium)

### Additional context

Solution:
We can override the `DeviseTokenAuth::SessionsController#new` to fix this.
before:
```rb
class DeviseTokenAuth::SessionsController # this is the logic inside the gem devise_token_auth
  def new
    render_new_error #this renders an error message that is shown in the image above.
  end
end
```
after:
```rb
class DeviseOverrides::SessionsController < DeviseTokenAuth::SessionsController
  def new
    # Maybe log here so the developers are aware of this.
    redirect_to login_page_url(error: 'access-denied') # this method will redirect to login page
  end
end
```

I tested this on local and is working as expected. I can help with PR. 🐱

**Comment by sojan-official** [comment]
@Nuzair46, Thanks for spotting this. Could you go ahead with a PR ? 🙏 😄
