### ISSUE TITLE
Documentation missing for email ENV config for kubernetes

### ISSUE THREAD

**Issue by pavlotsyhanok** [chatwoot/chatwoot#9045]
### Describe the bug

While deploying Chatwoot on Digital Ocean using your official Helm charts, I followed the provided instructions. However, I faced an issue with the email functionality not working correctly, specifically during the password reset process.

**Steps Followed:**

I deployed the Helm charts using the following command and env config, as per your documentation:

<img width="906" alt="image" src="https://github.com/chatwoot/chatwoot/assets/130260096/99125b0e-dbd8-4728-97ab-fab6b2bb3c1c">

```
helm upgrade chatwoot chatwoot/chatwoot \
  --set env.FRONTEND_URL="https://xxxx.xxx.com" \
  --set env.SMTP_ADDRESS="smtp.sendgrid.net" \
  --set env.SMTP_AUTHENTICATION="plain" \
  --set env.SMTP_DOMAIN="xxx@xxx.com" \
  --set env.SMTP_ENABLE_STARTTLS_AUTO="true" \
  --set env.SMTP_PORT="587" \
  --set env.SMTP_USERNAME="apikey" \
  --set env.SMTP_PASSWORD="SG.xxxx.xxxxx-xxxx-xxxxx" \
  -n default
```

Post-deployment, I encountered an issue where the password reset emails were not being sent.

<img width="287" alt="image" src="https://github.com/chatwoot/chatwoot/assets/130260096/237363a2-604a-4bcc-86c4-5f98ab647722">

**Resolution:**

After some investigation, including watching a tutorial video (linked here: [YouTube Tutorial](https://www.youtube.com/watch?v=iN2Dl0QkvEg&t=332s&ab_channel=Chatwoot)), I realized the environment variable `env.MAILER_SENDER_EMAIL` was not mentioned in your documentation. Upon adding this variable to the Helm chart configuration, the email functionality started working correctly.

**Suggested Documentation Update:**

I recommend updating the Helm chart deployment guide to include the `env.MAILER_SENDER_EMAIL` configuration. This addition will help future users avoid similar issues and streamline the deployment process.

### To Reproduce

1. Deploy k8s on Digital Ocean (or any other platform)
2. Enter   --set env as per documentation
3. Try calling email service to reset password

### Expected behavior

.env variables should be mentioned in official documentation

### Environment

Kubernetes

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
@pavlotsyhanok Thank you for trying out Chatwoot and taking the time to report this issue. 

I checked this out, and the `MAILER_SENDER_EMAIL` environment variable part is mentioned on all deployment pages.

1. https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts/#chatwoot-environment-variables
2. https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-emails
3. https://github.com/chatwoot/charts/tree/main/charts/chatwoot#chatwoot-environment-variables

Could you please share the doc/guide you followed for the installation?

**Comment by pavlotsyhanok** [comment]
Hi @vishnu-narayanan ,

I followed this page:

https://www.chatwoot.com/docs/self-hosted/deployment/helm-charts/

And **you are right**, it is there, however I must have overlooked it, I would recomend moving it closer to other email related variables:

![image](https://github.com/chatwoot/chatwoot/assets/130260096/3007117f-148e-4367-a8fe-db1cbfc4b054)

**Comment by vishnu-narayanan** [comment]
@pavlotsyhanok Thank you for the feedback. We are in the process of migrating env variables to something that can be updated from the super admin UI. That should help as we can group related variables together - Email, Facebook, and Storage. etc.
