### ISSUE TITLE
bug: Super Admin broken CSS

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#9047]
### Describe the bug

Reports of broken CSS in super admin  3.6.0

- https://discord.com/channels/647412545203994635/1212433294780530768
- https://discord.com/channels/647412545203994635/1212839146070999100/1212839146070999100

### To Reproduce

- Access super admin post update or install

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

**Comment by fsentinel** [comment]
Steps that work for me:

#update node to v20
sudo npm cache clean -f
sudo npm install -g n
sudo npm update

npx update-browserslist-db@latest

cwctl -upgrade

#If problem still persists, does it:
sudo -i -u chatwoot
cd chatwoot
RAILS_ENV=production rake assets:clean assets:clobber assets:precompile
cwctl -r

**Comment by sojan-official** [comment]
@fsentinel  Thanks for reporting back 

- closing this since there hasn't been other recent reports
