### ISSUE TITLE
WhatsApp missing profile image 

### ISSUE THREAD

**Issue by subngrill** [chatwoot/chatwoot#9054]
### Describe the bug

Hello Support i configure WhatsApp with cloud api send and receive perfectly the message but the user contact us profile picture not show in the conversation only show the contact name if defined but the profile pic no check screenshot i take and upload

![Screenshot_20240302_090412_Chrome Beta](https://github.com/chatwoot/chatwoot/assets/150310679/95af85c4-48a1-43e4-9442-cf9bbe2a5775)

### To Reproduce

Chatwoot self hosted versión 3.6.0
WhatsApp cloud api

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.4

**Comment by tiictechnology** [comment]
Estou com essa mesma dúvida e sem resposta!

#7288
