### ISSUE TITLE
Channel user data missing 

### ISSUE THREAD

**Issue by subngrill** [chatwoot/chatwoot#9075]
### Describe the bug

Hello Support i configure WhatsApp with cloud api send and receive perfectly the message but the user contact us profile picture not show in the conversation only show the contact name if defined but the profile pic no check screenshot i take and upload, or i need configure additional to get customer profile picture in WhatsApp?  

Please help me with this situation , get the username but not show the image profile in the conversacion check here.

![309474970-95af85c4-48a1-43e4-9442-cf9bbe2a5775](https://github.com/chatwoot/chatwoot/assets/150310679/99102638-6f32-4071-992e-e351005674d6)

### To Reproduce

ready describe above

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@subngrill Can you please share more information here? 

1/ Are you on Chatwoot cloud or are you on a self-hosted instance? If you are on cloud, please reach out to us on internal support. 

2/ If you are on self-hosted, please share the version you are using, the server logs etc.

**Comment by HighLiuk** [comment]
@pranavrajs Same problem here. I cannot see neither profile image nor profile name, just phone number.
![Markup 2024-09-04 at 17 23 29](https://github.com/user-attachments/assets/bd5ca1b1-74e9-4e65-a74b-c6a1363f6647)
In my case I'm using a Twilio WA inbox with docker chatwoot/chatwoot:latest (created 6 weeks ago)

**Comment by sojan-official** [comment]
- Profile picture is not exposed in whatsapp APIs hence it won't be available 
- if you have a picture you would like to update for the contact, you can update it using edit contact option
