### ISSUE TITLE
microsoft email option is grayed out if azure app id not configured

### ISSUE THREAD

**Issue by vishnu-narayanan** [chatwoot/chatwoot#9083]
### Is your feature or enhancement related to a problem? Please describe.

If `AZURE_APP_ID` is not configured, the Microsoft option will be hidden under the email channel. A better UX would be to grey out the MS icon(like we do for FB) so that users are informed of such an option being present.

How it is now?

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/0e539bad-dd0a-485d-a23a-62ad2859b317/2f07abe8-5aa9-4ac7-88b6-8b8b1a637703?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi8wZTUzOWJhZC1kZDBhLTQ4NWQtYTIzYS02MmFkMjg1OWIzMTcvMmYwN2FiZTgtNWFhOS00YWM3LTg4YjYtOGI4YjFhNjM3NzAzIiwiaWF0IjoxNzA5ODgyMDEwLCJleHAiOjMzMjgwNDQyMDEwfQ.BcCXNUypGXzHqbZjhFq0VqRLByDqepYJ8dOqrnoodGI)

### Describe the solution you'd like

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/502c596c-a32a-4bd9-9544-f97e2c04dbed/6710027f-56a9-4a3b-b06b-a4308433d6c1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi81MDJjNTk2Yy1hMzJhLTRiZDktOTU0NC1mOTdlMmMwNGRiZWQvNjcxMDAyN2YtNTZhOS00YTNiLWIwNmItYTQzMDg0MzNkNmMxIiwiaWF0IjoxNzA5ODgyMDEwLCJleHAiOjMzMjgwNDQyMDEwfQ.pSmTZ5mZMTy2HE0Q1KSOfF8onICTACM0BTcBZypW3k0)

### Describe alternatives you've considered

*No response*

### Additional context

Follow the same pattern used for Messenger/Facebook

![image](https://uploads.linear.app/2847f7b9-2caa-474c-b261-1c9bdc2a5da6/9627600f-af2e-486d-b3c6-b5807429a0ca/049586b3-fa86-4299-a7a4-a6cb334495d3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzI4NDdmN2I5LTJjYWEtNDc0Yy1iMjYxLTFjOWJkYzJhNWRhNi85NjI3NjAwZi1hZjJlLTQ4NmQtYjNjNi1iNTgwNzQyOWEwY2EvMDQ5NTg2YjMtZmE4Ni00Mjk5LWE3YTQtYTZjYjMzNDQ5NWQzIiwiaWF0IjoxNzA5ODgyMDEwLCJleHAiOjMzMjgwNDQyMDEwfQ.WHqJEE0greLRHyr88_T6cwHcIioIaVJ-9uROHQQZvUU)

**Comment by MJRT** [comment]
Hi @vishnu-narayanan, I would like to start contributing for chatwoot, could you assign this issue to me?
