### ISSUE TITLE
OpenAI proxy

### ISSUE THREAD

**Issue by dkarelov** [chatwoot/chatwoot#9088]
### Is your feature or enhancement related to a problem? Please describe.

OpenAI sometime does not allow to communicate from certain IP subnets due to unspecified reasons. If Chatwoot happens to be in such a subnet, there is no way to make the OpenAI integration work.

### Describe the solution you'd like

Add a proxy field to OpenAI integration, so all the requests going to OpenAI will use it

**Comment by pranavrajs** [comment]
@dkarelov Is there any documentation we can refer to?

**Comment by dkarelov** [comment]
No documentation needed - just send requests to OpenAI through a proxy server. Any http library that you use to send http requests to OpenAI api should have this functionality, it's a couple of lines of code.

**Comment by pranavrajs** [comment]
This seems like custom request, we will not be supporting it. Please feel free to comment if it is not the case.

**Comment by dkarelov** [comment]
@pranavrajs Not sure I got the logic. Chatwoot sends external requests to a third party (OpenAI). Any app that sends external requests usually has an ability to proxify these requests as can be based in the secure perimeter / has other reasons - e.g. all web browsers has an ability to define proxy, any messaging app has this ability etc. 
Why exactly are you considering this a "custom request" and what exactly it means?

**Comment by pranavrajs** [comment]
If I understand the issue properly, you are trying to add a proxy on Chatwoot for a network issue. I think adding an option in Chatwoot as config is an overkill as it would not be used any other customer.

**Comment by dkarelov** [comment]
No, it is not a network issue. It is an OpenAI issue. And it is extremely hard to overcome it as connection to OpenAI is managed on Chatwoot side. It is easier to change Chatwoot to something else rather than proxify all the requests to OpenAI from Chatwoot. 
At the same time, adding a configuration option to use proxy WITHIN Chatwoot - is a few lines of code. We are discussing it longer than to create it :)

**Comment by pranavrajs** [comment]
I would like to offer a differing viewpoint. This issue does not appear to be specifically related to Chatwoot. If you were to build any service on top of OpenAI, not just Chatwoot, it would likely encounter the same problem in your network. Based on this understanding, the issue should be solved outside of Chatwoot, not within. However, you are welcome to create a fork and add the proxy yourself.
