### ISSUE TITLE
feat: ability to zoom in images

### ISSUE THREAD

**Issue by WevrLabs** [chatwoot/chatwoot#9090]
### Is your feature or enhancement related to a problem? Please describe.

It would be useful to add the ability to zoom images in the chat.

### Describe the solution you'd like

when previewing an image in the chat, there should be an option to zoom the image when hovered over by the mouse, the zoom would be triggered when clicking on the image.

**Comment by pranavrajs** [comment]
Thanks for the suggestion. This is a good candidate for a contribution. Happy to review it if you can contribute.

**Comment by matheus-rodrigues00** [comment]
@pranavrajs I'd be glad to contribute on this one, can you assign to me?
