### ISSUE TITLE
Location Message Text Is Not Wrapped

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#9095]
### Describe the bug

On CW version 3.6.0, when receiving location message, it seems like its not wrapped within chat bubble and bleeds out of it as shown below;

![image](https://github.com/chatwoot/chatwoot/assets/25242465/8ab8ffc5-83bf-47ad-9f7e-3d4e7f2df361)

### To Reproduce

1. Send location message with long address/business name
2. Check in Chatwoot

### Expected behavior

It should wrap within the chat bubble

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Ubuntu 20

**Comment by pranavrajs** [comment]
@sanjayws Thanks for reporting this. We will check it out.
