### ISSUE TITLE
Integration with Telegram does not work

### ISSUE THREAD

**Issue by wedcanto** [chatwoot/chatwoot#9103]
### Describe the bug

I installed chatwoot with the help of the documentation. Installed nginx, domain and my chatwoot is working.

I created a telegram bot in BotFather, and inserted it when creating a channel (I did everything as written in the documentation https://www.chatwoot.com/docs/product/channels/telegram/).

There were no errors.

I'm trying to check the work - I'm writing to this Telegram bot from different accounts. But the messages that are sent to the Telegram bot do not appear in chatwoot. That is, no conversations are created.

What could I have done wrong? (the instructions are quite simple, there is practically nowhere to go wrong).

How to fix it?

Translated with DeepL.com (free version)

### To Reproduce

Install a clean chatwoot, create a bot, connect it as a channel.

### Expected behavior

I wanted to receive chatwoot messages that write to the telegram bot

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

 Ubuntu 22.04.4 LTS

### Browser and version

Firefox 115.8.0esr

### Docker (if applicable)

Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:13:09 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  

### Additional context

no

**Comment by wedcanto** [comment]
> [PR-985 Integration with Telegram does not work](https://linear.app/chatwoot/issue/PR-985/integration-with-telegram-does-not-work)

I'm not allowed access to your link.

**Comment by sojan-official** [comment]
ref: https://github.com/chatwoot/chatwoot/issues/7485#issuecomment-1681168495 

for debugging telegram errors on self-hosted

ref: https://www.chatwoot.com/docs/contributing-guide/telegram-channel-setup

**Comment by wedcanto** [comment]
> @wedcanto, the next thing you can do is verify whether these webhooks are coming correctly to the Chatwoot . you can see it in the logs. Also note that the telegram payload has an error
> 
> " "last_error_message": "Wrong response from the webhook: 404 Not Found","
> 
> Means telegram is experiencing 404 at some point. ensure that your ngrok URL is pointed to the correct port.

Thank you so much for trying to help!
I did the following - from scratch, installed Chatwoot not in the docker, but following the "Linux VM" instructions. And everything worked...

That's very strange, because I've already tried reinstalling several times. I think the bug can be closed.

But I have a question - where are the Telegram bot files in Chatwoot? I want to order some improvements from a programmer. I need to expand the capabilities of the Telegram bot. I want to send not only text and pictures, but also "Buttons" so that the user can choose from the options I offer.

**Comment by sojan-official** [comment]
closing as original issue is resolved. 

please refer: https://github.com/chatwoot/chatwoot/tree/develop/app/services/telegram

**Comment by KatiaSishost** [comment]
> closing as original issue is resolved.
> 
> please refer: https://github.com/chatwoot/chatwoot/tree/develop/app/services/telegram



I have the same problem, I replaced these files, I tried a systemctl restart chatwoot.target but nothing happened.

in cwctl --web logs

`root@ChatWoot:~# cwctl --logs web
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.106991 #30072]  INFO -- : [0a0a5a1c-1ac6-4183-a9c8-51d500877a60] Completed 200 OK in 11ms (Views: 2.0ms | ActiveRecord: 3.2ms | Allocations: 2397)
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.107668 #30072]  INFO -- : source=rack-timeout id=0a0a5a1c-1ac6-4183-a9c8-51d500877a60 timeout=15000ms service=16ms state=completed
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.666907 #30072]  INFO -- : source=rack-timeout id=9efb225c-e47c-4a00-94cb-5bc0f4de1f22 timeout=15000ms state=ready
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.667906 #30072]  INFO -- : [9efb225c-e47c-4a00-94cb-5bc0f4de1f22] Started GET "/api/v1/accounts/1/conversations?inbox_id=4&status=open&assignee_type=me&page=1&sort_by=last_activity_at_desc" for 192.168.1.1 at 2024-03-24 06:54:27 +0000
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.671721 #30072]  INFO -- : [9efb225c-e47c-4a00-94cb-5bc0f4de1f22] Processing by Api::V1::Accounts::ConversationsController#index as JSON
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.671818 #30072]  INFO -- : [9efb225c-e47c-4a00-94cb-5bc0f4de1f22]   Parameters: {"inbox_id"=>"4", "status"=>"open", "assignee_type"=>"me", "page"=>"1", "sort_by"=>"last_activity_at_desc", "account_id"=>"1"}
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.692299 #30072]  INFO -- : [9efb225c-e47c-4a00-94cb-5bc0f4de1f22]   Rendered api/v1/accounts/conversations/index.json.jbuilder (Duration: 2.4ms | Allocations: 563)
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.694652 #30072]  INFO -- : [9efb225c-e47c-4a00-94cb-5bc0f4de1f22] Completed 200 OK in 23ms (Views: 2.1ms | ActiveRecord: 9.4ms | Allocations: 4144)
Mar 24 06:54:27 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:27.695358 #30072]  INFO -- : source=rack-timeout id=9efb225c-e47c-4a00-94cb-5bc0f4de1f22 timeout=15000ms service=28ms state=completed
Mar 24 06:54:46 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:46.988492 #30072]  INFO -- : RoomChannel#update_presence
Mar 24 06:54:51 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:51.258495 #30072]  INFO -- : source=rack-timeout id=12d1c0cd-f19d-4766-b4dc-c2e54f2612ec timeout=15000ms state=ready
Mar 24 06:54:51 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:51.259324 #30072]  INFO -- : [12d1c0cd-f19d-4766-b4dc-c2e54f2612ec] Started POST "/webhooks/telegram/5951153007:AAGKYiQibfAFFrmmHpcydz-XXXXXX" for 91.108.6.36 at 2024-03-24 06:54:51 +0000
Mar 24 06:54:51 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:51.263316 #30072]  INFO -- : [12d1c0cd-f19d-4766-b4dc-c2e54f2612ec] Processing by Webhooks::TelegramController#process_payload as HTML
Mar 24 06:54:51 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:51.263474 #30072]  INFO -- : [12d1c0cd-f19d-4766-b4dc-c2e54f2612ec]   Parameters: {"update_id"=>976493067, "message"=>{"message_id"=>178, "from"=>{"id"=>2049270318, "is_bot"=>false, "first_name"=>"MC", "username"=>"XXXX", "language_code"=>"es"}, "chat"=>{"id"=>2049270318, "first_name"=>"MC", "username"=>"XXXX", "type"=>"private"}, "date"=>1711263291, "text"=>"/start", "entities"=>[{"offset"=>0, "length"=>6, "type"=>"bot_command"}]}, "bot_token"=>"[FILTERED]", "telegram"=>{"update_id"=>976493067, "message"=>{"message_id"=>178, "from"=>{"id"=>2049270318, "is_bot"=>false, "first_name"=>"MC", "username"=>"XXXX", "language_code"=>"es"}, "chat"=>{"id"=>2049270318, "first_name"=>"MC", "username"=>"XXXX", "type"=>"private"}, "date"=>1711263291, "text"=>"/start", "entities"=>[{"offset"=>0, "length"=>6, "type"=>"bot_command"}]}}}
Mar 24 06:54:51 ChatWoot chatwoot-web.1[30072]: I, [2024-03-24T06:54:51.265338 #30072]  INFO -- : [12d1c0cd-f19d-4766-b4dc-c2e54f2612ec] [ActiveJob] Enqueued Webhooks::TelegramEventsJob (Job ID: 245e473d-a714-4bf5-85fd-f0ed18735634) to Sidekiq(default) with arguments: {"update_id"=>976493067, "message"=>{"message_id"=>178, "from"=>{"id"=>2049270318, "is_bot"=>false, "first_name"=>"MC", "username"=>"XXXX", "language_code"=>"es"}, "chat"=>{"id"=>2049270318, "first_name"=>"MC", "username"=>"XXXX", "type"=>"private"}, "date"=>1711263291, "text"=>"/start", "entities"=>[{"offset"=>0, "length"=>6, "type"=>"bot_command"}]}, "controller"=>"webhooks/telegram", "action"=>"process_payload", "bot_token"=>"5951153007:AAGKYiQibfAFFrmmHpcydz-XXXXX", "telegram"=>{"update_id"=>976493067, "message"=>{"message_id"=>178, "from"=>{"id"=>2049270318, "is_bot"=>false, "first_name"=>"MC", "username"=>"XXXX", "language_code"=>"es"}, "chat"=>{"id"=>2049270318, "first_name"=>"MC", "username"=>"XXXX", "type"=>"private"}, "date"=>1711263291, "text"=>"/start", "entities"=>[{"offset"=>0, "length"=>6, "type"`
