### ISSUE TITLE
cwctl upgrade from develop branch 

### ISSUE THREAD

**Issue by sah-anshu** [chatwoot/chatwoot#9115]
### Is your feature or enhancement related to a problem? Please describe.

I have installed the application using cwctl -i which is targetted to master branch .

### Describe the solution you'd like

 I don't want to loose existing data. Is it possible to upgrade from develop branch.

**Comment by vishnu-narayanan** [comment]
@sah-anshu It is recommended to use the `master`/release branch for stability and the reason why its the default. Changes are merged multiple times a day to `develop` and might be unstable at times. 

If needed, you can modify the `upgrade` function in  `cwctl` to use the `develop` branch and use the `--upgrade` to pull in changes from develop.

Please reopen if you are facing issues.
