### ISSUE TITLE
Widget is not working in native Facebook Messenger Browser

### ISSUE THREAD

**Issue by p1rkl** [chatwoot/chatwoot#9145]
### Describe the bug

Seems like the widget is not working in the native facebook messenger browser. It's like not appearing at all.

### To Reproduce

1. Any environment
2. Any config
3. -
4. -

### Expected behavior

It should appear even in native browsers like facebook messenger

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
@p1rkl I am not able to understand. Would you be able to share a recording/screencast?

**Comment by humbernieto** [comment]
Facebook Messenger widgets disabled, cannot be used

[](url)
<img width="1470" alt="Captura de pantalla 2024-04-12 a las 3 42 29 a  m" src="https://github.com/chatwoot/chatwoot/assets/56887259/018b5568-59c8-4173-b02f-7efab52f64fc">

**Comment by pranavrajs** [comment]
Please use this guide to set it up [here](https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup).

**Comment by humbernieto** [comment]
Check the image on the chatwoot platform, it does not allow adding, it appears as disabled, I am not referring to Meta, I viewed the image, it even appears in black and white, it is disabled, let me understand.

**Comment by sojan-official** [comment]
> Check the image on the chatwoot platform, it does not allow adding, it appears as disabled, I am not referring to Meta, I viewed the image, it even appears in black and white, it is disabled, let me understand.

You need to configure the environment variable for messenger to be enabled as @pranavrajs  mentioned in the docs

**Comment by humbernieto** [comment]
Thank you very much, I just found them
FB_VERIFY_TOKEN=
FB_APP_SECRET=
FB_APP_ID=

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still facing issues.
