### ISSUE TITLE
Feature: Ability for the logged in user to create a new account

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#915]
Since chatwoot supports multiple accounts, a logged-in user should be to create a new account from dashboard. 

- Account switcher should give the option to create a new account
- On clicking the button modal shows a form asking for the account name 
- clicking save redirects to new account/show validation errors

## Notes 
- Account switcher appear only when you have multiple accounts 
- Use super admin/console to add multiple accounts for a user at the moment

## Mocks

![Screenshot 2020-06-02 at 10 23 57 AM](https://user-images.githubusercontent.com/73185/83481366-2f711080-a4bb-11ea-8f94-752cbbaf9924.png)

![Screenshot 2020-06-02 at 10 30 46 AM](https://user-images.githubusercontent.com/73185/83481733-27fe3700-a4bc-11ea-8bf9-b6e5f1547ddb.png)

**Comment by nithindavid** [comment]
I would prefer making `Create new account` as button text and `Create` instead of `submit`.

**Comment by divyesh2506** [comment]
Would like to work on this.

**Comment by sojan-official** [comment]
@divyesh2506   feel free to go ahead. i have assigned the issue to you. let us know if you have any questions :)

**Comment by divyesh2506** [comment]
@sojan-official we do need to ask for domain and support_email in the input box along with Account name, right?

**Comment by sojan-official** [comment]
@divyesh2506 thanks for bringing that up. they can configure these settings later in the account settings page. These settings might not be relevant for all users. 
So in this flow lets focus on collecting the bare minimum fields needed for an account ( same fields as signup )

**Comment by divyesh2506** [comment]
#985
