### ISSUE TITLE
@pranavrajs Can I check if any updates on this to use the 360 Dialog Cloud API?

### ISSUE THREAD

**Issue by oguzaltnby** [chatwoot/chatwoot#9152]
@pranavrajs Can I check if any updates on this to use the 360 Dialog Cloud API?
FYI - 360dialog are removing the On-premise APIs later this year (as their partner sent us the email and asking us to migrate to 360Dialog Cloud API instead of On-premise APIs)

_Originally posted by @harismateen in https://github.com/chatwoot/chatwoot/discussions/8185#discussioncomment-8815866_

**Comment by harismateen** [comment]
Sorry, i dont understand. Is it already done?
