### ISSUE TITLE
Bug: Dashboard breaks for a user without  associated accounts logs in

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#916]
**Describe the bug**
- Given  an agent/administrator in chatwoot account
- and an administrator removes the agent/administrator from the account 
- When the agent/administrator logs into the chatwoot account 
- the application throws a blank page 

Possible fixes:  
- show a screen showing you don't have access to any chatwoot accounts
- show create a new account screen as per #915

**Comment by neymarsabin** [comment]
@pranavrajs @sojan-official I would like to work on this.

**Comment by sojan-official** [comment]
@neymarsabin feel free to go ahead.
