### ISSUE TITLE
Customizable Timeout for Webhook Responses to Support Media Messages

### ISSUE THREAD

**Issue by VinCardoso** [chatwoot/chatwoot#9166]
### Describe the bug

When sending media messages (audio or images) via the WhatsApp (using a third-pary API), the operation often exceeds the hardcoded 5-second response wait limit in Chatwoot's webhook trigger logic. This results in the Chatwoot UI incorrectly indicating that the message was not sent, despite successful delivery on WhatsApp.

Print on Chatwoot:
<img width="540" alt="Screenshot 2024-03-27 at 11 40 40" src="https://github.com/chatwoot/chatwoot/assets/5439301/cd8eb41b-5fc4-4831-ad36-3f54982de6a3">

Print same conversation part on Whatsapp:
![IMG_B14A56549DB1-1](https://github.com/chatwoot/chatwoot/assets/5439301/20ba0991-a141-46ca-979a-7033b8ad1ee5)

The mídia was send, but on chatwoot said was a error of Timed out.

### To Reproduce

1. Configure Chatwoot to send media messages via the WhatsApp
2. Send a media message (either audio or image) through the API.
3. Observe that the Chatwoot UI indicates the message was not sent.

### Expected behavior

Chatwoot should accurately reflect the sent status of media messages. The system should wait longer than 5 seconds for a response when sending media messages through APIs. Making the wait time configurable via an environment variable would accommodate the varying response times for different media types and API/Webhook integrations.

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

MacOS 14.1.2

### Browser and version

Google Chrome Version 123.0.6312.59

### Docker (if applicable)

Docker Image:

https://hub.docker.com/layers/chatwoot/chatwoot/latest/images/sha256-3f88c2017f82e43793c2e135bff87c9382b45c7dd5a9920803ed1d8878efe49f?context=explore

Using Chatwoot version 
v3.7.0

### Additional context

The hardcoded wait time is located in trigger.rb at:

lib/webhooks/trigger.rb#29

A flexible timeout setting, configurable through an environment variable, would prevent messages from being prematurely marked as unsent. This enhancement is crucial for maintaining reliability and improving user experience, particularly in scenarios involving media-rich interactions over WhatsApp.

**Comment by vishnu-narayanan** [comment]
@VinCardoso Thank you for the detailed bug report.

**Comment by numb7** [comment]
Hi
We have a similar problem, but with messages

**Comment by sojan-official** [comment]
@VinCardoso, is there a specific third-party API which you are using or is it custom-managed? Longer timeouts mean jobs pending in the queue for long, which would impact subsequent jobs and slow down the system in general. 

We recommend handling message webhooks asynchronously, particularly actions such as media downloads, etc., in background jobs. This approach should help streamline the process and improve system efficiency

**Comment by andersonlemesc** [comment]
I have the same problem, using a third-party evolution API that works with Baileys,

When the media is larger, the API takes a long time to process it and chatwoot reports a timeout. 
I think a difference of 2 to 3 seconds would solve the problem. 

API used https://doc.evolution-api.com/v2/pt/get-started/introduction

**Comment by sojan-official** [comment]
I am closing this issue as it occurs with third-party apps, not with official providers. We have implemented the 5-second timeout to ensure the job queues don't get clogged up. I would recommend asking the third-party provider you use to process the webhook async.
