### ISSUE TITLE
No onboarding installation shown after deploying chatwoot

### ISSUE THREAD

**Issue by justrdk** [chatwoot/chatwoot#9169]
### Describe the bug

Hello, I am currently deploying chatwoot via helm into my k8s cluster. Application runs with no problems. I can sign up users and do everything in chatwoot I need to.

The problem I have is that I can't seem to be able to get a super admin user. According to documentation, the first account created on the application will be a super admin. After reading the source code I noticed this is done in the onboarding controller which is called in installation/onboarding route.

When I try to go to the installation onboarding route I get redirected to the root route of the application. So I only have choice to either signup or login. Problem here is that the signup page doesn't calls the onboarding controller but the account controller and the latter doesn't handles setting super admin to the account.

### To Reproduce

1. Deploy chatwoot with helm
2. Notice no onboarding route is loaded when deploying the application

### Expected behavior

I would expect that if no accounts are found on the database then the onboarding screen should be shown. Or when creating an account from the signup page, if there are no other accounts, the one being created is set as super admin.

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

### Browser and version

Brave Browser

### Additional context

I found this comment stating the new account flow, but that doesn't seems to be happening for me:
https://github.com/chatwoot/chatwoot/issues/900#issuecomment-1027311064

**Comment by vishnu-narayanan** [comment]
@justrdk Have you been trying out the installation multiple times? Installation via helm chart provisions redis/postgres which uses persistent volumes. These volumes will persist even if you delete the helm installation and install again. Chatwoot relies on key in redis to show the onboarding page.


Could you try deleting the helm installation along with persistent volumes for both postgres and redis and try a fresh install?

**Comment by gkp1** [comment]
I just installed using docker on ubuntu 22.. Main route redirects me automatically to login page instead of onboarding. Can't create first user, pruned everything from docker with `system prune` and `volume prune` before, so it is not caused by previous installations. 

It does not redirect me to `installation/onboarding`, and the onboarding route directs me to login page. I am testing currently on `serverIp:port/installation/onboarding`. The only thing different from the guide is that I used '3010:3000' instead of '127.0.0.1:3010:3000' to enable testing the app with the server ip `serverIP:port`.

Not sure if it only works if I configure SSL, I will point my domain to it and point nginx and report back here if it fixes this issue (I don't think it will)

`Docker Compose version v2.25.0` 
`Docker version 26.0.0, build 2ae903e`

**Comment by iannortnau** [comment]
We were able to solve this problem by running this command directly in the Redis console.

`Redis::Alfred.set(Redis::Alfred::CHATWOOT_INSTALLATION_ONBOARDING,` true)`

**Comment by justrdk** [comment]
> @justrdk Have you been trying out the installation multiple times? Installation via helm chart provisions redis/postgres which uses persistent volumes. These volumes will persist even if you delete the helm installation and install again. Chatwoot relies on key in redis to show the onboarding page.
> 
> Could you try deleting the helm installation along with persistent volumes for both postgres and redis and try a fresh install?

Same issue for me, everytime I provisioned a new chatwoot on cluster I don't get the onboarding screen.

**Comment by vishnu-narayanan** [comment]
@justrdk Have you been trying out the installation multiple times? Installation via helm chart provisions redis/postgres which uses persistent volumes. These volumes will persist even if you delete the helm installation and install again. Chatwoot relies on key in redis to show the onboarding page.

Could you try deleting the helm installation along with persistent volumes for both postgres and redis and try a fresh install?

**Comment by justrdk** [comment]
@vishnu-narayanan I deleted pvcs for both postgres and redis and did a fresh install and I still don't get the onboarding screen. I checked the database as well and there are no users stored in it at the time I first load the application.

**Comment by vishnu-narayanan** [comment]
@justrdk That should have worked.  You could try the redis workaround.

After deploying the chart, once the pods are up ssh into the redis pod. Access the `redis-cli` and run `Redis::Alfred.set(Redis::Alfred::CHATWOOT_INSTALLATION_ONBOARDING, true)`

Then try loading https://<your-installation-url>.

**Comment by vishnu-narayanan** [comment]
@justrdk Did it work for you?

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still facing issues.
