### ISSUE TITLE
Server 500-ing

### ISSUE THREAD

**Issue by AdityaAnand1** [chatwoot/chatwoot#917]
![image](https://user-images.githubusercontent.com/13274079/83502132-cac7ad00-a4de-11ea-95d1-005ab9a344e3.png)

Any idea what this is about? Is this project defunct? If so, it should be mentioned in the readme/archived. I just deployed to heroku, not sure where to go as there's no documentation anywhere.

**Comment by pranavrajs** [comment]
@AdityaAnand1 
1. Have you set up the required environment variables? https://www.chatwoot.com/docs/environment-variables

2. Would you share the server logs or logs of the 500 error response?

3. Please check if the services are up and running.

<img width="1239" alt="Screenshot 2020-06-02 at 3 07 54 PM" src="https://user-images.githubusercontent.com/2246121/83505010-d7e69b00-a4e2-11ea-8aef-603d1df17692.png">

**Comment by AdityaAnand1** [comment]
Which exact bare minimum environment variables are needed with heroku deploys?

* Hasn't it configured DB access automatically? And redis too?
* Do I have to setup a SMTP server myself? Is there a recommended approach or provider?

There should really be a minimal getting started document 😅, I suspect most people using this just want a quick and dirty plug and play intercom alternative for their website. Maybe we can start building one by recording the challenges I'm encountering, to begin with.

**Comment by AdityaAnand1** [comment]
Much of the documentation seems to be about building and running and developing the project rather than deploying as a plug and play self hosted chat service.

**Comment by pranavrajs** [comment]
@AdityaAnand1 That's the experience that we are aiming but that would take couple more sprints.

**Comment by AdityaAnand1** [comment]
No issues, all good things take time :) 

In the meantime, let's get back to this issue.

Which exact bare minimum environment variables are needed with heroku deploys?

* Hasn't it configured DB access automatically? And redis too?
* Do I have to setup a SMTP server myself? Is there a recommended approach or provider?

**Comment by pranavrajs** [comment]
> Hasn't it configured DB access automatically? And redis too?

This would be done automatically. 

> Do I have to setup a SMTP server myself? Is there a recommended approach or provider?

You can use any of the providers like Amazon SES, Sendgrid, MailChimp or Mailgun. Make sure you set the variables correctly.

**Comment by AdityaAnand1** [comment]
Really sorry, but I don't have time to do so much configuration to get this set up.

I went with drift chat instead, they have a decent free plan. Took maybe 5 minutes to onboard and deploy.

Really hope this project achieves true one click deployment some day. Good luck!

This project could do really well if it focused solely on quality and dev experience, even at the expense of certain features initially. I could see it even being monetized very well like Hasura or HashiCorp with a FOSS/Enterprise-paid business model. But for that to happen, the quality needs to be there :)

**Comment by sojan-official** [comment]
@AdityaAnand1 if you weren't particularly looking for a self-hosted solution, you could always try out the cloud version of chatwoot at https://app.chatwoot.com/ 

On the self-hosted front, we are always working on improving the deployment experience. It's an iterative process primarily based on user feedback. So thanks for that. 
Just that it would take a couple more sprints as Pranav stated above for us to truly get there. So do watch the space :)
