### ISSUE TITLE
confirm my account link in email causing the page freezing.

### ISSUE THREAD

**Issue by mo-ay** [chatwoot/chatwoot#9175]
### Describe the bug

when adding a new user from super admin, and the user receive the confirmation email with a link, and the user click on the link to confirm his email a new page opened and causing a freeze for ever. unless we 

### To Reproduce

1. self-hosting  in a linux env.
2. the email configured correctly in the .env and the frontendurl.
3. go to super admin -> users -> create new -> fill the fields -> create user.
4. the user will receive a confirmation email with a link " confirm my account" -> click on it -> page frees indefinity.
NOTE: if you create account user for this newly created user before the user click on the "confirm my account" the bug will not appear.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

CentOS Linux Version 7

### Browser and version

ion 122.0.2365.92 (Official build) (64-bit)Version 122.0.2365.92 (Official build) (64-bit)

### Docker (if applicable)

docker version:
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:41 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:44:05 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  
  docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 28
  Running: 16
  Paused: 0
  Stopped: 12
 Images: 37
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1160.49.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.444GiB
 Name: localhost.localdomain
 ID: BAX2:DXBY:LGVQ:DUHL:OQHQ:2LV2:NNGY:TOHB:QMKE:6L73:XBK7:5JTF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

docker-compose version
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by vishnu-narayanan** [comment]
@mo-ay Would you be able to share a screencast/recording of the behaviour?

**Comment by mo-ay** [comment]
yes I can, I'll record this behavior ->

> go to super admin -> users -> create new -> fill the fields -> create user.
> the user will receive a confirmation email with a link " confirm my account" -> click on it -> page frees indefinity.
> NOTE: if you create account user for this newly created user before the user click on the "confirm my account" the bug will not appear.
react if this sufficient, replay if you need other info/logs ..etc.

**Comment by mo-ay** [comment]
well, I can't realy record a video for it, avoid revealing any company's privacy. but I took a screenshots of the problem.
another thing, on firefox only if I wait enough firefox suggest to stop the page, when I stop the page a new scrren shows up  "

> New Account
> 
> Create a new account
> Uh oh! We could not find any Chatwoot accounts. Please create a new account to continue. 

"
first step in:  
![image](https://github.com/chatwoot/chatwoot/assets/71446618/4b602c80-4c3b-4ff8-9d68-4eb9e2e5691d)

second:
![image](https://github.com/chatwoot/chatwoot/assets/71446618/257d3e1a-e82a-4c7d-b421-6e837960575a)

third ( the freezing)

![image](https://github.com/chatwoot/chatwoot/assets/71446618/7f350fcb-5ea9-4bde-b25c-fa652f29ca0f)

after waiting on firefox:
![image](https://github.com/chatwoot/chatwoot/assets/71446618/79f0dd86-b792-4e09-9520-9f4ad04d0688)

after pressing stop in firefox:
![image](https://github.com/chatwoot/chatwoot/assets/71446618/e88be22a-a1fe-462f-bc28-2ea59953b67e)

**Comment by vishnu-narayanan** [comment]
@mo-ay, thank you for sharing the screenshots. This is a known issue at the moment.

As a workaround, what you can do right now is to add the user to an existing account by creating an account user.
