### ISSUE TITLE
We're sorry but something went wrong

### ISSUE THREAD

**Issue by brulio93** [chatwoot/chatwoot#9176]
### Describe the bug

I've installed chatwoot following documentation from https://www.chatwoot.com/docs/self-hosted/deployment/aws/
so far everythign was working fine.

But then I tried to login into the `super_admin` and as well worked fine, then I tried to logout and go to the regular user dashboard and the website shows this error:

![image](https://github.com/chatwoot/chatwoot/assets/13734494/3d1db340-187c-4d51-9d9f-58e7c0c7de06)

But the `super_admin` works fine:

![image](https://github.com/chatwoot/chatwoot/assets/13734494/cb999505-2cd4-4916-ae60-2711da9febd7)

### To Reproduce

1. Go to `<url>/app/login` and use credentials
2. Then create `SuperAdmin` user and login into the `super_admin` dashboard
3. Go again to regular user dashboard

### Expected behavior

Regular user dashboard should work with no issues

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Chrome 123.0.6312.86

**Comment by vishnu-narayanan** [comment]
@brulio93 Are you still facing the issue? If yes, could you share the logs?

ref: https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl#viewing-logs

**Comment by vishnu-narayanan** [comment]
Please reopen if you still have questions.
