### ISSUE TITLE
In dark mode, selecting (highlight) emails don't show the highlighted part

### ISSUE THREAD

**Issue by sanjayws** [chatwoot/chatwoot#9177]
### Describe the bug

When highlighting in light mode, you can see emails you highlighted as below; for example:
![image](https://github.com/chatwoot/chatwoot/assets/25242465/2d11693f-2541-4ca4-8f58-342f8de45fc2)

Now, switching to dark, you can't see highlights using the mouse; for example:
![image](https://github.com/chatwoot/chatwoot/assets/25242465/4271fac5-8033-48b2-ada6-8706a3d97670)

As you can see, the word "elementor" is indeed highlighted as right click does pick it up (mouse menu)

### To Reproduce

1) Select an email
2) Use dark mode
3) Try to highlight text in dark mode

### Expected behavior

Highlights in dark mode should be shown in the email channel

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

MacOS Sonoma 14.4.1

### Browser and version

Chrome 123.0.6312.87

**Comment by pranavrajs** [comment]
@sanjayws This was a deliberate choice for now. Some of the emails contain inline styles that could conflict with dark mode especially the HTML emails.

I will close this for now. We will explore it later if it becomes a problem.

**Comment by sanjayws** [comment]
Understood. Thanks @pranavrajs
