### ISSUE TITLE
Translation: Tamil Language support.

### ISSUE THREAD

**Issue by BTRajan** [chatwoot/chatwoot#918]
Eventhough we can add it on our self-hosted instances, native support would be good.

May be if required we can either do the translation or proof read.

please add.

**Comment by sojan-official** [comment]
We have enabled Tamil support in crowdin 
http://translate.chatwoot.com/

if you guys could contribute, we would love to have Tamil added.

**Comment by BTRajan** [comment]
Thanks Sojan.

**Comment by pranavrajs** [comment]
Closing this as the language is enabled in the version 1.6.x
