### ISSUE TITLE
Obtain IG_VERIFY_TOKEN 

### ISSUE THREAD

**Issue by pelucapampa** [chatwoot/chatwoot#9180]
### Describe the bug

How to obtain IG_VERIFY_TOKEN to environment variable.? 
I setup with token from Page on facebook developer app, but when i try to respond instagram message, I can only respond to facebook app admin.

### To Reproduce

In docker instalation 

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment]
@pelucapampa For `IG_VERIFY_TOKEN`, you have to set a value in the `.env` file and use the same with Facebook developer portal settings.

ref: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup/#configuring-the-environment-variables-in-chatwoot

**Comment by pelucapampa** [comment]
> @pelucapampa For `IG_VERIFY_TOKEN`, you have to set a value in the `.env` file and use the same with Facebook developer portal settings.
> 
> ref: https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/instagram-channel-setup/#configuring-the-environment-variables-in-chatwoot

Thanks, I define this token? Or obtain that ok facebook dev app? Because I'm using instagram Page token obtained on messenger instagram section on dev app
![Screenshot_2024-04-05-05-02-47-644_com android chrome](https://github.com/chatwoot/chatwoot/assets/120580431/969bd35c-02bb-4e5a-b53e-421a556fb2b8)

Could you tell me which option I need to make?
Thanks

**Comment by vishnu-narayanan** [comment]
You set this token in the chatwoot `.env` file and provide the same in FB developer console.

**Comment by vishnu-narayanan** [comment]
Please reopen if you still have questions.
