### ISSUE TITLE
Feature: Toggle web widget between full screen and the current minimized version

### ISSUE THREAD

**Issue by RonWalker22** [chatwoot/chatwoot#920]
**Is your feature request related to a problem? Please describe.**
When the conversation goes beyond a few questions, it frustrating not to be able to transition into full screen mode. Especially if the contextually information from the website itself, is not needed. 

**Describe the solution you'd like**
Allow the contact to toggle the widget between full screen and the current minimized version

**Comment by pranavrajs** [comment]
@RonWalker22 It looks like this is a duplicate for #1058. I'm closing this in favour of #1058 and it will be completed in #1174. Please feel free to reopen if this is not the case.
