### ISSUE TITLE
Reporting Chatwoot Security Vulnerability 

### ISSUE THREAD

**Issue by sahiloj** [chatwoot/chatwoot#9205]
### Describe the bug

Hello Team,

I have reported a security vulnerability Insecure direct object reference which leads to account takeover via the Security advisories. I see no response there any update on that or reply.  How should i report the issue any leads on that ?

Thanks !

### To Reproduce

Please, navigate to security advisories for further information. 

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@sahiloj Please send it to pranav[at]chatwoot[dot]com, sojan[at]chatwoot[dot]com. We will followup with the necessary actions.
