### ISSUE TITLE
Chatwoot Twitter 

### ISSUE THREAD

**Issue by LiLiJal** [chatwoot/chatwoot#9230]
### Is your feature or enhancement related to a problem? Please describe.

Hey, here 
I just read this note here https://www.chatwoot.com/features/twitter-integration " NOTE: Twitter integration has been temporarily discontinued as a result of modifications made by Twitter to its APIs. This includes limitations on the number of requests raised per minute, plus substantial pricing changes." 
Is it still actual ? 

### Describe the solution you'd like

We want to have Twitter channel creation but at this point we are blocked, please, support.

**Comment by sojan-official** [comment]
ref: https://github.com/orgs/chatwoot/discussions/6983#discussioncomment-6399943
