### ISSUE TITLE
Fetching Emails (imap via MS365) fails after some time

### ISSUE THREAD

**Issue by AndyHeinz** [chatwoot/chatwoot#9234]
### Describe the bug

After roughly a week, chatwoot stops fetching Emails from a ms365 Mailbox. 
The quickfix is going to Mailbox settings and saving the current imap settings. Then restarting the chatwoot stack. 
Problem is, that chatwoot only fetches the unread mails from the last 36 hours or so. 

1. How can I obtain the relevant logs for debugging the Bug
2. How can I import all unread Emails of that Mailbox 

### To Reproduce

Environment is dockerd with chatwoot 3.7.0.

### Expected behavior

Import every single Email.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 18.04

### Browser and version

Chrome / Firefox 

### Additional context

Thanks!

**Comment by vishnu-narayanan** [comment]
@AndyHeinz This is a known issue and should be fixed in the upcoming `v3.8` release. 

Ref: https://github.com/chatwoot/chatwoot/pull/9225

**Comment by vishnu-narayanan** [comment]
Please reopen if you are facing the same issue with v3.8. The `v3.8` release will be cut in a couple of hours.

**Comment by AndyHeinz** [comment]
Hi,
it now fails every ~24h:
`AdministratorNotifications::ChannelNotificationsMailer#email_disconnect
Net::ReadTimeout: Net::ReadTimeout with #<Socket:(closed)>
`
The cron fails, after restarting the cron, it fetches again. 
Is there a way to fetch that old emails?
Thanks!
