### ISSUE TITLE
Feature: Redis Sentinel support

### ISSUE THREAD

**Issue by kristiandrucker** [chatwoot/chatwoot#925]
**Is your feature request related to a problem? Please describe.**
I would like to ask if it would be possible to have Redis Sentinel support. I'm running a Sentinel cluster and Chatwoot doesn't want to connect to it.

**Describe the solution you'd like**
I would like to have Redis Sentinel support.

**Describe alternatives you've considered**
As an alternative I've set the sentinel master ip address directly in the configuration. I think this will cause issues in an event that a slave or other node than that master gets elected to be a master node.

**Additional context**
This is the error I got when I tried setting the Redis port to Sentinel:
```
Raven 3.0.0 configured not to capture errors: DSN not set
Creating scope :open. Overwriting existing method Conversation.open.
Started GET "/" for 127.0.0.1 at 2020-06-05 10:11:26 +0000
Processing by DashboardController#index as HTML
Completed 500 Internal Server Error in 22ms (Allocations: 314)
ERR unknown command `select`, with args beginning with: `1`, excluded from capture: DSN not set

Redis::CommandError (ERR unknown command `select`, with args beginning with: `1`,):

lib/global_config.rb:29:in `load_from_cache'
lib/global_config.rb:12:in `block in get'
lib/global_config.rb:11:in `each'
lib/global_config.rb:11:in `get'
app/controllers/dashboard_controller.rb:11:in `set_global_config'
```

**Comment by monarch0111** [comment]
@sojan-official The redis gem chatwoot is using supports SENTINEL [configuration by default](https://github.com/redis/redis-rb#sentinel-support). 

I guess this is pretty straight forward to add based on ENV variables and parsing sentinel config provided by user.

**Comment by sojan-official** [comment]
@monarch0111  if you would like to take this on, feel free to. 
We could introduce a new environment variable `REDIS_SENTINELS` and inject it to 
`app_redis_config` in  `/config/initializers/redis.rb` 

seems straight forward as you suggested.

**Comment by monarch0111** [comment]
> @monarch0111 if you would like to take this on, feel free to.
> We could introduce a new environment variable `REDIS_SENTINELS` and inject it to
> `app_redis_config` in `/config/initializers/redis.rb`
> 
> seems straight forward as you suggested.

Sure. Will take this up. Thanks!
