### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by shomid** [chatwoot/chatwoot#9250]
### Describe the bug

I updated Chatwood from version 3.2 to 3.7 and I get the following error when running::
![Screenshot from 2024-04-17 09-41-22](https://github.com/chatwoot/chatwoot/assets/8733354/9f39b720-724d-4399-9d2a-9e59cf7efa82)

### To Reproduce

1. development environment
2. docker-compose up

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

linux fedora

### Browser and version

chrome Version 123.0.6312.122 (Official Build) (64-bit)

### Docker (if applicable)

docker version
`Client: Docker Engine - Community
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:09:39 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:11 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
`

docker info
`Client: Docker Engine - Community
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 33
  Running: 1
  Paused: 0
  Stopped: 32
 Images: 57
 Server Version: 24.0.7
 Storage Driver: btrfs
  Btrfs: 
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.5-101.fc38.x86_64
 Operating System: Fedora Linux 38 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.01GiB
 Name: fedora
 ID: SAUS:ETN3:CAMH:JVAH:JNYE:AJMI:GLZG:2KSA:VHAT:CERF:6JVM:URLL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: shomid
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

docker-compose version
`docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.11.8
OpenSSL version: OpenSSL 3.0.9 30 May 2023`

**Comment by sanjayws** [comment]
I believe, CW team mentioned that it has to be an increment of 2 major versions, e.g. in your case, you need to go from 3.2 to  3.4 then 3.4 to 3.6 then 3.6 to 3.7 or 3.8 (released today)

**Comment by shomid** [comment]
solved by adding `import regeneratorRuntime from 'regenerator-runtime';` at the top of the app/javascript/packs/application.js file
