### ISSUE TITLE
Unable to add Contact Attributes from Conversation Panel - v3.8.0

### ISSUE THREAD

**Issue by irshad-k8** [chatwoot/chatwoot#9261]
### Describe the bug

In version 3.8.0 of the Chatwoot (Self Host Docker version) , when you click on "Contact Attribute" from the Conversation panel, the option to add a new attribute or view previously added attributes is not displayed as expected. 
The error I saw in the console is 
<img width="998" alt="image" src="https://github.com/chatwoot/chatwoot/assets/120436146/fa955af6-8a33-4c86-8a8a-7f3ea9074468">

### To Reproduce

To reproduce the issue , follow these steps:

1. Install and run version 3.8.0 using Docker in Ubuntu.
2. Open the conversation window.
3. Click on "More Details" within the conversation panel to access additional information.
4. Within the expanded details, locate and click on the "Contact Attributes" option.
<img width="443" alt="Screenshot 2024-04-19 at 4 40 46 PM" src="https://github.com/chatwoot/chatwoot/assets/120436146/693f7872-d81d-4e0e-9f2c-bbf701cf2861">

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu

### Browser and version

Google Chrome Version 124.0.6367.61

**Comment by iamsivin** [comment]
@irshad-cody, Could you please share a screen recording? We couldn't able to reproduce it. We have made some UX improvements to the custom attributes in the sidebar in our latest release. Previously, we had to open the custom attributes dropdown from the sidebar, select the attribute, click edit, and save the values to view all the available attributes in the account. Now, we are showing all the attributes from the account in the sidebar (both contact and conversation). If you don't have any attributes in your account, then we won't show them.
