### ISSUE TITLE
Text Typo in Inbox Settings under "Sender name" description

### ISSUE THREAD

**Issue by Seanytype** [chatwoot/chatwoot#9273]
### Describe the bug

In the settings section of an inbox, the description under "Sender name" says: 

"Select the name shown to **the your** customer when they receive emails from your agents." 
<img width="979" alt="Screenshot 2024-04-22 at 14 16 29" src="https://github.com/chatwoot/chatwoot/assets/108362899/adb00b96-ec3c-4ce6-be12-9da70dcc57bd">

### To Reproduce

In Chatwoot Navigate to:

1. Settings Gear
2. Inboxes
3. Settings of Inbox
4. Scroll to page bottom
5. Observe description of "Sender Name"  in business name configuration section.

### Expected behavior

To see correct phrasing

### Additional context

It's not really a bug, I just wanted to report this simple fix.

Thanks!

### Environment

app.chatwoot.com

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
@Seanytype Thank you for reporting this. This(and more 😅 ) will be fixed by https://github.com/chatwoot/chatwoot/pull/9326
