### ISSUE TITLE
Authorization failed. (Can't use EvolutionAPI nor N8N with Chatwoot. [SELF HOSTED] 

### ISSUE THREAD

**Issue by SMolizini** [chatwoot/chatwoot#9282]
### Describe the bug

![1](https://github.com/chatwoot/chatwoot/assets/167435967/7e8dd6af-c3c7-4767-8fd0-ea0db6e42e8e)
![2](https://github.com/chatwoot/chatwoot/assets/167435967/57f47078-9583-41e1-95f4-69d1a9367900)
What am I doing wrong? 

Chatwoot version 3.7.0 (also tried 3.8.0)

### To Reproduce

I just installed Chatwoot in a new VM and still not working using n8n and evoapi with it. Authorization Failed...

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Firefox

**Comment by pranavrajs** [comment]
@SMolizini We don't officially support N8n or Evolution API, please raise the request at respective forums. If you see that you are getting error from Chatwoot, please raise another ticket with logs and more information for us to debug it further.
