### ISSUE TITLE
Message reply marks the incorrect message

### ISSUE THREAD

**Issue by elizeufranca** [chatwoot/chatwoot#9283]
### Describe the bug

When the attendant marks a message to comment on it, ChatWoot marks the incorrect message for the user/customer, sometimes it is not even a message from that conversation

### To Reproduce

Customer sends a message or operator sends a message, then right-clicks on the message you want to comment on, writes the new message and sends.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Linux Ubuntu

### Browser and version

Google Chrome

**Comment by sojan-official** [comment]
@elizeufranca, could you share the version of Chatwoot you are using?  is there any customisations made in code? can you share a screencast of the behaviour?

**Comment by elizeufranca** [comment]
I use the latest version of Chatwoot available for Swarm, v3.8.0.
I also use an unofficial API to connect to WhatsApp, the Evolution API. Maybe it could be her bug.

**Comment by elizeufranca** [comment]
Below are screenshots of the problem mentioned.

![image](https://github.com/chatwoot/chatwoot/assets/139554820/e39f4fef-0a5e-4681-bdca-55b2bb96103d)
![image](https://github.com/chatwoot/chatwoot/assets/139554820/e81ce6e7-b4a8-4627-a015-2bc4473c807b)

![image](https://github.com/chatwoot/chatwoot/assets/139554820/b8d6e6f6-6f77-4f04-b2e1-17e34d023c61)

**Comment by elizeufranca** [comment]
The ChatWoot operator marks a message, comments on it, but the user/client is marked with another random message, sometimes marking a message that is not even from that conversation

**Comment by renealcantara** [comment]
I've same problem.

**Comment by sojan-official** [comment]
@elizeufranca We haven't received any reports of such behaviour on official providers for WhatsApp in Chatwoot.  Evolution API is outside of an official integration by the the Chatwoot team. Please reach out to their support for this case. 

@renealcantara, please  let us know if you aren't using Evolution API
