### ISSUE TITLE
Recebe mas não envia o email

### ISSUE THREAD

**Issue by suporteprevermed** [chatwoot/chatwoot#9294]
### Describe the bug

Tenho 2 caixas de entrada de email.
Estou recebendo os e-mails normalmente.
Mas ao responder, o destinatario não recebe a msg.
Gostaria de ajuda para para saber como resolver.

### To Reproduce

Caixa de entrada
e-mail
resposta
não chega ao destino

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Additional context

VPS - Hetzner

**Comment by vishnu-narayanan** [comment]
@suporteprevermed  Please add the following information

-  Chatwoot version
-  Installation environment
-  Spec of the machine
-  are there any customization to the code

- Share more details about your email channel and how you set it up. Which email provider are you using?

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still having issues.
