### ISSUE TITLE
Cannot Load Any Conversations

### ISSUE THREAD

**Issue by Wamy-Dev** [chatwoot/chatwoot#9300]
### Describe the bug

Whenever I try and load any conversations from the browser, it fails with a 500 Internal Server Error, which this as the error in the logs.

```
I, [2024-04-25T17:26:43.755035 #1]  INFO -- : [a8d7a57f-ceba-4992-b866-5cb322ab1211] Completed 500 Internal Server Error in 14999ms (ActiveRecord: 14599.1ms | Allocations: 492135)

F, [2024-04-25T17:26:43.756043 #1] FATAL -- : [a8d7a57f-ceba-4992-b866-5cb322ab1211]   

[a8d7a57f-ceba-4992-b866-5cb322ab1211] Rack::Timeout::RequestTimeoutException (Request ran for longer than 15000ms ):

[a8d7a57f-ceba-4992-b866-5cb322ab1211]   

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/views/api/v1/conversations/partials/_conversation.json.jbuilder:29

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/views/api/v1/accounts/conversations/index.json.jbuilder:10

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/views/api/v1/accounts/conversations/index.json.jbuilder:9

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/views/api/v1/accounts/conversations/index.json.jbuilder:8

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/views/api/v1/accounts/conversations/index.json.jbuilder:1

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/controllers/concerns/switch_locale.rb:39:in `set_locale'

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/controllers/concerns/switch_locale.rb:17:in `switch_locale_using_account_locale'

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/controllers/concerns/request_exception_handler.rb:11:in `handle_with_exception'

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/controllers/concerns/switch_locale.rb:39:in `set_locale'

[a8d7a57f-ceba-4992-b866-5cb322ab1211] app/controllers/concerns/switch_locale.rb:12:in `switch_locale'

I, [2024-04-25T17:26:43.756240 #1]  INFO -- : source=rack-timeout id=a8d7a57f-ceba-4992-b866-5cb322ab1211 timeout=15000ms service=15002ms state=completed

I, [2024-04-25T17:26:43.799964 #1]  INFO -- : source=rack-timeout id=f6969797-1080-4480-9dd4-fd5f41418626 timeout=15000ms state=ready
```

### To Reproduce

1. Open up chatwoot dashboard.

### Expected behavior

For all conversations to load.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

**Comment by Wamy-Dev** [comment]
- Chatwoot 3.8.0 (85aeaf2aee0a3d3acf7c806f12c2db81d6b5110f)
- Docker Self Hosted
- 4 CPU, 32GB ram, nvme disk
- No customization

**Comment by sojan-official** [comment]
@Wamy-Dev  Could you also give the following details 

- Estimated number of conversations in the system
- types of channels that you are using 
- Any other errors that you see in logs 
- also the spec of your database instance ?

It seems like the request is timing out. This usually happens when the Postgres query times out

**Comment by vishnu-narayanan** [comment]
@Wamy-Dev Could you check the supabase db logs and see if there are timeouts?

**Comment by vishnu-narayanan** [comment]
Please reopen if you are still having issues.

**Comment by jxs714** [comment]
This is the same issue I mentioned in the discord chat. It seems to be happening since the update after 3.7.0. I have not heard back

**Comment by jxs714** [comment]
Ok, so found out the issue for me. I had an email inbox that may have not been configured properly or was locked in the system with no error. Once I removed the inboxes that showed the same circle, it gave me an indication that it was the issue. Check for each inbox separately then remove and reconfigure each one. This fixed the issue for me
