### ISSUE TITLE
Problem with no account status (online, busy and disconnected)

### ISSUE THREAD

**Issue by Cup-Grape** [chatwoot/chatwoot#9313]
### Describe the bug

Hello everyone, we have identified a problem that is occurring in the most current versions, for example, "3.8.0" where you change the status to "Disconnected" for example and when you update the page the status is changed back to "Online" like this like "Busy", in previous versions this problem did not occur.

### To Reproduce

As shown in the video below, this problem fluctuates a lot and occurs when you change the status and update the page, so far the status always returns to "Online", even changing to "Disconnected" or "Busy" just update the page that will return to "Online".

https://github.com/chatwoot/chatwoot/assets/78883197/fc9d3be0-0e9f-4c21-918c-e7383978ac0b

### Expected behavior

It is expected that, as in previous versions, the platform will maintain the status we configured, even when updating the page, the platform needs to maintain the status.

In previous versions, if we changed the status to “disconnected”, for example, and refreshed the page, the platform would maintain the “disconnected” status until the user manually changed their status to “online”

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by vishnu-narayanan** [comment]
Did this start with  version`3.8` for you?

**Comment by Cup-Grape** [comment]
Hello everything is fine?

From what we verified, it is also occurring in other older versions, when we added it to Docker Swarm and separated the Sidekiq Frontend containers/stacks, if you could check, please

**Comment by pranavrajs** [comment]
Closed via https://github.com/chatwoot/chatwoot/pull/9477
