### ISSUE TITLE
Intermittently duplicating message in Whatsapp Channel (Weak connection)

### ISSUE THREAD

**Issue by Cauen** [chatwoot/chatwoot#9314]
### Describe the bug

The agent reported that she had a weak connection, she only sent the message once and it showed twice in the chat

Consulting the logs, the system records 2 calls to Api::V1::Accounts::Conversations::MessagesController#create. Which means it's something in the frontend.

A few messages were duplicated. They were very personalized, which rules out the option of the agent sending them again unintentionally, but that had never happened since January, so it's a very rare case.

Would there be any retry logic that perhaps in some scenarios could make the message be sent twice?

I tried reproducing locally by activating a network throttle. But I could not.

Details: The difference between the messages was 12 seconds. It wasn't a private message. It was from Whatsapp Cloud. Both were sent to the customer because the database records 2 different "source_ids".

Chatwoot version: 3.4.0
Cloud: Hetzner (Not relevant i think)

### To Reproduce

Wasnt able to reproduce D:

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows

### Browser and version

Chrome

**Comment by vitusan** [comment]
Good evening, gentlemen! I was facing the same issue with an API integration—I was receiving the same message_created payload twice. However, I remembered that I had configured a webhook trigger for the inbox and another webhook trigger in the integrations menu, under the webhook item. For me, it was enough to disable the 'extra' webhook event, which in my case was the integration webhook, and the duplicate messages stopped arriving. Hope it helps any poor souls stuck on this, and please don't reinstall your chatwoot instance before reading this, like some other comments pointed out in other issues related to this one.

**Comment by sojan-official** [comment]
There haven’t been further reports of this issue. Let’s reopen it if any new reports arise.
