### ISSUE TITLE
'Invalid access_token' Error with Chatwoot API Integration

### ISSUE THREAD

**Issue by hermesalvesbr** [chatwoot/chatwoot#9331]
### Describe the bug

I'm struggling to integrate with the Chatwoot API and keep encountering this error:

```json
{
  "error": "Invalid access_token"
}
```

I've set up the platformApp and obtained the necessary token for connection. The endpoint I'm attempting to access is:

```bash
curl --location 'https://help.website.com.br/platform/api/v1/accounts/2' \
--header 'api_access_token: tsgqcGchgoz3737LUb2dbA' \
--header 'Content-Type: application/json'
```

Unfortunately, I'm only getting a 401 error, as seen in the log below:

```
2024-04-30T13:44:37.065484268Z I, [2024-04-30T13:44:37.062131 #1] INFO -- : [22331f52-df8a-4ed8-80e9-7c6a98a0b2ed] Processing by Platform::Api::V1::AccountsController#show as JSON
2024-04-30T13:44:37.065528523Z I, [2024-04-30T13:44:37.062223 #1] INFO -- : [22331f52-df8a-4ed8-80e9-7c6a98a0b2ed] Parameters: {"id"=>"2", "account"=>{}}
2024-04-30T13:44:37.065535832Z I, [2024-04-30T13:44:37.063153 #1] INFO -- : [22331f52-df8a-4ed8-80e9-7c6a98a0b2ed] Filter chain halted as :set_platform_app rendered or redirected
2024-04-30T13:44:37.065540600Z I, [2024-04-30T13:44:37.063319 #1] INFO -- : [22331f52-df8a-4ed8-80e9-7c6a98a0b2ed] Completed 401 Unauthorized in 1ms (Views: 0.3ms | ActiveRecord: 0.0ms | Allocations: 193)
2024-04-30T13:44:37.065545599Z I, [2024-04-30T13:44:37.063646 #1] INFO -- : source=rack-timeout id=22331f52-df8a-4ed8-80e9-7c6a98a0b2ed timeout=15000ms service=7ms state=completed
```

I have restarted the server and cleared the Redis cache, yet the error persists. What am I doing wrong?

### Is This Bug Related to CapRover? Connection api Issues After One-Click Chatwoot Installation

I installed Chatwoot using the CapRover one-click app, which includes Nginx configurations. Could these settings be causing my API connection issues? I'm wondering if there might be an Nginx rule affecting cookies or tokens. Any guidance towards resolving this would be greatly appreciated. Please guide me to a solution.

```
RAILS_ENV=production
RAILS_LOG_TO_STDOUT=true
SECRET_KEY_BASE=********************
POSTGRES_HOST=srv-captain--chatwoot-postgres
POSTGRES_DATABASE=chatwoot
POSTGRES_USERNAME=chatwoot
POSTGRES_PASSWORD=************
REDIS_URL=redis://srv-captain--chatwoot-redis:6379
INSTALLATION_ENV=caprover
REDIS_PASSWORD=************
FRONTEND_URL=https://help.example.com
SMTP_ADDRESS=smtp.mailgun.org
MAILER_SENDER_EMAIL=support@example.com
SMTP_PORT=587
SMTP_ENABLE_STARTTLS_AUTO=false
SMTP_USERNAME=support@mg.example.com
SMTP_PASSWORD=**************************
SMTP_AUTHENTICATION=plain
SMTP_DOMAIN=mg.example.com
DEFAULT_LOCALE=pt-BR
FORCE_SSL=true
ENABLE_ACCOUNT_SIGNUP=api_only

```

### Expected behavior

A 200 response for the api:

```
{
  "account_id": 0,
  "user_id": 0,
  "role": "string"
}
```

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 23.10

### Browser and version

Chrome 124.0.6367.92 

### Docker (if applicable)

 **docker version**
Client: Docker Engine - Community
 Version:           26.1.0
 API version:       1.45
 Go version:        go1.21.9
 Git commit:        9714adc
 Built:             Mon Apr 22 17:07:06 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:07:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
**docker info**
Client: Docker Engine - Community
 Version:    26.1.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.26.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 9
  Paused: 0
  Stopped: 0
 Images: 29
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: active
  NodeID: wowant5656561j4e
  Is Manager: true
  ClusterID: ivspb8jp565656l6hww7
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
 Kernel Version: 6.5.0-28-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 47.04GiB
 Name: tytyty
 ID: cb3709dd5656566a3a63292bcb0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by pranavrajs** [comment]
@hermesalvesbr I don't think this is a bug. Please refer to this comment. https://github.com/chatwoot/chatwoot/issues/9203#issuecomment-2064531026
