### ISSUE TITLE
Your email inbox has been disconnected. Please update the credentials for SMTP/IMAP

### ISSUE THREAD

**Issue by jonaski** [chatwoot/chatwoot#9338]
### Describe the bug

When using a Microsoft account, e-mails are no longer received in chatwoot. An e-mail that chatwoot has been disconnected is received on the account.

According to the instructions on https://www.chatwoot.com/hc/user-guide/articles/1677843043-how-to-setup-an-email-channel, there should be button "Sign in with Microsoft", this button is missing under configuration.

### To Reproduce

Go to Inboxes / Settings / Configuration. "Sign in with Microsoft" button is missing.

### Expected behavior

Shows "Sign in with Microsoft" button.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@jonaski, thank you for reporting this. We're aware of the issue and are actively working on a fix. You can find more details [here](https://www.notion.so/Re-authorization-Flow-f1926a8e8ac54852b6a0f1340b717a83?pvs=21). 


Meanwhile, you can execute the following commands to enable the reauthorization button.
```ruby
inbox_id = xxx
inbox = Inbox.find(inbox_id)
channel = inbox.channel
channel.provider_config = {}
channel.save!
```

We will track the progress of this issue over https://github.com/chatwoot/chatwoot/issues/9207 as this is a duplicate.
