### ISSUE TITLE
Webhook security?

### ISSUE THREAD

**Issue by jsyang** [chatwoot/chatwoot#9354]
### Describe the bug

Hi, thanks for creating this great project. I'm setting up webhooks for ChatWoot and I'm hitting a wall on best practices for securing the Inbox webhook endpoint. I have a VPS set up to listen at the webhook URL but I want to secure it. Is there a way to lock this down so I can tell which requests to the webhook are genuine?

Have searched the documentation and codebase but only finding mentions of `api_access_token` nothing about securing the webhook. Am I missing something obvious here?[](url)

### To Reproduce

1. Create Inbox with channel = API
2. Set webhook endpoint to URL pointing to a VPS
3. Log all incoming HTTP traffic with the VPS
4. See that none of the headers contain anything that pin the requests back to ChatWoot (verify as genuine webhook calls)

### Expected behavior

For other platforms that offer webhook functionality there's usually something like a header which is sent with a predefined key. Or a header with a hash of the payload using a signing key.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by jsyang** [comment]
For additional reference, GitHub themselves have HMAC-digest-based webhook payload verification: https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries

I believe [Meta Webhooks](https://developers.facebook.com/docs/graph-api/webhooks/getting-started/#validate-payloads) are the same mechanism, as are countless other platforms that offer Webhook functionality.

Perhaps good to align with this practice unless I'm blind and have overlooked something?

**Comment by micheh** [comment]
This is a known missing feature, see https://github.com/chatwoot/chatwoot/issues/4732

Currently the only option is to use a webhook url that is not guessable, e.g. by using a random string in the url or as a query parameter. Not ideal, but slightly bit better than just using a url like /webhook/chatwoot

**Comment by jsyang** [comment]
Querystring key passing: I've used exactly that in my project. Thanks for mentioning that as an expected mitigation!

**Comment by sojan-official** [comment]
closing this in favour of https://github.com/chatwoot/chatwoot/issues/9354
