### ISSUE TITLE
whatsapp bot configuration tab is not showing up in chatwoot 3.8

### ISSUE THREAD

**Issue by hectorvent** [chatwoot/chatwoot#9359]
### Describe the bug

WhatsApp bot configuration tab is not showing up in Chatwoot 3.8.0. Build chatwoot locally using docker and running in it as well. 

### To Reproduce

Build chatwoot from v3.8.0 tag

### Expected behavior

Be able to see WhatsApp bot configuration tab

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

MacOS

**Comment by h4t0n** [comment]
I think that this affects also the other channels. I tried with Telegram and Web.

**Comment by hectorvent** [comment]
I found the issue... well, it's not an issue at all. Now we need to enable `agent_bots` in the account all features section in the admin console.

**Comment by hectorvent** [comment]
> I think that this affects also the other channels. I tried with Telegram and Web.

Thanks

**Comment by rudcode** [comment]
Sorry for bumping this closed issue, but is there any way to enable this on chatwoot community edition? because the "all features" section doesn't show up on chatwoot community edition.

**Comment by hectorvent** [comment]
I am using the community version. You should go into the administrative console and account section. I can share a screenshot later if you still don't find it.

**Comment by rudcode** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/7247249/4855266a-4efa-4a45-91af-4a5539f29092)

with community version the options is not there, but if I change the docker version with non community version the options show up
