### ISSUE TITLE
Ability required to unmute muted contacts.

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#937]
**Is your enhancement request related to a problem? Please describe.**
Yes, when you mute a contact, there is no way to undo this action.

**Describe the solution you'd like**
Once the mute has been clicked, link should change to unmute to undo. 

**Describe alternatives you've considered**
There are no alternatives.

**Comment by pranavrajs** [comment]
We have considered this option, will be adding it as an enhancement. At the moment, the muted contact can send a message after 6 hours.

**Comment by iammattmartin** [comment]
Thanks for confirming.

This looks like it it may have been a browser issue as tried another machine and it was not happening. Cleared out the cookies on the first and now this seems OK.

**Comment by JazabC** [comment]
Can I work on this?

**Comment by sojan-official** [comment]
@JazabC  please go ahead. I have added you as the assignee. let us know if you have any questions

**Comment by somenugget** [comment]
Can I take this issue?

**Comment by sojan-official** [comment]
@somenugget  feel free to take this if you have the bandwidth :)

**Comment by somenugget** [comment]
I need some help with this issue from the product perspective.

At this moment `Conversation#mute!` not only mutes conversation but also sets it's status to `resolved`(what was a bit confusing for me 🤔).
And it's not totally clear what should be done with `unmute`?:
* only unmute 

or 

* onmute
* change status back to `open`

**Comment by sojan-official** [comment]
@somenugget  sorry for the lack of clarity there.
- At the moment, when a new customer message arrives in a resolved conversation, it will get reopened unless its muted.

With this change, lets only focus on `unmute` -> ie `remove the conversation mute key from Redis`

For the moment.  let the agent manually toggle the conversation back to open if required or the system will automatically change it to open if a new message comes in.  We can further optimize this interaction in future, as we get more feedback.

**Comment by somenugget** [comment]
Thank you for clarification. I'll prepare PR later today
