### ISSUE TITLE
Re-open "resolved" conversations

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#938]
**Is your enhancement request related to a problem? Please describe.**
Yes, when you resolve a conversation, if someone then adds an update. It remains resolved. 

**Describe the solution you'd like**
The conversation should re-open again if opened. An ideal situation would be that once resolved, they can either update it within a specific time period, or a new conversation is forced. (admin selectable).

**Describe alternatives you've considered**
Leaving all conversations open would be the only current option but that makes resolving them a feature that would never be used.

**Comment by pranavrajs** [comment]
@iammattmartin The conversations should reopen if the user messages from the widget/any channel, but if the agent replies after a conversation is resolved, the status would not be updated. Are you suggesting to reopen the conversation whenever any party sends a message?

**Comment by iammattmartin** [comment]
Thanks for confirming.

This looks like it it may have been a browser issue as tried another machine and it was not happening. Cleared out the cookies on the first and now this seems OK.
