### ISSUE TITLE
Twitter public tweets and DM improvements

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#939]
**Is your enhancement request related to a problem? Please describe.**
Yes, at the moment if you are having a conversation with someone from a tweet, and they then DM you, this appears in the same conversation but when you reply, it is public tweet.

This is bad as you could be replying assuming it would go via DM.

**Describe the solution you'd like**
Each tweet should be related to the same root tweet (i.e threading). If that person replies to a different tweet days or weeks later, that should be a new conversation. Likewise, if a DM, that should be separate too, possibly we clear indication that one is a DM and one is public.

**Describe alternatives you've considered**
There are none at this time as far as I can see.

**Comment by pranavrajs** [comment]
@iammattmartin Can you please share a screencast of the behaviour, we have considering DMs and tweets as separate it will not be merged in a single conversation.

**Comment by iammattmartin** [comment]
As requested.

I tweeted one of our brands. It appeared.
I replied from the brand, this was sent to the user publicly.
The user then DM'd the brand, this was received in the existing conversation (with nothing visual to know it was a DM).
I replied from the brand, this was then done as a public tweet, not linked to any other.

https://www.dropbox.com/s/jdvcfaxvp3ni1jw/Screen%20Recording%202020-06-09%20at%205.10.48%20AM.mov?dl=0

Please confirm once viewed so I can remove this.

(I had to login to Twitter in the middle to change the DM settings)

**Comment by pranavrajs** [comment]
@iammattmartin You can remove the recording. I have understood the flow. Let me test it out.
