### ISSUE TITLE
Typing indicator shows activity on mouse action

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#940]
**Describe the bug**
In the customer widget, a simple mouse over/click on the staff side will generate the typing indicator. This should not happen.

**To Reproduce**
Go to the conversation
Click mouse in to text box
View widget to see typing indicator

**Expected behavior**
I would say that the typing indicator should only show when there is actual typing instead of just focus on the text area with mouse.

**Desktop:**
 - OS: macOS
 - Browser Firefox
 - Version 77.0.1

**Comment by richardonrails** [comment]
+1 -- having your cursor focused in the textbox should not leave a perpetual typing indicator. It makes the end user feel like more is coming when the agent might just be waiting.

**Comment by iammattmartin** [comment]
This also occurs when the reply option changes from "private note" back to "reply" even if the mouse does not have focus.
