### ISSUE TITLE
Enable Electron as a supported browser (for notifications)

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#945]
**Is your enhancement request related to a problem? Please describe.**
Not related to a problem as such. Using Electron (prior to any official app) via WebCatalog (Mac) to create an app. Notifications can't be enabled as CW believes it is a non-supported browser.

**Describe the solution you'd like**
Allow CW to consider Electron as a supported browser to enable notifications.

**Additional context**
I have tested this with a different browser string matching Firefox but this did not trick CW in to issuing the notifications.

**Comment by pranavrajs** [comment]
@iammattmartin I'm not sure whether this is possible without adding code on electron, we are following WebPush protocol right now. Let us investigate this.

**Comment by pranavrajs** [comment]
@iammattmartin I did a couple of research on this, we couldn't a good method to support push on electron shell which built outside of Chatwoot. I'm closing this and we would find a solution for https://github.com/chatwoot/chatwoot/issues/1345 in this sprint.
