### ISSUE TITLE
Duplicate messages if I repeatedly press enter button

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#946]
- Duplicate messages are sent if the network is slow and I repeatedly press enter on the reply box

**Comment by neymarsabin** [comment]
@pranavrajs Can I take this one?

**Comment by pranavrajs** [comment]
@neymarsabin Please feel free to do it, assigning this to you.

**Comment by neymarsabin** [comment]
@pranavrajs I think we need to have a loader/indicator whether the messages are being sent or not. That would be a good enhancement. For this issue, I just cleared the state of the message and it worked.

**Comment by pranavrajs** [comment]
@neymarsabin I think that should be enough, you don't need to wait for a message to be sent to send another one. A pending message in UI would fix that UX, this is handled in https://github.com/chatwoot/chatwoot/pull/852

**Comment by neymarsabin** [comment]
@pranavrajs opened a [PR - 987](https://github.com/chatwoot/chatwoot/pull/987)
