### ISSUE TITLE
Duplicity of messages sent to users on WhatsApp | Duplicidade de mensagens enviadas para usuário no WhatsApp

### ISSUE THREAD

**Issue by meumouse** [chatwoot/chatwoot#9465]
### Describe the bug

Percebemos um problema na versão 3.8.0 do Chatwoot que ao enviar uma mensagem para o usuário no WhatsApp, chega duplicada para ele, ou seja, na visão do atendente está sendo enviado uma única vez, mas se verificar pelo aparelho conectado via Evolution API aparece a mensagem duas vezes

English version:
We noticed a problem in version 3.8.0 of Chatwoot that when sending a message to the user on WhatsApp, it arrives in duplicate, that is, in the attendant's view it is being sent once, but if checked on the device connected via Evolution API it appears the message twice

### To Reproduce

Conexão via API com Evolution API

Configurações usadas:
- Assinar mensagens: Ativo
- Iniciar conversa como pendente: Ativo
- Importar contatos: Ativo
- Importar mensagens: Ativo
- Limite de dias para importar mensagens: 365

English version:
Connection via API with Evolution API

Settings used:
- Subscribe to messages: Active
- Start conversation as pending: Active
- Import contacts: Active
- Import messages: Active
- Day limit for importing messages: 365

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Docker (if applicable)

docker version 2.19.5
Swarm 26.1.2

**Comment by sojan-official** [comment]
@meumouse Thank you for reporting this issue. The Evolution API isn’t an official integration within Chatwoot, and currently, there are no reports regarding this on our official channels. For further assistance, please contact the original developers of the Evolution API integration.
