### ISSUE TITLE
I can't see anything after installation

### ISSUE THREAD

**Issue by Aserrano23** [chatwoot/chatwoot#9469]
### Describe the bug

I installed chatwoot in a Ubuntu 22.04 VM with docker, the installation gone fine but when i try to access localhost:3000 it says me "Unable to connect"

![Captura de pantalla 2024-05-15 a las 12 34 18](https://github.com/chatwoot/chatwoot/assets/51117311/85bb6f09-ff13-4164-9ea6-f81cdc735d08)

### To Reproduce

N/A

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Docker (if applicable)

DOCKER VERSION
![Captura de pantalla 2024-05-15 a las 12 31 45](https://github.com/chatwoot/chatwoot/assets/51117311/9ba8c860-5adb-481c-8615-35babea07363)

DOCKER INFO
![Captura de pantalla 2024-05-15 a las 12 32 07](https://github.com/chatwoot/chatwoot/assets/51117311/4f1b9f78-c281-4ef7-8331-b7dfff5fe063)

DOCKER COMPOSE VERSION
![Captura de pantalla 2024-05-15 a las 12 32 25](https://github.com/chatwoot/chatwoot/assets/51117311/b6510608-1e8e-4150-b78e-e20322ccb7c9)

**Comment by vishnu-narayanan** [comment]
@Aserrano23 Could you share the output of `docker ps`?

**Comment by fabr2004** [comment]
@Aserrano23 
If you applied default `docker-compose.yaml` then after you setup Docker you must install and configure `nginx`.
By its default, Chatwoot Docker itself doesn't communicate with exterior environment, it needs this proxy.

**Comment by vishnu-narayanan** [comment]
@Aserrano23 Please reopen if you are still facing issues.
