### ISSUE TITLE
"delete message" should delete on website inboxes

### ISSUE THREAD

**Issue by psifertex** [chatwoot/chatwoot#9472]
### Is your feature or enhancement related to a problem? Please describe.

Previously (https://github.com/chatwoot/chatwoot/issues/8560) a similar feature was closed because it's impossible to delete messages for some remote APIs. However, it should absolutely be possible still for the integrated javascript chatbox.

### Describe the solution you'd like

I'd like it when I delete a message in the chatwoot UI that it would be removed from the website. It is currently not. Note that not only does it not delete it in the live instance but even if I reload the webpage the message is not deleted. 

### Describe alternatives you've considered

There isn't an alternative as far as I know.

**Comment by pranavrajs** [comment]
@psifertex Can you please share a screencast of the behavior?

**Comment by pranavrajs** [comment]
Closing this here for now due to inactivity.
