### ISSUE TITLE
text/plain only emails are not rendered properly

### ISSUE THREAD

**Issue by jetliew** [chatwoot/chatwoot#9480]
### Describe the bug

Hi some of our messages in Chatwoot don't have paragraph spacing when received.

I've replicated the scenario, it's because when the email format is "Plain Text", there will no spacing when message received in Chatwoot. We have another platform but the arrived message has no issue.

Not sure it's a bug or it's intentional for that.
If it's the bug, is that possible to fix that?

### To Reproduce

Since I'm using Microsoft email, here's the steps:
1. On browser, New Mail > Message menu > Switch to Plain Text.
![image2](https://github.com/chatwoot/chatwoot/assets/91707784/5c5aedd8-dbf6-4fec-b24d-3f1f88aa0b0b)

2. Key in the text and put paragraph spacing, after that send the email.
3. When received the email in Chatwoot, the message will not have spacing.
![image1](https://github.com/chatwoot/chatwoot/assets/91707784/2b27bd75-48c6-4ed3-9aee-5c2c9056961e)

### Expected behavior

The messages should have paragraph spacing instead of no spacing between paragraph.

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows 10 Home

### Browser and version

v3.8.0

### Additional context

Platform: Self-Hosted
EML file as requested:
[email message EML.zip](https://github.com/chatwoot/chatwoot/files/15331316/email.message.EML.zip)

**Comment by pranavrajs** [comment]
<img width="596" alt="Screenshot 2024-05-21 at 4 36 23 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/59a14155-e873-48bf-a305-ea6530d6cd20">

A quick fix here is to replace the content with relevant HTML tags as shown in the code change above. We need to investigate whether there is a best practice to render text/plain content properly.
