### ISSUE TITLE
Problem with knowledge base function in Chatwoot self-deployed using Docker Compose

### ISSUE THREAD

**Issue by hei2077** [chatwoot/chatwoot#9485]
### Describe the bug

I am encountering some issues with the knowledge base functionality on my self-hosted Chatwoot instance. Firstly, despite following the documentation to set up and create a knowledge base, when attempting to access the knowledge base page, I receive the following error:

```json
{
  "error": "Domain: 127.0.0.1 is not registered with us. Please send us an email at support@chatwoot.com with the custom domain name and account API key"
}
```

I have already set the `FRONTEND_URL=https://my-chatwoot-domain.com` in the environment variables. Moreover, when adding new knowledge base articles, although the system prompts "Article published successfully" after editing, the articles do not appear in the console upon refreshing the page.

### To Reproduce

1. Deploy Chatwoot using Docker Compose according to the official documentation.
2. Set the `FRONTEND_URL` environment variable to `https://my-chatwoot-domain.com` in the Docker `.env` file.
3. Start the Chatwoot instance using Docker Compose.
4. Navigate to the knowledge base section via the admin dashboard.
5. Follow the prompts on the admin dashboard to create a portal (`Create Portal`).
6. Access the provided knowledge base link (`https://my-chatwoot-domain.com/hc/mySlug`) as indicated on the admin dashboard.
7. Observe that the page does not display any content, instead showing a JSON error message.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windous11

### Browser and version

Chrome 124.0.6367.201

## docker version
```
Client: Docker Engine - Community
 Version:           26.1.2
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        211e74b
 Built:             Wed May  8 13:59:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.2
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       ef1912d
  Built:            Wed May  8 13:59:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
## docker-compose version
`Docker Compose version v2.27.0`

**Comment by pranavrajs** [comment]
@hei2077 The error shows that 127.0.0.1 is not a valid domain registered in the installation. Are you using a reverse proxy with the docker-compose setup? It seems that some of the headers are not forwarded to the Chatwoot server.

**Comment by hei2077** [comment]
> @hei2077 The error shows that 127.0.0.1 is not a valid domain registered in the installation. Are you using a reverse proxy with the docker-compose setup? It seems that some of the headers are not forwarded to the Chatwoot server.

Thank you for your guidance on the reverse proxy settings. Following your advice, I update the configuration and it successfully resolved the issue.
