### ISSUE TITLE
Incomplete API response

### ISSUE THREAD

**Issue by TheProcedural** [chatwoot/chatwoot#9488]
### Describe the bug

Conversation details' response only contains the last message of the conversation and get conversation messages is also incomplete, only has a few more messages. Pagination doesn't seem to be a thing, I also tried that.

## Update:

![image](https://github.com/chatwoot/chatwoot/assets/54407345/75fbaf53-c9d1-4b8f-8772-6f6dae8ad042)
Anlysing your web app I noted that this actually looks like a lack of documentation. I realised that pagination is just a query param with the the id of the payload. So I suppose you just need to add this to the docs.

### To Reproduce

Fetch one conversation as described  in the link below

[https://www.chatwoot.com/developers/api/#tag/Conversations/operation/get-details-of-a-conversation](https://www.chatwoot.com/developers/api/#tag/Conversations/operation/get-details-of-a-conversation)

or

[https://www.chatwoot.com/developers/api/#tag/Messages/operation/list-all-messages](https://www.chatwoot.com/developers/api/#tag/Messages/operation/list-all-messages)

this second options will respond with more messages but still not all of them and pagination doesn't seem to exist in neither

### Expected behavior

To have all the messages in the conversation as the docs say the response should.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@TheProcedural The API is using a cursor based pagination. You can't query all the message in a given conversation. You could pass a before params which would return 20 messages before the cursor. We will update the documentation.

**Comment by TheProcedural** [comment]
> @TheProcedural The API is using a cursor based pagination. You can't query all the message in a given conversation. You could pass a before params which would return 20 messages before the cursor. We will update the documentation.

I realised that after posting the issue and I forgot to update it, sorry about that. But thank you for updating the docs!
