### ISSUE TITLE
Missing CSS for woot--notification div

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#9500]
### Describe the bug

For the inline code generated we see:

```
<span class="woot--notification"></span>
```

But this causes issues with page layout. 

On checking the class along with other classes that Chatwoot generates, it does not exist.

It looks like `woot--notification` may be an oversight and not actually generating.

### To Reproduce

Linux VM 3.9.0

Simply load current widget code on site. Beheaviour seen on your own site too with missing CSS for the class.

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Browser and version

Firefox

**Comment by pranavrajs** [comment]
@iamsivin Please take a look at the issue.
