### ISSUE TITLE
Missing "restart: always" at docker compose file

### ISSUE THREAD

**Issue by fabr2004** [chatwoot/chatwoot#9501]
### Describe the bug

When you download Docker compose template, it doesn't have "restart" directive for all services.
Therefore, when you restart your server Chatwood won't go online.

### To Reproduce

1. Follow the official guide here: https://www.chatwoot.com/docs/self-hosted/deployment/docker
2. Install Chatwood with Docker, it should work correctly.
3. Reboot your Server/VM/Container: Chatwood will not start again since it's missing `restart: always` at `rails` and `sidekiq` services.
4. Edit `docker-compose.yaml` file and add `restart: always` where is missing.
5. Reboot your stack, now Chatwood will go back online automatically.

### Expected behavior

Chatwoot shall get back online automatically when a system restart/reboot occurs.

### Environment

Docker

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu 24.04

### Docker (if applicable)

**root@chatwoot:~/chatwoot# docker version**
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        b72abbb
 Built:             Thu May 16 08:33:35 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.3
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       8e96db1
  Built:            Thu May 16 08:33:35 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**root@chatwoot:~/chatwoot# docker info**
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 26.1.3
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e377cd56a71523140ca6ae87e30244719194a521
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.4-3-pve
 Operating System: Ubuntu 24.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 6GiB
 Name: chatwoot
 ID: 81d335c1-92cf-40ef-8fdb-a7284096d2b7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**root@chatwoot:~/chatwoot# docker compose version**
Docker Compose version v2.27.0

**Comment by vishnu-narayanan** [comment]
@fabr2004 Thank you for taking the time to report this. This will be fixed via https://github.com/chatwoot/chatwoot/pull/9797
