### ISSUE TITLE
Missing A Report Module After Upgrading Version

### ISSUE THREAD

**Issue by Aiman-astios** [chatwoot/chatwoot#9508]
### Describe the bug

Hi after i upgrade the version of the chatwoot there were a report missing 
Before:
![image](https://github.com/chatwoot/chatwoot/assets/110952815/bdd7f9c7-c8d2-4476-82a2-66e6ade137ba)

After:
![image](https://github.com/chatwoot/chatwoot/assets/110952815/7158ae53-16b1-4c37-8c82-6d2ac8bfeebe)

i wanted to ask is this intentional or?

### To Reproduce

Run on a Linux, Manual Installation.
Chatwoot Latest Version 3.9.0

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Ubuntu

**Comment by pranavrajs** [comment]
@Aiman-astios There is no changes on this. Please check if the agent bots feature is enabled on all the accounts.
