### ISSUE TITLE
Contact attributes are missing on the web version since 1-2 months ago

### ISSUE THREAD

**Issue by mariusa** [chatwoot/chatwoot#9509]
### Describe the bug

Contact attributes are missing on the web version since 1-2 months ago. They continue to show properly on the Android app. 
I'm using your build at https://app.chatwoot.com/app/accounts
It says No attributes found, but they are properly sent from the client (same code as 2 years ago, no changes), and show on mobile.

### To Reproduce

1. Set contact attributes
2. See they don't show at https://app.chatwoot.com/app/

### Expected behavior

Show attributes, like it used to work until 1-2 months ago.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux

### Browser and version

Chrome

**Comment by sojan-official** [comment]
@mariusa If it’s on Chatwoot Cloud, could you raise a ticket using the contact support option? You can access it by clicking the user avatar on the bottom left. This helps us pinpoint the issue much more easily.

**Comment by sojan-official** [comment]
@mariusa, I tested this and found that only the custom attributes defined in settings will be rendered in the sidebar. The data is preserved in the contact object and is accessible via the API in other cases. I believe this was a behaviour change in one of the recent versions, so let me confirm it with the team.

Meanwhile, you can define the custom attributes you use in the settings tab, and the data will start appearing in the contacts tab. Defining this will help us identify the data type and make these values available in filters and automation as well.

**Comment by pranavrajs** [comment]
@mariusa This is done to ensure the quality of data so that we use it in the automations properly, will close this here for now.
