### ISSUE TITLE
Chore: Enhance the heroku one click deploy experience

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#951]
After deploying chatwoot to Heroku, one would have to configure mailer and storage as a minimum requirement for chatwoot to function. 

Let's make use of the available add ons like Cloudinary and mailgun to automate this process, so it will be truly one click. 

Steps
-----

- update app.json  to include cloudinary and mailgun add ons
- add the required environment variables as default values in app.json
- make changes in the application as required ( including cloudinary gem etc ) 

ref: https://hackernoon.com/image-storage-in-rails-apps-using-cloudinary-and-active-storage-9w2u3yli

**Comment by nithindavid** [comment]
@vishnu-narayanan Can you please check if this is still relevant?
