### ISSUE TITLE
Edit Attribute does not work anymore

### ISSUE THREAD

**Issue by idealprint** [chatwoot/chatwoot#9521]
### Describe the bug

Edit contact attribute does not work anymore. Now i have to delete and recreate.
![image](https://github.com/chatwoot/chatwoot/assets/56776316/ef8cbfca-b956-4df7-9487-b1e732a78cb1)

### To Reproduce

open a contact message -> see details -> contact attribute

### Expected behavior

Before, a pencil appeared indicating to edit the attribute. It does not appear anymore.

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu Linux 24 

### Browser and version

chrome

**Comment by pranavrajs** [comment]
This seems like a bug, we will have a fix for it soon.

**Comment by iamsivin** [comment]
> @iamsivin Can you please take a look into this? Also, please post when did it break. I suppose we had the option to edit the field if there is a value.

@pranavrajs The edit option is removed by this [PR](https://github.com/chatwoot/chatwoot/pull/9070/files#diff-fe9b82bbef1da31faa513332ed6015c0ed23765a6368832137a5408547da8938R172) as per the discussion. I will enable it back.

**Comment by idealprint** [comment]
hi. the edit option will be back on the next update?

**Comment by pranavrajs** [comment]
Yes, we have added it back.
