### ISSUE TITLE
Order message a in conversation by date/timestamp

### ISSUE THREAD

**Issue by zhiru** [chatwoot/chatwoot#9524]
### Describe the bug

We are using a hystory sincronizatio  off what’s app, the that’s are inserted correctly but the messages show in order based on index and must by first by date time than index

### To Reproduce

Insert manual, through database or api, messages with old date after actual

### Expected behavior

Show based on date time order

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by zhiru** [comment]
![IMG_3655](https://github.com/chatwoot/chatwoot/assets/4226997/7a539ad5-0ff2-4fc6-bb8c-15fa08b6b8b3)

**Comment by sojan-official** [comment]
@zhiru  We don't recommend directly populating the database, as the associated callbacks won't be executed. You can reorder the messages and populate the messages through a script.

**Comment by zhiru** [comment]
we are using a system to get history of messages, so when post/api/v1/accounts/..../conversations/.../messages tha messages saves right, but i can control the order off arriving dates.

example: post a message with date May 21, 12:55 PM, than May 17, 3:43 PM, than May 20, 6:13 PM, the order in chat box get`s out off order. 

I thought my team inserted it directly through the database but they told me they used the API as I mentioned above in the post, but they are using this one (https://www.postman.com/chatwoot/workspace/chatwoot-apis/request/162770-8f87071b-9910-4271-935a-7a12d619d109)
