### ISSUE TITLE
Export / Import (Backup) all Conversations

### ISSUE THREAD

**Issue by Evoltstore** [chatwoot/chatwoot#9527]
### Is your feature or enhancement related to a problem? Please describe.

- There seems to be no way to create a backup of all existing chatwoot conversations
- What happens if there is ever a major server issue? A business will lose ALL historic data of its tickets and conversations.
- What happens if Chatwoot stops being supported/developed in the future, all business messages become "stuck" and accessible only through Chatwoot?
- As a server gets full with more messages and images, it would make sense to create a backup of old messages and start fresh anew. 

### Describe the solution you'd like

Have a way to export ALL chatwoot conversations to a file that would be easy to interpret, maybe a JSON or a CSV
Ideally, have a way to import back into Chatwoot, but this is not mandatory.

**Comment by vishnu-narayanan** [comment]
@Evoltstore For a production deployment, it is recommended to enable automatic database backups. This feature is available in almost all cloud providers.

**Comment by pranavrajs** [comment]
Closing this as this is similar to #9692
