### ISSUE TITLE
Logo and agents profile pictures are not displayed on mobile

### ISSUE THREAD

**Issue by Adeline-S** [chatwoot/chatwoot#9533]
### Describe the bug

I set the logo image and the profile pictures. On desktop, the pictures are well displayed but when we visit the website on a smartphone, any image is displayed.

### To Reproduce

1. On any smartphone with Safari or Google Chrome browsers
2. Images format and size: I tested png and jpg, in 128x128 and 64x64. Nothing changed.

### Expected behavior

The pictures should be displayed correctly.

### Environment

Other [please specify in the description]

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

v3.9.0

### Browser and version

Safari 17.4.1 and Chrome Version 125.0.6422.80

### Additional context

We host the app in our own cloud server

**Comment by pranavrajs** [comment]
@Adeline-S Can you please share a screencast of the issue? There is too little information on which part of the product you have problems with.

**Comment by pranavrajs** [comment]
Closing this here for now due to inactivity.
