### ISSUE TITLE
[Bug] Sometimes not attaching error in message (ie: Message Undeliverable)

### ISSUE THREAD

**Issue by Cauen** [chatwoot/chatwoot#9542]
### Describe the bug

Sometimes, the error is attached to message
![image](https://github.com/chatwoot/chatwoot/assets/8796757/cc4c8dc3-32c6-47c6-b304-844e8ab9af1c)

But sometimes the error is ignored, and it's impossible to know why the message wasn't sent. The error was lost in limbo.
![image](https://github.com/chatwoot/chatwoot/assets/8796757/edc271da-4f03-4b49-87dc-eea30baf79e2)

In logs, ive extracted that was the same error from Whatsapp Cloud (131026)
The same error that had previously been linked to the message

### To Reproduce

Chatwoot Version: 3.8.0 in Docker (Cloud Hetzner)

In the logs these were the steps:

- I, [**2024-05-24T13:53:20.389699**]  INFO -- : [ActiveJob] [ActionCableBroadcastJob] [9f92df67-508c-4fe3-b7c2-24ba007e123f] Performing ActionCableBroadcastJob (Job ID: 9f92df67-508c-4fe3-b7c2-24ba007e123f) from Sidekiq(critical) enqueued at 2024-05-24T13:53:20Z with arguments: ...
- Performing EventDispatcherJob (Job ID: 16760969-cc4d-4a67-9958-0c6f1770c5d5) from Sidekiq(critical) enqueued at 2024-05-24T13:53:20Z with arguments: "message.created", Fri, 24 May 2024 13:53:20.337137450 UTC +00:00, {:message=>#<GlobalID:0x00007f58b2189ea0 @uri=#<URI::GID gid://chatwoot/Message/217876>>, :performed_by=>nil}
- I, I, [2024-05-24T13:53:20.424204]  INFO -- : [ActiveJob] [EventDispatcherJob] [16760969-cc4d-4a67-9958-0c6f1770c5d5] Performing EventDispatcherJob (Job ID: 16760969-cc4d-4a67-9958-0c6f1770c5d5) from Sidekiq(critical) enqueued at 2024-05-24T13:53:20Z with arguments: "message.created", Fri, 24 May 2024 13:53:20.337137450 UTC +00:00, {:message=>#<GlobalID:0x00007f58b2189ea0 @uri=#<URI::GID gid://chatwoot/Message/217876>>, :performed_by=>nil}
- I, [2024-05-24T13:53:20.430321]  INFO -- : [ActiveJob] [SendReplyJob] [e45018e7-806a-4f92-89ac-b579ca894e83] Performing SendReplyJob (Job ID: e45018e7-806a-4f92-89ac-b579ca894e83) from Sidekiq(high) enqueued at 2024-05-24T13:53:20Z with arguments: 217876
- I, [**2024-05-24T13:53:20.494002**]  INFO -- : [ActiveJob] [EventDispatcherJob] [16760969-cc4d-4a67-9958-0c6f1770c5d5] Enqueued ActionCableBroadcastJob (Job ID: 74617660-6b13-4cc8-ad45-1bc7e1c2bd4e) to Sidekiq(critical) with arguments: ["CGKrF6MYwd...
- I, [2024-05-24T13:53:20.497887]  INFO -- : [ActiveJob] [ActionCableBroadcastJob] [74617660-6b13-4cc8-ad45-1bc7e1c2bd4e] Performing ActionCableBroadcastJob (Job ID: 74617660-6b13-4cc8-ad45-1bc7e1c2bd4e) from Sidekiq(critical) enqueued at 2024-05-24T13:53:20Z with arguments: ["CGKrF6MYwdcU...
- I, [2024-05-24T13:53:20.523334]  INFO -- : [ActiveJob] [EventDispatcherJob] [16760969-cc4d-4a67-9958-0c6f1770c5d5] Enqueued WebhookJob (Job ID: 389434db-0603-4175-91f0-eaab24b8669b) to Sidekiq(medium) with arguments: "https://chat...
- I, [2024-05-24T13:53:20.527827]  INFO -- : [ActiveJob] [WebhookJob] [389434db-0603-4175-91f0-eaab24b8669b] Performing WebhookJob (Job ID: 389434db-0603-4175-91f0-eaab24b8669b) from Sidekiq(medium) enqueued at 2024-05-24T13:53:20Z with arguments: "https://chat...
- [2024-05-24T13:53:20.551394] ERROR -- : [ActiveJob] [SendReplyJob] [e45018e7-806a-4f92-89ac-b579ca894e83] {"error":{"message":"(#131026) Message undeliverable","type":"OAuthException","code":131026,"fbtrace_id":"AdjmlpoqDfFnAKcBFik1xzj"}}
- I, [2024-05-24T13:53:20.551503]  INFO -- : [ActiveJob] [SendReplyJob] [e45018e7-806a-4f92-89ac-b579ca894e83] Performed SendReplyJob (Job ID: e45018e7-806a-4f92-89ac-b579ca894e83) from Sidekiq(high) in 121.26ms

### Expected behavior

Any error that comes from Whatsapp Cloud is linked to the message to better understand the problem

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@Cauen Unfortunately, there is no way to reproduce this on our end. Please re-open this if you have any information to reproduce the issue.
