### ISSUE TITLE
Second inbox does not receive message

### ISSUE THREAD

**Issue by filipi2601** [chatwoot/chatwoot#9544]
### Describe the bug

When I send a message to Inbox X and then Inbox Y, the second inbox doesn't receive the message.

### To Reproduce

1. Send a message to Inbox X.
2. Send a message (from the same contact) to Inbox Y.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

**Comment by pranavrajs** [comment]
Closing this here for now due to inactivity.
