### ISSUE TITLE
Error attachment image

### ISSUE THREAD

**Issue by pphlucas** [chatwoot/chatwoot#9547]
### Describe the bug

Hi,

Hello, I have an image upload error in chatwoot (easypanel) I believe it is an error in Rubi.

When analyzing sidekiq I have this error below:
ActiveStorage::FileNotFoundError: ActiveStorage::FileNotFoundError

Version Chatwoot: 3.9.0

### To Reproduce

![Captura de tela 2024-05-25 194104](https://github.com/chatwoot/chatwoot/assets/16218388/4943ff4d-f420-477f-9a31-50c77ed4ac20)
![Captura de tela 2024-05-25 194049](https://github.com/chatwoot/chatwoot/assets/16218388/78be4084-31a9-494c-9cab-c9e0496847ac)

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

UBUNTU

**Comment by vishnu-narayanan** [comment]
@pphlucas Could you share the steps to reproduce this error? Are you getting error for all image uploads?

**Comment by mtuliosan** [comment]
I also have a problem uploading any file via chat. From what I understand, it is generating a URL like ".../rails/active_storage/blobs/redirect/..." and this URL is inaccessible, returning a 404 when accessed.

In the log, I have:
```

I, [2024-06-07T16:18:29.315947 #1]  INFO -- : [4fbd62b3-f7b4-421e-ac1c-5a9bf0aca62b] Completed 302 Found in 6ms (ActiveRecord: 0.5ms | Allocations: 1851)

I, [2024-06-07T16:18:29.316697 #1]  INFO -- : source=rack-timeout id=4fbd62b3-f7b4-421e-ac1c-5a9bf0aca62b timeout=15000ms service=18ms state=completed

I, [2024-06-07T16:18:29.465105 #1]  INFO -- : [0d01f850-99c0-4fa3-8dd8-c2fcc5b9b83a]   S3 Storage (373.6ms) Uploaded file to key: p5yzcouzaoyyd51gkv850uaekrs2 (checksum: 7Y/v7GxcsbHWZLRjudF5CQ==)

I, [2024-06-07T16:18:29.467183 #1]  INFO -- : [0d01f850-99c0-4fa3-8dd8-c2fcc5b9b83a] [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 4411ee95-8d13-4a05-acc8-29a5f1c01954) to Sidekiq(default) with arguments: #<GlobalID:0x00007f90f9c17118 @uri=#<URI::GID gid://chatwoot/ActiveStorage::Blob/468>>

I, [2024-06-07T16:18:29.472274 #1]  INFO -- : [0d01f850-99c0-4fa3-8dd8-c2fcc5b9b83a]   Rendered api/v1/accounts/conversations/messages/create.json.jbuilder (Duration: 3.8ms | Allocations: 911)

I, [2024-06-07T16:18:29.475854 #1]  INFO -- : [0d01f850-99c0-4fa3-8dd8-c2fcc5b9b83a] Completed 200 OK in 578ms (Views: 4.8ms | ActiveRecord: 76.4ms | Allocations: 39821)

I, [2024-06-07T16:18:29.476674 #1]  INFO -- : source=rack-timeout id=0d01f850-99c0-4fa3-8dd8-c2fcc5b9b83a timeout=15000ms service=588ms state=completed

I, [2024-06-07T16:18:29.828941 #1]  INFO -- : source=rack-timeout id=dd568b56-d81c-4a2d-8c77-1546d8001ce5 timeout=15000ms state=ready

I, [2024-06-07T16:18:29.829953 #1]  INFO -- : [dd568b56-d81c-4a2d-8c77-1546d8001ce5] Started GET "/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFFCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3fd1b37a13b1ef5ab65f8d78d43cf25f0ed0af88/Captura%20de%20tela%20de%202024-06-04%2020-42-29.png" for 172.18.0.1 at 2024-06-07 16:18:29 +0000

I, [2024-06-07T16:18:29.833642 #1]  INFO -- : [dd568b56-d81c-4a2d-8c77-1546d8001ce5] Processing by ActiveStorage::Blobs::RedirectController#show as PNG

I, [2024-06-07T16:18:29.833802 #1]  INFO -- : [dd568b56-d81c-4a2d-8c77-1546d8001ce5]   Parameters: {"signed_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFFCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3fd1b37a13b1ef5ab65f8d78d43cf25f0ed0af88", "filename"=>"Captura de tela de 2024-06-04 20-42-29"}

I, [2024-06-07T16:18:29.834870 #1]  INFO -- : [dd568b56-d81c-4a2d-8c77-1546d8001ce5] Filter chain halted as :set_blob rendered or redirected

I, [2024-06-07T16:18:29.835100 #1]  INFO -- : [dd568b56-d81c-4a2d-8c77-1546d8001ce5] Completed 404 Not Found in 1ms (ActiveRecord: 0.0ms | Allocations: 228)
```

POST: /api/v1/accounts/2/conversations/64/messages


RESPONSE :
.....data_url	"https://..../rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFVCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a2eb60469ad94d5e9bb917cdb8c74d65de3fffd0/Captura%20de%20tela%20de%202024-06-04%2020-42-29.png"

404

**Comment by mtuliosan** [comment]
@vishnu-narayananTradução

**Comment by mtuliosan** [comment]
waiting-for-reply @vishnu-narayanan

**Comment by juliancesar** [comment]
@pphlucas, if you manually access the URL after the 404 error, will it work?

**Comment by pphlucas** [comment]
Yes, I manually click the URL and get a 404 error, I installed CHATWOOT through EASYPANEL, I really don't know what it could be, possible configuration in the CHATWOOT template for EASYPANEL

**Comment by pranavrajs** [comment]
@TheOneironaut It seems the issue here is not with Chatwoot. It seems that you might not have a persistent storage setup configured.

If you are using docker, you need to specify the storage folder as a volume and make sure that the folder is getting stored persistently. https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose

Or use a persistent storage provider like S3, GCS etc.

Closing this here for now.
