### ISSUE TITLE
Message editor fails to render markdown headings

### ISSUE THREAD

**Issue by mazenkhalil** [chatwoot/chatwoot#9557]
### Describe the bug

The message editor component fails to render Markdown headings.

If the text within the editor contains `# ` , the save works as expected
![image](https://github.com/chatwoot/chatwoot/assets/21160900/b1183b1a-7402-4dc0-ac54-967866cee51e)

but upon rendering the component with `# ` within, it fails to render and shows as follow:
![image](https://github.com/chatwoot/chatwoot/assets/21160900/603dceca-5294-4cd4-8f5a-a428d5d2b01e)

The following error gets logged in the console.

![image](https://github.com/chatwoot/chatwoot/assets/21160900/368f6714-f099-4241-a458-784bff12501f)

### To Reproduce

1. Create a new website inbox
2. Enable channel greeting
3. Write '# Sample Message' in the text editor
4. Save the inbox settings
5. Close the inbox settings then open it again and observe the UI and the console log
 

### Expected behavior

The editor component should render properly

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
@mazenkhalil Thank you for reporting this.  I can reproduce this in staging.

**Comment by pranavrajs** [comment]
@iamsivin Please take a look at this issue.
