### ISSUE TITLE
Instalation Failure

### ISSUE THREAD

**Issue by edoardobadinotti** [chatwoot/chatwoot#9565]
### Describe the bug

When I run the install I keep getting  message during instalation while installing chatwoot part of:

error Command "webpack" not found

How can I solve this tried everything.  

### To Reproduce

Intall and happens alone

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu 20.04 LTS x64

### Browser and version

Google Chorme

### Additional context

Using server in Vultur

**Comment by edoardobadinotti** [comment]
Attaching my log of what happens during entire instalation on server
https://gist.github.com/edoardobadinotti/5d2dec63c8e40eab1883327ec29fe368

**Comment by vishnu-narayanan** [comment]
@edoardobadinotti Could you share the specifications of the machine you are trying to install chatwoot?

**Comment by edoardobadinotti** [comment]
Update finally got it working but now got it to install and trying to open it with http://myip:3000 and not opening

**Comment by edoardobadinotti** [comment]
http://45.32.174.10:3000 not opening.  Got it to install correctly it was lacking memory upgraded server and worked but now it simply wont open after completed install

**Comment by vishnu-narayanan** [comment]
Which cloud provider are you using? Have you opened port `3000`? 

Also, can you check the output of `curl http://localhost:3000`?

**Comment by edoardobadinotti** [comment]
<html><body>You are being <a href="http://localhost:3000/installation/onboarding">redirected</a>.</body></html>root@vultr:~#

I am using Vultr

**Comment by edoardobadinotti** [comment]
root@vultr:~# curl http://localhost:3000
<html><body>You are being <a href="http://localhost:3000/installation/onboarding">redirected</a>.</body></html>root@vultr:~#

**Comment by edoardobadinotti** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/171213321/ba1405e0-ba22-41fa-8330-d13ee1774a26)

**Comment by vishnu-narayanan** [comment]
```
root@vultr:~# curl http://localhost:3000/
You are being [redirected](http://localhost:3000/installation/onboarding).root@vultr:~#
```

That means chatwoot is running. To access it from the Internet, please open port `3000` on the Vultr control panel for your instance.

ref: https://docs.vultr.com/vultr-firewall

**Comment by edoardobadinotti** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/171213321/2473e205-5a13-4ff2-82ac-542086fbd34c)

**Comment by vishnu-narayanan** [comment]
@edoardobadinotti This seems to be an issue with Vultr.  Would you be able to reach out to Vultr support?

Also, Can you try deploying on Digitalocean(https://www.digitalocean.com/)?

**Comment by edoardobadinotti** [comment]
Ok now trying to install it in a digital ocean droplet.  but in the first stage i get this error and cant go passed it as it creates it in the log but doesnt allow me to do anything while instalation is running

![image](https://github.com/chatwoot/chatwoot/assets/171213321/13fc094c-6929-40fa-b848-2df0fa59caa1)**

**Comment by edoardobadinotti** [comment]
Already got it to work on digital ocean. The problem is with vultr for some reason dont understand what the issue isSent from my iPhoneOn Jun 5, 2024, at 4:53 AM, Vishnu Narayanan ***@***.***> wrote:﻿
@edoardobadinotti Are you still facing issues with installation?
Regd. the above screenshot, can you try proceeding to the next stage by selecting Keep the local version currently installed.

**Comment by vishnu-narayanan** [comment]
Awesome, marking this issue as closed.
