### ISSUE TITLE
Video message display issue

### ISSUE THREAD

**Issue by bin-bb** [chatwoot/chatwoot#9575]
### Is your feature or enhancement related to a problem? Please describe.

MP4 and other video formats should be directly displayed with the video tag instead of being downloaded, similar to Picture message.

<img width="394" alt="Video message display issue" src="https://github.com/chatwoot/chatwoot/assets/59748709/e77c8f0b-9958-4604-8e62-38205e19954d">

### Describe the solution you'd like

MP4 and other video formats should be directly displayed with the video tag instead of being downloaded, similar to Picture message.

**Comment by bin-bb** [comment]
The display method of video and picture messages in the Agent Dashboard dialog is very good.

**Comment by bin-bb** [comment]
Hope the display method of video and image messages in the widget dialog can be improved.

**Comment by bin-bb** [comment]
The images and videos of Dashboard conversations display very well.  Widget would be better this way.

<img width="387" alt="iShot_2024-06-04_06 47 23" src="https://github.com/chatwoot/chatwoot/assets/59748709/eaca5416-b66c-4385-a250-4ee508ad6c06">
<img width="736" alt="iShot_2024-06-04_06 48 35" src="https://github.com/chatwoot/chatwoot/assets/59748709/61b4904e-d5fa-4891-aa24-94a8fb354ce7">
<img width="732" alt="iShot_2024-06-04_06 48 50" src="https://github.com/chatwoot/chatwoot/assets/59748709/16205732-6be8-47b4-b678-feea58b8f9b8">

**Comment by pranavrajs** [comment]
@iamsivin Can you see if you can take this one?
