### ISSUE TITLE
Facebook app review requires information about permissions

### ISSUE THREAD

**Issue by thgh** [chatwoot/chatwoot#9595]
### Describe the bug

> Before you can start using your Facebook app in production, you will have to get it verified by Facebook.
> 

- pages_messaging: ok makes sense
- pages_show_list: is it required?
- pages_manage_metadata: is this used?
- business_management: for syncing business hours?
- pages_read_engagement?

For each of these, Facebook asks why they are requested.

### To Reproduce

1. Following https://www.chatwoot.com/docs/self-hosted/configuration/features/integrations/facebook-channel-setup
2. Go to developers.facebook.com
3. Select your app
4. Messenger > Messenger API Settings
5. <img width="922" alt="Screenshot 2024-06-05 at 07 41 15" src="https://github.com/chatwoot/chatwoot/assets/1109982/bb82daa0-1400-42b6-b9f3-fd57db6f5db6">
7. <img width="707" alt="Screenshot 2024-06-05 at 07 40 56" src="https://github.com/chatwoot/chatwoot/assets/1109982/6dd453b8-d704-4a95-a7d3-2f0a62577204">
7. Cannot make next screenshot as I already submitted

### Expected behavior

Docs could explain why permissions are required.

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

**Comment by laianeramos** [comment]
Yes! I still couldn't explain the pages_read_engagement permission. In my app review, they said the other permissions were valid for the app, but pages_read_engagement not, and I couldn't find out why it is necessary

**Comment by thgh** [comment]
All Facebook conversations show up in Chatwoot as coming from "John Doe". Which permission do you need to fix that?

**Comment by laianeramos** [comment]
@thgh pages_read_engagement or business user assest profile access (this last one is more easy to get)

**Comment by cpasqua** [comment]
Hi!

I'm trying to review the app in developers and they're responding with this.

. While testing, the URL provided led to a "site can't be reached" error. Please note that due to security purposes, we are unable to provide the information requested about how we access your app.

Has anyone gone through this? Do you have experience with it?

**Comment by sojan-official** [comment]
Closing this thread based on the response from  @CRSSA  : https://github.com/chatwoot/chatwoot/issues/9595#issuecomment-2248446539


@cpasqua this seems like a configuration issue with your facebook app settings or the installation config.  please see if there are any URL errors that occurs like the reviewer suggested

**Comment by muhsin-k** [comment]
https://github.com/orgs/chatwoot/discussions/7916#discussioncomment-13596672
