### ISSUE TITLE
How to install Ubuntu and Apache

### ISSUE THREAD

**Issue by netux55041** [chatwoot/chatwoot#9609]
### Describe the bug

Does not install on Apache

### To Reproduce

Does not install on Apache

### Expected behavior

Does not install on Apache

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by iammattmartin** [comment]
You'll need to give more detail but generally, this is not an application that runs in Apache.

**Comment by netux55041** [comment]
> [PR-1143 How to install Ubuntu and Apache](https://linear.app/chatwoot/issue/PR-1143/how-to-install-ubuntu-and-apache)

dont have access to this workspace.

**Comment by netux55041** [comment]
> You'll need to give more detail but generally, this is not an application that runs in Apache.

- https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm
- wget https://get.chatwoot.app/linux/install.sh
chmod +x install.sh
- ./install.sh --install
Some error has occured. Check '/var/log/chatwoot-setup.log' for details.
Encountered exception during recovery: certbot.errors.MisconfigurationError: nginx restart failed:

I am used APACHE... not nginx

**Comment by iammattmartin** [comment]
Well what does the log say?

**Comment by pranavrajs** [comment]
Closing this here as there is no information on the error. As @iammattmartin shared, the application doesn't run on Apache. 

From the comment and a quick google search, I think this is an issue with misconfiguration in the server. Please see the Stackoverflow thread. https://stackoverflow.com/questions/55698042/certbot-misconfigurationerror-nginx-restart-failed

If you are using Chatwoot alongside other applications, we don't officially support that. You have to run a standalone server for Chatwoot.
