### ISSUE TITLE
Database migration 

### ISSUE THREAD

**Issue by EDRfilho** [chatwoot/chatwoot#9614]
### Describe the bug

I did a git checkout from version 3.9.0 to version 3.3.1, however, when I went into superadmin I saw that the database migration was pending.
So I gave the commands: 

sudo -i -u chatwoot
cd chatwoot
RAILS_ENV=production bundle exec rake db:migrate
exit
systemctl daemon-reload && systemctl restart chatroot.target

It gave this error:
![Imagem do WhatsApp de 2024-06-07 à(s) 19 33 33_740e8853](https://github.com/chatwoot/chatwoot/assets/171742753/75217dff-07bc-424d-a9e5-28f20330d29a)

I gave this command:

sudo -i -u chatwoot
cd chatwoot
RAILS_ENV=production bundle exec rake db:prepare

It gave this error:

![image](https://github.com/chatwoot/chatwoot/assets/171742753/171a21d9-aa5f-404e-ae7e-6ddf762cf986)

How do I complete database migrations?

### To Reproduce

sudo -i -u chatwoot
cd chatwoot
RAILS_ENV=production bundle exec rake db:migrate
exit
systemctl daemon-reload && systemctl restart chatroot.target

sudo -i -u chatwoot
cd chatwoot
RAILS_ENV=production bundle exec rake db:prepare

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Windows pc - VPS Ubuntu 22.04.4 LTS

### Browser and version

Brave

### Additional context

Linux VM
Hetzner
Ubuntu 22.04.4 LTS

4
VCPU
8 GB
RAM
80 GB
DISK LOCAL

**Comment by pranavrajs** [comment]
@EDRfilho You can't downgrade from 3.9.0 to 3.3.1. The migration are not reversible. At the moment, there is no way fix as we don't support the downgrades. You would have to use 3.9.0
