### ISSUE TITLE
Add support for webhook actions in Macros

### ISSUE THREAD

**Issue by fhonline** [chatwoot/chatwoot#9616]
### Is your feature or enhancement related to a problem? Please describe.

<img width="657" alt="211125518-d30cf0b0-a3b3-4394-80d6-b5886e270f63" src="https://github.com/chatwoot/chatwoot/assets/95591514/30d104f5-318c-464e-b3bf-05da2974974c">

This would greatly help the integration of chat with any platform, executing just the macro, regardless of the webhook possibilities created in automations

Todo:

    Add support for a webhook event in macros
    Accept URL and Payload as parameters.

Validations:

    URL param: Required, should be a valid URL.
    Payload: Can be empty. Use {} as default if empty. It should be a valid JSON object.

Webhook event payload:

```
{
  "event": "macro_executed",
  "payload": {
    /*... Payload configured by the admin/agent in the macro definition */
  }
  "macro": {
    /*... macro object */
  },
  "agent": {
    /*... executed by agent */
  },
  "conversation": {
    /*... Conversation object at which this macro is executed */
  }
}
``` 

### Describe the solution you'd like

This could become an option where agents can trigger events in multiple different applications with one click. We could possibly ship standard pre-defined actions for products as generic integrations.

For eg: Updating a contact in Hubspot can be a similar webhook event with credentials, and the agent can trigger a macro which would then call the HubSpot API and update the fields as requested.

There are multiple workflows that can be created. (Sort of Zapier, but run manually by an agent)

**Comment by pranavrajs** [comment]
Duplicate https://github.com/chatwoot/chatwoot/issues/5968
