### ISSUE TITLE
Error: Message being delivered duplicately

### ISSUE THREAD

**Issue by jihee-k** [chatwoot/chatwoot#9618]
### Describe the bug

There are times when messages are sent in duplicate.

### To Reproduce

What I've checked so far is

First greeting to customer (macroX) -> Send specific macro -> reply from customer -> duplicate macro content sent earlier!

However, it is not a phenomenon that occurs every time, but an occasional phenomenon.
I want to know the cause, but can you figure it out?

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Browser and version

v3.8.0

**Comment by jihee-k** [comment]
No, there is no pattern.
The path I've found so far is below. This has happened a few times.

First greeting to customer (macroX) -> Send specific macro -> reply from customer -> duplicate macro content sent earlier

**Comment by jihee-k** [comment]
@pranavrajs 
No, there is no pattern.
The path I've found so far is below. This has happened a few times.

First greeting to customer (macroX) -> Send specific macro -> reply from customer -> duplicate macro content sent earlier!

**Comment by jihee-k** [comment]
@pranavrajs please check this issue

**Comment by pranavrajs** [comment]
@jihee-k This is not reproducible on our end. Can you please share any cases where we can reproduce this consistently?

**Comment by pranavrajs** [comment]
Possibly duplicate of https://github.com/chatwoot/chatwoot/issues/9314. Closing this here for now.
