### ISSUE TITLE
Contacts with out identifier

### ISSUE THREAD

**Issue by caiomzs** [chatwoot/chatwoot#9632]
### Describe the bug

When I add contacts manually within chatwoot, the identifier field within the database is registered with the value NULL.

When the contact does not exist, chatwoot registers it by inserting the remoteJid in the identifier field.

The problem is that I have many previously created contacts, and some automations in n8n use remoteJid (identifier) ​​to identify the lead. When it has a NULL value, my automation does not work.

### To Reproduce

1. When the contact is previously registered:
![registrado](https://github.com/chatwoot/chatwoot/assets/60412054/4778ef8c-04be-42aa-a550-a967c24d153f)

2. When the contact is NOT previously registered:
![naoregistrado](https://github.com/chatwoot/chatwoot/assets/60412054/f464e217-bcd3-43a7-9529-9581241b6b9f)

### Environment
Docker

### Cloud Provider
Other [São Paulo (BR) (Ascenty SP3 / Matrix)]

**Comment by jtayrone** [comment]
This is not a bug! To import contacts correctly and with the **`indentifier`** field filled in, you need to pass it in the import file. For example:

```
name,phone_number,identifier
Name Contact,+55xxxxxxxx,55xxxxxxxxx@s.whatsapp.net
```

**Comment by caiomzs** [comment]
> This is not a bug! To import contacts correctly and with the **`indentifier`** field filled in, you need to pass it in the import file. For example:
> 
> ```
> name,phone_number,identifier
> Name Contact,+55xxxxxxxx,55xxxxxxxxx@s.whatsapp.net
> ```

Right.

Here in Brazil, some numbers have an extra number, in theory it should be in accordance with the state's area code, but in practice it is not like that, for example: out of 10 contacts with the same area code, around 7 have this "extra number", and there is no way of knowing how the number will come from the Evolution API.

But... even if I manually add them one by one, the identifier field is null, in which case shouldn't it be created automatically? (considering that it was not import but insertion)

**Comment by sojan-official** [comment]
@caiomzs the identifier field is used to store the user id in your database and map it with the contacts in Chatwoot. Chatwoot never autogenerates the identifier field.  We only populate it if its passed on via the SDK , via import or manually through the API or UI. 

The identifier you shared in the screenshot must have been populated by an external API you are using.
