### ISSUE TITLE
Message receiving notification function

### ISSUE THREAD

**Issue by jihee-k** [chatwoot/chatwoot#9640]
### Is your feature or enhancement related to a problem? Please describe.

No notification is displayed even if the customer leaves a message, so it is not possible to check quickly

Even if I send you the solution, the customer can't see it right away, is there a solution?

### Describe the solution you'd like

If we send a message to the customer, I hope the customer can get a notification.

**Comment by jihee-k** [comment]
@sojan-official 
please check this issue

**Comment by pranavrajs** [comment]
@jihee-k It is not possible to understand the issue from the description. Can you please share more information on what you are trying to do and what the expectation is?

**Comment by jihee-k** [comment]
@pranavrajs 

Expectations: When we send a chat, the customer gets a notification that a message has come to us.

Reason for Need: Customers quickly check the messages we sent to help them learn the necessary information.

**Comment by pranavrajs** [comment]
@jihee-k 

If the customer is online, they would get the audio alert.  
If they are not, we will send a message to their email (if captured) with the message.

Closing this here for now as it seems the feature is already available. Please feel free to reopen this if it is not the case.
