### ISSUE TITLE
 Unable to Download Message Report and Encoding Issues

### ISSUE THREAD

**Issue by finda-soo** [chatwoot/chatwoot#9648]
### Describe the bug

The download button does not respond when clicked, and the downloaded report has encoding issues causing Korean characters to appear garbled. 
**Additionally, the ‘Conversations’ report tab also downloads the Agent report.**

<img width="523" alt="스크린샷 2024-06-17 오후 4 33 20" src="https://github.com/chatwoot/chatwoot/assets/163955250/bc53ff66-1fdd-40ef-adf5-789f98b7a6c5">

<img width="686" alt="스크린샷 2024-06-17 오후 4 35 14" src="https://github.com/chatwoot/chatwoot/assets/163955250/9ac1686f-6ddf-46df-970e-8a225cb744c6">

### To Reproduce

Environment: 
1. self-hosted version
2. Navigate to the report page.
3. Click the download button.
4. The button does not respond when clicked.
	
5. If the report is downloaded, the Korean characters appear garbled due to encoding issues.
6. In the ‘Conversations’ report tab, downloading a report results in the Agent report being downloaded.

### Expected behavior

1. Clicking the download button should successfully download the report.
2.The report should have the correct encoding so that Korean characters display properly.
**3. The ‘Conversations’ report tab should download the messages report, not the Agent report.**

### Environment

Kubernetes

### Cloud Provider

AWS

### Platform

Browser

**Comment by jihee-k** [comment]
@JeffOtano check this issue plz.
