### ISSUE TITLE
Ubuntu 22.04 or 24.04?

### ISSUE THREAD

**Issue by maxihoster** [chatwoot/chatwoot#9654]
### Describe the bug

Hello! On the documentation the OS supported is 20.04 but it's a wrong info or not?

Can we upgrade to 22.04 or 24.04?

Regards

### To Reproduce

Dist upgrade

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

None

### Operating system

Ubuntu

**Comment by devsubngrill** [comment]
Yes is possible Ubuntu 24.04 my installation is in Ubuntu 24

**Comment by vishnu-narayanan** [comment]
@maxihoster The installation is now supported on 20.04, 22.04 and 24.04.
