### ISSUE TITLE
Onlyfans inbox

### ISSUE THREAD

**Issue by srameshr** [chatwoot/chatwoot#9660]
### Is your feature or enhancement related to a problem? Please describe.

Creators and their management agencies with content on Onlyfans need Chatwoot CRM.

### Describe the solution you'd like

A new Onlyfans inbox 

### Describe alternatives you've considered

[Infloww](https://infloww.com/)

**Comment by pranavrajs** [comment]
Chatwoot is primarily focussed for businesses and their use cases. This request doesn't fit into that. We will not support it.

**Comment by srameshr** [comment]
@pranavrajs Agencies that manage multiple creators are all businesses. Can you please at least open it up for discussion?

**Comment by pranavrajs** [comment]
@srameshr The channel is not for businesses, it's for creators. We don't intend to support individual/personal brand accounts at the moment.
