### ISSUE TITLE
Limit storage per account and Monitoring account space usage

### ISSUE THREAD

**Issue by mmojadad** [chatwoot/chatwoot#9663]
### Is your feature or enhancement related to a problem? Please describe.

In self-hosted its important to have a mechanism to manage space. Already there is not any monitoring or limit definitions for account space usage. 

### Describe the solution you'd like

In superadmin ability to define limitation ( Size ) or Keep history date or unlimited option per account.
A monitoring report to show space usage per account.

### Describe alternatives you've considered

If chatwoot team have not plan to develop this future , Provide a command-line solution for self-hosted users.

**Comment by devsubngrill** [comment]
Great and options to maintenance example if account more 30,90 days without any conversation deleting and option to clean the database to old 15 , 30 , 90 days to maintain performance and to save in the database content no needed.

**Comment by pranavrajs** [comment]
@mmojadad Thank you for the request. However, this is not a core feature required for Chatwoot to function, so we will not be pursuing it.
