### ISSUE TITLE
Add a view to see the snoozed and pending conversations

### ISSUE THREAD

**Issue by laianeramos** [chatwoot/chatwoot#9665]
### Is your feature or enhancement related to a problem? Please describe.

We only can see snoozed and pending conversations if we use filters. It would be more efficient to have a menu already set to view this conversations, right under "unattended"

ref: https://github.com/chatwoot/chatwoot/issues/2657

### Describe the solution you'd like

![image](https://github.com/chatwoot/chatwoot/assets/169591365/d3c1491a-34da-4cf5-83dc-49205e9341b7)

**Comment by Midasstart** [comment]
I support this idea

**Comment by pranavrajs** [comment]
@Midasstart @laianeramos This filter is already available as shown in the image below. 

<img width="463" alt="Screenshot 2024-07-07 at 9 22 06 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/07aa89b5-bff2-43c2-9d84-87c57db63e62">

Please re-open this if it doesn't solve the issue.

**Comment by laianeramos** [comment]
@pranavrajs The request is to creat a column to the snoozed and pending conversations without having to filter, to facilitate remembering this conversations. Having to filter make us to forget about this conversations, and having a column specific for it is easier, like there is to “unattended conversation”. And for resolved conversations too would be nice. 

We would use the filters to get more specific information, like creation date, assignee, teams etc.

**Comment by pranavrajs** [comment]
Would it be easier to create a folder if you want to remember the conversations? See this documentation. https://www.chatwoot.com/hc/user-guide/articles/1677698771-group-chats-with-filters-save-as-folders

**Comment by laianeramos** [comment]
@pranavrajs sorry, I didn't know about this. Thank you!
