### ISSUE TITLE
bot responds even when agent is available

### ISSUE THREAD

**Issue by petebytes** [chatwoot/chatwoot#967]
**Describe the bug**
Agent shows available.
When user sends message the Bot responds with Agent away message

**To Reproduce**
1. Click on buble to open chat
2. Ensure Agent is 'available'
3. Send a message
4. See Bot responce

**Expected behavior**
The bot should not respond if the agent status available

**Screenshots**
![image](https://user-images.githubusercontent.com/676739/84741594-29236f80-af64-11ea-8e9c-ffad4a3bfce9.png)

![image](https://user-images.githubusercontent.com/676739/84741673-422c2080-af64-11ea-848c-d8b458bbfd4f.png)

**Desktop (please complete the following information):**
 - Firefox 78.0b7 (also tried chrome)

**Additional context**

**Comment by pranavrajs** [comment]
@petebytes There is some flaky behaviour with the way keys are set to expire now, this should be fixed in #874

**Comment by pranavrajs** [comment]
@petebytes The message has been renamed to greeting message which is meant to be sent for all users. The use case which you are suggesting would be covered via #234. You would be able to set a time when you will be available and a different message if you are unavailable.

**Comment by petebytes** [comment]
Ah! that makes sense.
This project is crazy active - keep up the amazing job.
