### ISSUE TITLE
Incorrect URL when sending survey responses

### ISSUE THREAD

**Issue by jeanjonathas** [chatwoot/chatwoot#9670]
### Describe the bug

When trying to send survey responses, the generated URL is incorrect. The generated URL is https:///survey/responses/0571ed41-1b9e-4bca-9d37-b838ebc9772e
### To Reproduce

In the production environment of Chatwoot self hosted by easypanel v3.10.0 vps hostinger
After ending a conversation, the system automatically sends the CSAT link, but it is broken.
See the error in the generated URL...

### Expected behavior

The expected URL should be https://chat.supervet.app/survey/responses/.

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

 Windows 10

### Browser and version

chrome

### Docker (if applicable)

easypanel [1.42.1](https://feedback.easypanel.io/changelog/1421)

**Comment by phpmac** [comment]
https/rails/active_storag

**Comment by jeanjonathas** [comment]
> https/rails/active_storag

in files or bd?

**Comment by phpmac** [comment]
> > https/rails/active_storag
> 
> in files or bd?

image,Also, when the browser notifies you, there will be problems with the URL you click.

**Comment by phpmac** [comment]
<img width="581" alt="截屏2024-06-24 02 13 21" src="https://github.com/chatwoot/chatwoot/assets/86544347/87d135a0-b75a-44cd-87c1-021a84c7c51c">

This is the picture sent by the administrator. It will be displayed like this. At the same time, there is a problem with the URL link. It is:

<img width="1213" alt="截屏2024-06-24 02 14 18" src="https://github.com/chatwoot/chatwoot/assets/86544347/2cc6b223-aa1d-48ef-9821-f54f684d0207">

This is the picture sent by the administrator, it will become like this
<img width="873" alt="截屏2024-06-24 02 14 44" src="https://github.com/chatwoot/chatwoot/assets/86544347/db2717aa-a073-44a1-9195-a5359d9c9ab9">

**Comment by jeanjonathas** [comment]
> <img alt="截屏2024-06-24 02 13 21" width="581" src="https://private-user-images.githubusercontent.com/86544347/342106837-87d135a0-b75a-44cd-87c1-021a84c7c51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY4MzctODdkMTM1YTAtYjc1YS00NGNkLTg3YzEtMDIxYTg0YzdjNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MmYyMzc5ZTg1NTM4MDAxYTAzY2Q3YTdiOTE2NzlmZjhhNDJlYTQ0ZjMyMzI0YjEwODBmNTg0M2ZiZTYxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3zkpPhaSz9HdCaFXtEKs7HDENkh6ZlTQxDba3XBK6FM">
> This is the picture sent by the administrator. It will be displayed like this. At the same time, there is a problem with the URL link. It is:
> 
> <img alt="截屏2024-06-24 02 14 18" width="1213" src="https://private-user-images.githubusercontent.com/86544347/342106866-2cc6b223-aa1d-48ef-9821-f54f684d0207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY4NjYtMmNjNmIyMjMtYWExZC00OGVmLTk4MjEtZjU0ZjY4NGQwMjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OWVhOTE2NWJhMjkwNDJiMDBkYzk1ZDcxMWJmODQ4MmIxZWZlM2QzMWQzNjgzNTMwZThkMzkzMmNiOGVlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQaJVdeNQ5TojE5Vfy_L7JWLNKJ7uFLPYJk64LluKoM">
> This is the picture sent by the administrator, it will become like this <img alt="截屏2024-06-24 02 14 44" width="873" src="https://private-user-images.githubusercontent.com/86544347/342106901-db2717aa-a073-44a1-9195-a5359d9c9ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY5MDEtZGIyNzE3YWEtYTA3My00NGExLTkxOTUtYTUzNTlkOWM5YWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YjZlYTczOWRmZDM1MWFiZjIyOTdjMDg2YmYxZTE4NTQxZjQxMDg1YjM1ODdkODgwMTg0MDFjYTdjM2QwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R8TgpBLvTlkSARO7P0R-_J41vtXnyTBt90TpZfqpSzo">

Thank you for clarifying.
However, I am a beginner in this area. I installed Chatwoot via EasyPanel and I don't know the name of the file I need to edit to configure this link.

**Comment by phpmac** [comment]
> > <img alt="截屏2024-06-24 02 13 21" width="581" src="https://private-user-images.githubusercontent.com/86544347/342106837-87d135a0-b75a-44cd-87c1-021a84c7c51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY4MzctODdkMTM1YTAtYjc1YS00NGNkLTg3YzEtMDIxYTg0YzdjNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MmYyMzc5ZTg1NTM4MDAxYTAzY2Q3YTdiOTE2NzlmZjhhNDJlYTQ0ZjMyMzI0YjEwODBmNTg0M2ZiZTYxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3zkpPhaSz9HdCaFXtEKs7HDENkh6ZlTQxDba3XBK6FM">
> > This is the picture sent by the administrator. It will be displayed like this. At the same time, there is a problem with the URL link. It is:
> > <img alt="截屏2024-06-24 02 14 18" width="1213" src="https://private-user-images.githubusercontent.com/86544347/342106866-2cc6b223-aa1d-48ef-9821-f54f684d0207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY4NjYtMmNjNmIyMjMtYWExZC00OGVmLTk4MjEtZjU0ZjY4NGQwMjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OWVhOTE2NWJhMjkwNDJiMDBkYzk1ZDcxMWJmODQ4MmIxZWZlM2QzMWQzNjgzNTMwZThkMzkzMmNiOGVlMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQaJVdeNQ5TojE5Vfy_L7JWLNKJ7uFLPYJk64LluKoM">
> > This is the picture sent by the administrator, it will become like this <img alt="截屏2024-06-24 02 14 44" width="873" src="https://private-user-images.githubusercontent.com/86544347/342106901-db2717aa-a073-44a1-9195-a5359d9c9ab9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjY4MDgsIm5iZiI6MTcxOTE2NjUwOCwicGF0aCI6Ii84NjU0NDM0Ny8zNDIxMDY5MDEtZGIyNzE3YWEtYTA3My00NGExLTkxOTUtYTUzNTlkOWM5YWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE4MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3YjZlYTczOWRmZDM1MWFiZjIyOTdjMDg2YmYxZTE4NTQxZjQxMDg1YjM1ODdkODgwMTg0MDFjYTdjM2QwOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R8TgpBLvTlkSARO7P0R-_J41vtXnyTBt90TpZfqpSzo">
> 
> Thank you for clarifying. However, I am a beginner in this area. I installed Chatwoot via EasyPanel and I don't know the name of the file I need to edit to configure this link.

Do you mean the file needs to be edited?

**Comment by jeanjonathas** [comment]
> https:///survey/responses/0571ed41-1b9e-4bca-9d37-b838ebc9772e

Exactly, where is the domain variable that makes the link work? Is this variable in the database or in the files? Because I have already looked in the settings and there is no place to configure this via the frontend.
https://$variable/survey/responses/

**Comment by phpmac** [comment]
> > https:///survey/responses/0571ed41-1b9e-4bca-9d37-b838ebc9772e
> 
> Exactly, where is the domain variable that makes the link work? Is this variable in the database or in the files? Because I have already looked in the settings and there is no place to configure this via the frontend. https://$variable/survey/responses/

Where is the file location of this code?

**Comment by jeanjonathas** [comment]
> > > https:///survey/responses/0571ed41-1b9e-4bca-9d37-b838ebc9772e
> > 
> > 
> > Exactly, where is the domain variable that makes the link work? Is this variable in the database or in the files? Because I have already looked in the settings and there is no place to configure this via the frontend. https://$variable/survey/responses/
> 
> Where is the file location of this code?

I don't know, this link appears in the automatic message from Chatwoot when CSAT is enabled.

**Comment by phpmac** [comment]
whats CAST, i want disable it,sir

**Comment by vishnu-narayanan** [comment]
@jeanjonathas Have you configured the `FRONTEND_URL` env variable?

ref: https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-frontend-url-domain

**Comment by jeanjonathas** [comment]
> @jeanjonathas Have you configured the `FRONTEND_URL` env variable?
> 
> ref: https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables#configure-frontend-url-domain

yes, that part is set up

**Comment by jeanjonathas** [comment]
help

**Comment by pranavrajs** [comment]
<img width="557" alt="Screenshot 2024-06-25 at 9 53 17 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/a7e36538-1967-44c2-81ac-e6bc52cead37">

@jeanjonathas This is how we generate the link. The only reason the URL is generated like the above is that you have not setup the FRONTEND_URL config. Now, if you have set it up. You must be missing the restart. Restart all the services, it should fix the issue.

**Comment by phpmac** [comment]
> <img alt="Screenshot 2024-06-25 at 9 53 17 PM" width="557" src="https://private-user-images.githubusercontent.com/2246121/343012948-a7e36538-1967-44c2-81ac-e6bc52cead37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzg0MjcsIm5iZiI6MTcxOTM3ODEyNywicGF0aCI6Ii8yMjQ2MTIxLzM0MzAxMjk0OC1hN2UzNjUzOC0xOTY3LTQ0YzItODFhYy1lNmJjNTJjZWFkMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDUwMjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU5M2I0MDViNWYwMWZmOTMwNDE2ZjY2NGU4YTg3NGNjOGU4NWJiZmQwMDk2NDM4MDczZmIyMWRmZTVhYzBlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9Zyl3HHrGdSGXjKvCMw9oJw2IzVZakq64ULOk7Qc5vY">
> @jeanjonathas This is how we generate the link. The only reason the URL is generated like the above is that you have not setup the FRONTEND_URL config. Now, if you have set it up. You must be missing the restart. Restart all the services, it should fix the issue.

thankyou so much
