### ISSUE TITLE
WhatsApp Message Templates not updating 

### ISSUE THREAD

**Issue by Abodolla** [chatwoot/chatwoot#9672]
### Describe the bug

When i make new WhatsApp Message Templates (text only) not shown in my WhatsApp channel 

### To Reproduce

Fix that issue or make that updated manually by  add Sync button or something related . 

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by shivamkb17** [comment]
Contact me, I Will fix whatsapp template issue for you.

**Comment by vishnu-narayanan** [comment]
@Abodolla Whatsapp templates are synced every hour. You should see new templates within an hour or less.

cc: @sojan-official

**Comment by pranavrajs** [comment]
Closing this as there is no specific issue identified here, can re-open if it is not the case.
