### ISSUE TITLE
OpenAI Integration is not working

### ISSUE THREAD

**Issue by justin4game** [chatwoot/chatwoot#9679]
### Describe the bug

If i am creating an OpenAI API Key, paste it into Chatwoo i will not getting any answers out of the ai tool : 
![image](https://github.com/chatwoot/chatwoot/assets/50381292/a33a4c98-c040-4d99-a19f-3f87a8b623c5)

### To Reproduce

1. Setup Project Enviroment
2. Create OpenAI Key
3. Then paste it and try a AI tool

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Linux Ubuntu 22

### Browser and version

Chrome

**Comment by justin4game** [comment]
![image](https://github.com/chatwoot/chatwoot/assets/50381292/13e6f60d-f1d1-43db-8e97-8947cd2a490f)

![image](https://github.com/chatwoot/chatwoot/assets/50381292/9b35f5ac-1f81-4a44-addf-62b12f9fb08f)

![image](https://github.com/chatwoot/chatwoot/assets/50381292/da049f9d-a21a-45a0-b548-8b53bed32b4f)

**Comment by vishnu-narayanan** [comment]
Could you check the server logs to see if there are any errors?

**Comment by justin4game** [comment]
10:21:11 backend.1  | Started POST "/api/v1/accounts/1/integrations/hooks/1/process_event" for ::1 at 2024-06-25 10:21:11 +0200
10:21:11 backend.1  | Processing by Api::V1::Accounts::Integrations::HooksController#process_event as JSON
10:21:11 backend.1  |   Parameters: {"event"=>{"name"=>"rephrase", "data"=>{"content"=>"How are you?"}}, "account_id"=>"1", "id"=>"1", "hook"=>{"event"=>{"name"=>"rephrase", "data"=>{"content"=>"How are you?"}}}}
10:21:11 backend.1  | OpenAI API request: {"model":"gpt-3.5-turbo","messages":[{"role":"system","content":"You are a helpful support agent. Please rephrase the following response. Ensure that the reply should be in user language."},{"role":"user","content":"How are you?"}]}
10:21:11 backend.1  | OpenAI API response: {
10:21:11 backend.1  |     "error": {
10:21:11 backend.1  |         "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
10:21:11 backend.1  |         "type": "insufficient_quota",
10:21:11 backend.1  |         "param": null,
10:21:11 backend.1  |         "code": "insufficient_quota"
10:21:11 backend.1  |     }
10:21:11 backend.1  | }
10:21:11 backend.1  |
10:21:11 backend.1  | Completed 200 OK in 286ms (Views: 0.1ms | ActiveRecord: 1.0ms | Allocations: 13143)

**Comment by justin4game** [comment]
I am sorry i forgot to put more credit on OpenAI i will close the issue
