### ISSUE TITLE
Gathering the chat room

### ISSUE THREAD

**Issue by jihee-k** [chatwoot/chatwoot#9683]
### Is your feature or enhancement related to a problem? Please describe.

There is a problem that the existing conversation history is deleted when the customer moves to another inbox.

### Describe the solution you'd like

고객의 관점에서 받은 편지함 간의 대화 연속성을 유지할 수 있는 방법이 필요합니다. 
고객이 모든 대화를 한 곳에서 볼 수 있는 기능 요청드립니다.

**Comment by pranavrajs** [comment]
@jihee-k Please start a discussion on the feature request with more information. https://github.com/orgs/chatwoot/discussions/categories/feature-requests

Please use English as the conversation as we don't have expertise in Korean.
