### ISSUE TITLE
rasa agentbot

### ISSUE THREAD

**Issue by zhaowei2021** [chatwoot/chatwoot#9685]
### Describe the bug

I have deployed Chatwoot on my server through a self-hosted setup and have also deployed a bot using the rasa-agentbot-demo, with the bot running via PHP. I have embedded the chat widget on my webpage. When a user sends a message, the agentbot responds correctly. When a human customer service agent takes over the conversation, the agentbot stops responding to the user's messages, but at this point, a bubbling status appears in the chat window, as shown in the picture. How can I fix this issue?

### To Reproduce

this is my php file

### Environment

Linux VM

### Cloud Provider

None

### Platform

None

```[tasklist]
### Tasks
```

**Comment by zhaowei2021** [comment]
![Dingtalk_20240626150342](https://github.com/chatwoot/chatwoot/assets/88483375/3870a6d0-5ed9-4d26-8449-c65f87bb3dc2)

**Comment by zhaowei2021** [comment]
<?php

/* Config */

$rasa_url = 'http://10.0.4.46:5005';
$chatwoot_url = 'http://10.0.4.8:3000';
$chatwoot_bot_token = 'cFETW6XCAyGjYPiatdvVvcQ4';
$userApiKey = 'WZ3jzUDUDJ9t22pkz2y8Nsp6';

$json = file_get_contents('php://input');
error_log("request payload: #{$json}", 0);

$data = json_decode($json);

$message_type = isset($data->message_type) ? $data->message_type : null;
$message = isset($data->content) ? $data->content : null;
$conversation = isset($data->conversation->id) ? $data->conversation->id : null;
$contact = isset($data->sender->id) ? $data->sender->id : null;
$account = isset($data->account->id) ? $data->account->id : null;

error_log("message_type: {$message_type}", 0);
error_log("message: {$message}", 0);
error_log("conversation: {$conversation}", 0);
error_log("contact: {$contact}", 0);
error_log("account: {$account}", 0);

if ($message_type == "incoming") {
    // 获取对话状态
    $conversation_status = get_conversation_status($account, $conversation);
    error_log("conversation_status: {$conversation_status}", 0);
    
    // 如果对话状态是 "pending"，则发送消息给机器人
    if ($conversation_status == "pending") {
        error_log("sending message to bot: {$message}", 0);
        $bot_response = send_to_bot($contact, $message);
        if (isset($bot_response->text)) {
            error_log("bot replied: {$bot_response->text}", 0);
            $create_message = send_to_chatwoot($account, $conversation, $bot_response->text);
        } else {
            error_log("bot did not return a valid response.", 0);
        }
    } else {
        error_log("conversation is handled by human agent, bot will not respond.", 0);
        // 返回一个明确的响应
        http_response_code(200);
        echo json_encode(["status" => "handled by human"]);
        return;

    }
}

function send_to_bot($sender, $message) {
    global $rasa_url;
    error_log("Preparing to send message to bot: {$message}", 0);
    $url = "{$rasa_url}/webhooks/rest/webhook";
    $data = array('sender' => $sender, 'message' => $message);

    $options = array(
        'http' => array(
            'method' => 'POST',
            'content' => json_encode($data),
            'header' => "Content-Type: application/json\r\n" .
                        "Accept: application/json\r\n"
        )
    );

    $context = stream_context_create($options);
    $result = file_get_contents($url, false, $context);
    if ($result === FALSE) {
        error_log("Failed to send message to bot. HTTP request failed.", 0);
        return null;
    }
    error_log("Message sent to bot, response received: {$result}", 0);
    $response = json_decode($result);
    return isset($response[0]) ? $response[0] : null;
}

function send_to_chatwoot($account, $conversation, $message) {
    global $chatwoot_url, $chatwoot_bot_token;
    error_log("Preparing to send message to Chatwoot: {$message}", 0);
    $url = "{$chatwoot_url}/api/v1/accounts/{$account}/conversations/{$conversation}/messages";
    $data = array('content' => $message);

    $options = array(
        'http' => array(
            'method' => 'POST',
            'content' => json_encode($data),
            'header' => "Content-Type: application/json\r\n" .
                        "Accept: application/json\r\n" .
                        "api_access_token: {$chatwoot_bot_token}\r\n"
        )
    );

    $context = stream_context_create($options);
    $result = file_get_contents($url, false, $context);
    if ($result === FALSE) {
        error_log("Failed to send message to Chatwoot. HTTP request failed.", 0);
        return null;
    }
    error_log("Message sent to Chatwoot, response received: {$result}", 0);
    return $result;
}

function get_conversation_status($account, $conversation) {
    global $chatwoot_url, $userApiKey;
    error_log("Getting conversation status for account: {$account}, conversation: {$conversation}", 0);
    $url = "{$chatwoot_url}/api/v1/accounts/{$account}/conversations/{$conversation}";
    $options = array(
        'http' => array(
            'method' => 'GET',
            'header' => "api_access_token: {$userApiKey}\r\n"
        )
    );

    $context = stream_context_create($options);
    $result = file_get_contents($url, false, $context);
    if ($result === FALSE) {
        error_log("Failed to get conversation status. HTTP request failed.", 0);
        return null;
    }
    error_log("Conversation status response received: {$result}", 0);
    $response = json_decode($result, true);
    return isset($response['status']) ? $response['status'] : null;
}

?>

**Comment by pranavrajs** [comment]
@zhaowei2021 The indicator is shown in the following cases: 

- If the agent is typing.
- If the conversation is in pending status and the inbox is connected with the agent bot. 

The second one seems to be the case here. Once the flow is complete in Rasa, please change the status of the conversation to open (from pending) and it should resolve the issue. 

Please feel free to reopen if it is not the case.
