### ISSUE TITLE
No Dialog 360 Whatsapp API

### ISSUE THREAD

**Issue by justin4game** [chatwoot/chatwoot#9688]
### Describe the bug

Hello, in the User Guide there is a possibility to select 360 Dialog but not in the web app?

### To Reproduce

1. Setup Enviroment
2. Look at images at this userguide: https://www.chatwoot.com/hc/user-guide/articles/1677832735-how-to-setup-a-whats_app-channel
https://app.chatwoot.com/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NrVHc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--826ce85840574910e6c2224fc4ca6ec2cc2fe0b5/whatsapp%20inbox%20api%20providers.png

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

**Comment by jtayrone** [comment]
Since version v3.9.0, it is no longer possible to connect dialog 360 inbox.

**Comment by justin4game** [comment]
Will this feature come back?

**Comment by jtayrone** [comment]
> is feature come back?
More details at: https://github.com/chatwoot/chatwoot/releases/tag/v3.9.0

**Comment by justin4game** [comment]
Thank you
