### ISSUE TITLE
Chatwoot Widget creates multiple conversation_id under one contact

### ISSUE THREAD

**Issue by heatonmar** [chatwoot/chatwoot#9696]
### Is your feature or enhancement related to a problem? Please describe.

When my widget was triggered. I could normally chat with agent A. But when I  tried to clean my session, login again and start a chat with agent A, I couldn't see the previous messages I sent. Seems like a new conversation_id was created under the same contact so the messages were gone in the frontend but I could still find the history messages through database (differeent conversation_id).
![image](https://github.com/chatwoot/chatwoot/assets/51690431/052d9391-6f90-4e2f-abdf-4356b751ad5c)

### Describe the solution you'd like

I'd like to find a way to merge all the conversations together under the same inbox_id and contact_id. No more new conversation_id.

```[tasklist]
### Tasks
```

**Comment by heatonmar** [comment]
> [PR-1187 Chatwoot Widget creates multiple conversation_id under one contact](https://linear.app/chatwoot/issue/PR-1187/chatwoot-widget-creates-multiple-conversation-id-under-one-contact)

Don't have access to this Workspace

**Comment by heatonmar** [comment]
`function initializeChatwoot(contactId, email, websiteToken) {
        alert('Chat Started');
        window.chatwootSettings = {"position":"right","type":"standard","launcherTitle":"Contact me"};
        (function(d,t) {
          var BASE_URL="https://xx.xxx.xx.xxx:3000";
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src=BASE_URL+"/packs/js/sdk.js";
          g.defer = true;
          g.async = true;
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            window.chatwootSDK.run({
              websiteToken: websiteToken,
              baseUrl: BASE_URL
            });
            // wait for Chatwoot SDK loaded
            window.addEventListener("chatwoot:ready", function () {
                // set User Info
                window.$chatwoot.setUser(contactId, {
                    email: email
                });
            });
          }
        })(document,"script");
    }`

**Comment by pranavrajs** [comment]
This is intentional to disallow impersonation. If you would like to see the chat history across sessions, please implement identity validation as described in the link below. 

https://www.chatwoot.com/hc/user-guide/articles/1677587479-how-to-enable-identity-validation-in-chatwoot
