### ISSUE TITLE
Dyte Integration i18n (Translation)

### ISSUE THREAD

**Issue by tristan-charbonnier** [chatwoot/chatwoot#9699]
### Is your feature or enhancement related to a problem? Please describe.

You can use Chatwoot in various languages but Dyte integration stays in English :(

![image](https://github.com/chatwoot/chatwoot/assets/135015151/96e1910b-ccc6-4cfa-af1c-4eae0c6bde2e)

### Describe the solution you'd like

Being able to translate the various strings used in Dyte integration ("Joined as", "Join" button label, etc).

**Comment by pranavrajs** [comment]
There is no option to provide a language in Dyte SDK. https://docs.dyte.io/guides/live-video/client-setup/javascript. Please re-open this if there is a misunderstanding.
