### ISSUE TITLE
Setup Javascript tests framework

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#97]
- [ ] Identify the framework to be used.
- [ ] Initialize the repo with basic specs.

**Comment by fluffynuts** [comment]
I'd like to work on this, with the suggestion to use Jest for the test framework.

I've also had experience with mocha and jasmine; jest is quite easy to get up and running, and, in addition, facilitates:
- incremental testing based on git status
- parallel testing, with each spec isolated from each other

Thoughts?

**Comment by pranavrajs** [comment]
> I'd like to work on this (especially if labelled with hacktoberfest, but even if not), 
I've added the label

> with the suggestion to use Jest for the test framework.

I've worked with Jest and mocha. Jest seems to be a good option. Please go ahead if you are interested.

**Comment by MatheusRich** [comment]
For testing I would suggest [Cypress](https://www.cypress.io).

**Comment by pranavrajs** [comment]
@MatheusRich We are looking for unit tests first, that's why Jest is taken into consideration, and yes for an end-to-end test Cypress or RobotFramework can be considered

**Comment by MatheusRich** [comment]
@pranavrajs In fact Cypress [can do unit testing too](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Test-Structure). But I understand it's good to use an already known lib

**Comment by fluffynuts** [comment]
Just a heads-up that I _am_ looking into this, currently having trouble getting Jest to perform the required Babel transforms so that tests can be written with the same syntax as prod code; in particular, statements like:
```
import 'some-module';
```
are not being transformed correctly. There must be something I'm Doing Wrong -- will update when I figure it out (:

**Comment by pranavrajs** [comment]
@fluffynuts Thanks for taking a look, could you please raise a PR, so that I'd be able to take a look and help.

**Comment by sojan-official** [comment]
closed in  #133
