### ISSUE TITLE
Adding additional info for all type of events in webhooks for bot

### ISSUE THREAD

**Issue by grumpygordon** [chatwoot/chatwoot#970]
**Is your enhancement request related to a problem? Please describe.**
Having ability to check browser version when user is triggering chat for the first time, e.g. not sending any message. Currently there is not a lot of info coming when event `webwidget_triggered` is sent.

**Describe the solution you'd like**
Add all/relevant metainfo to all type of events in case they might be utilized.

**Describe alternatives you've considered**
Trying to send message from bot side to get info about browser version of the user, more like a hack.

**Additional context**
This is a different question, but it's kind of related to additional data for the event `webwidget_triggered`. I assume that no conversation is created until the user sends first message because I don't get `conversation_id` with this  event. But because of that I don't know how to send greet message from the bot side. 

If conversation is indeed not created, I might create it via API if that doesn't ruin chatwoot's system. 
If conversation already exists, then it's id should be included to metadata.

**Comment by sojan-official** [comment]
@grumpygordon  if a conversation already exists we always include it in metadata. Your assumption on the first event is correct. With the current api, if you want to trigger a conversation on `webwidget_triggered` you have to create a conversation before sending the message.  

The dashboard only creates a conversation on the first message from the contact.

**Comment by pranavrajs** [comment]
Moving this to the next sprint as it wouldn't be completed by EOD today.
