### ISSUE TITLE
Add a trial mode with more feature

### ISSUE THREAD

**Issue by tristan-charbonnier** [chatwoot/chatwoot#9701]
### Is your feature or enhancement related to a problem? Please describe.

I tested your product and wanted to know if it matched our needs. My idea was to show it to my boss.
Unfortunately, the settings I wanted to use are not part of the free account (change button label and create a campaign).
It would be great to be able to test the full product for a few days. I don't think multiple agents are needed some for number of messages and conversations, ...

### Describe the solution you'd like

Create a trial mode with most features for a few days.

**Comment by vishnu-narayanan** [comment]
@tristan-charbonnier Hey, please reach out to `sales at chatwoot .com` or use the in-app chat to raise a request.

**Comment by pranavrajs** [comment]
Closing this as the trial option is already available in cloud. All the features expect emails should be working for the first 14 days. If you don't see this working, please reach out to us on in-app chat.
