### ISSUE TITLE
Dyte Integration default username pattern

### ISSUE THREAD

**Issue by tristan-charbonnier** [chatwoot/chatwoot#9702]
### Is your feature or enhancement related to a problem? Please describe.

I tried the Dyte integration. I noticed it generates a random username. Unfortunately, the username can be a little bit weird... especially, if you consider the guest is one of your client: for example, I got "cool-frog-74" 👎 

![image](https://github.com/chatwoot/chatwoot/assets/135015151/5cac97dc-01f7-4ef5-9115-8a7c26b80226)

### Describe the solution you'd like

Be able to setup a pattern for the autogenerated username like "visitor-%d".

**Comment by pranavrajs** [comment]
@tristan-charbonnier This is the random name given to user if the name is not available. This is a very common pattern in most of the products. If you have updated the name of the user on the contact panel, that name would be shown in the integration as well. Let me know if this is not the case. 

Closing this as we will not be picking the custom name generator function soon.
