### ISSUE TITLE
Voice messages sent by admin in Chatwoot received as Mp3 Music file instead of voice memo on Telegram

### ISSUE THREAD

**Issue by ARHAEEM** [chatwoot/chatwoot#9704]
### Describe the bug

When an admin sends a voice message to a user in Chatwoot, the message is received as an Mp3 Music file on Telegram instead of a voice memo. This behavior deviates from the expected functionality where voice messages should be received as voice memos.

![2ByMP6NYrW](https://github.com/chatwoot/chatwoot/assets/63544079/78be0a43-2021-42fe-81c8-a59fe8fe77af)

### To Reproduce

1. Access the Chatwoot platform as an admin.
2. Send a voice message to a user.
3. Have the user receive the message on Telegram.
4. Note that the message is received as an Mp3 Music file instead of a voice memo.

### Expected behavior

The voice message sent by the admin in Chatwoot should be encoded in ogg/opus format to ensure that it is received as a voice memo on Telegram. This alignment with standard voice memo formats will enhance user experience and streamline communication processes.

![image](https://github.com/chatwoot/chatwoot/assets/63544079/e7e2ca00-950b-4639-90e3-f2f6b18fe669)

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 24

### Browser and version

Firefox.

### Docker (if applicable)

Coolify.io Default config.

### Additional context

Just by changing the audio format, this problem can be fixed automatically. Also, using OGG Opus will reduce file sizes. If Chatwoot doesn't have FFMPEG integrated, it's open source and supported everywhere, and can convert the MP3 to OGG/Opus. The rest can be handled by telegram server.

Here's some sources:-
— encoding: https://github.com/vysheng/tg/issues/420#issuecomment-1272116366
— https://core.telegram.org/bots/api#sendvoice

**Comment by pranavrajs** [comment]
@ARHAEEM This is intentional. We have seen the failure rates with opus/ogg getting higher recently. Since there is no explanation on why the audio is not accepted, we have moved it to mp3 recording to make sure that the content is delivered properly. Please see the PR here. https://github.com/chatwoot/chatwoot/pull/9448

**Comment by pranavrajs** [comment]
Closing this as this can't be fixed.
