### ISSUE TITLE
Frontend hot reloading for contributing

### ISSUE THREAD

**Issue by iw4p** [chatwoot/chatwoot#9705]
### Describe the bug

Hi, I am trying to change some UI elements in the frontend codes (Vue). Currently after I am running the project using Procfile.dev which uses forman, I have to wait until [wdm] compiling finished. After each change wdm is going for another compiling and after it ends, I can see the changes (maybe 20-30s).
How can I active hot reloading to save time and see the changes as fast as I can?

### To Reproduce

1. make burn
2. change .env
3. make db
4. foreman start -f Procfile.dev

### Environment

Linux VM

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/9742
