### ISSUE TITLE
Snoozed Until is not working in mobile view

### ISSUE THREAD

**Issue by raya2021** [chatwoot/chatwoot#9707]
### Describe the bug

Snoozed Until is not working in mobile view. While we click the snoozed until in mobile view it is not oping at the same window after we go back to all chats the only it is pop up... While we enter the date time it is not updating. It is working proerly in desktop but not working in mobile view and pwa app.

### To Reproduce

Snoozed Until is not working in mobile view. While we click the snoozed until in mobile view it is not oping at the same window after we go back to all chats the only it is pop up... While we enter the date time it is not updating. It is working proerly in desktop but not working in mobile view and pwa app.

### Expected behavior

Snoozed Until is not working in mobile view. While we click the snoozed until in mobile view it is not oping at the same window after we go back to all chats the only it is pop up... While we enter the date time it is not updating. It is working proerly in desktop but not working in mobile view and pwa app.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by pranavrajs** [comment]
@iamsivin Can you please take a look at this issue?

**Comment by iamsivin** [comment]
> @iamsivin Can you please take a look at this issue?

@pranavrajs Sure, here is the [PR](https://github.com/chatwoot/chatwoot/pull/9717) which will fix this issue.
