### ISSUE TITLE
Cant connect to gmail imap with username and password any more they to use sign in with gmail

### ISSUE THREAD

**Issue by shamar112** [chatwoot/chatwoot#9716]
### Describe the bug

can connect to imap mail channel inbox, google says we should use sign in with google, can we get this option

Changes to Gmail syncing with other email clients

To keep your account more secure, Gmail no longer supports third-party apps or devices which require you to share your Google username and password. Sharing your account credentials with third-parties makes it easier for hackers to gain access to your account.

Instead, look for the option to "Sign in with Google," which is a safer way to sync your mail to other apps. [Learn about Sign in with Google](https://support.google.com/accounts/answer/12849458).

### To Reproduce

add inbox email channel, enter imap settingss for gmail

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 24

**Comment by sojan-official** [comment]
Gmail channel is available in the latest Chatwoot release 

https://github.com/chatwoot/chatwoot/pull/9622

ref: https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/google-workspace-setup
