### ISSUE TITLE
Google Gmail Inbox greyed in 10.2

### ISSUE THREAD

**Issue by cianopman** [chatwoot/chatwoot#9719]
### Describe the bug

Upgrading from 10.1 to 10.2 the new feature for Gmail Ouath2 inbox were grayed out and it can't selected.

### To Reproduce

Linux installation on ubuntu
with google clientid and client secret setted up on .env
upgrading from 10.1 to 10.2 the option to add gmail inbox was greyed.
![immagine](https://github.com/chatwoot/chatwoot/assets/85196476/805146cf-a856-4ae5-883e-7e50b6b8edc7)

### Environment

Linux VM

### Cloud Provider

GCP

### Platform

Browser

### Operating system

ubuntu

**Comment by sojan-official** [comment]
please follow : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/google-workspace-setup

**Comment by cianopman** [comment]
> please follow : https://www.chatwoot.com/docs/self-hosted/configuration/features/email-channel/google-workspace-setup

Hi, it's exacltly what I did but in 3.10.1 the button was clickable when I have upgraded to 3.10.2 It becames unclickable.

**Comment by cianopman** [comment]
Update: after few days the icon became clickable and the oauth2 works fine. Great job.

**Comment by Natotela** [comment]
v3.11.0
Build 8ea412bc85b7ba81d913fe573ca3a543a9157ea4
![image](https://github.com/user-attachments/assets/595609ad-73d5-49b3-a6c0-28472028c6e9)
Still greyed out, V3.11.0, self-hosted.
Any idea how this could "_magically_" become available?
