### ISSUE TITLE
Ability to set first name, last name, nick name on user profile

### ISSUE THREAD

**Issue by pranavrajs** [chatwoot/chatwoot#972]
Currently, we support only a single field to save the agent name, this looks like a bad UX as the end-user in the widget is seeing the full name of the user.

To fix this, split the name to first name and last name, use a nickname field, this would be displayed to the end-user.

#### Acceptance criteria

- Migrate from full name to first name, last name
- Use a public name (nickname) field, use this name on the widget
- On dashboard use nickname, on hover show full name

**Comment by sojan-official** [comment]
we will be retaining full name as it is easier to manage than first name and last name. Since some names could have multiple middle names as well. 
We will be renaming nickname to display name

**Comment by iammattmartin** [comment]
That should work.

Will these variables be exposed to email templates, so we can opt to use either full name or display name as needed?

**Comment by sojan-official** [comment]
@iammattmartin  yes, the variables will be exposed in email templates 

for the first iteration, we will be going in with using display names throughout the platform. But on the dashboard side in the agent's section, the full names will be displayed.

ie.
- full names won't be exposed to customers unless someone doesn't have a display name set or display name is set same as full name 
- in the dashboard, agents would be able to see both display name and full name.

**Comment by iammattmartin** [comment]
Just wanted to add to this, in the 1.7.0 release added on our end.

The "Display Name" also shows on the admin side when I think many would expect to see the full staff name "internally" but the display name "externally".

You may want to show a limited name in public i.e "Matt" but want to show the full name internally to identify the staff member when you have more than one with the same name etc.
