### ISSUE TITLE
Auto Reply to Facebook and Instagram Comments

### ISSUE THREAD

**Issue by mrj0b** [chatwoot/chatwoot#9724]
### Is your feature or enhancement related to a problem? Please describe.

we get a lot of comments on our facebook and instagram pages and it takes alot of time and effort to respond to all of them one by one

### Describe the solution you'd like

it would be nice if we can automate the process of answering all the comments using triggers keywords so every keyword would get a different answer 

### Describe alternatives you've considered

i found another service offers the solution i described its called manychat but we are already using chatwoot and like its workflow

**Comment by pranavrajs** [comment]
Duplicate https://github.com/orgs/chatwoot/discussions/8455
