### ISSUE TITLE
SSO Link loading forever

### ISSUE THREAD

**Issue by ducdang87** [chatwoot/chatwoot#9726]
### Describe the bug

Dear,
I successfully created a SSO link for a user using this api: platform/api/v1/users/{userId}/login. 
The output link look very well: https://chat.shipxanh.com/app/login?email=test3%40test.com\u0026sso_auth_token=***

But when I navigate to this link, it show loading icon forever.

This is my installation details:
Installation Type: Self hosted
Environment: Docker

Thank you so much for your support! 

![image](https://github.com/chatwoot/chatwoot/assets/11603921/e75022b4-3b32-46fd-97c8-dc1b32b0965e)

### To Reproduce

Run with docker compose, build with source tag V3.10.2

### Environment

Docker

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Debian 12

### Browser and version

Chrome

### Docker (if applicable)

Docker Compose version v2.28.1

Client: Docker Engine - Community
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:50 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:50 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.18
  GitCommit:        ae71819c4f5e67bb4d5ae76a6b735f29cc25774e
 runc:
  Version:          1.7.18
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by pranavrajs** [comment]
@ducdang87 There is no information for us to debug this issue. Please share any logs which can help us to look into this further. 
Please share the browser logs while logging in as well as the server logs.

**Comment by linjoe2** [comment]
having the same issue here... 

console log of the page doesnt say anything, just endeless loading...
server side also nothing relevant in the console:
```
rails-1     | I, [2024-10-14T03:53:37.198309 #1]  INFO -- : source=rack-timeout id=46f0646d-dd24-4f20-a966-503ebbd7bd39 timeout=15000ms state=ready
rails-1     | I, [2024-10-14T03:53:37.199241 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39] Started GET "/app/login?email=test4%40test.com%5Cu0026sso_auth_token%3Dac1088601ae5798dbf406e5a76842dd7f66cef3bb7f6a8f74cc698fa9b21ca5f" for 172.16.12.23 at 2024-10-14 03:53:37 +0000
rails-1     | I, [2024-10-14T03:53:37.200804 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39] Processing by DashboardController#index as HTML
rails-1     | I, [2024-10-14T03:53:37.200843 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39]   Parameters: {"email"=>"test4@test.com\\u0026sso_auth_token=ac1088601ae5798dbf406e5a76842dd7f66cef3bb7f6a8f74cc698fa9b21ca5f", "params"=>"login"}
rails-1     | I, [2024-10-14T03:53:37.208858 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39]   Rendered dashboard/index.html.erb within layouts/vueapp (Duration: 0.0ms | Allocations: 4)
rails-1     | I, [2024-10-14T03:53:37.211263 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39]   Rendered layout layouts/vueapp.html.erb (Duration: 2.4ms | Allocations: 2511)
rails-1     | I, [2024-10-14T03:53:37.211651 #1]  INFO -- : [46f0646d-dd24-4f20-a966-503ebbd7bd39] Completed 200 OK in 11ms (Views: 2.9ms | ActiveRecord: 0.0ms | Allocations: 7465)
rails-1     | I, [2024-10-14T03:53:37.212153 #1]  INFO -- : source=rack-timeout id=46f0646d-dd24-4f20-a966-503ebbd7bd39 timeout=15000ms service=14ms state=completed
rails-1     | I, [2024-10-14T03:53:44.779213 #1]  
```

**Comment by linjoe2** [comment]
so the hint i got where the issue was in mine:
```
Parameters: {"email"=>"test4@test.com\\u0026sso_auth_token=ac1088601ae5798dbf406e5a76842dd7f66cef3bb7f6a8f74cc698fa9b21ca5f", "params"=>"login"}
```

it suddenly became aparant that the email and sso_auth_token were not correctly split, replacing '\u0026' with '&' before sending the link to the user solves the issue
