### ISSUE TITLE
Excessive delay in receiving messages from Instagram and Facebook

### ISSUE THREAD

**Issue by laianeramos** [chatwoot/chatwoot#9728]
### Describe the bug

I created the Meta app to connect Facebook and Instagram and it's working almost fine, but messages take a long time to reach Chatwoot. The messages I send from Chatwoot are received almost instantly, but to receive messages on Chatwoot there has been a delay of 30 seconds to 10-15 minutes, or even hours. I talked to other people who are also experiencing the same and this has been happening for a while.

What can I do to fix this?

Here is some information from sidekiq.

### To Reproduce

1. Connect your Facebook and Instagram account to Chatwoot after creating the Meta app;
2. Send a message to the connected chatwoot account

### Expected behavior

send a message to the instagram or facebook account connected to chatwoot

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

ubuntu 20.04

### Browser and version

3.10.2

### Additional context

 Webhooks::InstagramEventsJob 

{"time"=>1720202483035, "id"=>"17841467081173734", "messaging"=>[{"sender"=>{"id"=>"372512955816700"}, "recipient"=>{"id"=>"17841467081173734"}, "timestamp"=>1720202481983, "read"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDY3MDgxMTczNzM0OjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI3NjAxNzQyNzE0MjMyMzAxNjozMTczMjEzNDkxNjk0NTkwMzE0NTkxMjU3NzA4ODgxNTEwNAZDZD"}}]}] | 

NameError: uninitialized constant Webhooks

Webhooks::InstagramEventsJob

[{"time"=>1720202474460, "id"=>"17841467081173734", "messaging"=>[{"sender"=>{"id"=>"372512955816700"}, "recipient"=>{"id"=>"17841467081173734"}, "timestamp"=>1720202474073, "message"=>{"mid"=>"aWdfZAG1faXRlbToxOklHTWVzc2FnZAUlEOjE3ODQxNDY3MDgxMTczNzM0OjM0MDI4MjM2Njg0MTcxMDMwMTI0NDI3NjAxNzQyNzE0MjMyMzAxNjozMTczMjEzNDc5NDIwMTMyMzQxOTY4MTQ0MTc2NDYwNTk1MgZDZD", "text"=>"Tudo bem?"}}]}] 

Name Error: uninitialized constant Webhooks

Webhooks::FacebookEventsJob 

"{\"messaging\":{\"sender\":{\"id\":\"7521931437893866\"},\"recipient\":{\"id\":\"349150891606617\"},\"timestamp\":1720206464975,\"message\":{\"mid\":\"m_GkTcjaeWSk0Yhaa9BHq2zbXZ0BT3iOe8DiEtYzVragxFpUpsE1p_npbRJSIeR4YqyF3myxxvfH5ksPPmivdBgw\",\"text\":\"Oi\"}}}"

Name Error: uninitialized constant Webhooks

Webhooks::FacebookEventsJob	
"{\"messaging\":{\"sender\":{\"id\":\"7521931437893866\"},\"recipient\":{\"id\":\"349150891606617\"},\"timestamp\":1720206464975,\"message\":{\"mid\":\"m_GkTcjaeWSk0Yhaa9BHq2zbXZ0BT3iOe8DiEtYzVragxFpUpsE1p_npbRJSIeR4YqyF3myxxvfH5ksPPmivdBgw\",\"text\":\"Oi\"}}}"
NameError: uninitialized constant Webhooks

**Comment by Liliadetassia** [comment]
O mesmo erro acontece com o meu tbm

**Comment by pranavrajs** [comment]
@laianeramos @Liliadetassia The information provided here is not sufficient to debug this further. Can you please confirm if you have made any changes and any additional information to debug this issue. The logs shared are partial logs, please share the complete logs (take the last couple of minutes logs and send it as a file)

**Comment by laianeramos** [comment]
@pranavrajs @sojan-official do you know what may be causing this and how to solve it?

**Comment by laianeramos** [comment]
> @laianeramos @Liliadetassia The information provided here is not sufficient to debug this further. Can you please confirm if you have made any changes and any additional information to debug this issue. The logs shared are partial logs, please share the complete logs (take the last couple of minutes logs and send it as a file)


@pranavrajs  Here's some logs, let me know if you need anything else. Thank you

[_chatwoot_nestor_chatwoot_sidekiq.txt](https://github.com/user-attachments/files/16128653/_chatwoot_nestor_chatwoot_sidekiq.txt)
[_chatwoot_nestor_chatwoot_app.1.ia1d6g1q3z7tkexnnk9mgfhlz_logs.txt](https://github.com/user-attachments/files/16128585/_chatwoot_nestor_chatwoot_app.1.ia1d6g1q3z7tkexnnk9mgfhlz_logs.txt)
[_chatwoot_nestor_chatwoot_sidekiq.1.lt6h05r2ifam92izc1yhs9fhk_logs.txt](https://github.com/user-attachments/files/16128587/_chatwoot_nestor_chatwoot_sidekiq.1.lt6h05r2ifam92izc1yhs9fhk_logs.txt)

**Comment by laianeramos** [comment]
@pranavrajs And here's some logs from another installation that works perfectly

[_chatwoot_nestor_chatwoot_app.1.4r921fvvqqq68nn6pe12on98g_logs (1).txt](https://github.com/user-attachments/files/16128872/_chatwoot_nestor_chatwoot_app.1.4r921fvvqqq68nn6pe12on98g_logs.1.txt)
[_chatwoot_nestor_chatwoot_sidekiq.1.g7tqho5d31g8ai97liqwe1qsj_logs (1).txt](https://github.com/user-attachments/files/16128873/_chatwoot_nestor_chatwoot_sidekiq.1.g7tqho5d31g8ai97liqwe1qsj_logs.1.txt)

**Comment by laianeramos** [comment]
@pranavrajs I solved it. There is no error (apparently), but the queue priority for Instagram and Facebook webhooks was set as default in the `facebook_events_job.rb` and `instagram_events_job.rb` files, so I changed it to high and now it is working perfectly. Is there a problem to keep it on high or should I change it to medium?
```ruby
class Webhooks::FacebookEventsJob < MutexApplicationJob
  queue_as :default
``` 
to

```ruby
class Webhooks::FacebookEventsJob < MutexApplicationJob
  queue_as :high
``` 
and 

```ruby
class Webhooks::InstagramEventsJob < MutexApplicationJob
  queue_as :default
``` 
to

```ruby
class Webhooks::InstagramEventsJob < MutexApplicationJob
  queue_as :high
```

**Comment by pranavrajs** [comment]
@laianeramos Adding more workers seems to be the solution here. As I understand, you are just experiencing a slow execution of jobs which means that the number of workers is not sufficient. Can you try adding more number of worker threads? 

Can you also check what is clogging up the Sidekiq job queue?

**Comment by laianeramos** [comment]
@pranavrajs to add more number of worker threads, i must set this variable to a higher number? can you recomend a number for me to set?
```
# the default value in Chatwoot is 10 
SIDEKIQ_CONCURRENCY=10
```
or this one?
```
# Only required to configure if absolutely necessary
# Defaults to Max threads value by default
# RAILS_MIN_THREADS=5
RAILS_MAX_THREADS=5
```
or both? or is something else?
Ref: https://www.chatwoot.com/docs/self-hosted/deployment/performance/optimizing-configurations/

About the Sidekiq job queue, I think that's the "remove_duplicate_notification_job" and "push_notification_job" because the same thing happens to them, they get stuck on retries frequently and are at the sidekiq default queue job too. How can I check this information?

**Comment by pranavrajs** [comment]
@laianeramos No, this is related to concurrency. Are you using a Linux Instance or docker? 

> About the Sidekiq job queue, I think that's the "remove_duplicate_notification_job" and "push_notification_job" because the same thing happens to them, they get stuck on retries frequently and are at the sidekiq default queue job too. How can I check this information?

@sojan-official Do we need these two job having same priority as the incoming message hooks? @muhsin-k 


Also, I've noted we don't have a command to increase the number of workers using cwctl. @vishnu-narayanan Can we support this? Something like multiple instances of same services as mentioned [here](https://www.stevenrombauts.be/2019/01/run-multiple-instances-of-the-same-systemd-unit/).

**Comment by laianeramos** [comment]
@pranavrajs I’m using docker

**Comment by pranavrajs** [comment]
@laianeramos You could use the replica feature for the sidekiq. Please refer to this [here](https://docs.docker.com/compose/compose-file/deploy/#replicas).

I'll close this for now as the issue would be resolved when there are more Sidekiq workers to process the jobs.
