### ISSUE TITLE
Update contact custom_attributes via API does not work

### ISSUE THREAD

**Issue by souzagaabriel** [chatwoot/chatwoot#9729]
### Describe the bug

Using this endpoint https://www.chatwoot.com/developers/api/#tag/Contacts/operation/contactUpdate
and setting to change custom_attributes the value does not change.

### To Reproduce

Send PUT with custom_attributes in endpoint https://www.chatwoot.com/developers/api/#tag/Contacts/operation/contactUpdate 

### Environment

app.chatwoot.com

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

**Comment by pranavrajs** [comment]
@souzagaabriel Please share the payload and the expected response. We will not be able to debug this further without this information.

**Comment by souzagaabriel** [comment]
Request payload:

{
    "headers": {
        "api_access_token": "XXX",
        "accept": "application/json,text/html,application/xhtml+xml,application/xml,text/*;q=0.9, image/*;q=0.8, */*;q=0.7"
    },
    "method": "PUT",
    "uri": "https://chatwoot.qualsistema.com.br/api/v1/accounts/13/contacts/75215",
    "gzip": true,
    "rejectUnauthorized": true,
    "followRedirect": true,
    "resolveWithFullResponse": true,
    "followAllRedirects": true,
    "timeout": 300000,
    "body": {
        "custom_attributes": "{\n\"adiar\": \nfalse\n}",
        "email": "teste3@testew.com"
    },
    "encoding": null,
    "json": false,
    "useStream": true
}



Response:
[
  {
    "payload": {
      "additional_attributes": {},
      "availability_status": "offline",
      "email": "teste3@testew.com",
      "id": 75215,
      "name": "Gabriel De Souza",
      "phone_number": "+XX",
      "identifier": "XX@s.whatsapp.net",
      "thumbnail": "https://chatwoot.qualsistema.com.br/rails/active_storage/representations/redirect/XXX.jpg",
      "custom_attributes": {
        "adiar": true
      },
      "last_activity_at": 1720197890,
      "created_at": 1717713571,
      "contact_inboxes": [
        {...}
        }
      ]
    }
  }
]


Some data was hidden with XX.

When I went to generate the payloads I found my error. I was sending the custom_attributes as a string and I didn't realize it because I was testing with n8n. Sending it this way as in the request example, it ignores the information sent in custom_attributes and does not notify anything, as we can see in the output that the "adiar" attribute remained the same as true and did not change to false while the email was modified.

**Comment by pranavrajs** [comment]
> When I went to generate the payloads I found my error. I was sending the custom_attributes as a string and I didn't realize it because I was testing with n8n. Sending it this way as in the request example, it ignores the information sent in custom_attributes and does not notify anything.

Thanks for the information. I guess the validation omits the one that are not valid. I don't think anything else is needed over here for the time being.
