### ISSUE TITLE
Add SLAs to Reports (% SLAs met)

### ISSUE THREAD

**Issue by svenbergfeld-ti8m** [chatwoot/chatwoot#9747]
### Is your feature or enhancement related to a problem? Please describe.

Our client needs reporting on how reliable their agents are able to act within response times as defined in the SLA in Chatwoot.
The company sets a global SLA (e.g. 'first response time should be less than 30 seconds'). Supervisors want to understand hoe many times team members are able to actually reply within these 30 seconds.

### Describe the solution you'd like

Per conversation, the system shall record if the First Response Time (FRT), Next Response Time (NRT), and Resolution Time (RT) was within the bounds as defined in the global SLA. Then, the system sall calculate
- the proportion "conversations where an agent **first** responded within the bounds as defined in the global SLA" / "All conversations"
- the proportion "conversations where an agent **next** responded within the bounds as defined in the global SLA" / "All conversations"
- the proportion "conversations where an agent marked the conversation as resolved within the bounds as defined in the global SLA" / "All conversations"

These 3 values shall be availbale on a per agent, per team and overall number.
All values should be available in the webapp and csv-export.

### Describe alternatives you've considered

I believe given the SLA implementation in Chatwoot and our clients need for reporting of the SLAs, there is no alternative that better integrates with the components already implemented in Chatwoot.

### Additional context

Our company, ti&m AG, is willing to implement this feature for the Chatwoot project, to make it available to our client.

**Comment by pranavrajs** [comment]
<img width="1192" alt="Screenshot 2024-08-02 at 1 01 38 AM" src="https://github.com/user-attachments/assets/f9a6ec10-f226-4f21-99f8-10d0313565d2">


@svenbergfeld-ti8m Please upgrade to the enterprise plan you should see the reports. This is already available.
