### ISSUE TITLE
Web Desktop notifications not working on Brave Broser

### ISSUE THREAD

**Issue by BrOrlandi** [chatwoot/chatwoot#9754]
### Describe the bug

When I try to enable push notifications using Brave Browser it shows the error alert saying: `This browser does not support desktop notification`.
I'm using Chatwoot V3.10.2 self hosted. It works on other browsers like Safari and Arc Browser. 
Tried on Brave using Mac OS and Linux, both has the same behavior.

![CleanShot 2024-07-10 at 13 57 42](https://github.com/chatwoot/chatwoot/assets/1594658/6e2c5c52-0dba-435b-8bbb-275c65eefe10)

### To Reproduce

1. Using Brave Browser, open chatwoot self hosted.
2. Go to Profile Settings
3. Go to Notifications Preferences
4. Click to Enable push notifications in your browser.
5. The toggle will not enable and will show the alert `This browser does not support desktop notification`

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

Mac OS / Linux

### Browser and version

Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)

**Comment by pranavrajs** [comment]
@BrOrlandi Under the browser privacy settings there is an option to "Use Google services for push messaging", please enable it and restart the browser. 

<img width="730" alt="Screenshot 2024-07-10 at 2 39 08 PM" src="https://github.com/chatwoot/chatwoot/assets/2246121/3d186bd7-f553-4f51-8a43-132f94f0870d">

**Comment by BrOrlandi** [comment]
It works! Thanks a lot, I didn't know that about Brave.
