### ISSUE TITLE
Playback of audio files from Facebook and Instagram not working

### ISSUE THREAD

**Issue by matteoerrera** [chatwoot/chatwoot#9755]
### Describe the bug

Updating from version 3.6.0 to version 3.10.2, I started encountering the following issue.
All incoming voice messages from Facebook and Instagram stopped working:
<img width="325" alt="Screenshot 2024-07-10 at 23 35 15" src="https://github.com/chatwoot/chatwoot/assets/12599244/22c7cb7c-614b-46da-8bb6-1a37bd1f099f">

Analyzing the content of the player, the URL is as follows:
`https://cdn.fbsbx.com/v/t59.3654-21/450362669_3770332926619624_4766029817055351038_n.mp4/audioclip-1720643521000-5294.mp4?_nc_cat=102&ccb=1-7&_nc_sid=d61c36&_nc_ohc=EQeRZofgAdIQ7kNvgEVOnzd&_nc_ht=cdn.fbsbx.com&oh=03_Q7cD1QG7aiSC_Wo2XrXZqx3Pb4Mz5I6TVT3xsGCZVlvbYoyGjA&oe=6690E15E?t=1720647120515`

Analyzing the payload that arrives from the webhook configured on the Facebook Developer Console, I noticed a slight difference:

`https://cdn.fbsbx.com/v/t59.3654-21/450362669_3770332926619624_4766029817055351038_n.mp4/audioclip-1720643521000-5294.mp4?_nc_cat=102&ccb=1-7&_nc_sid=d61c36&_nc_ohc=EQeRZofgAdIQ7kNvgEVOnzd&_nc_ht=cdn.fbsbx.com&oh=03_Q7cD1QG7aiSC_Wo2XrXZqx3Pb4Mz5I6TVT3xsGCZVlvbYoyGjA&oe=6690E15E`

The parameter "?t=1720647120515" is missing.
The issue seems to be due to Chatwoot appending the parameter using "?" instead of "&".

In the second case, the audio works, while in the first case, opening the URL shows the "Bad URL timestamp" error.

### To Reproduce

Using Chatwoot 3.10.2:

1. associate a Facebook page;
2. send a voice message to the Facebook page;
3. attempt to play the voice message.

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

Browser

### Operating system

All

### Browser and version

All

**Comment by pranavrajs** [comment]
Closing this via https://github.com/chatwoot/chatwoot/pull/9957
