### ISSUE TITLE
I keep getting messages from John Doe even after verifying the app with Facebook

### ISSUE THREAD

**Issue by matteoerrera** [chatwoot/chatwoot#9758]
### Describe the bug

I have set up my application on Meta Developer and have therefore successfully hooked up both the Instagram channel and the Facebook channel.

On Instagram I have no problems (user names appear correctly) however on Facebook even after getting the application approved, John Doe still appears.

From the Chatwoot documentation the following permissions are required

```
pages_messaging
pages_show_list
pages_manage_metadata
business_management
pages_read_engagement
```

pages_messaging was successfully approved.

All these other permissions instead:
```
pages_show_list
pages_manage_metadata
business_management
pages_read_engagement
```
I couldn't get them approved but I actually only need to hook one page to Chatwoot, so if my Facebook user is enabled as a developer, I can proceed with the hook (already done) even without having these permissions.

Theoretically, according to what I read in Meta's documentation, the pages_messaging (validated) permission should be sufficient to display the first and last name of users who send messages, so I don't understand where the problem lies.

### To Reproduce

- Hook up a Facebook page;
- Checking the app for pages_messaging permission
- Send a message to the page from a non-app user

### Expected behavior

The user's full name should appear

### Environment

Docker

### Cloud Provider

DigitalOcean

### Platform

None

**Comment by laianeramos** [comment]
Advanced permission to pages_manage_metadata is required even if you use the app only for your own account, that’s why you don’t receive contacts information (name and profile picture).

**Comment by matteoerrera** [comment]
Thanks for your feedback @laianeramos.
However, I found the solution.

The missing permission was `Business Asset User Profile Access` adding this solved the problem.
So right now I'm using the `pages_messaging` and `Business Asset User Profile Access` permissions and everything is working properly.

I think an update of the documentation is needed.

**Comment by laianeramos** [comment]
@matteoerrera yes, this two permission give access to user information. If I'm not wrong, pages_read_engagement too.

**Comment by matteoerrera** [comment]
> pages_read_engagement

Hi @laianeramos, I am not using this permission at the moment and everything seems to be working properly :)

**Comment by laianeramos** [comment]
> > pages_read_engagement
> 
> 
> 
> Hi @laianeramos, I am not using this permission at the moment and everything seems to be working properly :)

Me neither, I just said this permission give access to user information too :)

**Comment by ycarooliveira** [comment]
@laianeramos can you send me what you said to meta for each permission? I'm having half of them denied =/

**Comment by laianeramos** [comment]
@ycarooliveira sure! but it is in portuguese, are you brazilian?

**pages_manage_metadata:** Conte para nós como você está usando essa permissão ou recurso.
Essa permissão servirá para integrar o Messenger e Instagram ao nosso site para que nós possamos acessar as mensagens enviadas e recebidas, assim como recebê-las e respondê-las através do nosso app de mensagens, bem como as reações, edições e mensagens deletadas, através de webhooks.

**pages_messaging:** Conte para nós como você está usando essa permissão ou recurso.
Essa permissão servirá para conectar o Messenger para que nós possamos acessar as mensagens enviadas e recebidas, assim como recebê-las e respondê-las através do nosso app de mensagens e assim poder melhorar o nosso processo de recepção de solicitações de suporte e de serviços dos nossos clientes e melhorar o nosso processo de interação com nossos seguidores em geral.

**instagram_manage_messages:** Conte para nós como você está usando essa permissão ou recurso.
Essa permissão servirá para conectar o Instagram para acessarmos as mensagens enviadas e recebidas, assim como recebê-las e respondê-las através do nosso app de mensagens e assim poder melhorar o nosso processo de recepção de solicitações de suporte e de serviços dos nossos clientes e melhorar o nosso processo de interação com nossos seguidores em geral.

**Human Agent:** Conte para nós como você está usando essa permissão ou recurso.
Isso permitirá responder aos contatos após a janela de 24h através de atendentes humanos

As demais permissões, como pages_show_list, business_management e pages_read_engagement, não são necessárias caso você esteja fazendo o app somente para a sua página. Se quiser que outras pessoas conectem o instagram e facebook no seu chatwoot, é preciso solicitar essas permissões também.
Eu consegui a pages_show_list e business_management com as solicitações abaixo, mas nunca consegui aprovação de pages_read_engagement e acho que ela não é necessária ou pode ser substituída pela permissão Business Asset User Profile Access.

**pages_show_list:** Conte para nós como você está usando essa permissão ou recurso.
Essa permissão servirá para mostrar a lista de páginas que o usuário gerencia para que ele possa escolher qual conectar para acessar as mensagens através do nosso app de mensagens. 

**business_management:** Conte para nós como você está usando essa permissão ou recurso.
Essa permissão servirá para mostrar a lista de páginas/ativos que a empresa gerencia e permitir escolher qual quer conectar.

**Comment by ycarooliveira** [comment]
@laianeramos sim sou, por isso pedi ajuda sua xD, muito obrigado.

**Comment by laianeramos** [comment]
@ycarooliveira eu também não, rsrs no meu app não foi preciso, mas uso só para a minha empresa, não conecto outras contas
