### ISSUE TITLE
Widget font (Inter) lacks support for latin-extended characters

### ISSUE THREAD

**Issue by blazejstarosta** [chatwoot/chatwoot#9762]
### Describe the bug

The "Inter" font used by the widget lacks the support of latin-extended characters, which results in such characters showing in a different, smaller font. Polish characters, like "ą", "ę", "ł", "ż", "ś" are all displayed incorrectly and stand out. 

![image](https://github.com/chatwoot/chatwoot/assets/60388097/24efa573-2cdc-45f6-9afd-788a7f28b340)

### To Reproduce

Just open the widget in Polish language.

### Expected behavior

The letters should be of the same font. Either the Inter font has to be updated with extended character support or there should be an option in the settings to use fallback font? 

### Environment

Docker

### Cloud Provider

None

### Platform

None

**Comment by sojan-official** [comment]
cc: @pranavrajs

**Comment by pranavrajs** [comment]
We could use the latest Inter fonts, which should solve the issue. The size of the font is huge, so we went with a limited set. I understand the issue as rendering would be awkward. I will see if we can always switch the widget to system-ui, then Inter.

**Comment by pranavrajs** [comment]
The font files are updated with the latest version of Inter font from rsms.me. Earlier, we had selected a subset of the ligatures to reduce the font file size, doesn't makes sense to continue as we have wider audience.
