### ISSUE TITLE
Browser Push Notifications don't work

### ISSUE THREAD

**Issue by janik-sauerbier** [chatwoot/chatwoot#9763]
### Describe the bug

I'm not able to get Browser Push Notifications on self-hosted environment. I do get the notifications in the mobile app. I checked, and it's not because of my browser settings. 

Furthermore, I tried it with my own generated Vapid Key and I also tried it without setting them (VAPID_PUBLIC_KEY and VAPID_PRIVATE_KEY).

I get the following error logs, maybe that shows something.

> 2024-07-11T12:29:46.777358+00:00 app[worker.1]: E, [2024-07-11T12:29:46.777293 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.785696+00:00 app[worker.1]: E, [2024-07-11T12:29:46.785645 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.793726+00:00 app[worker.1]: E, [2024-07-11T12:29:46.793683 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.801728+00:00 app[worker.1]: E, [2024-07-11T12:29:46.801687 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.809653+00:00 app[worker.1]: E, [2024-07-11T12:29:46.809609 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.817084+00:00 app[worker.1]: E, [2024-07-11T12:29:46.817044 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.824822+00:00 app[worker.1]: E, [2024-07-11T12:29:46.824784 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)
> 2024-07-11T12:29:46.832763+00:00 app[worker.1]: E, [2024-07-11T12:29:46.832720 #2] ERROR -- : [ActiveJob] [Notification::PushNotificationJob] [db340a6f-864f-4e47-8504-9c0432186ee5] wrong number of arguments (given 1, expected 0; required keyword: endpoint)

### To Reproduce

Version 3.10.1
Hosted on Heroku

### Expected behavior

See Browser Notifications

### Environment

Heroku

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Mac OS

### Browser and version

Chrome 126.0.6478.127 (Official Build) (arm64)

**Comment by pranavrajs** [comment]
@janik-sauerbier This is already fixed in 3.10.2. Please update the version.

https://github.com/chatwoot/chatwoot/releases/tag/v3.10.2
