### ISSUE TITLE
message scheduling

### ISSUE THREAD

**Issue by suporteflowchatt** [chatwoot/chatwoot#9771]
### Is your feature or enhancement related to a problem? Please describe.

no

### Describe the solution you'd like

If you would like to implement the function of scheduling messages, the idea would be to have a button next to the send messages button so that you can select the data and time you would like that message to be sent, this makes it much easier to contact a customer who asked to send messages on another day or time

### Describe alternatives you've considered

button to schedule message

### Additional context

If you would like to implement the function of scheduling messages, the idea would be to have a button next to the send messages button so that you can select the data and time you would like that message to be sent, this makes it much easier to contact a customer who asked to send messages on another day or time

**Comment by laianeramos** [comment]
This is very useful and very important. Sometimes we need to contact customers or leads at future dates, with this function we could already schedule the message to be sent on a pre-established day and time, saving time and avoiding forgets. This improves the quality of the company's service and the team's productivity. its a win win

**Comment by laianeramos** [comment]
https://github.com/chatwoot/chatwoot/issues/9484

**Comment by sojan-official** [comment]
closing in favor of https://github.com/chatwoot/chatwoot/issues/9484
