### ISSUE TITLE
Markup / Styling of outbound messages

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#978]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
To provide an enhanced user experience, it would be helpful to be able to make text **bold**, _italic_, underlined, even [linked to other content](#), as well as lists and `maybe code`. Essentially standard markdown support.

**Comment by pranavrajs** [comment]
@iammattmartin We support links right now. If you paste http/https link, it will be detected automatically. Rest of the rich content support will be available when the email channel is available.

**Comment by iammattmartin** [comment]
Thanks.

In regard to links, I mean over and above that in that formatting texts to links instead of just showing the raw link. Just a better user experience.

**Comment by pranavrajs** [comment]
<img width="363" alt="Screenshot 2020-06-26 at 1 32 27 PM" src="https://user-images.githubusercontent.com/2246121/85834717-7d72ee80-b7b1-11ea-8fb2-36934fa36f1b.png">

This is the current message bubble UI. Are you suggesting something like a preview of the link as shown below? 
<img width="530" alt="Screenshot 2020-06-26 at 1 34 14 PM" src="https://user-images.githubusercontent.com/2246121/85834872-bdd26c80-b7b1-11ea-8672-ebb4374b0339.png">

**Comment by iammattmartin** [comment]
Link previews could work if there was only ONE link but if there were many, which we want to build in to content. i.e a set of instructions, being able to put a link specific to text (which would be `<a href="link">text for link</a> would be better.

**Comment by pranavrajs** [comment]
Oh! Okay, that comes down to the availability of a rich content editor. We will make that available soon along with email channel.

**Comment by pranavrajs** [comment]
Moving this to the next milestone as it is not complete.

**Comment by pranavrajs** [comment]
@nithindavid Please take a look at the https://www.npmjs.com/package/marked package to see if we can make use of this. 

Things to note if we are support markdown instead of HTML editor, we would need to see how we can render the content in emails and in the external channels like FB or Twitter.

**Comment by pranavrajs** [comment]
Closed via #1657
