### ISSUE TITLE
Images and files messages: client receive it, but its still red in chatwoot (time out reading data for server)

### ISSUE THREAD

**Issue by idealprint** [chatwoot/chatwoot#9785]
### Describe the bug

every time when send a message of file or image, we get this error:
![image](https://github.com/user-attachments/assets/86834299-2ef5-434e-a2ba-bbc08ef74508)
Timed out reading data for server

But in whatsapp, the message with image/files appears normally to user.
![image](https://github.com/user-attachments/assets/9202af5a-0d46-4f6d-8af0-7688b4b3f64f)

### To Reproduce

send a file or image via chatwoot in whatsapp channel

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 22.04

**Comment by andersonlemesc** [comment]
I have the same problem, in all cases the message is sent, but chatwoot marks it as a sending error, when I click on reprocess the message turns blue (sent).

**Comment by sojan-official** [comment]
@idealprint, you seem to be using an API inbox with a custom WhatsApp provider. Please double-check with the integration provider. Feel free to reopen this if the issue is with the official meta WhatsApp API channel, which Chatwoot supports.
