### ISSUE TITLE
Installation Failed - Ruby version mismatch?

### ISSUE THREAD

**Issue by rolymaz** [chatwoot/chatwoot#9789]
### Describe the bug

When installing chatwoot on a brand new unbuntu instance, the installer failed. 

Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
Synchronizing state of postgresql.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable postgresql
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
Already installed ruby-3.2.2.
To reinstall use:

    rvm reinstall ruby-3.2.2

Using /usr/local/rvm/gems/ruby-3.2.2
fatal: destination path 'chatwoot' already exists and is not an empty directory.
Required ruby-3.3.3 is not installed.
To install do: 'rvm install "ruby-3.3.3"'
Already on 'master'
Your branch is up to date with 'origin/master'.
Your Ruby version is 3.2.2, but your Gemfile specified 3.3.3
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 0.93s.
rake aborted!
Bundler::RubyVersionMismatch: Your Ruby version is 3.2.2, but your Gemfile specified 3.3.3
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/definition.rb:443:in `validate_ruby!'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/definition.rb:418:in `validate_runtime!'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler.rb:158:in `setup'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/setup.rb:32:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/ui/shell.rb:159:in `with_level'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/ui/shell.rb:111:in `silence'
/usr/local/rvm/gems/ruby-3.2.2/gems/bundler-2.5.14/lib/bundler/setup.rb:32:in `<top (required)>'
<internal:/usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/rvm/rubies/ruby-3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/chatwoot/chatwoot/config/boot.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/config/application.rb:3:in `require_relative'
/home/chatwoot/chatwoot/config/application.rb:3:in `<top (required)>'
/home/chatwoot/chatwoot/Rakefile:4:in `require_relative'
/home/chatwoot/chatwoot/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

Log file below

[Chatwoot-setup.log](https://github.com/user-attachments/files/16262600/Chatwoot-setup.log)

### To Reproduce

Retried the installer - same error

### Expected behavior

should install

### Environment

Linux VM

### Cloud Provider

Azure

### Platform

Browser

### Operating system

Linux (ubuntu 20.04)

**Comment by rolymaz** [comment]
I was able to fix this by manually installing ruby 3.3.3 using this guides: 

(not a linux expert - so i'm unsure whether i've done this correctly)

https://rvm.io/rvm/install

https://github.com/rvm/ubuntu_rvm

https://github.com/rvm/ubuntu_rvm/issues/15

**Comment by sojan-official** [comment]
@rolymaz  are you using cwctl for the installation ?

**Comment by rolymaz** [comment]
No, I used the ./Install.sh“”On 17 Jul 2024, at 23:12, Sojan Jose ***@***.***> wrote:﻿
@rolymaz  are you using cwctl for the installation ?

**Comment by sojan-official** [comment]
please use cwctl for managing installs 
https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl/

**Comment by vishnu-narayanan** [comment]
@rolymaz Chatwoot `v3.11` requires `ruby-3.3.3`. The installation script must have been referring to the old version when you tried to install.

I have verified the script now and it is set to install `3.3.3`. If you try this on a fresh installation, it should install `3.3.3` by default and successfully complete installation.

**Comment by rolymaz** [comment]
Thank you,

Here is the documentation I followed:

https://www.chatwoot.com/docs/self-hosted/deployment/linux-vm

It clearly says I should use ./Install.sh.  Please can you update the documentation so that others can avoid making the same mistake

This documenation, does not explain clearly how to use ctwl to install a new instance, I suggest you update this too:

https://www.chatwoot.com/docs/self-hosted/deployment/chatwoot-ctl/

**Comment by vishnu-narayanan** [comment]
@rolymaz You are right. It should be `./install.sh`, which is `cwctl` under the hood. Since you seem to have resolved the issue, I am closing this. 

Please reopen if you need help with this.
