### ISSUE TITLE
docker upgrade from version 2.8.1 to latest fails 

### ISSUE THREAD

**Issue by pritishpattanaik** [chatwoot/chatwoot#9795]
### Describe the bug

Hi, 

We are running chatwoot version 2.8.1 on docker container.  When we try to upgrade to the latest version, it failed on the upgrade. Now we are stuck, how to proceed for the migration. 

OS: Ubuntu 
Deployment: Docker 
Version: 2.8.1 

Step 1: $docker compose down 
Step 2: $docker compose pull # we have changed the image tag to latest 
Step 3: $docker compose up -d # we can see the version is upgraded in the app side 
Step 4: docker exec -it $(basename $(pwd))-rails-1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'

This failed with below error 
--------------------------

[root@sn3ylvx1b0005 chatwoot]# docker compose ps 
WARN[0000] /opt/chatwoot/docker-compose.yaml: `version` is obsolete 
NAME                  IMAGE                      COMMAND                  SERVICE    CREATED         STATUS         PORTS
chatwoot-postgres-1   postgres:12                "docker-entrypoint.s…"   postgres   4 minutes ago   Up 4 minutes   0.0.0.0:5432->5432/tcp
chatwoot-rails-1      chatwoot/chatwoot:latest   "docker/entrypoints/…"   rails      4 minutes ago   Up 4 minutes   3000/tcp, 0.0.0.0:3005->3005/tcp, :::3005->3005/tcp
chatwoot-redis-1      redis:alpine               "docker-entrypoint.s…"   redis      4 minutes ago   Up 4 minutes   127.0.0.1:6379->6379/tcp
chatwoot-sidekiq-1    chatwoot/chatwoot:latest   "bundle exec sidekiq…"   sidekiq    4 minutes ago   Up 4 minutes   3000/tcp
[root@sn3ylvx1b0005 chatwoot]# docker exec -it $(basename $(pwd))-rails-1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'
/gems/ruby/3.3.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /usr/local/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.4 to add mutex_m into its gemspec.
DEPRECATION WARNING: Dotenv::Railtie is deprecated! Use Dotenv::Rails instead. (called from <main> at /app/config/application.rb:14)
I, [2024-07-18T04:58:59.720794 #99]  INFO -- : Migrating to InitSchema (20230426130150)
== 20230426130150 InitSchema: migrating =======================================
-- enable_extension("pg_stat_statements")
   -> 0.0570s
-- enable_extension("pg_trgm")
   -> 1.6068s
-- enable_extension("pgcrypto")
   -> 0.0085s
-- enable_extension("plpgsql")
   -> 0.0073s
-- create_table("access_tokens")
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled: (StandardError)

PG::DuplicateTable: ERROR:  relation "access_tokens" already exists
/app/db/migrate/20230426130150_init_schema.rb:8:in `up'
/app/lib/tasks/db_enhancements.rake:26:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "access_tokens" already exists (ActiveRecord::StatementInvalid)
/app/db/migrate/20230426130150_init_schema.rb:8:in `up'
/app/lib/tasks/db_enhancements.rake:26:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'

Caused by:
PG::DuplicateTable: ERROR:  relation "access_tokens" already exists (PG::DuplicateTable)
/app/db/migrate/20230426130150_init_schema.rb:8:in `up'
/app/lib/tasks/db_enhancements.rake:26:in `block (3 levels) in <main>'
/app/lib/tasks/db_enhancements.rake:18:in `each'
/app/lib/tasks/db_enhancements.rake:18:in `block (2 levels) in <main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

### To Reproduce

# install version 2.8.1 with docker compose tag 
# docker compose pull 
# docker compose run --rm rails bundle exec rails db:chatwoot_prepare 
# docker compose up -d 

Upgrade to latest version ( 3.11) 

Step 1: $docker compose down 
Step 2: $docker compose pull # we have changed the image tag to latest 
Step 3: $docker compose up -d # we can see the version is upgraded in the app side 
Step 4: docker exec -it $(basename $(pwd))-rails-1 sh -c 'RAILS_ENV=production bundle exec rails db:chatwoot_prepare'

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 

### Docker (if applicable)

Docker version 26.1.4, build 5650f9b
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

**Comment by vishnu-narayanan** [comment]
@pritishpattanaik Upgrading from 2.8 to 3.11 is not recommended as it includes around 20+ releases in between. Please try upgrading one by one or at lease within 2-3 releases.

**Comment by pritishpattanaik** [comment]
Noted with thanks @vishnu-narayanan, will folllow this step.

**Comment by sfhmi** [comment]
hi @pritishpattanaik i run into the same problem, have you solve the issue? if its so, i wanna know how you fix the issue, thank you

**Comment by pritishpattanaik** [comment]
@sfhmi - Yes we have done the incremental version upgrade from 2.8.1 to 3.11, Below is the sample script we prepared. 

`echo 'Starting Migration'
echo 'make sure you use correct postgresqlt image name'
docker exec -i chatwoot-postgres-1 pg_dump -U postgres -d chatwoot_production > chatwoot_production.sql
echo 'DB dump completed'
echo 'incremental versions upgrade,  we are on V2.8.1'
declare -a arr=("v2.12.0" "v2.17.0" "v3.2.0" "v3.7.0" "v3.11.0")
echo 'now loop through the above array'
for i in "${arr[@]}"
do
    echo "$i"
    sed -i "s|chatwoot/chatwoot:[^ ]*|chatwoot/chatwoot:$i|g" docker-compose.yaml

    echo 'use docker-compose command in case you are running old docker version' 
    docker compose down 
    docker compose pull 
    docker compose up -d

    echo "Running migration ${i}"
    docker compose run --rm rails bundle exec rails db:chatwoot_prepare

    echo 'remove previous images to free the disk space'

    sleep 5
done
echo 'Migration Completed'`
