### ISSUE TITLE
SSL Certificate Invalid and "Nothing here yet :/" Message for Password Reset Link

### ISSUE THREAD

**Issue by hnmendes** [chatwoot/chatwoot#9808]
### Describe the bug

I've deployed the Chatwoot application using CapRover. The setup seems correct, and HTTPS is functioning. However, when a new agent receives an email to set up their account and clicks on the link, they are redirected to a page showing "Nothing here yet :/" with an invalid SSL certificate warning.

### To Reproduce

1. Deploy Chatwoot on CapRover.
2. Ensure that HTTPS is set up and functioning properly.
3. Invite a new agent to create an account, which sends an email.
4. Click on the password reset link in the email, e.g., https://mydomain.com/app/auth/password/edit?reset_password_token=userToken

### Expected behavior

The user should be redirected to a secure page where they can reset their password without any SSL certificate errors.

### Platform

Browser

### Additional context

Here is my current NGINX configuration for mydomain.com:

```
<%
if (s.forceSsl) {
%>
    server {

        listen       80;

        server_name  <%-s.publicDomain%>;

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }

        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        location / {
            return 302 https://$http_host$request_uri;
        }
    }
<%
}
%>


server {

    <%
    if (!s.forceSsl) {
    %>
        listen       80;
    <%
    }
    if (s.hasSsl) {
    %>
        listen              443 ssl http2;
        ssl_certificate     <%-s.crtPath%>;
        ssl_certificate_key <%-s.keyPath%>;
    <%
    }
    %>

        client_max_body_size 500m;
        underscores_in_headers on;
        server_name  <%-s.publicDomain%>;

        resolver 127.0.0.11 valid=10s;
        set $upstream http://<%-s.localDomain%>:<%-s.containerHttpPort%>;

        location / {

        <%
        if (s.redirectToPath) {
        %>
            return 302 <%-s.redirectToPath%>;
        <%
        } else {
        %>

            <%
            if (s.httpBasicAuthPath) {
            %>
                auth_basic           "Restricted Access";
                auth_basic_user_file <%-s.httpBasicAuthPath%>; 
            <%
            }
            %>

                proxy_pass $upstream;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

            <%
            if (s.websocketSupport) {
            %>
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
            <%
            }
            %>

        <%
        }
        %>

        }

        # Used by Lets Encrypt
        location /.well-known/acme-challenge/ {
            root <%-s.staticWebRoot%>;
        }
        
        # Used by CapRover for health check
        location /.well-known/captain-identifier {
            root <%-s.staticWebRoot%>;
        }

        error_page 502 /captain_502_custom_error_page.html;
        location = /captain_502_custom_error_page.html {
            root <%-s.customErrorPagesDirectory%>;
            internal;
        }
}
```

### Environment Details

- CapRover version: 1.11.1
- Chatwoot version: 3.11.0
- Server OS: Ubuntu 22.04

### Additional Information
- SSL certificate for mydomain.com was obtained through Let's Encrypt.
- The certificate appears to be correctly configured but results in an invalid certificate error when accessing the reset password link.
- No apparent errors in the NGINX logs or Chatwoot logs relevant to this issue.

**Comment by hnmendes** [comment]
Just got nginx logs and it gave me this:

> 2024/07/23 10:42:05 [error] 508#508: *190976 open() "/usr/share/nginx/default/app/auth/password/edit" failed (2: No such file or directory), client: 179.73.198.97, server: _, request: "GET /app/auth/password/edit?reset_password_token=<password_token> HTTP/1.1", host: "mydomain.com"
> 
> [23/Jul/2024:10:42:05 +0000] "mydomain.com" "GET /app/auth/password/edit?reset_password_token=<password_token> HTTP/1.1" 404 2401 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Mobile/15E148 Safari/604.1" "-"

I don't know why it's opening "/usr/share/nginx/default/app/auth/password/edit" - do you know what actions should i take here ?

**Comment by pranavrajs** [comment]
@hnmendes This seems like an issue with the Caprover SSL config. We do not officially maintain support for Caprover installations now. Please use a officially supported mode of installation for better support.
