### ISSUE TITLE
Whatsapp Cloud: Unable to receive images or attachments (500)

### ISSUE THREAD

**Issue by rgon** [chatwoot/chatwoot#9809]
### Describe the bug

When sending a whatsapp message with a photo or any other attachment, Chatwoot is unable to download it, after being triggered by the webhook. The `Webhooks::WhatsappEventsJob` is enqueued, but errors out with the following traceback:

<details>
<summary>Error log @ photo message webhook:</summary>
<pre>
rails-1     | I, [2024-07-19T18:52:52.302242 #1]  INFO -- : [cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb] Started POST "/webhooks/whatsapp/+MyPhoneNumber" for my.ip.address.xx at 2024-07-19 18:52:52 +0000
rails-1     | I, [2024-07-19T18:52:52.311326 #1]  INFO -- : [cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb] Processing by Webhooks::WhatsappController#process_payload as */*
rails-1     | I, [2024-07-19T18:52:52.311687 #1]  INFO -- : [cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb]   Parameters: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wamid.xxxxxxxxxxxxxxxxxxxx", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}], "phone_number"=>"+myPhoneNumber", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wamid.xxxxxxxxxxxxxxxxxxxxx=", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}]}}
sidekiq-1   | {"ts":"2024-07-19T18:52:52.314Z","pid":1,"tid":"4ilx","lvl":"INFO","msg":"start","ctx":{"class":"Webhooks::WhatsappEventsJob","jid":"8cacc304a3de1b8441c4c6f5"}}
rails-1     | I, [2024-07-19T18:52:52.314738 #1]  INFO -- : [cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb] [ActiveJob] Enqueued Webhooks::WhatsappEventsJob (Job ID: 77c1775e-877c-4032-a596-73612934c0eb) to Sidekiq(low) with arguments: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wwamid.xxxxxxxxxxxxxxxxxxxx=", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}], "controller"=>"webhooks/whatsapp", "action"=>"process_payload", "phone_number"=>"+myPhoneNumber", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wwamid.xxxxxxxxxxxxxxxxxxxx=", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}]}}
rails-1     | I, [2024-07-19T18:52:52.315088 #1]  INFO -- : [cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb] Completed 200 OK in 3ms (ActiveRecord: 0.0ms | Allocations: 872)
sidekiq-1   | I, [2024-07-19T18:52:52.315585 #1]  INFO -- : [ActiveJob] [Webhooks::WhatsappEventsJob] [77c1775e-877c-4032-a596-73612934c0eb] Performing Webhooks::WhatsappEventsJob (Job ID: 77c1775e-877c-4032-a596-73612934c0eb) from Sidekiq(low) enqueued at 2024-07-19T18:52:52Z with arguments: {"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wwamid.xxxxxxxxxxxxxxxxxxxx=", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}], "controller"=>"webhooks/whatsapp", "action"=>"process_payload", "phone_number"=>"+myPhoneNumber", "whatsapp"=>{"object"=>"whatsapp_business_account", "entry"=>[{"id"=>"myAccountID", "changes"=>[{"value"=>{"messaging_product"=>"whatsapp", "metadata"=>{"display_phone_number"=>"myPhoneNumber", "phone_number_id"=>"myPhoneID"}, "contacts"=>[{"profile"=>{"name"=>"My Whatsapp Contact Name"}, "wa_id"=>"clientPhoneNumber"}], "messages"=>[{"from"=>"clientPhoneNumber", "id"=>"wwamid.xxxxxxxxxxxxxxxxxxxx=", "timestamp"=>"1721415169", "type"=>"image", "image"=>{"mime_type"=>"image/jpeg", "sha256"=>"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=", "id"=>"1723304531774215"}}]}, "field"=>"messages"}]}]}}
rails-1     | I, [2024-07-19T18:52:52.315386 #1]  INFO -- : source=rack-timeout id=cff9be71-2068-4d1b-9d9e-ad6d9d6da8fb timeout=15000ms service=14ms state=completed
sidekiq-1   | E, [2024-07-19T18:52:52.980736 #1] ERROR -- : [ActiveJob] [Webhooks::WhatsappEventsJob] [77c1775e-877c-4032-a596-73612934c0eb] Error performing Webhooks::WhatsappEventsJob (Job ID: 77c1775e-877c-4032-a596-73612934c0eb) from Sidekiq(low) in 665.83ms: Down::ServerError (500 Internal Server Error):
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down/net_http.rb:340:in `response_error!'
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down/net_http.rb:177:in `rescue in open_uri'
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down/net_http.rb:144:in `open_uri'
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down/net_http.rb:94:in `download'
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down/backend.rb:13:in `download'
sidekiq-1   | /gems/ruby/3.3.0/gems/down-5.4.0/lib/down.rb:10:in `download'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb:15:in `download_attachment_file'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_base_service.rb:116:in `attach_files'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_base_service.rb:76:in `create_regular_message'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_base_service.rb:63:in `create_messages'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_base_service.rb:36:in `process_messages'
sidekiq-1   | /app/app/services/whatsapp/incoming_message_base_service.rb:15:in `perform'
sidekiq-1   | /app/app/jobs/webhooks/whatsapp_events_job.rb:10:in `perform'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/execution.rb:65:in `block in _perform_job'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/i18n-1.14.5/lib/i18n.rb:351:in `with_locale'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/core_ext/time/zones.rb:65:in `use_zone'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/execution.rb:64:in `_perform_job'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/instrumentation.rb:20:in `_perform_job'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/execution.rb:52:in `perform_now'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/instrumentation.rb:14:in `block in perform_now'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/instrumentation.rb:25:in `block in instrument'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/notifications.rb:206:in `block in instrument'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/notifications.rb:206:in `instrument'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/instrumentation.rb:35:in `instrument'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/instrumentation.rb:14:in `perform_now'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/logging.rb:18:in `block in perform_now'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/tagged_logging.rb:37:in `tagged'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/tagged_logging.rb:99:in `tagged'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/logging.rb:25:in `tag_logger'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/logging.rb:18:in `perform_now'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/execution.rb:30:in `block in execute'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/railtie.rb:54:in `block (4 levels) in <class:Railtie>'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/execution_wrapper.rb:88:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/reloader.rb:71:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/railtie.rb:53:in `block (3 levels) in <class:Railtie>'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `instance_exec'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/callbacks.rb:138:in `run_callbacks'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/execution.rb:28:in `execute'
sidekiq-1   | /gems/ruby/3.3.0/gems/activejob-7.0.8.4/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:220:in `execute_job'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:185:in `block (4 levels) in process'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:180:in `traverse'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job/interrupt_handler.rb:7:in `call'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:183:in `block in traverse'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/metrics/tracking.rb:26:in `track'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/metrics/tracking.rb:126:in `call'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:182:in `traverse'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/middleware/chain.rb:173:in `invoke'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:184:in `block (3 levels) in process'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:145:in `block (6 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_retry.rb:118:in `local'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:144:in `block (5 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/rails.rb:16:in `block in call'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/reloader.rb:72:in `block in wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/execution_wrapper.rb:92:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/activesupport-7.0.8.4/lib/active_support/reloader.rb:71:in `wrap'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/rails.rb:15:in `call'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:139:in `block (4 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:281:in `stats'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:134:in `block (3 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:25:in `call'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:133:in `block (2 levels) in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_retry.rb:85:in `global'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:132:in `block in dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/job_logger.rb:52:in `prepare'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:131:in `dispatch'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:183:in `block (2 levels) in process'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:182:in `handle_interrupt'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:182:in `block in process'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:181:in `handle_interrupt'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:181:in `process'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:86:in `process_one'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/processor.rb:76:in `run'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/component.rb:10:in `watchdog'
sidekiq-1   | /gems/ruby/3.3.0/gems/sidekiq-7.3.0/lib/sidekiq/component.rb:19:in `block in safe_thread'
sidekiq-1   | {"ts":"2024-07-19T18:52:52.986Z","pid":1,"tid":"4ilx","lvl":"INFO","msg":"fail","ctx":{"class":"Webhooks::WhatsappEventsJob","jid":"8cacc304a3de1b8441c4c6f5","elapsed":0.673}}
sidekiq-1   | {"ts":"2024-07-19T18:52:52.987Z","pid":1,"tid":"4ilx","lvl":"WARN","msg":"{\"context\":\"Job raised exception\",\"job\":{\"retry\":true,\"queue\":\"low\",\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Webhooks::WhatsappEventsJob\",\"args\":[{\"job_class\":\"Webhooks::WhatsappEventsJob\",\"job_id\":\"77c1775e-877c-4032-a596-73612934c0eb\",\"provider_job_id\":null,\"queue_name\":\"low\",\"priority\":null,\"arguments\":[{\"object\":\"whatsapp_business_account\",\"entry\":[{\"id\":\"myAccountID\",\"changes\":[{\"value\":{\"messaging_product\":\"whatsapp\",\"metadata\":{\"display_phone_number\":\"myPhoneNumber\",\"phone_number_id\":\"myPhoneID\",\"_aj_hash_with_indifferent_access\":true},\"contacts\":[{\"profile\":{\"name\":\"My Whatsapp Contact Name\",\"_aj_hash_with_indifferent_access\":true},\"wa_id\":\"clientPhoneNumber\",\"_aj_hash_with_indifferent_access\":true}],\"messages\":[{\"from\":\"clientPhoneNumber\",\"id\":\"wwamid.xxxxxxxxxxxxxxxxxxxx=\",\"timestamp\":\"1721415169\",\"type\":\"image\",\"image\":{\"mime_type\":\"image/jpeg\",\"sha256\":\"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=\",\"id\":\"1723304531774215\",\"_aj_hash_with_indifferent_access\":true},\"_aj_hash_with_indifferent_access\":true}],\"_aj_hash_with_indifferent_access\":true},\"field\":\"messages\",\"_aj_hash_with_indifferent_access\":true}],\"_aj_hash_with_indifferent_access\":true}],\"controller\":\"webhooks/whatsapp\",\"action\":\"process_payload\",\"phone_number\":\"+myPhoneNumber\",\"whatsapp\":{\"object\":\"whatsapp_business_account\",\"entry\":[{\"id\":\"myAccountID\",\"changes\":[{\"value\":{\"messaging_product\":\"whatsapp\",\"metadata\":{\"display_phone_number\":\"myPhoneNumber\",\"phone_number_id\":\"myPhoneID\",\"_aj_hash_with_indifferent_access\":true},\"contacts\":[{\"profile\":{\"name\":\"My Whatsapp Contact Name\",\"_aj_hash_with_indifferent_access\":true},\"wa_id\":\"clientPhoneNumber\",\"_aj_hash_with_indifferent_access\":true}],\"messages\":[{\"from\":\"clientPhoneNumber\",\"id\":\"wwamid.xxxxxxxxxxxxxxxxxxxx=\",\"timestamp\":\"1721415169\",\"type\":\"image\",\"image\":{\"mime_type\":\"image/jpeg\",\"sha256\":\"4/bjM/Z0S4PCmC3hsFO44+VYEBaSrWEggIzK5auY+Qo=\",\"id\":\"1723304531774215\",\"_aj_hash_with_indifferent_access\":true},\"_aj_hash_with_indifferent_access\":true}],\"_aj_hash_with_indifferent_access\":true},\"field\":\"messages\",\"_aj_hash_with_indifferent_access\":true}],\"_aj_hash_with_indifferent_access\":true}],\"_aj_hash_with_indifferent_access\":true},\"_aj_hash_with_indifferent_access\":true}],\"executions\":0,\"exception_executions\":{},\"locale\":\"en\",\"timezone\":\"UTC\",\"enqueued_at\":\"2024-07-19T18:52:52Z\"}],\"jid\":\"8cacc304a3de1b8441c4c6f5\",\"created_at\":1721415172.3131208,\"enqueued_at\":1721415172.3132591}}"}
sidekiq-1   | {"ts":"2024-07-19T18:52:52.987Z","pid":1,"tid":"4ilx","lvl":"WARN","msg":"Down::ServerError: 500 Internal Server Error"}
sidekiq-1   | {"ts":"2024-07-19T18:52:52.988Z","pid":1,"tid":"4ilx","lvl":"WARN","msg":"app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb:15:in `download_attachment_file'\napp/services/whatsapp/incoming_message_base_service.rb:116:in `attach_files'\napp/services/whatsapp/incoming_message_base_service.rb:76:in `create_regular_message'\napp/services/whatsapp/incoming_message_base_service.rb:63:in `create_messages'\napp/services/whatsapp/incoming_message_base_service.rb:36:in `process_messages'\napp/services/whatsapp/incoming_message_base_service.rb:15:in `perform'\napp/jobs/webhooks/whatsapp_events_job.rb:10:in `perform'"}

</pre>
</details>

The error occurrs in the file:
```log
sidekiq-1   | /app/app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb:15:in `download_attachment_file'
```
I have only tested this with the Whatsapp Cloud API.

### To Reproduce

1. Chatwoot community edition, running on docker. Happens both with a local and S3_compatible storage driver.
2. Set up a Whatsapp Business Cloud API account
3. Send a message from any phone number to the Chatwoot-controlled one.
4. You won't receive it, and see the attached error messages.

### Expected behavior

We can correctly receive and preview the sent image/attachment in the Chatwoot UI.

### Environment

Docker

### Platform

Browser

### Docker (if applicable)

<details>
<summary>docker version</summary>
<pre>
 Version:           27.0.3
 API version:       1.46
 Go version:        go1.21.11
 Git commit:        7d4bcd8
 Built:             Sat Jun 29 00:02:29 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.0.3
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.11
  Git commit:       662f78c
  Built:            Sat Jun 29 00:02:29 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</pre>
</details>
<details>
<summary>docker compose version</summary>
<pre>
Docker Compose version v2.28.1
</pre>
</details>

**Comment by rgon** [comment]
The problem seems to be in the `download_attachment_file` method, which is not implemented correctly for the whatsapp cloud API.

## What happens
The flow is the following:
+ User sends a picture/document.
+ The webhook gets called, with a messag.type = document (or else), and whose document={filename: ..., **id: xxx**}
+ Chatwoot parses the message and calls `download_attachment`
+ The app fetches `inbox.channel.media_url(attachment_payload[:id])` as if it were the file, and downloads it with `Down.download`

https://github.com/chatwoot/chatwoot/blob/23e30fcb1a0d8492fb93b53716b4a4c48ad00903/app/services/whatsapp/incoming_message_whatsapp_cloud_service.rb#L11-L16

## The actual FB API response
According to [Meta's Whatsapp Cloud API docs](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media/?locale=es_ES#retrieve-media-url), the response of `url_response` is not a file that can be downloaded, but rather one that contains a download `url`:
```json
{
   "url": "https://lookaside.fbsbx.com/whatsapp_business/attachments/?mid=123456789&ext=123456789&hash=xxxxxxxxxxxxxsJtvUnyz4U3cjKd-xxxxxxxxxxxxx",
   "mime_type": "application/msword",
   "sha256": "6a95165c68c02c8e0a13bac9fdf21460f37ea85037ebe09f856afxxxxxxxxxxx",
   "file_size": 49664,
   "id": "xxxxxxxxxxxx",
   "messaging_product": "whatsapp"
}
```

And then [download the media from this URL, passing the `access_token` as well](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/media/?locale=es_ES#download-media).

## Error responses
An unauthorized response also does not return `url_response.unauthorized`, but rather is like the following:

```json
{
   "error": {
      "message": "An access token is required to request this resource.",
      "type": "OAuthException",
      "code": 104,
      "fbtrace_id": "__redacted__"
   }
}
```

**Comment by sojan-official** [comment]
@rgon  what `HTTParty.get(inbox.channel.media_url(attachment_payload[:id])` returns is the payload which gets assigned to url_response

```
{
   "url": "https://lookaside.fbsbx.com/whatsapp_business/attachments/?mid=123456789&ext=123456789&hash=xxxxxxxxxxxxxsJtvUnyz4U3cjKd-xxxxxxxxxxxxx",
   "mime_type": "application/msword",
   "sha256": "6a95165c68c02c8e0a13bac9fdf21460f37ea85037ebe09f856afxxxxxxxxxxx",
   "file_size": 49664,
   "id": "xxxxxxxxxxxx",
   "messaging_product": "whatsapp"
}
```

url response is then parsed to get the "URL" parameter which gets passed to Down 

```
Down.download(url_response.parsed_response['url'], headers: inbox.channel.api_headers)
#url_response.parsed_response['url'] -> is the URL to actual file 
```

you can check the value of inbox.channel.api_headers to see if there are any errors

**Comment by rgon** [comment]
I was just correcting my comment (again) to reflect this, my bad, first-time-ruby confusion! 

The issue that gets logged is that this Down.download request receives a `500` server error. The FB API does indeed return a 500 error if unauthorized (not a 400/403, thus causing this much confusion).

```log
sidekiq-1   | E, [2024-07-19T18:56:19.336272 #1] ERROR -- : [ActiveJob] [Webhooks::WhatsappEventsJob] [2e9cad49-74f9-4e2d-b89e-c6b182e88bf2] Error performing Webhooks::WhatsappEventsJob (Job ID: 2e9cad49-74f9-4e2d-b89e-c6b182e88bf2) from Sidekiq(low) in 731.99ms: Down::ServerError (500 Internal Server Error):
```

I'm patching my installation with a bunch of logging to see where this goes. Will report back when I have more info.

**Comment by rgon** [comment]
Well this went weird.

The FB token I was using for facebook had granular permissions, limiting access to a specific account. 
<details>
<summary>Token explorer info</summary>
<pre>
Permissions: instagram_basic, whatsapp_business_management, instagram_manage_messages, whatsapp_business_messaging, public_profile

granular:
pages_show_list			myPageID : myPageName
pages_messaging			myPageID : myPageName
instagram_basic			myIGID
instagram_manage_messages	myIGID
whatsapp_business_management	myWaAccount
whatsapp_business_messaging	myWaAccount
</pre>
</details>
Apparently, even though FB supports that, those tokens did not have access to media resources, while everything else worked normally. It seems that FB does not recognize whether the media asset belongs to a specific Whatsapp account/page, raising a 500 error when trying to access it, instead of checking! Switching to a new token, generated with the procedure detailed in the docs, fixed the issue.

This is a problem with FB not parsing granular token scopes correctly, or with the user (myself) using those types of tokens.

FB' s use of 500 errors seems inappropriate, but overriding them may cause unintended consequences. Chatwoot's error handling seems correct. Maybe we should update the docs to indicate that you should not use granular tokens?

Closing the issue!

@sojan-official While reviewing the code, though, I've noticed many calls to the deprecated & v13 Facebook APIs (EOL since a few months ago). Will test and publish a PR updating their version.
