### ISSUE TITLE
Add conversions to none admin agents

### ISSUE THREAD

**Issue by datzent83** [chatwoot/chatwoot#9812]
### Is your feature or enhancement related to a problem? Please describe.

Not sure if I am posting this in the right place, but I have a few agents that are not admins. They are just field agents. The only way it seems I can assign an agent to a conversion is if the agent is an admin or part of a team. Is that by design?

### Describe the solution you'd like

Add new agent
Agent verified
Assign conversion to agent

**Comment by pranavrajs** [comment]
@datzent83 Directly assigning the conversation is not supported. You need to be part of an inbox. However, the changes related to #4216 should allow you to add people to inboxes and show them only the ones assigned to them. Closing this here for now.
