### ISSUE TITLE
Self host manual installation -  compilation failed v3.11

### ISSUE THREAD

**Issue by ozzyoss77** [chatwoot/chatwoot#9814]
### Describe the bug

Installation failed on step 6:
`I, [2024-07-21T21:50:34.801519 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage-3ab61e47dd4ee2d79db525ade1dca2ede0ea2b7371fe587e408ee37b7ade265d.js.gz
I, [2024-07-21T21:50:34.801736 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js
I, [2024-07-21T21:50:34.801879 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/activestorage.esm-01f58a45d77495cdfbdfcc872902a430426c4391634ec9c3da5f69fbf8418492.js.gz
I, [2024-07-21T21:50:34.802062 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js
I, [2024-07-21T21:50:34.802194 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable-5433453f9b6619a9de91aaab2d7fc7ff183e5260c0107cbc9a1aa0c838d9a74e.js.gz
I, [2024-07-21T21:50:34.802381 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js
I, [2024-07-21T21:50:34.802516 #28686]  INFO -- : Writing /home/chatwoot/chatwoot/public/assets/actioncable.esm-e01089c3ec4fe7817fa9abcad06cab6bdc387f95f0ca6aab4bf7ba7537f70690.js.gz
Compiling...
Compilation failed:`

I tried 5 times in 5 different instances between t3a.medium, large, and clarge, and I always get the error at that step. When I try to retry, the same thing happens on the same installation and on new ones."

### To Reproduce

1. Enviroment AWS EC2 t3a.medium (2vcpu, 4gb ram).
2. Manual isntallation linux with script.

### Environment

Linux VM

### Cloud Provider

AWS

### Platform

None

### Operating system

Ubuntu 24 LTS

**Comment by vishnu-narayanan** [comment]
@ozzyoss77 Compilation failure usually happens due to insufficient memory resources. An instance with 8 or more GB of RAM should have helped. 

Are you getting the same on t3a.large and large? 

Could you share the full log?

PS: If you are on AWS, you can get started easily with the official marketplace image.
https://aws.amazon.com/marketplace/pp/prodview-tolblk4kmdqd4

**Comment by pranavrajs** [comment]
@ozzyoss77 Please add swap space of 8GB+ and this should be resolved.
