### ISSUE TITLE
User can see conversations in teams he doesn't belong

### ISSUE THREAD

**Issue by laianeramos** [chatwoot/chatwoot#9826]
### Describe the bug

I noticed that if a user assign a conversation to a team he is not part of, he continues to have access to that conversation on his screen, through the url in the browser history or through the contacts module (in "previous conversations"). 

This should not happen. I think this is a security flaw.

### To Reproduce

1. Create a team and don't add a specific user to it;
2. In this specific user's profile, open a conversation that hi has access to and assign to the team that he is not part of;
3. The conversation will continue on the user's screen, even if he is on a team he doesn't belong to;
4. Copy the conversation URL and open it in a new tab, and he will continue to have access to it.
5. Access the contact's profile and open the "previous conversations", and the user will continue to have access to it

### Expected behavior

When transferring the chat to a team he is not part of, his access to that chat should be blocked, with a message informing him that he no longer has access because the conversation is on a team he does not participate in. 

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Microsoft Edge

**Comment by sojan-official** [comment]
Permissions in Chatwoot currently work over the access given in the inbox. Teams act as a conversation filter. 

Ref: 

https://github.com/chatwoot/chatwoot/issues/8787
https://github.com/chatwoot/chatwoot/issues/4216
