### ISSUE TITLE
Managing users in teams

### ISSUE THREAD

**Issue by laianeramos** [chatwoot/chatwoot#9827]
### Describe the bug

There is a flaw/bug to manage users in a team. When opening the team settings, a list of all agents on the account appears, but agents who are already part of that team are also unchecked. So, to make any changes I need to remember which users were already on that team and include/exclude the agents that I want/don't want to be part of the team, creating the risk of accidentally removing or adding someone. Agents who are already on the team should be marked as already included.

Furthermore, if I creat a new agent, I need to go into all the teams I want to include him in and add him one by one, remembering who was already on those teams so I don't accidentally remove or add someone. When creating/editing agents, I think there should show a list of teams allowing us to select which teams we want this user to be part of or removed from.

### To Reproduce

1. Edit a team
2. Edit/creat an agent

### Expected behavior

 Agents who are already on the team should be marked as already included.

When creating/editing agents, I think there should show a list of teams allowing us to select which teams we want this user to be part of or removed from.

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 20.04

### Browser and version

Microsoft Edge

**Comment by pranavrajs** [comment]
@laianeramos Can you please share a screencast? This is not reproducible. 

<img width="93" alt="Screenshot 2024-08-02 at 12 40 28 AM" src="https://github.com/user-attachments/assets/1ce48c17-3dd2-4564-9316-e14ef9baa316">

**Comment by laianeramos** [comment]
@pranavrajs i did some more tests and in versions 3.10 the agents are unmarked, but in 3.11 everthing seems alright. 

3.10: 

https://github.com/user-attachments/assets/740e2a58-471f-4aaa-b6cd-80425c2715ff

3.11: 

https://github.com/user-attachments/assets/3e8f010d-1353-4c64-a2fe-d156619927b4

**Comment by pranavrajs** [comment]
Closing this as this is no longer reproducible.
