### ISSUE TITLE
API auth documentation

### ISSUE THREAD

**Issue by incraigulous** [chatwoot/chatwoot#983]
Documentation for authenticating with the API needs to be added. It's possible it's already available somewhere, but I couldn't find it. I was able to find my access-token, but I'm not sure how to compose my request. 

My current requests looks like: 

```
GET http://0.0.0.0:3000/api/v1/accounts/1/inboxes
Accept: application/json
access-token: MRyjksRWoTA6yVvLpgisXVBf
token-type: Bearer
client: 23oVyoZMPavKsJqzkUmNoDD1
uid: john@acme.inc

```
That gets a 401 Unauthorized. I pulled the access token from the admin user profile, and I got the client from the javascript embed, but I'm sure that isn't the right place to find it. 

Is there a place where we can find authentication documentation? Any ideas what I'm doing wrong?

**Comment by sojan-official** [comment]
@incraigulous  we have merged the commit for the documentation. https://github.com/chatwoot/chatwoot/blob/4f83d5451ebfa4eac865588f5b1b8c07e2201bf9/swagger/swagger.json#L31
but didn't get a chance to update the website yet, will do over this weekend.

the access token is supposed to be in the header with the key `api_access_token`.

**Comment by sojan-official** [comment]
@incraigulous  we have updated the website with authentication documentation 
https://www.chatwoot.com/developers/api/#section/Authentication

**Comment by incraigulous** [comment]
Wow @sojan-official, you are fast!

**Comment by CL545740896** [comment]
#1057 
It is  not work in  create message api 
https://app.chatwoot.com/api/v1/accounts/1/conversations/2/messages
