### ISSUE TITLE
Twitter expansions to search and new tweets

### ISSUE THREAD

**Issue by iammattmartin** [chatwoot/chatwoot#984]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Twitter implementation to reply to tweets and DMs is great but to increase the scope, it would be good to be able to add the ability to add search terms that you want to monitor. Some people could use your brand band but not @ reply you. Picking up that interaction could provide much improve support. Whilst that can be done with external twitter clients, you then have to start the communication external.

This leads on to a second function with the ability to start outbound Tweets. Such as announcements or notices which people may reply to. Again, this would then allow the full history to be captured in the software rather than starting somewhere external and finishing internal.

Whilst this may not form core functionality, it appears to be something lots of similar stacks are adding to help with the customer support demand on businesses within social media channels.

**Comment by pranavrajs** [comment]
@iammattmartin 

> Twitter implementation to reply to tweets and DMs is great but to increase the scope, it would be good to be able to add the ability to add search terms that you want to monitor. Some people could use your brand band but not @ reply you. Picking up that interaction could provide much improve support. Whilst that can be done with external twitter clients, you then have to start the communication external.

This seems like a useful feature, however we are concerned with a lot of conversations being created which may be irrelevant to you. Let us explore the best ways to do this.

> This leads on to a second function with the ability to start outbound Tweets. Such as announcements or notices which people may reply to. Again, this would then allow the full history to be captured in the software rather than starting somewhere external and finishing internal.

This is more like social media management which may not align with the product roadmaps. We will get back on this.

**Comment by iammattmartin** [comment]
On the first count, maybe a page with recent tweets matching that search term instead of one conversation created for each match. In the search list, you could have a button where you can create a new conversation based on that tweet.

Overall it would venture a bit in to social management but at the heart it is still a support tool to find and assist customers. This will set it apart from similarly competing products that do similar but always lack in one way or another.

**Comment by pranavrajs** [comment]
> Overall it would venture a bit in to social management but at the heart it is still a support tool to find and assist customers. This will set it apart from similarly competing products that do similar but always lack in one way or another.

Yes, I totally agree with this. The vision of Chatwoot itself is to become a central repository for your customer data which can be used to provide contextual support. In that sense, every piece of information about the customer is relevant. We will think this through and will get back to you here.
