### ISSUE TITLE
Multimedia files do not play or display

### ISSUE THREAD

**Issue by ozzyoss77** [chatwoot/chatwoot#9848]
### Describe the bug

I have version 3.5 in production running without problems for a long time, but the hard drive got full and an expansion was done on AWS EC2. Additionally, the instance domain was changed manually. Since then, no multimedia files are displayed. Does anyone have any ideas on how to solve this?
![image](https://github.com/user-attachments/assets/a0eeb62f-05df-46f7-b977-df38dbd6a350)
![image](https://github.com/user-attachments/assets/40b710da-40cf-48db-a9ec-5205a45a4e6f)

### To Reproduce

1. Hard drive full
2. Expansion hard drive 
3. Change domain manually

### Environment

app.chatwoot.com

### Cloud Provider

AWS

### Platform

Browser

### Operating system

Ubuntu 22.04 LTS

### Browser and version

v3.5

**Comment by ozzyoss77** [comment]
Apparently, all the multimedia is pointing to the old domain:
I copy the URL of the multimedia file, and I get this:
https://admin.wrongdomain.com/app/accounts/2/conversations/193?messageId=122547

instead of:
https://admin.gooddomain.com/app/accounts/2/conversations/193?messageId=122547

**Comment by ozzyoss77** [comment]
I managed to fix it by performing a restart I found in the documentation:
`sudo systemctl restart chatwoot.target`
Instead of using:
`sudo cwctl restart`

**Comment by vishnu-narayanan** [comment]
@ozzyoss77 Thank you for reporting the solution as well.

For future reference: If you are changing domains, you should also change the `FRONTED_URL` env variable. Any change to env variables should also be accompanied by restarting the chatwoot server.
