### ISSUE TITLE
Location is missing even after MaxmindDB is configured

### ISSUE THREAD

**Issue by csyedbilal** [chatwoot/chatwoot#9852]
### Describe the bug

MaxmindDB working fine but location not displayed such as city and country!
![Screenshot_119](https://github.com/user-attachments/assets/157adf76-73ab-44a1-ab50-d0bd1b05939a)
![Screenshot_120](https://github.com/user-attachments/assets/bcb0b74c-8c6b-4cad-9c52-66182907fef7)
# sudo -i -u chatwoot
# cd chatwoot
# bundle exec rails ip_lookup:setup

### To Reproduce

root@chatwoot-test:~# docker exec -it root-rails-1 bundle exec rails ip_lookup:setup
/gems/ruby/3.3.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /usr/local/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.4 to add mutex_m into its gemspec.
DEPRECATION WARNING: Dotenv::Railtie is deprecated! Use Dotenv::Rails instead. (called from <main> at /app/config/application.rb:14)
I, [2024-07-30T12:44:41.778914 #2690]  INFO -- : [rake ip_lookup:setup] Fetch GeoLite2-City database
I, [2024-07-30T12:44:43.211107 #2690]  INFO -- : [rake ip_lookup:setup] Fetch complete
root@chatwoot-test:~# 

### Environment

Docker

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Debian GNU/Linux

### Browser and version

Latest 

### Docker (if applicable)

root@chatwoot-test:~# docker version
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.19
  GitCommit:        2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc:
  Version:          1.7.19
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
root@chatwoot-test:~# 
root@chatwoot-test:~# docker info
Client: Docker Engine - Community
 Version:    27.1.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 4
  Paused: 0
  Stopped: 1
 Images: 3
 Server Version: 27.1.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2bf793ef6dc9a18e00cb12efb64355c2c9d5eb41
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.1.0-9-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.569GiB
 Name: chatwoot-test
 ID: 652a5b07-a061-4afc-8e46-024763a2b52b
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

root@chatwoot-test:~#

**Comment by csyedbilal** [comment]
`root@chatwoot-test:~# docker exec -it 32beff13d8e3 /bin/sh     /app # bundle exec rails console
/gems/ruby/3.3.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32: warning: /usr/local/lib/ruby/3.3.0/mutex_m.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add mutex_m to your Gemfile or gemspec. Also contact author of activesupport-7.0.8.4 to add mutex_m into its gemspec.
DEPRECATION WARNING: Dotenv::Railtie is deprecated! Use Dotenv::Rails instead. (called from <main> at /app/config/application.rb:14)
Loading production environment (Rails 7.0.8.4)
irb(main):001> conversation = Conversation.find(11)
irb(main):002> 
=> 
#<Conversation:0x00007f42cd8a7e08
...
irb(main):003> contact = Contact.find(conversation.contact_id)
irb(main):004> 
=> 
#<Contact:0x00007f42cd5f39c8
...
irb(main):005> ip_address = contact.additional_attributes['created_at_ip']
irb(main):006> 
=> "52.187.26.37"
irb(main):007> geo_data = Geocoder.search(ip_address).first
irb(main):008> 
=> 
#<Geocoder::Result::Geoip2:0x00007f42d86cd758
...
irb(main):009>   city = geo_data.data.dig('city', 'names', 'en')
irb(main):010>   country_code = geo_data.data.dig('country', 'iso_code')
=> "SG"
irb(main):011> city = geo_data.data.dig('city', 'names', 'en')
=> "Singapore"
irb(main):012> exit`

**Comment by csyedbilal** [comment]
`# Retrieve the conversation and associated contact
conversation = Conversation.find(12)
contact = Contact.find(conversation.contact_id)

# Geocode the IP address to get location data
ip_address = contact.additional_attributes['created_at_ip']
geo_data = Geocoder.search(ip_address).first

# Extract city and country code from the geocoding result
city = geo_data.data.dig('city', 'names', 'en')
country_code = geo_data.data.dig('country', 'iso_code')

# Update the contact record
contact.update(
  location: city,
  country_code: country_code
)  //  
`

**Comment by pranavrajs** [comment]
@csyedbilal Is the ip_lookup feature enabled on the account? If not, please enable it in your SuperAdmin console.
<img width="1063" alt="Screenshot 2024-08-02 at 12 37 00 AM" src="https://github.com/user-attachments/assets/e0cb855f-3061-42e9-b63a-e08c210143ee">

**Comment by csyedbilal** [comment]
@pranavrajs yeah it is already enabled

![image](https://github.com/user-attachments/assets/188771ef-0139-437f-ae7f-72ad3fbca689)

**Comment by csyedbilal** [comment]
@pranavrajs any update ?

**Comment by csyedbilal** [comment]
@pranavrajs ??

**Comment by csyedbilal** [comment]
@pranavrajs ???

**Comment by csyedbilal** [comment]
??

**Comment by sojan-official** [comment]
will be fixed by https://github.com/chatwoot/chatwoot/pull/8052
