### ISSUE TITLE
Help Center as SaaS model

### ISSUE THREAD

**Issue by jjmmbb** [chatwoot/chatwoot#9887]
### Is your feature or enhancement related to a problem? Please describe.

Allow the possibility to create Help Center names not conflicting with other users.

### Describe the solution you'd like

Currently the name of HELPCENTER will be conflicted with different users. More than one user can not use the same name.

https://URL/hc/HELPCENTERNAME/

### Describe alternatives you've considered

create a URL that make a difference between users, like this:

https://URL/hc/[USERID]/HELPCENTERNAME/ | https://URL/hc/[UserName]/HELPCENTERNAME/

or something like that.

So users can easily use the same HC name.

**Comment by pranavrajs** [comment]
@jjmmbb This is intentional. If there is a conflict, you can always configure the the custom domain.
