### ISSUE TITLE
attachment not showing Cloud API

### ISSUE THREAD

**Issue by harismateen** [chatwoot/chatwoot#9890]
### Describe the bug

Hi, 

Whenerver a customer send an attachment as media file, it wont show under Chatwoot, but after refresh the screen then it shows, 

<img width="678" alt="image" src="https://github.com/user-attachments/assets/d6b1aca1-59c9-4098-8705-eebb57b1009a">

### To Reproduce

Kubernetes
Chatwoot verison v3.8.0
GCP 

### Expected behavior

if user attached anything, it should show under chatwoot. 

### Environment

Kubernetes

### Cloud Provider

GCP

### Platform

Browser

### Operating system

Ubuntu

**Comment by pranavrajs** [comment]
@harismateen There is not enough information to debug the error. Can you please share the logs and also find out whether Chatwoot receives the attachments and processes them, but drops them afterward?

**Comment by metazul** [comment]
Same problem here. Any attachment. Including an audio message that appears as disabled and is only enabled for listening after the page is refreshed.
I'm using version 3.11.0 with Docker.

**Comment by MatheusOsh** [comment]
We noticed the same problem here. Happens either on Chromium, Edge, and even in the APP. If the medias are sent to Storage, they only appear after a page refresh.

**Comment by metazul** [comment]
I was using Meta's test phone number. As soon as I added my phone number and switched to it, the problem went away.

**Comment by lsantiagond** [comment]
Same problem

**Comment by sojan-official** [comment]
If you are using test numbers, the attachments won't work. Please make sure to use a production number.
