### ISSUE TITLE
Whatsapp send file error

### ISSUE THREAD

**Issue by doryashar** [chatwoot/chatwoot#9894]
### Describe the bug

when sending attachment (image or document) to whatsapp account, i get "The message could not be sent. Please check your connection."
i'm using chatwoot + evolution both on caprover.
tried both google storage and local storage.
when i click on the "sent" file it does show it. so the issue is not the upload.

Docker log:

I, [2024-08-06T11:14:58.238919 #1]  INFO -- : source=rack-timeout id=e78b9b35-ab32-40a3-93c0-f1d4b0092b66 timeout=15000ms service=200ms state=completed
I, [2024-08-06T11:14:59.104013 #1]  INFO -- : [e899f3c1-c125-448b-92da-c52cc6e6d09c]   GCS Storage (1321.1ms) Uploaded file to key: gi51ggrmvy7a6z75716a1zq02e36 (checksum: rq0dGgasZ9CAW86FKwBSXg==)
I, [2024-08-06T11:14:59.113760 #1]  INFO -- : [e899f3c1-c125-448b-92da-c52cc6e6d09c] [ActiveJob] Enqueued ActiveStorage::AnalyzeJob (Job ID: 13cac311-6a73-412f-a677-b2151e949af4) to Sidekiq(default) with arguments: #<GlobalID:0x00007f25a99ab340 @uri=#<URI::GID gid://chatwoot/ActiveStorage::Blob/442>>
I, [2024-08-06T11:14:59.133237 #1]  INFO -- : [e899f3c1-c125-448b-92da-c52cc6e6d09c]   Rendered api/v1/accounts/conversations/messages/create.json.jbuilder (Duration: 15.6ms | Allocations: 1314)
I, [2024-08-06T11:14:59.144930 #1]  INFO -- : [e899f3c1-c125-448b-92da-c52cc6e6d09c] Completed 200 OK in 2816ms (Views: 18.6ms | ActiveRecord: 845.4ms | Allocations: 51909)
I, [2024-08-06T11:14:59.147464 #1]  INFO -- : source=rack-timeout id=e899f3c1-c125-448b-92da-c52cc6e6d09c timeout=15000ms service=2880ms state=completed
I, [2024-08-06T11:14:59.989166 #1]  INFO -- : source=rack-timeout id=e16cfa68-6c84-4dac-81c7-1e12c12f0913 timeout=15000ms state=ready
I, [2024-08-06T11:14:59.990250 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] Started POST "/api/v1/accounts/2/conversations/60/messages" for 172.18.0.1 at 2024-08-06 11:14:59 +0000
I, [2024-08-06T11:15:00.000470 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] Processing by Api::V1::Accounts::Conversations::MessagesController#create as JSON
I, [2024-08-06T11:15:00.003076 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913]   Parameters: {"content"=>"🚨 The message could not be sent. Please check your connection. ", "message_type"=>"outgoing", "private"=>"[FILTERED]", "account_id"=>"2", "conversation_id"=>"60"}
I, [2024-08-06T11:15:00.194903 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] [ActiveJob] Enqueued ActionCableBroadcastJob (Job ID: e6d94607-d82f-436c-bce7-f4122c0d7a14) to Sidekiq(critical) with arguments: ["56zRCvMG5KmWhPAtrWdfDnLP", "jc6ZK4uTfN4PZnjBYGu2xzfJ", "jBeNgkZKHsi4p4K49y4DKvpK", "zGdKQte4SRknvFSDU7n2qwAf", "HftKENaCzMU7goK4wokp93Do", "P33CH3jmRXcAa4J6iFVmaVnq", "wwawaaVLePcyggM6PDVP6mZ7", "Z6gJjjoQswxkxw4xuUFLRfvw"], "message.created", {:id=>7624, :content=>"🚨 The message could not be sent. Please check your connection. ", :account_id=>2, :inbox_id=>6, :conversation_id=>60, :message_type=>1, :created_at=>1722942900, :updated_at=>Tue, 06 Aug 2024 11:15:00.090807529 UTC +00:00, :private=>true, :status=>"sent", :source_id=>nil, :content_type=>"text", :content_attributes=>{}, :sender_type=>"User", :sender_id=>1, :external_source_ids=>{}, :additional_attributes=>{}, :processed_message_content=>"🚨 The message could not be sent. Please check your connection. ", :sentiment=>{}, :conversation=>{:assignee_id=>1, :unread_count=>0, :last_activity_at=>1722942900, :contact_inbox=>{:source_id=>"7ee6c699-76f4-4dbf-a3b8-1db0703ab508"}}, :sender=>{:id=>1, :name=>"Dor", :available_name=>"Dor", :avatar_url=>"https://web.MYDOMAIN.us//rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--739de0ad8944bf4d72330e9b4371cc0b1f28154b/1962bc0fd95ca0a08ea51165f7146230.jpeg", :type=>"user", :availability_status=>"online", :thumbnail=>"https://web.MYDOMAIN.us//rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--739de0ad8944bf4d72330e9b4371cc0b1f28154b/1962bc0fd95ca0a08ea51165f7146230.jpeg"}, :performer=>{:id=>1, :name=>"Dor", :available_name=>"Dor", :avatar_url=>"https://web.MYDOMAIN.us//rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--739de0ad8944bf4d72330e9b4371cc0b1f28154b/1962bc0fd95ca0a08ea51165f7146230.jpeg", :type=>"user", :availability_status=>"online", :thumbnail=>"https://web.MYDOMAIN.us//rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--739de0ad8944bf4d72330e9b4371cc0b1f28154b/1962bc0fd95ca0a08ea51165f7146230.jpeg"}}
I, [2024-08-06T11:15:00.219218 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] [ActiveJob] Enqueued EventDispatcherJob (Job ID: 55fc9967-0098-4fcc-92d1-f6c7d215d837) to Sidekiq(critical) with arguments: "message.created", Tue, 06 Aug 2024 11:15:00.134034384 UTC +00:00, {:message=>#<GlobalID:0x00007f25a9955fa8 @uri=#<URI::GID gid://chatwoot/Message/7624>>, :performed_by=>nil}
I, [2024-08-06T11:15:00.225061 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] [ActiveJob] Enqueued SendReplyJob (Job ID: b85d9cfc-1e58-4d00-b6f8-fc3da33058dc) to Sidekiq(high) with arguments: 7624
I, [2024-08-06T11:15:00.342463 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913]   Rendered api/v1/accounts/conversations/messages/create.json.jbuilder (Duration: 30.9ms | Allocations: 1377)
I, [2024-08-06T11:15:00.349535 #1]  INFO -- : [e16cfa68-6c84-4dac-81c7-1e12c12f0913] Completed 200 OK in 345ms (Views: 75.2ms | ActiveRecord: 48.8ms | Allocations: 13599)
I, [2024-08-06T11:15:00.350729 #1]  INFO -- : source=rack-timeout id=e16cfa68-6c84-4dac-81c7-1e12c12f0913 timeout=15000ms service=362ms state=completed
I, [2024-08-06T11:15:00.410908 #1]  INFO -- : source=rack-timeout id=75bb6ea8-bd35-431d-a58d-7ce17a92df2a timeout=15000ms state=ready
I, [2024-08-06T11:15:00.411826 #1]  INFO -- : [75bb6ea8-bd35-431d-a58d-7ce17a92df2a] Started POST "/api/v1/accounts/2/conversations/60/update_last_seen" for 77.137.67.75 at 2024-08-06 11:15:00 +0000
I, [2024-08-06T11:15:00.418278 #1]  INFO -- : [75bb6ea8-bd35-431d-a58d-7ce17a92df2a] Processing by Api::V1::Accounts::ConversationsController#update_last_seen as JSON
I, [2024-08-06T11:15:00.425461 #1]  INFO -- : [75bb6ea8-bd35-431d-a58d-7ce17a92df2a]   Parameters: {"account_id"=>"2", "id"=>"60"}
I, [2024-08-06T11:15:00.460175 #1]  INFO -- : source=rack-timeout id=c507601c-e422-4be0-8b4e-8e1a7aa34c4f timeout=15000ms state=ready
I, [2024-08-06T11:15:00.469056 #1]  INFO -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f] Started GET "//rails/active_storage/representations/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBTU0lKYW5CbFp3WTZCa1ZVT2hOeVpYTnBlbVZmZEc5ZlptbHNiRnNIYVFINk1BPT0iLCJleHAiOm51bGwsInB1ciI6InZhcmlhdGlvbiJ9fQ==--739de0ad8944bf4d72330e9b4371cc0b1f28154b/1962bc0fd95ca0a08ea51165f7146230.jpeg" for 77.137.67.75 at 2024-08-06 11:15:00 +0000
I, [2024-08-06T11:15:00.497825 #1]  INFO -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f] Processing by ActiveStorage::Representations::RedirectController#show as JPEG
I, [2024-08-06T11:15:00.515717 #1]  INFO -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f]   Parameters: {"signed_blob_id"=>"eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--12bbabc57891b019d00e47bdaf7c6ccb5d95c24a", "variation_key"=>"[FILTERED]", "filename"=>"1962bc0fd95ca0a08ea51165f7146230"}
I, [2024-08-06T11:15:00.598692 #1]  INFO -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f]   Disk Storage (7.6ms) Downloaded file from key: sb3eeeaz3rmte7ptc3vy49gon68n
I, [2024-08-06T11:15:00.606418 #1]  INFO -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f] Completed 500 Internal Server Error in 77ms (ActiveRecord: 28.6ms | Allocations: 2224)
F, [2024-08-06T11:15:00.636729 #1] FATAL -- : [c507601c-e422-4be0-8b4e-8e1a7aa34c4f]
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] ActiveStorage::FileNotFoundError (ActiveStorage::FileNotFoundError):
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f]
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service/disk_service.rb:150:in `rescue in stream'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service/disk_service.rb:143:in `stream'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service/disk_service.rb:29:in `block in download'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `block in instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service.rb:163:in `instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service/disk_service.rb:28:in `download'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/downloader.rb:32:in `download'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/downloader.rb:13:in `block in open'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/downloader.rb:24:in `open_tempfile'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/downloader.rb:12:in `open'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) lib/active_storage/service.rb:90:in `open'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) app/models/active_storage/blob.rb:301:in `open'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) app/models/active_storage/variant_with_record.rb:34:in `transform_blob'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) app/models/active_storage/variant_with_record.rb:19:in `process'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) app/models/active_storage/variant_with_record.rb:14:in `processed'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activestorage (7.0.8.4) app/controllers/active_storage/representations/base_controller.rb:14:in `set_representation'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:400:in `block in make_lambda'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:200:in `block in halting'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `block in invoke_before'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `each'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:595:in `invoke_before'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:116:in `block in run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] audited (5.4.1) lib/audited/sweeper.rb:16:in `around'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] audited (5.4.1) lib/audited/sweeper.rb:16:in `around'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actiontext (7.0.8.4) lib/action_text/rendering.rb:20:in `with_renderer'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actiontext (7.0.8.4) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `instance_exec'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:138:in `run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/abstract_controller/callbacks.rb:233:in `process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal/rescue.rb:23:in `process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `block in instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/notifications.rb:206:in `instrument'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activerecord (7.0.8.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/abstract_controller/base.rb:151:in `process'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionview (7.0.8.4) lib/action_view/rendering.rb:39:in `process'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal.rb:188:in `dispatch'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_controller/metal.rb:251:in `dispatch'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `each'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/journey/router.rb:32:in `serve'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/routing/route_set.rb:852:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] omniauth (2.1.2) lib/omniauth/strategy.rb:202:in `call!'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] omniauth (2.1.2) lib/omniauth/strategy.rb:169:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] omniauth (2.1.2) lib/omniauth/builder.rb:44:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/tempfile_reaper.rb:15:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/etag.rb:27:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/conditional_get.rb:27:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/head.rb:12:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/session/abstract/id.rb:266:in `context'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/session/abstract/id.rb:260:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/cookies.rb:704:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/callbacks.rb:99:in `run_callbacks'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] railties (7.0.8.4) lib/rails/rack/logger.rb:40:in `call_app'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `block in call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:37:in `tagged'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] activesupport (7.0.8.4) lib/active_support/tagged_logging.rb:99:in `tagged'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] railties (7.0.8.4) lib/rails/rack/logger.rb:25:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/method_override.rb:24:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/runtime.rb:22:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/static.rb:23:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack (2.2.9) lib/rack/sendfile.rb:110:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] actionpack (7.0.8.4) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] rack-cors (2.0.0) lib/rack/cors.rb:102:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] railties (7.0.8.4) lib/rails/engine.rb:530:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/configuration.rb:272:in `call'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/server.rb:464:in `process_client'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/server.rb:245:in `block in run'
[c507601c-e422-4be0-8b4e-8e1a7aa34c4f] puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'

### To Reproduce

send any attachment to any whatsapp user

### Environment

Docker

### Cloud Provider

None

### Platform

None

### Operating system

ubuntu

**Comment by pranavrajs** [comment]
@doryashar We don't support the Evolution API. However, the error seems to be with the storage configuration `ActiveStorage::FileNotFoundError`. Please configure persistent storage as described [here](https://www.chatwoot.com/docs/self-hosted/deployment/storage/supported-providers).

**Comment by rodneyoliveira** [comment]
@doryashar @pranavrajs I am facing the same problem since yesterday...without any change in my configuration or server...

@doryashar Did you solve the problem? Could you share the solution?

@pranavrajs My environment is hosted in a AWS EC2 instance(ChatWoot 3.12.0 + Evolution API 1.8.2) + AWS S3 to storage my uploads.

In time: I've already checked and uploads are ok on S3.

Thanks!!!!
![Captura de Tela 2024-08-30 às 16 12 07](https://github.com/user-attachments/assets/48036c87-3206-40fb-9d3e-1486dd4efdb3)
![Captura de Tela 2024-08-30 às 16 11 28](https://github.com/user-attachments/assets/a17a5481-1f2b-4abb-b0e4-116098a22e65)

**Comment by paseto** [comment]
@rodneyoliveira have you found any solution?

**Comment by rodneyoliveira** [comment]
Hi Giovani,

Yeah, I solved it.

The problem was region latency. When I was setting up my S3 I didn't
realize that I put it in a different region from my ec2 server. Since I've
changed and set both in the same region the problem is gone.

Best regards,

*Rodney de Oliveira*
_________________________________
*Ictweb - Soluções Digitais*
https://www.ictweb.com.br




Em sex., 20 de set. de 2024 às 08:59, Giovani Paseto <
***@***.***> escreveu:

**Comment by paseto** [comment]
Issue sorted, thank you!

Regards
