### ISSUE TITLE
Not possible to delete articles, with no category

### ISSUE THREAD

**Issue by brundles** [chatwoot/chatwoot#9935]
### Describe the bug

I've created an article for the Helpdesk via API. 

But then I've deleted the related category, and now I cannot access the article via the backend, but still see the article in the frontend under an "uncategorized" category.

So no way for me to delete this article :-(

### To Reproduce

1. Add a new article via API (probably it can also be done directly in browser). Make sure its published.
2. Delete the related category.
3. Find the article on the frontend, and see that you cannot see it via the backend.

### Environment

Linux VM

### Cloud Provider

DigitalOcean

### Platform

Browser

**Comment by pranavrajs** [comment]
@brundles The delete APIs are not documented properly. We will address this issue. We don't allow articles without a category from the UI. You could do a DELETE /articles/<id> or PATCH with status as draft which should fix this.
