### ISSUE TITLE
Enhancement: Identify a way to deliver action-cable message in case of a temporary disconnect 

### ISSUE THREAD

**Issue by sojan-official** [chatwoot/chatwoot#995]
while using the chatwoot dashboard, if the action cable gets terminated because of a network issue for a couple of seconds and get reconnected right after. The messages delivered from the back end would be missed during this period.  

The end-user who is using the system might be unaware of this change and might be having an inconsistent state with respect to the backend. Either alert the user to refresh the page or find a way to store the updates in a buffer and redeliver it on subsequent reconnect. 

### Potential Breakages 

- another agent marked a ticket resolved and i missed the update. I might end up reopening the ticket while clicking the resolve button. 
- an agent might miss out on messages from contact and might continue the conversation without context/vice versa

**Comment by pranavrajs** [comment]
Closing this here, we will address this issue in the sync-architecture project.
