### ISSUE TITLE
Receiving attachments error with Twilio

### ISSUE THREAD

**Issue by pato-1441** [chatwoot/chatwoot#9954]
### Describe the bug

Given an Inbox made with Twilio it receives the attachments, but it doesn't show it at the Chat unless you refresh the component. It shows an alert saying "1 Unread Message" and in the left panel it shows "No content available". This's happening on a cloud environment and also on a docker one too. In order to be able to see the attachment, you have to reload the page.

### To Reproduce

1. Configure a WhatsApp Twilio Channel.
2. Send an image/audio/GIF.

### Expected behavior

It should render the attachment on the chat at the moment it's received.

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

Browser

### Operating system

Windows 11

### Browser and version

Microsoft Edge Version 127.0.2651.98 (Official build) (64-bit)

### Additional context

Video showing the bug:
00:02 - Attachment received.
00:07 - Navigate outside /conversations.
00:11 - Reopen the conversation now showing the attachment received before.

https://github.com/user-attachments/assets/98b02e7c-b914-4be7-a748-fc686ad0829b

**Comment by pranavrajs** [comment]
@pato-1441 If you see this on Chatwoot cloud, please reach out via live chat support.

If you are on a self-hosted installation, this is most likely an issue with the storage configuration. You need to add persistent storage as per the documentation here: https://www.chatwoot.com/docs/self-hosted/#storage

Please share the server logs with the error so we can debug this better.
