### ISSUE TITLE
Chatwoot generates offensive names for anonymous users

### ISSUE THREAD

**Issue by dsmalicsi** [chatwoot/chatwoot#9958]
### Describe the bug

I don't know if it should be filed as a bug, but it's worth looking at how names are generated. If left unchecked, such names can be used or referenced by auto reply bots and canned responses, and this will surely offend the user.

<img width="195" alt="Screenshot 2024-08-14 at 3 03 25 PM" src="https://github.com/user-attachments/assets/57300296-9769-47e2-b79a-1b33ca7f93f2">

<img width="495" alt="Screenshot 2024-08-14 at 3 04 11 PM" src="https://github.com/user-attachments/assets/d74408d4-18ad-4f9d-9579-52b8d20afb74">

For context, bold star is the general term for an actor/actress who works for the porn industry.

[https://en.wiktionary.org/wiki/bold_star](https://en.wiktionary.org/wiki/bold_star
)

### To Reproduce

There's no exact way to reproduce since it's randomly generated.

### Environment

Docker

### Cloud Provider

AWS

### Platform

Browser

**Comment by vishnu-narayanan** [comment]
Thank you for reporting this issue. Fixing this is not a priority at the moment.
