### ISSUE TITLE
Multiple outboxes

### ISSUE THREAD

**Issue by matlinski** [chatwoot/chatwoot#9961]
### Is your feature or enhancement related to a problem? Please describe.

I work for a middle size company looking to switch away from LiveAgent. We have for example 5 e-commerce pages, each with it's own contact email and we cannot respond to all queries from the same outbox.

### Describe the solution you'd like

Please implement an account or team specific outbox. So we can actually choose you over closed-source options. I'm a developer myself and imagine that this shouldn't be a very hard feature to add.

### Describe alternatives you've considered

Running a chatwoot instance for each outbox, but that would be very expensive and impractical since our agents would have to register and log in to many of them.

### Additional context

Thank you in advance!

**Comment by matlinski** [comment]
That is great, but where can I set outbox for each account? This is what my feature request is about.

**Comment by sojan-official** [comment]
@matlinski, are you primarily using live chat or email for customer communication?

If you’re using email, you can set up channels with SMTP and IMAP credentials. You can also restrict agent access to specific inboxes by adding them as collaborators to that inbox. This way, responses will use the specific SMTP credentials of the corresponding inbox.

For live chat inboxes, there’s a configuration option available for setting up a specific response email, although the documentation for this feature is a bit lacking.

**Comment by matlinski** [comment]
Found it in the end! Thank you all!
