### ISSUE TITLE
Can I Force Set This Design To Input?

### ISSUE THREAD

**Issue by studionexus-lk** [chatwoot/chatwoot#9968]
### Is your feature or enhancement related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/427f996a-9d0e-433c-803c-c64ddb8041aa)

### Describe the solution you'd like

an option to set solid , rectangle input boxes

**Comment by pranavrajs** [comment]
@studionexus-lk No, this is not supported. You'll need to fork and make it work. Closing this as we will not support this anytime soon.
