### ISSUE TITLE
Help with new integration channel

### ISSUE THREAD

**Issue by devsubngrill** [chatwoot/chatwoot#9984]
### Describe the bug

Hello Support 

I want to test the new captian integration in alpha I ready enable the integration in the super admin and flush all cookies and cache from the browser but if click on the captain tab show me the integration no enable how yo i solved this ? Attached screenshots here.

Please check below 👇🏼 thanks

![Screenshot_20240819_205633_Chrome Beta](https://github.com/user-attachments/assets/0ddbb522-29df-4a1d-a9d0-150235d5b9d2)
![Screenshot_20240819_205746_Chrome Beta](https://github.com/user-attachments/assets/ecab6adf-35bc-4cda-8a82-22b61f995a94)
![Screenshot_20240819_205641_Chrome Beta](https://github.com/user-attachments/assets/e56f7458-96b9-476f-a252-def45def50a9)

### To Reproduce

Describe above 

### Environment

Linux VM

### Cloud Provider

Other [please specify in the description]

### Platform

Browser

### Operating system

Ubuntu 24.04

### Browser and version

Chrome 126.0.6478.182

**Comment by pranavrajs** [comment]
@devsubngrill This is not ready for production yet. The option to enable it will be available once we make it available for beta testing.
